### ISSUE TITLE
Launch PO Sync and announce changes

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91708]
## User Story
_"As a (persona), I (want to), (so that)."_

Assignee:
Peer Reviewer:

## Description
We need to publish all changes to include the new PO Sync touchpoint in the Collaboration Cycle. The purpose of this ticket will be to publish all changes to Platform Website, publish all changes to the Collab Cycle Kickoff operational process, and announce all changes to VFS teams.

Expected launch date is September 13. If any issues come up that will prevent us from meeting that date, please inform @humancompanion-usds ASAP!

#### Platform Website
- [Change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history)
- [PO Sync touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/po-sync) 
- [Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/touchpoints)
- [Calendly link](https://calendly.com/collaboration-cycle/po-sync)

#### Governance Team documentation
- [Collaboration Cycle Kickoff - Admin Tasks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Admin+Tasks)
- [Swim lanes](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2710864175/Collaboration+Cycle+Swim+Lanes+Diagram)
- [Collaboration Cycle Kickoff - Code Blocks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3387457549/Collaboration+Cycle+Kickoff+-+Code+Blocks)

#### Governance Team documentation
- [Collaboration Cycle Kickoff - Admin Tasks](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3427074070/91704+Collaboration+Cycle+Kickoff+-+Admin+Tasks)
- [Collaboration Cycle Kickoff - Code Blocks](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3426844736/91704+Collaboration+Cycle+Kickoff+-+Code+Blocks)

## Tasks
- [x] Draft Change History post and Slack announcement post (follow [guidance](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2290352129))
- [x] Sync with Matt Dingee about announcing at Monday Design and Research meeting
- [x] Publish PO Sync touchpoint page **by 9/10 before PW updates** (we need this link for other pages)
- [x] Add PO Sync touchpoint page link to other pages
- [x] Publish Governance Team documentation
- [x] Update swim lanes
- [x] Publish Platform website documentation and confirm the date on the page is updated

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The PO Sync touhcpoint has been added to the Collaboration Cycle
- [x] VFS teams have been made aware of the new PO Sync touchpoint

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Added some tasks, it is important to note that the PO Sync touchpoint page must be published on PW before we can publish other docs, we need the link.

**Comment by KKitagawa-Bosch** [comment]
PO Sync page and updated touchpoints page are live on confluence @allison0034. Wanted to do this first thing this morning so there was one more chance for you to get eyes on it before the push to platform this afternoon! 

[PO Sync ](https://vfs.atlassian.net/wiki/spaces/CC/pages/3439788033/PO+Sync)
[Touchpoints](https://vfs.atlassian.net/wiki/spaces/CC/pages/1768423528/Touchpoints)

**Comment by KKitagawa-Bosch** [comment]
Confluence draft for Change History post and Slack Notification is published [here](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3440246788/91708+-+Change+History+Post+and+Slack+Notification)

**Comment by KKitagawa-Bosch** [comment]
@allison0034 drafts for change history and slack notification are written and ready for review!

**Comment by allison0034** [comment]
Thanks @KKitagawa-Bosch , I made a few comments.

**Comment by allison0034** [comment]
New PO Sync page link has been added to other pages.
