### ISSUE TITLE
Copy of Continue GA4 & BigQuery Audit

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#91702]
### Description
 This ticket is to account for the work that we are doing for our audit of our Google Analytics Properties and BigQuery.
 
_This was unplanned work for the sprint, but given we've been spending significant time on it, we are injecting it into our sprint. Details of the audit can be found in the postmortem in the sensitive repo_

---

### Tasks

- [x] Perform audit of Google Analytics 4 Property
- [x] Perform audit of Google BigQuery
- [x] If needed, perform audit of Domo.
- [x] Log findings in postmortem

### Acceptance Criteria

- [x] Findings from audit have been shared in private Slack message.
- [x] Findings and outcome have been logged in postmortem.

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt -- given the audit work will continue into next sprint, I created a separate ticket to track that work #92641.

Given we are slowly coming to a close on that, hoping that might be the lat one we have on this.

FYI @dorseypa1
