### ISSUE TITLE
Determine changes to Kickoff process

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91704]
## User Story
As a Governance team member, I want to incorporate the PO Sync touchpoint into the Collaboration Cycle Kickoff process so that all VFS team Product Owners are informed they they must complete this required touchpoint.

Assignee:
Peer Reviewer:

## Description
In order to roll out the PO Sync, we need to ensure that we're adding the new PO Sync touchpoint to the VFS teams CC-Request ticket. The purpose of this ticket will be to update the Collaboration Cycle Kickoff - Admin tasks so that the PO Sync is added for ALL VFS teams (regardless of what questions they answer at Kickoff). 

Please note that while the PO Sync will be added to all CC-Request tickets, it is really only required for VFS teams that are contracted under OCTO. We had planned to add a question to our kickoff to determine if a VFS team is OCTO or not, however due to the urgency of this initiative, we are no longer doing that. Instead we'll add the PO Sync to every CC-Request ticket, and just communicate within the code block that it's only required for teams contracted in OCTO.

The purpose of this ticket is also to update the Collaboration Cycle Kickoff - code blocks to create a new PO Sync code block with instructions for the VFS team PO. 

The code block should communicate:

1. That the PO Sync is REQUIRED for all VFS teams contracted under OCTO.
2. The PO Sync is for the OCTO Product Owner only and no contractors should be involved and/or invited
3. The PO Sync must be scheduled right away. While the VFS team is free to schedule their DI, MPR and/or SR without having completed the PO Sync, they will be blocked from the meeting taking place if the PO Sync has not yet been completed. In other words, the PO Sync must occur prior to any Design Intent, MPR or SR.
4. The code block should include the Calendly link for the PO Sync created via ticket #91705.
5. The code block should include a link to the PO Sync touchpoint page on Platform Website.
6. Any other critical and/or important information communicated in the [proposal](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3407773924/PO+sync+-+proposal).

### Live pages
- [Collaboration Cycle Kickoff - Admin Tasks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Admin+Tasks)
- [Collaboration Cycle Kickoff - Code Blocks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3387457549/Collaboration+Cycle+Kickoff+-+Code+Blocks)

### Drafted pages
- [Collaboration Cycle Kickoff - Admin Tasks](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3427074070/91704+Collaboration+Cycle+Kickoff+-+Admin+Tasks)
- [Collaboration Cycle Kickoff - Code Blocks](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3426844736/91704+Collaboration+Cycle+Kickoff+-+Code+Blocks)

## Tasks
- [x] Update the CC Kickoff admin tasks to include adding the PO Sync as a listed touchpoint for every CC-Request ticket.
- [x] Update the CC Kickoff code blocks to include the new PO Sync code block. The code block should appear 1st, before Design Intent.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have modified our kickoff process so that every VFS teams who submits a Collaboration Cycle kickoff is informed they must complete a PO Sync
- [x] The PO Sync code block contains information for the VFS PO including the Calendly sign up link.

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Created drafts and put them under the draft pages section in this ticket.

**Comment by allison0034** [comment]
2 drafts pages are ready for @KKitagawa-Bosch review!

**Comment by KKitagawa-Bosch** [comment]
Looks solid to me! @allison0034 I just left one comment!
