### ISSUE TITLE
Determine operational impact of PO Sync to other touchpoints

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91706]
## User Story
As a Governance team member responsible for scheduling DI, AI, MPR and SR, I want to check to make sure the PO Sync occurred so that I don't allow VFS teams to engage in Collab Cycle without syncing with OCTO-DE Design PA leads first.

Assignee:
Peer Reviewer:

## Description
We need to update our documentation to check that a PO Sync has occurred and been approved before an OCTO VFS team can attend Design Intent, Architecture Intent, Midpoint Review, and/or Staging Review. The PO Sync is not currently applicable to any non-OCTO teams.

This ticket will include adding checks to our scheduling docs for DI, AI, MPR and SR to ensure that the PO Sync occurred and was approved.

### How to check if a PO Sync occurred and received OCTO-DE Design PA leads approval
When a PO Sync occurs and receives OCTO-DE Design PA lead approval, the OCTO-DE rep will add the `PO-sync-approved` label to the Collaboration Cycle Request ticket. This will populate the "PO Sync" field of the Collaboration Cycle Reviews GH Projects board (easily seen in the [Active view](https://github.com/orgs/department-of-veterans-affairs/projects/998/views/15))to have the value "Approved". Alternatively, if viewing the individual Collab Cycle Request ticket, the Governance team member can view the PO Sync field in the right side panel of options. See example below:

![Image](https://github.com/user-attachments/assets/d5dd183d-17c0-44fd-858d-f86cbeef61e5)

### How to check if a team is OCTO or non-OCTO
Similar to the PO Sync field in the gh Projects board, there is also a fields for OCTO PO. If the VFS team is non-OCTO, the value of this field will be "non-OCTO". If the team is within OCTO, the field will include the name of the OCTO PO.

**Example of a non-OCTO team:**
![Image](https://github.com/user-attachments/assets/dfc18b54-dd35-4d00-8bdc-4046ea094110)
**Example of an OCTO team:**
![Image](https://github.com/user-attachments/assets/cf727cda-bc5f-4bbd-9f42-b4eb81f3bc6f)

### What to do for an OCTO team if the PO Sync was not approved or has not yet been scheduled

- If you're scheduling for an Architecture Intent or Design Intent, and the team has not had a PO Sync, or it has not been completed/approved, do not schedule the touchpoint. We need to add instructions to our process for the following:
   - Notify the individual who scheduled the touchpoint via their Slack channel that since they have not completed a PO Sync, we cannot schedule the touchpoint at this time.
   - Cancel the DI/AI on the Collaboration Cycle Calendar. Use the same messaging said in Slack in the cancellation message.
- If you're scheduling a Midpoint Review and the team has not had a PO Sync, please also check to see if a Design Intent or Architecture Intent has occurred. If the team hasn't had a PO Sync, but they have had an Arch Intent or Design Intent, then they are okay to proceed with Midpoint Review. If they haven't had a PO Sync, Arch Intent or Design Intent, then we should not schedule the MPR. We need to add instructions to our process for the following:
   - Notify the individual who scheduled the touchpoint via their Slack channel that since they have not completed a PO Sync*, we cannot schedule the touchpoint at this time.
   - Cancel the MPR on the Collaboration Cycle Calendar. Use the same messaging said in Slack in the cancellation message. 
 - If you're scheduling a Staging Review and the team has not had a PO Sync, please also check to see if a Design Intent, Architecture Intent or Midpoint Review has occurred. If the team hasn't had a PO Sync, but they have had an Arch Intent, Design Intent, or Midpoint Review, then they are okay to proceed with Staging Review. If they haven't had a PO Sync, Arch Intent, Design Intent, or Midpoint Review, then we should not schedule the SR. We need to add instructions to our process for the following:
   - Notify the individual who scheduled the touchpoint via their Slack channel that since they have not completed a PO Sync*, we cannot schedule the touchpoint at this time.
   - Cancel the SR on the Collaboration Cycle Calendar. Use the same messaging said in Slack in the cancellation message.

*Please note that we have grandfathered in some VFS teams if they had a lower touchpoint that is not the PO Sync. However, the messaging should remain consistent across all. 

## Impacted Artifacts

- [Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Scheduling)
- [Architecture Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3468263425/Architecture+Intent+-+Scheduling)
- [Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling)
- [Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)

### Live pages
- 

### Drafted pages
- 

## Tasks
- [ ] See specifications above.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have updated the DI Scheduling guidance to check that a PO Sync occurred before scheduling the DI. 
- [ ] We have updated the AI Scheduling guidance to check that a PO Sync occurred before scheduling the AI.
- [ ] We have updated the MPR Scheduling guidance to check that a PO Sync occurred before scheduling the MPR. 
- [ ] We have updated the SR Scheduling guidance to check that a PO Sync occurred before scheduling the SR.
- [ ] We have introduced guidance to block VFS teams from scheduling DI, AI, MPR, or SR if the PO Sync has not occurred (with the exception of teams that were grandfathered in prior to the creation of the PO Sync)

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
ticket has been moved out of PO Sync initiative and into tech debt

**Comment by shiragoodman** [comment]
Spoke to Platform leadership about this work as it's getting overly complicated. I will be going in a different direction, asking VFS folks to validate that they've had their PO Sync in the DI, MPR and SR scheduling section. Instead of holding Governance team accountable for checking if PO Sync occurred, VFS teams will be asked to do it themselves.

**Comment by shiragoodman** [comment]
Closing
