### ISSUE TITLE
Decrease the Sentry RDS Storage (Dupe 1 of 2)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91712]
This ticket is a duplicate of [79198](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79198), for Sprint 9, due to developer access issues to DataDog or Citrix.

## Issue Description
After the Sentry spike issue has been solved [with the Identity and Mobile teams?] the RDS storage can be decreased. This was increased due to the extreme storage required because of the issues (up to 6mm according to[ this Slack thread](https://adhoc.slack.com/archives/C045LCF8WU8/p1711134858385029)) that are taking up space. 

---
## Tasks
- [x] Investigate the Sentry Spike Issue by assessing the current storage in Sentry (see [this](https://vagov.ddog-gov.com/dashboard/w2n-vq9-v75/rds-sentry-freetotalused-storage-space?fromUser=false&fullscreen_end_ts=1723488297115&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=overview&fullscreen_start_ts=1722883497115&fullscreen_widget=793808805161500&refresh_mode=sliding&view=spans&from_ts=1722883487167&to_ts=1723488287167&live=true) dashboard)
- [x] Compare filtered to actual storage usage (volume)

## Acceptance Criteria
- [ ] Comparison of the past and current storage volumes to determine if the RDS needs to be decreased.

**Comment by Kshitiz-devops** [comment]
Before March 20 2024 the storage of rds database was 330 gb After the spike of march 20 the db size increased to more than 1 TB and the allocated storage is 2000 gb. Looking at the diagram Those spike data are still present in database due to which we are still occupying more than 900 gb in storage for rds. Looking at the stable diagram we can reduce the space to 1.5 tb but I think we should start with data cleanup from rds to better evaluate the required space for rds. With data clean up I think we can reduce the allocated space for rds to be 1tb. Current retention period is set to default to 90 days. In conclusion I think we can lower it to 1.5 tb then after cleanup we can go lower.

**Comment by Kshitiz-devops** [comment]
Chart we are using: https://github.com/sentry-kubernetes/charts

**Comment by Kshitiz-devops** [comment]
https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-rds-blue-green-deployments-storage-volume-shrink/
