### ISSUE TITLE
[Design] Badge Indicator: Prep for DSC and design intent

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#91729]
### Background 
Matt will be presenting the badge indicator as a proposed experimental design at the DSC meeting on Sept 5. He'll need to prep for that as well as the design intent meeting as part of collab cycle.

### Tasks
- [x] Review artifacts and prep for DSC 
- [x] Prep for design intent (prep user flow and figma files)
- [x] Present at DSC (9/5 at 11:05 am et)
- [x] Present at design intent (9/10 at 3:30 pm et)
- [x] Coordinate with PM or DM on any post DSC or design intent tasks/tickets as needed

### Acceptance Criteria
- [x] Prep for DSC and design intent complete
- [x] Presentation given to DSC and design intent

## Resources
- [Experimental Design ticket 3229](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3229)
- Collab cycle ticket: #91542
