### ISSUE TITLE
Remove "Welcome to new Pittsburgh site" modal

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9172]
## Problem Statement
Modal announcing new Pittsburgh VAMC site is no longer needed

## Goal
Modal announcing new Pittsburgh VAMC site is no longer visible

---
## Tasks
- [ ] Disable/Remove modal announcing new Pittsburgh VAMC site

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
The modal is no longer present
