### ISSUE TITLE
Perform Access Review for Sidekiq Admin

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#91738]
Platform Security has requested we review [everyone who has access to Vets API Production Sidekiq Admin](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3214114817/ACCESS+REVIEW+-+Sidekiq) and if they should still have it (e.g. are they still a DSVA member).

An [access request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+in%3Atitle+%22Sidekiq+Admin+UI+access%22+) needs to have been approved for any member in [va-gov-sidekiq-prod](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-prod). After 6 months, their access needs to be re-requested.

## Tasks
- [x] Review [list of sidekiq teams](https://github.com/orgs/department-of-veterans-affairs/teams?query=sidekiq) and ensure va-gov-sidekiq-prod is the canonical team
- [x] Review Access Requests issues in GitHub and determine who should have access
- [ ] ~Create tickets for removal of members who should no longer have access.~

## Acceptance Criteria
- [x] A report for members who have access to Vets API's Production Sidekiq Admin is made available to Platform Security Team.
