### ISSUE TITLE
Perform Access Review for Vets API Production Terminal

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#91736]
Platform Security has requested we [review everyone who has access to Vets API Production Terminal](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3408790044/ACCESS+REVIEW+-+VetsAPI+Argo) (via ArgoCD) and if they should still have it (e.g. are they still a DSVA member).

An [access request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+in%3Atitle+%22Vets-api+terminal+access%22) needs to have been approved for any member in [dsva-vagov-vets-api-prod-rw](https://github.com/orgs/department-of-veterans-affairs/teams/dsva-vagov-vets-api-prod-rw). After 6 months, their access needs to be re-requested.

## Tasks
- [x] Review Access Requests issues in GitHub and determine who should have access
- [ ] ~Create tickets for removal of members who should no longer have access.~

## Acceptance Criteria
- [x] A report for members who have access to Vets API's prod terminal is made available to Platform Security Team.

**Comment by ericboehs** [comment]
I messaged Ken from Security and let him know that I finished this Access Review. See [Confluence](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3408790044/ACCESS+REVIEW+-+VetsAPI+Argo).
