### ISSUE TITLE
[FE] - refactor pre-check-in complete session storage

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#91743]
## Description
right now pre-check-in complete is stored as an object in session like this { complete: bool }, we should flatten it out like day-of is so that it is simply a bool value. 

## Wireframes
- [Wireframes]() **_insert link to sketch file_**

## Tasks
- [ ] update session storage for pre-check-in complete
- [ ] update usage in app to match
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/91743?planning-poker) with Zenhub @wullaski
