### ISSUE TITLE
[FE] - investigate demographics flags session on reload

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#91745]
## Description
On reload of day-of complete page, we are seeing a weird session value being set `undefined.should.send.demographics.flags`. This ticket is to investigate why this is being called before the namespace for the key exists.

## Tasks
- [ ] [FE] debug issue with should.send.demographics.flags
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/91745?planning-poker) with Zenhub @wullaski
