### ISSUE TITLE
[Design] Team Figma best practices: create and document

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#91757]
## Background
The Authenticated Experience team has not previously formalized any best practices for our Figma design files with:

- File Names
- Page names
- Symbol naming
- Handling shared custom components that apply just to our files (ex. the Nametag)

@twoangstroms and @mattmarino-adhoc want to create some basic documentation on how Auth. Exp. Figma files are standardized, and use that as the basis to better organize our files and their contents (in a future ticket(s)).

---
## Tasks
- [x] Establish naming conventions
- [x] Establish practices with the Auth. Exp. Pattern Library for shared custom components
- [x] Document all proposals on github

## Acceptance Criteria
- [x] Documentation created in the identity-personalization folder in github

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ Looking at github documentation

## Resources
[Figma folder](https://www.figma.com/files/team/1278375444205744118/project/176473451/Account-Experience?fuid=1316126118700040443)

[Github document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/design/(WIP)%20Auth.%20Exp.%20Figma%20best%20practices.md)

**Comment by mattmarino-adhoc** [comment]
[Proposal Google doc - WIP before putting it on github](https://docs.google.com/document/d/1YJuiKBrXxIbIEGDyTRmZoOlFzhzje6EDqt8FZzE42Ik/edit?usp=sharing)

**Comment by mattmarino-adhoc** [comment]
I will close this ticket out today since my recommendations will be complete, but at this point we should still consider this to be a draft - Dan and I will need to discuss this further next sprint.

**Comment by mattmarino-adhoc** [comment]
@twoangstroms
