### ISSUE TITLE
Identify Link Emojis: Partner Services (Upstream Services)  

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#91763]
## Pain Point:
The document, [Partner Services (Upstream Services)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885601877/Partner+Services+Upstream+Services), contains many link emojis (🔗) instead of proper link formatting. 
The page is presently of limited use to VFS Teams. 

## Description:
Separate tickets in this Epic will track the work of fixing broken links. 
Once the links are pointing to the correct pages and those emojis are replaced with page titles, this next step will be performed.
- This ticket is for the work of replacing the **remaining** link emojis with page titles.

### Screen shot:
> ![image](https://github.com/user-attachments/assets/ad69d4fd-e581-4e1e-a6b1-2c8f37f4a529)

---
## Tasks
- [x] Locate all remaining link emojis 🔗  
- [x] Replace all emojis with the current link in the form of the page title
- [x] check page for launch blockers
- [x] deploy page

## Acceptance Criteria
- [x] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/91763?planning-poker) with Zenhub @BSmolensky @cmarion93 @taylojill

**Comment by BSmolensky** [comment]
I know we are working on this page piece by piece. But I did want to note that your style guide does not endorse the use of URLs as hyperlinks. [Our style guide advises](https://vfs.atlassian.net/wiki/spaces/AP/pages/621609007/Grammar+and+punctuation#Links) the use of hyperlink text that describes where the user will go and what they will find when they select the hyperlink text. At the very least, it advises that we use the title of the linked doc or page: 

> Don't use a URL as link text. Instead, use the page title or a description of the page.

**Comment by jknipes** [comment]
@BSmolensky thank you for the heads up, task has been changed to require **page title** be used for the Display Text

**Comment by jknipes** [comment]
Moved into Current Sprint due to available capacity and to complete work on this page

**Comment by jknipes** [comment]
Work is completed, closing as _done_

**Comment by taylojill** [comment]
All emoji links removed and updated. Checked for blockers, date stamped, ready to publish.

**Comment by jknipes** [comment]
Work is complete, closing as _done_
