### ISSUE TITLE
Epic: Edit: Partner Services (Upstream Services)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#91769]
## Status
_Update each sprint until completed_
| Date | Status | Launch Date (see above) | Notes |
| ----- | ------ | ------------------------- | ------ |
| 10/17/24 | done | on-track | NA |

## Issue Description
The document, [Partner Services (Upstream Services)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885601877/Partner+Services+Upstream+Services), contains many broken links. 
The page is presently of limited use to VFS Teams.
We need to work with the Platform Product team to make sure all broken links are replaced with links to live pages.

14 of the links are broken or problematic as of August 28 2024. 
Here are the broken or bad links as of Aug 28. The list shows where in the grid each link is :

- [x] 1. MPI- outage- This link leads to a GitHub page that says “File not Found”
- [x] 2. MPI-Contacts - This link leads to a GitHub page that says “File not Found”
- [x] 3. MPI - monitoring- This link leads to a page that says "server not found".
- [x] 4. Appeals-outage- This link leads to a page that says "server not found".
- [x] 5. Appeals-Monitoring - This link leads to a page that "says server not found". 
- [x] 6. VA profile - contacts - This link leads to a confluence document in drafts, which VFS team members can’t access.
- [x] 7. EVSS- monitoring- Server not found
- [x] 8. EWIS - monitoring- Server not found
- [x] 9. Central mail - monitoring- server not found
- [x] 10. Central Mail - VFT docs- This leads to a Platform document that technically exists but says at the top “This API has been deprecated. Please use the Benefits Intake API.”
- [x] 11. MHV - monitoring- server not found
- [x] 12. Search.gov- monitoring- server not found
- [x] 13. eMIS - VFT docs- This leads to a Platform document that technically exists but says at the top “THIS PAGE WAS ARCHIVED ON 2/15/24 - Loki, Grafana, and Prometheus have been sunsetted and replaced by Datadog. This page contains only information about affected programs and DOES NOT contain any additional information that people need. As a result, this page was not edited and kept on the Platform Website. Instead, it was archived. For more information about Datadog, contact #dots-dsva.”
- [x] 14. eMIS - devops docs- This also leads to that Platform document page that technically exists but that says at the top, “THIS PAGE WAS ARCHIVED ON 2/15/24 - Loki, Grafana, and Prometheus have been sunsetted and replaced by Datadog. This page contains only information about affected programs and DOES NOT contain any additional information that people need. As a result, this page was not edited and kept on the Platform Website. Instead, it was archived. For more information about Datadog, contact #dots-dsva.”

---
## Tasks

- [x] Fix the broken links
- [x] Check off each of the 14 issues above as they are fixed
- [x] Review the page for any new problems
- [x] Decide whether to create further edit tickets for new work or publish the page
- [x] Check for launch blockers

## People/SMEs

- Jennifer Brown and Platform Product team

## Slack thread
See [this slack thread](https://dsva.slack.com/archives/CL181NRJQ/p1724865276408069).

## Acceptance Criteria
- [x] Links are fixed
- [x] Page is ready for deployment

### Screen shot:
> ![image](https://github.com/user-attachments/assets/ad69d4fd-e581-4e1e-a6b1-2c8f37f4a529)

**Comment by jknipes** [comment]
Work is complete, closing as _Done_
