### ISSUE TITLE
Investigate cause of lower than expected ITF creation rate

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#91764]
## Issue Description
The purpose of this ticket is to investigate and document the cause of the lower than expected ITF creation rate for pension applications.
Context: since the launch of ITF V0 we would generally expect ITFs to be created upon form launch for pension applicants, with the exception of certain known cases like unauthenticated applicants, applicants without the required LOA level or ITF API failures.  Stats recently pulled by Dan L indicated an 18% ITF creation rate, which is lower than expected

---
## Tasks
- [ ] _Compile statistics on ITF creation since launch
- [ ] Identify if possible the disposition of all ITF creation attempts and reason for failures
- [ ] Identify root cause of failures
- [ ] Create tickets to address failure points

**Comment by danlim715** [comment]
The reason for the large discrepancy between new InProgressForms created vs ITFs created was due to the fact that the ITF chart on the dashboard was displaying `avg_by` aggregate data as opposed to `sum_by`. The ITF data chart on the dashboard has been updated accordingly. I've also added a query for tracking missing participant IDs and will add queries for other failure states as they are incremented in datadog.
