### ISSUE TITLE
Refine the Customer Insights Database

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#91767]
## Purpose
We need a page for folks to be directed to that explains the Customer Insights Database, leads them to it, and also may link to explanatory documentation.

Note:  FDG landing may provide a good example of how to approach this.

## Tasks
- [x] [brainstorm](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3417768131/Create+Landing+page+for+Insights+Repo) needed features of landing (summary, link to Feedback Repo, how-to-use documentation)
- [x] include findings and recommendations from prior tickets [1](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3218112513/Feedback+Review+OCTO+PO+role+type+view+w+suitable+SMEs), [2](https://vfs.atlassian.net/wiki/spaces/~622b5b63932f0f00716bdfd6/whiteboard/3233611783)
- [x] create [user flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1725385309818/01ee46df6083258c768f0259cfaf065050c73662?sender=ud738fc7d7aafcb86aac51967) for the different personas

## Acceptance Criteria
- [x] Landing page is ready for next level refinements
