### ISSUE TITLE
Restore community care pharmacy searches

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9177]
## User Story or Problem Statement
As a Veteran, I need to be able to search for **Urgent care pharmacies (in VA's network)** so I know where I may fill prescriptions outside of the VA.

## Goal
Be able to restore search functionality for **Urgent care pharmacies (in VA's network)** on/around June 30. 

---
## Tasks
- [ ] Add flipper to **Urgent care pharmacies (in VA's network)** as facility type (was hidden in [#6809]. **(DO NOT TURN ON YET)**

## Acceptance Criteria
- [ ] Facilities team will be able to use flipper to restore **Urgent care pharmacies (in VA's network)** as a facility type in Facility Locator searches when notified. 
- [ ] **Urgent care pharmacies (in VA's network)** as a facility type in Facility Locator searches is turned off by default in Production. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Per OCC, we expect to return this to functionality near the end of June

**Comment by brangi** [comment]
merged
