### ISSUE TITLE
Toxic Exposure: Exposure locations not populating in overflow page if the user doesn't select any dates for those locations

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#91770]
## Issue Description
If you select any locations within a particular group (i.e. Gulf war 1990, Gulf war 2001, etc) and you DON'T specify any dates for these locations, then the locations do NOT get populated into multipleExposures array at all. The result here is that the locations they selected are not populated in the overflow, and are effectively lost.

The problem seems to stem from the fact that we are [only adding to the multiple exposures array](https://github.com/department-of-veterans-affairs/vets-api/blob/56b413d4a9e582e4d11b8783ee6d96f4d0450bcf/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb#L269) if the `xxxxDetails` node exists, and if no dates are entered within a group, the node is NOT present. The fix should probably be to expand the if statements to say 

`   if toxic_exposure_source['gulfWar1990Details'].present? _|| toxic_exposure_source['gulfWar1990'].present?_`
`   if toxic_exposure_source['gulfWar2001Details'].present? _|| toxic_exposure_source['gulfWar1990'].present?_`
or even simply...
`   if toxic_exposure_source['gulfWar1990'].present?`
`   if toxic_exposure_source['gulfWar2001'].present?`
etc.

---
## Tasks
- [ ] Fix the code referenced above to allow the multipleExposure array to populate even when no dates are entered 
- [ ] Add and/or modify unit tests to test for the scenario

## Acceptance Criteria
- [ ] Exposure locations appear on the overflow of the 526ez even when no dates are selected
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
