### ISSUE TITLE
2024 Q3 Platform Product: AWS RDS Free Storage space

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91785]
## User Story
As the Managers and Developers of the VA Platform, 
We need to mitigate the issue that was discovered on 8/28/24 regarding available space on AWS RDS,
So that spikes in the I/O are avoided and available space does not vary so wildly. 

## Issue Description
Review the Slack conversation [here](https://dsva.slack.com/archives/C30LCU8S3/p1724876030578449) that was noticed at 4:14pm et on 8/28/2024 by the Support Team. It was noted that over the last 2 days that there had been a significant decline in available space, and that there was a spike in query duration during the CPU update. This caused a backup in the queuing/ I/O /backup. 

## Tasks
- [x] Review as many snapshots as available to see what is available for past usage data, including RDS snapshots, preferably tables prior to 8/28/2024
- [x] Implement temporary fix, such as increasing the space, to account for any delays. 
- [x] Load the snapshot into a test instance and review for table sizes
- [x] Determine root cause of what is taking up space at such odd intervals
- [x] Create strategy for future work, if needed
- [x] Document discovery outcomes and indicate in comments where documentation is stored

## Success Metrics
The Platform Product team implements a quick fix to avoid delays, then creates strategy and work tickets to mitigate the available space issue. 

## Acceptance Criteria
- [ ] MVP to fix the space issue is complete and there are fewer significant spikes
- [ ] Strategy to mitigate this as a larger issue
- [ ] Future work outlined in discovery/design doc
- [ ] Testing completed with no new errors
- [ ] Documentation complete and stored
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by LindseySaari** [comment]
We are investigating potential causes for this

Sometimes during transactions, temporary files are created, so we are looking [into a job](https://github.com/department-of-veterans-affairs/vets-api/commit/27f2ec3dbb6d03720962d9787dd7ada91d5a2e41) that was introduced on Monday/potentially deployed on Tuesday. One possible factor could be time-consuming operations that generate large temporary files. Notably, this job processes and updates all rows in the CSV file within a single database transaction. If the CSV file is large, this could lead to long-running transactions, which may be contributing to the storage growth. We increased the space to 1TB to give us time to consult with the VFS teams, but the usage is still growing at a rate of 1-2GB per hour or more

It might simply be a natural need for increased storage. However, I'm leaning towards the possibility that it's due to a recent change in the codebase or an increase in form submissions or other data being saved to the database.

**Comment by LindseySaari** [comment]
We are going to continue to monitor the free space downward trend. It does tend to fluctuate quite a bit looking at the [60 day window.](https://vagov.ddog-gov.com/metric/explorer?fromUser=true&start=1719706107934&end=1724954284000&paused=true#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGABuMMgYYBoAdNpQDYJGcGkIbhjwafIY2cCR6sjNFRgAtBWIGuMY8hDj8to4UOMATDwgPAC6VK7ueJih4fuqhxgxpfFbuyAacmg5oH2PCAg5STgwTplHGhCZRJoUTtOSKZTpYFQIEgpz0JjKERuDxoLb8CD2TBYJxgj7AkRKHY8Ph3eTAhAAYSkwhgKBEhzQPCAA)



![Image](https://github.com/user-attachments/assets/4be61f85-824d-462f-b4ef-917fe05fa43c)

**Comment by jennb33** [comment]
9/4/2024 update: no surprises currently, we will continue to monitor.

**Comment by jennb33** [comment]
9/5/2024 update: no surprises currently, we will continue to monitor.

**Comment by jennb33** [comment]
9/9/2024 update: @flooose said this looks like it's getting back to its normal rates

**Comment by jennb33** [comment]
@flooose will keep an eye on the monitors the week of 9/16, closed this ticket
