### ISSUE TITLE
Clean-Up Datasets and QC Dashboards in Domo from GA4 Migration

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#91783]
### Description
We created a lot of datasets and QC dashboards in Domo as part of the GA4 Migration. This task is to review, and remove everything that was created for test purposes, so we can maintain an orderly Domo environment, and don't have unused artifacts crowding our instance.

### Artifact
- [GA4 Migration Dataset/Dashboard Deletion](https://docs.google.com/spreadsheets/d/1FfZwQjZpVHY5idLDcxqN7vMUC9_cgqslZPTKA5si8FM/edit?gid=0#gid=0)
---
### Tasks

- [x] Identify all of the test GA4 datasets that were created as part of the GA4 Migration.
- [x] Confirm they aren't still being utilized
- [x] Remove the datasets
- [x] Identify GA4 Test QC Dashboards
- [x] Confirm they aren't still being utilized
- [x] Remove the QC dashboards

### Acceptance Criteria
- [x] Old GA4 test datasets have been removed
- [x] Old GA4 QC test dashboards have been removed

**Comment by johnny-jesensky-adhoc** [comment]
We ended up pulling this into the current sprint from some extra bandwidth from our two analysts -- Christine and Basil.

We ended up wrapping this up, so marking as _Done_.

FYI @Blivaditis, @ChristineYoungZA
