### ISSUE TITLE
Implement Pre-Fill on Frontend for 686

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9178]
## User Story
As a Veteran, I want to have as much info filled in for me as possible so that I can get through these transactional forms as quickly and easily as I can.

## Considerations
- Pre-Fill has been setup [from the backend (#7883)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7883#issuecomment-624241167) but it needs to be integrated into the frontend.
- Here is his PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4188
- To implement, fields need to be mapped and most are automatic but there are 10 that need to be manually adjusted.

## Tasks
- [ ] Using a `preFillTransformer` to pass the correct data automatically
- [ ] Manually, there are 10 fields that need to be adjusted:
  - veteran address 
    - lives on mil base, 
    - base info, 
    - country name, 
    - address line 1 
    - and 2, 
    - city and 
    - zip code,
  - email address and 
  - phone number  

## Acceptance Criteria
- [ ] Implement these tasks and request a PR for merge
- [ ] Test pre-fill in staging
