### ISSUE TITLE
Update and execute script for updating required artifact changes at DI and MPR

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91807]
## User Story
As a Governance team member, I want to ensure that all VFS teams who have not yet scheduled a DI or MPR have up to date guidance and instructions in their Collaboration Cycle request ticket so they can rely on the ticket as a source of truth.

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
In ticket #89243, we are changing the required artifacts at Design Intent to include mobile web designs, and we are changing the required artifacts at Midpoint Review to include mobile web designs AND an up-to-date user flow.

The purpose of this ticket is to modify the script to update open Collab Cycle Request tickets with the new required artifacts at DI and MPR.

### Live pages
- 

### Drafted pages
- 

## Tasks
- [x] Write a script to update the open Collab Cycle Request tickets to reflect the artifact changes for DI and MPR
- [x] Coordinate with @erinrwhite and @briandeconinck via ticket #89243 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x]  All open Collaboration Cycle Request tickets include up to date guidance on artifacts at the Design Intent and Midpoint Review
- [x]  Governance team has been notified of the updates to the CC Request tickets via the #platform-governance-team channel

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
This ticket will be moved into the next sprint. The work is dependent on #89243 which is still incomplete.

**Comment by briandeconinck** [comment]
@it-harrison [Code blocks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3387457549/Collaboration+Cycle+Kickoff+-+Code+Blocks) are updated and ready for you to work your magic on the open tickets!

**Comment by it-harrison** [comment]
@briandeconinck I have updated all the tickets (all tickets without the `design-intent` label updated with new di code block and all tickets without the `midpoint-review` label updated with new mpr code block).  Here is a link to the relevant commit: https://github.com/it-harrison/ticket-body-update/commit/c4129389747d4c03fcfc833540e5ea17cd4b82ed

**Comment by briandeconinck** [comment]
I have checked a sample of impacted tickets and they all look good to me! I think you're good to notify in Slack per the ticket instructions, and I'll go post the change announcement in #89243.

**Comment by briandeconinck** [comment]
Changes announced in #vfs-change-announcements for #89243, so I think this is ready to wrap up @it-harrison!
