### ISSUE TITLE
[PM] Logged-in homepage: Set OKRs and KPIs 

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#9181]
## Background

We need to further define the OKRs and KPIs for the logged-in homepage redesign in order to get our baseline analytics set and ready to measure success for this project.

[Logged-in homepage product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/README.md)
[Preliminary OKR/KPI discussion in 7772](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7772)

## Tasks

- [x] Create preliminary objectives, key results, bets, and KPIs.
- [x] Review with team.
- [ ] Adjust and refine as necessary.

## Acceptance criteria

- [ ] Samara, Matt Shea, and Mickin agree on OKRs and KPIs for this project.

**Comment by Samara-Strauss** [comment]
Hi @mshea0606 and @MickinSahni — Attached are a first pass on some thoughts around OKRs and KPIs. I'd love to meet some time next week to discuss them, but if you have time in the meantime, feel free to leave comments right in the Word doc and send it back over the fence.

Also, sorry for the annoyance of having to do this in a Word doc, but that felt a little easier than trying to collaborate in Github for the time being. Once these are in a more finalized place, I will absolutely add this content to our product outline in Github.

Finally, you'll notice that I mostly have not specified baseline metrics for KPIs and have left an "X" in place of concrete numbers. That's because I don't have those baseline metrics yet so I can't gauge what a proper level of improvement would be. If we agree that whatever KPI I outlined is a good measurement of the OKR it's associated with, I will get the analytics team to pull the data we need in order to set those concrete numbers.

[https://app.zenhub.com/files/133843125/792d6b74-d395-44b8-b344-75d514e636c0/download](https://app.zenhub.com/files/133843125/792d6b74-d395-44b8-b344-75d514e636c0/download)

**Comment by mshea0606** [comment]
@Samara-Strauss Sounds good. I'm taking a look now.

**Comment by mshea0606** [comment]
[LIH OKR-KPIs (Matt's edits).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4702375/LIH.OKR-KPIs.Matt.s.edits.docx)

**Comment by mshea0606** [comment]
[LIH OKR-KPIs (Matt's edits)5-29-20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4702377/LIH.OKR-KPIs.Matt.s.edits.5-29-20.docx)

**Comment by MickinSahni** [comment]
My notes. Really wish we had a collaborative doc 🤷 

[LIH.OKRs-KPIs.MickinEdits.20200529.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4702535/LIH.OKRs-KPIs.MickinEdits.20200529.docx)

**Comment by MickinSahni** [comment]
Couple takeaways from the convo:

* Categorize Objectives - org vs. veteran (e.g. design system vs. tool/benefit interaction)
* Hierarchy of value - KPIs > Objectives > KRs > Bets
* Hierarchy/Timeline of Objectives - Org Objectives vs intermediate-term LIH Objectives vs now-term LIH Objectives


* Let's cap ourselves to 3 objectives like:
  * 1 - business objective
  * 1 - generic user objective
  * 1 - specific to the new Veteran objective

**Comment by Samara-Strauss** [comment]
@MickinSahni @mshea0606 [I updated the spreadsheet](https://docs.google.com/spreadsheets/d/1B6c1rY-1l64cWhHO7D8WjA328zwfdAhSgKkPatIKmts/edit#gid=0) and what I have so far is ready for feedback. I have three user-related objectives at this point and I'm trying to figure out whether there really are separate business objectives or not. After further thinking, I see creating authenticated tools patterns as more of a bet than an objective. The one thing I'm hung up on is log-ins and lo-in behavior. I haven't decided whether there can meaningfully be an objective around this because we're not doing anything that directly affects log-in at this point. However, I do think that if the logged-in experience is better and more usable, people may log in more or may spend less time in a logged-out state before logging in. So I'm not sure what to do here.

Let me know what feedback you have! Happy to hop on a call and discuss IRL, too.

**Comment by MickinSahni** [comment]
Hey Samara, taking a look and thinking thru feedback on the spreadsheet. Wanted to provide some immediate thoughts on ☝️ meanwhile:
> trying to figure out whether there really are separate business objectives or not. After further thinking, I see creating authenticated tools patterns as more of a bet than an objective.

Yep, makes sense to me. Perhaps it's a bet. I did like your reasoning that as a robust design practice, we have an extensive library of components. That includes the authenticated experience. 

It could be an OKR the Platform team responsible for maintaining the design system adopts as a parallel objective to our work here. (See [Shared OKRs](https://felipecastro.com/en/blog/tips-ex-googler-shared-okrs/)) As I mentioned, we should do our best to control our own scope/sphere of influence.

> I haven't decided whether there can meaningfully be an objective around this because we're not doing anything that directly affects log-in at this point.

> However, I do think that if the logged-in experience is better and more usable, people may log in more or may spend less time in a logged-out state before logging in.

My original stance was that it seemed out-of-scope for this iteration. In general, we *do* want to incentivize folks creating accounts to manage their VA benefits. I agree that it's probably an OKR to prioritize for our future selves. 

Does the [Analytics review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/analytics/analytics-summary.md#logged-in-homepage-discovery-analytics-review) call-out **logged-in** behavior separate from logged-in? I think I'm completely missing it. 🕵️ 

I will say that when it comes to log-in behavior, we can separate retention of our existing users from adoption of new users. I think adoption is what we're thinking about when we talk about log-in bets (please correct me though).

But, retention prob is in our direct/near-term control since there *are* people navigating to the logged-in homepage now. [This data](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/analytics/analytics-summary.md#from-the-homepage-people-primarily-navigate-into-the-tools-displayed-in-the-top-20-tasks) looks like it relates to the logged-out homepage. But, it's a good proxy as we know considering how similar logged-out is to logged-in. That seems like the best driver of any log-in bets we might make.

We can probably talk through this some more. I think I could talk this this last point better. 😬 😄 

@Samara-Strauss @mshea0606

**Comment by Samara-Strauss** [comment]
> Does the Analytics review call-out logged-in behavior separate from logged-in? I think I'm completely missing it.

I had a [very short section on it here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/analytics/analytics-summary.md#logged-in-vs-logged-out-why-do-people-come-to-the-site-what-do-they-do-here). I looked at top 20 pages for logged-in vs logged-out users. I didn't, however, look at how homepage interactions change for logged-in vs. logged-out. And, of course, you can only see My VA when logged-in.

> I will say that when it comes to log-in behavior, we can separate retention of our existing users from adoption of new users. I think adoption is what we're thinking about when we talk about log-in bets (please correct me though).

Yeah, I think this comes down to three things we potentially could look at:

- New people logging in for the first time.
- People spending less time in a logged-out state before logging in.
- People logging in more frequently.

I'm not sure if we should focus on some, all, or none of these.

> But, retention prob is in our direct/near-term control since there are people navigating to the logged-in homepage now. This data looks like it relates to the logged-out homepage. But, it's a good proxy as we know considering how similar logged-out is to logged-in. That seems like the best driver of any log-in bets we might make.

For retention, are you talking about the same or more people using the logged-in homepage? If so, I already have some notes in the spreadsheet about looking at % of users who use the homepage. In theory, we should see most of the My VA users move over to the logged-in homepage once My VA is retired, so we would estimate that we'd see the % of users using the homepage increase by about 5 – 8% ([% of people who use My VA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/analytics/analytics-summary.md#about-half-of-vagov-users-go-to-the-homepage-only-about-8-of-users-go-to-my-va)).

----

I am happy to regroup any time! Let's definitely talk this through more once you've had a chance to look at the spreadsheet. Thanks for all your help with this!

**Comment by MickinSahni** [comment]
> For retention, are you talking about the same or more people using the logged-in homepage?

Yep. I think a better framing would be adoption as it sounds like we're trying to pull folks over to the LIH from My VA. And that would be separate from acquisition of new users entirely, which is out of scope. Updated the spreadsheet accordingly.

**Comment by Samara-Strauss** [comment]
> Alrighty, took a look at the spreadsheet. Major change was to organize/group by categories of KPIs. Assuming those categories make sense, we can begin populating each category with specific tasks/actions we want to enable.

Yep, overall organization looks good!

> And that would be separate from acquisition of new accounts entirely, which is out of scope. Updated the spreadsheet accordingly.

> I think "new" carries a lot of weight here that we should explore. As it reads, it gets back to whether we're actually developing bets to take folks over to the LIH from other parts of the logged-in VA.gov or from the logged-out state itself.

Noted, and makes total sense. We won't include new users as a KPI.

> ^ These two seem to distill down to retention, which i've added to the spreadsheet.

Sounds good.

Looking forward to our chat tomorrow. Thanks for all your help, @MickinSahni!

**Comment by mshea0606** [comment]
@Samara-Strauss @MickinSahni  I've made some edits/additions to the [LIH value framework spreadsheet](https://docs.google.com/spreadsheets/d/1B6c1rY-1l64cWhHO7D8WjA328zwfdAhSgKkPatIKmts/edit#gid=0). I added a few KPI's and included the question they would help answer. I also added in an additional KR. I look forward to our discussion tomorrow!

**Comment by Samara-Strauss** [comment]
KR section of the spreadsheet is ready for review. I divided KRs into:

- Acquisition and retention
- Benefit engagement
  - By clicks on the homepage
  - By conversion metrics

Feel free to drop some comments in the doc, or let me know if you have questions!

**Comment by MickinSahni** [comment]
> [KR section of the spreadsheet is ready for review](https://docs.google.com/spreadsheets/d/1B6c1rY-1l64cWhHO7D8WjA328zwfdAhSgKkPatIKmts/edit#gid=0). I divided KRs into:
> 
>     * Acquisition and retention
> 
>     * Benefit engagement
>       
>       * By clicks on the homepage
>       * By conversion metrics
> 
> 
> Feel free to drop some comments in the doc, or let me know if you have questions!

@Samara-Strauss These look great! A few notes:

* Let's make sure we're focused on the most important outcomes and not overextended. We should cap our Objectives to 2-3 and and most 3 Key Results per Objective.
* In general, we should try for ratios (%'s) rather than numbers for our KPIs. It provides a grounding effect so we don't have to wonder whether 1,000 or 1,000,000 is a lot or a little. (Not always possible but something to strive for). 
* I [added a draft visual](https://docs.google.com/spreadsheets/d/1B6c1rY-1l64cWhHO7D8WjA328zwfdAhSgKkPatIKmts/edit#gid=516726482) here to organize our work done. Feel free to modify, it's incomplete. 

Next steps are to use baseline data to determine what targets should be set for each Key Result. The Adoption/Retention KRs look good. But the engagement ones need attention. Again, let's limit the number of things (i.e. KRs) we have to focus on. 

cc @mshea0606

**Comment by Samara-Strauss** [comment]
Thanks for the review @MickinSahni! I'm going to go through the spreadsheet and clean things up. Since I was only thinking about KRs last time, I'll take a pass at refining objectives and picking final KRs next. Should be able to get to that tomorrow.

**Comment by Samara-Strauss** [comment]
[I've created a new tab in the spreadsheet](https://docs.google.com/spreadsheets/d/1B6c1rY-1l64cWhHO7D8WjA328zwfdAhSgKkPatIKmts/edit#gid=1242119200) — "OKRs and KPIs revised" — where I've refined everything we've been talking about. I need to confirm whether we can actually calculate some of the proposed key results, but otherwise, this is ready for review.

If this looks good, I'll move forward and put in a request with the analytics team to get baseline metrics.

**Comment by Samara-Strauss** [comment]
@MickinSahni @mshea0606 checking back in again. Some thoughts:

- Pending your feedback on the current proposal for OKRs and KPIs, I think we can probably close this ticket and create further to-dos for future work (eg. working with teams to establish exact baseline metrics). At this point, I need to know whether you think the general direction of the objectives and the key results is way off (eg. do objectives seem relevant to what we want to accomplish? are KRs the best ways of measuring success?). If they look good, I think I can handle the rest of the refinement on my own or with less frequent check ins.
- As for the actual KRs themselves, I need to work with the teams who own the products I'm talking about to figure out what the most important conversion metrics are for them and what's possible to track through GA. So far:
  - If we don't already track applications submitted, I know we can by tracking clicks of the "Submit" buttons in each application. Of course, that means there is no metric for increasing submissions of all applications, and we might want to think of these individually (eg. the health care application, various disability applications, various edu benefits).
  - The VAOS team *is* tracking how many appointments are scheduled, so I'll confirm with them that this is their most important conversion metric and figure out what the right baseline metric should be.
  - The claim status team may not have OKRs and KPIs of their own for that tool (since I don't think it's been worked on in years, and everyone from the team who had worked on it is no longer here), so figuring out success metrics for this might be harder. I'll keep working with them until we get that figured out.

Let me know if you have any thoughts. I'd like to get this ticket closed out before the end of this sprint (end of day Tuesday) so please let me know if you have any feedback that might change the overall direction of where things are going now. If things look good, I'll create additional tickets for the rest of the work that needs to happen.

**Comment by Samara-Strauss** [comment]
One final thing — I renamed the file "Authenticated Experience Value Framework" because I wanted to use this same template to refine the OKRs and KPIs for the profile (as a product) and our profile 2.0 redesign (as a project). You'll see those two tabs in the spreadsheet now, but they have nothing to do with this specific to-do.

**Comment by MickinSahni** [comment]
> the general direction of the objectives and the key results is way off (eg. do objectives seem relevant to what we want to accomplish? are KRs the best ways of measuring success?). If they look good, I think I can handle the rest of the refinement on my own or with less frequent check ins.

These look pretty good, Samara. I especially like this "I removed the prescription and secure messages metrics from here since those tools don't live on VA.gov right now...". It shows how we might iterate on these KRs. 

> If we don't already track applications submitted, I know we can by tracking clicks of the "Submit" buttons in each application. Of course, that means there is no metric for increasing submissions of all applications, and we might want to think of these individually (eg. the health care application, various disability applications, various edu benefits).

Yes, I think we do want to track these individually and by the respective category they represent so we understand how/when we iterate the LiH. I.e. are we ignoring a particular benefit funnel while overextending on another? 

I would be surprised if we don't have number of submissions 😬 . But that sounds like an ok proxy. 

> The VAOS team is tracking how many appointments are scheduled, so I'll confirm with them that this is their most important conversion metric and figure out what the right baseline metric should be.

Perfect. Yeah I think Lenae has been keen on this sort of framing for the health products world. It's the exact sort of interactions i'd expect; work with the benefit line owners to figure out how we help via LiH. 

> The claim status team may not have OKRs and KPIs of their own for that tool (since I don't think it's been worked on in years, and everyone from the team who had worked on it is no longer here), so figuring out success metrics for this might be harder. I'll keep working with them until we get that figured out.

Fair enough. 

> If things look good, I'll create additional tickets for the rest of the work that needs to happen.

Sounds perfect. Things look good and is a great foundation for us to build/iterate on.

> I renamed the file "Authenticated Experience Value Framework" because I wanted to use this same template to refine the OKRs and KPIs for the profile.

YES. 🚀

**Comment by MickinSahni** [comment]
Also, I'd like to depict the finalized KPIs visually e.g. via that drawing I included. 

Feel free to update that or I can do it once we have the finalized OKRs w/ baselines.

**Comment by mshea0606** [comment]
@Samara-Strauss @MickinSahni This sounds good to me.

**Comment by Samara-Strauss** [comment]
> Also, I'd like to depict the finalized KPIs visually e.g. via that drawing I included.

Sounds good! I'll update it after we have the KRs finalized.

Thanks for both of your help in getting these to where they needed to be! I have learned SO much about OKRs and KPIs in this process. Really excited about that. :D

Closing and will open smaller tickets as needed.
