### ISSUE TITLE
[Design] My VA Forms Status: error handling if PDF cannot be generated

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#91825]
## Background
In the event that the user clicks the download link to download their form but the PDF cannot be generated we need to show them an error has occurred. 

## Tasks
- [x] Determine if there are existing models/designs for this scenario
- [x] Create designs for our specific scenario/use case
- [x] Review with team
- [x] Add to error scenarios in FE documention

## Acceptance Criteria
- [x] We have error state designs for when the PDF errors

**Comment by ajakabcin** [comment]
@mattmarino-adhoc are we still going to make our own version of this as it will appear on My VA? I'll need that for linking purposes and screenshots for the product guide : )

**Comment by mattmarino-adhoc** [comment]
Yep, we will need to have our own

**Comment by mattmarino-adhoc** [comment]
The existing models appear to not be feasible for MVP. More details to follow.

**Comment by mattmarino-adhoc** [comment]
[Figma mockups](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=2076-28877&t=KMMs9ELHpxjI1RkO-1)

**Comment by mattmarino-adhoc** [comment]
[The error scenario has been added to documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/FE-documentation-MVP.md)

**Comment by mattmarino-adhoc** [comment]
[Documentation updated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/FE-documentation-MVP.md)
