### ISSUE TITLE
Refactor vets-api deploy delay notification workflow

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#91838]
## User Story
As a backend Platform eng I want to know if deploys are being delayed because it's indicative of a failure in the pipeline.

## Issue Description
Originally implemented in https://github.com/department-of-veterans-affairs/va.gov-team/issues/84577, the [Deploy Delay Notifications](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/deploy_delay_notifications.yml) action posts a message in [#platform-cop-be-notifications](https://dsva.slack.com/archives/C039HRTHXDH) if commits are being merged but not deployed. This is really helpful because it alerts us that something is not right with the deployment pipeline. Could be a failing test on `master`, a failure in Argo, or a failure in the Build, Push, & Deploy GitHub Action. The sooner we find out about these things, the better. 

This workflow is a bit buggy, however. Many of us have had great intentions to fix it during our downtime while on support, but there hasn't been much downtime recently!

## Tasks
- [x] Investigate the workflow to determine what the bugs are
- [x] Fix bugs
- [x] Test/monitor

## Success Metrics
_Describe what success looks like for this work. Define specific, measurable outcomes that indicate success._

## Acceptance Criteria
- [x] Deploy delay workflow alerts when there is a delay
- [x] It should only alert once (i.e. it shouldn't keep posting a message every 30 min saying it's delayed)
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by ryan-mcneil** [comment]
Added extra error handling case so that we don't get broken error messages when the commit isn't found for some reason (5XX) and fixed logic (`-lt` was swapped for `-gt` in August which was wrong - the current configuration should fix it). I think we can take it a step further and check the last 5 commits, which I'm poking at on the side.
