### ISSUE TITLE
SPIKE | 686/674 Evidence upload page size limit

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#91831]
## Issue Description
_Some backup submissions of 686/674 fail because the page size of the pdf is too large._

Kyle Soskin shared: Did lighthouse throw the error? For 526 there was an old limit of 21x21. Lighthouse removed that for us once we discovered downstream can support up to like 78x101. So them removing that check allowed everything to work between 21 and 78 making it very rare to get an occurrence of that error. Just making sure this isn’t a case of them just not removing that limit on other endpoints as well.

Related FE work to prevent this issue is in #90383

---
## Tasks
- [ ] Determine if LH thew the error. If so, what is the page size limit LH is using? 526 had the limit updated to 78x101
- [ ] If the old 21x21 limit is being used, ask LH to expand to 78x101.

## Acceptance Criteria
- [ ] LightHouse is not an artificial limiting factor for evidence upload page size
---

**Comment by mjknight50** [comment]
We should revisit this with the work that @danlim715 did for pension/burial
