### ISSUE TITLE
Jill Create initial draft pages/outline: next-build docs CMS

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#91841]
## Problem statement
CMS Team does not have any documentation regarding the next-build process on the Platform Website. Content-build is going away and CMS' current contract ends Oct. 11, 2024. We need to begin to update the documentation.

## Issue Description
Jill Taylor will be working part-time for the CMS Team as they begin to move under the Platform. Jill will create new pages based on existing documentation and including the next-build information. 

---
## Tasks
- [x] Create an outline of topics
- [x] Create draft pages 
- [x] Create epic for all CMS work

## Acceptance Criteria
- [x] Pages created
- [x] All tasks completed
- [x] Ready for next step
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
This ticket is being brought into the current sprint due to reserved capacity for Content Team member @taylojill to support the CMS team.

**Comment by taylojill** [comment]
Currently at a stopping point on the CMS project, waiting for guidance from leadership. I created a draft list of topics, with more TBD after getting SME/leadership assistance. I also started two pages that are in a very rough draft state. I sent the topic list to @jknipes via our Slack channel.

**Comment by jknipes** [comment]
Tasks completed, closing this ticket
