### ISSUE TITLE
FMB Phase 4: Ask appropriate stakeholder team to redirect PDF

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#91852]
```[tasklist]
### Tasks
- [ ] Identify the right stakeholder
- [ ] Ask them to redirect  https://benefits.va.gov/BENEFITS/factsheets/general/Accrued.pdf  to va.gov/family-and-caregiver-benefits/survivor-compensation/accrued-benefits/    
- [ ] Confirm redirect is working and close ticket
```

**Comment by kristinoletmuskat** [comment]
This will be ready to do once the new page is live (after launch of phase 4)

**Comment by kristinoletmuskat** [comment]
Closing because this is going to be delayed until next year.
