### ISSUE TITLE
DR | Code cleanup & add missing tests

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#91894]
## Value Statement

**_As a_** developer
**_I want to_** remove deprecated & unused code
**_So that_** the code base is easier to maintain

---

## Background Context

- HLR will get an api update and some of the v1 code & data is no longer needed
- DR forms should have an e2e test for showing an alert after 101 issues are selected
- Investigate and remove or update code in all DR apps

## Acceptance Criteria

- [ ] DR apps have outdated and unused code removed
- [x] DR apps have additional code coverage

## Tasks

- [x] Remove HLR v1 code
- [x] Remove obsolete data migrations (e.g. HLR rep phone transformation)
- [x] Add HLR 101 selected issues e2e test
- [x] Add NOD 101 selected issues e2e test
- [x] Add SC 101 selected issues e2e test
- [x] Investigate all DR apps for unused code

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
Ready to merge after answering some code review questions.

**Comment by eileen-coforma** [comment]
Found a bug. Once it's merged, this can be counted as complete.
