### ISSUE TITLE
Determine call in method and number for sync

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91891]
## User Story
As an OCTO PO, I want to have a predetermined video call set up for the PO Sync meeting, so I know what to expect every time.

Assignee:
Peer Reviewer:

## Description
All DIs, MPRs, and SRs use the same Zoom information. The Zoom info is associated with @shiragoodman's Zoom account and it is included by default in every Calendly event. 

However, the PO Sync meeting will not be attended by Shira and/or other Governance team members. The purpose of this ticket is to determine if Matt and Danielle would like to continue using Shira's Zoom info, or if they'd rather use their own MS Teams info.

Pros of using Shira's Zoom:

- it's the same as the Zoom for DI, MPR and SR
- Zoom controls are easy to understand
- Zoom tends to be reliable.

Cons for using Shira's Zoom:
- cannot assign Matt or Danielle as host since they're not Oddball
- will not be able to record meetings as no host will be present
- if Shira has another meeting, 2 meetings might not be able to exist at once

In order to make the scheduling as easy as possible, the video call in information will need to be the same for each and every PO Sync. If Matt or Danielle would like to make it different for greater security, then there will be delays to the timeline as additional work and LOE will be needed.

### Live pages
- 

### Drafted pages
- 

## Tasks
- [x] Matt has created a MA Teams link (https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZTMzMzA5MTktY2FlZS00MWJiLThhODQtZjZmNTgxMWYzNmM3%40thread.v2/0?context=%7b%22Tid%22%3a%22e95f1b23-abaf-45ee-821d-b7ab251ab3bf%22%2c%22Oid%22%3a%22405c1400-337a-430d-98ea-65385c7e30c1%22%7d)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have determined the video call in preference from Matt and Danielle for the PO Sync
- [x] We have added the video call in information to the Calendly event for the PO Sync

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Per discussions at meeting on 8/30, maybe we just default to using Shira's Zoom and then change later if not being able to record the meeting or conflicts with Zoom becomes a significant problem.

**Comment by allison0034** [comment]
I added the MS teams link Matt provided to Calendly.

**Comment by shiragoodman** [comment]
@humancompanion-usds please keep us informed if the MS Teams information shared through Calendly becomes problematic. There are some other solutions we can explore.
