### ISSUE TITLE
Redis POAM: Create user credentials

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91890]
## User Story
As the Managers and Developers working on the Redis POAM, 
We need to create user credentials in Redis, 
So that we can continue to mitigate the encryption issue.

## Issue Description
Need to create user credentials in the Redis environment. 

## Tasks
- [ ] Create user credentials in the Redis environment in the next cluster first
- [ ] This will be done in the same context as the TLS upgrade
- [ ] Test Redis environment after user credentials have been created to ensure no new errors
- [ ] Document any changes made and link the documentation to this ticket. 

## Success Metrics
User credentials are created with no additional issues to the Redis environment.

## Acceptance Criteria
- User credentials are created
- Documentation is drafted, reviewed and finalized
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by flooose** [comment]
We should look at accomplishing this with [elasticache_user](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_user) and/or [elasticache_user_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_user_group)

**Comment by flooose** [comment]
The [test cluster](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92015) can be used to validate the terraform changes before making changes in the lower environments.

**Comment by jennb33** [comment]
9/26/2024 update: Per @flooose this work will be completed when the upgrade is complete in DEV; we initially thought that incremental cluster upgrades could be completed, but it actually needs to be done in one session. OK to close this ticket.
