### ISSUE TITLE
[BE] Test Cancel a Booked Appointment API Endpoint

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#91924]
## Tasks

- [ ] Test Cancel a Booked Appointment API Endpoint
- [ ] Write service in vets-api to integrate with API endpoint
- [ ] Write unit tests

[API Endpoints](https://dvagov.sharepoint.com/:x:/s/HealthApartment/EawwB7rmk8VAhuTmIkly6HIBnCMjNuN6af5yNGUQsNfPHw?e=4KBugQ)

**Comment by loripusey** [comment]
closing this as this is no longer part of the MVP
