### ISSUE TITLE
Discuss and Create Guidance Around Emojis for Style Guide

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#91935]
## User Stories
As a VFS Team member, I need to understand the meaning of emojis used on Platform website documentation, so that I can confidently build on va.gov

As a Platform team member, I need to know whether I can use emojis in documents I am writing so that I won't create launch blockers that would delay the publishing of my document on Platform website.

As a Platform Content team member, I need to know what uses of emojis are OK for documentation living on Platform website, so I can look for Launch Blockers and advise authors of documents.

## Issue Description
Content team needs to come up with clear guidance regarding the usage of emojis in Platform website documentation.
The use of a chain link emoji was found throughout a large table in Developer Docs during a recent deployment, and this called for [an extensive audit and lengthy conversation in Slack](https://dsva.slack.com/archives/CL181NRJQ/p1724865276408069).

---
## Tasks
- [x] Draft guidance around the use of emojis
- [x] Content team members review document and make comments:
- [x] Joe
- [x] Lauren
- [x] Casey
- [x] Jill
- [x] Brian
- [x] Hold additional meeting to discuss, if needed (Date: ___ Time: ___)

## Acceptance Criteria
- [x] All tasks completed
- [x] Edit ticket created for writing final document
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/91935?planning-poker) with Zenhub @BSmolensky @cmarion93 @laucon @taylojill

**Comment by BSmolensky** [comment]
That is good to know, Lauren! 

My initial thoughts on this are:

- If we are going to allow emojis at all, we should treat them like we treat bold, italics, etc -- they should be used sparingly and only to add emphasis or clarity.
- They should not be used for decoration or whimsy.
- We may even want to think about, perhaps, having an "approved emoji" list. 
- The way the [Platform Tools](https://vfs.atlassian.net/wiki/spaces/GS/pages/1872855066/Platform+tools) page uses the Socks emoji and the star emoji are brilliant: it adds clarity and emphasis. 
- YES to things like red Xs when things are not allowed and Green check marks when things are approved/allowed.
- NO to things like smiley faces, poop emojis, sparkles. And probably any moving emoji. 


Any way, we have plenty of time to talk this over. But these tings just popped into my mind and I wanted to log them somewhere.

**Comment by cmarion93** [comment]
Would an emoji count as a "decorative image"? 

https://design.va.gov/content-style-guide/alternative-text-for-images

**Comment by cmarion93** [comment]
@BSmolensky I think it's necessary to distinguish between emojis and emoticons, because they aren't the same. Emojis are inline images, whereas emoticons are those lo-fi, text-based symbols you've referred to.

**Comment by jknipes** [comment]
I added some comments in the Slack thread, and then realized the discussion is taking place here - HA!
I completely agree with [Brian's earlier comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91935#issuecomment-2322264623) about what would constitute proper usage.

The Microsoft guidance seems to refer to support messages to customers, rather than emoji use in documentation. Definitely good though to know what k15t will and won't support in publishing.

**Comment by BSmolensky** [comment]
@cmarion93 - I agree that our guidance should discuss the difference between the two. But my OP was simply (or not so simply, as it were) saying that [Emojis evolved from emoticons](https://en.wikipedia.org/wiki/Emoji#Evolution_from_emoticons_(1990s)) and therefore, many of the standard emojis are easy for screen readers to read. So, from an accessibility standpoint, as long as users stick to standard emojis we will likely not have a large accessibility issue.

**Comment by BSmolensky** [comment]
@jknipes - we should probably move this to its own Slack discussion on our content-chats channel. Just to make everything more easily accessible to all.

**Comment by jknipes** [comment]
moving into current sprint due to available capacity, continuation of project

**Comment by cmarion93** [comment]
Draft link: https://vfs.atlassian.net/wiki/spaces/PWD/pages/3478552585/Emojis+DRAFT

**Comment by jknipes** [comment]
instead of forbidden list, create box with message, something like: "anything not on the approved list is discouraged from use"

**Comment by jknipes** [comment]
work complete, closing as _Done_
