### ISSUE TITLE
Update our Collab Cycle flow

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91945]
## User Story
As a Governance Team member on support, I want to have documentation to reference, so that I know what touchpoints to add to kickoff tickets.

Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description
We've established anew OCTO PO Sync touchpoint but need to update our workflow and support docs ~~to make sure it only applies to OCTO teams.~~

Add clarification to PO Sync code block specifying that it is for OCTO only, however non-OCTO is able to participate if they choose to.

### Live pages

- [Collaboration Cycle Kickoff - Code Blocks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3387457549/Collaboration+Cycle+Kickoff+-+Code+Blocks)

### Drafted pages
- 

## Tasks
- [x] Update PO Sync Code block to note it is for OCTO teams only

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Operational documentation is updated and Governance Team members know when to suggest a PO Sync touchpoint.

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@allison0034 was any of this documentation updated when I was out? I am unsure if we still need to do this work.

**Comment by allison0034** [comment]
@shiragoodman we need to add a question to the kickoff questions and then update our flow chart... so no it was not worked on. We added the description and acceptance criteria.

**Comment by shiragoodman** [comment]
thanks @allison0034 . I'm unsure if we need to add a question to kickoff since we're currently adding the PO Sync to every collab cycle ticket, regardless is the team is OCTO. Let's discuss this ticket in refinement tomorrow. Thank you!

**Comment by allison0034** [comment]
@shiragoodman we are only added it to every ticket because we do not have the question yet. But we can def pivot, I think we really need to think about the process and what works best.

**Comment by erinrwhite** [comment]
Working on this in tandem with #93085 - added line to [PO Sync code block](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3467837441/93085+-+Erin+-Collaboration+Cycle+Kickoff+-+Code+Blocks):

> **Note:** The PO Sync touchpoint is for OCTO teams only. Non-OCTO teams are welcome to participate if they choose.

**Comment by erinrwhite** [comment]
[Collaboration Cycle Kickoff - Code Blocks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3387457549/Collaboration+Cycle+Kickoff+-+Code+Blocks) page updated and ready for review @allison0034

**Comment by erinrwhite** [comment]
@allison0034 Pushed these changes to [Collaboration Cycle Kickoff - Code Blocks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3387457549/Collaboration+Cycle+Kickoff+-+Code+Blocks) as part of #93085. all set to close?

**Comment by allison0034** [comment]
Good to close!
