### ISSUE TITLE
Define how to invite the OCTO-DE Design PA leads

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91944]
## User Story
As a Governance Team member, I want to have operational documentation, so that I can invite the right OCTO PA leads to the PO Sync.

Assignee: @allison0034 
Peer Reviewer: @KKitagawa-Bosch 

## Description
As part scheduling the new PO Sync touchpoint Governance Team members need guidance on how to complete the scheduling process. We have similar operational documentation for scheduling other touchpoints that we can reference.

### Live pages
- [PO Sync](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3467018468/PO+Sync+-+Scheduling)

### Drafted pages
- [PO Sync - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3456958466/91944+Allison+PO+Sync+-+Scheduling)

## Tasks
- [x] Create a distribution email with OCTO-DE leads (Matt, Danielle, Martha, Mikki, Shane, and Ryan) 
- [x] Create PO Sync documentation for Governance Team to follow
- [ ] [Matt has requested Governance Team get access](https://dsva.slack.com/archives/G01DXP10GCA/p1725454853032579) to set up MS Teams meetings for this
  - Shira will discuss with Matt at sync on 9/20 - want to try a wait and see approach.
  - Does the PO Sync need to be recorded? Shira votes no. If they wanted these convos to be contractor- facing, then contractors would be invited to the meeting in the first place

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] There is a mechanism for OCTO PA leads to be invited to PO Sync

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
[Created draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3456958466/91944+Allison+PO+Sync+-+Scheduling)

**Comment by allison0034** [comment]
I requested a PO sync email list and am waiting on that. @KKitagawa-Bosch do you want to take a look at the [PO Sync draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3456958466/91944+Allison+PO+Sync+-+Scheduling)?

**Comment by allison0034** [comment]
Email list has been created.

**Comment by allison0034** [comment]
@KKitagawa-Bosch the PO Sync page is ready for your review and under live pages.

**Comment by KKitagawa-Bosch** [comment]
@allison0034 looks good to me! The email list also comes up for me in google calendar, so looks like that is all working as well!

**Comment by allison0034** [comment]
@KKitagawa-Bosch tweaked a couple of things, take one more peek when you get back please.

**Comment by shiragoodman** [comment]
@allison0034 I spoke to Matt and he is ok with Governance not getting access to MS Teams. He agreed with the wait and see approach, and he also agrees that the sync's should not be recorded. thanks!

**Comment by allison0034** [comment]
@KKitagawa-Bosch ready for your review

**Comment by KKitagawa-Bosch** [comment]
@allison0034 looks good! My only thought is do we want to put the "add a checkmark" in a separate step since it's not /really/ part of notifying octo? But that's probably being a bit pedantic for something that's only being read by our team 🤷

**Comment by allison0034** [comment]
@KKitagawa-Bosch that's fair... updated!

**Comment by KKitagawa-Bosch** [comment]
Looks good to me! @allison0034
