### ISSUE TITLE
[QA] 10-10CG - Facilities: Review & update Test Cases

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#91947]
## Background
To improve the Facility Selection experience, we are implementing new functionality to allow users to input their city, state or postal code and get a list of results from which they can choose. We need to create the results list that contains radio cards to allow for the selection of a single facility. 

The cards should contain the facility name and address as shown in the Figma designs. Based on consultation with design system and accessibility experts, we can omit any pagination for this list. We should show all results on the same screen, loading 5 facilities at a time.

### Resources
- [Figma Designs](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2478-18708&node-type=SECTION&t=LIbnyXIFEnPa5jZz-0)
- [Test Cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-10-10cg-facility-selection.md)

## Tasks
- [x] Review existing test cases
- [x] Discuss with Design & Engineers on expected functionality 
     - Some has changed since the test cases were created
     - Notes are added to those that may need confirmation
- [x] Update the test cases where needed
- [x] Update test cases in Test Rail
     - This is required since we will be going through the Staging Review with the Governance team
     - Artifacts from Test Rail will be required at Staging review (separate ticket for gathering these)
  
## Acceptance Criteria
- Test cases have been reviewed and updated to match expected functionality for the CG Facilities search pages

**Comment by allanto-ah** [comment]
Test cases updated:
[1010cg-facilties-test-cases.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejVsQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8d673ae2a7a09ff40ab68b4d04ab1c25e9898a7/1010cg-facilties-test-cases.pdf)
