### ISSUE TITLE
[QA] 10-10CG - Facilities: Testing on Facilities search functionality

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#91949]
## Background
As a Veteran, I want to search for my preferred facility by city, state or postal code, so that I can see a list of results from which I can choose. 

### Resources
- [Figma Designs](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2478-18708&node-type=SECTION&t=LIbnyXIFEnPa5jZz-0)
- [Test Cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-10-10cg-facility-selection.md)

## Tasks
- [x] Review all screens against Designs
- [x] Validate the Search functionality
- [x] Validate that the page order and form flow is appropriate as expected
- [x] Validate the form Review Page display the expected Facility information
- [x] Validate the form Review Page edit/update functionality
- [x] Validate the CG facility (when different from selected facility) populates the downloadable PDF after submission
- [x] Perform Accessibility QA on new pages and functionality
- [x] Document any findings in the comments
- [x] Determine if a new ticket is needed for the findings
- [x] Review results with PM/Team (can be async)
  
## Acceptance Criteria
- The 10-10CG Facilities search pages and form Review page are functioning as expected, and have passed all Accessibility testing.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the facilities search functionality is working as expected. Attached is the results from Testrail. @hdjustice this is ready for review, let me know if there is something that I am missing. 

[10-10CG - Facilities search - TestRail.pdf](https://github.com/user-attachments/files/17837322/10-10CG.-.Facilities.search.-.TestRail.pdf)

**Comment by allanto-ah** [comment]
@hdjustice yeah, of course!
