### ISSUE TITLE
Release Tracking - Monthly expense support work

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#91946]
#### **Monthly expense work to support:**
- (S)Epic #[75716](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75716) Portal Overall FE/BE Logic Shift and Code Cleanup
- Epic #[79904](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/79904) Portal Maintenance 2024 (April, May, June)

**Release items**
Ticket #[68302](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/68302) Housing expenses (Mortgage/Rent) and Other expenses updates
Ticket #[83576](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/83576) [FSR] Housing expenses testing

- Release Dates
- [x] Thursday 09/05/24 - 5%
- [x] Friday 09/06/24 - 25%
- [x] Monday  09/09/24 - 50%
- [x] Wednesday 09/11/24 - 100%

## Acceptance Criteria
- [x] Production testing passed for each phase
## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by Tom-Davis** [comment]
@Dr-Pongo are we clear to check the last box and close this today?

**Comment by Dr-Pongo** [comment]
The launch is complete!
