### ISSUE TITLE
Write design doc for handling E2E Tests that run too long

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#91957]
## Issue Description
In an effort to reduce the time it takes our E2E suite to run in CI, we collected some data [here](https://va-gov.domo.com/page/604433393) about the average runtime of test specs. We set our target at 1 minute and all but 5 specs have met that average execution time over a long period of time. We'd like to address the ones that don't and have updates made to get their execution times down.

We need to write a design doc outlining our planned solution to get these tests to adjust to where they run within the expected timeframe. We also need to ensure this doc gets the proper approvals from stakeholders on our proposed solution.

---
## Tasks
- [x] Write design doc covering intended solution for long-running E2E tests.
- [x] Shop design doc to stakeholders for approval

## Acceptance Criteria
- [x] A plan is put in place to get the test suite time under control.
