### ISSUE TITLE
[QA] 10-10CG - Facilities: Complete End-to-End testing with CG Stakeholders/Tech team

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#91953]
## Background
As a Veteran, I want to search for my preferred facility by city, state or postal code, so that I can see a list of results from which I can choose. 

### Resources
- [Figma Designs](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2478-18708&node-type=SECTION&t=LIbnyXIFEnPa5jZz-0)
- [Test Cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-10-10cg-facility-selection.md)

## Tasks
- [x] Coordinate with CG tech team to complete End-to-End testing on new Facilities Search functionality
     - Select various facilities, including newer ones that have been added to the Facilities API (check with Mitch)
- [x] Validate that the CG supported facility information (when different than selected facility) is sent to the CARMA system
- [x] Document any findings in the comments
- [x] Determine if a new ticket is needed for the findings
- [ ] Review results with PM/Team (can be async)
  
## Acceptance Criteria
- The 10-10CG Facilities search end-to-end testing is completed successfully

**Comment by allanto-ah** [comment]
Issue has been fix on our side, but because of the break, CARMA won't be able to check on their side until next week

**Comment by allanto-ah** [comment]
Environment: Staging

Verified with CARMA team that the submitted CG forms are seen on their side as expected

E2E results: [Slack link](https://dsva.slack.com/archives/C02MJCT59S7/p1732642173485919)

**Comment by hdjustice** [comment]
Slack thread with confirmation from Waleed
---

Allan To
Dec 2nd, 2024 at 7:31 AM
Thank you! I'm going to submit a couple more today and if you can check as well, that'd be great! I'll let you know when I submitted them
Okay I just submitted two to the staging environment, can you confirm you can see on your side and send me the json as well? Thank you!


Waleed Jaffar
Dec 2nd, 2024 at 7:38 AM
yep I can see them!
 

> CARMA Case: CARMA Case Number	First VARD	Valid Application Received Date	Primary Caregiver Name	Secondary Caregiver #1 Name	Secondary Caregiver #2 Name	Created Date	CARMA 1010CG Service Request
> CD-1754344		12/2/2024	pfc pfc	sfc sfc		12/2/2024 9:33 AM	{ "data": { "veteran": { "primaryPhoneNumber": "8008271000", "email": "vets.gov.user+36@gmail.com", "address": { "street": "423 street city", "city": "city", "state": "AL", "postalCode": "52412", "county": "countyone" }, "ssnOrTin": "796043735", "fullName": { "first": "Wesley", "middle": "Watson", "last": "Ford" }, "dateOfBirth": "1986-05-06", "gender": "M", "plannedClinic": "608", "signature": "Wesley Watson Ford" }, "primaryCaregiver": { "primaryPhoneNumber": "2134123142", "address": { "street": "423 street city", "city": "city", "state": "AL", "postalCode": "52412", "county": "countyone" }, "fullName": { "first": "pfc", "last": "pfc" }, "dateOfBirth": "1987-02-01", "vetRelationship": "Spouse", "signature": "pfc pfc" }, "secondaryCaregiverOne": { "primaryPhoneNumber": "5121321234", "address": { "street": "423 street city", "city": "city", "state": "AL", "postalCode": "52412", "county": "countyone" }, "fullName": { "first": "sfc", "last": "sfc" }, "dateOfBirth": "1987-02-01", "vetRelationship": "Spouse", "signature": "sfc sfc" }, "signAsRepresentative": false }, "metadata": { "claimId": 72016, "claimGuid": "dd0bb19a-bd98-4f34-9a54-79642d49aa08", "submittedAt": "2024-12-02T15:33:25Z", "veteran": { "icn": "1012832025V743496", "isVeteran": false }, "primaryCaregiver": {}, "secondaryCaregiverOne": {} } }
> CD-1754346		12/2/2024	pfca pfca			12/2/2024 9:35 AM	{ "data": { "veteran": { "primaryPhoneNumber": "8008271000", "email": "vets.gov.user+36@gmail.com", "address": { "street": "123 city wstreet", "city": "city", "state": "KY", "postalCode": "52312", "county": "countyagain" }, "ssnOrTin": "796043735", "fullName": { "first": "Wesley", "middle": "Watson", "last": "Ford" }, "dateOfBirth": "1986-05-06", "gender": "M", "plannedClinic": "534", "signature": "test test" }, "primaryCaregiver": { "primaryPhoneNumber": "5131231234", "address": { "street": "123 city wstreet", "city": "city", "state": "KY", "postalCode": "52312", "county": "countyagain" }, "fullName": { "first": "pfca", "last": "pfca" }, "dateOfBirth": "1987-03-01", "vetRelationship": "Daughter", "signature": "pfca pfca" }, "signAsRepresentative": true, "poaAttachmentId": "4e9f2a73-d5e1-4252-8096-be9fd53ab843" }, "metadata": { "claimId": 72017, "claimGuid": "71457557-2d9a-4793-b17b-f63112886224", "submittedAt": "2024-12-02T15:35:25Z", "veteran": { "icn": "1012832025V743496", "isVeteran": false }, "primaryCaregiver": {} } }
> Click to expand inline (127 lines)



Allan To
Dec 2nd, 2024 at 7:41 AM
nice! looks good to me! thank you for the assistance as always!
