### ISSUE TITLE
[Design] My VA: Backup blue sky prototype from InVision

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#91962]
## Background
The Blue Sky prototype created with InVision will become unavailable at the end of the year, as InVision is shutting down. The prototype needs to be backed up using Figma.

## Tasks
- [x] Backup prototype to github
- [x] Find references (if any in GH) to old link and update

## Acceptance Criteria
- [x] Prototype backup is accessible in github, without using invision

**Comment by mattmarino-adhoc** [comment]
This was previously backed up in PDF format by Liz Lantz, unbeknownst to me...https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/blue-sky-prototype

**Comment by ajakabcin** [comment]
@mattmarino-adhoc rolling to next sprint
