### ISSUE TITLE
Copy of Copy of Appoint a Rep - Cross Accredited VSOR - User Test - Team Report

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#91965]
## Issue Description
Interviews and user test of the 21-22 with cross accredited VSORs.

## Tasks
- [ ] Create report
- [ ] Create ideation workshop based on findings
- [ ] Review report with key stakeholders
- [ ] Conduct ideation workshop for recommendations
- [ ] Create share-out and filing tickets

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
Materials uploaded to SP and share-out scheduled - closing ticket
