### ISSUE TITLE
Implement AL2 Review Deployment

### ISSUE THREAD

**Issue by ben-allen-oddball** [department-of-veterans-affairs/va.gov-team#91976]
## Issue Description
Given the outcome from the discovery spike:

https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/88199

Complete the remaining items and update review instance deployment process.

---
## Tasks
- [x] Implement legacy Ansible image discovery pattern to identify the latest AL2 Base Image
- [x] Test and validate cleanup still works
- [x] Peer Review and Merge

## Acceptance Criteria
 - [x] **Scenario: Implement legacy Ansible image discovery pattern to identify the latest AL2 Base Image**
  - Given the legacy Ansible image discovery pattern is implemented
  - When the pattern is used to find the latest AL2 Base Image
  - Then the correct image should be identified and returned
- [x] **Scenario: Test and validate cleanup still works**
  - Given the cleanup process has been implemented
  - When the cleanup process is tested with various scenarios
  - Then the cleanup should work as expected and not cause any issues
- [x] **Scenario: Peer Review and Merge**
  - Given a peer review is requested for the implementation
  - When the code is reviewed by another team member
  - Then the changes are merged into the main branch after approval

**Comment by ben-allen-oddball** [comment]
http://c81168fe67d4cc18d4d2d2e809edc380-api.review.vetsgov-internal/

**Comment by ben-allen-oddball** [comment]
http://jenkins.vfs.va.gov/blue/organizations/jenkins/deploys%2Fvets-review-instance-deploy/detail/vets-review-instance-deploy/150695/pipeline/

**Comment by ben-allen-oddball** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/14641
