### ISSUE TITLE
Schedule Reminder Messages to Tier 2 Support for Code Freezes

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#91986]
## Description 
In an effort to ensure code freezes happen on rotation without having to remember each time, we are going to create an automatic message to the engineers on DevOps, Frontend and Backend to create a code freeze. 

2024 Dates:

- 11/11/2024 - Veteran's Day
- 11/28 - 11/29 - Thanksgiving
- 12/23 - 1/3/2025 - Holiday Freeze

Additional information on code freezes [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies#DeploymentPolicies-Holidayreleasefreezeschedule).
---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Schedule out messages to enact a code freeze prior to each date listed above
- [x] Schedule a calendar reminder to send messages for 2025
- [x] Make sure documentation is accurate with the code freeze instructions for Frontend, Backend and DevOps [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630353240/Advanced+Ticket+Support+Best+Practices+Tier+2) 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
@bdech Going to take this one on and will have you review. You can focus on the Bonnie ticket!

**Comment by bdech** [comment]
Veteran's Day slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1726761374595109)

**Comment by bdech** [comment]
Thanksgiving slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1726761762784799)

**Comment by bdech** [comment]
Included new section in Advanced Ticket Support Best Practices

New section [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630353240/Advanced+Ticket+Support+Best+Practices+Tier+2#Code-Freeze)

**Comment by bdech** [comment]
Added to [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)

**Comment by alyssagallion** [comment]
Put incorrect sprint time period. Corrected.
