### ISSUE TITLE
[BE] Modify Appointment Serializer for finding appointment types in Upcoming appointments

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#91993]
## Description
Modify appointment serializer to pass through all the fields used for determining the appoinment type as in [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/backend-logic.md#appointment-types)

## Tasks
- [ ] [BE] **Modify Appointments Serializer**
- [ ] [BE] **rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Yes Lori, we need to send few fields for the front end to identify the type of appointments.  I am currently working on this.

**Comment by kanchanasuriya** [comment]
Currently addressing PR comments, Lori.  Based on the approval, it may get closed today.
