### ISSUE TITLE
Redirects/LInks  from BAM2 for Medical Device Reordering Tool 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#9200]
## Why you're here
- Content support for static public website pages
- Content support for authenticated application or tools
- For specific copy editing tasks
- Support for redirects that have **first been vetted by the VSP IA team**
- Engineering support for implementation of REACT sign in widgets

## Steps to complete intake request
- [x] Submit this request when VSA Public Website team intervention is required
- [x] Provide detailed information of your request to help us understand our role in completing your request 
- [x] Link to this issue in #vsa-public-websites in Slack, tag @Selina Cooper 

__When to submit a request__

Requests should be submitted at least **2 weeks** in advance of the targeted launch/completion.  Make your request as soon as you're aware you will need Public Website participation. Different types of requests may require more time in advance. For apps tool content support, try to engage a content person for your project kick-off.

---

### Background
This is  for Medical Device Reordering Tool which allows Veterans to reorder hearing aid batteries and accessories, there is a legacy app currently in eBenefits. - you an see is here 

https://staging.va.gov/hearing-aid-batteries-and-accessories

IIA Ticket for Collab Cycle with all the suggested links, redirects https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6378

* **Is the request related to a VA.gov tool? Provide a brief description of the tool or functionality:**  
   * Allows the veteran to reorder hearing aid batteries and accessories
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * Designs - https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens
   * Usability https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/medical-device-tool/research/usability-march20

The requested URL is www.va.gov/health-care/order-hearing-aid-batteries-and-accessories/ 
### Request Type
*Select all applicable and provide details behind your request* 

- [ ] **Content support for authenticated app/tool.** Note: Support is provided only for VSA apps teams that do not have its own dedicated content writer. In addition to the generic information above, please share:
   * Word document with draft if available, or link to the URL where the draft content appears:
      * < link > 
   * Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?)
      * < design context >
   * Scope: How many screens? (Or messages, etc.) 
      * < scope > 
      
      
- [ ] **Content support for a static public website page**
   * Is this to update existing static content? 
      * No
   * Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.)
      * Yes see page here https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction
   * Provide a list of URL/s that need to be reviewed or updated. 
      * See AI review which outlines all the suggestions https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-med-device-order.md
  

- [ ] **New URL or Redirect Requests**
   * Have you vetted this request by the VSP IA team?
      * Yes full review in collab cycle is completed and ticket attached here 
   * Link to VSP IA Redirect Request ticket
      * https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-med-device-order.md
      

### Desired/target implementation date
6/23

### Requestor info
*Indicate what team and who the primary contacts are on your team* 

- Team name: *enter name*
- DEPO product owner: Matt
- Product manager: Leah 
- Designer: *becca, Riley 
- FE engineer: Brad, Mahariel 
- Product/team Slack channel: BAM2

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by leahkeeler** [comment]
Hi @stephorkandatx - I saw this is in your current sprint, Thank-you! If by any chance this is done before the end of the sprint can you please ping me. cc @mnorthuis 

For easy reference the entire IA review is [here https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-med-device-order.md

Thanks! Leah

**Comment by stephorkandatx** [comment]
@leahkeeler will do. 
@lunascoop because these are redirects will we need to send advanced notice out? We can chat tomorrow so I am better aware of what needs to take place. Thanks!

**Comment by lunascoop** [comment]
@stephorkandatx these redirects do not require advanced notice since they are not legacy pages. Basically, the current page, https://www.va.gov/health-care/order-hearing-aid-batteries-prosthetic-socks/, will be split into two (one for ordering hearing aid supplies and the other for prosthetic socks). The new hearing aid supplies page should link to the static landing page for Form 2346 (ordering hearing aid supplies).

**Comment by mnorthuis** [comment]
@stephorkandatx @leahkeeler FYI there is a redirect issue template to ensure that all information is collected and we route them through the correct process.  I'm not sure if there is other work on this ticket, but please move the redirect requests into the redirect issue template.  Thank you!

**Comment by leahkeeler** [comment]
Thanks @mnorthuis - per @lunascoop its not a redirect per se - as the page is getting split up into hearing aids and accessories and the prosthetic socks is not changing -- does it still make sense to use the redirect template? want to make sure we are doing everything right

**Comment by mnorthuis** [comment]
It will actually require a redirect of the old URL to the new URL once the page is split up (because the 2 new pages will have new URLs).  I'm checking in with the PW team on this work tomorrow, so I will work with them on this and get the right tickets in place.

**Comment by lunascoop** [comment]
Closing this ticket. Redirect implementation will be captured in ticket #10027 . Content review efforts are captured in ticket #7234. Creation of Drupal pages are captured in ticket #10110.
