### ISSUE TITLE
Content Edit: 90948

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#92012]
## Problem Statement

- Sitewide team recently removed a flipper, but current documentation does not reflect this update. 
- Under **Step 2** of the `So, how do I use Drupal as the source of truth?` header of [this page](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for#Howtoopt-intoDrupalasthesourceoftruthforOracleHealth-relatedappsandwidgets-So,howdoIuseDrupalasthesourceoftruth), the example linked demonstrates the flipper behavior, which is now outdated.

## Issue Description
Per Footer ticket [90948](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/90948), we need to remove text from **Step 2** on [the How to Opt in to Drupal page](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for#Howtoopt-intoDrupalasthesourceoftruthforOracleHealth-relatedappsandwidgets-So,howdoIuseDrupalasthesourceoftruth?) on the website.

## Screenshot (scroll down to view red arrow):
![image](https://github.com/user-attachments/assets/e083e2cd-6398-4b34-8b0c-613cab98dfdc)

 

---
## Tasks
- [ ] Create copy of [the page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2330165343/How+to+opt-in+to+Drupal+as+the+source+of+truth+for+Oracle+Health-related+apps+and+widgets) in Draft space
- [x] Remove the text indicated by the red arrow above (also shown in red box on ticket [90948](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/90948))
- [x] Contact ticket 90948 author Randi Mays to confirm changes to page are sufficient
- [x] Check for Launch Blockers

## Acceptance Criteria
- [x] Section removed
- [x] Page ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/92012?planning-poker) with Zenhub @BSmolensky @cmarion93 @laucon @taylojill

**Comment by taylojill** [comment]
Page updated as requested. Ready to publish. Here's what I did:
1. Removed section called out with red arrow
2. Posted a note to requestor (Randi Mays) in our Slack channel
3. Added date stamp
4. Checked for blockers

**Comment by jknipes** [comment]
work is complete, moving to _Done_
