### ISSUE TITLE
[FSR] Update confirmation page components and fix heading structure

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#92010]
## Description

Enter a detailed description of the work - gherkin syntax below is acceptable.

Given: A veteran fills out an FSR
When: They submit an FSR and see the confirmation page
Then: They should see the updated components and correct styles and a screenreader user should hear the correct headings

## Tasks
- [x] Update components 
- [x] Fix spacing and styles
- [x] Fix heading structure 

## Design and Front End sync on implementation of design
- [ ] Required
- [x] Complete
- [ ] Not Required

## Acceptance criteria
- [x] Components and styles have been updated 
- [x] Heading structure has been fixed 

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
