### ISSUE TITLE
Update Download Page designs to exist outside of the form experience

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#92016]
## Background
Our developers have discovered that the VA Forms Library ends at the "Review" page which presents a challenge for us as we had planned for another page in the flow after "Review" -- the "Download" page.  

## Tasks
- [x] Present options to the team on how to address
- [x] Finalize an option
- [x] Update designs
 
## Acceptance Criteria
- [x] The MVP designs have been updated, based on the team's decision on how to address the "Download" page, now knowing it sits outside of the form experience.

**Comment by oddball-lindsay** [comment]
The team has discussed how to handle this and have decided that we can keep the Download page, but will need to remove the progress bar and the "back" button since the user is now technically out of the form flow experience.  

Original options presented by @mtri, where the team decided to proceed with Option 2.
https://dsva.slack.com/archives/C05L6HSJLHM/p1725047898860319

**Comment by mtri** [comment]
This change has been made across Appoint MVP and v2.

For v2 noting for the future there will be some logic since PDF generation and digital submission will both be available.

**Comment by oddball-lindsay** [comment]
@mtri heads up that I'm still seeing the "back" button in the Unauth MVP and v2 designs.

**Comment by mtri** [comment]
@oddball-lindsay Thanks for catching! It has been fixed.
