### ISSUE TITLE
Redis POAM: Create Elasticache Test Cluster 2

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#92018]
## User Story
As the Managers and Developers working on the Redis POAM, 
We need a test cluster that has encryption in-transit and user credentials 
So that we can test **encryption in-place** 

## Issue Description
This cluster will reflect the state of the Redis clusters after [encryption in-transit](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92015) and [user credentials](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91890) have been deployed.

## Tasks
- [ ] Verify that encryption in-place is enabled
- [ ] Use of the correct [type of encryption](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/at-rest-encryption.html#at-rest-encryption-enable) is in place, i.e. "Default", or "Customer managed key using KMS"
- [ ] Document the results

## Validation
A clear understanding of next steps in the lower environments is in place.

**Comment by flooose** [comment]
Findings in the [previous discovery story](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87249) have made this story unnecessary.
