### ISSUE TITLE
IA Tracker: Education Test Prep pages IA work

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#92047]
## Overview
https://dsva.slack.com/archives/C03MP8MEPCN/p1725059967654159

### Description
The content team is preparing to publish these 2 new pages:
https://preview-prod.vfs.va.gov/preview?nodeId=71649 (National tests and prep courses)
https://preview-prod.vfs.va.gov/preview?nodeId=71639 (Licensing and certification tests and prep courses)

Those 2 pages are going to replace these 2 old ones:
[Get paid back for test fees](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/test-fees/) (since content on this page is being split up into 2, it's not a 1:1 redirect situation; I have a question out to SMEs to see if they have any data on volume of requests for national test reimbursement vs requests for L&C reimbursement--will let you know what I hear back) **UPDATE: Requests for L&C test reimbursement are far more common than requests for national test reimbursement.**
[Can I use my VA education benefits to pay for preparatory courses](https://www.va.gov/resources/can-i-use-my-va-education-benefits-to-pay-for-preparatory-courses/)? (this R&S page only went live in July, so you'll need to take a look at PVs and see if the volume is high enough to warrant a redirect)

### Timeline
Beth says no rush
---

```[tasklist]
### IA deliverables
- [x] [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/education-tests-and-prep-courses-22-0803%2022-0810%2022-10272.md)
- [x] [Redirect ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93434)
- [x] [Crosslinks ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94182)
- [x] Update best bets
- [x] Update sitemaps
```

**Comment by kristinoletmuskat** [comment]
From Beth: "National tests is by far the minority. Paying for L&C tests using VA education benefits is far more common." This will help inform the redirect decision for the "Get paid back for test fees" page.
