### ISSUE TITLE
Medallia - Align the horizontal line with the width of the text content on drupal templates

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#92058]
## Issue Description

`event.drupal.liquid` (ex.: https://www.va.gov/tennessee-valley-health-care/events/71847/)
`campaign_landing_page.drupal.liquid` (ex: https://www.va.gov/initiatives/veteran-trust-in-va/)

<img width="1287" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUd0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f964d07c9cc9badcdad459d059a506074c8c12c1/Screenshot%202024-09-04%20at%209.54.22%20AM.png" alt="Screenshot 2024-09-04 at 9.54.22 AM.png" />

As a user,
I want the horizontal line above the "Last updated" date and "Feedback" button to match the width of the text content,
so that the layout appears balanced, uniform, and visually appealing.

---
## Tasks
- [ ] Update drupal temples
- [ ] Visually check to ensure horizontal line of `last updated` element matches text content width

## Acceptance Criteria
- [ ] The horizontal line should be aligned to match the width of the main text block on the page.
- [ ] The line should extend no further than the text content above it, maintaining a clean visual boundary.
- [ ] The width of the line should adjust dynamically to match the responsive layout, ensuring it maintains consistency on different screen sizes.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
