### ISSUE TITLE
BE | Maintenance Window Automation Tool | Send updates to pager duty to add maint windows

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#92099]
## Background
Currently, to add a maintenance window in VA.gov, we must first add it to a corresponding maintenance window to a PagerDuty service. VA.gov then polls PagerDuty for these maintenance windows and displays them for the appropriate components. 

We are prototyping a solution that will automatically create a maintenance window in PagerDuty. This approach will streamline the process and potentially improve efficiency by reducing the need for constant polling.

## Tasks
- [ ] Create an web-based application that provides a UI for users to create maintenance windows in PagerDuty.
- [ ] Document the process.

## Acceptance Criteria
- [ ] Maintenance window records can be successfully created in PagerDuty using a web-based administrative application.
- [ ]  Documentation is provided on the process, including how the push model works and how to configure it.
