### ISSUE TITLE
Burial POC v6 Build Error

### ISSUE THREAD

**Issue by DLarson-Oddball** [department-of-veterans-affairs/va.gov-team#92095]
## Issue Description
It has been reported that burial-poc-v6 is not building correctly with the latest version of vets-json-schema.

---
## Tasks
- Create bugfix to resolve the build error.

## Acceptance Criteria
- [ ]  burial-poc-v6 builds without errors. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
