### ISSUE TITLE
BE | Maintenance Window Automation Tool | Project Scaffolding and Admin UI

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#92098]
## Background
VA.gov relies on various upstream systems to properly function. When any of these upstream systems experience outages, we disable the affected areas of VA.gov (both web and mobile) to prevent users from accessing features that won't work correctly. 

The maintenance windows are managed through PagerDuty. VA.gov communicates with PagerDuty to retrieve the list of maintenance windows, and stores them in the VA.gov database. This information is made available to VA.gov through an API endpoint.

## Tasks
- [ ] Create project scaffolding and core dependencies.
- [ ] Create authentication.
- [ ] Create external systems and services admin UI.
- [ ] Create team assignment and role management admin UI.
- [ ] Create maintenance windows admin UI.

## Acceptance Criteria
- [ ] Project is in Github.
- [ ] User's can login and logout.
- [ ] User / Team assignment is working.
- [ ] Maintenance windows can be viewed, added, updated, or removed.

*Note: No system integration*

**Comment by alatempa** [comment]
won't do
