### ISSUE TITLE
Move Board from Zenhub to GitHub Projects

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#92127]
## Description 
We need to migrate the content of our Zenhub board to GitHub Projects. 

---

## Definition of Done
Complete all tasks below.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Create board
- [x] Migrate ZH tickets
- [x] Message Jason to get our project added to analytics
- [x] Reach out to Jennifer Brown if need assistance
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Unable to complete this sprint due to configuration issues that need consultation.

**Comment by alyssagallion** [comment]
Moved work in favor of DORA metrics.

**Comment by alyssagallion** [comment]
Boards moved.

Sprint Work: https://github.com/orgs/department-of-veterans-affairs/projects/813
Support Tickets: https://github.com/orgs/department-of-veterans-affairs/projects/1408
