### ISSUE TITLE
[FE] My VA Forms Status: Errors - full page error

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#92129]
## Background
Scenarios where a veteran will see a full page error:
- `/user/` API call fails (i.e. in-progress/Draft forms will also fail)
- getting a 296 status code (aka partial error) when calling `/v0/my_va/submission_statuses`

---
## Tasks
- [ ] write e2e tests to verify that current logic does indeed handle the scenarios above
- [ ] if not, then make sure that error code gets updated in Redux state 

## Acceptance Criteria
- [ ] full page error displays correctly when we get partial error
- [ ] full page error still displays correctly when `/user/` call fails 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_

1. toggle some kind of error listed 
2. verify that we see a full page error on My VA

## Resources
- optional: links, screenshots, etc.
