### ISSUE TITLE
[FE] My VA Forms Status: Errors - full page error

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#92130]
## Background
Scenarios where a veteran will see a full page error:
- `/user/` API call fails (i.e. in-progress/Draft forms will also fail)
- getting a 296 status code (aka partial error) when calling `/v0/user`

---
## Tasks
- [ ] write e2e tests to verify that current logic does indeed handle the scenarios above
- [x] if not, then make sure that error code gets updated in Redux state 

## Acceptance Criteria
- [ ] full page error displays correctly when we get partial error
- [x] full page error still displays correctly when `/user/` call fails 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Cypress e2e tests

1. toggle some kind of error listed 
2. verify that we see a full page error on My VA

## Resources
- optional: links, screenshots, etc.

**Comment by DanielMiller-agile6** [comment]
After some discovery, we found that failures to receive Draft forms during the /user request will result in a typical server error code, so we cannot handle this separately via 296 error.

Also, I found that we're already handling 296 errors with some specific code and UI for individual sections of the page, so I don't want to treat all 296 errors as "full page" errors, since this will break the existing functionality.

I wrote some tests to help me learn how this all works, but since this functionality is all handled by platform code, I'm not going to setup a PR for these tests.  Closing this ticket out as "won't implement" since there's nothing new we need to do here regarding Draft or Submission form errors.
