### ISSUE TITLE
[BE] 10-10EZ - BUG: Investigate file upload errors

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#92139]
## Background
While files uploaded with the 10-10EZ are fairly low, the number of errors that Veterans experience are at a higher rate than is acceptable.
These errors show up as `403` error codes.
We need to review the errors, determine whether they are truly 403 errors, what could be causing the 403 and/or other file upload errors, and what could we do to reduce them.

## Tasks
- [x] Investigate the existing 403 errors
- [ ] Determine if they are truly 403 errors or something else
- [ ] Determine if there is a root cause(s) for the file upload errors (403 and otherwise)
- [ ] Determine if there are any additional logs we could implement to gain better insight when the errors occur
- [ ] Determine if there are any content changes we could implement to guide Veterans when uploading a file

## Acceptance Criteria
- The file upload errors have been investigated and we have decided on a path forward

**Comment by hdjustice** [comment]
FYI - according to Google Analytics, there are approximately 70+ files uploaded per month by authenticated users, which goes against how we understood the file upload/document screen to appear in the user flow.

**Comment by hdjustice** [comment]
| Log-in Status | July | August |
|----------------|-----------------|-------------------|
|  --  Authenticated |  |  |
|Event hca-file-uploaded | 79 | 75 |
|Number of Users | 50 | 41 |
|Number of file upload page views| 65 | 61 |
|  --  Unauthenticated |  |  |
|Event hca-file-uploaded | 216 | 197 |
|Number of Users | 173 | 122 |
|Number of file upload page views| 273 | 204 |

**Comment by hdjustice** [comment]
@Mitch-A6 - Would you want to take a stab at adding an estimate here?  I know it is all exploratory, so whatever you think is fine.

**Comment by allanto-ah** [comment]
Flipper toggle has been enabled in production. Will keep this ticket here for now to see if anything comes up

**Comment by hdjustice** [comment]
Out of the improved logs that have been added here, do we have any further insights?

**Comment by hdjustice** [comment]
Anything new on this?  Are there links to the logs to see if there is anything we can get from them?

**Comment by hdjustice** [comment]
This issue needs to be addressed via library, need to check if it is on their radar. @hdjustice
