### ISSUE TITLE
[FE] My VA Forms Status: Errors - in-section

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#92131]
## Background
Scenarios where a veteran will see a in-section error:
- getting an `action-needed` status when calling `/v0/my_va/submission_statuses`

---
## Tasks
- [ ] build out alert 
- [ ] write or update unit and e2e tests
- [ ] make sure that error code gets updated in Redux state 

## Acceptance Criteria
- [ ] full page error displays correctly when we get partial error
- [ ] full page error still displays correctly when `/user/` call fails 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_

1. toggle the `action-needed` status from API  
2. verify that we see the in-section error 

## Resources
- optional: links, screenshots, etc.

**Comment by ajakabcin** [comment]
@allisonlu rolling to next sprint

**Comment by allisonlu** [comment]
@ajakabcin bumping down estimate to 2 points!

**Comment by ajakabcin** [comment]
Closing out - we validated this ahead of staging review last week
