### ISSUE TITLE
IA review: 85/15 Rule reporting  form (VA Form 22-10215)

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#92142]
## Issue description

OCTO has decided that since this is a non-Veteran-facing form, we won't get fully involved. Instead: Our IA team will review and provide placement direction. Our content and IA team will provide guidance on the H1 to ensure that it does not compete or cause confusion with any Veteran-facing forms. Beyond that, we cannot provide additional UX flow or content support.

Basically, this Collab Cycle ticket needs an IA review to make sure they're putting stuff in the right place. Once IA has taken a look, please run the H1 by CAIA Content to make sure it works.

CC intake: https://github.com/department-of-veterans-affairs/va.gov-team/issues/91665

---
## Tasks
- [x] IA review
- [ ] Share with CAIA Content specialist (Laura or A)
- [x] Share feedback with stakeholder in CC ticket

## Acceptance Criteria
- [x] Feedback has been shared with stakeholders

**Comment by scjwalker** [comment]
The [IA Spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/school-admins-enrollment-reporting.md) is ready for the team.
This spec covers both the 85/15 Rule, and the 35% Exemption.

**Comment by scjwalker** [comment]
Note: the task 'Share with CAIA Content specialist (Laura or A)' does not apply on this ticket, since this is not a Veteran-facing form and so it receiving IA support but not Content support.

**Comment by scjwalker** [comment]
Closing ticket, as IA spec is complete. I will support team questions via the CAIA Intake Tickets
