### ISSUE TITLE
Staged Rollout of Appoint a Representative 1.0

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#92158]
## Staged Rollout Schedule

[Release plan:](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/appoint-a-representative/release-plan-appoint-a-representative-1.0.md) 

- Stage A: 5% of users on 1/8 (Wednesday) + implement Datadog monitoring in Production https://github.com/department-of-veterans-affairs/va.gov-team/issues/92287
- Stage B: 50% of users on 1/13 (Monday)
- Stage C: 100% of users on 1/21 (Tuesday) + launch best bets for an initial boost to visibility + publish entry points

Dependency: 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/96246

## Tasks

- [x] Stage A: Enable the feature toggle for 5% of users ~and test users: kcschneid@yahoo.com and samuel.raudabaugh@va.gov~
- [x] Log metrics for Stage A in the release plan
- [x] Stage B: Enable the feature toggle for 50% of users -- pair with Kevin Schneider
- [x] Log metrics for Stage B in the release plan
- [x] Stage C: Enable the feature toggle for 100% of users

## Acceptance Criteria
- [x] Appoint a Representative is live on VA.gov for all users!
- [x] CAIA has been alerted to: remove the react widget from the landing page, add entry points, and implement best bets.

**Comment by oddball-lindsay** [comment]
We had some issues providing access to individual users. [Opened a support ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/100493) and [chatted with the support team in Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1736357161986949). Their recommendation is:

>  If you still need the behavior for both authenticated and un-authenticated users, you'll have to create two separate features toggles for this. We don't currently have the capability to create multiple actor types for a single feature.

I'm curious about the level of effort here. Jen's biggest concern is just confirming things won't break, which we confirmed earlier by accessing that 5% in Production. I'm still keeping that incognito browser window open lol.

**Comment by oddball-lindsay** [comment]
We could schedule a meeting with Kevin and Sam when we go to 50%.

**Comment by oddball-lindsay** [comment]
Placing this in blocked, would like to address this first:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101149

**Comment by oddball-lindsay** [comment]
We made it to 100%! Requested support from CAIA: https://dsva.slack.com/archives/C01K37HRUAH/p1737656773379539?thread_ts=1737468588.157319&cid=C01K37HRUAH
