### ISSUE TITLE
[Backend] Create Endpoint for Debt Letter VBMS PDF Downloads

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#9215]
## User Story or Problem Statement
An endpoint needs to be created to allow veterans to download PDF copies of their debt letters.

## Goal
Endpoint added that allows downloading of PDF debt letters.

## Objectives or Key Results this is meant to further
Part of the requirements of the debt letters MVP.

## Tasks
- [ ] Modify routes.rb to add the new route
- [ ] Add method to debt letters controller
- [ ] Add tests for the endpoint
- [ ] Update swagger documentation for the endpoint

## Acceptance Criteria
- [ ] Endpoint is available, and letters can be downloaded by the veteran.
