### ISSUE TITLE
E2E Tests for Appoint a Representative MVP

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#92156]
## Background
E2E testing for Appoint a Representative MVP, as we prepare for Staging Review.

[E2E Test Participation](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation):

> VFS teams should create at least one Cypress test spec in a tests/e2e folder in your product’s directory that follows the conventions described in the Writing an end-to-end test document. See End-to-end testing with Cypress for more information about writing Cypress tests on the platform.

## User flows to test
Must
1. Authenticated Veteran selects VSO rep with multiple organizations (21-22), "yes to some" for medical authorization and "yes" for address authorization.
2. Unauthenticated non-Veteran (21-22a), "yes" for all authorizations.

Nice to have (re-evaluate if we should do these, after the "must" scenarios)
1. Authenticated non-Veteran selects VSO rep with only one organization (21-22), "yes to some" for medical authorization and "yes" for address authorization.
2. Authenticated Veteran selects an organization (21-22), "no" for all authorizations.
3. Unauthenticated non-Veteran (21-22a), "no" for all authorizations.

## Tasks
- [ ] Write E2E test for Appoint a Representative (see above for the "Must" user flows to test)
- [ ] Share a link to our product's code in the comments, so Lindsay can include in the Staging Review request

## Acceptance Criteria
- [ ] End to end tests have been written for Appoint a Representative MVP (all paths?)
- [ ] All tests passing with adequate coverage

**Comment by oddball-lindsay** [comment]
@oddball-lindsay think about user flows for e2e testing

**Comment by oddball-lindsay** [comment]
Here's what I'm putting in our Staging Review request - thanks @cosu419!


> E2E tests
> https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/representative-appoint/tests/e2e
> 
> Code coverage
> https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/representative-appoint
> Run this command to see our code coverage for Appoint a Representative yarn test:coverage-app representative-appoint
