### ISSUE TITLE
Create React Widget for Landing Page Dynamic Content (Appoint a Rep)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#92160]
## Background
Our Appoint a Representative tool will be accessed through our landing page -- https://www.va.gov/get-help-from-accredited-representative/.

When we do our staged rollout, we will need to create a React widget that is connected to our `appoint_a_representative_enable_frontend` feature toggle.  And, based on the feature toggle state, the old vs. new landing page content will appear.

## Implementation Notes

CAIA will place the React widget on the landing page before we being our staged rollout, and we'll control visibility for the different stages through the feature toggle.  When we're ready to serve our product to 100% of users, then CAIA will replace the React widget with the new content for all to see.
- "Display 1: Modern tool" = feature toggle on (new experience connected to our staged rollout)
- "Display 2: Legacy forms" = feature toggle off (old experience we're moving away from)

The full process is detailed in this CAIA document: [Dynamic content in Drupal: Implementation and removal process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md#dynamic-content-in-drupal-implementation-and-removal-process)
And we have some learnings from when we did this once before in the Find release: https://github.com/department-of-veterans-affairs/va.gov-team/issues/69866

## Dynamic Content

"Display 1: Modern tool" = feature toggle on (new experience connected to our staged rollout)
```
Use our online tool to fill out your form.

[Secondary action link] Fill out your form online

If you don’t want to use our online tool to fill out your form, you can fill out one of the PDF forms listed here. The form you’ll need to fill out depends on the type of accredited representative you’re appointing.
```

"Display 2: Legacy forms" = feature toggle off (old experience we're moving away from)
```
Fill out one of the PDF forms listed here. The form you'll need to fill out depends on the type of accredited representative you’re appointing.
```

[Landing page source of truth can be viewed here](https://dvagov.sharepoint.com/:w:/r/sites/SitewideCAIA/_layouts/15/Doc.aspx?sourcedoc=%7B3B1F99D3-9EBA-4107-8778-D1095CEBF263%7D&file=3.%20ARM%20AAR%20V1%20landing%20page%20content.docx&action=default&mobileredirect=true).
<details> <summary> Screenshot </summary>

![Image](https://github.com/user-attachments/assets/8d861583-8615-4801-8aba-c331bce35af0)

</details>

## Tasks
- [ ] Create a react widget that can dynamically display current and new landing page content
- [ ] Share the widget with CAIA (ideally the week of 12/9) so they can implement it on their landing page 
- [ ] Meet with CAIA (A and Megan) to test and copyedit the react widget -- there is currently a meeting scheduled for this, on 12/17 from 10:30-11 am ET
- [ ] Connect react widget to Appoint a Representative frontend feature toggle

## Acceptance Criteria
- [ ] A react widget with CAIA-approved content has been added to the Appoint a Representative frontend feature toggle

**Comment by oddball-lindsay** [comment]
CAIA is tracking their portion of the work leading up to release in this ticket: https://mail.google.com/mail/u/0/#inbox/FMfcgzQXKWkpCqJRJzGCLjRDPGbPLmJJ
