### ISSUE TITLE
Publish FOIA Request Instructions

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#92175]
## Problem Statement
Platform Support team has been receiving FOIA request submissions via the Slack #vfs-platform-support channel, but the team is not responsible for handling these requests, and this slows down a time-sensitive process.

## Issue Description
VFS Teams need concise information on how to submit FOIA requests directly to OCTO, and this info should be posted in a location on Platform Website where VFS team members are likely to look. Platform Support PM agrees it should be posted on the landing page in the Support space on the website.

### Approved Instructions (Andrea Hewitt, Johnathan Kamens):
 - https://vfs.atlassian.net/wiki/spaces/PWD/pages/3411345451/Freedom+of+Information+Act+FOIA+requests

### Proposed location in IA for publishing:
<img width="960" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0d6Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b7631bbb434eb40034b106656c3846ac1a00af0/image.png" alt="image.png" />

---
## Tasks
- [x] Add Introduction at top of page
- [x] Add mention of needing PIV card in instructions
- [x] Add titles/roles to Kasey & Michelle's names
- [x] Add justification for notifying Kasey & Michelle in instructions
- [x] Add Feedback Footer
- [x] Fix any typos
- [x] Add Date Stamp
- [x] Check for Launch Blocking Issues
- [x] Publish the Approved Instructions above in proposed location in IA

## Acceptance Criteria
- [x] New Page is ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/92175?planning-poker) with Zenhub @BSmolensky @cmarion93 @laucon @taylojill

**Comment by BSmolensky** [comment]
As per our discussion during -- I think it was sprint planing -- the approved instructions still need a copy edit. There are punctuation issues, grammatical errors, no intro, and no footer. @jknipes - would it be possible to add four additional steps to the Task list? 

1. Add Intro
2. Add Footer
3. Fix typos
4. Check for Launch Blocking Issues

**Comment by BSmolensky** [comment]
@jknipes - Thanks for the quick update!

**Comment by BSmolensky** [comment]
Second Additional Note for whomever works on this ticket: We MUST include language about the use of Sharepoint. This was something that @taylojill brought up in the meeting about this page. We do not usually link to Sharepoint.

**Comment by jknipes** [comment]
Add a general source (Slack channel) to reach out to if Communications Leads are not available

**Comment by taylojill** [comment]
All tasks completed, checked for blockers, ready to publish.

**Comment by jknipes** [comment]
This ticket was pulled into this sprint due to available capacity and because of the important nature of the information, which needs to be available on Platform Website
