### ISSUE TITLE
HLR | Implement SME content suggestions

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#92170]
## Value Statement

**_As a_** Veteran

**_I want to_** submit the most up-to-date Higher Level Review form

**_So that_** I won't be at risk of having the form returned to me for using an expired form

---

## Background Context

The HLR paper form was updated April 30, 2024. Updates are mostly within instructions and content of the form to simplify and adapt more plain language.

Stakeholders came back with suggestions and feedback since updates were initially implemented. We want to incorporate this feedback before release.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] _New content updates to HLR form have been implemented_

## Designs and Build Notes
[FIGMA](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=0-1)

### Enablement team (if needed)
@jstrothman 

## Out of scope

- Add here

## Open questions

- Is the homelessness required for Lighthouse? We need to make that question optional.

## Tasks

- [x] Update content on Information page ([Spec](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=560-16887&m=dev))
- [x] Update content in homelessness question ([Spec](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=163-29654&m=dev))
- [x] Update issues for review ([Spec](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=586-32814&m=dev))
- [x] Update content on the Request an informal conference page ([Spec](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=586-32815&m=dev))
- [x] Update content on the Confirmation page [[Spec]](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=782-41892&t=t91H6aweTTsj4lkx-11) (does not need to be behind a feature flag)

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Work completed, but may not be available in staging right away

**Comment by eileen-coforma** [comment]
This is my bad. One minor change to the homelessness question. Remove the hint text altogether. I'm making a decision today to proceed without hint text.

**Comment by eileen-coforma** [comment]
I added a few more change requests from CAIA and VBA, which Robin's been working on:

Homelessness question
- Changed to optional, on the backend, we'll select no in order to meet LH requirements
- Remove hint text

Withdrawal from the legacy appeals process
- Add an H4 and a sentence to the paragraph about SOC and SSOCs

Confirmation page
- Remove "Need Help" component, because it's redundant information (contact info is already on the page)

**Comment by eileen-coforma** [comment]
@eileen-coforma to validate

**Comment by eileen-coforma** [comment]
@eileen-coforma to review new CAIA recommendation and add comment for Robin

**Comment by eileen-coforma** [comment]
@Mottie 
Caught some things in Validation.
<img width="824" alt="Screenshot 2024-09-19 at 2 14 55 PM" src="https://github.com/user-attachments/assets/87c08ade-bb23-49e2-82ef-9ddad70f11c4">
Intro paragraph is somehow shifted behind the action link. Is that intentional?

 
<img width="643" alt="Screenshot 2024-09-19 at 2 28 06 PM" src="https://github.com/user-attachments/assets/77c34972-d525-469b-9f39-c55068ff4d07">

Missing a sentence in the intro of [this page](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=757-40002&node-type=frame&t=yuwvlJ1n9mmyI2Kb-11)

"If you request an informal conference, it may take us longer to make a decision on your Higher-Level Review."

<img width="559" alt="Screenshot 2024-09-19 at 2 28 36 PM" src="https://github.com/user-attachments/assets/e0c1aedc-53f8-4016-8dbc-71eb43a274c2">

Use the new external window component (for consistency) on [this page](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=757-40649&node-type=frame&t=yuwvlJ1n9mmyI2Kb-11)

**Comment by eileen-coforma** [comment]
@Mottie I think this earlier comment got lost: https://github.com/department-of-veterans-affairs/va.gov-team/issues/92170#issuecomment-2361831025

It's the same language as SC
