### ISSUE TITLE
[Backend] Add Get Debt Letters from VBMS Method to Debt Letters Service

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#9217]
## User Story or Problem Statement
A method needs to be added the debt letters service that allows a veteran to download a particular debt letter.

## Goal
Method has been added to the service that allows a veteran to download a particular debt letter.

## Objectives or Key Results this is meant to further
Allows veterans to download debt letters.

## Tasks
- [ ] Add service method to download debt letters
- [ ] Update service related tests

## Acceptance Criteria
- [ ] A method will be added to the debt letters/DMC service that will allow veterans to download debt letters.

**Comment by leahkeeler** [comment]
@camerontesterman - can we close this?

**Comment by leahkeeler** [comment]
Can this be closed?
