### ISSUE TITLE
[QA] 10-10EZ - Facilities: Complete End-to-end testing with VES

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#92247]
## Background
As a Veteran, I want to search for my preferred facility by postal code, so that I can see a list of results from which I can choose. 

### Resources
[Figma Phased Designs](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5131-3754&node-type=CANVAS&t=joom4n3vLUHatY2V-0)

## Tasks
- [ ] Coordinate with EZ VES QA team/Joshua Faulkner to complete End-to-End testing on new Facilities Search functionality
     - Select various facilities, including newer ones that have been added to the Facilities API (check with Mitch on those)
- [ ] Validate that the EZ supported facility information is sent to the Enrollment system
- [ ] Document any findings in the comments
- [ ] Determine if a new ticket is needed for the findings
- [ ] Review results with PM/Team (can be async)
  
## Acceptance Criteria
- The 10-10EZ Facilities search end-to-end testing is completed successfully

**Comment by hdjustice** [comment]
Closing ticket - feature descoped
