### ISSUE TITLE
[FE, BE] 10-10EZ - Facilities: Create Endpoint monitoring Playbook

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#92241]
## Background
**Endpoint Monitoring**
All endpoints that the product accesses need to be monitored in [Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-applications-and-infrastructure-with-datad). Monitors should be configured according to the guidance in [this document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/playbooks/endpoint-monitoring.md). To satisfy this standard, VFS teams must complete a [playbook](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/playbooks/template.md) that details how they will respond to any errors that fire.
This is a launch-blocking standard, meaning teams MUST have alerts set up in Datadog, and teams MUST submit their playbook.
Enforcement of this QA standard will begin this upcoming Tuesday September 10, and will be enforced immediately at Staging Review.
This standard is intended to help us get to Zero Silent Failures (silent to the Veteran) across the entire platform. 

## Tasks
- [ ] Review existing Datadog monitors
- [ ] Determine if new monitors are needed for any endpoints we don't currently monitor
- [ ] Create those monitors (if needed)
- [ ] Create Playbook, using the template and our current team procedures ([runbook](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/application/1010EZR-Runbook.md#10-10ezr-production-runbook), [EZ monitors & alerts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/Existing%20Monitors%20and%20Alerts.md))
- [ ] Review with PM to satisfy Collab Cycle requirement prior to Staging review

## Acceptance Criteria
- All endpoints have monitors and the playbook is complete
