### ISSUE TITLE
[CST] Update tracked item name for 5103 in Recent Activity

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#92258]
## Background Context

We need to update the name of the 5103 tracked item in Recent Activity. 

e.g. We opened a request for "Review evidence list (5103 notice)"

<img width="840" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkcwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08a7340592e5e2a7fb2b380ffe262a922716093d/Screenshot%202024-09-05%20at%203.08.55%E2%80%AFPM.png" alt="Screenshot 2024-09-05 at 3.08.55 PM.png" />

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
[FIGMA](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=3844-11137&t=KvEVrrU3LrN0DTX2-4)

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
Note: Standard 5103s will not show up in Recent Activity until they are closed, due to the nature of that tracked item type. That is OK. We should still update the name for both Standard and Custom 5103s.

## Tasks
- [ ] _Update language in Recent Activity updates for Automated 5103 Notice and 5103 Evidence Notice (Custom and Standard) tracked items_
- [ ] _Update language for all statuses represnted in Recent Activity section for these tracked items (see all statuses [here](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST---V2-(Evidence-Submission)?node-id=966-7080&t=w4g57QiLyKasgUA1-4)_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Updates related to Standard 5103 and Custom 5103 tracked items in Recent Activity match the spec in terms of how they reference the 5103_
- [ ] _AC_
- [ ] _AC_

**Comment by skylerschain** [comment]
LGTM 👍 

![Image](https://github.com/user-attachments/assets/fbec5980-148c-4cad-a17a-e735e68c3c36)
