### ISSUE TITLE
POST LAUNCH - Add Flag for Living on Military Base to Pre-Fill Data

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#9225]
`Consider doing this after first version launch`

## Background
The data returned by our prefill endpoint does not include any data about if the vet lives on a military a base however our form includes a specific checkbox for living on a military base and extra fields pertaining to the military base. This means that when an address is prefilled and it is a military base it will not trigger the checkbox nor the extra fields to show up. We need to send a specific piece of data mapped to the correct field on the front end as to if the user is at a military base or not as well as data for the added fields.

## Goal 
We could automate the pre-fill for those Veterans that are living on a base because as of now, it does not select that box.

## Considerations
- Have a small team chat about this before work commences
- This may be an issue in that vet360 (or where ever pre-fill data comes from), where we are getting the prefill data from, might not have this military address/ non-military address data and if that is the case we may need to add logic to the back end prefill to send this data in the prefill object returned. 
- Ask Lihan if there is a way to do dynamic pre-fill like this might need to check for the box
  - Can we pre-fill other military base data?

## Tasks
- [ ] Adjust the incoming fields to affect the military box and have that in place for the Veteran.

## Acceptance Criteria
- [ ] When a Veteran that is living on a base logs in to the 686, they should have that box checked
- [ ] A PR has been requested for merging

**Comment by jason-gcio** [comment]
Need more info on Pre-fill to make this more effective

**Comment by jason-gcio** [comment]
Checking with Auth Exp on how far the pre-fill might go

**Comment by jason-gcio** [comment]
juice might not be worth the squeeze
