### ISSUE TITLE
[SC]: Accessibility testing of research prototype

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#92283]
## Value Statement

**_As a_** Veteran participating in the Supplemental Claims Form Updates research

**_I want to_** navigate the Supplemental Claims Form prototype without issues

**_So that_** I can provide feedback to the Decision Reviews team.
---

## Background Context

- [Prototype in staging](https://staging.va.gov/decision-reviews/test-sc/introduction)
- An accessibility audit needs to be conducted to ensure the prototype works well with screen readers, etc.

## Outcome, Success Measure, KPI(S), and Tracking Link

- N/A

## Acceptance Criteria

- [x] Accessibility testing is complete by accessibility specialist
- [x] Any feedback is relayed via ticket for engineers

## Designs and Build Notes

- N/A

### Enablement team (if needed)

N/A

## Out of scope

- N/A

## Open questions

- N/A

## Tasks

- [x] Audit complete
- [x] Tickets filed

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by davidakennedy** [comment]
I've completed testing of the prototype over the last two days. Here are some details on what I found:

- I found only one issue that would affect screen readers negatively. That's #92621.
- I found similar issues to what I've filed previous in the design system, with https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3225 and https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3226.
- I also experienced #72521, which is a known issue that's really a problem with VoiceOver.

@Mottie knows about the one known issue. Testing is complete.
