### ISSUE TITLE
Improve organization of 526 research documentation

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#92282]
## Issue Description
Team members, OCTO, and VBA stakeholders need an easy way to search and access past research completed on the 526ez. Currently, documentation for research studies live in Github, but other sources float around Drive, Mural, Google Docs, and Sharepoint, without sufficient structure. 

**Impact:** Once these documents are organized, everyone will have access to research and a better understanding of the Veteran experience filing for disability. 

---
## Tasks
- [X] Identify and gather documentation (research reports, decks from readouts, journey maps, and any related artifacts)
- [X] Pick centralized platform (Google Drive, Sharepoint, and Github all seem like viable options)
- [ ] Ask stakeholders for preference to make sure it is a useful resource
- [X] Create logical structure for documentation, including naming conventions 
- [X] Develop a protocol to keep the repository updated and maintained
- [X] Clean up other partial records so there is one clear source of truth for up-to-date info

## Acceptance Criteria
- [X] [Github quick-links 526 page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/quick-links.md) is updated
- [X] All UX research documentation is gathered and uploaded to the centralized platform.
- [X] Access permissions are correctly set up for all relevant parties.
- [X] A maintenance plan is in place for updating and managing the repository. **I am the only one doing it, I will just be sure to add new studies. **
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by evelynhilbrichdavis** [comment]
Google Drive would be a place for OCTO to review and hash things out, not a place for things to live long term. Ultimately all documentation should be in Github in a format that VA owns. 
@mengA6 to follow up and confirm on use case for Sharepoint.

**Comment by evelynhilbrichdavis** [comment]
- Google drive has been set up for internal organization of archived documents. This will serve new and existing team members.
- Meeting with Conditions Team tomorrow; they recently reorganized their Drive so I want to learn quickly what worked well
