### ISSUE TITLE
Non-Veteran Claimants: Do not require a Veteran phone number

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#92286]
## Background
While forms on VA.gov require a Veteran phone number, our stakeholders are concerned that this is not realistic in cases where a survivor is seeking representation and the deceased Veteran would not have a phone number.

While phone numbers are not a required form field, obtaining a phone number can be helpful for the representative to contact the Veteran if there are issues with their POA request, or even with accepting the request. The team has decided to proceed with this logic for the `/appoint-rep/veteran-contact-phone-email` page:

1. If it's the **Veteran** filling out the form, require Veteran phone number (so rep can contact Veteran)
2. If it's the **non-Veteran** filling out the form, require Claimant phone number (so rep can contact the non-Veteran claimant) but do not require Veteran phone number as there may be cases where a Veteran is deceased.

## Tasks
- [ ] Implement logic above for the `/appoint-rep/veteran-contact-phone-email` page
- [ ] Update unit tests?

## Acceptance Criteria
- [ ] Veteran phone number is only required when Veterans are completing the form

**Comment by holdenhinkle** [comment]
Done
