### ISSUE TITLE
Remove Virtus

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#92296]
## Summary

The gem [virtus](https://github.com/solnic/virtus) is discontinued and should be removed. Currently 130 classes use `Virtus.model`

## Tasks

- [ ] Review alternative solutions (such as [dry-struct](https://github.com/dry-rb/dry-struct))
- [ ] Review & Identify duplication in Virtus models 
- [ ] Create tickets to remove/replace Virtus models 

## Acceptance Criteria

- [ ] `virtus` gem is removed from Gemfile
