### ISSUE TITLE
Update broken CDC links on translated About COVID-19 vaccines pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#92330]
> [!WARNING]
> Do not use this ticket unless directed to do so by the CAIA team.

## Issue description
We have several broken links on our [About COVID-19 vaccines](https://www.va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine/) in Spanish and Tagalog that are specific to the CDC. We recently updated the English page and we need to now update the links in the Spanish and Tagalog pages as well. 

When we fix the broken links we'll want to make sure we're linking to a Spanish/Tagalog CDC page if available. If the links are only in English we'll need to add (in English) to the end of each link. 

## Tasks

- [x] Update links on Spanish page (Victoria)
- [x] Update links on Tagalog page (Victoria)
- [x] Review Spanish page (Megan/Sara) 
- [x] Review Tagalog page (Megan/Sara)
- [x] Publish Spanish page (Megan/Sara)
- [x] Publish Tagalog page (Megan/Sara)

## Acceptance Criteria
- [x] Links are working on live Spanish page
- [x] Links are working on live Tagalog page

## Configure this issue
- [ ] _Attach to an Epic (what body of work is this a part of?)_
- [ ] _Label with Originator/Team (product team or stakeholder requesting support)_
- [ ] _Label with Open Date_
- [ ] _Label with Estimate (level of effort expected for this ticket)_
- [ ] _Add assignee name to each task they will complete (if known)_

**Comment by moviedosoco** [comment]
@RLHecht Reviewing and creating a Word doc with all the Spanish and Tagalog links before updating the pages in Drupal.

**Comment by moviedosoco** [comment]
Hi @megzehn, the links on the Spanish page are updated and ready to be reviewed and published: https://preview-prod.vfs.va.gov/preview?nodeId=36461

**Comment by moviedosoco** [comment]
@megzehn The links on the Tagalog page are updated and ready to be reviewed and published:
https://preview-prod.vfs.va.gov/preview?nodeId=36427

**Comment by megzehn** [comment]
Thank you @moviedosoco! Confirming I reviewed the links and both of these pages are published.

**Comment by moviedosoco** [comment]
@megzehn Thank you! 
@RLHecht The tasks and acceptance criteria have been completed, so we can close this ticket out.
