### ISSUE TITLE
Move New Docs to Analytics Deployment Space

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#92334]
## Issue Description
Analytics Team unable to move new documents regarding GA4 Instructions into the A&I deployment space for publishing. We need to assist so the Analytics team can make sure VFS Teams have information about the new metrics tool.

---
## Tasks
- [x] Contact Analytics PM Johnny Jasinsky
- [x] Solve issue
- [x] Move pages into deployment space

## Acceptance Criteria
- [x] New documents are ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
This ticket created due to available capacity and urgency of the work

**Comment by taylojill** [comment]
Huddled with Johnny and solved issue by making a copy of the page and then moving it to the space for publishing. Page checked for blockers, ready to publish.
