### ISSUE TITLE
Edit: Partner Services - MPI

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#92332]
## Issue Description
The table on [Partner Services (Upstream Services)](https://depo-platform-documentation.scrollhelp.site/developer-docs/partner-services-upstream-services), contains many broken links.
The page is presently of limited use to VFS Teams.
We need to work with the Platform Product team to make sure all broken links are replaced with links to live pages.

**We will make corrections in increments, per ticket, and deploy as-is daily.**

This ticket is for work on the **MPI links**
 1. MPI- outage- This link leads to a GitHub page that says “File not Found”
 2. MPI-Contacts - This link leads to a GitHub page that says “File not Found”
 3. MPI - monitoring- This link leads to a page that says "server not found".
---
## Tasks

- [x] Copy page into Drafts Space
- [x] Contact SME on Product Team - Ryan Johnson
- [x] Fix each link to go to the correct live page (not Confluence, not Google drive)
- [x] Replace link emojis with name of destination page
- [x] Save the changes and test each link
- [x] Prepare for deployment -  IGNORE all subsequent link issues

## People/SMEs

- Jennifer Brown and Platform Product team

## Slack thread
See [this slack thread](https://dsva.slack.com/archives/CL181NRJQ/p1724865276408069).

## Acceptance Criteria
- [x] Links are fixed
- [x] Page is ready for deployment

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/92332?planning-poker) with Zenhub @BSmolensky @cmarion93 @taylojill

**Comment by taylojill** [comment]
Message sent to Ryan Johnson via Slack platform-content channel.

**Comment by taylojill** [comment]
Feedback received, changes made to page in draft space.

**Comment by jknipes** [comment]
work is complete, moving to _Done_
