### ISSUE TITLE
Edit: Partner Services - Appeals

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#92333]
## Issue Description
The table on [Partner Services (Upstream Services)](https://depo-platform-documentation.scrollhelp.site/developer-docs/partner-services-upstream-services), contains many broken links.
The page is presently of limited use to VFS Teams.
We need to work with the Platform Product team to make sure all broken links are replaced with links to live pages.

**We will make corrections in increments, per ticket, and deploy as-is daily.**

This ticket is for work on the **Appeals links**

1. Appeals-outage- This link leads to a page that says "server not found".
2. Appeals-Monitoring - This link leads to a page that "says server not found".

---
## Tasks

- [x] Copy page into Drafts Space
- [x] Contact SME on Product Team - Ryan Johnson
- [x] Fix each link to go to the correct live page (not Confluence, not Google drive)
- [x] Replace link emojis with name of destination page
- [x] Save the changes and test each link
- [x] Prepare for deployment  - IGNORE all subsequent link issues

## People/SMEs

- Ryan Johnson - Platform Product team

## Slack thread
See [this slack thread](https://dsva.slack.com/archives/CL181NRJQ/p1724865276408069).

## Acceptance Criteria
- [ ] Links are fixed
- [ ] Page is ready for deployment

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/92333?planning-poker) with Zenhub @BSmolensky @cmarion93 @taylojill
