### ISSUE TITLE
Edit: Partner Services - Central Mail

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#92345]
## Issue Description
The table on [Partner Services (Upstream Services)](https://depo-platform-documentation.scrollhelp.site/developer-docs/partner-services-upstream-services), contains many broken links.
The page is presently of limited use to VFS Teams.
We need to work with the Platform Product team to make sure all broken links are replaced with links to live pages.

**We will make corrections in increments, per ticket, and deploy as-is daily.**

This ticket is for work on the **Central Mail**

1. Central mail - monitoring- server not found
2. Central Mail - VFT docs- This leads to a Platform document that technically exists but says at the top “This API has been deprecated. Please use the Benefits Intake API.”

---
## Tasks

- [x] Copy page into Drafts Space
- [x] Contact SME on Product Team - Ryan Johnson
- [x] Fix each link to go to the correct live page (not Confluence, not Google drive)
- [x] Replace link emojis with name of destination page
- [x] Save the changes and test each link
- [x] Prepare for deployment -  IGNORE all subsequent link issues

## People/SMEs

- Ryan Johnson - Platform Product team

## Slack thread
See [this slack thread](https://dsva.slack.com/archives/CL181NRJQ/p1724865276408069).

## Acceptance Criteria
- [ ] Links are fixed
- [ ] Page is ready for deployment

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/92345?planning-poker) with Zenhub @BSmolensky @cmarion93 @taylojill

**Comment by BSmolensky** [comment]
This is another one where we should ignore all the other broken links when we "prepare for deployment"...right?
