### ISSUE TITLE
Update Coronavirus language

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9234]
## Problem Statement

How might we give Veterans the most relevant and accurate facility operating status information?

---
## Tasks
- [ ] Update alert language from **old Coronavirus update:**

> For answers to questions about how COVID-19 may affect your VA health appointments, benefits, and services, use our VA coronavirus chatbot . Many VA and community provider locations have changing hours and services due to COVID-19. For your safety, please call before visiting any location to ask about getting help by phone or video.

**to New Coronavirus update:**

> For questions about how COVID-19 may affect your health appointments, benefits,
> and services, use our [coronavirus chatbot](https://www.va.gov/coronavirus-chatbot/). Many locations have changing hours and services. For your safety, please call before visiting to ask about getting help by phone or video. We require everyone entering a VA facility to wear a cloth face covering. [Learn more about this requirement](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/)

- [ ] Include https://www.va.gov/coronavirus-chatbot/ for chatbot link
- [ ] Include https://www.va.gov/coronavirus-veteran-frequently-asked-questions/ for "Learn more about this requirement"

## Acceptance Criteria
- [ ] Facility Locator now displays new language above the search boxes and 
- [ ] Veteran can visit chatbot 
- [ ] Veteran can visit coronavirus FAQ
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
@mmiddaugh @brangi  here's the updated language!

[https://app.zenhub.com/files/133843125/89171242-66e6-4b64-84ae-aef67c424dbb/download](https://app.zenhub.com/files/133843125/89171242-66e6-4b64-84ae-aef67c424dbb/download)
