### ISSUE TITLE
Edit: Partner Services - eMis

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#92348]
## Issue Description
The table on [Partner Services (Upstream Services)](https://depo-platform-documentation.scrollhelp.site/developer-docs/partner-services-upstream-services), contains many broken links.
The page is presently of limited use to VFS Teams.
We need to work with the Platform Product team to make sure all broken links are replaced with links to live pages.

**We will make corrections in increments, per ticket, and deploy as-is daily.**

---

This ticket is for work on the **eMis** links

1. **eMIS - VFT docs**- This leads to [an archived Confluence document](https://vfs.atlassian.net/wiki/spaces/CIT/pages/1887174669/EMIS) that says at the top “THIS PAGE WAS ARCHIVED ON 2/15/24 - Loki, Grafana, and Prometheus have been sunsetted and replaced by Datadog. This page contains only information about affected programs and DOES NOT contain any additional information that people need. As a result, this page was not edited and kept on the Platform Website. Instead, it was archived. For more information about Datadog, contact #dots-dsva.”
2. **eMIS - devops docs**- This also leads to [the archived Confluence document page ](https://vfs.atlassian.net/wiki/spaces/CIT/pages/1887174669/EMIS)

---
## Tasks

- [x] Copy page into Drafts Space
- [x] [PER THIS COMMENT](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92348#issuecomment-2341834159), REMOVE THE ROW IN THE TABLE
- [x] Save the changes  
- [x] Prepare page for deployment - IGNORE all subsequent link issues

## People/SMEs

- Jennifer Brown and Platform Product team

## Slack thread
See [this slack thread](https://dsva.slack.com/archives/CL181NRJQ/p1724865276408069).

## Acceptance Criteria
- [x] Links are fixed
- [x] Page is ready for deployment

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/92348?planning-poker) with Zenhub @BSmolensky @taylojill @cmarion93

**Comment by BSmolensky** [comment]
Hey @jknipes - I think it would be helpful if the TASK lists section got a quick update. Given that we are deploying this page each day after the small changes are made, I am not sure that we need "Prepare for deployment." Or, if you want to keep it, maybe add a note after it reminding us that we should ignore all subsequent link issues...? Just a thought.

**Comment by jknipes** [comment]
Per @jennb33 and @LindseySaari the row in this table eMis can simply be removed:
![image](https://github.com/user-attachments/assets/5578159f-50c3-4111-b5f2-2fec0472a9e1)

**Comment by jknipes** [comment]
Tasks are complete, AC has been met, moving to _Closed_
