### ISSUE TITLE
Update digital submission designs with research recommendations + ARP expectations

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#92341]
## Background
We recently ran a study with cross-accredited VSO Representatives, and have recommendations on how to improve our designs around digital submission, which include both Find v3 and Appoint v2. The share-out is scheduled for **Monday 9/23**.

The ARF team has also been working through what contact information they might add via the Accredited Rep Portal. We can also explore meeting the ARP contact information inputs in the Find a Rep detail page.

## Tasks
- [x] Update Find v3 designs based on research recommendations and ARP expectations
- [x] Request CAIA support for research findings that are content related
- [x] Update Appoint v2 designs based on content recommendations
- [x] Update Widget v2 designs based on content recommendations
- [x] Share design updates with the team
- [x] Update designs based on any team input
- [x] Confirm the team is good with the updates

## Acceptance Criteria
- [x] Designs are updated based on research/content recommendations and ARP expectations.
- [x] We are ready to schedule a second Midpoint Review.

**Comment by oddball-lindsay** [comment]
All of the research findings are related to content -- updated the task list above to reflect that.

We'll join CAIA OH next Tues 10/1 to ask for help on the content updates.

From there, we can implement that content then be ready for a second Midpoint Review.

**Comment by oddball-lindsay** [comment]
@mtri let me know when you're feeling good about everything and I can get started on #93831

**Comment by mtri** [comment]
@oddball-lindsay All set! Thanks!
