### ISSUE TITLE
Edit: Partner Services - MHV, Search.gov

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#92346]
## Issue Description
The table on [Partner Services (Upstream Services)](https://depo-platform-documentation.scrollhelp.site/developer-docs/partner-services-upstream-services), contains many broken links.
The page is presently of limited use to VFS Teams.
We need to work with the Platform Product team to make sure all broken links are replaced with links to live pages.

**We will make corrections in increments, per ticket, and deploy as-is daily.**

This ticket is for work on the **MHV and Search.gov** links

1. MHV - monitoring- server not found
2. Search.gov- monitoring- server not found

---
## Tasks

- [x] Copy page into Drafts Space
- [x] Contact SME on Product Team - Ryan Johnson
- [x] Fix each link to go to the correct live page (not Confluence, not Google drive)
- [x] Replace link emojis with name of destination page
- [x] Save the changes and test each link
- [x] Prepare for deployment - IGNORE all subsequent link issues

## People/SMEs

- Ryan Johnson (Platform Product team)

## Slack thread
See [this slack thread](https://dsva.slack.com/archives/CL181NRJQ/p1724865276408069).

## Acceptance Criteria
- [x] Links are fixed
- [x] Page is ready for deployment

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/92346?planning-poker) with Zenhub @BSmolensky @taylojill @cmarion93

**Comment by BSmolensky** [comment]
@jknipes - same note as the other ticket in this series. Thank you.

**Comment by BSmolensky** [comment]
@jknipes - I have several questions regarding the work on this ticket. 

- For both the the links highlighted in the description above, the ticket says that these are "server not found"issues. I am not getting a "server not found" notice. The links in question appear to be Grafana links. 
-- Grafana requires SOCKS Proxy but Grafana has been partially sunset and most of it has been replaced by Datadog.
-- Should we just add the "SOCKS Proxy required" language to the links or do we need to find the corresponding Datadog link?
- The instructions say to  "Replace link emojis with name of destination page." But it is unclear if these instructions apply only to the TWO links we are fixing or if we should replace all the link emojis in the two ROWS
-- There are 5 links in the MHV row and 5 links in the Search(dot)gov row. 

I will wait to hear back from you before contacing the SME.

**Comment by BSmolensky** [comment]
SME Contacted via Slack. Waiting response.

**Comment by BSmolensky** [comment]
Update is Blocked for now. SME is getting a SOCKS error. This is part of a larger problem. https://dsva.slack.com/archives/CBU0KDSB1/p1726493303110399 - Will circle back later this week to check on status.

**Comment by BSmolensky** [comment]
Block removed. SME verified that Grafana links need to be updated to datadog links. SME will provide new links. Waiting for SMEs update.

**Comment by jennb33** [comment]
9/16/2024 update: Ryan is working with Brian Smolinsky to complete this work.

**Comment by BSmolensky** [comment]
SME supplied new Datadog Links. Will update page later today.

**Comment by BSmolensky** [comment]
Thank you for the quick replies and super fast assistance @rjohnson2011 !!!

**Comment by BSmolensky** [comment]
Page Updated. Ready to deploy. Should be deployed this afternoon. Ticket is ready to close.

**Comment by jennb33** [comment]
Closing ticket, thank you @BSmolensky and @rjohnson2011 for your quick, efficient work!
