### ISSUE TITLE
Sept 2024 Metrics

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#92351]
## Background
Time to pull monthly metrics for Sept 2024.

## Tasks
- [x] Add GA4 metrics for Sept to the [GSheet](https://docs.google.com/spreadsheets/d/16Tr3nVdRHTteverx5yoBoBV32s0wvUrtW4-Daoi4hEE/edit?gid=458272975#gid=458272975)
- [x] Add Datadog metrics for Sept to the [GSheet](https://docs.google.com/spreadsheets/d/16Tr3nVdRHTteverx5yoBoBV32s0wvUrtW4-Daoi4hEE/edit?gid=458272975#gid=458272975) (Widget only)
- [x] Export the GSheet to Excel and upload to Sharepoint

## Acceptance Criteria
- [x] September analytics are in Sharepoint
