### ISSUE TITLE
Create templates to standardize monitors and dashboards

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#92368]
## User Story
As the Managers and Developers for the VA Platform, 
We need to create a template that standardizes monitor and dashboard alerts to share with the rest of the Platform teams, 
So that the Platform will become further standardized for monitor and dashboard alerts. 

## Issue Description
We need to have more consistent alerts and monitors for the VA Platform, so the team will be creating templates for standardized work on the Platform.

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Success Metrics
A standardization template for monitors and dashboard alerts will be created and shared with all other Platform and VFS teams 

## Acceptance Criteria
- [ ] There will be a template to share with all other Platform and VFS teams that will assist in standardizing how monitors and dashboard alerts are created by other teams. 
- [ ] This will contribute to OCTODE's efforts to eliminate all silent alerts
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
