### ISSUE TITLE
Facility health services content model

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9237]
## User Story or Problem Statement
How might we make harden VAMC facility health services content?

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/e5916805-f784-4fc9-8724-90aec64a646a)

## Goal
National content is not locally editable
The editorial experience for local content is efficient and low risk for usability and accessibility defects

---
## Tasks
- [ ] Identify which areas of facility health service content is national vs local
- [ ] Develop workable content model to support local and national content

## Acceptance Criteria
VAMC system editor at the local level can:

- [ ] add local content
- [ ]  view national content
- [ ]  view who can edit national content
- [ ]  cannot edit national content
- [ ]  view how and where localized content will render
- [ ]  anticipate how content changes will impact updates/deployment and blast notifications to Veterans

VHA editor at the national level can:

- [ ] view all versions of these pages from all VAMC systems in one spot (Dashboard)
- [ ]  find and interact with national detail page content
- [ ]  can bulk edit national content
- [ ]  can easily access and add a token
- [ ]  can view informational errors about tokens
- [ ]  view how and where national content will render
- [ ]  anticipate how content changes will impact update/deployment and blast notifications to Veterans

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@ethanteague, during my review of the Facility Health Services Content for Wilkes-Barre (109 listings), the following fields do not seem to be required: 
- Building or Department
- Address
- Phone extension
- Additional Phone Number(s)

NOTE:  Services appear to populate either **Building or Department** or **Address**. Only one service had populated neither one.

**Comment by mmiddaugh** [comment]
@ethanteague @davidconlon capturing feedback from demo earlier today:

- Service Offered? -> may not be necessary since the area would not be populated if the service is not available

- Editorial experience for the following should be more similar to how they appear in the front end
   - Referral Required? Y/N
   - Walk-ins Accepted? Y/N
   - Online Scheduling Available? Y/N

Questions for Stan's team:

- How many addresses are needed?
- How many extra phone numbers are needed?
- Is the second address redundant? (ie: pharmacy/pharmacy refills)
