### ISSUE TITLE
[CST] custom events for claim letter downloads

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#92394]
## Value Statement
Custom event tags on claim letter downloads will allow to easily create dashboards in GA to see download trends over time and test our bets related to claim letters and evidence requests. 

---
### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Work with Jamie Stutt to create letter download dashboard in GA that use our shortname values.

**Comment by jstrothman** [comment]
@jacobworrell  I spoke with Jamie Stutt this morning & she adjusted in Google Tag Manager so GA is now picking up the URL and link text, as originally worked on in #72444 
As structured at that time, the url tracked removes the long string that makes the urls overly long and difficult to parse.

Jamie said we should submit a [new Analytics Implementation ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+collab-cycle-review%2C+collaboration-cycle%2C+gtm&projects=&template=analytics-google-analytics-implementation-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) indicating we'd like to track friendly names. VFS Analytics would work with us to decide which parameter to use for this (e.g. in an existing parameter like File Name or in a new parameter)
As this is no longer broken (we're getting the URL) -- if we don't want to address this during this sprint, we should indicate target time in the ticket

The values to pass are in Column I of this [CST letter downloads codes and names spreadsheet (SharePoint)](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Benefits%20Management%20-%20CST/claims-letters/CST%20-%20Letter%20Download%20Codes%20and%20names.xlsx?d=w266d54b5b5db471f84bf21212761bb88&csf=1&web=1&e=PycaTA)

Here's the list for convenience (letter code(s): letter short name)

- 34, 700, 859: Specific evidence request
- 408: Exam scheduled
- 942: Evidence final notification
- 864, 1605: 3rd party records request
- 184: Claim decision or other notification
- 704, 706, 858: 5103
- 27: Appeal decision

**Comment by jstrothman** [comment]
Related #92525

**Comment by samcoforma** [comment]
@jacobworrell I think this can be closed
