### ISSUE TITLE
Edit: ESI Pages - ArcGIS.com

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#92408]
## User Stories
_"As a VFS Team member, I need to know the information on the External Service Integrations
is up-to-date and complete, so that I can build on va.gov with confidence"_

## Issue Description

The [External Service Integrations](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations) section of Platform Website contains pages with several formatting errors and missing information, as well as use of personal names. We need to edit the pages in this section.

## SME:

- (Page owner is Lindsay Hattamer)
---
### [Spreadsheet with comments for each page](https://docs.google.com/spreadsheets/d/1fmV4M-mV4wIVCPsxYzxK_c2KjsdlQaGepG1B9VwFQvE/edit?gid=0#gid=0)
---
### This ticket is for the editing of the 
[ArcGIS.com](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886814279/ArcGIS.com) page
---
## Tasks
- [ ] ~~Content team ticket assignee: Review page comments first~~
- [ ] ~~Add additional comments if necessary~~
- [ ] ~~Copy page and move copy to DRAFT Space (page **Copy** will not retain comments)~~
- [ ] ~~Review comments with SME~~
- [ ] ~~Make formatting corrections~~
- [ ] ~~With SME update information including any links~~
- [ ] ~~SME review Final Draft for accuracy~~
- [ ] ~~Prepare page for deployment~~
- [x] Check for incoming links
- [x] Archive by moving to PCT archive

## Acceptance Criteria
- [ ] ~~Updates and corrections made~~
- [ ] ~~Page is ready for deployment~~
- [x] Page has been moved to the PCT archive 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
11/5 Jason mentioned the ESI tickets might be spread to the Back End CoP as the Product team has low capacity due to OOO, Tier 2 Support duty and FOIA request.

**Comment by BSmolensky** [comment]
Moved into current sprint due to bandwidth and connection to ticket already in sprint.

**Comment by BSmolensky** [comment]
Ticket was updated and edited to reflect new goal for this page: we need to archive it. This is no longer an edit ticket it is an archive ticket. The tasks and acceptance criteria have been updated to reflect this change.

**Comment by BSmolensky** [comment]
There were no incoming links to this page from the PW. Archive is a go.

**Comment by BSmolensky** [comment]
Page moved to the PCT Archive so we can more easily reference this page during out ESI work, if necessary.

**Comment by BSmolensky** [comment]
All tasks complete. Acceptance Criteria met. Ticket is ready to close.

**Comment by jknipes** [comment]
Closing as _Done_
