### ISSUE TITLE
Design | Profile | Contact Page Revisions | Revise Expand in Military Base Addresses

### ISSUE THREAD

**Issue by twoangstroms** [department-of-veterans-affairs/va.gov-team#92409]
## Background
The AE Profile Team is working on revising interface content and affordances in the Contact page within the Profile section. **WHO TKTKTK** uncovered a handful of data quality issues PLEASE PROVIDE LINK that may be related to this. **WHAT DOES DATA QUALITY MEAN HERE?**

It is our hypothesis that the proposed changes in this and related tickets will reduce the entry errors experienced by Veterans.

This ticket is focused on the [expand section](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1724336887395/0f107c7e971dc93f275a3585cb916cc9ceea55af?wid=0-1724338473291) and will involve revising the content. No other design work is required.

### Goals/Outcomes
- Proposed text in the expand is clear
- Proposed text in the expand is shared with other teams that present the same affordance to users
- Proposed text is standardized across products
- We see reduced confusion from Veterans encountering this text

### Resources

- [Military Base Addresses](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1724336887395/0f107c7e971dc93f275a3585cb916cc9ceea55af?wid=0-1724337342688) section of the [AE Profile - Contact Information Page Revisions Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1724336887395/0f107c7e971dc93f275a3585cb916cc9ceea55af?sender=u304c8d504aa1d0ae42659303)
- [686C - Military Base Outside the U.S. Address Issues Figma file](https://www.figma.com/design/LgjF3Kf8ozrBWMjPOQEKVV/686C---Military-Base-Outside-the-U.S.-Address-Issues?node-id=0-12&node-type=CANVAS&t=rAO5ED5kTWJBT5bR-0)

### Tasks
- [ ] Proposed text is changed in relevant Figma AE files
- [ ] Sign off from relevant parties 
- [ ] FE ticket is created to make these changes

### Acceptance Criteria

**Comment by mtcA6** [comment]
@twoangstroms are you adding this to the current sprint?

**Comment by ACParker89** [comment]
@clantosswett @nickjg231 @asiisii - Can you all please take a look at the figma files linked in the Tasks and give your approval/questions/concerns?

**Comment by asiisii** [comment]
> @clantosswett @nickjg231 @asiisii - Can you all please take a look at the figma files linked in the Tasks and give your approval/questions/concerns?

I didn't see any expanded section design when I looked at the Figma file linked @twoangstroms

**Comment by twoangstroms** [comment]
@asiisii Sorry, I know it's hard to see!

<img width="553" alt="Screenshot 2024-09-16 at 12 43 21 PM" src="https://github.com/user-attachments/assets/52ce8567-aab0-4d84-8ac3-6289fac11556">

**Comment by twoangstroms** [comment]
@asiisii The "Content: " won't go into the design the user sees, of course, but that's how the file was structured, so I didn't change that.

**Comment by asiisii** [comment]
@twoangstroms No need to apologize. Just to confirm, the current expanded text is: ‘The United States is automatically chosen as your country if you live on a military base outside of the country.’ The proposed new text is: ‘Addresses on U.S. military bases, whether domestic or abroad, are considered domestic addresses. When you check this box, we automatically choose the United States as the country.’ Is that correct?

Current text: 👇🏼
<img width="585" alt="Screenshot 2024-09-16 at 1 48 30 PM" src="https://github.com/user-attachments/assets/97bda994-d940-4553-8090-73244c5e6bfb">

**Comment by twoangstroms** [comment]
@asiisii Right! It's [this horizontal lane](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1724336887395/0f107c7e971dc93f275a3585cb916cc9ceea55af?wid=0-1724338473291) in the Contact Information update Mural

**Comment by asiisii** [comment]
@twoangstroms what do you think of changing the second part of the proposed text to this "Checking this box automatically sets ‘United States’ as your country." ?

**Comment by twoangstroms** [comment]
I get it, but the quotation marks aren't part of the style guide, so let's not mess with that.

**Comment by clantosswett** [comment]
This looks good though I don't know that I totally understand the need for the updated text. It feels unnecessarily wordy. If there is a specific reason we want to add the context let me know.

**Comment by twoangstroms** [comment]
Good questions, @clantosswett. It comes from [this epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89505), and refers to [work done by 686C](https://www.figma.com/design/LgjF3Kf8ozrBWMjPOQEKVV/686C---Military-Base-Outside-the-U.S.-Address-Issues?version-id=5016999883&node-id=0-12&node-type=canvas&t=w0EcyZ46OfM8W0Bl-0), but both predate my being on the team.

**Comment by alatempa** [comment]
OBE - this pattern is live
