### ISSUE TITLE
[TREX Norming] Roles Exercise

### ISSUE THREAD

**Issue by pammicmac** [department-of-veterans-affairs/va.gov-team#92413]
## Issue Description

Coming out of the [08/29 DBEX-TREX Teaming Workshop](https://app.mural.co/t/agilesixapplications0942/m/agilesixapplications0942/1723755991503/e925e34f687bef48c7ea4a1e3c5000a1ae8f474b?wid=0-1724952873797), our # 1 priority was
> RE Roles/Responsibilities: What, if anything, could be reorganized or redistributed to increase efficiency?
> How UX roles change w/ a HCD lead
> How we come to design solutions (which roles do this) and how we align on them
> How we plan the details of design epics (which roles do what)

As a TREX Team Member, I want to understand my role and the other roles on the team, so that we can work together seamlessly :tada:

---
## Tasks
- [ ] Schedule roles exercise (Targeting next sprint, Sept 25 or 26)
- [ ] Participate in roles exercise (1 - 1.5 hr workshop)
- [ ] Complete action items coming out of workshop
- [ ] Start experiment on with how we work together 

## Acceptance Criteria
- [ ] Written experiment doc outlining what success looks like, etc (Pam has a template somewhere)
- [ ] Additional ticket written to follow up on experiment after 4 sprints
  - Consider including "Add any new process/roles/ways of working coming out of experiment" as AC for that ticket
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
