### ISSUE TITLE
Spike: Research Upload Failures to 530 form

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#92412]
## Issue Description
Steve Albers made us aware of some Lighthouse Upload failures related to the 530 form.  Investigate issue and report back to Steve and/or potentially create ticket to resolve.

Context:
Slack thread:https://dsva.slack.com/archives/C05MS96P6P2/p1725891128159039

`{"data":{"id":"36ac327b-7401-461f-b791-249f7d458f0b","type":"upload","attributes":{"guid":"36ac327b-7401-461f-b791-249f7d458f0b","code":"DOC108","updated_at":"2024-09-07T19:57:07.927Z","detail":"Maximum page size exceeded. Limit is 78 in x 101 in.","uploaded_pdf":{"total_documents":4,"total_pages":16,"content":{"page_count":9,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":454114,"attachments":[{"page_count":5,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":584039},{"page_count":1,"dimensions":{"height":116.67,"width":70.83,"oversized_pdf":true},"file_size":1679490},{"page_count":1,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":6036214}]},"line_of_business":"NCA"},"status":"error","location":null}}}%
`
--
## Tasks
- [ ] _Investigate issue to identify root cause
- [ ] Report back to Steve and/or create follow on ticket to resolve

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mjknight50** [comment]
There are a few pieces of this:
1.  How to remediate this particular failure.
2. What was the experience of the veteran?  As far as they know, it was a success?
3. What is the overall solution for these PDF sizing failures.  Sanja has requested an ADR that addresses the overall issue and would like the solution to be applicable across teams.

**Comment by TaiWilkin** [comment]
# Summary of issue

When submitting Benefits claims, the `Lighthouse::SubmitBenefitsIntakeClaim` job doesn't validate attachments before submitting the claim. When the attachments reach Lighthouse, they're rejected by `VBADocuments::UploadValidations`. The error from VBADocuments is logged to DataDog, but since it occurs after submission, it doesn't trigger an error in `Lighthouse::SubmitBenefitsIntakeClaim`. The polling for benefit intake jobs does transition the FormSubmission to a failure state. 

# Recovering the claim data

The GUID attached to the VBA error message is the benefits_intake_uuid (not the claim confirmation number). Using this number, the FormSubmission object can be obtained with `FormSubmission.where(benefits_intake_uuid: {guid})`. This provides access to the logs and other information related to the form submission attempt. The error message from the failed attachment submission can also be found in the related FormSubmissionAttempt. 

The payload sent to Lighthouse can be downloaded from AWS via ArgoCD:
```
guid = "long-id-123-abc"
o = VBADocuments::ObjectStore.new
f = o.first_version(guid)
puts f.object.presigned_url(:get, expires_in: 1.day.to_i)
```

The payload can then be processed and transferred to a .zip file locally:
```
raw_file = "path/to/raw/file/locally"  
begin
	parsed = VBADocuments::MultipartParser.parse(raw_file.path)
	files = [
	{ name: 'content.pdf', path: parsed['content'].path },
	{ name: 'metadata.json', path: VBADocuments::PayloadManager.write_json(submission.guid, parsed).path }
	] + VBADocuments::PayloadManager.attachments(parsed)
rescue VBADocuments::UploadError
	files = [{ name: 'payload.blob', path: raw_file.path }]
end

zip_file_name = "path/to/local/location/#{guid}.zip"
Zip::File.open(zip_file_name, Zip::File::CREATE) do |zipfile|
	files.each do |file|
		zipfile.add(file[:name], file[:path])
	end
end

puts zip_file_name
```

The downloaded data includes the metadata, all attachments, and the claim PDF itself.

# Remediating the failed claim

@matt4su In order to remediate a claim which has failed, I recommend manually submitting the claim and supporting documents via a secure process (possibly SharePoint?). Due to the presence of PII, it must be done securely. I can provide the .zip file of claim data when we have determined the best process to hand the information over to the appropriate team. 

# Preventing future failed claims

We shouldn't submit claims to Lighthouse with invalid attachments. As an initial step, I recommend we update Lighthouse::SubmitBenefitsIntakeClaim to validate attachments when adding them (see PensionBenefitIntakeJob#perform and PensionBenefitIntakeJob#process_document). This will cause an error to be raised in the Sidekiq job, triggering retries and logging.

We also shouldn't allow users to upload documents which will fail Lighthouse validation when they're submitting to a form that uses Lighthouse. I recommend we update the upload file endpoint that creates PersistentAttachments so it doesn't allow files that wouldn't pass validation to be uploaded to VA.gov. The endpoint should return an error message, which should be displayed to the user so they can adjust their submission.

**Comment by matt4su** [comment]
Have reached out to our VBA colleagues to determine what group could process the claim manually and they pointed  me to Erica Dunbar in VBACO who has yet to respond.

**Comment by matt4su** [comment]
As I have not heard back from Erica Dunbar reached out to Joseph Sykes, another contact I was referred to in VBA today.

**Comment by matt4su** [comment]
Utilize new best practices process and Sharepoint folder to have claim manually processed.. https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/remediation.md
