### ISSUE TITLE
ITF | add logging for missing information and error tracking

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#92423]
Clarify and add logging in `CreateIntentToFileJob`

Task:
- [ ] clearly log what issue occurs during the job
- [ ] catch 'unfixable failure' error to prevent job retry

Acceptance:
- [ ] logs for each case distinguishable in DataDog
- [ ] 100% test coverage for job class
