### ISSUE TITLE
[a11y Support] CAIA: Testing - Voice Command and Interactive Elements

### ISSUE THREAD

**Issue by coforma-jamie** [department-of-veterans-affairs/va.gov-team#92432]
# CAIA A11y Testing
> [!CAUTION]
>  - **TESTING:** Voice command and interactive elements
> - **TIMING:** This ticket has the **potential for delays**, _due to limited access to testing tools_. We are currently reaching out to a11ys, who have or may have access to these voice-command tools. 
> - **Accessibility CoP:** This ticket's end result will likely be a collaboration of CAIA and the Accessibility Community of Practice.
>  - **DEFINITION OF DONE**: Refer to the task list in this ticket, for actionable items.

### Screen Reader Bias
There tends to be a bias towards designing accessible products for screen reader users, with voice command users (folks using apps like Dragon, Voice Control, etc.) not explicitly considered.

This may be because there's a lot of material online about how screen readers interact with interactive elements like `<a>` and `<button>`. But there's not a lot available for those same interactions with voice command software.

### How this applies to VA
We have components (🔗) that programmatically pull headings into `aria-labels` on buttons, such as the "Edit" buttons on the [Review page template](https://design.va.gov/templates/forms/review). And we've advised VFS teams to use `aria-label` or `aria-labelledby` to account for screen reader users in various situations. 

- How does that impact voice command users? 
- Are they able to access those interactive controls using their assistive technology?

### Our goal
Test how the most widely-used voice command apps interact with a variety of interactive elements, both standard and VADS, that have accessible names derived from the following:
- visible text
- `aria-label` that meets "Label in name" criteria
- `aria-label` that doesn't meet "Label in name" criteria
- 'aria-labelledby'

### How will we go about this testing?

- CAIA has created a testing scenario web page on GH Pages and an audit spreadsheet.
- Each tester will choose a voice command app from a pre-defined list.
- The tester will test a number of scenarios, as laid out on the GHP page.
- The tester will document their findings in the audit spreadsheet, including videos and summaries, if possible.
- CAIA will summarize and present the findings to the wider Accessibility CoP.

### Important Links
- [Interactive elements GHP testing page](https://coforma-jamie.github.io/VoiceCommandTest/)
   - If you aren't able to see the VADS components at the bottom of the page, use [this testing doc](https://c4lrj7.csb.app/) on [Codesandbox](https://codesandbox.io/p/sandbox/voice-command-testing-forked-c4lrj7?file=%2Fsrc%2FApp.js%3A228%2C36) instead
- [Audit spreadsheet on Google Sheets](https://docs.google.com/spreadsheets/d/154S4eYogg-k-Lx-GFLZuriIs8Nr3q2LO7gRY3jxamvU/edit?gid=0#gid=0)

## CAIA Assignees

<details><summary>Toggle to view CAIA assignee info</summary>

- @coforma-jamie 
- @SarahKay8 
- TBD
- TBD
</details>

## Team Info

<details><summary>Toggle to view team info</summary>

- **Team name:** CAIA
- **OCTO product owner:** Martha Wilkes
</details>

## Definition of Done
"Testing complete:" all tests run and documented.
```[tasklist]
### a11y Tasks
- [x] Inform A11y CoP of this work
- [x] Talon + Rango Extension Testing `complete` [Access the Talon and Rango Extension Summary in Comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92432#issuecomment-2349578760)
- [x] Apple iOS Voice Control testing `complete` [Access the iOS Voice Control Summary in Comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92432#issuecomment-2364272347)
- [x] Apple MacOS Voice Control testing `complete` [Access the MacOS VoiceControl Summary in Comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92432#issuecomment-2349558831)
- [x] Windows Speech Recognition (Win 10 and earlier) testing `complete` [Access the Windows Speech Recognition Summary in Comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92432#issuecomment-2353160592)
- [x] Windows Voice Access (Win 11) testing `complete` [Access the Windows Voice Access Summary in Comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92432#issuecomment-2406073145)
- [x] Android Voice Access testing `complete` - Brian [Access the Android Voice Access Summary in Comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92432#issuecomment-2402962207)
- [ ] Dragon (earlier version) testing complete - Brian? `we don't have access to Win 7 so we can't test`
- [x] Dragon (latest version) testing complete `complete` [Access the Dragon (latest version v16) Summary in Comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92432#issuecomment-2402847308)
- [x] [Results](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/accessibility-cookbook.md#visually-hidden-link--button-text-best-practices) summarized by CAIA
- [x] Solicit assistance from CAIA a11ys and the CoP
- [x] Results presented to larger A11y CoP
```

```[tasklist]
## Ticket Updates (CAIA Internal)
- [ ] _Connect to an `Epic` or `Intake` (what body of work is this a part of?)_
- [x] _Label with `Originator/Team` (product team or stakeholder requesting support)_
- [x] _Label date in the `Open Date` field_
- [x] _Label with `Estimate` (level of effort expected for this ticket)_
- [x] _Add `Assignee(s)` name(s) to ticket_
- [x] _Add `Assignee(s) name(s) to each task` they will complete via handle tag (if known)_
- [x] _Select a `Priority Level`_ (@artsymartha68 feedback needed)
- [x] _Update date in `Last Checked` field_
- [x] _Label with `Actual` (level of effort it took to complete this ticket)_
- [x] _Update date in_ `Closed  Date`
- [ ] **Related Ticket:** #94246
```

**Comment by sara-amanda** [comment]
## Priority Status

[@artsymartha68](https://github.com/artsymartha68) in lieu of our a11y/OCTO meeting today, are you able to review this ticket and let us know what priority level you would prefer we assign this ticket? For now, by default, I have flagged it as a `Chipper`. Jamie has begun the work, so it will not be showing in `New Intakes` to prompt a review, @NaomiPMC so that is why we are inquiring via ticket, and Slack. Thanks so much!

**Comment by artsymartha68** [comment]
I think Chipper is the correct category. The VA 508 office is just starting tech reviews of their Dragon contract applicants so without that contract in place, I'm not aware of a substitute option.

**Comment by coforma-jamie** [comment]
## Summary: MacOS Voice Control

What can you use to activate an interactive element?

- **Standard link - no ARIA:** accessible name
- **Standard link - no ARIA, duplicate:**  accessible name
- **Standard link - aria-label, beginning match:**  accessible name
- **Standard link - aria-label, match in the middle:**  accessible name
- **Standard link - aria-label, no match:**  accessible name
- **Standard link - aria-labelledby:**  accessible name
- **Standard button - no ARIA:**  accessible name
- **Standard button - no ARIA, duplicate:**  accessible name
- **Standard button - aria-label, beginning match:**  accessible name
- **Standard button - aria-label, match in the middle:**  accessible name
- **Standard button, aria-label, no match:**  accessible name
- **Standard button, aria-labelledby:**  accessible name
- **Standard text input -  no ARIA:**  accessible name
- **Standard text input -  aria-label, beginning match:**  accessible name
- **Standard text input -  aria-label, middle match:**  accessible name
- **Standard text input -  aria-label, no match:**  accessible name
- **Standard radio buttons -  aria-label, beginning match:** visible name, accessible name
- **Standard radio buttons -  aria-label, middle match:** visible name, accessible name
- **Standard radio buttons -  aria-label, no match:** visible name, accessible name
- **Standard checkbox - aria-label, beginning match:** visible name, accessible name
- **Standard checkbox - aria-label, middle match:** visible name, accessible name
- **Standard checkbox - aria-label, no match:** accessible name
- **VADS link - no ARIA:** accessible name 
- **VADS link - no ARIA, duplicate:** accessible name 
- **VADS link - aria-label, beginning match:** accessible name 
- **VADS link - aria-label, match in the middle:** accessible name 
- **VADS link - aria-label, no match:** accessible name 
- **VADS button - no ARIA:** accessible name 
- **VADS button - no ARIA, duplicate:** accessible name 
- **VADS button - aria-label, beginning match:** accessible name 
- **VADS button - aria-label, match in the middle:** accessible name 
- **VADS button - aria-label, no match:** accessible name 
- **VADS text input - no ARIA:** accessible name (must include hint text) 
- **VADS radio button - tile with description text:** accessible name (must include hint text) 
- **VADS checkbox - tile with description text:** none - can't be activated

**Comment by coforma-jamie** [comment]
## Summary: Talon + Rango extension

What can you use to activate an interactive element?

Note: Talon requires the Rango extension to use "fuzzy search," i.e. select elements via text on a web page. Talon also uses letter flags to distinguish clickable items.

- **Standard link - no ARIA:** visible name
- **Standard link - no ARIA, duplicate:**  visible name
- **Standard link - aria-label, beginning match:**  visible name
- **Standard link - aria-label, match in the middle:**  visible name, accessible name
- **Standard link - aria-label, no match:**  visible name
- **Standard link - aria-labelledby:**  visible name
- **Standard button - no ARIA:**  visible name
- **Standard button - no ARIA, duplicate:**  visible name
- **Standard button - aria-label, beginning match:**  visible name
- **Standard button - aria-label, match in the middle:**  visible name
- **Standard button, aria-label, no match:**  visible name
- **Standard button, aria-labelledby:**  visible name
- **Standard text input -  no ARIA:**  none - must use letter flag
- **Standard text input -  aria-label, beginning match:**  none - must use letter flag
- **Standard text input -  aria-label, middle match:**  none - must use letter flag
- **Standard text input -  aria-label, no match:**  none - must use letter flag
- **Standard radio buttons -  aria-label, beginning match:** none - must use letter flag
- **Standard radio buttons -  aria-label, middle match:** none - must use letter flag
- **Standard radio buttons -  aria-label, no match:** none - must use letter flag
- **Standard checkbox - aria-label, beginning match:** none - must use letter flag
- **Standard checkbox - aria-label, middle match:** none - must use letter flag
- **Standard checkbox - aria-label, no match:** none - must use letter flag
- **VADS link - no ARIA:** visible name
- **VADS link - no ARIA, duplicate:** visible name
- **VADS link - aria-label, beginning match:** visible name
- **VADS link - aria-label, match in the middle:** visible name
- **VADS link - aria-label, no match:** visible name
- **VADS button - no ARIA:** visible name
- **VADS button - no ARIA, duplicate:** visible name
- **VADS button - aria-label, beginning match:** visible name
- **VADS button - aria-label, match in the middle:** visible name
- **VADS button - aria-label, no match:** visible name
- **VADS text input - no ARIA:** none - must use letter flag
- **VADS radio button - tile with description text:** visible name
- **VADS checkbox - tile with description text:** none - must use letter flag

**Comment by coforma-jamie** [comment]
## Summary: Windows Speech Recognition (Win10 and below)

_What can you use to activate an interactive element?_

In general, Windows Speech Recognition picks up both visible and ARIA-defined accessible names, as long as the visible text is contained within the accessible name. For example:
- if aria-label is "treat" and and visible label is "treat me," it recognizes both...
- but if aria-label is "fur" and visible label is "scales", it only recognizes "fur."

**Exceptions:** 
- It wasn't able to pick up `<va-checkbox>` or `<va-radio>` at all.
- links and checkboxes didn't work with visible names for "match in the middle" tests

**Note:** I had issues with the app picking up my voice accurately. Refer to the spreadsheet for items that may be slightly off / could be retested.


- **Standard link - no ARIA:** visible name
- **Standard link - no ARIA, duplicate:**  visible name
- **Standard link - aria-label, beginning match:**  visible name, accessible name
- **Standard link - aria-label, match in the middle:**  accessible name
- **Standard link - aria-label, no match:**  accessible name
- **Standard link - aria-labelledby:**  accessible name
- **Standard button - no ARIA:**  visible name
- **Standard button - no ARIA, duplicate:**  visible name
- **Standard button - aria-label, beginning match:**  visible name, accessible name
- **Standard button - aria-label, match in the middle:**  visible name, accessible name
- **Standard button, aria-label, no match:**  accessible name
- **Standard button, aria-labelledby:**  accessible name
- **Standard text input -  no ARIA:**  visible name
- **Standard text input -  aria-label, beginning match:**  visible name, accessible name
- **Standard text input -  aria-label, middle match:**  visible name, accessible name
- **Standard text input -  aria-label, no match:**  accessible name
- **Standard radio buttons -  aria-label, beginning match:** visible name, accessible name
- **Standard radio buttons -  aria-label, middle match:** visible name, accessible name
- **Standard radio buttons -  aria-label, no match:** accessible name
- **Standard checkbox - aria-label, beginning match:** none - visible name, accessible name
- **Standard checkbox - aria-label, middle match:** none - accessible name
- **Standard checkbox - aria-label, no match:** none - accessible name
- **VADS link - no ARIA:** visible name
- **VADS link - no ARIA, duplicate:** visible name
- **VADS link - aria-label, beginning match:** visible name, accessible name
- **VADS link - aria-label, match in the middle:** visible name, accessible name
- **VADS link - aria-label, no match:** accessible name
- **VADS button - no ARIA:** visible name
- **VADS button - no ARIA, duplicate:** visible name
- **VADS button - aria-label, beginning match:** visible name, accessible name
- **VADS button - aria-label, match in the middle:** visible name, accessible name
- **VADS button - aria-label, no match:** accessible name
- **VADS text input - no ARIA:** visible name
- **VADS radio button - tile with description text:** none
- **VADS checkbox - tile with description text:** none

**Comment by SarahKay8** [comment]
IOS Voice Control 



### Summary of Success:

- **Visual Labels**: In most cases, visual labels activate the element using voice commands. 
- **ARIA Labels**: When visual labels don't work, ARIA labels are typically effective. 
- **Mixed Response**: A few cases where neither visual label nor ARIA responded.

### Standard Link:

1. **Standard link**: No ARIA, duplicate  
   - **Behavior**: Tap (visual label) activates.

2. **Standard link**: Aria-label, beginning match  
   - **Behavior**: Tap (aria-label) activates. Visual label no response.

3. **Standard link**: Aria-label, match in the middle  
   - **Behavior**: Tap (aria-label) activates. Visual label no response.

4. **Standard link**: Aria-label, no match  
   - **Behavior**: Tap (aria-label) activates. Visual label no response.

5. **Standard link**: Aria-labelledby  
   - **Behavior**: Tap (IN) received focus.

---

### Standard Button:

1. **Standard button**: No ARIA, duplicate  
   - **Behavior**: Tap (visual label) activates.

2. **Standard button**: Aria-label, beginning match  
   - **Behavior**: Tap (visual label) activates. Must select between 1 or 2 to select.

3. **Standard button**: Aria-label, match in the middle  
   - **Behavior**: Tap (visual label) no response. Tap (aria-label) activates.

4. **Standard button**: Aria-label, no match  
   - **Behavior**: Tap (visual label) no response. Tap (aria-label) activates.

5. **Standard button**: Aria-labelledby  
   - **Behavior**: Tap (visual label) no response. Tap (aria-label) activates.

---

### Standard Text Input:

1. **Standard text input**: No ARIA  
   - **Behavior**: Tap (visual label) activates. Actual input text field is active.

2. **Standard text input**: Aria-label, beginning match  
   - **Behavior**: Tap (visual label) activates. Tap (aria-label) activates.

3. **Standard text input**: Aria-label, middle match  
   - **Behavior**: Tap (visual label) activates. Tap (aria-label) no response.

---

### Standard Radio Buttons:

1. **Standard radio buttons**: Aria-label, beginning match  
   - **Behavior**: Tap (visual label) activates. Tap (aria-label) activates.

2. **Standard radio buttons**: Aria-label, middle match  
   - **Behavior**: Tap (visual label) activates. Tap (aria-label) activates.

3. **Standard radio buttons**: Aria-label, no match  
   - **Behavior**: Tap (visual label) activates.

---

### Standard Checkbox:

1. **Standard checkbox**: Aria-label, beginning match  
   - **Behavior**: Tap (visual label) activates.

2. **Standard checkbox**: Aria-label, middle match  
   - **Behavior**: Tap (aria-label) activates. Visual label no response.

3. **Standard checkbox**: Aria-label, no match  
   - **Behavior**: Tap (aria-label) activates.

---

### VADS Link:

1. **VADS link**: No ARIA  
   - **Behavior**: Tap (visual label) activates.

2. **VADS link**: No ARIA, duplicate  
   - **Behavior**: Tap (visual label) activates.

3. **VADS link**: Aria-label, beginning match  
   - **Behavior**: Tap (aria-label) activates.

4. **VADS link**: Aria-label, match in the middle  
   - **Behavior**: Tap (aria-label) activates.

5. **VADS link**: Aria-label, no match  
   - **Behavior**: Tap (aria-label) activates.

---

### VADS Button:

1. **VADS button**: No ARIA  
   - **Behavior**: Tap (visual label) activates.

2. **VADS button**: No ARIA, duplicate  
   - **Behavior**: Tap (visual label) activates.

3. **VADS button**: Aria-label, beginning match  
   - **Behavior**: Tap (aria-label) activates.

4. **VADS button**: Aria-label, match in the middle  
   - **Behavior**: Tap (aria-label) activates.

5. **VADS button**: Aria-label, no match  
   - **Behavior**: Tap (aria-label) activates.

---

### VADS Text Input:

- **VADS text input**: No ARIA  
   - **Behavior**: Tap (visual label) activates.

---

### VADS Radio Button:

- **VADS radio button**: Tile with description text  
   - **Behavior**: Tap (visual label) activates.

---

### VADS Checkbox:

- **VADS checkbox**: Tile with description text  
   - **Behavior**: Tap (visual label) activates.

**Comment by briandeconinck** [comment]
## Summary: Dragon (latest version, v16)

- [ ] Summary linked in ticket task list.

### What can you use to activate an interactive element?

Dragon is pretty great on all standard HTML elements matching visible text. When using `aria-label` or `aria-labelledby`, there are a couple of trouble spots:
- When an element has an `aria-labelledby` that references both itself and another element, the sequence in which they're referenced seems to matter (link ID must come first).
- When text inputs have an `aria-label`, the `aria-label` doesn't appear to work.

Dragon really struggled with VADS web components. Neither visible text nor accessible names worked, with the exception of the radio button tile. 


- **Standard link - no ARIA:** visible name
- **Standard link - no ARIA, duplicate:**  visible name
- **Standard link - aria-label, beginning match:**  visible name, accessible name
- **Standard link - aria-label, match in the middle:**  visible name, accessible name
- **Standard link - aria-label, no match:**  visible name, accessible name
- **Standard link - aria-labelledby:**  visible name; accessible name depends on the order that elements are referenced
- **Standard button - no ARIA:**  visible name
- **Standard button - no ARIA, duplicate:**  visible name
- **Standard button - aria-label, beginning match:**  visible name, accessible name
- **Standard button - aria-label, match in the middle:**  visible name, accessible name
- **Standard button, aria-label, no match:**  visible name, accessible name
- **Standard button, aria-labelledby:**  visible name; accessible name depends on the order that elements are referenced
- **Standard text input -  no ARIA:**  visible name
- **Standard text input -  aria-label, beginning match:**  visible name
- **Standard text input -  aria-label, middle match:**  visible name
- **Standard text input -  aria-label, no match:**  visible name
- **Standard radio buttons -  aria-label, beginning match:** visible name, accessible name
- **Standard radio buttons -  aria-label, middle match:** visible name, accessible name
- **Standard radio buttons -  aria-label, no match:** visible name, accessible name
- **Standard checkbox - aria-label, beginning match:** visible name, accessible name
- **Standard checkbox - aria-label, middle match:** visible name, accessible name
- **Standard checkbox - aria-label, no match:** visible name, accessible name
- **VADS link - no ARIA:** none
- **VADS link - no ARIA, duplicate:** none
- **VADS link - aria-label, beginning match:** none
- **VADS link - aria-label, match in the middle:** none
- **VADS link - aria-label, no match:** none
- **VADS button - no ARIA:** none
- **VADS button - no ARIA, duplicate:** none
- **VADS button - aria-label, beginning match:** none
- **VADS button - aria-label, match in the middle:** none
- **VADS button - aria-label, no match:** none
- **VADS text input - no ARIA:** none
- **VADS radio button - tile with description text:** visible name, accessible name
- **VADS checkbox - tile with description text:** none

**Comment by briandeconinck** [comment]
## Summary: Android Voice Access

- [ ] Summary linked in ticket task list.

### What can you use to activate an interactive element?




- **Standard link - no ARIA:** visible name
- **Standard link - no ARIA, duplicate:**  visible name
- **Standard link - aria-label, beginning match:**  visible name, accessible name
- **Standard link - aria-label, match in the middle:**  visible name
- **Standard link - aria-label, no match:**  visible name, accessible name
- **Standard link - aria-labelledby:**  visible name, accessible name
- **Standard button - no ARIA:**  visible name
- **Standard button - no ARIA, duplicate:**  visible name
- **Standard button - aria-label, beginning match:**  visible name, accessible name
- **Standard button - aria-label, match in the middle:**  visible name, accessible name
- **Standard button, aria-label, no match:**  accessible name
- **Standard button, aria-labelledby:**  visible name, accessible name
- **Standard text input -  no ARIA:**  visible name
- **Standard text input -  aria-label, beginning match:**  visible name, accessible name
- **Standard text input -  aria-label, middle match:**  visible name, accessible name
- **Standard text input -  aria-label, no match:**  accessible name
- **Standard radio buttons -  aria-label, beginning match:** visible name, accessible name
- **Standard radio buttons -  aria-label, middle match:** visible name, accessible name
- **Standard radio buttons -  aria-label, no match:** visible name, accessible name
- **Standard checkbox - aria-label, beginning match:** accessible name
- **VADS link - no ARIA:** visible name
- **VADS link - no ARIA, duplicate:** visible name
- **VADS link - aria-label, beginning match:** visible name, accessible name
- **VADS link - aria-label, match in the middle:** visible name, accessible name
- **VADS link - aria-label, no match:** visible name, accessible name
- **VADS button - no ARIA:** visible name
- **VADS button - no ARIA, duplicate:** visible name
- **VADS button - aria-label, beginning match:** visible name, accessible name
- **VADS button - aria-label, match in the middle:** visible name, accessible name
- **VADS button - aria-label, no match:** accessible name
- **VADS text input - no ARIA:** visible name
- **VADS radio button - tile with description text:** accessible name
- **VADS checkbox - tile with description text:** visible name

**Comment by srancour** [comment]
## Summary: Windows Voice Access (Win 11)

- [ ] Summary linked in ticket task list.

### What can you use to activate an interactive element?

Generally, Windows Voice Access (Win 11) does well with both visible names and accessible names. It does select on anything close to the phrase used. Exceptions:
1. When visible names and accessible names have no match, visible name doesn't work
2. Some inconsistent behavior around VADS radio buttons and checkboxes
3. If spoken slower and emphasizing the dot, a label that is similar to a url will make Voice Access think it's a url you're trying to click on
4. There's a weird focus issue where on the VADS link matching in the middle it focuses on the link after even though it clicks the correct link


- **Standard link - no ARIA:** visible name
- **Standard link - no ARIA, duplicate:**  visible name
- **Standard link - aria-label, beginning match:**  visible name, accessible name
- **Standard link - aria-label, match in the middle:**  visible name, accessible name
- **Standard link - aria-label, no match:**  accessible name
- **Standard link - aria-labelledby:**  visible name, accessible name
- **Standard button - no ARIA:**  visible name
- **Standard button - no ARIA, duplicate:**  visible name
- **Standard button - aria-label, beginning match:**  visible name, accessible name
- **Standard button - aria-label, match in the middle:**  visible name, accessible name
- **Standard button, aria-label, no match:**  accessible name
- **Standard button, aria-labelledby:**  visible name, accessible name
- **Standard text input -  no ARIA:**  visible name
- **Standard text input -  aria-label, beginning match:**  visible name, accessible name
- **Standard text input -  aria-label, middle match:**  visible name, accessible name
- **Standard text input -  aria-label, no match:**  accessible name
- **Standard radio buttons -  aria-label, beginning match:** visible name, accessible name
- **Standard radio buttons -  aria-label, middle match:** visible name, accessible name
- **Standard radio buttons -  aria-label, no match:** accessible name
- **Standard checkbox - aria-label, beginning match:** visible name, accessible name
- **Standard checkbox - aria-label, middle match:** visible name, accessible name
- **Standard checkbox - aria-label, no match:** accessible name
- **VADS link - no ARIA:** visible name
- **VADS link - no ARIA, duplicate:** visible name
- **VADS link - aria-label, beginning match:** visible name, accessible name works only if spoken quickly
- **VADS link - aria-label, match in the middle:** visible name, accessible name
- **VADS link - aria-label, no match:** accessible name
- **VADS button - no ARIA:** visible name
- **VADS button - no ARIA, duplicate:** visible name
- **VADS button - aria-label, beginning match:** visible name, accessible name
- **VADS button - aria-label, match in the middle:** visible name, accessible name
- **VADS button - aria-label, no match:** accessible name
- **VADS text input - no ARIA:** visible name
- **VADS radio button - tile with description text:** none
- **VADS checkbox - tile with description text:** none

**Comment by artsymartha68** [comment]
Thank you all for this deep dive! Sounds like Brian's doc for the general public would be an excellent resource to share with VFS and DST teams.

We may be able to find a Dragon user within the VA community if you feel like testing with a daily user is needed.

**Comment by coforma-jamie** [comment]
After discussion:
- We don't need to test with an everyday Dragon user, since this was a technical test ("does Dragon let you do X," vs "how do users use Dragon to do X")
- @briandeconinck is going to work on a public-facing document with our results, but that won't be a part of this ticket.
