### ISSUE TITLE
Improve Datadog dashboard(s)

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#92430]
## Issue Description
As a T-REX team member I would like the Datadog dashboards we use to monitor 526 submissions of primary, backup, and failsafe path to be improved.

---
## Tasks
- [ ] 

## Acceptance Criteria
- [ ] All DD graphs & metrics are clearly labeled or annotated to communicate what the metrics track, in simple, human readable language - so technical and non-technical folks can understand what they are looking at
- [ ] To support the LH migration, the same metrics are tracked side by side
- [ ] To the greatest extent possible, 526 form core metrics are tracked for both EVSS and LH
- [ ] Metrics that are no longer needed are removed from the dashboard
- [ ] Dashboards we no longer use are deleted
- [ ] Dashboards are labeled or named clearly to represent what information they present
- [ ] Primary, backup, and failsafe path usage is represented
- [ ] Metrics that aren't working are fixed
- [ ] New metrics that are needed to understand failure scenarios are added and annotated similar to the above

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
