### ISSUE TITLE
Remove/replace Virtus models for FormProfiles

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#92440]
As an engineer, I want to use Vets::Model instead of the virtus gem for FormProfile related models, so that I can remove virtus gem

## Summary 

- Replace virtus models with Vets::Model (mostly 1-to-1 update)
- Roughly 50 classes
- Update Array attributes to use new convention

## Tasks

- [x] Communicate intentions with whatever team is in charge of FormProfile models
- [ ] ~Create new temp subclass VirtusFormProfile (copy the original)~
- [ ] ~Update subclasses of FormProfile to subclasses of VirtusFormProfile~
- [x] Update FormProfile to include from Vets::Model
- [ ] ~Switch models to new FormProfile from VirtusFormProfile (50 models)~
- [x] Update FormProfile related models to Vets::Model

Anticipated PRs:
- FormProfile (superclass)
- MDOT
- 526ez
- 2122
- 21686c
- Any remaining FormProfile related models

## Acceptance Criteria

- [x] FormProfile related models use Vets::Model not virtus

## Example conversion for subclasses
before
```ruby
class FormFullName
  include Virtus.model

  attribute :first, String
  attribute :middle, String
  attribute :last, String
  attribute :suffix, String
  attribute :service_branches, Array[String]
end
```

after
```ruby
class FormFullName
  include Vets::Model

  attribute :first, String
  attribute :middle, String
  attribute :last, String
  attribute :suffix, String
  attribute :service_branches, String, array: true
end

**Comment by stevenjcumming** [comment]
Update: `Vets::Model` can not only replace virtus, but also be mixed with virtus models. This means I don't need to create any intermediate class (`VirtusFormProfile`). This should reduce the time required to complete this task

**Comment by stevenjcumming** [comment]
21-686c is going to be removed in another PR:

- https://github.com/department-of-veterans-affairs/vets-api/pull/21987
