### ISSUE TITLE
Chore: Remove/replace Virtus models for IVCChampva

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#92446]
## User Story
As an engineer, I want to replace Virtus and Common::Base with Vets::Model, so that I can remove Virtus gem.

## Issue Description
- This Issue is for `modules/ivc_champva` (5 models)
- The goal is to replace remove Virtus from those models
- The virtus gem ([source](https://github.com/solnic/virtus)) is discontinued and must be replaced
- The replacement is `Vets::Model` ([source](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/vets/model.rb))
- This should not affect any functionality. 
- Some changes from hash notation to dot notation are required

## Tasks
- [ ] Replace Virtus in IVCChampva module

## Acceptance Criteria
- [ ] No class uses Virtus 
- [ ] Serialized responses are identical
- [ ] No functionality changes

**Comment by AshleyGuerrant** [comment]
@stevenjcumming - can you update the ticket description using the [SRE Team template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?template=platform-product-validation.md)?
