### ISSUE TITLE
BE | IES | Continued discovery

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#92459]
## Background 
Last sprint we identified a backend engineer (Scott Simon) that can provide answers to our technical questions.

Meeting scheduled for 9/12

## Tasks
- [x] Attend meeting scheduled for 9/12 and determine if we're going to need to build an IES API from scratch or if there's something we can reuse from the other team 
- [x] Document technical options

## Acceptance Criteria 
- [x] Follow up with team

**Comment by mtcA6** [comment]
@tpharrison what else do you think we should aim to uncover for ILER/IES? And what do you think for this size wise?

**Comment by ACParker89** [comment]
Met 9/12


- We do not need to build an API 
- We need to meet with the DoD IES Team 
- @clantosswett @ACParker89 Will work together to determine next steps/POC for the above call

**Comment by ACParker89** [comment]
Follow Up (Needs to happen prior to Chris Johnson/VEO Meeting) 
- Read L. Jefferies [Email ](https://dsva.slack.com/archives/C909ZG2BB/p1726578662204049)
- Meet w. IES DoD Team 
- LOE and timeline 

CC: @clantosswett
