### ISSUE TITLE
FE | Ch33 Migration | Post Launch Cleanup (Part 2 -Legacy Code Depreciation)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#92457]
## Background 

Now that we've launched the Ch33 work, we need to remove the feature toggle(s) and deprecate the legacy page. We removed toggles in #89743, this story is to depreciate the code we no longer need. 

## Tasks 
- [ ] clean up the code to remove stale references 
- [ ] determine if we need to keep any of the toggles (maybe the one to bring down the entire page? )
- [ ] make sure `profileShowDirectDepositSingleForm` and `profileShowDirectDepositSingleFormUAT` logics are cleaned up properly
- [ ] make sure we don't have any Redux code related to the legacy code
- [ ] need to remove `paymentInformation` actions file, talk to VA team if its okay to remove it as they're importing that file in `src/applications/personalization/dashboard/components/benefit-application-drafts/BenefitApplications.jsx` but they're not using it after they imported it
- [ ] clean up our [FE documentation ](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/direct_deposit/frontend_documentation.md)to remove stale references 

### these toggles shouldn't exist anymore
profile_show_direct_deposit_single_form 
profile_show_direct_deposit_single_form_UAT
profile_show_direct_deposit_single_form_alert
profile_show_direct_deposit_single_form_edu_downtime

### toggles to keep 
profile_hide_direct_deposit

## Acceptance Criteria 
- [ ] we no longer have  the legacy code 
- [ ] we're no longer making extra duplicative requests to the legacy Ch33 endpoint 

> [!NOTE]  
> This can be dangerous, MHV team accidentally removed code for their secondary nav. We want to make sure we don't do something similar

**Comment by mtcA6** [comment]
@asiisii can you modify the copy here for the new verion of this ticket since I didn't change the contents

**Comment by mtcA6** [comment]
and a size

**Comment by tpharrison** [comment]
@asiisii The feature toggles have been removed from staging and production.
