### ISSUE TITLE
[ANALYTICS] Create new Health Services content "LIST & PLAYBOOK" for VA Cheyenne health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9246]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN 19 Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## TASKS: See below list of Stories
- [x] Laramie Mobile Telehealth Clinic
- [x] Cheyenne VA Medical Center
- [x] Fort Collins VA Clinic
- [x] Loveland VA Clinic
- [x] Rawlins VA Clinic
- [x] Sidney VA Clinic
- [x] Sterling VA Clinic
- [x] Torrington VA Mobile Clinic
- [x] Wheatland VA Mobile Clinic

## Definition of Done 
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* Laramie Mobile Telehealth Clinic
* Cheyenne VA Medical Center
* Fort Collins VA Clinic
* Loveland VA Clinic
* Rawlins VA Clinic
* Sidney VA Clinic
* Sterling VA Clinic
* Torrington VA Mobile Clinic
* Wheatland VA Mobile Clinic
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] _Archived in Github and/or SharePoint for review by Product Lead and PAOs
