### ISSUE TITLE
[ANALYTICS] Create new System Data documents "HSL LIST & PLAYBOOK" for VISN-19 Medical Systems [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9247]
## VAMC - Product Outline
[VAMC-upgrade Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2019.md)

## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN 19 Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## VAMC-Upgrade KPI met with this EPIC
_These tasks support the load of CONTENT from legacy to NEW web systems prior to Milestone date for VISN 19._
* VA Cheyenne health care
* VA Eastern Colorado health care
* VA Western Colorado (Grand Junction) health care
* VA Montana health care
* VA Eastern Oklahoma health care
* VA Oklahoma health care
* VA Salt Lake City health care
* VA Sheridan health care

## Definition of Done 
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
- [x] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

- [x] _Archived in Github and/or SharePoint for review by Product Lead and PAOs
