### ISSUE TITLE
Update NOD confirmation page confirmation alert language

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#92481]
## Value Statement

**_As a_** Veteran that has just submitted an appeal on VA.gov
**_I want to_** have the most realistic and up-to-date information about the Board Appeal process
**_So that_** I can understand what to expect next

---

## Background Context
The Board came back with concerns about the inaccurate messaging in our current success message. Since submitting the form does not address the fact that there is time before submission and receipt, we need to clarify that it's not successfully submitted until they get a confirmation letter. Otherwise, BVA is not comfortable us returning a copy of their submission to them.

## Acceptance Criteria
- [x] User can access confirmation page after submission
- [x] User sees updated information in the alert, what to expect next, and an HTML return of their responses.

## Designs and Build Notes

- [FIGMA](https://www.figma.com/design/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?node-id=1543-13764&m=dev)

### Enablement team (if needed)
@jstrothman 

## Out of scope
- Confirmation email
- PDF download

## Tasks

- [ ] Update success alert to new screen [FIGMA](https://www.figma.com/design/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?node-id=1951-14228&m=dev)

## Definition of Ready

- [ ] LH endpoint is available
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@eileen-coforma to validate that this is complete

**Comment by eileen-coforma** [comment]
Waiting for ticket to merge. Will update when it's ready to validate.

**Comment by Mottie** [comment]
Changes are available in staging
