### ISSUE TITLE
[FE] [TECH DEBT] - add (opens in a new window) text to external link component

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#92499]
## Description
We now have several links that open in a new tab, they all have `(opens in a new window)` added to the link text. We can move this functionality to our link component to automatically append it to the link text when `target="_blank"`

## Tasks
- [ ] Add append text functionality to external link component
- [ ] Update link text to not have it hard-coded
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92499?planning-poker) with Zenhub @wullaski
