### ISSUE TITLE
10-10 EZR emergency contact

### ISSUE THREAD

**Issue by bmrea1** [department-of-veterans-affairs/va.gov-team#92493]
## Issue description

The 10-10EZR Health Benefits Update paper form asks for Next of Kin and Emergency Contact information but the product team left it off their online form MVP launch. Now the team is circling back and adding the Next of Kin and Emergency Contact to their online form. They will start with the Emergency Contact first.
[Mural NoK-EC](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698340057865/2e2eced8589757c192a1601579a871cab97d3565?sender=ubf5503bf47b6eb1e92730053)
    [Figma Link](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=2614-34432&t=kjqB9kvXOYsMkeRV-1)

---
## Tasks

- [x] Review designs and provide content feedback
- [x] Share with product team

## Acceptance Criteria
- [ ] Share content feedback/review with designers

**Comment by aliyahblackmore** [comment]
**Update here:** 

- I did one last review of the emergency contact screens in [Figma ](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=2614-34674&t=gLMAyElepnTFCy7Q-4):party-sparkles:
- I tracked one question on that note in the destructive screen section.   It doesn't seem like there's a need for any other static page adjustments at this time, but Hieu will let me know if there was something else he's interested in changing.
 Hieu mentioned today that there may be a potential shift re: primary/secondary contacts. I'll look out for any design updates in the coming days. The contact freeze date (9/10) will shift because of this, but the current designs have all of the content recs.
- And I'll hold on sharing the static page update with your SMEs just in case the primary/secondary updates impact the page.

**Comment by aliyahblackmore** [comment]
**Update here:** 

- I got the okay from Hieu to turn back to this work now. 

- The engineers on their team tested a few options for a "Primary contact" selection. Due to backend constraints, they're unable to implement any sort of check box or option to select a Primary contact at this time. 

- The first card will always be the Primary contact and the team decided to move forward with using content to explain that, at this time. I'll take a look at the content.

**Comment by aliyahblackmore** [comment]
**Update here:** 

- Chatted with Hieu about an additional update on the flow intro screen to note that the changes on this form will only apply in this form, since the updates in the EZR won't track in VA profile.

- The team will follow up re: the difference between the PDF and online form and confirm that their SMEs are okay with this. If they are and there isn't a plan to update the PDF to match in the near future, we can consider a note on the static page and about form page that explains that they'll need to use the online form if they want to add two contacts.

- I'll finish up on Monday and track the content changes (via comments) on the prefill screens.

**Comment by aliyahblackmore** [comment]
Update here:

I went through the Emergency Contact screens again and wrapped up content and tracked the changes on the ADD/EDIT screens

- As we chatted on Friday, I added the note on the intro screen to state that the information they add in the form will only apply to the form (since the info likely won't show in VA profile at this time). I also tracked a similar note on the add/review screens.
- I changed "postal" to "postal code" to align with the design system
- And I tracked the content from the "New" section in the "ADD/EDIT" sections using comments.
 - And team is chatting with their SMEs tomorrow re: the difference between the online form and PDF (2 contacts vs. 1)

**Comment by aliyahblackmore** [comment]
The designers learned that there are a few constraints in the list&loop pattern (they can't use body text or text between the header and question). For their V1, they decided to use hint text for the emergency contact screens.

I reviewed and adjusted any necessary screens! Whenever they review with SMEs, we can make accuracy of information updates if needed.

**Comment by aliyahblackmore** [comment]
These designs are with the product team and on hold for now.  

The team will revisit with their SMEs in the future. And they'll confirm if they'll move forward with 2 fields vs. 1 field.

Moving this to blocked for now.

**Comment by VCM86** [comment]
Closing--reach out if you have any questions.
