### ISSUE TITLE
[FE] [TECH-DEBT] - Create shared components for travel review page

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#92498]
## Description
The travel review page for OH travel and check-in share a bunch of stuff. We can probably break some of those content blocks out into little components that both can use.

## Tasks
- [ ] Create shared components for travel-review page
- [ ] implement the new components 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92498?planning-poker) with Zenhub @wullaski
