### ISSUE TITLE
[FE] Redux state tracking for appointments-cc flow

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#92490]
Make sure items are tracked for each page, and the state flow works properly

- [ ] Appointments list w/ task card
- [ ] Referral / intro page
- [ ] Select date & time ([New wireframe](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2217-61186&t=Rq3LontPGEuFBygU-4))
- [ ] Review page
- [ ] Confirmed - appt detail page

**Comment by lee-delarm6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92490?planning-poker) with Zenhub @wullaski @brianseek

**Comment by benbrasso-agile6** [comment]
Added new wireframe for the select data and time page to the list above. Trying not to disturb anyone, shhhh.

**Comment by loripusey** [comment]
closing for now, will replace with new FE & BE tickets being created
