### ISSUE TITLE
[FE] [TECH DEBT] - update to use button pair

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#92500]
## Description
The `<va-button-pair>` component now allows custom text. We should update our confirmable pages and travel pages to use the component.

https://design.va.gov/storybook/?path=/docs/uswds-va-button-pair--docs

## Tasks
- [ ] Update our two button usage to use va-button-pair
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92500?planning-poker) with Zenhub @wullaski
