### ISSUE TITLE
[CDP] VHA Lighthouse data discovery

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#92544]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Continue refinement of mockups to align with new Lighthouse data.

---
## Tasks
 _What work is necessary for this story to be completed?_
- [x] Confirm data in mockup/prototype is consistent with Lighthouse data we will be receiving

## Acceptance Criteria
 _What will be created or happen as a result of this story?_
- [x] Information in mockup/prototype is consistent with Lighthouse data

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Continuation of [#90671](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/90671)

**Comment by mgleo** [comment]
Mockup discussed with Lighthouse team during _Lighthouse & VODA: Payment History Initiative Technical Sync_ 9/19
