### ISSUE TITLE
Translation work for COVID-19 vaccine updates

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#92552]
> [!WARNING]
> Do not use this ticket unless directed to do so by the CAIA team.

## Issue description

We updated our [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/) page with updated information for 2024-2025 vaccine guidance. We need to get this content translated and added to the Spanish and Tagalog pages. All the content that changed is in the blue featured content box and in the accordion "Currently available COVID-19 vaccines."

**Note:** These translations don't go to the State Department but to a group within VA.

## Tasks
_What work is necessary for this ticket to be completed? Examples:_
- [ ] Create word doc with content to be translated (Victoria)
- [ ] Send to VA translation group (Randi)
- [ ] Update Spanish page (Victoria) 
- [ ] Update Tagalog page (Victoria)
- [ ] Review Spanish page (Sara/Megan)
- [ ] Review Tagalog page (Sara/Megan)
- [ ] Publish Spanish page (Sara/Megan)
- [ ] Publish Tagalog page (Sara/Megan)

## Acceptance Criteria

- [ ] Spanish page is live with changes
- [ ] Tagalog page is live with changes

## Configure this issue
- [ ] _Attach to an Epic (what body of work is this a part of?)_
- [ ] _Label with Originator/Team (product team or stakeholder requesting support)_
- [ ] _Label with Open Date_
- [ ] _Label with Estimate (level of effort expected for this ticket)_
- [ ] _Add assignee name to each task they will complete (if known)_

**Comment by moviedosoco** [comment]
@RLHecht, @megzehn Alerts were added on the Spanish and Tagalog pages to indicate that the information there isn't the most current, and to check the English page instead. These alerts will be removed once we update both Drupal pages with the correct translations. 
Spanish: https://www.va.gov/health-care/covid-19-vaccine-esp/
Tagalog: https://www.va.gov/health-care/covid-19-vaccine-tag/

**Comment by moviedosoco** [comment]
Hi @RLHecht, this is the Word document with the highlighted content to be translated in Spanish and Tagalog languages.
[COVID-19 vaccines at VA_UPDATED CHANGES.docx](https://github.com/user-attachments/files/16985902/COVID-19.vaccines.at.VA_UPDATED.CHANGES.docx)

**Comment by RLHecht** [comment]
@moviedosoco Here's the Spanish content back from the translators. Can you please update the Drupal page with these changes and pass to Megan to review and publish? thanks!

[25157_Covid Vaccines at VA_Spanish.pdf](https://github.com/user-attachments/files/17016282/25157_Covid.Vaccines.at.VA_Spanish.pdf)

**Comment by moviedosoco** [comment]
@RLHecht Drupal page in Spanish is updated with the changes.
@megzehn The page '**Vacunas contra el COVID-19 en VA**' is ready to be reviewed and published. Thank you!

http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by megzehn** [comment]
Thank you, @moviedosoco! 

Confirming I reviewed and published this page.

**Comment by RLHecht** [comment]
@moviedosoco Here is the tagalog content back from the translators. Can you please update the Drupal page and pass to Megan to publish? Thanks!

[25158_Covid Vaccines at VA_Tagalog.pdf](https://github.com/user-attachments/files/17059234/25158_Covid.Vaccines.at.VA_Tagalog.pdf)

**Comment by moviedosoco** [comment]
@RLHecht Will do, thank you!

**Comment by moviedosoco** [comment]
@megzehn Tagalog page '**Mga bakuna sa COVID-19 sa VA**' is updated in Drupal, and is ready to be reviewed and published. Thank you!
http://preview-prod.vfs.va.gov/preview?nodeId=16413

Also, I fixed a couple of typos that were in the Spanish page. Could you please review and publish? Thank you!
http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by megzehn** [comment]
Thank you for your careful work on these, @moviedosoco!! Confirming that I reviewed and published both pages.

**Comment by megzehn** [comment]
@RLHecht and @moviedosoco since these are published, I'm going to move this to validate. But let me know if that's wrong!

**Comment by moviedosoco** [comment]
Hi @RLHecht @saratorres2, as per our convo in Slack on Dec 2nd, the page needs a small update in accordion **How we monitor vaccine safety**, which is the removing of the bolded sentence and the two CDC links. 

I removed them in SPA (**Cómo monitoreamos la seguridad de las vacunas**) and FIL (**Paano namin sinusubaybayan ang kaligtasan ng** **bakuna**)   accordions and left them in draft in Drupal, so Sara can publish the three pages at once when you have updated the English page. Thank you!

- SPA Drupal node https://prod.cms.va.gov/health-care/covid-19-vaccine-esp
       Preview: https://preview-prod.vfs.va.gov/preview?nodeId=16359

- FIL Drupal node https://prod.cms.va.gov/node/16413/latest
       Preview: https://preview-prod.vfs.va.gov/preview?nodeId=16413

**Comment by saratorres2** [comment]
@moviedosoco I've published changes to the English, Spanish, and Tagalog pages, and am waiting for the updates to go live before moving ticket to validate.

**Comment by saratorres2** [comment]
@moviedosoco Updates to page are now live. @aprocik1 Work on this ticket is complete.

**Comment by moviedosoco** [comment]
@saratorres2 Thank you!
