### ISSUE TITLE
Determine LOE for migrating Separation Locations (BRD) endpoint [Oct 15]

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#92555]
## Issue Description
As a team member I want to know how much work there is to do (if any) to migrate the separation locations endpoint from EVSS to Lighthouse.

---
## Tasks
- [ ] See AC

## Acceptance Criteria
- [x] Document what was done and what work is remaining in order to migrate this endpoint
- [x] Estimate of how long this could take
- [x] Tickets are created for the migration with sufficient detail so we know where to start

## Additional Information
OCTO would like the EVSS endpoints migrated by February 2025. This is a hard deadline for OCTO.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aurora-a-k-a-lightning** [comment]
**Document what was done and what work is remaining in order to migrate this endpoint**
What was done:
2/6/2024: 
- we added BRD Provider to switch to LH in separation_locations endpoint

Work remaining:
1. test the LH BRD provider on staging
-- the complexity here is that the data call is wrapped in the redis cache.
-- is there a way to clear this cache and re-retrieve the data to test that this is working properly? 
-- we may be able to do this through the rails console
-- this may also not be necessary because the redis cache clears for a user, so we may just ahve to hit the page in the form and we'll be good.
2. Release Plan for Production (if we don't have one)
-- because LH BRD is already used in other parts of the application, the increments can be higher. 
-- the main thing to "monitor" is missing data on the frontend
--- what will the user see if this is missing?
3. ModProd? If desired. Not strongly recommended, but always good if paranoid.
4. Release to Production according to Release plan

**Estimate of how long this could take**
- The testing on staging should be a couple points worth of work, unless it is difficult to clear the redis cache/check if the new LH BRD provider was used in the call, which we can see in datadog 
-- the cache may be cleared due to time already for a staging user, so try that first.
- Release Plan: probably not very long as the endpoint is pretty small
- Release: increments can be higher

**Tickets are created for the migration with sufficient detail so we know where to start**
- otw

**Comment by aurora-a-k-a-lightning** [comment]
tickets for remaining brd work:
1. [Canary Launch for BRD #76274]( https://github.com/department-of-veterans-affairs/va.gov-team/issues/76274**_**_) (old, needs refining, but that _**is**_ the task)
2. [Staging Testing for Separation Locations feature in 526]()
