### ISSUE TITLE
Product Spike: Research Prefill of File Number and Direct Deposit

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#92554]
## Issue Description
Perform  product research around Prefill of File Number and Direct Deposit.
Context: our VBA stakeholders indicated these are the highest priority items of the additional prefill opportunities we presented them based on the Engineering research documented in this ticket.   https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/90771

---
## Tasks
- [ ] _Investigate what other teams have done around prefill in these areas.
- [ ] _Reach out to data governance team for their input on the best data source for these items.
- [ ] _Create implementation tickets if it looks feasible.

## Acceptance Criteria
- [ ] _Implementation ticket(s) craeted for prefill where it's feasible
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by matt4su** [comment]
Feedback from Data Governance council below.  I have sent a follow up message to Jason McGuire per their recommendation.

>Good Afternoon Matt,

 

I have confirmed that we do not yet have the points of contact for file number and direct deposit data beyond the information available in VASI (VA DGC is currently working to identify all Data Stewards at VA).

 

However, the VA Enterprise Data Catalog Team currently has metadata from the following 3 VBA systems:

 

Acronym

System Name

VASI ID

CRP

VBA Corporate Database

1153

LGY

Loan Guaranty

1489

VBA-EDW

VBA Data Warehouse

1689



The VA EDC team can help you with searching for specific data if it is in the systems mentioned above.   For example, here is a search from the VA EDC for direct deposit data on the above system:  [Search for direct deposit | Collibra Data Intelligence Platform](https://departmentofva.collibra.com/search?q=direct%2520deposit&d=c2de7042-2ac5-4820-a313-21af625cbc5d&ORGANIZATION=d02ae9dc-620d-4e38-baf3-89aff9ea21d3%2Cedabf9d2-a978-40f8-8722-8e16f2e39bad%2C88c512aa-3cd8-4263-b127-afdd88915617).  Please contact [@MCGUIRE, JASON J. (AMIDA TECHNOLOGY SOLUTIONS, INC.)](mailto:JASON.MCGUIRE1@va.gov) of the VA EDC team for additional information.

 

Hopefully this helps and please reach out if there is any additional information we can provide that would be helpful.  Again, thank you for proactively reaching out to us.

 

Respectfully,


Anne Klieve / VA DGC Executive Secretariat

 

 

Anne Klieve | PMP | CDMP | Six Sigma Black Belt

**Comment by matt4su** [comment]
Jason McGuire referred me to Steven Hamilton, the VASI information owner fro the CRP system.  I have reached out to Steven.

**Comment by aplatt-coforma** [comment]
Per @matt4su, this has been deprioritized at this point. We'll backlog this ticket until it becomes higher priority.
