### ISSUE TITLE
[Research] 10-10CG - Facility & Baseline: Hold Kick-Off call with Perigean and populate observer signup sheet

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#92575]
## Benefit to the Veteran
As a Veteran and/or Caregiver, I want to participate and provide feedback on VA.gov development, so that I know the changes made will work for us.

## Scope
Now that our research plan and convo guide is finalized and approved, we are ready to talk with our Perigean partners to clarify our needs and set up research sessions

## Tasks
- [x] Discuss questions, audience targets and other needs with the Perigean partner
- [x] Talk through the schedule to confirm Perigean requirements are met and the schedule is manageable
- [x] Create Sign-up sheet for Researcher, Note taker, and Observers on Slack Canvas
- [x] [PM] Reach out to Stakeholders with schedule, if they would like to observe any

## Acceptance Criteria
- We have held a kick-off call with Perigean to talk through the questions to ask in the survey and the audience we want to reach.

**Comment by jessicastump** [comment]
[Link to the Slack canvas observer sign up sheet here](https://dsva.slack.com/docs/T03FECE8V/F07M7PB62FL) - will post to the 1010 team channel once we have some scheduled :)
