### ISSUE TITLE
[IA Intake] <govcio-vebt>: <Statement of Assurance of Compliance with 85% Enrollment Ratios (VA Form 22-10215)>

### ISSUE THREAD

**Issue by ameliahackingVA** [department-of-veterans-affairs/va.gov-team#92591]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: govcio-vebt
- **OCTO product owner:** Darla van Nieukerk ([darla.vannieukerk@va.gov](mailto:darla.vannieukerk@va.gov))
- **Product name:** Statement of Assurance of Compliance with 85% Enrollment Ratios (VA Form 22-10215)
- **Product manager:**  Kara Ciprich ([kara.ciprich@va.gov](mailto:kara.ciprich@va.gov))
- **Slack channel:** [govcio-vebt-team](https://join.slack.com/share/enQtNzcwNTA1NDUwOTEwOS1iZDcxZmUwZGQ1ZjE4YWI4ODRjZTU1ZGY2NDA3ZjU1OTNjY2NjYWRiNTBjZDkwZTI2NDhmY2MzMDgzZjY5MjY0)
- **Dedicated content writer on your team (if you have one):** Garry Forbes @gforbes4 ([garry.forbes@va.gov](mailto:garry.forbes@va.gov))
- **Dedicated a11y specialist on your team (if you have one):** `Insert name and/or GH handle`
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [X] Digitizing a new form
- [ ] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?
This form is intended for school officials and administrators to submit (resources for schools); it is not designed for Veteran's to use.

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [X ] No
- [ ] I’m not sure

### Where are you at in your timeline?
We’ve initiated the digital transformation process for this form. This is connected to another form, 22-10216, which we initiated through the collaboration cycle. However, they will remain separate and will not be merged in the online system. We are aiming to have this pushed to production by the end of this year.

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [X ]  No
 
 **Note:** For an incremental launch, we use React widgets to display dynamic content. We'll need at least 2 weeks of extra time to coordinate the content for this and work with your engineer. [Learn more about our process for dynamic content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md). If your launch plans change, notify CAIA of the change as soon as possible so we can talk about how that will impact the timeline.

**If you are releasing incrementally:**
- **What dates do you anticipate starting and ending your incremental launch?** `Enter dates`
- **What is the name of your engineer who will build the React widget?** `Name`

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide a link to your Collaboration Cycle Request:
- [91664 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91664)

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Wireframes](https://www.figma.com/design/f9TussyZYnC5UVSnqBPJqC/VEBT-Form-22-10215%3A-Statement-of-Assurance?node-id=200-13014&node-type=canvas&t=Xfm3alb5e1NHe0R3-0)
- [User Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718211888145/62b605a599fa763fd3a91f46fb89b74f0748d1bb?wid=0-1718311983284&outline=open)
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-education-benefits-tools/Forms/22-10215/collab%20cycle/govcio-vebt_Form_22-10215_Product%20Outline.md)

## Next steps
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92143
- [ ] (IA Spec)[https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/school-admins-enrollment-reporting.md]
```

**Comment by scjwalker** [comment]
Hi @ameliahackingVA, may I check one thing about how you're setting up the digital version of 22-10215? Currently there are the downloadable versions of 22-10215 (the 85/15 compliance), and 22-10215a (extra space in case a school has too many programs for just the main form).

1. When you digitize the form, am I understanding correctly that 22-10215 and 22-10215a will become a single form flow, so there will be no digital version of 22-10215a?

2. Will there still be a downloadable pdf version of 22-10215a?

**Comment by ameliahackingVA** [comment]
1. That is correct, we are creating a flow that eliminates the need for a supplemental "extra pages" form. 
2. Yes, it will still be available for users that want to go the PDF route instead

**Comment by scjwalker** [comment]
@strelichl for this one as well, could we please add ticket(s) for creating the About page for this form, and adding the link to the digitized form to the 'Find a VA Form' search result? 
Mikki reviewed my draft IA Spec for this work, and flagged that those should be ticketed separately since they're not done by the product team.

**Comment by scjwalker** [comment]
The [IA Spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/school-admins-enrollment-reporting.md) is ready for the team.
This spec covers both the 85/15 Rule, and the 35% Exemption.

**Comment by mnorthuis** [comment]
IA spec is updated.  It has also moved, so please update your links. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/non-veteran/school-admins-enrollment-reporting.md
