### ISSUE TITLE
Content Edit: Ticket 90874

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#92609]
## Pain point:
The Functionality of building isolated applications page states that `continuousDeployment` flag is optional and enables continuous deployment when set to `true`. This information is incorrect and could lead developers to make the wrong decision when building.

## Issue Description
Per ticket [90874](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90874#issuecomment-2341583857), we need to correct the **table** on the [Functionality of building isolated applications page ](https://depo-platform-documentation.scrollhelp.site/developer-docs/functionality-of-building-isolated-applications) to show the correct information. 

**Specifically this section:**
---
<img width="868" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNS9GQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22437032667a70ac6ac27c68f50940b3b77a293c/image.png" alt="image.png" />

Should be updated as follows:

> **Name** `continuousDeployment` 
**Required** No 
**Description** Disables continuous deployment when set to `false`, otherwise enabled by default for applications on the [allow-list](https://github.com/department-of-veterans-affairs/vets-website/blob/main/config/changed-apps-build.json)
---
## Tasks
- [x] Review details of this ticket
- [ ] Copy page to the Draft Space
- [x] Make edits in table
- [x] Save changes 
- [x] Test the link
- [x] Prepare page for deployment

## Acceptance Criteria
- [x] Page will be updated with the correct information
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/92609?planning-poker) with Zenhub @BSmolensky @cmarion93 @taylojill

**Comment by taylojill** [comment]
Table updated. I found a 404 under the last heading. Message sent to Peter Hill and Nick Sprinkle requesting updated URL. Waiting for response.

**Comment by taylojill** [comment]
I deployed this page with a 404 under the Testing heading. Message sent to Peter Hill and Nick Sprinkle via Slack content channel requesting updated URL/link. Will update page once info is received.

**Comment by taylojill** [comment]
No response from SMEs on the 404. I removed the link and will update if information is provided.

**Comment by jknipes** [comment]
Work is complete, moving to _Closed_
