### ISSUE TITLE
Documentation Support: Endpoint Monitoring

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#92620]
## Issue Description
Matt Dingee needed to publish a new page today and this required the involvement of team members who were already assigned to working on deployment and finalizing tickets for the current sprint. Jill and Brian needed to make edits and IA configurations while corresponding with the page author.
This ticket is to document the work and allocation of manpower.

---
## Tasks
- [x] Review [Endpoint Monitoring 
](https://depo-platform-documentation.scrollhelp.site/developer-docs/endpoint-monitoring) draft 

- [x] Resolve issues with Scroll Content Quality Check
- [x] Resolve publishing issues
- [x] Make copy of page
- [x] Rename page
- [x] Resolve glitches in Scroll Viewport
- [x] Publish page

## Acceptance Criteria
- [x] New page published on Platform Website.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Tasks completed, acceptance criteria met, moving to _Closed_
