### ISSUE TITLE
GA4 Property Audit Cont.

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#92641]
### Description
 This ticket is to account for the work that we are doing for our audit of our Google Analytics 4 Property and BigQuery.

---

### Tasks

- [ ] Perform audit of Google Analytics 4 Property
- [ ] If needed, perform audit of Domo.
- [x] Log findings in postmortem

### Acceptance Criteria

- [x] Findings from audit have been shared in private Slack message.
- [ ] Findings and outcome have been logged in postmortem.

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt -- As this is ongoing work that will continue into our next sprint, I created a separate ticket for this to track this next sprint. 

- [Ongoing Work -- GA4 Property Audit Cont.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93612)

Note, I will be on the lookout for your Teams message on what audit work is remaining over our secure Teams chat.

FYI @dorseypa1
