### ISSUE TITLE
Edit: ESI Pages - Active Directory Federation Services

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#92646]
## User Stories
_"As a VFS Team member, I need to know the information on the External Service Integrations
is up-to-date and complete, so that I can build on va.gov with confidence"_

## Issue Description

The [External Service Integrations](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations) section of Platform Website contains pages with several formatting errors and missing information, as well as use of personal names. We need to edit the pages in this section.

## SME:

- Back End CoP - **Ryan McNeil**
---
- ### [Spreadsheet with comments for each page](https://docs.google.com/spreadsheets/d/1fmV4M-mV4wIVCPsxYzxK_c2KjsdlQaGepG1B9VwFQvE/edit?gid=0#gid=0)

### This ticket is for the editing of the 
[Active Directory Federation Services](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1888485505/Active+Directory+Federation+Services) page
---
## Tasks

- [x] Content team ticket assignee: Review page comments first
- [x] Add additional comments if necessary
- [x] Copy page and move copy to DRAFT Space (page **Copy** will not retain comments)
- [x] Review comments with SME
- [x] Make formatting corrections
- [x] With SME update information including any links
- [x] SME review Final Draft for accuracy
- [x] Prepare page for deployment

## Acceptance Criteria
- [x] Updates and corrections made
- [x] Page is ready for deployment 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
11/5 Jason mentioned the ESI tickets might be spread to the Back End CoP as the Product team has low capacity due to OOO, Tier 2 Support duty and FOIA request.

**Comment by jknipes** [comment]
Moving this ticket to 2 Sprints Out, as ESI tickets will be worked on with Back End CoP beginning Sprint 20

**Comment by jknipes** [comment]
[See Slack chat for initial conversation and suggested remedies](https://dsva.slack.com/archives/CL181NRJQ/p1738252096602729)

**Comment by ryan-mcneil** [comment]
I've determined the page is no longer needed. The technical content is no longer relevant, and the personal contacts are no longer desirable. If the service is for some reason re-integrated in the future, I'm confident proper contacts will be provided at that time.

**Comment by BSmolensky** [comment]
As part of the archiving process, I checked to see if there were any active incoming links to this page. There is one. Additional ticket created on the PCT board to remove that incoming link at some point in the future.

**Comment by BSmolensky** [comment]
All tasks complete. Page has been archived. This change is immediately reflected in Confluence but will not appear on the PW until the next SVP deployment.

**Comment by BSmolensky** [comment]
Acceptance criteria met. Page is ready to close.

**Comment by jknipes** [comment]
Closing ticket as _Done_
