### ISSUE TITLE
Test RES endpoint migration

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#92651]
## Issue Description
_The RES integration team is tracking toward an October 2 launch of the new RES endpoint for VR&E. Va.gov needs to send test VR&E payloads to the new endpoint to ensure we are ready to migrate on 10/2/2024._

---
## Tasks
- [ ] Update any existing monitors and/or create new monitors
- [ ] Send VR&E payload to all RES environments
- [ ] Coordinate testing with RES Team
   - Hope Lam
   - Jon Wilson
   - Kalpana Reddy
   - Keith Story
   - Nabeel Malik
   - Michael Lasutschinkow

## Acceptance Criteria
- [ ] RES signs off on all testing requirements
- [ ] Existing monitors have been reviewed and updated or
- [ ] New monitors have been created
---
