### ISSUE TITLE
FE | Appointment Reminder PHI/PII | Add Facility and Clinic Details Checkbox for Health Appointment Reminders in Notification Settings

### ISSUE THREAD

**Issue by asiisii** [department-of-veterans-affairs/va.gov-team#92656]
## Summary

We need to implement a new functionality for the **"Your Health Care"** communication group on the **Notification Settings** page, specifically for the **"Health appointment reminders"** item. This item currently has two notification channels:
- **Notify me by text** (already available in production)
- **Notify me by email** (currently behind the `profileShowMhvNotificationSettingsEmailAppointmentReminders` flipper toggle)

Each channel has a checkbox with labels:
- **Notify me with text**
- **Notify me with email**

### New Functionality

- [ ] **Add New Section Under Channel List:**
  - [x] #96296
  - [ ] **Description:** (Grayed out) "The clinic name may include the type of care you're receiving, such as 'cardiology.'"
  
- [ ] **Add New Checkboxes:**
  - [ ] "Include facility and clinic details in email notifications"
  - [ ] "Include facility and clinic details in text notifications"

- [ ] **Conditional Display:**
  - [ ] If the **Notify me by email** checkbox is selected, display only the **"Include facility and clinic details in email notifications"** checkbox.
  - [ ] If the **Notify me by text** checkbox is selected, display only the **"Include facility and clinic details in text notifications"** checkbox.
  - [ ] If both the **Notify me by email** and **Notify me by text** checkboxes are selected, display both **"Include facility and clinic details in email notifications"** and **"Include facility and clinic details in text notifications"** checkboxes.
  - [ ] If neither checkbox is selected, hide the entire section, including the header, description, and both checkboxes.

- [ ] **New Feature Toggle:**
  - [ ] Add and use the `profileShowNotificationSettingsAppointmentPhiPiiPermission` toggle to control the visibility of the new section.
  - [ ] Ensure the section (header, description, and the two facility/clinic checkboxes) is only displayed when this toggle is turned on and at least one of the channel checkboxes (**Notify me by email** or **Notify me by text**) is checked.
  
> **ℹ️ Info:**  
> The section should only be visible when at least one of the channel checkboxes (**Notify me by email** or **Notify me by text**) is checked, and the newly created toggle is turned on.

## Tasks

- [ ] **Detailed Behavior:**
  - [ ] Ensure that the new section is only shown when one of the first two channel checkboxes is checked.
  - [ ] Display the new section when "Notify me by email" is checked with the "Include facility and clinic details in email notifications" checkbox.
  - [ ] Display the new section when "Notify me by text" is checked with the "Include facility and clinic details in text notifications" checkbox.
  - [ ] Hide the section when both of the main channel checkboxes are unchecked.
  - [ ] Ensure that the "Notify me by email" checkbox is only visible when the `profileShowMhvNotificationSettingsEmailAppointmentReminders` toggle is enabled.

- [ ] **Mobile Friendliness:**
  - [ ] Ensure that the new section and its elements are responsive and display correctly on mobile devices.

- [ ] **Redux Store:**
  - [ ] Verify that the data for the new checkboxes is correctly stored in the Redux store along with existing notification settings.

## Backend Integration Questions

> [!WARNING]
> VA Profile's work will block us - PoC is Autumn A. 

Before we can fully implement this functionality, we need to clarify the following with the backend team:

- **Data Structure:** How is the data for this new header, description, and checkboxes coming from the backend? 
  - We need to know how to link these new checkboxes to the **Health appointment reminders** communication item.
  - How will we iterate over the data to generate the correct labels for "Include facility and clinic details in email notifications" and "Include facility and clinic details in text notifications"?

- **Data Identification:** How will the frontend identify the correct checkbox for email vs text notifications? 
  - When the user clicks the "Include facility and clinic details in email notifications" checkbox, how do we know it is specifically for email and not text (and vice versa)?

- **Payload:** What does the backend want the payload to look like when these new checkboxes are updated? 

We need these details to ensure smooth and accurate implementation of the frontend functionality.

## Related Design Ticket

- [Design Ticket #86208](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86208)
- [Related figma file](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=736-2743&node-type=canvas&t=eUFrQjLm8oMbBjzl-0)

## Acceptance Criteria 
- [ ] we have a new PHI/PII appointment reminder permission behind a feature flag (should be able to test with user 202 I think that has healthcare)

**Comment by mtcA6** [comment]
@asiisii 
Added the figma file.

My only question is related to this section:
![image](https://github.com/user-attachments/assets/fb6341eb-fcd4-47ed-a26f-0ba0986708b6)

Want to make sure when we go to build this we don't have any confusion about the conditional reveal. 
If [a channel] is selected the user should only see the permission related to [a channel]. Want to make sure the conditional review only reveals the related field. The only time the conditional reveal should show the permission for both  channels is if both channels are selected.

**Comment by mtcA6** [comment]
and I'm wondering if we need another toggle :/

**Comment by asiisii** [comment]
> @asiisii Added the figma file.
> 
> My only question is related to this section: ![image](https://private-user-images.githubusercontent.com/129431463/366541936-fb6341eb-fcd4-47ed-a26f-0ba0986708b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNzI4NDUsIm5iZiI6MTcyNjA3MjU0NSwicGF0aCI6Ii8xMjk0MzE0NjMvMzY2NTQxOTM2LWZiNjM0MWViLWZjZDQtNDdlZC1hMjZmLTBiYTA5ODY3MDhiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxNjM1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjY2OTNhOWI3NDQ5MGUxNjIxNTcyYmJlY2MzNDJmYjNiNjdiOWIwMTBlNTdmM2EzMzE0MTc0ODczZTBiMTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PNleJ4NgMIJKKzXEnXssM73UK66iK9PjRba5RWwvaII)
> 
> Want to make sure when we go to build this we don't have any confusion about the conditional reveal. If [a channel] is selected the user should only see the permission related to [a channel]. Want to make sure the conditional review only reveals the related field. The only time the conditional reveal should show the permission for both channels is if both channels are selected.

@mtcA6 Thank you for reviewing the ticket. I just updated the conditional display section to be more clear and descriptive. 
And yes, we will need a new toggle. I was going to ask you what we are going to name it during our sprint planning

**Comment by mtcA6** [comment]
thoughts on `profileShowNotificationSettingsAppointmentPhiPiiPermission`

**Comment by mtcA6** [comment]
I believe this was duplicated by: https://github.com/department-of-veterans-affairs/va.gov-team/issues/97679
