### ISSUE TITLE
Maintenance Bot Documentation

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#92654]
## Description 
A new maintenance bot was created in #platform-tech-team-support and we need to document how the bot works while also documenting the process that support follows to use it.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Identify where the maintenance bot information should live 
- [x] Ensure that it is either documented here as well or pointed to [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2434433157/Creating+Maintenance+Windows+in+PagerDuty)
- [x] Send to the bot creator to ensure all documentation is accurate 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Complete. Closing!
