### ISSUE TITLE
Global | Replace momentjs

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#92666]
## Value Statement

**_As a_** VA team member
**_I want to_** ensure that all VA applications are not dependent on a deprecated library (momentjs)
**_So that_** we can use a maintained library (date-fns) which is small and more performant

## Background Context

Momentjs is deprecated, but is still being used by numerous apps and platform within the vets-website repo. Platform has recommended using date-fns in place of moment.

Related tickets:
- #22635 
- #90200

## Acceptance Criteria

- [ ] Platform switched to using date-fns
- [ ] All applications use date-fns
- [ ] Notify teams that moment has been removed
- [ ] Moment and moment-timezones removed as a dependency

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [ ] Update platform date utilities to use date-fns
- [ ] Add global date utilities that apps can use, e.g. date comparisons, formatting, etc
- [ ] Investigate and implement a method to get date-fns to behave similarly to moment in terms of time zones
- [ ] Compile a list of apps using moment
- [ ] Replace moment usage in all apps (in multiple small PRs?)
- [ ] Replace moment-timezones with date-fns equivalent
- [ ] Remove moment as a dependency
- [ ] Remove moment-timezones as a dependency

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
Molly to start this today

**Comment by Mottie** [comment]
Molly working on platform changes

**Comment by kayline** [comment]
Current branch lives here: https://github.com/kayline/vets-website/tree/upgrade-momentjs-platform

Moment has been removed from utilities, but other parts of platform wrote their own date helpers that still use Moment

**Comment by kayline** [comment]
Implementation files in `src/platform` calling Moment:
 - /Users/molly/workspace/personal_forks/vets-website/src/platform/user/profile/vap-svc/util/personal-information/personalInformationUtils.js
 - /Users/molly/workspace/personal_forks/vets-website/src/platform/site-wide/announcements/selectors.js
 - /Users/molly/workspace/personal_forks/vets-website/src/platform/site-wide/moment-setup.js
 - /Users/molly/workspace/personal_forks/vets-website/src/platform/pdf/templates/veteran_status.js
 - /Users/molly/workspace/personal_forks/vets-website/src/platform/monitoring/DowntimeNotification/util/helpers.js
 - and all test files for these use cases
