### ISSUE TITLE
Discovery: Cleanup the Sentry RDS Storage 

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#92665]
This ticket is a spinoff of [91712](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91712), for Sprint 10. We need to do a cleanup of the Sentry RDS Storage before the storage amount can be further decrease.

## User Story
As the Managers and Developers of the VA Platform, 
We need to cleanup the RDS Storage in Sentry, 
So that we can lower the storage amount from 1.5Tb to an amount that will be determined.

## Issue Description
The [ticket to decrease the RDS storage](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91712) reached a blocker in that the storage can only be lowered to 1.5Tb, then a cleanup needs to occur in order to further lower the storage.  The original ticket was triggered due to because of the issues (up to 6mm according to [this Slack thread](https://adhoc.slack.com/archives/C045LCF8WU8/p1711134858385029)) that are taking up space. 

---
## Tasks
- [ ] Clean up RDS storage in Sentry
- [ ] Test as required
- [ ] Adjust monitors as necessary, once the findings between past and current storage usage has been established. 
- [ ] Document what was deleted and the overall process and link to this ticket

## Acceptance Criteria
- [ ] All obsolete data is deleted from the Sentry RDS Storage
- [ ] Documentation on what was deleted is captured and shared as required
- [ ] Any testing has been completed successfully with no errors

**Comment by jennb33** [comment]
Closing this ticket as it is complete.
