### ISSUE TITLE
Decrease EKS prod ASG and adjust Puma

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#92667]
During PACT we increased our min ASG size for an expected traffic spike. We can now lower this down and adjust pods appropriately.

## Tasks

- [ ] Lower min ASG value incrementally
- [ ] Adjust min pods for bulkheads
- [ ] Monitor backlog and other relevant metrics to ensure performance

## Acceptance Criteria

- [ ] Auto scaling group auto scales with traffic and handles deploy events without a backlog

**Comment by ericboehs** [comment]
Postponed for a new upcoming PACT ACT surge.
