### ISSUE TITLE
[Frontend] Veterans need to be alerted if they they haven't placed an order for batteries in the past 2 years or only have rechargeable aids

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#9267]
## User Story or Problem Statement
Our team recently discovered that the DLC will not be able to send us data identifying rechargeable hearing aids. How might we create an empty state for Veterans who order hearing aid accessories for their rechargeable devices but do not order batteries?

There are two use cases to consider:

- Veteran has not placed an order for batteries in the past 2 years
- Veteran only has rechargeable hearing aids on file

## Goal
_An empty state for the 'battery selection' page notifying the Veteran that the VA does not have battery-eligible devices on file and provide next steps if that information is incorrect_

## Objectives or Key Results this is meant to further
- _MDT development_
---
## Tasks
- [ ] _Develop an empty state for the 'battery selection' page following [the InVision mockup](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/418131333) proposed by the design team_
(Please reference [the documentation about the battery selection screens](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-battery-selection.md#prototype-c2-p1-battery-selection) as needed)
- [ ] _Review the UI with the design team_

## Acceptance Criteria
- [ ] _An empty state for the 'battery selection' page is developed_
- [ ] _The empty state's UI has been reviewed with the design team_
---

**Comment by mr0sari0** [comment]
PR for this:

https://github.com/department-of-veterans-affairs/vets-website/pull/12763
