### ISSUE TITLE
Explore pulling Settings automatically from ENV vars

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#92671]
Explore pulling from ENV automatically based on name. For example, `Settings.rack_timeout.wait_timeout` would pull from the `SETTINGS__RACK_TIMEOUT__WAIT_TIMEOUT` ENV var.

## Tasks

- [x] Determine feasibility of this approach
- [ ] ~Create ticket(s) for implementing approach~

## Acceptance Criteria

- [x] Approach has been considered well enough to be continued or abandoned.

## Additional Notes

Replacing all Settings with their appropriate ENV var is out of scope.

**Comment by ericboehs** [comment]
We're using the config gem which has this feature built in. In fact we have it enabled. The only thing missing is that we need to switch the `env_separator` to `__` from `.` and update a few files.

**Comment by ericboehs** [comment]
Updated here: https://github.com/department-of-veterans-affairs/vets-api/pull/18466
