### ISSUE TITLE
Make updates to proposed CD process to address concerns

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#92676]
## Issue Description
When discussing the CD solution with Jeff Keene, some concerns were raised about the concept of deploying straight to production. An alternative solution was raised to allow apps to deploy at their own pace, but still stop at staging and have them manually deploy to prod. These changes should be reflected in our desiign doc for our proposed solution.

---
## Tasks
- [x] Update design doc with proposed changes
- [x] Resubmit for approval

## Acceptance Criteria
- [x] The new design doc has been approved or additional changes are ticketed to be made.
