### ISSUE TITLE
[Design] My VA: Brainstorm workshop concepts

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#92694]
## Background
During our team prioritization exercise we discussed the notion of conducting a design workshop to think through the future of My VA. This ticket is to set aside time for Matt to brainstorm workshop concepts/ideas and goals for the workshop.

## Tasks
- [x] Perform additional cursory research, prelim. documentation as needed
- [x] Discussion with Auth. Exp. stakeholders
- [x] Draft workshop plans
- [x] Review with Design
- [x] Review with Product

## Acceptance Criteria
- [x] Draft plan created
- [x] Draft plan reviewed by Design and Product

**Comment by mattmarino-adhoc** [comment]
This ticket will now also include some additional planning, research documentation

**Comment by mattmarino-adhoc** [comment]
This is going to need to continue on to next sprint, as we'll need more feedback and info before being able to proceed with these workshop efforts.

**Comment by mattmarino-adhoc** [comment]
Meetings scheduled for 10/2 and 10/3 to discuss plans.
