### ISSUE TITLE
Impact assessment of GitHub Transfer app not supported by DataDog

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#92701]
## User Story
As the Managers and Developers of the VA Platform, 
We need to assess the impact of learning that the GitHub Transfer app is not supported by DataDog,
So that we can create a plan that can mitigate this issue.

## Issue Description
Per @Kshitiz-devops in a Slack thread, we learned on 9/11/2024 that the Github Transfer app is not supported by Datadog, the Platform's major security app. 
In order to have an app made, we need to have an admin create the app instead. Paul is trying to get access.

## Tasks
- [ ] Need to assess the impact of DataDog not supporting GitHub Transfer on the VA Platform
- [ ] Need to determine a process to have a Transfer app created so that DataDog is supported
- [ ] Do we need to have an admin do it? how frequently? 
- [ ] Document as necessary and include link in this ticket

## Success Metrics
We have created a Create Transfer App process

## Acceptance Criteria
- [ ] There will be a documented process for creating a Transfer app to DataDog
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
10/9/2024 update: @Kshitiz-devops is still waiting for a response from DataDog to address this issue.

**Comment by jwoodman5** [comment]
We are blocked until we get a response from Datadog. Putting this on hold until we get a response, then will pull it in.
