### ISSUE TITLE
Inform users that POA requests will expire 60 days after digital submission

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#92705]
## Background
Jen has advised us to assume the policy for a POA request to expire after 60 days has been approved, and to start incorporating this into our designs.

This makes the most sense to mention in:
1. The end of the Appoint a Rep flow, on the Next Steps page after digital submission 
2. The Widget "pending rep" states
3. VA Notify email notifications -- thinking we can first get our designs in order then engage CAIA for help with the email notifications, based on where we land with our designs.

Mayyybe the Introduction page? But this could be information overload at that stage.

I don't think this will affect Find a Rep -- current or future versions.

## Tasks
- [x] Incorporate mentions of the POA request expiring after 60 days in the Appoint experience
- [x] Incorporate mentions of the POA request expiring after 60 days in the Widget experience

## Acceptance Criteria
- [x] ARM products have mentions of the POA request expiring 60 days after submission.
- [x] Designs are ready for CAIA contributions -- content on the products as well as guidance in the VA Notify email notifications.

**Comment by mtri** [comment]
[Slack discussion](https://dsva.slack.com/archives/C05L6HSJLHM/p1726698670370119)
[Figma designs](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=10596-233335&node-type=canvas&t=k01fawK2X7C9taSa-11)
[CAIA content request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65809#issuecomment-2369626832)
