### ISSUE TITLE
[CST] Subheader in claim letters page should be Source Sans Pro

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#92700]
### Bug

I noticed one bug in the 5103 subheader implementation. It looks like the subheader font has been changed to Bitter. It should be Source Sans Pro.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3pLQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3b5774263ee671f6ac46568a1399588286fb254/Screenshot%202024-09-11%20at%202.38.54%E2%80%AFPM.png" alt="Screenshot 2024-09-11 at 2.38.54 PM.png" />

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Change subheader from Bitter to Source Sans Pro_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Subheaders for all claim letter list items are updated to Source Sans Pro_

**Comment by skylerschain** [comment]
From @davidakennedy: 

> "It does need to be a h2. That's because it's important that we pair the date with the letter type so AT users understand how each heading on the page is different. There's no accessibility issue with changing the font family via class."

@harshil1793 So let's override via class.
