### ISSUE TITLE
Domo dashboard outline for OKRs

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#92712]
## Background
Once our OKRs are finalized, I'd like to outline a Domo dashboard for visualizing the OKRs. This will help guide Analytics in implementation and ultimately provide an easily way for stakeholders to track our OKRs.

## Tasks
- [ ] Outline OKRs in a Domo dashboard
- [ ] Share with the team for feedback
- [ ] Incorporate team's feedback

## Acceptance Criteria
- [ ] A Domo dashboard has been outlined and is ready to present to Analytics
