### ISSUE TITLE
[ANALYTICS] Create new Health Services content "LIST & PLAYBOOK" for VA Montanta System Part 1 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9276]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN 19 Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Fort Harrison VA Medical Legacy Site](https://www.montana.va.gov/locations/directions.asp)

## TASKS: See below list of Stories
* Part 1
- [ ] Anaconda VA Clinic
- [ ] Benjamin Charles Steele VA Clinic
- [ ] Bozeman VA Clinic
- [ ] Cut Bank VA Clinic
- [ ] David J. Thatcher VA Clinic
- [ ] Fort Harrison VA Medical Center
- [ ] Glasgow VA Clinic

## Definition of Done 
- [ ] Validated list of all SYSTEM and FACILITY Health Services_
- [ ] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* Anaconda VA Clinic
* Benjamin Charles Steele VA Clinic
* Bozeman VA Clinic
* Cut Bank VA Clinic
* David J. Thatcher VA Clinic
* Fort Harrison VA Medical Center
* Glasgow VA Clinic

- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [ ] _Archived in Github and/or SharePoint for review by Product Lead and PAOs
