### ISSUE TITLE
CY3 | VRE 1B | Pull json data to confirm pdf data

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#92764]
## Issue Description
_A subset of VRE 1B pdfs include claimant info that does that match other info on the claim. Example: Pamela is listed as the claimant but Kristy's ssn is listed and the two have no relation to each other. To verify that the info included on the pdfs was correct, the VBA has requested that we pull the raw claim data and verify it matches what was on the pdf._

A full list of claims is on [sharepoint](https://dvagov.sharepoint.com/:x:/r/sites/CodeYellow/Shared%20Documents/CY%203/CY3%20Secure%20Folder/VR%26E/CY3_VRE1B_RESULTS_20240826.xlsx?d=wc4fa4697c4384db8a774bcdfac52cd69&csf=1&web=1&e=bLvWeG)
). See the "records with issues" tab and the claims highlighted in red. Each of those 12 claims need to be examined.

---
## Tasks
- [ ] Pull json data for 12 claims marked as mismatching

## Acceptance Criteria
- [ ] Confirm that pdfs that were generated match the raw data that the user submitted
- [ ] Add notes to spreadsheet indicating findings for each claim
- [ ] Collect jsons into a file and provide to VBA
---
