### ISSUE TITLE
Request the generated PDF when user advances from Review page

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#92779]
## Background
When a user clicks "Continue" on the review page, we will need to get the generated PDF of the completed form so that the user can successfully download it on the next page (the Download page).

The frontend for building these pages has been handled in these tickets:
- Review page #91411
- Download page #91412

And the backend for PDF generation has been addressed in these tickets:
- New endpoints for 21-22/21-22a PDF generation #82841
- Generate an accessible PDF of the completed 21-22/21-22a for a user to download #82223
- Broaden request specs for 2122 and 2122a PDF generation endpoints #89429

## Tasks
- [ ] Hit the PDF endpoint, for the relevant form
- [ ] Handle the response
- [ ] Save to local storage
- [ ] Send along the VSO representative or VSO IDs (so the backend can lookup their contact information)

## Acceptance Criteria
- [ ] When a user is taken to the Download page, the PDF will be available for download and the user can successfully download it.
- [ ] The PDF is able to surface a VSO or VSO Rep's contact info for the 21-22

**Comment by holdenhinkle** [comment]
Colin created a PR to update the json request body sent to the pdf generation endpoint to match what's the endpoint is expecting.
