### ISSUE TITLE
Add urls to MVP scope page in Figma

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#92776]
## Tasks

Follow Platform Content Guidelines for url paths. 

- [x] Review platform guidelines for url paths
- [x] Add url paths for each page in the MVP page Figma file 
- [x] Review with Peter (and Appts FE Team) to ensure consistency. Url paths are also documented in their git repo today. So, that can be reviewed as well. 

## AC

- [x] Page paths are documented as annotations on each page in Figma
- [x] Communicate to engineers that these are completed

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92776?planning-poker) with Zenhub @cgednalske

**Comment by benbrasso-agile6** [comment]
Reviewed during SME Sync on Sept 24, 2024. URLs are good - https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2145-37798&t=tcGErNs27ZHULCEu-4

**Comment by benbrasso-agile6** [comment]
Created FE ticket - https://github.com/orgs/department-of-veterans-affairs/projects/1323/views/1?sliceBy%5Bvalue%5D=department-of-veterans-affairs%2Fva.gov-team%2362496&pane=issue&itemId=80950403
