### ISSUE TITLE
[ANALYTICS] Create new Health Services content "LIST & PLAYBOOK" for VA Eastern Oklahoma MC [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9278]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN 19 Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Eastern Oklahoma (Muskogee) VA Medical Legacy Site](https://www.muskogee.va.gov/)

## TASKS: See below list of Stories
- [ ] Ernest Childers VA Outpatient Clinic
- [ ] Jack C. Montgomery VA Medical Center
- [ ] Jack C. Montgomery East VA Clinic
- [ ] McAlester VA Clinic
- [ ] McCurtain County VA Clinic
- [ ] Tulsa Eleventh Street VA Clinic
- [ ] Vinita VA Clinic
- [ ] Yale Avenue VA Clinic

## Definition of Done 
- [ ] Validated list of all SYSTEM and FACILITY Health Services_
- [ ] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* Ernest Childers VA Outpatient Clinic
* Jack C. Montgomery VA Medical Center
* Jack C. Montgomery East VA Clinic
* McAlester VA Clinic
* McCurtain County VA Clinic
* Tulsa Eleventh Street VA Clinic
* Vinita VA Clinic
* Yale Avenue VA Clinic
- [ ] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [ ] _Archived in Github and/or SharePoint for review by Product Lead and PAOs
