### ISSUE TITLE
Temporary  accredited_entities_for_appoint_temp endpoint

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#92797]
## Background
We are currently unable to hit OGC's Accreditation API on vets-api Staging and Production environments.

To move forward with our Appoint MVP release, where users will need to search for individual/organizations, we will need a temporary version of the `accredited_entities_for_appoint_temp` endpoint that relies on legacy representatives and organizations tables. 

_Note: When vets-api Production can hit the OGC Accreditation API, we can pursue our ideal/final solution with the originally intended endpoint `accredited_entities_for_appoint`._

## Tasks
- [x] ~Create two new models (one for individuals and one for organizations) in our `representation_management` module~ Will use existing models in the Veterans module
- [ ] Create a new controller to handle this route
- [ ] Create a new serializer 
- [ ] Write the tests

## Acceptance Criteria
- [ ] Users can search for individual reps or organizations at the beginning of Appoint a Representative.

**Comment by jvcAdHoc** [comment]
[draft pr](https://github.com/department-of-veterans-affairs/vets-api/pull/18659)

**Comment by oddball-lindsay** [comment]
This temporary endpoint is called `original_entities`
