### ISSUE TITLE
Replace moment with date-fns in Combined Debt Portal and Verify Date Formatting Consistency

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#92800]
### Overview

We need to replace the usage of `moment` with `date-fns` in the Combined Debt Portal. The key areas to focus on are components and pages where `moment` is used for date formatting and calculations, ensuring that date functionality remains consistent after the update.

Below is a list of components and pages that currently use `moment`:

- **Unit Tests**:
  - `combinedHelpers.unit.spec.js`
  
- **Utils**:
  - `helpers.js`
  
- **Components**:
  - `Alerts.jsx`
  - `DebtLettersTable.jsx`
  - `HistoryTable.jsx`
  - `DebtDetails.jsx`
  - `DownloadStatement.jsx`
  - `HTMLStatementLink.jsx`
  - `StatementCharges.jsx`

- **Containers**:
  - `HTMLStatementPage.jsx`

### Key Functions to Verify:

The following functions, which involve date calculations and formatting, must be tested to ensure no behavioral changes after the migration to `date-fns`:

```js
// Calculate Due Date
export const calcDueDate = (date, days) => {
  return moment(date, 'MM-DD-YYYY')
    .add(days, 'days')
    .format('MMMM D, YYYY');
};

// Verify Current Balance by comparing due date
export const verifyCurrentBalance = date => {
  const currentDate = moment();
  const dueDate = calcDueDate(date, 30);
  return currentDate.isSameOrBefore(dueDate);
};

// Sort Statements by Date
export const sortStatementsByDate = statements => {
  const dateFormat = 'MM-DD-YYYY';
  return statements.sort(
    (a, b) =>
      moment(b.pSStatementDate, dateFormat) -
      moment(a.pSStatementDate, dateFormat),
  );
};
```

### Tasks:

- [ ] Replace all `moment` imports with `date-fns` in the listed components and containers.
- [ ] Update the above key functions (`calcDueDate`, `verifyCurrentBalance`, `sortStatementsByDate`) to use `date-fns` equivalents.
- [ ] Ensure date formatting and calculations remain consistent, particularly the format `MMMM D, YYYY` and comparisons.
- [ ] Run unit tests and perform manual testing on date-related functionality in the debt portal to ensure no regressions.

### Acceptance Criteria:

- [ ] All instances of `moment` have been replaced by `date-fns`.
- [ ] Date functionality and formatting remains consistent after the migration.
- [ ] Unit tests pass successfully with the new implementation.

**Comment by Dr-Pongo** [comment]
Sister ticket for CDP:
- **[FSR] Replace moment with date-fns in Financial Status Report and Verify Date Formatting Consistency [#94327](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94327)**
