### ISSUE TITLE
[ANALYTICS] Create new Health Services content "LIST & PLAYBOOK" for VA Oklahoma City MC [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9280]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN 19 Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Oklahoma City VA Medical Legacy Site](https://www.oklahoma.va.gov/)

## TASKS: See below list of Stories
- [x] Ada VA Clinic
- [x] Altus VA Clinic
- [x] Ardmore VA Clinic
- [x] Blackwell VA Clinic
- [x] Enid VA Clinic
- [x] Lawton VA Clinic
- [x] North May VA Clinic
- [x] Oklahoma City VA Medical Center
- [x] South Oklahoma City VA Clinic
- [x] Stillwater VA Clinic
- [x] Wichita Falls VA Clinic

## Definition of Done 
- [ ] Validated list of all SYSTEM and FACILITY Health Services_
- [ ] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* Ada VA Clinic
* Altus VA Clinic
* Ardmore VA Clinic
* Blackwell VA Clinic
* Enid VA Clinic
* Lawton VA Clinic
* North May VA Clinic
* Oklahoma City VA Medical Center
* South Oklahoma City VA Clinic
* Stillwater VA Clinic
* Wichita Falls VA Clinic

- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [ ] _Archived in Github and/or SharePoint for review by Product Lead and PAOs
