### ISSUE TITLE
[ANALYTICS] Create new Health Services content "LIST & PLAYBOOK" for VA Salt Lake City MC [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9281]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN 19 Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Salt Lake City VA Medical Legacy Site](https://www.saltlakecity.va.gov/)

## TASKS: See below list of Stories
- [ ] Elko VA Clinic
- [ ] George E. Wahlen VA Medical Center
- [ ] Idaho Falls VA Clinic
- [ ] Ogden VA Clinic
- [ ] Orem VA Clinic
- [ ] Pocatello VA Clinic
- [ ] Price VA Clinic
- [ ] Roosevelt VA Clinic
- [ ] St. George VA Clinic
- [ ] Weber County VA Clinic
- [ ] Western Salt Lake VA Clinic

## Definition of Done 
- [ ] Validated list of all SYSTEM and FACILITY Health Services_
- [ ] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* Elko VA Clinic
* George E. Wahlen VA Medical Center
* Idaho Falls VA Clinic
* Ogden VA Clinic
* Orem VA Clinic
* Pocatello VA Clinic
* Price VA Clinic
* Roosevelt VA Clinic
* St. George VA Clinic
* Weber County VA Clinic
* Western Salt Lake VA Clinic

- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [ ] _Archived in Github and/or SharePoint for review by Product Lead and PAOs
