### ISSUE TITLE
[FSR] BE - Housing expense feature flag deprecations (After 11/12/24)

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#92821]
### To be completed _after_ November 12, 2024
`financial_status_report_expenses_update` reached 100% on 9/12/24, so we can deprecate the legacy functionality roughly 60 days after, since (ideally) no in progress FSR will have this flag set to false so the feature flag can be safely removed. 

**FE deprecation ticket:**
- department-of-veterans-affairs/va.gov-team#92819

**FE implementation:**
- department-of-veterans-affairs/va.gov-team#68302
- department-of-veterans-affairs/va.gov-team#83576

Feature flag implementations:
- [vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/29563)
- [vets-api](https://github.com/department-of-veterans-affairs/vets-api/pull/16623)

## Tasks
- [ ] Confirm no in progress FSR has `financial_status_report_expenses_update` set to true
- [ ] Remove the legacy functionality from BE functions
- [ ] Remove feature flag definition on `vets-api` (_after_ `vets-website` merge)
- [ ] Regression test to confirm functionality is still solid

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] `financial_status_report_expenses_update` is removed from BE 
- [ ] Housing expense update is the new default

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
Confirm housing expense checklist is no longer included in the FSR and the new default is the single input. 

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by digitaldrk** [comment]
PR for cached copays submitted:
https://github.com/department-of-veterans-affairs/vets-api/pull/22112

**Comment by digitaldrk** [comment]
Seems like we're carrying this over. Got some feedback on the FE PR asking for changes.

Here's the PR: https://github.com/department-of-veterans-affairs/vets-website/pull/36550

**Comment by digitaldrk** [comment]
This is still in code review. Andrew sort of picked it up and he got pulled into Digital Dispute.
