### ISSUE TITLE
Remove and change content that tells Veterans they can file again

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#92831]
## Description 

Veterans can't file another claim for the day. Need to change content on the success page and any other end pages that are using this content. 

## Tasks

- [x] Make content change to remove reference of filing again. [Wireframe](https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=3432-3868&t=V3REdzVVwV1atRgK-4).
- [x] Ensure no other pages need this same change. 

## AC

- [x] Final wireframe and final content
- [x] Let FE know there's a new ticket for them to work on to implement this change

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92831?planning-poker) with Zenhub @zach-park

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92831?planning-poker) with Zenhub @cgednalske

**Comment by loripusey** [comment]
@zach-park can you point?

**Comment by zach-park** [comment]
> @zach-park can you point?

Done!

**Comment by benbrasso-agile6** [comment]
@loripusey created FE ticket for this small content change on the /complete page - https://github.com/orgs/department-of-veterans-affairs/projects/1323/views/1?sliceBy%5Bvalue%5D=department-of-veterans-affairs%2Fva.gov-team%2362496&pane=issue&itemId=80938776
