### ISSUE TITLE
[FE, QA] 10-10CG - Improvement: Explore Secondary CGs when Yes, then No is selected

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#92834]
## Benefit to the Veteran
As a Veteran/Caregiver, I want the application to perform according to my selections, so that I am confident in the data that I have entered and want included on the form.

## Background
Test finding from CG tech team:
>- Gaspare brought up that SCG 1 and 2 issues
>      - Weird thing happened.
>      - Enter primary CG, then select Yes and enter secondary CG, select yes to add additional secondary CG, then go back to select No to secondary CG (not the "additional), the form retains the info on additional secondary CG
>      - Then the user can move forward through the form after going back to select No on secondary CG, but the form does not flow through the additional secondary CG pages, nor does it allow to remove the additional secondary CG input
>      - Ideal function: application will either remove all secondary CGs when No is selected at any time (including after going back through the form).

## Scope
- Set the form to remove all identified secondary caregivers when the initial "Do you want to add a secondary caregiver" question is answered No at any time before submission

## Tasks
- [x] Update UI to remove all secondary and additional secondary caregiver data when the initial "Do you want to add a secondary caregiver" question is answered No at any time before submission
- [x] Validate that any time this question is answered No, even if data has been entered for a secondary and/or additional secondary caregiver, that all the secondary/additional secondary caregiver data has been deleted/removed from the form on submit
- [x] QA/PM to validate page flow and functionality
     - Signoff in the comments is required prior to launch
- [x] PM to inform CG stakeholders of the update and validation
- [x] Launch to production

## Acceptance Criteria
- The 10-10CG form has been updated to ensure all secondary caregiver data is removed when the initial secondary caregiver question is answered No.

**Comment by longmd** [comment]
@allanto-ah , this one is ready for QA review. Should be a quick review for this one. [Here is the Review Instance link](http://22a3ee48c862d075753b16d04995ecb4.review.vetsgov-internal/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg/)

**Comment by allanto-ah** [comment]
Environment: RI

Looks good in the Review Instance. Once this goes to staging, will do an E2E with CARMA

**Comment by longmd** [comment]
We should be able to do e2e with CARMA from the RI using +36--Wesley Watson Ford.

**Comment by allanto-ah** [comment]
Oh hmm, I submitted a couple forms in the RI, but when I asked CARMA they don't see it in their staging environment. Is there another environment I should be asking them to check?

**Comment by longmd** [comment]
I _think_ they have one called `pre-prod`. You might try having them check that.

**Comment by hdjustice** [comment]
Unless they've made a change in their environments, our connections should not have changed since the last time we tested with them.  Not sure why the submission is not going thru.

**Comment by allanto-ah** [comment]
CARMA is receiving the submission as expected when I'm submitting using our staging environment, but not when I'm using the RI. They said there hasn't been any changes on their side either: [Slack](https://dsva.slack.com/archives/C02MJCT59S7/p1729263542010399) thread

**Comment by longmd** [comment]
@allanto-ah , I think we may have found the issue. Since the new oAuth 2.0 authentication is still behind a feature flag, it was not turned on by default in the Review Instance. I just turned it on and did a submission. I am waiting on verification from CARMA. Marla said the are traveling today, so we may have to wait until tomorrow for confirmation.

**Comment by hdjustice** [comment]
d'oh!  that would do it.  Great find!

**Comment by longmd** [comment]
@hdjustice , I have verified the change with CARMA per this screenshot. We are good to go with this update.

![Image](https://github.com/user-attachments/assets/a189e7d5-4676-4628-b44e-add95199c711)
