### ISSUE TITLE
Gather quantitative data for what users are selecting on the /appointments page in pre-check-in

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#92844]
## Tasks

- [x] Gather quantitative data for what users are selecting on the /appointments page in pre-check-in
- [x] Create hypothesis to explain the data
- [x] Create recommendations for impacting the data to increase volume of pre-check-in completions

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92844?planning-poker) with Zenhub @loripusey

**Comment by loripusey** [comment]
- [Spreadsheet that is a dump of data from GA4 for each week from 7/29 to 9/9 ](https://docs.google.com/spreadsheets/d/1x8TNK-o_hI2HTcmUHlmvkjBSGQ7QIIY20J2oAMx5wpk/edit?gid=0#gid=0)
- [Looker Studio dashboard for Landing page metrics](https://lookerstudio.google.com/reporting/9f71ed46-8744-4ae3-bef3-8adaed91ca9e/page/7A9BE/edit)

**Comment by loripusey** [comment]
Based on the data, it does not look like users are clicking other links instead of "Review your information now". My hypothesis is that because nothing on this page says "pre-check-in" that Veterans are confused because of the terminology change. My recommendation is to change the action link to "Review your information now (i.e. complete Pre-Check-in)"

**Comment by benbrasso-agile6** [comment]
Yeah, not bad idea. I think we'll have to A/B test something. Again, if we have time for it. But, we can chat more later when we meet.

**Comment by loripusey** [comment]
![image](https://github.com/user-attachments/assets/6b0501b1-eae1-4470-96ab-d9e258bcf706)

**Comment by loripusey** [comment]
Action items to explore:
- Remove the Refresh button from Pre-Check-in
- Change the wording of the "Review your information now"
- Change the working of "Your appointments"
- Remove the Medallia survey - ticket will be done in October
