### ISSUE TITLE
[ENGINEER] Create and/or Clone all nodes required for VA Eastern Colorado System in the Menu and associated all facility pages [BE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9284]
## User Story or Problem Statement
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement required va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Menu and Page checklist](https://drive.google.com/drive/folders/1QliZFSkQHEruGgjOGRihG8tohYxswjm1)

## Tasks
_Creation of the following Drupal types/menus and pages_
- [x] System Page (Clone from Erie VA health care)
    * Add to Menu below VA 
- [x] Health Services Listing Page (Clone from Erie VA health care)
    * Add to Menu just below System
- [x] Location Listing Page (Clone from Erie VA health care)
    * Add to Menu Just Below Health Services
    * Go back to System Page and link the following Facility pages to Main System 
- [x] vha_554	Rocky Mountain Regional VA Medical Center
- [x] vha_554GB	Aurora VA Clinic
- [x] vha_554GC	Golden VA Clinic
- [x] vha_554GD	PFC James Dunn VA Clinic
- [x] vha_554GE	PFC Floyd K. Lindstrom Department of Veterans Affairs Clinic
- [x] vha_554GF	Alamosa VA Clinic
- [x] vha_554GG	La Junta VA Clinic
- [x] vha_554GH	Lamar VA Clinic
- [x] vha_554GI	Burlington VA Clinic
- [x] vha_554GJ	Denver VA Clinic
- [x] vha_554QB	Jewell VA Clinic
- [x] vha_554QC	Salida VA Clinic
* Next Section:
- [x] About us Page (Clone from Erie VA health care)
    * Add to Menu under About VA 
- [x] Mission-Vision (Clone from Erie VA health care)
    *  Add to Menu under About us 
- [x] History (Clone from Erie VA health care)
    * Add to Menu under About us 
- [x] Performance Page (Clone from Erie VA health care )
    * Add to Menu under About us 
- [x] Leadership Listing Page (Clone from Erie VA health care)
    *  Add to Menu under About us 
* Next section:
- [x] Work with Us Page (Clone from Erie VA health care)
    * Add to Menu under About VA
- [x] Jobs and Careers (Clone from Erie VA health care )
    * Add to Menu under Work with Us
- [x] Internship and Fellowship (Clone from Erie VA health care)
    * Add to Menu under Work with Us
- [x] Volunteer and Donate (Clone from Erie VA health care)
    * Add to Menu under Work with Us
* Next Section:
- [x] Policies Page (Clone from Erie VA health care Erie VA health care )
    * Add to Menu under About VA 
- [x] Contact us (Clone from Erie VA health care)
    * Add to Menu under About VA 

## Acceptance Criteria
- [x] Validation that all pages created and assigned to the correct SYSTEM. (review in SYSTEM lookup page and take inventory.
- [x] Validate that all menu pages show up in Menu and are visible in the correct order on the menu
- [x] Validate that pages are read to take data load information
- [x]  All system pages listed above have been created

**Comment by lealester** [comment]
Need to update Parent Item(s) (location) under Menu Settings
Meta tag for Eastern Colorado (-2 characters), Volunteer or donate listing page
