### ISSUE TITLE
[Design] Create low-fi wireframe options 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#92856]
## Description 

Based on our kickoff with Sam and Kristen, and then initial userflow work we've done, let's move into creating 1 or 2 low-fi wireframe options for the new userflow for this research. 

Content can be draft and/or simply use latin or a gray box. 

[Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/Initiatives/check-in-with-staff.md)

## Tasks

- [x] Create 1 or 2 low-fi wireframe options (does not have to include every single alternative path)
- [x] Document pros and cons of each 
- [ ] Get feedback from CIE Team, Kristen and Sam

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92856?planning-poker) with Zenhub @cgednalske @zach-park

**Comment by cgednalske** [comment]
I'm wondering if it's too early for us to narrow down the options without first doing the research? 👀  Would it be that much more work to do low-fi versions of all of them?

**Comment by benbrasso-agile6** [comment]
Are you proposing research before the pilot research? I get that, but I think IVC wants us to move forward with this. Going to be difficult to squeeze all this work in. Let's chat it out next week and come up with a plan.

**Comment by benbrasso-agile6** [comment]
With Kristen for review - https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4366-34003&t=6XFyJSuAANTxDg9Q-4

**Comment by benbrasso-agile6** [comment]
Added to review during SME sync this week

**Comment by benbrasso-agile6** [comment]
@cgednalske with our discussion today, I don't think we need to address anything related to changing 15 mins to 5 mins, since we're going in this direction now. Right?

**Comment by cgednalske** [comment]
Well...not sure. Sounds like when it comes to the problem it could be a helpful thing to do regardless to mitigate the situation 🤷‍♀  What do you think? Could we explore/do that in parallel in some way?

**Comment by benbrasso-agile6** [comment]
It won't exist anywhere though... https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4366-34003&t=UXoHaANr655s2lGv-4

We could force it to exist somewhere. But, I don't think it belongs anywhere anymore.

**Comment by benbrasso-agile6** [comment]
Well, okay, maybe it can be worked in on that success page.

**Comment by benbrasso-agile6** [comment]
Let's close this ticket; since I don't think we're going to get any more feedback until the IPT meeting
