### ISSUE TITLE
10-10CG - Zero Silent Error checklist

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#92850]
## Benefit to the Veteran
As a Veteran, I want to be notified in the event that a failure occurs with my 10-10CG application, so that I may address it and make any adjustments to ensure a successful submission.

## Background
VA Platform initiative
- [This document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md) details how your Veteran-facing team can perform discovery tasks to determine if your application (product, service, et al.) has a silent failure.

>Thank you for helping us find and fix silent failures. It is our collectively responsibility as stewards of the Veteran's data to track these problems down and fix them. We appreciate your support and dedication in helping us reach the goal of zero silent errors. This is a blameless process. We want to thoroughly investigate this problem so that we know the depth and breadth of the problem and can take the necessary steps to address it.

<details>
<Summary>What is and is not a silent failure? (expand for details)</Summary>

- What is a silent failure?

     - Silent failures are any errors that occur within your application on any public facing VA platform (VA.gov, mobile application, VA Notify, et. al.) whereby the user (Veteran, claimant, 3rd party, etc.) interacting with your application is NOT made aware that an error has occurred.

- What is NOT a silent failure?
     - If an application returns an error to the user immediately upon detection of the error, then the error is not silent.
     - If an application sends an email to the user notifying them that an error with their transaction has occurred, then the error is not silent (so long as sending the email is also monitored and confirmed to have been sent).

</details>

## Scope
- Determine whether the 10-10CG has any silent errors that occur, document them (if any) and create a plan to address them quickly.

## Tasks
- [x] Review the [10-10CG checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10CG%20Form/Endpoint%20Monitoring%20%26%20Zero%20Silent%20Failures/10-10CG%20Zero%20Silent%20Failures%20checklist.md) as a team
- [x] Determine if we have any silent failures on the 10-10CG
- [x] [Document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md#file-silent-errors-issues-in-github) the silent failures
- [x] Create tickets for investigation, [monitor setup](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md#set-up-monitoring-in-datadog) and [documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md#how-to-create-a-user-data-flow-diagram), if any is needed on addressing silent failures 
- [x] Inform PO of results, and remediation plan if needed.
- [x] If no silent failures are found, notify the [#zero-silent-failures](https://dsva.slack.com/archives/C07KTTFP308) Slack channel (mention Team (10-10 Health Apps) & Portfolio (Health Tools), and that no silent failures were found)

## Acceptance Criteria
- The team has gone through the checklist for the 10-10CG and found no silent failures present.

**Comment by hdjustice** [comment]
* Does your application have a user-facing transaction that is submitted to a back-end system? 
  * NOTE: This is not limited to online forms! Other examples can include:
    * Uploads of documents and/or attachments
    * Performing an action (Such as refilling a prescription or ordering supplies)
* Are you using any of the following APIs:
    * [Lighthouse Appeals Status](https://developer.va.gov/explore/api/appeals-status/docs?version=current)
    * [Lighthouse Benefits Documents API](https://developer.va.gov/explore/api/benefits-documents/docs)
    * [Lighthouse Benefits Intake API](https://developer.va.gov/explore/api/benefits-intake/docs) / Central Mail
    * [Lighthouse Decision Reviews](https://developer.va.gov/explore/api/decision-reviews/docs?version=current)
    * [EVSS Document Upload](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/evss.md)
* Does your application submit to an API that relies on Sidekiq (or another background job processor)?

If you answered yes to any of these questions then go through the following [checklist](#checklist) as a team exercise to determine if your application has silent failures.

### Checklist

#### Start

* [ ] Do you know when your application shipped to production?
  * If not, use Github to determine, roughly, when your application shipped to users.
* [ ] Did your application use the same APIs when it shipped as it does today?
  * If not, then you'll need to consider the path user data took through both the current architecture and the previous architecture. You will need to account for potential failures in all paths since your application shipped.

#### Monitoring

* [ ] Do you monitor the API that you submit to via Datadog? 
  * If not, [set up monitoring in Datadog](#set-up-monitoring-in-datadog).
* [ ] Does your Datadog monitoring use the appropriate tagging?
  * If not, [implement tagging standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards). Adding the [dependency tag](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards#MonitorTaggingStandards-Recommended:dependency) is highly recommended!
* [ ] Do errors detected by Datadog go into a Slack notifications channel?
  * If not, start directing errors in Datadog to a dedicated Slack channel. See [#veteran-facing-forms-notifications](https://dsva.slack.com/archives/C063SM22J3H) for an example.
* [ ] Does more than one person look at the Slack notifications channel containing errors on a daily basis? 
  * If not, then follow this [guide on managing errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md)
* [ ] Do the team members monitoring the Slack channel have a system for acknowledging and responding to the errors that appear there? 
  * If not, then follow this [guide on managing errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md)

⚠️ **Failure to have endpoint monitoring in place is a blocking QA standard at Staging review as of 9/10/24.** If you answered no to any of the questions above, you will be blocked from shipping at the Staging review touchpoint in Collab Cycle.

#### Reporting errors

* [ ] Have you filed issues for errors that are appearing in Datadog / Slack?
  * If not, then start filing Github issues for new categories of errors following [this guidance](#file-silent-errors-issues-in-github)
* [ ] Do all fatal errors thrown in your application end up visible to the end user either in the user interface or via email?
  * If not, then file Github issues to capture error categories following [this guidance](#file-silent-errors-issues-in-github)

#### Documentation

* [ ] Do you have a diagram of the submission path that user data your application accepts takes to reach a system of record? 
  * If not, then [create a user data flow diagram](#how-to-create-a-user-data-flow-diagram) that captures this information. 
* [ ] Do you understand how the error is handled when each system in the submission path fails, is down for maintenance, or is completely down?
  * If not, then create documentation that captures how errors in each system are handled. Detail which systems retry a submission and what happens when those retries exhaust. Show this in your diagram.
* [ ] Has the owner of the system of record receiving the user's data indicated in writing that their system notifies or resolves 100% of fatal errors once in their custody?
  * If not, work with OCTO to meet with the owner of the system and get their agreement in writing.
  * Please document the outcome of this conversation in your product's documentation in Github.

#### User experience

* [ ] Do you capture all of the potential points of failure and make those errors known to the user via email notification and/or through the application on VA.gov or the mobile application?
  * If not, don't worry. Few teams are doing this and we'll be providing resources to help you do this in your application. Proceed to [create a user data flow diagram](#how-to-create-a-user-data-flow-diagram). That diagram will help us to help you and your team to create this user experience.

**Comment by hdjustice** [comment]
10-10CG zero silent failures checklist to-do items:

- Using APIs?
     - Are we using EVSS Document Upload API?
- Did your application use the same APIs when it shipped as it does today?
     - need to do research on this, I do know that we did stop using EVSS APIs, as well as moved from CARMA directly to MuleSoft.  This would be a Yes, and we need to determine what they were and what they are now for any remediation
- Datadog Monitoring tagging needed?
     - Luis is aware of this
- Have you filed issues for errors that are appearing in Datadog / Slack?
     - Need clarification on this question, we open team tickets, but we do not file them with categories
- Understanding how errors are handled when each system in the path fails, in maintenance or completely down?
     - Check overview doc, may need to create diagram
- System receiving data indicating how fatal errors are handled?
     - Need this outlined in writing from Mulesoft/CARMA
- Capture and notify user of all potential points of failure?
     - Need to check CARMA (noted above)

**Comment by hdjustice** [comment]
Converted to Epic and stories created to address outstanding checklist questions.
