### ISSUE TITLE
[ENGINEER] Create and/or Clone all nodes required for VA Montana System WITH MENU, associate facility pages [BE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9286]
## User Story or Problem Statement
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement required va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Menu and Page checklist](https://drive.google.com/drive/folders/1QliZFSkQHEruGgjOGRihG8tohYxswjm1)
[Pittsburgh Pilot Website](https://va.gov/pittsburgh-health-care/)

## Tasks
_Creation of the following Drupal types/menus and pages_
- [x] System Page (Clone from Erie VA health care)
    * Add to Menu below VA Montana health care
- [x] Health Services Listing Page (Clone from Erie VA health care)
    * Add to Menu just below System page
- [x] Location Listing Page (Clone from Erie VA health care)
    * Add to Menu Just Below Health Services
    * Go back to System Page and link the following Facility pages to Main System 
- [x] 436	Fort Harrison VA Medical Center
- [x] 436A4	Miles City VA Medical Center
- [x] 436GA	Anaconda VA Clinic
- [x] 436GB	Great Falls VA Clinic
- [x] 436GC	David J. Thatcher VA Clinic
- [x] 436GD	Bozeman VA Clinic
- [x] 436GF	Kalispell VA Clinic
- [x] 436GH	Benjamin Charles Steele VA Clinic
- [x] 436GI	Glasgow VA Clinic
- [x] 436GK	Glendive VA Clinic
- [x] 436GL	Cut Bank VA Clinic
- [x] 436GM	Lewistown VA Clinic
- [x] 436HC	Merril Lundman VA Outpatient Clinic
- [x] 436QA	Hamilton VA Clinic
- [x] 436QB	Plentywood VA Clinic

* Next Section:
- [x] About us Page (Clone from Erie VA health care)
    * Add to Menu under About VA Montana
- [x] Mission-Vision (Clone from Erie VA health care)
    *  Add to Menu under About us 
- [x] History (Clone from Erie VA health care)
    * Add to Menu under About us 
- [x] Performance Page (Clone from Erie VA health care )
    * Add to Menu under About us 
- [x] Leadership Listing Page (Clone from Erie VA health care)
    *  Add to Menu under About us 
* Next section:
- [x] Work with Us Page (Clone from Erie VA health care)
    * Add to Menu under About VA Montana
- [x] Jobs and Careers (Clone from Erie VA health care )
    * Add to Menu under Work with Us
- [x] Internship and Fellowship (Clone from Erie VA health care)
    * Add to Menu under Work with Us
- [x] Volunteer and Donate (Clone from Erie VA health care)
    * Add to Menu under Work with Us
* Next Section:
- [x] Policies Page (Clone from Erie VA health care Erie VA health care )
    * Add to Menu under About VA Montana
- [x] Contact us (Clone from Erie VA health care)
    * Add to Menu under About VA Montana

## Acceptance Criteria
- [x] Validation that all pages created and assigned to the correct SYSTEM. (review in SYSTEM lookup page and take inventory.
- [x] Validate that all menu pages show up in Menu and are visible in the correct order on the menu
- [x] Validate that pages are read to take data load information
- [x]  All system pages listed above have been created
