### ISSUE TITLE
Add the "Flag outdated information" feature to Find a Rep v3 designs

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#92861]
## Background
After we have closed our designs for stakeholder feedback (EOD Friday 9/20) we can add back in the "Flag outdated information" feature to our Find a Rep v3 designs, to prepare for the next Veteran-facing study.

**This ticket is ready for pickup as early as Monday 9/23.** 

## Tasks
- [x] Add the "Flag outdated information" feature back into our Find a Rep v3 designs
- [x] Share with team for feedback
- [x] Incorporate team feedback

## Acceptance Criteria
- [x] Find a Rep v3 designs have the "Flag outdated information" feature, so we can get Veteran feedback in a future study.

**Comment by mtri** [comment]
Links:\
[Detail page](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=0%3A19109&node-id=8275-203162&node-type=frame&t=f1jfEEA2MuzlFHgC-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=120%3A75196&show-proto-sidebar=1)\
[Report modal](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=0%3A19109&node-id=120-156674&node-type=frame&t=f1jfEEA2MuzlFHgC-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=120%3A75196&show-proto-sidebar=1)\
[Report modal with one report](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=0%3A19109&node-id=905-72310&node-type=frame&t=f1jfEEA2MuzlFHgC-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=120%3A75196&show-proto-sidebar=1)\
[Report modal with both reports](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=0%3A19109&node-id=905-73097&node-type=frame&t=f1jfEEA2MuzlFHgC-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=120%3A75196&show-proto-sidebar=1)\
[Detail page with reported banner](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=0%3A19109&node-id=8275-204225&node-type=frame&t=f1jfEEA2MuzlFHgC-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=120%3A75196)

I will capture annotations for this functionality on the detail page for v2 when I build out annotations for Find v3 with the new detail page.
