### ISSUE TITLE
[ENGINEER] Create and/or Clone all nodes IN Menu for VA Eastern Oklahoma System and associate all facility pages [BE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9287]
## User Story or Problem Statement
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement required va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Menu and Page checklist](https://drive.google.com/drive/folders/1QliZFSkQHEruGgjOGRihG8tohYxswjm1)
[Clonable Website](prod.cms.va.gov)

## Tasks
_Creation of the following Drupal types/menus and pages_
- [X] System Page (Clone from Erie VA health care)
    * Add to Menu below VA Eastern Oklahoma health care
- [x] Health Services Listing Page (Clone from Erie VA health care)
    * Add to Menu just below System page
- [x] Location Listing Page (Clone from Erie VA health care)
    * Add to Menu Just Below Health Services
    - [x] Go back to System Page and link the following Facility pages to Main System 
- [x] 623 Jack C. Montgomery VA Medical Center
- [x] 623BY Ernest Childers VA Outpatient Clinic
- [x] 623GA McAlester VA Clinic
- [x] 623GB Vinita VA Clinic
- [x] 623GC McCurtain County VA Clinic
- [x] 623QA Jack C. Montgomery East VA Clinic
- [x] 623QB Tulsa Eleventh Street VA Clinic
- [x] 623QC Yale Avenue VA Clinic
* Next Section:
- [x] About us Page (Clone from Erie VA health care)
    * Add to Menu under About VA Eastern Oklahoma
- [x] Mission-Vision (Clone from Erie VA health care)
    *  Add to Menu under About us 
- [x] History (Clone from Erie VA health care)
    * Add to Menu under About us 
- [x] Performance Page (Clone from Erie VA health care )
    * Add to Menu under About us 
- [x] Leadership Listing Page (Clone from Erie VA health care)
    *  Add to Menu under About us 
* Next section:
- [x] Work with Us Page (Clone from Erie VA health care)
    * Add to Menu under About VA Eastern Oklahoma
- [x] Jobs and Careers (Clone from Erie VA health care )
    * Add to Menu under Work with Us
- [x] Internship and Fellowship (Clone from Erie VA health care)
    * Add to Menu under Work with Us
- [x] Volunteer and Donate (Clone from Erie VA health care)
    * Add to Menu under Work with Us
* Next Section:
- [x] Policies Page (Clone from Erie VA health care Erie VA health care )
    * Add to Menu under About VA Eastern Oklahoma
- [x] Contact us (Clone from Erie VA health care)
    * Add to Menu under About VA Eastern Oklahoma

## Acceptance Criteria
- [x] Validation that all pages created and assigned to the correct SYSTEM. (review in 'SYSTEM' lookup page and take inventory.
- [x] Validate that all menu pages show up in Menu and are visible in the correct order on the menu
- [x] Validate that pages are read to take data load information
- [x]  All system pages listed above have been created
