### ISSUE TITLE
[Research] Create Conversation Guide for check in with staff initiative

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#92884]
## Description
Create the conversation guide for testing with users

## Tasks
- [ ] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [ ] Create conversation guide

## Acceptance Criteria
- [ ] Review conversation guide with team 
- [ ] Post finalized conversation guide to GitHub folder

**Comment by outerpress** [comment]
@StevenStraily to review this and adjust the AC/points as needed
