### ISSUE TITLE
Content Edit: 92452 - SSOe page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#92902]
## Pain Point:
VFS teams need current info on SSOe, which provides sign-in capability to a range of VA websites, but the SSOe page in both [Confluence](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887436810/SSOe) and on [Platform Website](https://depo-platform-documentation.scrollhelp.site/developer-docs/ssoe) has not been updated in >150 days.
 
## Issue Description
Per ticket [92452](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92452), we will be updating the SSOe page with the help of VFS Identity SME Megan Driscoll, who prepared the update in partnership with the Platform Identity team.

## Final Draft in Google Docs:

- https://docs.google.com/document/d/1YnU2AXkQ2c8BFqBWfvyjoC1xsMo22w9KNPTuY5ppOgs/edit?usp=sharing

---
## Tasks
- [x] Copy [Confluence page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887436810/SSOe) to the Drafts Space
- [x] Replace the page content with [the final draft in Google Docs](https://docs.google.com/document/d/1YnU2AXkQ2c8BFqBWfvyjoC1xsMo22w9KNPTuY5ppOgs/edit?usp=sharing)
- [x] Check for links to existing page
- [ ] Replace links to point to new page (has a new page title) if needed
- [x] Prepare for deployment

## Acceptance Criteria
- [x] SSOe page content has been updated
- [x] Page is ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/92902?planning-poker) with Zenhub @BSmolensky @cmarion93 @taylojill

**Comment by jknipes** [comment]
[This work should also satisfy ticket 90184](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90184)

**Comment by taylojill** [comment]
Page updated as requested per source data provided. Here's what I did:
- Copy and paste all content from [this source data page](https://docs.google.com/document/d/1YnU2AXkQ2c8BFqBWfvyjoC1xsMo22w9KNPTuY5ppOgs/edit?usp=sharing)
- Changed page title to match source data page title
- Checked for links to the current page, none found
- Checked for blockers, added date stamp, ready to publish

**Comment by jknipes** [comment]
work is complete, closing ticket as _Done_
