### ISSUE TITLE
[Frontend] Provide clearer content on the product selection screens' alerts

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#9290]
## User Story or Problem Statement
During usability testing, we uncovered that some participants thought if they were ineligible to order one set of products (batteries/accessories), they were ineligible to place an order entirely. How might we make content improvements to product selection screens' alerts based on our findings?

## Goal
_Alerts that are clearer for our users to understand_

## Objectives or Key Results this is meant to further
- _MDT development_
---
## Tasks
- [ ] Update content on the battery and accessory selection screens ([pages 15-20 in the invision prototype](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/416259607_C2P1-_Batteries_V-02))
(Please reference [the documentation about the battery selection screens](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-battery-selection.md#prototype-c2-p1-battery-selection) and [accessory selection screens](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-accessory-selection.md) as needed)
- [ ] Review the UI with the design team

## Acceptance Criteria
- [ ] Battery and accessory selection pages updated with new content from invision prototype
- [ ] The empty state's UI has been reviewed with the design team
---

**Comment by mr0sari0** [comment]
PR for this:

https://github.com/department-of-veterans-affairs/vets-website/pull/12763
