### ISSUE TITLE
Enable V2::ContactInformation::Service in all tests

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#92904]
## User Story
ContactInformation::Service needs to be updated to V2 before PCIU can be depreciated.

## Issue Description
V2::ContactInformation::Service needs to be enabled for all rspec tests. To move forward with V2::ContactInformation::Service testing, the service was disabled in other places not using V2::ContactInformation

Specs to update:
- [ ] modules/mobile/spec
- [x] async_transactions
- [ ] spec/lib/lighthouse/benefits_documents
- [ ] spec/lib/va_profile/person
- [ ] spec/rakelib
- [ ] spec/requests/swagger_spec.rb
- [ ] spec/requests/v0/profile
- [ ] spec/sidekiq/copay_notifications/mcp_notification_email_job_spec.rb

## Tasks
- [ ] Enable V2::ContactInformation::Service
- [ ] Update VCRs, if necessary

## Success Metrics
- [ ] Tests passing with V2::ContactInformation::Service

## Acceptance Criteria
- [ ] V2::ContactInformation::Service has been enabled for all tests
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
9/19/2024 - STG instance is down, Rachal was connected to them and they got taken down. Kyle M is helping her re-connect. She has a couple more things to test with the new Person V2 Service.

**Comment by jennb33** [comment]
9/23/2024 update: Trevor had some feedback on the PRs, after this is complete we should begin testing after the PRs are merged.

**Comment by RachalCassity** [comment]
@LindseySaari @jennb33 PR merged!
