### ISSUE TITLE
[Team] 10-10EZR Performance Monitoring: Work through Zero Silent Error checklist

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#92912]
## Benefit to the Veteran
As a Veteran, I want to be notified in the event that a failure occurs with my 10-10EZR application, so that I may address it and make any adjustments to ensure a successful submission.

## Background
VA Platform initiative
- [This document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md) details how your Veteran-facing team can perform discovery tasks to determine if your application (product, service, et al.) has a silent failure.

>Thank you for helping us find and fix silent failures. It is our collectively responsibility as stewards of the Veteran's data to track these problems down and fix them. We appreciate your support and dedication in helping us reach the goal of zero silent errors. This is a blameless process. We want to thoroughly investigate this problem so that we know the depth and breadth of the problem and can take the necessary steps to address it.

<Summary>What is and is not a silent failure? (expand for details)</Summary>

- What is a silent failure? 

     - Silent failures are any errors that occur within your application on any public facing VA platform (VA.gov, mobile application, VA Notify, et. al.) whereby the user (Veteran, claimant, 3rd party, etc.) interacting with your application is NOT made aware that an error has occurred.

- What is NOT a silent failure?
     - If an application returns an error to the user immediately upon detection of the error, then the error is not silent.
     - If an application sends an email to the user notifying them that an error with their transaction has occurred, then the error is not silent (so long as sending the email is also monitored and confirmed to have been sent).

**I've started a checklist in Docs [here](https://docs.google.com/document/d/1akl-g499rSaEPbBa-zZX2bxzmUtRi74kjPSwEthocYw/edit)**

**Acceptance Criteria**
- [ ] Review the [checklist](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md#how-to-determine-if-your-application-may-have-silent-failures) as a team (Answer checklist questions in Comments section below)
- [ ] Determine if we have any silent failures on the 10-10EZR
- [ ] [Document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md#file-silent-errors-issues-in-github) the silent failures
- [ ] Create tickets for investigation, [monitor setup](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md#set-up-monitoring-in-datadog) and [documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md#how-to-create-a-user-data-flow-diagram), if any is needed on addressing silent failures 
- [ ] Inform PO of results, and remediation plan if needed.
- [ ] If no silent failures are found, notify the [#zero-silent-failures](https://dsva.slack.com/archives/C07KTTFP308) Slack channel (mention Team (10-10 Health Apps) & Portfolio (Health Tools), and that no silent failures were found)
- [ ] **Success: The team has gone through the checklist for the 10-10EZR and remediated any silent failures**
