### ISSUE TITLE
[FE] 10-10CG - Improvement: County field - Short Term fix

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#92916]
## Benefit to the Veteran/Caregiver
As a Veteran and/or Caregiver, I want the application to be easy and clear, so I know exactly what information is being asked of me.

## Background
After adding the county field on the 10-10CG form, applicants are entering the country name (US, USA, United States). This is causing an issue for the staff to determine the correct Caregiver facility and the system to auto-calculate stipends, as it is based on the residential county.

## Scope
As a short-term fix, we will add a line of hint text, guiding applicants to provide their county, as well as temporary field validation to restrict users from entering US, USA, United States.  
This short-term fix is to reduce the number of applications being submitted with the incorrect info.  
- Out of scope: Longer-term fix will be coordinated with CG tech team to potentially include data validation against a common source.  Additional designs, such as moving the County field to its own page is also a consideration.

### Reference
- [Figma design](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=3070-60151&node-type=section&t=6laU5Vz1eJXyeqnf-0)

## Tasks
- [x] Add hint text to the County field
- [x] Include field validation to restrict users from entering the following input:
     - U.S
     - U.S.
     - U.SA
     - U.S.A
     - U.S.A.
     - United States
     - UnitedStates
     - United States of America
     - UnitedStatesOfAmerica
- [x] Review with PM/QA for validation & signoff
     - Signoff required in the comments of this ticket
- [ ] Launch to production

## Acceptance Criteria
- Veterans & Caregivers will now have guidance on the County field, and error messages to assist them with what kind of information is needed when a mistake is made.

**Comment by hdjustice** [comment]
Wow.. i was trying to make it not so cumbersome, but thank you so much for expanding the list!

**Comment by hdjustice** [comment]
Decision made: include the restrictions below (the field will not accept them).  We will retain "us" and "usa" as allowable, as those letter groups are included many county names

- U.S
- U.S.
- U.SA
- U.S.A
- U.S.A.
- United States
- UnitedStates
- United States of America
- UnitedStatesOfAmerica

**Comment by hdjustice** [comment]
If applicants continue to add "us" or "usa" as input, our next step will be to add the "Country" field at the top of the Address page, in an effort to inform the applicant that this value is already being accounted for.

**Comment by longmd** [comment]
@allanto-ah / @hdjustice , this is available for review [in this RI](http://9bdd448ecfed81c0ff4a48bc56f2d6d8.review.vetsgov-internal/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg). Note, we were able to add `US` and `USA` to the regex. So those should be invalid on their own, but okay in a name like `Tuscolusa`.

**Comment by allanto-ah** [comment]
Looking good! 

@hdjustice / @longmd one thing that I'm going to note here is that if I add a punctuation or space before and/or after the disallowed list, I can bypass the validation. Since this is a short-term fix, I don't know how much we would want to put in effort for this, but I wanted to ask for your opinions. 

If the user enters any of the disallow words in the list, they'll get a validation error which will tell them to enter a county in the US, but I'm wondering about users who may accidentally put in a space at the beginning or the end of the county field, which will allow them to bypass the front end validation. 

Either way if we decide if this is worth to adjust or not, I wanted to add a note here. Video of example: https://github.com/user-attachments/assets/6745a809-04fe-4bd9-8ab0-234a766b485f

**Comment by longmd** [comment]
@allanto-ah , I think that's a good callout. While we really couldn't do anything about a user adding additional text characters, like punctuation, we could easily account for any white space on the front or back side of the string and trim that. I'll go ahead and make that adjustment.

**Comment by longmd** [comment]
@allanto-ah , [here is an updated RI](http://30d78ab70fc97678b0611f4c31910340.review.vetsgov-internal/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg) with the whitespace accounted for in the validation.

**Comment by allanto-ah** [comment]
@longmd 

The `County` field for Primary Family Caregiver, Secondary Family Caregiver and Additional Secondary Family Caregiver in the home address section allows for the items in the disallowed list to go through. Did we need to add the validation on those as well? See attached video.

https://github.com/user-attachments/assets/d5fafda5-fd34-463e-beb7-35e8ab080eb5

**Comment by longmd** [comment]
@allanto-ah , Doh!!! Of course.... I have applied these updates to that pattern as well. Here is the screenshot:

![Image](https://github.com/user-attachments/assets/0f6bf79d-e04f-455d-9a44-cf77fd4a2c84)

I will send you a new RI when the build completes.

**Comment by longmd** [comment]
@allanto-ah , [here is an updated RI.](http://0d5af4828efd2db587626a0c4e18a252.review.vetsgov-internal/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg)

**Comment by allanto-ah** [comment]
Environment: RI

Verified that this is working as expected. Users are unable to enter in any words in the disallowed list and no regression.

**Comment by longmd** [comment]
@hdjustice , we have QA sign-off here... we can ship this whenever you'd like.

**Comment by hdjustice** [comment]
Good to launch!  thank you both!
