### ISSUE TITLE
[FE] 10-10EZ - Improvement: Update File Upload page conditional

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#92917]
## Benefit to the Veteran
As a Veteran who has a VA.gov account and MPI profile, I want to skip uploading documentation with my healthcare application, so that I can quickly complete and submit it without having to look for unnecessary documents.

## Background
The existing conditionals for the File Upload page to display to users are (both must be true):
1. Not short form eligible — disability rating less than 50% & does not receive compensation of “highDisability”
2. User is not found in MPI when completing the identity verification form as a guest user

However, it has been found that ~60 users per month that are showing as "authenticated", which would mean they should also have an MPI profile, are presented with the File Upload screen.

## Scope
We need to update the conditionals to ensure that we are displaying the file upload screen to the appropriate audience.

## Tasks
- [x] Update conditional to include an authentication check
- [x] Ensure that authenticated users can skip the document upload page
- [x] Validate with QA/team

## Acceptance Criteria
- The file upload screen is displayed to the appropriate audience, as expected.

**Comment by longmd** [comment]
@allanto-ah / @hdjustice , I have validated this works as expected. Y'all are welcome to have a go on staging to validate from your side.

**Comment by allanto-ah** [comment]
Thank you! I'll take a look on staging

**Comment by longmd** [comment]
Closing as completed.
