### ISSUE TITLE
Debug Vets-API Backend Approval Workflow

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#92923]
## User Story
Pull requests, not needing backend approval, is not being label correctly.

## Issue Description
[Label Pull Request Reviewers workflow ](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/require_backend_label.yml)is supposed to omit backend approval when the requested PR team belongs to Mobile, Identity, or Lighthouse. Unfortunately, labels are not correctly working.
 
## Tasks
- [ ] Find the bug
- [ ] Fix the workflow

## Success Metrics
- [ ] Workflow is properly tagging "required-backend-approval"
- [ ]  Workflow is properly tagging "omit-backend-approval"

## Acceptance Criteria
- [ ] Workflow is properly tagging "required-backend-approval"
- [ ]  Workflow is properly tagging "omit-backend-approval"
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
