### ISSUE TITLE
VSS CC - Fetch and Store Referral Data

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#92927]
## Description 

Path forward for accessing referral information using Planatir...

<img width="900" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzdhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4289a03832595460958bd5a31cea701781d386e/Screenshot%202024-09-16%20at%2012.14.40%E2%80%AFPM.png" alt="Screenshot 2024-09-16 at 12.14.40 PM.png" />

<br/> 
<br/> 

DB table is located in Files > Data - Community Care > data > raw > ReferralsCubeFact_Raw

Stephen has provided an export of the column names only in PDF format for now. See [Slack thread](https://dsva.slack.com/archives/C06RMRJCLHH/p1726505070527829) for more information about access to Planatir. 

[CC_ReferralData_ColumnNamesOnly.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFRhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d31cdb4e22a4dbf256e0c3ab1c809ce5910e709/CC_ReferralData_ColumnNamesOnly.pdf)

Requesting access should look like...

<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFBhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb3cc386e21dabff3be61dfe00b0dff9f1b0bca6/Screenshot%202024-09-16%20at%2012.43.18%E2%80%AFPM.png" alt="Screenshot 2024-09-16 at 12.43.18 PM.png" />

## Tasks

- [ ] Request access to CDW; [follow steps in Slack thread](https://dsva.slack.com/archives/C06RMRJCLHH/p1726667054494449?thread_ts=1726505070.527829&cid=C06RMRJCLHH)
- [ ] Figure out what query we need to write in Planatir to export the least amount of referral data. (This will just be a one-time export for now. BAH is looking into having this query run programatically nightly and dumping it into a restricted shared folder (TBD) that CIE and Appts FE can access. 
- [ ] Parse the exported raw data into usable data to store in restricted shared folder (TBD) that will be used to store, retrieve, and send referral information to VAOS and VA Notify
- [ ] Identify shared, restricted folder to store data in
- [ ] Identify and implement deleting referral information we no longer need. E.g., do we want to check if the appointment has been scheduled? Does the referral status change to scheduled? Do we delete them after the referral expiration date?

**Comment by benbrasso-agile6** [comment]
@loripusey does this need to get pointed? Or, are engineers figuring out tickets still for this?

**Comment by loripusey** [comment]
I'm not sure, @brianseek @lee-delarm6 ?

**Comment by brianseek** [comment]
¯\_(ツ)_/¯

**Comment by loripusey** [comment]
@lee-delarm6 can you either point this or break it down into some tickets that can be pointed?

**Comment by benbrasso-agile6** [comment]
Feels like this is high priority for next sprint, but I don't want to dictate the needs

**Comment by loripusey** [comment]
No longer using Palantir, so don't need this ticket, closing.
