### ISSUE TITLE
Begin Prototype for "View your VA payment history"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9292]
## Goal
The next step for this feature is to create prototypes so that FE can develop the components that are necessary.

## Consideration
- See what's coming into the API (check with BE) as that might impact design 
  - Do return statements come back? What other payment types are called?

## Tasks
- [ ] Based on feedback from Design Intent Reviews in the Collaboration Cycle, and findings from the research sessions, create the initial page(s) using UXPin

## Acceptance Criteria
- [x] Screens of the first pages' prototype are shared with the team 
- [x] Links to the prototype are included in the [feature outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-payment-history/README.md)

**Comment by sporeboy** [comment]
Starting point for the prototype laid-out. UXPin link here: https://preview.uxpin.com/546893e0b210374a0734240e0ca9fccc2e02ed11#/pages/129039987

**Comment by sporeboy** [comment]
Prototype working with three user flows:
- Logged-in Veteran
- Dependent not signed-in
- Veteran or service member not signed-in

The prototype currently captures info from the name screen and presents it in the review.
