### ISSUE TITLE
Analyze Domo Datasets with Large Row Count

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#92932]
### Description
We need to get an understanding of where we are with our Domo usage for the current contract year. 

The migration to GA4 created a lot of activity and data movement in our instance, this ticket is to get an assessment of the following, most notably on data rows.

### Tasks
Identify the counts for the following in our Domo instance.
- Data Rows
We can likely us [this dataset](https://va-gov.domo.com/datasources/bdac503d-0cda-4a8e-aba8-8243175d6f4f/details/data/table) to help identify details on each.

---

### Tasks

- [x] Review datasets that have greater than 5M rows.
- [x] For each dataset, review it, including cards attached, downstream data flows, and last updated date.
- [x] For each dataset, add comments in column K based on findings.
- [x] In Column L, leave a recommended action -- this might include something like Keep -- all rows needed, or delete, or investigate in BigQuery -- let's try to be as thorough and definitive as possible.
_We ultimately want to get our row count down, and see if there are obvious areas we can remove a dataset, or if we need to trim it_

### Artifacts

- [Domo Tables](https://docs.google.com/spreadsheets/d/1y6WRGftpGzzCwrytaFjoxrzZaLBmAqNZ58sXIQMmj68/edit?gid=2007741445#gid=2007741445)

---

### Acceptance Criteria

- [x] We have an accurate count of datasets that are used, with row count.
- [x] Findings have been consolidated in spreadsheet
- [x] Findings reviewed with the rest of the team.

**Comment by johnny-jesensky-adhoc** [comment]
@ChristineYoungZA, @Blivaditis - This is the spreadsheet I want to talk through on our sync on Monday -- want to review our datasets by row count, which ones have no cards associated with them, and ultimately flag whether we should keep as is, delete, or possibly optimize.

**Comment by johnny-jesensky-adhoc** [comment]
We have reviewed our datasets, and marked large ones as either candidates for deletion, or possible trimming/purging. 

- [Domo Dataset Audit](https://docs.google.com/spreadsheets/d/1y6WRGftpGzzCwrytaFjoxrzZaLBmAqNZ58sXIQMmj68/edit?gid=2007741445#gid=2007741445 )

Will look to continue this work as part of [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94439). Moving this to _Done_.

FYI @ChristineYoungZA, @Blivaditis
