### ISSUE TITLE
Finalize PCPG (CH36) Prototype

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9293]
## Goal
The next step for this feature is to finish the prototype so that FE can start to develop the components that are necessary.

## Tasks
- [ ] Based on feedback from Design Intent Reviews in the Collaboration Cycle, and findings from the research sessions, complete the initial page(s) using UXPin
- [x] Collect some feedback on some specifics

## Acceptance Criteria
- [x] Screens of the prototype are shared with the team
- [x] Links to the prototype are included in the [feature outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/README.md)

**Comment by sporeboy** [comment]
Stakeholder comment incoming on XD mock up here: https://xd.adobe.com/view/d37b343f-1a48-4aee-782d-2a78d6109478-a54a/

UXPin prototype here: https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/128093534

**Comment by sporeboy** [comment]
Mockups revised per stakeholder feedback starting here: https://xd.adobe.com/view/d37b343f-1a48-4aee-782d-2a78d6109478-a54a/screen/2301033c-4f0a-4130-b06e-4028a0ae4413/8832-Start-1
