### ISSUE TITLE
[Business Optimization] Create Draft run book for "Soft-Launch/Dual-publish" of VAMC Systems [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9294]
## Story
As a VAMC team member, I need a run process and division of labor, so I can best plan, coordinate and process the soft launch for VAMC web sites.

## Goal
_Provide an easy to understand and easy to fill out/confirm spread sheet to the PAOs to provide pertinent information needed to complete the multiple layers of the VAMC-Upgrade_

## Objectives or Key Results this is meant to further
- _Increase System page completion each quarter_
- _Increase velocity overall through business optimization_

## Resources - Tools - Documentation
[Kick_off_package](https://drive.google.com/drive/folders/1cJxbxigsy-OZxm-swU2d0lrrmVkilzNp)

## Tasks
_Copy edit content of Analytics PowerPoint Presentation:
- [ ] Draft Run book with Tasks, Division of labor and sign offs
- [ ] Present to Facilities and CMS team
- [ ] Set up meeting for Facilities and CMS to discuss draft 
- [ ] Update draft with feedback from Team

## Acceptance Criteria
Items that must be validated to be fully accepted and story closed:
* Fully reviewed document is saved in original location.
