### ISSUE TITLE
Fine-tune Reek configuration to focus on critical code smells in vets-api

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#92940]
## User Story
As a **developer**, I want to fine-tune the Reek configuration for vets-api, so that it flags only critical code smells and doesn't produce excessive noise during reviews.

## Issue Description
We enabled [Reek](https://github.com/troessner/reek) for code quality analysis in vets-api but found that it was too noisy, flagging a wide range of code smells that resulted in too many non-critical comments. As a result, we had to disable it. We have an existing configuration file (`reek.yml`), but it needs refinement to focus only on the most important code smells, reducing unnecessary feedback. 

### Resources
- PRs had Reek comments for a couple weeks in Aug. 2024. [See these commits](https://github.com/department-of-veterans-affairs/vets-api/commits/master/?since=2024-08-05&until=2024-08-13).
- [reek.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.reek.yml)
- [Notes from CoP meeting](https://vfs.atlassian.net/wiki/spaces/BCP/pages/4553408513/12+22+25) where configuration was discussed. We decided on the following:
    - Start with a single rule/smell, [duplicate method call](https://github.com/troessner/reek/blob/v6.3.0/docs/Duplicate-Method-Call.md). But first, make sure rubocop doesn't cover the same thing
    - We think it's a good idea to give devs a heads up about how it will impact them, how to fix, whether it'll be blocking, etc.
    - Add documentation to the platform website. 

## Tasks
- [x] Review the current `reek.yml` configuration.
- [x] Comment in this ticket with the overlap and non-overlap the duplicate method call has with the duplicate method that rubocop has. 
- [x] Comment out (or remove) all config _except_ the one we decided to start with (duplicate method call)
- [x] Test Reek with the updated configuration on a subset of the codebase to validate that it is catching meaningful issues without being overly noisy.
- [x] If it seems helpful, make a page on the platform website with info for how they can resolve their errors. Place in the Developer Docs section of Confluence so it's published to the platform website. 
- [x] Notify backend developers (in #vfs-all-teams and #platform-cop-backend) so they are expecting the change. You can tell them _why_ we're making the change and link to relevant docs.

## Acceptance Criteria
- [x] `reek.yml` is updated and reflects the new fine-tuned configuration.
- [x] Reek is re-enabled in the codebase with the updated configuration.

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
