### ISSUE TITLE
[BE] 10-10CG - Improvement: Determine if we send submission date/time stamp to Mulesoft/CARMA

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#92962]
## Benefit to the Veteran
As a Veteran and/or Caregiver, I would like my PCAFC application to be received at the time I submit it online, so that I can be sure it is processed based on this time, and not a later time if the application is not received by the downstream system within that time.

## Background
Over the summer, there was a time where applications were queued in Mulesoft and could not be processed in CARMA right away.  Due to this issue, the date/time of submission was not captured and applications could not be processed FIFO, as is policy.

## Scope
We need to determine whether we capture the date/time that the application is submitted online, and whether we already send that to MuleSoft/CARMA.  If we do send it today, we need to determine the attribute so that the schema can be updated and MuleSoft/CARMA can receive it.  If we don't send it today, we need to make a change so that it can be sent, along with schema updates.

## Tasks
- [x] Determine whether the submission date/time is captured by our team
- [x] Determine whether this attribute is already included in the data sent to MS/CARMA
- [x] Determine whether we need to add it in the data we send to MS/CARMA
- [x] Create a ticket for updating the request - [#93116](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93116)
- [x] Create a ticket to account for testing with the tech team - [#93118](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93118)
- [x] Create a ticket for launch [#93121](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93121)

## Acceptance Criteria
- We have determined whether we already have and send the date/time of submission, and whether additional changes are needed.

**Comment by hdjustice** [comment]
Mitch & Heather met to walk through a submission in staging and determine whether there is an attribute that can be used to send to CARMA for submission date/time.  Mitch found an attribute and drafted up a response that was sent via email to Waleed and the rest of the CG stakeholders/tech team

> Hello Waleed & team!
> 
> Mitch and I were able to run a test submission in staging, and we think we found the info you need.
> 
> We can add 'submitted_at: claim.created_at,' on lib/carma/models/submission.rb:23 to send the Claim's created_at date as the submitted_at for CARMA to consume.
> 
> Questions:
>- is the timestamp they want the creation time of the 'CaregiversAssistanceClaim'?
>      - This is currently initialized on app/controllers/v0/caregivers_assistance_claims_controller.rb:19
>           - The timestamp as we receive the CG Form submission, before we queue it for processing on :26
>-  Do you want to receive it as a top-level 'submitted_at' attribute, or possibly a different name?
maybe as a subattribute of 'metadata'?
> Let us know what questions you have, and any other thoughts on this info.

**Comment by hdjustice** [comment]
Ramesh responded to the email and confirmed what we are looking for

> we are looking at the time the 1010CG form was submitted by the dyad on [va.gov](http://va.gov/) and sent for processing. And for the attribute naming convention any name is fine and can be a top level attribute as it applies to the whole application.

**Comment by hdjustice** [comment]
We have determined that we will send the `claim.created_at` value for the `submitted_at` attribute. We have informed the CG tech team that this is the attribute to use. We must make a small change on our va.gov side and send the request body to CG team for review.  Additional tix have been created to account for this change (see description above)

**Comment by hdjustice** [comment]
Received response from Ramesh that they would like it to be a _subattribute_ rather than an attribute
