### ISSUE TITLE
[FE] - Update appointment details page for past appts in Appts app

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#92966]
## Description
Update details page as outlined in linked figma.

## Wireframes
- [Wireframes](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2160-2072&t=eMbpPmJ6uz8UYmQP-4)

## Tasks
- [ ] update content and structure
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92966?planning-poker) with Zenhub @wullaski

**Comment by benbrasso-agile6** [comment]
Not needed; engineering hasn't created tickets for this Epic yet
