### ISSUE TITLE
Disable legacy socks environment

### ISSUE THREAD

**Issue by ben-allen-oddball** [department-of-veterans-affairs/va.gov-team#93011]
## Issue Description
Disable legacy socks environment.

---
## Tasks
- [x] Disable the legacy socks access. (Sep 17, after 9PM)
- [x] Detach ENI from SOCKS 
      https://us-gov-west-1.console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#NetworkInterface:networkInterfaceId=eni-4cd40615
- [x] Detach EIP from Jumpbox 
      https://us-gov-west-1.console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#ElasticIpDetails:AllocationId=eipalloc-ecbb2bd6
- [ ] _Reassign legacy EIPs to new socks / jump boxes? (Sep 17, after 9PM)_
- [ ] Disable jenkins jobs (Sep 17, after 9PM)
- [ ] Disable github actions (Sep 17, after 9PM)
- [ ] Shutdown legacy hosts (next week)
- [ ] Remove code from devops repo (next week)
- [ ] Import resources for ENI into SOCKS deployment terraform
- [ ] Import resources for EIP into Jumpbox deployment terraform
- [ ] Remove resources from legacy terraform.
