### ISSUE TITLE
[Analytics] Request tracking on back link breadcrumbs 

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#93017]
## Description

The week prior to office hours on 9/16/2024, we realized that the breadcrumb event tracking in GA4 wasn't pulling data from details pages that utilize back link breadcrumbs in lieu of the traditional V3 breadcrumb component. This is likely because no teams have tracking implemented on it since this isn't captured automatically. After confirming w/ appointments team (who has had back link breadcrumbs the longest) that they aren't actively tracking data on it, we posed the question about how to pursue tracking to analytics team in the #vfs-analytics channel. It is likely that no teams in the health portal have tracking enabled on details pages, so a single event strategy that all teams could implement would be beneficial for research/metrics collection long-term. 

### User story

As a Cartography team member, I want to be able to understand how users are navigating the portal, and in order to compare various types of navigation to the usage of secondary navigation, I need to collect data on breadcrumb usage, including back link breadcrumbs. 

### Notes
- Slack thread w/ appointments team - they don't think they're collecting data on back link breadcrumbs, but Jeff Roof mentioned that he would look into it. [Thread here](https://dsva.slack.com/archives/C03CGTDLTFF/p1726512775500529).
- Slack thread in #vfs-analytics channel [here](https://dsva.slack.com/archives/C1Q4294JJ/p1726514986042759)

Possible tasks:
- [x] See if appointments team has a strategy implemented. If so, can we piggy back off of it? 
  - Appointments does not have tracking implemented on back breadcrumbs
- [x] If not, fill out analytics ticket for custom event to track back link breadcrumbs
  - [ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93020)
- [x] Go to analytics office hours to get clarification on the best approach
- [x] Tag/connect Robyn on communications about this 

## Acceptance criteria
- [x] a strategy has been identified and is being implemented
- [x] Teams are aware of what to do in order to get data collection on back link breadcrumbs

**Comment by fmccaf1** [comment]
Important to ask about timelines in conversations about scope

**Comment by sterkenburgsara** [comment]
Update: went to analytics office hours today to ask about the back link breadcrumbs tracking. It sounds like VADS may need to add tracking to this component on their end, but Jamie wants to look at the implementation in a few places to better speak to how this might be set up. If it should be set up independent of VADS, then custom process will need to be implemented by all teams who leverage back link breadcrumbs in the health portal. This will include shutting off the current analytics event on this element (which is on the link component) and setting up a custom event. 

In order to investigate, Jamie needs a few test users, URLs and use cases to examine herself in staging. I will provide those asap - probably tomorrow in the body of the request ticket I placed with their team. 

I have some other outstanding questions around some differentiated use cases for back link breadcrumbs, some of which do not match the current component that's in VADS and may require adjustment and further dev implementation notes. I brought this conversation to the IA CoP for further conversation & will circle back.

**Comment by sterkenburgsara** [comment]
cc @rbsingleton

**Comment by sterkenburgsara** [comment]
Based on some Q&A with Mikki about use-cases for `<- Back` link "breadcrumbs" will be moving forward with one implementation request to cover all requests, and will be able to divide analytics out by link text (generic or specific) as needed. 

<img width="1868" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODJFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d78fa538ee0490cce39d843ce0ee934e7fd91bff/Screenshot%202024-10-30%20at%209.40.54%E2%80%AFAM.png" alt="Screenshot 2024-10-30 at 9.40.54 AM.png" />

**Comment by sterkenburgsara** [comment]
Update: 10/30/24 - provided use cases to Jamie in analytics request ticket. Moving to blocked since this is now in analytics' hands.

**Comment by wesrowe** [comment]
I just pinged the Analytics team ticket for status.

**Comment by sterkenburgsara** [comment]
Based on data in the analytics ticket, it looks like this is getting picked up by analytics team in their current sprint.

**Comment by sterkenburgsara** [comment]
Have not heard back from vfs-analytics team. They have since gotten a new PM and I am unfamiliar with their prioritization process. Re-adding the "blocked" label due to external team dependency.

**Comment by sterkenburgsara** [comment]
Followed up w/ analytics team PM Adam Oye. Will follow up if I get a response back about this ticket / ETA on prioritization.

**Comment by sterkenburgsara** [comment]
@dcloud thank you! Looks like as long as the `va-link` component is leveraged for back breadcrumbs, we can use GA4 to capture data engagement with that link out of the box. I will inspect back breadcrumbs with dev tools for these teams & talk to PMs about follow-on tickets if there are deviations from that pattern. This ticket can close.
