### ISSUE TITLE
[Content] Update final content in wireframe for referrals and requests page after CAIA input

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93024]
## Background

[Discovery/design ticket with short-term referral location direction](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90909)

Figma: [short-term referral location approach](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=3980-9088&t=IIsRgCIUATq69ZEC-1)

## Tasks

- [ ] Update final content in wireframe for referrals and requests page after CAIA input. Work with Laura to confirm content for Pending name change (Requests and referrals) and new h2 headings. 
- [ ] Get appropriate approval for Pending name change (ask Kristen who needs to be involved)
- [ ] Update all CC Figma files with new design

## AC

- [ ] Figma files updated with new design
- [ ] Content finalized and approved
- [ ] Reviewed with UX and Kristen

[Design Link](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=3980-9089&t=KHAVW8Qvv8zNGwIn-1)
