### ISSUE TITLE
Content Review: Education Rewrite Restart Bundle

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9302]
Content review task, to review PW Content work that has been created and/or updated

Goal:
Complete a review of the listed items. As needed, document recommendations so that we can create follow-up tasks. 

Output:
* Recommendations of updates, as needed
* If no recommendations, able to proceed to platform & accessibility reviews

List of items to review:
Education Rewrites Restart bundle
- [x] [Montgomery GI Bill - Active Duty (Chapter 30) rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8634)
- [x] [Post-9/11 GI Bill (Chapter 33) rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8593)
- [x] [2020 VA education benefit rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8592)
- [x] [Montgomery GI Bill - Selected Reserve (Chapter 1606) rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8635)
- [x] [$600 buy-up program rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8636)
- [x] [Survivors' and Dependents' Educational Assistance Program (Chapter 35) rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8637)
- [x] [Post-9/11 GI Bill monthly housing allowance rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8638)
- [ ] [Post-9/11 GI Bill Resident Rate Requirements](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8639)
- [ ] [Apply to restore GI Bill benefits](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8641)
- [ ] [Compare education benefits](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8640)

**Comment by DanielleThierryUSDSVA** [comment]
# Notes from reviews
(will cross post in individual issues as well)

## 2020 VA education rates
- Updated the year in the intro text and meta description. It still had 2019, and looks like date was only updated in H1 and title tag but missed in intro text and meta description. 
- We need to fix the URL for Post-9/11 GI Bill (Chapter 33) rates. It looks like it's /2020-post-911-gi-bill-chapter-33-rates. The main rates page for the current year should be year-agnostic so that it can remain an evergreen year. I'll fix this on the actual page and then fix here to match.
- Fixed link summary for $600 Buy-Up program. It still had a reference to increasing REAP payment in there, but REAP is no longer available.
- Moved GI Bill Comparison tool up into the main section as the first link. Since this tool specifically lets the user look at and compare rates, it feels like it really should be up there in the main section rather than buried in related links. Going to check in with Mikki on this one for a gut check.

**Comment by DanielleThierryUSDSVA** [comment]
**NOTE:** In reviewing these pages against their corresponding pages within the [How to use benefits](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/) section, it's become clear that now that we are adding rates pages on these benefits, we should remove that information from the "How to use benefits" pages and simply link over to the relevant rates pages for the different programs (ie, post-9/11, mgib-sr, etc). Otherwise, we'll need to update rates for each program in multiple places. We should do this asap, as the rates are already out of date on the  

This brings up 2 additional questions:

**1. How do we better track pages with rate information and when that information needs to be updated?** Beth and I had proposed a long while back that we have a Drupal feature that allows our content folks to flag pages with rate (or other timely) information along with noting the date that the page will need to be next reviewed/updated, and that then generates an automatic reminder to follow up (for example, if rates for a benefit will change in October every year, we would get a notification in September to follow up with SMEs and get the new rates). This is an important feature so that we're not trying to manually keep track of all the various pages and dates. Not sure where this is at in terms of discussion, etc. Will follow up with team and create an issue to discuss.
**2. Do we need all of the individual "How do use your benefits" pages?** If we remove the rate information from these pages, some of the pages will be very light on content. Will follow up with an issue for Mikki, Meg, Beth, and I to discuss more from an IA/content strategy perspective.

**Comment by DanielleThierryUSDSVA** [comment]
# Notes from reviews (continued)

## Compare VA education benefits

- Fixed post-9/11 eligibility date (was listed as "on or after September 10, 2001"; should be "on or after September 11, 2001"
- Changed separated text headers to table captions for improved accessibility for screen readers

**Comment by DanielleThierryUSDSVA** [comment]
Hi @stephorkandatx. Just giving you an update on this ticket in preparation of today's planning meeting. The review is taking quite a bit of time/effort. I also want to align with @bethpottsVADEPO on some phrasing now that she's on the team, and she's going to help me double check rate numbers. We're hoping to have this review complete today or tomorrow, and will keep you updated. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @stephorkandatx update for sprint planning: I continue to make my way through these amid other priorities. This will need to carry over to next sprint. I will also pull in @bethpottsVADEPO to ensure that we're totally aligned on these before sending to SMEs since she'll be representing us for VBA efforts. Thanks!

**Comment by psanders86** [comment]
@RLHecht I went through and updated the language in the (and thanks for helping with the redirects!). This page is ready for copyediting.

http://preview-prod.vfs.va.gov/preview?nodeId=1007

**Comment by RLHecht** [comment]
@psanders86 I've copyedited this page. My one comment is that the H1 is over the 52-character limit.

**Comment by RLHecht** [comment]
Closing out this ticket! We are tracking the non-rates page work in other tickets.
