### ISSUE TITLE
Copy of Update digital submission designs based on stakeholder feedback

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#93029]
## Background
After presenting our Appoint, Find and Widget digital submission designs to stakeholders, we have received some minor feedback for Find a Rep.

1. The organization selection drop down is really long
2. Are the advanced filters mutually exclusive? Or can both be used?
3. What if the advanced filters don’t have search results? What would that empty state look like?

**Note**: We are accepting feedback async via email from stakeholders by EOD next Friday, 9/20. I will be sure to include additional feedback in this ticket as it arises!

## Tasks
- [ ] Update designs based on stakeholder feedback
- [ ] Review updates with the ARM team

## Acceptance Criteria
- [ ] Digital submission designs have been updated for accuracy, based on stakeholder review
