### ISSUE TITLE
Debt Portal Silent Failure Audit

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#93030]
_Debt Portal Silent Failures Audit_

## Issue Description
Conduct complete audit to determine if the debt portal application has silent failures that need to be addressed. 

## Details
***What are Silent Failures?***
Silent failures are any errors that occur within your application on any public facing VA platform (VA.gov, mobile application, VA Notify, et. al.) whereby the user (Veteran, claimant, 3rd party, etc.) interacting with your application is NOT made aware that an error has occurred.

## Tasks
- [ ] Conduct audit of debt portal application to identify any silent failures that have occurred since the launch of the debt portal - January 2021. Leverage **[documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md)** to progress through checklist.
- [ ] Report Audit findings to VA Product Owner

## Acceptance Criteria
- [ ] All silent failures have been identified
- [ ] All silent failures identified have been remediated
- [ ] Action has been taken to avoid silent failures going forward.

**Comment by HeatherRienks** [comment]
@denisecoveyduc - is this still needed or do we have newer epics that account for this work?


@Tom-Davis

**Comment by denisecoveyduc** [comment]
I think this may have been a duplicated. The intent for this ticket was the initial audit for silent failures which has been achieved. I am comfortable if we close this ticket at this point. @Tom-Davis @HeatherRienks
