### ISSUE TITLE
Documenting Bonnie Task Ownership 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#93055]
## Description 
We have realized there may be a gap between what LightHouse is taking over from a process perspective for EVSS and what tasks Bonnie handles. Since she'll be leaving in roughly a year, we want to ensure that nothing is missed. We are combining notes from Lindsay and Brandon to create one Confluence doc. We will then share it with leadership to determine if there are any gaps and what next steps might be.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Create draft Confluence page
- [x] Brandon adds notes to the page
- [x] Lindsay adds notes to the page
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
Created draft page and typed up some notes I had jotted down.

**Comment by bdech** [comment]
https://vfs.atlassian.net/wiki/spaces/PTST/pages/edit-v2/3481534465?draftShareId=6fb54837-1b5e-4f29-881a-d573b0202285

**Comment by alyssagallion** [comment]
Complete. Closing.
