### ISSUE TITLE
When user hits "back" to the rep-selection page, resurface their original query (same session only)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#93054]
## Background
What happens when a user hits "Back" on `contact-representative`?

The team discussed and decided...

**If the user hits "Back" in the same session**:
1. The selected representative is null-ed out
2. **The user can see the query they just entered**
   1. **We'll cache the user's rep query on the frontend to support this** 
3. The user will need to select a rep (same or a new one) to move back to `contact-representative`
   1. If the user tries to "Continue" we will throw the validation error 

-------

If an authenticated user leaves the form experience and revisits the `representative-selection` page later via the "Back" button, they will see the default flow:
1. The selected representative is nullified
2. The user will need to reenter their query (we will be unable to preserve because this is a new session) 
3. The user will need to select a rep (same or a new one) to move back to `contact-representative`
   1. If the user tries to "Continue" we will throw the validation error 

## Tasks
- [ ] Implement frontend logic to preserve a user's representative query in the same session
- [ ] Implement frontend logic to nullify the rep selection, if the user hits "back" to revisit the `representative-selection` screen

## Acceptance Criteria
- [ ] When user hits "back" to the rep-selection page, they are able to see the representative query they just entered and can re-select a representative from the search results.

**Comment by cosu419** [comment]
This is ready for review @mtri

**Comment by mtri** [comment]
QA ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/93957
