### ISSUE TITLE
Content Review: Life Insurance Rewrites Batch #1

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9306]
Content review task, to review PW Content work that has been created and/or updated

Goal:
Complete a review of the listed items. As needed, document recommendations so that we can create follow-up tasks.

Output:
* Recommendations of updates, as needed
* If no recommendations, able to proceed to platform & accessibility reviews

List of items to review:
Life Insurance Rewrites, Batch 1

- [x] [Convert to a commercial policy](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8365)
- [x] [Calculate your needs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8439)
- [x] [Uninsurable health issues](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8542)
- [x] [Insurance plans](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8548)

**Comment by lwalsh617** [comment]
@DanielleThierryUSDSVA -- Hi Danielle, @stephorkandatx created this ticket for your review of batch 1. The attached Word doc has everything you need for all 4 pages:
- Drupal url
- Heroku url for comparison
- Crosslinking recommendations
- Questions I have
Let me know if you want to walk through these together and I can capture your verbal feedback and share it back to you. Whatever is easiest. Thanks!
[life-insurance-rewriting-phase1_v1.1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4753444/life-insurance-rewriting-phase1_v1.1.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lwalsh617 @stephorkandatx. Noting that I will have edits/comments back on these pages by Wednesday morning. Will also share with @bethpottsVADEPO to make sure we're totally aligned on these since she's going to be the one representing the team for all things VBA moving forward. Thanks,

**Comment by stephorkandatx** [comment]
Thanks @DanielleThierryUSDSVA .

**Comment by lwalsh617** [comment]
@stephorkandatx Circling back on this per our discussion on standup yesterday. We can move this to next sprint. Thanks!

**Comment by stephorkandatx** [comment]
@lwalsh617 and @DanielleThierryUSDSVA is the content review work carrying to next sprint, or the work to do updates/edits based on the content review?

**Comment by lwalsh617** [comment]
See my comment above yours. :). Yes, carrying to next sprint.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lwalsh617. Took me a little longer than I'd hoped to finalize reviews amid all the priorities this past week. Will post as I finalize.

I pulled the content into Word docs to track edits. And, where it wasn't just a plain language/style edit, I included notes re: reason for edit for clarity. Feel free, of course, to reach out with any questions as you incorporate the edits into the Drupal pages. 

I'll also upload a copy of the overall review doc with notes/answers to questions. Thanks!

[Life insurance with certain health issues_dt_6.22.20](https://app.zenhub.com/files/133843125/ce82ab7e-975d-4365-9e09-86173c2fe87a/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lwalsh617. Just keeping you updated: Shifting priorities and will post additional docs as soon as I can. Thanks!

**Comment by lwalsh617** [comment]
@DanielleThierryUSDSVA -- Thanks for the heads up, Danielle. I can put some polish on the other batches in the mean time, so all good.

**Comment by lwalsh617** [comment]
@DanielleThierryUSDSVA -- I updated the pre-existing conditions page  Two things to note:

**1) Dividing the bulleted list of pre-existing conditions.** I considered splitting it into types of health conditions, but there don't seem to be natural categories. (You could do a category like "Auto immune conditions" but I don't think that's helpful to Veterans.) So I landed on dividing into two categories:  Conditions that can lead to higher insurance rates versus those that can result in denial of coverage. 

We'll need some input from SMEs on this. (For example, you can make a case for having "Heart conditions" on the rate increase list, or  "Recent heart attack" on the coverage denial list, or both. Ditto with cancer. Having it can increase your rates. Currently being treated for it can lead to coverage denial. I can flesh out the coverage denial list if you like, or we can get SME input first. Just let me know. 

2. **High blood pressure.** I saw that you flagged the term "plain language". I thought you meant that you changed it from "hypertension," but high blood pressure was on the current page, so just wanted to double check that you're not looking for me to change it to something else. 

Here's the preview link: http://preview-prod.vfs.va.gov/preview?nodeId=5582

FYI, @stephorkandatx

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @lwalsh617!

1. I like this idea a lot! I think it would be okay to flesh out a draft for SME input and see what they say. 

2. Not sure what happened there, but yes, it had said "hypertension" and I changed to "high blood pressure." Nothing else needed there.

Also, 2 FYIs for you on this work:

1. Because there are just so many priorities on my end right now, I'm going to remove sprint commitments for my rewriting reviews. And then we can work next steps into your sprint work as reviews are complete. This way, the moving deadlines are clear rather than keeping having to push.

2. I think many of the LI pages we're working on will likely end up going into the Learning Center. So we should chat soon about how we can keep LC templates in mind when writing these pages so that they'll be easy to refactor for LC when ready. I'll reach out next week to put some time on our calendars for that.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lwalsh617. Edits to insurance plans page  and how much life insurance do I need page below. I'd like to ask @bethpottsVADEPO to do a final review of the Drupal pages for any final refinements. 

[S-DVI insurance plans_dt (7.15.20)](https://app.zenhub.com/files/133843125/f57b4d51-7658-4270-80f5-d4131dabc138/download)

[How much life insurance do I need_dt_7.15.20](https://app.zenhub.com/files/133843125/a50f2e70-9b8b-4e02-ac1f-43702bce0d37/download)

**Comment by lwalsh617** [comment]
@DanielleThierryUSDSVA -- Thanks for posting the feedback. That means I can get that into this sprint during planning today.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lwalsh617 @bethpottsVADEPO 

For final page in Batch 1, I think we may want to follow the flow of info in the brochure that's linked to from the page rather than the page itself. It does a couple of nice things:
1) Surfaces the "when can I convert?" info sooner 
2) Streamlines the how to info (which is the same across all types except for the docs you need to submit) 

Also, then we wouldn't need to link to the pdf at all.

[Convert to a commercial life insurance policy_dt_7.21.20](https://app.zenhub.com/files/133843125/365540db-9750-4e26-8110-3108f0a095d8/download)

Take a look at the version above, and feel free to finalize as you see fit. Also, we should align on sentence vs. title capping for terms like "leave and earnings statement" and "conversion notice". I'm in favor of sentence casing wherever possible, but let me know what you think. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
@lwalsh617 One more thought on convert to a commercial life insurance: we should include a crosslink to VGLI since you can convert SGLI to VGLI within a certain time period as well.

**Comment by DanielleThierryUSDSVA** [comment]
@lwalsh617 @bethpottsVADEPO If you have everything you need from this issue, could you go ahead and close it? I don't want to close it on you before you're ready. Thanks!

**Comment by lwalsh617** [comment]
All set!
