### ISSUE TITLE
Redirect Implementation Strategy: Publish New Page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#93073]
## Issue Description

- Sitewide Public Websites needs this page published as a priority, because it is currently holding up other work.
- We will schedule fixing the formatting issues in future sprint(s).

---
## Tasks
- [ ] [Publish Redirect Implementation Strategy](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3462922242/DRAFT+Redirect+Implementation+Strategy) page

## Acceptance Criteria
- [ ] Page will be published
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Adding this work to the current sprint due to priority, and available reserved capacity

**Comment by BSmolensky** [comment]
Created copy of page. Read through all comments. Ported over comments that pertain to this round of edits. Will begin edit by fixing large, launch-blocking issues and formatting issues. If there is time, I will the proceed to fix some of the medium-sized issues with the page. This edit will likely NOT include fine-tuning, copy editing, or correcting all Style Guide violations. 

MAIN ISSUES:

- Page needs a Date Stamp
- Page needs an intro
- All images need alt text and captions
- All broken links need to be fixed
- Main table needs to be cleaned up
- Overall formatting needs to make sense
- All VA.govs need to be unlinked so that page doesn't look so chaotic.

**Comment by BSmolensky** [comment]
SME has provided captions. Waiting on alt text. I am working on the above list. Also, looking at ways to organize page info in a way that reads more cleanly.

**Comment by BSmolensky** [comment]
I have updated a draft of the original page as follows:

- all images now have caption and alt text
- there are no broken links
- date stamp added
- intro added
- unlinked all VA.govs 

I am still working on re-organizing the page. I should have some options for the SME to go over soon.

**Comment by BSmolensky** [comment]
Here is a link to the prelim edit of this page. I will move it to the IA later today. 
 
https://vfs.atlassian.net/wiki/spaces/~637b96fdfde064eda2ed7417/pages/3476291585/V1+-+Redirect+Implementation+Strategy

**Comment by BSmolensky** [comment]
Waiting for SME to approve location in IA and to approve final edit. Once approved page will be deployed. Once deployed, announcements will go out in Slack.

**Comment by BSmolensky** [comment]
Page is live on the site. https://depo-platform-documentation.scrollhelp.site/developer-docs/redirect-implementation-strategies. Ticket is ready to close.
