### ISSUE TITLE
Toxic Exposure: Multiple Exposures fail uniqueness validation for "airspace" option

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#93079]
## Issue Description
[Duplicate submissions](https://vagov.ddog-gov.com/dashboard/mqg-msb-htb/benefits---disability---526---evss-to-lh-submit--generatepdf?query=service%3Avets-api%20%40name%3A%22ClaimsApi%3A%3AV2%3A%3AVeterans%3A%3ADisabilityCompensationController%22%20env%3Aeks-prod%20%40payload.action%3Asynchronous%20AND%20%40http.status_code%3A422&fromUser=true&index=%2A&overlay=events&panelFrom=1726612800000&panelStorageType=hot&panelTo=1726614000000&panelType=logs&refresh_mode=sliding&sort=time&from_ts=1726599096144&to_ts=1726613496144&live=true) from one particular user failed with a 422 on submit, but succeeded in the backup path. The problem was that the array of MultipleExposure violated the `"uniqueItems"=>true` constraint by having 2 exposures of the "airspace" option with the same start and end dates - one in the GulfWar1990 section, and one in the GulfWar2001. This was repro'd in staging.

```
`{"airspace"=>{"startDate"=>"2015-01-07", "endDate"=>"2015-08-31"}`
```
Another scenario that came in was not with the "airspace" option, but "Afghanistan". Here, it exists in the gulfWar1990Details _and_ the otherHerbicideLocations section. The fix should be the same: normalize/de-dupe the multipleExposures array
```
     "toxicExposure"=>
      {"specifyOtherExposures"=>{"startDate"=>"2009-12-01", "endDate"=>"2009-11-01", "description"=>"burn Pit Exposure"},
       "otherExposuresDetails"=>{"radiation"=>{"startDate"=>"2008-12-01", "endDate"=>"2009-11-01"}},
       "otherExposures"=>{"radiation"=>true},
       "otherHerbicideLocations"=>{"startDate"=>"2008-12-01", "endDate"=>"2009-11-01", "description"=>"Afghanistan"},
       "herbicide"=>{"none"=>false},
       "gulfWar2001"=>{"none"=>true},
       "gulfWar1990Details"=>{"afghanistan"=>{"startDate"=>"2008-12-01", "endDate"=>"2009-11-01"}},
       "gulfWar1990"=>{"afghanistan"=>true},
```
---
## Tasks
- [ ] Create and/or modify unit tests as needed to explicitly test for the above scenario

## Acceptance Criteria
- [ ] Fix the [Form526ToLighthouseTransform](https://github.com/department-of-veterans-affairs/vets-api/blob/7fea8bada597d82d12c45bb7687876a98a706d94/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb#L303) service to de-dupe the MultipleExposures array
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
