### ISSUE TITLE
My HealtheVet on VA.gov: Prominence on VA.gov

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#93081]
## Veteran story
Veterans need one place to manage their VA benefits and health care online. As we move closer to our goal of bringing My HealtheVet to its new home on VA.gov, we need to create strategic entry points to it and redesign content to better bring people into the portal and its tools.

## Tasks and timelines

**Content tasks**
- [x] #101413
- [x] #101415
     - Refill and track VA prescriptions
     - Get your VA medical records
     - Use secure messaging
     - Schedule and manage health appointments
- [x] #101418
- [x] #101417
- [x] #101419
- [x] #101422
- [ ] Update crosslinks across the site

**IA tasks**
- [x] Create IA spec for VA.gov entry points to My HealtheVet on VA.gov ([IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/mhv-tool-landing-pages.md))
- [x] #103368 
- [x] #104153 
- [x] #104155 
- [x] Add/update hub page links and teaser text
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/104889

**Facilities tasks**
- [x] Update widgets within facility pages
- [x] Update link references to MHV classic site to point to VA.gov pages

**Comment by DanielleThierryUSDSVA** [comment]
@strelichl This is the new ticket I mentioned in our meeting today. I've added the details and timeline here. Feel free to adjust the ticket as needed!

**Comment by mnorthuis** [comment]
@DanielleThierryUSDSVA Per our discussion, notes on work needed to change over all entry points on VA.gov from MHV national portal to MHV on VA.gov:

Possible entry point placements:
- Header (existing, already links to MHV on VA.gov)
- Primary nav (TBD)
- Home page (TBD) 
- My VA
- Health care hub page (TBD)
- Health care hub static tool landing pages
- VAMC sites (some pages have sign in widget and direct link to tool, others have links to static tool pages)
- TBD: Other unauth pages that link directly to tools or MHV

The preferred approach is to change over all links on VA.gov at the same time to eliminate confusion caused by different links leading to different experiences.  

First phase:
- Fully launch all domains of medical records 

Second phase:
- Determine approach to unauth tool pages - maintain individual pages or merge to a single MHV on VA.gov page. 
   - If we keep individual pages
     - Merge the Labs and tests and Download medical records pages into single medical records page in Drupal, redirect/retire old pages
     - Move remaining unauth tool pages from React to Drupal and determine aproach for OH vs VistA versions of content (i.e. separate Drupal pages or R&S pages), redirect/retire old pages
     - Update links to the unauth tool pages across the site
   - If we merge unauth tool landing pages
     - Create new merged unauth page for MHV on VA.gov in Drupal, redirect and retire all the old pages
     - Remove links to individual unauth tool pages across the site and add link to new unauth MHV on VA.gov page
- Create/revise sign in widgets across the experience (unauth tool pages, VAMC pages, others?) to remove content that is currently part of them, and ensure they point to MHV on VA.gov correctly
  - This includes transferring ownership of widgets from Public Websites to Cartography
- Remove temporary landing pages in Medications and Secure Messages
  - Create content pages in R&S for information previously on the temporary landing pages
  - Update all links to go to the correct tool page and not the temporary landing pages
- Create any additional R&S pages needed to support the transition to MHV on VA.gov experience 
- Update all VA.gov

**Comment by kristinoletmuskat** [comment]
Hi @mnorthuis, here is a first [draft of the current entry points](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1728071932126/91696c078149ca319e0cf553278f2780db11efe8?wid=0-1728079483350) documented, with a lil pro/con list considering whether we want to create a consolidated health tool landing page or keep the separate landing pages. 

Feel free to leave comments, let me know if this isn't what you were looking for, or we can chat during our sync on Wednesday.

**Comment by kristinoletmuskat** [comment]
Confirmed with Mikki that IA work is complete for now, pending convos with MHV team and pulling in content.

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA , I updated the top of this ticket based on our recent work and decisions. Linked tickets have more specific to-do lists for each part of the work. I got locked out of Drupal before I could grab all the links, but hopefully this is all the info you need!

**Comment by mnorthuis** [comment]
@kfink24 Dropping a link to the IA spec here for reference.  

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/mhv-tool-landing-pages.md

@wesrowe I added some information under entry points related to our conversation yesterday on the React widgets needed. 

FYSA @sterkenburgsara

**Comment by mnorthuis** [comment]
@VCM86 This would be a ticket for content QA.  You can reach out to either myself or @DanielleThierryUSDSVA

**Comment by VCM86** [comment]
@mistymg -- Mikki and Danielle plan to fill you in on this ticket while I'm OOO. It will require basic clean-up/housekeeping.

**Comment by mistymg** [comment]
@jonichan-ia and I met with Randi today to learn more about content audits and how to do one.

**Comment by sterkenburgsara** [comment]
@mnorthuis Did we remove best bets that point users back to MHV Classic? If not, could we consider doing that by June 4 so that site search doesn't surface that once we sunset all the tools?

**Comment by jonichan-ia** [comment]
I removed the best bets so the new pages are showing up in top recommendations.

**Comment by mistymg** [comment]
Good to close!
