### ISSUE TITLE
backend_statuses API filters down to production services regardless of environment

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#9308]
## Issue Description
See discussion here: https://dsva.slack.com/archives/CBU0KDSB1/p1589924631316500

Frontend downtime banners are controlled by the `v0/backend_statuses` endpoint. That in turn poll pagerduty for the list of services and gets their statuses. But the code in `lib/pagerduty/models/service.rb` is hard-coded to use a prefix of `External:` which is the pattern for production services. 

So, the  staging backend_statuses endpoint returns results for production, and there's no good way of testing downtime notifications in staging. 

---
## Tasks
- [ ] Add an entry in settings.yml that indicates the per-environment prefix by which pagerduty services should be queried/filtered. Can be `External:` for prod and `Staging: External:` for dev/staging. 
- [ ] Update lib/pager_duty to use this configurable value. Note when passed to the pagerduty query API this should be URL-escaped.
- [ ] Update specs to ensure Settings is consistent with recorded values/factories before running tests.
- [ ] Validate that staging services, not prod services, show up in staging API response.

## Acceptance Criteria
- [ ] It should be possible to schedule a staging incident or maintenance window and see it reflected at `staging-api.va.gov/v0/backend_statuses`
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by patrickvinograd** [comment]
Also note that in the current https://staging-api.va.gov/v0/backend_statuses response, all the `service_id` attributes are empty, because the production services don't line up with the service id-to-name mapping in Settings.local.yml for staging. Fixing above would fix that.

**Comment by patrickvinograd** [comment]
This was fixed by the [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5458) mentioned above.
