### ISSUE TITLE
686 | Trigger for Action Needed Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#93107]
## Issue Description
For any async job where we've accepted the payload from the vets-website...   if we've called an async job, meaning one that we aren't notifying the veteran of a failure, we need to do the following:

1.  Log it.

You can use this lib/zero_silent_failures/monitor.rb  to help you do the logging.
Here are examples of usage:  https://github.com/department-of-veterans-affairs/vets-api/pull/18941/files

2.  Send an email
         a. We should be able to get the VA-notify template ID's from Fiorella.

Also, here is some documentation that may help:
[https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/maste[…]tform/practices/zero-silent-failures/logging-silent-failures.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md)

## Resources
- [VA Notify Platform Overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#successes)
- [VA Notify GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify)
- [VA Notify Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/VA%20Notify%20Playbook.pdf)
- [API docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#reviewing-our-api-docs)
- [Completing the "create trigger" tickets](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Strike/Completing%20Trigger%20Tickets/create_trigger.md)
- [Forms Strike Team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/form%20confirmations) can assist with setting up a confirmation email trigger

---
## Tasks
- [ ] - Building on the research and workflows from the [mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727757799534/c7c5f5a6dc1b8f451ecab5f02afa70a9325b93c8?sender=u070fbdc641c5ca111da83793), use the logging library to log the failure.
- [ ] -
- [ ] Test notification by logging into staging with a test user, updating the profile ID to something that sends to you
- [ ] Determine alerting and error handling if email fails to deliver
- [ ] Implement [new statsd metric](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94325). See this [write up](https://dsva.slack.com/files/U05UWBJFN48/F07SCT1RV7B/silent_failure_logs.pdf).
- [ ]  Update form [flow diagram](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727757799534/c7c5f5a6dc1b8f451ecab5f02afa70a9325b93c8?sender=u934f98f179a86c76e6ee9592) to include action needed email

## Acceptance Criteria
- [ ] A notification trigger that sends an email to the address the claimant entered in the form when: (if no address is entered into the form, use their VA profile email)
   - [ ] Claim fails to establish through backup pathway (open question on how long to wait for success)
   - [ ] Evidence fails to upload (immediately)
   - [ ] Evidence fails to upload (days later) (open question on how long to wait for success)
- [ ] Logging and monitoring for failed sends
- [ ] New statsd metric implemented
- [ ] Form flow updated to include action needed email
- [ ] Turn on flipper in production

**Comment by steele-lm** [comment]
@evansmith Dene shared that for stage 1, we'll send two separate emails to the Veteran if they submit a 674 with a 686. In the future, @fiorella-io will work on a single custom email template that will be sent to a Veteran if both forms fail. I'll create a new ticket to cover the combined 686/674 failure.

**Comment by steele-lm** [comment]
@evansmith I also updated the AC to call out that the failure email for 686 (and all other forms) should be sent to the email the user enters into the form.
