### ISSUE TITLE
[BE] 10-10CG - Improvements: Update request to include 'submitted_at' subattribute with submission date/time stamp

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93116]
## Benefit to the Veteran
As a Veteran and/or Caregiver, I would like my PCAFC application to be received at the time I submit it online, so that I can be sure it is processed based on this time, and not a later time if the application is not received by the downstream system within that time.

## Background
Over the summer, there was a time where applications were queued in Mulesoft and could not be processed in CARMA right away.  Due to this issue, the date/time of submission was not captured and applications could not be processed FIFO, as is policy.

## Scope
We have determined that we will send the `claim.created_at` value for the `submitted_at` subattribute.  We have informed the CG tech team that this is the attribute to use.  We must make a small change on our va.gov side to ensure the data is sent downstream successfully.

## Tasks
- [x] Update request body to include the `submitted_at` subattribute under `metadata`
- [x] Confirm that the `submitted_at` subattribute populates with the `claim.created_at` value
- [x] Send request body to CG team to review
- [ ] Work with CG team to make any other updates prior to testing

## Acceptance Criteria
- We have made the necessary changes to send the `submitted_at` subattribute with a date/time stamp to CARMA (through MuleSoft).

**Comment by allanto-ah** [comment]
Environment: Staging

E2E testing with CARMA was completed successfully. Slack conversation: [Link](https://dsva.slack.com/archives/C02MJCT59S7/p1727109426955579)
