### ISSUE TITLE
[BE] 10-10CG - Improvement: Complete E2E testing on new 'submitted_at' subattribute with CG tech team

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93118]
## Benefit to the Veteran
As a Veteran and/or Caregiver, I would like my PCAFC application to be received at the time I submit it online, so that I can be sure it is processed based on this time, and not a later time if the application is not received by the downstream system within that time.

## Background
Over the summer, there was a time where applications were queued in Mulesoft and could not be processed in CARMA right away.  Due to this issue, the date/time of submission was not captured and applications could not be processed FIFO, as is policy.

## Scope
Now that we have made the necessary changes to include the `submitted_at` subattribute populated with the `claim.created_at` value, and the CG tech team has made their changes, we can conduct end-to-end testing.

## Tasks
- [ ] Coordinate with CG tech team to conduct end-to-end testing of the additional subattribute 
- [ ] Validate that submissions are successful and the `submitted_at` subattribute is populated with the `claim.created_at` value
- [ ] Address any findings that lead to submission failures as a result of this change
- [ ] PM to sign off once testing has been determined successful
     - Signoff required in the comments section of this ticket
- [ ] Prepare to launch the change, in coordination with the CG tech team

## Acceptance Criteria
- We have completed successful end-to-end testing with the CG tech team and are ready to launch the change
