### ISSUE TITLE
Add partial SSN in 20-0996 SIP call

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#9311]
## Issue Description
Backends "Save in progress" SIP response to `/v0/in_progress_forms/20-0996` should include last 4 of SSN per the FE design.

---
## Tasks
- [ ] Include last 4 of SSN in SIP response for form 20-0996

## Acceptance Criteria
- [ ] BE supplies everything FE needs to complete design implementation of form 20-0996
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
