### ISSUE TITLE
VRE | Trigger for Action Needed Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#93112]
## Issue Description
_If there is an existing failure email notification, confirm that it is sent through VA Notify. If yes, stop using existing email template and start using new failure email notification template created for all benefit forms. [Implement additional statsd metric](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md) to inform OCTO-level dashboard._

_If there is not an existing failure email notification, create a trigger that will send the VA Notify failure email template when a claim fails the backup submission pathway._

## Resources
- [VA Notify Platform Overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#successes)
- [VA Notify GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify)
- [VA Notify Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/VA%20Notify%20Playbook.pdf)
- [API docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#reviewing-our-api-docs)
- [Completing the "create trigger" tickets](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Strike/Completing%20Trigger%20Tickets/create_trigger.md)
- [Forms Strike Team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/form%20confirmations) can assist with setting up a confirmation email trigger

---
## Tasks
- [ ] If VA Notify is already leveraged, migrate failure notification to the new email template
If a failure email is not currently sent:
- [ ] Build notification code to call the VA Notify API
   - [ ] Notification should trigger an email when a submission fails the backup pathway (total failure) or evidence fails to upload
   - [ ] The default email address should be the email the user entered into the form. If no email exists within the form, use their MyVA profile email.
- [ ] Test notification by logging into staging with a test user, updating the profile ID to something that sends to you
- [ ] Determine alerting and error handling if email fails to deliver
- [ ] Implement [new statsd metric](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94325). See this [write up](https://dsva.slack.com/files/U05UWBJFN48/F07SCT1RV7B/silent_failure_logs.pdf).
- [ ] Update form [flow diagram](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727286761015/c720da157691aad3bd756fcd75f1e7ec6099cef7?sender=u934f98f179a86c76e6ee9592) to include action needed email

## Acceptance Criteria
- [ ] A notification trigger that sends an email to the address the claimant entered in the form when:
   - [ ]  Claim fails to establish through backup pathway (open question on how long to wait for success)
   - [ ] Evidence fails to upload (immediately)
   - [ ] Evidence fails to upload (days later) (open question on how long to wait for success)
- [ ] Logging and monitoring for failed sends
- [ ] New statsd metric implemented
- [ ] Form flow updated to include action needed email
- [ ] Turn on flipper in production
