### ISSUE TITLE
2024 Q3 PACT Act bulkhead removal (dupe 1)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#93128]
This is a new ticket for Q3; as the previous ticket ([91578](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91578)) was closed prematurely.

## User Story
As the managers and developers for the VA Platform, 
We need re-enable the bulkheads from the Q3 PACT Act submissions, 
So that they are present for the next round of submissions. 

## Issue Description
Need to pull down the bulkheads that were stood up for the PACT Act Q3 monitoring, as the Pact Act surge for Q3 seems to be over. See [this Slack thread](https://adhoc.slack.com/archives/C06G2QB9X8T/p1724343446903649) for managerial direction. 

## Tasks
- [x] Re-enable Q3 PACT Act bulkheads
- [x] Perform testing as necessary
- [x] Document any issues as necessary

## Success Metrics
Q3 PACT Act bulkheads have been removed from the Platform.

## Acceptance Criteria
- [ ] Q3 PACT Act bulkheads are live in production
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
9/19/2024 update: Lindsey updated the pods, so this ticket can be closed.
