### ISSUE TITLE
QA AVS Survey for Launch 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#93127]
## Issue Description
We need to implement and test the coding for the QA survey in preparation for the upcoming launch. 
---
## Tasks
- [x] QA coding for survey questions
- [x] Ensure all data collection processes function properly
- [x] Run test cases ensuring responses are captured accurately
- [x] Implement any necessary validation logic
- [x] Coordinate with development team 
- [x] Report any bugs or issues 

## Acceptance Criteria
- [x] Survey questions are coded and display correctly
- [x] Response data is correctly captured
- [x] Validation logic functions as expected
- [x] QA testing is completed with no bugs 
- [x] Survey is ready for launch 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
10/2/24
Unable to view the feedback button - still receiving error in the pipeline for feedback button and a support ticket has been created - expected resolution 10/3/24
the feedback button can be manually triggered, however there is still work to do before completion 
Reached out to stakeholder Nina Anusavice to inform of launch status

**Comment by aubreyarcangel** [comment]
Upon QAing the AVS survey in production it as found that data is not being recorded from Chrome browsers specifically. The survey team will collaborate with Medallia to troubleshoot this issue. There is currently no timeline for resolution.
Action item: I will need to change the feedback button in production to point back to the sitewide VFS survey until this issue is resolved.

**Comment by ATMiddleton** [comment]
Survey launched - we still need access to the data

**Comment by clantosswett** [comment]
Not seeing any updates here but I'm assuming this should be closed?

**Comment by ATMiddleton** [comment]
Hey Chante,

Aubrey was to update and close yesterday - I will check with him.

Best regards,

Anita
Product Manager
305-522-2306
