### ISSUE TITLE
[BE] 10-10CG - Improvement: Coordinated launch of new 'submitted_at' subattribute

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93121]
## Background
Over the summer, there was a time where applications were queued in Mulesoft and could not be processed in CARMA right away.  Due to this issue, the date/time of submission was not captured and applications could not be processed FIFO, as is policy.

## Scope
Now that end-to-end testing has been successful, we are ready to coordinate the launch of the new subattribute into production.

## Tasks
- [x] Coordinate a launch date with the CG tech team
- [ ] Determine if a phased launch is possible
- [x] Launch new subattribute change into production
- [x] Monitor form submissions in Datadog
- [x] Monitor and communicate via Slack/email with CG team on submissions activity, watching for failures or discrepancies
- [ ] Address any findings that are a result of this change

## Acceptance Criteria
- We have successfully launched the new subattribute change into production
