### ISSUE TITLE
Design Spike: Failure Messaging Updates

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#93137]
## Issue Description
The purpose of this ticket is to identify messaging and notification updates for Pension and Burial needed to match the templates the Veteran Facing Forms team created for the Zero Silent Failures initiative.

---
## Tasks
- [x] _Review engineering spike that documents failure points and how the system handles them today. #93133
- [x] _Identify changes required to stay aligned with VFF team Design Templates.   https://github.com/department-of-veterans-affairs/VA.gov-team-forms/tree/main/Design/patterns/Application%20status
- [ ] _Create design tickets for changes needed

## Acceptance Criteria
- [ ] _Tickets created for changes needed

**Comment by echin393** [comment]
VFF team recommends 3 VA Notify email templates for different scenarios, and I noticed that we have an open question in the Burial MURAL about which confirmation email is correct, because two are being sent during two different jobs.

1. Can we identify which confirmation email templates are being sent? Is one for successful submission ("Thanks for submitting your form"), and one for successful receipt ("We've received your form")? Or, are **both** being sent for successful submission?
2. Alternatively, can we not tell which email templates are being used because they're still in progress? 

cc @matt4su @TaiWilkin

**Comment by echin393** [comment]
**Next Steps**
* Tai to continue technical discovery on email templates in #93133
* HCD to assess whether the Zero Silent Failures initiative requires front-end changes to set expectations on form submission on the confirmation page, including content changes in the **Success alert** and the **What to Expect** progress list.
