### ISSUE TITLE
AE-Sprint 22 (5.22-6.2)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#9314]
# Sprint 22 (5/20 – 6/2)
Order of priorities
1. Finish remaining design tickets
2. Continue Build
3. IA review
4. Team validates things are working in staging pre-QA

### Design
- [x] [Design] Mobile navigation documentation #8234
- [x] [Design] Update DD Header #9423
- [x] [Design]- Show a more specific error message when we cannot initialize somebody in VA Profile #9353
- [x] [Design] Design Mobile Sub Navigation #8233
- [x] [Design]- Update profile page for when a user is not in MPI #9145
- [x] [Design] - Create Updated Account Settings mock based on T&C ticket findings #8824
- [x] Profile 2.0: Propose IA/URL plan for the profile itself #5538

### Build
- [ ] [FE] Profile 2.0: Build the contact information section #5353
- [x] [FE]- Show a more specific error message when we cannot initialize somebody in VA Profile #8847
- [x] [FE] Update account security MPI error message #9220
- [x] [FE] Profile 2.0: Build the direct deposit section #5355 
- [x] [FE] Profile 2.0: Build connected apps section #5357
- [ ] [FE] Remove Direct Deposit on the profile if users are not eligible #8571
- [x] [FE] Build LOA1 Account Security Screen #9012
- [x] [FE] Mount a new profile wrapper that will be responsible for showing either the old or new Profiles #8698
- [x] [FE] - Remove everything related to "Account" if profile is turned on #8699
- [x] [FE] Profile Name Tag Updates - Desktop and Mobile #9059
- [x] [FE] Email updates to Account Security #9060
- [ ] [FE] Bug- Direct Deposit v2 - focus is on Edit button on first launch #9075

***Team verifies in staging that everything is behaving the way it should be BEFORE we do QA***

### Miscellaneous, bug fixes, maintenance, hardening, 508 etc
- [x] [Backend] NoMethodError in personal information serializer #9132
- [x] Fix logic for showing "Blocked from Direct Deposit" alert #9316

### PM
- [X] Submit Analytics Review Ticket (Analytics Implementation or QA Support for [Profile 2.0] #9488)
- [x] Submit IA Review #IA Request [Profile 2.0] #9670
- [x] Update profile 2.0 epic

### Unplanned work
- [x] [FE] Change how we track when we make "GET /ppiu/payment_information" calls #9593 
- [x] Investigate what is causing the variance in Direct Deposit data between GA views #9605

**Comment by Samara-Strauss** [comment]
Can we close this?

**Comment by mshea0606** [comment]
@Samara-Strauss closed.
