### ISSUE TITLE
DR | Confirm that SavedClaims/stored submissions table shows same errors as original error scanning

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#93143]
## Value Statement

**_As a_** developer

**_I want to_** to be able to reference the SavedClaims table

**_So that_** we can view errors and respond to them

---

## Background Context
We want to make sure that the code changes we've made are properly capturing the errors that are occurring downstream and that we can rely on that table instead of our usual process for scanning for errors (querying the LH records)

## Acceptance Criteria

- [ ] Table displays the same errors as the ones we see when querying the Lighthouse records

## Tasks

- [ ] Compare the errors shown in the table to the queried records between the beginning and end of the sprint

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by anniebtran** [comment]
Some queries I've tried to run to try and compare some numbers:
```rb
# Supplemental Claim Evidence Submissions (Lighthouse) that did not make it to VBMS, grouped by the ID of the form submission
AppealsApi::EvidenceSubmission.joins(:upload_submission).where.not(upload_submission: { status: 'vbms'}).where(supportable_type: 'AppealsApi::SupplementalClaim').group(:supportable_id).count.length
=> 1924
# SC Saved Claims that have not had a delete date set (i.e. have not reached VBMS status)
SavedClaim::SupplementalClaim.where(delete_date: nil).count
=> 1594

# Only counting LH evidence records in "error" status
AppealsApi::EvidenceSubmission.joins(:upload_submission).where(upload_submission: { status: 'error'}).where(supportable_type: 'AppealsApi::SupplementalClaim').group(:supportable_id).count.length
=> 448
# Only counting SavedClaims with form in "complete" status 
SavedClaim::SupplementalClaim.where(delete_date: nil).where('metadata LIKE ?', "%{\"status\":\"complete\"%").count
=> 475
```

Observations:
- Some of the `SavedClaims` don't include the evidence upload data in their metadata and do have their `delete_date` set 😬 
  - Example: `SavedClaim::SupplementalClaim id = 9823874`

**Comment by dfong-adh** [comment]
@anniebtran I've completed https://github.com/department-of-veterans-affairs/va.gov-team/issues/93400. Records that were already flagged for deletion prior to the backfill with all attachments in `vbms`  status were not touched, but all other records have been or will be automatically reprocessed.

**Comment by anniebtran** [comment]
Refined these queries a bit as I wasn't accounting for when we started persisting `SavedClaim` records

```rb
start_date = Date.new(2024, 8, 1)

# Count for LH Supplemental Claim submissions that have evidence errors
AppealsApi::EvidenceSubmission.joins(:upload_submission).where(upload_submission: { status: 'error'}).where(supportable_type: 'AppealsApi::SupplementalClaim').where('appeals_api_evidence_submissions.created_at > ?', start_date).group(:supportable_id).count.length
=> 31
# Count for LH Supplemental Claim submissions with form errors
AppealsApi::SupplementalClaim.where(status: 'error').where('created_at > ?', start_date).count
=> 0
# Count for SavedClaim::SupplementalClaim records with error status included somewhere in the metadata and a nil delete date
SavedClaim::SupplementalClaim.where(delete_date: nil).where('metadata LIKE ?', "%\"status\":\"error\"%").order(created_at: :asc).count
=> 31

# Same for NOD
# Lighthouse record counts
AppealsApi::EvidenceSubmission.joins(:upload_submission).where(upload_submission: { status: 'error'}).where(supportable_type: 'AppealsApi::NoticeOfDisagreement').where('appeals_api_evidence_submissions.created_at > ?', start_date).group(:supportable_id).count.length
=> 2
AppealsApi::NoticeOfDisagreement.where(status: 'error').where('created_at > ?', start_date).count
=> 0

# SavedClaim count
SavedClaim::NoticeOfDisagreement.where(delete_date: nil).where('metadata LIKE ?', "%\"status\":\"error\"%").order(created_at: :asc).count
=> 2

# HLR (no evidence submissions)
# Lighthouse record count
AppealsApi::HigherLevelReview.where(status: 'error').where('created_at > ?', start_date).count
=> 1
# SavedClaim count
SavedClaim::HigherLevelReview.where(delete_date: nil).where('metadata LIKE ?', "%\"status\":\"error\"%").order(created_at: :asc).count
=> 1

```

Everything seems to be matching, so I think we are good to close! 🎉
