### ISSUE TITLE
VSOR - VA Claims Process Interviews - Planning

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#93153]
## Issue Description
Exploratory interviews with VSORs to understand current claims process, supporting forms, and technology. Target audience will include those who do and do not use SEP to see how processes vary. Learnings will be used to inform ARP claims process flows.

## Tasks
- [ ] Create GitHub research folder
- [ ] Create research plan
- [ ] Create conversation guide
- [ ] Submit all materials to team for review
- [ ] Create revisions Zenhub ticket

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
https://docs.google.com/document/d/1BbyQuK7yecGuF8Z1xtN0AbE2jF8-ZqP52HfQCqq3hQ0/edit?usp=sharing
https://docs.google.com/document/d/1PWEUeqdBnnHLnXsr0RKdAMjEBiG8r2sXtEaxPZ4AULM/edit?usp=sharing

Materials ready and sent to Lesley and Jen for review
