### ISSUE TITLE
[Design] Requests and referrals link component on appointment list. 

### ISSUE THREAD

**Issue by Cieramaddox** [department-of-veterans-affairs/va.gov-team#93156]
## Background

Figma: [Long-term referral location exploration](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=4225-12035&t=ObtKlQrWrHCpL6Sk-1)

## Tasks

- [x] Show with task card, does UI still work 
- [ ] Discuss design decisions with UAE UX team 
- [ ] Create wireframes
- [ ] Decide if show link just on upcoming page or also past appointments page? (Sara S., Peter R.)
- [ ] Get approval on name of the page Requests and Referrals (Also, Kristen started to ask questions about using the slash in the title.) 

## AC

- [ ] Mockups created
- [ ] Content finalized and approved
- [ ] Reviewed with UX and Kristen

[Design Link](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=4225-12035&t=ObtKlQrWrHCpL6Sk-1)

**Comment by cgednalske** [comment]
FYI @Cieramaddox I'm not "on" this ticket necessarily - just attached for awareness because I'm having trouble seeing what all is being worked on for CC UX across our boards.

**Comment by cgednalske** [comment]
@Cieramaddox fyi I moved this to validate 🎉

**Comment by benbrasso-agile6** [comment]
@cgednalske tickets on multiple boards are independent. You'll need to move that ticket on https://app.zenhub.com/workspaces/appointments-fe-ux-5fff340c2d80a4000fb6f69c/board?labels=appointments-cc-direct as well

**Comment by benbrasso-agile6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/2024-10%20Check%20in%20with%20an%20MSA%20after%20eCheck-in%20experiment%20in-person%20UAT%20with%20Veterans%20and%20clinic%20staff

**Comment by benbrasso-agile6** [comment]
How's this ticket doing? All done?
