### ISSUE TITLE
Debt Letters -Integrate with eFolders/VBMS API to download letters 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#9315]
## Issue Description
_As a veteran sho has incurred debt that generated a debt letter, I would live the ability to download the letter that was mailed to me on va.gov after I am logged in and authenticated

---
## Tasks
- [ ] _Integrate with vbms endpoint
- [ ] _Authenticate veteran and look up debt letter information in eFolders
- [ ]_Retrive letter or letters for download

## Acceptance Criteria
- [ ] _For any given authenticated test user who has letter(s) in eFolders, they should have the ability to retrieve one or more letter(s) that are stored in eFolders 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
