### ISSUE TITLE
[BE] 10-10EZ - Zero Silent failures: Validate APIs used

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93158]
## Benefit to the Veteran
As a Veteran, I want to be notified when there is a fatal error with my application, so that I can make any necessary changes for a successful submission.

### Reference
- [EZ zero silent failures checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/Endpoint%20Monitoring%20&%20Zero%20Silent%20Failures/10-10EZ%20Zero%20Silent%20Failures%20checklist.md)

## Scope
To ensure we account for all fatal errors that can occur for the 10-10EZ form, we need to confirm the APIs we use currently, and have used since production launch in May 2016.

> - Using APIs?
>     - Are we using EVSS Document Upload API?
> - Did your application use the same APIs when it shipped as it does today?
>     - need to do research on this, I do know that we did stop using EVSS APIs, so this would be a Yes, and we need to determine what they were and what they are now for any remediation.  

## Tasks
- [x] Research the APIs that are used with the 10-10EZ
- [x] Research any API changes that have occurred as far back as you can go
     - Use Github tickets
     - Use any documentation found in the [current](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application) and [old](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/vets-application) folders 
- [x] Outline the APIs used and when they were used
- [x] Tag PM to review

## Acceptance Criteria
- Any and all APIs used with 10-10EZ form have been identified.

**Comment by coope93** [comment]
### API's currently in use: 
- Veteran Enrollment System - submit validated form data and documents
- Veteran Enrollment Eligibility System - used to validate if a Veteran is eligible for healthcare. 
- S3 - Temporarily store POA files before3 submitting them to Mulesoft. Also used to store facilities .csv file that is used to validate updated facilities.
- MPI - Validate veteran status
- Lighthouse Facilities API - Used to generate list of valid facilities
- BGS - Used to get disability rating information
- VaNotify - Used to send submission failure email

### Questions: 
facilities job process - what all do we need to document here about that? @Mitch-A6

**Comment by coope93** [comment]
@hdjustice @longmd @Mitch-A6 I went through the 10-10EZ flow (mostly on the backend) and added the api's I am aware of. Let me know if I missed any or if we need to clarify anything here.

**Comment by hdjustice** [comment]
> S3 - Temporarily store POA files before3 submitting them to Mulesoft. Also used to store facilities .csv file that is used to validate updated facilities.

Hey @coope93 - this item above applies to the CG. Do we use the same/similar service for other file uploads for EZ?

**Comment by coope93** [comment]
> > S3 - Temporarily store POA files before3 submitting them to Mulesoft. Also used to store facilities .csv file that is used to validate updated facilities.
> 
> Hey [@coope93](https://github.com/coope93) - this item above applies to the CG. Do we use the same/similar service for other file uploads for EZ?

My mistake, I copied it from CG as far as the POA. We do store hca attachment files in s3 before sending them to the enrollment system, they are just not POA's and instead any of the attachment types we accept.

**Comment by hdjustice** [comment]
Next Steps: Review old [Enrollment system docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/vets-application/product/enrollment-system) to confirm if the endpoints we use are the same or if there are some old ones we no longer use. ([this doc may be helpful](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/vets-application/product/enrollment-system/3-11-e-and-e-service-description-010213.docx))

**Comment by hdjustice** [comment]
After some research was done into the old archived documentation, we have found that the endpoint APIs we are using today have not changed since the form was launched.
> As far as we know, the wsdl file is used to describe the available endpoints and services for an api. In our case, we have [this voa.wsdl file](https://github.com/department-of-veterans-affairs/vets-api/blob/5c1085739fdea0d943329b2af98e8a653c3bd2a0/config/health_care_application/wsdl/voa.wsdl#L4) , which was originally added 8 years ago when the 10-10EZ form was first created online. It has only had one edit ([which was related to updating the gem we use to make the request 3 weeks ago](https://github.com/department-of-veterans-affairs/vets-api/commits/5c1085739fdea0d943329b2af98e8a653c3bd2a0/config/health_care_application/wsdl/voa.wsdl)), but which did not change any of the endpoint descriptions. It looks like the only endpoints we use with the enrollment system are the saveSubmitForm (used to submit the completed form) and the getFormSubmissionStatus (which is used by our healthcheck endpoint). 
> So in conclusion, our usage in regards to which endpoints we are using have not changed since the app was first created.
