### ISSUE TITLE
[DA] 10-10EZ - Zero silent failures: Datadog Monitoring tags

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93159]
## Benefit to the Veteran
As a Veteran, I want to be notified when there is a fatal error with my application, so that I can make any necessary changes for a successful submission.

### Reference
- [EZ zero silent failures checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/Endpoint%20Monitoring%20&%20Zero%20Silent%20Failures/10-10EZ%20Zero%20Silent%20Failures%20checklist.md)

## Scope
To ensure we account for all fatal errors that can occur for the 10-10EZ form, we need to ensure we are using the right tagging within Datadog

## Tasks
- [ ] Follow the guidance in the [Monitor Tagging Standards]9https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards)
- [ ] Confirm all 10-10EZ monitors have the appropriate tagging per the guidance
- [ ] Tag PM to review

## Acceptance Criteria
- All Datadog monitors for the 10-10EZ have the appropriate tagging

**Comment by hdjustice** [comment]
not needed, duplicate of #93164
