### ISSUE TITLE
[BE, PM] 10-10EZ - Zero silent failures: End-to-end system failures

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93166]
## Benefit to the Veteran
As a Veteran, I want to be notified when there is a fatal error with my application and the submission failure email fails, so that I can make any necessary changes for a successful submission.

### Reference
- [EZ zero silent failures checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/Endpoint%20Monitoring%20&%20Zero%20Silent%20Failures/10-10EZ%20Zero%20Silent%20Failures%20checklist.md)

## Scope
To ensure we account for all fatal errors that can occur for the 10-10EZ form, we need to confirm the process for when a fatal error occurs within VES and how that is handled.  We also need to document how errors are handled when each system in the end-to-end path fails, in maintenance or completely down (this includes retries process).  All this should be documented in a diagram, as well as obtaining the VES process in writing.

## Tasks
- [x] Reach out to Joshua Faulkner on VES team to understand the process of what happens when 10-10EZ fails after a successful receipt from VA.gov
- [x] Obtain this VES process in writing
- [x] Create and/or update the [Submission flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/engineering/10-10EZ%20Flow%20Chart.md) to include the end-to-end error handling (see [Comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93166#issuecomment-2364508430) for details)
- [x] Review with team for accuracy

## Acceptance Criteria
- End-to-end submission flow, including error handling, is documented and shared with the team.

**Comment by hdjustice** [comment]
Sent email to Joshua Faulkner requesting written confirmation of what happens when a submission is received from VA.gov, but encounters a fatal error within VES.  Response:

> The system does not resolve a fatal error, that is the exact definition of a fatal error, you cannot recover from it.
> 
> Errors that are fatal/unrecoverable are moved into a manual workflow for the staff to take action on the application submission. Most of the scenarios are expected and intentional, especially in the anonymous submission route; but unexpected errors also follow that same flow.

**Comment by hdjustice** [comment]
Next Step - [Submission flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/engineering/10-10EZ%20Flow%20Chart.md) document needs to be updated to include the VES handling fatal/unrecoverable failures process, per Joshua F above

**Comment by pshahVA** [comment]
@hdjustice , Is this to address an error that has already happened or to prevent future errors?

**Comment by hdjustice** [comment]
Hi @pshahVA - The remaining tasks here are to update documentation to include some details we found in our research of APIs used and error handling.  So I suppose this would be to help educate and prevent future errors.

I am sorry if this is not the right thing to do for this "managing errors" step of the ZSF initiative.  That section was not clear to me on what teams are supposed to do.  I had not heard of categories or any of this before, and the guidance just says to create tickets with categories. In following the slack channel, it seemed like we should be tracking the work teams are doing to fill in gaps/improve monitoring.  I thought this would fall into that sort of thing.

**Comment by hdjustice** [comment]
All current updates have been made.  Additional updates will be made as future work impacts the submission flow.
