### ISSUE TITLE
[BE, PM] 10-10CG - Zero silent failures: End-to-end system failures

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93171]
## Benefit to the Veteran
As a Veteran, I want to be notified when there is a fatal error with my application and the submission failure email fails, so that I can make any necessary changes for a successful submission.

### Reference
- [CG zero silent failures checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10CG%20Form/Endpoint%20Monitoring%20%26%20Zero%20Silent%20Failures/10-10CG%20Zero%20Silent%20Failures%20checklist.md)

## Scope
To ensure we account for all fatal errors that can occur for the 10-10EZ form, we need to confirm the process for when a fatal error occurs within MuleSoft and CARMA, and how that is handled.  We also need to document how errors are handled when each system in the end-to-end path fails, in maintenance or completely down (this includes retries process).  All this should be documented in a diagram, as well as obtaining the MuleSoft/CARMA process in writing.

## Tasks
- [x] Reach out to the CG team to understand the process of what happens when 10-10CG fails after a successful receipt from VA.gov
     - Confirm the Submission Failure communication to Veterans/Caregivers
- [x] Obtain this process in writing, to include both MuleSoft and CARMA
- [ ] Create and/or update the [Architectural Overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/eng-docs/10-10%20Architectural%20Overview.pdf) to include the end-to-end error handling
- [x] Review with team for accuracy

## Acceptance Criteria
- End-to-end submission flow, including error handling, is documented and shared with the team.

**Comment by hdjustice** [comment]
Sent email to CG team requesting written confirmation & process of handling fatal errors once the application is in their custody (errors are not sent back to VA.gov)
