### ISSUE TITLE
Copy of [BE] 10-10EZ - Zero Silent failures: Validate APIs used

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93170]
## Benefit to the Veteran
As a Veteran, I want to be notified when there is a fatal error with my application, so that I can make any necessary changes for a successful submission.

### Reference
- [EZ zero silent failures checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/Endpoint%20Monitoring%20&%20Zero%20Silent%20Failures/10-10EZ%20Zero%20Silent%20Failures%20checklist.md)

## Scope
To ensure we account for all fatal errors that can occur for the 10-10EZ form, we need to confirm the APIs we use currently, and have used since production launch in May 2016.

> - Using APIs?
>     - Are we using EVSS Document Upload API?
> - Did your application use the same APIs when it shipped as it does today?
>     - need to do research on this, I do know that we did stop using EVSS APIs, so this would be a Yes, and we need to determine what they were and what they are now for any remediation.  

## Tasks
- [ ] Research the APIs that are used with the 10-10EZ
- [ ] Research any API changes that have occurred as far back as you can go
     - Use Github tickets
     - Use any documentation found in the [current](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application) and [old](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/vets-application) folders 
- [ ] Outline the APIs used and when they were used
- [ ] Tag PM to review

## Acceptance Criteria
- Any and all APIs used with 10-10EZ form have been identified.

**Comment by coope93** [comment]
### API's currently in use: 
- MuleSoft - form data and documents are submitted here upon being validated
- S3 - Temporarily store POA files before submitting them to MuleSoft.
- MPI - Validate veteran status during form validation flow

### Previously used
- CARMA - Initially the 10-10CG data was submitted to CARMA directly, but it was updated to submit to MuleSoft which handles sending the data to CARMA now. 

### Future APIs
- Okta - Not yet live but all work in vets-api has been completed. Planning to update the auth flow with MuleSoft to use Okta to generate an auth token this fall once the CARMA team finishes some updates.

**Comment by coope93** [comment]
@hdjustice @longmd @Mitch-A6 I went through the 10-10CG flow (mostly on the backend) and added the api's I am aware of. Let me know if I missed any or if we need to clarify anything here.

**Comment by hdjustice** [comment]
I think that is accurate from what I could find.  Thank you!  This information is documented in the checklist
