### ISSUE TITLE
Remove all AL1 review instances.

### ISSUE THREAD

**Issue by ben-allen-oddball** [department-of-veterans-affairs/va.gov-team#93183]
## Issue Description
Remove / destroy all AL1 review instances and merge / test AL2 code in devops repo.

---
## Tasks
- [x] Merge new AL2 code into the DevOps repo (Sept 21 or 22)
- [x] Remove / destroy all existing AL1 review instances. (Sept 21 or 22)
- [x] Test / validate AL2 Review deploy from main branch (Sept 21 or 22)

## Acceptance Criteria
- [x] No more AL1 Review instances exist
