### ISSUE TITLE
Create new, simplified visual of Collab Cycle touchpoints

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#93198]
## User Story
As a VFS team member, I want to visually see what touchpoints are in the Collab Cycle and how to flow through them so that I am able to meet the expectations of Platform.

Assignee: @allison0034 
Peer Reviewer: @erinrwhite 

## Description
With the introduction of the new PO Sync and the Architecture intent (along with the planned Engineering & Security track) we need to create a helpful visual aid for VFS teams to understand what touchpoints exist in the Collab Cycle, what track they're on (if any) and what phase of development they should occur in. 

Are there other features/information we should be including in this visual? 

Please keep in mind that this should be a simplified visual aid for VFS teams. It should be noted that this doesn't have to be the _only_ visual aid that Governance provides. If we feel a secondary visual of the Collaboration Cycle would be helpful to demonstrate the specifics around each touchpoint, please share with Shira and we can work on in a separate ticket. 

### Live pages
- 

### Drafted pages
- [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727377585674/2799354ec00423d2403b66482662a2c80ccab903?sender=u870c8d9c6b47768924793768)

## Tasks
- [x] Create new flow
- [x] Get feedback from team

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have drafted a new, simplified visual of the Collaboration Cycle and the included touchpoints that has been reviewed and approved by Governance team members

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Shira's rough concept <img width="678" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1BxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d674f50ac4930dabde65a8638917dafba0a9d9e7/rough_flow_CollabCycle.png" alt="rough_flow_CollabCycle.png" />

**Comment by shiragoodman** [comment]
Comments from team on Shira's design:

- Don't like the 3rd column (Additional Services)
- CMS, Analytics and Contact Center can fit it whenever
- aligns with my idea of simplifying
- good start
- talk about phases and the phase names
- looks really "waterfall-y" - how can we make it more agile-looking?
- indicate required touchpoints with an asterisk? something small/easy. bold border or text.
- Do we want to indicate that steps can be repeated?
- from a dev perspective, blurring of the phases. sometimes you're testing and developing at the same time.
- agree with 3rd track. a little confusing.
- This is much easier to digest immediately than what came before.
-

**Comment by allison0034** [comment]
[Started Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727377585674/2799354ec00423d2403b66482662a2c80ccab903?sender=u870c8d9c6b47768924793768)

**Comment by allison0034** [comment]
@erinrwhite want to take a look at the [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727377585674/2799354ec00423d2403b66482662a2c80ccab903?sender=u870c8d9c6b47768924793768) and let me know your thoughts? I have 2 very similar visuals.

**Comment by allison0034** [comment]
@erinrwhite ready for your final review.

**Comment by shiragoodman** [comment]
@allison0034 I'd like to get opinions of folks outside of Governance team. Would you mind sharing this visual with a few additional folks, maybe a couple from Platform, and a couple others from VFS, to get their thoughts and opinions? yes, it's readable and understandable for us on Governance, but I want to make sure others are able to understand and digest it too. Please lmk if you need some help determining who to share it with.

**Comment by allison0034** [comment]
Sure, who on platform would you like me to reach out to? I am sure I can find some PMs on VFS teams.

**Comment by shiragoodman** [comment]
sorry, @allison0034 . I didn't check my notifications all day yesterday! 

We did talk about this flow at our 1:1 on 10/4. At this time, please hold off on contacting other PMs and VFS teams. To reiterate what was said yesterday, I'd like to try and move away from the Governance touchpoint-centric view. Right now, our touchpoints may be the main flow and main path of Collab Cycle, but that won't always be the case. We do need to ensure that the Engineering & Security track (right now, just the Arch Intent) is also front and center. 

Let me know if you'd like to discuss further. Thank you!

**Comment by allison0034** [comment]
Met with Governance team and we voted on a possible visual solution. Per Shira I am closing this ticket.

**Comment by erinrwhite** [comment]
@allison0034 looking good - ticket good to close. 👍🏻
