### ISSUE TITLE
Provide good release strategy guidance and VSP process

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#932]
## User Story
As a VFS Team, I need to know how to create an effective release strategy and plan, so I can test safely in production and iterate to meet success criteria before launching my new product to millions of users.

## Goal
VFS Teams are following our guidance and using beta / feature flags and other iterative release methodologies to effectively test in production and have a strong indication of how their product will be used, how it'll impact users, and how it'll impact VA business prior to going fully "live".

## Notes
- Unicorns, CMS team, Krakens, and VA.gov Launch team, have put together solid release plans in the past leveraging phased rollout methods w/criteria that must be met before moving on to the next phase, and KPIs to track success. Could be good to interview them and review their docs to get a good foundation in place.

## Acceptance Criteria
- [ ] Documentation w/templates and guidance exists
- [ ] Any required or optional processes are documented (i.e. how/whether we'll validate plans, how VFS teams can collab w/us on this, do we require a Go/No Go mtg at each phase?)
- [ ] Docs have been shared in Slack and presented to VFS Teams for awareness
