### ISSUE TITLE
Silent Errors Audit (DUE October 1st)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#93202]
## Description

Perform an Audit of the Debt Portal to identify and record any instances of Silent Errors that need to be addressed.

Guidance from the platform team on how to manage errors can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md#reporting-errors-to-octo).

## Tasks
- [x] Document Silent Error occurrences
- [x] Definition of documented errors
- [x] Record any additional error data
- [x] Create a checklist
    * [Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/back-end/silent-errors/checklist.md)
## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [X] Not Required

## Acceptance criteria
- [ ] All the documentation from the audit is linked to this ticket
- [ ] PO has reviewed and approved the documentation
- [ ] Any tickets are drafted to address any issues that need to be corrected immediately

## Testing
- [X] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [X] Description written
- [X] Tasks defined
- [X] Acceptance criteria written
- [X] Testing defined
- [X] Add Labels
- [X] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
I think we've done as much as we can for the time being! Moving to blocked until Derek can get his hands on

**Comment by digitaldrk** [comment]
[debt_slient_error_report.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejRjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4046e8d97922b810e9a613e66f6624aee0bbdcbf/debt_slient_error_report.xlsx)

**Comment by Tom-Davis** [comment]
@digitaldrk @Dr-Pongo I believe this can be closed, correct? @denisecoveyduc do you have everything you need for the audit phase?

@dhill802 FYI

**Comment by denisecoveyduc** [comment]
@Tom-Davis TBD to be honest.  Unless we need to move it we have a meeting tomorrow (10/10) to sync up on all things related to the silent failures work. Let's plan to revisit this ticket during that discussion.
