### ISSUE TITLE
Create source of truth Pension user flow in Figma

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#93212]
## Issue Description
The parts of the  Pension Figma file is out of date with what is on PROD as well as bloated so working with it is slow. In this ticket we want to create an new, cleaned up source of truth Figma file that matches with what's on PROD
---
## Tasks
- [x] Create a new well organized user flow file in Figma that uses best practice standards to organize the file 
- [x] Make sure the flow matches with what's in PROD
- [x] Share with the team to ensure we all have the same understanding of how the file is set up.

## Acceptance Criteria
- [x] New Figma file is created that represents what is in PROD

**Comment by echin393** [comment]
We discussed in our [HCD backlog workshop](https://docs.google.com/spreadsheets/d/1A1scap82CI3kbPwfTKodVeZ5ZLJgqQFEUjsg2hrn_zE/edit?gid=0#gid=0) that this ticket can be closed. I did another review of prod and updated the content accordingly in Figma – although there may still be differences in the list and loop pattern and in spacing.
