### ISSUE TITLE
Review old (Figma) design backlog tickets

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#93213]
## Issue Description
We want to review this older Figma update tickets in the design backlog to see if they can be worked on, updated or closed/won't do.

---
## Tasks
- [x] Review tickets the following tickets: #80847, #80636, #73158
- [x] Determine if they should be:
 1. worked on, then set the Status to "Needs Refinement"
 2. requirements of the ticket adjusted due to recent changes, then edit ticket requirements then set the Status to "Needs Refinement"
 3. no longer needs to be done due to recent changes, then add a comment to note why we no longer need to work on it then close the ticket. 

## Acceptance Criteria
- [x] The 3 noted tickets are reviewed and updated accordingly.

**Comment by echin393** [comment]
All three backlog tickets have now been moved to "Needs Refinement"; notes for what has been updated and outstanding design questions are in each of the individual tickets.
