### ISSUE TITLE
Copy of Audit Confirmation Email Copy

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#93210]
## Issue Description
_Review the confirmation emails Veteran's receive when submitting a Chapter 36 or COE claim to ensure the copy is accurate and complies with Platform standards. (Chapter 31 was reviewed and updated in February 2024. Burial was reviewed in June 2024.)_

---
## Tasks
- [ ] Submit Chapter 36 confirmation email copy for CAIA review
- [ ] Submit COE confirmation email copy for CAIA review

## Acceptance Criteria
- [ ] Follow on tickets as needed
---
