### ISSUE TITLE
[FE] My VA Forms Status: Spacing updates

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#93222]
## Background
Matt identified some minor discrepancies in the form status work on staging.

1. The Received cards have an extra line of spacing at the bottom of them
2. There is supposed to be 4px between the alert on Action Needed cards and the text above it ("Submission failed on: X"), as well as 4px between that and the download link when available, that isn't currently there.
3. Spacing between the Tag and the card title should be 12px, it's currently 16px.
4. Spacing between the card title and the form number ("VA Form 21-4142") should be 4px. It looks like something happened with the Figma file that accidentally added a little more spacing below the title, which was not intended. 

## Tasks
- [ ] Screenshare with Matt if needed to go through findings
- [ ] Address spacing issues as identified above
- [ ] Request review from Matt for validation once on staging

## Acceptance Criteria
- [ ] Spacing issues are resolved

## Resources
- [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1726767914095139)

**Comment by allisonlu** [comment]
PR opened and approved - I put a `DO NOT MERGE` label and [commented for context](https://github.com/department-of-veterans-affairs/vets-website/pull/32251#issuecomment-2392267063)

**Comment by allisonlu** [comment]
PR merged! will tag matt and aj once this gets onto staging and is ready for validation

**Comment by allisonlu** [comment]
@ajakabcin @mattmarino-adhoc 

ready for validation! log in as user 88 and confirm the spacing discrepancies listed in the description have been addressed.

**Comment by mattmarino-adhoc** [comment]
@allisonlu I may be inspecting this incorrectly but it appears that the spacing between the title and the form name is 14px (10+4), at least for some of the cards? Can you confirm before I approve?

**Comment by mattmarino-adhoc** [comment]
@allisonlu said as much on Slack but to confirm: LGTM, ready to merge!
