### ISSUE TITLE
Respond to the discovery effort on Zero Silent Failures

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#93229]
## Background
Matthew Dingee posted a request asking all VFS to review their products for silent failures. Here's the post - https://dsva.slack.com/archives/CE4304QPK/p1726600494318029

Respond to his request.

## Tasks
- [x] Reviewed the [How to discover if your application has a silent failure](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md) document
- [x] Respond accordingly

## Acceptance Criteria
- [x] This has been handled

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by holdenhinkle** [comment]
I reviewed the [How to discover if your application has a silent failure](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md) document and determined ARM's products do not have any silent failures.

ARM's products currently do not persist, process, or submit any forms or other requests like file uploads or performing an action (such as refilling a prescription or ordering supplies), etc..

I posted to the #zero-silent-failures Slack channel that we do not have any silent failures - https://dsva.slack.com/archives/C07KTTFP308/p1726771961196239

**Comment by holdenhinkle** [comment]
cc @parkerbees

**Comment by oddball-lindsay** [comment]
I was suspecting we were ok on the silent failures front and have been meaning to review the [Managing Tagging Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards) and guideline for [Managing Errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md) to confirm.

Thanks @holdenhinkle for taking the lead and confirming!

**Comment by holdenhinkle** [comment]
### Checklist

#### Start

* [ ] Do you know when your application shipped to production?
  * If not, use Github to determine, roughly, when your application shipped to users.
* [ ] Did your application use the same APIs when it shipped as it does today?
  * If not, then you'll need to consider the path user data took through both the current architecture and the previous architecture. You will need to account for potential failures in all paths since your application shipped.

#### Monitoring

* [ ] Do you monitor the API that you submit to via Datadog? 
  * If not, [set up monitoring in Datadog](#set-up-monitoring-in-datadog).
* [ ] Does your Datadog monitoring use the appropriate tagging?
  * If not, [implement tagging standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards). Adding the [dependency tag](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards#MonitorTaggingStandards-Recommended:dependency) is highly recommended!
* [ ] Do errors detected by Datadog go into a Slack notifications channel?
  * If not, start directing errors in Datadog to a dedicated Slack channel. See [#veteran-facing-forms-notifications](https://dsva.slack.com/archives/C063SM22J3H) for an example.
* [ ] Does more than one person look at the Slack notifications channel containing errors on a daily basis? 
  * If not, then follow this [guide on managing errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md)
* [ ] Do the team members monitoring the Slack channel have a system for acknowledging and responding to the errors that appear there? 
  * If not, then follow this [guide on managing errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md)

⚠️ **Failure to have endpoint monitoring in place is a blocking QA standard at Staging review as of 9/10/24.** If you answered no to any of the questions above, you will be blocked from shipping at the Staging review touchpoint in Collab Cycle.

#### Reporting errors

* [ ] Have you filed issues for errors that are appearing in Datadog / Slack?
  * If not, then start filing Github issues for new categories of errors following [this guidance](#file-silent-errors-issues-in-github)
* [ ] Do all fatal errors thrown in your application end up visible to the end user either in the user interface or via email?
  * If not, then file Github issues to capture error categories following [this guidance](#file-silent-errors-issues-in-github)

#### Documentation

* [ ] Do you have a diagram of the submission path that user data your application accepts takes to reach a system of record? 
  * If not, then [create a user data flow diagram](#how-to-create-a-user-data-flow-diagram) that captures this information. 
* [ ] Do you understand how the error is handled when each system in the submission path fails, is down for maintenance, or is completely down?
  * If not, then create documentation that captures how errors in each system are handled. Detail which systems retry a submission and what happens when those retries exhaust. Show this in your diagram.
* [ ] Has the owner of the system of record receiving the user's data indicated in writing that their system notifies or resolves 100% of fatal errors once in their custody?
  * If not, work with OCTO to meet with the owner of the system and get their agreement in writing.
  * Please document the outcome of this conversation in your product's documentation in Github.

#### User experience

* [ ] Do you capture all of the potential points of failure and make those errors known to the user via email notification and/or through the application on VA.gov or the mobile application?
  * If not, don't worry. Few teams are doing this and we'll be providing resources to help you do this in your application. Proceed to [create a user data flow diagram](#how-to-create-a-user-data-flow-diagram). That diagram will help us to help you and your team to create this user experience.

**Comment by holdenhinkle** [comment]
Please check if this needs to be done; I'm pretty sure it does:

Does your Datadog monitoring use the appropriate tagging?
  * If not, [implement tagging standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards). Adding the [dependency tag](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards#MonitorTaggingStandards-Recommended:dependency) is highly recommended!

***

This needs to be done too (see my comments below).

#### Documentation

* [ ] Do you have a diagram of the submission path that user data your application accepts takes to reach a system of record? 
  * If not, then [create a user data flow diagram](#how-to-create-a-user-data-flow-diagram) that captures this information. 
  * **NOTE FROM HOLDEN:  Looking at the examples notes here, the diagrams I referenced above are not sufficient.** 
* [ ] Do you understand how the error is handled when each system in the submission path fails, is down for maintenance, or is completely down?
  * If not, then create documentation that captures how errors in each system are handled. Detail which systems retry a submission and what happens when those retries exhaust. Show this in your diagram.
  * **NOTE FROM HOLDEN: I should document our error handling for Find A Rep and the POA widget**

**Comment by holdenhinkle** [comment]
One you complete the above items, please comment in the [#zero-silent-failures](https://dsva.slack.com/archives/C07KTTFP308) Slack channel and link to the completed/updated checklist in this ticket (or elsewhere if there's a better place to document the checklist).

This is due October 1st.

Thank you so much

**Comment by oddball-lindsay** [comment]
Priority for next sprint: 
1. Ensure existing Datadog monitoring meets the tagging standards - #93851
2. Update Find and Widget technical documentation to meet new platform standards #93852

**Comment by oddball-lindsay** [comment]
Posted in #zero-silent-failures with an update that we've gone through the checklist and while we don't have any silent failures, we do have the two action items listed above.

https://dsva.slack.com/archives/C07KTTFP308/p1727810789674669

**Comment by holdenhinkle** [comment]
Thank you @oddball-lindsay
