### ISSUE TITLE
FE-BE | Profile | Maintenance Windows

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#93234]
## Background

When an external API that VA.gov Profile relies on is undergoing maintenance, users should see a maintenance notification within the relevant UI component, informing them of the service disruption so they can adjust their actions accordingly.

## Tasks

Contact Information

- [x] API service code used to trigger maintenance window - `vapro_contact_info`.
- [x] FE: Add a UI notification that displays when an active maintenance window is found for the component's external API.
- [x] BE: Add a PagerDuty service to staging.
- [x] BE: Add a PagerDuty service to production.

Direct Deposit Information

- [x] API service code used to trigger maintenance window - `lighthouse_direct_deposit`.
- [x] FE: Add a UI notification that displays when an active maintenance window is found for the component's external API.
- [x] BE: Add a PagerDuty service to staging.
- [x] BE: Add a PagerDuty service to production.

Military Information

- [x] API service code used to trigger maintenance window - `vapro_military_info`.
- [x] FE: Add a UI notification that displays when an active maintenance window is found for the component's external API.
- [x] BE: Add a PagerDuty service to staging.
- [x] BE: Add a PagerDuty service to production.

Notification Settings

- [x] API service code used to trigger maintenance window - `vapro_notification_settings`.
- [x] FE: Add a UI notification that displays when an active maintenance window is found for the component's external API.
- [x] BE: Add a PagerDuty service to staging.
- [x] BE: Add a PagerDuty service to production.

Personal Health Care Contacts

- [x] API service code used to trigger maintenance window - `vapro_health_care_contacts`.
- [x] FE: Add a UI notification that displays when an active maintenance window is found for the component's external API.
- [x] BE: Add a PagerDuty service to staging.
- [x] BE: Add a PagerDuty service to production.

Personal Information

- [x] API service code used to trigger maintenance window - `vapro_personal_info`.
- [x] FE: Add a UI notification that displays when an active maintenance window is found for the component's external API.
- [x] BE: Add a PagerDuty service to staging.
- [x] BE: Add a PagerDuty service to production.

## Acceptance Criteria

The following Profile components should each be mapped to a PagerDuty service. When a maintenance window is active, the component should display a maintenance notification to the user if the current time falls within the start and end times of the window.

- [x] Contact Information
- [x] Direct Deposit Information
- [x] Military Information
- [x] Notification Settings
- [x] Personal Health Care Contacts
- [x] Personal Information

These can be tested in staging (and potentially in production by using short off-hour maintenance windows).

**Comment by tpharrison** [comment]
- [BE Staging PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3134#pullrequestreview-2346361067)

**Comment by tpharrison** [comment]
@nickjg231 The BE changes are deployed in staging.  Let me know when the FE changes are deployed so we can test.  BE production changes have been approved an will be deployed on Monday, Oct 7th.

**Comment by ACParker89** [comment]
@nickjg231 @asiisii @tpharrison - will the validation for this roll into 47?
