### ISSUE TITLE
Collaboration Cycle for [IIR Team, Veteran Status Card, New Home & User Experience]

### ISSUE THREAD

**Issue by mcommons10** [department-of-veterans-affairs/va.gov-team#93231]
Please view the [Milestone](https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1413) for all feedback and findings tickets associated with this Collaboration Cycle initiative. 
 
### VFS team name

Iterate, Innovate & Run

### Product name

Veteran Status Card

### Feature name

New Home & User Experience

### GitHub label for team

va-iir

### GitHub label for product

veteran-status

### Public DSVA Slack channel for VFS team

iir-product-teams-public

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

August 2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Unsure

### Do you need to capture any additional analytics or metrics?

Yes

### Will a VA editor (Drupal) notice this change?

No

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-status/v2-IIR/new-home-and-ux-product-outline.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C05RJS5DANT/p1726772832990199)
</details>

### PO Sync
<details>
  <summary>Toggle PO Sync instructions</summary>

##### OCTO Product Owner
- [x] Review [PO Sync Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/po-sync) to understand what this sync involves.
- [x] Schedule your PO Sync (with at least 2 business days lead time from now):
  - Open the [Calendly PO Sync calendar](https://calendly.com/collaboration-cycle/po-sync)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Schedule Event"
- [x] Link all artifacts in the `PO Sync artifacts for review` section below at least two business days before the scheduled PO Sync. Please don't add artifacts in the comments section.

**PO Sync artifacts for review**
[See guidance on PO Sync artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/po-sync#POSync-Whatartifactswillbeneeded?) Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-status/v2-IIR/new-home-and-ux-product-outline.md)

Optional:
- [x] Any other artifacts you have so far: [Link to draft of Figma designs](https://www.figma.com/design/AobGKkBvIiDuYXR2QqkytC/IIR-Veteran-Status?node-id=989-26713&node-type=canvas&t=v9UpIqDHlSeEoEwY-0)

##### Governance Team actions
- [x] Meeting date/time: **Tuesday, October 1, 2024 at 11:00am ET**

##### OCTO PA Leads
- [ ] If the initiative receives OCTO alignment to proceed, add the PO-Sync-approved label to this ticket.
- [x] If the initiative does not receive OCTO alignment to proceed, comment and close this ticket. 

</details>

### Design Intent

<details>
  <summary>Toggle Design Intent instructions</summary>

##### VFS team actions
- [X] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [X] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [X] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.
  
**Design Intent artifacts for review**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [X] [User flow](https://www.figma.com/design/AobGKkBvIiDuYXR2QqkytC/IIR-Veteran-Status?node-id=989-26713&node-type=canvas&t=2am6B7ZLC6Wc8Alr-0)

Not required, but nice to have:
- [X] [Wireframes](https://www.figma.com/design/AobGKkBvIiDuYXR2QqkytC/IIR-Veteran-Status?node-id=989-26713&node-type=canvas&t=2am6B7ZLC6Wc8Alr-0) (if provided, must include mobile wireframes)

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Governance Team actions
- [x] [Design Intent Slack thread with VFS team](https://dsva.slack.com/archives/C05RJS5DANT/p1727356135317089)
- [x] Meeting date/time: 01:30pm Eastern - Thursday, October 3, 2024
  
##### Governance Team actions

- [x] Update this ticket with the Zoom recording
  - [Recording link
](https://oddball-io.zoom.us/rec/share/af2P5NTdXJ8377t6Gv-Ne9Q1cVh71arkml2IQBT6tbXTB7iO_kjJleGujB3Yt0-1.3m5nM91MS5PaKtTH) 
 - Passcode: `XMmnUK.0`
- Accessibility
  - [x] Feedback ticket attached
  - [ ] No feedback
- Design
  - [x] Feedback ticket attached
  - [ ] No feedback
- IA
  - [x] Feedback ticket attached
  - [ ] No feedback
  
##### VFS team actions

- [x] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  

</details>

### Architecture Intent
<details>
  <summary>Toggle Architecture Intent instructions</summary>

##### VFS team actions
- [x] Review [Architecture Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent) to understand what this touchpoint involves.
- [x] Schedule your Architecture Intent (with at least 2 business days lead time from now):
  - Open the [Calendly Architecture intent calendar](https://calendly.com/collaboration-cycle/architecture-intent)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [x] Link all artifacts in the `Architecture Intent artifacts for review` section below at least two business days before the scheduled Architecture Intent. Please don't add artifacts in the comments section.
  
**Architecture Intent artifacts for review**

[See guidance on Architecture Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent#ArchitectureIntent-Whatartifactswillbeneeded?) Feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [x] Fully completed [Architecture Intent Meeting](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/collaboration-cycle/architecture-intent/checklist/va_iir-veteran_status-01232025.md)
- [ ] [User data flow diagram](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-create-a-user-data-flow-diagram.md), if your application accepts data from a user.

##### Platform Team actions
- [x] Meeting date/time:  01:30pm - Tuesday, January 28, 2025 (Eastern Time)

##### Platform Team actions

- [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode:
- Engineering feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback
- Mobile Engineering feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback
- Security feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback  

##### VFS team actions

- [x] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [x] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review

<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

**Required artifacts**
- [x] [Design prototype or high-fidelity mockup](https://www.figma.com/design/AobGKkBvIiDuYXR2QqkytC/IIR-Veteran-Status?node-id=2898-86364&t=aBpZ9fBxlJyeDI6w-0)
  - The designs in the green boxes are what we are focused on reviewing. We've added the current live designs and a previous design iteration that was used in testing for additional context.
- [x] Up to date user flow (User flow is incorporated in the figma files)
- [x] Link to [CAIA intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95487#issuecomment-2460274331) 

**Not required, but nice to have artifacts**
- [ ] Accessibility annotations included as part of your design
- [ ] Research plan
- Links to specific CAIA artifacts:
  - [ ] IA spec
  - [ ] Content source of truth
- Any other artifacts you have so far
 
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C05RJS5DANT/p1737668295266989)
- [x] Meeting date/time: 02:00pm - Friday, January 31, 2025 (Eastern Time)

##### Platform actions

* Accessibility
  * [x] Feedback added to milestone
  * [ ] No feedback
* Content
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Design
  * [ ] Feedback added to milestone
  * [ ] No feedback
* IA
  * [ ] Feedback added to milestone
  * [x] No feedback
* [x] Update this ticket with the Zoom recording
- [Recording link](https://oddball-io.zoom.us/rec/share/sD4pgOJIaE5GPDJIBccIeZi_khMBFskXBPUqPc1YjoLwFWW722j8NoZJvOQnhpTH.mjjwQoazESV6_mPS)
- Passcode: `tUYK29%5`
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns

</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/112823

</details>

### Staging Review

<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**

Link to all of our [Staging Review artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-status/v2-IIR/redesign-staging-review-artifacts.md#veteran-status-card-redesign-staging-review-artifacts)

**Required artifacts**
- [x] **URL(s) to review the product**
  - The product should be available on an [approved staging environment](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-environment-guidance-for-vfs-teams). 
  - List pages, sections of pages, and/or user flows impacted by this work.
- [x] **Drupal or Staging URL for updated primary entry point:** the main way Veterans will access the tool through site navigation (not search)
  - If the primary entry point is not a page on VA.gov, include information about how to view it. Reach out to `@platform-governance-team-members` on Slack with any questions.
- [x] **Test users and scenarios** (when applicable)
  - Store [test user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md), passwords, and tasks in a .md file in the va.gov-team-sensitive repository. 
  - Make sure all user scenarios can be tested, i.e.: in-progress form, submitted form, new form.
- [x] **Link to Sitewide CAIA intake ticket**, if applicable.
- [x] **Completed accessibility testing artifact:** see [instructions and link to accessibility testing template](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
- [x] **QA Artifacts:** artifacts that correspond to each of the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
  - [x] Regression test plan
  - [x] Test plan
  - [x] Coverage for References
  - [x] Summary (Defects) reports
  - [x] E2E tests
  - [x] Code coverage
  - [x] Endpoint monitoring playbook
  - [x] Logging silent failures

**Not required, but nice to have artifacts**
- [ ] **Content source of truth:** link to CAIA Content feedback, such as a content source of truth.
- [ ] **Information Architecture spec:** link to CAIA IA feedback, such as an IA spec.
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C05RJS5DANT/p1749838213175739)
~~- [x] Meeting date/time: 11:30am - Tuesday, June 17, 2025 (Eastern Time)~~
- [x] New Meeting date/time: 02:00pm - Friday, June 20, 2025 (Eastern Time - US & Canada)

##### Platform actions

- [ ] Update this ticket with the recording
  - [Recording link ](https://urldefense.com/v3/__https://dvagov-my.sharepoint.com/:v:/g/personal/shira_goodman_va_gov/EbhCc5mWyLlAs1ZgRAuOl5EBP_NSzNMudv0okavA54tvQw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=VdbvFM__;!!K2n62VMvFw!DCuEZW8xSpxEzpFiQTOv5tCY-4gacYcGsxIBtcCuEwnaeFQwvLHwWnpxqS28HeyyHe8LVoldT2cxmO4VuGvMwhM02HUraoiPZb4%24)
  
##### VFS actions
  
- [x] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [x] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [x] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [x] Share ServiceNow ticket number here: REQ45443613
- [x] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
- [ ] [Complete Collaboration Cycle feedback survey](https://ows.io/qs/gb1dfnkl)

</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/4120

#### Platform actions
- [x] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by mcommons10** [comment]
Just wanted to call out that this project includes mobile app work and designs.

**Comment by humancompanion-usds** [comment]
PO Sync happened on Tuesday 10/1. Good discussion on how this team might determine if the status card is being accepted as well as the path to replace the VIC.

**Comment by rtwell** [comment]
Reviewing the problem statements from the product outline, I did want to bring up some points that would be great to clarify:

Problem statement:

> * The web and mobile app experiences are not aligned (they have different homes in each experience and look very different)

* This is not a known problem (at least to the mobile team). It would be helpful if we listed specifics (both the differences and why they are problems). Without this, we cannot measure these changes. 

> * It is not an industry standard experience (think airline tickets, event tickets, insurance cards, etc.)

* Can we define what standards we want to meet? and by what measure? Veteran Status is not the same as the examples listed (outside of the "wallet" UX), so it would be good to understand what standards we want to meet, and making sure they align with this feature. It's hard to know what problem meeting "industry standards" is solving.

**Comment by mcommons10** [comment]
Great questions @rtwell. Here are my thoughts:

In regards to web and mobile alignment:
- On the mobile app, vet status is very easy to find as it lives on the homepage and is also at the top of the profile page. This is not the case on web. On web it lives at the bottom of the /military-information page and we believe this makes it hard for users to find and access (in August there were ~533k views for vet status in the mobile app and ~13k views on the web).
- On the mobile app, vet status is a page, on web it is in an actual card format. We want to align on a card format across experiences so it can be consistent and businesses who are validating users’ vet status have a single card/design/pattern to reference whether it is being used from the mobile app, the web, or a printed version.

In regards to industry standard experience:
- I think what I was getting at with this problem statement is actually covered in the second bullet: _The current experience is not meeting OCTO/government goals of having digital experiences that are “consistent with [the public’s] favorite consumer websites and mobile apps.”_ Adding add-to-wallet capabilities and not requiring users to print the card from the web are the main changes we want to make to support this problem statement.

**Comment by rtwell** [comment]
thanks for the follow up @mcommons10 

> On the mobile app, vet status is very easy to find as it lives on the homepage and is also at the top of the profile page. This is not the case on web. On web it lives at the bottom of the /military-information page and we believe this makes it hard for users to find and access (in August there were ~533k views for vet status in the mobile app and ~13k views on the web).

is this because users can't find it or because most users don't go to a website for this sort of thing? just because web has fewer views than the app doesn't mean it isn't findable…it might mean the modality isn't a good fit (eg not only do users have to jump through the hoops of signing in, then they have to download, print, remember to take it with them. The app is always there and VS is just a tap or two away.) The appointments space is another good example: historically there are far fewer appointments in the month of December, which could be perceived as a problem because a number is going down, but the reality is its the holidays and people tend to not book as many appointments (and ideally are also getting healthier). given that, fewer views simply does not conclusively mean "this is not working". So, how do we plan on knowing what we're doing is meeting needs? I wonder if there is some research that needs to happen here. just my 2¢.


> On the mobile app, vet status is a page, on web it is in an actual card format. We want to align on a card format across experiences so it can be consistent and businesses who are validating users’ vet status have a single card/design/pattern to reference whether it is being used from the mobile app, the web, or a printed version.

This still sounds hypothetical to me—do we **know** that this is a problem? the app has been active for ~4 years with _a lot_ of differences between web and we have yet to hear feedback that these differences were a problem (a user was trying to complete some kind of task, but couldn't). While I'm all for consistency and continuity, I think these should be coupled with known user problems so we have a framework to operate. and again I would like to emphasis how we measure the success of these adjustments?. To my knowledge, we don't know if this actually works in retail stores (in either of its current forms), so what baseline are we starting with to measure these improvements?

**Comment by mcommons10** [comment]
@rtwell - 
It is clear that mobile is doing something right based on the traffic numbers and I agree that less views on web doesn't mean there is a problem. One of our hypotheses is that the mobile placement/IA is driving find-ability. This assumption is supported by our current data.  We would like to test a similar pattern on web to see if we can improve our current baseline. 

If Vet Status ends up replacing the VIC (which is an active conversation cc: @JeffBarnesUSDS), not having it available on all platforms would be a blocker to adoption. 

Our hypothesis is that Vet Status is missing standardizations that are preventing a unified cross platform digital experience. They are the same product but as a user we want to test if that is intuitively understood. This isn not to say that the the web and mobile experiences should be identical, but they should be related and complimentary. 

Thanks for the note about the mobile app card design. Exactly the type of feedback we were hoping from the Design Intent.

**Comment by rtwell** [comment]
@mcommons10 
It would be helpful to define what a "unified cross platform digital experience" means and for the team to propose how they plan to measure the efficacy of this. 

> If Vet Status ends up replacing the VIC (which is an active conversation cc: @JeffBarnesUSDS), not having it available on all platforms would be a blocker to adoption.
I'm not suggesting it shouldn't be across platforms. Can you please clarify?

**Comment by mcommons10** [comment]
@rtwell 
In my mind a unified cross platform digital experience = to the extent possible, common IA, design and UX patterns; however, this is a broader VA wide convo I'd like to involve Jeff in. It's my understanding that building that cohesion is the reason for working towards Experience Teams. Right now web and mobile act different, look different, and live in different places. 

> I'm not suggesting it shouldn't be across platforms. Can you please clarify? 

Wanted to call that out specifically since there could reasoning to say mobile gets 40x more views and isn't worth continuing to build out on web.

**Comment by mcommons10** [comment]
Thanks @strelichl! We actually had a ticket next sprint to submit an intake ticket - glad we're on the same page. We do have some specific things we are wanting content help with. We'll keep you posted next week once we finish a few things on our end.

cc: @DavidPearlUX

**Comment by DonMcCaugheyUSDS** [comment]
Thanks for participating in today's Architecture Review meeting.  Here are our suggestions:

- continue to think about if/how disability rating is included on the card
- work with the help desk team to build playbook of troubleshooting steps when the card is not available for a Veteran or there is an error
- add some end-to-end tests to ensure the new card is correctly integrated in the profile page

**Comment by rtwell** [comment]
Must
- Users must know they can scroll on the screen. I suspect this will be addressed when we:
  - Move the sentence at the top below the card
- Content at the bottom - Start with the bare minimum and expand/add from there. The minimum = what is on Veteran Status now. 
- Users must we able to easily read the card when holding in shaky hands from a distance (eg holding the phone out at arms length so an employee at Home Depot can easily read the card—both in horizontal and vertical orientations. 
  - This may be achieved by exploring which text is bold
  - Additionally, the card must adapt to the use case where both Text Size and/or Display Zoom are enabled on a phone
- Check with our a11y expert (who isn't here yet) but I believe the content below the card might need a header to ensure AT users can navigate easily

cc @mcommons10

**Comment by DavidPearlUX** [comment]
These edits have been made to [the figma file](https://www.figma.com/design/AobGKkBvIiDuYXR2QqkytC/IIR-Veteran-Status?node-id=3197-30380&t=dyq5H2F6NXpR9Bem-1). Thank you

David

**Comment by rtwell** [comment]
Hi @DavidPearlUX I would like to introduce you to @JonathanPostMO who recently joined the mobile app team. He'll be reviewing any design work that will live in the app. I've asked him to take a gander at this work to ensure it's meeting our standards.

**Comment by JonathanPostMO** [comment]
Hey @DavidPearlUX, looking forward to connecting tomorrow—cheers.
