### ISSUE TITLE
[BE] 10-10EZ - Zero silent failures: Set up VA Notify Callback integration for Submission Failure email

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93247]
## Benefit to the Veteran
As a Veteran, I want to be notified in some way that my application submission has failed, so that I can make corrective actions to resubmit.

## Scope
As part of the Zero silent failures initiative, we must ensure that any part of the 10-10EZ process from starting the application to successful submission and processing downstream is accounted for where ever there is a fatal error and the Veteran is not notified.  For this work, we want to set up Delivery Status callbacks from VA Notify so we can track anytime that a submission failure email fails to send to the Veteran.  This way, we can capture Veteran data and ensure they are contacted through our existing escalation process.
NOTE: There is a specific task to complete in the [Logging Silent Failures guidance](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/274bea7fb835e51626259ac16b32c33ab0b2088a/platform/practices/zero-silent-failures/logging-silent-failures.md#logging-silent-failures), once the VA Notify team has completed their effort to create a callback mechanism.

### Reference
- [VA Notify Callback integration document](https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/va_notify#va-notify-callback-integration-guide-for-vets-api)
- [Logging Silent Failures document with details](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md)
      - Be sure to use the "future" guidance
> In future, teams will be notified when VA Notify has a call back mechanism to determine if an email reached the intended recipient. At that time, teams should use the following log message:
>
>`tags = ['service:veteran-facing-forms', 'function: form submission to Lighthouse']
>StatsD.increment('silent_failure_avoided', tags:)`

## Tasks
- [x] Review the VA Notify Callback integration document for guidance
- [x] Implement the setup for the 10-10EZ Submission Failure email
     - Document how the team will be notified of the issue (Datadog?)
     - Consider in the event of multiple failures, how will we be able to tell which email send failed?  What identifying data will we have?
- [x] Create a new monitor (and logs?) in Datadog to track the email send failures
- [x] Complete QA testing as needed to ensure the functionality of the callback in the event of an email send failure
- [x] Update backend tests as needed
- [x] Review with PM prior to launch
     - Signoff required in the comments
- [ ] Launch to production
- [ ] Proceed to [#98589](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98589) to update documentation

## Acceptance Criteria
- We now have a process in place to monitor, track and remediate any email send failures

**Comment by allanto-ah** [comment]
QA comment: Regression has been completed and E2E was done with CARMA as well. Outside of regression there isn't much else we can QA.

**Comment by allanto-ah** [comment]
@hdjustice when you have a chance, can you please review? Thank you!

**Comment by hdjustice** [comment]
As long as we followed the process outlined for us from VA Notify team, then we should be fine.  If we do get a failure in the future, we will be extra diligent in checking to make sure it was logged appropriately as [Silent Failure avoided (email verified)](https://vagov.ddog-gov.com/dashboard/n6c-twn-swr/silent-failure-tracker?fromUser=false&refresh_mode=sliding&from_ts=1735592853025&to_ts=1736197653025&live=true) in the DD Silent Failures monitor as well as watching for our own [monitor](https://vagov.ddog-gov.com/monitors/306837) for emails failing

**Comment by hdjustice** [comment]
Moving ticket to BLOCKED

> for the vanotify callbacks, after talking with Nathan Wright on the vanotify team we discovered that since our emails are in their own service and not the general vets-api service, the current default callbacks don't work with them. It's something they are working on, but they had not done it yet just so they could get the basic functionality out first. He was able to enable it for us in staging, so we are able to successfully test it and the monitors, but I don't think we want to turn it on in production just yet. We currently still increment the required zsf metric that it could have failed, so we are still in compliance.

**Comment by coope93** [comment]
@hdjustice talked with VANotify and they said we should have the functionality we need to turn this on either next week or hopefully no later than the week after next.

**Comment by hdjustice** [comment]
ok, i will sched for next sprint.  If there is time to work on this before then, that is fine.

**Comment by coope93** [comment]
I merged https://github.com/department-of-veterans-affairs/vets-api/pull/20235 in and validated in staging that both formats work for passing the callback metadata. Planning to turn this on in production, which will ensure that the callbacks for this email work correctly. We still need to wait on VANotify to finish their change to add our service to the callbacks, but once that is in place and the flipper is turned on for the callbacks we are good to go.

**Comment by coope93** [comment]
We will want to turn https://vagov.ddog-gov.com/monitors/306837 on as part of this and make sure it is pointed to production and not staging. We may also want to talk with the EZR team to add a similar monitor.

**Comment by hdjustice** [comment]
Monitor is unmuted and pointed to PROD environment.

**Comment by coope93** [comment]
Flipper toggle `hca_zero_silent_failures` was removed from the `features.yml`and all environment databases.
