### ISSUE TITLE
Redis POAM: Configuration drift in devops Redis Terraforms

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#93265]
## User Story

As the team responsible for the Redis POAM,
We need to clean up configuration drift of our Redis clusters,
So that we can implement the POAM.

## Issue Description

In the context of the [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87249) for security enhancements in our  Redis clusters, it was discovered that the Terraforms in our the devops repo have experience configuration drift. This blocks the implementation of the Redis POAM and needs to be resolved.

## Tasks
- [ ] Address the configuration drift associated with all the clusters

## Success Metrics

- [ ] We can move ahead with the POAM

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
This work will be duped for Sprint 11 under ticket [93476](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93476)

**Comment by jennb33** [comment]
9/26/2024: @flooose needs to reach out to the Security team about Security groups  (and also to Hector?) to clarify some questions.
