### ISSUE TITLE
Submission failure for VRE on 9/20/24

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#93266]
# Overview
A submission failed for VR&E on the benefits intake API:
https://dsva.slack.com/archives/C06C2D2PJQZ/p1726805083750759

The submission failed with this:
`{"data":{"id":"bbbd2342-a7ca-4550-afd6-4f67460ad4fe","type":"upload","attributes":{"guid":"bbbd2342-a7ca-4550-afd6-4f67460ad4fe","code":"DOC202","updated_at":"2024-09-19T18:56:36.892Z","detail":"Upstream status: Unidentified Mail: We could not associate part or all of this submission with a Veteran. Please verify the identifying information and resubmit.","uploaded_pdf":{"total_documents":1,"total_pages":3,"content":{"page_count":3,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":1370351,"attachments":[]},"line_of_business":"VRE"},"status":"error","location":null}}}%`

This error is sometimes addressed just by resubmitting the form. 

I tried to find the submission but had no luck, which is odd:

`SavedClaim::VeteranReadinessEmploymentClaim.find_by!({ guid: 'bbbd2342-a7ca-4550-afd6-4f67460ad4fe' })`
```

(irb):2:in `<main>': Couldn't find SavedClaim::VeteranReadinessEmploymentClaim with [WHERE "saved_claims"."type" = $1 AND "saved_claims"."guid" = $2] (ActiveRecord::RecordNotFound)
irb(main):003> SavedClaim::VeteranReadinessEmploymentClaim.first
```

# Tasks 
- [ ] - Determine if the logged in veteran was a LOA1/LOA3, this will help us know if the kick-back of the submission was a mistake or legitimate.  Another way would be to just look at the submission itself and see if it looks reasonable. [Some documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity#planning-and-testing-identity) on identify levels.
- [ ] - If the submission looks reasonable, re-submit the form.
- [ ] - If the submission looks to be fake data from a logged in user, let's discuss options.

**Comment by mjknight50** [comment]
Any update on this ticket, please?

**Comment by tfink419** [comment]
I've checked a bit in production connecting with BGS and it appears this veteran is not registered in BGS at all. I ran `find_by_ssn` with the veteran's ssn number from the form and it returned empty

**Comment by steele-lm** [comment]
Follow the sharepoint remediation path. Submission will be zipped up and posted to SharePoint for manual remediation.

**Comment by steele-lm** [comment]
Claim was zipped up and uploaded to SharePoint by @evansmith
