### ISSUE TITLE
[CST] Update text on CST Homepage for "What if I don't see my appeal?" section

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#93274]
### Current UI:
<img width="1386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVB2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b81eb111fb6f2fd1564a5a1011737107e8c1778/Screenshot%202024-09-20%20at%2010.58.08%E2%80%AFAM.png" alt="Screenshot 2024-09-20 at 10.58.08 AM.png" />

### Suggested content:

**What if I can’t find my claim or decision review?**

If you recently submitted a claim or requested a decision review, we might still be processing it. Check back for updates. For more information, contact your Veterans Service Organization or representative.

---

This is a long outstanding content update request to match the "decision reviews" terminology instead of saying "appeals" as well as making a few other changes.

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- [FIGMA](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST-V2?node-id=621-10696&t=uNgwvoiQNysojpJg-4)

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Update text of "What if I can't find my appeal?" section of CST home page to match spec above_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Text has been updated_

**Comment by jstrothman** [comment]
Let's match the page title -- i.e. we refer to claims, decision reviews, or appeals, so that people can find the word appeal, if that's what they're looking for. 

So the content change here would be:

What if I can’t find my claim, decision review, or appeal?
If you recently submitted a claim or requested a Higher Level Review or Board appeal, we might still be processing it. Check back for updates. 

I'm surprised by the sentence: "For more information, contact your Veterans Service Organization or representative," as we don't assume people are working with a representative. Let's leave out the sentence, and rely on the 
"Need help" content that comes directly after this paragraph.

**Comment by skylerschain** [comment]
Updated mocks to match Julie's comment above.
