### ISSUE TITLE
Get appropriate GitHub groups created for deployment permissions

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#93278]
## Issue Description
There are two different groups that will be able to approve different kinds of deployments. One will be senior VFS developers who can approve team deployments that are in good standing. The other, will be platform approval, for teams that require a bit more oversight. 

Right now, there is a FE Admin group that serves as a support team group. This will need to be double checked to ensure it does not require updating.

Additionally, a group of senior VFS developers will need to be collected. This process may include having to inquire with each team for engineers that qualify. A maintenance plan for this group will also need to be developed to add future members while removing those that offboard.

---
## Tasks
- [ ] Check over front end admins group to ensure it is current.
- [ ] Collect list of senior VFS developers from teams
- [ ] Create GitHub senior VFS developer group
- [ ] Draft maintenance plan for VFS senior developer group.

## Acceptance Criteria
- [ ] All necessary GitHub permissions groups have been created and are current.

**Comment by CBonade** [comment]
https://github.com/orgs/department-of-veterans-affairs/teams/fe-deployment-approval-team group created here.
