### ISSUE TITLE
Implement permissions requirements on the deployment gate in CI

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#93279]
## Issue Description
Once we have GitHub teams created, we need to create the conditional logic that will determine the level of approval needed for each deployment in CI. This should start with everyone being allowed to deploy with senior VFS developer approval, and escalate to platform approval if it is deemed necessary. The CI deployment should automatically adjust to these conditions.

---
## Tasks
- [ ] Implement minimum approval permissions for deployments
- [ ] Make level of permission required conditional based on the circumstances of the application.

## Acceptance Criteria
- [ ] Permissions requirements have been set up for staged deployments.
