### ISSUE TITLE
Edit: Rename DSVA Slack to OCTO Slack 1 of 8

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#93297]
## User Story
"As a user of Platform Website, I want to see `OCTO Slack` used to reference the workplace in Slack, so that I know the related information is current."

## Description
There are currently ~8 pages on Platform Website still using DSVA Slack to refer to the VA's workspace.
The name has been changed to Office of CTO at VA some time ago.
We need to update all references to the workspace.

![Image](https://github.com/user-attachments/assets/70ce1a89-b4d2-4429-a677-b13957c68908)

- This edit is for the [Slack Profile](https://depo-platform-documentation.scrollhelp.site/getting-started/slack-profile) page

---
## Tasks
- [x] Locate usage of `DSVA Slack` on the page
- [x] Change to `OCTO Slack` - _Approved by PO Erika Washburn_

## Acceptance Criteria
- [x] All tasks completed
- [x] Page is ready for deployment

### Relevant artifacts:

- [VA Platform pages referencing DSVA Slack](https://docs.google.com/spreadsheets/d/1xdlq0Ssg6mBqE5_KSqytiSQLScMk1g1klY2vxKbCPv8/edit?gid=903934024#gid=903934024)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
'OCTO Slack' approved by PO Erika Washburn

**Comment by BSmolensky** [comment]
Are these going to have specific pages assigned to each of the 8 tickets? Without the specific pages, it's hard to accurately score.

**Comment by jknipes** [comment]
@BSmolensky Each specific page is linked at the bottom of the issue description

**Comment by BSmolensky** [comment]
@jknipes Thank you.
