### ISSUE TITLE
Frontend Build Pipeline Improvements

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#933]
## High Level User Story
As a VSP developer, I need quicker and more resilient build-times so I can spend less time waiting for CI to finish.

## Hypothesis/(es)
If we improve the build pipeline, developer satisfaction will increase because wait times will decrease.

## Goals
- [ ] Customer satisfaction is measurably increased

## Objectives
This work supports O1 and O3:

> O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

> O3: Stability and resiliency of the Platform's systems and teams continue to improve.

## Definition of Done
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Epic`**

**Comment by kfrz** [comment]
@alexpappasoddball @rianfowler I suggest we move this to the tools-fe
