### ISSUE TITLE
Edit: Rename DSVA Slack to OCTO Slack 8 of 8

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#93301]
## User Story
"As a user of Platform Website, I want to see `OCTO Slack` used to reference the workplace in Slack, so that I know the related information is current."

## Description
There are currently ~8 pages on Platform Website still using DSVA Slack to refer to the VA's workspace.
The name has been changed to Office of CTO at VA some time ago.
We need to update all references to the workspace.

![Image](https://github.com/user-attachments/assets/70ce1a89-b4d2-4429-a677-b13957c68908)

This edit is for the [Accessibility on VA.gov](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-on-va-gov) page

---
## Tasks
- [x] Locate usage of `DSVA Slack` on the page
- [x] Change to `OCTO Slack` - _Approved by PO Erika Washburn_

## Acceptance Criteria
- [x] All tasks completed
- [x] Page is ready for deployment

### Relevant artifacts:

- [VA Platform pages referencing DSVA Slack](https://docs.google.com/spreadsheets/d/1xdlq0Ssg6mBqE5_KSqytiSQLScMk1g1klY2vxKbCPv8/edit?gid=903934024#gid=903934024)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
this issue grabbed from the Backlog to be completed in current sprint due to available reserved capacity and low estimate

**Comment by jknipes** [comment]
Work is completed, closing as _done_
