### ISSUE TITLE
Immediate Care Alert Messaging for Veterans Scheduling Appointments

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#93314]
## Task Description
User Story: As a Veteran scheduling an appointment for an urgent matter, I need to easily discover and understand where I can get help for immediate medical needs without being overwhelmed by alerts.   The objective is to balance the need for Veterans to be aware of immediate care options without causing them to feel overwhelmed by constant alerts. By strategically placing these messages and making them dismissible, the tool aims to enhance the scheduling experience while ensuring critical information is communicated effectively.

## Notes and References
- Current workspace in [figma
](https://www.figma.com/design/2GyMzzLIpqN5mkYzXlwQ87/Scheduling-improvements-workspace-%7C-Appointments-FE?node-id=3154-8345&t=ps2Q8fksnblEI1VN-1)
## Acceptance Criteria
- [ ] Iterate the alert design based on Veteran feedback and feedback from the VHA mental health group.

## Deliverables
- Figma design file

---
## How to configure this issue
- [ ] Add title and task description
- [ ] Attach to an Epic
- [ ] Add labels based on work type: design, discovery, documentation, strategy
- [ ] Delete this section

**Comment by melissa-lefevre** [comment]
Proposed screens:

1. **Dismissible Immediate Care Message:**
**Activation Conditions:**
First time the Veteran uses the scheduling tool.
**Functionality:**
The message appears only once unless the Veteran chooses to dismiss it by selecting "don't show this message again."
**Purpose:**
To provide critical information about immediate care resources without causing alert fatigue.


2. **Alert for Severe or Alarming Signs and Symptoms in the Reason for Appointment Text Field:**
**Activation Condition:**
If the Veteran mentions any severe or alarming signs and symptoms.
**Functionality:**
When the Veteran selects “continue,” the tool will identify the input and trigger a dedicated emergency care alert page.
**Purpose:**
To ensure that Veterans with potentially serious conditions receive immediate guidance on seeking immediate care.

**Comment by melissa-lefevre** [comment]
Recap from the VHA Mental Health SMEs meeting:

- Melissa presented research on the immediate medical care alerts concept
- Feedback/ discussion points:
- Consider having the "Do you need care now" alert with a yes or no option every time the Veteran schedules.
- Melissa responded that: 1. I might be concerned that having it be a yes or no would hide the urgent, crisis, emergency care resources behind more clicks. 2. Having it show up every time might frustrate Veterans so we were showing it once when they first schedule with an option to not show it again, in combination with the AI alert that will appear when an alarming sign or symptom is entered.
- There was concern on increasing the current strain on human based VA crisis response systems.
- Currently in the alert the Crisis line is the first bullet and it should be swapped with the medical emergency.
- We should include the 988 resource.
- They suggested their "approved" wording, which is "You're not alone - the Veterans Crisis Line is here for you."

**Comment by melissa-lefevre** [comment]
**First time scheduling alert**
Display this message the first time the Veteran uses the scheduling tool and also when they select Mental health as a type of care. They will not see this messages again if they select “don’t show this message again”
<img width="280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzVGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed923929f4433080c5448dcdc04c3441aff4ac60/Screenshot%202024-10-14%20at%209.01.56%E2%80%AFAM.png" alt="Screenshot 2024-10-14 at 9.01.56 AM.png" />

**Comment by melissa-lefevre** [comment]
**Alarming S/SX alert**
If the Veteran mentions any severe or alarming signs and symptoms, when the Veteran selects “continue” the tool will identify this and trigger the following page.  
<img width="1092" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFZGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e8b91197f79967b610a8e2c6a1862c75289b623/Screenshot%202024-10-14%20at%209.03.39%E2%80%AFAM.png" alt="Screenshot 2024-10-14 at 9.03.39 AM.png" />

**Comment by melissa-lefevre** [comment]
CAIA ticket : [CAIA Intake] Appointments Team: First time scheduling "The scheduling tool is not meant for emergency care" message https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/93755
