### ISSUE TITLE
[CST] Add VA Notify to vets-api settings

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#93319]
## Background
We need to add the necessary settings for our VANotify service to the vets-api configuration in the `vsp-infra-application-manifests` repo

## Engineering Notes
- We are only going to add configuration settings for the staging and prod environments
- We need to add settings for both Staging and Prod, but we can't add settings for both environments in the same PR, so we need to create one PR for Staging, and another for Prod
- VANotify template IDs:
  - Staging: 85c72a70-7dde-4682-91da-e841f927f12c 
- AWS Parameter Store params:
  - Staging: [/dsva-vagov/vets-api/staging/vanotify/services/benefits_management_tools/api_key](https://us-gov-west-1.console.amazonaws-us-gov.com/systems-manager/parameters/%252Fdsva-vagov%252Fvets-api%252Fstaging%252Fvanotify%252Fservices%252Fbenefits_management_tools%252Fapi_key/description?region=us-gov-west-1)
  - Production: [/dsva-vagov/vets-api/prod/vanotify/services/benefits_management_tools/api_key](https://us-gov-west-1.console.amazonaws-us-gov.com/systems-manager/parameters/%252Fdsva-vagov%252Fvets-api%252Fprod%252Fvanotify%252Fservices%252Fbenefits_management_tools%252Fapi_key/description?region=us-gov-west-1)

## Tasks
- [x] Add parameters for Staging to AWS Parameter Store
- [x] Add parameters for Production to AWS Parameter Store
- [x] Add VANotify service settings for Staging
- [x] Add VANotify service settings for Production

## Acceptance Criteria

- [x] Necessarily configuration values are in place for staging and prod environments
