### ISSUE TITLE
[CST] Create/duplicate template in VA Notify for silent failures

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#93316]
## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks

- [x] Get onboarded to VA Notify production environment
- [ ] Reach out to 526 team to get copy of template
- [ ] Create new template in VA Notify using copy in staging and prod

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] The VA Notify template used by 526 team to send emails is adapted as needed for the evidence failure use case, so that veterans understand which evidence job failed
