### ISSUE TITLE
Update security.txt file to be hosted on va.gov and publicly accessible

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#93321]
## Issue Description
While we added the security.txt file to the vets-website repository, the file needs to be accessible via url. There doesn't seem to be any documentation around how we'd host a specific file, so this will require reaching out to other parties for expertise. 

---
## Tasks
- [x] Reach out to necessary parties to figure out how to host a file on va.gov
- [x] Implement hosting as necessary
- [x] Test to ensure the file is accessible

## Acceptance Criteria
- [x] The file is accessible on va.gov
---

**Comment by CBonade** [comment]
Got this done with the help of Kyle from infra. Ended up moving the file to the revproxy and hosting it directly from there. Removed the file from vets-website to keep things tidy.
