### ISSUE TITLE
[CST] Create a cron job that scans the table looking for job failures to kick off the email to VA Notify

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#93329]
## Eng Notes

- do we want to verify with anyone the acceptable time frame of the email? 
- evidence submissions table

## Tasks

- [ ] Steal from DR team
- [ ] Create a job that scans the evidence_submission table for FAILED status 
- [ ] This should call this sidekiq job and send emails - https://github.com/department-of-veterans-affairs/va.gov-team/issues/94466
- [ ] Periodic_jobs.rb
- [ ] add tests

## Acceptance Criteria

- [ ] Whenever there's a failed upload job, we're able to send emails via the cron job
- [ ] We use cron to send notifications once per hour

**Comment by pmclaren19** [comment]
blocked by this ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/94466
