### ISSUE TITLE
[CST] Create a table to store upload metadata

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#93322]
## Eng Notes

The table needs to store the following:

- ID: an id for the job
- Identifier: The ICN of the user who uploaded the file
- Claim Identifier: Optional id of associated claim
- UserAccount.id: The id reference to the UserAccount
- TemplateMetadata: Data to be used in the email template (first name, last name, file name, upload date, etc)
- Upload Status: The status of the upload sidekiq job
- VA Notify ID: The id of the VA Notify message being sent (if one needs to be sent)
- VA Notify Status: The status of the email (if one needs to be sent)
- Delete Date: The date when this record needs to be deleted (assuming success)
- TrackedItem ID

Possible future feature could be showing these records in CST to show status of uploads

## Tasks

- [x] Determine what data to add to the table
- [x] Generate initial model in migration files
- [x] Update model to be more specific
- [ ] Migrations get run automatically put into place on server side

## Acceptance Criteria
- [x] PR with migration files gets accepted by Platform
- [x] PR with model file gets accepted by Platform

**Comment by samcoforma** [comment]
From @jerekshoe "Can we call the table _EvidenceSubmissions_?"
