### ISSUE TITLE
[CST] Create webhook endpoints for VA Notify to call to update the Email status on the table

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#93324]
## Background Context

Once a record is in the evidence submission table is marked as 'failed', we would reach out to VA Notify to send an email to a user. If that email fails for some reason they would call the webhook endpoint so they could update us on why it failed. We need to create this end point so they have something to call. 

### Callback instantiation
```
callback_options = {
      callback_klass: 'ExampleTeam::CustomNotificationCallback',
      callback_metadata: {  statsd_tags: { service: 'ExampleTeam' } }
    }
    VaNotify::Service.new(NOTIFY_SETTINGS.api_key, callback_options)
```

### Callback Class format
```
module ExampleTeam
  class CustomNotificationCallback
    def self.call(notification)
      case notification.status
      when 'delivered'
        # success
        StatsD.increment('api.vanotify.notifications.delivered')
      when 'permanent-failure'
        # delivery failed
        # possibly log error or increment metric and use the optional metadata - notification_record.callback_metadata
        StatsD.increment('api.vanotify.notifications.permanent_failure')
        Rails.logger.error(notification_id: notification.notification_id, source: notification.source_location,
                           status: notification.status, status_reason: notification.status_reason)
      when 'temporary-failure'
        # the api will continue attempting to deliver - success is still possible
        StatsD.increment('api.vanotify.notifications.permanent_failure')
        Rails.logger.error(notification_id: notification.notification_id, source: notification.source_location,
                           status: notification.status, status_reason: notification.status_reason)
      else
        StatsD.increment('api.vanotify.notifications.other')
        Rails.logger.error(notification_id: notification.notification_id, source: notification.source_location,
                           status: notification.status, status_reason: notification.status_reason)
      end
    end
  end
end
```

Callback format:
```
"id":"6ba01111-f3ee-4a40-9d04-234asdfb6abab9c",  -- this is the notification id
"reference":null,  
"to":"",  -- this is the recipient's contact info
"status":"delivered",  -- this will specify the delivery status of the notification
"created_at":"2023-01-10T00:04:25.273410Z",  
"completed_at":"2023-01-10T00:05:33.255911Z",  
"sent_at":"2023-01-10T00:04:25.775363Z",  
"notification_type":"SMS",   -- this is the channel/type of notification
"status_reason": "", -- populated if there's additional context on the delivery status
"provider":"pinpoint"
```
> VA Notify uses bearer tokens for authenticating with services when making a callback. The bearer token can be any form that the called service endpoint accepts. These should be long-lived, but not permanent, bearer tokens.
> Each service will have their own policy for updating a long-lived bearer token. Contact VA Notify if an updated bearer token is required to meet security policies.
> We recommend not hardcoding acceptance of only a single bearer token, so bearer token updates are not disruptive.

## Tasks

- [x] Determine how VA Notify sends status and what those statuses are, research what webhook needs
- [x] Create new callback service
- [x] Pass in `callback_options` everywhere we instantiate `VaNotify::Service.new`

## Acceptance Criteria

- [x] We have an end point set up and configured for VA Notify to call for statuses

**Comment by pmclaren19** [comment]
@jerekshoe @samcoforma @jacobworrell 
I think we want to update the ticket info to note that the endpoint should call the datadog metric that is being create here - [BMT - add custom metrics to track BMT failure items](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94325) . 

We should also add what happens to the table when the email fails. Are we adding a email_failed boolean or email_failed_date?

**Comment by samcoforma** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/20494
