### ISSUE TITLE
[CST] Convert code we’ve written to send emails to a Sidekiq job that’s callable

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#93331]
## Tasks

- [ ] Create method that runs the Sidekiq job to send the email and update status 

## Acceptance Criteria

- [ ] Request for email is sent to VA Notify
- [ ] Status of request is added to our table

**Comment by pmclaren19** [comment]
duplicate
