### ISSUE TITLE
Edit: ESI Pages - VHA Access to Care

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#93342]
## User Stories
_"As a VFS Team member, I need to know the information on the External Service Integrations
is up-to-date and complete, so that I can build on va.gov with confidence"_

## Issue Description

The [External Service Integrations](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations) section of Platform Website contains pages with several formatting errors and missing information, as well as use of personal names. We need to edit the pages in this section.

## SME:

- Rebecca Tolmach (as of 2/11)
---
### [Spreadsheet with comments for each page](https://docs.google.com/spreadsheets/d/1fmV4M-mV4wIVCPsxYzxK_c2KjsdlQaGepG1B9VwFQvE/edit?gid=0#gid=0)
---
### This ticket is for the editing of the 
[VHA Access to Care](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887240236/VHA+Access+to+Care) page = mostly style guide issues?
---
## Tasks
- [x] Transfer comments from Spreadsheet to the Confluence document
- [x] Content team ticket assignee: Review page comments first
- [x] Add additional comments if necessary
- [x] Copy page and move copy to DRAFT Space (page **Copy** will not retain comments)
- [x] Review comments with SME
- [x] ~~Make formatting corrections~~
- [x] ~~With SME update information including any links~~
- [x] ~~SME review Final Draft for accuracy~~
- [x] ~~Prepare page for deployment~~

## NEW TASKS after discussing with SME

- [x] Page needs to be archived/deleted
- [x] check for incoming links
- [x] move to PCT Archive so we can easily keep track of these pages and access its info if we need to. 
- [x] Create ticket to archive/delete [ArcGIS page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886814279/ArcGIS.com) as well
- [x] Add in-line comment to ESI parent page that suggests listing "Lighthouse" in the "Relevant External Services" column for Facility Locator

## Acceptance Criteria
- [x] ~~Updates and corrections made~~
- [x] ~~Page is ready for deployment~~
## UPDATED Acceptance Criteria
- [x] VHA Access to care page archived
- [x] ArcGIS Archive ticket created
- [x] In-line comment made on ESI Parent page. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
11/5 Jason mentioned the ESI tickets might be spread to the Back End CoP as the Product team has low capacity due to OOO, Tier 2 Support duty and FOIA request.

**Comment by BSmolensky** [comment]
After discussing issues with SME, the resolution here is to delete/archive the page. This ticket has been updated with new tasks and new acceptance criteria.

**Comment by BSmolensky** [comment]
Checked for incoming links: none. Page moved to the PCT Archive.

**Comment by BSmolensky** [comment]
ARcGIS ticket updated/created.

**Comment by BSmolensky** [comment]
In-line comments made on ESI parent page.

**Comment by BSmolensky** [comment]
All tasks complete. Acceptance criteria met. Ticket is ready to close.

**Comment by jknipes** [comment]
Closing as _Done_
