### ISSUE TITLE
Implement E2E Coverage reporting

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#93358]
## Issue Description
We tried implementing E2E code coverage in the past but our runners ran out of memory without being able to accomplish it. With larger memory runners now, we would like to implement this as it's a necessary safeguard for continuous deployment.

---
## Tasks
- [x] Add coverage reporting to our E2E test suite.
- [ ] Ensure coverage data uploads to a data source (such as BigQuery) so it can be referenced in CI for deployment safety verification.

## Acceptance Criteria
- [ ] We can easily see the coverage % for any app for E2E tests.
- [ ] The coverage numbers are accessible by our CI workflow for any app.
---

**Comment by CBonade** [comment]
All necessary pieces were installed for this and coverage runs on each test run when the correct env variable is set. That being said, all coverage is registering as 0 as the individual tests are having trouble reporting their numbers. Breaking this troubleshooting piece off into a new ticket as it will require its own batch of research to resolve.
