### ISSUE TITLE
[Design] MDT - Veterans need clearer next steps when they do not see their device or accessories available during product selection

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#9335]
## Issue Description
During usability testing, we found that Veterans were able to easily find the additional information component that housed information about what to do if they don't see their device or accessory, but they told us that the information housed within wasn't entirely sufficient. 

Some feedback we got about this content (paraphrased):
- "It's weird that the directive is different between batteries and accessories"
- "I'm not sure I'd be able to get in contact with my actual audiologist directly - maybe include instructions about leaving information with the assistant"
- "I'd like to see the number to call instead of a link to get the number"

---
## Tasks
- [x] Rewrite the content in both the content
- [x] Update GH documentation with changes
- [x] Create a Frontend ticket for the work to be implemented

## Acceptance Criteria
- [x] New content provided
- [x] Frontend ticket made and linked below

**Comment by rileyorr** [comment]
I've updated the designs with the new content: [Hearing aid batteries](https://vsateams.invisionapp.com/share/KWX53U12MGX) | [Hearing aid accessories](https://vsateams.invisionapp.com/share/9GXIP1XDUSF)
I reached out to Peggy to see if she prefers reviewing the content change via ticket - currently waiting on a response.

**Comment by rileyorr** [comment]
I've updated the GH documentation and created [a ticket for frontend implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9695). I noted in the ticket that the content needs to be reviewed by a VSP content specialist.

**Comment by rileyorr** [comment]
Peggy would prefer to review the content during staging review, so I will reach out to Mahariel to see if it is possible to fit in these content changes before tomorrow's staging review.
