### ISSUE TITLE
Update Stakeholder Mural

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#93364]
## Background
Our stakeholder mural could use a refresh -- adding in new folks, consolidating to the folks that are involved with our work on a regular basis, and their level of involvement. 

## Tasks
- [x] Update [Stakeholder Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699986925507/b10367544c62e9b5e91ce0402cfb40d15b33804f?sender=ubac5f0487f25bc4431288699)
- [ ] Discuss with Jen and Lesley to fill in the gaps

## Acceptance Criteria
- [x] The stakeholder mural is updated and has RACI indicators, to better guide collaboration across key people.

**Comment by oddball-lindsay** [comment]
Got the general table outlined and feeling fairly confident on most offices and titles.

Just need to add my original notes into the table and then I'll be ready for Jen and Lesley's help.

**Comment by oddball-lindsay** [comment]
Added everything I could, ready now for Jen/Lesley's feedback which I'll try to collect in our morning meeting tomorrow.

**Comment by oddball-lindsay** [comment]
Closing this out, will pass to Jen/Lesley for help updating the open areas of stakeholder info.
