### ISSUE TITLE
After warning period, place eligible apps on allow list for deployment

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#93360]
## Issue Description
Once our 60-day warning period has passed, apps that are isolated and not on the allow list for Staged Continuous Deployment, should be moved to that list. This will allow the apps to take advantage of controlling their own deployment cadence, as well as ensure they do not require a platform approval to deploy.

---
## Tasks
- [x] Check SCD allow list vs the app isolation report to determine what apps are isolated but not on the list.
- [x] Add the apps that are isolated to the list to allow them to deploy at their own cadence.

## Acceptance Criteria
- [ ] ~All eligible apps have been added to Staged Continuous Deployment~
- [x] Batches of apps have started to make their way onto the allow-list.
---

**Comment by CBonade** [comment]
An announcement was put out in [#vfs-change-announcements](https://dsva.slack.com/archives/C03R5SBELQM/p1739913497228179) covering the changes coming. The apps will begin moving on to the allow list on Monday, 2/24. Apps that do not make it this sprint, will be broken off into a separate ticket to continue this work next sprint.

**Comment by CBonade** [comment]
Apps moved over today: 

- _mock-form
- _mock-form-ae-design-patterns
- 686c-674
- accreditation
- appeals
- ask-a-question
- ask-va
- auth
- burial-poc-v6

**Comment by CBonade** [comment]
For launch 2/26:

- dhp-connected-devices
- disability-benefits
- discharge-wizard
- discover-your-benefits
- dispute-debt
- ds-playground
- ds-v3-playground
- e-folders
- edu-benefits

The rest of the apps will be batched up in a separate ticket.
