### ISSUE TITLE
Capture experience working with non-OCTO teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#93369]
## User Story

As a Governance team member, I want to document the challenges that my full team has faced when providing support to a non-OCTO team in the Collaboration Cycle, so that Governance and OCTO can define an escalation path for these teams in the future.

Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
OCTO-DE has created an [initiative](https://github.com/department-of-veterans-affairs/digital-experience-products/issues/1176) for creating a customized experience in the Collab Cycle for working with non-OCTO teams. The initiative is still in it's early days, and OCTO-DE does not yet have a complete understanding of the problem's faced when working with a non-OCTO team.

The purpose of this ticket is for Governance team to capture our experience working with non-OCTO teams so that we can be fully aware of all problems and challenges faced. 

The full scope of this ticket will be all practice areas, as well as any other roles Governance team members fill. All practice areas include accessibility, design, IA, QA, content and product.

### Live pages
- N/A

### Drafted pages
- New internal document: [Platform Governance team experience working with non-OCTO VFS teams](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3555196944/Platform+Governance+team+experience+working+with+non-OCTO+VFS+teams)

## Tasks
- [x] Determine what method Governance should take in collecting and documenting this information 
   - The [Platform Research methods](https://vfs.atlassian.net/wiki/spaces/DCP/pages/1472888866/Platform+Research+Methods) may be a valuable resource, however you're welcome to define your own approach
   - are there questions you want Governance to answer? Should we do this via survey, mural board or utilize other tools? do we want to capture both positive and negative things?
- [x] Solicit the Governance team for their review and input
- [x] Summarize content shared from Governance team in Confluence doc. Share with OCTO-DE, specifically @artsymartha68 
   - [Summary doc](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3555196944/Platform+Governance+team+experience+working+with+non-OCTO+VFS+teams) 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team has documented our experience working with non-OCTO teams in the Collaboration Cycle
- [x] Governance has shared this with @artsymartha68 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
Status update: Reviewing past CC tickets has taken a bit longer than budgeted. I think there's value in finishing that work, but this will likely carry over into the next sprint (probably Thursday or Friday).

**Comment by shiragoodman** [comment]
@briandeconinck where are we with this work? I haven't heard an update since last sprint.

**Comment by briandeconinck** [comment]
@allison0034 This is finally ready for review! [Platform Governance team experience working with non-OCTO VFS teams](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3555196944/Platform+Governance+team+experience+working+with+non-OCTO+VFS+teams)

**Comment by allison0034** [comment]
This looks good, I would just add some specifics around your stats. Also, I find it interesting that statistically we did not have major issues with non OCTO teams but the Governance team "feels" like they are more effort. I don't know if we want to call that out or not. Just found it interesting. Really you kinds did call it out in the part I highlighted on your doc.

**Comment by briandeconinck** [comment]
Thanks for the comments! Changes I've just made:
- Moved the Method section up and included more detail on what tickets I looked at.
- Added some additional numbers/context in the detailed discussion

**Comment by shiragoodman** [comment]
@briandeconinck i agree with Allison. This is really great and well structured. It will be very helpful information for our OCTO-DE leads have when deciding how to proceed with the initiative. 

When you're ready to share with Martha, I encourage you to share it in the #platform-collaboration-cycle channel so all OCTO-DE practice area leads can see. however, please only tag Matt and Martha.

Let me know if you have any other questions or concerns. I value your effort!

**Comment by allison0034** [comment]
@briandeconinck looks good, made one small comment.

**Comment by briandeconinck** [comment]
Comments resolved! @allison0034 if you want to give it one extra read and check off the peer review boxes, I'll share with @artsymartha68 and we can close this out.

**Comment by allison0034** [comment]
Looks good to me!
