### ISSUE TITLE
[Design] Debt Letters - Compile a list of expected data

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#9336]
## Issue Description
Once we have completed our ideation session with the team, we should have a good idea of what the data requirements are on the frontend. We'll compile these ideas as a checklist to investigate feasibility of displaying the data.

---
## Tasks
- [x] Create a list of requirements and nice-to-have data to be displayed on the frontend
- [x] Put list in the design folder in GH

## Acceptance Criteria
- [x] List uploaded to GH and linked to this ticket
- [ ] Ticket made for backend to investigate feasibility

---
## Dependency
- Ideation happens first!

**Comment by rebeccawalsh** [comment]
**Current:**
- fileNumber
- payeeNumber
- personEntitled
- deductionCode
- benefitType
- amountOverpaid
- amountWithheld
- debtHistory
  - debtId
  - date
  - letterCode
  - status
  - description 

**Proposed additions:**
- Amount paid
- Interest / fees accrued
- Balance
