### ISSUE TITLE
[Design] Debt Letters - Create a hi-fidelity screens

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#9337]
## Issue Description
_Once ideation/brainstorming is completed and wireflows are validated, the design team needs to create hi-fidelity prototypes in Sketch. These screen(s) will be used to create the UXPin prototype for usability testing._

---
## Tasks
- [ ] _Create a hi-fidelity prototype in Sketch based off the approved wireflows_
- [ ] _Review hi-fidelity prototypes with the team to get validation from frontend engineers that design is feasible_
- [ ] _Comment with a link to the prototypes as an upload to InVision or UXPin_

## Acceptance Criteria
- [ ] _Hi-fidelity prototypes have been approved by the team_
- [ ] _Prototypes have been linked to this ticket_
---

**Comment by rebeccawalsh** [comment]
@leahkeeler this one can be deleted, as we have more specific tickets now in our sprint.
