### ISSUE TITLE
Add Contact Center teams Slack channel to touchpoint page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#93371]
## User Story
As a VFS team member with questions about the Contact Center touchpoint, I want to know where I can go to ask those questions so that I can receive support.

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @it-harrison 

## Description
The slack channel (#vsp-contact-center-support) for the Veteran Support team (aka Contact Center) is not easily found on their Contact Center [touchpoint page. ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-center-review)The purpose of this ticket is to add it.

### Live pages
- [Contact Center Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-center-review) touchpoint page

### Drafted pages
- [Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3547725846/93371+-+Keegan)

## Tasks
- [ ] Add the Slack channel to the appropriate section of the touchpoint page
  - Request maybe? "For questions about this touchpoint, please visit #vsp-contact-center-support" - something like that

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The Slack channel for the Veteran Support team is listed on the Contact Center touchpoint page
 
## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by KKitagawa-Bosch** [comment]
Created a draft [here](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3547725846/93371+-+Keegan) and added the slack channel based on how slack channels are handled on other touchpoint pages. 

@it-harrison let me know what you think!

**Comment by shiragoodman** [comment]
I'll peer review on behalf of @it-harrison . This looks good @KKitagawa-Bosch  - you should be good to push to Platform Website. ty!

**Comment by KKitagawa-Bosch** [comment]
Changes pushed, will close ticket later when they go live!

**Comment by KKitagawa-Bosch** [comment]
Pushed!
