### ISSUE TITLE
[Design] Wireframe for when when the selected provider doesn't have their time slots open to EPS/WellHive

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93373]
## Task Description

There will be scenarios where some PTs (or other providers) don't open their time slots to EPS/WellHive. The program decided that that's okay and that Veterans should still be able to call and schedule their first appointment. What pages need to be changed or created to support this flow? For example, they wouldn't be selected a date and time. But, they would need to, 1) review the provider, and 2) have a way to contact the provider (e.g., phone number). 

Make sure to include information about, 1) provider doesn't offer online scheduling, and 2) this will become an upcoming appt when the external provider reaches out to VA. 

## Acceptance Criteria
- [x] Wireframe(s) drafted
- [ ] Wireframes(s) reviewed 
- [ ] Finalized wireframe(s) added to MVP scope page with annotations
- [ ] Stub out FE ticket for this work 

## Deliverables
- [ ] Finalized wireframe(s) added to MVP scope page with annotations
[Design Explorations](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=4976-12596&t=sGPf5kjHGeBmHDmH-1)

---
## How to configure this issue
- [ ] Add title and task description
- [ ] Attach to an Epic
- [ ] Add labels based on work type: design, discovery, documentation, strategy
- [ ] Delete this section

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-FE-UX-5fff340c2d80a4000fb6f69c/issues/department-of-veterans-affairs/va.gov-team/93373?planning-poker) with Zenhub @cgednalske

**Comment by benbrasso-agile6** [comment]
Adding 1 pt for Christina, since this task will be primarily assigned to Ciera

**Comment by benbrasso-agile6** [comment]
@Cieramaddox all finished up with this ticket?
