### ISSUE TITLE
[Design] Debt Letters - Ideation Workshop

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#9338]
## Issue Description
With this issue, we'll set up and host a workshop for team members to come and put their ideas on the board and share. The goal of having this workshop is to align on a vision for the debt letters MVP prior to bringing the idea(s) to VSP.

---
## Tasks
- [x] Create workshop plans
- [x] Schedule workshop
- [x] Host workshop
- [x] Attach mural board here

## Acceptance Criteria
- [x] Workshop run
- [x] Mural board attached

**Comment by rileyorr** [comment]
Here's a link to [the Mural board we used for the ideation workshop](https://app.mural.co/t/vsa8243/m/vsa8243/1590173930514/c0dcc29fddb240204b0e1f93cc0b1caf2c04f421).
