### ISSUE TITLE
Create Journey Map for Veterans applying on VA.gov for disability comp

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#93389]
## Issue Description
As a team member, I want a comprehensive journey map that outlines the steps to fill out the form, so that our stakeholders can understand the process clearly and ensure consistency in the experience

Even though we don't have usability issues currently prioritized, it is important that we keep our findings well organized for whenever that work gets picked up. New team members also have a hard time following the form and it's many components.

While there are many user maps in VA, none specifically address the online journey of filing, exclusively. 
---
## Tasks
- [ ] Create journey map that looks at the form steps and points out pain points
- [ ] Decide which pain points and how to visualize
- [ ] Determine whether this is a working doc or finished deliverable
- [ ] Decide if new versions should be made for particular scenarios. 

## Acceptance Criteria
- [ ] OCTO review
- [ ] Present to others
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
