### ISSUE TITLE
Swap UTF8-cleaner gem with rack-utf8_sanitizer

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#93388]
## Issue Description
When upgrading to Rack 3+, there's about 120 failing specs because an attribute on the `env` object became optional in rack 3, and the gem ([utf8-cleaner](https://github.com/singlebrook/utf8-cleaner)) hasn't been maintained in 5 years to patch the issue. This new gem ([rack-utf8_sanitizer](https://github.com/whitequark/rack-utf8_sanitizer)) should provide the same sanitization and is actively maintained. 

---
## Tasks
- [ ] Swap out gems, and add middleware as required
- [ ] Achieve passing specs

## Acceptance Criteria
- [ ] changes are deployed to production
