### ISSUE TITLE
Discovery: Brainstorm improved org/formatting for Redirect Page

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#93394]
While working on tickets #92269 and #93073, we realized that the page needs a serious overhaul to bring it in line with our style guidance and to maximize a user's ability to understand the information on the page. The first part of this objective: brainstorm alternatives. 

### TASKS:

- [x] Brainstorm organizational and formatting changes
- [x] Play around with draft docs to determine best path(s) forward. 
- [x] Save your work to share with future edit ticket. 

### Acceptance Criteria:

- [x] Several new organizational options discovered

**Comment by BSmolensky** [comment]
Here are the two main reorg page options:

- [Version 2](https://vfs.atlassian.net/wiki/spaces/~637b96fdfde064eda2ed7417/pages/3476258817/V2+-+Redirect+Implementation+Strategy): remains one page
- [Version 3](https://vfs.atlassian.net/wiki/spaces/~637b96fdfde064eda2ed7417/pages/3469213926/V3+-+Redirect+Implementation+Strategy): creates child pages for each redirect type

**Comment by BSmolensky** [comment]
This ticket is ready to close.
