### ISSUE TITLE
Toxic Exposure - (found during 25%) - invalid date XXXX is coming through for the year in exposure dates fields

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#93403]
### Description
As a Veteran, when I enter a year date in an optional field on my 526 form, I expect that it will be sent to VA and my claim will be submitted successfully. This impacted 8 submissions for 3 unique users. The form component doesn't provide four-digit year validation and doesn't allow a Veteran to complete only one field (either date, month, or year). We've talked with the forms team and are not sure if or when a fix is forthcoming. Because these fail completely and want to avoid this, we are considering a different approach.

### Issue 1 - "Invalid Date"
Today, a Veteran's 526 submission fails the primary and backup path when they don't enter a year (although the date fields are optional) because "XXXX-12 is not a valid date.". This is has currently affected 7 submissions for 2 unique Veterans. 

{"errors":[{"detail":"XXXX-12 is not a valid date.","source":"data/attributes//toxicExposure/multipleExposures//exposureDates/beginDate","title":"Unprocessable Entity","status":"422"}

#### Tasks
- [ ] Ask LH if they can relax the validation rules for this scenario
- [ ] We could consider overriding the [web component pattern](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/web-component-patterns/datePatterns.jsx#L326)

---
### Issue 2 - "Two-digit Year"
Today, a Veteran's 526 submission fails the primary and backup path when they enter a two-digit year (although the date fields are optional) because the year is two digits, and "0" isn't a valid choice for month or day. This is has currently affected 1 submission, for 1 unique Veteran.

Another issue is this is coming through from the frontend: `"endDate": "77-06-01"` (originally seen in the `otherHerbicideLocations` attribute), which the backend parsed as `"endDate": "77-0--0"`, which lighthouse no likey

#### Tasks
- [ ] Ask LH if they can relax the validation rules for this scenario
- [ ] We could consider overriding the [web component pattern](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/web-component-patterns/datePatterns.jsx#L326)
- [ ] Explore what the Veteran-facing experience is like when we set the backend schema as well and identify if there's an option to send an error message back to the frontend and what this would look like.

### Additional Information
- We're having trouble reproducing both of these issues
- How did EVSS handle this
- Can we/should we update/change the schema

**Comment by pacerwow** [comment]
We'll continue to monitor the progress of the forms team and work with them to understand if or when a change to the component will address this.

**Comment by christinec-fftc** [comment]
fyi i'm doing the discovery task of seeing whether overriding the start and end date schemas on the FE is feasible

**Comment by christinec-fftc** [comment]
regex fun

web component pattern: year-month-day. all are optional with X's
`^(\\d{4}|XXXX)-(0[1-9]|1[0-2]|XX)-(0[1-9]|[1-2][0-9]|3[0-1]|XX)$`

LH: year or year-month is allowed
`^(?:19|20)[0-9][0-9]$|^(?:19|20)[0-9][0-9]-(0[1-9]|1[0-2])$`

proposed custom FE pattern: year-month-day is allowed. (BE currently strips out the day)
`^(?:19|20)[0-9][0-9]-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$`

**Comment by christinec-fftc** [comment]
[testing notes ](https://docs.google.com/spreadsheets/d/1uAdr7a_nomSsQXHHwqNTKnE1cYTAQSKNLqh937ToF9w/edit?usp=sharing)

**Comment by christinec-fftc** [comment]
2 considerations with the FE short term solution. We can now prevent X dates, but
1. found another platform bug. the friendly error message displays on the page itself, but not on the review page
<img width="1160" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW9SQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b45c8c426f1511a91f4efd3c0710161b5ccb47f3/image.png" alt="image.png" />

2.[ PR #32178](https://github.com/department-of-veterans-affairs/vets-website/pull/32178/) currently disallows X's from any date field since we have seen submission issues with all 3 fields. Do we want to ship with no X's allowed or should we still allow X's in the month and day since they are actually optional

**Comment by christinec-fftc** [comment]
high level notes from our eng sync this morning. tl;dr; we decided to sync up both FE and BE to use vets-json-schema. there's still some work to do on both ends, but great progress and hoping to have pr's ready tomorrow
FE: found a way to configure the error messages on the review page to be friendly. since there are 40+ TE pages will look into making this dynamic but won't spend too much time on it. static is also a viable option
BE: writing vets-json-schema unit tests

**Comment by christinec-fftc** [comment]
Results of testing on staging after all 3 pr's finally went in (vets-json-schema, vets-api, and vets-website)

1. Created a new claim with a new condition, one TE condition
2. For gulf war 1990 question, selected Afghanistan, then entered a partial date (no year), e.g. Jan 5. Was still able to move fw due to known platform issue around touched fields.
3. On Review page, saw the 'Invalid Date' for Afghanistan, but continued to submit for testing's sake. Got an error, 'Your application is missing some information' for 'Service start date for Afghanistan'. FE changing working as expected which provides specific field info ✅
![Image](https://github.com/user-attachments/assets/fe136da8-bed8-4acd-b7c8-4c0548aa8143)

4. Edit 1990 locations to de-select Afghanistan. Submit again
5. Got generic error message
![Image](https://github.com/user-attachments/assets/cb6dcdda-749a-486d-83da-ee8ad42b06d1)

6. If I go back to 526, it prompts me to continue or create a new application

**Comment by christinec-fftc** [comment]
For reference, the previous UX was a non specific error if the location was selected
![Image](https://github.com/user-attachments/assets/f0fe6eef-3005-463c-9259-325c9757f6fd)

and a submission failure if the location with partial/invalid date was deselected

**Comment by christinec-fftc** [comment]
I am concerned that the IPF is still lingering when the BE error occurs (steps 5 and 6 from the staging test above). I asked the team if we currently have any tickets in the backlog to address this, but doesn't sound like it. I can think of two options here, welcome to more ideas.

Option 1
Address this via [Toxic Exposure: Veteran changed their mind about a location/hazard scenario #94396](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94396). This ticket is asking whether we should design a scenario to prompt the Veteran about a destructive action

Option 2
If we decide option 1 is not needed, then we can create a new FE eng ticket to update the [submit transformer](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-work-with-transformforsubm) to strip out any TE dates which do not have a selected location/hazard associated with it. Here is an example of what the data looks like when the Veteran changes their mind. They initially had `afghanistan: true` which allowed them to start entering a date, but then they went back and deselected afghanistan. In this option we would remove the afghanistan dates from the submission, along with any other TE dates that are also orphaned.
![Image](https://github.com/user-attachments/assets/085fd41b-fa2a-4ab2-ae69-f433b9a0af64)

**Comment by christinec-fftc** [comment]
Team discussion notes: We agreed that both options should be done, but that option 2 is the short term fix and option 1 is longer term, possibly a candidate for the next set of TE research.

Ticket for option 1 https://github.com/department-of-veterans-affairs/va.gov-team/issues/95121
