### ISSUE TITLE
Remove instructions for setting toggle in CC Request tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#93417]
## User Story
As a Governance team member, I want to remove the steps in scheduling for adding the default open toggles so that my on support work load is slightly lessened and I'm no longer completing unnecessary steps. 

Assignee: @allison0034 
Peer Reviewer: @it-harrison 

## Description
Governance team uses the `<details>` and `<details open>` github markdown syntax in Collab Cycle Request tickets to set the different sections of the ticket to be set to open or closed. This is an additional step we take in order to make it convenient/easy for the VFS team to see which touchpoint they should be focusing on.

Due to an increased workload for the Governance on-support person, we will no longer be defaulting the toggles to "open" when the status of the ticket changes. The purpose of this ticket is to edit the Kickoff, DI, MPR and SR instructions to remove all instructions to change the toggle to open or to no longer set the toggle to open.

### Live pages
- [Collaboration Cycle Kickoff - Admin Tasks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Admin+Tasks)
- [Collaboration Cycle Kickoff - Code blocks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3387457549/Collaboration+Cycle+Kickoff+-+Code+Blocks)
- [Design Intent - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2775253404/Design+Intent+-+After+the+Meeting)
- [Midpoint Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790686759/Midpoint+Review+-+After+the+Meeting)
- [Staging Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447023/Staging+Review+-+After+the+Meeting)
 are there other impacted guidance docs?

### Drafted pages
- 

## Tasks
- [x] Remove the instructions in the operational guidance for setting the toggle to open and/or removing the open toggle
- [x] Ensure the guidance still flows as expected and is easy to follow

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team no longer sets the touchpoint toggle to open and/or no longer removes the open toggle

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@it-harrison this is ready for your review. I edited all the pages under the live section in this ticket. I tried to comment where I made the changes.

**Comment by it-harrison** [comment]
@allison0034 looks good!
