### ISSUE TITLE
[Design] Badge indicator: Design solution for error states

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#93414]
## Background
We will need to design(s) for error scenarios on the badge indicator, which include:

1. The API call to tell if there are unread messages fails
2. We can tell there are unread messages but don't know the count
3. Clarify handling of any possible error states related to secure messaging and the count displayed

## Tasks
- [x] Create designs for error states
- [x] Share with DSC to amend our experimental design submission (async is fine)
- [x] Add finalized approach to FE documentation

## Acceptance Criteria
- We have designs for error state(s) and documentation is updated

**Comment by mattmarino-adhoc** [comment]
I inquired about how VA Mobile App team handled a possible error scenario with item count not being displayable, their answers appear in this Slack thread: https://dsva.slack.com/archives/C018V2JCWRJ/p1727804592232889

**Comment by mattmarino-adhoc** [comment]
Meeting with Dan to review a few possible scenarios. I've been discussing content with Laura from CAIA to address possible error messaging (akin to what the Mobile App is doing).

**Comment by mattmarino-adhoc** [comment]
Mobile app team documentation for their handling of error scenarios:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/design-personalization/content/content%20decision%20log.md

https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=u85a35f55e50d7c375c782462

**Comment by mattmarino-adhoc** [comment]
Carrying over to next sprint, looking for resolution ASAP

**Comment by mattmarino-adhoc** [comment]
At this time, the following appears to be true:
- There are two API calls for secure messages that include message counts, both would have to be failing for no count to be possible
- An inability to access the inbox would also likely be part of any inability to display a count, but could depend on the error code

I am proceeding for now with the understanding that a count being unable to display would only happen as part of a set of secure messaging API failures that would likely impede access to SM. 

[We do however possibly need a little more clarification, related conversation in this Slack thread](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/gh/department-of-veterans-affairs/va.gov-team/81961)

**Comment by mattmarino-adhoc** [comment]
We got clarity on 10/15 regarding possible error scenarios when talking with the SM team. We will proceed with the use of an alert that indicates that messaging is unavailable (and nothing that is specific to a count not showing, since that will not be happening unless there are larger issues with SM).

**Comment by mattmarino-adhoc** [comment]
Contacted CAIA again for review/assistance of alert messaging for error scenarios

**Comment by mattmarino-adhoc** [comment]
We will attend the DSC meeting on 10/24 to discuss error states with them.

**Comment by mattmarino-adhoc** [comment]
We are now going to include two variants of error states as proposals (implementation may not accommodate this for MVP):
- warning for when messaging might work (400 error codes)
- warning for when messaging definitely doesn't work (500 error codes)

**Comment by ACParker89** [comment]
Meeting w. DSC on 10/24

**Comment by ACParker89** [comment]
Roll to 48

**Comment by mattmarino-adhoc** [comment]
Based on the midpoint review, we have taken a new approach:
- We WILL go back to having two types of handling: when the inbox is likely inaccessible, and when the count is unavailable but the inbox _may_ be accessible
- The "Go to your inbox" link will always appear
- The warning alert will appear above the link when we believe the inbox is inaccessible, along with a "?" badge
- Just the "?" badge state when the count is unavailable but the inbox may still be functional otherwise

**Comment by mattmarino-adhoc** [comment]
@laurwill the history of updates are in the comments here

**Comment by mattmarino-adhoc** [comment]
Carrying over, but mostly complete

**Comment by mattmarino-adhoc** [comment]
Asking Brian DeConinck for additional accessibility input again to ensure we have solid aria text

**Comment by mattmarino-adhoc** [comment]
Completed

**Comment by mattmarino-adhoc** [comment]
@allisonlu @DanielMiller-agile6 FYI
