### ISSUE TITLE
[CST] Back navigation bug when going from claim list to claim detail and back

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#93426]
## Value Statement
**_As a_** Veteran
**_I want to_** easily navigate around CST in a way that makes sense
**_So that_** I'm not confused about where I am and the experience is easy

---
## Background Context

Currently there is a bug with browser navigation in the following scenario:

- There is a paginated list of claims in CST
- User goes to Page 2 of the list of claims
- User clicks into claim
- User goes "back" by clicking back button in browser
- It takes the user to Page 1 of the list of claims

**Expected behavior**
When the user clicks back in the browser navigation to go back to the claim list, it returns them to the place within the list that they were last on. For example:

- User is on Page 2 of claim list
- User clicks in claim details
- User clicks "back" to navigate backwards in browser
- User is returned to Page 2 of claim list (not Page 1)

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- No spec. See "expected behavior" above. 

### Enablement team (if needed)
@member of team

## Engineering 
Guidance from CAIA:

> "In My HealtheVet, teams pass the page # as a parameter in the URL & the back link breadcrumb routes the user back to that page of the results. This gets complicated when filters or sort are applied - that info needs to be stored. But teams are doing this the way you are suggesting! I can give you names if you want to have these folks connect with another team re: implementation strategy"

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Update the logic to match the desired navigation behavior_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _When a user navigates back to the previous page using the browser "back" button, they'll go to the correct pagination page of results_
- [ ] _The breadcrumb behavior should adhere to CAIA guidance and not follow the logic for the browser tab_
- [ ] _Solution assumes that users will someday be able to filter claims and appeals on the list view_
- [ ] _Upon load, focus should snap to the area that aligns with CAIA accessibility standards as best as possible_

**NOTE:** According to CAIA guidance, the breadcrumb should not follow the logic defined here. It has separate logic, and we should leave it as is.

**Comment by skylerschain** [comment]
Design QA: LGTM 👍
