### ISSUE TITLE
[PM] My VA Forms Status: Execute QA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#93427]
## Background
We need to execute QA on the forms status feature by performing the test cases on a range of browsers. 

QA strategy and artifacts outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/QA/README.md).

## Tasks
- [x] Execute assigned test cases on identified browsers
- [x] Document success/failures in spreadsheet
- [x] Work with PM to create tickets for items that need to be addressed

## Acceptance Criteria
- [x] QA is complete
- [x] Any bugs are logged in tickets for resolution

**Comment by ajakabcin** [comment]
QA is 95% complete - just need to test error scenarios when they're ready cc @allisonlu

**Comment by ajakabcin** [comment]
complete!
