### ISSUE TITLE
VSOR - VA Claims Process Interviews - Interview Prep

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#93420]
## Issue Description
Exploratory interviews with VSORs to understand current claims process, supporting forms, and technology. Target audience will include those who do and do not use SEP to see how processes vary. Learnings will be used to inform ARP claims process flows.

## Tasks
Tasks
- [ ] Slack to VSO channel
- [ ] Set-up Enjoy HQ project
- [x] Create sign-up sheet
- [x] Set up Slack channel w/ observers
- [ ] Create folders in Sharepoint
- [ ] Create notes and debrief Mural
- [ ] Create observer kick-off video
- [ ] Transfer demographics to sign-up sheet & Excel
- [ ] Conduct pilot session
- [ ] Create conduct interview Zenhub ticket

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
All materials prepped and ready to go

Closing ticket
