### ISSUE TITLE
[CDP] Test updated VBSAPI GetPDFStatementById and GetHTMLStatementById

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#93430]
## Issue Description
Given: The user has copay statements      
When: The user choose to download a copy of the statement  
Then: The user can still download a copy of their copy statement using the updated VBSAPI endpoints

## Tasks
As requested by the VBS team, we need to provide 4 documents/screenshots as described by the matrix below
- [ ] Test each of `GetPDFStatementById` and `GetHTMLStatementById` endpoints
- [ ] For each endpoint, find a single page statement and a multi-page statement and retrieve the API results for each of these statement types.

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Retrieve the 4 documents/screenshots requested by the VBS team

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by JunTaoLuo** [comment]
I have already sent the requested documents to Megan on the VBS team so all the action items are complete. One followup we should discuss is that our code never calls the `GetHTMLStatementById` endpoint. VBS claims that VADO is the only consumer of this endpoint so if we don't use it, should we ask them to remove it? Or will this endpoint be used in the future?

**Comment by JunTaoLuo** [comment]
Hey @Tom-Davis I have one quick question before I close out this ticket. Can you help me with my previous comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93430#issuecomment-2369028365)?

**Comment by JunTaoLuo** [comment]
Open question will be addressed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/93514.
