### ISSUE TITLE
[CST] Change text of tracked item updates in Recent Activity

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#93433]
## Background Context

We are updating the text of the standard tracked item status update in Recent Activity.

Why? Due to the various tracked item names, it's better to have a standard text that is a little bit more flexible. We are using a colon before the name to ensure that no matter what the tracked item name is that's dynamically inserted based on the API call, the status update text is grammatically correct.

<img width="1788" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlgyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20e17f6f18452e0d1d77c3c396d914f756d241ac/Screenshot%202024-09-23%20at%202.30.13%E2%80%AFPM.png" alt="Screenshot 2024-09-23 at 2.30.13 PM.png" />

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- [FIGMA](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST-V2?node-id=3015-11421&t=EmToI0DeWvUiRSnd-4)

### Enablement team (if needed)
@jstrothman

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Update text for all status changes as described in the FIGMA spec above_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Tracked item status updates in Recent Activity show the updated text_
