### ISSUE TITLE
EVSS PCIU Migration: Step 7: Refactoring Contact information

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#93448]
## User Story
As the managers and developers for the VA Platform, 
We need to refactor content information in the new PCIU environment, 
So that the content information prefills correctly after PCIU has been migrated to EVSS.

## Issue Description
Need to refactor the contact information. 

## Tasks
- [ ] Refactor current content information in PCIU
- [ ] Document process
- [ ] Test refactored content information as needed

## Success Metrics
PCIU Contact information has successfully been refactored and tested. 

## Acceptance Criteria
- [ ] Contact information has been correctly refactored
- [ ] Documentation on process has been captured
- [ ] Any necessary testing is complete. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note:** Work continues on this ticket because a number of roadblocks appeared that are in the process of being solved. This ticket will rollover to Sprint 16.

**Comment by RachalCassity** [comment]
Starting this work after the PCIU replacement PR is in review.

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note:** During Sprint 15 (2024), https://github.com/department-of-veterans-affairs/vets-api/pull/18729 was being reviewed and there was a cascading effect because of changes that need to be made based on PR feedback. As a result, this ticket is blocked and will be removed from Sprint 16. Additional modifications to the epic workflow are being track in https://github.com/department-of-veterans-affairs/va.gov-team/issues/98514.

**Comment by AshleyGuerrant** [comment]
Closing as a duplicate of #93444
