### ISSUE TITLE
Scaffold Out the "View your VA payment history" Page(s)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9344]
## Goal
The next step in building this feature is to build out the initial pages based on the currently designed prototype from Design.

## Considerations
- Consider routes, what mock data might need to be in place and any other initial activities as we home in on the first version.

## Tasks
- [x] Create the pages for the various screens for this feature
- [x] Frame or stub out the component areas based on the [prototype](https://preview.uxpin.com/546893e0b210374a0734240e0ca9fccc2e02ed11#/pages/129039987) / [mockup](https://xd.adobe.com/view/44399930-6143-4192-6e80-99a0566c4092-3208/screen/5b8c5a45-c694-42a6-b7f2-e2ca01b90916/View-Payments-1/)
- [ ] Create a list of next steps that need to be implemented

## Acceptance Criteria
- [ ] The initial pages have been created locally and a quick view has been shared with the team
