### ISSUE TITLE
EVSS PCIU Migration: Step 8: Refactor ContactInformationV2

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#93444]
## User Story
As a developer, I want to reduce confusion over the Contact InformationV2 Service so I will refactor the existing code.
## Issue Description
ContactInformationV2 currently contains code that is difficult to read, maintain, or extend. This refactoring task aims to improve code quality by applying best practices, removing redundancies, and optimizing the code structure without changing the existing functionality.

At the moment, the MPI::Service re-initializes their info from Contact Information once every 24 hours. When Contact Information is updated, the MPI cache should also be updated with present data.

[Manual Smoke Test Instructions](https://vfs.atlassian.net/wiki/spaces/PPT/pages/4030038071/Manual+Smoke+Test+Instructions) should be used to document the testing process.

## Tasks
- [ ] Refactor Service code
- [ ] Refactor Transaction code
- [ ] Update MPIData redis cache when updating VAProfileRedis::V2::ContactInformation.for_user(@user) in Contact Information Service V2. -> Cannot be tested locally or in dev. 
- [ ] Test refactored content information as needed
- [ ] Document process of testing and any corrections from the first round of testing the contact information refactoring.

## Success Metrics
- [ ] Code is refactored
- [ ] Specs are passing
- [ ] MPIData cache is updated with current Contact Information in Staging.

## Acceptance Criteria
- [ ] Contact information has been correctly refactored
- [ ] Documentation on process has been captured
- [ ] Documentation of the testing outcomes and results
- [ ] Any necessary testing is complete. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by RachalCassity** [comment]
Screenshots from [Created PersonV2 Service and enabled ContactInformationV2 for StatementIdentifierService and McpNotificationEmailJob](https://github.com/department-of-veterans-affairs/vets-api/pull/18514) that should be addressed:
![Image](https://github.com/user-attachments/assets/87c50fd6-baed-4b71-a40e-c5db7ef0b66d)
![Image](https://github.com/user-attachments/assets/dbfbee75-c91b-46a7-8000-a1e67703a928)
![Image](https://github.com/user-attachments/assets/20473197-b3c3-47e6-8460-405e5d36eecb)
![Image](https://github.com/user-attachments/assets/65901705-36e6-4876-a346-639ea67419a2)

**Comment by AshleyGuerrant** [comment]
Moving out 2 sprints. This work should happen after ContactInformation is complete.

**Comment by AshleyGuerrant** [comment]
**Standup note:** This ticket was discussed with the team, and while the refactoring is a nice-to-have it is definitely not critical to this initiative. Moving this ticket to the backlog so the team can continue to focus on the critical work for this initiative.

**Comment by RachalCassity** [comment]
[EVSS PCIU Migration: Step 9: Testing Contact Info Refactor](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93453#top) tasks have been added to this ticket. [EVSS PCIU Migration: Step 9: Testing Contact Info Refactor](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93453#top) can be closed.

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note**: ejecting from the current sprint due to the government shutdown on 101/25. Work on this ticket can be resumed sometime after the shutdown is resolved.

cc @jwoodman5 @RachalCassity
