### ISSUE TITLE
Scaffold Out the "PCPG (CH36)" Page(s)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9345]
## Goal
The next step in building this feature is to build out the initial pages based on the currently designed prototype from Design.

## Considerations
- Consider routes, what mock data might need to be in place and any other initial activities as we home in on the first version.

## Tasks
- [x] Create the pages for the various screens for this feature
- [x] Frame or stub out the component areas [based on the prototype](https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/128093534/simulate/sitemap)
- [ ] Create a list of next steps that need to be implemented

## Acceptance Criteria
- [x] The initial pages have been created locally and a quick view has been shared with the team
