### ISSUE TITLE
[CST] Hack PMR pending first party requests to be  third party requests

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#93456]
## Value Statement
**_As a_** veteran checking the claim details for an in progress claim
**_I want to_** be presented with accurate information about action items I need to take
**_So that_** I take those actions and improve my claim outcomes.

---
## Background Context

Currently PMR Pending requests are showing up as actions for the veteran to take. In reality, these are third party requests and we should merely be informing the veteran that the VA is taking steps to gather their private medical records on their behalf as part of their "duty to assist". 

Similar to the HAIMS STR request issue, BGS is miscategorizing these tracked items as first party requests ("needed from you"), they should be categorized as ("needed from others"), so that they show up in the correct section of CST and not as alerts for the veteran to take action. 

Long term solution is to get BGS to categorize these tracked items correctly. Short term solution is to hack the FE code to categorize PMR Pending tracked items as "needed_from_others" despite it not coming through that way on the backend. 

Current UI example of first-party alert: 

![Image](https://github.com/user-attachments/assets/8c9870d4-b327-45bd-993a-177fe1150d1c)

### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Tracked item Status is needed_from_you, but ideally would say needed_from_others
- Display name = PMR Pending

## Out of scope
- Add here

## Open questions
- What about the claim card alert? 

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] PMR Pending requests are visible as a third party alert in "For Others" section of CST. 
- [ ] PMR Pending requests do not show in the "For you" section of CST.
- [ ] "Private Medical Records Pending request" is the label used instead of the acronym

**Comment by jstrothman** [comment]
@jacobworrell Could you display the name as "Private Medical Record" instead of "PMR Pending"
As with other 3rd party requests, CST displays text ahead of this ("Request for others" "We opened a request for 'PMR Pending'). It will be easier to understand what this is if PMR is spelled out and "pending" is removed.

**Comment by LouisFettet** [comment]
Here's a quick screenshot of what I've got locally so far under "Recent activity" (the alert under "What you need to do" is no longer rendered):
![Image](https://github.com/user-attachments/assets/dde68418-9283-4d97-8782-7d417d1c7184)

Just a quick question for @jacobworrell : @jstrothman suggested replacing "PMR Pending" with "Private Medical Record" and dropping the "Pending", but the issue description says to change it to "Private Medical Records Pending request". Which one should I use?

**Comment by jacobworrell** [comment]
@LouisFettet I think we should go with Julie's recommendation, drop "Pending" and make it "Private Medical Record request"

**Comment by LouisFettet** [comment]
Roger that, thanks @jacobworrell. I'll add "request" to the end of the label shown in the screenshot above, so that the full sentence states `We opened a request for "Private Medical Record request"`. 

Unless we think that adding "request" at the end is too duplicative? I suppose we currently do the same thing for HAIMS STR, e.g. `We opened a request for "HAIMS STR Request"`. So maybe it's fine? Sorry if I'm being pedantic 😅

**Comment by jstrothman** [comment]
@LouisFettet Let's not add "request" to the end. It should just read  `We opened a request: "Private Medical Record"`

By replacing the word "for" with a ":" we eliminate some of the funky wording. I hope we'll make this change across-the-board but not in this issue. (The "HAIMS STR Record request" wording is something we'll address separately by using a human-friendly description in future as well.)

**Comment by LouisFettet** [comment]
Sounds good, I'll drop the "request". And yes there's a separate ticket (#93433) to replace the "for" with a colon across the board, so I won't handle that here. Thanks all!
