### ISSUE TITLE
Disco: What frequency can we generate 526 pdf within 30 seconds?

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#93464]
## Issue Description
As a PM I would like to know with what frequency our systems are able to generate a 526 pdf within 30/20/10/5 seconds so that I can understand the feasibility of providing this to the Veteran on the Confirmation screen and/or in a follow up email to be sent directly after the Veteran submits their application.

---
## Tasks
- [ ] Farm existing metrics to see if we can have this information
- [ ] Get numbers for p90, p, 95, and p99
- [ ] Report on and consider percentage use of the primary path (as this indicates we can generate this within 24 hours)
- [ ] If existing metrics don't capture this information please create one if needed
- [ ] Add metrics to our Datadog reporting
- [ ] Add links to these metrics on the 526 metrics document

## Acceptance Criteria
- [ ] We have reporting that indicates the frequency by which we can generate a pdf within 30 seconds
- [ ] Metrics are shared with the PM and socialized with the team to the extent appropriate

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
