### ISSUE TITLE
Redis POAM: Dev-Environment Redis Security Upgrades

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#93500]
## User Story
As owner of the vets-api Redis instance
We need to apply security upgrades to the Redis clusters in the **dev** environment
So that they are in security compliance

## Issue Description

The [discovery work](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3463512080/AWS+Elasticache+Redis+Discovery+and+Results) in the preview instance help us get clarity on the technical requirements for the upgrade. This story will apply those findings to the first of our lower, live environments.

## Tasks
- [ ] Communicate the work to platform and VFS teams
- [ ] Apply the upgrade plan as outlined in the documentation above
- [ ] Document any noteworthy findings for the next environment
- [ ] Communicate changes to the security team so that they may validate the work

## Success Metrics
- The dev environment has all the necessary security measures in place
- vets-api continuous to work without issue

## Acceptance Criteria
- 

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
