### ISSUE TITLE
Content for 10-10EZR Next of Kin

### ISSUE THREAD

**Issue by bmrea1** [department-of-veterans-affairs/va.gov-team#93502]
## Issue description
The 10-10 health apps teams is adding Next of Kin to the online 10-10EZR.
[Link to intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91447)

We'll also need to adjust the static page to include "next of kin" is the list of types of information someone can update.
[Link to static page](https://www.va.gov/health-care/update-health-information/)

---
## Tasks for designs
_What work is necessary for this ticket to be completed? Examples:_
- [x] Assess request
- [x] Review content
- [x] Add content recommendations in Figma
- [x] Share with product team

## Acceptance Criteria
- [ ] Product updates are live

**Comment by aliyahblackmore** [comment]
Hieu shared on Friday that he'll share the updated designs in the next 1-2 weeks. Moving this to "Blocked" for now.

**Comment by aliyahblackmore** [comment]
**Updates here:** 

Content feedback is ready for the designers in their [Figma file](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=6081-70662&node-type=instance&t=3pzDZcGsGBSr6AjX-0).

- I adjusted the content here based on the information from the designs and the definitions from the designers/product team. The product team will review with their SMEs have them confirm/okay that the definition here (that’s aligned with VA profile and check in) works. We can make adjustments if needed (i.e. whether we leave “medical documentation and benefits”).  

- Team shared on 10/25 that if they can’t move forward with two entries for NOK, they’ll mock up designs for one entry at that time. There may be some slight content adjustments there (i.e. using “This is the person” instead of “These are the people"). 

- I added the tentative static page update to the “Personal information” point on the static page mock up in their designs. We can revisit that when you all are ready to launch to Veterans. We’ll want to ensure we coordinate timing for publishing - if NOK is coming after EC, we can assess. 

- I added in the form intro page mock up to the NOK section  and tracked the update to the “Personal information” bullet point. I also noted the areas of the mock up that don’t align with what’s in production and tracked changes. 

- It seems like the appointments/check-in team is having ongoing conversations to learn more about NOK and how VA health facilities use that information. As the product team gets any more info about how facilities using this information and continue their conversations with the check in and VA profile teams, we can revisit and update any of the definitions.  I recommend continuing conversation with the VA profile and check in teams to keep these definitions aligned where possible if all data is eventually going to the same API.

**Comment by aliyahblackmore** [comment]
We made some additional updates for V1. 

[Notes are in the intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91447#issuecomment-2492188422)

**Comment by VCM86** [comment]
Closing--reach out if you have any questions.
