### ISSUE TITLE
Verify that GetHTMLStatementById is unused

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#93514]
## Issue Description

This is a followup to some discussions that came out of https://github.com/department-of-veterans-affairs/va.gov-team/issues/93430 where we found that we do not use the  VBS `GetHTMLStatementById` endpoint. The VBS team believes that we are the only consumer of this API and may need it in the future. We should figure out if we plan to use this in the future and if not, ask them to remove this endpoint.

## Tasks
- [ ] Double check that we don't use the `GetHTMLStatementById` endpoint
- [ ] Verify with leadership that we don't plan to use this in the future
- [ ] Ask VBS to remove this endpoint

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] All tasks from the description are completed    

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points

**Comment by JunTaoLuo** [comment]
FYI Megan Palmer said the following when I told them that we don't use this endpoint and asked if any others used it:

> The endpoints are built for VODA and only used by VODA. We need to make sure they work, as you may use more of them in the future, as well as verify updates to them.

**Comment by denisecoveyduc** [comment]
This is not a requirement at this time. We work closely with VBS and have not received any indication that this is a problem.
