### ISSUE TITLE
DISCOVERY | Investigate why Deleted feature flippers are re-added

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#93511]
## User Story
As a developer, I want to investigate the underlying source of the issue of features being re-added after deletion, so that the system properly handles feature flags and doesn't retain outdated features.

## Issue Description
Based on the research that was done in https://github.com/department-of-veterans-affairs/va.gov-team/issues/87532 and the logging that was added in https://github.com/department-of-veterans-affairs/vets-api/pull/18575, we have identified that the problem is related to some pods running with an outdated version of `features.yml`. As a result, features that have been deleted are being re-added automatically.

The goal is to investigate the underlying source of the caching bug where features are re-added after they have been removed. The caching issue was noticed when a VFS team added error logs to a flipper, `Rails.logger.error("SM:Configuration Flipper error: #{e.message}") `.  

To resolve the undefined method 'column_for_attribute' for class Flipper::Gate error in a Flipper + ActiveRecord setup, you must ensure that the Flipper::Gate constant refers to the correct ActiveRecord-backed class, specifically Flipper::Adapters::ActiveRecord::Gate. This issue arises when a call like Flipper::Gate.column_for_attribute(:value) is made, but Flipper::Gate is not actually an ActiveRecord model.

[Flipper-redis](https://github.com/jnunemaker/flipper-redis) was incorporated into the Flipper gem. Locally, when flipper-redis is added to the Gemfile, the Flipper errors are no longer in the rails logs. 

All pods need to the latest version of `features.yml`.

Local puma logs (w/o flipper-redis):
```
=> Booting Puma
=> Rails 7.2.2.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
DEPRECATION WARNING: SentryLogging is deprecated and will be removed in June 2025. Use Vets::SharedLogging instead. (called from <top (required)> at /Users/rachalcassity/va/vets-api/lib/sentry_logging.rb:5)
2025-05-23 09:02:55.503217 E [42952:11880 configuration.rb:44] Rails -- RX:Configuration Flipper error: undefined method `column_for_attribute' for class Flipper::Gate
2025-05-23 09:02:55.503411 E [42952:11880 configuration.rb:41] Rails -- RX:Configuration Flipper error: undefined method `column_for_attribute' for class Flipper::Gate
2025-05-23 09:02:55.503508 E [42952:11880 configuration.rb:39] Rails -- SM:Configuration Flipper error: undefined method `column_for_attribute' for class Flipper::Gate
2025-05-23 09:02:5
```

If you want to delete a batch of flippers from the db, we have [instructions for that process](https://vfs.atlassian.net/wiki/spaces/BCP/pages/3481370733/Removing+feature+flippers).

Relevant Datadog search links:
- [Datadog search for "Error processing Flipper features"](https://vagov.ddog-gov.com/logs?query=env%3Aeks-staging%20%22Error%20processing%20Flipper%20features%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1727190935000&to_ts=1727192735000&live=true)
- [Datadog search for "The following feature flippers were added"](https://vagov.ddog-gov.com/logs?query=env%3Aeks-dev%20%22The%20following%20feature%20flippers%20were%20added%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1727190935000&to_ts=1727192735000&live=true)
- [Datadog search for "Consider removing features no longer in config/features.yml"](https://vagov.ddog-gov.com/logs?query=env%3Aeks-dev%20%22consider%20removing%20features%20no%20longer%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1727190935000&to_ts=1727192735000&live=true)**

## Reported Flipper Redis Issues
1. https://github.com/flippercloud/flipper/issues/926
2. https://github.com/flippercloud/flipper/issues/905
3. https://github.com/flippercloud/flipper/issues/884

## Tasks
- [ ] Investigate why the redis is not correctly caching the features. 
- [ ] Inspect [flipper](https://github.com/flippercloud/flipper) configurations:
- [ ] Identify a solution to resolve caching issues and write up any necessary follow-up tickets.
  
## Acceptance Criteria
- [ ] Discovery doc is reviewed
- [ ] Follow-up ticket created. 

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by rmtolmach** [comment]
Observations from working on this in https://github.com/department-of-veterans-affairs/va.gov-team/issues/87532:

I cleaned up the deprecated feature toggles in each env and added logging to [config/initializers/flipper.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/flipper.rb). After the logging was added, in all 4 envs, we see this message in dd: `The following feature flippers were added: ["va_notify_user_account_job", "remove_pciu"]`. All envs only mention two flippers getting added. When I search the message "Consider removing features no longer in config/features.yml:" (i.e. how many features the env thinks is deprecated), staging, sandbox, and prod have been purged of _almost all_ deprecated flippers–those envs look good. HOWEVER, dev does _not_ look good. In that "Consider removing..." message, there are probably 100 (even though I've deleted them all twice in the last week). Those 100+ aren't being added in the `Flipper.add(feature)` line of flipper.rb, b/c we'd know about it through the logging. They're getting added somewhere else. That's the mystery. [This line](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/flipper.rb#L58-L59) made me do a double-take b/c it mentions `dev` specifically, but idk if it's related.

**Comment by nfstern02** [comment]
I spent a few hours on this issue and **I know how to fix it**. It's a timing issue w/Flipper on bootup. @rmtolmach let's huddle and I can walk you through the solution. It was blazingly simple once the problem was isolated.

**Comment by nfstern02** [comment]
Btw, these errors are showing up on DataDog production too.

**Comment by rmtolmach** [comment]
> I spent a few hours on this issue and **I know how to fix it**. It's a timing issue w/Flipper on bootup. [@rmtolmach](https://github.com/rmtolmach) let's huddle and I can walk you through the solution. It was blazingly simple once the problem was isolated.

For clarification: Noah is referring to the `RX:Configuration Flipper error: undefined method `column_for_attribute' for class Flipper::Gate` errors, _not_ the problem of deleted feature flippers getting re-added. So this ticket is still needed.

**Comment by AshleyGuerrant** [comment]
@rmtolmach - thanks for digging into this, that's awesome news! Thanks, backlog cleanup for the win!
