### ISSUE TITLE
[BE] My VA TMA: Support silent failures audit

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#93541]
## Background
Per OCTO priorities we've been asked to conduct an audit of our applications and endpoints to determine if we have any silent failures. Tom is taking point on completing the audit for My VA and Profile but will need support from Daniel to execute. Chante will need to present on our findings on Oct 2 so this is top priority.

Target completion by 9/30

## Tasks
- [x] [Review silent failures documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md#how-to-discover-if-your-application-has-a-silent-failure)
- [x] meet with Tom to go over the spreadsheet and report he has created
- [ ] Work with Tom to complete the checklist
- [x] Coordinate with PM if there are any follow on tasks

## Acceptance Criteria
- Audit is complete and any follow-on tasks are documented in the spreadsheet and/or captured in our backlog

**Comment by DanielMiller-agile6** [comment]
Here's some notes from my audit of silent errors on My VA:

- Add custom service tag for “myva” in datadog (we're currently using the “profile” tag). Requires platform_support ticket? Tom is looking into how to do this, as neither of us had permissions to do so.
- Ensure our dependency list for DowntimeNotification is accurate (which service identifyer is "benefits intake api"? Is that vbms?). add ‘mhv_sm’ dependency to list, or handle within MyVA to avoid inaccessible dashboard when only downtime is secure messaging?
- add monitors for list of myva controllers (errors & volume anomaly)
	- V0::MyVA::SubmissionStatusesController#show
	- V0::BenefitsClaimsController#index
	- V0::AppealsController#index   
	- VAOS::V2::AppointmentsController#index
	- V0::DebtsController#index
	- V0::MedicalCopaysController#index
	- V0::Profile::PaymentHistoryController#index

I will add new monitors for each controller listed here as part of this ticket.  I've coordinated with Tom to include my findings in his AuthExp audit report.

**Comment by ajakabcin** [comment]
thank you for this @DanielMiller-agile6! I'm going to hold off on making any follow-up tickets for this work until Chante presents our findings at tomorrow's OCTO meeting in case there are additional action items. I think then it may make sense to have a dedicated refinement session to discuss action items. Thanks!

cc @tpharrison @ACParker89

**Comment by tpharrison** [comment]
@DanielMiller-agile6 I have opened this [support ticket](https://dsva.slack.com/archives/CBU0KDSB1/p1727288642641199) to address most/all of these issues.

cc/ @ajakabcin @ACParker89

**Comment by ajakabcin** [comment]
Closing this out - any follow up work will be handled separately
