### ISSUE TITLE
[Design] My VA TMA: support silent failures audit (documentation & UX portion)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#93548]
## Background
Per OCTO priorities we've been asked to conduct an audit of our applications and endpoints to determine if we have any silent failures. Tom is taking point on completing the audit for My VA and Profile with support from Daniel to execute. There are two sections within the checklist for documentation (user flows, general documentation of error handling etc.) and user experience (how do we handle errors in the application - or otherwise). This is where Tom and Daniel need some assistance from Design.

Chante will need to present on our findings on Oct 2 so this is top priority.

## Tasks
- [x] [Review silent failures documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md#how-to-discover-if-your-application-has-a-silent-failure) - specifically the [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md#documentation) and [User experience](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md#user-experience) sections
- [x] Meet with Tom and AJ to provide answers where needed in the reports Tom created
- [x] Coordinate with PM if there are any follow on tasks

## Acceptance Criteria
- Audit (documentation and user experience portions specifically) is complete and any follow-on tasks are documented in the spreadsheet and/or captured in our backlog

**Comment by mattmarino-adhoc** [comment]
Will sync with engineering about documentation on Monday

**Comment by ajakabcin** [comment]
@mattmarino-adhoc and @twoangstroms - re the user flows, I think it will be sufficient for this audit to say "yes we have them" and point to our user flows in our use case documentation. If they're looking for something more specific we can address post-audit presentation

- [My VA use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases)
- [Profile use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/use-cases)

**Comment by mattmarino-adhoc** [comment]
@ajakabcin that works for me

**Comment by ajakabcin** [comment]
One more note there's some guidance in the silent failures overview with considerations for creating user flows that calls out identifying points of failure. I think what we have is probably sufficient but we can create some follow up tickets to review them to more specifically call out where points of failure could occur.

cc @ACParker89 (flagging for you for Mike M)

**Comment by mattmarino-adhoc** [comment]
@ajakabcin yep, I'm discussing with engineering still, we can try to address them at least high-level in existing user flows before Oct 2 if we have time

**Comment by ajakabcin** [comment]
Closing as complete - documentation is noted for the audit, we'll have some follow on tasks to update user flows with possible failure points
