### ISSUE TITLE
Static page update on Update your health benefits information page - Next of Kin updates

### ISSUE THREAD

**Issue by bmrea1** [department-of-veterans-affairs/va.gov-team#93540]
## Issue description

The 10-10 health apps teams is adding Next of Kin to the online 10-10EZR.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/91447

We'll also need to adjust the static page to include "next of kin" is the list of types of information someone can update.
[Link to static page](https://www.va.gov/health-care/update-health-information/)

## Tasks for static page
- [ ] Update page
- [ ] Copyedit
- [ ] Share with SMEs for review
- [ ] Publish page

## Acceptance Criteria
- [ ] Product has launched
- [ ] Static page updates live
