### ISSUE TITLE
[Design, FE] My VA Forms Status: A11y prep for forms status staging review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#93553]
## Background
In preparation for staging review we need to perform a11y tests/provide evidence that we perform a11y tests on the new forms status work on My VA. This will be a joint effort from Design and FE to perform these tests, and Product to ensure everything is documented to submit the request. 

[A11y staging review preparation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) documentation for reference. Noting for future reference, a11y platform folks have introduced a new format for completing these tests. For staging review, a11y asks that the team submit a11y testing via [this ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). More documentation [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#Prepareforanaccessibilitystagingreview-Usingtheaccessibilitytestingartifactartifact).

## Tasks
- [x] Design and FE to perform the accessibility tests as documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/launch-materials/forms-status-on-My-VA-a11y-staging-review-prep.md)
- [x] PM to assist as needed and track progress in staging review artifact documentation
- [x] Design and FE to let PM know when complete so they can fill out [this request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)

## Acceptance Criteria
- [ ] Accessibility test ticket is submitted for Staging Review

## Resources
- Use staging users 88, 226 and/or Cecil Morgan for the tests depending on the scenarios
- Examples of a11y prep for past staging reviews:
     - Dot indicator: [test report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/dot-indicator/create-dot-indicator/launch-materials/dot-indicator-a11y-staging-review-prep.md), #67204 
     - My VA audit UX improvements: [test report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/launch-materials/my-va-audit-improvements-a11y-staging-review-prep.md), #54648

**Comment by allisonlu** [comment]
I've performed all the [checks listed in the a11y prep doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/launch-materials/forms-status-on-My-VA-a11y-staging-review-prep.md). 

Ready for @ajakabcin 's validation, and @mattmarino-adhoc too, if he wants to check color contrast and zoom

**Comment by mattmarino-adhoc** [comment]
Zoom is good, but color contrast appears that it may only pass AA WCAG standards - this is due to the current color choices of the tag component. This is not something we can resolve as a team. In addition, it appears the incorrect typography is showing up on the component (using the Bitter serif font, instead of Source Sans Pro) - this is inconsistent for the component and VADS. @allisonlu

**Comment by ajakabcin** [comment]
Submitted #93786

**Comment by ajakabcin** [comment]
You guys are rockstars thank you!
