### ISSUE TITLE
Discovery: Team Chooses Which Version to Publish

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#93557]
## Pain Point 
The Content Team published an MVP version of [the Redirect Integration Strategy page ](https://depo-platform-documentation.scrollhelp.site/developer-docs/redirect-implementation-strategies) but it is still not formatted well and will be hard to use by VFS Teams.

### Content Team needs to vote on which of 2 proposed versions of this page to replace the current one.

- [Version 2 - Still one page](https://vfs.atlassian.net/wiki/spaces/~637b96fdfde064eda2ed7417/pages/3476258817/V2+-+Redirect+Implementation+Strategy)

- [Version 3 - now with child pages](https://vfs.atlassian.net/wiki/spaces/~637b96fdfde064eda2ed7417/pages/3469213926/V3+-+Redirect+Implementation+Strategy)

---
## Tasks

Each Team Member vote which version should be published as the final version.

@BSmolensky 
- [ ] Version 2     
- [x] Version 3

@taylojill 
- [ ] Version 2     
- [x] Version 3

@cmarion93 
- [ ] Version 2    
- [x] Version 3

@jknipes 
- [ ] Version 2   
- [x] Version 3

## Acceptance Criteria
- [x] We will have chosen the final version to replace the current one on Platform Website
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/93557?planning-poker) with Zenhub @BSmolensky

**Comment by BSmolensky** [comment]
I am going to withhold my vote until the rest of the team has voted. Since I created the two versions, I would like to see everyone's feedback without potentially biasing the results with my own opinion.

**Comment by cmarion93** [comment]
@BSmolensky This section is a little confusing because redirect type is used to mean two different things at once. The redirect type in the intro to and title of the table refers to redirect origin and destination, whereas the "Type" column in the table refers to whether the redirect is server-side or client-side. The immediate solution I'm thinking of is to name the column "Client-side or server-side," but would that be too bulky?

![Image](https://github.com/user-attachments/assets/f8e1ff75-6bea-4d54-afcb-6a63411fa568)

**Comment by BSmolensky** [comment]
@cmarion93 - Thank you for this feedback! I will be sure to fix this once it's time to finalize the page(s). Thank you, as well, for your vote!

**Comment by jknipes** [comment]
work is complete, moving to _Closed_
