### ISSUE TITLE
Complete Zero Silent Failures Checklist

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#93561]
## Issue Description
As a DBEX team member I want to complete the Zero Silent Failures (ZSF) checklist (below) to ensure that We provide the very best Veteran experience. The activities listed below will be completed and any future product, design, or engineering work needed to address ZSF is identified and tickets are created for this work with clear action items.

---
## Tasks
- [ ] Complete the checklist below
- [ ] OCTO, Team 1, Team 2 meet as needed to discuss or resolve any items
- [ ] PMs and Eng Leads from both teams meet with the Zero Silent Failures federal lead team on October 2nd

## Acceptance Criteria
- [ ] The checklist below is completed
- [ ] Create tickets for any additional work to address gaps

## Additional Information
Text-based documentation is saved in products/disability/526ez

---
#### Start

* [ ] Do you know when your application shipped to production?
  * If not, use Github to determine, roughly, when your application shipped to users.
* [ ] Did your application use the same APIs when it shipped as it does today?
  * If not, then you'll need to consider the path user data took through both the current architecture and the previous architecture. You will need to account for potential failures in all paths since your application shipped.

#### Monitoring

* [ ] Do you monitor the API(s) that you submit to via Datadog? 
  * If not, [set up monitoring in Datadog](#set-up-monitoring-in-datadog).
* [ ] Does your Datadog monitoring use the appropriate tagging?
  * If not, [implement tagging standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards). Adding the [dependency tag](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards#MonitorTaggingStandards-Recommended:dependency) is highly recommended!
* [ ] Do errors detected by Datadog go into a Slack notifications channel?
  * If not, start directing errors in Datadog to a dedicated Slack channel. See [#veteran-facing-forms-notifications](https://dsva.slack.com/archives/C063SM22J3H) for an example.
* [ ] Does more than one person look at the Slack notifications channel containing errors on a daily basis? 
  * If not, then follow this [guide on managing errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md)
* [ ] Do the team members monitoring the Slack channel have a system for acknowledging and responding to the errors that appear there? 
  * If not, then follow this [guide on managing errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md)

⚠️ **Failure to have endpoint monitoring in place is a blocking QA standard at Staging review as of 9/10/24.** If you answered no to any of the questions above, you will be blocked from shipping at the Staging review touchpoint in Collab Cycle.

#### Reporting errors

* [ ] Have you filed issues for errors that are appearing in Datadog / Slack?
  * If not, then start filing Github issues for new categories of errors following [this guidance](#file-silent-errors-issues-in-github)
* [ ] Do all fatal errors thrown in your application end up visible to the end user either in the user interface or via email?
  * If not, then file Github issues to capture error categories following [this guidance](#file-silent-errors-issues-in-github)

#### Documentation

* [ ] Do you have a diagram of the submission path that user data your application accepts takes to reach a system of record? 
  * If not, then [create a user data flow diagram](#how-to-create-a-user-data-flow-diagram) that captures this information. 
* [ ] Do you understand how the error is handled when each system in the submission path fails, is down for maintenance, or is completely down?
  * If not, then create documentation that captures how errors in each system are handled. Detail which systems retry a submission and what happens when those retries exhaust. Show this in your diagram.
* [ ] Has the owner of the system of record receiving the user's data indicated in writing that their system notifies or resolves 100% of fatal errors once in their custody?
  * If not, work with OCTO to meet with the owner of the system and get their agreement in writing.
  * Please document the outcome of this conversation in your product's documentation in Github.

#### User experience

* [ ] Do you capture all of the potential points of failure and make those errors known to the user via email notification and/or through the application on VA.gov or the mobile application?
  * If not, don't worry. Few teams are doing this and we'll be providing resources to help you do this in your application. Proceed to [create a user data flow diagram](#how-to-create-a-user-data-flow-diagram). That diagram will help us to help you and your team to create this user experience.

## We don't have any silent errors!

Great! Please let us know that you went through the checklist above as a team and did not find any silent failures in our Slack channel: [#zero-silent-failures](https://dsva.slack.com/archives/C07KTTFP308) and send us a link of a copy of [this](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md#checklist) completed checklist. If you don't connect to a backend system, you don't need to fillout the checklist but let us know in your message.   You don't have to hang out in there once you have notified us. Just pop in, tell us who you are (which team and in which portfolio) and that no failures were found. Thanks!

### Set up monitoring in Datadog

Follow this [guidance on endpoint monitoring](https://depo-platform-documentation.scrollhelp.site/developer-docs/endpoint-monitoring) to get going. Then following the guidance on [monitoring performance](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-applications-and-infrastructure-with-datad) to get up to speed with Datadog.

#### Examples

* [Benefits Intake API Form Submission Tracking](https://vagov.ddog-gov.com/dashboard/4d8-3fn-dbp/benefits-intake-form-submission-tracking?fromUser=false&refresh_mode=sliding&from_ts=1725259648303&to_ts=1725864448303&live=true)
* [Banana Peels (Lighthouse Appeals/Forms/Benefits Intake APIs)](https://vagov.ddog-gov.com/dashboard/aea-kge-ekt/banana-peels-lighthouse-appealsformsbenefits-intake-apis?fromUser=true&refresh_mode=sliding&from_ts=1725259764640&to_ts=1725864564640&live=true)
* [Benefits Sidekiq Death Queue view](https://vagov.ddog-gov.com/dashboard/ftx-zzd-v9j/benefits-sidekiq-job-death-queue-view) - shows recently exhausted Sidekiq jobs.

[Additional examples](https://depo-platform-documentation.scrollhelp.site/developer-docs/platform-dashboards-in-datadog)

### File silent errors issues in Github

We want to know about your silent errors so that we can help you to fix them. To do this, follow the process in the [Managing Errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md) document.

### How to create a user data flow diagram 

Creating a user data flow diagram is a requirement of the Zero silent errors initiative and will be a required asset at the Architecture Intent touchpoint of the Engineering and Security track of Collaboration Cycle.

[Learn how to create a user data flow diagram](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-create-a-user-data-flow-diagram.md)

**Comment by lisacapaccioli** [comment]
In this [thread](https://dsva.slack.com/archives/C04KW0B46N5/p1727281874619959),  please link me to any document or artifact you've worked on related to submission flow, failure/error cases. Even if they're out of date or partial, they'll help me as I take a first pass at the checklist for zero silent failures. I have a few already but am just casting a wide net! more is better! looking for your pile of links before EOD today. (edited) 

**Sam Stuckey**
- [top level doc that explains the safety net in both technical / non-technical terms](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/the-526-failure-saftey-net.md). (probably the most relevant)

features that support / power the safety net:
- [526 scopes (programatic interface to state)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/526_scopes.md)
- [paranoid success polling](http://d/) (how we cover an edge case)
- [State TDD (how we define success so we can cover failure)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/untouched_submission_audit/526_state_repair_tdd.md)

Remediation era docs
- [deduplicating (top level, has nested docs)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/deduplicating_526_submissions.md)
- [discovery doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/complex_submission_deduplication.md)
- [audit discover (precursor to state)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/post_remediation_audit_for_untouched_submissions.md)
- [Audit 'funnel' (precursor to scopes)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/untouched_submission_audit/funnel_logic.md)
- [Proposal on how to get to 100% coverage (precursor to State TDD)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/untouched_submission_audit/closing_the_blackhole.md)


**Kyle Soskin**
[doc](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57489#issuecomment-1540202820) from a while ago of stuff I thought should be monitored, and how, not sure if any of it got made
I feel like I probably had a lot of other stuff, but will have to dig around for it


**Aurora Hampton**
1. [high-level domain model](https://lucid.app/lucidchart/645d8a16-22de-4971-9626-198da0483430/edit?page=0_0&invitationId=inv_f335ce12-6583-4396-8892-0c33e67c8b9e#)
2. [technical overview for submit migration to lighthouse](https://lucid.app/lucidchart/645d8a16-22de-4971-9626-198da0483430/edit?invitationId=inv_f335ce12-6583-4396-8892-0c33e67c8b9e&page=Ky8k5yKoOg9P#)
3. [diagram used for our 2022 form version PSIRR](https://lucid.app/lucidchart/645d8a16-22de-4971-9626-198da0483430/edit?invitationId=inv_f335ce12-6583-4396-8892-0c33e67c8b9e&page=S.QYMIEDG_Hk#)

non-diagram things
1. [what happens if pdf polling fails in the primary path?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/lighthouse_submission_remediation.md)
2. [troubleshooting 2022 form version problems](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/526/TREX/DEBUG/SOP-Toxic-Exposure-Lighthouse-Form526-Submission-Troubleshooting.md)
3. [supplemental documentation to the remediation process](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/526/TREX/DEBUG/remediation_playbook.md)

**Nathan Burgess**
I believe all I had were the two diagrams in the [bottom left of this page](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704307770399/7ba4dac361cbc90633616ae0a476bf7ac0db94f2?sender=142a9bae-4ab6-46ce-bf33-5d53289e5dfa) which include my initial discovery of where I believed the silent failures were, plus a draft of a "state machine" that could track the status of all of the ancillary documents, but our understanding of the failure points may have changed in the meantime, this was back in the beginning of the year when I first noticed where things could be slipping through the cracks
mural.comural.co
[526 Claim Submission Migration - Polling](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704307770399/7ba4dac361cbc90633616ae0a476bf7ac0db94f2?sender=142a9bae-4ab6-46ce-bf33-5d53289e5dfa) (32 kB)
So that would be "(Current) Ancillary Jobs Flow, Retry and Fail State Diagram" and "(Future) Ancillary Actions State Machine"

**Comment by emilytheis** [comment]
I moved this checklist into a markdown file in the sensitive repo since it will need to live on beyond the lifecycle of this ticket:

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/investigations/Disability%20526-%20Zero-Silent-Failures-Checklist-.md
