### ISSUE TITLE
[FSR] Sentry logging for form submission

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#93564]
## Issue Description
We may be able to add some additional Sentry logging on form submission  where we pack up the streamnlined info in the following file:
`src/applications/financial-status-report/config/submitForm.js`

## Tasks
- [ ] Investigate opportunity for Sentry logging on form submission
- [ ] (optional) Implement Sentry log

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Investigation for Sentry logging on submission complete
- [ ] (optional) Implement additional sentry logging for submission

## Testing
- [ ] Test senty logs when form submission fails

Test procedures:      
Try manually breaking submission (rename endpoint?) see what the logs pop

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by HeatherRienks** [comment]
This ticket can be closed since vets website is no longer using Sentry.
FYI @denisecoveyduc
