### ISSUE TITLE
[VETS-API] [DISCOVERY] Iterate on Current Backend CI Checks

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#93566]
## Issue Description
There are currently several issues with the GHAs that are attempting to simplify the lives of the BE CoP when it comes to approving PRs, but instead have had some unintended effects that are blocking/slowing development, raising a ton of noise, and adding to our workload. I believe we need to to step back and establish what we're trying to accomplish, what we have that's working, what doesn't work, and what needs to be put in place to achieve our ideal workflow.

---
## Tasks
- [x] Establish explicit criteria for PR approval
- [x] Whiteboard ideal process with edge cases
  - [x] failing specs
  - [x] updating to master
  - [x] re-approvals
  - [x] approvals required by multiple teams
  - [x] teams exempt from backend approval (Mobile, Identity, Lighthouse?)
- [x] Consider options for workflows to meet these requirements, regardless of what is already in place
  - [x] Determine if any existing checks can be used or easily modified to meet these 
- [x] Discuss options with CoP
- [x] Create tickets for follow up work

## Acceptance Criteria
- [x] Confluence page is created with whiteboard and decisions documented
- [x] Tickets created

**Comment by ryan-mcneil** [comment]
Whiteboard: https://vfs.atlassian.net/wiki/spaces/PRT/pages/3535470594/Vets+API+CI+Backend+approval+Consolidation

**Comment by ryan-mcneil** [comment]
Next ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/95609
