### ISSUE TITLE
Edits: Redirect Implementation Strategy Part 1 of 2

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#93560]
## Pain Point 
The Content Team published an MVP version of [the Redirect Integration Strategy page ](https://depo-platform-documentation.scrollhelp.site/developer-docs/redirect-implementation-strategies) but it is still not formatted well and will be hard to use by VFS Teams.

## Issue Description
We need to work on the edits on which ever version we go with from **[ticket 93557](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93557)** 

UPDATE: Team and polled Engineers all agreed that the multi-page options is best. This will require building 8 new pages. 

---
## Tasks
- [x] Get first 4 (of 8) pages complete
- [x] Prepare for deployment but wait to deploy until all 8 pages are ready. 

## Acceptance Criteria
- [x] Final version of first 4 (of 8)  pages will be completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/93560?planning-poker) with Zenhub @BSmolensky

**Comment by BSmolensky** [comment]
Ticket was modified to account for the unanimous choice of the version to build. The version everyone picked requires building 8 new pages. Additionally, this sprint saw a major issue that took everyone's time. This ticket will now be part 1 of 2.

**Comment by BSmolensky** [comment]
Criteria met. Ticket ready to close.

**Comment by jknipes** [comment]
work complete, closing as _Done_
