### ISSUE TITLE
[CDP] VBA Payment History Overview heading updates to match design

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#93565]
## Issue Description
Given: A veteran visits the CDP  
When: The veteran views the overpayments summary page
Then: They should see a [simplified header view](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=2075-17888&node-type=frame&t=UV65Nj1cIaZp65Dh-11) without the payment disclaimer now that [payment history for VBA is 100% live](https://dsva.slack.com/archives/CPE4AJ6Q0/p1727104980842939).

Follow-up to https://github.com/department-of-veterans-affairs/va.gov-team/issues/86972 

**Current version:** 
<img width="656" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEQ4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ccf63667f446444a1c402ad505b28503229ecc5/Screenshot%202024-09-24%20at%202.50.48%E2%80%AFPM.png" alt="Screenshot 2024-09-24 at 2.50.48 PM.png" />

**Proposed version:**
<img width="596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEg4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fc3da0113246d511312f0f931af4fbf5e0fb959/Screenshot%202024-09-24%20at%202.51.51%E2%80%AFPM.png" alt="Screenshot 2024-09-24 at 2.51.51 PM.png" />

## Tasks
- [x] Updated heading structure, remove redundant `h2`
- [x] Turn cards into `h2`

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Headings have been updated and payment disclaimer info has been removed.

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
