### ISSUE TITLE
ITF v1 research prep

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#93571]
### Background: 
We have scheduled the ITF comprehension research to start the week of Oct 7th with 10 participants currently scheduled. This ticket is to keep track of the prep work needed prior to those sessions.

### Tasks:

- [x] Add calendar invites to shared VA Pension & Burials Gcal
- [x] Schedule a debrief to follow each session (15 min is fine); Add these debriefs to shared VA Pension & Burials Gcal
- [x] Create and promote [sign-up sheet](https://dsva.slack.com/docs/T03FECE8V/F07P14KB002) (create in Slack canvas)
- [x] Create [Mural notetaking doc](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727466897798/418be4e4760965f98f1008eb07c92fd9020071f8?sender=uea0ff2dc88ba9faba70f3857)
- [x] Create participant tracker doc [(here is an example)](https://docs.google.com/spreadsheets/d/1uPNTLLsMGSeiYu8dVDVnVWlIcKZ0728V4CT6pQyhJuY/edit?gid=1606067745#gid=1606067745)
- [x] (Prior to internal pilot) Test all use cases within prototype (both mobile and desktop experiences)
- [x] Schedule pre-pilot session
- [x] Complete pre-pilot session
- [x] Schedule internal pilot session
- [x] Complete internal pilot session
- [x] Finalize conversation guide
   - [x] (Optional) Create a copy of the conversation guide for each participant based on which criteria they fit (experience v. no experience filing a claim) and fill in suggested time estimates for each section based on the time the session is taking place
- [x] Finalize Figma prototypes
   - [x] Create copies of prototypes by participants
   - [x] Update Mural notetaking doc 
- [x] Test Perigean Zoom account--any issues logging in/2FA issues?
- [ ] (Optional) Daniela and Elisabeth to sync on a moderator support plan
- [x] (Optional) [Review VA Platform guidance](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#4-Run-a-pilot-session) on preparing for research for any additional helpful tips!

### Acceptance Criteria:
- All of the items in the above checklist have been completed prior to our first session on Tuesday, Oct 8th.

**Comment by djones2113** [comment]
Closing as completed. Any final related prep work can be incorporated into the conduct research ticket (#94184)
