### ISSUE TITLE
Prepare the Q3 Survey for Launch

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#93572]
## Purpose
Step through the tasks to prep, launch, run, and synthesize the quarterly survey

## Tasks
- [x] [Prepare Survey in Optimal Workshop](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Platform+Satisfaction+Survey)
- [x] Update w/ the new questions and format
- [x] Send updated format to Leadership

## Acceptance Criteria
- [x] Survey is ready to launch
