### ISSUE TITLE
Revise the Customer Insights Database

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#93573]
## Purpose
We need a page for folks to be directed to that explains the Customer Insights Database, leads them to it, and also may link to explanatory documentation.

Note:  FDG landing may provide a good example of how to approach this.

## Tasks
- [x] update with newest insights
- [x] make 'area' tag, rename to 'theme'
- [x] focus on insights per team

## Acceptance Criteria
- [x] Landing page is updated with new format
