### ISSUE TITLE
Design user pathways from MHV to VA.gov for each login state 

### ISSUE THREAD

**Issue by lalexanderson-dsva** [department-of-veterans-affairs/va.gov-team#9358]
## Issue Description
We are looking to redirect MHV links to appointments from pointing to mobile to pointing to VAOS-R. MHV enables users to sign in directly using their Premium, Advanced, or Basic accounts, as well as through the SSOe experience. Only the SSOe experience will have inbound SSOe; the other three will not. We need to show MHV what the user experience should be coming in from MHV to va.gov for each case. Basic and advanced accounts need to upgrade to premium before they can use scheduling. Direct premium will need to reauthenticate - we need to decide whether we should point direct premium users to our Scheduling Tools Landing Page or to the actual VAOS app.

---
## Tasks
- [ ] Design the user flow from mHV to va.gov for the ssoe inbound
- [ ] Design the user flow from mHV to va.gov for the direct premium inbound

## Acceptance Criteria
- [ ] 2 users flows showing screen-by-screen the desired state for Veterans
- [ ] User understands they are accessing a new scheduling experience 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lenaecb** [comment]
Provided recommendation for this update to MHV team

Recommendation:
_The blue button changes from "Sign in with My HealtheVet" to "Sign in with My HealtheVet Basic or Advanced Account." This will encourage users to use the sign-in helper if they are not trying to sign in with either a basic or advance and enables their use of SSOe._

Mockup below:
![image (3) (1).png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/3c310002-f489-4e82-8bcf-927268946e23)

Closing ticket.
