### ISSUE TITLE
Configure VAProfileRedis::V2::ContactInformation

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#93588]
## User Story
VAProfileRedis::V2::ContactInformation needs to be configured for V2::ContactInformation

## Issue Description
To ensure user's vet360_contact_info is not affected by the upgrade in FormProfile and in mobile requests.

Files To update:

- [ ] VAProfileRedis::V2::ContactInformation
- [ ] ContactInformation::Service configuration
- [ ] spec/models/va_profile_redis/contact_information_spec.rb

## Tasks
- [ ] VAProfileRedis::V2::ContactInformation
- [ ] ContactInformation::Service configuration
- [ ] spec/models/va_profile_redis/contact_information_spec.rb

## Success Metrics
- [ ] Tests passing with VAProfileRedis::V2::ContactInformation

## Acceptance Criteria
- [ ] VAProfileRedis::V2::ContactInformation has been enabled for V2::ContactInformation
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
