### ISSUE TITLE
EKS Upgrade Testing Plan: Step 6: Sidekiq Functionality (dupe 1)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#93586]
This is a dupe ticket of [74644](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74644) to complete the work in Sprint 11. 

The VA Platform Product team is undergoing an EKS upgrade. As part of the process, it is necessary to conduct comprehensive testing on various components of Vets-API to ensure seamless functionality and performance during the upgrade.

**From the [EKS Testing Proposal](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3000631374/Vets+API+on+EKS+Automation+Discovery+and+Proposal)**: 
> As part of the current EKS upgrade process, comprehensive testing on various components of Vets API is essential in order to ensure seamless functionality and performance. Upgrading EKS can introduce changes that affect the behavior of deployed applications. Testing verifies that deployed applications remain compatible with any EKS changes. It ensures that all aspects of Vets API continue to operate as expected, without introducing regressions or unexpected behavior that could disrupt services for users. 
> 
> Because of future goals to conduct upgrades on a 3-6 month cadence, it is the Product Platform team’s goal to maximize the automation of these upgrade testing processes. By automating these tests, verification of successful upgrades is potentially expedited and the right amount of time for necessary adjustments can be allocated. The Vets API components that require testing are below, along with the potential automation strategies. The objective is to standardize testing methodologies across the platform, thereby eliminating the inconsistency of testing solutions across EKS applications.

Part Six of Testing plan - Sidekiq Functionality

**Tasks**
- [x] Find a basic Sidekiq job to use for testing
- [x] Create Datadog monitor to check for errors on sidekiq startup on the new cluster. 
- [x] Document the steps that will need to be followed by the person doing the upgrade testing [in this Confluence document](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3127246924/Steps+for+EKS+Upgrade+Test).

**Success Metrics**
- [x] Sidekiq functionality is tested and it runs
- [x] Confluence doc is updated

**Acceptance Criteria**
- [x] Sidekiq functionality is comprehensively tested during the upgrade. 
- [x] The documentation is updated with the necessary steps and instructions for this step.

### Validation
- [ ] Review the new monitor: https://vagov.ddog-gov.com/monitors/284651 (not added to Terraform)
- [ ] Review step 6 of the documentation: https://vfs.atlassian.net/wiki/spaces/PPT/pages/3127246924/Steps+for+EKS+Upgrade+Test#6.-Sidekiq-Functionality

**Comment by jennb33** [comment]
10/2/2024 update: @rmtolmach has some questions for Lindsey (from Friday 9/27pm). She would like to talk this through, as it feels like we have enough monitors in place currently that would alert us if there was an issue with Sidekiq. Is this ticket still relevant?

**Comment by jennb33** [comment]
10/3/2024 update: @rmtolmach met with @rjohnson2011 and @flooose on 10/2, strategy will be to take Sidekiq down in dev to verify that the monitors are working.

**Comment by rmtolmach** [comment]
I ran a test today by taking down sidekiq (in dev) in this PR: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3135. The following errors occurred: 
- [Pods are down...kube_deployment:vets-api-sidekiq](https://dsva.slack.com/archives/C24RH0W11/p1727983330278289)
- [Platform - ArgoCD: App Degraded](https://dsva.slack.com/archives/C039HRTHXDH/p1727983236077759)

Rachal suggested adding [this line](https://github.com/department-of-veterans-affairs/vets-api/commit/365f4d65ef4c8d6a935129b19129bd0538f29025) to the sidekiq initializer and then adding a log monitor for the error string we get when sidekiq redis is _not_ up. Lindsey agrees that's a good idea, so I will do that tomorrow.

**Comment by rmtolmach** [comment]
- PR merged https://github.com/department-of-veterans-affairs/vets-api/pull/18750
- Monitor created in DD UI: https://vagov.ddog-gov.com/monitors/284651
- Documentation updated: https://vfs.atlassian.net/wiki/spaces/PPT/pages/3127246924/Steps+for+EKS+Upgrade+Test#6.-Sidekiq-Functionality

**Comment by jennb33** [comment]
10/7/2024 update: @rjohnson2011 will review this

**Comment by rjohnson2011** [comment]
PR and new DD monitor look great. Ready to close!

**Comment by jennb33** [comment]
10/7/2024 update: ticket closed
