### ISSUE TITLE
Discovery around GH actions auto populate column in GH projects board for PO Sync

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#93583]
## User Story
As a Governance team member, I want to be able to easily see in the Collab Cycle Reviews GH Projects board if a VFS team participated in a PO Sync so that I can know if it's ok to move forward with a previously scheduled touchpoint.

Assignee: @it-harrison 
Peer Reviewer: @KKitagawa-Bosch 

## Description
Both OCTO-DE Design PA leads and Governance team need to be able to easily see if a VFS team has completed the PO Sync touchpoint. However, since this is an OCTO only touchpoint, Governance will not easily see/know when a PO Sync occurred (like they do with a DI, MPR or SR). OCT-DE Design PA Leads do have an action to add the `PO-Sync-approved` label to the Collaboration Cycle Request ticket post-PO Sync, however the built-in automations in GitHub projects do not allow for a field to be populated based on whether or not a label exists or not.

The purpose of this ticket is to add a new GH actions script to the [Collaboration Cycle Reviews gh projects board ](https://github.com/orgs/department-of-veterans-affairs/projects/998/views/1?visibleFields=%5B%22Title%22%2C%22Status%22%2C124265769%2C124265843%2C124265868%2C%22Milestone%22%2C%22Assignees%22%2C%22Labels%22%2C129286631%2C134533290%2C130664846%5D)that would auto populate a new field in the board to make it easy for all to see that the PO sync occurred and was approved.

Note: Eric Boehs shared a script he wrote with the #github-projects-cop channel that may be helpful. [Check it out!](https://dsva.slack.com/archives/C07H8R1PTGX/p1727191765231639)

### Live pages
- 

### Drafted pages
- 

## Tasks
- [ ] After doing initial discovery, contact Shira if there are limitations and/or restrictions to completing this ticket

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We had a new column in the Collab Cycle Reviews GH projects board that specifies whether the PO sync occurred and if it was approved.

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
I have verified locally that this is doable - I have also added an action to the repo; however, the permissions generated for the GITHUB_TOKEN during the workflow run are not sufficient to modify a project (whereas my personal token is); I am working with support to increase permissions.

**Comment by it-harrison** [comment]
@KKitagawa-Bosch check out the [action](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/gov-team-po-sync.yml) and the [script the action calls](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/scripts/github-actions/po-sync.js)

**Comment by shiragoodman** [comment]
Due to @it-harrison 's comments above, this work will be moving into the next sprint.

**Comment by shiragoodman** [comment]
@it-harrison what is the update on this? I saw on Friday's Slack up that you're still working on "continued negotiations to add token to va.gov-team repo" - is this still accurate? Is there anything I can do to help expedite this?

**Comment by it-harrison** [comment]
@shiragoodman I have gotten a Distribution Group and Email Permissions for the group (meaning we have governanceteam@va.gov email address) but I need to get access to the account so I can verify adding an account for this address on GitHub. I am in conversation with some one through "YourIt".

**Comment by it-harrison** [comment]
The distribution group email is waiting to receive the ability to receive third-party emails, which is necessary to create an account with Github; once this is accomplished it should be possible to add the custom token to the repo.

**Comment by it-harrison** [comment]
@KKitagawa-Bosch This is ready for review. 
* [workflow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/gov-team-po-sync.yml)
* [script the workflow calls](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/scripts/github-actions/po-sync.js)
To test:
* add the `PO-Sync-approved` label to this [dummy ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96097)
* verify that `Approved` appears in the `PO Sync` column of our [Project Board](https://github.com/orgs/department-of-veterans-affairs/projects/998/views/1) in row 202, for the dummy ticket (at the bottom of the Table)

**Comment by it-harrison** [comment]
@shiragoodman the current admins for the `va.gov-team` repo are [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/24497#issuecomment-2440050959).

**Comment by KKitagawa-Bosch** [comment]
@it-harrison "po-sync-approved" is appearing in the labels column, but "approved" is not appearing in the po-sync column

**Comment by it-harrison** [comment]
@KKitagawa-Bosch I think it is working. You may have checked too soon -- the action takes about 2.5 minutes to run. When I tried it this is what happened:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmFHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2da7d90360641931deb1f973ed007566f6f3f9d/po-sync.mov)

**Comment by KKitagawa-Bosch** [comment]
Did a retest and it worked!
