### ISSUE TITLE
Burials | datadog monitors clean-up

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#93599]
# Overview
The burials monitors are inconsistently named and in some cases don't seem to be correct.

https://vagov.ddog-gov.com/monitors/manage?q=team%3Abenefits%20service%3A%22burial-application%22&order=desc

# Tasks
- [x] Clean up the monitor names so that they are consistently named. 
- [x] Check each monitor for correct metric/log query
- [x] One of the monitors is in error and disabled.  I think this one can be deleted, but review and confirm. _not our group_
- [x] Can the monitor for ClaimsApi::ClaimEstablisher be deleted? _No - updated description and applied correct tag_

Naming convention:
`Benefits <form_id> <form name> <type> <controller/job> <event> <method>
`
e.g.
```
Benefits 21P-527 Pension Metric SideKiq exhausted count
Benefits 21P-527 Pension Metric Pension_claims 422/500 errors count
Benefits 21P-527 Pension Logs Pension_claims Status:!200 >20%
```

**Comment by wayne-weibel** [comment]
https://dsva.slack.com/archives/C053U7BUT27/p1727294692767399
