### ISSUE TITLE
Redis POAM: TTL monitoring

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#93606]
## User Story
As the managers and developers for the VA Platform, 
We need to further understand the TTLs that are at -1, 
So that we can minimize the unnecessary persistence of bad data in Redis. 

## Issue Description
@Kshitiz-devops brought the TTL issue to the team, via [this Slack message](https://dsva.slack.com/archives/CE4304QPK/p1727205902397569). He will be reviewing this issue and reaching out to teams that have TTLs that have the -1 setting to better understand why these are set to that level. 

## Tasks
- [ ] Reviewing the teams with TTLs (time to live) that are set to -1 to understand why they have assigned that number
- [ ] Document what is learned about the TTLs
- [ ] Link documentation here

## Success Metrics
We will have a better understanding of the TTLs, and ideally can correct the -1 settings in order to eliminate the unnecessary persistence of bad data in Redis. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

![Image](https://github.com/user-attachments/assets/fde8a537-5935-455a-aa2b-63523a781500)
![Image](https://github.com/user-attachments/assets/79ab8353-a271-4c91-85db-4a19d069335f)
![Image](https://github.com/user-attachments/assets/fbc3579c-dcf2-442a-baf8-a41889bfa6e4)
![Image](https://github.com/user-attachments/assets/d01f22c2-7455-4b6c-98c6-ab1632da3340)

**Comment by jennb33** [comment]
9/26/2024 - @Kshitiz-devops was able to supply the metadata, plan is to push use of the name spacing pattern once all the keys have been identified.

**Comment by jennb33** [comment]
9/30/2024 updates: @Kshitiz-devops reports that this work is almost complete. Other teams are making those adjustments. We have found a few teams that haven't responded

**Comment by jennb33** [comment]
10/7/2024 update: may be able to close this ticket on Tuesday, as there have not been any instances lately since it was brought to other team's attention.

**Comment by jennb33** [comment]
10/8/2024 update: Work is complete per @Kshitiz-devops and this ticket can be closed.
