### ISSUE TITLE
Ensure that the right confirmation page is being displayed in various submission scenarios

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#93603]
## Issue Description
As a Veteran, when I submit my application I want to see a confirmation page that accurately describes the confirmation scenario and if something goes wrong I want to know about it.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] When the Veteran views the confirmation page after submitting their application, the message is accurate relative to the Veteran's submission state (success, fail, etc.)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
