### ISSUE TITLE
BE | Auth Experience | Monitoring | Update Datadog Teams and Tags

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#93609]
## Background
We have a teams named `VFS Auth Experience Profile & My VA` with an `auth-experience-profile` tag.  This tag isn't named correctly based on the name of the team.  

**Questions**

- Should we rename the `VFS Auth Experience Profile & My VA` and make it specific to Profile?  Or should we keep the name, but update the tag to be less Profile specific; something like `auth-experience`. 
 
## Tasks
- [x] Determine if we need 1 or 2 teams for Auth Experience.
- [x] Open a ticket to make the changes.

## Acceptance Criteria
- [ ] The team changes are made in DD with the appropriate supporting tags and services.

**Comment by ACParker89** [comment]
@tpharrison will open a support ticket and then we will determine next steps

**Comment by tpharrison** [comment]
Opened Platform Support ticket on Sep 25th - https://dsva.slack.com/archives/CBU0KDSB1/p1727288642641199.
