### ISSUE TITLE
Define our plan for Diary study

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#93602]
## User Story
As a Governance team member supporting the Collaboration Cycle, I want to define our plan for the Diary study with regards to including Mobile App in Collab Cycle so that my team can document and implement a plan for getting our process, standards and knowledge updated.

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @briandeconinck 

## Description
In ticket #87330, Governance defined a high level [research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3436871682/2024-09+Research+plan+for+folding+mobile+app+into+the+Collaboration+Cycle) for how we will determine what the Governance Team needs to know in order to include the mobile app in the Collab Cycle. The Research Plan included 2 approaches - a Cognitive Walkthrough and a Diary study. 

The purpose of this ticket is define our plan for the Diary study. What are the specifics of our research approach? How will we go about completing our diary study? The Platform Research - [Conversation Guide template](https://vfs.atlassian.net/wiki/spaces/DCP/pages/1474494518/TEMPLATE+Platform+Conversation+Guide) may be a helpful resource in completing this ticket.

### Live pages
- 

### Drafted pages
[- Diary Study Research Plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3524820993/2024-10+Research+Plan+for+Governance+Team+Adding+Mobile+App+to+the+Collaboration+Cycle+Diary+Study)

## Tasks
- [x] Define the specifics of our Diary Study research approach
- [x] Consult with @naomimarcussen if you have any questions or would like to discuss ideas
- [x] Please be sure to save your plan in the Governance/Research space on Confluence (should be a child page of the research plan)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance has a defined plan for completing the Diary Study approach for bringing mobile app into the Collaboration Cycle

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@KKitagawa-Bosch please read through this ticket and lmk if you have any questions. ty!

**Comment by KKitagawa-Bosch** [comment]
In progress! Sorry, forgot to move it in zenhub. Pretty much done with the "discovery" phase, writing up a plan today/tomorrow

**Comment by KKitagawa-Bosch** [comment]
@briandeconinck @shiragoodman draft of the methodology is ready for review in [Confluence](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3524820993/2024-10+Research+Plan+for+Governance+Team+Adding+Mobile+App+to+the+Collaboration+Cycle+Diary+Study)

A thought: do we want to create child pages for each practice area to document their diary entries in confluence? Or is there a better place to store those entries?

**Comment by briandeconinck** [comment]
@KKitagawa-Bosch I think that all makes sense! And unless Shira suggests otherwise I think a child page for each practice area in Confluence makes sense too.

**Comment by shiragoodman** [comment]
also @KKitagawa-Bosch re the child pages for each practice area, could you get those set up now so that it's easy for Governance team members to document their observations when the study begins? ty!

**Comment by KKitagawa-Bosch** [comment]
@shiragoodman made those edits to the page and launching the child pages now!

**Comment by briandeconinck** [comment]
Updates look good! And those resources about diary studies that you linked to are great, thank you!

I think this is ready to close.
