### ISSUE TITLE
MVP Upstream Services - Crosswalk Upstream Services documents

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#93600]
## User Story
As the Managers and Developers of the Platform,
We need to crosswalk Upstream Services documentation,
So that there is consistent information collected for these services and it is documented in a consistent way for future work.

## Issue Description
This work started with [89190](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89190) and will continue into Sprint 11 to ensure that Service Classes, FWDProxy and any other resources about upstream services are gathered and level-set. 

Refer to: 
- [Systems Connections](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3393552723/System+Interconnections) (from Security team; fill in empty spaces as able)
- [Upstream services](https://docs.google.com/spreadsheets/d/12Qt19KwWCPBmSeTzx-e_OfErqni_HESb71x_2Gsw3OE/edit?gid=1050925785#gid=1050925785) description document 
- [External Services Integration](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations)

## Tasks
- [x] Review Service Classes
- [x] Review External service sources ([here](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations))
- [ ] Review FWD Proxy for external services

## Success Metrics
All documentation (systems connections, upstream services and External Services integration) is consistent across each of them. 

## Acceptance Criteria
- [x] Consistent list of upstream services and their associated attributes. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
10/2/2024 updates: Ryan has been adding to the current doc but keeping it in draft form. This ticket should be closed by the end of the day.

**Comment by rjohnson2011** [comment]
These are the services I've found that are not reflected in our external services list. I don't believe any are upstream services - rather external (Salesforce, Slack) or internal (within vets-api repo). 

```
BIP Claims Service
Central Mail Service
CHIP 
Decision Review Service
eFolder Service
Form1010 Service
IAM SSOE OAuth Service
IHUB Service 
LGY Service
MAP (Medical Appointment Platform) Services
Preneeds Service
RES Service
Salesforce Service
Slack Service
VeText Service
VRE (Veteran Readiness and Employment) Service
```
