### ISSUE TITLE
Add webpack bundle analyzer to vets-website

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#93610]
## Issue Description
To target specific performance improvement opportunities on vets-website, we want to use [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer). This will spotlight where our biggest performance drags are coming from. The package will need to be installed and then run to generate the graph.

---
## Tasks
- [x] Install webpack-bundle-analyzer
- [x] Run webpack-bundle-analyzer

## Acceptance Criteria
- [x] Webpack bundle analyzer can be used to get performance information about our apps.
