### ISSUE TITLE
Ongoing Work -- GA4 Property Audit Cont.

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#93612]
### Description
 This ticket is to account for the work that we are doing for our audit of our Google Analytics 4 Property and BigQuery.

---

### Tasks

- [x] Continue audit of Google Analytics 4 Property
- [x] Use MS Teams to communicate specifics,
- [x] Provide regular updates to stakeholders in Slack.
- [x] Log findings in postmortem

### Acceptance Criteria

- [x] Findings from audit have been shared in private Slack message.
- [x] Findings and outcome have been logged in postmortem.

**Comment by johnny-jesensky-adhoc** [comment]
Our audit work for our GA4 Properties is mostly finalized, though there were still be some on-going tasks that will be outlined in a separate ticket.

With Jamie OOO for most of this week -- moving this task to _Done_.

FYI @jestutt
