### ISSUE TITLE
BE | Auth Experience | Monitoring | No Silent Error Report

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#93613]
## Background

The authentication experience teams have been asked to assess their level of compliance with the requirements. Each team will be assessed on whether they have met the requirement or not, with documentation provided if necessary.

More background [can be found here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md).

The following checklist is related to the checklist found in the No Silent Errors guidance document (linked above):

## Tasks
| **Area**             | **Requirement**                                              | **Documented** |
| -------------------- | ------------------------------------------------------------ | -------------- |
| **Documentation**    | Do you have a diagram of the submission path that user data your application accepts takes to reach a system of record?  | Done            |
|                      | Do you understand how the error is handled when each system in the submission path fails, is down for maintenance, or is completely down?  | Done            |
|                      | Has the owner of the system of record receiving the user's data indicated in writing that their system notifies or resolves 100% of fatal errors?  | Done           |
| **Monitoring**       | Do you monitor the API that you submit to via Datadog?   | Done            |
|                      | Does your Datadog monitoring follow the appropriate tagging standards?  | Done          |
|                      | Do errors detected by Datadog go into a Slack notifications channel?  | Done           |
|                      | Does more than one person monitor the Slack notifications channel?  | Done          |
|                      | Do the team members monitoring the Slack channel have a system for acknowledging and responding to error notifications (on-call rotation)? | Done          |
| **Reporting Errors** | Have you filed issues for errors that are appearing in Datadog / Slack? | Done          |
|                      | Do all fatal errors thrown in your application end up visible to the end user either in the user interface or via email? | Done          |
| **User experience**  | Do you capture all of the potential points of failure and make those errors known to the user via email notification and/or through the application?  | Done        |

## Acceptance Criteria

- [x] Touch-base review on Monday, Sep 30th.
- [x] Create a document that covers which requirements are being met and which are not.
- [x] Review document with team.

**Comment by tpharrison** [comment]
@twoangstroms Let's meet and discuss further.

@ACParker89 Can we close this ticket out and create a new for the User flow diagrams?  This ticket was only intended to ensure we addressed everything in our summary report.
