### ISSUE TITLE
10-10EZ & 10-10CG - BUG: Add keys to redis.yml file

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93615]
## Background
A member of the Platform Product team (DevOps) informed VFS teams of some Redis keys that are not defined in the `redis.yml` configuration file of the vets-api repo.  They also have a TTL (Time to live) of -1, which makes them persist indefinitely in the Redis store.  

After a preliminary review, our teammate found that the keys our forms (EZ and CG) are using should have an appropriate TTL defined in the `redis.yml`.  Review the Slack Conversation below for more details.

### Resources
<details>
<Summary>Slack conversation - Expand to view</Summary>

>- **From Kshitiz Shrestha**
We have noticed some Redis keys that are not defined in the redis.yml configuration file of the vets-api repository. Additionally, these keys have a TTL (Time to Live) of -1, meaning they are persisting indefinitely in the Redis store.
We would like your assistance in identifying where these keys are being set or defined within the vets-api codebase. Moreover, we are trying to understand why the TTL for these keys is set to -1, as this could lead to unnecessary persistence of data in Redis.
Could you please provide guidance on where these keys are located and the reasoning behind the TTL configuration?
Your help in resolving this matter is much appreciated.

>- **Brandon Cooper**
>Just to clarify on two of those keys, are they `Form1010cg:*` or is that from a search where it is a key that starts with `Form1010cg:` and has the wildcard at the end for other values? The same question for the `HCA:*` key. Additionally, what is the `(2700)` with the key? Is that the value? Just making sure I understand what all I should be looking for.

>- **Lindsey Hattamer**
I believe that's a wildcard character :this: but I will let Kshitiz confirm

>- **Brandon Cooper**
Thanks! If that is the case, my guess is those two keys come from [here](https://github.com/department-of-veterans-affairs/vets-api/blob/91e46fbe4c995629d7b4df7a33c983975abb2ca9/app/sidekiq/form1010cg/submission_job.rb#L55)  and [here](https://github.com/department-of-veterans-affairs/vets-api/blob/91e46fbe4c995629d7b4df7a33c983975abb2ca9/app/sidekiq/hca/log_email_diff_job.rb#L29). Those look like a redis key is being set that starts with `HCA` and `Form1010cg`. I tested it locally on the spec, but it looks like when you call `redis.set` without defining a `ttl` it defaults to `-1`, which is probably why we have these keys with -1 set. [It looks like we call redis.set a few places in vets-api so these may be where the others are coming from](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvets-api+redis.set&type=code).

>- **Lindsey Hattamer**
> Thank you for the link :this: This is really helpful because we assumed that most folks just followed the [namespaced redis pattern](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-guide-caching-with-redis-namespace-in-vets-)
>
> For the keys that belong to your team, is a -1 TTL appropriate? It seems like we would want a TTL for those keys

>- **Brandon Cooper**
Yeah, I agree. I'll have to do a little more digging into it, but I don't think `-1` is necessary for these. They're both used in sidekiq jobs so they should expire at some point for sure.
>
> So for those two keys, it looks like I should add them to the redis.yml file as per the documentation to avoid key collisions/this issue in the future?

>- **Lindsey Hattamer**
Yeah exactly. The namespacing (through the `redis-namespace`) gem helps us to avoid the key collisions

>- **Kshitiz Shrestha**
Form1010cg and HCA is namespace for the key. 2700 in the parenthesis is the number of keys with TTL -1.

</details>

## Tasks
- [x] Review the Slack conversation
- [ ] Implement the redis keys per the [platform documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-guide-caching-with-redis-namespace-in-vets-), ensuring to set TTL's for both the EZ and CG keys within the the `redis.yml` configuration file of the vets-api repo. 
- [x] Review with Engineer teammates for peer review and any questions

## Acceptance Criteria
- Any redis keys used by the 10-10 team will utilize the `redis-namespace` gem and follow all expected implementation norms.
- Any existing implementations of the redis keys that are deemed as an inappropriate use of redis should either be refactored or tickets created to implement them in a different way.

**Comment by coope93** [comment]
The `Form1010cg` redis key was removed in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18699) to utilize the `retry_monitoring` middleware instead of a redis key. The `HCA::LogEmailDiffJob` redis key will need another ticket to reimplement the job and statsD value because that value will most likely needed persisted in perpetuity, most likely in a new database table or similar.

**Comment by coope93** [comment]
I created https://github.com/department-of-veterans-affairs/va.gov-team/issues/94285 for updating the `HCA::LogEmailDiffJob`.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the metrics are incrementing as expected
