### ISSUE TITLE
VSO Rep locations aren't behaving as expected

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#93624]
## Expected 
Searching for a VSO Rep by location and name will bring that person up in the Find a Rep search results.

Working as expected for a VSO Rep in New Jersey with name Sonya Bulluck:
<img width="931" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9BQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a6453f18e44460ac8ebe1c266c717e06b318a34/image.png" alt="image.png" />

## Actual
Some VSO Reps aren't coming up when you search for their location and name.

1. Carolyn Burns in Vineland, NJ
2. Diana Pitman in Vineland, NJ (Diana has the same address as Carolyn)
3. Darrell Whitman in Sacaton, AZ

## Steps to Reproduce

Using Carolyn Burns in Vineland, NJ as an example: 

1. Enter "New Jersey" or "NJ" or "08362" in the location field
2. Enter "Carolyn Burns" in the name field
3. Search with the default 50 miles
4. No results
<img width="937" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a52b2d671196879ba09f04a68eaa6f0626d5f75e/image.png" alt="image.png" />

5. Increase search radius to "Show all" 
6. Rep is visible, but the distance is unexpectedly large placing them at the very bottom of the search results. This has me suspecting that we're not pulling in the location correctly.

<img width="663" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54d32e0930725be24d6ece3d9a09550aa8688ffe/image.png" alt="image.png" />

## Tasks
- [ ] Investigate and understand the impact (how many reps are affected)
- [ ] Propose a solution and estimated effort to complete
- [ ] _Depending on the impact and scope of the solution_ Implement a fix

**Comment by oddball-lindsay** [comment]
Update: I noticed that the Trexler File will remove the zero, if the zip code starts with a zero. This would cause the zip code to no longer be valid and I'm suspecting this is what's causing the buggy experience.

Why is Sonya Bulluck serving up okay if her zip code also starts with a 0? I'm guessing that this is because we're only updating representatives when their information has changed and perhaps Sonya's information hasn't changed recently.

**Comment by oddball-lindsay** [comment]
The new Trexler File has fixed the issue with zeros being dropped from zip codes and it has been processed. Unfortunately, I'm still seeing weird location behavior for these representatives so the bug is not resolved.

Curious at this point to get dev input to learn more about what is going on here.

**Comment by oddball-lindsay** [comment]
Possibly affected by the Lighthouse address validation, or even the Mapbox service we're using for location.

**Comment by jvcAdHoc** [comment]
There are 657 `veteran_representatives` records with lat and long set to 0. The `Carolyn Burns` example is one of them. I'd guess that when the address validation api is uncertain about coordinates that it sends back 0s as default values. I'll ask around to confirm. I couldn't find the answer in their documentation.

**Comment by jvcAdHoc** [comment]
I looked at a random set of 30 and all 30 were PO Box addresses

**Comment by jvcAdHoc** [comment]
![Image](https://github.com/user-attachments/assets/f558d714-f739-4fcc-bbac-18326a273969)

**Comment by jvcAdHoc** [comment]
A warning message:
![Image](https://github.com/user-attachments/assets/13bd0b33-eedc-44ea-8725-ea073830d71a)

**Comment by oddball-lindsay** [comment]
Thanks for sharing this, Jon! 657 records is quite a lot.

Are there any clues as to why the lat/long isn't set to 0 for Sonya Bulluck, who also has a PO Box address?

![Image](https://github.com/user-attachments/assets/3af1f101-9ce4-40b5-aa21-1aefee044839)

**Comment by jvcAdHoc** [comment]
![Image](https://github.com/user-attachments/assets/df23b409-6611-44dd-84b6-a7d4d771c436)

In the addresses from GCLAWS: 
- 3322 College Dr
	- had address 1 data: `3322 College Drive`
	- had address 2 data: `PO Bos 1500`
- P.O. Box 31003 
	- had a mixed address 1: `FDVA PO Box 31003`
	- the address validator came back with zip code `33733`, but GCLAWS had `33731`
- P.O. Box 6000
	- only had the P.O. box in address 1
	- no address 2

My best guess is a few things could be at play here:
- poor data quality (e.g. mismatched zip codes)
- the address validator struggles with addresses that mix a street address and a P.O. box
  - there are 650 records with 0 lat and 0 long as of today 
  - 541 records with 0 lat, 0 long, "box" as part of the  address 1 string, and a non-nil address 2
  - 59 records with 0 lat, 0 long, "box" as part of the  address 2 string, and a non-nil address 1

**Comment by jvcAdHoc** [comment]
Suggestions:
1. If the address validator responds with a warning and/or 0 for lat + long, then we consider the address invalid
2. Retry validation:
  i. First with address 2 set to nil
  ii. If i. fails and there is a non-nil address 2, try with address 2 set to address 1
  iii. if ii. fails and there is a non-nil address 3, try with address 3 set to address 1
  iv. If i-iii. fail, consider the address as invalid

Unfortunately the address validator must have at least one of address 1, 2, and 3 to work:
![Image](https://github.com/user-attachments/assets/dbe0a827-8500-401d-a507-e41c3a9becb1)

**Comment by jvcAdHoc** [comment]
2. would at least give an attempt at keeping those 650 in FAR

**Comment by oddball-lindsay** [comment]
Thanks so much for all of this @jvcAdHoc it's really helpful to know the failure rate and I really appreciate the solution that you proposed; it makes sense to me. 

I'd like to move forward with the solution because that's a significant amount of reps that we can surface in Find to bring more help to Veterans. And I think it'd be helpful to set up a Datadog monitor for when an address is invalid and/or the lat long is set to 0 so we can keep an eye on this situation, but that can be in our backlog for now and we can tackle after Appoint MVP. 

@holdenhinkle what do you think of my thoughts above, as well as Jon's proposed solution? 

-------

By the way @jvcAdHoc, is that address 2 `PO Bos` a typo in your [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93624#issuecomment-2397638745), or in the GCLAWS database?
> - 3322 College Dr
>    - had address 1 data: `3322 College Drive`
>    - had address 2 data: `PO Bos 1500`

**Comment by jvcAdHoc** [comment]
@oddball-lindsay good catch, that's a typo

**Comment by holdenhinkle** [comment]
Cool, thanks. This seems like a good approach. Go go it!

**Comment by oddball-lindsay** [comment]
@jvcAdHoc Jen gave the okay to move forward with the solution ([Slack convo](https://dsva.slack.com/archives/C05L6HSJLHM/p1728413001163369)) and I imagine that increases the scope of this ticket. What should we bump the estimate up to, with the fix in mind?

**Comment by jvcAdHoc** [comment]
@oddball-lindsay could we close this ticket and make a new one for the fix? I'd estimate the fix as a 3.

**Comment by oddball-lindsay** [comment]
Makes sense! Fix is in the ticket referenced above, going to close this out.
