### ISSUE TITLE
[Research] Set up unmoderated survey for "see staff after check-in"

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#93639]
## Background
In #93025, we determined that an unmoderated survey can help us glean more information around Veterans' experience checking in while testing if Veterans will notice and understand the updates added to the sign-in page and confirmation page telling them to see a staff member after completing online Check-in.

## Tasks
- [ ] Setup unmoderated survey in Optimal Workshop based on the the outline in #93025
- [ ] Add any questions based on the in-person research plan and conversation guide
- [ ] Review with UX and Kristen

## AC
- [ ] Survey set up Optimal workshop 
- [ ] Survey reviewed by UX and Kristen

**Comment by benbrasso-agile6** [comment]
@cgednalske can @zach-park shadow on this ticket during the set up?

**Comment by zach-park** [comment]
@cgednalske , Pages (1, 2, and 3) are inserted into the optimal workshop survey. Please note that Page 1 will be updated upon finalizing the wireframe. (Cc: @benbrasso-agile6 )

**Comment by cgednalske** [comment]
@zach-park nice! Looks like you have two versions (1 with the header and footer and 1 without). We can definitely go with the version that does NOT includes the VA header/footer because the second version is much easier to take in for the purposes of the survey.

**Comment by zach-park** [comment]
> [@zach-park](https://github.com/zach-park) nice! Looks like you have two versions (1 with the header and footer and 1 without). We can definitely go with the version that does NOT includes the VA header/footer because the second version is much easier to take in for the purposes of the survey.

Hi @cgednalske (Cc: @benbrasso-agile6 ), I updated the wireframe images with the latest with Laura's feedback. I also uploaded the the wireframe image for the A/B testng so you can find it in the image section.

**Comment by zach-park** [comment]
Looks great! Thank you!

**Comment by cgednalske** [comment]
@zach-park Version 2 study is also ready - in the same folder for Check in with staff after eCheck-in, so you can add the V2 images to that one.

**Comment by zach-park** [comment]
@cgednalske , the version 2 is now updated with the alternative page 1 wireframe and ready for validation. Thank you!

**Comment by benbrasso-agile6** [comment]
For version 1; couple comments @zach-park @cgednalske 

- On the Welcome screen, it's a bit hard to decipher bold vs. not when it's within a sentence. Consider (not must) not mixing bold and normal in the same paragraph. 
- On the Instructions screen, I might choose to replace "related" with "corresponding" in Part 2. 
- Question 1: I might recommend adding a duration. E.g., have you used online check-in within the last 6 months? Might be a better indicator if they're familiar with PCI. 
- Question 2: Should 5 be "very positive". Seems like the order should be flipped. Maybe flip for all quantitative questions. 
- There's no conditional set up for, if I answer "No," I'm still asked to answer how check-in was. Seems like something we need to account for differently. 
- Question 4: Seems like a trick question. Online check-in doesn't require staff intervention. I think you need to first ask if Veterans interacted with staff before, during, or after online check-in. Then, if so, what information did staff need or provide support for?  
- Question 5: What if I didn't interact with staff? Why am I required to answer this question? I would get stuck an exit out at this point. 
- Question 9: Instead of friend or family member, I would keep it to ".. to other Veterans." 

Once I got going past Part 1, it was great!

**Comment by cgednalske** [comment]
Sounds good! Will definitely look into and update those 👍 Thanks!

**Comment by cgednalske** [comment]
So the one I'm not sure I agree with is the "last 6 months." We just want feedback about eCheck-in (both good and bad), including if someone used it, but then decided to stop for whatever reason. So it seems like whether they've used it overall gets at that better, whereas last 6 months is more likely to lean towards repeat users. 

The conditional for if someone says no to that sounds good 👍  - totally forgot about that. And really what this question is is a double check that the recruitment criteria is met. So if they say no, it will skip the rest of Part 1 entirely.

**Comment by benbrasso-agile6** [comment]
Yep, yep. Sounds good.

**Comment by benbrasso-agile6** [comment]
@zach-park @cgednalske version 2 looks good. 

Question: since we have two versions, is there a confirmation page variation we want to also test in version 2? If not, that's ok. 

I think Kristen will like this study overall.

**Comment by cgednalske** [comment]
Nope - just the one! I don't think there was any uncertainty around that one (including Laura's feedback).

**Comment by cgednalske** [comment]
@benbrasso-agile6 

> Question 4: Seems like a trick question. Online check-in doesn't require staff intervention. I think you need to first ask if Veterans interacted with staff before, during, or after online check-in. Then, if so, what information did staff need or provide support for?
> Question 5: What if I didn't interact with staff? Why am I required to answer this question? I would get stuck an exit out at this point.

You're right those are a little confusing. Because the point of the questions is mostly "did you have to interact with staff (at any point)? And how did that go?" I've changed the two questions to the following. How do these sound? 

- Have you ever needed to ask staff for assistance before, during, or after checking in online check-in?
- Tell us about your experience asking staff for assistance before, during, or after checking in online.

**Comment by cgednalske** [comment]
Oh wait - re the confirmation page, what happened to the body text there? I didn't think we were taking out the part that said they're checked in online  👀  @zach-park 

@benbrasso-agile6 I'm guessing that's why you were asking about versions?

**Comment by benbrasso-agile6** [comment]
I sort of remembered that area below the h1, yeah.

**Comment by zach-park** [comment]
> Oh wait - re the confirmation page, what happened to the body text there that was below the H1? I didn't think we were taking out the part that said they're checked in online 👀 [@zach-park](https://github.com/zach-park)
> 
> [@benbrasso-agile6](https://github.com/benbrasso-agile6) I'm guessing that's why you were asking about versions?
> 
> **_Update:_** [@zach-park](https://github.com/zach-park) I added a comment on the confirmation page in Figma for you to take a look and make sure they're the same. The Figma version has the body text, but the version in the surveys does not.

Apologies, an oversight. I updated the wire and the screenshot in the survey with the correct one (with body text).

**Comment by cgednalske** [comment]
Yay - everything looks accurate now 🎉  I think we can close this and then we'll get and implement feedback as we run the "pilot" (aka have Kristen and other folks try it out)

**Comment by cgednalske** [comment]
Thanks for all the great feedback on Part 1 @benbrasso-agile6! It's a lot smoother now.
