### ISSUE TITLE
[Design] Create Wireflows for 'Debt Letters MVP' 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#9363]
## Issue Description
_Once the team participates in the ideation/brainstorming session and finalizes the 'Debt Letters MVP''s features for MVP, the design team will take everyone's ideas and create wireflows. These wireflows will be reviewed with the team and stakeholders and may be iterated on._

---
## Tasks
- [x] _Wireflows will be created in Miro/Mural capturing the required features for MVP and following VA's design system library components_
- [x] _Design team presents the wireflows to BaM2 team and stakeholders for feedback_
- [x] _If feedback needs to be incorporated, design team will create another ticket to capture that work_
- [x] _This iteration of the wireflows is documented in GH and linked to this ticket_

## Acceptance Criteria
- [x] _Wireflows are created in Mural/Miro based on ideation session_
- [x] _Wireflows have been presented to team/stakeholders_
- [x] _(Optional) If feedback needs to be incorporated, a ticket has been created to capture that work_
- [x] _Wireflows are documented in GH and linked to this ticket_

---

**Comment by rileyorr** [comment]
The [first iteration of the wireflows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/wireframes.md) have been uploaded to GH. We will be presenting them in the BaM2 team meeting today for feedback.

**Comment by rileyorr** [comment]
I've created a [ticket to incorporate feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9647) based on the team meeting, design intent check-in, and the meeting with the DMC SME's next week.
