### ISSUE TITLE
Start creating short presentation about experiment for IPT

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93630]
## Description 

October 3rd, present to IPT about how we're approaching the "check in with MSAs" experiment, and to get their feedback on current progress. 

At a high-level, outline could include: 

- [ ] Background and problem
- [x] Might want to squeeze in a highlevel blueprint to show that cell signal is an issue, which is why we moved to 45 mins. That has always been the problem that has remained unsolved. If it worked well, we could have kept eCheck-in how it was, and it would have worked for staff too. 
- [ ] Questions we're looking to answer
- [ ] Research approach, e.g., two methodologies
- [ ] Wireframes (low-fi)
- [ ] Might need a quick service map to show where VistA gets updated and where staff take actions
- [ ] How we'll track success
- [ ] Risks with this approach: don't know if we can toggle updating echeckin status on/off per facility, larger level of effort to turn this feature off and still have demos go through (e.g., longer to actually test something and get feedback), will require front and back of house training
- [ ] Show Fallback solution(s), if those are concerns by IPT: 1) keep eCheck-in updating appt status in VistA, or 2) no eCheck-in, rebrand eCheck-in to pre-check-in, but only if demos need to be reviewed, and turn on BT VistA app

Maybe no more than 15 slides. 

## Tasks

- [ ] Create presentation for IPT

**Comment by benbrasso-agile6** [comment]
@cgednalske I just added one bullet, re: service map. We'll figure out. Either wireframes with some annotations or maybe separate slides for Vet-facing wireframes vs. service map of how things will work. E.g., it's prob a simpler version of https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696788763395/d3aa60a7420ece422a6f6b84659c33350279b782?sender=u37bb983bd3fc3cc00c7d3286

**Comment by benbrasso-agile6** [comment]
@cgednalske made a few edits to the outline above

**Comment by benbrasso-agile6** [comment]
Added more detail to last bullet point above

**Comment by benbrasso-agile6** [comment]
I'm going to start looking at this today
