### ISSUE TITLE
Review of updated Q3 Survey

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#93649]
## Purpose
Step through the tasks to prep, launch, run, and synthesize the quarterly survey

## Tasks
- [x] Discuss alteratons/additions with Platform Leadership (clarity on Platform products/services)
- [x] Quick convo guide: Pilot new survey (ask around confusing questions/areas: what would be helpful?)
- [x] Pilot new survey

## Acceptance Criteria
- [x] Survey is shared w/ Leadership for sign-off
- [x] Survey has been piloted with a few VFS users
