### ISSUE TITLE
Deliver Endpoint for VA File Number to FE

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9365]
## Goal
We need the VA File number to go to FE so we can gate the form in the event that it is not in place and the Veteran can go get some help putting those in place.

## Tasks
- [x] Create route
- [x] Create Service
    - [x] Add tests
- [x] Create Controller
    - [x] Add tests
- [x] Add Serializer
- [x] Establish a connection to BGS using the Veterans SSN in a session object with a service (using `participant_id` currently, can use SSN if required)
  - [x] May need to update the BGS gem (Don't need to do this)
- [x] Return serialized payload received from BGS to frontend

## Acceptance Criteria
- [x] A PR is requested for merging

### Next step
- [ ] The FE is able to receive the serialized payload to pass into the gating operation

**Comment by digitaldrk** [comment]
People service returns the below values fyi incase we want to add more to Serializer:
```
{
  :brthdy_dt,
  :cmptny_decn_type_cd,
  :cmptny_decn_type_nm,
  :death_hist_ind,
  :email_addr,
  :fid_decn_categy_type_cd,
  :fid_decn_categy_type_nm,
  :file_nbr,
  :first_nm,
  :first_nm_key,
  :gender_cd,
  :ins_file_nbr,
  :last_nm,
  :last_nm_key,
  :middle_nm,
  :middle_nm_key,
  :mlty_person_ind,
  :ptcpnt_dto,
  :ptcpnt_id,
  :ssn_nbr,
  :ssn_vrfctn_status_type_cd,
  :station_of_jurisdiction,
  :svc_nbr,
  :termnl_digit_nbr,
  :vet_ind
}
```

**Comment by digitaldrk** [comment]
Yuuuge thanks to @kathleencrawford for her help getting this through.

## PR
https://github.com/department-of-veterans-affairs/vets-api/pull/4331

**Comment by digitaldrk** [comment]
@here this is a legit PR now

**Comment by jason-gcio** [comment]
cc: @cohnjesse
