### ISSUE TITLE
Create Vets::Response

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#93666]
Create a generic "Response" model that will be used as the base class for objectifying external api json responses

There is greater variety amongst "Response" models, and additional functionality may be required (ticket was updated from 1 point to a 2 point)
 
## Tasks
- [x] Create Vets::Response from Vets::Model
- [x] Test with a subclass of Common::Base
- [x] Test in place of a subclass of Common::Base

## Acceptance Criteria
- [x] Response can set/get attributes 
- [x] Response can serialize it's attributes
- [x] Response contains a status and a response body
- [x] Response can be subclassed easily
- [x] Response could be used directly 
- [x] Response can validate response json format

**Comment by stevenjcumming** [comment]
`Vets::Response` was used directly in place of `MebApi::DGI::Claimant::ClaimantResponse`

It required additional (however minor) updates the service, controller, and serializer

**Comment by stevenjcumming** [comment]
Vets::Response was used successfully as a subclass for `Apps::Responses::Response`

It didn't require changes outside of the subclass
