### ISSUE TITLE
Updates to Q&A section of main Yellow Ribbon page

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#9366]
## Issue Description
As a Veteran I want the most up to date information on specifics of the Yellow Ribbon Program.

Tammy sent some requested updates; Anne responded with some questions to clarify.

## Tasks
- [ ] _Anne to get feedback from Tammy to clarify edits to text. Anne - 5/19
- [ ] _Make updates to sections of page. Anne
- [ ] Copy edit and publish. Randi
- [ ] Send updated URL to Tammy to share with other stakeholders.

Page: https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/
