### ISSUE TITLE
ClamAV Temp File Conflicts

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#93665]
What details are necessary for understanding the specific work or request tracked by this issue?

We're encountering [issues with teams](https://dsva.slack.com/archives/CBU0KDSB1/p1727355068823809?thread_ts=1726848103.765629&cid=CBU0KDSB1) storing temp files in the ClamAV `app/clamav_tmp` directory, even when the files don’t need to be scanned (just stored temporarily). In this support case, the PDF is generated internally by Vets API and doesn't require scanning, it's just temporarily stored. I think we should consider using a separate directory for non scanned temporary files to avoid unnecessary interaction with ClamAV.

All files sent to Vets API should still be scanned, but separating concerns could help prevent issues, especially given the ephemeral nature of the shared volume due to pod scaling and/or termination. I explored some around using persistent volume claims, but I don't think that would solve the core issue, which relates more to pod lifecycles than file persistence. Even a PVC would go away if pods were terminated. I don’t think race conditions are a factor here either, as the file is only created and not scanned.

Any thoughts on this are appreciated, but initially, it seems best to have teams store non scanned temp files outside the shared ClamAV volume to see if this helps to solve the issue. I do think though that scaling and termination most likely plays a role here.

## Tasks
- [ ] Discover is pod scaling/termination is related to the errors being returned when accessing the tmp files
- [ ] Explore solutions such as a separate directory for non-scan files or using Persistent Volume Claims (PVC's)
- [ ] Identify any unnecessary interactions between Rails generated files and ClamAV
- [ ] Analyze the current process of storing temporary files in the shared ClamAV volume
- [ ] Ensure ClamAV can still access files that need to be scanned without conflict

## Acceptance Criteria
- [ ] Errors around accessing tmp files no longer exist
