### ISSUE TITLE
Address Remaining Payload Tasks

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9367]
## Goal
There are a few remaining tasks that need to be nailed down ahead of launching to production as far as what goes into the payload and how that data is structured.

## Tasks
- [x] Establish code for what to do with `marriage history`
  - Veteran marriage history
  - Spouse marriage history
- [x] Need to address how military address data is coming from the payload.

## Acceptance Criteria
- [x] Tasks are addressed and a PR has been prepared for merging.
