### ISSUE TITLE
Submit BGS gem PR

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9368]
## Goal
All the calls that are needed to send a 686 are ready to go so we need to submit these changes to the BGS gem for approval so we can continue development. 

## Tasks
- [x] Review the code diff, look for anomalies, breaks, syntax errors
- [x] Run tests on the calls
- [x] Submit PR to have them merged

## Acceptance Criteria
- [x] A PR has been requested for merging

**Comment by digitaldrk** [comment]
## PR
https://github.com/department-of-veterans-affairs/lighthouse-bgs/pull/19
