### ISSUE TITLE
Establish Connection with Sentry

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9369]
## Goal
Sentry is a tool that monitors and reports errors thrown that we are interested in - we want to make sure our feature is hooked up into this system so that we can watch for errors and address them quickly as they happen.

## Considerations
- For order of operations, 686 code needs to be pushed into an environment that can be seen by Sentry first - this ticket may go at the same time

## Tasks
- [x] Review access to Sentry, after using SOCKS
- [x] Consider Slack integration/ dashboard, if possible
- [x] Establish tags based on feature, FE and/or BE
- [x] Add Sentry Alerts for when VA file number is null

## Acceptance Criteria
- [x] Sentry is poised to capture and monitor errors upon deployment for the 686

**Comment by digitaldrk** [comment]
FYI: Slack integration is not possible at this time given the version of Sentry we are on (9). VSP is working on upgrading to a newer version (10).

**Comment by digitaldrk** [comment]
I don't have permissions to complete this ticket. There is a thread regarding this in the eben channel in DSVA

**Comment by digitaldrk** [comment]
@micahchiang @cohnjesse 

This seems done for BE.

I think there is code that needs to be added to FE to define tags let's chat next week to see if there is anything you need from BE.
