### ISSUE TITLE
Redirects Page - Engineer Feedback

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#93703]
## Pain Point 
The Content Team published an MVP version of [the Redirect Integration Strategy page ](https://depo-platform-documentation.scrollhelp.site/developer-docs/redirect-implementation-strategies) but it is still not formatted well and will be hard to use by VFS Teams.

### Content Team needs to get engineer feedback on which of 2 proposed versions of this page to replace the current one.

- [Version 2 - Still one page](https://vfs.atlassian.net/wiki/spaces/~637b96fdfde064eda2ed7417/pages/3476258817/V2+-+Redirect+Implementation+Strategy)

- [Version 3 - now with child pages](https://vfs.atlassian.net/wiki/spaces/~637b96fdfde064eda2ed7417/pages/3469213926/V3+-+Redirect+Implementation+Strategy)

---
## Tasks
Reach out to these engineers to see which version they would prefer, as a first-time user of a **redirect**

- [x] Dakota Larson - preferred version **THREE**
- [x] Matt Long - preferred version **THREE**
- [x] Matthew Knight - preferred version **THREE**
- [x] Tony Gravell - preferred version **THREE**

## Acceptance Criteria
- [x] All engineers have voted or chosen not to vote.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by BSmolensky** [comment]
Reached out to all four engineers asking if they would like to participate. Once I hear back, I will provide the ones who are interested with the two options. Then I will update this ticket with their feedback.

**Comment by BSmolensky** [comment]
Have heard back from all four. All four have agreed to participate. Have received 2 votes and awaiting two more.

**Comment by BSmolensky** [comment]
It is unanimous. All four voted for Version 3.

**Comment by BSmolensky** [comment]
Acceptance Criteria met. Ticket is ready to close.

**Comment by jknipes** [comment]
Closing per previous comment
