### ISSUE TITLE
Create PDFs for VFS Teams

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#93701]
## Pain Points
VFS Teams do not have access to Confluence and therefore they cannot view Content Style Guide or How To Work With Us docs.
VFS Teams want to migrate GitHub docs to Platform Website and these usually require extensive revision and formatting.

## Issue Description
We need to create PDF versions of our docs and put them into a "package" to share with VFS Teams.

---
## Tasks
- [ ] Create PDFs of How To Work With Us and Style Guide (and _______ )
- [ ] Create page in Content Team Confluence space to house links to these docs
- [ ] Send message in Content private Slack channel alerting team members to docs

## Acceptance Criteria
- [ ] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Additional tickets:
- How To Work With Us
- Style Guide

**Comment by jknipes** [comment]
We are delaying scheduling of this in favor of prioritizing
