### ISSUE TITLE
Design | 674 | In-Progress Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#93714]
## Issue Description
_When a user submits a claim on VA.gov, they should receive an email letting them know their claim submission is in-progress._

- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks
- [ ] Customize in-progress email text with form details
- [ ] Create email template in VA Notify

## Acceptance Criteria
- [ ] In-progress email has been created in VA Notify
---
