### ISSUE TITLE
PR Process Review

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#93710]
## Description 
We have identified a a few pain points in the PR review process:

- There is no clearly defined start point from when a 24 hour review time period starts
- There are instances when the work is not complete, the engineer then corrects the issues, and now it is a 72 hour time period (what is the process there)?
- We want to enact systems that create organic adherence to process not just creating documentation to read through (though we will do this as well)

As a result we want to review the PR review process. 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Document PR process from VFS Team to Support Team
- [ ] Document PR process from Tier 1 to Tier 2
- [ ] Document PR Process from Tier 2 back to VFS Team
- [ ] Identify potential gaps
- [ ] Identify potential solutions
- [ ] Add team's PR review data to the documentation
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Moved work in favor of AP release work and DORA Metrics.

**Comment by alyssagallion** [comment]
Doc Here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/edit-v2/3492347919?draftShareId=2572bdd6-4cbb-4b58-a3e0-f51cf75463bf

**Comment by alyssagallion** [comment]
Complete.
