### ISSUE TITLE
Design | COE | Confirmation and Failure Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#93715]
## Issue Description
_After [confirmation and failure email text](https://www.figma.com/design/dlhofkIJz3MC81PD0pJAb8/OCTO-%7C-Form-Status-Project-(VFF-%2B-My-VA)?node-id=60-49517&node-type=frame&t=WuOBGtzc4Gew77Zo-0) has been finalized by CAIA, it may need to be customized to fit each form and then created in VA Notify.

See proposed email text [here](https://www.figma.com/design/dlhofkIJz3MC81PD0pJAb8/OCTO-%7C-Form-Status-Project-(VFF-%2B-My-VA)?node-id=60-49517&node-type=frame&t=WuOBGtzc4Gew77Zo-0) and [more info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md).

---
## Tasks
- [ ] Customize receipt/confirmation email text if needed
- [ ] Update receipt/confirmation email template in VA Notify
- [ ] Customize failure email text if needed
- [ ] Create failure email template in VA Notify

## Acceptance Criteria
- [ ] Receipt/confirmation email has been updated in VA Notify
- [ ] Failure email has been created in VA Notify
---
