### ISSUE TITLE
Design | PCPG | 36 | Confirmation Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#93718]
## Issue Description
_New confirmation (received) email templates are available. We need to review the current template the form is using and determine if updates need to be made._

- [Current emails](https://docs.google.com/document/d/1kkbkDhgaGJuNrJbz2uHZGWAmbAq0ac21_nkpDQ8FkTc/edit#heading=h.nvwukvkz72q6) in use that need to be updated.
- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks
- [x] Review current confirmation email and determine if changes need to be made to align to updated template
- [x] Update form number to 27-8832
- [x] Create new Draft Confirmation email
- [x] Update "Next Steps" and "What to do if you have questions" info
## Acceptance Criteria
- [ ] Confirmation email template is updated in VA Notify

**Comment by hubgitian** [comment]
Note:
Existing Form name in the file name needs to be updated from
`Chapter 36 (form 28-8832) Confirmation`
to
`Chapter 36 (form 27-8832) Confirmation`
but we should wait because this existing file ( with existing triggers) will map to the new "In Progress" template.

**Comment by hubgitian** [comment]
## Current (outdated) confirmation email
![Image](https://github.com/user-attachments/assets/798afd83-0d7a-4e4b-bb9e-6c3c903634cf)

**Comment by hubgitian** [comment]
## New "Form Received" template 
This new content replaces the existing "Confirmation" email
Note: Next steps still needs to be added to this template
![Image](https://github.com/user-attachments/assets/d484652c-57ad-42a5-b5ef-c61dcc05361b)

**Comment by hubgitian** [comment]
### Content Approved by CAIA ✅
### VA Notify filename: `27-8832 Chapter 36 Form Received - Draft` 
<img width="810" alt="Image" src="https://github.com/user-attachments/assets/e971d122-5824-4fab-a76e-fa447e29c900" />
