### ISSUE TITLE
Resolve dependency issues surrounding body-parser

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#93725]
An outdated version of the `body-parser` dependency has left a vulnerability for a denial of service. Version 1.20.3 resolves this vulnerability, however in numerous platform repositories we have dependencies that are not compatible with the upgraded version of body-parser. We'll first need to update these dependencies in each repository, and then update body-parser to ensure that he vulnerability no longer exists.

Platform repositories in question:

- [platform-pe-test-fe](https://github.com/department-of-veterans-affairs/platform-pe-test-fe)
- [platform-support-slackbot](https://github.com/department-of-veterans-affairs/platform-support-slackbot)
- [vsp-test-user-dashboard](https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard)
- [component-library](https://github.com/department-of-veterans-affairs/component-library)
- [veteran-facing-services-tools](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools)
- [vets-website](https://github.com/department-of-veterans-affairs/vets-website)

## Tasks
- [x] For each of the above repositories, evaluate which of the dependencies use body-parser as a dependency.
- [x] For each dependency identified, attempt to update to a version compatible with 1.20.3 of body-parser without breaking the contents of the repository.
- [x] If able to successfully update all dependencies, update body-parser to at least version 1.20.3.
- [x] If unable to successfully update a dependency, on a case-by-case basis create follow-on tickets for deep investigation.

## Acceptance Criteria
- [x] Denial of service vulnerabilities have been removed.

**Comment by little-oddball** [comment]
Reference to the filter provided: https://github.com/advisories/GHSA-qwcr-r2fm-qrc7/dependabot?query=user:department-of-veterans-affairs

**Comment by IGallupSoCo** [comment]
[platform-pe-test-fe](https://github.com/department-of-veterans-affairs/platform-pe-test-fe), [vsp-test-user-dashboard](https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard), and [veteran-facing-services-tools](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools) all appear to have no dependencies that introduce `body-parser`.

**Comment by IGallupSoCo** [comment]
After working through some misunderstanding on my part, I have ascertained that [component-library](https://github.com/department-of-veterans-affairs/component-library) is also free of any body-parser dependencies

**Comment by IGallupSoCo** [comment]
platform-support-slackbot is getting spun off into a separate ticket for the backlog, as the unit tests are failing in a fresh pull of the master branch
