### ISSUE TITLE
[Design] 10-10EZ - Reg Only: Minor changes to content (pre-launch)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93739]
## Benefit to the Veteran
As a Veteran, I want to have clear guidance and messaging on the application, so that I know what steps to take when I need assistance

## Scope
During a routine HEC call on 9/25, we received feedback on a couple of items that need content changes.  We are addressing a few of them here before we launch the Reg Only feature.  The changes are listed below and may require some guidance from our CAIA Content SME.

1. Update Reg Only info page on the statement "We recommend calling our HEC to register".  The Veteran cannot register over the phone, but can receive guidance and assistance. The statement should align with this direction.
2. Rearrange the info accordion on the Reg/Enroll question page, moving the accordion toward the top of the page so that the information is findable and accessible to those Veterans who would like more information here.
3. Update the "Check your personal information" page - currently lists the Benefits phone number to change their information, however Veterans need to call the EED (Eligibility & Enrollment Dept) to change their personal info.

## Tasks
- [x] Update designs to reflect the changes described above
- [x] Review with CAIA as needed
- [x] Inform Engineer/PM when design updates are ready

## Acceptance Criteria
- Designs are updated with the appropriate content and ready for development

**Comment by jessicastump** [comment]
Link to [Figma section](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=6560-83996&t=aURFbdJ4NsOaOxqZ-4) where updates are drafted - I will tag Aliyah and go over tomorrow during weekly content sync to see if there are any concerns or anything else needed. Being this is mostly moving already approved content, we should be good :)

**Comment by jessicastump** [comment]
Some comments from Aliyah after the CAIA content review: 

> Some notes:
> For the additional info component on the question page, I recommend leaving it after the radio buttons ([comment](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=6573-9938&t=OQiojiwiPmtNMt5M-4)). The content before the question would get quite long if someone expands that component. But if you all, as the designers, think that it would actually be best between the body text and note, that is okay for this MVP. All in all, we should plan to revisit this once you all gather feedback and data about this reg-only path.
> I moved the contact information up on the information alert if someone only wants to register. Since the footer of the form includes contact / need help information, moving this up may help to distinguish that if they need help with reg only they should call HEC specifically. We can revisit post MVP based on feedback/data.
> And I'd like to, if possible, revisit the phone vs. mail or in person register conversation in the future :slightly_smiling_face: Mostly, I'm wondering if this is an option that'll exist in the future based on any data/feedback you all get!



@hdjustice and @longmd - the [Figma file](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=6562-84036&node-type=frame&t=aURFbdJ4NsOaOxqZ-0) is updated and image of alert changes are below. 

![Image](https://github.com/user-attachments/assets/dd5ddc7a-4561-4b6f-a813-eec8873841df)


Any thoughts on the pushback on the additional info component placement? I prefer it after the radio buttons too, but am okay with moving it up for the experiment phase...we can revisit after the first month of data and/or if we end up doing user research sessions.

**Comment by longmd** [comment]
RE: the additional info component... I'm not sure I have a preference either way? We could always treat it like we are the "(Recommended)" text and revisit after the first 30 days.. _OR_ we could flip it and give HEC a win for the first 30 days BY moving it up, then revisit and maybe move it down to gather data on that position, too?

**Comment by hdjustice** [comment]
Let's move it up for 1st month, I will track accordion clicks (adding that to our release plan and brief as a tracking metric) and we can revisit.  I agree it makes the page top-heavy, but until we get clear guidance for "registering", we don't have anything else to use.

**Comment by jessicastump** [comment]
Uploading images post-content review of additional items: 

![Image](https://github.com/user-attachments/assets/df8f3ff4-fead-497c-9ab5-b738c0ffe348)
![Image](https://github.com/user-attachments/assets/c223a152-e949-4f4b-88e2-819ff9b89f97)
![Image](https://github.com/user-attachments/assets/c23bd619-eb78-4c86-ac39-bdbcff018c94)

**Comment by jessicastump** [comment]
[HEC Meeting Feedback 9.25.24 - TICKET #93739.pdf](https://github.com/user-attachments/files/17168185/HEC.Meeting.Feedback.9.25.24.-.TICKET.93739.pdf) - PDF of Figma section showing before and after versions of changes made after the HEC meeting this week.

**Comment by jessicastump** [comment]
content check-in complete and closing this ticket -- cc @hdjustice and @longmd

**Comment by hdjustice** [comment]
There was some back & forth with the HEC team on the Personal info page, and we settled on leaving the benefits number as it is today.
