### ISSUE TITLE
[Design] 10-10EZ - Improvement: Update Compensation question option for "up to 40%"

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93745]
## Benefit to the Veteran
As a Veteran, I want to have clear guidance and messaging on the application, so that I know what options to select with confidence

## Scope
During a routine HEC call on 9/25, we received feedback on the Compensation page where we ask whether a Veteran receives disability compensation, with a rating of up to 40%, 50% or above, or no (they do not receive disability compensation).  The feedback was the wording of the option for "up to 40%" to state something like "40% or less".  See comparison below:
- Current wording for the options
>- Yes, for a service-connected disability rating of up to 40%
>- Yes, for a service-connected disability rating of 50% or higher
>- No

- Suggestion for rewording the "up to 40%" option
>- Yes, for a service-connected disability rating of 40% or less
>- Yes, for a service-connected disability rating of 50% or higher
>- No

## Tasks
- [x] Update designs to reflect appropriate wording of the Compensation options
- [ ] Review with CAIA - open ticket for review
- [x] Inform Engineer/PM if there are any follow-ups and when design updates are ready

## Acceptance Criteria
- Designs are updated with the appropriate content and ready for development

**Comment by jessicastump** [comment]
Thinking this can be pointed a 2 and the step/task to review with CAIA/open ticket can be adjusted to "go to office hours/review async" if we even think that is still needed? - @hdjustice and @jessicawoodin

**Comment by hdjustice** [comment]
It is such a tiny change, I dont know if going to office hours is necessary.  If we feel that we need input from CAIA, then that is fine, but I feel like we could trust our experience here.

**Comment by jessicastump** [comment]
Agree - I think it is okay to skip for this change but wanted to confirm before removing that step

**Comment by jessicawoodin** [comment]
@hdjustice - I updated the [Figma file](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=8820-163) to reflect this content change. I agree that this change is small enough that we don't need input from CAIA, so I skipped that step. This is ready for development. Let me know if you need anything else from me!

Also, I still can't edit anything in GitHub, so I can't check off the tasks or close the ticket :)

**Comment by hdjustice** [comment]
This is great, thank you @jessicawoodin !  I tagged this story in the Dev ticket and updated the design links there.  I will close this one.
