### ISSUE TITLE
[FE, QA] 10-10EZ - Reg Only: Update Compensation question option for "up to 40%"

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93748]
- [Design ticket #93745](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93745) is complete and ready for UI update

## Benefit to the Veteran
As a Veteran, I want to have clear guidance and messaging on the application, so that I know what options to select with confidence

## Scope
During a routine HEC call on 9/25, we received feedback on the Compensation page where we ask whether a Veteran receives disability compensation, with a rating of up to 40%, 50% or above, or no (they do not receive disability compensation).  The feedback was the wording of the option for "up to 40%" to state something like "40% or less".  

### References
- [Figma Design](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=8820-163&p=f&t=g8PKlNE70LG4O0Hi-0)
- Design ticket #93745 

## Tasks
- [x] Update Compensation page UI to reflect appropriate wording of the Compensation option
- [x] Review with QA/PM
     - Signoff in the comments is required prior to launch
- [x] Once signoff has been provided, launch to production

## Acceptance Criteria
- Compensation page on the 10-10EZ is updated with the appropriate content

**Comment by longmd** [comment]
@allanto-ah , this has been updated. See screenshots below.

| Before | After |
| ------ | ----- |
| ![Screenshot 2025-04-03 at 11 01 01](https://github.com/user-attachments/assets/d179f6d8-3571-4dc6-8e83-0af8f0f00537) | ![Screenshot 2025-04-03 at 11 00 34](https://github.com/user-attachments/assets/6c182a49-da29-4ece-bdc5-2fe13b48a059) |

**Comment by allanto-ah** [comment]
@longmd that looks good to me!
