### ISSUE TITLE
Review Incident Commander Documentation for Knowledge Gaps

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#93753]
## Description 
Quarterly we review our documentation to identify knowledge gaps. This ticket will house the task of reviewing all of our Incident Commander documentation.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Review existing documentation here: [Incident Commander](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2442854463/Incident+Commander) [Incident Commander Toolkit](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2652504280/Incident+Commander+toolkit)
- [x]  Identify if there is anything from [this page](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/incident-categorization.md) that could be added to our documentation
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
