### ISSUE TITLE
[FE] My VA Forms Status: (QA bug) tag component font does not match VADS

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#93767]
## Background
On staging, it appears that the font in the tag component we're using for the forms status cards does not match what is in VADS.

Staging:
<img width="444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjBhQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f85ded6fee5e74cdc4eb89f60d88da1294a3bdcb/Screenshot%202024-09-26%20at%203.10.44%E2%80%AFPM.png" alt="Screenshot 2024-09-26 at 3.10.44 PM.png" />

VADS:
<img width="128" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjhhQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cdca0b0b9bd70a276b48bfb157094f9be905f6b6/Screenshot%202024-10-02%20at%202.23.54%E2%80%AFPM.png" alt="Screenshot 2024-10-02 at 2.23.54 PM.png" />

https://design.va.gov/components/tag

## Tasks
- [ ] Correct font in component tags to match VADS
- [ ] Consult with VADS as needed for assistance
- [ ] Request review from Matt for validation

## Acceptance Criteria
Font in tag component matches VADS

**Comment by ajakabcin** [comment]
@mattmarino-adhoc to add screenshots/specs for reference

**Comment by DanielMiller-agile6** [comment]
looks like this is being caused by a VADS bug.  I notified the DS team and they've created a new ticket to fix:
https://github.com/department-of-veterans-affairs/component-library/pull/1354

**Comment by DanielMiller-agile6** [comment]
verified fixed DS styles on staging:
![Image](https://github.com/user-attachments/assets/5512a8d1-0351-4047-aa47-dbbee3886bfc)
