### ISSUE TITLE
Discovery: CODE VA

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#93778]
## User Stories
As a PM for the Lighthouse Team, I need to know who will manage updates to the Getting Started with VA.gov page on CODE VA, so that I can focus on APIs

As a PM for the Platform Content Team, I need to understand the task of maintaining the Getting Started with VA.gov page, so I can decide whether my team can take on this role 

As a Platform Content Team member, I need to know whether the Getting Started with VA.gov page maintenance will require knowledge of markdown language and the cadence of update and deployment, so that I can make regular updates to the page

## Issue Description

- Content Team PM will talk with Bryan Ivie from Lighthouse to better understand the services of Lighthouse Team and the purpose of CODE VA as a resource for developers.

---
## Tasks
- [x] Joe meet with Bryan Ivie
- [x] 2nd meeting with Bryan, Zack and Jill Taylor
- [x] Conversation in Slack with Lighthouse

## Acceptance Criteria
- [x] All tasks completed 
- [x] Additional ticket(s) created to track next steps
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
12/4 Joe Knipes and Bryan Ivie, w/ Jill Taylor (Platform Content) and Dean Z. (Code VA)

 - Markdown docs, built using Makedocs, upload to CodeVA
   - Tech docs is where docs reside
     - Starter Guide > VA.gov 
     - Need to select SOURCE at top right (must be signed into GitHub and PIV access)
 - The Ask is to go to the Developer Starter Guide repo, we should own and maintain VA.gov stuff.
   - Need to register it as a component
   - Maintain GitHub actions workflow, 99% of which is created by CodeVA team w/documentation. 
     - Setting up workflow so that it triggers when we push updates to the repo
   - Jill re: comfort level
     - Good so far, knows markdown, doesn’t know GH actions or GH workflow; not 100% on those processes
     - CodeVA team + Bryan can provide support
     - Updates to the workflow or yaml metadata may be needed here or there, but should be infrequent
     - Will need help with source code, branching, merging - what happens after done writing
   - Updates become self-service for us, will be as-needed depending on what goes on with our Platform. 
   - This is what represents how engineers on CodeVA would be doing things at VA.gov Platform.
     - Erika (PO) should stay aware of what is important for us to communicate out, and let us know. Maybe another team 
close to the content would let us know as well. Additionally, there are validations that run on the docs before publishing which will point out broken links, and prevent publishing, print out error messages. 
     - Joe can ask, “Hey Andrea and Clint, outside of what is already here, what would be important to have here?” 
 - Next Step
   - Give Erika the updated ask
   - Bryan, Dean will go back to team and create next steps to get Jill ready
   - Joe figure out the workflow (w/Bryan), including:
     - how to spread the word on PW about what APIs are available, etc. 
   - They want CodeVA to be a one-stop shop for VA developers to visit to pull information from a variety of different software platforms and information sources. 

cc: @EWashb @jwoodman5

**Comment by jknipes** [comment]
Next Steps will be tracked in [ticket 99962](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?pane=issue&itemId=92497117&issue=department-of-veterans-affairs%7Cva.gov-team%7C99962)
