### ISSUE TITLE
Priority #2: Update program page to support launch of new online 10-10CG form (Epic)

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9377]
Epic to house tickets, feedback for our ability to update the program page to support the launch of the new online 10-10CG form

## Background 
[Public Websites update request from Caregivers](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7326)

## Acceptance Criteria
- [x] Kickoff meeting (4.8.20)
  - Align on process, schedule, and information
- [x] Content and design briefing (5.6.20)
  - VA.gov content team will review all references, including the 10-10CG form and additional documentation provided by the form team. Team will come to the meeting prepared with any open questions for clarification.
- [ ] Content/design review (5.14.20 - 5.21.20)
  - VA.gov content team will provide the caregiver team with preview of changes for accuracy review. The caregiver team will have 5 business days to review, with a meeting scheduled as needed to answer questions and align on content
- [ ] Additional rounds of revision and review as needed
  - Teams will work together to align on final content.
- [ ] Final design preview (5.25.20)
  - VA.gov team will incorporate final content into Drupal page and send a PDF to the caregiver team , 3 days ahead of ready-to-publish date.
- [ ] Final sign off (5.28.20)
  - Caregiver team to provide final sign off

**Comment by stephorkandatx** [comment]
mockup to caregiver team along with urls for main page and online application form. https://app.zenhub.com/files/133843125/56c53607-9b4b-4620-ad4a-f5b4c797ec5c/download
