### ISSUE TITLE
[Frontend] MDT - End to End Test 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#9378]
## Issue Description
End to end test on the medical device reordering tool to include form fill and error handling 

---
## Tasks
- [ ] _Write end-to-end test 
- [ ] _Execute test 
## Acceptance Criteria
- [ ] _Test passes without any errors 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mr0sari0** [comment]
Moving to backlog to focus on ui tickets for staging review.

**Comment by mr0sari0** [comment]
Tests for Greg, Mark, Pauline, Jerry, and Eddie have been completed. Waiting on a refactor from @U-DON which will greatly reduce the amount of spec files and code needed to accommodate our different user scenarios.

**Comment by mr0sari0** [comment]
Refactor has been completed. The PR has been merged to `master`.
