### ISSUE TITLE
Create Sample Page in Confluence

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#93788]
## Pain Point
VFS Teams have recently been submitting pages for publishing that have many problems and require extensive editing, reworking and formatting. This work often comes with the expectation of prioritizing over other issues due to a rushed delivery schedule, which disrupts the velocity of the team.

## Issue Description
Content Team should create a Sample Page that is well structured, formatted correctly and adheres to our style guide, and which avoids launch blocking.

---
## Tasks
- [ ] Create sample page
- [ ] add arrows and notes to highlight elements of proper formatting
- [ ] PCT reviews and approves
- [ ] publish document in Confluence
- [ ] promote page in Demo 
- [ ] promote page in Team of Teams
- [ ] promote in future Tip of The Sprint

## Acceptance Criteria
- [ ] All tasks are completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/93788?planning-poker) with Zenhub @BSmolensky @cmarion93 @taylojill

**Comment by BSmolensky** [comment]
FWIW: This might be an Epic.

**Comment by jknipes** [comment]
work completed, closing as _done_

**Comment by jknipes** [comment]
[Sample page instructions are here](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3565617356/Draft+Sample+Confluence+page+93788)
