### ISSUE TITLE
Alert user when there is an error generating their PDF

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#93783]
## Background
When a user clicks "Continue" on the Review page and there is an error generating the PDF for download:
1. Do not progress to the Download page, keep the user on the Review page which is technically the last step still in the Save in Progress experience.
2. Show an error on the Review page and encourage the user to click "Continue" again.
3. When the user clicks "Continue" again, try to re-send all of the information captured in the Appoint experience frontend to the backend for re-generating the PDF.

We need design guidance on how to show this error on the Review page.

## Tasks
- [x] Design an error on the Review page, for scenarios where there is an error generating their PDF
- [x] Consult CAIA on content
- [x] Share designs with the team and confirm there are no concerns before heading into implementation

## Acceptance Criteria
- [x] The team is aligned on an error state, when there is an issue generating the PDF.

**Comment by mtri** [comment]
Figma:
[Desktop](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=11122-225739&node-type=frame&t=mE4sUt7u3YunwgQJ-11)
[Mobile](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=11122-226180&node-type=frame&t=mE4sUt7u3YunwgQJ-11)

[Slack thread](https://dsva.slack.com/archives/C05L6HSJLHM/p1727881112949239)
