### ISSUE TITLE
Address errors/inconsistences with Architecture Intent touchpoint page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#93808]
## User Story
As a Governance team member, I want to ensure that the guidance published on the Architecture intent is accurate and free of errors so that it can be relied upon and trusted by VFS teams.

Assignee: @briandeconinck 
Peer Reviewer: @erinrwhite 

## Description
The Architecture Intent touchpoint page was created by Andrea Hewitt in order to help facilitate the Architecture Intent quickly within the Collaboration Cycle. There are several known errors and issues with the page that we need to address.

In addition, no other pages or guidance for the Collaboration Cycle was updated to be inclusive of the new Architecture Intent. The purpose of this ticket is to address the errors and inconsistencies, as well as ensure Architecture Intent is listed appropriately across the Collaboration Cycle section of Platform Website. 

### Live pages
- [Architecture Intent](https://vfs.atlassian.net/wiki/spaces/CC/pages/3460136961/Architecture+Intent?atl_f=content-tree)
- [Touchpoints](https://vfs.atlassian.net/wiki/spaces/CC/pages/1768423528/Touchpoints)
- [Contact Us](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764524036/Contact+us)
- [Design Intent](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+Intent)
- [Midpoint Review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781039167/Midpoint+Review)

### Drafted pages
- 

## Tasks
- [x] Sync with Shira re: updates to Contact Us page
   - need to change the name of the OCTO Practice Area leads to include "Design"
   - Per discussion with Shira, we'll follow up on listing the OCTO engineering leads in a future ticket
- [x] Identify which pages re: Architecture Intent need to be addressed and updated within the Collaboration Cycle section of Platform Website and list them above under Live Pages
   - [Architecture Intent](https://vfs.atlassian.net/wiki/spaces/CC/pages/3460136961/Architecture+Intent?atl_f=content-tree)
   - [Touchpoints](https://vfs.atlassian.net/wiki/spaces/CC/pages/1768423528/Touchpoints)
   - [Contact Us](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764524036/Contact+us)
   - [Design Intent](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+Intent)
   - [Midpoint Review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781039167/Midpoint+Review)
- [x] Update the identified pages to reflect the Architecture Intent
- [x] Update the Arch Intent touchpoint page to fix the known issues and errors

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Architecture Intent touchpoint page has been updated to address the errors and inconsistencies
- [x] The other pages of the Collaboration Cycle section on Platform Website that have been impacted by the addition of the Architecture Intent have been updated to reflect the new touchpoint

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@briandeconinck have you started this work yet? Please let me know the status so I can be sure to plan for next sprint.

**Comment by briandeconinck** [comment]
@shiragoodman  Haven't started yet but I intend to start it today! I can comment with an update by EOD for if I think it'll finish this sprint or carry over.

**Comment by briandeconinck** [comment]
@erinrwhite I think this is ready for review! Let me know if I missed any other pages.

**Comment by briandeconinck** [comment]
- Thanks for the catch!
- Per @shiragoodman, we're going to follow up with a list of the engineering leads in a future ticket --- but I'll defer to her on what to do with Ray's name until then.

**Comment by briandeconinck** [comment]
Chatted with Shira in Slack, Ray's name is fine in the section it's in now pending the next ticket

**Comment by erinrwhite** [comment]
Looking good to close!
