### ISSUE TITLE
Creating a process to fix leaked API Keys on VA Platform

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#93803]
## User Story
As the managers and engineers working on VA Platform,
We need to establish standard guidance for API leaked keys,
So that when these occur they are addressed and mitigated in a consistent manner.

## Issue Description
While on support, @LindseySaari encountered a leaked API key and realized that there were no standard procedures to address leaked APIs for Platform. 
We need to create a process for fixing leaked APIs so that the fixes are addressed and made consistently.  

## Tasks
- [ ] Create process for fixing API leaked keys
- [ ] Vet process among platform engineers for validation
- [ ] Finalize process
- [ ] Disseminate process with other VA Platform teams for consistency. 

## Success Metrics
The Platform team will have a consistent process by which to mitigate leaked API keys

## Acceptance Criteria
- [ ] There will be a consistent process across the platform to fix leaked API keys on the Platform
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jwoodman5** [comment]
@LindseySaari has started a [doc](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3565453488/WIP+-+Mitigating+and+Handling+Leaked+API+Keys) for this.

**Comment by LindseySaari** [comment]
[WIP doc](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3565453488/WIP+-+Mitigating+and+Handling+Leaked+API+Keys) is up for review! Thanks!

**Comment by LindseySaari** [comment]
I've [asked the content team for some assistance](https://dsva.slack.com/archives/CL181NRJQ/p1730729411319479) with getting this doc deployed to Platform website and the support team is also providing a few areas where this could be linked

**Comment by LindseySaari** [comment]
This has been [deployed to Platform website!](https://depo-platform-documentation.scrollhelp.site/developer-docs/mitigating-and-handling-leaked-api-keys). Closing :)
