### ISSUE TITLE
[DISCOVERY] Left Nav IA Feedback

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9380]
## Issue Description
This issue captures IA feedback given by @mnorthuis during the [staging review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8485) for the VAMC left navigation menu upgrade. 

**1.** For some L3 content that is hidden in the left nav, the left nav is still displayed on the page but the left nav no longer has a "you are here" indicator. Examples:
  - https://staging.va.gov/pittsburgh-health-care/women-veteran-care/
  - https://staging.va.gov/pittsburgh-health-care/internships-fellowships/forms/

**2.** URLs do not reflect that these are L3 pages - their breadcrumbs are accurate but URLs are not

**3.** The "Home" portion of the breadcrumb disappears on some pages, but not all. For example, it is not shown Health services and Locations pages, but does appear on Events and About us.
  - "Home" should take you to va.gov home page. 
  - "Pittsburgh health care" should go back to the health care system primary page.

**4.** The L2 options in the left nav do not all have hover states when they are expanded to show L3 items, but they do have hover states there are no L3s to show.
  - Per @rtwell, when a user is on a page, that page in the side nav should not be clickable or have a hover state (because the user is on that page). 

**5.** For content that is at the top level of the VAMC site, and not part of a "spoke", there is no "You are here" indicator in the left nav. The left nav should be designed to accommodate this, or it should be removed, or the IA should be reviewed for these pages.
  - Example: https://staging.va.gov/pittsburgh-health-care/make-an-appointment/
---
## Tasks
- [ ] Determine expected behavior for each of the scenarios outlined above
- 1. Do not display Left Nav**or** display left nav and "you are here" indicator?
- 5. Design the left nav to accommodate "you are here" **or** remove the content **or** review the IA?

- [ ] Create individual issues as needed and estimate

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rtwell** [comment]
I will offer what clarification I can:

1. For pages like [Women Veteran care](https://staging.va.gov/pittsburgh-health-care/women-veteran-care/), the side nav should be present, and the parent page (in this case, **Health services**) should display the "you are here" marker.

2. Correct. 

3. We will not display "Home" in the breadcrumb on Pittsburgh. Users consistently expected it to direct them to Pittsburgh home, not VA.gov proper. The fact that it is showing on some breadcrumbs currently is a bug. 

4. Correct. 

5.  I concur—this is part of a larger conversation that i think @mnorthuis @jenniferlee-dsva Meg Peters @davidconlon need to have a come to Jesus moment and figure out what to do with them. 

6. For pages that do not have a spot in the left nav (e.g. all of the individual News releases):
* their respective breadcrumb would be **VA Pittsburgh health care** > **News releases** > **News release title**
* The side nav is hidden

**Comment by mnorthuis** [comment]
I would like to continue to discuss numbers 3 and 6 above.  Pulling in @mpeterz as well. 

3. I do have concerns about removing the "Home" link in the breadcrumb.  I understand where this is coming from but I have a couple of follow up questions...
  - How often are users trying to get to the main health care system page?  This seems to me to be not a common thing users would be looking to do, but I could very well be very wrong.  I'm also wondering if this will be an issue for health care systems where the system name is not so similar to the main VAMC name?
  - Could we alter the labels used in the breadcrumb to give links more info scent?  For example "VA home", or add the word "system" to the primary system page.  

6. If we are showing the left nav for pages like those in issue 1 in the original list, why wouldn't we show the left nav on these as well?  The parent page would be highlighted as the you are here (i.e. News releases), providing users with an easy way to get out of News releases and into another area of the VAMC site.

**Comment by davidconlon** [comment]
@mnorthuis Thanks-this is great feedback and we can take this (and likely many other things) into consideration for a future iteration.  We're by no means done with this, but we're done for now.

I think that there are elements that it would be helpful to have more analytics and systems coming on-line and we may need to take other items into consideration as we think about how it could work for the rest of VA.gov (or not, for that matter)!

**Comment by mmiddaugh** [comment]
Keep this open as it collects IA feedback and issues for consideration
