### ISSUE TITLE
[Design, FE, QA] 10-10EZ - Facility: Remove checkbox for "minimum essential coverage"

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93819]
## Benefit to the Veteran
As a Veteran, I want to ensure the information I provide on the 10-10EZ be usable and actionable, so that I can be confident with my answers/designations.

## Scope
During review of the form updates provided in June 2024 and discussing with the HEC stakeholders, we found that the checkbox for a Veteran to indicate that they are "enrolling to get minimum essential coverage under the Affordable Care Act" was removed from the paper form and is no longer needed on the online form.

We need to remove the "minimum essential coverage" checkbox and info accordion from the online form.

![Image](https://github.com/user-attachments/assets/6c5f77b6-1b47-4fd8-ab23-c4914428be62)

## Resources
- [Figma Design](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=6931-7097&node-type=canvas&t=w82GGMTB4dohaqui-0)

## Tasks
- [x] Update the design file to remove the checkbox for "minimum essential coverage" and the info accordion
- [x] Update the Facility selection page to remove the checkbox and info accordion
- [x] Complete regression testing to ensure there are no impacts to form completion and submission
- [x] Review with PM
     - Signoff is required in the comments prior to launch
- [ ] Launch to production

## Acceptance Criteria
- The "minimum essential coverage" checkbox and accordion info has been removed from the 10-10EZ form.

**Comment by hdjustice** [comment]
Check in to back end changes, VES may be impacted.  Check for requirement.

**Comment by jessicastump** [comment]
Link to [Figma page draft](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=6931-7097&node-type=canvas&t=w82GGMTB4dohaqui-0) with removal and adjustments - the removal resulted in a double header that needed fixed and also suggesting we update the "OR" text with this iteration (and need to add a task/reminder to update design source of truth files once this is in production).

**Comment by longmd** [comment]
@jessicastump , one thing I noticed on the links on this page: we have them opening in new tabs, but we're not indicating that to the user. I know the guidance is not to have things open in new tabs, especially links within VA.gov. Should we adjust these to open in the same window, or add the text `(opens in a tab)` to the links?

**Comment by jessicastump** [comment]
@longmd Nice catch on adding the new tab language, that is newer guidance we might as well update while on this page too :) 
Looking at the docs - https://design.va.gov/content-style-guide/links#linking-to-external-sites - I think adding the (opens in new tab) should work for all, the one is a subdomain and that seems to fall more in line with VA.gov rules still. Updated the figma file and adding annotations for the links - if there is anything that would be helpful to document in the design file (aria label, etc), let me know!

**Comment by allanto-ah** [comment]
Environment: RI

Verified that there were no regression issues and submissions are working as expected

E2E with VES: [Slack](https://dsva.slack.com/archives/CMJ2V70UV/p1729270896223289)

![Image](https://github.com/user-attachments/assets/6239cdb5-d58e-4e0a-9481-44b43455d414)

**Comment by hdjustice** [comment]
The UI looks good, and we are currently sending a "false" value for the aca indicator.  The application submitted and processed successfully as expected.  We will look into whether we can remove the aca indicator attribute from the backend in another ticket.
`         <ns0:acaIndicator>false</ns0:acaIndicator>`

**Comment by hdjustice** [comment]
This is good to launch to production

**Comment by longmd** [comment]
This has been merged and will be in prod shortly.

**Comment by hdjustice** [comment]
Confirmed with Josh Faulkner that the attribute `<ns0:acaIndicator>false</ns0:acaIndicator>` is required in the schema and should have a default value of "false" if the checkbox is removed from the UI.  The application will not be accepted and processed if it is missing this attribute.  
We have removed the checkbox in this ticket and will close ticket #94276 with no further action required.  See [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94276#issuecomment-2427646795) for Slack conversation
