### ISSUE TITLE
Add CMS gh label if/when VFS team selects "unsure" re: CMS question at kickoff

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#93812]
## User Story
As a CMS team member, I want to be able to review the Collab Cycle kickoff that come through where the VFS team responded "unsure" to the VA editor question so that I can determine whether or not this VFS team needs support from CMS.

Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description
We have noticed that VFS team have been answering "unsure" to the new, CMS question, "Will a VA editor (Drupal) notice this change?" In addition to recommending the CMS Request touchpoint, Governance has proposed adding the CMS gh label to the ticket. This would allow the CMS team to review the request, and if they think the VFS teams need to sync with them, then they can proceed with a CMS request. If not, then the CC Request ticket can be left as is, and CMS team will remove their label and comment that the VFS team does not need to complete a CMS request.

### Live pages
- [Collab Cycle Kickoff - admin tasks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Admin+Tasks)

### Drafted pages
- 

## Tasks
- [x] Modify the Collab Cycle Kickoff- admin task instructions so that if/when a VFS team responds "unsure" to the question, "Will a VA editor (Drupal) notice this change?", Governance team notifies the CMS team by adding the `CMS follow up` label and tagging the team on the kickoff request thread.

- [x] Once instructions have been written and reviewed/approved by Governance, share with Grace and Marissa via the #sitewide-cms-platform 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have defined a process for adding the CMS label if/when VFS team answer "unsure" to the Drupal question at kickoff
- [x] We have updated the Kickoff admin tasks doc to reflect this change.

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@gracekretschmer-metrostar FYI

**Comment by shiragoodman** [comment]
Per planning on 10/23, we will ADD the CMS Request code block when the VFS team selects "unsure" for the Drupal question. IF/when the VMS team determines No, the VFS team does not need support from CMS team, then they can just comment on the ticket.

**Comment by erinrwhite** [comment]
@shiragoodman updated the ticket a little more per our discussion at refinement. I am going to follow up w/Grace and Marissa to ensure this process is a go for them and that they don't need additional documentation.

**Comment by erinrwhite** [comment]
Grace was OOO late last week - anticipating hearing back her today to ensure this workflow is okay to go.

**Comment by shiragoodman** [comment]
@erinrwhite if she doesn't respond today, I'd recommend tagging her tomorrow and giving her a nudge. Ty!

**Comment by erinrwhite** [comment]
Meeting with Grace tomorrow/Thursday 10/31!

**Comment by erinrwhite** [comment]
Next steps: if team is unsure, apply label "CMS Follow up" and tag @gracekretschmer-metrostar in the slack kickoff request thread in #platform-collaboration-cycle

**Comment by erinrwhite** [comment]
doh! Thank you @allison0034, [process updated and ready for your review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Admin+Tasks#Step-2%3A-Review-VFS-team-submission)

**Comment by allison0034** [comment]
Looks good!
