### ISSUE TITLE
[BE] 10-10CG - Improvements: Update retries to exhaust after 14 retries

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93823]
## Background
Due to some issues and increasing timeouts in March 2023, the 10-10CG retries was increased from 14 to 22 retries before ultimately failing the submission.
After reviewing the 10-10CG setup for something else, we realized we did not decrease the retries limit back to 14 once the timeout issues were resolved.   We need to decrease the retries limit back to 14 retries so that we align with the [Ultimate Failures procedure](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10CG%20Form/Vets-api%20retries%20for%20MuleSoft%20-%20Ultimate%20Failures%20process.md).

## Tasks
- [x] Update the retries to limit at 14 retries before exhausting and ultimately failing the submission.
- [x] Complete testing to ensure the limitation is in effect and submission retries do not exceed 14 before ultimately failing
- [x] Review with PM
     - Signoff is required in the comments prior to launch
- [x] Launch to production

## Acceptance Criteria
- Retries for the 10-10CG have been decreased to the previous limitation, per procedure.

**Comment by hdjustice** [comment]
Change is made, good to go!

**Comment by coope93** [comment]
I validated a job in staging and the job data had the retry_count at 14, as well as the retry value at 14 once it was in the dead queue. 
```
  {"retry"=>14,
   "queue"=>"default",
   "args"=>["not a valid claim id"],
   "class"=>"Form1010cg::SubmissionJob",
   "jid"=>"42fe3bfd38a4be5c1399afc8",
   "created_at"=>1730469509.9037182,
   "request_id"=>"N/A",
   "remote_ip"=>"N/A",
   "user_agent"=>"N/A",
   "user_uuid"=>"N/A",
   "enqueued_at"=>1730559601.470897,
   "error_message"=>"Couldn't find SavedClaim::CaregiversAssistanceClaim with 'id'=not a valid claim id",
   "error_class"=>"ActiveRecord::RecordNotFound",
   "failed_at"=>1730469510.2393794,
   "retry_count"=>14,
   "retried_at"=>1730559601.49174}
```

**Comment by allanto-ah** [comment]
All tasks are completed and has been validated in staging. Closing
