### ISSUE TITLE
Include "Note" to users that contact info updates in Appoint do not push to Profile

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#93827]
## Background
We have agreed that any contact information updates in Appoint MVP do not push to the Profile.  To make this clear to users, we'll want to add in a "Note" to the contact info screens, to set proper expectations with users.

[A has left comments in Figma](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=9725-316004&node-type=canvas&t=8Cvdx7rNvXuFT6Gg-0) with guidance on how to include this content on Veteran Information screens, when the user is an authenticated Veteran.

We also need to carry this same concept over to the Claimant Information screens, when the user is an authenticated non-Veteran claimant.

The unauthenticated experience will not have this content.

## Tasks
- [x] Add in content for the Veteran Information screens, when the user is an authenticated Veteran
- [x] Add in content for the Claimant Information screens, when the user is an authenticated non-Veteran claimant
 
## Acceptance Criteria
- [x] Any authenticated user will see a note, setting expectations that updating their information in the Appoint a Rep form-fill experience will not update in their VA.gov Profile.

**Comment by mtri** [comment]
Screens have been added to the [non-Prefill MVP designs](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=9725-316004&node-type=canvas&t=dViXLnRWDfiMBEdM-11).
[Authenticated Veteran claimant screens ](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=9725-449126&node-type=frame&t=dViXLnRWDfiMBEdM-11)
[Authenticated non-Veteran claimant screens](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=10938-327107&node-type=frame&t=dViXLnRWDfiMBEdM-11)
