### ISSUE TITLE
Request second Midpoint Review for digital submission designs

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#93831]
## Issue Description
This is to track the request of a Midpoint Review, to get Governance's feedback on updates to our digital submission designs, before we head into another Veteran-facing study.

---
## Tasks
- [x] Create a second Midpoint Review section in the [existing Collab Cycle epic for digital submission designs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78846)
- [x] Add in relevant links
- [ ] Schedule Midpoint Review and invite team members

## Acceptance Criteria
- A Midpoint Review has been scheduled
- All materials have been provided for the Midpoint Review meeting

**Comment by oddball-lindsay** [comment]
@mtri I have all the links documented in our [Collab Cycle ticket for digital submission designs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78846), in the "Midpoint Review 2" section. I pulled from your [Slack post](https://dsva.slack.com/archives/C05L6HSJLHM/p1724097561875169?thread_ts=1724097556.508469&cid=C05L6HSJLHM), so I'm feeling pretty good about the list. 

...But I was thinking about how the main intent of a Midpoint Review is to prepare for an upcoming research study and wondering if it makes sense to do a synchronous review of Find v3 and maybe Widget v2, but leave Appoint v2 up to async since it's mostly content updates and we may not be putting that back in front of users.  

Before scheduling the Midpoint Review, I was going to check with Governance on this approach in their Office Hours tomorrow -- sent over an invite if you'd like to join :).

**Comment by mtri** [comment]
@oddball-lindsay Good idea– doing Find and Widget synchronous and separating Appoint out as async makes sense to me since the bulk of changes and new functionality are in Find and the Widget. I think this will help focus the synchronous conversation too since there's a lot to look at. I'll join the office hours tomorrow to help confirm.

Thanks!

**Comment by oddball-lindsay** [comment]
Midpoint has been scheduled -- thanks so much for coordinating and making the async explanations @mtri 🙏
