### ISSUE TITLE
Fix validation errors not displaying on BDD "what type of evidence do you want us to review as part of your claim" flow

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#93839]
## Issue Description
Validation errors ("Select at least one") are not displaying in the BDD flow of supporting evidence

---
## Tasks
- [x] Check to see if this is a V2 component, if it is consider updating it to V3
- [x] Look into the validation function to see if it's working properly
- [ ] 

## Acceptance Criteria
- [ ] Initial click on this checkbox selects the checkbox
- [ ] There is no validation error
