### ISSUE TITLE
Benefit Hubs Reviews: Updated, Focused Review

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9384]
**Goal**

We are iterating on our approach to how we may update or make improvements to the Benefit Hubs content, after discussions regarding IA, best practices, and navigation. The original ask was to 'flatten' the navigation but this does not appear to be the best way to frame our overall goal to improve how our levels of content can best be accessed and understood by users.

With this in mind, we'd like to create a more focused review of existing content to see if there are opportunities for quick wins and improvements. 

How might we review Agent Orange and Disability hub, such that we could potentially generate recommendations to:
* clean up navigation? ex: looking at the existing levels - any room for improvement?
* make organization recommendations that can streamline the experience or impact the nav levels?

**Tasks**
This ticket is a Review ticket, and as such the output will be unknown until it's undertaken. 
Proposed areas of focus: Agent Orange, and Disability Hub
- [x] Review Agent Orange for potential improvements
- [ ] Review Disability Hub for potential improvements
- [ ] Document findings for future work

Disability navigation doc can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/header-footer-and-navigation/page-nav/content-ia/disability-hub-levels-nav-052020.docx)
Navigation Research for the Pittsburgh nav can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/left-nav/research-findings.md)

**Comment by stephorkandatx** [comment]
The two proposed areas of focus are because they either were more of a 'lift and shift' or have some areas we think we could find quick wins.

**Comment by DanielleThierryUSDSVA** [comment]
@mnorthuis Here's my initial review and recommendation for the Agent Orange section within Disability. Would like to grab some time together week of June 1 to talk through this further. And we can continue talking through the larger Disability IA/content strategy. Thanks!
[Agent Orange disability section_IA and content strategy_5.30.20](https://app.zenhub.com/files/133843125/e7e9b52b-2ef2-458a-86e4-37d87404f06f/download)

**Comment by mnorthuis** [comment]
6/1/20 - @DanielleThierryUSDSVA and @mnorthuis reviewed approach and are in agreement.   Two additional tasks to be done prior to finalizing:
- Danielle to review SEO data for specific terms and pages that will be consolidated
- Mikki to review analytics for traffic of pages that will be consolidated

We will regroup later this week.

**Comment by mnorthuis** [comment]
Two legacy pages that sit in the left nav at an L5 level of Disability linked to from https://www.va.gov/disability/how-to-file-claim/evidence-needed/fully-developed-claims/:

1) https://www.benefits.va.gov/FDC/checklist.asp
- This content is covered on How to apply page and [fully developed claims page](https://www.va.gov/disability/how-to-file-claim/evidence-needed/fully-developed-claims/)
- During WBC, we had determined to retire this page and redirect it to the [fully developed claims page](https://www.va.gov/disability/how-to-file-claim/evidence-needed/fully-developed-claims/)

2) https://www.benefits.va.gov/FDC/walkthrough.asp
- This page tells users how to apply on eBenefits including screen shots
- We can remove this page from left nav and include it as an on page link on the [fully developed claims page](https://www.va.gov/disability/how-to-file-claim/evidence-needed/fully-developed-claims/)
- Waiting for reply from BAM1 team on whether after BDD launch there will be any additional applications going through eBenefits - if not, this page can be retired and redirected

**Comment by mnorthuis** [comment]
Checked with PM on BAM1, looks like once BDD goes live as part of the 526, there will not be any 526 claims filed via eBenefits any longer, which means we can retire the walkthrough page. 

https://dsva.slack.com/archives/C5AGLBNRK/p1591044986392000

**Comment by mnorthuis** [comment]
6/3 Notes - Discussion around "How to file" page hierarchy in Disability
- The L5 page for[ filing overseas](https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/file-while-overseas/) could easily be incorporated into its parent page "[Pre-discharge claims](https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/)" .  This will accomplish the short term goal of eliminating an L5 page
- Beyond that, this entire content area would benefit from a full review and possible restructuring.  The parent of this structure is "How to apply", but the hierarchy of content under it does not answer that question.  In other words, if I go to "How to apply" I should be presented with content that answers that question...right now, you are presented with additional questions "What evidence is needed", "When to file".  This is also very different to how we filter users to the claim form within the wizard - that filters users based on the type of claim form (pre-discharge, original claim, increase claim, appeal, etc).  We need to rectify how we have this structured to be more clear.
- At first glance, SEO data supports a change to the structure - the lower level pages have more SEO value in their keywords than their parent pages do.

**Comment by stephorkandatx** [comment]
based on sprint planning discussion, this ticket can be closed out & new items spun up @DanielleThierryUSDSVA
