### ISSUE TITLE
Ensure existing Datadog monitoring meets Platform's new tagging standards

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#93851]
## Background
As part of the "zero silent failures" initiative, there is guidance on how to setup Datadog monitoring.

We already have monitoring in Datadog for our Rep Status Widget, but we need to make sure the monitoring meets [Platform's new tagging standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards). Required tags are:
1. env
2. team
3. itportfolio
4. service
5. dependency

See documentation linked above for more context into these tags.

## Tasks
- [ ] Review Datadog monitoring platform standards
- [ ] Review our existing Datdog monitoring
- [ ] Update monitoring to ensure we include all required tags

## Acceptance Criteria
- [ ] Our existing Datadog monitoring has been enhanced to meet Platform's new standard of required tags.

**Comment by oddball-lindsay** [comment]
Assigning Jen to this ticket per the [Zero Silent Failures (ZSF) Issues/Tickets  Managing Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727392241472/ff14036aadadd12d211990fa217340424a24b8b4?sender=ubac5f0487f25bc4431288699) instructions.

**Comment by jvcAdHoc** [comment]
I submitted a ticket to get Datadog write permissions (currently read only) so that I can update tags

**Comment by holdenhinkle** [comment]
Asked the #public-datadog channel to add our team to DataDag - https://dsva.slack.com/archives/C01G6J7UGGH/p1728577711628669

**Comment by oddball-lindsay** [comment]
Holden connected with Steve Albers earlier today and this should be good to go, we should be able to accomplish what we need under the "Benefits" umbrella.

**Comment by holdenhinkle** [comment]
PR adding the `representation-management` service to `datadog-service-catalog/datadog-service-catalog.yml`

**Comment by holdenhinkle** [comment]
PR correcting a Datadog service tag - https://github.com/department-of-veterans-affairs/vets-api/pull/19208

**Comment by holdenhinkle** [comment]
I was told to create a file in `/terraform/environments/datadog/monitors` (devops repo) for each endpoint we're monitoring with its corresponding Datadog export pasted in the file but I don't think I need to; none of the other services like ours did that. I'm going to wait and see.

![Image](https://github.com/user-attachments/assets/ecd2b8f0-8511-4748-bcd4-8773cf6e810d)

**Comment by holdenhinkle** [comment]
Our service - https://vagov.ddog-gov.com/apm/services/representation-management/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%210%29&env=eks-prod&fromUser=false&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apods%29%2Cversion%3A%210%29&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cchanges%3A%28%29%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&start=1730410754947&end=1730414354947&paused=false

**Comment by holdenhinkle** [comment]
### [OCTO Benefits Portfolio](https://vagov.ddog-gov.com/organization-settings/teams/02d65116-27e9-11ee-ad54-da7ad0900007/benefits)
![Image](https://github.com/user-attachments/assets/7ef686df-c307-4744-8c5b-ed72941f18c8)

### [Representation Management Service](https://vagov.ddog-gov.com/apm/services/representation-management/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%210%29&env=eks-prod&fromUser=false&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apods%29%2Cversion%3A%210%29&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cchanges%3A%28%29%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&start=1730734525022&end=1730738125022&paused=false)
![Image](https://github.com/user-attachments/assets/1f57225e-445f-48a4-ad1c-7e14cd8a149b)

**Comment by holdenhinkle** [comment]
## All tags have been implemented

### representation_management/v0/power_of_attorney
![Image](https://github.com/user-attachments/assets/ae6b8e38-cc2f-4639-974f-c8308e73e25f)

### veteran/v0/other_accredited_representatives
![Image](https://github.com/user-attachments/assets/3bd2ca5c-5788-4ae3-ba5d-7abbf37b7544)

### veteran/v0/vso_accredited_representatives
![Image](https://github.com/user-attachments/assets/f614baaa-248a-4cb8-b2df-cda7d64a8751)

**Comment by holdenhinkle** [comment]
I also configured 4 for the recommended monitors with the default/suggested values:

### [Enabled monitors](https://vagov.ddog-gov.com/apm/services/representation-management/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%210%29&env=eks-prod&fromUser=false&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apods%29%2Cversion%3A%210%29&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cchanges%3A%28%29%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&start=1730736665007&end=1730740265007&paused=false)
