### ISSUE TITLE
Rates tables creation using spreadsheets

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9385]
As a stakeholder,
I need a way to easily generate and share updated rates
So that I can get my needed updates implemented on VA.gov

The researched-and-ready approach we have chosen:
* The Public Websites team will structure and share spreadsheets (Excel) to our stakeholders, who will fill out the spreadsheets with their content
* The Public Websites team will identify all the VBA stakeholder groups who will use, or may use in the future, spreadsheets to capture table data for Drupal upload onto VA.gov
* When the spreadsheets are sent back to the PW team, we will turn the spreadsheets into CSVs and the 'import' into Drupal for the appropriate rate table. List of pages:
Create by cloning in Drupal 2018 historic rates tables pages. Each page will be its own separate ticket. Legacy pages need to be redirected. The pages are:

Benefit hub | Name of page | URL
-- | -- | --
Careers and Employment | Subsistence allowance rates | https://www.benefits.va.gov/vocrehab/subsistence_allowance_rates.asp
Disability | 2020   Veterans disability compensation rates | https://www.va.gov/disability/compensation-rates/veteran-rates/
Disability | 2020   VA special monthly compensation rates | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
Disability | 2020   special benefit allowances rates | https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/
Disability | 2020   birth defect compensation rates | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
Disability | 2020   VA DIC rates for spouses and dependents | https://www.va.gov/disability/survivor-dic-rates/
Disability | 2020   VA DIC rates for parents | https://www.va.gov/disability/parent-dic-rates/
Education and training | Survivors’   and Dependents’ Educational Assistance | https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/
Education and training | Post-9/11   GI Bill and other VA education benefit rates | https://www.va.gov/education/benefit-rates/
Health Care | VA   health care copay rates | https://www.va.gov/health-care/copay-rates/
Housing | VA   funding fee and loan closing costs | https://www.va.gov/housing-assistance/home-loans/funding-fee-and-closing-costs/
Housing | VA   home loan limits | https://www.va.gov/housing-assistance/home-loans/loan-limits/
Life Insurance | Servicemembers’   Group Life Insurance (SGLI) | https://www.va.gov/life-insurance/options-eligibility/sgli/
Life Insurance | Family   Servicemembers’ Group Life Insurance (FSGLI) | https://www.va.gov/life-insurance/options-eligibility/fsgli/
Life Insurance | Veterans’   Group Life Insurance (VGLI) | https://www.va.gov/life-insurance/options-eligibility/vgli/
Pension | VA   pension rates for Veterans | https://www.va.gov/pension/veterans-pension-rates/
Pension | VA   Survivors Pension benefit rates | https://www.va.gov/pension/survivors-pension-rates/

**Tasks**

For first two spreadsheets - main Disability rates, and DIC rates, for Sandy Tadeo/Elana and for Angie Smith and Kelly Wante, respectively:

- [x] Internal review of Disability rates spreadsheet(s)
- [x] Finalize structure/layout of rates table spreadsheet(s)
- [x] Develop talking points, education strategy for when we present to stakeholders (this may be very lightweight, but will help in making sure we provide consistent material)
Note: we are planning to schedule time with stakeholders in a series of meetings, vs one big meeting
- [x] Stretch goal: schedule the first group of stakeholders' meeting - done 5/28 with approval from Sandy Tadeo et al.

Individual tickets:
1. Main Disability rates spreadsheet approved by Sandy, Elana, et al. 6/2/20. [this epic ticket number was the original individual ticket]
2. DIC rates - 1: #9676. Approved by Angie, Wendy, et al 6/23. 
3. DIC rates - 2: 
3. Pension ratea: 
More TK

**Comment by stephorkandatx** [comment]
@AnneHurley take a look at this and let me know if anything needs clarification

**Comment by AnneHurley** [comment]
@stephorkandatx I added a line to the intro about identifying all the stakeholder groups who'll need these, both now and possibly in the future. We'll also need all the names of the appropriate people in each group. 

Meanwhile I'll upload a copy of the rates groups spreadsheet - @DanielleThierryUSDSVA  FYSA.

**Comment by AnneHurley** [comment]
[Master list of rates pages]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/4659577/Rates.Pages.-.master.list.from.Selina.xlsx)

**Comment by AnneHurley** [comment]
Sandy Tadeo and disability rates stakeholders approved their template 5/29. Now creating DIC version for meeting/approval with Angie (Alfreda) Smith and @bethpotts.

@stephorkandatx and @DanielleThierryUSDSVA  FYSA

**Comment by stephorkandatx** [comment]
Re-opening as a new Epic, to house @AnneHurley's work.

Anne to update the description as needed.
