### ISSUE TITLE
VR&E Monitors Clean-up

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#93867]
# Overview
The VR&E (28-1900) monitors are inconsistently named. 

# Tasks
- [x] - Clean up the monitor names so that they are consistently named. 
- [x] - Determine if the monitors are sufficient and working correctly.  
- [x] - Open new tickets if necessary to address monitors
- [x] - Link to the monitors when completed in this ticket.

Naming convention:
`Benefits <form_id> <form name> <type> <controller/job> <event> <method>
`
e.g.
```
Benefits 21P-527 Pension Metric SideKiq exhausted count
Benefits 21P-527 Pension Metric Pension_claims 422/500 errors count
Benefits 21P-527 Pension Logs Pension_claims Status:!200 >20%
```

**Comment by tfink419** [comment]
The following monitors were updated (names and slight tweaks to alert conditions):
https://vagov.ddog-gov.com/monitors/186965
https://vagov.ddog-gov.com/monitors/186966
https://vagov.ddog-gov.com/monitors/188837
https://vagov.ddog-gov.com/monitors/188839
https://vagov.ddog-gov.com/monitors/240972

This one I fully updated the monitor as the message it was checking for did not exist:
https://vagov.ddog-gov.com/monitors/234453
