### ISSUE TITLE
Content Edit: #93873

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#93883]
## Issue Description
We need to fix the broken links described in [Footer ticket 93873](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93873)

---
## Tasks
- [x] Contact a SME from Forms team or original authors of the page
- [x] fix broken links on page
- [x] prepare for publishing

## Acceptance Criteria
- [x] All tasks completed 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
The work is actually to be performed on the linked GitHub page, NOT Platform Website. Respond to requestor.

**Comment by jknipes** [comment]
Reached out to Jaci Wilkinson on VFF team to locate updated GitHub doc

**Comment by jknipes** [comment]
pulled this ticket in to current sprint due to available capacity and quick turnaround time.
closing as _completed_
