### ISSUE TITLE
COE Monitors Clean-up

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#93913]
# Overview
The COE (26-1800) monitors are inconsistently named. 

# Tasks
- [x] - Clean up the monitor names so that they are consistently named. 
- [x] - Determine if the monitors are sufficient and working correctly.  
- [x] - Open new tickets if necessary to address monitors
- [x] - Link to the monitors when completed in this ticket.

Naming convention:
`Benefits <form_id> <form name> <type> <controller/job> <event> <method>
`
e.g.
```
Benefits 21P-527 Pension Metric SideKiq exhausted count
Benefits 21P-527 Pension Metric Pension_claims 422/500 errors count
Benefits 21P-527 Pension Logs Pension_claims Status:!200 >20%
```

**Comment by tfink419** [comment]
Cleaned up naming on these 3 COE monitors:
https://vagov.ddog-gov.com/monitors/187100
https://vagov.ddog-gov.com/monitors/272235
https://vagov.ddog-gov.com/monitors/272234
