### ISSUE TITLE
Investigate 4142 Submissions and tracking

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#93923]
## Background Context

- We need to track the submission status of 4142 forms (from SC Claims) and follow the same zero silent failure method of notifying Veterans if it fails

## Outcome, Success Measure, KPI(S), and Tracking Link

- Come up with a plan and design on how to do this

## Acceptance Criteria

- [ ] _Design plan for tracking these submissions_

## Out of scope

- Actual Implementation

## Open questions

- Is it stored anywhere now (no) 

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by kayline** [comment]
Technical decision: Save 4142 form information as part of DecisionReviewV1::Appeals::SupplementalClaimServices.process_form4142_submission. Create new model associated to AppealSubmission, similar to AppealSubmissionUpload.
