### ISSUE TITLE
Analyze Percentage of PRs Not Meeting Review Requirements

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#93936]
## Description 

Currently, all pull requests (PRs) submitted for review are expected to meet the outlined requirements here. However, we've observed a significant number of PRs that do not adhere to these guidelines, leading to unnecessary workload and a decline in overall quality.

Objective: Analyze the percentage of PRs that fail to meet the review requirements to assess the scope of the issue. This analysis will inform whether it’s worthwhile to reinstate the PR bot automation that identifies unmet requirements.

Acceptance Criteria:

- Conduct a quantitative analysis of recent PR submissions to identify the percentage that do not meet the outlined requirements.
- Compile findings in a report for the team.
- Provide recommendations based on the analysis (including the potential reintroduction of the PR bot).
- Close this ticket once the analysis and recommendations are delivered.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Conduct a quantitative analysis of recent PR submissions to identify the percentage that do not meet the outlined requirements.
- [x] Compile findings in a report for the team.
- [x] Provide recommendations based on the analysis (including the potential reintroduction of the PR bot).
- [x] Close this ticket once the analysis and recommendations are delivered to Alyssa
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
August Analysis Here by Person:[Uploading... Screenshot 2024-10-04 at 12.23.17 PM.png]

**Comment by alyssagallion** [comment]
August Analysis:[Uploading... Screenshot 2024-10-04 at 12.35.13 PM.png]

**Comment by alyssagallion** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUFrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31f6999911b0ce96d00a1c3d0512984950475170/Screenshot%202024-10-04%20at%2012.35.37%20PM.png" alt="Screenshot 2024-10-04 at 12.35.37 PM.png" />
