### ISSUE TITLE
VSOR - VA Claims Process Interviews - Recruit SEP Users

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#93940]
## Issue Description
Exploratory interviews with VSORs to understand current claims process, supporting forms, and technology. Target audience will include those who do and do not use SEP to see how processes vary. Learnings will be used to inform ARP claims process flows.

## Tasks
Tasks
- [x] Put banner on SEP to recruit users of SEP to participant panel.
- [ ] IF we do not hit 1 - 3 SEP users, send survey to panel to find additional SEP users.
- [ ] Recruit 1 - 3 SEP users to understand SEP specific use cases and needs for ARP.

## Acceptance Criteria
- [ ] All tasks complete
