### ISSUE TITLE
SPIKE: Can we use the Search Providers Appts in EPS to show scheduled appt as an upcoming appt in the Appts app

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93946]
## Description 

Since MSAs are responsible for moving appts from EPS into HSRM, which could take days, potentially, we need to show the scheduled appt in Upcoming appts to the Veteran as soon as the finish the workflow. Therefore, can we: 

- [x] use the Search Providers Appts in EPS to show scheduled appt as an upcoming appt in the Appts app,
- [ ] determine which method we should use of the two options provided, 
- [ ] remove it from the upcoming appt list once it's in VistA, and
- [ ] what value(s) will we be looking for to know it's a duplicate? 

## Tasks

- [ ] Determine answers to spike questions
- [ ] Create follow up ticket to implement this work (can be 1 or more tickets). Or, ping Ben to help create tickets. 

## AC

- [x] Questions are answered
- [ ] Implementation tickets are created

**Comment by benbrasso-agile6** [comment]
> There are two flavors of Appointment retrieval:
> You can retrieve the Appointment with the details and status as of the last time WellHive interacted with the external provider's system for an update (e.g. when the appointment was just booked, or when WellHive last polled which happens every 24 hours)
> This is what Appointment.search returns
> This is not limited.
> You can ask WellHive to reach out in real-time to retrieve the latest details and status from the external provider. 
> This is invoked using Appointment.show for a specific appointment with the retrieveLatestDetails param specified as true
> This is limited

**Comment by benbrasso-agile6** [comment]
- [x] use the Search Providers Appts in EPS to show scheduled appt as an upcoming appt in the Appts app, and 

Yes. 

There are two flavors of Appointment retrieval:

You can retrieve the Appointment with the details and status as of the last time WellHive interacted with the external provider's system for an update (e.g. when the appointment was just booked, or when WellHive last polled which happens every 24 hours)
This is what Appointment.search returns
This is not limited.

You can ask WellHive to reach out in real-time to retrieve the latest details and status from the external provider.
This is invoked using Appointment.show for a specific appointment with the retrieveLatestDetails param specified as true
This is limited

**Comment by benbrasso-agile6** [comment]
@simiadebowale checking in on this ticket since you missed Scrum of Scums today. On schedule with this ticket?

**Comment by simiadebowale** [comment]
will wrap this up tomorrow @benbrasso-agile6

**Comment by simiadebowale** [comment]
When a referral is schedule/booked through EPS:
Step 1: Pull the booked appointment from the EPS appointment.search endpoint (`/appointments`).
When appointments are moved from EPS to HSRM and `vaos service` starts returning them, HSRM will return the appointment with the referral Id.
Step 2: Compare referral Ids between appointments from EPS and HSRM (through vaos service), If ids match, exclude the EPS duplicate from the appointment list displayed to Veteran.

**Comment by ldelacosta** [comment]
@benbrasso-agile6 @JRRoof - This spike ticket is ready for review. I'll move this to External dependencies. Please close it out if you don't need additional info.

**Comment by benbrasso-agile6** [comment]
Thanks! I'll re-document this in our other related tickets. Closing!

**Comment by benbrasso-agile6** [comment]
Tossed implementation ticket in backlog to get picked up later: https://github.com/orgs/department-of-veterans-affairs/projects/1323/views/1?sliceBy%5Bvalue%5D=department-of-veterans-affairs%2Fva.gov-team%2362496&pane=issue&itemId=83341905&issue=department-of-veterans-affairs%7Cva.gov-team%7C94914
