### ISSUE TITLE
VSOR - VA Claims Process Interviews - Recruit Non-SEP Users

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#93942]
## Issue Description
Exploratory interviews with VSORs to understand current claims process, supporting forms, and technology. Target audience will include those who do and do not use SEP to see how processes vary. Learnings will be used to inform ARP claims process flows.

## Tasks
Tasks
- [ ] Select participants from panel to fill in gaps of demographics not spoken to in other interviews.
- [ ] Recruit enough participants to fill 8 - 10 total participants for the study.

## Acceptance Criteria
- [ ] All tasks complete
