### ISSUE TITLE
Flipper UI is slow to load

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#93985]
[Flipper UI](http://api.va.gov/flipper/features) is very slow to load (15s+). It was not like this a few weeks ago. Determine root cause.

## Tasks

- [ ] Investigate the cause of Flipper UI's slow response time

## Acceptance Criteria

- [ ] Cause of issue is known and documented
- [ ] Issue to resolve is created or work is delegated to respective team

**Comment by ericboehs** [comment]
After spending nearly all day on it, I found [the issue](https://github.com/department-of-veterans-affairs/vets-api/blob/f5cd5110f72d6139a10b9e535eca66923309cc63/lib/search/configuration.rb#L26) that's causing Feature Flipper UI to have very long load times. Working with an engineer on it. He's moving the Flipper check to their controller(s).

Initially I tried [updating Flipper UI](https://github.com/flippercloud/flipper/pull/888) but turns out that's not the cause.

**Comment by ericboehs** [comment]
Resolved via https://github.com/department-of-veterans-affairs/vets-api/pull/18693
