### ISSUE TITLE
UX | Conversation with CAIA to understand role and inclusion

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#93993]
Reserving this space to reach out to CAIA to start understanding how users on that side will interact with the Form Builder and what touchpoints need to be created.

CAIA contacts: Laura Willwerth, Megan Zehnder, and A Procik.

## Tasks 
- [x] Prepare artifacts to illustrate role of the tool in form conversion
- [x] Review with SME (Jeana) and PO (Matt)
- [x] Schedule meeting time 
- [x] Use diagram to indicate where CAIA might interact with tool or user
- [x] Discussion with CAIA to align, share visuals, ask questions
- [x] Document learnings for sharing back to the team

## Acceptance Criteria
- [x] Insights collected ([recording here](https://drive.google.com/file/d/1FNwl3FG898-S5J-JVhMx2H5pWWnpvv-L/view?usp=drive_link))
- [x] Link and update shared with team

**Comment by gopixelsgo** [comment]
@brian-wilke I agree, that epic would be helpful.

**Comment by gopixelsgo** [comment]
Topics and questions to start with: 
- Where might we want to remove guesswork on the part of the user as it relates to CAIA interactions? (improved hints?)
- What tasks do CAIA have once a form conversion is submitted for review?
- Does this review align with existing steps in the Collab cycle, or is this a different path?

**Comment by brian-wilke** [comment]
This ticket needs to be continued. Meeting not set yet.

**Comment by gopixelsgo** [comment]
Our meeting with CAIA is scheduled for Oct. 30, so this ticket will roll over to the next sprint to complete the remaining steps.
