### ISSUE TITLE
Finish IPT presentation

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93995]
## Description 

October 3rd, present to IPT about how we're approaching the "check in with MSAs" experiment, and to get their feedback on current progress. 

At a high-level, outline could include: 

- [x] Background and problem
- [x] Might want to squeeze in a highlevel blueprint to show that cell signal is an issue, which is why we moved to 45 mins. That has always been the problem that has remained unsolved. If it worked well, we could have kept eCheck-in how it was, and it would have worked for staff too. 
- [x] Questions we're looking to answer
- [x] Research approach, e.g., two methodologies
- [x] Wireframes (low-fi)
- [x] Might need a quick service map to show where VistA gets updated and where staff take actions
- [x] How we'll track success
- [x] Risks with this approach: don't know if we can toggle updating echeckin status on/off per facility, larger level of effort to turn this feature off and still have demos go through (e.g., longer to actually test something and get feedback), will require front and back of house training
- [x] Show Fallback solution(s), if those are concerns by IPT: 1) keep eCheck-in updating appt status in VistA, or 2) no eCheck-in, rebrand eCheck-in to pre-check-in, but only if demos need to be reviewed, and turn on BT VistA app

Maybe no more than 15 slides. 

## Tasks

- [x] Create presentation for IPT

**Comment by benbrasso-agile6** [comment]
Done - https://docs.google.com/presentation/d/19qITYJXgIZZhBCle4c2WePFiMzktxDF0dvdPrh2Ddt4/edit#slide=id.g305e2b46671_0_89

Will post in slack shortly.

**Comment by benbrasso-agile6** [comment]
Not going to move ticket until new sprint starts tomorrow.

**Comment by benbrasso-agile6** [comment]
Will post the presentation somewhere in Git and then close this

**Comment by benbrasso-agile6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/2024-10%20Check%20in%20with%20an%20MSA%20after%20eCheck-in%20experiment%20in-person%20UAT%20with%20Veterans%20and%20clinic%20staff
