### ISSUE TITLE
[CDP] Alert Banner for Chapter 33 Debts 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#94034]
## Issue Description
Alert for Chapter 33 Debts should be updated to include information to contact DMC with questions. 
### Current copy:
> VA is transitioning to a new system for processing Post 9-11 Chapter 33 financial transactions. Due to this transition, Chapter 33 debt balance information may not reflect recent payments you have made by benefit offset, check, credit card, or ACH. Your payment will not be considered late and will reflect the date received once system updates are completed. This message only applies to Post 9-11, Chapter 33 debts.

### Previously proposed copy
> VA is transitioning to a new system for processing Post 9-11 Chapter 33 financial transactions. Due to this transition, Chapter 33 debt balance information may not reflect recent payments you have made by check, credit card, or ACH. If you believe your Chapter 33 debt balance does not reflect recent payments, we encourage you to contact the Debt Management Center: at ask.va.gov or call 800-827-0648, after 07/12/2024. Your payment will not be considered late and will reflect the date received once system updates are completed. This message only applies to Post 9-11, Chapter 33 debts.

### Previous ticket
- **DMC request for Alert Banner for Chapter 33 Debts 3/3 [#88192](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/88192)**

## Tasks
- [ ] Confirm alert should stay active
- [ ] Confirm new copy with steakholders
- [ ] Update copy

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Alert copy is updated OR removed

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures: 
Confirm copy is displaying as intended. 
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
