### ISSUE TITLE
Updating decision reviews number callouts to first person

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#9404]
## Issue Description
As a member of the content team I need to make sure all content adheres to the VA.gov style guide. We should be writing in first person rather than third.

The number callout answer text throughout the decision reviews hub should change VA to "us," "we," and "our" when appropriate.![Screen Shot 2020-05-21 at 9.58.57 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/fcb26840-026a-4f9e-b839-a67b4e82ef55)

For example, new text should read:
H3: How long does it take VA to make a decision?
Our goal for completing Higher-Level Reviews is 125 days. A review may take longer if we need to get records or schedule a new exam to correct an error.

---
## Tasks
Update text on the following pages: ( @RLHecht )
- [x] [Fiduciary claims](https://www.va.gov/decision-reviews/fiduciary-claims/)
- [x] [Supplemental claims](https://www.va.gov/decision-reviews/supplemental-claim/)
- [x] [Higher-Level Reviews](https://www.va.gov/decision-reviews/higher-level-review/)
- [x] [Insurance claims](https://www.va.gov/decision-reviews/insurance-claims/)
- [x] [After a Board Appeal decision](https://www.va.gov/decision-reviews/board-appeal/after-board-appeal-decision/)

## Acceptance Criteria
- [x] All pages listed above show changes on live site
---

**Comment by lwalsh617** [comment]
@RLHecht - We might want to make this site-wide, not just decision reviews. I know I pulled the language from VA.gov. There's at least one non-DR page that has it:  
https://www.va.gov/disability/after-you-file-claim/
Should we add  "do a site-wide search" at the top of this ticket just to make sure?

**Comment by RLHecht** [comment]
@lwalsh617 Yeah, I just found some on a few other pages as well. Will update ticket and confirm with Danielle that since it's sitewide we should definitely be changing them all.

**Comment by RLHecht** [comment]
Changes to all these pages have been made. Moving to validate. FYSA @stephorkandatx

**Comment by RLHecht** [comment]
These are all validated. Closing ticket. FYSA @stephorkandatx
