### ISSUE TITLE
[CST] Relocate the 5103 waiver confirmation message to a page where Veterans are more likely to expect it.

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#94059]
## Value Statement
**_As a_** Veteran
**_I want to_** see my waiver confirmation message on a page that is logical
**_So that_** I don't get confused and think I have to take more actions if I don't.

---
## Background Context

After [research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2024-07-Development-Letters/research-findings.md), we found that Veterans were confused when the 5103 waiver confirmation appeared on the files tab. Some scrolled down and saw options to upload more evidence, which caused a disconnect.

We plan to relocate the confirmation message to a more intuitive location to avoid confusion.

Below is an example of the confirmation message in the files page.

<img src="https://github.com/user-attachments/assets/6d80cdef-d4b4-40e9-8180-640112596fd0" width="375" >

### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- [Epic Link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94050)

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] _create design options that satisfy the goal of this ticket_
- [x] _share design with team members_
- [ ] _create feature flag, "5103 improvements"_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Design satisfies the goal of this ticket _
- [ ] _feature should be behind feature flag, "5103 improvements"_

**Comment by uxgary** [comment]
The alert has been relocated to the Details (status) page. 

Section of the [Figma file for Engineers](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=4637-19172&t=No1Pj0lJTNO0OjKA-4)

![Image](https://github.com/user-attachments/assets/da25b39b-49c4-48ea-90e8-0a53076dfeb2)
