### ISSUE TITLE
Create a strategy for how team can make Contact Center data more actionable

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#94051]
## Issue Description
As a Researcher I want our team to have an aligned strategy for how we'll gather, process, and understand Contact Center data in a way that is less manual so it takes less time to analyze.

### 526 & Veteran Support Data
Historically, UX has relied on Medallia survey data for 526ez health checks and is currently using it to look for usability issues and other pain points with the new feature during the Toxic Exposure release. 

While Medallia can provide invaluable insight into how Veterans are completing the form in real time, feedback is limited and is not easily accessible to AT users. One of the surveys, the Intercept, is not optimized, as OCTO is currently working to improve it across products.

### Benefits to adding MyVA411 data to TREX toolkit
MyVA411 data, which comes from VEO Tier 1 contact centers, however, provide another data stream of user feedback that we can use to evaluate form health and monitor releases.
**Pros of adding MyVA411 data:**
* Calling is more accessible means of giving feedback than completing the Medallia survey (documented here)
* A much larger and diverse data set, as Veterans call to be unblocked or for other support
* Captures wide swath of pain points where Veterans have to call for information or assistance

## Veteran Impact
Overall, the benefits of understanding how to efficiently and effectively review MyVA411 data will benefit our team in the short and long term.

### Short term
- An input for the research plan for TE usability testing in November. As requested by OCTO, our early findings from monitoring will direct how we evaluate the design (research questions, hypothesis, etc). This will allow us to dig deeper into the usability and propose better post MVP enhancements. 
- More robust monitoring capabilities as we roll out a new feature with a questionable user experience. 
### Long term
- Improve TREX research ops. Help us automate/expedite the data synthesis so we can perform 526 health checks more regularly in a sprint, pulling less from other prioritized work. 
- Build capacity in the ecosystem by starting conversation and documenting best practices about MyVA411 data, which is not often utilized or discussed in slack channels

## Relevant Tickets
- [UX monitoring of TE Release (v1.0 10-50% rollout)](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/92321)

---
## Tasks
- [x] Slack farm knowledge from other teams 
- [ ] talk w contact center team to get more information **message sent 9/4 am to schedule**
- [ ] Get list of teams who've pulled CC data recently
- [x] identify the different approaches other teams are taking for analysis 
- [ ] Perform light technical discovery to understand if there are things we can implement now
- [ ] For any technical work that is a larger effort, write tickets for that work
- [ ] Share what we've learned with other teams for knowledge transfer
- [ ] Identify if we're able to add a new case category to better segment or organize the data

## Acceptance Criteria
- [x] A strategy for our team for how to approach making the call center data more digestible
- [x] A new document that can influence how others understand and leverage contact center data

## Additional Information
The Contact Center stores a large volume of rich data that helps VA understand Veteran concerns, issues, and pain points. However, Platform documentation on data mining, cleaning, exploration, and exploring is light on details. We know that VA teams are hungry for data and we believe that by improving our own process and contributing what we learned back to the VA ecosystem, that all teams will benefit from what we've learned.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by evelynhilbrichdavis** [comment]
Megan Hicks is another useful resource, noted in refinement.

**Comment by evelynhilbrichdavis** [comment]
Working doc to collect all the moving parts: https://docs.google.com/document/d/1vOy9Yyemm2AeMSC9NQBukWoaz67RNWt5pWkqSZ2OWpI/edit

**Comment by evelynhilbrichdavis** [comment]
**Current contact list includes mix of slack thread/short sync with:**
Contact Center Team (reached out)
Research-ops channel open question
Heather Real, VEO CX Specialist (done)
Conditions Team - scheduled for 10/6 3:30-4pm EST
Megan Hicks, VRO Team - contacted to schedule
Florence McCafferty - contacted
Internal sync w/ 
@Aurora Hampton

**Comment by evelynhilbrichdavis** [comment]
@pacerwow this ticket is closed with a report posted to the Github Analytics folder as [MyVA411 Discovery Write-up. ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/analytics/MyVA411%20Discovery%20Write-up.md).

Two activities remain coming out of this discovery. 
1. Set a meeting with Megan Hicks to discuss Streamlit.
2. Have the Contact Center meeting (hard time scheduling it) to get answers on the possibility of upstream category creation.

**Comment by mayacarrolluxa6** [comment]
@evelynhilbrichdavis @pacerwow @pammicmac It appears this task was closed without meeting the acceptance criteria. I see a document with some rough [notes](https://docs.google.com/document/d/1vOy9Yyemm2AeMSC9NQBukWoaz67RNWt5pWkqSZ2OWpI/edit), but I don’t see a strategy document that we can present to OCTO. Given their recent feedback regarding our failure to meet our stated sprint goals, I’m curious about how we want to communicate this. It looks like we’ve only gotten as far as some Slack discussions and identifying an approach.

**Comment by evelynhilbrichdavis** [comment]
@mayacarrolluxa6 @pacerwow @pammicmac Hey! It looks like you might've missed the Github document I listed in the ticket comments. You can review the completed approach here: [MyVA411 Discovery Write-up.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/analytics/MyVA411%20Discovery%20Write-up.md) 
I'll follow up in the slack thread as well. I actually have a few edits I can add based on yesterday's call with the Contact Center that I will get in there ASAP.
