### ISSUE TITLE
[CST] [ENG] Navigate to the files upload section within the files tab from notice details page

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#94061]
## Value Statement
**_As a_** Veteran
**_I want to_** directed straight to the file upload section after clicking a CTA to upload evidence
**_So that_** I'm not confused by landing on a page that doesn't immediately display the upload options.

---
## Background Context

The [research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2024-07-Development-Letters/research-findings.md), revealed that Veterans were momentarily confused when clicking the 'upload evidence' link from the notice details page, as they were directed to the top of the files page. It took them time to reorient themselves and locate the upload section.

We aim to link them directly to the 'additional evidence' section of the files page, allowing them to quickly understand where they are and take the necessary steps to upload their evidence.

Below is an example of the confirmation message in the files page.

<img src="https://github.com/user-attachments/assets/2d541482-7595-4142-b340-2b967fd15d33" width="600" >

### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- [Epic Link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94050)

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Deep link the "evidence upload" link from the notice details page to the "additional evidence" heading on the files page.
- [ ] _(If necessary) adjust the scroll position of the files page on desktop and mobile to ensure the heading isn't obscured by the browser after navigating._

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _the "evidence upload" link from the notice details page shoujld navigate directly to the "additional evidence" heading on the files page. _

**Comment by skylerschain** [comment]
This one is more of an engineering ticket as I think it would just involve updating the link. Pointed it at a 1 but happy to defer if Eng feels differently.

**Comment by pmclaren19** [comment]
Hey @harshil1793 heres the [ticket](https://github.com/department-of-veterans-affairs/vets-website/pull/30899/files#diff-a922e08e61ae5b5e9c6d22c4e0d4646a45312dfe7e386f2d25053ec54520bb05) I was referring to that I worked where we removed the scrolling logic from `AdditionalEvidencePage.jsx `and added it to the parent component `FilesPage.jsx`. It is using `setPageFocus()` and `setUpPage()` to set the page focus. I'm pretty sure that your going to want to change the code in FilesPage.jsx, lines 42 - 46 where `setUpPage()` is being called since the va-breadcrumbs is the focus that we want to override.

**Comment by jacobworrell** [comment]
@harshil1793 Hello, what's the status on this ticket? Is there a PR?

**Comment by pmclaren19** [comment]
Tested in Staging on user 19, 1st claim and it looks good! @skylerschain @jacobworrell please review and close if all looks good!

**Comment by skylerschain** [comment]
Design QA: LGTM 👍
