### ISSUE TITLE
Update existing FMB R&S page: Career resources for military and surviving spouses

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#94070]
## Description
We need to add a bullet point about and crosslink to the eMentor program on VA.gov.

- Update this page: [Career resources for military and surviving spouses](https://www.va.gov/resources/career-resources-for-military-and-surviving-spouses/)
- Update this section: What other programs can I participate in?
- Add this program: [eMentor program](https://www.hqafsa.org/ementorprograms.html)

## Tasks
- [x] DB: Draft
- [x] AP: Review
- [ ] BP: Determine if SMEs need to review this page
- [ ] MZ: Copyedit and publish

## Criteria
- [ ] The eMentor program addition has been published on VA.gov

**Comment by d-beyer** [comment]
@aprocik1 I added the eMentor program to the page:
- [Preview: Career resources for military and surviving spouses](https://preview-prod.vfs.va.gov/preview?nodeId=71222)

**Comment by aprocik1** [comment]
@d-beyer, this is great! I made two small updates:
- I removed "and how to sign up" from the eMentor link label, so that it matches the other link labels in this section.
- I moved the eMentor bullet point to be first in the list. I think the DOLEW bullet point looks odd in the middle of the list, since it has two links.

I'll ask Beth if SMEs need to review this page today. Thanks!

**Comment by aprocik1** [comment]
Update: Beth asked SMEs about this. They're unaware of the eMentor program, so they're uncertain about our publishing this content.

Beth is following up with Mikki to better understand her identifying this program in the IA spec.

**Comment by aprocik1** [comment]
Update: Beth confirmed that we don't need to add the eMentor program to this page. I'm closing this ticket as complete.
