### ISSUE TITLE
Trigger Burial Action Needed email notification

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#94086]
## Issue Description
Trigger an email notifying applicants that their Burial application failed to submit on VA.gov. This email should only be sent if all backup submission pathways have been exhausted, and the submission meets the [criteria of a silent failure](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/zero-silent-failures-categories.md), and the applicant has provided an email address.

Trigger: A failure occurs that meets zero silent failure criteria as identified in [Pension Submission Monitoring documentation](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723151514073/384e8cb5052fd80bfd6d93da645b97e5b22984b2?sender=ud143866fd5369378295a0267).

- Build out the functionality to call VA Notify
- Use the email address entered in the form
- Build out monitor and alert if email fails

Leverage for Stage testing the template created in VA Notify:
Public endpoint: https://staging-api.va.gov/vanotify
Internal VA Network endpoint: https://staging.api.notifications.va.gov/
Template Name: 21P-530EZ – Action Needed Template
Template ID: f78126ea-eab3-4ff7-a4e0-b77d31a93904

Important note: The deadline for this work is 11/12 as part of Zero Silent Failures initiative.  Other notifications for the Zero Silent failure Initiative will be documented in separate tickets.

---
## Tasks

- [ ]  Trigger send of the Action Needed template when a silent failure occurs
- [ ] Build out the functionality to call VA Notify
- [ ] Build out monitor and alert if email fails

## Acceptance Criteria
- [ ] Submissions that meet zero silent failure criteria are identified through backend process
- [ ] Notifications sent to applicants that provided email address when trigger logic met.
- [ ] Monitors and alerts identify when emails fail

**Comment by matt4su** [comment]
Closed as we combined with [#91426](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91426) in 10/17 Engineering refinement discussion
