### ISSUE TITLE
Medallia, CSAT, and KPI discovery and alignment (overall approach)

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#94108]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

In this new fiscal year, the VA is measuring and tracking KPIs by capturing more quantitative data on Veteran satisfaction with VA.gov as a whole experience. One way to capture this progress is through tracking CSAT scores on the Domo dashboard and in Medallia survey feedback. Reporting on CSAT systematically (monthly or quarterly) for the debt portal and FSR pages is a goal for the VA Financial Management team. 

The goal is to capture **accurate and meaningful** CSAT measures and other quantitative measures per product (debt portal and FSR). 

The UX Research team is currently doing discovery work to tackle this initiative in multiple parts to define and streamline the process. @charlottecesana and @mgleo are working on related tasks individually and collaboratively to move forward our team's quantitative knowledge and data for the VA Financial Management products. 

**Quantitative data is shared in (presented differently):** 

Medallia Surveys data sets (quantitative and qualitative data) and Domo Dashboard (**quantitative only**) 

**Goals identified:** 

Domo Dashboard  Discovery: 
 
1. Come up with a strategy to see which query is most meaningful in the Domo dashboard to capture accurate and meaningful CSAT score per product, per survey.  

### Related tickets:

[CSAT Epic ](#102209 )

**Medallia:** 

Medallia data improvement requests
[#101911](https://github.com/department-of-veterans-affairs/va.gov-team/issues/101911)
- Conversations the team is having with Contact Center and Analytics team in the next few weeks to improve the data sets we are receiving each month 

February Medallia Feedback Report (for January 2024 data)
[#101914](https://github.com/department-of-veterans-affairs/va.gov-team/issues/101914)

Custom Survey Medallia Data Report
[#102258](https://github.com/department-of-veterans-affairs/va.gov-team/issues/102258)
- A review and report of the Custom survey feedback that was missing from data sets

---

## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [x] Spend time in the Domo dashboard to analyze different query results and accuracy/meaning
- [x] Investigate to understand the data lineage of CSAT outputs in Domo based on the 3 surveys in the debt portal and FSR pages
- [ ] Define accurate and meaningful queries we can track in Domo going forward

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [x] A better understanding of the Domo dashboard capabilities and what data we can gather that is both accurate and meaningful
- [ ] A Github document or other asset to share with VA stakeholders explaining process and reasoning

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Original ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/94533

Mural created from original ticket: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727813174404/04302dc85c11edf9bacff80c2897298c2e0bb2f5?sender=ua78f969c4cddcbfe56b27885

Domo CSAT Dashboard: https://va-gov.domo.com/page/1545882322

**Comment by charlottecesana** [comment]
The report is complete and is [on Github. 
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/research/medallia_reports/medallia-analytics-report-february-2025.md)
