### ISSUE TITLE
ZSF: Burial Submission In Progress Email 

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#94107]
Send an email notifying applicants that their Burial application was submitted on VA.gov. This email will only be sent if the form has been submitted and the applicant has provided an email address.

Trigger: Submission of the Burial form

This email replaces the current confirmation email, which should be retired when this ticket goes to production.

Leverage for Stage testing the template created in VA Notify
Public endpoint: https://staging-api.va.gov/vanotify
Internal VA Network endpoint: https://staging.api.notifications.va.gov/
Service ID: 5e5cded3-3c76-46a3-9eef-cb63589e76be
Template Name: 21P-530EZ-Submission Confirmation
Template ID: 231fe431-9180-4ab3-8c94-c77c80dcd05f

Production:
Public endpoint: https://api.va.gov/vanotify
Internal VA Network endpoint: https://api.notifications.va.gov/
Service ID: 066bd626-5082-45a3-84a1-349dabd2b6ba
Service Name: Pension Benefits
Template Name: 21P-527EZ-Submission Confirmation
Template ID: 54d0dd41-dcd0-48b4-8de8-55788048e1ef

Important note: The deadline for this work is not included in the 11/12 deadline but per Matt D a stretch goal for that date as part of Zero Silent Failures initiative. Other notifications for the Zero Silent failure Initiative will be documented in separate tickets.
Considered as Stage 3 (not due 11/12): https://dsva.slack.com/canvas/C07QVEDUQ2D?focus_section_id=temp:C:GOa45235f2eaca74f7ea0751b1af

**Tasks**

- [x] Create a Burial-specific instance of the Submission in progress template [#98083](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98083)
- [ ] Map/update the Burial-specific date elements in the template (ENG)
- [ ] Update settings to use Template ID (ENG)
- [ ] Trigger send of the notification when a submission occurs  (ALREADY SETUP)
- [ ] Turn off confirmation email

**Acceptance Criteria**
- [ ] Submissions that meet submission criteria are identified through backend process
- [ ] Notification template created and burial-specific data elements updated/mapped.
- [ ] Notification aligned with design system example
- [ ] Notifications sent to applicants that provided email address when trigger logic met.
- [ ] Confirmation email no longer sent
