### ISSUE TITLE
[Discovery] "Did you mean" search parameters

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9410]
## Problem statement
How can we ensure the parameters used for searching match the Veteran's intended input? 

## Current behavior 
The input entered by the user can be misunderstood when they are passed to mapbox as geographic parameters. This results in the potential for a result list which is technically accurate but not as intended. 

**Examples:** 
Glendale, CO returns locations in Connecticut (but correct if "Colorado" is entered)
Hollywood, CA returns locations in Kansas (but correct if "California" is entered)
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/2a01fda4-4dfb-4df8-9de2-55325612ba05)
![image (35)](https://user-images.githubusercontent.com/55411834/82576830-65230a80-9b47-11ea-96e4-71defd1484bc.png)
![image (36)](https://user-images.githubusercontent.com/55411834/82576836-694f2800-9b47-11ea-93ed-dadfc2382918.png)

## Expected behavior
- A user starts typing their street address into the address form field.
- A list of matching results is presented to the user and can be selected as the input. 

![image](https://user-images.githubusercontent.com/55411834/84812270-61aa6400-afcb-11ea-9712-bcd45bb4e8c5.png)

## Task
- [ ] Investigate the tech options for an interaction which allows the user to validate the intended search parameters auto-complete with/without presence of geolocator, including the following considerations:

> Does the tech geolocate the user to improve address predictions? 
> Can the tech handle addresses such as APOs, FPOs?
> Does the tech standardize the address according to official postal format?
> How are fake addresses handled?
> How many characters must be entered before results are suggested?
> How are results restricted (limited to state? Country?)
> How will parameters be impacted by user interaction with map?
> How will suggested options be presented for users of assistive tech (508 compliance)?

- [ ] Determine if our current version of Mapbox will allow this functionality (do we need to move to API/other component?)

- [ ] Identify set of test scenarios to help evaluate the tech/prototype, such as

> Same city name found in more than one state (such as Hollywood)
> Location entered as state abbreviation vs full state name
> 5 digit house numbers vs zip codes
> Test with/without location bias
> Test number of characters needed as input to generate solid result list
> Test match on full words and substrings

Acceptance Criteria
- [ ] Artifact: Document our options, based on the discovery findings 
- [ ] We have enough information to prototype for use in testing and user research

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by brangi** [comment]
This seems to be more of a mapbox issue `forwardgeocode` not detecting the abbreviation on the states  with https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#forwardgeocode - we provide ` let types = ['place', 'region', 'postcode', 'locality', 'address'];` which according to the documentation - https://docs.mapbox.com/api/search/#data-types -  should be enough to detect the state. I will keep investigating

**Comment by davidconlon** [comment]
Mapbox did not respond until today (6/2)

Mapbox  support team is working on this ticket and apologize for the delay. 
Since this is a geocoder feedback issue, they're engaging their search team internally. 
We may have a technical workaround that you can implement on your end, but they really do want this behavior to be fixed for all of our users. They will give us more info by EOD.

**Comment by mmiddaugh** [comment]
From Mapbox: 

> I have added this to the issue I opened with the search team. I did want to mention that when you turn off type=address and autocomplete, this also returns what you are expecting to see: 
> The tricky thing about this is that the result in Kansas is not technically wrong, but it being the top ranked return, being a street address, is odd, rather than being the city name like you expect. 
> In the short term, I suggest turning off autocomplete, and removing the address type from the geocoder in order to move the behavior of the geocoder towards what you are expecting. 

![image](https://user-images.githubusercontent.com/55411834/83912189-45ccd580-a722-11ea-91b9-dd7e4c6efa1d.png)

**Comment by mmiddaugh** [comment]
Consider auto-complete functionality
Will need to conduct research and/or consider A/B testing

**Comment by mpelzsherman** [comment]
Capturing results [here](https://docs.google.com/document/d/1gafjdX1dV2pVpStTp31SmyPecDDlQ5SI0cUvuS2yNOY/edit#).

**Comment by mpelzsherman** [comment]
Added a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/13370) that turns off autocomplete. Greatly improves the geolocation aspect of search.

**Comment by mpelzsherman** [comment]
Many of the concerns in this task have been addressed by simply turning off the autocomplete option. I would like to suggest we revisit this issue after we have had a chance to re-evaluate our current solution with this new, improved behavior.

**Comment by mpelzsherman** [comment]
For the purposes of this effort, only MapBox and native geolocation are being considered.
Google Maps API is a widely used competitor of MapBox, but has been deemed too expensive.

**Comment by mpelzsherman** [comment]
Doc uploaded to https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/PredictiveGeolocation.md
