### ISSUE TITLE
ZSF: Pension Received notification

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#94112]
Send an email notifying applicants that their Pension application was received on VA.gov. This email will only be sent if the form has been received and the applicant has provided an email address.

Trigger: Status Changed to read vbms from benefits intake API (trigger copied from VFF template, may need to be updated)

Leverage for Stage testing the template created in VA Notify
Public endpoint: https://staging-api.va.gov/vanotify
Internal VA Network endpoint: https://staging.api.notifications.va.gov/
Service ID: 066bd626-5082-45a3-84a1-349dabd2b6ba
Template Name: 21P-527EZ – Received
Template ID: 54140052-af03-4d2b-9903-cd33f21dc422

Production:
Public endpoint: https://api.va.gov/vanotify
Internal VA Network endpoint: https://api.notifications.va.gov/
Service ID: a28aae3e-0467-476b-a3bb-1dd216bf4f2f
Service Name: Pension Benefits
Template Name: 21P-527EZ - Received
Template ID: 799d1246-8eb7-4edf-a3ca-7b2f114beff7

Important note: The deadline for this work is not included in the 11/12 deadline but per Matt D a stretch goal for that date as part of Zero Silent Failures initiative. Other notifications for the Zero Silent failure Initiative will be documented in separate tickets.
Considered as Stage 3 (not due 11/12): https://dsva.slack.com/canvas/C07QVEDUQ2D?focus_section_id=temp:C:GOa45235f2eaca74f7ea0751b1af

**Tasks**
- [x] Create a Pension-specific instance of the Received template [#98083](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98083)
- [x] Map/update the Pension-specific date elements in the template
- [x] Trigger send of the notification when status changed from benefits intake API

**Acceptance Criteria**
- [ ] Applications that meet the criteria are identified through backend process
- [ ] Notification template created and pension-specific data elements updated/mapped.
- [ ] Notification aligned with design system example
- [ ] Notifications sent to applicants that provided email address when trigger logic met.

**Comment by wayne-weibel** [comment]
@danlim715 

First is to look at:

modules/pensions/lib/pensions/notification_email.rb
lib/burials/notification_email.rb
and update personalization if additional fields are required for the template.
Then add to settings (vets-api and vsp-infra-application-manifests) in vanotify.services in the pension/burial sections (search for 'vanotify_services_pension' or 'vanotify_services_burial') - template_id and flipper_id. This setting is what is used in lib/va_notify/notification_email/saved_claim.rb

Now for sending the received email; currently it is the BenefitsIntakeStatusJob which runs periodically. You will want to add an additional function similar to monitor_failure for tracking and sending the received email - using Burial::NotificationEmail and Pension::NotificationEmail ...
There is also the lib/lighthouse/benefits_intake/submission_handler/saved_claim.rb which is a submission handler to work with the new status job (lib/lighthouse/benefits_intake/sidekiq/submission_status_job.rb - not enabled yet). Since this will be behind a flipper it may be worth getting the new job up and running first - remove the current job and get new one running from periodic_jobs and all entries as before. Then would only need to add handling code in a single place. Burial and Pension each have an inheriting handler in their module
https://github.com/department-of-veterans-affairs/va.gov-team/issues/99536

**Comment by aplatt-coforma** [comment]
@danlim715 - Dene has approved the templates. We can proceed with this ticket during sprint 9. Thanks!
cc @matt4su

**Comment by aplatt-coforma** [comment]
Submitted the following on staging for testing. 
Your information for this application
Your name
Anh Platt

Date you submitted your application
Jan 14, 2025 1:25 PM CST

Confirmation number
76e963f4-1da4-4d25-836e-3081cee165b1

![Image](https://github.com/user-attachments/assets/42db8a00-42d8-470f-a57a-9ed13569a340)

I received the "received your application" email. Will wait for this new "recieved your VA form" email.

**Comment by wayne-weibel** [comment]
On production and lower env, the template ids are populated, so will close the outstanding settings pr
![Image](https://github.com/user-attachments/assets/909da036-eb2e-4ad7-a494-772c69d1bb21)
