### ISSUE TITLE
Q3 2024 Metrics

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#94124]
## Background
Time to pull quarterly quant/qual metrics for Q3 2024.

Process for the FAQ survey feedback:
1. View [Github folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/sitewide-content/unauthenticated-content-outcomes-and-metrics/monthly-experience-ratings/ratings-by-month) and grab the link for "Resources and support ratings spreadsheet" (in the bottom Analysis section).
2. View the spreadsheet link in Sharepoint and request access
3. Once access is granted, locate the row that has our FAQ page. 
3. Document the metrics for our FAQ page:  Good, Bad and Total responses, and % of Good and % of Bad.

## Tasks
- [x] [Request contact center feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=ianMcCullough-ob%2C+ATMiddleton&labels=VSP-contact-center%2Ccc-data-request&projects=&template=qualitative-data-request.yml&title=Qualitative+Data+Request) for MyVA411 for Q3 ([example ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87293))
- [x] [Request contact center feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=ianMcCullough-ob%2C+ATMiddleton&labels=VSP-contact-center%2Ccc-data-request&projects=&template=qualitative-data-request.yml&title=Qualitative+Data+Request) for Medallia for Q3 ([example ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87294))
- [x] Remove PII from feedback
- [x] Recap contact center feedback in Sharepoint
- [x] Gather FAQ survey feedback for Q3 (process notes above)
- [x] Recap FAQ survey feedback in Sharepoint

## Acceptance Criteria
- [x] Q3 analytics are in Sharepoint

**Comment by oddball-lindsay** [comment]
MyVA411 data request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/94139
Medallia data request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/94140

**Comment by oddball-lindsay** [comment]
Received the Medallia export -- 137 responses. There was no MyVA411 data for Q3. Will start working through the Medallia export to remove PII.

Also received the August spreadsheet for the FAQ survey feedback, re-requested July. The person who manages these seems to be out until Monday so I don't anticipate getting access to the September data until next week.

**Comment by oddball-lindsay** [comment]
Medallia export for Q3 has PII removed and is uploaded to Sharepoint. The quantitative summaries have been added to our Recap of Responses spreadsheet, but I had a question about how to approach the qualitative analysis of the comments for both the VFS and A11 surveys -- I noticed that the categories are not consistent across past exports.

@jfinnerty13 is the goal to categorize all comments, ideally with the existing categories but adding new categories if I can't find a good fit? Or is the goal to only track the frequency of comments that fall within the existing categories?

**Comment by jfinnerty13** [comment]
Goal is to use existing categories but add in new ones if there isn't a good fit :) just so we can point month over month. Thanks for putting this all together!

**Comment by oddball-lindsay** [comment]
Contact Center quant/qual feedback have been recapped. Just waiting on the FAQ survey feedback, hoping to wrap this up next week!

**Comment by oddball-lindsay** [comment]
FAQ page ratings are in for July and August, just waiting for the September spreadsheet to finalize this.

@jfinnerty13 heads up that I've reorganized our "Performance Metrics" folder to accommodate the new export of Resources and Support Ratings (which is where we get the feedback for our FAQ page).
- I added a "Quarterly Metrics" folder and then nested the Recap of Responses spreadsheet directly in it
- Also in that new folder is the Contact Center exports, and a new folder for storing the Resource and Support Ratings monthly summaries from CAIA

**Comment by oddball-lindsay** [comment]
I got impatient and just asked Randi Hecht for the raw numbers for our FAQ page, for Sept 2024: 
- Good: 84	
- Bad: 24	
- Total: 108

For future quarters, it sounds like monthly spreadsheets will be uploaded to Github roughly a week after the month wraps up. But Randi also said that it's okay to ping her for a quick pull, independent of accessing the spreadsheet with all the R+S raw data.
