### ISSUE TITLE
[ZSF] Datadog checklist remediation

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#94147]
There are places in the checklist where we're not living up to the monitoring, alerting, and issue-creating standards set by the ZSF -- please create each of these as tickets and add the zero-silent-failures label. 

This includes needs to improve tagging, having a workflow to ensure the notifications channel is monitored/someone responds when they are looking into an issue, and creating issues out of all datadog alerts. 

Jobs related to our submissions are currently regularly reported as [top sources of silent failures in the weekly status report](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/reports/09272024.md) on this effort. It's possible that some of these jobs either automatically trigger backup paths or veteran notifications and should not be considered silent failures. 

All monitors should have the following tags, according to [this page:](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards)
form:526ez
team:benefits
service:disability-application
env:eks-prod
itportfolio:benefits-delivery
Dependency:<evss|lighthouse> _(recommended)_

**Resources**

- [Status report 9/27/24](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/reports/09272024.md)
- [Slack channel discussion](https://dsva.slack.com/archives/C04KW0B46N5/p1727837728124249)

**Comment by pacerwow** [comment]
We need tags for team, itportfolio, dependency

**Comment by lisacapaccioli** [comment]
@va-albers We might need some more details to support what is needed to do for DD cleanup. Were you planning to have another follow up meeting that would help us define this ticket more? (cc @pacerwow)

**Comment by lisacapaccioli** [comment]
@kylesoskin Here's the ticket I was referring to this morning in planning that needed more details.

**Comment by lisacapaccioli** [comment]
[Aurora](https://dsva.slack.com/archives/C04KW0B46N5/p1728651601520939)
my notes are in a sharepoint document: [#94147 datadog monitors for zsf](https://dvagov-my.sharepoint.com/:w:/r/personal/aurora_hampton_va_gov/Documents/Document.docx?d=w9168a88189d64a6ea32fbc1d5217697b&csf=1&web=1&e=xMfgv1) 

Next Steps:

1. Organize this list, separating out what we already have for 526 ZSF (in notes above)
3. Create Spreadsheet outlining the 526 ZSF monitors
4. Identify gaps of ZSF points that may be missing (Create tickets/implement if missing)
6. Outline playbook for creating tickets from the monitor alert slack notifications
7. Tag monitors with the desired tags
8. Post-ZSF – work with steve to clean up datadog (the notes indicate some that are...questionable to have)

**Comment by aurora-a-k-a-lightning** [comment]
from friday's DD monitors meeting, it was unclear to me if we have the monitors we need. team Carbs :bread: seems to know more about that. 

so what i did for today was tagged the monitors we do have with the desired tags and then made a sample playbook for one that i know is ZSF... or at least a template from the ZSF monitor playbook template Steve Albers provided.

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/benefits/playbooks/526/monitors

**Comment by lisacapaccioli** [comment]
@freeheeling I only added you to this ticket today. The purpose of the ticket as to do DD cleanup, specifically to the tagging (see above description for what the ask from OCTO was). Aurora started this work, but the ask was to see if Carbs can think of anything that was not already handled. I am not sure what works remain, so please work with @kylesoskin to determine if there was additional requests from Steve that needs to be included. Please reach out to @aurora-a-k-a-lightning if you need any additional information on what she was able to do.

**Comment by freeheeling** [comment]
@lisacapaccioli – Should I continue to work off this ticket or create a new one with criteria that's specific to the objectives to be accomplished?

**Comment by lisacapaccioli** [comment]
@freeheeling If you find work that needs to be done I would track that work separately in a new ticket so that you and Aurora can keep separate in progress/done statuses.

**Comment by freeheeling** [comment]
Documenting my understanding and progress:
If a backup is triggered or email request to notify a veteran is acknowledged as a result of a failed upload of any form or supplementary evidence, then the job is **not** considered a ZSF. If a job exhausts that does not trigger a failure email or a job to dispatch an email fails / never executes, then this constitutes a ZSF.

I have (or soon will have) implemented logging and metrics tracking in the event of a failure/non-action for the following:

- 0781 failure email
- 4142 failure email
- evidence upload failure email
- 526 submission failure email
- 526 backup submission exhaustion
- 526 status polling job (notifies in event of backup submissions with 'expired'/'error' status)

If this list is an accurate representation of all situations where we should be accounting for silent failures, it sounds as though a playbook would be required for each scenario.

**Comment by freeheeling** [comment]
**Slack**
- [Form 526 Backup Submission Retries exhausted](https://vagov.ddog-gov.com/monitors/274836) monitor
  - **Search:** `in:#benefits-disability-notifications form 526 backup submission retries exhausted`
- [Exhausted EVSS::DisabilityCompensationForm::Form526DocumentUploadFailureEmail](https://vagov.ddog-gov.com/monitors/236086) monitor
  - **Search:** `in:#benefits-disability-notifications Form526DocumentUploadFailureEmail`
    - **NOTE:** no results
- [Failure in EVSS::DisabilityCompensationForm::Form526DocumentUploadFailureEmail](https://vagov.ddog-gov.com/monitors/236086) monitor
  - **Search:** `in:#benefits-disability-notifications Form526DocumentUploadFailureEmail`
    - **NOTE:** no results
- [Exhausted EVSS::DisabilityCompensationForm::Form4142DocumentUploadFailureEmail [Prod]](https://vagov.ddog-gov.com/monitors/284627) monitor
  - **Search:** `in:#benefits-disability-notifications Form4142DocumentUploadFailureEmail`
    - **NOTE:** no results
- [Failure in EVSS::DisabilityCompensationForm::Form0781DocumentUploadFailureEmail [Prod]](https://vagov.ddog-gov.com/monitors/284378) monitor
- [Exhausted EVSS::DisabilityCompensationForm::Form0781DocumentUploadFailureEmail [Prod]](https://vagov.ddog-gov.com/monitors/259702) monitor
- [Failure in EVSS::DisabilityCompensationForm::Form4142DocumentUploadFailureEmail [Prod]](https://vagov.ddog-gov.com/monitors/259701) monitor

**Monitors**
- [Form 526 Backup Submission Retries exhausted](https://vagov.ddog-gov.com/monitors/274836)
  - **policy tags:** env:eks-prod, itportfolio:benefits-delivery, service:disability-application
  - **tags:** dependency:evss, dependency:lighthouse, form:526ez, team:benefits, watchtower
  - **query:** `logs("default_zero(count[env:eks-prod @message_content:"Form 526 Backup Submission Retries exhausted"])").last("15m") > 0`
  - **recipient:** Slack benefits-disability-notifications
  - **priority:** P1 (Critical)
- [Exhausted EVSS::DisabilityCompensationForm::Form526DocumentUploadFailureEmail
](https://vagov.ddog-gov.com/monitors/236086)
  - **policy tags:** env:eks-prod, itportfolio:benefits-delivery, service:disability-application
  - **tags:** dependency:va-notify, form:526ez, ~team:benefits~, watchtower
    - **NOTE:** unable to add `team:benefits` to tags
  - **query:** `logs("@named_tags.class:"EVSS::DisabilityCompensationForm::Form526DocumentUploadFailureEmail" @level:warn @message_content:"Form526DocumentUploadFailureEmail retries exhausted" @named_tags.dd.env:eks-prod").index("*").rollup("count").last("5m") > 1`
    - **NOTE:** should the alert threshold be decreased to **zero**?
  - **recipient:** Slack benefits-disability-notifications
  - **priority:** Not Defined
    - **NOTE:** should a priority be assigned if this is ZSF?
- [Failure in EVSS::DisabilityCompensationForm::Form526DocumentUploadFailureEmail](https://vagov.ddog-gov.com/monitors/236085)
  - **policy tags:** env:eks-prod, itportfolio:benefits-delivery, service:disability-application
  - **tags:** dependency:va-notify, form:526ez, ~team:benefits~, watchtower
    - **NOTE:** unable to add `team:benefits` to tags
  - **query:** `logs("@named_tags.class:"EVSS::DisabilityCompensationForm::Form526DocumentUploadFailureEmail" @level:error @named_tags.dd.env:eks-prod").index("*").rollup("count").last("5m") > 1`
    - **NOTE:** should the alert threshold be decreased to **zero**?
  - **recipient:** Slack benefits-disability-notifications
  - **priority:** Not Defined
    - **NOTE:** should a priority be assigned if this is ZSF?
- [Exhausted EVSS::DisabilityCompensationForm::Form4142DocumentUploadFailureEmail [Prod]](https://vagov.ddog-gov.com/monitors/284627)
  - **policy tags:** env:eks-prod, itportfolio:benefits-delivery, service:disability-application
  - **tags:** dependency:va-notify, form:526ez, ~team:benefits~, watchtower
    - **NOTE:** unable to add `team:benefits` to tags
  - **query:** `logs("@named_tags.class:"EVSS::DisabilityCompensationForm::Form4142DocumentUploadFailureEmail" @level:warn @named_tags.dd.env:eks-prod").index("*").rollup("count").last("5m") > 1`
    - **NOTE:** should the alert threshold be decreased to **zero**?
  - **recipient:** Slack benefits-disability-notifications
  - **priority:** Not Defined
    - **NOTE:** should a priority be assigned if this is ZSF?
- [Failure in EVSS::DisabilityCompensationForm::Form0781DocumentUploadFailureEmail [Prod]](https://vagov.ddog-gov.com/monitors/284378)
- [Exhausted EVSS::DisabilityCompensationForm::Form0781DocumentUploadFailureEmail [Prod]](https://vagov.ddog-gov.com/monitors/259702)
- [Failure in EVSS::DisabilityCompensationForm::Form4142DocumentUploadFailureEmail [Prod]](https://vagov.ddog-gov.com/monitors/259701)

**Metrics**
- `vets_api.statsd.worker_evss_form526_backup_submission_process_exhausted`
  - applied on the [Benefits - Form 526 Disability Compensation](https://vagov.ddog-gov.com/dashboard/ygg-v6d-nza) dashboard

**ZSF trigger points**
- `Form526BackupSubmissionProcess::Submit` job
  - if job exhausts:
    - logs "Form 526 Backup Submission Retries exhausted"
    - triggers `Form526SubmissionFailureEmailJob` ('send_backup_submission_exhaustion_email_notice' Flipper [disabled])
      - if job fails:
        - logs "Form526SubmissionFailureEmailJob notification failed"
        - `StatsD.increment("#{STATSD_PREFIX}.error")`
      - if job exhausts:
        - logs "Form526SubmissionFailureEmailJob retries exhausted"
        - `StatsD.increment("#{STATSD_PREFIX}.exhausted")`
        - `StatsD.increment('silent_failure', tags: DD_ZSF_TAGS)`
      - if failure in exhaustion block:
        - logs "Failure in Form526SubmissionFailureEmailJob#sidekiq_retries_exhausted"
        - `StatsD.increment('silent_failure', tags: ::Form526SubmissionFailureEmailJob::DD_ZSF_TAGS)`
  - if failure in exhaustion block:
    - logs "Failure in Form526BackupSubmission#sidekiq_retries_exhausted"
    - `StatsD.increment('silent_failure', tags: ::Form526SubmissionFailureEmailJob::DD_ZSF_TAGS)`
- `SubmitForm0781` job 
  - if job exhausts:
    - logs "Submit Form 0781 Retries exhausted"
    - triggers `Form0781DocumentUploadFailureEmail` ('form526_send_0781_failure_notification' Flipper)
      - if job fails:
        - logs "Failure in SubmitForm0781#sidekiq_retries_exhausted"
        - `zsf_monitor.log_silent_failure(log_info, user_account_id, call_location:)`
      - if job exhausts:
        - logs "Form0781DocumentUploadFailureEmail retries exhausted"
        - `StatsD.increment("#{STATSD_METRIC_PREFIX}.exhausted")`
        - `zsf_monitor.log_silent_failure(log_info, user_account_id, call_location:)`
      - if failure in exhaustion block:
        - logs "Failure in Form0781DocumentUploadFailureEmail#sidekiq_retries_exhausted"
        - `StatsD.increment("#{STATSD_METRIC_PREFIX}.exhausted")`
        - `zsf_monitor.log_silent_failure(log_info, user_account_id, call_location:)`
  - if failure in exhaustion block:
    - logs "Failure in SubmitForm0781#sidekiq_retries_exhausted"
    - `zsf_monitor.log_silent_failure(log_info, user_account_id, call_location:)`
- `SubmitForm4142Job`
- `SubmitUploads` job

**Comment by freeheeling** [comment]
### ZSF monitors needed:
- [ ] `SubmitUploads` job – if email job fails or other failure/error in exhaustion block
  - [ ] "Failure in SubmitUploads#sidekiq_retries_exhausted"
- [ ] `SubmitForm4142Job` – if email job fails or other failure/error in exhaustion block
  - [ ] "Failure in SubmitForm4142#sidekiq_retries_exhausted"
- [ ] `SubmitForm0781` job – if email job fails or other failure/error in exhaustion block
  - [ ] "Failure in SubmitForm0781#sidekiq_retries_exhausted" 
- [ ] `Form526BackupSubmissionProcess::Submit` job
  - [ ] "Failure in Form526BackupSubmission#sidekiq_retries_exhausted"
- [ ] `Form526SubmissionFailureEmailJob`
  - [ ] "Form526SubmissionFailureEmailJob retries exhausted"
  - [ ] "Failure in Form526SubmissionFailureEmailJob#sidekiq_retries_exhausted"
- [ ] `Form526StatusPollingJob` (dependent on 'send_backup_submission_polling_failure_email_notice' Flipper **[disabled]**)
  - [ ] if error after updating `backup_submitted_claim_status` to 'rejected' but before notifying veteran
  - [ ] this is ZSF until Flipper gating `Form526SubmissionFailureEmailJob` is enabled

**Comment by freeheeling** [comment]
- created [Failure in EVSS::DisabilityCompensationForm::SubmitUploads](https://vagov.ddog-gov.com/monitors/293099) monitor with the following configuration:
  - **query:** `events("default_zero(count[@named_tags.class:"EVSS::DisabilityCompensationForm::SubmitUploads" @level:error @named_tags.dd.env:eks-prod @message_content:"Failure in SubmitUploads#sidekiq_retries_exhausted"])").last("15m") > 0`
  - **recipient:** Slack benefits-disability-notifications
  - **priority**: P1 (Critical)
  - **policy tags:** env:eks-prod, itportfolio:benefits-delivery, service:disability-application
  - **tags:** dependency:evss, form:526ez, team:benefits, watchtower

**Comment by freeheeling** [comment]
1. PR submitted to [add polled failure status logging of form 526](https://github.com/department-of-veterans-affairs/vets-api/pull/19252)
2. Created [Form526StatusPollingJob submission failure response](https://vagov.ddog-gov.com/monitors/293624) monitor to notify in the event a failure type response is returned when polling Benefits Intake for the status of a form 526 submission transmitted via the backup process.
