### ISSUE TITLE
[DR] Track VA Notifications send and report on failures

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#94148]
## Value Statement

**_As a_** Veteran

**_I want to_** have any notifications sent to me be tracked and verified that it was delivered

**_So that_** I can have confidence that I am notified on any errors or actions I have to take.

---

## Background Context

- When we send a notification to a veteran about a failed submission, we should track that it was delivered and make note of instances that fail for further notification to be determined later.

## Outcome, Success Measure, KPI(S), and Tracking Link

- We have a way to note all success and failed emails sent

## Acceptance Criteria

- [x] _We have a way to note all success and failed emails sent_

## Open questions

- There have been notes of VA Notify web hook data not being useful

## Tasks

- [x] _Research VA Notify Webhook API_
- [x] _Create/Modify data table to include notification ids for verification_
- [ ] _Create/Modify Webhook endpoint for collection of results and updating tables_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by comaurice** [comment]
Will check info from a previous integration to see what is reusable

**Comment by dfong-adh** [comment]
PR created: https://github.com/department-of-veterans-affairs/vets-api/pull/18945

**Comment by dfong-adh** [comment]
PR created: https://github.com/department-of-veterans-affairs/vets-api/pull/18990

**Comment by dfong-adh** [comment]
PR ready for review: https://github.com/department-of-veterans-affairs/vets-api/pull/18998

**Comment by kayline** [comment]
Need to push the templates to prod, then we can turn on the feature in prod

**Comment by kayline** [comment]
Needs a PR to add a reference field to the request

**Comment by dfong-adh** [comment]
PR ready for review
