### ISSUE TITLE
Q4 2024 Metrics

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#94145]
## Background
Time to pull quarterly quant/qual metrics for Q4 2024.

Process for the FAQ survey feedback:
1. View [Github folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/sitewide-content/unauthenticated-content-outcomes-and-metrics/monthly-experience-ratings/ratings-by-month) and grab the link for "Resources and support ratings spreadsheet" (in the bottom Analysis section).
2. View the spreadsheet link in Sharepoint and request access
3. Once access is granted, locate the row that has our FAQ page. 
3. Document the metrics for our FAQ page:  Good, Bad and Total responses, and % of Good and % of Bad.

## Tasks
- [ ] [Request contact center feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=ianMcCullough-ob%2C+ATMiddleton&labels=VSP-contact-center%2Ccc-data-request&projects=&template=qualitative-data-request.yml&title=Qualitative+Data+Request) for MyVA411 for Q4 ([example ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94139))
- [ ] [Request contact center feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=ianMcCullough-ob%2C+ATMiddleton&labels=VSP-contact-center%2Ccc-data-request&projects=&template=qualitative-data-request.yml&title=Qualitative+Data+Request) for Medallia for Q4 ([example ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94140))
- [ ] Gather FAQ survey feedback for Q4 ([process notes](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718224425278/b300ea8d63dcaaa0cdad0ebf6b4a65a20fcc9371?wid=0-1726091483139))
- [ ] Remove PII from Q4 feedback
- [ ] Compile Q4 feedback at a high level in Sharepoint

## Acceptance Criteria
- [ ] Q4 analytics are in Sharepoint

**Comment by oddball-lindsay** [comment]
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/99627
