### ISSUE TITLE
Design | COE | Action Needed Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94157]
## Issue Description
_When a VA.gov claim fails to submit, VA.gov needs to email the Veteran letting them know they need to take additional action._

- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks
- [x] Customize failure email text with form details
- [x] Create failure email template in VA Notify

## Acceptance Criteria
- [ ] Failure email has been created in VA Notify
---

**Comment by fiorella-io** [comment]
Created action needed email for COE. I'm not sure if the `(((reference_number))` will pull the reference number of this form
![Image](https://github.com/user-attachments/assets/ca493783-bf55-4c43-9b72-fd4aed570435)

**Comment by steele-lm** [comment]
Need to discuss with LGY stakeholders to determine how to determine if a claim fails.

**Comment by sanjabaj2** [comment]
LGY already told us that once they accept the submission, the claim will not fail on their side. This ticket is not needed for action needed emails.  @steele-lm @mjknight50 Also, this conclusion was part of the initial investigation into ZSF that was presented to ZSF team. Did we discover something new recently? 
![Image](https://github.com/user-attachments/assets/7e7a0d8e-4640-4b98-b742-27127bea6064)

**Comment by steele-lm** [comment]
@sanjabaj2 You're correct. I'll close this ticket since it's not needed.
