### ISSUE TITLE
[Design] My VA TMA: update user flows to include failure points

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#94153]
## Background
As a follow-up action item from the silent failures audit, we need to review and update our My VA user flows to identify potential points of failure/errors that the user may encounter and what the UX is in those situations.

## Tasks
- [x] Review user flows (see resources section for links)
- [x] Update flows to include points of failure
- [x] Update copy on error messages (per Matt & AJ discussion)
- [x] Coordinate with Dan T for consistency across My VA and Profile

## Acceptance Criteria
- User flows are updated to include points of failure in the UX

## Resources
All My VA use cases + user flows:
- [LOA1 use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/LOA1-use-cases) + [user flow](https://www.figma.com/file/15yOY4VEzitxm5tRMDiAzz/My-VA?type=design&node-id=0-7050&mode=design)
- [Claims and appeals use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/claims-and-appeals-use-cases) + [user flow](https://www.figma.com/file/15yOY4VEzitxm5tRMDiAzz/My-VA?type=design&node-id=0-7177&mode=design)
- [Health care use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/health-care-use-cases) + [user flow](https://www.figma.com/file/15yOY4VEzitxm5tRMDiAzz/My-VA?type=design&node-id=0-7253&mode=design)
- [Benefit payments use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/benefit-payments-use-cases) + [user flow](https://www.figma.com/file/15yOY4VEzitxm5tRMDiAzz/My-VA?type=design&node-id=0%3A7514&mode=design&t=ZhUs1Oeae2EQjVFh-1)
- [Outstanding debts use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/outstanding-debts-use-cases) + [user flow](https://www.figma.com/file/15yOY4VEzitxm5tRMDiAzz/My-VA?type=design&node-id=0-7422&mode=design)
- [Education and training use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/education-and-training-use-cases) + [user flow](https://www.figma.com/file/15yOY4VEzitxm5tRMDiAzz/My-VA?type=design&node-id=0-7591&mode=design)
- [Benefit application drafts use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/benefit-application-drafts-use-cases.md) + [user flow](https://www.figma.com/file/15yOY4VEzitxm5tRMDiAzz/My-VA?type=design&node-id=0%3A7642&mode=design&t=CREOF8xG3jKa75nz-1)

**Comment by ACParker89** [comment]
@ajakabcin can we add profile to this and assign to @twoangstroms as well?

**Comment by mattmarino-adhoc** [comment]
My VA is done, but consistency may not be totally there with Profile after this sprint - I continued using the model we've been consistently using for IA flow charts, Profile may benefit from that as well.
