### ISSUE TITLE
[Design] My VA Forms Status: update use case documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#94156]
## Background
Post-launch of our MVP we need to update the "Benefit application drafts" use case documentation to reflect the current state/functionality of the section on My VA.

## Tasks
- [x] Update use case scenarios for Benefit applications drafts (to be renamed Benefit applications and forms)
- [x] Update LOA1 use case to reflect revised functionality around benefit applications and forms
- [x] Update figma files/links
- [x] Review/update user flows if not already done
- [x] Ask to PM to review 

## Acceptance Criteria
Use case and design documentation is up to date and reflects what is released in production

[Benefit applications and forms (including drafts) use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases)

**Comment by mattmarino-adhoc** [comment]
@a6marinos @ACParker89 I think this doesn't need much work, I missed seeing this one previously - let's bring it in to this sprint.

**Comment by mattmarino-adhoc** [comment]
carrying over

**Comment by mattmarino-adhoc** [comment]
@a6marinos Hey Mike, please take a look when you get a chance - this should be good, while also all linking to the FE documentation that provides more in-depth specifications and info on the variations of benefit applications, forms, and drafts.
