### ISSUE TITLE
VSOR - VA Disability Compensation Claim - Interviews - Analysis

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#94163]
## Issue Description
Exploratory interviews with VSORs to understand current claims process, supporting forms, and technology. Target audience will include those who do and do not use SEP to see how processes vary. Learnings will be used to inform ARP claims process flows.

## Tasks
Tasks
- [ ] Remove PII from transcripts
- [ ] Upload transcripts and audio to EnjoyHQ
- [ ] Gather quotes and themes in EnjoyHQ
- [ ] Create reporting ticket

## Acceptance Criteria
- [ ] All tasks complete
