### ISSUE TITLE
[Design] Create Final Wireframes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#94167]
## User Story
As a team, we would like to add the pre-check-in feature to the VAHB application.

## Background

Once we finish onboarding and solidify a user flow, we need to create a designs based on the user flow for Pre-check-in in VAHB mobile app.

## Tasks

- [ ] Create designs for Pre-check-in in VAHB mobile app
- [ ] Review with UX
- [ ] Submit to Kristen and VAHB designers (can be in one of our syncs)

## Acceptance Criteria
- [ ] Userflow created
- [ ] Reviewed with UX 
- [ ] Submitted to Kristen and VAHB designers

**Comment by benbrasso-agile6** [comment]
@loripusey FYI, Added some info at the top of this ticket description.

**Comment by loripusey** [comment]
How is this Mobile Intake ticket different than the Change Request that Kristen created?

**Comment by benbrasso-agile6** [comment]
I believe they're the same. Kristen's was for Medication Review. 

The link above I just pulled from the mobile slack channel's bookmarks.

**Comment by loripusey** [comment]
Ah, so maybe Kristen needs to submit one for Pre-Check-in in VAHB then

**Comment by benbrasso-agile6** [comment]
Or we can... 

Could ask her about it at a next meeting. I feel like the web vs mobile app collab isn't quite running seamlessly yet.

**Comment by benbrasso-agile6** [comment]
Re-pinged for access to Figma; dragging their feet. OCTO needs to work that out. https://dsva.slack.com/archives/C018V2JCWRJ/p1728055066183809?thread_ts=1723480337.898309&cid=C018V2JCWRJ

**Comment by cgednalske** [comment]
@loripusey I don't know that we need this ticket around anymore. Because we split out the design work into different stages of wireframe work, this has pretty much become a general duplicate.
