### ISSUE TITLE
Burial | Remove StructuredData::ProcessDataJob

### ISSUE THREAD

**Issue by TaiWilkin** [department-of-veterans-affairs/va.gov-team#94168]
## Issue Description

`StructuredData::ProcessDataJob` (`app/sidekiq/structured_data/process_data_job.rb`) is an async job that performs several tasks that more properly belong to other classes, lacks monitoring and logging, and has no retries or exhaustion handling, making it a likely location for silent failures. Refactor the code to move the work done in `StructuredData::ProcessDataJob` to `SavedClaim::Burial` or `Lighthouse::SubmitBenefitsIntakeClaim`, and then remove `StructuredData::ProcessDataJob`.

---
## Tasks
- [x] Move the code in `StructuredData::ProcessDataJob` to `SavedClaim::Burial` and/or `Lighthouse::SubmitBenefitsIntakeClaim`
- [x] Review the code to ensure that any potential errors in the move code will be tracked. 
- [x] Remove `StructuredData::ProcessDataJob`

## Acceptance Criteria
- [ ] `StructuredData::ProcessDataJob` has been removed
