### ISSUE TITLE
[FE] Update Pre-Check-in to Address Drop in Usage

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#94164]
## User Story
As a team, we have seen a decline in the usage of Pre-Check-in since we launched the new landing page. After looking at the metrics, UX/Product decided to implement the following changes to address this drop.

- Remove the Refresh button 
- Change the wording of the "Review your information now"
- Change the wording of "Your appointments"

## Wireframes
- [Wireframes](https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=768-21622&node-type=section&t=jYF1uYbRWs4upsmy-0)

## Tasks
- [ ] Remove the Refresh button 
- [ ] Change the wording of the "Review your information now"
- [ ] Change the wording of "Your appointments"
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@cgednalske / @benbrasso-agile6 / @zach-park This one is merged and ready to validate in stage, local, or in the screenshot in the PR: https://github.com/department-of-veterans-affairs/vets-website/pull/32618

**Comment by benbrasso-agile6** [comment]
@zach-park @cgednalske ready for validation ^

**Comment by zach-park** [comment]
Looks good to me. Thank you!

Please note that I also cleaned up the Figma page to show the [final design](https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=768-21622&t=PhIY2frGQnMoPSHY-1) only. Thank you
