### ISSUE TITLE
VSOR - VA Disability Compensation Claim - Interviews - Conduct Non-SEP Interviews

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#94162]
## Issue Description
Exploratory interviews with VSORs to understand current claims process, supporting forms, and technology. Target audience will include those who do and do not use SEP to see how processes vary. Learnings will be used to inform ARP claims process flows.

## Tasks
Tasks
- [ ] Complete interviews
- [ ] Manage interview day to day (team coordination, debriefs, interviews, etc.)
- [ ] Download videos and transcripts
- [ ] Compile notes
- [ ] Upload notes, transcripts, and video to Sharepoint
- [ ] Upload notes and transcripts to EnjoyHQ

## Acceptance Criteria
- [ ] All tasks complete
