### ISSUE TITLE
Draft non-PHI email notification

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#94170]
## Tasks

- [x] Draft email notification, no PHI
- [x] Remove PHI SMS version 
- [ ] Review with CAIA
- [ ] Resubmit to Privacy Officer 
- [x] Add to VA Notify ticket

**Comment by benbrasso-agile6** [comment]
@cgednalske @Cieramaddox ya'll want to give this content a review prior to Wednesday? https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=3510-29676&t=MTz7FUuFoS7g2l0G-4

I submitted a ticket for Laura to review too - https://github.com/department-of-veterans-affairs/va.gov-team/issues/95345
