### ISSUE TITLE
Submitted Email: Add template id to infrastructure

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#94195]
## Issue Description
Add template id of Submitted Email to infrastructure 

---
## Tasks
- [x] decide Settings path in manifests repo
- [x] make the update in manifests repo and vets-api
- [x] update path in AWS Parameter Store
- [x] that's it!
- [x] check in Argo that ENV settings are legit

## Acceptance Criteria
- [ ] All settings updated in the above places (Staging + Production) _**(don't forget)**_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
confirmed deployed to Staging
![Image](https://github.com/user-attachments/assets/2b8cac5b-905f-42cd-9586-0d9e11247b82)

**Comment by sethdarragile6** [comment]
Confirmed the new setting is deployed to Staging, and the environment variable set appropriately.
