### ISSUE TITLE
Build the send email trigger for Submitted Emails

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#94200]
### Issue Description
As a Veteran submitting a disability claim through the either primary or backup path
I want to receive an email confirmation that acknowledges VA has has successfully received my claim
So that I have confidence my claim was received and know what to expect next

Dependent on 
- #94194 

### Background
The system currently sends a "received" email only through the primary path workflow when a submitted claim ID exists (backup path will be added shortly). No email that lets the Veteran know VA has recieved their claim is currently sent through either the primary or backup path.

### Tasks

- [x] create feature flag for Submitted email: `disability_526_send_form526_submitted_email`
- [x] create story to remove feature flag later https://github.com/department-of-veterans-affairs/va.gov-team/issues/102475
- [x] make method to send "Submitted" email in `Form526Submission` model (near to received email)
- [x] call "Submitted" email method in two places:
  - [x] [app/sidekiq/evss/disability_compensation_form/submit_form526.rb:171 ](https://github.com/department-of-veterans-affairs/vets-api/blob/97a9462c1609d5bee26946d16551490a81d8ff4c/app/sidekiq/evss/disability_compensation_form/submit_form526.rb#L171)
  - [x] [app/sidekiq/evss/disability_compensation_form/submit_form526.rb:205](https://github.com/department-of-veterans-affairs/vets-api/blob/97a9462c1609d5bee26946d16551490a81d8ff4c/app/sidekiq/evss/disability_compensation_form/submit_form526.rb#L205)
- [x] Submitted email template id: `9b5510d4-f115-4735-b2e4-726f4ff281ad`
- [x] ensure `personalization_parameters['submitted_claim_id']` is an empty string (not `nil`) if there is no claim id

### Acceptance Criteria

- The system sends the Submitted Email notification when a claim is "submitted" on the backup or primary path
- The system logs calls to va-notify

---

### Open Questions
- We can't log email failures, correct? VA-notify handles email logging and does not log failures.

**Comment by aurora-a-k-a-lightning** [comment]
Feature flag name is: `disability_526_send_form526_submitted_email`

**Comment by aurora-a-k-a-lightning** [comment]
### Pseudo Backup Path testing results:
We cannot test the Backup Path in staging. However, I was able to send the email using the Form526Submission from the previous test without a claim id, and the email shows up the same, just without the claim id, as expected

![Image](https://github.com/user-attachments/assets/891b57d3-9d6c-4002-a2ce-e82d7f45e71f)
