### ISSUE TITLE
Upgrade autosave component on Review & Submit page

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#94217]
## Issue Description
Upgrade autosave component from V1 to V3.

For reference the Figma design file for this feature is [here](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/(526ez)-Submission-Experience?node-id=34-73279&node-type=canvas&t=ApNRPKRTgXAYAMBh-0).

## Tasks
- [ ] The autosave component on the Review & Submit page is upgraded to V3

## Acceptance Criteria
- [ ] The autosave component on the Review & Submit page is upgraded to V3
- [ ] If this isn't possible, document and share the reasons why and create tickets for any future work, organized and tagged correctly

**Comment by pacerwow** [comment]
Closing at not needed, the component in production is a v3 component.
