### ISSUE TITLE
Discovery: V3 Web Component Upgrade

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#94228]
## Issue Description
As a team member I want to upgrade all of our web components to V3 so that I can be in compliance with the platform standard and benefit from new functionality of these new components. However, I don't know what needs upgrading, so I need a list of those components. I'd prefer not to go through a few sprints of just updating components, so I would like to know what we can upgrade along the way while we build new features.

---
## Tasks
- [ ] 

## Acceptance Criteria
- [ ] Document a list of the components which need upgrading in Github
- [ ] Some suggestions of where we can upgrade components as we build the upcoming features on our roadmap 

--
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mayacarrolluxa6** [comment]
@pacerwow I have concerns about including this ticket in our Sprint 10 goals. Ideally, the HCD group would participate, but from my understanding, the v3 Web Component upgrade is a lower priority than the remaining submission experience work from Shannon’s perspective. Additionally, with our reduced capacity this sprint, I’m not confident we have the bandwidth to take this on. I recommend removing it from Sprint 10.
