### ISSUE TITLE
Modify confirmation banner content on Confirmation page for successful submissions

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#94221]
## Issue Description
As a Veteran, I want to understand the status of my submission in clear, straightforward language so that I feel confident that VA is trying to submit my application. When I submit my application, I want immediate feedback regarding the status of my application.

The content change for this confirmation banner represents a "success" and should be shown during a successful submit flow (with claim id, less than 30 seconds). The copy should read "Your submission is in progress".

For reference the Figma design file for this feature is [here](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/(526ez)-Submission-Experience?node-id=34-73279&node-type=canvas&t=ApNRPKRTgXAYAMBh-0).

---
## Tasks
- [ ] 

## Acceptance Criteria
- [ ] The confirmation banner "Your submission is in progress" is set on the Confirmation page
- [ ] The banner is displayed when the appropriate application and system conditions are met to indicate a 200 response with claim id
- [ ] The confirmation banner is shown for success

**Comment by pacerwow** [comment]
Closed as a dupe, replaced by #95230
