### ISSUE TITLE
Determine LOE for PCIU migration [Oct 15]

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#94227]
## Issue Description
As a team member I want to know how much effort is remaining to do remove PCIU calls from 526 prefill. We believe this is actually decommissioning work as there isn't a solution that covers the prefill that covers what PCIU covers. We need to know what was done before and what's remaining.

---
## Tasks
- [ ] Talk to the Platform team to understand if their prefill options have changed since we last engaged w them
- [ ] Understand what our contribution needs to be
- [ ] Investigate the issues that surfaced around the latency issue we saw
- [ ] Tag Emily/Sam W on all of these comms
- [ ] Can we get a commitment from Platform team to investigate and fix any issues that we encounter
- [ ] Understand what the UX would be to help weigh our solution
- [ ] Understand exactly what PCIU prefills

## Acceptance Criteria
- [ ] A plan for how we'll do this work
- [x] An estimated time duration or t-shirt size of effort (if we consider Toxic Exposure an XL)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
A little backstory is in order. Back in January, we introduced a flag called [disability_compensation_remove_pciu](https://github.com/department-of-veterans-affairs/vets-api/pull/15171) and used it remove PCIU calls for 10% of users. After a day of running and gathering logs/stats in [DataDog](https://vagov.ddog-gov.com/dashboard/qv6-xpd-7xg/benefits---disability---526---evss-to-vaprofile-526ez-contact-info-pre-fill?fromUser=false&refresh_mode=weekly&from_ts=1728889200000&to_ts=1729011305452&live=true), we shut the flag off due to a relatively dramatic drop in mailing address prefill success (findings detailed [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/evss-pciu-migration-discovery.md#missing-mailing-address-investigation)). After [various](https://dsva.slack.com/archives/C7TE0PFTL/p1708732310734809) [inconclusive](https://dsva.slack.com/archives/C04KW0B46N5/p1723076922972259?thread_ts=1723048745.296229&cid=C04KW0B46N5) inquiries to platform and VA Profile, Emily made to the call to pause the "migration" (or more accurately the "decommissioning") of PCIU because of the overall degradation of the user's experience.

**Where to go from here** (a.k.a. "LOE")

1. Continue to decommission PCIU calls from 526EZ prefill via the `disability_compensation_remove_pciu` flag (LOW effort). 
- code is already in place to decommission PCIU calls from 526EZ prefill. 
- If we agree to accept a certain percentage of degraded performance, it's only a matter of doing a stepped release
2. Allow platform to upgrade/remove PCIU at the global prefill level, then perform stepped release of 526 prefill (LOW-MEDIUM effort)
- see slack thread: https://dsva.slack.com/archives/C04KW0B46N5/p1726865634861069
- Platform team is [currently updating](https://dsva.slack.com/archives/C04KW0B46N5/p1726865634861069) API calls to VAProfile::ContactInformation in global prefill, with plans to [remove PCIU there afterwards](https://dsva.slack.com/archives/C06JM7UUHE3/p1728067598443839?thread_ts=1727709160.762799&cid=C06JM7UUHE3). 
- It is possible that the update _could_ reduce or eliminate the latency issues we observed
- Once their upgrade to V3 is complete, we could open our `disability_compensation_remove_pciu` again to determine whether or not matters have improved
3. Continue to engage the VA Profile and Platform teams to investigate and fix the latency issues (MEDIUM-???) 
- we have generally gone down this road, to [little effect](https://dsva.slack.com/archives/C04KW0B46N5/p1723076922972259?thread_ts=1723048745.296229&cid=C04KW0B46N5).

**Comment by pacerwow** [comment]
The task noted above "Understand what our contribution needs to be" wasn't able to be completed as we found it difficult to determine this in discussing these options with VA.  We'll set up time with OCTO to ask for help in thinking through these options and what our contribution needs to be.

**Comment by pacerwow** [comment]
Let's go with option 2, plan B is option 1... JP to clean up this comment later.
