### ISSUE TITLE
Create User Flow

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#94232]
## Background

Once we finish onboarding, we need to create a user flow for Pre-check-in in VAHB mobile app, based off PCI pre-check-in but adapted to the mobile platform.

At least partially blocked by [Complete initial onboarding for working in VAHB #94639](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94639)

## Tasks

- [x] Create userflow for Pre-check-in in VAHB mobile app
- [x] Review with UX and Kristen
- [ ] Submit for review with VAHB designers (can be in one of our syncs)

## Acceptance Criteria
- [x] Userflow created
- [x] Reviewed with UX and Kristen
- [ ] Submit for review with VAHB designers

**Comment by benbrasso-agile6** [comment]
@zach-park @cgednalske can ya'll drop your points in as a comment? If we need discussion to point, just say the word.

**Comment by cgednalske** [comment]
I'm having a hard time understanding what all is included in this ticket 👀  It even seems like a few tickets put together. So would definitely love a discussion at some point, if possible.

**Comment by benbrasso-agile6** [comment]
Np. I think it's all from a template. I didn't modify this one. Talk about it next week.

**Comment by cgednalske** [comment]
@loripusey I updated the ticket to only include the specific steps for this.

**Comment by cgednalske** [comment]
@zach-park @StevenStraily I'd like to propose that this is a 3‍⃣ instead of a 5

**Comment by zach-park** [comment]
> @zach-park @StevenStraily I'd like to propose that this is a 3‍⃣ instead of a 5

It sounds good with me!

**Comment by cgednalske** [comment]
@zach-park fyi I put myself on here as backup/for discussions, but this should be mostly you! 🙂

**Comment by zach-park** [comment]
I'm just capturing a note based on Kristen's explanation today. And I was wondering if offering two separate versions would be helpful: One as MVP (e.g., notification as an entry point only) and another version as an enhancement. :)

**Comment by cgednalske** [comment]
@zach-park 👍 I have that included as a entry point (possible, future) along with the MVP entry points (I don't think it needs a separate whole flow)

**Comment by cgednalske** [comment]
@zach-park I've added a bunch based on the updates Kristen gave us today and THINK I've covered most everything ([Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1732046663886/09f5f082d33ea39fff3e7321b4c502d49c053b34)). Take a look if you have a second and let me know if I've missed or misrepresented anything! 

If we can get to a good draft point by tomorrow I can see about scheduling a meeting with Kristen and Lori either Friday or Monday to go over this and discuss the questions we still need answers to (also documented in the flow). I'm not sure if there's much more we can do without getting those questions answered first.

**Comment by zach-park** [comment]
> Mural

Hi @cgednalske , I've added some comments in the Mural. Thank you!

**Comment by cgednalske** [comment]
Meeting with Kristen today to go over these [userflows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1732046663886/09f5f082d33ea39fff3e7321b4c502d49c053b34) and pressing questions.

**Comment by loripusey** [comment]
I think it's good to close

**Comment by cgednalske** [comment]
@zach-park could briefly show the userflow(s) in demo tomorrow seeing as I'll be out? 

No need to show specifics, just show that there are two versions: 
- [One focused on demos plus setting pre-check-in status](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1732046663886/09f5f082d33ea39fff3e7321b4c502d49c053b34?wid=0-1732315856536)
- [One focused on demos only ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1732046663886/09f5f082d33ea39fff3e7321b4c502d49c053b34?wid=0-1732315834370)

Other things to mention: 
- We reviewed the questions and concerns around this initiative with Kristen today - digging into all the backend questions. (Brian and Lori can elaborate on these questions if needed)
- We also talked through how mobile will need to first add next of kin and emergency contact if we are to allow editing
- Kristen will look into how the backend work should be prioritized, which will determine the rest of the roadmap for this initiative. 
- In the meantime, there are screens within both userflows that will remain the same regardless. Zach will start designing these with the mobile app UI.
