### ISSUE TITLE
Design | VRE | Action Needed Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94254]
## Issue Description
_When a VA.gov claim fails to submit, VA.gov needs to email the Veteran letting them know they need to take additional action._

- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks
- [x] Customize failure email text with form details
- [x] Create failure email template in VA Notify

## Acceptance Criteria
- [ ] Failure email has been created in VA Notify
---

**Comment by fiorella-io** [comment]
Created action needed template for VR&E

<img src="https://github.com/user-attachments/assets/ba5958d2-228b-46ce-bfeb-aaff1fc71e91" width="70%">
