### ISSUE TITLE
Design | PCPG | Action Needed Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94252]
## Issue Description
_When a VA.gov claim fails to submit, VA.gov needs to email the Veteran letting them know they need to take additional action._

- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks
- [x] Customize failure email text with form details
- [x] Create failure email template in VA Notify

## Acceptance Criteria
- [ ] Failure email has been created in VA Notify
---

**Comment by fiorella-io** [comment]
Created action needed email for PCPG

<img src="https://github.com/user-attachments/assets/a0728f48-b735-48e0-a264-ba92baf2edb8" width="70%">

**Comment by fiorella-io** [comment]
We need to update the form number for this form's confirmation email.

I got the below warning when I tried to update the email template name. Do we need to update anything on Domo @steele-lm? 
![Image](https://github.com/user-attachments/assets/9767f86c-e008-445b-bed0-66d06d13052a)

**Comment by steele-lm** [comment]
@fiorella-io Good catch. I'll reach submit a request to the analytics team to update the template name. Is the new template name: Chapter 36 (form 25-8832) Confirmation?

**Comment by fiorella-io** [comment]
The form number should be (form 27-8832). I'll update the name after our sync with Dene
