### ISSUE TITLE
Copy of Add back end monitor for Silent Errors (Debts - BSG & DMC)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#94253]
## Description

Add back end monitor for Silent Errors:

- BGS Request
  - Error message
  - Backtrace
- DMC Request
  - Error message
  - Backtrace

## Tasks
- [ ] Add back end Error Message for BGS
- [ ] Add backtrace for BGS
- [ ] Add back end Error Message for DMC
- [ ] Add backtrace for DMC

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required

## Acceptance criteria
- [ ] Item one from the description performs as described in the description
- [ ] Item two from the description performs as described in the description

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by JunTaoLuo** [comment]
FYI I believe the error messages and backtraces was updated as part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/91367:
- https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/copay_notifications/new_statement_notification_job.rb

However, there is still Datadog Monitors to be updated for this job so I recommend using this issue to track that work:
- [ ] `new_statement_notification_job.rb`: Datadog Monitor need to be updated from `api_copay_notifications_new_statement_failure` to `api_copay_notifications_new_statement_retries_exhausted`
