### ISSUE TITLE
Alert user when there is an error generating their PDF

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#94257]
## Background
When a user clicks "Continue" on the Review page and there is an error generating the PDF for download:
1. Do not progress to the Download page, keep the user on the Review page which is technically the last step still in the Save in Progress experience.
2. Show an error on the Review page and encourage the user to click "Continue" again.
3. When the user clicks "Continue" again, try to re-send all of the information captured in the Appoint experience frontend to the backend for re-generating the PDF.

We would also like to monitor when this error occurs, but we can tackle that later in [#92287](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92287)

## Designs
[Desktop](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=11122-225739&node-type=frame&t=IGDah6NCIaisQbAw-0) and [Mobile](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=11122-226180&node-type=frame&t=SDTwo3fIAuLbKfiB-0)

![Image](https://github.com/user-attachments/assets/9c8b2259-cda7-400e-a011-f3b4fc20b21f)

## Tasks
- [ ] Create the alert as designed for (see above)
- [ ] Assign proper logic so the alert is displayed to users when there is an error generating a PDF
- [ ] In this scenario, ensure the "Continue" button re-sends information to the backend for re-generating the PDF

## Acceptance Criteria
- [ ] If our application has issues generating the PDF for download, the user is unable to progress to the Download page and instead sees an error on the Review page asking them to try again.

**Comment by oddball-lindsay** [comment]
Forthcoming PR for this, which will also address:
- This ticket
- "Back" button on the Select Representative screen (when navigating back there from the Review page)
- "Opens in a new tab" for the Find a Rep link, on the Select Representative screen

Will likely need help from the team to merge the PR after approved.
