### ISSUE TITLE
Design | PCPG | 36 | In-Progress Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94258]
## Issue Description
_When a user submits a claim on VA.gov, they should receive an email letting them know their claim submission is in-progress._

- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks

- [x] Create email template in VA Notify
- [x] Customize in-progress email text with form details
- [x]  update "What to do if you have questions" info
- [ ] update "ESTIMATED NUMBER OF DAYS BETWEEN SUBMISSION AND RECEIPT"

## Acceptance Criteria
- [ ] In-progress email has been created in VA Notify
---

**Comment by hubgitian** [comment]
## New In-Progress Draft Template
### VA Notify filename: `27-8832 Chapter 36 Submission In Progress - Draft`
**still to do:** update "what to do if you have questions" info
![Image](https://github.com/user-attachments/assets/2bbf4860-ad38-4648-8c24-28f47a23d630)

**Comment by hubgitian** [comment]
## VA Notify filename: `27-8832 Chapter 36 Submission In Progress - Draft`

The only thing left to add to this template, which I'm currently digging into is the "ESTIMATED NUMBER OF DAYS BETWEEN SUBMISSION AND RECEIPT" portion in the second paragraph. Otherwise this should be good to go pending a potential CAIA content review.

<img width="854" alt="Image" src="https://github.com/user-attachments/assets/49105a7d-451f-4414-95ee-1339d01c112f" />

**Comment by hubgitian** [comment]
### Content Approved by CAIA ✅
#### VA Notify filename: `27-8832 Chapter 36 Submission In Progress - Draft`

<img width="808" alt="Image" src="https://github.com/user-attachments/assets/60dcf2df-8b83-4f32-b3a8-0cff6b8e11ea" />
