### ISSUE TITLE
Add back end monitor for Silent Errors (FSR - VBA & VHA)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#94255]
## Description

Add back end monitor for Silent Errors:

- VBA Request
  - Error message
  - Backtrace
- VHA Request
  - Error message
  - Backtrace

The Debt Silent Error Report can be found [here](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.zenhub.com%2FattachedFiles%2FeyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejRjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ%3D%3D--4046e8d97922b810e9a613e66f6624aee0bbdcbf%2Fdebt_slient_error_report.xlsx&data=05%7C02%7CThomas.Davis%40GovCIO.com%7C926a663df388456f19a008dce36a5597%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C638635293065439262%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=8tFwg2%2Fwbo6vIHYsblhndlZQdn6FGaGxyi%2B43js%2FcOw%3D&reserved=0).

## Tasks
- [x] Add back end Error Message for VBA
- [x] Add backtrace for VBA
- [x] Add back end Error Message for VHA
- [x] Add backtrace for VHA - VBSSubmissionJob
- [x] Add backtrace for VHA - SharepointSubmissionJob

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required

## Acceptance criteria
- [ ] Item one from the description performs as described in the description
- [ ] Item two from the description performs as described in the description

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by JunTaoLuo** [comment]
FYI I believe the error messages and backtraces are all updated as part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/91367:
- https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/debts_api/app/sidekiq/debts_api/v0/form5655/vba_submission_job.rb
- https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/debts_api/app/workers/debts_api/v0/form5655/vha/vbs_submission_job.rb
- https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/debts_api/app/workers/debts_api/v0/form5655/vha/sharepoint_submission_job.rb

However, there is still Datadog Monitors to be updated for each of these jobs so I recommend using this issue to track that work:
- [ ] `vba_submission_job.rb`: Datadog Monitor need to be added for `api_vba_submission_retries_exhausted`
- [ ] `vbs_submission_job.rb`: Datadog Monitor need to be updated from `api_vbs_submission_failure` to `api_vbs_submission_retries_exhausted`
- [ ] `sharepoint_submission_job.rb`: Datadog Monitor need to be updated from `api_vha_sharepoint_submission_failure` to `api_vha_sharepoint_submission_retries_exhausted`
