### ISSUE TITLE
NOD | Release confirmation page updates

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#94268]
## Value Statement

**_As a_** member of the Decision Reviews Team
**_I want to_** release our Notice of Disagreement (NOD) confirmation page changes
**_So that_** Veterans can benefit from the content changes

---

## Background Context

We updated the NOD confirmation page to show all of the submitted form data to enable Veterans who print the page to see the choices and data they submitted to the VA. These changes are behind a feature toggle `nod_confirmation_update` which is currently enabled in staging, but disabled in production.

- Release plan?
- Project key dates?

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] Staged release of NOD confirmation page complete
- [ ] Release plan followed
- [ ] Monitor analytics post launch

## Designs and Build Notes

- Add here

### Enablement team (if needed)
@ member of team

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by comaurice** [comment]
Will add launch plan to this ticket

**Comment by Mottie** [comment]
NOD confirmation page needs an accessibility audit prior to release

**Comment by eileen-coforma** [comment]
DK is starting the accessibility audit

**Comment by comaurice** [comment]
[Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/nod-confpage-release-plan-2024.md). Expecting to release updates Dec 2nd.

**Comment by comaurice** [comment]
Released in Prod Dec 2nd. Closing as complete
