### ISSUE TITLE
Support: Unit Test silent failures

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#94264]
Unit Tests have been silently failing in CI, while the GHA check registers as a "pass" and allows them through. This has resulted in the main branch being inundated with 50+ failing tests. This needs to be corrected ASAP to ensure the integrity of production.

## Tasks
- [ ] Diagnose and correct the cause of the silent failures.
- [ ] Work with teams to get the failing tests sorted out, whether that's on the side of the test or the code it's testing.
- [ ] Get a deploy out to production

## Acceptance Criteria
- [ ] Daily deploys have resumed at their normal cadence.
