### ISSUE TITLE
Copy of COE | Trigger for In-Progress Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94266]
## Issue Description
_If there is an existing failure email notification, confirm that it is sent through VA Notify. If yes, stop using existing email template and start using new failure email notification template created for all benefit forms._

_If there is not an existing failure email notification, create a trigger that will send the VA Notify failure email template when a claim fails the backup submission pathway._

## Resources
- [VA Notify Platform Overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#successes)
- [VA Notify GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify)
- [VA Notify Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/VA%20Notify%20Playbook.pdf)
- [API docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#reviewing-our-api-docs)
- [Completing the "create trigger" tickets](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Strike/Completing%20Trigger%20Tickets/create_trigger.md)
- [Forms Strike Team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/form%20confirmations) can assist with setting up a confirmation email trigger

---
## Tasks
- [ ] If VA Notify is already leveraged, migrate failure notification to the new email template
If a failure email is not currently sent:
- [ ] Build notification code to call the VA Notify API
   - [ ] Notification should trigger an email when a submission fails the backup pathway (total failure)
   - [ ] The default email address should be the email the user entered into the form. If no email exists within the form, use their MyVA profile email.
- [ ] Test notification by logging into staging with a test user, updating the profile ID to something that sends to you
- [ ] Determine alerting and error handling if email fails to deliver

## Acceptance Criteria
- [ ] A notification trigger that sends an email to claimant when their submission fails
- [ ] Logging and monitoring for failed sends
