### ISSUE TITLE
Copy of Design | COE | In-Progress Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94260]
## Issue Description
_When a user submits a claim on VA.gov, they should receive an email letting them know their claim submission is in-progress._

- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks
- [ ] Customize in-progress email text with form details
- [ ] Create email template in VA Notify

## Acceptance Criteria
- [ ] In-progress email has been created in VA Notify
---

**Comment by hubgitian** [comment]
## Current Chapter 31 | 28-1900 emails (1 & 2 have identical content) 


The path is on submission it first tries to upload to vbms (#1) and Lighthouse (#2) is the backup path in case that fails.

1. **Chapter 31 (form 28-1900) Confirmation** | _Sent from_: `send_vbms_confirmation_email`
2. **Chapter 31 (form 28-1900) Confirmation (CMP)** | _Sent from:_ `send_lighthouse_confirmation_email`
3. **28-1900 Action needed** | _Sent from_: `send_vbms_confirmation_email`

## Screenshots
![Image](https://github.com/user-attachments/assets/43852e5b-2dfa-45a8-84ee-fde4c0034a92)
![Image](https://github.com/user-attachments/assets/834d09e2-bb13-4f1d-9565-eec8b1a90b0a)

cc: @AdamKing0126 @kingbmike

**Comment by hubgitian** [comment]
## **Form Submission in progress** template

The following template (once populated) is presumably what should replace the content of the emails listed in the previous comment ( `Chapter 31 (form 28-1900) Confirmation` ` 
Chapter 31 (form 28-1900) Confirmation (CMP)` ) as they already have triggers in place that match clicking the **Submit** button on the form.
<hr>

`# Your PLAIN LANGUAGE FORM NAME submission`

`Dear ((first_name)),`

`Thank you for submitting your PLAIN LANGUAGE FORM NAME AND VA FORM NUMBER on VA.gov. Our system receives most forms quickly. But sometimes, problems during the submission process prevent a form from getting to our system.`

`When we receive your form, we’ll send you another email to confirm that we have it. This process may take up to ESTIMATED NUMBER OF DAYS BETWEEN SUBMISSION AND RECEIPT days.`

`If there are any issues that prevent us from receiving your form, we’ll contact you to tell you what to do next.`

`^## Submission details`
`^`
`^__Form submitted__`
`^PLAIN LANGUAGE FORM NAME AND VA FORM NUMBER
`^
`^__Date submitted__`
`^((date_submitted))`
`^`
`^__Confirmation number__`
`^((confirmation_number))`

`## What to do if you have questions`

`Call us at CALL CENTER NUMBER (TTY: 711). We’re here DAYS AND HOURS OF OPERATION.`

`Thank you`

`---`

`You’re receiving this email because you submitted a form on VA.gov. Please don’t reply to this email. `
### Rendered Markdown
![Image](https://github.com/user-attachments/assets/6d61ae4e-da97-4c98-a7c5-0daa4889d5ac)

**Comment by hubgitian** [comment]
## New "In Progress" Email Template
### VA Notify filename `28-1900 Chapter 31 Submission In Progress - Draft`
![Image](https://github.com/user-attachments/assets/62495b21-e94f-4d03-a9ba-a1dd83d68cfb)

**Comment by hubgitian** [comment]
#### VA Notify filename: 28-1900 Chapter 31 Submission In Progress - Draft
This email is complete except for the following information
`ESTIMATED NUMBER OF DAYS BETWEEN SUBMISSION AND RECEIPT`
I'm currently researching the correct value to enter in for this.

<img width="832" alt="Image" src="https://github.com/user-attachments/assets/d44e16d7-df10-45ab-aae2-3cacb50b6ba0" />

**Comment by hubgitian** [comment]
### Content approved by CAIA ✅
**VA Notify filename: 28-1900 Chapter 31 Submission In Progress - Draft**

<img width="797" alt="Image" src="https://github.com/user-attachments/assets/2435fdc7-2fda-4595-83ee-143ca2c74945" />
