### ISSUE TITLE
Yellow Ribbon Part 2 - Content updates

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#9426]
## Issue Description
_Some content in the Yellow Ribbon search tool, and on Va.gov pages, needs to be updated after the launch of the tool_

---
## Tasks
- [ ] _1. New copy on tool landing page itself. Needs to be changed to: **Content below in first comment** per Jen Lee and Janice_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** TBD
- [ ] **Attached to an Epic** (#8347)
- [ ] **Labeled with Team** (Public Websites)
- [ ] **Labeled with Practice Area** (`frontend`, `design`, product`, ``content`)

**Comment by AnneHurley** [comment]
Copy on Yellow Ribbon tool landing page needs to be:
Find a Yellow Ribbon school
Find out if your school participates in the Yellow Ribbon Program. If you already have Post-9/11 GI Bill benefits, the Yellow Ribbon Program can help pay for tuition for associates or higher degrees. The amount of money you get varies by school, degree type, and the program you're enrolled in.

@jenniferlee-dsva  Capturing this here, pending review by Janice.
@stephorkandatx @RLHecht  FYSA

**Comment by RLHecht** [comment]
@AnneHurley One change to the above copy is it should be "associate or higher degrees." No plural for associates.

**Comment by jenniferlee-dsva** [comment]
@AnneHurley @RLHecht - The ^ feels awkward to me, with the plural degrees. It's slightly different from what Anne and I went over together, though I understand why we should keep the "If you already have" part. And we need to add "academic" in the last sentence. 

@RLHecht - could you copy check this: 

Find out if your school participates in the Yellow Ribbon Program. If you already have Post-9/11 GI Bill benefits, the Yellow Ribbon Program can help `**you** `pay for tuition for `**an** `associate or higher `**degree**`. The amount of money you get varies by school, degree type, and the program you're enrolled in. The amount of money you get varies by school, degree type, and the `**academic** `program you're enrolled in.

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  thanks much.

**Comment by jenniferlee-dsva** [comment]
Doh - Caught a duplicate sentence above - will edit out. @kelsonic @RLHecht ^

**Comment by RLHecht** [comment]
The above text looks OK to me @jenniferlee-dsva @kelsonic @AnneHurley

**Comment by RLHecht** [comment]
This has been validated on live site. Closing ticket. FYSA @stephorkandatx
