### ISSUE TITLE
Design | 674 | Action Needed Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94278]
## Issue Description
_When a VA.gov claim fails to submit, VA.gov needs to email the Veteran letting them know they need to take additional action._

- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks
- [ ] Customize failure email text with form details
- [ ] Create failure email template in VA Notify

## Acceptance Criteria
- [ ] Failure email has been created in VA Notify
---
