### ISSUE TITLE
[BE] 10-10EZ - Facility page: Remove checkbox for "minimum essential coverage"

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#94276]
## Benefit to the Veteran
As a Veteran, I want to ensure the information I provide on the 10-10EZ be usable and actionable, so that I can be confident with my answers/designations.

## Scope
During review of the form updates provided in June 2024 and discussing with the HEC stakeholders, we found that the checkbox for a Veteran to indicate that they are "enrolling to get minimum essential coverage under the Affordable Care Act" was removed from the paper form and is no longer needed on the online form.

This field is required on the backend and sent to VES.  We send a value to VES to indicate whether the box is checked or not.
Removing this from the schema could result in failed submissions, due to the VES requirement of having a value.

We need to determine whether VES can make a change to remove this field or have it set as "optional".  We also may be able to make changes to the schema to always send an "unchecked" value until the VES change can be made.

## Tasks
- [ ] Confirm with Joshua Faulkner that the field is required to have a value to be accepted by VES
- [ ] Discuss possibility of having VES make the change, and what steps are needed to get that scheduled
- [ ] Update schema to default to the unchecked value
- [ ] Complete regression testing to ensure there are no impacts to form completion and submission
- [ ] Review with PM
     - Signoff is required in the comments prior to launch
- [ ] Launch to production

## Acceptance Criteria
- EZ submissions are accepted in VES with no impact to Veterans as a result of this backend change.

**Comment by hdjustice** [comment]
Chk with JF on VES field reqs

**Comment by hdjustice** [comment]
Confirmed with Josh Faulkner that the attribute `<ns0:acaIndicator>false</ns0:acaIndicator>` is required in the schema and should have a default value of "false" if the checkbox is removed from the UI.  The application will not be accepted and processed if it is missing this attribute.  
We have removed the checkbox in ticket #93819 and will close this ticket with no further action required.

**Comment by longmd** [comment]
@hdjustice , we can reopen and look to do some clean-up work. We can clean up the schema to remove the contract between the FE & BE, then default the value being sent from the BE to VES to be `false` before ultimately removing sending the `false` value from the FE to the BE with every submission.

**Comment by hdjustice** [comment]
alrighty, if that is a nice clean way to do things, I am for it.  I will reopen, readjust the info and we can review

**Comment by coope93** [comment]
[Merged step 1 of `vets-json-schema`  in `vets-api` to make `isEssentialAcaCoverage` optional. ](https://github.com/department-of-veterans-affairs/vets-api/pull/22720)
