### ISSUE TITLE
Design | 674 | Claim Received Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94277]
## Issue Description
_New confirmation (received) email templates are available. We need to review the current template the form is using and determine if updates need to be made. Stage 3 SZF_

- [Current emails](https://docs.google.com/document/d/1kkbkDhgaGJuNrJbz2uHZGWAmbAq0ac21_nkpDQ8FkTc/edit#heading=h.nvwukvkz72q6) in use that need to be updated.
- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

Current confirmation email:
<img width="645" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3ZRQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b6dfd717cdaaf9aac754c9d52b55efca053d256/image.png" alt="image.png" />

---
## Tasks
- [x] Review current confirmation email and determine if changes need to be made to align to updated template
- [x] If changes do need to be made, update existing confirmation email template in VA Notify

## Acceptance Criteria
- [x] Confirmation email template is updated in VA Notify

**Comment by steele-lm** [comment]
@ajialeilani I wasn't sure if there was a separate confirmation email for 674 or if the 686/674 shared an email, but I created a standalone ticket for 674 just in case.

**Comment by ajialeilani** [comment]
Updated 686c [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82901#issuecomment-2400379328)

**Comment by ajialeilani** [comment]
Will have draft ready in [Canvas](https://dsva.slack.com/docs/T03FECE8V/F07S0PD89MY) by EOD. Call with Fiorella to review.
