### ISSUE TITLE
Design | 686/674 | ZSF Confirmation Page MVP

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94287]
## Issue Description
_When a user submits a claim on VA.gov, the confirmation page should allow them to check the claim's status and outline what's next._

- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status#showing-form-submission-status-on-the-form-confirmation-pages).
- [Confirmation page template](https://www.figma.com/design/dlhofkIJz3MC81PD0pJAb8/OCTO-%7C-Form-Status-Project-(VFF-%2B-My-VA)?node-id=69-82688&node-type=frame&t=orq6V1C4T9yfiiS0-11)
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks
- [x] Update confirmation page designs to:
   - [x] Align to design system guidance for application status
   - [x] Align to design system guidance for "what's next" info

## Acceptance Criteria
- [x] [Wireframe](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=2776-51211&node-type=frame&t=enDBpERdNZmmSsIn-0) that includes application status updates and what's next info
---

**Comment by steele-lm** [comment]
This work is blocked until there is design system guidance established for pdf downloads on the confirmation page. This [slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1724180305823079) highlights teams currently working on designs.

**Comment by ajialeilani** [comment]
Updated success alert and `What to expect` section in [Figma](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=2776-51211&t=hIB141nGEYT36l8t-1). 

Looking into whether we need to conditionally add the pension intake mailing address.
