### ISSUE TITLE
Terraform Cleanup: Updates to Terraforms, Sandbox environment

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#94294]
## User Story
As the managers and developers of the VA Platform and specifically the Platform Terraform clusters,
We need to perform updates to the Sandbox environment when cleaning up the Terraforms, 
So that the the Terraform clusters within the Sandbox environment are properly maintained.

## Issue Description
As discovered in [discovery documentation](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3463512080/AWS+Elasticache+Redis+Discovery+and+Results) for the Redis POAM, Redis clusters need to be recreated in order to support encryption in-transit and encryption in-place. 
The Terraforms in the devops repo reference an external Terraform module specific to vets-api resources. The code from [this documentation](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3463512080/AWS+Elasticache+Redis+Discovery+and+Results) needs to be adapted and added. 
- The resources labeled as NEW RESOURCE above need to be added to this Terraform module, with appropriate, environment-specific names/naming/labeling. These resources need to be created for each cluster within the environment.
- The resource labeled EXISTING RESOURCE will only need to have the following lines added to it’s definition. _Note:_ Refer to the discovery doc [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3463512080/AWS+Elasticache+Redis+Discovery+and+Results) for access to the code (these are just images)
![Image](https://github.com/user-attachments/assets/8b59f7b7-06e5-493f-89f2-f2026eb23fab)
- A variable named vets_api_redis_password will need to be introduced in [variables.tf](https://github.com/department-of-veterans-affairs/prt-preview-manifest/tree/master/terraform/variables.tf). _Note:_ Refer to the discovery doc [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3463512080/AWS+Elasticache+Redis+Discovery+and+Results) for access to the code (these are just images)
![Image](https://github.com/user-attachments/assets/9267dc49-bc83-40c2-af21-96a71a860be3)

It is important to remember these two points while doing this work in any of the environments: 
- For the production upgrade, vets-api will have to experience downtime. During this downtime, vets-api will have to be taken offline entirely so that a backup can be made of each Redis cluster. The backups will subsequently be referenced as the source of data for the newly created clusters that get spun up with the required security enhancements.
- After the upgrade to the new clusters, vets-api will have to be deployed to reflect the changes in the Redis endpoints.
- A variable named vets_api_redis_password will need to be introduced in [variables.tf](https://github.com/department-of-veterans-affairs/prt-preview-manifest/tree/master/terraform/variables.tf)
- Along with these changes, this Terraform module will need to be tagged and release according to the changes outlined above, perhaps even a **major version** upgrade.

## Tasks
- [ ] Vets-api has to be brought down in the Sandbox environment. This will be done by scaling the replicas in the deployment down to 0.  _Note:_ Refer to the discovery doc [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3463512080/AWS+Elasticache+Redis+Discovery+and+Results) for access to the code (these are just images)
![Image](https://github.com/user-attachments/assets/df0b3526-acea-4160-ac6f-433ebdab9d0b)
- [ ] A manual backup has to be made of each Redis instance in the cluster 
- [ ] Starting with [dev](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/dsva-vagov-dev/main.tf#L283) environment, an upgrade to the new version from step 2 in [Rollout Steps](https://vfs.atlassian.net/wiki/spaces/PPT/pages/edit-v2/3463512080#Rollout-Steps) needs to be carried out. This is accomplished by updating the release number in the devops Terraform to that of the release that resulted from step 2 in Rollout Steps.
- [ ] A Terraform -var-file has to be created. _Note:_ Refer to the discovery doc [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3463512080/AWS+Elasticache+Redis+Discovery+and+Results) for access to the code (these are just images)
![Image](https://github.com/user-attachments/assets/68701f59-bc51-4ff7-b1ac-8bad56cd8a66)
- [ ] A targeted tf plan should reflect the changes introduced by the new version. _Note:_ Refer to the discovery doc [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3463512080/AWS+Elasticache+Redis+Discovery+and+Results) for access to the code (these are just images)
![Image](https://github.com/user-attachments/assets/c3fdf7ae-2422-4a4d-bfd3-374ed63d6437)
- [ ] In that case, tf apply tfplan.out can be run
- [ ] After all the clusters are upgraded, any sanity checks can be made before redeploying the application
- [ ] The deployment should also negate any need for scaling the previous deployment back up.

## Success Metrics
The Redis Terraform clusters will be updated in such a way that they can support encryption in-transit and encryption in-place in the Sandbox environment. 

## Acceptance Criteria
- [ ] Sandbox environment will have updated and tested Redis clusters that will, once the rest of the environments have been upgraded, can support encryption in-transit and encryption in-place. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by AshleyGuerrant** [comment]
This ticket is stale and the [Terraform upgrade](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98290) has already been completed. Closing out.
