### ISSUE TITLE
Edit presentation slides for meeting with Shane next week

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#94295]
## Tasks

- [ ] Make updates to slide deck for next IPT conversation with VeText. Include the following:
  - [ ] Goals: Increase PCI utilization and bene travel
  - [x] Use alternative solution 1 but change messaging a bit; make it clear that there's two steps, 1) bene travel (optional) (might need messaging if this has already been completed), and 2) check in, where there's two paths, 1) is go up to MSA, or 2) is to complete eCheck-in, which will update the check in status to CHECKED IN in VistA (but tell Veteran to go tell staff that you've arrived)
  - [ ] We want to pilot this at 1 or 2 facilities, so we probably can't change much with VeText 
  - [ ] List out VeText questions to bring up, e.g., what problems does VeText foresee with these changes, especially knowing that sites can change their own templates? Does VeText see any other opportunities that are feasible right now to meet our goals?

**Comment by benbrasso-agile6** [comment]
@loripusey @cgednalske I capture our to-do's? Any changes?

**Comment by loripusey** [comment]
When I raised my hand the other day in the IPT meeting but no one could hear me, I was going to weigh in that this all seems like we are significantly increasing the complexity of eCheck-in (in terms of trying to explain to the Veteran what's going on) all because we don't want to put effort into training staff to properly use & configure eCheck-in. So, I'm not really comfortable with the choices we are being asked to make. But, I also recognized that it is not my call, so I guess I have no changes.

**Comment by benbrasso-agile6** [comment]
Oh, yeah, Christina and I feel the same way. 

I created that slide that lists out the factors that are contributing to the problem, but Kristen had asked us to breeze through the background. So, I didn't spend time on it.

**Comment by benbrasso-agile6** [comment]
I guess I should post that presentation in the channel if I still have access to it... just as an FYI

**Comment by benbrasso-agile6** [comment]
Yeah; I lost access since I didn't join from the VA network; here's the link to the PDF, if you have access to the chat and feel like posting. But, no big deal.

https://dvagov.sharepoint.com/:b:/s/AppointmentsUXSync/Efw3ivysXEpBhLyoL2Ef9tsBkixTIeb-zN9JoVMOj57FFg?e=ouTapF

**Comment by cgednalske** [comment]
Looks good! Only comment I have is that I think there are a few things we'd want to work out for how exactly the alternative solution would be approached. We've already identified the options of a) a rebrand with multiple paths or b) a rebrand where the content stays closer to as is (whether called check-in or not), so probably good to take a look at both options. Like what's the most efficient way to do this where we only change what we have to and don't disrupt Veterans' expectations too much?  It will really rely on content nuances - yet those could change the experience significantly. 

@benbrasso-agile6 do you think we can work on a couple high-level userflows showing the direction(s) we're now thinking? It will probably be helpful if everyone can clearly visualize.

**Comment by benbrasso-agile6** [comment]
Sure, let's meet to talk it through; I don't think we need to spend too much work on things at this point knowing that it should just be a re-hash of the conversation we had, but with Shane.

**Comment by benbrasso-agile6** [comment]
![Image](https://github.com/user-attachments/assets/77dc3f73-ff24-467a-b600-d4bde190d1b0)

**Comment by benbrasso-agile6** [comment]
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1728071978841/e1438601814caf818468eca4eb1cb8a06dfdbc9a?sender=ua2ec2e34eb6128f3375e0207

**Comment by benbrasso-agile6** [comment]
Let me add this pres in Git real quick before closign

**Comment by benbrasso-agile6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2024-10%20Check%20in%20with%20an%20MSA%20after%20eCheck-in%20experiment%20in-person%20UAT%20with%20Veterans%20and%20clinic%20staff/readme.md
