### ISSUE TITLE
FMB Phase 6 IA plan

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#94310]
```[tasklist]
### Tasks
- [x] IA tickets created
- [x] Completed [mural template](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684260449054/7d2a6588b6861b0fb19a31d73cad49fe1a5abd3d?wid=0-1727988977544)
- [x] Completed [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/family-hub-phase-6-housing.md)
- [x] [Redirect ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94859) created
```

**Comment by kristinoletmuskat** [comment]
Prep is done
