### ISSUE TITLE
526EZ Incoming Issues

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/va.gov-team#94324]
## Issue Description
Remove the `if Flipper.enabled?` call from app/sidekiq/evss/disability_compensation_form/submit_uploads.rb line 34

### Background Information
https://dsva.slack.com/archives/C053U7BUT27/p1728023310065679

> A reminder to make sure that you are getting rid of feature flags when they are no longer needed.
> This is because there is a bug in the job that adds new feature flags and deletes outdated ones from the database - it occasionally deletes out flags that should still be active.  The flags are usually re-added shortly thereafter but these "new" flags are set to off.  As a result of this the feature flag delete job has been disabled, but occasionally someone forgets this and manually rerun the job occasionally, causing problems for apps.  Good to be on the safe side and avoid this risk.  Thanks!

Name of Requester: Steve Albers

Relevant Dates/Timeline: No

**Content artifacts**

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] 
- [ ] 

## How to configure this issue
- [ ] Attached relevant links/slack threads
- [ ] Labeled with Type (`bug`, `request`, `discovery`, `documentation`, etc.)
- [ ] Labeled with Urgency** (`urgent`, `high priority`, etc.)
