### ISSUE TITLE
[CDP] Payment disclaimer and small bug updates

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#94331]
## Add payment disclaimer to Overpayment summary page
`va.gov/manage-va-debt/summary/debt-balances`

Add 

> Please note that payments may take up to 4 business days to reflect after processing. 

<img width="1360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9f58fa4debab4f2607ad7be07c944863153ae74/Screenshot%202024-10-02%20at%202.39.50%E2%80%AFPM.png" alt="Screenshot 2024-10-02 at 2.39.50 PM.png" border="4" />

## Remove payment disclaimer from Debt and Bills Overview page
`va.gov/manage-va-debt/summary`

Remove
> Any payments you may have made to your copay bills will not be reflected here until our systems are updated with your next monthly statement.

Before:
<img width="1282" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU1qQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53fa669900419afc77bc5e2138acc0edc1f5762b/Screenshot%202024-10-04%20at%209.38.59%E2%80%AFAM.png" alt="Screenshot 2024-10-04 at 9.38.59 AM.png" border="4" />
After update:
<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d4b1fa1a2134322c0e223b83d0b2d6bfaadd5af/Screenshot%202024-10-04%20at%209.39.16%E2%80%AFAM.png" alt="Screenshot 2024-10-04 at 9.39.16 AM.png" border="4" />

## Update text on Overpayment Detail page
`va.gov/manage-va-debt/summary/debt-balances/details/[customID]`

Remove 
> You can check the status of this debt.

> Debt letter history (caption only)

Add text to caption field

> Find dates and summaries for the letters sent to your address on file below.

Before:
<img width="1486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTBqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--432cb115fcacd8c02f58517c1c433a86c5394244/Screenshot%202024-10-04%20at%209.46.55%E2%80%AFAM.png" alt="Screenshot 2024-10-04 at 9.46.55 AM.png" border="4" />

After:
<img width="1376" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkFqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8472c005a730175518631570ee163d344a56a83/Screenshot%202024-10-04%20at%209.47.51%E2%80%AFAM.png" alt="Screenshot 2024-10-04 at 9.47.51 AM.png" border="4" />

## Update alignment and text on Overpayment Detail page
`va.gov/manage-va-debt/summary/debt-balances/details/[customID]`

On desktop, Current and Original balance should be top aligned and Current balance should have a right margin.
On mobile, Current and Original balance should stack on top of each other (without a left or right margin).

Before:
<img width="1360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkVqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ed43fc28aab6b1012a94bf9ef81d38eded1e441/Screenshot%202024-10-04%20at%209.50.46%E2%80%AFAM.png" alt="Screenshot 2024-10-04 at 9.50.46 AM.png" border="4" />

After:

<img width="1438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c41b70bb16fbb076d2db29967cf4884370e2b7f9/Screenshot%202024-10-04%20at%2010.19.33%E2%80%AFAM.png" alt="Screenshot 2024-10-04 at 10.19.33 AM.png" border="4" />

## Tasks
- [x] Update Overpayment summary page
- [x] Update Debt and Bills overview page
- [x] Update Overpayment detail page

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required

## Acceptance criteria
- [x] Updates made to Overpayment summary page, Debt and Bills overview page, Overpayment detail page

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by OptionSelect** [comment]
Per convo with Megan, addtl work to be done <img width="1458" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVU3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a11a54ee5da1a4ec761fe74864c88c97fc73ed3/image.png" alt="image.png" />

**Comment by mgleo** [comment]
**Overpayment detail page:**

Any date listed, including on transaction history table, should be in this format _September 6, 2024_ 
[See design system page](https://design.va.gov/content-style-guide/dates-and-numbers)
<img width="250" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzQ4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4b69cb9b97ca09d220e6a5ab39e5821848445d5/Screenshot%202024-10-10%20at%203.42.57%E2%80%AFPM.png" alt="Screenshot 2024-10-10 at 3.42.57 PM.png" />
<hr/>

**Debt details**:
Both title should be in Source Sans Pro
09/06/2024 should be "September 6, 2024"
> Current balance as of September 6, 2024
> Original overpayment balance:


$Amounts font size should be 1 step lower in size.
> $120.40
>$166.67


<hr/>

On desktop, there should be 40px horizontal spacing between _Current_ and _Original_ section

<img width="1160" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1U3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dd22690f2a82c6606046917696e3eeff2e85de7/Screenshot%202024-10-10%20at%203.37.55%E2%80%AFPM.png" alt="Screenshot 2024-10-10 at 3.37.55 PM.png" />

<hr/>

On mobile, there should be 32px vertical spacing between _Current_ and _Original_ section
<img width="270" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1k3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbe14de72c1b60c0a72e9c1b3267cb8330587036/Screenshot%202024-10-10%20at%203.38.27%E2%80%AFPM.png" alt="Screenshot 2024-10-10 at 3.38.27 PM.png" />
