### ISSUE TITLE
DMC time out issue investigation

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#94342]
## Description

As VODA has seen notifications in the [Alert ](https://dsva.slack.com/archives/C02EYV9NJFJ)channel we began to investigate some time out issues related to the DMC communication. Several steps were taken already to minimize the issue but after DMC shared some concerns on the ability of the service to manage the load from VODA we wanted to collect some additional data here to support a solution.

#### **Our Research**

- **Question:** How many times a day are we calling DMC?
  - **Answer:** Average for the past 6 days is 247.531k with a max of 317.26k and a minimum of 107.59k
- **Question:** How long have we seen these time out issues for?
  - **Answer:** Largely began June 11th of this year
 <img width="1112" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzBtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f4ba63bb0fce0f7f3dca8b069c5b7ab87141aa3/image.png" alt="image.png" />
- **Question:** Did anything change in recent month (on our end or DMCs) that may be causing the influx?
  - **Answer:** No changes have been made on our side until these errors began. We then began mitigation efforts on our side. First, we extended the timeout on our side from 15 seconds to 30 seconds (DMC timeout maximum). After this, we implemented caching on our side. We cache empty responses from DMC to prevent repeated requests, our caching implementation deployed on July 25th.
Denise informed us that the DMC had made some changes on or around July 8 - 12th
> DMC has done some work on their education debts and apparently because of that work which happened between July 8-12.. their infrastructure is getting a ton of calls from these other calls.
So the current thought is it is them that is causing DMC not to be robust enough.. not us calling them.
- **Question:** In our opinion is that really an unexpected load?  (I anticipate this will only increase.)
  - **Answer:** We cannot find any extraneous calls. We have found a possible temporary solution where we disable the debts request being fired from /my-va/
- **Question:** How many of those calls result in a response of "no-debts"
  - **Answer:** I originally answered this question thinking the question was about _failed responses_. I will answer both instances of empty/no-debts and failed responses
    - **Empty/no-debt responses:** Note the graphic below from the past 7 days. About 1/2 of all responses were empty. Of those cached empty responses, 30% were returned (this is where we returned the cached response instead of making a request to DMC)
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU1tQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdbe512ef1424020b2c6eae2e407751a500bb232/image.png" alt="image.png" />
    - **Errored responses:** This is tough to tell exactly. Vast majority of errors are either 504 or 503. 504 being "Time out" and 503 being "Unavailable". vets-api will halt requests after a 50% error threshold is met. It takes 30 seconds to timeout, I doubt vets are waiting 30 seconds. See graphic below:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEFtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8fea6666881cd6a3b1297a5dd077266a600841fb/image.png" alt="image.png" />

- **Question:** Can he explain the caching steps that have been taken. i.e what are we caching,  how long are we caching the results, etc.
  - **Answer:** When the veteran visits specific pages, a request is made to DMC. When the response comes back, we check if the response is 'empty' (no debts). If the response is empty, we save/cache the response. This cached response is saved until 5AM daily. If the veteran navigates to a page that makes the DMC request the same day, we will return the cached response instead of making the request to DMC. Once we go past 5AM, the cached response is deleted to keep up-to-date with latest data. If there _are_ debts in the response, we do not cache and run a request every time. See graphic below (past 2 days):
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE1tQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1aab9ba6759a78bfd72502e08b45347dc0e5898d/image.png" alt="image.png" />

#### **Separately (regarding BGS)**
- **Question** Does BGS even have information they can share about if a Veteran has a debt? If so what is the timeline of what they have? Can they share paid debts, debts from 6 months ago etc?
  - **Answer:** We had a meeting with the DMC team on 10/3 where we discussed additional approaches. We are waiting for a contact within BGS to help us find a BGS request that we can use to determine if a veteran has debts.
- **Question** What are VODA's concerns about pinging BGS for file number and debt status - followed by then calling DMC.  Do we think that will increase wait times for Veterans for example?
  - **Answer:** This is the current flow to get debts:
    - Request to BGS to get Filenumber
    - Request to DMC using Filenumber to retrieve debts

Inherently, adding requests to other systems increases possibility of error.

[A while back, I looked into removing the BGS request to get the Filenumber](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/zh/594). It looks promising to use the "birlsId" and remove the BGS request for the filenumber.

We should see what the BGS request that we are considering returns. Maybe it returns filenumber too.

## Tasks
- [x] Complete the answers for the posed questions.

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [x] All the questions are answered.
- [ ] If needed or available any documentation is created and linked here.

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by denisecoveyduc** [comment]
Thank you for this detailed summary! I am going to synthesize this and also share with our DMC partners to hopefully entice them to make some changes on their end.
