### ISSUE TITLE
Toxic Exposure: Remove dates from LH submit request for unselected location/hazard options 

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#94369]
## Issue Description
When a user selects a particular hazard or location option (e.g. "Iraq"), enters a partial date for the option, but then goes back and deselects that option- this partial date (e.g. "XXXX-03-XX") makes it to the backend as-is, then on to the submit request to Lighthouse (where it results in a non-retryable error). We should also guard against the possible scenario of submitting full, valid dates for options that were unselected.

---
## Tasks
- [ ] Modify `transform_multiple_exposures` ([link](https://github.com/department-of-veterans-affairs/vets-api/blob/941ebae5f21cf0446abed0b26e0597634d949300/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb#L315)) to filter out dates where the option was set to `false`
- [ ] Write unit tests against this scenario

## Acceptance Criteria
- [ ] Dates associated with unselected location/hazard options are omitted from the LH submit API request

## Related Links
- [slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1728062433929929?thread_ts=1727124599.563729&cid=C01DBGX4P45)
- [slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1727982567748269)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
