### ISSUE TITLE
Quarterly Debt Portal Outage Tracker

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#94364]
## Description

Starting this quarter we will be updating the Debt Portal Outage Tracker located [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/back-end/outage-tracker.md).

## Tasks
- [x] Update the document for last quarter (July, August, September).
- [x] Monitor for new outages.
- [x] Debt Portal Outage Tracker when an outage is detected.

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] The report is updated and complete.

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by Tom-Davis** [comment]
@digitaldrk here is the new ticket for the report @denisecoveyduc asked for us to create. We can update the GitHub page if we see a better layout for the data.
