### ISSUE TITLE
Migrate from Zenhub to Github Projects

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#94393]
## Background
The team has been seeking an alternative to Zenhub, and it seems like the VA is leaning strongly towards Github Projects.

## Tasks
- [x] Migrate all issues to GH Project
- [x] Create custom fields
- [x] Setup the current sprint
- [x] Organize issues on the full board into the correct priority 
- [x] Add estimates to issues
- [x] Create milestones for each feature version (possibly use GH's parent tickets instead)
- [x] Move issues from epics (ZH) to milestones (GH)
- [x] Confirm issues without milestones is accurate
- [ ] Categorize issues by features (labels vs. custom field?)

## Acceptance Criteria
- [x] The Zenhub board has been fully migrated to an ARM Github Project
- [x] The Github Project has full functionality parity with Zenhub

**Comment by oddball-lindsay** [comment]
Curious to learn more about how the IIR team uses the sprint continuation field, since I can't seem to filter the view to see both `sprint:@current,@previous` and `continuation:@current`

**Comment by oddball-lindsay** [comment]
Using Parent tickets for most epics, with the exception of development for Appoint MVP since there are more issues than the 50 sub-issue limit -- will be using a milestone for that.

The categorization of features by labels or a custom field is a "nice to have" with no immediate need. It's also quite manual to classify each issue, so I will save that for a later time if/when the need arises.
