### ISSUE TITLE
[CST] Create a job to poll Upload Status

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#94404]
## Background Context

In an effort to have zero silent failures we need to poll LH document end point to know when an evidence submission has failed.

When the polling job beings the `evidence_submission` table will have records with a status of `PENDING`, we reach out to the lighthouse API to get the status of those `PENDING` records (we provide the request_id) then lighthouse returns to us the statuses (PENDING, FAILED, SUCCESS)

- If the status is `PENDING` we don’t do anything and retry later
- If the status is `SUCCESS`, we update the `evidence_submissions` table with a delete date (+ 60 days from current date) and update the status to `SUCCESS`
- If the status is `FAILED` then we update the `evidence_submissions` table with a `FAILED` status and populate the acknowledge_date with a date of 30 days from the current date.

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- [List of document statuses](https://developer.va.gov/explore/api/benefits-documents/docs?version=current)

Statuses: 

- IN_PROGRESS: the workflow is currently executing.
- SUCCESS: the workflow has completed all steps successfully.
- FAILED: the workflow could not complete because a step encountered a non-recoverable error.

Endpoint: 
UploadRequestAsyncProcessingStatusBulkResponseV1.UploadRequestStatuses

</body>
</html>

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] Look at 526 implementation to see how they do this
- [x] Lift and shift what we can
- [x] Create a job that hits the lighthouse endpoint: UploadRequestAsyncProcessingStatusBulkResponseV1.UploadRequestStatuses and update the evidence_submission table with the new statuses. 
- [x] Populate the delete_date to  + 60 days when a file upload is successful
- [x] Populate the status to SUCCESS when a file upload is successful
- [x] Populate the status to FAILED when a file upload is FAILED
- [x] Populate the acknowledge_date to + 30 days when a file upload is FAILED
- [x] Need to add the following fields to the evidence_submissions table
               acknowledge_date
               delete_date

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] Create a job that hits the lighthouse endpoint: UploadRequestAsyncProcessingStatusBulkResponseV1.UploadRequestStatuses and update the evidence_submission table with the new statuses. 
- [x] `delete_date` is set to  + 60 days when a file upload is successful
- [x] `status` is set to SUCCESS when a file upload is successful
- [x] `status` is set to FAILED when a file upload is FAILED
- [x] `acknowledge_date` is set to + 30 days when a file upload is FAILED

**Comment by pmclaren19** [comment]
@jerekshoe @samcoforma Hey guys are we going to be doing polling with EVSS? if so will that be handled in this ticket or another one?

**Comment by jerekshoe** [comment]
We can’t, EVSS doesn’t have a way for us to check the status of documents they have accepted

**Comment by samcoforma** [comment]
@jerekshoe @pmclaren19 The 526 team is hitting the Lighthouse upload status endpoint with batches of 100 documents to poll per polling request. Can you think of a reason for us to use a different number of documents for any reason?

**Comment by jerekshoe** [comment]
> [@jerekshoe](https://github.com/jerekshoe) [@pmclaren19](https://github.com/pmclaren19) The 526 team is hitting the Lighthouse upload status endpoint with batches of 100 documents to poll per polling request. Can you think of a reason for us to use a different number of documents for any reason?

Not that I can think of, though there may be reasons to think about it once we have the ability to collect more data. Main thing I can think of would be the volume of uploads we handle vs the volume they handle but 100 may work just fine regardless honestly

**Comment by pmclaren19** [comment]
@jacobworrell created [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97199) ticket , since its currently blocking our work here!
