### ISSUE TITLE
[CST] Migrate EVSS::DocumentUpload exhaustion handler to Lighthouse::DocumentUpload

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#94406]
## Background Context
Once we have the Sidekiq exhaustion handler for the `EVSS::DocumentUpload` job created, we want to create a similar one for the `Lighthouse::DocumentUpload` job. This will allow us to send failure emails to Veterans when the `Lighthouse::DocumentUpload` exhausts its retries.

### New Feature
- Why are we doing this work?
- Epic Link

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] Create a new Sidekiq exhaustion handler based on the one used for the `EVSS::DocumentUpload` job
- [ ] Write rspec tests for the new Sidekiq exhaustion handler

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] The sidekiq exhaustion email functionality for EVSS has been transferred over to LH
- [ ] We can test the sidekiq job failure in Staging
