### ISSUE TITLE
Collaboration Cycle - Bring notifications standards into the Collaboration Cycle

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#94414]
## Status

| Date | Status | Launch Date | Notes |
| ----- | ------ | ------------------------- | ------ |
|3/18/2025| Complete |      | Work complete. |
| 2/26/2025 | In Progress| On track | Aligned on priorities. Should close next sprint.|
| 2/4/2025 | In Progress| Paused | Syncing with Matt on 2/7 to align on priorities. No work in progress this sprint.|
| 1/15/2025 | In Progress| On track | Planning to make updates to design intent artifacts this upcoming sprint. Need to pivot initiative details away from discovery. |
| 12/18/2024 | In Progress| On track | Met with VANotify. May need to pivot from discovery. Will discuss with PO |
| 11/14/2024 | Not Started | On track | Still refining with team and will share with OCTO before work begins |

## Problem Statement 

The zero silent failures work ([see initiaitve](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91771)) allowed OCTO-DE to recognize that there are more issues than just the silent failures. For example, Governance recently learned that if a VA facility cancels an appointment that a Veteran has, the Veteran is only notified if they log into VA.gov. There is no email or text message sent to notify the Veteran of their cancelled appointment.

To address the lack of necessary email and/or text notifications to the Veteran, Governance team [recently introduced](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94416) a new [VA.gov Experience Standard](https://design.va.gov/about/experience-standards/#user-receives-appropriate-notification-from-the-va-or-vagov-about-the-status-of-their-request) that states the following:

> User receives appropriate notification from the VA or VA.gov about the status of their request.

Governance team now knows that Veteran's must receive notifications about their form submission status (per ZSF). We also are aware that the VA would like to make sure the Veteran receives notifications about the status of their appointment (per the appointment example above). However, it is not clear to Governance team what other scenarios would require a notification via text or email. (For example, at the [Midpoint Review with Appointments Team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87703) on 11/14/2024, their PM shared that they have considered sending a notification if/when the appointment request sits idle for 30 days).

The objective of this initiative is to determine in what scenarios we would require a text or email notification to be sent to the Veteran so that we can plan to enforce in the Collaboration Cycle.

How might Governance team identify the scenarios in which a notification would be a requirement?
How might we communicate these scenarios to VFS teams?

## Hypothesis or Bet

- If we understand the existing scenarios in which notifications are currently sent, then we will be able to ascertain which scenarios are critical vs. nice, but not necessary.
- If we identify the scenarios in which a notification would be a requirement, we will be able to help ensure that Veterans receive communications outside of VA.gov for critical information. 

## We will know we're done when... ("Definition of Done")
*What requirements does this project need to meet for you to finish this initiative?*

- [ ] We have identified which scenarios on VA.gov would require a notification via text/emails/push.
- [ ] We have determined what additional education on notifications may be needed for our practice area specialists
- [ ] We have identified if our process for supporting the Collaboration Cycle Kickoff needs to be modified to support notification standards. 
- [ ] We have identified if our process for supporting the Design Intent needs to be modified to support notification standards. 
- [ ] We have identified if our process for supporting the Midpoint Review needs to be modified to support notification standards. 
- [ ] We have identified if our process for supporting the Staging Review needs to be modified to support notification standards. 

## Known Blockers/Dependencies 
N/A

## Projected Launch Date
TBD

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1912569976/Platform+Product+terminology?atlOrigin=eyJpIjoiM2VmNzY2MTZkZWE4NGY2NmJmNjk2YWIwMmJhMGZiZmYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [Platform Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [ ] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by shiragoodman** [comment]
@humancompanion-usds FYI - please feel free to add on or comment.

**Comment by shiragoodman** [comment]
This initiative has changed from "Bring in VA Digital Notifications" to a "Discovery for bringing notifications standards into the Collaboration Cycle". 2 other initiatives have been created: 

1. Add VA Notify to the Collaboration Cycle process
2. Complete Staging Review on VA Notify templates

**Comment by shiragoodman** [comment]
notes from Governance refinement 11/14:

- is this within the scope of Governance?
- do we have the right to do this? Could there be conflict within OCTO?
- Our guidance that we give teams is based off of what's in VADS - will there be a set of notifications standards that is published as a result of this work? And then the Experience Standard supports adherence or not to the notification standard?
- How does this process work? VFS teams don’t seem to really know when and how the notifications work

How can we begin this work?
1. Sync with Dave Conlon - we want to ensure we're not stepping on anyone's toes or conflicting with other teams.

**Comment by humancompanion-usds** [comment]
@shiragoodman - Let's discuss this one on Friday. I'm flagging it as one of the 3 prioritized initiatives for the quarter. I think we're perhaps not on the same page on this one. I'm looking for the team to enforce the 3 touch points for all forms which are documented here as of November: https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status Yes, I'm aware we already enforce all VADS patterns, but I want to ensure there is a focus on this as I will be asking all teams working on forms to do this by a certain date. If there are notifications we want to cover that are not forms related then it would be great if this team could work with the Design System team to define gaps in either our patterns or the experience standards so that both teams can work to plug those gaps. This is not related to how those notifications get sent, which is VA Notify. Thus I don't think we need to sync with Dave on this.

**Comment by shiragoodman** [comment]
sounds good @humancompanion-usds . I'll add to our agenda for Friday. We didn't pick up any work from this initiative for the current sprint, so I think it's a good time to pivot and make sure we're on the same page, and planning work in alignment with that.

**Comment by shiragoodman** [comment]
Spoke to @humancompanion-usds on 2/7. Initiative will be pivoting away from ensuring critical notifications are sent, and instead focus on ensuring VFS teams:
- have a plan in place if/when an email notification bounces
- have a plan in place if/when an SMS fails
- update the UI to reflect the status of the users data submission (for both synchronous submissions and asynchronous submissions)
   - _Synchronous submission is processed in real time (within minutes) and UI is updated quickly, whereas asynchronous submission makes a call to a backend system (minutes, sometimes hours or days) and UI cannot be updated right away_
- use the [form submission status pattern](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status) when applicable.

In addition, Governance team will help identify gaps in either the VADS patterns or the experience standards for notifications and UI status changes not related to forms. (Example: VA cancelling a Veterans appointment. How is the veteran notified via notification and the VA.gov UI? Do we need a VADS pattern for this?)
