### ISSUE TITLE
SPIKE | 686 evidence upload failures

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94433]
## Issue Description
_Determine if 686 has experienced evidence upload failures between the start of CY1 1/12/2012 to when the backup path was implemented on 10/5/2023._

An example scenario:
A veteran submits a 686 online and includes 2 PDFs of evidence. The EP creation works and so does the job to place the 686 form PDF in the efolder. But one piece of evidence is rejected by BGS because it's too big. Prior to the backup path, what would be the outcome? and what about now?

Please review this [slack thread](https://dsva.slack.com/archives/C07KTTFP308/p1732135843004959) and [this thread](https://dsva.slack.com/archives/C0547Q0K0LF/p1732146893355569).

---
## Tasks
- [x] Determine if there have been any evidence upload failures where the evidence failed but the claim went through to BGS
   - CY1 found failed claims as far back as 1/12/2012 and the backup pathway was implemented on 10/5/2023

## Acceptance Criteria
- [ ] Mural showing process flow of form has been updated to include evidence upload flows
- [ ] A list of submissions that may have fallen through the cracks (if any), which includes:
   - [ ] date of evidence submission
   - [ ] claim ID
   - [ ] Veteran ID info
   - [ ] reason for upload failure
- [x]  Monitoring and logging tickets have been created (if needed)
- [ ]  Remediation tickets have been created (if needed)
---

**Comment by sanjabaj2** [comment]
@steele-lm Do we have any blockers for this ticket, or is it just a matter of time? The ticket hasn't been added to any sprints yet. Do you know when can it be picked up.

**Comment by sanjabaj2** [comment]
Also, need to reconfirm that we don't have individual evidence failures after we have implemented backup path.

**Comment by TaiWilkin** [comment]
I've made some progress in evaluating the possible failure points in the flow (although still a lot of work to be done in this investigation). Please find the notes so far below. Given that I don't regularly work with this form, any relevant context or corrections to the below is appreciated. 

# Current flow

<img width="639" alt="Image" src="https://github.com/user-attachments/assets/f82d642e-1908-4a60-8c40-12e2cae0bc0e" />

## Errors in initial submission:
1. Since VBMS::SubmitDependentsPdfJob.perform_sync submits the attachments first, it's possible for all attachments to succeed and then the claim upload to fail, but any error here will cause the claim to be passed to CentralMail::SubmitCentralForm686cJob AND an error is raised to the user.
2. If we reach submit_forms, then the attachment and claim PDF uploads to VBMS already occurred. The remaining work doesn't involve form/attachment uploads unless there's a problem. 
3. In BGS::Form686c.new.submit, I believe what happens is that BGS is directly updated to reflect the requested dependency changes from the form. An error during this process will cause retry of BGS::SubmitForm686cJob. Exhaustion will cause the claim to be passed to CentralMail::SubmitCentralForm686cJob. If an error occurs during cleanup of BGS::Form686c.new.submit, it gets logged but doesn't trigger the retry. 
4. BGS::SubmitForm674Job is triggered in submit_forms after BGS::Form686c.new.submit finishes OR in submit_to_standard_service if the claim isn't an eligible 686c. It's very similar to BGS::SubmitForm686cJob, but for 674, and also falls back to CentralMail::SubmitCentralForm686cJob.
5. CentralMail::SubmitCentralForm686cJob collects all the documents (claim, attachments) and submits them to Lighthouse at the same time. Errors for either  apply to both, and trigger retries. On exhaustion, the user is emailed. 
## Errors after submission:
1. I don't see any place in the VBMS::SubmitDependentsPdfJob flow that is set up to monitor submitted claims after upload to VBMS.
2. If the claim and attachments are uploaded through CentralMail, then a FormSubmissionAttempt is created. My assumption is that if the claim OR attachments fail after submission, that will be caught by BenefitsIntakeStatusJob, which will email the user. 

# Before 10/5/23

## Errors in initial submission:
1. VBMS::SubmitDependentsPdfJob.perform_async was used instead of VBMS::SubmitDependentsPdfJob.perform_sync, meaning that errors here weren't raised to the user. In addition, there was no backup flow to CentralMail, so failures here would cause the PDF submission to fail completely.  Failures in attachment uploads should have caused the claim to fail as well. 
	1. Look for logs of "VBMS::SubmitDependentsPdfJob failed!"
2. In most cases, a failure in SubmitDependentsPdfJob wouldn't have prevented BGS::SubmitForm686cJob.perform_async from being reached. 
3. If an error occurred during BGS::SubmitForm686cJob.perform_async, it would trigger submission via CentralMail::SubmitCentralForm686cJob. 
4. CentralMail::SubmitCentralForm686cJob collects all the documents (claim, attachments) and submits them to Lighthouse at the same time. Errors for either  apply to both, but don't trigger retries. It looks like failures triggered an email to the user.
## Errors after submission:
1. I don't see any place in the VBMS::SubmitDependentsPdfJob flow that is set up to monitor submitted claims after upload to VBMS.
2. If the claim and attachments are uploaded through CentralMail, it looks like CentralMailClaims had CentralMailSubmissions which were updated to 'success' when the claim and attachments reached VBMS. I don't see any tracking of errors after that initial acceptance. 
# Summary

1. During initial submission, I believe that there couldn't have been a case where attachments failed and the claim succeeded, either before or after 10/5/23, since attachments were/are either uploaded before the claim or at the same time. 
	1. The entire PDF submission would have failed in these cases before 10/5/23. These failures would just have been logged with no user notification, although the process might have proceeded to BGS::SubmitForm686cJob and updated BGS directly afterwards.
2. It's also possible that attachments or claims failed *after* submission to VBMS via VBMS::SubmitDependentsPdfJob. Depending on how VBMS handles the related (but separately submitted) documents, I don't know if they would have the entire claim given failed attachments or not. I believe these would have slipped through the cracks.
3. Since the CentralMail submissions are submitted together, I would expect that VBMS would fail the entire claim if an attachment failed. Once the failure email was set up, users should have been notified if their claim failed, but I can't tell when that was implemented (sometime before September 2023).

**Comment by sanjabaj2** [comment]
Thank you for the detailed analysis, @TaiWilkin. Without diving into logical use cases, would it be possible to indicate which one could potentially result in silent failure and do we have a way of getting the details for offline remediation?

**Comment by TaiWilkin** [comment]
@sanjabaj2 
- Partial silent failures might have occurred before 10/5 where the PDF upload failed but BGS was updated successfully. We can find these by looking for logs with "VBMS::SubmitDependentsPdfJob failed!"
- If PDF upload to VBMS succeeded but the claim failed in VBMS, then that would have resulted in a silent failure. I don't know of a way to directly check for that - it's a similar situation to the one we're in with older Burials claims
- There might be old CentralMail submissions that failed silently, but the code isn't tracked far enough back to be certain, and I don't see any obvious way to track any cases down

**Comment by TaiWilkin** [comment]
Issues arising from this task: 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/100960
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/100943
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/100911

**Comment by sanjabaj2** [comment]
Partial silent failures might have occurred before 10/5 where the PDF upload failed but BGS was updated successfully. We can find these by looking for logs with "VBMS::SubmitDependentsPdfJob failed!"
>>> Can you document these instances if we have them? 

If PDF upload to VBMS succeeded but the claim failed in VBMS, then that would have resulted in a silent failure. I don't know of a way to directly check for that - it's a similar situation to the one we're in with older Burials claims
>>> Can you create list of cases that we need to double check in VBMS? I'll add to the list of Burial claims that we need to verify.

**Comment by TaiWilkin** [comment]
I've now looked further into the "VBMS::SubmitDependentsPdfJob failed!" instances. This log was added May 10, 2023, and there wasn't error logging prior. Per the [commit message](https://github.com/department-of-veterans-affairs/vets-api/commit/aeea0f27477645a5365fdb16efb8ffc3e6f026f3) when it was added, the team was actively monitoring these logs, so it's unlikely any slipped through. Unfortunately, the DataDog logs only go back to late October 2023, so I wasn't able to pull up the older logs without rehydrating logs. I *think* rehydrating logs has an associated cost, and so it doesn't seem worthwhile to dig further if the team at the time was already monitoring. Let me know if you disagree. 
Next I'll look into the VBMS calls themselves. I've realized that this is a direct submission to VBMS (vs going through Lighthouse like Pension/Burials), so I'm going to have to investigate how that works before I can collect appropriate data for it.

**Comment by TaiWilkin** [comment]
What I'm currently seeing for the VBMS submissions is that they either succeed or throw an error. If they can fail after reaching VBMS when submitted via this method, there's nothing documented where I can find it. We could reach out to someone at VBMS to find out if it can happen with direct submission, but I'm not sure who we'd speak to.

**Comment by sanjabaj2** [comment]
> What I'm currently seeing for the VBMS submissions is that they either succeed or throw an error. If they can fail after reaching VBMS when submitted via this method, there's nothing documented where I can find it. We could reach out to someone at VBMS to find out if it can happen with direct submission, but I'm not sure who we'd speak to.

I think if VBMS accepted the upload, we can conclude it was a success.
What is the result when upload throws error? Is it displayed to the user, or just logged? If error is displayed to the user, we should be fine.

**Comment by sanjabaj2** [comment]
> I've now looked further into the "VBMS::SubmitDependentsPdfJob failed!" instances. This log was added May 10, 2023, and there wasn't error logging prior. Per the [commit message](https://github.com/department-of-veterans-affairs/vets-api/commit/aeea0f27477645a5365fdb16efb8ffc3e6f026f3) when it was added, the team was actively monitoring these logs, so it's unlikely any slipped through. Unfortunately, the DataDog logs only go back to late October 2023, so I wasn't able to pull up the older logs without rehydrating logs. I _think_ rehydrating logs has an associated cost, and so it doesn't seem worthwhile to dig further if the team at the time was already monitoring. Let me know if you disagree. Next I'll look into the VBMS calls themselves. I've realized that this is a direct submission to VBMS (vs going through Lighthouse like Pension/Burials), so I'm going to have to investigate how that works before I can collect appropriate data for it.

@va-albers Steve, this is related to research into any potential evidence upload failures, up to us implementing LH Benefits Intake API with re-tries. What is your take on re-hydrating logs?
I wonder if we can use LH Benefits Documents API and retrieve a list of documents so we can match if we have document names?  This is where access to claim evidence API would be handy. :)

**Comment by sanjabaj2** [comment]
@TaiWilkin I just want to have a standalone "Thank you" message for all your work on this so far. Thank you!

**Comment by mjknight50** [comment]
Hi @sanjabaj2 - Can we close this or do want additional work on this?

**Comment by sanjabaj2** [comment]
> Hi [@sanjabaj2](https://github.com/sanjabaj2) - Can we close this or do want additional work on this?

There are 2 comments from me that are not addressed. Also, maybe a meeting with Tai, Laura, Steve, I to see what options do we have to get to the a list of potential failures.

**Comment by raudabaugh** [comment]
> What is your take on re-hydrating logs? 

According to Datadog's estimate tool, it would cost somewhere around $1,200-1,700 to rehydrate for that time period, which may be worth it if we haven't already captured the relevant info elsewhere.

> I wonder if we can use LH Benefits Documents API and retrieve a list of documents so we can match if we have document names?

This is doable if you have claim IDs and file numbers: see [generate_csv.rb](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/bdda4897bf530fb23a1d401097d313a7748d6891/teams/benefits/scripts/526/evidence_upload_silent_failures/generate_csv.rb#L233)

**Comment by mjknight50** [comment]
@raudabaugh @TaiWilkin @sanjabaj2 and @mjknight50 met on this.  

@TaiWilkin is going to take the claims in question and check their status against Lighthouse to see which, if any, were rejected.
The assumption being that those that were accepted didn't have issues with their evidence.

Based upon the findings, we will determine if we need to rehydrate back to May 2023.

**Comment by TaiWilkin** [comment]
@sanjabaj2 @mjknight50 
# Data

*149,938* Dependency Claims were submitted between 05-10-23 and 10-05-23. None have Benefits Intake IDs tracked in the vets-api database, so I was unable to check for their presents in LH.

19,417 dependency attachments were created during that same period, of which 17,876 are linked to a SavedClaim. My best guess is that the 1,541 unlinked attachments are primarily from claims that were never submitted (they get linked during submission, before being submitted to LH). 
*17,788* documents are listed within the Dependency Claims from the period as attachments. Of those, 17,785 listed the id of the persistent attachment, and I was able to cross-reference and confirm we have the attachments in our database.
Three documents had no id referenced within the Dependency Claims data, so I was unable to verify the presence of those attachments. 
We don't track the attachments' benefits intake id (although that might be the same as the claim's intake id?), so I was unable to validate their presence in lighthouse.

I also ran through a subsection of the claims with @raudabaugh's suggested search code, but didn't get results. I'm having trouble verifying, but I suspect the claim_id being used to search for documents here isn't the same as the vets-api SavedClaim.id, which is what I have access to to search with. 

# Next Steps

We can't realistically ask VBMS to manually check ~150,000 claims. (I wish there was a search that just took file_number and form id, and returned a status!)

- I recommend we ask VBMS to check that approximately the correct number of claims were submitted in the time period from VA.gov, with approximately the correct number of attachments overall. Given the delay in proceeding from vets-api to VBMS, there might be a slight difference between when we sent them and when they were submitted that could make the number a bit fuzzy. We could potentially cut down on that by providing details for the first few claims and last few claims from our period for review, so they can more accurately match our start and end points. 

- I also recommend we specifically ask them to check the three claims that had unidentified attachments.

**Comment by steele-lm** [comment]
Alex confirmed that 686 claims from this timeframe were remediated with the Code Yellow 1 effort. The 686+evidence claim submission is an all-or-nothing job, so if the evidence fails to upload, the entire claim fails. Because of this, there should not be scenarios where the claim pdf succeeded but the evidence failed.
