### ISSUE TITLE
SPIKE | COE evidence upload failures

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94432]
## Issue Description
_Determine if COE has experience evidence upload failures._

---
## Tasks
- [ ] Determine if there have been any evidence upload failures

## Acceptance Criteria
- [ ] Mural showing process flow of form has been updated to include evidence upload flows
- [ ] A list of submissions that may have fallen through the cracks (if any), which includes date of evidence submission, claim ID, and reason for upload failure
- [ ]  Monitoring and logging tickets have been created (if needed)
- [ ]  Remediation tickets have been created (if needed)
---

**Comment by steele-lm** [comment]
Confirmed that evidence upload failures are rescued in the same way a failed claim is, so the failure is not silent. The Veteran is notified right away of the failure.
