### ISSUE TITLE
Submit CAIA ticket to update CC page on unauth site for direct scheduling cc appts

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#94444]
## Tasks

- [x] Fill out CAIA request to update information on these resource pages about cc digital self scheduling:
    - [x] https://www.va.gov/resources/how-to-get-community-care-referrals-and-schedule-appointments/
    - [x] https://www.va.gov/health-care/schedule-view-va-appointments/

**Comment by benbrasso-agile6** [comment]
Created and posted in Sitewide CAIA slack channel 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/95652
