### ISSUE TITLE
Separate the tasks into educational or administrative

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#94446]
## User Story
As a Governance team member supporting Platform Orientation, I want to determine which tasks in the New VFS Team member ticket are educational and which tasks are administrative so that I can move the tasks to their appropriate future home.

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @allison0034 

## Description
Now that we have defined our preferred terms via ticket , we must now sort through the New VFS Team Member gh issue ticket to determine which tasks fall in which bucket. We will NOT be validating whether or not the task/linked guidance is still appropriate within this ticket, so please focus on just determining whether it fits the definition of educational or administrative.

**Educational:** tasks that teach new VFS team members about the various processes in the [VA.gov](http://va.gov/) Platform organization and how their role and purpose fits into the broader organizational structure.

**Administrative:** housekeeping tasks used to gather information on new VFS team members, provide them with access to technologies, and maintain professional and legal compliance between [VA.gov](http://va.gov/) and its various contractors.

## Impacted Artifacts

[New VFS Team Member gh template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team-member%2C+platform-tech-team-support&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D)

Please note that you are NOT making any changes to the gh template within the scope of this ticket. 

## Tasks
- [x] Copy the tasks from the "Onboarding Checklist" section of the New VFS Team Member gh ticket into a new draft page on Confluence. 
- [x] Determine if each task is educational or administrative (per the definitions from #94445)
- [ ] Once complete, share with your peer reviewer to confirm that they concur with your "bucketing"
- [ ] Share with Shira once in agreement

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have defined which tasks in the New VFS Team member ticket fall into the "educational" bucket 
- [ ] We have defined which tasks in the New VFS Team member ticket fall into the "administrative" bucket 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
this ticket was not intended to be added to the Oct 10-23 sprint

**Comment by KKitagawa-Bosch** [comment]
@allison0034 Created a draft and separated all the tasks [here](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3572334597/94446+-+Keegan) let me know what you think!

**Comment by allison0034** [comment]
@KKitagawa-Bosch looking good! I agree with all the placement of items. Made a few comments.

**Comment by KKitagawa-Bosch** [comment]
@allison0034 @shiragoodman could you look and confirm for me I think these comments are a bit out of scope of this ticket. The goal here as I understood it was just to bucket out the tasks, not to rewrite the ticket/add headings/etc.

**Comment by allison0034** [comment]
I think by changing and adding "Administrative" and "Educational" headings, the rest of the headings need to be looked at to make sure they still make sense and are still inline with accessibility, but I will default to whatever you and Shira decide..

**Comment by shiragoodman** [comment]
@allison0034 @KKitagawa-Bosch responding to reiterate what I said at standup. The headings are out of scope for this ticket. We're only focused on the tasks, and will be updating the ticket design for the administrative tasks in #94448 (Allison) and will redesign the education tasks for Platform Website in #94449.

**Comment by allison0034** [comment]
@KKitagawa-Bosch I am still seeing the missing "note" and extra space... I commented in the doc.

**Comment by allison0034** [comment]
@KKitagawa-Bosch the "note" is currently part of the task. I see you have the task, but not the note part. You may want to make a comment in your draft to use the task verbiage in the GH ticket and not in your draft if you are removing parts of tasks. I just don't want who ever works on the GH ticket to think you trimmed any content on purpose. I could see how they could easily copy/paste your text and then the stuff you trimmed is left off.
<img width="1856" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2FCQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f19190802ab236bc65d2e686551f88ceabaf65c/Screenshot%202024-10-29%20at%202.31.21%E2%80%AFPM.png" alt="Screenshot 2024-10-29 at 2.31.21 PM.png" />

**Comment by shiragoodman** [comment]
Thanks for the clarification, @allison0034 . I also was a bit unsure what you meant by "note". 

Heads up - you're working on the gh ticket! via #94448
