### ISSUE TITLE
Define onboarding vs. orientation and preferred terms

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#94445]
## User Story
As a Governance team member supporting Platform Orientation, I want to come up with definitions for onboarding vs. orientation so that I know how to categorize the tasks appropriately.

As a Governance team member supporting Platform Orientation, I want to confirm the preferred terms for the 2 types of tasks associated with this ticket. 

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @allison0034 

## Description
Before we can begin splitting the orientation tasks from the onboarding tasks, we must first define what we mean by "orientation task" and "onboarding task." Per the [epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85562), Shira has defined, "The orientation tasks are intended to help educate them on the processes, practices, rules and overall 'way we do things' when building on the VA.gov Platform. The onboarding tasks are so that the new team member can gain access to Platform products, tools and services, including GitHub repos, Atlas, and other tools that are Atlas-dependent."

In addition to coming up with definitions for the 2 types of tasks, we must also choose our preferred terms for these 2 types of tasks - we do not have to keep the terms "orientation" and "onboarding."

The purpose of this ticket is to come up with definitions for the 2 different tasks, and determine which preferred terms we would like to use moving forward. 

### Live pages
- 

### Drafted pages
- [Draft Notes](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3551494151/94445+-+Keegan+-+define+onboarding+vs.+orientation)

## Tasks
- [ ] Come up with definitions for onboarding and orientation. See ticket description and/or epic for more details.
- [ ] Define our preferred terms for "onboarding" tasks and "orientation" tasks

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have determined which preferred term we'd like to use moving forward for the current "onboarding" tasks
- [x] We have determined which preferred terms we'd like to use moving forward for the current "orientation" tasks
- [x] We have come up with definitions for both "onboarding" and "orientation" (or the new preferred terms)
- [x] We have updated ticket #94446 to include the preferred terms for "onboarding" and "orientation"

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by KKitagawa-Bosch** [comment]
@allison0034 I've been playing with a lot of options and I keep coming back to the distinction being sort of "one-time housekeeping" versus "ongoing learning about the platform and the job" 

I've put some thoughts into words in [this page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3551494151/94445+-+Keegan+-+define+onboarding+vs.+orientation), could you take a look and let me know what you think and I can refine from there?

**Comment by shiragoodman** [comment]
@allison0034 please read through the[ initiative](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85562) to familiarize yourself with the "why". 

@KKitagawa-Bosch I think you slightly missed the point of the exercise. The objective was not to define onboarding and orientation, but to come up with a word we could use to describe the educational tasks associated with learning about the Platform vs. the administrative tasks _required_ for new folks so that they can actually build on the platform. I have been calling them orientation and onboarding, respectively, bc that's how I interpret it, but it's clear that I don't share the same definitions as everyone else.

Let me try this another way.. We need a formal description of the "educational tasks associated with learning about the Platform" and a preferred term for those types of tasks. We also need a formal description of, "administrative tasks _required_ for new folks so that they can actually build on the platform" and a preferred term for those types of tasks. If you think my text in quotes is sufficient, then great! However, I think we could build on them a bit to provide more clarity. 

Let me know if you'd like to discuss this further. Thanks.

**Comment by allison0034** [comment]
@shiragoodman I understand we want to separate out things based on based on VFS team members and non VFS team members. I still think calling them orientation vs onboarding is going to cause confusion. When we did research around this those words were just too close together and people did not understand the difference.

My suggestion is to drop the word orientation. All of these things are tasks you need to do to be onboarded to the VA. You could make a list of tasks that all new employees do (ie VFS and non VFS team members) and then also a list for only VFS team members. Does that make sense?

**Comment by allison0034** [comment]
If you want to confirm the confusion, maybe send out a quick survey link and ask a simple question like "When thinking about joining a new company, what do the words onboarding and orientation mean to you?"

- They have different meanings
- I don't really know if they have different meanings or not
- They have the same meaning

**Comment by shiragoodman** [comment]
Ok I think we're at the point where we need a call between the 3 of us @KKitagawa-Bosch @allison0034 . The word "onboarding" HAS NOT been used at all in Platform Orientation. I'm not suggesting we use the words "onboarding" or "orientation"! this is just what I've been calling them to make it easier to communicate, however the whole point of this ticket is to come up with our _preferred terms_ for use moving forward. Words that align with the 2 different types of tasks - educational and administrative per my last comment.

**Comment by shiragoodman** [comment]
The tasks are being split out into education tasks for learning and educating yourself on the Platform (this could be anything from reading the "getting help on Slack" guidance on PW, to watching the DST orientation, or watching the Accessibility orientation), and then the other tasks are all administrative (this could be filling out your Slack profile, opting out of Google Analytics, sharing your info with Platform, getting access to the VA GH Org).

**Comment by shiragoodman** [comment]
maybe we just use those terms? Administrative and Education? Then maybe change "Platform Orientation" to "VA.gov Orientation" with Education being 1 part of it and Administrative being another part

**Comment by KKitagawa-Bosch** [comment]
Ah, yes it does seem I misunderstood what you were asking for, sorry about that! 

However, all of the reading and research I did still informs this task though, I think I can take another stab at it today using that knowledge gained! 

I was going to say exactly what you did @shiragoodman and ask if there's any reason not to literally use administrative and education. I think those terms are very clear

**Comment by shiragoodman** [comment]
Thanks @KKitagawa-Bosch . Apologies for the lack of clarity. This ticket and #94446 are definitely a chicken and egg situation.  How can we separate the tasks if we don't know what topics we're separating them into? vs. How can we define the type of tasks if we haven't already separated them into logical buckets? It's a challenge.

If you like administrative and education, then so do I. However, we do still need formal definitions of what the education tasks are vs. what the administrative tasks are. I gave some examples above, however, I think looking at the[ New VFS Team member ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team-member%2C+platform-tech-team-support&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D)may also help. We'll likely use these definitions later on to help communicate the 2 types of tasks to VFS teams (when we launch), and we'll also use them in our next ticket for separating the tasks in the ticket template per #94446. Let me know if you still need some clarity.

**Comment by KKitagawa-Bosch** [comment]
@allison0034 @shiragoodman added some possible definitions to the [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3551494151/94445+-+Keegan+-+define+onboarding+vs.+orientation)

Not married to these as they are, but struggling to figure out what I don't like? So I'm throwing it over to y'all for ideas

**Comment by shiragoodman** [comment]
@KKitagawa-Bosch i added a couple comments. Please make the definitions more specific to the Platform Orientation process and the VA.gov Platform. ty!

**Comment by KKitagawa-Bosch** [comment]
@shiragoodman first attempt at va-specific definitions added!

**Comment by allison0034** [comment]
@shiragoodman @KKitagawa-Bosch don't forget, per [the initiative](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85562)...

> We'd like to separate the onboarding tasks from the orientation tasks and create 2 separate processes because we have encountered several challenges when tying the 2 together including non-VFS team members

Looks like most of these terms include VFS team members only, what about the non VFS team members?

**Comment by shiragoodman** [comment]
@allison0034 the administrative tasks (fka onboarding) are VFS- specific. Platform team members have another process for sharing team info and getting access to tools (it's all in the email Andrea sends when we join). The educational tasks (what I was previously calling education) are not necessarily VFS-specific. some of these tasks may be valuable for any new person, including Platform. Such as the General Orientation session, or getting help from the Platfrom in Slack, or learning how to access tools. It's the same whether you're platform or VFS.

For now, we won't plan on distinguishing between VFS tasks and everyone tasks. When this initiative is complete, we'll share with Andrea and she can decide along with Platform leadership if there's value in sharing any of this with Platform.

**Comment by shiragoodman** [comment]
@allison0034 I just responded to your comment in the [draft. ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3551494151/94445+-+Keegan+-+define+onboarding+vs.+orientation)That might help explain our stance a bit better. Please let me know.

**Comment by allison0034** [comment]
@shiragoodman so it seems our main concern is the VFS team members knowing what they need to do... not so much the non VFS team members correct?

**Comment by shiragoodman** [comment]
@allison0034 if by non-VFS team members, you're referring to the Platform team member who take action on the ticket to add the VFS to the repo and to Atlas, then correct. They know what they're doing. We're also hoping that my cleaning up the template and limiting it to just admin tasks, it'll make it much easier for the Platform folks to take action on the ticket. - less clutter.

**Comment by shiragoodman** [comment]
hey @KKitagawa-Bosch - please be sure to finalize this work and close out the ticket. I was under the impression that it would close by end of sprint yesterday.

**Comment by KKitagawa-Bosch** [comment]
@shiragoodman ah sorry I thought I was waiting for confirmation on those definitions from you! If they're good to go I'll close this out right now
