### ISSUE TITLE
SPIKE | Identify 686/674 APIs for REST migration

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94450]
## Issue Description
_Determine what 686/674 endpoints can be migrated to the new REST API endpoints, so we can determine what endpoints we need to ask the implementation team to prioritize. Relates to the SOAP -> REST migration effort in #91282._

---
## Tasks
- [ ] Determine what 686/674 endpoints can be migrated to the new REST API endpoints
- [ ] Cross-reference this list with the list of endpoints scheduled for migration that was provided by the SOAP/REST team

## Acceptance Criteria
- [ ] List of APIs that can be migrated to RESTful APIs. List should identify which VA.gov APIs are ready to migrate and which RESTful APIs still need to be developed
---

**Comment by mjknight50** [comment]
Opened a ticket with BEP Services Intake 
https://jira.devops.va.gov/servicedesk/customer/portal/60/BEPOSD-367

**Comment by mjknight50** [comment]
I have escalated the ticket in an attempt to get more information.

**Comment by mjknight50** [comment]
Moving to backlog.

**Comment by mjknight50** [comment]
Received two swagger docs to review:

Claims API: https://claims-test.dev.bip.va.gov/swagger-ui.html#/Claims/createClaim
Claims Evidence API:  https://claimevidence-api-test.dev.bip.va.gov/api/v1/rest/swagger-ui.html

**Comment by mjknight50** [comment]
I opened a JIRA ticket asking some questions about BIP API:

> Our team is responsible for the 686c/674 VA forms. We are exploring the idea of using the BIP claim API instead of Lighthouse.
> 
> I have a few questions on this:
> 
> Can you please walk me through the flow of how the JSON payload from [va.gov](http://va.gov/) would get into VBMS via BIP?
> If we also use BIP evidence API, do we need to use Lighthouse for anything (apart from a back-up path)?
> What is the SLA for BIP API? Are there regular maintenance windows or downtimes?
> I’ve looked at the schema and sample payload for creating a new claim but I don’t see any data points that would map our JSON payload to a claim. It feels very limited compared to the data we are capturing and what would be needed for adjudication within VBMS. Where does the claim information itself get provided? Or is that just via the evidence upload?

**Comment by mjknight50** [comment]
Closing this spike in favor of the next step:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/103926
