### ISSUE TITLE
Pension | Design spike for failure/error emails (stage 1)

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#94459]
### Background:
As part of the ZSF effort, we need to inform the veteran when their Pension applications failed to be submitted.

### Additional Info:
* Generic [email templates](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status#status-in-myva) + specific failures [customized templates](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/ERwp3QmSIyhEuyWK4AKvRNQB1BOkgJ7g8Boh3ko6lZ3YGA?e=B7L2Lk&wdLOR=cCBC9D334-27B5-8946-823E-7E531127EF6C) from CAIA.
        *  We must confirm each remediation process makes sense for each specific form- if process can't be confirmed then generic email will be implemented first
    * General guidance:platform and [github](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)
    * Email publishing acceptance criteria ([sample ticket](https://dsva.slack.com/archives/C057W3N9K2S/p1728065064797879?thread_ts=1727980851.243379&cid=C057W3N9K2S))

### Tasks:
- [x] Engineering and Design collaborate to understand all failure points and remediation user action pathways per form
- [x] Design determines how many failure email versions need to be made and map each type back to failure point Likely these where applicable:
   - Evidence fail
   - Full loss
   - Supplemental form loss
- [x] Touch point with VA crew to share findings from first 2 tasks
- [x] Design updates email templates ensuring clear error and remediation next steps for each error type  (get CAIA review if we have questions)
- [x] [@Dené Gabaldón](https://dsva.slack.com/team/U06Q5JNA30C) to review
- [x] Submit to privacy review (tbd)
- [x] Submit to VAnotify team to add template [#94099](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94099)

ENG ticket to implement email triggers: #91426 (Sidekiq exhaustion at LH)

**Comment by gmaciolek** [comment]
Update [posted in Slack](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1728920302611/0e9b48b0886e0ba427fb3d6bd1b9dfc15918a5ae?wid=0-1728945238656) with link to an [in-progress MURAL board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1728920302611/0e9b48b0886e0ba427fb3d6bd1b9dfc15918a5ae?wid=0-1728945238656) where I'm documenting the post-submission user experience and identifying failure scenarios and "action needed" emails to be sent.

**Comment by gmaciolek** [comment]
Summary of findings for both Pension and Burial:

**Failure points:**
- Submitting to LH
- LH submitting to VBMS

**Remediation steps:**
Submit a paper application by mail or in person. (We don't want them to resubmit online because the submission is likely to fail again.)

**Types of failures:**
All failures are total failures. We submit the form data and all supplemental documentation/evidence together. Currently, there could never be a scenario where only the form submits successfully, but not the attached documents (or vice versa).
Note: May want to consider submitting the form and the supporting documents separately in the future.

**Comment by gmaciolek** [comment]
- Email copy finalized and approved internally
- Email is in a VA Notify template
- No privacy review required
- Pending final approval from VBA

Closing this ticket and will create a new ticket to update the email if we need to make changes based on VBA's feedback and concerns
