### ISSUE TITLE
Redesign Platform Orientation pages for Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#94454]
This ticket has a dependency on #96283. Work for this ticket should not begin until #96283 is complete.

## User Story
As a new VFS team member, I want to be able to turn to the Platform Website for accurate and clear instructions for getting oriented to Platform products and services, so that I can complete all necessary steps and begin supporting my team to build on VA.gov. 

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @allison0034 

## Description
The purpose of this ticket is to redesign the existing Platform Orientation pages on Platform Website, including the [landing page](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-orientation), the [guidance for new teams and team members page](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members), the [Orientation Sessions](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions) page (the only thing on this page that should change is the highlighted note at the top of the page) and the creation of the new educational tasks page. 

Using the flow created in ticket #96283, update the content, design, and IA of the Platform Orientation pages so it is clear what steps and actions a new VFS team member should take in order to complete the Platform Orientation process. Guidance for a New VFS Team should remain the same.

The scope of this ticket does not include publishing the revised pages. That will happen at a later date, when we launch.

### Live pages
- [Platform Orientation landing page](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-orientation)
- [Guidance for new teams and team members page](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members)
- [Orientation Sessions](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions)
- New Educational Tasks page

### Drafted pages
- [Landing Page
](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3633184794/Platform+Orientation)
- [New Team Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3633184828/Guidance+for+new+teams+and+team+members)
- [Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3633184878/Orientation+Sessions)
- [Educational Tasks
](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3632496649/Educational+Tasks)

## Tasks
- [ ] Update the content, design and IA of the current Platform Orientation pages
- [ ] Create a new page for the educational tasks
- [ ] Be sure to include the new user flow via ticket #96283

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have redesigned the Platform Orientation pages on Platform Website to reflect the new flow and change in process

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
This ticket has been combined with #94449 and #94455, and renamed to support the redesign/creation of all Platform Orientation pages (excluding the [Orientation Sessions page](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions)).

**Comment by allison0034** [comment]
@shiragoodman I am working on the swim lane now. Both Keegan and I believe that we only need to add a block referring to the educational tasks. With that in mind, I would like to see how Keegan lays out the educational page so I can use the correct verbiage (could be "complete tasks" or maybe "review page"). I have a [placeholder in the flow right now](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1731413610683/ae6ec7abd3fb2fdad59b0dec361221020b0e2e35), but are you ok with @KKitagawa-Bosch going ahead and starting on this so I can update the verbiage when they are done to align with the page?

**Comment by shiragoodman** [comment]
@allison0034 yes, totally fine with that. We're not launching anything yet, so if we determine post redesign of the Platform Website pages that we need to reword or change anything in the template, we'll have time to do that.

**Comment by KKitagawa-Bosch** [comment]
Drafted pages created and linked in ticket

**Comment by KKitagawa-Bosch** [comment]
@allison0034 these are ready for a round of edits, I think! 

I adjusted a lot of the flow of things with the intent of making the process clearer for new VFS team members to see exactly what they're expected to do and where those things are housed. All the draft pages are updated in confluence!

**Comment by KKitagawa-Bosch** [comment]
@shiragoodman how much power do I have to change the [Platform Orientation landing page](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-orientation)? There are things I would love to change, but wasn't sure if bigger sweeping changes were within scope here or if I should keep it to smaller edits

**Comment by shiragoodman** [comment]
@KKitagawa-Bosch you have ALL the power. Please. This is an overhaul, so do what you feel needs to be done.

**Comment by allison0034** [comment]
Looks good, I made 1 suggestion and updated the flow image.

**Comment by KKitagawa-Bosch** [comment]
@allison0034 moved stuff around on the [Platform Orientation](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3633184794/Platform+Orientation) page, I think it's a good bit clearer now, let me know what you think!

**Comment by allison0034** [comment]
Looks good to me!
