### ISSUE TITLE
[CST] Create Sidekiq job to handle document upload failure email notifications

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#94466]
## Background Context

We want to transfer functionality of Sidekiq exhaustion handler into a separate job so we can retry emails in VA Notify. 

### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] Create new sidekiq job for sending emails
- [ ] Create rspec tests to verify functionality
- [ ] Update existing document upload jobs to call the new Sidekiq job

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] We have ability to retry sending emails to VA Notify if the email fails to send.
- [ ] The existing document upload jobs are using the new jobs we create

**Comment by pmclaren19** [comment]
merged to staging and tested and looks good!
