### ISSUE TITLE
Project Kickoff Life Insurance Content

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9446]
## Steps to complete Project Kickoff
- [X] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [X] Andrea and Megan will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to ~~rough draft of product outline~~ Epic housing this series of work ([link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8434))
- Explanation of the problem space

Completion of life insurance hub rewriting.

High level user story - As a Veteran or family member who needs or has VA life insurance, I need to have clear, accurate, easy-to-access information about my life insurance benefits so I can plan my future.

Our "Bet" - If we provide VA life insurance information in a modernized, easy-to-read form then we expect Veterans and family members to find the information they need.

OKR - Finishing this epic will allow the team to meet the goal of redirecting all tier 1 legacy benefit pages by end of Q2.

## Meeting attendees from **requesting team**
- Product Manager (required): Stephanie Orkand
- DEPO Product Lead (required): Danielle Thierry
- Entire VFS team (recommended): **names**

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** YES - content initiative

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
TIME REQUEST: 05/27/2020 at 11:30am ET
- _If no available time slots work for your team, write your availability and requirements here and Megan/Andrea will reach out as needed_
