### ISSUE TITLE
Implement red error alert for Confirmation page

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#94479]
## Issue Description
As a Veteran, I want to understand the status of my submission in clear, straightforward language so that I feel confident that VA is trying to submit my application. When I submit my application, I want immediate feedback regarding the status of my application.

For reference the Figma design file for this feature is [here](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/(526ez)-Submission-Experience?node-id=34-73279&node-type=canvas&t=ApNRPKRTgXAYAMBh-0).

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ]The error banner "We're sorry..." is set on the Confirmation page
- [ ]The banner is displayed when the appropriate application and system conditions are met to indicate an immediate failure of the submission
- The success banner should continue to display when success conditions are met

## Additional Information
for non 200 response
for non 200 we show the red
for no job id 
at point of submission, call submitallclaim, 

retryable and non retryable is the job status endpoint

no changes to red alert on review and submit

as long as we get job id back, it's green

show red error alert for submitallclaim error

Implement "We're sorry..." alert for any non 200 responses between va.gov and vets-api

**Comment by pacerwow** [comment]
Closed, not needed as we will not be editing this error alert.
