### ISSUE TITLE
 Original Claims: Prompt users to verify their identity

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#9448]
## Issue Description

Form 562 requires that the user have an EDIPI to submit and the back end only gets EDIPI from MVI/MPI for identity-verified users so we should prompt users to verify their identity before starting the form.

As an example the prescriptions call to action has a prompt to "verify your identity".
<img width="1588" alt="Screen Shot 2020-05-21 at 2 13 27 PM" src="https://user-images.githubusercontent.com/19188/82689217-22852f00-9c28-11ea-9771-e1133460ec04.png">
## Tasks
- [ ] before a user starts form 526 they should be prompted to verify their identity.  

## Acceptance Criteria
- [ ] once we ask users to identity-verify the count of [this issue in sentry](http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/116743/activity/) should drop significantly
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
I think we can just duplicate that exact verify box above and just replace the sentence below the heading with:

_"When you verify your identity you can use VA.gov to file claims for disability, track your claims and download your VA benefit letters."_

To make it a bit more specific to include the intent of the page the user is on (file a claim for disability).

**Comment by Mottie** [comment]
Done in https://github.com/department-of-veterans-affairs/vets-website/pull/12821
