### ISSUE TITLE
Include Claim ID in Summary Box conditionally

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#94482]
## Issue Description
As a Veteran I want to see my claim ID in the Summary box of the Confirmation screen so that I feel confident that VA is trying to submit my claim. 

This story is to include Claim ID in Summary Box conditionally

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] The claim ID is displayed in the Confirmation screen's Summary box when the submission is successful and the claim ID is available
- [ ] If the claim ID isn't available, the Summary box is still shown
- [ ] Other contents and appearance of the Summary box are unchanged

**Comment by pacerwow** [comment]
Closed as a dupe, replaced by #95241
