### ISSUE TITLE
Implement summary box content changes

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#94481]
## Issue Description
As a Veteran I want the language used on the Confirmation page to match other language that is used when VA communicates to me in the days following my submission so that the status of my application is communicated in clear, simple language that is easy to understand.

Implement the content changes in the Summary box on the Confirmation page.

For reference, [here](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/(526ez)-Submission-Experience?node-id=34-73279&node-type=canvas&t=ApNRPKRTgXAYAMBh-0) is the Figma design file.

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] The Summary box content language "date initiated" is changed to "date submitted"
- [ ] Other Summary box content and appearance is unchanged

## Open Questions
What is the change here? Staging and Figma designs both read "date submitted". We may not need this.

**Comment by pacerwow** [comment]
Closed as not needed! The copy in staging matches the figma designs, so no change here is necessary to update the summary box copy.
