### ISSUE TITLE
UI: Display Facility health services operating status

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9449]
## Issue Description
As a Veteran, I need to view the operating status for individual health services at my local VAMC facility so that I know if there is a change in availability. 

**Two new fields will be made available in Drupal (pending final DEPO approval)**

- Facility Health Service operating status (three possible statuses: _Normal, Limited_ and _Closed_)
- Facility Health Service operating status notes (free text, 300 char)

These fields will be displayed in the Services section of facility detail pages for **VA health facilities only** 

we can use the service list as built by Ethan without the operating status. This may require design input. 

## Current functionality: 
![image](https://user-images.githubusercontent.com/55411834/82690622-cb785d80-9c19-11ea-8ccb-28db5ae97f1f.png)

## Expected Functionality

**Draft design**

![draft service status on facility detail page](https://user-images.githubusercontent.com/55411834/82691433-1fd00d00-9c1b-11ea-9dbf-b1858af9fbb2.png)

---
## Tasks

**For VA Health facilities only**
- [ ] Connect React component to Drupal to consume operating status
- [ ] Remove _Service_ disclaimer alert (This list may not include all of the services available at this location.)
- [ ] Add display for _Services and Operating Status_ (Design to be finalized)
- [ ] Display to include:
   - "As of" date
   - Operating status listed by service (order TBD)
   - Free text content in operating status notes 

## Acceptance Criteria
Existing functionality will be maintained 
- [ ] Given a Veteran views a Benefit facility detail page
- [ ] Given a Veteran views a Cemetery facility detail page
- [ ] Given a Veteran views a Vet Center facility detail page
- [ ] Given a Veteran views a Community Care facility detail page

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ethanteague** [comment]
@mmiddaugh @davidconlon this work is completed (as defined by task), but will definitely need to be iterated. I'm not able to deploy it to a testing environment (devshop issues, and complexity related to drupal stuff that may not be released), so for now, a screenshot that I have included in the pr will have to suffice: 
![image](https://user-images.githubusercontent.com/2404547/84037676-e7476780-a96c-11ea-8a78-65cfcac9c670.png)

**Comment by mmiddaugh** [comment]
There are conflicts on this page due to changes the Facilities team has made since this particular work was done. We'll need Ethan's support to get this ready for hand off to the Facilities team to bring to the front end.

**Comment by mmiddaugh** [comment]
For reference, the relevant PR is https://github.com/department-of-veterans-affairs/vets-website/pull/12992/files

**Comment by davidmpickett** [comment]
If this were to be implemented today, it would need to be at the Service Location level, since any service can have multiple service locations, which may have separate statuses. Current roadmap for Service Location does not include Status.

**Comment by davidmpickett** [comment]
Also unclear if this level of information is useful to veterans and/or sustainable for editors to maintain

**Comment by mmiddaugh** [comment]
closing as no longer relevant
