### ISSUE TITLE
Pull records for failed submissions

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#94494]
## Description
We need to see failed submissions going back to at least July and see how many submissions failed and possibly why they failed.

We need to get this info to Denise. Maybe a spreadsheet format is optimal. If there is possible PII we should send via encrypted VA email.

**As a follow up to these tickets:**

- [94342 Veteran's failed submission](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94342)
- [94400 Veteran's failed submission](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94400)

Related tickets

- [94497 DMC time out issue tracking 2/3](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94497)
- [94498 DMC time out issue tracking 3/3](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94498)
- [94501 DMC time out issue notifications](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94501)

## Tasks
- [ ] Complete the investigation for the 2 posed issues.

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] All the questions are answered.
- [ ] Any documentation is created and linked here.

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by digitaldrk** [comment]
Spreadsheet below has data and graphs that illustrate our error rate over days and months. It also has all errors and their occurance count

[form_status_error_report.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2cvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72fc40f3ad82cde76ff985ac05d29c6d1b241040/form_status_error_report.xlsx)
