### ISSUE TITLE
DMC time out issue tracking 3/3

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#94498]
## Description

As a follow up to these tickets

- [94342 Veteran's failed submission](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94342)
- [94400 Veteran's failed submission](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94400)

Related tickets

- [94494 DMC time out issue tracking 1/3](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94494)
- [94497 DMC time out issue tracking 2/3](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94497)
- [94501 DMC time out issue notifications](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94501)

Research how best to track outages/incidents moving forward so we have a detailed record of events as they are popping up.

## Tasks
- [ ] Research and create a proposal on how we do/can track and report outages.

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] A solution is defined.
- [ ] Steps to implement the solution are documented.
- [ ] A ticket to implement the solution (in the future) is drafted.

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by Tom-Davis** [comment]
Closing based off prior work is complete and no additional issues.
