### ISSUE TITLE
Establish a Veteran facing message when a failure occurs

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#94501]
## Description
Submit a VA Notify ticket in order to send an email to users when a failure occurs.

As a follow up to these tickets

- [94342 Veteran's failed submission](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94342)
- [94400 Veteran's failed submission](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94400)

Related tickets

- [94494 DMC time out issue tracking 1/3](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94494)
- [94497 DMC time out issue tracking 2/3](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94497)
- [94498 DMC time out issue tracking 3/3](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94498)

Establish a Veteran facing message when a failure like this occurs.

## Tasks
- [x] UX Develop a message/display method to be implemented when this error occurs
- [x] Create VA Notify ticket

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required

## Acceptance criteria
- [x] Email message created
- [x] VA Notify ticket created

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by mgleo** [comment]
Help users to stay informed of their form submission status pattern in the Design System: https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status

VA Notify templates:
https://github.com/department-of-veterans-affairs/VA.gov-team-forms/tree/main/Design/patterns/Application%20status/VA-notify-email
