### ISSUE TITLE
[Design] MDT - Update content page with usability study feedback

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#9450]
## Issue Description
During usability testing, we surfaced some issues with the Order Hearing Aid Batteries and Accessories content page that need addressed:

- Veterans weren't recognizing the 'Order hearing aid supplies' button as a method to order online
- Veterans assumed that we were going to send them off to eBenefits, which they don't like
- Veterans assumed that online is no good because they couldn't order accessories online through ebenefits, but they can with our VA.gov tool!

---
## Tasks
- [x] Update the content page [here](https://vsateams.invisionapp.com/d/main?origin=v7#/console/19309480/410077290/preview?scrollOffset=2613)
- [x] Update ticket 7234 and tag Selina Cooper that the update is complete and ready to be built out
- [x] Update this ticket when completed

## Acceptance Criteria
- [x] Ticket is updated
- [x] Selina is notified of the updates

**Comment by rebeccawalsh** [comment]
Changes made in the following screens:
- [Unauthenticated](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/410077289_Content_Page_-_Unauthenticated_-_Desktop)
- [Authenticated](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/410077290_Content_Page_-_Authenticated_-_Desktop)

[Ticket updated for Selina](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7234)
