### ISSUE TITLE
Pension: new statsd to feed ZSF Dashboard

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#94515]
## Issue Description
The purpose of this ticket is to create a Pension-form specific statsd/datadog metrics that feed a Dashboard Steve Albers is creating to track system failures.
Reference [writeup and guidance](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md)

---
## Tasks
- [x] Review [reference documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md)
- [x] In all cases where a Pension system operations result in a silent failure write out a Datadog metric which captures the issue
- [x] In all cases where a Pension system operation would have resulted in a silent failure, but that silent failure was avoided by notifying the Veteran of the issue, write out a Datadog metric which captures the avoided issue
- [x] If there are cases where we cannot write these metric note these cases with the ticket creator & product owner. An example of this would be a case where the team only received notification of errors in email, or where an API used by the system does not provide a success/failure response that matches this goal.

## Acceptance Criteria
- [x]  Metrics created per referenced standards
- [x] Cases where metrics cannot be created are identified and noted

**Comment by mjknight50** [comment]
Relevant dashboard:
https://vagov.ddog-gov.com/dashboard/n6c-twn-swr/silent-failure-tracker?fromUser=true&refresh_mode=sliding&from_ts=1730574102787&to_ts=1730746902787&live=true
