### ISSUE TITLE
[Engineer] Update changed and Rebuild DEVSHOP sites for review and testing [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9451]
## User Story or Problem Statement
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement required va.gov web pages_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[VISN 4 Content Stack Spreadsheet](https://drive.google.com/drive/folders/1f_PRAt67ccYNm5DkJiAKwINsSX_S5_4o)
[Menu and Page checklist](https://drive.google.com/drive/folders/1QliZFSkQHEruGgjOGRihG8tohYxswjm1)
[Pittsburgh Pilot Website](https://va.gov/pittsburgh-health-care/)

## Tasks
_Rebuild and publish of the following Drupal Devshop Sites_
- [x] Altoona
- [x] Butler
- [x] Coatesville
- [x] Erie

## Acceptance Criteria
_Validation that all pages are at least created and ready to accept content from Copy editor_
- [X] Sites are rebuilt in Devshop
- [X]  Sites are published and tested for access
- [X]  Sites are handed off to Review team stories
- [X ]  After review all pages are confirmed, links updated
- [X ]  After updates sites are rebuilt and processed for testing by 508 and Accessibility
