### ISSUE TITLE
Product Spike: Research if we need to notify MyVA

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#94518]
## Issue Description
- [ ] _Research wwe need to notify MyVA to [update status card](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status#status-in-myva)?  Updates may be needed as we implement status notifications as part of Zero Silent Failures initiatives.

---
## Tasks
- [ ] _Review proposed design to [update status card](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status#status-in-myva)?
- [ ] _Interface with MyVA Product owners to understand current state

## Acceptance Criteria
- [ ] _Report out on what/if any changes are needed
- [ ] _Create tickets for any required changes
---

**Comment by aplatt-coforma** [comment]
@matt4su - adding the "design" label to this ticket. I think when Gretchen is available, we should revisit this ticket and potentially use it as the initial design audit for the MyVet cards.
