### ISSUE TITLE
BE | Profile | Document Maintenance Window Setup and Configuration

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#94528]
## Background
Document how to set up PagerDuty services and configure vets-api to poll for these maintenance windows.

## Tasks
- [x] Document how to create PagerDuty services.
- [x] Document how to configure vets-api to poll for maintenance windows.
- [x] Document how to create a maintenance window and verify it's activation in VA.gov
  
## Acceptance Criteria
- [x] Add documentation to VA.gov sensitive repository.
- [x] Walkthrough with VFF team.
- [x] Review with Auth Experience team.

**Comment by tpharrison** [comment]
Walkthrough scheduled with Eric Tillberg (VFF) Oct 8th, 3pm ET.

**Comment by tpharrison** [comment]
Added this document - [BE Maintenance Window Setup Instructions](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/developer/maintenance_window_setup.md)
