### ISSUE TITLE
GA Event Optimization

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#94529]
### Description
This ticket is to implement some of optimization work identified in [this spike ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89612).

> current events that could be moved to pass-thru information collected via other events
> ex: phased-roll-out-enabled event that says what version of the header is loaded generated 15m events in the last 7 days but this information works better for analysis when it's collected with the page_view event along with any direct header interaction events
> dataLayer events with high event counts to see if they've been implemented correctly
> ex: login-account-transition-success-modal-closed fires on nearly every modernized VA.gov page and generated 21m events in the last 7 days. Does it need to?
> interacts already identified with redundant events or that could be better measured in other ways
> ex: loading the login modal fires an attempted login event for each of the login service options when the attempt should instead be measured based on which service the user selects -- 1 user click event instead of 4(?) onload events
> ex: pages with user-/front-end redirects load too far causing the page_view and other events to fire
> Not aiming to identify everything at this time -- double fires are almost impossible to find unless you're already looking at the interaction for measurement.

---

### Tasks

- [ ] Implement tracking optimization
- [ ] Confirm events are still being tracked
- [ ] Quantify estimated reduction in hits

### Acceptance Criteria

- [ ] Initial round of tracking
- [ ] Number of hits/events have been redcued
