### ISSUE TITLE
DOMO Dashboard / CSAT Discovery

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#94533]
_What details are necessary for understanding the specific work or request tracked by this issue?_

In this new fiscal year, the VA is going to measure progress toward OKRs by capturing more quantitative data on Veteran satisfaction with VA.gov as a whole experience.

One way to capture this progress is through tracking CSAT scores on Medallia surveys.

Reporting on CSAT scores over time for the debt portal and FSR pages is a goal for our team.

Since the CSAT is measured differently across the 3 surveys that are live on the site so far, the team is finding the best way to capture past scores that are both valid (accurate) and reliable.
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [ ] Create Mural to identify CSAT questions and best practices
- [ ] DOMO dashboard discovery
- [ ] Meet with Analytics team
- [ ] Goal 3
- [ ] Goal 4

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [ ] Mural created
- [ ] DOMO dashboard discovery
- [ ] Attended Analytics Office Hours
- [ ] Domo dashboard URL corrections
- [ ] Removal of modal/pop up survey in the debt portal
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSA---Debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/94533?planning-poker) with Zenhub @charlottecesana
