### ISSUE TITLE
Edit: Emoji Guidance for Style Guide

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#94535]
## User Stories
As a VFS Team member, I need to understand the meaning of emojis used on Platform website documentation, so that I can confidently build on va.gov

As a Platform team member, I need to know whether I can use emojis in documents I am writing so that I won't create launch blockers that would delay the publishing of my document on Platform website.

As a Platform Content team member, I need to know what uses of emojis are OK for documentation living on Platform website, so I can look for Launch Blockers and advise authors of documents.

## Issue Description
Related to [ticket 91935](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91935), we need to edit and publish the guidance on use of emoji.

---
## Tasks
- [x] Create final version of Emoji Guidance

## Acceptance Criteria
- [x] page is complete and published on Confluence
- [ ] announce on #platform-content
- [ ] schedule for future Tip of The Sprint
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/94535?planning-poker) with Zenhub @cmarion93

**Comment by jknipes** [comment]
Work is complete, moving to _Closed_

**Comment by jknipes** [comment]
![Image](https://github.com/user-attachments/assets/12d5e7f3-48fc-4c68-b914-1b2b9f0010f6)
