### ISSUE TITLE
[ENG] 10-10CG - BUG: Investigate browser autocomplete issues on form

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#94536]
## Benefit to the Veteran
As a Veteran, I would like to use my browser's autocomplete functionality to complete common sections of the form with my saved info, so that I don't have to type everything out.

## Scope
Investigate a found issue during one of the CG research sessions (video below).  If no one on the team uses autocomplete within the browser, may need to create info for one to test out this issue and dive into what is happening when it autofills. FakeFiller plugin has been used in the past with no issues, so might need to use something more specific to the user of the browser for this investigation.

> Our participant was filling out one of the form pages (in staging btw) using autocomplete and then the "continue" button didn't do anything when she clicked it and no error was popping up either. I had her refresh the page and that was clearly a mistake because it took her back to the beginning of the form and erased everything

Comment from Matt Long (FE)
>If I had to make a guess... It’s going to be something with the state select box not registering the form data. I’ve seen that on other platforms with autocomplete.

https://github.com/user-attachments/assets/7db218d8-7838-458f-b88a-849ef718b435

## Tasks
- [ ] Investigate issue to determine root cause
- [ ] Confirm if root cause impacts other forms on VA.gov
- [ ] Review with team/PM for next steps

## Acceptance Criteria
- Determine what may be the root cause of the issue found, and whether it is widespread on VA.gov or specific to our form.

**Comment by allanto-ah** [comment]
@Mitch-A6 I'm not sure if this issue is related, but wanted to bring it to your attention. I've only ran into this in Safari so far. Haven't seen this is Microsoft Edge, Chrome, Firefox

### Issue 1: On Safari (18.1), when I try to edit the birth date, it seems to remove some of the text in the other fields

https://github.com/user-attachments/assets/0d26bdc2-de55-4c5b-b159-7b1d74d26207

**Comment by Mitch-A6** [comment]
This fix was manageable for the custom FormField components of [AddressWithAutofill](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/caregivers/components/FormFields/AddressWithAutofill.jsx), but unfortunately the other fields are all run through the Forms System where we have less control. I'm checking whether that's feasible from our end.
