### ISSUE TITLE
DR | Update Lighthouse Pundit Policy to remove first name check for ITF

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#94544]
## Value Statement

**_As a_** Veteran without a first name on my profile

**_I want to_** the system to be able to submit an ITF for me without a permissions/403 error

**_So that_** I can get credit for when I decided to start my form

---

## Background Context

When [updating the pundit policy for ITF to reduce unnecessary 403s](https://github.com/department-of-veterans-affairs/vets-api/pull/17129), Lighthouse had still checked for a first name for their ITF endpoint. They no longer needed it but to get our fix in sooner, we just included it as a part of the policy. They've [now updated their endpoint](https://dsva.slack.com/archives/CE6UEJ6BZ/p1721233484503439?thread_ts=1717100090.559599&cid=CE6UEJ6BZ) to not check for first name anymore, so we can remove it from our check as well.

If unable to access that thread in the `#api-benefits-claims` slack channel, here's what Kayla Watanabe said:

On June 18th, 2024

> We looked into this further and found that we originally added the check for first name as it was recommended for an internal request we were making to EVSS. We are no longer using that EVSS service and confirmed that we do not require a first name for establishing an intent to file. I will add a ticket to our backlog to remove that check to prevent this error for future intent to file requests.

and on July 17th, 2024
> We deployed an update yesterday that removes the internal check for first name on our intent to file service. Please let us know if you continue to see any issues related to this.

## Acceptance Criteria

- [ ] Users with no first name will not see a 403 when they try to hit our ITF endpoint

## Tasks

- [ ] Update [this Lighthouse policy](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/policies/lighthouse_policy.rb#L14-L18) to remove the check for a user's first name

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design
