### ISSUE TITLE
[Design, FE, QA] 10-10CG - Improvements: Update Confirmation page to remove "24 hour" reference

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#94550]
## Benefit to the Veteran
As a Veteran, I want the submission confirmation page to provide clear expectations of what will happen next, so that I am not mislead or misunderstanding the CG application process.

## Scope
Update the content on the Confirmation page, removing the reference to "24 hours", and replace with more consistent, clear guidance.
Info from CG team:
>After reviewing with the team, we would recommend updating the language in the first bullet point to clarify that the user should receive an autogenerated email, as there appears to be confusion around being contacted by staff within that time frame. We will defer to your team for any suggestions, but would like to see language that aligns with the following:
>- "If you gave us your email address, you will receive an autogenerated email. Make sure to check your inbox and your spam or junk folder."

## Resources
- [Figma Design](https://www.figma.com/proto/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2930-67957&node-type=instance&t=EUUhWg1tjIgVWLwc-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A4727&starting-point-node-id=2930%3A67957)
- Screenshot of current content
     - ![Image](https://github.com/user-attachments/assets/17290502-8391-4434-bafa-2877d5a15c40)

## Tasks
- [x] Work with Content to review and update Confirmation page
- [x] Update designs and review with PM/FE teammates
     - PM will inform CG stakeholders
- [x] Update UI content
- [x] Inform PM/QA for readiness
- [x] PM/QA to complete validation
     - [x] Signoff in comments is required prior to launch
- [x] Launch to production
- [x] Inform CG stakeholders of production update to confirmation page

## Acceptance Criteria
- The CG Confirmation page has been updated to remove specific reference to the applicant being contacted within "24 hours", replaced with more accurate, consistent content

**Comment by jessicastump** [comment]
[Figma page started here](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=3389-7821&node-type=canvas&t=UOFKVEyRDVNDybkT-0) and will schedule a meeting with Aliyah (CAIA) to review early this week/review async via Slack

**Comment by jessicastump** [comment]
@hdjustice - CAIA ticket opened here: [CAIA Intake] <Health Enrollment 1010 Team>: <10-10CG Caregiver Application - Confirmation Page Edits> #95502
Chatted with Aliyah today - they needs to confirm on their end if using the content "confirmation email from our system" is okay in place of auto-generated. Once I hear back, this should be quick to resolve.

**Comment by hdjustice** [comment]
great!  I have it on for next sprint, hopefully we can knock it out, but I know Aliyah has a ton of stuff on her plate

**Comment by jessicastump** [comment]
From Aliyah and will put recommended content draft below:

> After chatting more with our managing editor, we likely wouldn't recommend specifying that the confirmation email comes from a "system" vs. a "live person."

> - Specifying that the confirmation email is coming from an automated system isn't part of our site style. Across different VA products (forms, tools, text systems) we don't describe that emails or notifications are coming from an automated/auto-generated system. 
> - We don't talk about auto-generation in the more recent email content that's in the design system - and there aren't plans to update that right now. 


---- 

### Draft 10/22/24

[h2]What to expect next  

A member of the Caregiver Support Team where the Veteran receives care or plans to receive care will contact the Veteran and any caregivers to discuss this application and eligibility.  

**If you shared your email address**, you'll receive a confirmation email first. Then we’ll contact you to discuss this application and eligibility. Be sure to check email inbox, spam, or junk folders.  

**If you didn't give us your email address**, we'll contact you by phone or mail to discuss this application and eligibility.

**Comment by hdjustice** [comment]
We can share via email, but also discuss in this Friday's stakeholder call

**Comment by hdjustice** [comment]
Sent email to CG stakeholders with draft content and received a same-day response from Gaspare that it looked good.  We can move foward with the Confirmation page update.

> Thanks Heather for the updated prompt and the explanation on the language used.
> 
>  We reviewed the suggested draft from 10/22/24 and it looks good on our end!
> 
> Our team will be on VA travel during the upcoming meeting this Friday – is there any chance we can cancel and cover the agenda items on the following call?
> 
> Thanks in advance,
> 
> Gaspare
> 
> Gaspare Caruso, LCSW  (He/Him)
> Acting Health System Specialist-CARMA|EHR
> Caregiver Support Program
> VA Central Office

**Comment by longmd** [comment]
@hdjustice / @allanto-ah , [here is a review instance link](http://6005f8ab228a2959c9dbeada0e9b4b6b.review.vetsgov-internal/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg/introduction) to validate the updates. Here is the screenshot of the updates from my validation:

![Screenshot 2024-11-06 at 10 49 59](https://github.com/user-attachments/assets/2e8a1b6b-0095-4640-8a23-eff636a148f1)

**Comment by allanto-ah** [comment]
Environment: RI

Verified that this matches the designs. Looks like PM approved, we should be good to go to production

**Comment by hdjustice** [comment]
Yes, good to go to prod.  Thanks for checking it out @allanto-ah !
