### ISSUE TITLE
Implement monitoring for invalid rep addresses

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#94572]
## Background
We discovered in #93624 that there were 657 representatives with an invalid address, which resulted in their latitude and longitude being set to 0 and thus did not allow the representatives to be associated by users' search locations as expected. 

The fix will be tackled in https://github.com/department-of-veterans-affairs/va.gov-team/issues/94579, but it'd also be nice to set up monitoring so that we can be more aware if any other representatives have invalid addresses.

## Tasks
- [ ] Set up Data Dog monitoring for when addresses are invalid
- [x] Route notifications to #benefits-representation-management-notifications Slack channel

## Acceptance Criteria
- [ ] The ARM team will be notified when representatives have invalid addresses.
