### ISSUE TITLE
Prep Reporting Table for Mobile Team & Date Suffix Query Changes

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#94570]
### Description
This task is to implement some of the recommendations we identified in https://github.com/department-of-veterans-affairs/va.gov-team/issues/93505.

---

### Tasks

- [x] Meet with Victor on 10/10 to help implement date suffix changes to Looker report
- [x] Finish prepping new reporting table as defined in our recommendations from our first task.
- [x] Create a partitioned Mobile Team reporting table in BQ.
- [ ] Automate the daily process of extracting and summarizing the subset of data needed for the Moblie team reports from most recent GA partition, appending the results to a permanent partitioned mobile team reporting table in BQ.
- [x] Enforce all date selections in looker to reference the partiton column in the mobile team reporting table

### Acceptance Criteria

- [x] Data suffix changes have been made to the Looker report -- Mobile owned task, but offering our support.
- [x] Reporting table is prepped and ready for Mobile Team -- **Update:** Work is dependent on a few things from the Mobile Team -- who will be the ones to implement the actual changes -- will be implemented next sprint.
