### ISSUE TITLE
Pension | Design: Update Alert and what to expect next section on Confirmation page

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#94580]
### Background: 
As part of the ZSF effort, there are some changes that all team's are asked to include in their product confirmation pages per VFS guidance. This includes an alert box and the "what to expect next" section. See page template link below.

Figma page template: https://www.figma.com/design/dlhofkIJz3MC81PD0pJAb8/OCTO-%7C-Form-Status-Project-(VFF-%2B-My-VA)?node-id=69-82688&node-type=frame

### User Story: 
As a veteran who just submitted my Pension application, I want to be informed of my submission process.

### Tasks:
- [ ] Create draft to review with CAIA and work with them to make sure the entire page still makes sense
- [ ] Review with Dene for approval 
- [ ] Inform Product/Scrum master when ready for Eng

### Acceptance Criteria
- [ ] Figma design file is created using the approved design and copy
- [ ] Update <Eng ticket> with any additional info and provide handoff sync with eng

**Comment by gmaciolek** [comment]
[Pension confirmation page design file](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/WIP---21P-527EZ---Pension-Benefits?node-id=9392-54150&t=ohOVsiCmr4wy665h-4) is ready for engineering.

Note:
- The time frame in the alert re: how long it takes us to receive a form is still unconfirmed. I assume we can start on the rest of the updates to the page and update this number, if needed, after confirming it.
- Start with the annotations for the authenticated desktop experience. For the unauthenticated experience, I only annotated where it differs from the authenticated experience.

Question:
Is there anything that needs to be done from an engineering perspective to enable tracking clicks on the link in the alert?
