### ISSUE TITLE
Burial | Design: Update alert and what to expect next section on confirmation

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#94581]
### Background: 
As part of the ZSF effort, there are some changes that all team's are asked to include in their product confirmation pages per VFS guidance. This includes an alert box and the "what to expect next" section. See page template link below.

Figma page template: https://www.figma.com/design/dlhofkIJz3MC81PD0pJAb8/OCTO-%7C-Form-Status-Project-(VFF-%2B-My-VA)?node-id=69-82688&node-type=frame

### User Story: 
As a veteran who just submitted my Burial application, I want to be informed of my submission process.

### Tasks:
- [ ] Create draft to review with CAIA and work with them to make sure the entire page still makes sense
- [ ] Review with Dene for approval 
- [ ] Inform Product/Scrum master when ready for Eng

### Acceptance Criteria
- [ ] Figma design file is created using the approved design and copy
- [ ] Update <Eng ticket> with any additional info and provide handoff sync with eng

**Comment by gmaciolek** [comment]
[Burial confirmation design file](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=3857-8187&t=m6lNLsYjwp74LBux-4) is updated for engineering. Things to note:
- The time frame indicated in the alert for how long it can take for a form to be received is still unconfirmed. I'm assuming we can move ahead with the rest of the changes to the page and we can update that number if we need to, once its confirmed.
- Start with the annotations in the authenticated desktop version. For the unauthenticated experience, I only annotated parts of the page that differ from the authenticated experience.
- I didn't annotate the mobile designs (the changes are the same as for desktop), I just added some spacing guidance.

Question:
Is there anything in particular that needs to be done from an engineering perspective to track clicks on the link in the alert? We'd like to track interaction with that alert to see if users are clicking on it and leaving the page without scrolling to see the rest of the content.
