### ISSUE TITLE
Copy of Design | VRE | ZSF Confirmation Page MVP

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94588]
## Issue Description
_When a user submits a claim on VA.gov, the confirmation page should allow them to check the claim's status and outline what's next._

- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [Confirmation page template](https://www.figma.com/design/dlhofkIJz3MC81PD0pJAb8/OCTO-%7C-Form-Status-Project-(VFF-%2B-My-VA)?node-id=69-82688&node-type=frame&t=orq6V1C4T9yfiiS0-11)
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks
- [ ] Update confirmation page designs to:
   - [ ] Align to design system guidance for application status
   - [ ] Align to design system guidance for "what's next" info

## Acceptance Criteria
- [ ] Wireframe that includes application status updates and what's next info
---

**Comment by steele-lm** [comment]
Blocked: Waiting on API development to allow retrieval of pdf.
