### ISSUE TITLE
Document issues with XX date

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#94584]
Issue Description
As a member of a VA team or OCTO, I would like a summary of the issues with XX date so that I can be sure I am getting an authoritative perspective of this issue. Currently I have to Slack farm and cobble together disparate pieces of information and I'm not sure what is true, what is current, and what I should use as my source of truth if I'm either working to understand this issue or facing this issue currently in my product.

---
## Tasks
- [x] Investigate issues that came through with X's for military service dates
- [x] Investigate issues related to TE
- [x] Meet with folks to better understand backend engineering challenges

## Acceptance Criteria
- [x] A published document in Github covering the issue with appropriate detail

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by christinec-fftc** [comment]
doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/implementation/94584_summary_of_invalid_dates.md
