### ISSUE TITLE
Update the Debt Portal Tech Stack Document

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#94596]
## Description

We need to have the Debt Portal Tech Stack Document audited and updated where necessary.

We expect this to be a FE/BE collaboration - perhaps more contributors depending on the topic.

The document is located here: [Debt Portal Tech Stack Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/general/tech-stack.md)

## Tasks
- [x] Update the Debt Portal Tech Stack Document

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] The Debt Portal Tech Stack Document has been updated and the team and VA PO notified.

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by JunTaoLuo** [comment]
@Dr-Pongo and I have finished updating the document. Thanks Andrew!

**Comment by denisecoveyduc** [comment]
Thanks @JunTaoLuo  and @Dr-Pongo  I spoke with @dhill802 about having the rest of the engineering team read it over in case they notice anything is missing or needs further clarification but agree that this document fulfills the need. Thank you!

**Comment by digitaldrk** [comment]
LGTM 👍
