### ISSUE TITLE
Generate performance reports for each app on vets-website

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#94624]
Using the webpack-bundle-analyzer, we need to generate a performance report for each app on vets-website. Using these reports, any relevant tickets to reliability team, or the app team, should be made.

## Tasks
- [ ] Generate a webpack bundle analyzer report for each app on vets-website
- [ ] Generate any tickets that result from those reports.

## Acceptance Criteria
- [ ] Tickets have been made to cover any performance issues present in apps.
