### ISSUE TITLE
Execute Diary Study with Governance team

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#94627]
## User Story
As a Governance team member, I want to participate in the Diary Study for bringing Mobile App into the Collab Cycle so that I can begin to understand what mobile knowledge gaps exist for my practice area. 

Assignee: @allison0034 @briandeconinck @erinrwhite @it-harrison @KKitagawa-Bosch 
Peer Reviewer: @shiragoodman 

## Description
In ticket #93602, we defined our plan for completing the Diary Study for bringing mobile app into Collab Cycle. In this ticket, Governance team members will complete the exercise for their practice area with at least 1 Design Intent, 1 Midpoint Review and 1 Staging Review. Governance team members are encouraged to document their observations from more than 1 of the specified touchpoints, however 1 is the required minimum. Observations for the Diary Study should be documented in the appropriate practice area child page for the [Diary Study research method.](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3524820993/2024-10+Research+Plan+for+Governance+Team+Adding+Mobile+App+to+the+Collaboration+Cycle+Diary+Study)

## Tasks
- [ ] Review the Diary Study research approach to understand what is expected of you
- [ ] Before, during and after each Collab Cycle touchpoint included in the research, document your practice area specific observations and questions in the appropriate child page of the [Diary Study research method.](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3524820993/2024-10+Research+Plan+for+Governance+Team+Adding+Mobile+App+to+the+Collaboration+Cycle+Diary+Study)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Design representative from the Governance team has documented their observations/questions from a Design Intent, Midpoint Review and Staging Review
- [x] The Accessibility representative from the Governance team has documented their observations/questions from a Design Intent, Midpoint Review and Staging Review
- [x] The Information Architecture representative from the Governance team has documented their observations/questions from a Design Intent, Midpoint Review and Staging Review
- [x] The Content representative from the Governance team has documented their observations/questions from a Midpoint Review and Staging Review
- [x] The Quality Assurance representative from the Governance team has documented their observations/questions from a Staging Review

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Beginning diary study for design.

**Comment by shiragoodman** [comment]
@allison0034 @KKitagawa-Bosch @erinrwhite @briandeconinck @it-harrison Are you all logging your diary entries someplace private? There is not a single update to any of [diary study practice area pages ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3524820993/2024-10+Research+Plan+for+Governance+Team+Adding+Mobile+App+to+the+Collaboration+Cycle+Diary+Study) and we have had 2 design intents, 1 midpoint review and 2 staging reviews since the start of this sprint. I had expected you all to use these pages to document your questions and concerns for the upcoming touchpoints but it it does not appear that ANY of you have done that. This work will clearly need to move over into the next sprint. 

For all upcoming touchpoints applicable to your practice area, PLEASE make the diary study a priority. If you are having trouble managing your workload, please let me know and we can discuss, but failing to complete the diary study is not an option.

**Comment by erinrwhite** [comment]
@shiragoodman I should have read through more slowly! I have definitely been logging this info in my private notes. I will move my notes so far over.

**Comment by KKitagawa-Bosch** [comment]
Just added my stuff to confluence!

**Comment by allison0034** [comment]
I started it last week. I planned on reviewing the recordings for past touchpoints today. I also scheduled a meeting with the new mobile app designer for tomorrow.

**Comment by shiragoodman** [comment]
Thanks @erinrwhite @KKitagawa-Bosch and @allison0034 .

Allison - I think you're jumping the gun a little bit. We will be reaching out to the mobile app folks, but that's not part of this research. The findings from the cognitive walkthrough and diary study will ideally help drive the conversations we need to have with our mobile app counterparts. you can continue with your meeting, but please note that you'll likely need to meet with them again.

**Comment by shiragoodman** [comment]
1 team member is still working on their diary study, so this work will move into the next sprint.
