### ISSUE TITLE
Finalize new Collab Cycle flow design and publish to Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#94634]
## User Story
As a Governance team member supporting the Collab Cycle, I want to finalize the new simplified visual of the full Collab Cycle so that I can publish it to Platform Website for VFS team use.

Assignee: @allison0034 
Peer Reviewer: @erinrwhite 

## Description
In ticket #93198, Governance team proposed a new design demonstrating the overall flow of the Collaboration Cycle. This design is intended to replace the [current swimlane diagram ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713545938981/37e39668eee6d6756e56b687f9c7851632340258?sender=u870c8d9c6b47768924793768) because the swimlane diagram 1) has become too complicated and cluttered due to the addition of several new touchpoints in 2024 (CMS Request, PO Sync and Architecture Intent), and 2) due to the size of the diagram, it's not able to be published as an image on Platform Website and is only accessible from a link, meaning it's not as visible to VFS teams as we'd like it to be.

In this ticket, we will finalize the design for the [new, simplified visual (version 4) ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727377585674/2799354ec00423d2403b66482662a2c80ccab903?sender=u870c8d9c6b47768924793768), and publish the image as an image file, no longer as a Mural. Then, the new visual will be published to the [Collaboration Cycle Overview page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/overview) and the link to the swimlane Mural will be removed. Due to this change, we will need to reevaluate the existing content and potentially make changes.

We will ensure that the new image and new content meets our own standards for design, accessibility, content and IA.

### Live pages
- [Collaboration Cycle Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/overview)

### Drafted pages
- [Collaboration Cycle Overview](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3533864961/94634+Allison+Collaboration+Cycle+Overview)

## Tasks
- [x] Review comments from Platform leads and other Collab Cycle leads from [this Slack thread.](https://dsva.slack.com/archives/G01DXP10GCA/p1728415308346619) Incorporate any feedback if the recommendation is valid.
- [x] Finalize the design and the content within the design
   - Note: as discussed on 10/8 in the review with Governance team, the "When to schedule" section should not be part of the image and should be published as content on the Collab Cycle Overview page.
- [x] Convert the design from a mural to an image file (png, jpeg, whatever makes sense)
- [x] Create a draft of the Collab Cycle Overview page
- [x] Remove the old swimlane mural link
- [x] Add the image and the "when to schedule" content to the page
- [x] Ensure you have written appropriate alt text for the image. Consult @briandeconinck for his input.
- [x] Submit for peer review 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have removed the swimlane mural diagram from the Collab Cycle overview page
- [x] We have added the new Collab Cycle flow diagram to the Collab Cycle overview page

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@KKitagawa-Bosch can you please take a look at the content on the [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727377585674/2799354ec00423d2403b66482662a2c80ccab903?sender=u870c8d9c6b47768924793768)?

**Comment by KKitagawa-Bosch** [comment]
@allison0034  Made some comments in the mural!

**Comment by allison0034** [comment]
@KKitagawa-Bosch I made most of your content changes. Everything is now in the actual draft in the draft section of this GH ticket. Want to take another look? For context, all the info was pulled from [PW collab cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/touchpoints).

@briandeconinck can you please help with alt text?

**Comment by KKitagawa-Bosch** [comment]
@allison0034 looks good overall! Made one more comment and also bumping that the "general comment" about periods on the right side is still there. Very small stuff, both of them

**Comment by allison0034** [comment]
@KKitagawa-Bosch I don't see any comments in the draft page??? Am I missing them? ; )

**Comment by KKitagawa-Bosch** [comment]
Oh! Sorry I was commenting in the mural still. Post-SR brain :P 

I'll go look at the draft page!

**Comment by allison0034** [comment]
@shiragoodman take a look at the [draft page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3533864961/94634+Allison+Collaboration+Cycle+Overview) when you get a chance, I had to adjust the layout of the text for accessibility (heading structure and font size) reasons.

**Comment by erinrwhite** [comment]
@allison0034 I added some comments too - thanks for the lift on this!

**Comment by KKitagawa-Bosch** [comment]
@allison0034 left one baby comment (literally one missing period) otherwise looks solid!

**Comment by shiragoodman** [comment]
@allison0034 I reviewed, and it looks good. the only concern I have is when to schedule CMS Request. please review my comment Allison, and reach out to CMS team for clarification. Please tag the thread here. ty!

**Comment by shiragoodman** [comment]
@allison0034 per our conversation via Slack, please move forward with the work with the CMS Request content as-is. I will reach out to Grace and we can discuss how to proceed. If we make any changes, it will be handled in another ticket. Thank you!

**Comment by allison0034** [comment]
@briandeconinck I added engineering to the list, also I need the alt text.
@erinrwhite you can review everything except alt text : )

**Comment by briandeconinck** [comment]
@allison0034 Added alt text. Whew!

**Comment by allison0034** [comment]
@erinrwhite we are good to review. : )

**Comment by erinrwhite** [comment]
Looks good @allison0034 just don't forget to update the last updated date when you push to live!

**Comment by allison0034** [comment]
@erinrwhite thank you!
