### ISSUE TITLE
Complete initial onboarding for working in VAHB

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#94639]
## Tasks

- [x] [Review VA: Health and Benefits app documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/UX/How-We-Work/designing-ui/)
- [x] Install and [run VAHB demo](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DemoMode/#steps-to-access-demo-mode) (Link updated)
- [x] Start to think about entrance paths for pre-check-in after getting an understanding of [VAHB information architecture](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/UX/How-We-Work/designing-ui/#iaflows). (No deliverable on this task.)
- [x] Review intake document where OCTO and VAHB leadership discuss scope
- [x] Document scope questions
- [ ] Review profile part of VAHB to help answer Don's question about reusing it

**Comment by benbrasso-agile6** [comment]
@zach-park once the tickets in this upcoming sprint are completed, this is a ticket that we'll all want to work on individually

**Comment by zach-park** [comment]
@StevenStraily @cgednalske , I'm wondering if anyone has a test user credential that we could use to log-into the app. If so, please let me know. Thank you!

**Comment by juancstlm-a6** [comment]
@zach-park Any user that works on va.gov staging should work on mobile. You can also use the demo mode feature on the app. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Demo%20Mode%20Access/demoModeAccess.md

**Comment by zach-park** [comment]
Completed onboarding.

**Comment by cgednalske** [comment]
If we're all done with this I think we can close it! 🎉
