### ISSUE TITLE
[CST] Silent Failures CST UI Design Exploration

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#94646]
## Value Statement
**_As a_** Veteran
**_I want to_** understand when a failed document upload in CST has occurred
**_So that_** I can take the necessary action to remediate that failure and get my claim related documents into the VA

---
## Background Context

As part of the Silent Failures initiative, we created some ideas for CST UI improvements as part of the [Silent Failures Journey Map](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93555). This ticket's work is to create the actual spec for those design improvement proposals in Figma and share with the team. There are also a few open questions that came out of the Journey Map discussion that need to be answered in the design proposal.

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] _Create spec for proposed CST Silent Failures UI improvements_
- [ ] _Answer open questions generated in Journey Map discussion_
- [x] _Share design spec with the team_
- [ ] _Share with enablement team_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] _Design spec for this work is documented in Figma_
- [x] _Spec has been shared with BMT team_

**Comment by uxgary** [comment]
Design file has been [linked](https://www.figma.com/design/m1Xt8XjVDjZIbliCYcCKpE/Silent-Failures-CST-Improvements?node-id=2266-8707&t=pC1vKwnWwbko3Fcn-4)
