### ISSUE TITLE
[FE] Badge Indicator: "Componentization" process familiarization

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#94649]
## Background
When we get into the badge indicator build we will also need to keep in mind that it will need to be built as a web component to be entered into the design system. We need to review the process we went through previously so we can understand and better form our approach.

## Tasks
- [x] Review [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/badge-indicator/badge-indicator-FE-documentation.md) to understand specs and goal of badge indicator
- [x] Review [experimental design + component build](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/update-design-system-component/documentation/experimental-design-and-component-build.md) documentation
- [x] Reach out to DSC with any questions
- [x] Coordinate with Matt and Allison (who previously did a  component build) as needed
- [x] Work with PM to create FE tickets for implementation as needed or make updates to existing FE implementation [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91205)

## Acceptance Criteria 
- Team understands technical approach for badge indicator build and how to incorporate component build process

## Resources
- #59398 (last time the team built a component)

**Comment by DanielMiller-agile6** [comment]
I think the deal situation will be to build out our UI component with styles + react in the most basic state (html + css).  This could be done without a Web Component to start with.  This will allow us to build our our feature, and provide a prototype of the component to learn if additional functionality should be built into the eventual DS component.

Badge indicator could just be a new class name, which would make it more flexible.  Although if we'd like the "clamping" behavior (i.e. values over 99 display as "99+") to be built into a Web Component, we should do that inside of the DS repo after arch review.
