### ISSUE TITLE
Create Decision Review failed form email template

### ISSUE THREAD

**Issue by comaurice** [department-of-veterans-affairs/va.gov-team#94659]
## Value Statement

**_As a_** veteran

**_I want to_** to receive notification if my form submission fails (0995/0996/10182)

**_So that_** they can submit the form through other means and still get their claim established.

---

## Background Context

- We have an email template for the evidence already but need one for the original form submission too

## Outcome, Success Measure, KPI(S), and Tracking Link

- An email is able to be sent to the Veteran with the proper template designated for it

## Acceptance Criteria

- [x] A template is established for form submission failures for the following forms
   - [x] 20-0995 Supplemental Claim
   - [x] 20-0996 Request for Higher-Level Review
   - [x] 10182 Request a Board Appeal
   - [x] 21-4142 & 21-4142a "Authorization to Disclose Information to the Department of Veterans Affairs (VA) | General Release for Medical Provider Information to the Department of Veterans Affairs"
   - [x] Evidence upload within 0995 Supplemental Claim
   - [x] Evidence upload within 10182 Request a Board Appeal

## Design / Build Notes

- [FIGMA](https://www.figma.com/design/XMIeCLMBlMNgCFk01RuuSu/Decision-Reviews-Post-Submission-Failure-Notification-Emails?node-id=0-1&node-type=canvas&t=a9KySPQDERRHeCyU-0)

### Enablement team (if needed)
@ member of team

## Out of scope

- Add here

## Open questions

- Check with 526 team if they have a template already
   - We adapted the template they're using for form (but it doesn't fully apply to ours) and evidence.
   - They're looking to adapt our 4142 form template, since the one they created doesn't quite follow governance.

## Tasks

- [x] Create email template design/copy specs
- [x] Create email templates on VANotify
- [ ] Analytics link generator
- [x] Submit [VA Notify Intake Ticket](https://github.com/department-of-Veterans-affairs/va.gov-team/issues/new?assignees=christy-tongty%2C+mjones-oddball%2C+GitSamJennings&labels=vanotify-intake&template=VANotify-Business-Intake.md&title=Business+intake+form+for+%5BBusiness+or+team%5D)
- [ ] Contact Center review (pre staging)
   - [ ] Supplemental Claims
   - [ ] Board Appeals
   - [x] Higher-Level Review 
- [ ] Privacy Officer review (post staging)

**Comment by shaunburdick** [comment]
Link to thread talking about the required privacy review: https://dsva.slack.com/archives/C07KTTFP308/p1729097179636119

**Comment by shaunburdick** [comment]
Link to template for Privacy Review: https://github.com/department-of-Veterans-affairs/va.gov-team/issues/new?assignees=christy-tongty%2C+mjones-oddball%2C+GitSamJennings&labels=vanotify-intake&template=VANotify-Business-Intake.md&title=Business+intake+form+for+%5BBusiness+or+team%5D

**Comment by eileen-coforma** [comment]
I included the design for the form submission error emails. I also [linked](https://dsva.slack.com/archives/C06V3RU6HA9/p1729199668129209) it to Julie and Amy for review. Once I get approval, I'll let Derek know.

**Comment by eileen-coforma** [comment]
@dfong-adh @shaunburdick 

A few questions:
Do we have different use cases for failure types or will it all be individual emails? Ie.
1. Do we need a notification for a full form failure? Form + attached documents + ancillary forms (whole shebang) AND/OR
2. Do we need a notification for separate failures? 
   a. Form by itself
   b. Evidence by itself (if so, will it be single emails for each piece of evidence failed?)
   c. Ancillary forms by itself

**Comment by shaunburdick** [comment]
> [@dfong-adh](https://github.com/dfong-adh) [@shaunburdick](https://github.com/shaunburdick)
> 
> A few questions: Do we have different use cases for failure types or will it all be individual emails? Ie.
> 
> 1. Do we need a notification for a full form failure? Form + attached documents + ancillary forms (whole shebang) AND/OR
> 2. Do we need a notification for separate failures?
>    a. Form by itself
>    b. Evidence by itself (if so, will it be single emails for each piece of evidence failed?)
>    c. Ancillary forms by itself

Option 2!

**Comment by eileen-coforma** [comment]
Last Friday, I asked Andrew Gray a few questions about the SC process to clarify how evidence can be sent/processed for an 0995 if it's not sent with the form.

> Should evidence be sent to the same address as the 4142 for SC compensation claims?
> What happens if an SC is received without evidence (due to failure in the digital process)?
> Is there a time period for the Veteran to submit their evidence separately?
> What are the impacts of duplicate evidence?

**Comment by eileen-coforma** [comment]
I created a VANotify draft email for HLR form failures. Sent tests to Julie and DK.

**Comment by eileen-coforma** [comment]
Had a chat with Julie about the email templates. Got her approval. 
Designs are done in FIGMA. Not yet in VANotify. Maurice and I should have edit access now, so we can do this, or should we have Derek do it?

- [ ] Will need to make a VANotify intake request for this work.
- [ ] Get CAIA to review the 4142 email template, since it varies from the VFF templates.
- [ ] Need to create these templates in VANotify.
- [ ] Need to set up a PO review.

@shaunburdick @comaurice do we want a separate ticket for the following approval work, or do you want to use this ticket to push everything to finish (production-ready)?

I also snagged this list of to-dos from another team. Do we want to separate these into tickets and responsibilities?

Pre production reviews 
- [ ] Submit [VA Notify Intake Ticket](https://github.com/department-of-Veterans-affairs/va.gov-team/issues/new?assignees=christy-tongty%2C+mjones-oddball%2C+GitSamJennings&labels=vanotify-intake&template=VANotify-Business-Intake.md&title=Business+intake+form+for+%5BBusiness+or+team%5D)
- [ ] Engineering review of  [VA Notify API docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify#general-steps)
- [ ] CAIA review (pre Contact Center) 
- [ ] Contact Center review (pre staging)
- [ ] Privacy Officer review (post staging)

DataDog Monitoring
- [ ] Dashboard 
- [ ] Notification of successful email sent
- [ ] Notification when emails fail to trigger/send
- [ ] See [DataDog metric increment](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/274bea7fb835e51626259ac16b32c33ab0b2088a/platform/practices/zero-silent-failures/logging-silent-failures.md) for proper labeling 

Pre-production 
- [ ] Confirm access to [VA Notify Self Service Portal](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify#getting-access-to-our-self-service-portals)
- [ ] Staging testing 
- [ ] Obtain Production API key from VA Notify
- [ ] Push templates to production VA Notify

**Comment by kayline** [comment]
Break out DataDog and Pre-Pro to separate tickets

**Comment by eileen-coforma** [comment]
Submitted VANotify intake ticket: [Business intake form for Benefits Decision Reviews](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95708)

Sent an email for VA OIT Privacy Officer to see if we can get the PO approvals, but Amy left this note:

> Just saw your email to the OIT Privacy Officer -- thanks for sending it!
> As a FYI, we've gotten inconsistent feedback around whether the OIT or VBA Privacy Officer is the right group to reach out to :melting:. Regardless, we're also trying to determine whether we can bypass privacy officer review for ZSF emails or if they can be centralized.

Moving this to blocked/waiting until we get response on either of those two items.

**Comment by eileen-coforma** [comment]
Created a separate ticket for the Datadog and Pre-production tasks [Prepare Decision Review failed form email templates for PROD](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95703)

**Comment by eileen-coforma** [comment]
Reached out to John G for verification on the evidence submission methods for NOD

Templates are in VANotify

Contact Center Reviews may need to be scheduled (separate ticket)?

**Comment by kayline** [comment]
SC and NOD need Contact Center review and Privacy Officer review. @comaurice and @eileen-coforma will work on this

**Comment by davidakennedy** [comment]
I tested our template with a screen reader, as well as looked at the source code. It should work well for people who use assistive technology. The only potential improvement I'd make is adding `role=”presentation”` to the tables. But that's an enhancement, and not a blocker. It would make the announcements in some screen readers less verbose, improving the screen reader experience.

**Comment by comaurice** [comment]
The email error notifications of the 3 forms and supporting documents are behind feature flag and ready for deployment. Will confirm with Amy that we can push the templates to Prod today 10/31. The 4142 template (not yet ready) would go-live separately next week.
