### ISSUE TITLE
Launch the Customer Insights Database

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#94658]
## Purpose
We need a page for folks to be directed to that explains the Customer Insights Database, leads them to it, and also may link to explanatory documentation.

Note:  FDG landing may provide a good example of how to approach this.

## Tasks
- [x] update existing insights with updated 'q2 format' and clean up any 1-off quotes
- [x] Find a way to filter old insights out (like create a column and tag, then add that filter to the "view")
- [x] create new page for platform teams (sectioned out with their own views) and how to tag
- [x] design lead review
- [x] update as needed

## Acceptance Criteria
- [x] Landing page is ready for Launch
