### ISSUE TITLE
Set up Confluence space for Q3 2024 Survey

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#94662]
## Purpose
Duplicate any Confluence views from q2
-We'll want it for complete results when the survey closes

Reference: [Old Metrics page](https://vfs.atlassian.net/wiki/spaces/AP/pages/2616164361/Metrics+for+the+Quarterly+Platform+Services+Satisfaction+Survey) | [Newer Metrics page](https://vfs.atlassian.net/wiki/spaces/AP/pages/3077111862/Platform+Satisfaction+Metrics)

## Tasks
- [x] Duplicate previous survey confluence space
- [x] Think about how to separate 'all quarters' from specific quarters
- [x] Update participant numbers/rates table
- [x] Modify space for new direction allowing for updated questions and format

## Acceptance Criteria
- [x] Q3 space is ready
