### ISSUE TITLE
Fix validation issues in PDF Generation

### ISSUE THREAD

**Issue by opticbob** [department-of-veterans-affairs/va.gov-team#94683]
## Background
When trying to go through the appoint workflow for #92238 there were validation errors in the PDF generation step.  Some of them require backend fixes.  Front end fixes can be found in #92779 .

## Tasks
- [x] Convert submitted 3 character country codes to 2 character codes
- [x] Fix claimant zip code suffix error for blank strings
- [ ] Take different paths through the workflow to see if any more validation errors can be triggered.

## Acceptance Criteria
- [ ] A request body created by the frontend in staging will not trigger validation errors in the local environment
- [ ] New fixes will have tests
