### ISSUE TITLE
[Design] Profile TMA: update user flows to include failure points

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#94691]
## Background
As a follow-up action item from the silent failures audit, we need to review and update our Profile user flows to identify potential points of failure/errors that the user may encounter and what the UX is in those situations.

## Tasks
- [ ] Review user flows (see resources section for links)
- [ ] Update flows to include points of failure

## Acceptance Criteria
- User flows are updated to include points of failure in the UX

## Resources
All Profile use cases + user flows:
- [x] [Personal information use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information/use-cases#readme) + [user flow](https://www.figma.com/file/qfyUmEOVawplgrEKYKFp0f/Profile---Personal-information?type=design&node-id=0%3A1&mode=design&t=3BjAesVLktQXS6X2-1)
  - [x] [Silent errors page in Figma](https://www.figma.com/design/qfyUmEOVawplgrEKYKFp0f/Profile---Personal-information?node-id=546-2171)
- [x] [Contact information use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/use-cases#readme) + [user flow](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/p/32C331B8-812D-46FE-AF7D-DCA63C881713/canvas)
  - [x] [Silent errors page in Figma](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=1180-993) 
- [x] [Military information use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information/use-cases#readme) + [user flow](https://www.figma.com/file/zb5ecY9yMnupiLjaH9UmSc/Profile---Military-Information?type=design&node-id=0%3A1&mode=design&t=ISGgZpVUB35oOzXb-1)
  - [x] [Silent errors page in Figma](https://www.figma.com/design/zb5ecY9yMnupiLjaH9UmSc/Profile---Military-Information?node-id=548-2140) 
- [x] [Direct deposit use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/use-cases#readme) + [user flow](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile-Direct-Deposit?type=design&node-id=0%3A306&mode=design&t=JeBw2hRh9J5QSuL7-1)
  - [x] [Silent errors page in Figma](https://www.figma.com/design/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?node-id=1620-2798) 
- [x] [Notification settings use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/notification-preferences/use-cases#readme) + [user flow](https://www.figma.com/file/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?type=design&node-id=1%3A12888&mode=design&t=beICgF9Ke3eKxb6t-1)
  - [x] [Silent errors page in Figma](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=1139-8068) 
- [x] [Account security use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/account-security/use-cases#readme) + [user flow](https://www.figma.com/file/05k2PTmuDVgBj2HnzUZayg/Profile---Account-Security?type=design&node-id=0%3A1&mode=design&t=iNSbLjANTt9uOIhh-1)
  - [x] [Silent errors page in Figma](https://www.figma.com/design/05k2PTmuDVgBj2HnzUZayg/Profile---Account-Security?node-id=484-2044) 
- [x] [Connected apps use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/connected-apps/use-cases#readme) + [user flow](https://www.figma.com/file/eMR2XSTGnWQgF2YEphWK8O/Profile---Connected-Apps?type=design&node-id=0%3A1&mode=design&t=52kJ3RZzhAkZMo0E-1)
  - [x] [Silent errors page in Figma](https://www.figma.com/design/eMR2XSTGnWQgF2YEphWK8O/Profile---Connected-Apps?node-id=286-1335) 
- [x] [Personal health contact use cases (fka Next of Kin / Emergency Contact use cases)](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-health-care-contacts/use-cases) + user flow (TK)
  - [x] [Silent errors page in Figma](https://www.figma.com/design/uYMdNtQnrzq7OiDl0rPF9k/Profile---Personal-health-care-contacts?node-id=2403-2177)

**Comment by ACParker89** [comment]
@twoangstroms - Progress update on this? should we roll it?

**Comment by twoangstroms** [comment]
@ACParker89 Sadly, yes. Mainly because I was out all last week. There's a chance I could power through it today but Profile files don't have the IA flows that My VA does so I'm having to do a bit of generating work.
