### ISSUE TITLE
Hurricane Helene and Hurricane Milton Banner

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#94712]
## Description

We need to create a banner for the current hurricane disasters.

Connect with CAIA to ensure the copy aligns with VA.gov standards and any other messages.

This banner should be displayed on:

1. The unauthenticated side (which will also involve working with CAIA)
2. The main summary page
3. The VBA & VHA summary pages

So no matter which way a Veteran logs in the banner will be displayed to them.

**Hurricane Disaster Help.**
VA is aware of the current disasters surrounding Hurricane Helene and Hurricane Milton. If you have been impacted by these hurricanes or any other disaster, VA wants to help.  

- **For help with VA benefit debt:** Contact our Debt Management Center by calling 800-827-0648 (or +1-612-713-6415 from overseas) to request temporary financial relief or via Ask VA (select "Veterans Affairs-Debt" as the category). We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET. If you have hearing loss, call TTY: 711.
- **For help with VA debt related to medical care and pharmacy services:** Call our Health Resource Center at 866-400-1213 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET.

## Tasks
- [x] Have CAIA approve or update the proposed text.
department-of-veterans-affairs/va.gov-team/issues#94873 
- [x] Create the banner.
- [x] Connect with CAIA to set up the unauthenticated banner.
- [x] Front end to implement on the summary pages. (Main Summary, VBA Summary and VHA Summary)

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [x] The banner displays as intended

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
After a team discussion we are replacing the current expandable generic disaster alert with this hurricane alert. 
Informational (blue) alert set to switch back to the generic expandable one on December 09 until we're directed otherwise. 

Example screenshot for approval:
<img width="710" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenMzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a2188aa60f8e0b47cc21ab453f97773c5d249a4/image.png" alt="image.png" />

**Comment by dhill802** [comment]
Priority - pulled into Sprint 136 after sprint commitment made.

**Comment by mgleo** [comment]
CAIA intake ticket created [#94873](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94873)

**Comment by dhill802** [comment]
Waiting on CAIA response. Megan reached out via their Slack channel to see if we could get someone to review today. (expandable info alert added to a Drupal page)

**Comment by Dr-Pongo** [comment]
Copy has been updated! Screenshots here and in the PR: 

<img width="617" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGhWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d579dd3ae63fb4b55c8bf673f0671b43dcfa3bcf/image.png" alt="image.png" />

- department-of-veterans-affairs/vets-website/pull/32344

**Comment by Dr-Pongo** [comment]
Banner is live in the CDP app, and on relevant unauth page(s). The alert is set to expire on `debt-balances` and `copay-balances` on 12/09/2024, so we've made a follow on ticket to address the CMS stuff, and/or update the alert in the app.
- **[CDP] Temporary hurricane banner update (complete prior to 12/09/2024) [#95923](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/95923)**

FYSA @denisecoveyduc
