### ISSUE TITLE
Alert Update for when the DMC endpoint times out

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#94725]
## Description

As reaching out thru AskVA can theoretically take up to 5 days sometimes, we need to make an update to the alert messages noted here.

**Updated text:**
If you need immediate assistance with overpayment debt, call the Debt Management Center at 800-827-0648 (TTY: 711). For international callers, use 612-713-6415. We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET.

**Alerts to update - 5 alerts on 3 pages:**

- Debt and bill overview page (2 errors): _manage-va-debt/summary_
  - Both copay and overpayments are not available
  - Overpayments are not available
- Overpayment summary page (2 errors): _manage-va-debt/summary/debt-balances_
  - Overpayments not available
  - Overpayments not available, our records show you have copay bills
- Copay summary page: - _manage-va-debt/summary/copay-balances_
  - Overpayments not available

## Tasks
- [ ] Update all 5 alerts.

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] The alerts display as intended

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by mgleo** [comment]
**Debt and bill overview page (2 errors):** `manage-va-debt/summary`
- Both copay and overpayments are not available
<img width="782" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEUzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46d81333f397e744e19426bbd0bc662a73037a87/Screenshot%202024-10-09%20at%204.35.47%E2%80%AFPM.png" alt="Screenshot 2024-10-09 at 4.35.47 PM.png" />

- Overpayments are not available
<img width="731" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE0zQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f6b68f750e0bb78cfe51da1a3d42f7e43022043/Screenshot%202024-10-09%20at%204.36.32%E2%80%AFPM.png" alt="Screenshot 2024-10-09 at 4.36.32 PM.png" />


**Overpayment summary page (2 errors):** `manage-va-debt/summary/debt-balances`
- Overpayments not available
<img width="706" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDQzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0e8bb59843e8db46e455aab2d85337d663b52bd/Screenshot%202024-10-09%20at%204.40.50%E2%80%AFPM.png" alt="Screenshot 2024-10-09 at 4.40.50 PM.png" />


- Overpayments not available, our records show you have copay bills
<img width="792" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUUzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1bef676749c21d19156122cfcba63763674606ec/Screenshot%202024-10-09%20at%204.43.31%E2%80%AFPM.png" alt="Screenshot 2024-10-09 at 4.43.31 PM.png" />


**Copay summary page:** - `manage-va-debt/summary/copay-balances`
- Overpayments not available
<img width="457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEEzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15d8e8115e81e82daf40f2c3514e48f72b3895e8/Screenshot%202024-10-09%20at%204.34.50%E2%80%AFPM.png" alt="Screenshot 2024-10-09 at 4.34.50 PM.png" />

**Comment by Dr-Pongo** [comment]
Including content change for copay errors as well since they don't match designs. Shouldn't add too much overhead to the ticket

**Comment by Dr-Pongo** [comment]
Included some language changes to some vha as well to align existing messaging
