### ISSUE TITLE
Create new GitHub team for CODEOWNERS purposes

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#94721]
## User Story
As the managers and engineers for the VA Platform, 
We need to satisfy the support request and create a new GitHub team for CODEOWNER purposes, 
So that all relevant information is accurately reflected in Atlas tool. 

## Issue Description
A support request was received by the Platform Product team where a developer wanted a new Github team created for CODEOWNERS purposes. The Atlas database will need to be updated to reflect the new team and its associated records. After this request has been completed, a process for these types of requests can be documented and shared to ensure that all relevant information is accurately reflected in Atlas. 

It was initially assumed that a GitHub team would only need to be created during onboarding (which may be the case here), but we should ensure that we account for all scenarios where this might occur and make sure the records are properly reflected in Atlas.

## Tasks
- [ ] Create new GitHub team for CODEOWNERS purposes
- [ ] Document process for creating new GitHub team
- [ ] Share process with all teams to ensure all relative information is accurate in Atlas. 

## Success Metrics
There will be a satisfied requestee and a new process for standardization of how these requests come in and how they are completed. 

## Acceptance Criteria
- [ ] There will be a new GitHub team for CODEOWNERS purposes
- [ ] There will be a process created and shared for how to request new GitHub teams. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
