### ISSUE TITLE
[Design, FE, QA] 10-10CG - Improvement: Add "Country" field to address pages

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#94730]
## Benefit to the Veteran
As a Veteran/Caregiver, I want to make sure my residential country United States is being captured, so that I can feel more confident in providing input in the County field.

## Scope
In an additional attempt to reduce the number of applications having a form of US, USA, United States, or other varieties of the country name in the County field, we will add the Country field with a default and only value of United States (no other options will be available or allowed).

## Tasks
- [ ] [Design] Update 10-10CG design to include the Country field on all address pages (Veteran, Primary, Secondary, Additional Secondary)
- [ ] [FE] Update 10-10CG UI to include the Country field on all address pages (Veteran, Primary, Secondary, Additional Secondary)
- [ ] [QA] Validate that the Country field appears on all address pages, that United States is the default value, and no other values can be selected or added in this field.
     - [ ] QA/PM signoff is required in the comments prior to launch
- [ ] [FE] Launch to production

## Acceptance Criteria
- The Country field is added to all address pages to deter applicants from adding Country names in the County field
