### ISSUE TITLE
DR | Reduce blank PDF errors (WIP)

### ISSUE THREAD

**Issue by kayline** [department-of-veterans-affairs/va.gov-team#94736]
## Value Statement

**_As a_** veteran submitting evidence

**_I want to_** see an warning when I try to submit very small PDF files (<20kb)

**_So that_** I can open the files and make sure they are not blank before I submit them

---

## Background Context

- We've been seeing a fair number of PDFs fail to submit because they are blank. It seems to happen in various ways, but often a blank PDF is less than 20KB, which would be almost impossible for a PDF with any content. `vets-api` is already checking size to make sure no file is too big. We could add another check and warn if a file is very small. It seems likely that veterans are printing/saving/converting PDFs without opening them to check it was successful, so prompting them to check may catch things sooner.
- Current remediation is the veteran will get a physical letter a few weeks after trying to upload, informing them the file failed to process. We're moving to email soon, but that still asks them to mail in a copy of the evidence. I'm not sure at this time if the letter and/or email include information about what the problem was (i.e. the file was blank).

## Outcome, Success Measure, KPI(S), and Tracking Link

- Measurable reduction in number of "Blank PDF" evidence submission failures

## Acceptance Criteria

- [ ] Veteran will see warning if submitting a very small file
- [ ] Veteran can override warning and submit anyway

## Designs and Build Notes

- Add here

### Enablement team (if needed)
@ member of team

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [ ] Build vets-api size check
- [ ] Implement vets-website warning

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
I did a spike a while back. There were some issues with the file input web component not showing the correct errors when setting the document type - I'd have to test it again to see if that issue has been fixed. Spike should be quick; updating may take a couple of days if it's working as expected
