### ISSUE TITLE
Remove the Pension Debt banner

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#94761]
## Description

Locate and if still on the site - remove the Remove the Pension Debt banner from the portal.

## Tasks
- [ ] Remove the banner

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] The banner no longer displays

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
Completed a cursory search for "Pension Debt", and what I found didn't seem like it should be removed, so waiting for @Tom-Davis to come back into town for clarification!

**Comment by OptionSelect** [comment]
Per my search as well and convo with Denise, we believe this one has been completed in the past as we do not see a banner to remove.
