### ISSUE TITLE
Health Resource Center telephone number

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#94773]
## Issue Description
There's a list of common phone numbers in [component-library](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/contacts.ts) which makes it easier and more consistent to maintain. Currently the DMC number is in there, but it would be beneficial to include the number we regularly use for help with copays at the Health Resources Center `866-400-1238` since we use it in so many places, and we've had issues of a mistype in the past. 

#### Component Library contacts definition:
- [contacts.ts](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/contacts.ts)

## Tasks
- [x] Update component-libary contacts to include Health Resources Center number
  - This may involve coordinating with platform for approval
- [ ] FSR tasks
  - [ ] Update `va-telephone` instances in FSR to use new CONTACT import for Health Resources Center
  - [x] Double check we're using CONTACTS.DMC imports wherever we have that number listed (`8008270648`)
  - [x] Double check we're using CONTACTS.DMC_OVERSEAS imports wherever we have that number listed (`6127136415`)
  - [x] Update any relevant tests for FSR
- [ ] CDP tasks
  - [ ] Update `va-telephone` instances in CDP to use new CONTACT import for Health Resources Center
  - [x] Double check we're using CONTACTS.DMC imports wherever we have that number listed (`8008270648`)
  - [x] Double check we're using CONTACTS.DMC_OVERSEAS imports wherever we have that number listed (`6127136415`)
  - [x] Update any relevant tests for CDP
  
**Note:** Removing this task, I've added a couple of suspect numbers to look into, everything else is happy
- [ ] ~~If all items are covered validate that [ticket 94773](https://github.com/orgs/department-of-veterans-affairs/projects/1514/views/10?pane=issue&itemId=88349189&issue=department-of-veterans-affairs%7Cva.gov-team%7C85566) is/is not still needed~~

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] component-library is updated with Health Resource Center number 
- [ ] FSR is using CONTACTS import for all instances of Health Resource Center number, DMC, and DMC OVERSEAS numbers
- [ ] CDP is using CONTACTS import for all instances of Health Resource Center number, DMC, and DMC OVERSEAS numbers
- [x] All existing tests passing

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points

**Comment by Dr-Pongo** [comment]
component-library changes merged! Need to update locally and get a PR up for vets-website stuffs too

**Comment by Dr-Pongo** [comment]
Closing out with work completed as we need to wait for component library release. 

- Follow on ticket for health resource center number update once component library releases
department-of-veterans-affairs/va.gov-team/issues/101205
