### ISSUE TITLE
Create new non-lb QA standard for logging silent failures

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#94791]
## User Story
As a Platform Team member supporting the OCTO effort for zero silent failures for VA.gov, I want to introduce a new QA Standard for VFS teams to log/capture silent failures so that OCTO can keep track of this metric moving forward.

Assignee: @it-harrison 
Peer Reviewer: @erinrwhite 

## Description
In order to help OCTO capture data relating to silent failures, specifically around capturing a silent failure and capturing the prevention of a silent failure, Governance has been asked to introduce a new QA standard requiring VFS teams to log silent failures data. The new standard will have ID QA7 and reference the [Logging silent failures gh guidance. ](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md)

In order to validate this logging of silent failures at a VFS team Staging Review, Governance will ask VFS teams to specify within their Collab Cycle Request ticket to "point to the lines of code in GitHub that show this logging is occurring" per Governance PO @humancompanion-usds .

**Standard area:** Logging silent failures
**ID:** QA7
**Standard description:** The product code must log all silent failures to statsd
**Severity:** Warning, not launch-blocking

### Live pages
- [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards)
- [How to complete a QA review for the Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+the+Staging+review+touchpoint)
- [QA Standards Collab Cycle Findings for Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+QA%2C+Staging%2C+qa-standards&projects=&template=collab-cycle-qa-findings-staging.md&title=QA+Standards+-+VFS+Team+-+VFS+Product) - gh template
- [Change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history)

### Drafted pages
- 

## Tasks
- [x] Create a draft of the QA Standards page on Platform Website
- [x] In the draft, add QA7 per the description above. 
- [x] In the draft, add a new section under "How Standards are validated" for Logging Silent. Provide specific details as to how the standard is validated, including a link to the logging silent failures gh guidance.
- [x] For the How to complete a QA review for SR touchpoint doc, add a new section for Logging Silent Failures, including information wrt how Governance will validate (no need to create a draft - just edit the live doc)
- [x] For the gh template, create a PR with proposed changes to the template, including a new section for Logging Silent Failures
- [x] Draft a new post for the Collab Cycle Change history log.
- [x] Create a Slack post for #vfs-change-announcements channel following [change announcement guidance.](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2290352129/Slack+Change+Announcement+format) No need to create a new draft page... Slack announcement draft can be shared in this ticket via GH comment. 
- [x] When all changes are drafted, shared with @humancompanion-usds for his review and approval.
- [x] If required, make changes requested by Matt.
- [x] Once Matt has signed off on changes, publish all pages to Platform Website. Once all pages are live, announce changes via #vfs-change-announcements channel on OCTO Slack.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have added a new QA standard for logging silent failures 
- [x] We have an operational process for validating that this standard is met at Staging Reviews
- [x] We have modified our template for reporting to the VFS team at SR whether the Logging Silent Failures QA standard was met or not met.
- [x] We have announced our changes to VFS teams

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison @erinrwhite This is a new, urgent ticket that Matt asked us to pick up ASAP. I will get it fully refined by EOD, and Ian can begin working on it right away. Erin, you will need to announce this change in ToT on Tuesday. I will be sure to add it to the slide. Feel free to reach out to me today if you have any questions, or @humancompanion-usds on Monday if you aren't able to get to it until then.

**Comment by it-harrison** [comment]
@humancompanion-usds the artifacts are ready for you to review

**Comment by shiragoodman** [comment]
@erinrwhite @it-harrison have you verified the published pages? When you do, this ticket can be closed. Thank you!

**Comment by erinrwhite** [comment]
Published pages and slack post looking good here! Good to close.
