### ISSUE TITLE
UX | Update "Now" prototype to reflect input from October 9 PO-UX Sync

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#94793]
## Description
Based on review of October Prototype on October 9th, make the following adjustments per input from the PO.

## Tasks 
- [x] Remove "signed in only" option from the prototype as it will not be an option to have a non-signed in experience
- [x] Improve the adjustability or process of re-ordering added steps within the layout tab
- [x] Show multi-pattern (multi-response) step information in the layout tab

## Acceptance Criteria
- [x] Changes listed above are made in Figma (link: [Figma file](https://www.figma.com/design/qsCcFgAYwLDUgU6jRmZerc/Form-Engine---POC---VA-Form-21-4140?node-id=2672-18496&t=aG6CGB6TK6czlNht-1)) 
- [x] Updates are shared back to PO (link: [view notes here](https://dsva.slack.com/archives/C071YDEEJ58/p1729108290656759?thread_ts=1729096104.892669&cid=C071YDEEJ58))
- [x] Team has been briefed on update (16th minute sync - Fallout Friday) (link: recording)

**Comment by brian-wilke** [comment]
Updated figma file shared to Matt (PO) after reviewing with Jeana (SME) as part of our weekly syncs. 
Resulting in a new ticket and test items for next week (new ticket created).

**Comment by brian-wilke** [comment]
Shared out week's updates in the 16th minute on October 18.
