### ISSUE TITLE
Add address line 3 in 20-0996 SIP call

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#9479]
## Issue Description
Backend's "Save in progress" SIP response to `/v0/in_progress_forms/20-0996` should include address line 3

---
## Tasks
- [ ] Include address line 3in SIP response for form 20-0996

## Acceptance Criteria
- [ ] BE supplies everything FE needs to complete design implementation of form 20-0996
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SarahJaine** [comment]
this one is a little more confusing that I expected https://github.com/department-of-veterans-affairs/vets-api/compare/sj-add-address3-form0996

**Comment by SarahJaine** [comment]
Decided to close without fixing
