### ISSUE TITLE
Content updates for check-in page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#94790]
> [!WARNING]
> Do not use this ticket unless directed to do so by the CAIA team.

## Issue description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
_What work is necessary for this ticket to be completed? Examples:_
- [ ] Assess request
- [ ] Draft content
- [ ] Review 
- [ ] Share with requesting team
- [ ] Update page
- [ ] Copyedit
- [ ] Publish
- [ ] Alert requesting team

## Acceptance Criteria
_What will be created or happen as a result of this story? Examples:_
- [ ] Updated content is live on the site
- [ ] Product has launched
- [ ] Feedback has been shared with requesting team

## Configure this issue
- [ ] _Attach to an Epic (what body of work is this a part of?)_
- [ ] _Label with Originator/Team (product team or stakeholder requesting support)_
- [ ] _Label with Open Date_
- [ ] _Label with Estimate (level of effort expected for this ticket)_
- [ ] _Add assignee name to each task they will complete (if known)_

**Comment by mistymg** [comment]
Closing this sub-issue as nothing happened here.
