### ISSUE TITLE
Update the New Flipper UI's uncommon features Actors, %'s, etc)

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#94800]
Upon smoke testing the new release of the Flipper UI, it quickly became apparent that the less common features (using actors, groups, %'s) needed some love

## Tasks
- [x] Fix UI bug related to loading actor-related features
- [x] Add comparable UI notes related to actors/groups that were lost in the transition to standard views (in the layout)
- [x] Updating RouteAuthorization and respective tests for actors/groups/%s as these were not covered before (and could be accessed by bad actors)

## Acceptance Criteria
- [x] New Flipper UI is tested and deployed to Prod.
