### ISSUE TITLE
UX | Surface patterns to user for selection within building a step

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#94801]
## Description
Refine the user flow to incorporate the pattern selection (based on the pattern matrix). These wireframes and screens should show the patterns available to the user of the tool, so that they can add in a pattern to a new step that they created as part of the form conversion. These wireframes/screens will be reviewed by the SME and PO prior to sharing to the team for alignment.  These will be in the Hi-Fidelity section of our figma file. We may explore listing all available patterns versus suggesting the "correct" or "assumed" pattern, or hiding already implemented patterns. 
We may also show access to more information about proper pattern use (as per the design system). We may also share what parts of this pattern can be modified prior to inclusion in the conversion. 

For a future state, we may also allow building blocks of patterns to provide custom functionality.

## Tasks

- [x]  Wireframe and mockup the current available patterns as defined in the Pattern Matrix
- [x]  Provide more than one option for review by the SME and PO 
- [x]  Incorporate feedback from PO and SME in preparation to share to larger team
- [x]  Share to team in 16th minute, or as needed in a larger meeting

## Acceptance Criteria

- [x]  Option 1, Option 1b Wireframes and screens of selection options (link: [option 1,1b located here](https://www.figma.com/design/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?node-id=4325-140139))
- [x]  Option 2 (link: [Figma file](https://www.figma.com/design/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?node-id=4357-66350&t=Kj0JpiqksnPe0ywL-1))
- [x]  Team has reviewed and discussed option 1
- [x]  Team has reviewed and discussed option 2

**Comment by brian-wilke** [comment]
Updated shared [deck](https://docs.google.com/presentation/d/1duYcVcicRCF3mjjSP_fyehRlWEZURnxsxxy96j8k6ko/edit?usp=sharing) to reflect both the single (one add at-a-time) as well as showing previously added steps inputs from the teams. 

Updated the WIP Nov prototype to reflect this level of feature for clarity

**Comment by gopixelsgo** [comment]
Added the link to Option 2. We received initial SME feedback on this today, but will still need to make updates and share with our team to meet acceptance criteria. This will continue into next sprint.
