### ISSUE TITLE
UX | Visual design for Employment History List and Loop UI in Form Builder

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#94803]
## Description
This ticket is to be used by the designers working on the Form Builder Editorial UI. Design the necessary screens required to enable use of the "Your employers" (Employment History List and Loop) Step and pattern so that it can be selected to be included in a form conversion. 

## Tasks 
- [x] Wireframe out[ initial screens](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1731966039437/21ce5c5627e3277baad965c530e7e2a2b7238c1a) and [options](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1733403710215/64b3fc4a5bd139f4a790b60967bf1f01ce798fe0)
- [x] Share either wireframes or prototypes as necessary to get necessary feedback and input from team/stakeholders
- [x] Align with team's feasibility 
- [x] Adjust Form Builder screens

## Acceptance Criteria
- [x] Feedback collected 
- [x] Feedback implemented in [Form Builder screens](https://www.figma.com/design/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?node-id=4619-59446&t=sVaSxepfYMt2LQAJ-1) and prepped for shareout at Fallout Friday

**Comment by Karak888** [comment]
start with Jeana to review and understand difficulties, etc.

**Comment by Karak888** [comment]
@brian-wilke I am confused on this one, and hoping you can shed some light?  If Derek is moving forward next sprint (13) with rendering and normalizing list and loops for Employment History, wouldn't this have to have already occurred, or is this something that we will do as enhancements as we move iteratively?  And / or, is it that Jeana still needs to review, etc. ?  Thank you!

**Comment by brian-wilke** [comment]
@Karak888, Yes... short answer, Enhancements. 

Long answer:
In a perfect world, we would have already sketched, then wireframed options, converted to a prototype and tested with at our SMEs and PO before beginning any costly code.  

However, we are running parallel tracks on this project and this maybe one that is more heavily influenced in the short term by what is technically possible first, before we refine the experience. I think the forward progress being made by the engineering team is consistent with how the rest of this project has existed and will continue to be. We have adopted the posture of refining what exists instead of making design decisions first.

**Comment by brian-wilke** [comment]
@gopixelsgo is the lead on this ticket.

**Comment by gopixelsgo** [comment]
Noting that some of the original tasks outgrew this ticket and have been broken out into [this ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1253/views/21?pane=issue&itemId=90440562&issue=department-of-veterans-affairs%7Cva.gov-team%7C98810) and [this ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1253/views/21?pane=issue&itemId=90416083&issue=department-of-veterans-affairs%7Cva.gov-team%7C98748).
