### ISSUE TITLE
Build and publish Spanish disaster help page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#94813]
> [!WARNING]
> Do not use this ticket unless directed to do so by the CAIA team.

## Issue description

We recently published a [disaster help](https://www.va.gov/resources/disaster-help/) page in English. A VEO translation team translated the content into Spanish. We need to build the page in Drupal and publish. PW will then add a toggle to it. 
---
## Tasks
_What work is necessary for this ticket to be completed? Examples:_
- [ ] Assess request
- [ ] Draft content
- [ ] Review 
- [ ] Share with requesting team
- [ ] Update page
- [ ] Copyedit
- [ ] Publish
- [ ] Alert requesting team

## Acceptance Criteria
_What will be created or happen as a result of this story? Examples:_
- [ ] Updated content is live on the site
- [ ] Product has launched
- [ ] Feedback has been shared with requesting team

## Configure this issue
- [ ] _Attach to an Epic or Intake if this is related to other work_
- [ ] _Label with Originator/Team (product team or stakeholder requesting support)_
- [ ] _Label with Open Date_
- [ ] _Label with Estimate (level of effort expected for this ticket)_
- [ ] _Add assignee name to each task they will complete (if known)_
- [ ] _Update the status to reflect where this work is in the pipeline (in progress, backlog, etc.)_

**Comment by RLHecht** [comment]
Uploading the translated word doc here: 

[SPFFIN Disaster help.docx](https://github.com/user-attachments/files/17333509/SPFFIN.Disaster.help.docx)

**Comment by moviedosoco** [comment]
@RLHecht The **_Asistencia frente a una catástrofe_** page is built in Drupal.

Drupal preview: http://preview-prod.vfs.va.gov/preview?nodeId=73621)

**Comment by RLHecht** [comment]
Thank you for doing this so quickly! Noting here that we published the page 10/10. There's an accordion of text in the housing section that wasn't translated, so the VEO translation team will give to us today to add to the page. Victoria also needed to translate the NCA content and related links. We've sent the page to the translation team to QA. PW is adding the toggle today as well. 

Let's leave this ticket open until we get the housing accordion put onto the page.

**Comment by moviedosoco** [comment]
The housing accordion was added to Drupal. This page is now ready to be reviewed and publish.

Drupal preview: https://preview-prod.vfs.va.gov/preview?nodeId=73621

**Comment by moviedosoco** [comment]
@RLHecht and @strelichl Since this page is published (https://www.va.gov/resources/disaster-help-esp/), I'm going to move this to Validate.
