### ISSUE TITLE
Review and complete zero silent failures checklist

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#94814]
Review the [zero silent failures checklist](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md#checklist) and complete any tasks that are called out. 

Acceptance criteria
- Complete any tasks called out in the doc above
- Capture any recommendations for monitoring beyond what we have in place
- Update any relevant documentation within the team (readme, playbook, on call rotation, etc.)

More overall context in the [zero-silent-failures readme](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/README.md).

**Comment by michaelclement** [comment]
Engineering will plan to take a crack at this collaboratively and share out anything that we find.

**Comment by michaelclement** [comment]
# 94814 - Zero Silent Failures Checklist - Notes
*24 October, 2024*
## Summary
Our checklist is almost complete, there are just a couple boxes we need to follow up on, specifically regarding diagrams of our data flow and the written confirmation from Pega that they handle erorrs appropriately.

## Action items:
- Don will make a mermaid chart showing how data flows through our system
- Don to follow up about credentials for "Missing Pega Status" endpoint
- Steve to create error docs per this prompt: 
  - *"then create documentation that captures how errors in each system are handled. Detail which systems retry a submission and what happens when those retries exhaust. Show this in your diagram."*
- Michael to follow up with Bo and Premal about getting something from Pega in writing

**Comment by michaelclement** [comment]
### Checklist

#### Start

* [X] Do you know when your application shipped to production?
  - 22 October, 2024
* [X] Did your application use the same APIs when it shipped as it does today?

#### Monitoring

* [X] Do you monitor the API that you submit to via Datadog? 
* [X] Does your Datadog monitoring use the appropriate tagging?
* [X] Do errors detected by Datadog go into a Slack notifications channel?
* [X] Does more than one person look at the Slack notifications channel containing errors on a daily basis? 
* [X] Do the team members monitoring the Slack channel have a system for acknowledging and responding to the errors that appear there? 

⚠️ **Failure to have endpoint monitoring in place is a blocking QA standard at Staging review as of 9/10/24.** If you answered no to any of the questions above, you will be blocked from shipping at the Staging review touchpoint in Collab Cycle.

#### Reporting errors

* [X] Have you filed issues for errors that are appearing in Datadog / Slack?
* [X] Do all fatal errors thrown in your application end up visible to the end user either in the user interface or via email?

#### Documentation

* [ ] Do you have a diagram of the submission path that user data your application accepts takes to reach a system of record? 
  * If not, then [create a user data flow diagram](#how-to-create-a-user-data-flow-diagram) that captures this information. 
* [ ] Do you understand how the error is handled when each system in the submission path fails, is down for maintenance, or is completely down?
* [ ] Has the owner of the system of record receiving the user's data indicated in writing that their system notifies or resolves 100% of fatal errors once in their custody?
  * If not, work with OCTO to meet with the owner of the system and get their agreement in writing.
  * Please document the outcome of this conversation in your product's documentation in Github.

#### User experience

* [X] Do you capture all of the potential points of failure and make those errors known to the user via email notification and/or through the application on VA.gov or the mobile application?

**Comment by michaelclement** [comment]
**Re the followup with Bo and Premal**
Talked with Bo about it a bit in these slack threads:
- [This DSVA thread](https://dsva.slack.com/archives/C068Y3ZFKNJ/p1729703838201969)
- [This internal slack thread](https://adhoc.slack.com/archives/C06MJ1F17FU/p1729802136986029)

Seems like currently we're in somewhat of a holding pattern on this point (getting something in writing from Pega) until we have more direction surrounding what we _have_ to get. @baltes Is there anything I'm missing on this front? We may want to loop in Premal sooner rather than later.

**Comment by pshahVA** [comment]
Just an FYI, that I already did this as there was a rush to get it done in time for our review. Its [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/champva/team/ivc-silent-failures-checklist.md). Let's just keep this one updated.

**Comment by michaelclement** [comment]
Got it, thank you Premal! We'll make updates to that file as needed.
