### ISSUE TITLE
GitHub Issues - Content Team Migration

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#94825]
## Pain Point
We will soon be migrating our ZenHub board to GitHub Issues and tracking our work there, but no one on the team really understands how this will happen, nor is familiar with the new system.

## Issue Description
Content Team needs to educate ourselves about GitHub Projects by taking advantage of all video learning, internal discussions, and documentation.

---
## Tasks
- [ ] Team members have watched [Product Team demo video from 10/9/24](https://drive.google.com/file/d/1hI7qDXBiWVGb1gzLsUanS5pLAyDFAoxe/view)
___ JK; ___ BS; ___ JT; ___ CM

- [ ] Team members have read [About Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects) on the GitHub website
___ JK; ___ BS; ___ JT; ___ CM

## Acceptance Criteria
- [ ] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/94825?planning-poker) with Zenhub @BSmolensky @cmarion93 @taylojill

**Comment by jknipes** [comment]
Moved to `In Progress` pipeline due to timely nature of the issue - we are migrating our board to Projects on Monday 10/21/24

**Comment by jknipes** [comment]
all work complete, moving to _Closed_
