### ISSUE TITLE
Write guidance for Support Tier 1

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#94823]
## Pain Point
Support Team documentation for handling content edit requests from VFS teams is incomplete and could cause confusion for Tier 1 support.

## Issue Description

- Per the tasks on [Support ticket 81435](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/81435), we should help write better guidance in Confluence for this process.
---
## Tasks
- [x] Joe create process for Tier 1 Support to handle inquiries from VFS team members about creating or updating content on Platform Website

## Acceptance Criteria
- [x] Confluence document is updated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
[Document update](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1#Platform-Content-Team-Submissions)

**Comment by jknipes** [comment]
Pulled into current sprint due to available capacity, prioritized as Support to Other Teams (see Epic).
Work is complete, closing as _Done_.
