### ISSUE TITLE
[ERROR STATE] ZSF - Sharepoint Submission Failed 503

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#94838]
## Description

We did a query for all submissions in state: error(DB column called 'state'). We then pulled these results into a spreadsheet and grouped by error message. We need to get better error messages to clue us into what our issues are, maybe add the stacktrace. This ticket addresses submissions that have gone into an error state that state Sharepoint Submission Failed particularly, the 503 message. 

This error seems quite rare, might be a one-off, adding this ticket just so we document it. We should look into Sidekiq retries for this one.

`SharePoint Submission Failed: BackendServiceException: {:status=>503, :detail=>nil, :code=>"VA900", :source=>nil}.`

<img width="1522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelU5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c12146279877d2ccba6c635126c62008b75265f1/image.png" alt="image.png" />

## Tasks
- [ ] NEED

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] Decide if it is a retry item
- [ ] If it is setup a retry and notification

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by digitaldrk** [comment]
There are only 2 results of this error in the DB.

The first happened: Fri, 16 Aug 2024 14:38:26.458695000 UTC +00:00
The last happened: Thu, 19 Sep 2024 14:21:19.258367000 UTC +00:00

This happened on the SharepointSubmission job.

https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/debts_api/app/sidekiq/debts_api/v0/form5655/vha/sharepoint_submission_job.rb

We have retries for this job (4). I will submit a PR to spread out the retries
