### ISSUE TITLE
[ERROR STATE] ZSF - Sharepoint Submission Failed to Open TCP connection

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#94840]
## Description

We did a query for all submissions in state: error(DB column called 'state'). We then pulled these results into a spreadsheet and grouped by error message. We need to get better error messages to clue us into what our issues are, maybe add the stacktrace. This ticket addresses submissions that have gone into an error state that state Sharepoint Submission Failed.

This error seems quite rare, might be a one-off, adding this ticket just so we document it. We should look into Sidekiq retries for this one.

<img width="1522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelU5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c12146279877d2ccba6c635126c62008b75265f1/image.png" alt="image.png" />

## Tasks
- [ ] Come up with a plan to fix the issue, retry the request with the relevant service(s). Basically get the error occurrence down.
- [ ] This ticket may have already been handled working on other tickets. Look for retry logic added between when you look at this ticket and when this ticket was created

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] A best effort is made to mitigate this error

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
Per Refinement, this is no longer needed - all ZSF work has been completed.
