### ISSUE TITLE
[ERROR STATE] ZSF - The Server Responded with Status 500

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#94842]
## Description

We did a query for all submissions in state: error(DB column called 'state'). We then pulled these results into a spreadsheet and grouped by error message. We need to get better error messages to clue us into what our issues are, maybe add the stacktrace. This ticket addresses submissions that have gone into an error state that state "The Server Responded with Status 500".

I do not know where this error is coming from. Once we know where the error is happening, we can look into preventing it.

<img width="1522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelU5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c12146279877d2ccba6c635126c62008b75265f1/image.png" alt="image.png" />

## Tasks
- [ ] Find out where the 500 error is coming from, what system is setting the error message in the FSR `error_message` column of the 5655_submission table
- [x] Add better messaging that includes the source of the error
- [ ] Come up with a plan to fix the issue, retry the request with the relevant service(s), or if possible talk to the team that administers that system to find out if there is an issue there

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] Document source of the issue
- [x] PR that adds better error messaging
- [ ] Plan to get error occurrence down (if possible)

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by digitaldrk** [comment]
The last occurrence of this issue was Mon, 30 Sep 2024 21:56:01.079009000 UTC +00:00.

[We have since pushed a PR that adds better logging](https://github.com/department-of-veterans-affairs/vets-api/pull/18974)

We cannot surmise the source of the issue but I am confident that we will know going forward if it happens again.
