### ISSUE TITLE
[ERROR STATE] ZSF - The Server Responded with Status 400

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#94841]
## Description

We did a query for all submissions in state: error(DB column called 'state'). We then pulled these results into a spreadsheet and grouped by error message. We need to get better error messages to clue us into what our issues are, maybe add the stacktrace. This ticket addresses submissions that have gone into an error state that state "The Server Responded with Status 400".

I do not know where this error is coming from. Once we know where the error is happening, we can look into preventing it.

<img width="1522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelU5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c12146279877d2ccba6c635126c62008b75265f1/image.png" alt="image.png" />

## Tasks
- [ ] Better error messaging that includes the source/service that caused the error
- [ ] Mitigation plan for reducing occurrence of error

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] PR for better error messaging stored in the `error_message` column in the 5655_submissions` table
- [ ] Plan for mitigating occurrences if possible. Could be retries, could be looking into why we got a 400 and making change to the payload/PDF.

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by digitaldrk** [comment]
The last occurrence of this issue was Thu, 08 Aug 2024 15:20:05.728501000 UTC +00:00

[We have since pushed a change that will l log the source of the issue](https://github.com/department-of-veterans-affairs/vets-api/pull/18974)

We cannot surmise the source of the issue but I am confident that we will know going forward if it happens again.
