### ISSUE TITLE
[Medallia Digital Surveys] Change Feedback button to target sitewide VFS survey on AVS pages

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#94851]
## Issue Description
An issue was identified with the Medallia customized AVS survey. Until the issue is resolved, we need to change the survey that is triggered by the button.

---
## Tasks
- [ ] Change feedback button AVS pages to point to VFS sitewide survey

## Acceptance Criteria
- [ ] Feedback on AVS URLs triggers VFS sitewide survey
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by manalo-soco** [comment]
@aubreyarcangel Is there a URL?
