### ISSUE TITLE
526 Flow Initial Page Focus Audit Followups

### ISSUE THREAD

**Issue by bacitracin** [department-of-veterans-affairs/va.gov-team#94868]
## Issue Description
After the 526 flow was reviewed to check that the initial page focus was consistent it was found there were a couple of areas that could be improved or investigated. 

---
## Tasks
- [ ] See if we can change the focus on the /start page from the body to the H1. We may not have control over this.
- [ ] Look into what’s so special about the Review & Submit page, and why all screenreaders correctly land on the H2 Progress Stepper when on all other pages they had issues (VO + Safari desktop & iOS, TalkBack + Chrome)
- [ ] Investigate the keyboard focus & screenreader virtual cursor focus mismatch (VO + Safari desktop & iOS, TalkBack + Chrome)

## Acceptance Criteria
- [ ] above tasks completed & documented
---
## Resources
- [ ] Summary of findings from the focus audit
- [ ] [Focus audit](https://docs.google.com/spreadsheets/d/1uazSB3Jt25fqHyTcxiC2A33guVOn_ZPxQ2YHeyOA_Ss/edit?usp=sharing)in Google Docs
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
