### ISSUE TITLE
On-site Search Type Ahead POC/prototype

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9486]
## Issue Description
We would like to build a proof of concept that incorporates the search.gov's "type ahead" capability into our va.gov site search (desktop and mobile) so that we can begin to review what this experience could like from a UX and accessibility perspective

---
## Tasks
Depending on when we can get to this work, this may happen asynch (Nick) then showing the POC to Design (Liz) or done together in a meeting
- [x] POC incorporating type ahead with va.gov on-site search
- [x] Desktop and mobile POC to review
- [x] Meeting/demo: reviewed with Design, and something we can share with Accessibility (demo)

## Acceptance Criteria
- [x] POC of 'type ahead' for mobile, desktop va.gov is generated, is minimal but sufficient to demonstrate what 'type ahead' could look like

**Comment by stephorkandatx** [comment]
We can do a demo, but we can't merge it because connecting with search.gov would need a secret key and would need to be built into the API.

**Comment by ncksllvn** [comment]
Demo recorded here, https://dsva.slack.com/archives/C011K1VSTC3/p1591305962015200

**Comment by ncksllvn** [comment]
Opened a PR to preserve the code although it is in no way merge-ready. We'd need a new API route built first, although that would be simple. 

https://github.com/department-of-veterans-affairs/vets-website/pull/12975

### Screenshots

#### Open state w/o input
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/76d579d8-aed7-4059-af5f-0e578284cae2)

#### Open state w/input
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/4f0c1e33-861e-463f-b5cb-484d7ea7e6c9)

### Open state w/option highlighted
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/4ed568b7-4c7a-4ee5-901d-a29218e63491)

**Comment by andaleliz** [comment]
@andaleliz to document any UX/a11y concerns and share back with the team and Jennifer Strickland. Not about type of results or quality of results.

Desktop and mobile

**Comment by ncksllvn** [comment]
Some mobile pics. I didn't apply any special style for mobile to get this UX. 

Screen recording here - https://dsva.slack.com/archives/C011K1VSTC3/p1591373031008700

### Mobile view
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/70666be6-dbfd-427a-9dd3-2f40eb85dff2)

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/06578942-907a-4ada-b304-47341f690b76)

**Comment by andaleliz** [comment]
@stephorkandatx and @ncksllvn I've taken a look at both of the videos, finally! I also spent some time digging into the facility locator type-ahead, thinking that is a reasonable model for us.

**General** 

1.  We're off to a good start!
2. I noticed the facility locator uses a dark blue background for the selected search result, and what is in the POC is a lighter blue. I'd recommend going w/ what the facility locator has for the following reasons:
    - Improved contrast ratio
    - consistency
    - darker blue will create greater differentiation if a user is scrolled to a point in the homepage where the background is blue

3. It looks like the mark-up for the suggestions has a major case of div-itis. I think it should be a `<ul>` but maybe this is part of the a11y known issues you mentioned Nick. Are those documented anywhere?

4. Generally it would be good to get a thorough a11y review of this as I'm sure there are some splinters I'm not seeing.  I don't see anything major that I haven't called out here.

**Desktop**
I don't have any desktop specific concerns from the video or what I saw on the facility locator page.

**Mobile**
Noticed a couple of things on the facility locator page:
- there is a weird lag for the suggestions to appear, it almost seems like it's not working for a second. I don't know if that's just the FL app itself or a function of the search box that would also appear in our implementation.
- There is a really narrow tap target between scrolling the page, and scrolling the results since the results take up the full screen. I'd love to brainstorm some ways to make that easier for mobile users. Also would be curious to get thoughts from our a11y team on the most accessible way to address that.

Not sure what else is needed from me on this or what next steps are. I'll stay tuned!

**Comment by stephorkandatx** [comment]
@johnhashva I am closing this out. We have the videos above that we can review with a11y in the future, as we look to pick this work back up
