### ISSUE TITLE
Edit: Replace Link Emojis: Partner Services (Upstream Services)  

### ISSUE THREAD

**Issue by taylojill** [department-of-veterans-affairs/va.gov-team#94918]
## Pain Point:
The document, [Partner Services (Upstream Services)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885601877/Partner+Services+Upstream+Services), contains many link emojis (🔗) instead of proper link formatting. 
The page is presently of limited use to VFS Teams. 

## Description:
Separate tickets in this Epic will track the work of fixing broken links. 
Once the links are pointing to the correct pages and those emojis are replaced with page titles, this next step will be performed.
- This ticket is for the work of replacing the **remaining** link emojis with page titles on the active page.

### Screen shot:
> ![image](https://github.com/user-attachments/assets/ad69d4fd-e581-4e1e-a6b1-2c8f37f4a529)

---
## Tasks 
- [x] Update live page to replace all link emojis with the current link in the form of the page title
- [x] check page for launch blockers
- [x] deploy page

## Acceptance Criteria
- [x] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
91763 work is being continued in this ticket as an edit

**Comment by taylojill** [comment]
Live page updated. Checked for blockers, date stamped, ready to publish.

**Comment by jknipes** [comment]
work is complete, closing as _Done_
