### ISSUE TITLE
[ENG] 10-10CG - Improvement: Allow pdf download after pdf download failures

### ISSUE THREAD

**Issue by coope93** [department-of-veterans-affairs/va.gov-team#94916]
## Benefit to the Veteran
As a Veteran/Caregiver, I want to be able to download a pdf copy of my 10-10CG submission, regardless of if there were any other errors.

## Scope
To make the 10-10CG pdf download functionality more robust, we should ensure that the download link remains regardless of if a past request to download has failed. Currently, if button was clicked and returned an error, we hide the download link and display an error. Instead, we should render an error and display the download link to allow for the Veteran/Caregiver to retry the download, since there may have been a one off reason the download did not work. 
- We could consider limiting this logic based on the error response code
- The risk of not doing that is that if something is really broken, the Veteran/Caregiver could repeatedly click the button and it would keep generating errors.

## Tasks
- [x] Confirm with PM and Design that this change is okay
- [x] [FE] Update button logic and subsequent tests to not hide the button on failure response
- [x] [FE] Examine and evaluate if limiting the behavior based on specific error responses would be valuable. A first step could be to introduce it without this limitation, but create a ticket to add it later. Or, we decide we don't want this behavior. 

## Acceptance Criteria
- The download pdf button at the end of the form will not be hidden after there is an error downloading a pdf, and will allow for more attempts.

**Comment by hdjustice** [comment]
- Maybe let's not limit the number of times a person could try downloading
- Could add additional logging to identify how many times this happens
- Check with CG team on whether there is another way for a user to get a copy of the application (this error can occur whether the submission is successful or not)

**Comment by hdjustice** [comment]
Design updates #104473

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that users are still able to download the PDF successfully after a PDF download failure. The ways that was tested to cause PDF download failures were:

1. No network
2. Invalid csrfToken value

<img width="1502" alt="Image" src="https://github.com/user-attachments/assets/13abaf6e-bef8-4c60-958d-b88d89e7b49f" />
<img width="1502" alt="Image" src="https://github.com/user-attachments/assets/4fb5e598-3250-4891-b2b5-bbe63e16aec3" />
