### ISSUE TITLE
Additional validation fixes for 2122 PDF

### ISSUE THREAD

**Issue by opticbob** [department-of-veterans-affairs/va.gov-team#94919]
## Background
The frontend and backend have both had some revisions and now we still have some validation errors happening.

- Submission without a claimant should be possible.
- The organization name has been replaced with an id.

## Tasks
- [x] Confirm that submission without a claimant is possible and tested
- [x] Lookup the org name from the supplied id

## Acceptance Criteria
- [x] The PDF renders as usual with the org name lookup

**Comment by opticbob** [comment]
I had some local env issues when setting up this branch but those are now resolved.

There is now a specific test to ensure that form submissions without a claimant succeed.

I did not find any way to match countries that should have states/provinces or not on the back end.  It looks like we're counting on the frontend validation there.

The frontend validates international postal codes for Canada but I'm not sure what other countries.  Canadian postal codes are 6 digits, which won't fit on our form as is.  We'll have to discuss what to do in those situations.

**Comment by oddball-lindsay** [comment]
Need to fix tests and have an open question about querying the old vs. new tables conditionally. Aiming to put this up for review today.

Let's move the open question about international province / postal codes to a new ticket.

**Comment by opticbob** [comment]
The following details have been removed from this ticket for inclusion in a future ticket.  You can find a slack discussion of these details [here](https://dsva.slack.com/archives/C044AGZFG2W/p1729102147542169)

### Background
- Not all countries have state codes, if the frontend submits without state code it should be allowed.
- Different countries have different postal code standards as well.

### Tasks
- [ ] See if there is a backend tool for unifying a country code with the possible states/provinces or if countries may not have states/provinces.  If there is consider it in the validation.  If not, remove the validation and rely on front end validation of state codes.
- [ ] Same for postal codes
- [ ] See if the frontend supports international postal codes

### Acceptance Criteria
- [ ] Submissions with an address in a country without state codes shouldn't throw a validation error.
- [ ] International postal codes are accepted

**Comment by opticbob** [comment]
This has been through a first round of reviews and the second round has been requested.

**Comment by opticbob** [comment]
The second round of reviews has been addressed and the third round has been requested.

**Comment by opticbob** [comment]
The PR for this has been approved by @jvcAdHoc .  I'll ping platform for a review at 2:15 Central time tomorrow afternoon if it hasn't been reviewed by then.

**Comment by opticbob** [comment]
The previous comment was unnecessary.  Platform reviewed the PR today and it has now been merged.
