### ISSUE TITLE
Content Edits: https://github.com/department-of-veterans-affairs/va.gov-team/issues/88957

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#94929]
## Issue Description
Per [ticket 88957](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88957), we need to add additional guidance re: ICNs

---
## Tasks
- [ ] Read [ticket 88957](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88957)
- [ ] Draft changes as suggested
- [ ] Share changes with Johnathan Kamens for approval

## Acceptance Criteria
- [ ] Page updated and ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
