### ISSUE TITLE
[CST] [ENG] (Tech Debt) `lastPage` navigation data stored in application state is unreliable.

### ISSUE THREAD

**Issue by LouisFettet** [department-of-veterans-affairs/va.gov-team#94937]
## Value Statement
**_As an_** engineer supporting CST
**_I want_** navigation data in state to be reflected accurately
**_So that_** I have confidence in writing features and fixes that interact with this data.

---
### Bug

While this isn't technically a bug impacting end-users, the way we're currently handling the `lastPage` value in application state makes it difficult to predict how certain pages and components will behave before and after loading.

This issue was documented [in Slack](https://dsva.slack.com/archives/C056854SVT8/p1725383010865999) during work on #86080:

> We rely on a `lastPage` value in state to determine where the user was before their current page, but this value gets set immediately on application load to the current page (instead of getting set after the user navigates once). This is causing problems when the user navigates for the first time; if a component relies on a `componentDidUpdate` hook that expects `lastPage` to change, it won’t fire because we’ve already set `lastPage` on load instead of on navigate (subsequent navigation works as expected).

## Outcome, Success Measure, KPI(S), and Tracking Link
N/A

## Design
N/A

## Engineering 

We're setting `lastPage` to the current page on application load (as soon as navigation / location data is available) here: https://github.com/department-of-veterans-affairs/vets-website/blob/96681a9a511eecc6ec3aeaaa4e99e95d08c21fc1/src/applications/claims-status/containers/ClaimsStatusApp.jsx#L57-L61

On a first pass, it seems that `lastPage` is currently used in a couple of ways:
1. To scroll and / or focus on the appropriate element on a page depending on where the user was last. There seem to be a number of different checks to determine where to scroll / focus the user. 
**NOTE:** If there is an existing doc or a previous issue that outlines the expected behavior, that would be really useful here to ensure everything is working as intended.
2. For setting a `backUrl` prop on some components (although it's unclear if this gets used anywhere).

## Out of scope

N/A

## Open questions
- Do we need to store something like `currentPage` in state for circumstances where we currently need `lastPage` to be set upon application load?

## Tasks
- [ ] Audit all uses of `lastPage` to determine:
  - Is it _actually_ asking about the previous page visited?
  - What would happen if this value wasn't set yet?
  - What happens when its value is set to the current page on initial application load? (Especially for pages that typically aren't visited directly, e.g. one of the tabs on the claims detail page or the document request page).
- [ ] Update [containers/ClaimsStatusApp.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/96681a9a511eecc6ec3aeaaa4e99e95d08c21fc1/src/applications/claims-status/containers/ClaimsStatusApp.jsx) so that we only set `lastPage` on a change to a route (when the user navigates).
- [ ] Based on the audit, some uses of `lastPage` will need to be updated to account for the value not being set on initial application load. A new value like `currentPage` may need to be added to state.

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria

As this is a tech debt issue and the exact changes needed are unclear at time of writing, engineering sign-off in code review serves as meeting the AC. Otherwise, ideally, the changes here do not impact the user experience at all (unless there are inconsistencies that are addressed as part of this work).

**Comment by pmclaren19** [comment]
Updated the tasks to include removing `backUrl`
