### ISSUE TITLE
[FSR] Deprecate unused enhanced feature flag

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#94930]
## Issue Description
`combined_financial_status_report_enhancements` has been removed for some time now, it's safe to remove any remaining references to it via `enhancedFinancialStatusReport`. The flag has been defaulted to true 

Flag is defaulted to true in `src/applications/financial-status-report/containers/App.jsx`:154

- [PR for removing feature flag from vets-api definitions (and defaulting it to true in FSR)](https://github.com/department-of-veterans-affairs/vets-website/pull/28078)

### Feature flag clean up tickets:
- ~~**[FSR] Deprecate unused enhanced feature flag [#94930](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94930)**~~ (this one)
- **[FSR] Deprecate unused streamlinedwaiver feature flag [#94931](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94931)**
- **[FSR] Deprecate unused streamlinedWaiverAssetUpdate feature flag [#94932](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94932)**

## Tasks
- [x] Remove any instances of `enhancedFinancialStatusReport`
- [x] Confirm functionality is unaffected

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] All references to `enhancedFinancialStatusReport` have been removed
- [x] FSR is functioning as normal     

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by Dr-Pongo** [comment]
Moving to blocked until Penny is back so we can wrap this up together!

**Comment by penny-lischer** [comment]
Unit tests still in progress due to removal of flag
