### ISSUE TITLE
[FSR] Deprecate unused streamlinedWaiverAssetUpdate feature flag

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#94932]
## Issue Description
`financial_status_report_streamlined_waiver_assets` has been removed for some time now, it's safe to remove any remaining references to it via `streamlinedWaiverAssetUpdate`. The flag has been defaulted to true 

Flag is defaulted to true in `src/applications/financial-status-report/containers/App.jsx`:155

- [PR for removing feature flag from vets-api definitions (and defaulting it to true in FSR)](https://github.com/department-of-veterans-affairs/vets-website/pull/28078)

### Feature flag clean up tickets:
- **[FSR] Deprecate unused enhanced feature flag [#94930](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94930)**
- **[FSR] Deprecate unused streamlinedwaiver feature flag [#94931](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94931)**
- ~~**[FSR] Deprecate unused streamlinedWaiverAssetUpdate feature flag [#94932](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94932)**~~ (this one)

## Tasks
- [ ] Remove any instances of `streamlinedWaiverAssetUpdate`
- [ ] Confirm functionality is unaffected

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] All references to `streamlinedWaiverAssetUpdate` have been removed
- [ ] FSR is functioning as normal     

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by amponce** [comment]
PR approved, ready for merge today. Joe noticed a strange axe bug that we're now seeing on main, I might hold on merging to see if it's there is a fix that might be bundled into this PR so we can get it out faster

**Comment by amponce** [comment]
Note -  **All references to streamlinedWaiverAssetUpdate have been removed:** We ended up keeping the app.jsx reference to `streamlinedWaiverAssetUpdate` because of a backend dependency that needs to be addressed in a future ticket.
