### ISSUE TITLE
Content Edits: 86577 - Platform Browser Policy

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#94933]
## Issue Description
Per [footer ticket 86577](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86577), we need to update information on Platform Browser Policy to align with Design System
---
The browser support policy in the Platform docs site says we support the current plus previous version of all browsers. The Design System says we support:

> ... older and newer browsers through progressive enhancement. We follow the 2% rule: we support any browser above 2% usage as observed by [analytics.usa.gov](https://analytics.usa.gov/).

These docs should agree. I believe it results in the same list of browsers and in fact analytics.usa.gov doesn't get into versions:

![Screenshot 2024-06-21 at 4 34 54 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/52176351/d514c122-c0ee-4fcb-bd33-15b25ccb2cb7)

Thus I believe the Design System's take on this is correct.

### Relevant URLs

- https://depo-platform-documentation.scrollhelp.site/developer-docs/browser-support-policy
https://design.va.gov/about/#browser-support
---
## Tasks
- [x] Add introduction that includes a version of the Design System policy: `Browser support
The Design System supports older and newer browsers through progressive enhancement. We follow the 2% rule: we support any browser above 2% usage as observed by [analytics.usa.gov](https://analytics.usa.gov/).`
- [x] Make changes according to Description
- [x] Update date stamp

## Acceptance Criteria
- [x] all tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by taylojill** [comment]
Page updated as requested. No SG issues. Date stamp added, checked for blockers, ready to publish.

**Comment by jknipes** [comment]
work is complete, closing as _Done_.
