### ISSUE TITLE
Content Edit: 82291 pt. 2

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#94934]
## Issue Description
We need to update the ZenHub authorization information per the last comments in [ticket 82291](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82291)

---
## Tasks
- [ ] Read last comments in [ticket 82291](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82291)
- [ ] Update page

## Acceptance Criteria
- [ ] Page is updated and ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Closing this ticket as ZenHub is no longer available.
