### ISSUE TITLE
[FSR] Deprecate unused streamlinedwaiver feature flag

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#94931]
## Issue Description
`financial_status_report_streamlined_waiver` has been removed for some time now, it's safe to remove any remaining references to it via `streamlinedWaiver`. The flag has been defaulted to true 

Flag is defaulted to true in `src/applications/financial-status-report/containers/App.jsx`:155

- [PR for removing feature flag from vets-api definitions (and defaulting it to true in FSR)](https://github.com/department-of-veterans-affairs/vets-website/pull/28078)

### Feature flag clean up tickets:
- **[FSR] Deprecate unused enhanced feature flag [#94930](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94930)**
- ~~**[FSR] Deprecate unused streamlinedwaiver feature flag [#94931](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94931)**~~ (this one)
- **[FSR] Deprecate unused streamlinedWaiverAssetUpdate feature flag [#94932](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94932)**

## Tasks
- [x] Remove any instances of `streamlinedWaiver`
- [x] Confirm functionality is unaffected

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] All references to `streamlinedWaiver` have been removed
- [x] FSR is functioning as normal     

## Testing
- [x] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by OptionSelect** [comment]
Per convo with Andrew in standup putting this on bench until we receive Denise determination that behavior is no longer needed.

**Comment by Dr-Pongo** [comment]
After some more chats! Let's update FSR so streamlined waiver feature flag is used in a single spot to enable/disable the feature. Here are some of the references I found and suggestions for how to proceed. (I'll update the todo's in the main ticket 

**Current references in non-json files (5):** 
- `src/applications/financial-status-report/utils/streamlinedDepends.js`
	- Does this seem like a good spot to be our feature controller? if isEligibleForStreamlined is false then all of the other streamlined functionality is disabled. 
- `src/applications/financial-status-report/containers/App.jsx`
	- Update to reference flag again (has been hard coded to true leading up to disabling)
- `src/applications/financial-status-report/components/employment/EmploymentQuestion.jsx`
	- Currently checks feature flag before making fetch for GMT data, switch to checking isEligibleForStreamlined instead? 
- `src/applications/financial-status-report/components/household/DependentAges.jsx`
	- There is a reference here, but not sure if we need it? First glance it looks like we may not need the check any more and we can just remove the jump to monetary assets checklist? 
- `src/applications/financial-status-report/config/chapters/veteranInformationChapter.js`
	- I don't think we need this in the depends anymore!

**Comment by OptionSelect** [comment]
This ticket will likely roll into next sprint due to it being blocked and repurposed to newly discussed tasks after speaking with Denise and Andrew.

**Comment by OptionSelect** [comment]
This ticket might roll due to needing additional support from FE team members who have been pulled into helping with PDF generation effort. Work is all done its just nagging tests not happy.
