### ISSUE TITLE
1010EZ form in-progress email

### ISSUE THREAD

**Issue by aliyahblackmore** [department-of-veterans-affairs/va.gov-team#94944]
## Issue description
The 1010 health apps team needs content support on an email that's sent out to Veterans who have a saved and in-progress form. It's an email to remind them that they have a form that's in progress and the expiration date. 

[Intake request ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94826)
[Figma file](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=6580-432765&node-type=section&t=Tx8Dyz9VjKq7RvFq-0)

---
## Tasks
- [ ] Assess request
- [ ] Draft content
- [ ] Share with requesting team

## Acceptance Criteria
- [ ] Feedback has been shared with requesting team

## Configure this issue
- [ ] _Attach to an Epic or Intake if this is related to other work_
- [ ] _Label with Originator/Team (product team or stakeholder requesting support)_
- [ ] _Label with Open Date_
- [ ] _Label with Estimate (level of effort expected for this ticket)_
- [ ] _Add assignee name to each task they will complete (if known)_
- [ ] _Update the status to reflect where this work is in the pipeline (in progress, backlog, etc.)_

**Comment by aliyahblackmore** [comment]
**Update here** 

- Content feedback is ready in their Figma file. 

- I shared with the team that once CAIA gets this email template in to VA notify, there may be some slight adjustments in the future.
