### ISSUE TITLE
Remove Playbook from VA.gov XML Site Map

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#9494]
## What happened?
The legacy [Vets.gov Playbook ](https://www.va.gov/playbook/) is currently positioned at the top of the VA.gov XML site map and needs to be removed because the content of the Playbook is no longer updated.  (Note per @KevinMHoffmanUSDS  and @mnorthuis : DEPO needs to determine if the Playbook should be updated and relaunched, or permanently retired.)

A related ticket with additional context is [here.](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13817)

[# Specs:
- Device: Desktop and Mobile
- Browser: All Browsers
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
- The Vets.gov product playbook should no longer be included in the [VA.gov xml site map](https://www.va.gov/sitemap.xml).

## Tasks

- [x] John to get confirmation with DEPO that this should be removed
- [ ] If it moves forward Sam would need time to explore the Vets.gov Playbook

## Acceptance Criteria
- [ ] The Vets.gov playbook is no longer included in the VA.gov xml site map.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by denisecoveyduc** [comment]
1/13 - @johnhashva  will review with the business to confirm if this is something we really want to do or not.

**Comment by denisecoveyduc** [comment]
In Planning discussion Jan 12 - @johnhashva received confirmation that this playbook can be removed from the site map. This will therefore be explored in Sprint 39.

**Comment by srsuddath** [comment]
Ticket has been merged and pages have been removed from sitemap
