### ISSUE TITLE
VBA Change Call-First to Online Tools and Customer Service Number on Detail page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9496]
## Issue Description

The current function of "Planning to visit? Please call first as information on this page may change." is inaccurate in the case of Benefits facilities. VBA does not wish to provide local numbers and only provides a national call center number.  This national call center number will be unable to answer questions such as "Where do I park" or visit-related information.  

In addition, there is an opportunity to direct veterans to online tools to assist him or her before going to a VA facility.

As a Veteran, I need to know how to reach VBA customer service so that I can get more information about the benefit service I seek. 

## Expected behavior
Add link to VBA online customer service tool, phone number or other benefit website.

**To check on the status of your claim or appeal**, use our _online claim status tool_. [link to: https://www.va.gov/claim-or-appeal-status] 
 
**To get help with benefits**, call 800-827-1000 [hyperlink phone number] toll-free. We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. If you have hearing loss, call TTY 711.

**For other benefit questions**, use our online customer service tool called _IRIS (Inquiry Routing & Information System)_. {link to: https://iris.custhelp.va.gov/]

---
## Tasks
- [ ] For VA Facilities type = Benefits Replace "Planning to visit? Please call first as information on this page may change."
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
[https://app.zenhub.com/files/133843125/2b010519-2d2d-47f0-a9ee-92c6fb7d8cbc/download](https://app.zenhub.com/files/133843125/2b010519-2d2d-47f0-a9ee-92c6fb7d8cbc/download)

This is the "evergreen" text

**Comment by davidconlon** [comment]
We need to prioritize this for Sprint 26 as part of the COVID response as VBA facilities reopen.

**Comment by davidconlon** [comment]
Also, we now know that IRIS is funded for at least 6 months.

**Comment by brangi** [comment]
merged
