### ISSUE TITLE
Test the Accreditation API in Staging

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#94994]
## Background
The Accreditation API _should_ be available to us in Staging, but we are experiencing issues reaching it. Perhaps it's just that we need to use the port 4501.

This ticket is to confirm we can access the Accreditation API in Staging, and that it meets our expectations.

If it doesn't meet expectations, then we should let Randy Trexler know asap so that adjustments can be made as we move towards Production.

## Tasks
- [x] Successfully access the Accreditation API in Staging
- [x] Document in this ticket if the API meets our expectations (and if not, what is missing)

## Acceptance Criteria
- [ ] We understand how the Accreditation API fits into our expectations, with digital submission in mind.
- [ ] If we require additional work on the Accreditation API, that work has been communicated to Randy Trexler and our Product Owner, Jen Bertsch.

**Comment by oddball-lindsay** [comment]
Hoping to get access from Randy Trexler's team to swap to the "right" port number (ie the port number we got approved through the ESECC process).

**Comment by oddball-lindsay** [comment]
@holdenhinkle confirmed that we are now able to hit the Accreditation API from vets-api Staging: https://dsva.slack.com/archives/C06ABHUNBRS/p1729891836264159

And we know from Swagger documentation that the API meets our expectations, the difference is now we can do that from vets-api directly and no longer need to rely on the Swagger docs.
