### ISSUE TITLE
ARM Research: Manage VSO Panel

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#95006]
## Background
Ongoing ticket to upload new VSO sign-ups to participant panel. Covering until ARF/ART is onboarded. Managing once a sprint.

## Tasks
- [ ] Review [GDrive](https://forms.gle/duTQscHHq9381Lse8) and [Sharepoint](https://forms.office.com/g/R8QkG87L8h ) for new sign-ups
- [ ] Mark new sign-ups in [Excel sheet](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Cross-product%20and%20crews/Research%20ops-%20VSO%20%26%20Accredited%20Rep/Panel%20Recruitment/2024-09-13%20VSO%20Emails.xlsx?d=wdb1eff4f30814f0196211bbcf1da44db&csf=1&web=1&e=uXVvIE)
- [ ] Transfer sign-ups to [participant panel](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representatives/Research/00%20Participant%20Panel/2024_10_Rep_ParticipantPanel.xlsx?d=w6c6ec23af1814f2abf5beeb5849d7c39&csf=1&web=1&e=v3C5dE)
- [ ] Clean up information in participant panel
- [ ] Inform Lesley of new sign-ups

## Acceptance Criteria
- [ ] Tasks complete, create new ticket for next sprint
