### ISSUE TITLE
Create an On Call Schedule for Datadog alerts

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#95016]
## Background
We have alerts from Datadog routing to #benefits-representation-management-notifications on Slack, but need to define who owns those alerts and what we do when an alert arises.

## Tasks
- [ ] Document an On Call schedule with ARM developers
- [ ] Add the On Call schedule to the FAR team calendar for visibility
- [ ] Document expectations for the developer on call

## Acceptance Criteria
- [ ] When a Datadog alert comes through, the team knows who will be handling the alert and what that "handling" consists of.

**Comment by oddball-lindsay** [comment]
https://docs.google.com/spreadsheets/d/1hPR4yDqK7ju5BSkbORhh9nnEc3HMBbgWifDbLv9IPi8/edit?gid=0#gid=0
