### ISSUE TITLE
Create Datadog Monitors for Form Submission Storage

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#95024]
## Value Statement

**_As a_** Veteran

**_I want to_** have errors alert developers directly in Slack

**_So that_** I can have confidence that failures/errors are not missed and are remediated as necessary.

---

## Background Context

As we now have StatsD metrics encompassing Form Submission storage as part of #90103, we can also create monitors for alerts to be sent to the appropriate Slack channels. The team will not need to manually monitor the dashboard or daily API report emails for errors.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Datadog monitors are created for health metrics being tracked on https://vagov.ddog-gov.com/dashboard/fps-2wj-ceb
- Datadog monitors send the alerts to #benefits-decision-reviews-notifications

## Acceptance Criteria

- [x] Monitors are created for each type of submission failure (forms and evidence uploads)

## Open questions

- Add here

## Tasks

- [x] Create monitors for HLR, NOD, SC form errors
- [x] Create monitors for NOD and SC evidence errors
- [ ] Ensure monitor alerts are sent to the Slack channel #benefits-decision-reviews-notifications

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
Monitor created: https://vagov.ddog-gov.com/monitors/287790

**Comment by dfong-adh** [comment]
Monitors for form errors created:
https://vagov.ddog-gov.com/monitors/287858
https://vagov.ddog-gov.com/monitors/287859
https://vagov.ddog-gov.com/monitors/287860
