### ISSUE TITLE
[BE] 10-10EZ - BUG: Investigate why VeteranDateofBirth isn't consistently saved in form_data

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#95049]
## Benefit to the Veteran
As a Veteran, I want to return to my in-progress application, and submit it without errors, so that I can feel confident that my form data is complete and accurate

## Scope
Related to #94779, this ticket is to investigate the issue where an authenticated Veteran is returning to the 10-10EZ form in-progress, and when they try to submit, the `VeteranDateofBirth` value is not saved in the `form_data`.  This is not happening in any sort of pattern or consistency.

## Tasks
- [ ] Investigate the issue
- [ ] Determine root cause
- [ ] Determine solution
- [ ] Discuss with team/PM for next steps

## Acceptance criteria
- The issue has been investigated and we have next steps to resolve it.
