### ISSUE TITLE
Prepare OH MVP prototype from midpoint review

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#95048]
## Task Description
Prepare the OH MVP prototype from midpoint review

## Notes and References
-[ Collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87703)

## Acceptance Criteria
- [ ] Make sure all of the screens we intend to have  reviewed are in the prototype
- [ ] Make sure all of the interactions work
- [ ] Add link to prototype to the[ ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87703)
- [ ] check off prototype in the required artifacts section of the ticket

## Deliverables
- [prototype file](https://www.figma.com/design/EHR9zBpGnAgc7bHqeIGEoT/OH-Direct-Schedule-MVP-%7C-Appointments-FE?node-id=2980-18211&node-type=canvas&t=DggqMNsdulrF5uvc-11)

**Comment by outerpress** [comment]
No need for a prototype since we have user flows, closing
