### ISSUE TITLE
[VETS-API] Fix "EOF" issue in CI

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#95056]
The following error is popping up in a Github Action for PRs every so often:

`/home/runner/work/_temp/3711f819-88c3-4533-82f2-1842aa10d536.sh: line 345: unexpected EOF while looking for matching "'
Error: Process completed with exit code 2.`

## Tasks
- [ ] Determine Root Cause
- [ ] Submit and test solution

## Acceptance Criteria
- [ ] Fix has been pushed to master and error is no longer appearing
