### ISSUE TITLE
[FSR] BE legacy feature flag deprecation 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#95068]
## Issue Description
Investigate feature flags up for deprecation to see if a BE effort is necessary. The flags have been removed from `vets-website` (`src/platform/utilities/feature-toggles/featureFlagNames.json`) and `vets-api` (`config/features.yml`). 

- [FE PR that defaulted flags to true in FSR](https://github.com/department-of-veterans-affairs/vets-website/pull/28078)

### Feature flags for removal
- `combined_financial_status_report_enhancements`
- `financial_status_report_streamlined_waiver`
- `financial_status_report_streamlined_waiver_assets`

### FE Feature flag clean up tickets
- **[FSR] Deprecate unused enhanced feature flag [#94930](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94930)**
- **[FSR] Deprecate unused streamlinedwaiver feature flag [#94931](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94931)**
- **[FSR] Deprecate unused streamlinedWaiverAssetUpdate feature flag [#94932](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94932)**

## Tasks
- [x] Confirm legacy functionality disabled by feature flags is no longer around
- [ ] (Optional) Create tickets to clean up now deprecated functionality

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] Legacy functionality is confirmed no longer around
- OR
- [ ] Follow on tickets have been created for cleanup work

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by penny-lischer** [comment]
Confirmed in both vets-api and vets-website that these features are non existent.
