### ISSUE TITLE
Change Owner of API Client for Performance Dashboard to Service Account

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#95079]
### Description
As discussed in meeting with Mason on 10/16, this ticket is to work to move the API Client for the Performance Dashboard from Adam King, to our Domo Service Account. This is to ensure that if Adam leaves, the Performance Dashboard is still able to function.

We need to change the owner from Adam, to our Service Account.

![Image](https://github.com/user-attachments/assets/a8dba28d-3705-4e5b-9fb9-f1e030ddae2b)

---
### Tasks

- [x] Navigate to Domo App Store
- [x] Download _**Domo APIs**_
- [x] Create a Dev Portal Login with our Service Account (VA.gov Platform Analytics & Insights)
- [x] Change the owner of the API Client for the _performance_dashboard_ from Adam King to Service Account (if needed, schedule time with Mason Crane for this)

### Acceptance Criteria

- [x] API Client for Performance Dashboard is dependent on the Platform Analytics Service Account, (as opposed to Adam King)

**Comment by johnny-jesensky-adhoc** [comment]
@MasonOddball -- think I captured most of what we discussed earlier -- let me know if I missed anything. 

I'll keep you and @mcommons10 posted on when our team might be able to get to this work.

**Comment by johnny-jesensky-adhoc** [comment]
Met with, and emailed over the API Client information to the IIR Team. They should have everything the need on this -- moving to _Done_.

FYI @Blivaditis
