### ISSUE TITLE
[CAIA a11y Research] Content Feedback: Authenticated Experience Design Patterns Team: Prefill Pattern

### ISSUE THREAD

**Issue by sara-amanda** [department-of-veterans-affairs/va.gov-team#95070]
> [!NOTE]
> CAIA Accessibility Specialists met with the Authenticated Experience Design Patterns Team to prepare for upcoming research sessions.
> - [x] **There were a few questions, surrounding content**, that were shared and are now housed in this ticket. 
> - [x] **Next Step:** Handing off the content portion via this ticket, to the CAIA Content Team. (Added comment to intake and ticket to content task list in intake.)

## What to review
- [CAIA Feedback Request page](https://www.figma.com/design/1z3bAkQl4uR1IvAxmtyqZi/AE-Design-Patterns---Update-Prefill?node-id=689-21949&node-type=canvas&t=IXY2qkZoahO6lzBs-0)
   - check out the [Research Study page](https://www.figma.com/design/1z3bAkQl4uR1IvAxmtyqZi/AE-Design-Patterns---Update-Prefill?node-id=3387-40809&node-type=canvas&t=IXY2qkZoahO6lzBs-0) to see those designs in context
   - leave feedback as Figma comments

## Important Dates
The Authenticated Experience Design Patterns Team is currently prepping for research and is working on a design prototype via Codespace based on the Figma designs, that will be used in user testing.
- **10/16/2024 to 10/25/2024:** The content updates would need to be recommended, prior to the user testing. 
- **10/28/2024**: The pilot for user testing is planned to take place the last week in October, using the Codespace prototype.
- **11/4/2024 to 11/25/2024:** The user testing will be taking place the first and second weeks of November, using the Codespace prototype. 

## Issue description

- There is not a lot of guidance currently on the updating process. 
- The team is working through this, as part of their research and designs.

### Auto-Select Set to Yes

**The team is wondering if there is any guidance on `auto-select`?**  
#### Form Question Example
- **Question**: Do you also want to save this updated home phone number to your VA.gov profile? (*Required)
- **Answer**: Yes (selected by default) or No

#### Image of Auto-Filled Prompt

![Question: Do you also want to save this updated home phone number to your VA.gov profile? *Required answer. Yes is the answer that is selected by default.](https://github.com/user-attachments/assets/f23d10e8-74c6-4f92-87be-6abc1d1441eb)

> [!TIP]
> _**Accessibility Tip**: It is easy to skip something if it is not there. It can also skew results._ 

### Saving Inquiries

**The team is curious as to:** 
- How they should reflect, how to change where it saves? 
- How should they convey that it has saved, and where it has saved? 

_They would also like to collect data on this and where the best place to save is._

 ### Update Limitations

**The team would like to include language around why we don't allow updates to certain pieces of personal information.** 
- They are also not 100% certain of the correct information to convey at this time, so your knowledge in this area would be very helpful. 
- **Second Sentence:** The team is looking for help with the second sentence in this language surrounding why they don't allow certain updates. 

> Note: To protect your personal information, we don't allow online changes to your name, date of birth, or Social Security number. If you need to change this information for your health benefits, call your VA health facility. Find your VA health facility. 

#### Image of Current Limitations Text
![Note: To protect your personal information, we don't allow online changes to your name, date of birth, or Social Security number. If you need to change this information for your health benefits, call your VA health facility. Find your VA health facility.](https://github.com/user-attachments/assets/74a30757-6be3-477c-8a7b-630526d9cb22)

### Fields
- **Name** (This can be edited in some forms, not all.)
- **SSN** (See section below for questions on SSN.)
- **DOB** (Do they have to go to SSA, if there is an error on VA?) 
- **Gender** (There may be a process, but not sure how to update with VA.)
- **Service History** (Can't be updated in profile, but can be provided.)

#### Image of Card View: Veteran Info Fields
![Card image of fields name, sun, dob and gender](https://github.com/user-attachments/assets/4da848cb-07f3-4a72-818e-f581a0133cc8)

### SSN Field

- Do they have to go to SSA if there is an error on VA for SSN? 
- SSN Display: How do they standardize the accessibility of SSN (dots, asterisks, etc.) is there a visual standard for this? 
 
> [!TIP]
> _**Accessibility Tip**: Across VA we have seen an asterisk and a screen reader will say star, star, star, dash 1234. If it could say last four of social security number 1234, that would be ideal._
 
---
## Tasks
_What work is necessary for this ticket to be completed? Examples:_
- [x] Assess request
- [x] Draft content
- [x] Review 
- [x] Share with requesting team
- [ ] Update page
- [ ] Copyedit
- [ ] Publish
- [x] Alert requesting team

## Acceptance Criteria
_What will be created or happen as a result of this story? Examples:_
- [ ] Updated content is live on the site
- [ ] Product has launched
- [x] Feedback has been shared with requesting team

## Configure this issue
- [x] _Attach to an Epic or Intake if this is related to other work_
- [x] _Label with Originator/Team (product team or stakeholder requesting support)_
- [x] _Label with Open Date_
- [x] _Label with Estimate (level of effort expected for this ticket)_
- [ ] _Add assignee name to each task they will complete (if known)_
- [ ] _Update the status to reflect where this work is in the pipeline (in progress, backlog, etc.)_

## Related Tickets
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/90140
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/94733

**Comment by sara-amanda** [comment]
## Ticket Handoff

@strelichl please find this new content task ticket, stemming from an accessibility meeting we held today with the Authenticated Experience Design Patterns Team. These are the content inquiries they expressed. I have included the questions, screenshots, along with a list of important dates, as they prepare for research. 

Should you have any questions, @coforma-jamie @mutiaadhocteam and myself were on that call, today. 

cc: @NaomiPMC

**Comment by coforma-jamie** [comment]
@strelichl  ready for closure review

**Comment by sara-amanda** [comment]
> [@strelichl](https://github.com/strelichl) ready for closure review

- [x] Validated - Closing for @strelichl and adding to tracking sheet, @NaomiPMC
