### ISSUE TITLE
FE | Profile | Unplanned Work

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#95071]
## Background
This is unplanned work.

## Tasks
Okta/Datadog Access
- [x] Resolve issue with PIV card
- [x] Pair with Matt Long
- [x] Submit request for Okta
- [x] Submit request for Datadog
- [x] Access is granted for both

TMS access
- [x] Recover my VA TMS account 

Keybase issues
- [x] Resolve issue with Keybase application needing repaired

PII ticket:
 - [x] Discuss with Asiisii

## Acceptance Criteria
- [ ]
