### ISSUE TITLE
DR | Poll Lighthouse for 4142 status and set status in vets-api

### ISSUE THREAD

**Issue by kayline** [department-of-veterans-affairs/va.gov-team#95084]
## Value Statement

**_As a_** developer

**_I want to_** to check whether 4142s make is successfully to CMP

**_So that_** so I can track and notify about failures

---

## Background Context

Historically some form and evidence submissions have failed to make it all the way through CMP, but we did not have a way to check or take action when it happened. We have tracking adn notification in place for our main forms and evidence, but not for the 4142 form we sometimes submit as a PDF using teh evidence upload endpoint.

## Outcome, Success Measure, KPI(S), and Tracking Link

- DataDog dashboard showing any 4142 failures

## Acceptance Criteria

- [ ] DD Dashboard shows total failures over time
- [ ] SecondaryAppealForm record for each failure can be used to identify the veteran

## Designs and Build Notes

Log the failure as described [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md) until we finish the next story adding notifications

### Enablement team (if needed)
@ member of team

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by kayline** [comment]
In-progress PR here: https://github.com/department-of-veterans-affairs/vets-api/pull/19040
