### ISSUE TITLE
[FSR] Wizard - FE / Design Sync

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#95102]
## Issue Description
Sync with Design team on finalized designs to ensure feasibility and new feature comprehension. 
- [**Convo with CAIA**](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92685#issuecomment-2403456589)
- [**Mural that CAIA created**](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719575899476/af5312c6ead879ab159500a9ee7a572e11ed0b0a?wid=0-1719576030379&sender=ua78f969c4cddcbfe56b27885)

## Tasks
- [x] Sync with design to understand new feature 
- [x] Confirm FE tickets cover all changes

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [x] FE and Design agree on new features
- [x] FE has tickets which cover all new features

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by Dr-Pongo** [comment]
Including a PR to show/hide existing wizard reset link based on current feature flag (`show_financial_status_report_wizard`) so we can more easily separate features.
