### ISSUE TITLE
[FSR] Wizard - Create feature flag

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#95103]
## Issue Description
Create a feature flag that, when activated, will hide the existing FSR Wizard, and update relevant links in CDP which point to the FSR. (Assuming they will now point to the new static page)

Follow [platform guidance on creating feature flags](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide)

## Tasks
- [x] Feature flag has been created in `vets-api`
- [x] Feature flag has been created in `vets-website`

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] New feature flag has been created 

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
