### ISSUE TITLE
[FSR] Wizard - Implement wizard changes

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#95104]
## Issue Description
Implement feature flag created in ticket below to hide existing wizard and include content changes for beginning of FSR. 

- **[FSR] Wizard - Create feature flag [#95103](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/95103)**
- **_Coming soon_** - link to finalized designs for FSR introduction page(s)

## Tasks
- [ ] Update wizard in FSR to show/hide based on the feature flag above
- [ ] Update FSR intro content
- [ ] Confirm changes with design (show & tell?)

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Wizard is showing/hiding based on feature flag
- [ ] FSR introduction pages include new content based on feature flags
- [ ] Changes previewed and approved by design

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by Dr-Pongo** [comment]
Just waiting on final approval from CAIA I think!

**Comment by OptionSelect** [comment]
Blocked until CAIA feedback received per convo with Devi.

**Comment by Dr-Pongo** [comment]
Closing this out now that Wizard work and definitions have changed
