### ISSUE TITLE
[FSR][CDP] Wizard - Generate relevant testing 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#95107]
## Issue Description
Generate relevant unit and/or e2e tests to cover new Wizard changes if applicable. 

## Tasks
- [ ] Create new tests to cover wizard changes

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Wizard changes have relevant testing where necessary 

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by Tom-Davis** [comment]
This ticket is not needed for the approach being taken.
