### ISSUE TITLE
Hide Products tab from Atlas

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#95114]
## User Story
As someone looking into VA products, I want to not be confused about outdated products in Atlas, so that there is one source of truth when it comes to VA Products.

## Issue Description
Since the "Products" tab (and maybe "Owners", too?) is not maintained and seem to be confusing people, hide that tab or have it link to the [VFS product directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory) instead. 

## Tasks
- [ ] Determine whether "Owners" should be hidden.
- [ ] Decide whether "Products" tab should be hidden or if it should link to the [VFS product directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory) instead. 
- [ ] Make the changes in Atlas

## Success Metrics
_Describe what success looks like for this work. Define specific, measurable outcomes that indicate success._

## Acceptance Criteria
- [ ] PRs to Atlas are reviewed, merged, and validated. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by rmtolmach** [comment]
Rachal's idea: we could hide Products under an admin role so that we don’t loose the code but it’s hidden from all users.
