### ISSUE TITLE
Remove duplicate Teams in Atlas

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#95112]
## User Story
As a user of Atlas, I want there to be one source of truth for teams, so that I am confident in Atlas's data.

## Issue Description
It was [brought to our attention](https://dsva.slack.com/archives/C0460N83Y9G/p1729102220025669?thread_ts=1729002796.015489&cid=C0460N83Y9G) that there are many duplicate (or almost duplicate) team names. This is confusing. Here is the list (grouped by duplicates):
https://www.va.gov/atlas/product_directory/teams/249
https://www.va.gov/atlas/product_directory/teams/244
https://www.va.gov/atlas/product_directory/teams/107

https://www.va.gov/atlas/product_directory/teams/243
https://www.va.gov/atlas/product_directory/teams/204

https://www.va.gov/atlas/product_directory/teams/96
https://www.va.gov/atlas/product_directory/teams/247
https://www.va.gov/atlas/product_directory/teams/240

https://www.va.gov/atlas/product_directory/teams/85
https://www.va.gov/atlas/product_directory/teams/246

https://www.va.gov/atlas/product_directory/teams/24
https://www.va.gov/atlas/product_directory/teams/259

https://www.va.gov/atlas/product_directory/teams/58
https://www.va.gov/atlas/product_directory/teams/238

https://www.va.gov/atlas/product_directory/teams/226
https://www.va.gov/atlas/product_directory/teams/237

https://www.va.gov/atlas/product_directory/teams/234
https://www.va.gov/atlas/product_directory/teams/5

## Tasks
- [x] For each group of duplicates, move team **info** and **members** under one Atlas Team, then delete the dupes. 
- [x] If a team goes by multiple names, specify that in the "Other Names" field. 

## Success Metrics
When scrolling through the Teams in Atlas, there are no duplicate teams

## Acceptance Criteria
- [x] All duplicate Teams are consolidated
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by davidpetras** [comment]
This compiled list of teams has been consolidated. 

Complete
