### ISSUE TITLE
EYB: Cross-browser Testing

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9512]
As a MVP development team, I need to conduct cross browser testing as part of the pre-launch activities.

## Assumptions:
1. Requirements for cross browser testing are located in GitHub: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/DeveloperDocs/testing/cross-browser-manual-testing.md
2. The final/complete build has been deployed to staging
3. All parts of the form are present and working correctly
4. Tester has access to most common browsers including: Chrome, Safari, IE 11, Firefox. This could be using an external tool like Browserstack or a Virtual Machine
5. Tester can access mobile simulation and desktop formats
6. End to End test script exists here: [TBD]

## Acceptance Criteria:
1. The update to "Estimate Your Benefits" functionality within the comparison tool has been tested and run through from beginning to end with no errors or problems on most common browsers and formats: 
   a. Chrome
   b. Firefox
   c. Safari 
   d. IE 11
   e. Mobile
   f.  Using google's responsive features.

## Tasks
- [ ] Ensure that all changes are deployed to Staging before being testing
- [ ] Test form end to end on Chrome
- [ ]  Test form end to end on Firefox
- [ ] Test form end to end on Safari
- [ ] Test form end to end on IE 11
- [ ] Test form end to end on Mobile
- [ ] Test form using google's responsive features.
