### ISSUE TITLE
Create feature toggle for new confirmation page

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#95149]
## Issue Description
As a team member, I want a feature toggle so that I can control the availability of the new confirmation page changes that Veterans will see. This will help me mitigate risk associated with releasing new features. This will put all changes to the confirmation page, loading page, and alerts behind one toggle.

Update 10/17/24: engineers discussed and agreed this could be a FE only toggle. If we need to persist the toggle value, look into saving it as `formData` rather than `sessionStorage`

## Tasks
- [x] Determine the feature toggle name
- [x] Determine if this is a frontend or backend toggle
- [x] Create the toggle using [Platform best practices](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide) as a guide
- [x] Figure out if toggle persistence across pages is needed or if we can just call it from `ConfirmationPoll` and pass it down to its components

## Acceptance Criteria
- [x] A feature toggle is created that follows our naming convention
- [x] The feature toggle exists for both staging and production
- [x] Ensure the toggle is available in Flipper Admin
- [x] Toggle retrieval is added to appropriate page(s), component(s)

## Additional Information
Suggested name for toggle: disability_526_new_confirmation_page
We can use the vanilla feature toggle, no need to persist this as formData

**Comment by aurora-a-k-a-lightning** [comment]
For:

> Figure out if toggle persistence across pages is needed or if we can just call it from ConfirmationPoll and pass it down to its components

i am using a pattern found on other applications that uses the `<Toggler>`  utility. 
If we want to use something else, that fine with me. 
My code simply proves that the toggle can be retrieved and utilized :D
