### ISSUE TITLE
Burial Product Spike: Approach for Action Needed email

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#95158]
## Issue Description
The purpose of this ticket is to explore how to handle the "Action Needed" email for the burial form given that email is not a required field.

---
## Tasks
- [ ]  Research how other teams handle similar scenarios
- [ ]  Brainstorm within delivery team
- [ ] Propose options and suggested approach to enablement team

## Acceptance Criteria
- [ ]  Options and suggested approach documented and presented to enablement team for feedback

**Comment by aplatt-coforma** [comment]
We got guidance from the VA enablement crew to proceed with requiring emails for all forms on va.gov https://dsva.slack.com/archives/C07QVEDUQ2D/p1730990852811129 for decision on requiring email.

Closing this ticket since the approach as need provided. Will create engineering ticket to make email a required field for Burial
