### ISSUE TITLE
SC | Update frontend with new form questions

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#95167]
## Value Statement

**_As a_** developer of the Supplemental Claim app
**_I want to_** start building the frontend
**_So that_** it will be ready once Lighthouse completes the API

---

## Background Context

After completing research on our Supplemental Claim prototype, we now want to implement these changes into the live Supplemental Claim form; but add it behind a feature toggle so that we can test and release the new form in stages.

The prototype was a completely separate app and did not involve any feature toggle code work, so implementing it in the main application will require extra caution to ensure that both versions can be submitted without issues.

Additionally, we may need to revisit our list & loop pattern. Consider switching over to the alternate list loop pattern developed by the forms team.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [x] Feature toggle implemented
- [ ] Data migration in place
- [ ] All new pages added
- [ ] Update confirmation page to show submitted data
- [ ] Unit tests & E2E tests added and all passing
- [ ] Maintain 90+% code coverage
- [ ] Flow tested in staging

## Designs and Build Notes

- [Figma](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=1394-21883&node-type=canvas&t=aWISQuXKYJDco9Ub-0)
- Continue discussions, and update design, if new list loop pattern is to be used

### Enablement team (if needed)
@ member of team

## Out of scope

New API endpoint has not yet been implemented:
- Update submit transformer
- Add new API endpoint

## Open questions

- ~Should we include updates to confirmation page?~ Yes!

## Tasks

- [ ] Feature toggles only show new or old content
- [ ] Add migration of in progress data
- [ ] Add housing situation page
- [ ] Add MST option question page
- [ ] Add option indicator question page
- [ ] Add facility type page
- [ ] Update VA facility page (month/year selector)
- [ ] Update evidence summary page (only show month/year)
- [ ] Add review page components
- [ ] Update confirmation page to show submitted data
- [ ] Add/update unit tests
- [ ] Add/update E2E tests
- [ ] Add/update mock data

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by kayline** [comment]
WIP, probably 5 or 6 PRs total

**Comment by Mottie** [comment]
Supplemental Claim changes are now enabled for all users in staging. Changes to evaluate:
- [ ] Introduction page MST content below OMB info
- Living situation chapter
  - [ ] Homeless or at risk (optional, no errors)
  - [ ] Living situation (visible when "Yes" is selected for homeless question)
    - [ ] Error if "None" and any other checkbox is checked 
  - [ ] Other housing risk (visible when "another housing risk" is selected on living situation page)
    - [ ] Error if more than 100 characters entered
  - [ ] Point of contact (visible when "Yes" is selected for homeless question)
    - [ ] Error for invalid phone number
- [ ] MST option (after issue summary, or opt-in page if any legacy issues exist) (optional, no errors)
- [ ] MST option indicator (visible when "Yes" is selected on MST page) (optional, no errors)
- [ ] Facility types page (optional, no errors)
- [ ] VA evidence request page (required, but only content changes)
- Add VA treatment location (visible if "Yes" selected for VA evidence)
  - [ ] Content changes
  - [ ] Treatment date has date validations, but is ignored if the "I don't have the date" checkbox is selected
- [ ] Evidence summary shows VA treatment date or "I don't have the date" 
- Review & submit page updates
  - [ ] New "Living situation" chapter with up to 4 pages
  - [ ] Issues for review chapter has MST option & MST option indicator pages
  - [ ] Evidence chapter has treatment facilities & locations with short date or no date message

**Comment by eileen-coforma** [comment]
Almost done writing unit tests for PR. Will be out today.

**Comment by Mottie** [comment]
This is ready for review in staging

**Comment by eileen-coforma** [comment]
@Mottie 

I confirmed all of the new pages are in, and looks good for the most part. It's an exact carryover from the prototype.

A few minor things (missed on my part):

1. Facility question is required, not optional. I've updated the design to reflect that.

2. VA treatment date, is there a way to validate if someone _either_ entered a date _or_ checked the _I don't have the date_ checkbox, so both values can't move forward. Right now, if there are values in both, it just passes "I don't have a date"

**Comment by Mottie** [comment]
Ready for validation in staging.

**Comment by Mottie** [comment]
@comaurice will validate today

**Comment by comaurice** [comment]
Remaining validation discoveries to be addressed in #98304
