### ISSUE TITLE
[BE] 10-10EZ - Improvement: Populate the VES Facilities cache when it is empty and a request comes in

### ISSUE THREAD

**Issue by Mitch-A6** [department-of-veterans-affairs/va.gov-team#95160]
## Issue Description
AS A Veteran or Developer applying for health care
I WANT the list of VA Medical Facilities to be maximally up to date
SO THAT I can choose a recently activated facility, and avoid one that is no longer operating.
... without having to wait until 4:30pm on the day a DB spins up for the first time.

The 10-10EZ form relies on the `std_institution_facilities` table to filter Lighthouse's results for a state to the Facilities VES is ready to use. Currently the job to populate this runs daily at 4:30pm, but that means local dev environments and Review Instances need devs to run it manually before they can get through the facility selection page. 

---
## Tasks
- [ ] run the `HCA::StdInstitutionImportJob` when receiving a facilities query if the table is empty.

## Acceptance Criteria
- [ ] When filling out the 10-10EZ form's Insurance Information section (step 5) and selecting your preferred VA medical facility with a fresh DB, choosing a state always populates the `Center or clinic` dropdown's values.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
