### ISSUE TITLE
[CDP] Unit test coverage for /actions

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#95189]
## Issue Description
Update unit tests for `actions` to get coverage to the acceptable 80% range. Currently the **Branches** is below the threshold:
<img width="987" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXRWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12540b1a3923d41fc8c359ce206618f0c310860b/image.png" alt="image.png" />

The following command opens the report above
- `yarn test:coverage-app combined-debt-portal`

This is a follow on after our last staging review: GH-92381. We met acceptable standards for the new feature/release, but this will make for smoother reviews moving forward. 

## Tasks
- [x] Add/update unit tests for actions

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] /actions **Branch** coverage is in the acceptable range

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by amponce** [comment]
| Coverage        | | |
| ------- | ------ | ----- |
|![image](https://github.com/user-attachments/assets/586dab29-d831-4604-a61c-043b35f24656)
| ![image](https://github.com/user-attachments/assets/9a97178e-f2df-4cff-89bb-9e07ea682b74)        |
