### ISSUE TITLE
Copy of [CDP] Unit test coverage for /utils

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#95191]
## Issue Description
Update unit tests for `/utils` to get coverage to the acceptable 80% range. Currently the **Functions** is below the threshold:
<img width="987" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXRWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12540b1a3923d41fc8c359ce206618f0c310860b/image.png" alt="image.png" />

The following command opens the report above
- `yarn test:coverage-app combined-debt-portal`

This is a follow on after our last staging review: GH-92381. We met acceptable standards for the new feature/release, but this will make for smoother reviews moving forward. 

## Tasks
- [ ] Add/update unit tests for utils

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] /utils **Functions** coverage is in the acceptable range

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
