### ISSUE TITLE
HLR | Update confirmation page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#95199]
## Value Statement

**_As a_** Veteran
**_I want to_** see the data I entered on the confirmation page
**_So that_** I can print it out and maintain a record of the submission

---

## Background Context

We'll soon be implementing a change to our Board Appeal form (#94268) to show submitted data on the confirmation page. Soon after, we will need to update our Higher-Level Review from confirmation page

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] Update confirmation page to show submitted data
- [ ] Unit tests & E2E tests added and all passing
- [ ] Maintain 90+% code coverage
- [ ] Flow tested in staging

## Designs and Build Notes

- [Figma](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=1366-17625&node-type=frame&t=01p2ojCL5qsY8fy1-0)

## Open questions

- Add here

## Tasks

- [ ] Update confirmation page to show submitted data
- [ ] Add/update unit tests
- [ ] Add/update E2E tests
- [ ] Add/update mock data

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
Robin working on this and implementing design, possibly ready today

**Comment by dfong-adh** [comment]
PR ready for NOD, HLR PR depends on NOD. SC next after

**Comment by eileen-coforma** [comment]
Waiting on platform. 3 business day lead required for platform review. On day 2.

**Comment by eileen-coforma** [comment]
Has been reviewed. Will be merged after today's production deploy. Is behind a feature flag.

**Comment by Mottie** [comment]
Updates to HLR confirmation page are now available in staging. The feature toggle is fully enabled in staging as well.

**Comment by eileen-coforma** [comment]
@Mottie 

I'm sorry for not catching this earlier, but I forgot to match our success alerts to the one's we established for the Zero Silent Failure format "submission is in progress" etc. 

I've now updated the[ FIGMA designs ](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=1366-17624&m=dev)to reflect this.

**Comment by Mottie** [comment]
Confirmation page success alert update is now available in staging for validation

**Comment by comaurice** [comment]
I can validate this today

**Comment by comaurice** [comment]
## Staging validation (Selected informal conference with rep)

<img width="1015" alt="Image" src="https://github.com/user-attachments/assets/9d23ad39-a676-4eab-8bcb-b157e17acd83" />
The "What to Expect Next" section doesn't directly match Design (shown below).
<img width="805" alt="Image" src="https://github.com/user-attachments/assets/a0f2e49c-a0f6-4370-a93c-9683359e36a8" />

This is also the case when selecting information conference with no rep AND when selecting no informal conference at all. So the "What to Expect Next" section isn't a direct match to Design for all 3 options. 

Everything else looks good 👍

@Mottie

**Comment by comaurice** [comment]
Awaiting PR review

**Comment by Mottie** [comment]
Ready for validation in staging.

**Comment by comaurice** [comment]
Maurice will validate today

**Comment by comaurice** [comment]
Validated. All good @Mottie
