### ISSUE TITLE
[UX/FE] Pre-fill Alert content update

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#95225]
## Issue Description
The content guideline notes that we should not include directional text within the copy/content. As directional language can make the experience difficult for Veterans using screen readers. The blue prefill alert has directional text that would need to be updated.

---- 

#### Benefit to the Veteran
Improve accessible for visually impaired Veterans.

#### Where
This was initiated by CAIA (Aliyah) as they were reviewing EC/NOK mockups.

#### Why
We want to match the form with the latest guidelines.

#### What
- UX to confirm content with CAIA
- Dev to update staging/produciton to match UX mock.

#### References / Resources

- [Figma Link](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=5972-118741&t=cRlI6dQ0HKjZG6XI-1)

---

## Tasks
- [x] UX to coordinate with CAIA for content update
- [x] UX to identity and update all of the relevant mockups
- [x] UX to present to team/Dev
- [x] Dev to confirm prefill alert can be update or has to go through Forms Library.
- [x] If through Forms Library, put in request to change the content.
- [ ] Review / show-and-tell with the entire EZR teams

## Acceptance Criteria
All of the blue prefill alert in the EZR flow has been updated exclude directional text.

---

**Comment by IMHieuVo** [comment]
The following page has the blue prefilled alert:
- [ ] Veteran Info - Mailing Address
- [ ] Household Financial Info - Martial Status
- [ ] Insurance - Medicaid question

Current prefill message: 
_We've prefilled some of your information from your account. If you need to correct anything, you can edit the form fields below._

**Comment by longmd** [comment]
Just noting that all three locations mentioned above share the same platform-based import. I will update that component, so this will be a global change across all applications on VA.gov that utilize this import.

**Comment by longmd** [comment]
Here is Aliyah's note regarding this update:

> Hieu didn't previously share (because he didnt know) that the changes would affect anyone that uses the component. I was only recommending a content update because I thought it was specific to EZR.
> Here's what I'm thinking now:
> I don't want a change that may impact multiple forms right now (i.e the change will update the component for all), let's just leave the prefill component as it is for now. It's [already in the design system](https://design.va.gov/components/form/prefill#step) as is (with "below").
> Using "below" isn't ideal, but I believe the CAIA team is currently doing some prefill work - I can flag that directional language for them.
