### ISSUE TITLE
New Confirmation Page: Non 200 submission status testing

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#95245]
## Issue Description
Handle non 200 (error) scenarios from submission_status. For each of these, we should still display the green success alert since failure notification will come via email. Likely no code changes here, just testing.

Dependent on
- #95237
-  #95241 
## Tasks
- [x] Mock up a non-200 response from vets-api
- [x] Test scenarios for different http codes, as needed

Based on docs [here ](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/getSubmissionStatus)
401 unauthorized
403 forbidden
404 no record found
500 or any other non 200?

mocks: https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/(526ez)-New-Confirmation-Page-and-Email-Touchpoints?node-id=8405-81028

## Acceptance Criteria
- [x] Verify success alert is displayed and yellow alert does not display.

**Comment by aurora-a-k-a-lightning** [comment]
during testing for 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/95241
https://github.com/department-of-veterans-affairs/vets-website/pull/33012

i tested throwing a 500 error:

- frontend polled 3 times
- got 500 internal server error each time
- on the third poll, frontend pushed forward to new confirmation screen with green box, no claim id version (expected)!

**Comment by christinec-fftc** [comment]
Found a similar response as ahay's notes above, testing with 401, 403, 404 and 500 response codes [video](https://github.com/user-attachments/assets/d9319431-b7ce-4a21-b8b7-227895af4c8d)
