### ISSUE TITLE
Payment History showing incorrect information

### ISSUE THREAD

**Issue by jstrothman** [department-of-veterans-affairs/va.gov-team#95240]
## Value Statement
**_As a_** Veteran
**_I want to_** recognize the payments in my payment history
**_So that_** I don't see confusing payments or mistake payments to 3rd parties as intended for me

---
## Background Context
There are 2 problems on the Payments History page:

1. Ch 33 payments to educational institutions are unexpectedly displaying as if they were paid to the Veteran
  - This causes Veterans to think they didn't receive money they should have and call the Contact Center or even incur expenses trying to pursue missing payments
  - It's assumed that issue started in August after BGS release 6 – newly using EMPWR when CH33 came over to CorpDB
2. There are education payments incorrectly displaying as C&P Hardship
  - Hypothesis: Somewhere before display on VA.gov, code 5 is being translated as C&P Hardship which is accurate for some Code 5 payments, but if the program is edu service, we should call it Education Payment or something like that
  - Unknown if this is a new issue

This problem was initially flagged to Chante, and Julie has been on 2 calls with people from BGS (plus others).
We should schedule a call with two people from BGS Team 2 (Julie has contact info) for engineering discovery.

Our Contact Center contact suggests we add a warning message to VA Payment History page to reduce Veteran questions about confusing information

10/23: Julie to provide update to James Meredith and the rest of the people from the calls

## Outcome
- Veterans will no longer see incorrectly categorized payments

## Design
- Draft language to warn about confusing information (will need to discover if we can display only to people viewing the incorrect info or if that will take too long, should we draft language for everyone)

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Add here

## Out of scope
- Deciding whether it's helpful for Veterans to see payments to 3rd parties (educational institutions)

## Open questions
- Add here

## Tasks
- [ ] Identify staging users or other way to duplicate the issue
- [ ] Filter out payments not being made to the veteran
- [ ] Filter out Attorney Fee payments (if those are not included in the bucket above)
- [ ] Rename C&P Hardship payments being made to EDU as "Post-9/11 GI Bill"

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] 3rd party payments for Ch 33 no longer display on Payment History
- [ ] C&P Hardship is no longer shown as a description of Education Payments
- [ ] Alert warning of confusing information is no longer present on the Payment History page

**Comment by CorySohrakoffUSDS** [comment]
Payments README from vets-webiste: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/disability-benefits/view-payments/README.md

**Comment by dysbo** [comment]
@iandonovan reached out via email this week with follow up questions; we will update when we get a response and are able to refine this effort further.

**Comment by iandonovan** [comment]
@jstrothman @amylai-va 

I've just watched the recording of our meeting and I have written the following notes:

```
Usually Chapter 33 is for school-related disbursements. Tuition & Fees is sent to the school (and is erroneously shown to the veteran) but things like books or housing is sent to (and displayed to on the Payment History page) the veteran.

[meeting member, redacted] recommends looking at the **recipient** data and excluding items that are not sent to the veteran. An example would be a payment sent to the veteran's child.

There are Chapter 33 payments that are not sent to the veteran. The way to determine this is to look at the recipient information and then exclude the ones sent to anybody other than the veteran.

I think currently we display all the Chapter 33 payments under the supposition that the user will read the descriptions, but it can be confusing to surface these items at all.

It appears we are currently displaying Attorney Fee payments, too, for example. We may want to hide these (using recipient data).
```

Some of the things discussed in the meeting (e.g. Attorney Fee payments) aren't explicitly mentioned in this ticket, but we floated the idea of suppressing or removing those items anyway. I walked away from the meeting with a sense that we perhaps wanted to alter the Payment History page to not show **any** payments that are disbursed to anyone other than the veteran looking at the page, not only the Ch33 or incorrectly-labeled-as-Hardship ones. I think that solution is elegant, but it's a bit wider-ranging than the initial proposal. What are your thoughts?

**Comment by jstrothman** [comment]
@iandonovan Andrew provided responses from VBA Office of Administrative Review, and they've requested a conversation. Andrew is looking for a time to schedule this week.

I'll forward the email to you in case you can be prepared to identify the 3rd party payments we understand are being shown to Veterans.

In the meantime, we have confirmation to: Suppress display of Attorney Fees

**Comment by iandonovan** [comment]
Moving this ticket to Closed but opening a new one for testing, as testing appears to be quite involved.
