### ISSUE TITLE
UX | "Now" prototype - refine Visual design of prototype

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#95309]
## Description
Post review with Matt, it was commented that we need to more closely align the UI of the Form Builder to the visual design of the design system. 

Specifically: 

- Review point/pixel size and align to the minimum 16.96 size for smallest content.  Ok to adjust larger as necessary.
- Create more separation for added steps in the layout tab
- Button is for action, link is for navigating, so recommendation is to change 'Back' to a link and move to top of the section to act as a breadcrumb
- Check contrast ratio on grey text, ideally aim for AAA compliance

## Tasks 
- [x] Create new page within working figma file to indicate this revision
- [x] Make adjustments as asked for
- [x] Review with SME and PO
- [ ] Apply to Pattern Matrix if appropriate

## Acceptance Criteria
- [x] Feedback implemented in (link: [Figma file](https://www.figma.com/design/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?node-id=2005-15225&t=kwWR4duC9zzeFHAN-1))
- [x] Team has reviewed and discussed item (link: recording)

**Comment by brian-wilke** [comment]
Decided against trying to version or rebuild components from scratch. 
For expediency, a new (from duplicate) file was initiated in order to keep the work separate. 

This file is located [here.](https://www.figma.com/design/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?node-id=2005-15225)

**Comment by brian-wilke** [comment]
Changes made:

- Updated all colors to pull from the VADS
- Updated all text styling to pull from the VADS
- showed alternate pattern for layout tab (needs further refinement)
- Assumed we will use pattern for Respondents, refining information collection order options

Will share updates out at Fallout Friday.

**Comment by brian-wilke** [comment]
Still need to relink connections to make prototype function

**Comment by brian-wilke** [comment]
Prototype has been rebuilt and re-linked to reflect the VADS as well as most recent alignments on who  can use the form generated by this process. 

[Flow](https://www.figma.com/proto/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?page-id=2005%3A15225&node-id=2263-31760&node-type=canvas&viewport=50688%2C-221%2C0.8&t=MFrwjCtv12mo3vHs-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2263%3A31760&show-proto-sidebar=1) for end to end (at this time)

[Flow for adding a single step](https://www.figma.com/proto/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?page-id=2005%3A15225&node-id=2318-62102&node-type=canvas&viewport=50688%2C-221%2C0.8&t=MFrwjCtv12mo3vHs-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2318%3A62102&show-proto-sidebar=1)

[Flow for adding multiple steps](https://www.figma.com/proto/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?page-id=2005%3A15225&node-id=2617-23791&node-type=canvas&viewport=50688%2C-221%2C0.8&t=MFrwjCtv12mo3vHs-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2617%3A23791&show-proto-sidebar=1)

[Review page with a single step added](https://www.figma.com/proto/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?page-id=2005%3A15225&node-id=4081-41517&node-type=canvas&viewport=50688%2C-221%2C0.8&t=MFrwjCtv12mo3vHs-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4081%3A41517&show-proto-sidebar=1)

[Review page with multiple steps added (in line)](https://www.figma.com/proto/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?page-id=2005%3A15225&node-id=4065-35436&node-type=canvas&viewport=50688%2C-221%2C0.8&t=MFrwjCtv12mo3vHs-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4065%3A35436&show-proto-sidebar=1)

[Review page with multiple steps on additional page](https://www.figma.com/proto/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?page-id=2005%3A15225&node-id=4081-43586&node-type=canvas&viewport=50688%2C-221%2C0.8&t=MFrwjCtv12mo3vHs-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4081%3A43586&show-proto-sidebar=1)
