### ISSUE TITLE
[BE] 10-10CG - Notifications: Add logging for resolved failures

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#95342]
## Benefit to the Veteran
As a Veteran, I want to be confident that the VA is monitoring failures, so that issues can be resolved quickly with little to no impact to Veterans.

## Scope
- As part of the Zero Silent Failures and Collab Cycle QA Standards, we are required to add logging for Resolved Failures (when the failure is made known to the Veteran).  
     - **NOTE** The 10-10CG form does not have silent failures outside of the known VA Notify email failure callback.  This callback mechanism is in progress with VA Notify and will be implemented when ready for teams to use.  Therefore, our team will implement the "Resolved Failures" logging process.

## Resources
- [Logging Silent Failures document with details](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md)
      - Be sure to use the "future" guidance
> In future, teams will be notified when VA Notify has a call back mechanism to determine if an email reached the intended recipient. At that time, teams should use the following log message:
>
>`tags = ['service:veteran-facing-forms', 'function: form submission to Lighthouse']
>StatsD.increment('silent_failure_avoided', tags:)`

- [Zero Silent Failures guidance folder](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/platform/practices/zero-silent-failures)
- [10-10CG Zero Silent Failures checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10CG%20Form/Endpoint%20Monitoring%20%26%20Zero%20Silent%20Failures/10-10CG%20Zero%20Silent%20Failures%20checklist.md)

## Tasks
- [x] Review the Logging [Silent Failures document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md)
- [x] Add the required logging for [Resolved Failures](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md#logging-resolved-failures) on the Form Submission failure code
- [x] Complete testing to ensure the logging is being captured as expected
- [x] Review with PM/team
     - Signoff is required prior to launch
- [x] PM to add these details to the [Zero Silent Failure document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/Endpoint%20Monitoring%20%26%20Zero%20Silent%20Failures/10-10EZ%20Zero%20Silent%20Failures%20checklist.md)
- [x] Launch to production

---
## Acceptance Criteria/Definition of Done
-  Resolved failures for the 10-10CG are being logged

---

## How to configure this issue
- [x] **Labeled with Team** (`1010-team`)
- [ ] **Labeled with Form** (`1010-ez`, `1010-ezr`, `1010-cg`)
- [ ] **Labeled with Feature** (`facilities-cg`, `registration`,  `toxic-exposure`, etc.)
- [ ] **Labeled with Discipline** (`backend`, `frontend`,  `design`, `QA`, `research`, etc.)
- [ ] **Project selected** (`1010 Health Apps team`)
- [ ] **Epic Reationship (parent) identified**

**Comment by hdjustice** [comment]
Ticket not required - There is an agreed-upon process in place between the 10-10 Health Apps team and the CG Stakeholder team.  the CG team manages the automatic emails with VA notify themselves, and when there is a failure on their side after submission, the CG team contacts the user. If there is a failure on our side before it reaches the downstream systems, we send the contact info directly to the CG team and they contact the user.

**Comment by allanto-ah** [comment]
QA comment: Spoke with Brandon and we are not sure how to get VANotify to fail on purpose. As this is also adding logging, no additional QA is needed outside of ensuring that nothing broke with the change. Regression has been completed and E2E was done with CARMA as well

**Comment by allanto-ah** [comment]
@hdjustice when you have a chance, can you please review? Thank you!

**Comment by hdjustice** [comment]
As long as we followed the process outlined for us from VA Notify team, then we should be fine.  If we do get a failure in the future, we will be extra diligent in checking to make sure it was logged appropriately as [Silent Failure avoided (email verified)](https://vagov.ddog-gov.com/dashboard/n6c-twn-swr/silent-failure-tracker?fromUser=false&refresh_mode=sliding&from_ts=1735592853025&to_ts=1736197653025&live=true) in the DD Silent Failures monitor as well as watching for our own [monitor](https://vagov.ddog-gov.com/monitors/306837) for emails failing

**Comment by hdjustice** [comment]
Moving ticket to BLOCKED

> for the vanotify callbacks, after talking with Nathan Wright on the vanotify team we discovered that since our emails are in their own service and not the general vets-api service, the current default callbacks don't work with them. It's something they are working on, but they had not done it yet just so they could get the basic functionality out first. He was able to enable it for us in staging, so we are able to successfully test it and the monitors, but I don't think we want to turn it on in production just yet. We currently still increment the required zsf metric that it could have failed, so we are still in compliance.

**Comment by coope93** [comment]
@hdjustice talked with VANotify and they said we should have the functionality we need to turn this on either next week or hopefully no later than the week after next.

**Comment by hdjustice** [comment]
ok, i will sched for next sprint.  If there is time to work on this before then, that is fine.

**Comment by coope93** [comment]
I turned this feature on this morning. These are very rare so I wouldn't expect to even see any soon, but we will keep an eye on it for a little bit before we remove the flipper logic.

**Comment by coope93** [comment]
Flipper toggle `caregiver_use_va_notify_on_submission_failure` was removed from the `features.yml`and all environment databases.
