### ISSUE TITLE
[BE] 10-10EZ - Notifications: Add logging for resolved failures

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#95343]
## Benefit to the Veteran
As a Veteran, I want to be confident that the VA is monitoring failures, so that issues can be resolved quickly with little to no impact to Veterans.

## Scope
- As part of the Zero Silent Failures and Collab Cycle QA Standards, we are required to add logging for Resolved Failures (when the failure is made known to the Veteran).  
     - **NOTE** The 10-10EZ form does not have silent failures outside of the known VA Notify email failure callback.  This callback mechanism is in progress with VA Notify and will be implemented when ready for teams to use.  Therefore, our team will implement the "Resolved Failures" logging process.

## Resources
- [Logging Silent Failures document with details](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md)
- [Zero Silent Failures guidance folder](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/platform/practices/zero-silent-failures)
- [10-10EZ Zero Silent Failures checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/Endpoint%20Monitoring%20%26%20Zero%20Silent%20Failures/10-10EZ%20Zero%20Silent%20Failures%20checklist.md)

## Tasks
- [x] Review the Logging [Silent Failures document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md)
- [x] Add the required logging for [Resolved Failures](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md#logging-resolved-failures) on the Form Submission failure code
- [x] Complete testing to ensure the logging is being captured as expected
- [x] Review with PM/team
     - Signoff is required prior to launch
- [x] PM to add these details to the [Zero Silent Failure document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/Endpoint%20Monitoring%20%26%20Zero%20Silent%20Failures/10-10EZ%20Zero%20Silent%20Failures%20checklist.md)
- [ ] Launch to production

---
## Acceptance Criteria/Definition of Done
-  Resolved failures for the 10-10EZ are being logged

---

## How to configure this issue
- [x] **Labeled with Team** (`1010-team`)
- [x] **Labeled with Form** (`1010-ez`, `1010-ezr`, `1010-cg`)
- [x] **Labeled with Feature** (`facilities-cg`, `registration`,  `toxic-exposure`, etc.)
- [x] **Labeled with Discipline** (`backend`, `frontend`,  `design`, `QA`, `research`, etc.)
- [x] **Project selected** (`1010 Health Apps team`)
- [x] **Epic Reationship (parent) identified**

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the metrics in datadog are incrementing as expected

![Image](https://github.com/user-attachments/assets/cbac75b4-408a-49ea-82c2-1eb784b97037)

**Comment by allanto-ah** [comment]
@hdjustice when you get a chance, please review! thank you!

**Comment by hdjustice** [comment]
Reviewed [Datadog tracker](https://vagov.ddog-gov.com/dashboard/n6c-twn-swr/silent-failure-tracker?fromUser=false&refresh_mode=sliding&tpl_var_env%5B0%5D=eks-prod&from_ts=1729187697952&to_ts=1729792497952&live=true) and testing results are appearing on the tracker as expected.  
Link to DD tracker added to the [ZSF checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/Endpoint%20Monitoring%20&%20Zero%20Silent%20Failures/10-10EZ%20Zero%20Silent%20Failures%20checklist.md#monitoring)
