### ISSUE TITLE
CypressViewportUpdater::UpdateCypressViewportsJob

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#95353]
Not veteran-facing. This was added by a former Platform member in https://github.com/department-of-veterans-affairs/vets-api/pull/5846 in 2021. It seems like it's owned by Platform. This job, "Updates Cypress files in vets-website with data from Google Analytics." Cypress is a JavaScript testing framework. I don't see any error handling, so there could be silent failures, but there's no veteran impact. I do see this in the dead queue with the error: `OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key`.
This job is periodically ran every day.
[Readme](https://github.com/department-of-veterans-affairs/vets-api/tree/master/app/sidekiq/cypress_viewport_updater)
 
## User Story
As a Platform engineer, I want to determine the usefulness and reliability of the `UpdateCypressViewportsJob`, so that errors are handled properly, and the job does not silently fail or end up in the dead queue.

## Issue Description
This ticket came out of the Zero Silent Failure initiative. There are most likely silent failures, but this is not veteran-facing, so it doesn't fit the criteria to be an urgent fix. However, we do need to determine whether this job is still useful and if so, fix it up so the errors are handled and the job doesn't end up in [Sidekiq's dead queue](https://api.va.gov/sidekiq/filter/dead). 

## Tasks
- [x] Understand the `UpdateCypressViewportsJob`.
  - [x] What does the job do?
  - [x] Is the job still needed?
  - [x] Does the job need exception handling added?
  - [x] Any other modifications needed?

- [x] If it still provides a useful function, add error handling. 
- [x] Run the job to make sure it doesn't end up in the dead queue. 

## Success Metrics
Error handling exists and failures aren't silent.

## Acceptance Criteria
- [x] Error handling exists, is tested and validated. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by RachalCassity** [comment]
Pull request data: https://github.com/department-of-veterans-affairs/vets-api/pull/5848
