### ISSUE TITLE
[BE] 10-10CG - Notifications: Implement VA Notify for CG submission failure emails in Staging

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#95356]
## Benefit to the Veteran
As a Veteran/Caregiver, I want to be immediately notified when my application submission has failed, so that I can take whatever actions are advised to complete a successful submission

## Background
As part of the Submission failure notification emails creation with VA Notify, we need to implement the API keys provided by the VA Notify team for the Staging environment, so we can test submission failures to trigger the new notification process.

Implementing [Delivery Service Callbacks status](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify#delivery-status-callbacks) will be a future iteration once the VA Notify team has completed their effort.

### Resources
- [Figma Design file](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=3520-7715&node-type=section&t=e73I3Y5hjZTGMONp-0)

## Tasks
- [x] Update 10-10CG to send an email to the Veteran email from the form data through VA Notify when the sidekiq job has run out of retries
- [x] Utilize flipper toggle to allow for staging testing
- [x] Add Staging API (received from VA Notify to VA emails) to notification trigger code
     - Do not deploy to production until this is fully tested
- [x] Turn flipper toggle on in staging

## Acceptance Criteria
- API keys provided by VA Notify for the Staging environment have been implemented

**Comment by coope93** [comment]
@allanto-ah This will require a sidekiq job running out of retries (currently 16 retries so a little less than 3 days) that also has an email address set in the form for the Veteran. I forget if we have a good way to have this fail without directly calling the job, since most failure cases are caught in our initial validation before running the job. We may need to manually create a job that fails from the command line. I can pair with you if you want to see about how to get one to fail.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the VANotify failure submission email is sent as expected. 

![Image](https://github.com/user-attachments/assets/5b1ab379-775c-4bef-831e-0a810d8cbf92)

### Note: There is a slight content mismatch from staging and Figma, but there will be more content changes and the work will be done in a separate ticket which will also address this mismatch
![Image](https://github.com/user-attachments/assets/e35d0a9b-1ef8-49e5-b060-f612c234d268)

**Comment by allanto-ah** [comment]
Moved one of the task to it's own ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/97745. Closing this ticket
