### ISSUE TITLE
[PM, BE] 10-10CG - Notifications: Create Production template and update config values

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#95361]
## Benefit to the Veteran
As a Veteran/Caregiver, I want to be immediately notified when my application submission has failed or post-submission validation error, so that I can take whatever actions are advised to complete a successful submission

## Background
As part of the Submission failure notification emails creation with VA Notify, we need to create production email based on staging email template and set up for production keys.

For reference, you follow [these directions](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-Stepstocreateanewsecretvalue:) to connect the aws parameter store values with the settings.yml file. This branch must be deployed _after_ we have added the production values in aws parameter store. 

### Resources
- [Figma Design file](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=3520-7715&node-type=section&t=e73I3Y5hjZTGMONp-0)

## Tasks
- [x] In VANotify create production email based on staging email template.
- [x] Work with platform to set aws parameter store for production api_key and template_id
- [x] Deploy branch with updated configs

## Acceptance Criteria
- The production template is ready for use in VA Notify
- Note: this email will be triggered by a submission failure or a post-submission validation error that also results in a submission failure.

**Comment by hdjustice** [comment]
This is in production

**Comment by coope93** [comment]
Validated the new template id was present, sent a test email to confirm the template, and turned the flipper back on in production.
