### ISSUE TITLE
Log silent failures [SILENT ERRORS] Add mandated metrics

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#95376]
## Description

[Octo has mandated a convention to log silent errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md). We need to add this to our system to get within guidelines

Link to slack announcement:
https://dsva.slack.com/archives/CPE4AJ6Q0/p1729114032588019

## Tasks
- [ ] Add OCTO mandated tagging for silent errors

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] Tagging meets OCTO criteria

## Testing
- [x] N/A if non development work

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
