### ISSUE TITLE
Review & Update Best Bets/Top Recommendations

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#9538]
## Issue Description
The Top Recommendations which appear at the top of VA.gov search results for most popular keywords -- and is powered by Search.gov (e.g. Best Bets) -- have been loosely maintained managed since the launch of VA.gov in 2018.   As they are an important component of our on-site search experience, the content strategy team needs to take a fresh look at the entire collection of 200+ recommendations to implement needed updates and enhancements, reflecting the latest keyword trends and VA.gov's up-to-date content priorities.

## Screenshot for Reference

<img width="856" alt="Screen Shot 2020-05-27 at 1 52 09 PM" src="https://user-images.githubusercontent.com/63107147/83055516-f1d73800-a021-11ea-8a60-7a74a2fea948.png">

---
## Tasks
- [x] Obtain from Search.gov a spreadsheet version download of all current VA.gov Top Recommendations (assigned to @johnhashva -- expected next week)
- [ ] Review the spreadsheet with @DanielleThierryUSDSVA along with an updated list of the 1000 VA.gov most popular search terms (assigned to @johnhashva)
- [ ] Work with content team to update and refine the Top Recommendations -- example of an issue here https://github.com/department-of-veterans-affairs/va.gov-team/issues/9454 (assigned to @Danielle)
- [ ] Batch upload the new Top Recommendations via Search.gov content management system (assigned to @johnhashva)
- [ ] Determine with Search.gov if there is a less manual approach to Top Recommendations  -- for example, by leveraging the VA.gov metadata/site map and potentially implementing a flag in the CMS to allow editors to indicate selections (assigned to @johnhashva)

## Acceptance Criteria
- [ ] The updated Top Recommendations are reflected in VA.gov search results
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnhashva** [comment]
Updated ticket to reflect the delivery from Search.gov of the VA.gov Best Bets/Top Recommendations Excel.  @DanielleThierryUSDSVA and @bethpotts will review and determine updates -- which we may submit as an batch upload.

**Comment by stephorkandatx** [comment]
@johnhashva is there a spreadsheet attached to this ticket?

**Comment by johnhashva** [comment]
VA.gov Best Bets batch export from June 2020.
[1474_va_best_bets.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4754190/1474_va_best_bets.xlsx)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @johnhashva. I'm in the process of reviewing this. Don't have an ETA yet, but will keep you posted.

**2 related notes:**

- For non-VA search results titles (ie, Google et al), we use title casing. But for Best Bets, since it's on VA.gov, I recommend that we go with sentence casing to align with our style guide. So I'll make those updates as well as I go.
- I know we also need to talk about how Best Best recommendations get updated/maintained in terms of team member roles and capacity planning. I'm out for a few days next week, but would love to chat with you and @bethpottsVADEPO later in the week about that. If that makes sense to you, feel free to add time to our calendars or I can look for times. Thanks!

Thanks!
Danielle

**Comment by DanielleThierryUSDSVA** [comment]
Hi again, @johnhashva! 

I know we're talking about updating these as a batch, but I thought it might be helpful if I upload versions as I go in case you have the bandwidth and want to update some in the meantime.

I noticed that line 26 "beneficiary travel" was going to the legacy page rather than our modernized page. So that may be one to update sooner than later.

Thanks!
[1474_va_best_bets_WIP DT review_8.4.20.xlsb](https://app.zenhub.com/files/133843125/aa9c781b-6af9-4d83-924f-f87ab7f9b5e1/download)

**Comment by johnhashva** [comment]
Hi @DanielleThierryUSDSVA -- just changed the Best Bets URL for beneficiary travel to https://www.va.gov/health-care/get-reimbursed-for-travel-pay/.  LMK if I missed anything.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @johnhashva!

@MickinSahni For sprint planning - I'm going to continue working on this next sprint. Thanks!

**Comment by MickinSahni** [comment]
> Thank you, @johnhashva!
> 
> @MickinSahni For sprint planning - I'm going to continue working on this next sprint. Thanks!

Thanks, Danielle. Hey @johnhashva. This seems like it has potential to majorly impact search analytics, no? Not sure how far out the batch upload is but we should prioritize click-through analytics. Something to add to the search discovery chat.

**Comment by johnhashva** [comment]
We have indeed prioritized click-through analytics -- but dependent on Search.gov to complete development/testing of that new capability for API clients.   Latest word on that: the final round of work on that has been delayed, repeatedly, by security-related and now Type-Ahead issue resolution.

**Comment by MickinSahni** [comment]
> We have indeed prioritized click-through analytics -- but dependent on Search.gov to complete development/testing of that new capability for API clients. Latest word on that: the final round of work on that has been delayed, repeatedly, by security-related and now Type-Ahead issue resolution.

Hmm that sucks. Wonder if we move on and ask the Analytics team to give us a table that let's us calculate it ourselves on the dashboard we're asking them to create.

**Comment by johnhashva** [comment]
Good idea!  Let me get my ducks in a row for a research/analytics "spike" for Search, based on the Top Questions doc I've created.    I will schedule a walk-through of that doc with you first so we can weave your thinking/value framework components into the overall ask.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @johnhashva. Catching up from being out for a few days, and I think I saw in slack that we're deprioritizing this content review for now. Can you confirm? If yes, I'll move to icebox. Thanks!

**Comment by johnhashva** [comment]
That is correct.

**Comment by johnhashva** [comment]
As we "restart" this fresh assess of Best Bets/Top Recos, a few strategic questions/consideration to address:

First, two "constraints":
- As it stands, the Search.gov feature only allows you to link to a distinct URL once.  You can't have multiple Best Bets for the same page.  
- Second, there's a limit of only two Best Bets displayed.  So, for a popular keyword such as "burials" or "cemeteries" -- where we may want to promote three different pages (e.g. add "Find a burial site") -- we will have to prioritize. 

<img width="529" alt="Screen Shot 2020-10-28 at 10 35 22 AM" src="https://user-images.githubusercontent.com/63107147/97452624-4f421e80-190b-11eb-8dd6-102fc917957a.png">
 

 Search.gov's recommendation to get around this is to create a graphics Best Bet.  More here: search.gov/manual/best-bets.html

+ Question for Search.gov: If we have three Best Bets pointing to different pages but containing the keywords "cemeteries" and "burials" -- is it possible that any combination of the three will display based on relevance?  

**Strategic considerations for VA.gov:**

- With a limit of 350, what gets the priority for “promotion”? 
- What criteria is used to weigh effectiveness (click thru data)— so that we can continue to optimize or replace?
- Who is responsible (Product or Content Strategy) for owning?

**Comment by DanielleThierryUSDSVA** [comment]
These are great questions and constraints to discuss, @johnhashva. Thank you. Would love to discuss further soon.
