### ISSUE TITLE
Review exception handling for Platform-owned Sidekiq jobs [Part 1 of 2]

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#95476]
## User Story
As a platform backend dev, I want to know that all of the Sidekiq jobs we own are functioning properly, so that the Platform is stable.

## Issue Description
As a follow-up to the review of Sidekiq jobs done in https://github.com/department-of-veterans-affairs/va.gov-team/issues/94632, we need to go a little deeper into the low-priority jobs to review them for error handling. Use the [sidekiq-exception-handling-review board](https://github.com/orgs/department-of-veterans-affairs/projects/1166/views/1?filterQuery=owner-%28team%29%3APlatform) (filtered by `owner-(team):Platform`) and go through the jobs labeled `Low` and review the four listed in the Tasks section for the following:
1. What does the job do?
2. Is the job still needed?
3. Answer the questions in the "Draft" for each job (where applicable).
4. Does the job need exception handling added?
5. Any other modifications needed?

Add findings to the Draft for each job and then move each into the "Assessment Review Complete" column. For any that need work done, click "Convert to issue" on the Draft and add our team label.

## Tasks
- [x] Review the exception handling and answer the questions listed above in the Draft for each of the platform-owned jobs:
    - [x] ExportBreakerStatus
    - [x] ExternalServicesStatusJob
    - [x] FeatureCleanerJob
    - [x] PagerDuty::CacheGlobalDowntime
- [x] Convert to issue any that need more work done.

## Success Metrics
Platform-owned Sidekiq jobs are audited for necessity and error handling. Tickets are created for future work.

## Acceptance Criteria
- [x] The four jobs listed above have been reviewed and filled out in the [Sidekiq board](https://github.com/orgs/department-of-veterans-affairs/projects/1166/views/1?filterQuery=owner-%28team%29%3APlatform+).
- [x] Any that need more work are converted to Issues.
- [x] Any that don't need more work are moved to the "Action Items/Review Completed" column. 
---

## Validation
- [x] Check [Sidekiq board](https://github.com/orgs/department-of-veterans-affairs/projects/1166/views/1?filterQuery=owner-%28team%29%3APlatform+) and review the three issues in "Action Items/Review Completed" column.

**Comment by AshleyGuerrant** [comment]
**Standup note**: Breaking this ticket up into 2 tickets, with 4 classes per ticket.

**Comment by rmtolmach** [comment]
Progress so far: 
- [FeatureCleanerJob](https://github.com/orgs/department-of-veterans-affairs/projects/1166/views/1?filterQuery=owner-%28team%29%3APlatform&pane=issue&itemId=50745041) done. **Action needed: none for now.** This job doesn't run. Some day if/when we ever want to spend time investigating the bug that makes this job a liability, we can make a ticket to re-vamp it. 
- [PagerDuty::CacheGlobalDowntime](https://github.com/orgs/department-of-veterans-affairs/projects/1166/views/1?filterQuery=owner-%28team%29%3APlatform&pane=issue&itemId=50745162). **Still investigating** whether the job is needed anymore. I think there will be a small amount of work that will come out of the investigation. 
- [ExternalServicesStatusJob](https://github.com/orgs/department-of-veterans-affairs/projects/1166/views/1?filterQuery=owner-%28team%29%3APlatform&pane=issue&itemId=50674383). **In progress.** This was all part of an external service status page which no longer exists (AFAIK. Will need to confirm). If that's the case, I'll convert the draft to a ticket to rip it all out! tbd, though.

**Comment by rmtolmach** [comment]
I merged https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3309 as a small fix to an error I found while working on`CacheGlobalDowntime`.

**Comment by rmtolmach** [comment]
✅ converted [ExternalServicesStatusJob](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99307) to an issue. It needs some error handling. 

Moving on to the last one! `ExportBreakerStatus`

**Comment by rmtolmach** [comment]
✅ Converted [ExportBreakerStatus](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99419) to an issue. It needs some more investigation and a few modifications.

Moving to In Review

**Comment by LindseySaari** [comment]
Follow up ticket looks great!

**Comment by LindseySaari** [comment]
Reviewed the board and ✔
