### ISSUE TITLE
Data Ingestions pipeline for Tier I data 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#95488]
## Issue Description
Create or update the ETL pipeline to ingest Tier 1 data from its source system into the Domo environment.
---
## Tasks
- [x] Apply necessary transformations to the raw Tier 1 data to match the Domo schema and format.
- [x] Modify the existing dashboard layout to incorporate the new Tier 1 data views, charts, and visualizations.
- [x] Work with stakeholders to define key metrics and performance indicators to be visualized on the dashboard for Tier 1 data.
- [x] Conduct user testing with stakeholders to ensure the Tier 1 data meets their needs and the dashboard is user-friendly.
- [x] Based on user testing feedback, make final adjustments to the dashboard, ensuring that it delivers business value and meets user expectations.
- [x] Establish automated data quality checks to ensure the integrity of the Tier 1 data.

## Acceptance Criteria
- [x] Tier 1 data is successfully pulled from the source system into Domo.
- [x] Successful integration of Tier 1 data into Domo with no performance issues.
- [x] Tier 1 data is successfully pulled from the source system into Domo.
- [x] Tier 1 data is displayed on the dashboard in an organized and clear format.
- [x] Charts for Tier 1 metrics are aligned with the overall design of the existing dashboard.
- [x] Timely ingestion and transformation of Tier 1 data with accurate reporting.
- [x] Data quality maintained with no unresolved issues related to Tier 1 data.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by newworld2616** [comment]
- Salesforce report was created. for Tier 1.

- Analyzing the Tier 1 data.

- Next steps are pending.

**Comment by ATMiddleton** [comment]
All data is visible - the rest of the team will review and provide feedback. 

@newworld2616 met with @UXCamG  and @UXCamG will provide feedback on aesthetics.

**Comment by ATMiddleton** [comment]
@UXCamG approved aesthetics.

**Comment by ATMiddleton** [comment]
DOMO dashboard been updated with Tier I data and is functioning properly.
