### ISSUE TITLE
Add FAQ for how to close Collab Cycle Request tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#95491]
## User Story
As a Governance team member supporting Collab Cycle, I want to create a new FAQ so that VFS team can understand how to close their Collab Cycle Request tickets.

Assignee: @briandeconinck 
Peer Reviewer: @KKitagawa-Bosch 

## Description
Several PMs have asked recently if they're able to close the Collaboration Cycle Request ticket after they've completed Staging Review, even if they still have unresolved findings tickets. The purpose of this ticket is to create a FAQ for the Platform Website so that we can provide proper guidance to VFS teams.

### Live pages
- [FAQs](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/faqs)

### Drafted pages
- [Draft FAQs](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3577053186/95491+-+FAQs)

## Tasks
- [x] Sync with Shira, if needed, to get her perspective on when a ticket can be closed
- [x] Create a draft question and draft response
   - Re-wrote existing question/response about feedback and findings tickets
- [x] Share with your peer reviewer for feedback.
- [x] Once aligned, share with Shira for feedback.
- [x] After approved, publish new question to FAQs page on PW

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have added a new FAQ to the FAQS page on Platform Website that answers when a Collaboration Cycle Request ticket can be closed.

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@KKitagawa-Bosch This is ready for review!

[Draft FAQs](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3577053186/95491+-+FAQs)

Shira and I chatted about this yesterday and I proposed re-writing the existing question about when to close feedback/findings tickets as a combined question about all CC tickets. I attempted that in my draft, but if you think it works better as two separate questions I think we could split it up fairly easily. But please check what I have against what's live on Platform website to make sure I didn't meaningfully change the feedback/findings part in my rewrite.

**Comment by KKitagawa-Bosch** [comment]
@briandeconinck looks really good to me! I think combining them is a really good idea and it works as is 

Added one comment, but overall I think it's very close

**Comment by briandeconinck** [comment]
@KKitagawa-Bosch Made an edit --- let me know if that looks good.

@shiragoodman Per the task list, I think this is ready for you to review!

**Comment by KKitagawa-Bosch** [comment]
@briandeconinck looks good!

**Comment by shiragoodman** [comment]
@briandeconinck @KKitagawa-Bosch looks it over and no questions! New combined FAQ works for me. ty!

**Comment by briandeconinck** [comment]
Changes are queued up for Platform website. Looks like I missed the publishing cutoff by about 30 minutes, so the update will be published while I'm out of office. @KKitagawa-Bosch and @shiragoodman can I hand off to you for closing this out for end of sprint?

**Comment by shiragoodman** [comment]
Validated that the page has been published to Platform Website. Closing!
