### ISSUE TITLE
[Design] Update Drupal Intro Page

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#9550]
## Issue Description
_As a veteran I would like to clearly understand where to click to order supplies. Usability study findings revealed that the design of the button to order supplies is not clear to the veterans 

---
## Tasks
- [ ] _Update design in Drupal intro page _
- [ ] _Provide new design to Selena
## Acceptance Criteria
- [ ] _Design reflects usability findings _
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by leahkeeler** [comment]
Duplicate - closing
