### ISSUE TITLE
[Discovery] Convert In Progress BDD form to 526 form

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#9551]
## Issue Description
Recent changes to fix an in progress bug and other small BDD related things (#9416) has resulted in the BDD and 526 forms to now have different form IDs. These form IDs are used in multiple places in the front end, but one of the primary ways they are used is for determining if a user already has an in progress form.

For BDD, users can only fill out the form if they are 180-90 days from separation. In one scenario, a user could begin the BDD form at the appropriate time, not finish/submit the form, and then return to apply for disability benefits less than 90 days from separation or even after separation. In this case, users should fill out the 526 form, so we would ideally allow the user to continue the 526 form as if it were "in progress" by pulling the information from the BDD form.

Originally, when the forms shared IDs, this process of resuming the BDD form inside of 526 happened automatically. However, the form IDs need to be different in order to handle many other situations, so this automatic functionality is lost. Now, when attempting to fill out the 526 form after beginning the BDD form, the user will have to start from the beginning.

From my limited research into the in progress functionality and after briefly discussing the situation with Robin, it does seem that modifying the in progress functionality should be possible to allow users to resume the BDD form inside of the 526 flow. That being said, there are trade-offs and side effects to be aware of in addition to possible solutions that involve the back end making changes, which is why this ticket is marked for discovery instead of development.

The most apparent trade-off is that even when the data is pulled from the in progress BDD form, we would still need the user to start from the beginning of 526 because the 526 form contains additional and different fields that the user will need to verify have the correct information. It may ultimately make more sense to have the user start from scratch.

There should also be discussion about how this data should be converted to a 526 in progress form. Should it happen when we make a request for in progress 526 forms (and none are returned)? Should it happen automatically after the user is less than 90 days from separation? And a sort of spin-off question: do we need to gate the user from BDD using the back end services array after the BDD form has been converted to a 526 form? We wouldn't want users to accidentally begin a BDD form after their data has been converted to 526.

---
## Tasks
- [ ] Discuss options/side-effects of converting an in progress BDD form to a 526 form

## Acceptance Criteria
- [ ] Determined direction to take regarding converting in progress BDD forms to 526 forms
- [ ] Appropriate spin-off development tickets are created (if necessary)

**Comment by ndsprinkle** [comment]
After meeting with the engineers, this is our solution:
- As originally planned as a long term goal, we will combine forms 526 and BDD in to a single form
- This eliminates the need to convert one form to another as the 526 form will now conditionally show steps based on separation date
- This solution will require virtually no back end work, but if all goes well then the back end code for BDD can be removed
- There will be several smaller tickets created to handle small tweaks that will be necessary for the combination of the forms
- There will be one main ticket that is created to handle the moving of all BDD components to 526 and the addition of conditions to show/not show the BDD components
- A cleanup ticket will also be created to remove all existing separation BDD form code and URLs when testing of the new form flow is complete

Once all necessary tickets are created, I will comment them below.

The main reason for this decision is that it will actually require the same or less work than designing and engineering a solution that would convert the BDD form to 526 and convey that conversion to the user. With the solution above, there will be no conversion necessary and the user will be able to continue the exact same for no matter when their separation date is.

**Comment by ndsprinkle** [comment]
Tickets created: #11182 #11183 #11184 #11185 #11186 #11187 #11188 #11189 #11190
