### ISSUE TITLE
Screenreader users can miss instructions when focus moves to Review accordion input

### ISSUE THREAD

**Issue by bacitracin** [department-of-veterans-affairs/va.gov-team#95528]
## Issue Description
This issue was identified in the [accessibility audit of the review & confirmation pages ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94614)of the 526 form.

Since focus goes to the input when Editing areas, in some sections of the accordion lengthy instructions are skipped & the user has to backtrack to read them. Maybe we could put an `aria-describedby` on the inputs so that they are associated/read out the instructions? The instructions are quite long unfortunately.

[**Expected severity**](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-defect-severity-rubric): a11y-defect-1
**Page**: review-and-submit
**Environment**: any screenreader/browser combo
**Estimated Level of Effort to fix**: High
**Design system component involved**: Yes
**Relevant WCAG success criteria**: N/A

### To Reproduce:
- Use a screenreader and edit one of the following sections: Example: Contact Information, Additional Disability benefits, Fully Developed Claim program. You'll see that focus lands on an area below the instructions. 

#### Expected Behavior
-  Focus lands on the header for the new instructions, or if  landing on the input the user hears the associated instructions.

#### Actual Behavior
- The sreenreader user hears the input but not the additional previous instructions. The user has to navigate backwards to learn what to do.

## Tasks
- [ ] Figure out which implementation makes sense (changing focus vs adding aria-describedby to the input)
- [ ] Please update the "Fix Status" column in the [526 Accessibility Audit issues tracking doc](https://docs.google.com/spreadsheets/d/1paNxD798NSMrjZeUe9WwVQ4xRdl439ypKyPDPW3CXIo/edit?gid=2034611899#gid=2034611899) when ticket is started and completed.

## Acceptance Criteria
- [ ] Screenreader users do not miss the instructions.
- [ ] Accessibility Audit issue tracking doc is updated with ticket status
