### ISSUE TITLE
General focus issues when using VO/Safari/iOS combo

### ISSUE THREAD

**Issue by bacitracin** [department-of-veterans-affairs/va.gov-team#95533]
## Issue Description
This issue was identified in the [accessibility audit of the review & confirmation pages ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94614)of the 526 form.

There is an existing system problem with Voiceover/Safari/iOS where it just totally loses focus. So fixing this might be out of our hands.

[**Expected severity**](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-defect-severity-rubric): a11y-defect-1
**Page**: review-and-submit
**Environment**: VoiceOver/Safari iOS
**Estimated Level of Effort to fix**: High
**Design system component involved**: Yes
**Relevant WCAG success criteria**: [2.4.3 Focus Order Level A](https://www.w3.org/WAI/WCAG22/quickref/?currentsidebar=%23col_overview#focus-order)

### To Reproduce:
- This is a placeholder issue for the general focus issues that occur when using Voiceover + Safari on iOS.  It's not totally clear how to reliably recreate the focus jumping around.

#### Expected Behavior
-  Focus should move reliably when navigating through the page.

#### Actual Behavior
- Sometimes focus jumps to the body, or down into the footer. 

## Tasks
- [ ] Investigate the issue & document how to reliably reproduce this "random" jumping. 
- [ ] If possible, implement a fix. Otherwise document the issue in a new ticket.
- [ ] Please update the "Fix Status" column in the [526 Accessibility Audit issues tracking doc](https://docs.google.com/spreadsheets/d/1paNxD798NSMrjZeUe9WwVQ4xRdl439ypKyPDPW3CXIo/edit?gid=2034611899#gid=2034611899) when ticket is started and completed.

## Acceptance Criteria
- [ ] Voiceover/Safari/iOS Focus issues are documented and reproducable.
- [ ] Accessibility Audit issue tracking doc is updated with ticket status
