### ISSUE TITLE
Create wireframe when link is selected about appointment has been scheduled

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#95547]
## Description 

If a Veteran selects a link from a sms or email to schedule their appointment for their referral, BUT they've already scheduled the first appointment, what do we show the Veteran? E.g., this appointment has already been scheduled. 

This could happen when the appointments is booked in EPS, waiting for an MSA to add it into HSRM. Or, it could be in VistA already, but for some reason, the Veteran selected the link again. 

## Tasks

- [ ] Create wireframe with content
- [ ] Review with designers
- [ ] If needed, consult with CAIA on content
- [ ] Add into MVP scope page (errors Section) with annotation 
- [ ] Add to Specs page in Figma, if needed

**Comment by benbrasso-agile6** [comment]
@cgednalske is just a reviewer on this ticket
