### ISSUE TITLE
Usability Testing Prep: STEM Stand-alone (VA Form 22-10203)

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#9554]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/10203_product_outline.md)
- [Prototype - with copy](https://bahdigital.invisionapp.com/share/AUIADV5GTC2)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/research/research-plan.md)
- Link to regression test plan / [Test cases/test plan in TestRail](https://dsvavsp.testrail.io/index.php?/plans/view/416)

## Meeting attendees from **Booz Allen**
- Product Manager (required): Darrell Neel, neel_darrell@bah.com
- DEPO product lead (required): Matt Self, matthew.self2@va.gov
- Anyone else from your team who significantly contributed to the artifacts provided (required): Amy Knox knox_amy@bah.com, Cindy Cruz cruz_cindy@bah.com; Jen Jones jones_jennifer2@bah.com; Michael Delli-Gatti delli-gatti_michael@bah.com; Adam Sonntag sonntag_adam@bah.com; 
Also: Will McCormack mccormack_will@bah.com; Dan Shawkey shawkey_daniel@bah.com; Desiree Turner turner_desiree@bah.com

## Scheduling
- Requested times
Friday, May 29 at 2:00pm ET
Monday, June 1 at 3:30pm ET

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by meganhkelley** [comment]
Scheduled for 6/1! ✅

**Comment by pjhill** [comment]
@amyknox -- The test artifact information appears to be missing / incomplete.  There does not appear to be a link to a regression test plan, and the link to the functional test plan sends me to a blank test plan.

**Comment by pjhill** [comment]
QA review of artifacts is not relevant for this collaboration cycle meeting per information from the BAH team -- 
1. Regression testing is not relevant since this is a brand new form.
1. Functional test plan is not available yet because the user stories have not been completed.
