### ISSUE TITLE
Privacy policy checkbox appears twice on the Form Controls menu on the VoiceOver Rotor

### ISSUE THREAD

**Issue by bacitracin** [department-of-veterans-affairs/va.gov-team#95546]
## Issue Description
This issue was identified in the [accessibility audit of the review & confirmation pages ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94614)of the 526 form.

[**Expected severity**](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-defect-severity-rubric): a11y-defect-4
**Page**: review-and-submit
**Environment**: any screenreader/browser combo
**Estimated Level of Effort to fix**: Medium
**Design system component involved**: Yes
**Relevant WCAG success criteria**: N/A

### To Reproduce:
- Check out the form controls shortcuts screen on your screenreader (for example on VoiceOver the Rotor). 

#### Expected Behavior
-  "I have read and accept the privacy policy. (*Required)" should appear once

#### Actual Behavior
- "I have read and accept the privacy policy. (*Required)" appears twice.
![Image](https://github.com/user-attachments/assets/6d177fee-cfcc-40a5-b459-206ae4644217)

## Tasks
- [ ] See if we the privacy policy checkbox can be updated to only count as one form control. If so, fix it. if not, document the issue.
- [ ] Please update the "Fix Status" column in the [526 Accessibility Audit issues tracking doc](https://docs.google.com/spreadsheets/d/1paNxD798NSMrjZeUe9WwVQ4xRdl439ypKyPDPW3CXIo/edit?gid=2034611899#gid=2034611899) when ticket is started and completed.

## Acceptance Criteria
- [ ] The checkbox only appears once on Form controls shortcut pages

- [ ] Accessibility Audit issue tracking doc is updated with ticket status
