### ISSUE TITLE
IA Guidance: Left Nav

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#95555]
## IA standards request
Define the following for the left nav component:
- About 
- When to use
- When to consider something else
- Usability guidance
- Can we standardize between benefit hub and facility left navs? What are the considerations there?

- This guidance will live in the current [Left Nav Component in VADS](https://design.va.gov/components/sidenav). 
- Take into account any V3 plans and guidance in USWDS that is not in VADS

### Tasks
- [ ] Review/analyze existing documentation and implementation - Kristin 
- [ ] Draft standard - Kristin
- [ ] Initial review  - Mikki
- [ ] Edits based on initial review - Kristin
- [ ] Relevant stakeholder review + socializing with design system team - Mikki
- [ ] Final review and approval by Mikki - Mikki
- [ ] Publish in VADS - Erin
- [ ] Communicate out to the org - Mikki

### Acceptance criteria

- [ ] Final draft in google docs approved by Mikki
- [ ] Guidance has been approved by relevant stakeholders
- [ ] Guidance published in Github

**Comment by kristinoletmuskat** [comment]
Draft standard in sharepoint: https://dvagov-my.sharepoint.com/:w:/r/personal/michelle_northuis_va_gov/Documents/IA/Standards/Secondary%20Nav.docx?d=w71644b388a9e4d8a99fe88ec8c369080&csf=1&web=1&e=kcWA0J
