### ISSUE TITLE
IA Guidance: Primary Nav

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#95552]
## IA standards request
Define the layout and placement criteria for the healthcare and benefits menu section of the primary navigation. It should include the flyouts for each benefit area.

Goal:
Document guidance on the design of the primary nav, usage of the nav, and clear criteria for what content or links can be added and where they can/cant go.  This will provide information for teams to review before coming to IA to request a primary nav link or addition. 

This guidance will most likely live in IA github, not in VADS. 

### Tasks
- [ ] Review/analyze existing documentation and implementation - IA 
- [ ] Establish scope of effort and where guidance lives - IA
- [ ] Draft revised standard - Kristin
- [ ] Initial review  - Mikki
- [ ] Edits based on initial review - Kristin
- [ ] Final review and approval by Mikki - Mikki
- [ ] Publish in Github - Kristin
- [ ] Communicate out to teams - Mikki

### Acceptance criteria

- [ ] Final draft in google docs approved by Mikki
- [ ] Guidance has been approved by relevant stakeholders
- [ ] Guidance published in Github

**Comment by kristinoletmuskat** [comment]
Hi @mnorthuis, this is ready for your first draft review. 

I know we're not publishing this one in VADS, but I stubbed out the standards template following the same pattern as our other standards. lmk if you think we need a different direction for these internal standards.

[WIP](https://docs.google.com/document/d/1TgYFVN-_OCcpZ2J-fcH2WvQQAmcdlu2sLo9hAv-9gqk/edit?tab=t.0)

See the [mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694550504118/9ab9423b7a907602411017fd5a5fbff952ebc8bd?wid=0-1729647016685) for most up-to-date guidance by section (so that it’s easier to compare with the visual, and so we don’t have to keep both up to date as we edit. Once we have a close-to-final draft in mural, I can move the text for guidance by section into the WIP document).

**Comment by mnorthuis** [comment]
Went through mural and made some updates, created draft info for the About VA menu there as well.  Take a look and let me know if there are any questions, otherwise I think the Mural info can then be moved into the Google doc.  It'll ultimately need to go in a Sharepoint doc, so if you want to skip the Google doc, I can create a sharepoint doc for this to go in.

**Comment by mnorthuis** [comment]
Sharepoint doc - https://dvagov-my.sharepoint.com/:w:/r/personal/michelle_northuis_va_gov/Documents/Primary%20nav%20guidance%20for%20VADS.docx?d=w9bcc29bdd9b74308a2e8194d076a595e&csf=1&web=1&e=MIfYtN

Please move the mural info to this doc for OCTO review.

**Comment by kristinoletmuskat** [comment]
Just updated! Here are our links:

[Google draft](https://docs.google.com/document/d/1TgYFVN-_OCcpZ2J-fcH2WvQQAmcdlu2sLo9hAv-9gqk/edit?tab=t.0#heading=h.efzncwe2ayez)

[Sharepoint draft](https://dvagov.sharepoint.com/:w:/r/sites/SitewideCAIA/Shared%20Documents/Primary%20Nav.docx?d=wae0e473b3f1f42358f29e5bce383a996&csf=1&web=1&e=OVzPrr): it was much easier to download a copy from google and upload it into sharepoint, rather than copying the information from one place to the other. I hope this works ok!

@mnorthuis
