### ISSUE TITLE
IA Guidance: Benefit Subhub Template

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#95553]
## IA standards request
Define the layout and placement criteria for the Benefit Subhub template (currently in use in Family Member hub only). It should an outline of the sections in the template, what each section is for, and criteria for being included in each section. 

Goal:
Document guidance on the design of the template, usage of the template, and clear criteria for what content or links can be added and where they can/cant go.  This will provide information for teams to review before coming to IA to request use of the subhub. 

This guidance will most likely live in IA github, not in VADS. 

### Tasks
- [ ] Review/analyze existing documentation and implementation - IA 
- [ ] Establish scope of effort and where guidance lives - IA
- [ ] Draft standard - Kristin
- [ ] Initial review  - Mikki
- [ ] Edits based on initial review - Kristin
- [ ] Final review and approval by Mikki - Mikki
- [ ] Publish in Github - Kristin
- [ ] Communicate out to IA team - Kristin

### Acceptance criteria

- [ ] Final draft in google docs approved by Mikki
- [ ] Guidance has been approved by relevant stakeholders
- [ ] Guidance published in Github

**Comment by kristinoletmuskat** [comment]
Hey @mnorthuis, this is ready for your first-pass review in [google doc](https://docs.google.com/document/d/1J_3MF01hVUT3-j0bplhbPy9aH8X7_FNvUxgrEHX4nx8/edit?tab=t.0) and [mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694550504118/9ab9423b7a907602411017fd5a5fbff952ebc8bd?wid=0-1729979042699). 

I'm wondering if we can do our initial back-and-forth in google docs before exporting and uploading to sharepoint (if needed). Would that work for you?

**Comment by mnorthuis** [comment]
@kristinoletmuskat We need to move away from Google docs.  We can do initial work in Mural, but it will need to be in a sharepoint doc to share out for reviews.

**Comment by kristinoletmuskat** [comment]
@mnorthuis here is the sharepoint file of this standard for your review: https://dvagov-my.sharepoint.com/:w:/r/personal/michelle_northuis_va_gov/Documents/Home%20page%20guidance%20for%20VADS.docx?d=w69f2bb4012964aa1aba48016dc43a53e&csf=1&web=1&e=bRZBJI
