### ISSUE TITLE
IA Guidance: Pagination

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#95554]
## IA standards request
Define the following for the pagination component:
- When to use
- When to consider something else
- Usability guidance
- Usage of back button with pagination (KO added)
- Pagination and filtered results (KO added)

- This guidance will live in the current [Pagination Component in VADS](https://design.va.gov/components/pagination). 
- Take into account any V3 plans and guidance in USWDS that is not in VADS

### Tasks
- [ ] Review/analyze existing documentation and implementation - Kristin 
- [ ] Establish scope of effort and where guidance lives - Kristin
- [ ] Draft standard - Kristin
- [ ] Initial review  - Mikki
- [ ] Edits based on initial review - Kristin
- [ ] Relevant stakeholder review - Mikki
- [ ] Final review and approval by Mikki - Mikki
- [ ] Publish in VADS - Erin
- [ ] Communicate out to the org - Mikki

### Acceptance criteria

- [ ] Final draft in google docs approved by Mikki
- [ ] Guidance has been approved by relevant stakeholders
- [ ] Guidance published in Github

**Comment by kristinoletmuskat** [comment]
@mnorthuis here is the first draft ready for review: https://dvagov-my.sharepoint.com/:w:/r/personal/michelle_northuis_va_gov/Documents/IA/Standards/Pagination.docx?d=wf298b2157b674a6fa3117b8235917967&csf=1&web=1&e=DJORX4

I have an open Q to the DST about that strategy, and just added the one situation that has come up (how to move from detail results back to the list via browser back vs breadcrumbs).
