### ISSUE TITLE
Remove Unused ENV variables from vets-api environmental helm charts and vets-api code

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#95565]
Utilize the "Setting/Module Mapping tab of https://docs.google.com/spreadsheets/d/1-7PLskyY67b4J1fsk-FADYxnSN1UrmVziFfFIt_1saU/edit?gid=1247793891#gid=1247793891 remove unused settings from vets-api code and the vets-api environmental helm charts

## Tasks
- [x] remove variable from settings files
- [x] remove remove variable from ENV helm charts

## Acceptance Criteria
- [x] vets-api code is modified removing unused values and ENV helm charts and parameter store is cleared of unused values
- [x] vets-api code and env charts have been deployed with adjusted code
- [x] Sufficient testing has been completed to minimize risk
