### ISSUE TITLE
Illustrate that the vets-api parent chart can be used as a dependency of the vets-api ENV charts when published in ECR

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#95569]
We need to illustrate that argoCD is able to utilize a chart dependency that is published in ECR

## Tasks
- [ ] publish a parent helm chart in ecr
- [ ] deploy an env chart through argoCD referencing the published vets-api parent helm chart

## Acceptance Criteria
- [ ] the current PULL methodology of vets-api can work with a parent helm chart published in ECR
