### ISSUE TITLE
[practice] initiative: description

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#95563]
## Background

As a user, I want a consistent, easy to comprehend user experience across VA.gov, including when things go wrong, so that I can be informed and know what to do (or not) next.

This related to #94435 and the auditing of alerts and errors on My VA. During that audit, it was determined that the "Outstanding debts" section uses the error alert style for an API error, while we use the warning style for other kinds of similar errors with APIs/systems-based issues.

The warning style will need to be updated.

---
## Tasks
- [ ] Update design in Figma
- [ ] Discussion, handoff with engineering and product

## Acceptance Criteria
- [ ] Update design in Figma

## Validation
- Who can validate this ticket? PM, Engineering

## Resources
[IA flow for Outstanding debts](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=0-7422)

**Comment by ACParker89** [comment]
@mattmarino-adhoc will this be worked in 48?

**Comment by mattmarino-adhoc** [comment]
Yep!

**Comment by mattmarino-adhoc** [comment]
[Updated alert style](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=0-164&t=dodcchlZc2GrICxI-1)

**Comment by mattmarino-adhoc** [comment]
@allisonlu @DanielMiller-agile6 Please take a look at this - we will be updating the alert style for all outstanding debt related alerts from 'error' to 'warning'
