### ISSUE TITLE
Create IAM access groups for Parameter store

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#95572]
Create new IAM groups for access to parameter store values that are grouped by the vets-api module name

## Tasks
- [x] A read only and read/write access group for each module of vets-api and for the 'common' values
- [ ] each group has appropriate permissions (read for read, read/write for read/write) specific to the module.

## Acceptance Criteria
- [ ] IAM groups are created for each module
