### ISSUE TITLE
[CDP] VHA - Update mockups based on research

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#95587]
## Description

Update VHA mockups based on feedback we received during research.

## Tasks
- [x] Update Figma mockups

## Acceptance criteria

- [x] Mockups have been created in Figma
- [x] Share with Lighthouse

**Comment by mgleo** [comment]
[Updated mockups](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=4147-24675&t=awwDHd0UUjPhdUCk-1)
