### ISSUE TITLE
Updated QA test scripts in TestRail

### ISSUE THREAD

**Issue by adamcaniparoli** [department-of-veterans-affairs/va.gov-team#95601]
## Issue Description
Creating a more in-depth manual QA process: potentially paving the path for a better automated QA process someday

---
## Tasks
- [x] Gain access to TestRail (using Matt Knight's login, if anyone needs this in the future)
- [x] Create manual test script for a smoke Test for Form 527
- [ ] Create manual test script for a full test for Form 527

## Acceptance Criteria
- [x] Fully updated test script for a smoke Test for Form 527
- [ ] Fully updated test script for a full test for Form 527
---
