### ISSUE TITLE
Consolidate BE CI Checks

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#95609]
During the [discovery work](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3535470594/Vets+API+CI+Backend+approval+Consolidation) done in #93566, it was determined that we can consolidate 3 of our backend CI checks into a single GHA. This will require stripping out some unnecessary functionality (noted in Discovery doc), and reworking the 3 actions into a single action. There is also some complicated shell scripting that may be able to be replaced by a ruby script for ease of maintenance 

## Tasks
- [x] Create consolidated CI check(s) combining elements from existing checks
- [ ] ~~Replace complicated scripting with ruby script~~
- [ ] ~~Test, with help of users on different teams to confirm edge cases are met~~

## Acceptance Criteria
- [ ] ~~Updated GHA is merged to master~~
- [x] Create Follow-up ticket to finish up work - https://github.com/department-of-veterans-affairs/va.gov-team/issues/96587
