### ISSUE TITLE
ZSF | Pension & Burial - Report the total numbers

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#95608]
## Issue Description
Slack request here: https://dsva.slack.com/archives/CE4304QPK/p1729530355646899

We need to report on: 
- Total Resolved Silent Failures
- Total Unresolved Silent Failures
- Toal Unrecoverable Silent Failures

---
## Tasks
- [x] Using our research/discovery around ZSF, please provide totals to the 3 items noted above.
- [x] Update this ticket with totals since the spreadsheet already has some historical numbers that we don't want to override. 

## Acceptance Criteria
- [x] Totals are provided by Nov 12

Additional Note:
Original request asked to provide totals in this [Sharepoint spreadsheet](https://dvagov.sharepoint.com/:x:/r/sites/oitocto1/Zero%20Silent%20Failures/All%20OCTO%20Products.xlsx?d=w079f026ab15e4b1c97e042c657eaaf0f&csf=1&web=1&e=Fo6FWz) but since it already has numbers for Pension and Burials we were advised not to override.

**Comment by aplatt-coforma** [comment]
I got access to the spreadsheet and see these are the recorded numbers. We should validate if these are correct.
![Image](https://github.com/user-attachments/assets/c182ddca-4a7c-412d-bb6c-32fc6f119414)

**Comment by sanjabaj2** [comment]
I asked the same question. These are from old, old, discovery before we stood up new pension and burial apps. I think our new, zsf project discovery should go into [This excel sheet. ](https://dvagov.sharepoint.com/:x:/r/sites/oitocto1/_layouts/15/Doc.aspx?sourcedoc=%7B079F026A-B15E-4B1C-97E0-42C657EAAF0F%7D&file=All%20OCTO%20Products.xlsx&wdLOR=c4ED56EF5-F98E-467B-9ACA-220366AA22A0&action=default&mobileredirect=true)

**Comment by aplatt-coforma** [comment]
Thanks @sanjabaj2 . The screenshot I shared is taken from that same spreadsheet. With this ticket, we will update those numbers for based on the recent discovery work that we completed for ZSF. Is there a need to keep those existing numbers in that spreadsheet or can we override?

**Comment by sanjabaj2** [comment]
Please do not override. 

For now, just make sure that we have github issues created for any category type of silent failures that we discovered after CY3 date, along with numbers of failures.  I need to sort out what do they want reported in the excel and I can take care of that.

**Comment by TaiWilkin** [comment]
@aplatt-coforma What dates do we want for these? From March 2024 until now?

**Comment by aplatt-coforma** [comment]
@sanjabaj2 - can you help answer Tai's question about timeframe for this request? cc @matt4su

**Comment by TaiWilkin** [comment]
| Pensions | Burials
-- | -- | --
Resolved (including resolution by retry) | 66 | 12
Unresolved | 0 | 90
Missing status | 0 | 2546
Unrecoverable (excluding unattempted) | 0 | 0


Failures requiring research and remediation:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/97053
https://github.com/department-of-veterans-affairs/va.gov-team/issues/97057
https://github.com/department-of-veterans-affairs/va.gov-team/issues/97060
https://github.com/department-of-veterans-affairs/va.gov-team/issues/97088
https://github.com/department-of-veterans-affairs/va.gov-team/issues/97091
https://github.com/department-of-veterans-affairs/va.gov-team/issues/97092

In addition to those failures, additional claims of unknown status are listed in [Possible Burial Failures.xlsx](https://github.com/user-attachments/files/17738286/Possible.Burial.Failures.xlsx). 

Missing status: The claims under "probable successes" in the spreadsheet were submitted to Central Mail, but we don't know if they were received or processed successfully. I recommend that we create a follow-up issue to coordinate with Central Mail to confirm status of those claims.
