### ISSUE TITLE
Update New Confirmation Page to align with VFF template (due by EOD on 10.28)

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#95600]
As the VFF team, we would like other forms teams to adopt the new VFF Confirmation page template that was integrated into the codebase on October 18th.

**Tasks**
- [x] Steven will align the [New Confirmation page Designs](https://www.figma.com/design/dlhofkIJz3MC81PD0pJAb8/OCTO-%7C-Form-Status-Project-(VFF-%2B-My-VA)?node-id=703-41778&t=Qt1OyatDslHnOVLp-4) with the new [VFF Confirmation Page Template](https://www.figma.com/design/dlhofkIJz3MC81PD0pJAb8/OCTO-%7C-Form-Status-Project-(VFF-%2B-My-VA)?node-id=703-41778&t=Qt1OyatDslHnOVLp-4). 
- [x] Evelyn will review the updated designs from a research perspective
- [x] Maya will review the updated designs with Shannon and Jared
- [x] Maya will send a slack message to Matt Dingee, Shannon, and Emily by EOD Monday to get OCTO's feedback on the updated design. 
- [x] Jared, Steven, Maya, Christine will meet before EOD on 10.29 to review the proposed changes

**Acceptance Criteria**
- [x] The redesigned Confirmation page successfully meets the usability goals identified during the Timely and Truthful prototype testing.
- [x] The updated New Confirmation page design does not delay the goal of beginning development on 10/29.
- [x] The updated New Confirmation page design is expected to pass the staging review.
- [x] The updated New Confirmation page design is visually consistent with the standards set by the VFF team.
- [x] CAIA feedback and copy updates that cannot be incorporated in this increment have been documented and added to the backlog for future consideration.

### Drivers
Steven

### Consulted
Evelyn, Maya

**Comment by mayacarrolluxa6** [comment]
@pacerwow @StevenStraily Trying to get time with Shannon on 10.22 to discuss the timing and priority of this from OCTO's perspective.

**Comment by mayacarrolluxa6** [comment]
https://design.va.gov/templates/forms/confirmation#need-help

**Comment by mayacarrolluxa6** [comment]
Deadline: EOD on Monday to finalize this page and regroup as team on next steps.

**Comment by StevenStraily** [comment]
Work completed [here](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/(526ez)-New-Confirmation-Page-and-Email-Touchpoints?node-id=8405-84364&t=Aio8R2ofrvN4i04A-4) and undergoing review today (10/28).
