### ISSUE TITLE
Copy of PR Bot Testing

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#95627]
## Description 

We are reviving the PR Bot to ensure that all requirements are met before a Pull Request (PR) is submitted for review to the Tier 2 team. The following steps outline the tasks necessary to launch a test of the PR Bot.

Acceptance Criteria:

- GitHub and Slack tokens are successfully acquired.
- The code is hosted on Heroku for continuous operation.
- The route for PR responses is tested to an alternate channel.
- Once the setup is approved, messages will be rerouted back into the support channel.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Token Access: Acquire a GitHub Token
- [ ] Token Access: Acquire a Slack Token
- [ ] Hosting: Host the code on Heroku to ensure continuous operation
- [ ] Testing: Test the PR response route to confirm it functions correctly in the alternate channel
- [ ] Re-routing: Once the setup is validated and approved, re-route the messaging back to the support channel
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Moved to next sprint, waiting on VA and can't finish.

**Comment by bmatos312** [comment]
Worked with Adrian and got slack token and bot setup.
got approval from bill chapman and working on rerouting
