### ISSUE TITLE
Add appointment details null state tracking

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#95657]
## Description

This is the engineering ticket follow-up to https://github.com/department-of-veterans-affairs/va.gov-team/issues/86273. From the investigation, we have the following design:

1. We choose to report base statistics on the FE using GA4 similar to what we do for [fetch results](https://github.com/department-of-veterans-affairs/vets-website/blob/436ce04628d106e6c8673fd1b51dbb30807bf07b/src/applications/vaos/appointment-list/redux/actions.js#L191C15-L200). For reporting, we'll use GA interface to query for the results and produce answers to the questions listed above, see section 4 below.
2. When displaying appointment details on the FE (i.e. [in these layout files](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/vaos/components/layout)), we will increment the following statistics when they are expected to be present on the appointment type, see section 3 for which field/metric is expected for each appointment type.  
  - i. Type of care: increment `vaos-null-states-expected-type-of-care` [^1] since all appointments should contain this field, then increment `vaos-null-states-missing-type-of-care` if it's not available.
  - ii. Provider: increment `vaos-null-states-expected-provider` if it's expected for the appointment, then increment `vaos-null-states-missing-provider` if not available. 
  - iii. Facility ID: increment `vaos-null-states-expected-facility-id` if expected, then increment `vaos-null-states-missing-facility-id` if not available. Note that this would imply missing facility details and facility phone as well.
  - iv. Facility details (name and address): If the facility ID is present, increment `vaos-null-states-expected-facility-details` if expected, then increment `vaos-null-states-missing-facility-details` if not available.
  - v. Facility phone: If the facility ID is present, increment `vaos-null-states-expected-facility-phone` if expected, then increment `vaos-null-states-missing-facility-phone` if not available.
  - vi. Clinic phone: increment `vaos-null-states-expected-clinic-phone` if expected, then increment `vaos-null-states-missing-clinic-phone` if not available.
  - vii. Any null state: increment `vaos-null-states-expected-total` for each appointment, then increment `vaos-null-states-missing-any` if any of the fields from i-vi is missing.
3. Here are the fields expected for each appointment type, this information comes from [this source of truth](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=1152-86021&node-type=section&t=JxCCEJVEATxksVxs-0):

| Appointment type | Type of Care | Provider | Facility ID | Facility Details | Facility Phone | Clinic Phone | 
| - | - | - | - | - | - | - |
| In person | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | 
| Video (At home) | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | 
| Video - At VA | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | 
| Video - At ATLAS | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | 
| Phone | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | 
| CC | ✅ | ✅ | ❌ | ❌ | ❌ | ❌  |
| Claims Exam | ✅ | ❌ | ✅ | ✅ | ✅ | ✅ |
| VA Request | ✅ | ❌ | ✅ | ✅ | ✅ | ❌ |
| CC Request | ✅ | ✅ | ❌ | ❌ | ❌ | ❌ |

## Development Checklist

- Null state statistics is added for each of the following appointment type:
  - [ ] In person
  - [ ] Video (At home)
  - [ ] Video - At VA
  - [ ] Video - At ATLAS
  - [ ] Phone
  - [ ] CC
  - [ ] Claims Exam
  - [ ] VA Request  
  - [ ] CC Request

- Child tickets:
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/98976
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/98977
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/98978
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/98979
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/98980
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/98981
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/99006

### Design Assets
N/A

### Developer Reference
N/A

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove)

**Comment by JunTaoLuo** [comment]
All child tickets have been filed. Should this ticket be closed or converted to a feature ticket @JRRoof ?

**Comment by JRRoof** [comment]
Epic #99318 was created.  Closing this ticket.
