### ISSUE TITLE
BE | Profile | Test Tags | Direct Deposit

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#95666]
## Background
When modifying a feature in vets-api, it would be faster to run specs related to a feature or our team instead of running the full test spec (eg: 10,000+ specs).  RSpec provides a tag for this.

We want to tag our test cases related to the profile team, with the tag “**:profile**” as the second parameter of **it** / **describe** / **context** .

```ruby
# spec/controllers/v0/profile/direct_deposits_controller_spec.rb
describe V0::Profile::DirectDepositsController, team: :profile, feature: :direct_deposit do
  # test code ...
end
```

We can instruct RSpec to only run tests with a specific tag like this:

```ruby
bundle exec rspec spec --tag team:profile
bundle exec rspec spec --tag feature:direct_deposit
bundle exec rspec spec --tag team:profile --tag feature:direct_deposit
```

## Tasks
- [x] Review Vets-API specs (Tom/Asiisii).
- [x] Add `team: :profile` and `feature: :direct_deposit` tags to Personal Information specs (Tom).

## Acceptance Criteria
- [x] Direct Deposit spec files have the appropriate tags.
- [x] BE engineer handbook updates.

**Comment by tpharrison** [comment]
@asiisii I've added [this document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/tutorials/testing/rspec_tags.md) to our sensitive repo.

Please review when you get a chance and let me know what you think.  I'm going to reach out to a few other engineers and get their feedback as well.

**Comment by asiisii** [comment]
> [@asiisii](https://github.com/asiisii) I've added [this document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/tutorials/testing/rspec_tags.md) to our sensitive repo.
> 
> Please review when you get a chance and let me know what you think. I'm going to reach out to a few other engineers and get their feedback as well.

I reviewed the document, and I really appreciate how clear and detailed it is, @tpharrison

**Comment by tpharrison** [comment]
@asiisii My changes have been merged, so you can close this out whenever the remaining tasks are finished.  Let me know if you need anything from me.
