### ISSUE TITLE
Complete rollout of parameter store normalization

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#95667]
The Parameter store normalization effort is nearing completion. Complete the remaining SSM value copies and ENV variable creations

## Tasks
- [x] Copy Parameter store keys to new path
- [x] update values.yaml file in parent helm chart for copied keys

## Acceptance Criteria
- [x] Parameters store set up
