### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Blivaditis** [department-of-veterans-affairs/va.gov-team#95672]
### Description
This ticket is a continuation of the work started in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92932). This is part of an effort to reduce our row count in Domo, and to clean up our instance only for what is needed.

Artifact -- [Domo Dataset Audit](https://docs.google.com/spreadsheets/d/1y6WRGftpGzzCwrytaFjoxrzZaLBmAqNZ58sXIQMmj68/edit?gid=2007741445#gid=2007741445)

---

### Tasks

- [x] Review datasets marked as -- Delete in [our spreadsheet](https://docs.google.com/spreadsheets/d/1y6WRGftpGzzCwrytaFjoxrzZaLBmAqNZ58sXIQMmj68/edit?gid=2007741445#gid=2007741445) ensure that deletion is the appropriate and that the dataset does not power any cards  or data flows. 
- [x] Once we review as a team, and confirmed, move forward with deletion.
- [x] For datasets marked as partial purge -- determine requirements for each, (i.e. Remove data prior to 1 Jan 2023).

### Acceptance Criteria

- [ ] Datasets have been deleted
- [ ] Datasets that need to be purged have requirements for purging

**Comment by johnny-jesensky-adhoc** [comment]
Hi @Blivaditis -- do we need this ticket? Looks like it's just titled, _Test_.

**Comment by Blivaditis** [comment]
No it's not needed.
