### ISSUE TITLE
Domo Audit: Wave 1

### ISSUE THREAD

**Issue by Blivaditis** [department-of-veterans-affairs/va.gov-team#95673]
### Description
This ticket is a continuation of the work started in [this ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/95672). This is part of an effort to reduce our row count in Domo, and to clean up our instance only for what is needed. This specific ticket pertains only to the datasets marked as Wave 1, wave 1 indicates that a dataset is no longer in use and can be deleted. All necessary info can be found in the artifact attached, Wave 2 & 3 will take place in another ticket.  

Artifact -- [Domo Dataset Audit](https://docs.google.com/spreadsheets/d/1y6WRGftpGzzCwrytaFjoxrzZaLBmAqNZ58sXIQMmj68/edit?gid=2007741445#gid=2007741445)

---

### Tasks

- [x] Review datasets marked as -- Delete (Wave 1) in [our spreadsheet](https://docs.google.com/spreadsheets/d/1y6WRGftpGzzCwrytaFjoxrzZaLBmAqNZ58sXIQMmj68/edit?gid=2007741445#gid=2007741445) ensure that deletion is the appropriate and that the dataset does not power any cards  or data flows. 
- [x] Confirm Datasets are no longer in use
- [x] Delete all datasets marked Wave 1
- [x] Ensure all wave 2 datasets have date ranges and are ready for purging 

### Acceptance Criteria

- [x] All dataset marked wave 1 have been deleted
- [x] Datasets that need to be purged have requirements for purging

**Comment by ChristineYoungZA** [comment]
All of wave 1 datasets have been deleted, and wave 2 is ready for deletion.
