### ISSUE TITLE
Add note to SR upload instructions for when the number of issues exceeds 20

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#95681]
## User Story
As a Governance team member, I want to be reminded that is/when we attempt to upload more than 20 issues via the Issue Uploader tool, that there are built in pauses so I don't think that anything is wrong.

Assignee: @it-harrison 
Peer Reviewer: @erinrwhite 

## Description
[In a recent Staging Review,](https://dsva.slack.com/archives/GNF5GSD9N/p1729176694790499) Governance ran the issue uploader tool with a csv file that had more than 20 lines (aka more than 20 documented findings). If/when this occurs, the issue uploader has built in pauses for a minute every set of 20, "to avoid requests failing due to rate limits." There should be a timer visible. Please connect with @it-harrison if you have any questions.

The purpose of this ticket is to update our operational guidance so that Governance team members are reminded of this pause, so that they don't take any unnecessary action.

### Live pages
- [How to generate Staging Review issue tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets)
- [How to use the bulk issue uploader](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3239870645/How+to+use+the+bulk+issue+uploader)

### Drafted pages
- 

## Tasks
- [x] Determine where in the guidance it would be valuable to make this change/add this note
- [x] If there are any comments in either of the SR docs referenced, please address the comments 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team members are prepared if/when a SR has more than 20 findings

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@erinrwhite - as it turns out, the information re this ticket is [already live](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3239870645/How+to+use+the+bulk+issue+uploader#Using-the-bulk-issue-uploader-to-generate-Staging-Review-tickets):
I did run another test with dummy data and verified that the tool is working as described.

**Comment by erinrwhite** [comment]
Well looky there - looking good to me. I can also verify that the last time I was on-support the uploader needed to sleep for a minute and did exactly as described. Think we are okay to close.

**Comment by shiragoodman** [comment]
Thank you both. Reminder to you both that next time someone has issues with anything, "Have you checked the documentation?" needs to become our default response. ALWAYS.
