### ISSUE TITLE
[EventBus Gateway] Create a basic helm chart with a sample Deployment to sync to Argo CD.

### ISSUE THREAD

**Issue by LouisFettet** [department-of-veterans-affairs/va.gov-team#95680]
### Background

We already have an application in VFS Argo CD for the `dev` environment (from work done in #89039): [eventbus-gateway-dev](https://argocd.vfs.va.gov/applications/eventbus-gateway-dev).

This application is currently set to sync from updates in the [vsp-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests) repository, looking at the `/apps/eventbus-gateway/dev` directory on `main`.

**Note**: Currently, many infrastructure configs for applications in the repo are duplicated for different environments. We should attempt a cleaner solution where we utilize the same templates for all environments, using environment values-files to account for any differences in the environments. ~For this reason we **do not** want the Argo CD application to point at a `dev` directory (but rather point at the main directory and use a `dev.yaml` environment file).~ **Update:** This isn't feasible, so the solution seems to be to house our Helm chart outside the repo and then pull it in as a dependency into each individual environment chart like Vets API does.

### Task

- [x] Create a new branch in the [vsp-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests) repository as a long-running development branch for EventBus Gateway.
  - The branch is [eventbus-gateway-init-dev](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/eventbus-gateway-init-dev).
- [x] Create the `/app/eventbus-gateway` directory on the new branch and generate a basic helm chart (should contain `Chart.yaml`, `values.yaml`, and a `templates/` directory).
  - This was performed within the `dev` directory.
-  Create a sample Kubernetes `Deployment` configuration under `templates/` titled `deployment.yaml`.
   - We should use the sample `Deployment` available in the [Karafka docs](https://karafka.io/docs/Deployment/#kubernetes).
     - There is another example of both a `Deployment` and a `Service` [here](https://github.com/making/cloud-karafka-service-broker/blob/develop/k8s/sample/consumer.yml).
   - We should use a publicly available image as a "hello world" (building our own application image will happen in another ticket).
- [x] Configure the Argo CD application to sync from the new branch by changing the applications' `TARGET_REVISION` to the new branch.
  - This was performed in the new development Argo CD application set up by the platform team.
- [x] Ensure the application is running on the same cluster as [vets-api-dev](https://argocd.vfs.va.gov/applications/vets-api-dev), `dsva-vagov-dev-cluster`.
  - This should work when we're ready to move from the development Argo CD application to the one managed by the app-of-apps.

### Acceptance Criteria

- [ ] Upon pushing a new commit to the new development branch, the Argo CD application should auto-sync.
- [ ] Argo CD application appears green (healthy and synced).
- [ ] Argo CD application contains a single `Deployment` that appears green (healthy and synced).
