### ISSUE TITLE
Coronavirus in-body alerts

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#9569]
# User story
As a Veteran or family member, I need to know that I can still file claims for benefits and get help with managing extensions, claim exams, debt, and other concerns during the coronavirus pandemic.

## Issue description
We need to create reusable in-body alerts to place on relevant health care and benefit pages across VA.gov to provide contextual information about how the coronavirus may affect appointments, benefits, and services. 

#### Alert component 1

**You can still file a claim and apply for benefits during the coronavirus pandemic**
Get the latest information about in-person services, claim exams, extensions, paperwork, decision reviews and appeals, and how best to contact us during this time. 
[Go to our coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#benefit-payments-claims-claim-).

#### Alert component 2

**We can help with your questions about debt and other financial concerns**
Get the latest information about concerns like managing VA debt, or paying your VA copays or VA-backed home loan during this time.
[Go to our coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#debt-copays-appeals-and-other-)

#### Alert component 1

- [x] https://www.va.gov/disability/how-to-file-claim/
- [x] https://www.va.gov/disability/how-to-file-claim/when-to-file/
- [x] https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/
- [x] https://www.va.gov/disability/how-to-file-claim/evidence-needed/
- [x] https://www.va.gov/disability/how-to-file-claim/evidence-needed/fully-developed-claims/
- [x] https://www.va.gov/disability/how-to-file-claim/evidence-needed/standard-claims/
- [x] https://www.va.gov/disability/how-to-file-claim/additional-forms/
- [ ] https://www.va.gov/claim-or-appeal-status/ _(Let's look at this one first to make sure an alert will work)_
- [x] https://www.va.gov/disability/upload-supporting-evidence/
- [x] https://www.va.gov/disability/va-claim-exam/ _(Let's look at this one - it has 2 alerts now and think that's probably too much)_
- [x] https://www.va.gov/disability/get-help-filing-claim/
- [x] https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/
- [ ] https://www.va.gov/careers-employment/education-and-career-counseling/ _(not adding now because i don't want to mess with this page, as it's being edited based on program name change)_
- [x] https://www.va.gov/pension/how-to-apply/
- [x] https://www.va.gov/pension/how-to-apply/fully-developed-claim/
- [x] https://www.va.gov/pension/aid-attendance-housebound/
- [x] https://www.va.gov/pension/survivors-pension/
- [ ] https://www.va.gov/decision-reviews/ _(let's look at this one; decision reviews smes requested an alert on this page, but it already has an alert)_
- [x] https://www.va.gov/decision-reviews/supplemental-claim/
- [x] https://www.va.gov/decision-reviews/higher-level-review/
- [x] https://www.va.gov/decision-reviews/board-appeal/
- [x] https://www.va.gov/decision-reviews/multiple-party-claims/ _(can't seem to find this one)_
- [x] https://www.va.gov/decision-reviews/contested-claims/
- [x] https://www.va.gov/decision-reviews/faq/
- [ ] https://www.va.gov/disability/file-an-appeal/ _(can't seem to find this one)_

**Question to think about:** Should we also add this alert to disability and pension eligibility pages? 

#### Alert component 2

- [x] https://www.va.gov/housing-assistance/home-loans/loan-types/purchase-loan/
- [x] https://www.va.gov/housing-assistance/home-loans/loan-types/cash-out-loan/
- [x] https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/
- [x] https://www.va.gov/housing-assistance/home-loans/loan-types/interest-rate-reduction-loan/
- [x] https://www.va.gov/housing-assistance/home-loans/surviving-spouse/
- [x] https://www.va.gov/housing-assistance/home-loans/trouble-making-payments/
- [x] https://www.va.gov/health-care/copay-rates/
- [x] https://www.va.gov/health-care/pay-copay-bill/

---
## Tasks
- [x] Develop content for 2 in-body alerts (confirmed no JTF approval needed) (Danielle)
- [x] Identify relevant pages to place alerts (Danielle)
- [x] Create alerts in Drupal (Danielle)
- [x] Add alerts to relevant pages in Drupal (Danielle)
- [ ] Check alert content and placement and set pages to publish (Randi)

## Acceptance Criteria
- [ ] Alerts added to each relevant page and validated on live site
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
**For Monday:**

Hi @RLHecht. I've created the 2 new alerts and added them to the relevant pages. Can we connect on Monday morning to:

- Review and make sure everything looks okay, then publish
- Go over the few that I have questions about above
- Remove the global covid banner from these pages to reduce # of banners/alerts 

Thank you!

FYSA @stephorkandatx

**Comment by RLHecht** [comment]
These have all been published except for ones that would cause double alerts:

- https://www.va.gov/disability/va-claim-exam/
- https://www.va.gov/disability/file-an-appeal/ 
- https://www.va.gov/claim-or-appeal-status/
- https://www.va.gov/decision-reviews/

The global alert has also been removed from all the pages that have been published.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, thank you, @RLHecht! Much appreciated.

**Comment by RLHecht** [comment]
All pages that were published yesterday have been validated on live site. FYSA @stephorkandatx

**Comment by RLHecht** [comment]
@stephorkandatx There are a few pages that we didn't put the alert on yet because they either have another alert at the moment or we are doing other work on. Should we keep this ticket open for those stragglers or set up a new separate ticket for them? @DanielleThierryUSDSVA
