### ISSUE TITLE
Determine accounts effected by the submission failure error

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#95699]
## Description

Identify those affected by the AddressLine 2 issue #[95595](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/95595) and prepare a communication mechanism to notify those impacted that they may resubmit their forms.

## Tasks
- [ ] Report on the total number of saved/in progress forms
- [ ] Report on the total number of saved/in progress forms for the time frame that the error existed
- [ ] Report on the contact Email addresses of the Veterans that were impacted by the error from the report above
- [ ] Submit an Email via VA-Notify with content provided by the PO informing those impacted that they can resubmit now

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [X] Not Required

## Acceptance criteria
- [ ] The tasks are completed
- [ ] A new ticket is drafted for the sending of the Email (if needed)

## Testing
- [X] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [X] Description written
- [X] Tasks defined
- [X] Acceptance criteria written
- [X] Testing defined
- [X] Add Labels
- [X] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by Tom-Davis** [comment]
@digitaldrk @Dr-Pongo @denisecoveyduc here is the ticket we talked about at DSU. Once the "AddressLine 2 issue #[95595](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/95595)" is resolved we can pull the repots noted here and start the communication process.

**Comment by Tom-Davis** [comment]
Due to the error flow, we do not have access to users that saw the problem.

**Comment by denisecoveyduc** [comment]
@digitaldrk @Dr-Pongo @dhill802 -  Wondering if one of you might be able to provide a bit more clarity on @Tom-Davis's comment from last week. It sounds like we are not able to generate a list of submissions that failed?  Do we have any information about how many submissions this might be?

_**Follow on:**_ Possibly you already have but let's discuss how we can prevent this type of issue in the future.  Can we integrate an alert, retry logic, silent failure communication to the Veteran, etc.?  If any of those have already been added to the backlog can we link them in this ticket for reference and tracking. Thank you.

**Comment by digitaldrk** [comment]
> [@digitaldrk](https://github.com/digitaldrk) [@Dr-Pongo](https://github.com/Dr-Pongo) [@dhill802](https://github.com/dhill802) - Wondering if one of you might be able to provide a bit more clarity on [@Tom-Davis](https://github.com/Tom-Davis)'s comment from last week. It sounds like we are not able to generate a list of submissions that failed? Do we have any information about how many submissions this might be?
> 
> _**Follow on:**_ Possibly you already have but let's discuss how we can prevent this type of issue in the future. Can we integrate an alert, retry logic, silent failure communication to the Veteran, etc.? If any of those have already been added to the backlog can we link them in this ticket for reference and tracking. Thank you.

Hi there, sure thing.

This is not a silent failure, the user was provided feedback that there was an error. The submission was not sent in/submitted therefore, we did not have the opportunity to save the form. The veteran had the opportunity to come back to the form and submit later.

We added an alert one day before this ticket was created: https://vagov.ddog-gov.com/monitors/289709

We also have a dashboard for item for data issues that throw errors: https://vagov.ddog-gov.com/dashboard/shm-nr4-75f?fromUser=false&fullscreen_end_ts=1733167336298&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=edit&fullscreen_start_ts=1732994536298&fullscreen_widget=4187743382441932&refresh_mode=sliding&view=spans&from_ts=1732994527625&to_ts=1733167327625&live=true
