### ISSUE TITLE
Form Engine:  Supporting third-party authentication

### ISSUE THREAD

**Issue by gopixelsgo** [department-of-veterans-affairs/va.gov-team#95692]
## Description
This is a placeholder to discuss as a team what it means to include this in our scope. Recent PO feedback has clarified this as a requirement. Our current scope has kept the focus on Veteran and Beneficiary respondents. Implementing the respondent pattern and aligning with the greater VA experience means supporting 3rd party (VSO, PoA) authentication. 

For example, the prompt in the 'Who will submit this form?' step, would ask:

Who is allowed to submit this form?
[ ]  Allow a third party to sign and submit this form for a Veteran or Beneficiary(ies)
[ ]  Only the Veteran or Beneficiary can sign and submit this form

If the first option is chosen we’ll need to include login and credential upload.

**Impacts to UX:** Intro copy communicating the need to have the credential first, collecting their name and info (assuming they are the signor - also is that automatic?), offering a link to that form, etc. 

## Tasks 
- [ ] Review and discuss as a team 
- [ ] Identify next steps

## Acceptance Criteria
- [ ] Next steps identified 
- [ ] New ticket(s) and applicable epic created as needed

**Comment by Karak888** [comment]
kara to create this as an epic. will need discussion in order to know what next steps will be from UX as well as engineering.

**Comment by Karak888** [comment]
I am taking this off of you all of course unless you have tickets to add.  I am closing this as I have already created an epic for this in GH and we can create tasks and subtasks under epic as we go through. I am taking the lead on this as discussed.

**Comment by Karak888** [comment]
This is not at an epic level and will move this to become a task rather than an epic.  Can always re-assess at a later date. @gopixelsgo @brian-wilke

**Comment by Karak888** [comment]
Need to determine if this is a priority and if so will need to get started soon. Kara to discuss with Matt.
