### ISSUE TITLE
Burial FE engineering audit

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#95706]
## Issue Description
From an engineering perspective we wanted to do a general review on the FE code on Burial and identify any areas for improvement and/or standardization. 
---
## Tasks
- [ ] Review FE Burial code and take with previous FE engineers (as needed)
- [ ] Review FE Burial open tickets
- [ ] Outline areas for improvement and/or standardization
- [ ] Create tickets as needed for prioritization

## Acceptance Criteria
- [ ] Knowledge is gained
- [ ] areas of improvement are documented and review with product and tech lead
- [ ] tickets are created if needed
