### ISSUE TITLE
Prepare Decision Review failed form email templates for PROD

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#95703]
## Value Statement

**_As a_** developer

**_I want to_** the email templates to be made available in Prod

**_So that_** we can release the new capability to notify to veterans upon submission/evidence upload

---

## Background Context
Eileen can add additional context here...

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] All monitoring tasks have been completed
- [ ] All pre-production tasks have been completed.

## Designs and Build Notes

- Add here

### Enablement team (if needed)
@ member of team

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

DataDog Monitoring
- [ ] Dashboard 
- [ ] Notification of successful email sent
- [ ] Notification when emails fail to trigger/send
- [ ] See [DataDog metric increment](https://github.com/department-of-veterans-affairs/va.gov-team-

Pre-production
- [ ] Confirm access to [VA Notify Self Service Portal](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify#getting-access-to-our-self-service-portals)
- [ ] Staging testing
- [ ] Obtain Production API key from VA Notify
- [ ] Push templates to production VA Notify
- [ ] VA Notify Service Production API Key added to production vsp-infra-application-manifests configuration
- [ ] Veteran-Uploaded Document Failure Mailer template ID added to production vsp-infra-application-manifests configuration
- [ ] VA Notify Service Production API Key added to production EKS

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by kayline** [comment]
We should include 4142 notifications in this
