### ISSUE TITLE
File change request in SNOW for dns zone delegation and await correspondence

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#9570]
## Issue Description
Change request needs to be filed in Service Now to delegate the *.vfs.va.gov zone to the VSP-Operations team.

---
## Tasks
- [x] File ticket with Service Now folks via CAG
- [ ] Await correspondence / further instruction
- [ ] Update this ticket with any discrepancies, issues, etc.

## Acceptance Criteria
- [ ] Proper ticket is filed with proper team and the desired dns zone is delegated to VSP-Ops team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Current planned switch-over planned for Wednesday 7/8/2020 @ approximately 2:30pm Eastern.

**Comment by jbritt1** [comment]
DNS zone delegation complete.
