### ISSUE TITLE
New SOCKS Documentation 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#95713]
## Description 
SOCKS has undergone a major upgrade and with that, troubleshooting issues has changed. The Platform Support team has been asked to update resources on identifying and resolving issues. 

---

## Definition of Done
Updates to the [SOCKS Troubleshooting + Best Practices](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2633236495/SOCKS+Troubleshooting+Best+Practices) page with additional potential issues, steps to identify, and steps to resolve ---

## Tasks 
_Steps to reach definition of done._ 
- [x] Meet with @ben-allen-oddball to discuss: 
- - New SOCKS high-level overview
- - Common and/or anticipated potential issues
- - Identifying issues 
- - Steps to resolve said issues
- [x] Update documentation including possible screenshots and step-by-step instructions
- [x] Review documentation with reliability team to ensure accuracy
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)

- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Carried over due to holiday break.

**Comment by alyssagallion** [comment]
Waiting on Ben, moved to next sprint.

**Comment by lindsay-insco** [comment]
@GWright321 and I met with Ben and confirmed that at this time, T1 needs no documentation updates. 

I will work with DevOps to gather resources for Tier 2

**Comment by lindsay-insco** [comment]
Updated ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/101832)

**Comment by alyssagallion** [comment]
Closing!
