### ISSUE TITLE
Documentation: Tier 1 AWS Password Reset Process

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#95722]
## Description 

The Tier 1 Team has recently taken on the task of resetting AWS passwords. We want to document the process for Tier 1 folks [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3554377844/AWS+Password+Reset+and+MFA+Removal). 

---

## Definition of Done
All tasks are complete below.
---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Add credential information when logging into the AWS account
- [ ] Add step-by-step process for different tasks we own
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
