### ISSUE TITLE
Issue with data validation in submission `creditorName` and `spouseFullName/last` [FSR]

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#95727]
## Description

[We have an issue with data being submitted to the transform code](https://vagov.ddog-gov.com/logs?query=host%3Avets-api-web-775468d46b-7wpq7%20service%3Avets-api%20container_id%3A484992418a2da8114187da84973c31252c256402904a94643df16c4733bd88ca%20filename%3A0.log%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZK6yrxfAAD1bo9vYiLc6ACk&event=AgAAAZK6yqyKghz1tQAAAAAAAAAYAAAAAEFaSzZ5cnhmQUFEMWJvOXZZaUxjNkFDZgAAACQAAAAAMDE5MmJhY2ItMDUxMC00OGRkLTgwZjUtZDQyM2RlZDZkYzcw&fromUser=true&link_source=monitor_notif&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&to_event=AgAAAZK6yqz_ghz1wgAAAAAAAAAYAAAAAEFaSzZ5cnhmQUFEMWJvOXZZaUxjNkFDcwAAACQAAAAAMDE5MmJhY2ItMDUxMC00OGRkLTgwZjUtZDQyM2RlZDZkYzcw&viz=&from_ts=1729710397627&to_ts=1729710697728&live=false) we've rolled out. After fixing the `addressLine2` issue and adding error logging, [we have seen a couple errors sprinkle ](https://dsva.slack.com/archives/C02EYV9NJFJ/p1729711921885939) in:

```
"The property '#/personalData/spouseFullName/last' of type null did not match the following type: string in schema file:///app/lib/debt_management_center/schemas/fsr.json"
```
```
DebtsApi::V0::FsrFormBuilder validation failed:

The property '#/installmentContractsAndOtherDebts/1/creditorName' of type null did not match the following type: string in schema file:///app/lib/debt_management_center/schemas/fsr.json"

"The property '#/installmentContractsAndOtherDebts/2/creditorName' of type null did not match the following type: string in schema file:///app/lib/debt_management_center/schemas/fsr.json"

"The property '#/installmentContractsAndOtherDebts/3/creditorName' of type null did not match the following type: string in schema file:///app/lib/debt_management_center/schemas/fsr.json"

"The property '#/installmentContractsAndOtherDebts/4/creditorName' of type null did not match the following type: string in schema file:///app/lib/debt_management_center/schemas/fsr.json"
```

We need to fix these issues so veterans an continue to submit 5655's

## Tasks
- [x] Figure out best course of action for creditorName `null` field. Do we do an empty string like with `addressLineTwo`? Do we need to add some validation on the FE?

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required

## Acceptance criteria
- [ ] no more errors for creditorName

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
