### ISSUE TITLE
[VA Notify] Add new variables to code for VA Notify Silent Failures email

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#95738]
## Background Context

To match our email content with the [CAIA spec provided](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/VA-notify-email/3c-action-needed-resubmit-alternative-way.md#email-body) I (Skyler) updated the [VA Notify template content](https://dsva.slack.com/archives/D03BAGN8FPW). As part of that I added two new variables, which now need to be added to the code so that the emails don't fail:
- datesubmitted
- datesubmissionfailed

![Image](https://github.com/user-attachments/assets/bdfc90cb-1259-4f8e-8d38-c89bf9669139)

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Add variables to code for VA Notify email_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Variables have been added so that there are no email failures_

**Comment by jerekshoe** [comment]
Can we change the variable names to `date_submitted` and `date_failed`?

**Comment by skylerschain** [comment]
Updated variable names and updated screenshot above
