### ISSUE TITLE
Platform Console final cleanup

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#95735]
## User Story
As a platform engineer, I want to remove the Platform Console, so that we can eliminate unused and unmaintained systems and reduce operational overhead.

## Issue Description
The [Platform Console](https://platform-console-ui-utility.vfs.va.gov/) is no longer being maintained or used. We have been given approval by Clint to take it down. 

This is the final task (but could be done alongside other deprecation tasks in the Epic).

## Tasks
- [ ] All [Platform Website documentation](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-console) about the Platform Console is removed. (Found in [Confluence here](https://vfs.atlassian.net/wiki/spaces/GS/pages/2308931631/Platform+Console).
- [ ] Look for any more Platform Console information on the Platform Website and remove it.
- [ ] Delete GitHub Teams associated with all environments of Platform Console (this is step 5 [from this doc](https://vfs.atlassian.net/wiki/spaces/OT/pages/2521399636/Deprecate+and+remove+application+from+ArgoCD+and+EKS#Step-5%3A-Delete-GitHub-Teams-associated-with-the-application))
    - [ ] Search for the application [here](https://github.com/orgs/department-of-veterans-affairs/teams?query=dsva-vagov-) (it’ll start with `dsva-vagov-`). 
    - [ ] Open a [new issue](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new/choose) in the github-user-requests repo and ask them to delete the teams. Only [owners](https://github.com/orgs/department-of-veterans-affairs/people?query=role%3Aowner) have permissions to delete teams.
   
## Success Metrics
_Describe what success looks like for this work. Define specific, measurable outcomes that indicate success._

## Acceptance Criteria
- [ ] No mention of Platform Console on Platform Website
- [ ] Request has been made to delete teams. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by Efe-Oddball** [comment]
Reducing the points in this ticket to a 3 and moving to a resolved state
