### ISSUE TITLE
Documentation: Creating DataDog Filters

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#95730]
## Description 
We are owning the process of creating DataDog Filters to [insert reason here]. We need to document the piece of the process we are involved in. 
---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Add step-by-step process to this document (link here)
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Work complete. Closing!
