### ISSUE TITLE
Fix CI Step: Update Unit Test Allow List

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#95748]
The Update Unit Test Allow List step of CI has not worked for some time. When trying to copy files, it is unable to find the destination directory.

## Tasks
- [ ] Diagnose the issue with this step of the workflow.
- [ ] Put a solution in place with thoughts around what caused the problem in the first place, ensuring it won't reoccur
- [ ] Test the workflow to ensure it functions as expected.

## Acceptance Criteria
- [ ] The Unit Test Stability Allow List can update every time the stability review runs.
