### ISSUE TITLE
[UX] 10-10EZR: Create Notifications Ideation Workshop

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#95743]
## Issue Description
Building off the User Generated Content analysis, prep and run a team ideation session leveraging the research conducted to determine potential designs for notifications. 

---
## Tasks
- [x] Create Mural for ideation workshop
- [x] Dry run/practice workshop with UX team
- [x] Collab with PM to invite the right stakeholders

## Acceptance Criteria
- [x] The team has practiced and is ready to run an ideation workshop on notifications

**Comment by RenataKeck** [comment]
Workshop scheduled for 11/21. May require a follow-up workshop or discussions, which will be tracked in the sibling ticket to this one.
