### ISSUE TITLE
CRITICAL: Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#95754]
## Issue Description
Resolve the critical dependabot alert -- https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/148

---
## Tasks
- [x] Assess the alert
- [x] Resolve the alert

## Acceptance Criteria
- [ ] Dependabot is no longer alerting about this vulnerability
---

**Comment by pjhill** [comment]
Latest attempt is here, but it's not going well. The Staging and Production builds keep failing. Error messages appear to be related to garbage collection and memory errors.

**Comment by pjhill** [comment]
Merged that PR, but the alert remains in place because some other package requires a version 6 babel dependency. Working on removing that v6 babel dependency here -- https://github.com/department-of-veterans-affairs/vets-website/pull/32833

**Comment by ericboehs** [comment]
@JoeTice to look at.

**Comment by IGallupSoCo** [comment]
Verified.  This ticket is partially resolved, but further completion will be contingent upon the Node upgrade effort.
