### ISSUE TITLE
Offboard COE, PCPG, VRE

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#95791]
## Issue Description
_The PCPG, COE, and VRE forms will be off-boarded to the IIR team. To prepare for this, we need to collect documentation and processes to onboard the IIR team to these forms._

Suggested location to collect and link to docs is the GH product repo for each form:
- [COE](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/apply-for-home-loan-COE/README.md)
- [PCPG](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/education-career-counseling/README.md)
- [VRE](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/vocational-rehab/README.md)

---
## Tasks
- [ ] Collect product info
- [ ] Collect design info
- [ ] Collect engineering info

## Acceptance Criteria
- [ ] TBD
---

**Comment by steele-lm** [comment]
Collecting info in this working [doc](https://docs.google.com/document/d/13Dm3cPJA_LIWvQFgBK0ShuDGPNdqObwGTUjdO5YNwkE/edit?usp=sharing).
