### ISSUE TITLE
Design spike: Explore requirements for updating Burials overview page

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#95794]
## Issue Description
The [Burials overview/description page]([url](https://www.va.gov/burials-memorials/veterans-burial-allowance/)) doesn't include options to submit in person or get help from an accredited representative. The Pension How to apply page does include these options. Submitting in person or getting help from an accredited rep are options for the Burial application as well.

---
## Tasks
- [ ] Look for current CAIA guidance for pages like this (if it exists), including how to request to have the page updated
- [ ] Draft copy updates, following CAIA guidance
- [ ] Submit ticket to the appropriate team (CAIA?) to have the page updated

## Acceptance Criteria
- [ ] Ticket created to update page
---

**Comment by kristinoletmuskat** [comment]
Hello! Just noting that the process is to submit a CAIA ticket to have this page updated. And process-wise, we can write up draft changes then get CAIA content to wordsmith it according to the style guide. CAIA makes the changes themselves.
