### ISSUE TITLE
Add VA Notify webhook to failure emails

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#95814]
## Issue Description
_VA Notify is adding a web hook to vets-api that will allow teams to track the success or failure of specific email templates. Once available, we need to monitor success/failure for all our "action needed" emails._

Additional work will be done in other tickets to retry the "action needed" email using the address listed in the Veteran's profile (if different).

---
## Tasks
- [x] Add failure email success/failure monitoring to:
   - 686
   - 674
   - 686+674
- [x] Integrate with zero silent failure library 

## Acceptance Criteria
- [x] We know when an "action needed" email fails to reach the Veteran
---

**Comment by steele-lm** [comment]
Blocked: Sanja is exploring a centralized solution, so all teams do not need to implement separate monitoring.

**Comment by humancompanion-usds** [comment]
@sanjabaj2 - For now I would suggest using the VA Notify webhook, which is now available, and logging the emails that fail for your applications. Where you can, I would recommend falling back to sending an SMS to the user's phone number AND to showing the error in the UI of VA.gov (following [this pattern](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status) as best you can). We may decide that doing those 2 things, even given that we cannot verify receipt of the SMS (to my knowledge, I know this is becoming technically possible), is sufficient to declare the failure no longer silent in that we made reasonable attempts to reach the user and they would see the status reflected if/when they sign back into VA.gov.

While I agree a centralized solution is desirable, as you well know, we are a long way away from having such a solution.
