### ISSUE TITLE
Content support for 22-10215 About page and link

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#95813]
## Issue description
The IA spec for updates to VA Form 22-10215 includes the need to create the About page for this form, and adding the link to the digitized form to the 'Find a VA Form' search result.

---
## Tasks
- [ ] Draft content
- [ ] Review 
- [ ] Share with requesting team
- [ ] Update page
- [ ] Copyedit
- [ ] Publish
- [ ] Alert requesting team

## Acceptance Criteria
- [ ] Updated content is live on the site

**Comment by mnorthuis** [comment]
URLs for the two digitized forms are below.  These URLs should be validated before publishing to ensure they are accurate.  Development on these forms is being done outside of OCTO. 

Form 22-10215: https://www.va.gov/school-administrators/85-15-rule-enrollment-ratio/
Form 22-10216: https://www.va.gov/school-administrators/35-percent-exemption/

**Comment by mnorthuis** [comment]
@arianaadili @GovCIOLiz Please let us know when these online forms will be live as soon as you are aware.

**Comment by RLHecht** [comment]
I published these 2 form pages minus the online form. Once that's ready I can add it to the page and republish.

**Comment by laurenvocke-va** [comment]
Reviewed and published both pages. I'll confirm when they're live
