### ISSUE TITLE
Copy of 688 | Retry "action needed" email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#95819]
## Issue Description
This is not due 11/12/24 with the other "action needed" work.

_If a claim fails the backup pathway, an "action needed" email is sent to the email address the Veteran entered into the form. If that email fails, the "action needed" email should be resent to the email address on the Veteran's profile (if different)._

---
## Tasks
- [ ] Add logic to check for a profile email and compare it to the email entered in the form. If different, re-send the "action needed" email to the profile email
- [ ] Add monitoring to alert if the resent email also fails bc the failure is then silent

## Acceptance Criteria
- [ ] "Action needed" email is resent to profile email if it fails to send to the email entered in the form
- [ ] If resend fails, alert as a total failure
---

**Comment by steele-lm** [comment]
This work is blocked pending a conversation with VA Notify about implementing the "action needed" email retry behavior as a VA Notify feature rather than a form-by-form feature.
