### ISSUE TITLE
Pull DataDog PII Incident List for Q2 and 13 2024

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#95827]
## Description 
We were asked by Erika Washburn to collect a list of all DataDog PII Incidents for Q2 and Q3 of 2024. This information will then be sent via spreadsheet to Erika and Ray directly. [Results are documented here](https://docs.google.com/spreadsheets/d/115OJQcXzD_gFCYQC_z27J910NCVdTDekC4RBPYu3-tY/edit?gid=1644646483#gid=1644646483). 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Create a copy of the Platform Support Responses spreadsheet [here](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit?gid=0#gid=0)
- [x] Organize the data so that it reflects DataDog PII Incidents
- [x] Send to leadership (Erika and Ray) 

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Work complete and sent to Erika and Ray. Closing!
