### ISSUE TITLE
Accessibility Check- Coronavirus Content: FAQs, Chatbot

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9583]
Recent updates to the Coronavirus content on va.gov (specifically for the FAQs, and content within the chatbot) have taken place and we would like to do a check on the page to ensure we have not introduced accessibility issues to the experience. 

https://www.va.gov/
https://www.va.gov/coronavirus-veteran-frequently-asked-questions/
https://www.va.gov/coronavirus-chatbot/
https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/
https://www.va.gov/welcome-kit/

Things that have changed:
- [ ] Implemented a new chatbot CTA on the Coronavirus FAQs page
- [ ] Adjusted messaging on FAQs
- [ ] Added a new question around masks
- [ ] Added the COVID-19 alert to the Pre-discharge claim page
- [ ] Updated the chatbot content per new CDC self-checker questions ( #8968)
- [ ] Updated the homepage/global banner messaging
- [ ] Updated the "Quick Start guide" Coronavirus & BaM PDFs with 508-compliant versions ( #9091)
- [ ] Updated content for facility locator messaging ( #9364)

**Comment by FranECross** [comment]
Old/obsolete ticket. Closing
