### ISSUE TITLE
Audit data validation in FSR submissions to catch nil values throwing errors

### ISSUE THREAD

**Issue by penny-lischer** [department-of-veterans-affairs/va.gov-team#95831]
## Description

[We have an issue with data being submitted to the transform code](https://vagov.ddog-gov.com/logs?query=host%3Avets-api-web-775468d46b-7wpq7%20service%3Avets-api%20container_id%3A484992418a2da8114187da84973c31252c256402904a94643df16c4733bd88ca%20filename%3A0.log%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZK6yrxfAAD1bo9vYiLc6ACk&event=AgAAAZK6yqyKghz1tQAAAAAAAAAYAAAAAEFaSzZ5cnhmQUFEMWJvOXZZaUxjNkFDZgAAACQAAAAAMDE5MmJhY2ItMDUxMC00OGRkLTgwZjUtZDQyM2RlZDZkYzcw&fromUser=true&link_source=monitor_notif&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&to_event=AgAAAZK6yqz_ghz1wgAAAAAAAAAYAAAAAEFaSzZ5cnhmQUFEMWJvOXZZaUxjNkFDcwAAACQAAAAAMDE5MmJhY2ItMDUxMC00OGRkLTgwZjUtZDQyM2RlZDZkYzcw&viz=&from_ts=1729710397627&to_ts=1729710697728&live=false) we've rolled out. After fixing the `addressLine2`, `creditorName`, and `spouseFullName/last` issues and adding error logging, there may be others that should be addressed before errors get thrown.

We need to fix these issues so veterans an continue to submit 5655's

In one instance, Andrew was able to verify that the frontend was setting a default string pre 'transform and submit'. Might be good to revisit the old FE implementation and see if they have use cases that we're missing. 

## Tasks
- [ ] Audit the FE to see what fields had default values being set before the logic switch to BE
- [ ] Add the default values to BE found in the audit that are missing
- [ ] Add unit tests

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] no more errors for missing default values

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by Tom-Davis** [comment]
No errors at this time, closing.
