### ISSUE TITLE
Document current front end performance data

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#95842]
Looking forward to a front end performance initiative, we want to document all existing performance data we have. This includes the ability to use the webpack bundle analyzer on any individual app, as well as any links to lighthouse data reports.

## Tasks
- [ ] Create a confluence document to collect up any frontend performance data we have available.
- [ ] Add lighthouse data and any webpack bundle analyzer instructions.
- [ ] Share document with Clint and/or Jeff as necessary.

## Acceptance Criteria
- [ ] A comprehensive document with all current frontend performance data is available for reference.

**Comment by AshleyGuerrant** [comment]
Closing this ticket as stale, it was written before all of the tickets in the[ Improve Frontend Performance epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/109342) and is duplicated in tickets in that epic.
