### ISSUE TITLE
Documentation: Document Types of LightHouse Tickets Platform Support Receives

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#95841]
## Description 
We have noticed an influx in tickets for LightHouse related issues. To ensure that there is cross-training on our team between Tier 1 members and to ensure the best experience for LH folks, we want to document the best way to handle each ticket type. The documentation will live [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3566764042/LightHouse+Platform+Support+Ticket+Types). 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Collect and add all LH ticket types from Tier 1 members
- [ ] Add step-by-step process for each ticket type that is specific to this process (does not include the general steps that are already outlined in Ticketing Best Practices that apply to all tickets)
- [ ] Add how to handle LH Slack accounts not being able to access DSVA Slack workflows, there is a way to connect them but need to document it on the page mentioned above. Otherwise, they can't use the Slack Support Bot.
- [ ] Send the finished document [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3566764042/LightHouse+Platform+Support+Ticket+Types) to review with the Tier 1 team and Alyssa
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Mistakingly put this in the wrong sprint.

**Comment by alyssagallion** [comment]
Work no longer needed. Current processes now cover these types of tickets. Closing!
