### ISSUE TITLE
Attempt to automate PR check for existing codeowners on vets-website

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#95884]
Vets-api has implemented a workflow that will deny a pull request if the files in the PR do not have an existing codeowners entry. While vets-website does not plan to be as granular with theirs, we should do this for ensuring at least each directory has one codeowner.

## Tasks
- [ ] Attempt to lift the workflow from vets-api to vets-website and modify it to be directory-based
- [ ] If Task 1 does not work out, try and craft a solution for this issue.

## Acceptance Criteria
- [ ] New code can no longer be committed to vets-website without a codeowner attached.
