### ISSUE TITLE
Assist IIR Team w/SVP

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#95885]
## Issue Description
IIR (Innovation, Iteration and Run) team has a new Scroll Viewport site called [Memo Project - IIR](https://memo-project.scrollhelp.site/mpi/). Platform Content team will be available to answer questions as they emerge.

## SME on IIR

- Pete Egan

---
## Tasks
- [x] PC team members offer guidance to IIR team as needed

## Acceptance Criteria
- [x] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by BSmolensky** [comment]
This seems more like an Epic and then the actual instances of work with the team would become individual tickets (once needed). Just a thought.

**Comment by jknipes** [comment]
closing as _done_.
