### ISSUE TITLE
[BE] 10-10CG - BUGs: Investigate JSON Schema 500 errors on #create controller

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#95897]
## Background
Reviewing for `#download` errors on the 10-10CG form, it was found that there are some different 500 errors coming up on the V0::CaregiversAssistanceClaimsController#create resource.  They are referring to some sort of JSON Schema issue.
We need to investigate these errors, determine root cause and if there is any solution we can put in place to either resolve on our side, or guide the user to avoid the errors.
We may also need to work with the CG team to confirm the schema requirements match up.

## Resources
- [Datadog log with schema errors](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aeks-prod%20service%3Acaregiver-application%20-status%3Aok%20-resource_name%3A%28%22POST%20403%22%20OR%20%22V0%3A%3ACaregiversAssistanceClaimsController%23download_pdf%22%29%20error.type%3A%22JSON%3A%3ASchema%3A%3AReadFailed%22&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=service-entry&spanViewType=errors&storage=hot&traceQuery=&view=spans&start=1728651865818&end=1729861465818&paused=false)

## Tasks
- [x] Investigate the errors
- [x] Determine root cause
- [x] Review findings with team to determine whether there are any options for resolution

## Acceptance Criteria
- The team will have an idea of the issue and have discussed a plan to resolve

**Comment by coope93** [comment]
Spent some time looking into this today. These all look to be caused by this error: 

`Read of file at /usr/local/bundle/cache/ruby/3.3.0/gems/ruby-saml-1.17.0/lib/schemas/2909da20-6ab0-595f-93cf-fdc3e923cdd2 failed.`

I want to note that the uuid in the directory path is consistent between all failures `2909da20-6ab0-595f-93cf-fdc3e923cdd2`. 

This error is occuring in the saved_claim model  and form_matches_schema method (which is shared with other claims/forms), and it looks like that utilzes a json-schema gem. 

Additionally, it looks like similar errors are happening for another team is running into the same issue. [Their ticket is here.](https://github.com/department-of-veterans-affairs/octo_watchofficer/issues/259)

Planning to look at implementing some more logging in our form validation logic to see if we can get more context on the error.

**Comment by coope93** [comment]
[This datadog query](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aeks-prod%20-status%3Aok%20error.type%3A%22JSON%3A%3ASchema%3A%3AReadFailed%22&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=true&graphType=flamegraph&historicalData=true&messageDisplay=inline&netviz=sent_vol%3A%3A%2Ctcp_r_pct%3A%3A%2Crtt%3A%3A&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=service-entry&spanViewType=metadata&storage=hot&traceQuery=&view=spans&start=1729021375897&end=1730230975897&paused=false ) shows intermittent occurrences for seven different forms with distinct service tags having this same issue in the `form_matches_schema` method in the `SavedClaim` class when using the json-schema gem. [This chart shows the forms and their occurrences](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aeks-prod%20-status%3Aok%20error.type%3A%22JSON%3A%3ASchema%3A%3AReadFailed%22&agg_m=count&agg_m_source=base&agg_q=service&agg_q_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&netviz=sent_vol%3A%3A%2Ctcp_r_pct%3A%3A%2Crtt%3A%3A&query_translation_version=v0&shouldShowLegend=true&sort=time&sort_m=&sort_m_source=&sort_t=&spanType=service-entry&spanViewType=metadata&storage=hot&top_n=10&top_o=top&traceQuery=&view=spans&viz=timeseries&x_missing=true&start=1729021550499&end=1730231150499&paused=false). It looks like we are intermittently unable to load the schema file to validate against.

**Comment by coope93** [comment]
Reached out to platform support in slack to see if they have any insight on this. [slack link](https://dsva.slack.com/archives/CBU0KDSB1/p1730231639585529) and the [github issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96086).

**Comment by coope93** [comment]
I posted this in the slack thread, but this is the current update on the investigation into these errors: 

At the moment, the best I can figure is something in the gem update on 10/10 caused something to break with how we are reading in the schema file. Still not sure what exactly. We had previously updated the `SavedClaim` class to use the `fully_validate_schema` method [here](https://github.com/department-of-veterans-affairs/vets-api/pull/18554/files), and I suspect that may be where the problem lies since the SavedClaim 's are the only place we are using that method vs using `fully_validate`, which we use in other places which do not seem to have the same issue. That's my best guess at the moment for this issue. Not sure on the best next steps, however.

**Comment by coope93** [comment]
The slack link referenced above with Platform support has the most recent information about this issue. The current plan is to merge in the additional logging PR to see if it gives us more context. It does seem like the issue lies in the gem update and something being incompatible, but we have yet to discover the root cause. This issue is consistent for any claims classes that inherit from `SavedClaim`.

**Comment by coope93** [comment]
@allanto-ah I'd like to turn the flipper toggle on to turn off the `fully_validate_schema` method  in staging. We can then submit some 10-10CG's and validate that they didn't fail or anything before we turn it on in prod.

**Comment by allanto-ah** [comment]
@coope93 Yeah that sounds good to me

**Comment by allanto-ah** [comment]
Environment: Staging

Verified with the flipper toggle on that there are no regression issues. Submissions work as expected. E2E slack [test](https://dsva.slack.com/archives/C02MJCT59S7/p1731959358565449)

**Comment by coope93** [comment]
Turned on the flipper toggle to turn off the `fully_enable_schema` call for saved_claims this morning. As of this morning we are still seeing a few of the errors, so we plan to monitor it today to see if the total is lower or not. Watching [these logs](https://vagov.ddog-gov.com/logs?query=env%3A%22eks-prod%22%20service%3Avets-api%20%40message_content%3A%22Error%20during%20form%20validation%21%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&source=monitor_notif&storage=hot&stream_sort=desc&viz=stream&from_ts=1731421142048&to_ts=1732025942048&live=true). Next steps may be looking into replace the `json-schema` gem with another gem that is more actively maintained to do the json schema validation. Another team mentioned they may have capacity to take that work on. 

Another potential band-aid for the 10-10 team would be to implement some sort of small retry logic for validating the schema, which would allow for better limiting the errors by retrying the failures that are raising exceptions. It would still have the errors, but the impact to the Veterans should be lessened.

**Comment by coope93** [comment]
EZR ran into the same error when trying to validate the json schema [here](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aeks-prod%20error.type%3A%22JSON%3A%3ASchema%3A%3AReadFailed%22%20-service%3Avets-api&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=4068701367517623081&spanType=service-entry&spanViewType=errors&storage=hot&timeHint=1731946823520&trace=AwAAAZNAEz9glV8YwwAAABhBWk5BRTByLUFBQ190UUxTZG5XLUl4c0UAAAAkMDE5MzQwZGMtNGRkNi00ODJmLThjOWYtNDVlM2FjZmQ0YzgwAACG2A&traceID=296018036423739573&traceQuery=&view=spans&start=1731944570624&end=1732030970624&paused=false). It really looks like it's a bug in the gem somewhere.

**Comment by hdjustice** [comment]
We got another one of these for the [EZ form](https://vagov.ddog-gov.com/apm/traces?query=%28%28env%3Aeks-prod%29%20OR%20%28env%3Aeks-prod%29%20OR%20%28env%3Aeks-prod%29%20OR%20%28env%3Aeks-prod%29%29%20status%3Aerror%20%40http.status_code%3A500%20resource_name%3A%28%22V0%3A%3ACaregiversAssistanceClaimsController%23create%22%20OR%20%22V0%3A%3AHealthCareApplicationsController%23create%22%29%20error.type%3A%28%22JSON%3A%3ASchema%3A%3AValidationError%22%20OR%20%22JSON%3A%3ASchema%3A%3AReadFailed%22%20OR%20%22JSON%3A%3AParserError%22%29&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=true&graphType=service_map&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=desc&spanID=3745334040915856235&spanType=all&spanViewType=errors&storage=hot&timeHint=1732109458738&trace=AwAAAZNJxN0yku4EngAAABhBWk5KeE9pSEFBQ0ZuOG9jZGdpZ0ZZc0YAAAAkMDE5MzQ5YzYtMDNkOC00MGUxLTk3NzItYzIwNTI1YTM4OWRjAAAA4g&traceID=399662204049692825&view=spans&start=1730433600000&end=1732111500000&paused=true) this morning as well.

**Comment by coope93** [comment]
@allanto-ah Trying one more thing on our end before we close this one out. https://github.com/department-of-veterans-affairs/vets-api/pull/19571 adds the ability for the system to automatically retry validating the schema if it fails the first time. It will attempt it a total of 3 times. I think as far as QA we'll want to turn it on in staging and validate that we can still successfully validate? Since the underlying issue is flaky, I'm not sure how we validate it when it throws an exception the first time. But as long as it still works I think we are good.

**Comment by allanto-ah** [comment]
@coope93 Sounds good, yeah we can turn it on in staging and try to submit to validate. As you said as long nothing is broken, we should be good!

**Comment by coope93** [comment]
@allanto-ah And to clarify, it calls this validate _before_ it enqueues the background jobs. So if it does error, a generic error response should get returned the browser and displayed.

**Comment by coope93** [comment]
I turned the retry flipper toggle on in production this morning. I will monitor the logs to see if it is used at all and see if it helps or not.

**Comment by coope93** [comment]
Marking this as done. Another team has a ticket to replace the gem that is causing the error, and we have a band aid fix in for the 10-10CG that we hope will make it a little better until then.

**Comment by coope93** [comment]
I wanted to note that since merging and turning on the retry logic for this schema validation check, we have had 0 errors from it 🥳 . [Datadog link with error occurrences](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aeks-prod%20service%3Acaregiver-application%20-status%3Aok%20-resource_name%3A%22POST%20403%22%20error.type%3A%22JSON%3A%3ASchema%3A%3AReadFailed%22&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=true&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=service-entry&spanViewType=errors&storage=hot&traceQuery=&view=spans&start=1733148058687&end=1733320858687&paused=false) and another [Datadog link with the logs for the retries](https://vagov.ddog-gov.com/logs?query=env%3A%22eks-prod%22%20service%3Avets-api%20%40message_content%3A%2A%22Form%20validation%20succeeded%20on%20attempt%22%2A&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&source=monitor_notif&storage=hot&stream_sort=desc&viz=stream&from_ts=1733148012270&to_ts=1733320812270&live=true). So the issue in the schema validation is still failing, but it is retrying and succeeding which then allows the request to succeed and the Veterans to not get an error here.
