### ISSUE TITLE
Send Received email for backup path submissions

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#95908]
## Issue Description
As a Veteran I want to receive an email when my submission was received by VA. It isn't important to me how VA processes it, I am expecting an email so that I can feel confident VA is working on my application.

## Tasks
- [ ] 

## Acceptance Criteria
- [ ] A received email is sent to the Veteran when their submission uses the backup path

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mayacarrolluxa6** [comment]
Designs

Prototype
https://www.figma.com/proto/f0CuXrBUVs86NDm6cqmduK/(526ez)-Submission-Experience?page-id=1%3A39&node-id=72-362090&p=f&viewport=846%2C534%2C0.27&t=bXqgNASm9ikx6TZn-1&scaling=scale-down&content-scaling=fixed

Mockups
https://www.figma.com/design/f0CuXrBUVs86NDm6cqmduK/(526ez)-Submission-Experience?node-id=1-39

![Image](https://github.com/user-attachments/assets/c3679944-e54b-486a-9fe3-5c2481fd4e5d)

**Comment by aurora-a-k-a-lightning** [comment]
Received email template has been updated to handle Claim Id conditionally in VANotify staging.
Make sure to release these changes to VANotify production alongside releasing the Received Email in the Backup Path feature (when you turn on the feature flag).
The feature flag to turn on is:
```
disability_526_send_received_email_from_backup_path
```

![Image](https://github.com/user-attachments/assets/27ac291b-2094-4940-b352-33d6718aafb0)

**Comment by aurora-a-k-a-lightning** [comment]
[Datadog Dashboard](https://vagov.ddog-gov.com/dashboard/xjp-pyw-j42?fromUser=false&p=1&refresh_mode=sliding&from_ts=1738111551597&to_ts=1738197951597&live=true) to track the Received emails, broken into total, primary, and backup paths.

**Comment by aurora-a-k-a-lightning** [comment]
Testing on Staging:
1. I sent the backup path received email to myself and it looks exactly as the mock ups above

![Image](https://github.com/user-attachments/assets/fbc6d312-9bc8-446e-8358-b6ba7893ca20)
Fun fact i received it at 12:34PM :)

2. Production is working well, no regression errors. Since we moved/refactored the trigger, I wanted to be sure we're still seeing it and that it is segmented correctly. The Primary Path graph should match the Total graph until we turn on the Backup Path Received Email.

![Image](https://github.com/user-attachments/assets/ac9d0b4f-a4e0-4253-9d31-294f74b68151)

3. As predicted, we can't trigger the Datadog Dashboard to check the monitoring for the Backup Path, however, I ran through a submission end-to-end and saw the new logging working on the primary path. I'm going to ask around if we can trigger the logging manually to see the dashboard working properly - I haven't been able to yet.
 
Confidence level is high for releasing this on PRODUCTION 2/4/2025!
