### ISSUE TITLE
DAP Access for tracking eBenefits Analytics

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#95927]
## Background
After consulting the Analytics team about tracking eBenefits, it seems that GA4 is not appropriate for accurate tracking and instead [we should use DAP to monitor traffic on this site](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93144#issuecomment-2422695523).

See [Get Started with DAP](https://digital.gov/guides/dap/get-started-with-dap/#step-1-register-as-a-dap-user) documentation for reference.

## Tasks
- [x] Email the DAP team at [dap@gsa.gov](mailto:dap@gsa.gov) to request a registration form. We will need to use our va.gov email addresses.
- [x] Create a Google Account, connected to our va.gov email addresses
- [x] Complete the registration form
- [x] Gain approval from the agency’s DAP point of contact
- [x] Confirm access to DAP, via https://analytics.usa.gov/

## Acceptance Criteria
- [x] Through access to DAP, we will be able to monitor eBenefits traffic.

**Comment by oddball-lindsay** [comment]
Sent an email requesting the registration form for both myself and @jfinnerty13.

**Comment by oddball-lindsay** [comment]
@jfinnerty13 turns out we need to first associate our va.gov email addresses with a Google account. 

Eric Moreno responded to my email with what seems to be updated instructions for DAP access. And the first step has a link to create a Google account, associated with your va.gov email. 

I just made my Google account for my va.gov email -- when you're done making yours, we can respond back to Eric letting him know we are now ready for the registration form. Feel free to respond to him if you get to that before I sign on. Otherwise just lmk when you're done and I'll email him on behalf of both of us!

**Comment by oddball-lindsay** [comment]
Step 2 of the instructions ended up being unclear -- are we good with the existing email? Or do we also have to fill out the linked questionnaire? Seems like an either/or situation, asked Eric for guidance on next steps for us.

**Comment by oddball-lindsay** [comment]
@jfinnerty13 next step is to complete this form https://vaww.oit.va.gov/services/dap/dap-access-request/

Our current contract ends on 8/6/25 :)

**Comment by oddball-lindsay** [comment]
Confirming I'm able to access the "DAP" section of GA4: https://analytics.google.com/analytics/web/#/p393249053/reports/intelligenthome

I set up an ["eBenefits (DAP)" report](https://dsva.slack.com/archives/D05MLDP68AH/p1730857182371579) mirroring the configuration we have it in our [existing GA4 reporting](https://analytics.google.com/analytics/web/?pli=1#/analysis/p419143770/edit/s8Td-mYMQoKwisXggjlrqw) but the session count is just as low as it has been in our existing report -- less than 5 per day.

Good news: we have access,
Bad news: doesn't look like reporting is any different than what we were seeing in GA4 before. 

Is it possible traffic really is just that low?

**Comment by oddball-lindsay** [comment]
Unlikely traffic is that low, because of what we saw in UA3 (~50-200 users per day). It may not be the best use of folks' time to try and correct eBenefits tracking in GA4 since it is a site/tool that we're moving away from. Will recommend to Jen that we focus on the success of our products on VA.gov and move away from closely monitoring the eBenefits site.
