### ISSUE TITLE
[CDP] Temporary hurricane banner update (complete prior to 12/09/2024)

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#95923]
## Issue Description
Follow on ticket for: **Hurricane Helene and Hurricane Milton Banner [#94712](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/94712)**

This temporary alert is set to expire on `debt-balances` and `copay-balances` on 12/09/2024; the alert on the summary page will revert to the generic assistance with disaster relief on the same day. We need to remove the unused code once the alert expires, or decide on another direction. 

## Tasks
- [x] Remove unused code for alert
- [ ] Investigate CMS options for injecting alerts for future temporary use
- [ ] Open ticket for CMS implementation

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] Temporary alert has been removed
- [ ] Process established for future temporary alerts

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by Dr-Pongo** [comment]
> We can leave the banner in place and remove the Dec 9th end date entirely.
- Denise 

We can update the existing alert with the new language and remove the old one. Seems like it could still be worthwhile to investigate the CMS option too!
