### ISSUE TITLE
Content Edit: #95642 ID.me page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#95935]
## Issue Description
Per footer ticket [95642](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?pane=issue&itemId=84547507&issue=department-of-veterans-affairs%7Cva.gov-team%7C95642), Identity Team would like to update the information on the [ID.me page ](https://depo-platform-documentation.scrollhelp.site/developer-docs/id-me).

---
## Tasks
- [x] Copy update draft from ticket 95642 into Content Team Draft space
- [x] format document
- [x] edit document
- [x] review with author
- [x] prepare for deployment

## Acceptance Criteria
- [x] All tasks complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
