### ISSUE TITLE
Content Edit: #95645 Update DS Logon page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#95938]
## Issue Description
Per ticket [95645](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?pane=issue&itemId=84547529&issue=department-of-veterans-affairs%7Cva.gov-team%7C95645), Identity Team needs to update the DS Logon page. The team has provided a draft of the update in ticket 95645.

---
## Tasks

- [x] Copy update draft from ticket 95645 into Content Team Draft space
- [x] format document
- [x] edit document
- [x] review with author if needed
- [x] prepare for deployment

## Acceptance Criteria
- [x] All tasks complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by BSmolensky** [comment]
moved into current sprint due to available capacity.

**Comment by BSmolensky** [comment]
Document has been edited, formatted, and corrected. Waiting on SME to get back to me regarding an alternative for a personal name and personal email address listed as a contact in the doc. 

Since this is not a LB issue, I plan to deploy this page this afternoon. Hopefully I will hear from the SME before then. At which point I will correct the issue before deployment. If, however, the SME needs more time to find an alternative, I will deploy the page as is and create a ticket in our backlog to replace the personal name/email.

**Comment by jknipes** [comment]
Closing as _done_
