### ISSUE TITLE
Reorder Slack Canvas

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#95965]
## Issue Description
We need to reorder the links and headings in our public channel Canvas (#platform-content) to address priorities and for better readability.

## Related ticket

- [90590](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90590)

---
## Tasks
- [x] using the test Canvas in #content-chats-1531, rearrange links and headings
- [x] review changes with Content team
- [x] paste changes into public channel Canvas

## Acceptance Criteria
- [x] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
moving into current sprint to continue work from 90590

**Comment by jknipes** [comment]
Closing as _Done_
