### ISSUE TITLE
[DESIGN] Update Check-in to tell Veterans to go up to MSAs 5 min after appointment time

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#95964]
## Background

_(Note: this is separate from the "Check-in with MSAs after eCheck-in" initiative)_

To help with problems around Veterans going up to staff too late/being in the wrong waiting room, Veteran-facing and staff-facing UX and Kristen have determined we should decrease the 15 min time  to 5 min after their appointments, as far as when we tell Veterans to go up to the desk if they haven't been called back.

Kristen will let IVC know to make sure there aren't any concerns with this.

Once confirmed, we need to update Check-in to tell Veterans to go up to MSAs 5 min after appointment time, instead of 15 minutes.

## Tasks

- [x] Update Check-in designs to tell Veterans to go up to the desk if they haven't been called back 5 minutes after their appointment time
- [ ] Review with UX and Kristen
- [ ] Once confirmed, place designs in "Waiting for release"
- [ ] Once confirmed, update "latest designs" in Figma page

## AC
- [ ] Check-in designs are updated
- [ ] Reviewed with UX and Kristen
- [ ] Designs placed in "Waiting for release"
- [ ] Check-in "latest designs" Figma page updated with change

**Comment by zach-park** [comment]
@cgednalske , here is the feature page: 
https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4975-5574&t=uhbv0FYeHYBquFBx-1

Thank you!

**Comment by zach-park** [comment]
@cgednalske @StevenStraily , I updated the Figma file based on yesterday's feedback and decision from the UAE UX sync meeting:
https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=5030-6729&t=neLai69LeHleS9Cv-1

And it is ready for validation. Thank you!

**Comment by cgednalske** [comment]
Great! Looks like everything is resolved 👍 🎉

**Comment by cgednalske** [comment]
@zach-park make sure you also update this in the Latest Design page, as well as move the feature to "Waiting for release" (I've started adding this as AC in the tickets btw ☝ so we can make sure we're not forgetting to make these updates)

**Comment by zach-park** [comment]
Updated the latest design page and also moved from the feature page to the waiting to release page. Thank you!

**Comment by cgednalske** [comment]
@zach-park can you also make sure the Figma page is included in the [engineering ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96034)?

@loripusey btw this is a change for Check-in in general to help out with the problem overall - not specific to the "Check-in with staff after eCheck-in initiative." Not sure if this was clear or not.

**Comment by loripusey** [comment]
Yep, I got that, but thanks for clarifying
