### ISSUE TITLE
Fix issues with 2122(a) PDF generation

### ISSUE THREAD

**Issue by opticbob** [department-of-veterans-affairs/va.gov-team#95975]
## Background
@jvcAdHoc has discovered some additional fixes that need to be made to the backend to ensure that all paths through the appoint a rep process can generate a PDF.

## Tasks
- [x] Convert middle names to middle initials on the backend
- [x] Ensure that picking just a org works successfully
- [ ] ~~Ensure that picking a rep with one org works successfully~~This turned out to be a frontend issue, not a backend one.
- [x] Add `individual_type` to the original representative model
- [x] Conditions of appointment isn't in the payload, make sure we're not referencing it

## Acceptance Criteria
- [x] A data object generated by the staging front end will be able to generate a PDF in local development once the `id`s of any representative or organization are changed to what is present locally.

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by opticbob** [comment]
4 out of 5 tasks are done here, tomorrow I need to clarify the remaining (Ensure that picking a rep with one org works successfully) one with @jvcAdHoc to make sure I know what problem he was anticipating.

**Comment by opticbob** [comment]
This has been submitted to @jvcAdHoc for the second round of review.

**Comment by opticbob** [comment]
This has been submitted to @jvcAdHoc for another round of review.  The end product should be a lot more robust than it was before.

**Comment by opticbob** [comment]
This has been merged!
