### ISSUE TITLE
Notify on failure of 4142s

### ISSUE THREAD

**Issue by comaurice** [department-of-veterans-affairs/va.gov-team#95980]
## Value Statement

**_As a_** Veteran

**_I want to_** notified when my 4142 submission fails to submit

**_So that_** I am apprised and can take action to mail it in directly

---

## Background Context

- Subsequent work following the 4142 investigation and submission tracking

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] Veteran receives an email when the 4142 submission fails
- [ ] Failure is logged and available for remediation

## Designs and Build Notes

- Add here

### Enablement team (if needed)
@ member of team

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [ ] Scan table SecondaryAppealForms for negative statuses
- [ ] Get needed email templates set up in staging and prod
- [ ] Send notifications to needed parties with information to resolve the issue
- [ ] Mark the record when the notification is sent

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design
