### ISSUE TITLE
Discovery for baseline metric to capture satisfaction before and after copay balance update (part 1)

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#95996]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Review of qualitative feedback left by Veterans on dissatisfaction with copay balance not updating in time.  
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [x] Request Medallia reports for a certain time
- [x] Create a coding manual
- [x] Comb through reports and code for dissatisfaction with copay balance not updating in time. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [x] A numerical value on the number of entries that can be used to compare to a new value after the launch of the updated copay balance, or a percentage

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by charlottecesana** [comment]
Roughly 1/3 of qualitative feedback left on the debt portal pages can be attributed to this issue - specifically for the most recent quarter.
