### ISSUE TITLE
[Business Optimization] Update and rebuild Health Services Intake page for PAO input [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9599]
## User Story or Problem Statement
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement intake for for PAO to complete and validate prior to data discovery is complete_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[VISN 4 Content Stack Spreadsheet](https://drive.google.com/drive/folders/1f_PRAt67ccYNm5DkJiAKwINsSX_S5_4o)
[Menu and Page checklist](https://drive.google.com/drive/folders/1QliZFSkQHEruGgjOGRihG8tohYxswjm1)
[Pittsburgh Pilot Website](https://va.gov/pittsburgh-health-care/)

## Tasks
_Optimize and update HSL and Facilities Data intake sheet for PAO to upload and complete_
- [ ] VA Eastern Oklahoma health care
- [ ] VA Oklahoma health care
- [ ] VA Cheyenne health care
- [ ] VA Eastern Colorado health care
- [ ] VA Grand Junction health care
- [ ] VA Montana health care
- [ ] VA Salt Lake City health care
- [ ] VA Sheridan health care

## Acceptance Criteria
_Validation that all pages are accessible and certain cells are locked for information use only_
*VA Eastern Oklahoma health care
*VA Oklahoma health care
*VA Cheyenne health care
*VA Eastern Colorado health care
*VA Grand Junction health care
*VA Montana health care
*VA Salt Lake City health care
*VA Sheridan health care
