### ISSUE TITLE
QA for Appoint a Rep MVP (Lindsay)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96019]
## Background
Please reference this [Team QA for Appoint a Rep MVP](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1729288707438/0467e91be142faef94d26132b88fa3319939529d) Mural for assignments and guidance.

## Tasks
- [ ] Review the screens within your assigned chapter, via your specified devices
- [ ] Notate QA findings directly in the Mural -- one card per finding

## Acceptance Criteria
- [ ] You have reviewed the screens within your assigned chapter and have reported any QA findings

**Comment by oddball-lindsay** [comment]
- [ ] Rep Selection chapter - mobile Safari (auth)
- [ ] Rep Selection chapter - mobile Safari (unauth)
- [ ] Rep Selection chapter - desktop Safari (auth)
- [x] Rep Selection chapter - desktop Safari (unauth)

- [ ] Authorizations chapter - mobile Safari (auth)
- [ ] Authorizations chapter - mobile Safari (unauth)
- [ ] Authorizations chapter - desktop Safari (auth)
- [ ] Authorizations chapter - desktop Safari (unauth)

**Comment by oddball-lindsay** [comment]
Keeping this open to cover for Holden, will tackle that tomorrow.

**Comment by oddball-lindsay** [comment]
- [ ] Claimant chapter - mobile Safari (unauth)
- [x] Claimant chapter - desktop Safari (unauth)
- [ ] Claimant chapter - mobile Safari (auth)
- [ ] Claimant chapter - desktop Safari (auth)


- [ ] Veteran chapter - mobile Safari (unauth)
- [x] Veteran chapter - desktop Safari (unauth)
- [ ] Veteran chapter - mobile Safari (auth)
- [ ] Veteran chapter - desktop Safari (auth)
