### ISSUE TITLE
[TASK] Content on CHAMPVA claim form

### ISSUE THREAD

**Issue by bmrea1** [department-of-veterans-affairs/va.gov-team#96016]
## Issue description
The IVC forms team is digitizing the CHAMPVA claim form and they need content support. This is a ticket to track the ongoing content work on the CHAMPVA claims form. 

[Here's the intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82503)

---
## Tasks
- [x] Assess request
- [x] Share content recommendations pre-midpoint 
- [x] Post-midpoint and pre-research content recommendations 
- [x] Post-research content recommendations
- [ ] Post-staging updates
- [ ] Share with requesting team

## Acceptance Criteria
- [ ] Updated content is live on the site
- [ ] Product has launched
- [ ] Feedback has been shared with requesting team

## Configure this issue
- [ ] _Attach to an Epic or Intake if this is related to other work_
- [ ] _Label with Originator/Team (product team or stakeholder requesting support)_
- [ ] _Label with Open Date_
- [ ] _Label with Estimate (level of effort expected for this ticket)_
- [ ] _Add assignee name to each task they will complete (if known)_
- [ ] _Update the status to reflect where this work is in the pipeline (in progress, backlog, etc.)_

**Comment by aliyahblackmore** [comment]
This work started a few months ago. I provided a first round of content support and recommendations pre and post midpoint review. 

They're done with their research and will begin their pre-staging review updates.


**Update here:**

- I'm joining the first half of the teams research roadmapping session to listen in. They'll review the form recommendations, assess impact, and prioritize next steps.

- Jamie shared their [research synthesis ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/champva/10-7959a/user-research/10-7959a-champva-claims-research-report%20report.md)earlier today.

- It seems like some of the feedback in the synthesis connects to a few of the pre-research questions https://github.com/department-of-veterans-affairs/va.gov-team/issues/82503#issuecomment-2195859219. We can assess what questions they team may still need answers on from their SMEs.

- And I'll check in with the team again about whether people with Kaiser can use the online form (discussed in 9/19 meeting).

**Comment by aliyahblackmore** [comment]
Product team reviewed their research findings and began scoring each recommendation for impact (i.e. prioritizing when the update may happen). 

**I added a few follow up questions and comments about the recommendations in their [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1728573604115/353d2bc111ecf4c0e81e8fa30f9bd232d6e8c379):**

1- Intro page -  finding # 2 shares that participants read the requirements in depth. But the recommendation is that the screen should include all of the requirements and supporting document information. The form intro page does currently include all of the form requirements and supporting documents- curious to know if there were specific piece of information participants didn't understand (like any of the supporting documents)?

2- Additional info component on upload screen - initial content rec pre-research was to remove this. But there were some recommendations on adjustments ([Figma comment](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1728573604115/353d2bc111ecf4c0e81e8fa30f9bd232d6e8c379)) if the team wanted to move forward with it. Was there any feedback that showed participants want this information here?

3- Codes for billing - discovery work on number of digits for codes.

**Comment by aliyahblackmore** [comment]
Update here:

Rachel asked for a review of the some sponsor/rep adjustments to the beginning of the forms - [Figma file](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=2571-37695&node-type=frame&t=KbDvqhMxPk47BcSx-0). I reviewed and confirmed with them that as long as it's true that someone selecting "Veteran a claim for my spouse/dependent" is always the Sponsor, then the updated flow works.

I also re- tracked a few other pre-midpoint notes/comments (we can revisit some of the SME/accuracy things after staging, but before the incremental launch). 

[See intake request for notes on the other design/content comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82503)

**Comment by aliyahblackmore** [comment]
Moving this to blocked for now. The team has an upcoming staging review.

**Comment by aliyahblackmore** [comment]
**Update here after 12/12 IVC sync:**

-TBD staging review in January.
- I noted an outstanding question around Kaiser Permanente insurance and claims. 
   -Syd previously mentioned online form wouldn't allow claims for this insurance, but the team planned to revisit this. Jamie will look into this again and ask SMEs. We can adjust the content on the form intro screen, upload screen (tbd), and static page once they get an answer.
- Since multiple claims will be a post-MVP update, I'll plan to take a look at updates next week.
- And I [tracked a note in Figma](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv?node-id=2613-68001#1062797371) re: submitting claims and dates of service on the multiple claims design. I'll take a look at the form intro page/list&loop and assess content needs there.

**Comment by aliyahblackmore** [comment]
(Cross posting from intake) 

**Update on MVP Kaiser Permanente question:**

Just tracking some notes here about Kaiser Permanente. If the product team hasn't confirmed ahead of staging, we can revisit and adjust before MVP launch.

- **If the team won't allow beneficiaries with this insurance to use the online version of the form**, we'll likely need to adjust the static page entry point and form intro page to say that they'll need to use the PDF version of the form at this time.
    Note: If you have Kaiser Permanente insurance, you'll need to file a claim using the PDF version of our form.
- **If they will allow beneficiaries with this insurance to use the online version of the form**, the current upload screens will need the details specific to submitting a claim with Kaiser Permanente. Those details are currently on the [static page](https://www.va.gov/resources/how-to-file-a-champva-claim/). And this can happen in one of these ways.
     - [If this is feasible from an engineering/design perspective] Show Kaiser Permanente details conditionally. If someone enters Kaiser Permanente as their insurance provider earlier in the flow, show them an upload screen with the details.
     - [If you all can't show these details conditionally] Update the upload screen and with Kaiser Permanente details.

**Update here on post-MVP multiple claims updates:**

- I'm planning to take a look at the multiple claims flow adjustments later this week.

- If there are any outstanding items (i.e. questions) that content needs to revisit, we can plan to circle back ahead of MVP and adjust along with the Kaiser Permanente question on the MVP form. Or we can circle back to these design updates post-MVP.

**Comment by aliyahblackmore** [comment]
**Updates on multiple claims flow:** 

I started to review the [screens](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=2613-68001&t=b9LblxQ5g5HeH0j2-4) yesterday and added content recommendations. But there are a few outstanding product / SME questions, so we might need to revisit some of these screens in early January and adjust them before these updates launch.

:notebook:**Here's a summary of some of the updates and questions**

- It actually looks like the content needed to cover two use cases for multiple claims:
    - Multiple appointments on one day with different providers. Or picking up different prescriptions or prescription refills on one day.
    - Recurring appointments with the same provider on different dates (i.e. once a week). Or prescriptions or prescription refills on different dates (i.e. picking up the same prescription every month).

- On the form intro screen and pre-screen for the list&loop - I adjusted the content for multiple claims based on the above.  Based on the PDF version of the form, it seems like this is how beneficiaries need to submit multiple claims. :link: Links to  [intro page](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=2613-68001&t=b9LblxQ5g5HeH0j2-4) and [pre-screen](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=2613-98322&t=GgLPShlpmnnQYpb6-4)
  - The product teams can let us know if their SMEs confirm that the content accurately describes how folks need to submit multiple claims.
- On the intro screen - there's a product question about hospitals, surgeries, and submitting claims. :link:[Link to question](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv?node-id=2613-68001#1072873636)
- On the EOB upload screen for folks with other health insurance - there's a product/SME question about EOBs that have multiples dates of service and care/prescriptions.  :link:[Link to question](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv?node-id=2613-68284#1071558578)
- On the list&loop recovery screen - there's a product/design question and consideration about displaying a unique identifier on the summary cards to help people know which claim they added. :link:[Link to question](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv?node-id=2613-97926#1072897214)

I'll wrap up content recommendations on the other areas of the list&loop summary screen on Monday.

**Comment by mistymg** [comment]
Closing this old task for Danielle as we have people assigned to this epic and actively working on CHAMPVA claim form.
