### ISSUE TITLE
Review and Audit existing Best Bets

### ISSUE THREAD

**Issue by scjwalker** [department-of-veterans-affairs/va.gov-team#96015]
## Issue description
Review and audit existing best bets for duplication, age, relevancy, and against most recent criteria used to approve a best bet request.  

There are currently over 500 best bets in place, and many are competing for the same terms, or are no longer relevant/accurate.  We need to review and clean this experience up and create a process for ongoing analysis and review to maintain them.

Priority: Prod work, standards work, online form audit (above), this work.

---
## Tasks
- [ ] Define process for confirming that Best Bets are using the most salient terms
- [ ] Document the process, for use going forward
- [ ] Set up an audit/documentation process all current Best Bets
- [ ] Review and clean up all existing Best Bets

## Acceptance Criteria
- [ ] All current Best Bets have been audited, and terms have been cleaned up
- [ ] There's a documented process for choosing terms, to use going forward

**Comment by mnorthuis** [comment]
This export is from September, so it won't have any recent additions.  We can use this for now to establish an approach to the audit and decision making.   If a newer export is needed, a request can be made to search@gsa.gov. 

For this export I specifically requested them to also include any data they have on performance.  That has not been included in previous exports, so be sure to include specifics in the request.  

[Best Bets Export VA September 2024.csv](https://github.com/user-attachments/files/17738703/Best.Bets.Export.VA.September.2024.csv)

**Comment by jonichan-ia** [comment]
@mnorthuis I've worked through the comments and changes. Is this the request template we want to link to: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?template=Search+Best+Bet+Request.md. How do I update it so it says Content & IA team instead of Sitewide?

@laurenvocke-va when you get the chance, would you mind taking a look at [draft](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Standards%20and%20governance/IA%20Standards/Best%20Bets%20Guidance%202026%20updates.docx?d=wf32c09b6530d422797dc845c96fcf415&csf=1&web=1&e=lsdtWJ) before we publish to VADS?

**Comment by jonichan-ia** [comment]
I've worked through additional feedback on the guidance doc and added a draft for the request template. I tagged @mnorthuis in the doc for final review. Lauren has already looked through the guidance for style.

**Comment by jonichan-ia** [comment]
I've updated the [request template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/Search%20Best%20Bet%20Request.md) with Mikki's feedback.

The guidance is ready to publish in VADS but we need to discuss the side nav label. I left some suggestions in the [doc](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Standards%20and%20governance/IA%20Standards/Best%20Bets%20Guidance%202026%20updates.docx?d=wf32c09b6530d422797dc845c96fcf415&csf=1&web=1&e=PE6AXa&nav=eyJjIjoxNzE5MjI3NTIwfQ) and will ask the IA team for feedback.
