### ISSUE TITLE
Update to Curly Apostrophes

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96025]
## Background
There is a Platform content style guideline to use curly apostrophes, and we have some straight apostrophes in our products.

This is not a priority, as there is no impact to the user experience (including accessibility) -- this is simply a [standard for standard's sake](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95146#issuecomment-2441836249).

## Tasks
- [ ] Review Find a Representative and update any straight apostrophes to curly apostrophes
- [ ] Review the different states of the Representative Status Widget and update any straight apostrophes to curly apostrophes
- [ ] Review Appoint a Representative and update any straight apostrophes to curly apostrophes

## Acceptance Criteria
- [ ] Our products only use curly apostrophes, to match Platform's content style guide.
