### ISSUE TITLE
Ensure form inputs are within form character limitations

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96028]
## Background
We will be implementing character limitations on the frontend (#96027), but there are a few fields that the frontend may not be able to enforce in which case the backend will need to truncate the input to fit into the character limitations of the form, before generating the PDF.

## Tasks
The backend will need to truncate the following fields for each PDF.

### [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf)
**Field 7: Veteran's Mailing Address**
- [x] 2 characters for State/Province
- [x] 2 characters for Country
- [x] 9 characters for Zip Code/Postal Code - this will actually need to overflow into the second zip/postal code field.

**Field 12: Claimant's Mailing Address**
- [x] 2 characters for State/Province
- [x] 2 characters for Country
- [x] 9 characters for Zip Code/Postal Code - this will actually need to overflow into the second zip/postal code field.

### [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf)
**Field 7: Veteran's Mailing Address**
- [x] 2 characters for State/Province
- [x] 2 characters for Country
- [x] 9 characters for Zip Code/Postal Code

**Field 13: Claimant's Mailing Address**
- [x] 2 characters for State/Province
- [x] 2 characters for Country
- [x] 9 characters for Zip Code/Postal Code

**Field 16a: Name of Individual Appointed as Representative** 
- [x] 12 characters for the First Name
- [x] 1 character for the Middle Initial
- [x] 18 characters for the Last Name

**Field 16c: Address of Individual Appointed as Claimant's Representative** 
- [x] 30 characters for No. & Street
- [x] 5 characters for Apt./Unit Number
- [x] 18 characters for City
- [x] 2 characters for State/Province
- [x] 2 characters for Country
- [x] 9 characters for Zip Code/Postal Code

**Field 16e: Email Address of Individual Appointed as Claimant's Representative** 
- [x] 78 characters for Email Address 

## Acceptance Criteria
- [x] The backend will enforce character limitations that match the forms, so that the generated PDF at the end of the experience does not introduce any issues with downstream processing.

**Comment by opticbob** [comment]
I'll start this first thing tomorrow.

**Comment by opticbob** [comment]
I didn't make a lot of progress on this, I spent most of the day getting other PRs merged, approved, and updated.

**Comment by opticbob** [comment]
This is coming along, I'm trying to check the boxes above as I go.

@oddball-lindsay I do have a question for you: Do we have truncation length limits for the veteran and claimant email addresses for the 2122 and 2122a?  We're not truncating them as is and that would be a good fit in with this ticket.

**Comment by oddball-lindsay** [comment]
@opticbob There are limits to the email fields, but I was thinking we'd simply implement character restrictions for email on the frontend (https://github.com/department-of-veterans-affairs/va.gov-team/issues/96027), since that is a user input. Would that be enough?

**Comment by opticbob** [comment]
@oddball-lindsay Frontend character limitations will work great for user input.  Thanks!

**Comment by opticbob** [comment]
I'm fixing the lasts tests on this and expect to have it ready for review in the morning.

**Comment by opticbob** [comment]
This has been approved by @jvcAdHoc and Platform.  It has now been merged.
