### ISSUE TITLE
Report on representatives that have invalid addresses

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96026]
## Background
392 representatives (7% of all representatives) have a nil location in Production, meaning there is no latitude and longitude associated with these representatives. Our hypothesis is that this is because these representatives have no address or an invalid address, stemming from the data we receive from OGC.

The impact of this is that these representatives are unable to be surfaced in Find a Representative, since that product is location-based and representatives with a nil location have no location to ground the search on.

The team leaders are interested in learning more about these representatives to understand:
1. What type they are (VSO, VSO representative, attorney or claims agent)
2. What their existing contact information looks like

This information will help us understand why these representatives have a nil location, and will also help guide conversations with ARF and stakeholders to determine how we might get valid addresses assigned to these representatives.

## Tasks
- [ ] Generate a report for representatives with a nil location, based on the criteria above.
- [ ] Share the report with the team.

## Acceptance Criteria
- [ ] The team has an understanding of why representatives end up with a nil location.
- [ ] The team leaders have a report to guide solution conversations with ARF and stakeholders.

**Comment by holdenhinkle** [comment]
Sam recently (some time in the past month) ran a query to find out how many reps have have `null` lat/long/location values. Get the list of actual reps should be super easy. Also, I think these numbers (392 representatives (7% of all representatives)) have gone down significantly since Sam and Josh made some improvements to address validation.
