### ISSUE TITLE
QA for Appoint a Rep MVP (Janelle)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96020]
## Background
Please reference this [Team QA for Appoint a Rep MVP](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1729288707438/0467e91be142faef94d26132b88fa3319939529d) Mural for assignments and guidance.

## Tasks
- [ ] Review the screens within your assigned chapter, via your specified devices
- [ ] Notate QA findings directly in the Mural -- one card per finding

## Acceptance Criteria
- [ ] You have reviewed the screens within your assigned chapter and have reported any QA findings

**Comment by jfinnerty13** [comment]
Memo to check
* Unauthenticated flow
* LOA1 flow
* LOA3 flow

**Comment by jfinnerty13** [comment]
Blocked until we figure out what to do about pre-fill

**Comment by jfinnerty13** [comment]
Updated QA Mural to reflect change in flow. Only now impacts non Veteran claimant flow. Veteran flow is good for the above. Closing ticket for now as I've gone as far as I can until pre-population is up and running, thanks!
