### ISSUE TITLE
Add character limits for Appoint a Representative

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96027]
## Background
The fields on the 21-22 and 21-22a paper/PDF forms have boxes to write each character in and we have decided to match this functionality on the frontend of our Appoint MVP experience. In this context, a "character" can be a letter, number, space, or special character (e.g. hyphen, period).

While our stakeholders have not explicitly said that the fields in these forms have character limitations, the VA Forms team has shared a risk that they've overcome where extending beyond the boxes (i.e. the character limit)  may cause the form to be rejected by any automated or manual processing. 
> I think if the PDF limits what you can submit and you are submitting through central mail, you need to make sure anything you do won't cause the form to be rejected by any automated or manual processing. We've been told we can't extend outside of boxes because of OCR scanners. But each form may be different.  We particularly have had to pay attention to this when a Form asks for apt/unit number and only allows a certain number of characters

We absolutely do not want our generated PDFs from Appoint a Representative to cause issues with downstream processing, so to be safe we need to instill the following character limitations on the frontend. 

Implementation notes:
- There is already formatting/character limitations for SSN, Date of Birth, and Telephone inputs, so we don't need to add additional logic to check these fields.
- There are some fields that the user won't be typing in themselves, in which case we will need to truncate on the backend when filling out the PDF form. That backend work will be handled in https://github.com/department-of-veterans-affairs/va.gov-team/issues/96028.

## Tasks

Implement character limits on the following pages and related fields, as follows. We can reference the schema file for this: https://github.com/department-of-veterans-affairs/va.gov-team/issues/93506

/claimant-relationship
- [x] 42 characters for the "Describe your relationship to the Veteran" open input

/claimant-personal-information
- [x] 12 characters for the First Name
- [x] 1 character for the Middle Initial
- [x] 18 characters for the Last Name

/claimant-contact-mailing
- [x] 30 characters for No. & Street (Street address)
- [x] 5 characters for Apt./Unit Number (Street address line 2)
- [x] 18 characters for City
- [x] 2 characters for State/Province/Region
- [x] 9 characters for Zip Code/Postal Code

/claimant-contact-phone-email
- [x] 31 characters for Email address

/veteran-personal-information
- [x] 12 characters for the First Name
- [x] 1 character for the Middle Initial
- [x] 18 characters for the Last Name

/veteran-contact-mailing
- [x] 30 characters for No. & Street (Street address)
- [x] 5 characters for Apt./Unit Number (Street address line 2)
- [x] 18 characters for City
- [x] 2 characters for State/Province/Region
- [x] 9 characters for Zip Code/Postal Code

/veteran-contact-phone-email
- [x] 61 characters for Email address

/veteran-identification
- [x] 9 characters for Veteran's VA File Number
- [x] 9 characters for Veteran's Service Number

## Acceptance Criteria
- [x] The frontend will enforce character limitations that match the forms, so that the generated PDF at the end of the experience does not introduce any issues with downstream processing.

**Comment by rjohnson2011** [comment]
PR here -> https://github.com/department-of-veterans-affairs/vets-website/pull/33725

**Comment by oddball-lindsay** [comment]
This is looking 99% good. The only area where the character limits are not being enforced is 
> 2 characters for State/Province/Region

When a non-United States country is selected, the user has the option to free-fill that field (no longer restricted to a dropdown box) and there are no character limitations.

This is affecting all pages where a State/Province/Region can be entered:
- `claimant-contact-mailing` (non-Veteran user)
- `veteran-contact-mailing-address` (non-Veteran user)
-  `veteran-contact-mailing` (Veteran user)

Steps to reproduce:
1. On the screens above, select a non-US country
2. Enter text into the State/Province Region field and observe that there are no character limitations.

**Comment by oddball-lindsay** [comment]
Leaning towards moving forward with MVP release and addressing this frontend character limitations later. We can still rely on backend truncation to ensure the PDF is generated.
