### ISSUE TITLE
Align content on VADS for experimental design with new user flow

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#96032]
## User Story
As a VFS team member, I want to have up to date documentation to reference, so that I know how to follow the experimental design process.

Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
Governance team has recently [published a new flow](https://design.va.gov/about/contributing-to-the-design-system/) to the VADS that steps through the experimental design process. The new flow is up to date and accurate, however the content supporting these pages does not align.

The purpose of this ticket is to update the content on all live pages shared below, if necessary, to reflect the updated Experimental Design flow.

Once all content is up to date, @naomimarcussen has recommended that Governance announce these changes at the Design sync meeting on Mondays.

### Live pages
- [Contributing to the design system](https://design.va.gov/about/contributing-to-the-design-system/)
- [Experimental components and patterns](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns)
- [Suggest an addition or update](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [Add a component or pattern once approved](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved)

### Drafted pages
- [Draft - Contributing to the design system](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3663462414/96032+-+Contributing+to+the+design+system)
- [Draft - Experimental components and patterns](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3662905370/96032+-+Experimental+components+and+patterns)
- [Draft - Suggest an addition or update](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3663429668/96032+-+Suggest+an+addition+or+update)
- [Draft - Add a component or pattern once approved](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3663429678/96032+-+Add+a+component+or+pattern+once+approved)

## Tasks
- [x] Review all live pages to determine where content is out of sync.
- [x] Make updates to the content to align with the Experimental Design flow
   - Note: if you are uncertain on any preferred wording, please connect with Matt Dingee for his input. 
- [x] Peer review changes
- [x] Once content is aligned, submit pull request to DST for approval/merge
   - [PR 3616](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3616)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance has updated the experimental design pages on VA Design System to align with the Experimental Design flow.

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed (for Governance, however notification for design community would be preferred)

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Brian was out sick Nov 13-15. Since Collab Cycle reviews are the priority, I have directed him to work on catching up with Collab Cycle work. This ticket will not be picked up this sprint and will be moved into the next sprint.

**Comment by shiragoodman** [comment]
reassigned this to the appropriate tech debt initiative.

**Comment by shiragoodman** [comment]
@briandeconinck is this work in progress? We're 3 days into the sprint and I would've expected this work to have started by now. Please lmk.

**Comment by briandeconinck** [comment]
Yes! Sorry, updating the ticket status and updating with progress made so far right now.

**Comment by briandeconinck** [comment]
Commenting with an end-of-sprint update: Drafts in progress, almost done; work will carry over into next sprint but should be wrapped up pretty soon after.

**Comment by briandeconinck** [comment]
@allison0034 Draft content changes are ready for review!
- [Draft - Contributing to the design system](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3663462414/96032+-+Contributing+to+the+design+system)
- [Draft - Experimental components and patterns](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3662905370/96032+-+Experimental+components+and+patterns)
- [Draft - Suggest an addition or update](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3663429668/96032+-+Suggest+an+addition+or+update)
- [Draft - Add a component or pattern once approved](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3663429678/96032+-+Add+a+component+or+pattern+once+approved)

Note that I've made no changes to the Experimental components and patterns page --- but please let me know if I missed something in there that needs updating. (I may include updates to the heading structure in my PR, but that's just me playing accessibility specialist.)

On the other three pages, I've included comments describing the changes I made (eg. new section here, existing content with minor revisions there, etc) plus a question or two for you.

Thank you!

**Comment by allison0034** [comment]
@briandeconinck I made some comments. Let me know if you want to chat.

**Comment by briandeconinck** [comment]
@allison0034 I think I've addressed all of your comments. Would you give them another look?

- [Draft - Contributing to the design system](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3663462414/96032+-+Contributing+to+the+design+system)
- [Draft - Experimental components and patterns](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3662905370/96032+-+Experimental+components+and+patterns)
- [Draft - Suggest an addition or update](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3663429668/96032+-+Suggest+an+addition+or+update)
- [Draft - Add a component or pattern once approved](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3663429678/96032+-+Add+a+component+or+pattern+once+approved)

**Comment by allison0034** [comment]
I think this looks good, should you run it by Matt?

**Comment by briandeconinck** [comment]
Per @shiragoodman, created [PR 3616](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3616)

**Comment by shiragoodman** [comment]
@briandeconinck looks like Matt left a couple comments in the PR. I approved, however please still address his comments. I will check in on this tomorrow during standup.

**Comment by briandeconinck** [comment]
Matt's comments have been addressed and @allison0034 has given her 👍 for those edits. Waiting on Matt to approve then changes will be merged in.

Per @shiragoodman in Slack, closing this ticket as complete.
