### ISSUE TITLE
Analytics Tools: Quarterly Access Reviews [Q4 2024] - Google Tag Manager & GA4

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#96058]
### Description
OCTO-DE teams are responsible for periodically reviewing access to systems and applications they manage to ensure that only authorized personnel have the required access and permissions.

Remove any users that should no longer have access to the systems or applications. Results must include a list of user access that was changed and why. Note -- we have guidance to deactivate users who have not been active in more than 1 year.

Document the results of the review using the below template.

---
### Tasks

- [x] Remove any users that should no longer have access to the systems or applications. Results must include a list of user access that was changed and why. Note -- we have guidance to deactivate users who have not been active in more than 1 year.

- [x] Document the results of the review using the below template. 

### Acceptance Criteria

- [x] Necessary information on the access review template is filled out.

**Comment by johnny-jesensky-adhoc** [comment]
Results have been documented in Confluence -- moving this to _**Done**_.

FYI @ChristineYoungZA
