### ISSUE TITLE
BE | My VA | Form Submission Status | Update Query

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#96060]
## Background
Initially, the relationship between `form_submissions` and `form_submission_attempts` was not normalized - the `benefits_intake_uuid` was stored in both tables.  This caused the query we use to pull the form submission statuses for a user more complex in order for it to accommodate the design.

These tables are being normalized by the VFF team, so we can simplify the query.

## Tasks
- [x] Refactor the form submission status query to retrieve the latest `benefits_intake_uuid` from the `form_submission_attempts` table for each record in the `form_submissions` table for the user.
- [x] Update related specs.

## Acceptance Criteria
- [x] PR Review from VFF team.
- [ ] Test in staging.

**Comment by tpharrison** [comment]
Eric Tillberg has made changes to form submission models and asked if I can update the query that returns a user's form submissions.  Going to work on this today.

**Comment by mtcA6** [comment]
@gileswells @Diana20920 since this is open and incomplete I'm wondering if we need to work through this

**Comment by Diana20920** [comment]
@mtcA6 it looks like Tom did update the query:

![Image](https://github.com/user-attachments/assets/caf97b42-8996-4e8f-99f3-d3f6d055e135)
