### ISSUE TITLE
Domo Audit Wave 2: Purging & Confirmation

### ISSUE THREAD

**Issue by Blivaditis** [department-of-veterans-affairs/va.gov-team#96068]
### Description
This ticket is a continuation of the work started in [this ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/95672) and [this ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1168/views/3?filterQuery=&pane=issue&itemId=84533855&issue=department-of-veterans-affairs%7Cva.gov-team%7C95673). This is part of an effort to reduce our row count in Domo, and to clean up our instance only for what is needed. This specific ticket pertains only to the datasets marked as Wave 2, wave 2 indicates that a dataset is still in use, but has historical data that can be purged. All necessary info, including the date ranges for deletion can be found in the artifact attached.

Artifact -- [Domo Dataset Audit](https://docs.google.com/spreadsheets/d/1y6WRGftpGzzCwrytaFjoxrzZaLBmAqNZ58sXIQMmj68/edit?gid=2007741445#gid=2007741445)

---

### Tasks

- [x] Review datasets marked as -- Purge (Wave 1) in [our spreadsheet](https://docs.google.com/spreadsheets/d/1y6WRGftpGzzCwrytaFjoxrzZaLBmAqNZ58sXIQMmj68/edit?gid=2007741445#gid=2007741445) ensure that deletion is the appropriate and that the dataset does not power any cards  or data flows. 
- [x] If any new datasets are identified as wave 1, push to delete after confirming no negative impact
- [x]  Review all datasets marked wave 2, update date ranges to remove and finalize list
Note: Encountered a snag when moving to purge the datasets, any migrated data cannot be purged with out current method. We will look into the best way to remove the data identified for purging/ 

### Acceptance Criteria

- [x] All dataset we reviewed in Audit 1 have been reviewed and updated
- [x] All datasets that are meant to be deleted have been deleted and confirmed

**Comment by Blivaditis** [comment]
All of the datasets from our original audit have been reviewed and the recommended action was updated. I identified dataset views that were previously overlooked that were no longer needed. The views did not add/remove any information that couldn't be done at the dashboard/card level. With this in mind I swapped all of the charts powered by the view to be powered by the original dataset and transferred the views structure directly into the cards (function/filter). In just views alone I was able to remove over 1 billion rows of redundant unneeded data.
