### ISSUE TITLE
User submissions failed due to missing ICN in the Lighthouse API request - Investigation

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#96071]
## Issue Description
During the course of the TE 1.0 100% rollout, ~~6~~ 8 submissions failed in the backup path due to missing ICNs. A fix-it ticket #95942 was entered that has the finer details. This ticket is to investigate the root cause and explore possible UX validations for the problem when it is encountered again.

---
## Tasks
- [ ] Determine the root cause of the issue
- [ ] Reach out to OCTO, platform and/or the Identity team to explain the situation and gain insight
- [ ] If it turns out to be a scenario that is mitigatable by the user, write stories as needed to enable BE and/or FE validation to direct (or warn) the user

## Acceptance Criteria
- [ ] Document findings in a wiki

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
