### ISSUE TITLE
Analytics: request tracking on benefit hub secondary nav 

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#96092]
## Description

This sprint, @fmccaf1 and @sterkenburgsara were interesting in benchmarking the statistical differences between mobile + desktop usage of the My HealtheVet secondary navigation against the differences between usage across modalities of the different secondary navigation component used across the unauth benefit hub pages on VA.gov. 

As we tried to pull data, we realized that there is no event tracking on the benefit hub secondary navigation, which is preventing us form making an informed comparison against the newer navigation bar pattern that has been launched within My HealtheVet on VA.gov. This ticket is for submitting a ticket to analytics to implement event tracking on this component and track any questions or surrounding work that may bubble up around that request. 

### User story

As a Cartography team member, I want to be able to make comparisons that help us understand the extent to which the My HealtheVet on VA.gov secondary navigation bar is working better than, the same as, or worse than other secondary navigation patterns on VA.gov.

### Notes
- [Analytics implementation request ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96090)

Possible tasks:
- [ ] File implementation request ticket with analytics team.
- [ ] Notify Robyn + Mikki about request for their visibility
- [ ] Once implemented, CAIA will need to add the event tracking to all pages with the secondary navigation pattern in Drupal

## Acceptance criteria
- [ ] Request has been submitted to analytics team
- [ ] Questions have been answered / office hours attended as necessary

**Comment by sterkenburgsara** [comment]
// cc @rbsingleton @mnorthuis

**Comment by sterkenburgsara** [comment]
Moving to blocked since this is now waiting for analytics for implementation.
