### ISSUE TITLE
Update URL

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#96091]
## Pain Point
Platform Website's URL `https://depo-platform-documentation.scrollhelp.site/` is confusing to users, presenting a name for the website, "Depo Platform Documentation" which is different from "Platform Website" or "The VA Documentation Site".

## Issue Description
Content team needs update the URL so that it will reflect the name of the website as it is commonly known, or as OCTO and Platform would like to call it. Currently the homepage shows this: ![Image](https://github.com/user-attachments/assets/b6fca8c1-283a-4af3-9b86-368367a877a9) 
While the end of the URL string cannot be changed (`.scrollhelp.site`), we can update the first part.

---
## Tasks
- [ ] change URL to `VA Platform documentation`.scrollhelp.site to match the homepage
- [ ] announce in Team of Teams
Announce in Slack channels: 

- [ ] platform-content
- [ ] change-announcements
- [ ] vfs-all-teams
- [ ] create 2nd ticket 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
This may be informed by engineering documentation research currently in progress
