### ISSUE TITLE
[CST] Update breadcrumb and H1 for 1P and 3P document request pages

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#96099]
## Background Context

We want to update the language of the breadcrumb and H1 for 1P and 3P document request pages to match a new format and remove the "Request for" language that currently exists.

Current
![Image](https://github.com/user-attachments/assets/2df11a15-1029-4199-a428-2001eb859a54)

New
Change string in breadcrumb and H1 of document request page to just: `[Request name]`
Example: `RV1 - Reserve records request`

FIGMA links will be provided as part of working this ticket

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Update src/applications/claims-status/components/claim-document-request-pages/DefaultPage.jsx to no longer use `Request for`

## Out of scope
- Add here

## Open questions
- @skylerschain do we also want to update the document request page for this change and the 5103 page for this change?

## Tasks
- [ ] _Create Figma mock for this ticket_
- [ ] _Update CST V2 Figma file to reflect this change_
- [ ] _Implement new string for breadcrumb and H1 page titles for document request page_
- [ ] _Implement new string for breadcrumb and H1 page title for 5103, since that is its own unique implementation (I think)_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] _All 1P and 3P requests use the new string format in the breadcrumb and H1 of the document request page (see screenshot above)_
- [x] _All 1P and 3P requests use the new string format on for the alert title on the detail page_
- [x] _Update 5103 to align with intended language_
- [x] The title of the page tab is updated to the new string format

**Comment by pmclaren19** [comment]
@skylerschain  do we also want to update the document request page for this change and the 5103 page for this change?

**Comment by pmclaren19** [comment]
@skylerschain so the Document title also uses the 'Request for' language. Im assuming you would also like this to be changed?

**Comment by pmclaren19** [comment]
@skylerschain merged in change and verified it looks good in Staging! Feel review to review and lmk if you have any questions.

**Comment by skylerschain** [comment]
LGTM! 👍
