### ISSUE TITLE
FE/BE | Profile | Contact Information | Discovery - Address Validation Upgrade

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#96147]
## Background
The platform product team is currently migrating the vets-api to use VA Profile's Contact Information API version 2 (upgrading from v1).

When we migrate to Contact Info V2, we'll need to also upgrade to [VA Profile Address Service V3](https://developer.va.gov/explore/api/address-validation/docs?version=current) for compatibility reasons.

## Tasks
- [x] Identify FE changes and create ticket.
- [x] Identify BE changes and create ticket.

## Acceptance Criteria
- [x] Review with team
- [x] Tickets with acceptance criteria have been created.

**Comment by tpharrison** [comment]
Mike Richard and Jeff Barnett reached out to let us know they're ready for testing on the profile for the address validation changes (validation key change for invalid address, and the removal of Puerto Rico i believe).

**Comment by tpharrison** [comment]
I've reviewed the code and there are no changes we need to make. Initially, we thought that a data field was being renamed from `/cityStateProvince` to `/locality`, but this update refers to an endpoint, not a data element within the response.
