### ISSUE TITLE
[Discovery] Vets-json-schema build process

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#9614]
## Issue Description

The Lighthouse team has implemented an API call that returns the JSON schema used by their service for a particular form.

Currently the Higher-Level Review form has this in place - see https://dev-developer.va.gov/explore/appeals/docs/decision_reviews?version=current#operations-Higher-Level_Reviews-get_higher_level_reviews_schema 

Since Lighthouse plans to provide a schema for this form, and forms supported in the future, we should consider including this in the `vets-json-schema` repo build process. Before that, we need to have a discussion. Some considerations have been outlined in the tasks section below.

Related discussion: https://dsva.slack.com/archives/CKUCFQAHJ/p1590694497036400

## Tasks

- [ ] Discuss pro & cons of this method
- [ ] Discuss versioning
- [ ] Document process needed to update the schema
- [ ] Discuss adding a back-end pass through that accesses Lighthouse's api using their api key

## Acceptance Criteria
- [ ]

**Comment by rianfowler** [comment]
We should make a [design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/README.md) for this before doing any work. Dynamically pulling json schemas- even in the build process- has broad implications.
