### ISSUE TITLE
Dispute Form - Mockups

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#96144]
## Description
[Mobile and Desktop mock ups for Digital Dispute form (link to Figma file)](https://www.figma.com/design/D8tfoPhUZlqBUomMTxzkQb/Dispute-Form-(VHA-VBA)?node-id=19-220)

## Tasks
- [x] Figma mockups for dispute form based on [User flow](https://www.figma.com/design/D8tfoPhUZlqBUomMTxzkQb/Dispute-Form-(VHA-VBA)?node-id=1-339&t=p1wxf301YkuNTlKG-1)

## Acceptance criteria
- [x] [Figma mockups](https://www.figma.com/design/D8tfoPhUZlqBUomMTxzkQb/Dispute-Form-(VHA-VBA)?node-id=19-220&t=WreEDgMBcSjVXNmG-1)

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by mgleo** [comment]
Digital dispute form Figma mock ups: https://www.figma.com/design/D8tfoPhUZlqBUomMTxzkQb/Dispute-Form-(VHA-VBA)?node-id=19-220&t=WreEDgMBcSjVXNmG-1
