### ISSUE TITLE
VRE |

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#96157]
## Issue Description
As outlined in #83962 by Steve:

> Traditionally a Sidekiq job will try to call perform(), and it will re-call perform() again for retryable issues by throwing an exception, until it fails enough times to call the sidekiq_retries_exhausted where it will run the backup path. In veteran_readiness_employment_claim.rb, around line 118, the code immediately calls the backup path if the upload_to_vbms job fails one time. This bypasses the Sidekiq retry mechanism. Generally the backup path for retryable issues should happen in the sidekiq_retries_exhausted handler so the job can try the main path multiple times? In this current configuration I'm not sure if the exhausted handler would be called even if the remote system was unavailable.

Research done by Micah uncovered:

> It looks like there is one item that I hadn't been tracking. The unchecked item that is mentioned by Steve does operate in that incorrect way. We would need to separate out the VBMS upload method from the LH/BI backup path. We should exhaust retries on VBMS uploads before attempting the LH backup path._

---
## Tasks
- [ ] Separate the VBMS upload method from the LH/BI backup path
- [ ] Exhaust retries on VBMS before attempting the LH backup path

## Acceptance Criteria
- [ ] VBMS upload method is separate from the LH/BI backup path
- [ ] Retries are exhausted before attempting the LH backup path
---
