### ISSUE TITLE
UI: Consistent community urgent care results, regardless of path

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9615]
## User Story:
As a Veteran, I need consistent and accurate information about community urgent care locations regardless of search path so that I get the information I need. 

## Background
With the MVP release, urgent care became searchable via facility type drop down and referral text was removed from the facility card.  

However, many Veterans are still searching for urgent care facilities using Facility type = "Community providers (in VA's network)"  + Service type = "Clinic/Center- Urgent care. 

## Current behavior
<details> 
  <summary>This search path can be misleading to Veterans. (expand)</summary> 

   - The list of results can be incomplete and inaccurate (addressed separately in [#5128]

   - This search path does not display the alert

   - Search result cards include misleading and unnecessary referral information.

![legacy results](https://user-images.githubusercontent.com/55411834/85904795-e153e200-b7c6-11ea-971a-4726324c696d.png)

</details>

## Expected behavior

<details> 
  <summary> When a Veteran searches for urgent care using Facility type = "Community providers (in VA's network)"  + Service type = "Clinic/Center- Urgent care", the results and experience are the same as when a Veteran searches using Facility type = "Urgent care"  + Service type = "Community urgent care (in VA's network)". (expand)</summary> 

![image](https://user-images.githubusercontent.com/55411834/85904431-f3815080-b7c5-11ea-87fb-dfc090f9c6ac.png)

</details>

## Tasks
- [ ] Display alert for searches when Facility type = "Community providers (in VA's network)"  + Service type = "Clinic/Center- Urgent care".
- [ ] Remove referral information from search result cards
- [ ] Ensure data returned contains POS 17 and 20
- [ ] Ensure existing functionality is maintained for non-urgent Community provider searches
- [ ] Ensure existing functionality is maintained for VA urgent care searches
- [ ] Ensure the back end data from API is displayed in local and review instance
- [ ] Ensure unit tests are available
- [ ] Ensure your code changes are covered by E2E tests 
- [ ] Run axe checks using the Chrome or Firefox browser plugin 
- [ ] Test for color contrast and color blindness issues
- [ ] Zoom layouts to 400% at 1280px width 
- [ ] Test with 1 or 2 screen readers 
- [ ] Navigate using the keyboard only 

## Acceptance Criteria:

- [ ] When a Veteran searches for urgent care using Facility type = "Community providers (in VA's network)"  + Service type = "Clinic/Center- Urgent care", the results and experience are the same as when a Veteran searches using Facility type = "Urgent care"  + Service type = "Community urgent care providers (in VA's network)". 

When Facility type = "Urgent care" + Service type = "VA urgent care", then 
- [ ] Results should include only VA urgent care facilities from Facilities API
- [ ] Search results cards **do not** include referral information 
- [ ] Alert **does not** display

When Facility type = "Urgent care" and Service type = " Community urgent care providers (In Network)", then 
- [ ] Results should include only VA Community Care (In Network) locations (PPMS Place of Service 17 and 20)
- [ ] Search results cards **do not** include referral information 
- [ ] Alert **displays** below search box
- [ ] SERVICE displays as RETAIL/WALK-IN CARE or URGENT CARE (based on POS code)

When Facility type = "Community providers (in VA's network)" and Service type = "Clinic/Center- Urgent care", then 
- [ ] Results should include only VA Community Care (In Network) locations (PPMS Place of Service 17 and 20)
- [ ] Search results cards **do not** include referral information 
- [ ] Alert **displays** below search box
- [ ] SERVICE displays as RETAIL/WALK-IN CARE or URGENT CARE (based on POS code)

When Facility type = "Community providers (in VA's network)" and Service type = other non-urgent care service (such as Podiatry or Dentist) then 
- [ ] Results include relevant specialty results
- [ ] Search results cards **do** include referral information 
- [ ] Alert **does not** display below search box

## Acceptance Criteria
- [ ] Unit tests pass
- [ ] E2E tests cover new code 
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

**Comment by brangi** [comment]
Merged
