### ISSUE TITLE
Create QA Smoke Test

### ISSUE THREAD

**Issue by adamcaniparoli** [department-of-veterans-affairs/va.gov-team#96152]
## Issue Description
The smoke test should take no more than 15 minutes to complete and outline basic product functionality. Ideally this test follows the most common path through the app. This test is being created in TestRail: https://dsvavsp.testrail.io/index.php?/cases/view/104430 
This is a manual test (not automated).

---
## Tasks
- [ ] Compile analytics to determine most common path through the Form 527 application 
- [ ] Write out manual test 
- [ ] Run through test and review to make sure nothing is being left out

## Acceptance Criteria
- [ ] Creation of full manual test script that can be run through in TestRail, with each step allowing a Passed/Faiedl/Blocked/Skipped value
---
