### ISSUE TITLE
[CST] Align placement of feedback message alerts in CST

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#96168]
## Background Context

We need to conduct an audit of all of our alerts in CST to ensure that they are: 
- In the optimal place on the page
- Consistent in their placement across all alerts

A couple examples of these alert:
- Document upload confirmation message
- Error message for Type 2 Failure

**_Example of a feedback message alert in CST_**

<img width="565" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUNHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1ad16b959522217d1e0b63d90560c566cbe764d/Screenshot%202024-10-30%20at%202.21.54%E2%80%AFPM.png" alt="Screenshot 2024-10-30 at 2.21.54 PM.png" />

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Conduct audit of all these feedback message alerts_
- [ ] _Create design spec for where all these alerts should be placed_
- [ ] _Implement changes to placement of these alerts_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Audit of all CST feedback alerts is complete_
- [ ] _Design spec for alert placement is created_
- [ ] _Design spec is implemented
_

**Comment by skylerschain** [comment]
This is a dupe of #96593
