### ISSUE TITLE
Prepare for Research: Facility Locator Redesign

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9616]
## Issue Description
How might we test a first iteration of the Facility Locator redesign?  

## Goals
-Learn how Veterans and Caregivers may use the new filter feature as well as the addition of the quick links.

Answer the following: 

- Is it more intuitive to have two search fields instead of three?
- How are people filtering services for each facility type?
- Is there a need for a Google-like open search

---
## Tasks
- [ ] Review [card sort readout](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator/research/user-research/redesign/filter-categorization)
- [ ] Review and complete draft [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/redesign/prototype-testing/prototype-v1/research-plan.md)
- [ ] Create conversation guide
- [ ] Ensure prototype supports research plan and conversation guide

## Acceptance Criteria
- [ ] Approved research plan and conversation guide
- [ ] Prototype can support research plan and conversation guide and is available for user research sessions

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
