### ISSUE TITLE
Create and Publish on OCTO and VA.gov Veteran Support Applications, Terms/Terminology, Acronyms and Training Modules

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#96193]
## Issue Description
_Complete list of software applications
Training modules with screen shots reflecting the lifecycle of escalated cases
---
## Tasks
- [ ] Categorize items into relevant categories 
- [ ] create a user-friendly searchable document 

## Acceptance Criteria
- [ ] _Published document to OCTO and VA.gov Teams/SharePoint including list of Veteran Support applications
- [ ] Published document to OCTO and VA.gov Teams/SharePoint including glossary of acronyms, terms and terminology
- [ ] _Published document to OCTO and VA.gov Teams/SharePoint including Veteran Support team members training modules 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
Sync meeting is scheduled for Wednesday, November 6, at 3:30 p.m. ET.

**Comment by starlow00** [comment]
Training module samples, which I can download as PPT when needed for publication outside of our team:
*AVA training: GI Bill/SCO request https://docs.google.com/presentation/d/1AkzkUSZVpYESuDZEEEMUek3WrqIO93rYuVPpyUv4Lp0/edit?usp=sharing

*KM plain-language audit presentation
https://docs.google.com/presentation/d/1aMsVtnmdgnaBlem1T_9BEYYIki5-oa-X7Btz9h-3PNM/edit?usp=sharing

*EVSS issues presentation
https://docs.google.com/presentation/d/1XNqMHrS1rr0nnUJcCx4b8ndxx3dLRNDZ/edit?usp=sharing&ouid=116802734035541176783&rtpof=true&sd=true

*Tier 2 or Not Tier 2 presentation
https://docs.google.com/presentation/d/13dTdyp8rUD-cWUq9MbW9STeXvZbtFzEU/edit?usp=sharing&ouid=116802734035541176783&rtpof=true&sd=true
*AVA training: VHA PATS-R 
https://docs.google.com/presentation/d/1872M1OgU__XfiBX3COoClFrMkfOkLmvrv0n8Uuo-AuM/edit?usp=sharing

*SF training: Trouble changing direct deposit
https://docs.google.com/presentation/d/1G701HNclCetN9l2QicqbKmoitu61atTlzfAsfLi9AlQ/edit?usp=sharing

*General SF case handling
https://docs.google.com/presentation/d/1hqeefkAovv-YQMWR_i7RkDIASMrGqR3F/edit?usp=sharing&ouid=116802734035541176783&rtpof=true&sd=true

*SF Email builder presentation
https://docs.google.com/presentation/d/12UYc98ZnJE3o4hSA7HKJ0jPnipOng8xZ/edit?usp=sharing&ouid=116802734035541176783&rtpof=true&sd=true

*QRGs and templates presentation
https://docs.google.com/presentation/d/133Gp5rjQZ0dC0Co_t7tlY1O951RZcSOo/edit?usp=sharing&ouid=116802734035541176783&rtpof=true&sd=true

**Comment by starlow00** [comment]
Other training documents: [VEO Glossary SRT 10022024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN081Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4801050634ec783912cdcf83f716fecc89dffb1a/VEO%20Glossary%20SRT%2010022024.docx)

[Veteran Support training documents.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1M1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62b1b83d51c486186874d592b0497afd8ecc0103/Veteran%20Support%20training%20documents.zip)

**Comment by starlow00** [comment]
[All OCTO Products.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2U1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58028c06fff3ec9911db0800d259aa0e23d8f400/All%20OCTO%20Products.xlsx)

[VA Call Center List.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2k1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b40412d3247403a21a5b8f74ddbb7bfc57e1e82/VA%20Call%20Center%20List.docx)

**Comment by Kimberley2023-CSM** [comment]
[Acronym Glossary.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzY4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e01d8ea189f8c752162189081c5c9166dd2e7e9a/Acronym%20Glossary.xlsx)

**Comment by Kimberley2023-CSM** [comment]
This is the site where you can view a list of approved Federal products.
https://marketplace.fedramp.gov/products here's all the fedramped products!

**Comment by starlow00** [comment]
Product guide abstracts (summaries): https://docs.google.com/document/d/1UR6h1elYYz0vLrb-jdKhACRC4Hkq9lgM4uJdBvEoR4I/edit?usp=sharing

**Comment by UXCamG** [comment]
[Tier 1 & 2 process](https://vfs.atlassian.net/wiki/x/s4DPag)
[Veteran Support Education](https://vfs.atlassian.net/wiki/x/mgCYpg)
[VA Digital forms](https://vfs.atlassian.net/wiki/x/foDuag)
[How to request a digital form](https://vfs.atlassian.net/wiki/x/YoDnag)
[Review the Domo dashboard](https://vfs.atlassian.net/wiki/x/O4A6eQ)
[Survey Compliation](https://vfs.atlassian.net/wiki/x/AgBAx)

**Comment by ATMiddleton** [comment]
To be publised on 
Veteran Support Platform page - https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-help-from-the-veteran-support-team  
Veteran Support Confluence - https://vfs.atlassian.net/wiki/spaces/Contact/overview
SharePoint/Teams on VA.gov -

**Comment by ATMiddleton** [comment]
Updating sequence, 
Platform page 
Confluence 
SharePoint/Teams on VA.gov

**Comment by ATMiddleton** [comment]
All of the above items will be categorized and forwarded to the Platform team for feedback and updates for publication the week of December 1st.

**Comment by starlow00** [comment]
Veteran Support intro video: https://youtu.be/5I1swV8ifwE?si=GFvN7AWYi_-ESVHe

**Comment by ATMiddleton** [comment]
@Kimberley2023-CSM @UXCamG @starlow00 and @ATMiddleton reviewed documentation and organized VA.gov Teams/SharePoint folders for easy navigation.
