### ISSUE TITLE
Veteran Support Big Picture Chart 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#96192]
## Issue Description
Create a pictorial image reflecting how Veteran Support exists in OCTO 
---
## Tasks
- [x] Create an org chart visual of where Veteran Support exists within OCTO.
- [ ] 
## Acceptance Criteria
- [ ] The image clearly and accurately reflects the department’s core functions and values.
- [ ] Key responsibilities or activities of the department are visually represented using appropriate symbols or icons.
- [ ] Image published to Veteran Support Canvas 
- [ ] Image published to Veteran Support Teams on the VA side 
- [ ] 
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Meeting with CS team 1st week of January and we should be able to complete this task at that time.

**Comment by UXCamG** [comment]
[Contact Center](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727196066679/e1b32c82b789188b823116bf82a5f251f78a10a4?sender=u1b194f0dc03d715330)
