### ISSUE TITLE
Add DI, MPR and SR date in Collab Cycle Reviews GH projects board

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96217]
## User Story
As a VA.gov team member, I want to be able to refer to the Collab Cycle Review GH projects board and rely on the dates in the DI, MPR and SR columns so that I can get the information I need without having to open the toggles.

Assignee: @briandeconinck 
Peer Reviewer: @it-harrison 

## Description
Governance team switched to GH projects a couple months ago for our Collaboration Cycle Reviews board. While we made a change to update the Status in the GH Projects board when touchpoints are scheduled and completed (opposed to updated the Zenhub pipelines), we never added a task for the On Support person to fill in the DI, MPR and SR date fields. This is valuable bc it allows us to see at a glance if the VFS team had a touchpoint and when.

The purpose of this touchpoint is to update our operational guidance for scheduling so that when a touchpoint is scheduled, the on support person adds the date/time within the body of the ticket AND in the appropriate field within the GH Projects board. 

### Live pages
- [Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Scheduling)
- [Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling)
- [Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)

### Drafted pages
- 

## Tasks
- [x] Edit the DI, MPR and SR scheduling docs to include a step for adding the date to the GH Projects date field
- [x] If this is a 2nd touchpoint (such as a 2nd Midpoint Review, or 2nd Staging Review), the more recent date should take priority in the gh projects field

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team members add the DI date to the Design Intent field of the GitHub Projects Collaboration Cycle Reviews board when scheduling the DI
- [x] Governance team members add the MPR date to the Midpoint Review field of the GitHub Projects Collaboration Cycle Reviews board when scheduling the MPR
- [x] Governance team members add the SR date to the Staging Review field of the GitHub Projects Collaboration Cycle Reviews board when scheduling the SR

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@it-harrison This is ready for review! Note that I've entirely rewritten Step 6 for each page to make updating the status and adding the date flow together cleanly. Let me know if there's anything that doesn't make sense!
- [Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Scheduling)
- [Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling)
- [Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)

**Comment by it-harrison** [comment]
@briandeconinck - perfect! good to close!
