### ISSUE TITLE
Determine how we can share the new Collab Cycle Survey with VFS teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96218]
## User Story
As a VFS team member, I want to provide feedback to Governance team about my experience in the Collaboration Cycle so that Governance team can capture the pros and cons of the VFS experience in Collaboration Cycle.

As a Governance team member, I want to incorporate the new Collab Cycle survey into existing communication methods already in use by Governance team so that we're not making more work for Governance team members, and meeting VFS teams where they're already at.

Assignee: @erinrwhite 
Peer Reviewer: @it-harrison 

## Description
@naomimarcussen has graciously offered to create a new survey for Governance team that will help gather more frequent and more specific feedback from VFS teams participating in the Collab Cycle. While Naomi will be creating the survey, she will need Governance teams help in distributing it. The purpose of this ticket is to determine where the survey can be shared and implement the survey into our process.

As of 11/19/24, Naomi has created the Collaboration Cycle survey and generated a [preview.](https://dj540s05.optimalworkshop.com/questions/f54355271969f160ef41182ba9ceb61c) Please be sure to coordinate with Naomi to  access the live survey to be incorporated into Collab Cycle guidance and communication methods. 

### Shira's thoughts on where we can share the survey link

- [Contact Us page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us) on Platform Website
- Collab Cycle Feedback template for DI and MPR
- Collab Cycle Findings template for SR (aka DraftingTemplate)
- Slack workflow messaging (for KO, DI, MPR and SR)
- QA processes?

### From Erin:
 - We can included as the after-meeting web page link on our CC zoom meetings

### Live pages
- [Contact Us page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us) on Platform Website
- Collab Cycle Feedback template for DI and MPR
- Collab Cycle Findings template for SR (aka DraftingTemplate)
- Zoom post-attendee survey link - this will mean we need to generate new Zoom meeting links and get them updated in Calendly @shiragoodman 

### Drafted pages

- [x] Zoom post-meeting survey link for DI, MPR and SR (and Architectural Intent?) - @shiragoodman This will likely mean needing to generate new Zoom meeting links (since previously created meetings cannot have Surveys assigned) and get those meeting links updated in Calendly as well
- [x] [DRAFT Contact Us page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3665985537/96218+-+Erin+-+Contact+us) on Platform Website
- [x] Collab Cycle Feedback template for DI and MPR - [PR submitted](https://github.com/department-of-veterans-affairs/va.gov-team/pull/97975)
- [ ] Collab Cycle Findings template for SR (aka DraftingTemplate)
- [x] Updated instructions for meetings hosts for DI, MPR, and SR
- [ ] Collab cycle code blocks - add a link to survey in VFS actions after each touchpoint
 

## Tasks
- [x] Review the survey created by Naomi
- [x] Decide where we want to share the survey with VFS teams. Ideally we want to "meet them where they're at" and we also don't want to introduce any manual steps for ourselves. 
- [x] Once assignee and peer reviewer agree where the survey should be shared (ideally more than 1 place), be sure to clearly communicate it within this ticket.
- [x] Contact Naomi for the live version of the survey. Do not share out the draft survey link.
- [ ] Create pull requests and/or documentation drafts of the impacted pages or templates. If we decide to share the survey in the Staging Review findings tickets, we will need to edit the DraftingTemplate so please loop in Shira.
- [ ] Publish changes once peer reviewed.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have incorporated the Collaboration Cycle survey in existing communication methods for Governance teams

## Team Notification
- [x] Slack post on #platform-governance-team - specifically note changes to moderator in-meeting script
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
Places to share the link:

- [As a zoom attendee survey link](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0067657) - this would need to be configured by the owner of the zoom meeting (Shira for most touchpoints; not sure who owns Architecture Intent meeting). This feature is not available for MS Teams, so the PO sync would not have this feature.
- As links within the Collab Cycle ticket, under "VFS Actions" for each touchpoint
- In CC feedback tickets
- Touchpoint pages on platform website!

The ticket says we shouldn't add any manual tasks, **and**  another idea is to add a step for our post-meeting tasks, to send a link to the survey to the VFS team's channel in Slack. This could be a copy/paste, or we can automate sending a message using GitHub workflows and an emoji as we do with the other parts of the scheduling process. It is higher touch, but it also "meets teams where they are" and is higher visibility (a post in the team's main slack channel) which likely means teams would be more likely to fill it out.

We'll also need to update our moderator scripts for closing out meetings, to notify folks about the survey and encourage them to complete it.

@it-harrison what think?

**Comment by erinrwhite** [comment]
Shared preview survey with team for feedback!

**Comment by erinrwhite** [comment]
Success with zoom post-meeting survey link! 
![Image](https://github.com/user-attachments/assets/b0212aa3-7572-4794-8c4c-a7a6321b4410)

**Comment by erinrwhite** [comment]
@shiragoodman @it-harrison I'm updating our list of pages to add the survey link to. Here's the final list!

- [ ] Zoom post-meeting survey link for DI, MPR and SR (and Architectural Intent?) - @shiragoodman This will likely mean needing to generate new Zoom meeting links (since previously created meetings cannot have Surveys assigned) and get those meeting links updated in Calendly as well
- [ ] [Contact Us page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us) on Platform Website
- [ ] Collab Cycle Feedback template for DI and MPR
- [ ] Collab Cycle Findings template for SR (aka DraftingTemplate)
- [ ] Collab Cycle code blocks - adding links within the Collab Cycle ticket, under "VFS Actions" for each touchpoint

**Comment by erinrwhite** [comment]
@shiragoodman Here's the link I added to the midpoint/DI feedback ticket template - maybe something similar for the link in the SR feedback tickets in the Drafting Template?

`_How did this touchpoint go? [Give feedback on the Collaboration Cycle process](LINK) at any time._`

**Comment by shiragoodman** [comment]
I like it. Any suggestion as to _where_ in the Staging Review finding ticket this should like (aka where in the DraftingTemplate)?

**Comment by shiragoodman** [comment]
@erinrwhite I have added the survey to the Collab Cycle SR Findings template via the DraftingTemplate - here's what it will look like
![Image](https://github.com/user-attachments/assets/38615cc3-ddcc-4984-88c7-4e254400fb43)

**Comment by shiragoodman** [comment]
Do we want to add it to the DST DraftingTemplate too?

**Comment by shiragoodman** [comment]
@erinrwhite I reviewed all of your draft docs and they are looking good to go. Please be sure to share the collab Cycle code blocks once the updates are made so @it-harrison or I can review. thanks!

**Comment by shiragoodman** [comment]
@erinrwhite I have reviewed all of the above and everything looks good to go. Please move forward with merging the PR. This ticket can be closed once everything is live. Ty!

**Comment by erinrwhite** [comment]
PR merged and [Contact Us page updated on PW](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us)! closing, @shiragoodman can you check off AC as well? thank you!
