### ISSUE TITLE
Add external-secret.io support to existing EKS clusters

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#96210]
We need the ability to use the external-secrets.io apiversion for parameter store key values. As a result, the extern-secrets.io CRDs need to be added and configured in the existing dev, sandbox, staging and production EKS clusters.

the NEXT EKS clusters use the following code:
- https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/blob/main/terraform/modules/platform-distro/helm_external-secrets.tf
- https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/blob/main/terraform/modules/platform-distro/helm_values/helm_external-secrets.yaml

## Tasks
- [ ] Add CRDs for external secrets
- [ ] Configure external secrets

## Acceptance Criteria
- [ ] An external secret using the external-secrets.io apiVersion successful pulls from the parameter store

**Comment by ericboehs** [comment]
May push out https://github.com/department-of-veterans-affairs/va.gov-team/issues/95667
