### ISSUE TITLE
Finalize TE research material and submit to Platform

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#96213]
## Issue Description 

Ticket scope includes developing the conversation guide and finalizing all research materials (plan, screener, conversation guide). Before submitting the study to Platform, it will be reviewed internally and by stakeholders to ensure alignment. 

## Background
We will be conducting Veteran-facing usability testing on the new feature in the 526ez along with the IPF alerts from the 1.1 rollout. This user testing will complement ongoing UX monitoring of the release ([TE Monitoring](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/2024-08-Toxic-Exposure/TE-Monitoring.md)). Findings from previous monitoring will inform research questions and help to focus the study, itself.

## Impact
At a high level, we want to know what aspects of the UX are causing problems for Veterans, leading to abandonment, cognitive fatigue, frustration, etc. We are also curious about how the In Progress Form is impact opt-in/out rates for Veterans. 
Findings from the study will help drive design improvements to the TE flow, making it easier and more intuitive for Veterans to apply for benefits.

## Tasks
- [x] Draft conversation guide
- [ ] Get feedback on materials from HCD team and OCTO stakeholders **_Awaiting Shannon feedback post-offsite_**
- [x] Submit study to Platform by 11/18

## Acceptance Criteria
- [ ] Study materials are complete and reviewed by Product Management, HCD group, CARBs design HCD Lead, and OCTO Design Lead **_Awaiting Shannon feedback post-offsite_**
- [x] Study is submitted to Platform
- [x] Plan is adjusted as needed based on outcomes of AT decisioning

**Comment by mayacarrolluxa6** [comment]
@evelynhilbrichdavis Will this include the updates for testing with Veterans who use assistive technology? I’m hoping for us to submit materials for both AT and non-AT users as a single package to OCTO’s Research Lead on 11/18, as originally planned.

**Comment by mayacarrolluxa6** [comment]
@evelynhilbrichdavis 

**CAIA Ticket**
We have Shannon’s approval to open a ticket with CAIA for support testing with veterans who use assistive technology. Please review the ticket in a Zoom meeting with me before submitting it.

**TE Usability Testing - Synthesis and Reporting Expectations**

_By End of Year 2024:_

	•	We will provide Shannon and Emily with an initial summary of results after testing each cohort.
	•	Final synthesis and reporting will be completed before year-end, along with two share-out sessions:
	•	A session with the OCTO enabling team and VBA.
	•	An open-invite session for the Benefits portfolio and health team, or alternatively, a recorded share-out.

_By Q1 2025:_

	•	We will present in the OCTO Research Share-out. To secure a spot, we’ll request to be added to the waiting list before the end of 2024, as scheduling can take several months.

If you have any questions or concerns, feel free to schedule a 1:1 with me to discuss them.

**Comment by mayacarrolluxa6** [comment]
Toxic Exposure Evaluative Research Timelines

Managed in [this](https://docs.google.com/document/d/1fAMb4xONNfWjxSkY3yoiQvVC3rvJfd7fVLBYvpSzl_I/edit?usp=sharing) document.

Sprint 9 
October 23 - November 5 
Draft research plan
Draft research goals
Past TE research knowledge transfer

Sprint 10 
November 6 - November 19
Finalize research materials and submit to Platform.
Shannon would like to have the research plan (goals, screening criteria, discussion guide) sent to Shane by the 18th at the latest.*
Finalized Research Materials include:
Research goals
Research plan
Screening criteria
Discussion guide
Recruit participants 
Kickoff meeting with Perigean

Sprint 11 
November 20 - December 03
Work paused for Thanksgiving holidays
Start testing on Monday 12.2
Conduct moderated usability tests (with veterans who use assistive technology and veterans who do not use assistive technology)
Run semi-structured usability testing session on the 1.1 TE release in production or staging environment 
Collect data 
Synthesize data 

Sprint 12 
December 4 - December 17
Conduct moderated usability tests (with veterans who use assistive technology and veterans who do not use assistive technology)
Run semi-structured usability testing session on the 1.1 TE release in production or staging environment 
Collect data 
Synthesize data 

Sprint 13 
December 18 - December 31
Write topline insights report
Share report with stakeholders
Analyze data for trends
Share-out findings 
Recommend improvements

**Comment by evelynhilbrichdavis** [comment]
Hey @mayacarrolluxa6 , thanks for the support! I should've opened this ticket yesterday apologies for the lack of visibility. At the start of sprint, I was working Discovery to determine feasibility & timing of running AT user testing for TE
[#96522](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96522) and upskilling to be prepared to run AT sessions, which are new to me. 

My timeline (shared out yesterday in huddle): 
1. 11/14: Share out conversation guides for approval during Product UX sync, async w/ Ruben +Tracy (unless they want to join)
2. 11/15: Share material out on slack so Shannon can review it (as per Bi-Weekly Design Sync)
3. 11/18: Send to Shane by EOD. Shannon said that if she doesn't review it by then, send it anyway and she will follow up later. 

Let me know if you have any further questions! Looking forward to the study.

**Comment by mayacarrolluxa6** [comment]
@evelynhilbrichdavis I've completed my review of both AT & non-AT test plans and conversation guides. I've left feedback as comments in the google docs and in Slack. 

I think it would be beneficial to center both the AT and non-AT user guides around real-world use cases for the toxic exposure flow. I’ve drafted these and appreciate it if you could review and comment on the scenarios in [this](https://docs.google.com/document/d/1nSHPZw4vZn4v0QaBn58DlsLuBXLMksSZoaDChnOerPs/edit?usp=sharing) document. Thanks!

Toxic Exposure Evaluative Research
Test Scenarios

Scenario 1: 
I am a Veteran who was exposed to toxic chemicals (such as burn pits, agent orange, radiation, airborne hazards, water contamination) during my past military service. I want to claim disability compensation benefits without having to prove a direct connection between the exposure and my health condition.
File a new claim for a toxic-exposure related presumptive condition.
File a new claim for a toxic-exposure related presumptive condition and other non-presumptive conditions.
Request an increase for a pre-existing toxic-exposure related presumptive condition.
Request an increase for a pre-existing toxic-exposure related presumptive condition and other non-toxic exposure-related non-presumptive conditions.
Update an existing claim with new information now that I know the PACT Act may make it easier for me to qualify for disability compensation due to toxic chemical exposure.

Scenario 2: 
I am an active duty Service Member who was exposed to toxic chemicals (such as burn pits, agent orange, radiation, airborne hazards, water contamination) during my current military service. I want to claim disability compensation benefits without having to prove a direct connection between my exposure and health condition, so I can receive assistance immediately after being discharged from service.
File a new claim for a toxic-exposure related presumptive condition.
File a new claim for a toxic-exposure related presumptive condition and other non-presumptive conditions.
Request an increase for a pre-existing toxic-exposure related presumptive condition.
Request an increase for a pre-existing toxic-exposure related presumptive condition and other non-toxic exposure-related non-presumptive conditions.
Update an existing claim with new information now that I know the PACT Act may make it easier for me to qualify for disability compensation due to toxic chemical exposure.

Scenario 3: 
I am a caregiver or legal representative of a Veteran who was exposed to toxic chemicals (such as burn pits, Agent Orange, radiation, airborne hazards, or water contamination) during their military service. I want to claim disability compensation benefits without having to prove a direct connection between the exposure and my charge’s health condition.
File a new claim for a toxic-exposure related presumptive condition.
File a new claim for a toxic-exposure related presumptive condition and other non-presumptive conditions.
Request an increase for a pre-existing toxic-exposure related presumptive condition.
Request an increase for a pre-existing toxic-exposure related presumptive condition and other non-toxic exposure-related non-presumptive conditions.
Update an existing claim with new information now that I know the PACT Act may make it easier for my charge to qualify for disability compensation due to toxic chemical exposure.

**Comment by evelynhilbrichdavis** [comment]
Thanks for the notes, Maya. I have already addressed this feedback elsewhere. We can look for places to pump up the mock scenario, but we also hope to see Veterans use their own military service history to complete the flow- the best kind of real world use case!

**Comment by evelynhilbrichdavis** [comment]
In order to close this ticket, we need feedback from Shannon.

**Comment by evelynhilbrichdavis** [comment]
Received feedback from Liz, another OCTO design lead. I will make small adjustments tomorrow to the conversation guides, but we can close this ticket.
