### ISSUE TITLE
[UX] 10-10EZR: Run Notifications Ideation Workshop 

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#96212]
## Issue Description
Sibling ticket to [#95743](95743). Running an ideation workshop and post-workshop tasks.

---
## Tasks
- [x] Run workshop
- [x] Document design solutions
- [x] Create tickets for any design/engineering discovery still required to explore options

## Acceptance Criteria
- [x] The team has a design direction for notifications, and the tickets to complete the work

**Comment by RenataKeck** [comment]
[Ideations workshop Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1729187237610/bb0ea1a863e9bc0c5af814b40814dd900852c3ac)
