### ISSUE TITLE
Product Discovery: Display submission status on va.gov

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#96226]
## Issue Description
As a PM I want a clear and concise problem statement respective to understanding submission status and want to know how this can be implemented for form 526 so that I can communicate the problem, solution, and proposed level of effort to the team and our stakeholders.

Much is known about this Veteran problem already and this is a low-risk, high value benefit we can bring to Veterans so we should avoid lengthy discovery and research cycles or activities that are not fit for purpose. By keeping this fast and light, we'll be better positioned to build and ship it to Veterans. Other teams have already implemented this, we'll leverage their knowledge and experience to quickly understand what we should do to implement a similar feature for 526. 

## Tasks
- [x] Identify the people and teams to meet with for the most valuable information
- [x] Meet with folks and ask them how to display submission status on va.gov
- [x] Review existing desk research for information about the problem
- [x] Slack farm to collect known information about the problem & solution
- [x] Write a short, clear and concise problem statement including at least one success criteria
- [x] Document the high level steps to design and build it

## Acceptance Criteria
- [x] Existing knowledge is leveraged to understand the problem and root causes
- [x] A short, clear and concise problem statement is written
- [x] Established design and web component patterns are understood and inform our grasp of feasibility
- [x] Key assumptions and knowledge gaps are identified
- [x] Determine if Collab Cycle is required
- [x] At least one success criteria is established
- [x] The team could start design work on it, if asked (ignoring capacity)
- [x] Results are shared with the team and stakeholders
- [x] At a high level, steps to design and build this are known
- [x] The product roadmap is updated as required

## Additional Information
What open questions do we have from Research, Design, Engineering?
How do backup path submissions impact feasibility?
What should the statuses be on the MyVA card? Similar to the process list? Different?

### Summary
I spoke with Mike M., Aurora H. and Tom H. and learned that MyVA displays a user's list of form submissions along with their statuses on the My VA dashboard page, but MyVA doesn't actively poll for updates. 526 isn't currently in the list of forms that they retrieve status for. Feasibility of displaying an up-to-date submission status on a MyVA card is unclear due to unknown timing of 526 being included in the list of specified forms. Additionally, 526 would need engineering work to provide status to MyVA. One approach we could take would be to make an adapter to get the 526 status and add it on to the response from the SubmissionStatusesController. For changes in the near term, Authenticated Experience team would more likely be involved. MyVA/Profile team is considering how to enable other teams to develop under their guidance, but support for this is a ways off.

### Value
[Findings](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/554) from Authenticated Experience research and Disability Benefits research show that Veterans desire to know the status of their submission, and gaps in understanding this can lear to low confidence in the submission process. It's worth noting however, that our findings were mixed, with 2 of 8 participants sharing that they would check every day to see if their claim was available online. Research also discovered VA Claim Tracker, a third-party tool that "helps veterans review data related to their disability claim. Most veterans filing for disability claims with the VA find it hard to obtain a complete overview of their claim progress. This extension provides more details on the veterans claim status by using data already provided by the claim detail page in an easy to understand format." It is for these reasons, that we deem this to be of value to Veterans.

### Usability
Based on research, the usability of MyVA is mixed. However, Authenticated Experience has already made efforts to improve MyVA. Addressing these challenges is out of our control, due to being a consumer of the MyVA platform, but Veterans expressed that the statuses "were sufficient". 

### Feasibility
Yes, this is feasible to build however it will not be without technical complexity. We could begin to build the functionality on our end to support this feature, but MyVA would still need to query or retrieve for the 526 status, so there is some dependency on the Authenticated Experience. 526 is not currently in their list in the [Form Status on MyVA MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/README.md#functionality--scope) documentation.

We're leveraging the VA Design System Pattern [Stay informed of their submission status](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status). In particular [Showing form submission status in My VA](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status#showing-form-submission-status-in-my-va) which details that 526 would exist separately from 526 subforms, such as 4142 or 0995. 

The Pattern establishes 2 components— Alert and Card.

Because we're leveraging an established Patten and Components, we feel confident about designing this in 2024. Engineering and implementation risks are still valid, but are not considered to be a design blocker.

### Viability
Yes, this solution works for VA. VA has demonstrated solutions in this area, and the established pattern helps move VA.gov teams toward similar solutions. Regarding prioritization, that remains to be seen. While there is clear value to be delivered, there is a dependency on the Authenticated Experience team in order for this to be implemented.

The Authenticated Experience team is currently working to understand if changes to MyVA would require DEBX to go through Collaboration Cycle, but this is unclear at the moment.

Without being on the Authenticated Experience team's roadmap for Form Status on MyVA, it's unclear when we should plan the engineering work, but for now we are still planning on completing the design and we've noted an "Engineering dependency on Authenticated Experience tea,"

More detail on risks & challenges and a proposed solution is described in the [Submission Experience initiative brief.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/product/feature-briefs/Submission%20Experience.md#64-submission-status-on-myva)

### Success Criteria
1. Veterans can find the status of their submission on VA.gov (MyVA)
2. Veterans have the information they need to get help from the contact center
3. Veterans have greater confidence in the submission process

**Comment by mayacarrolluxa6** [comment]
@pacerwow As we discussed, I recommend building on the discovery work we began in Sprint 9 for the “Provide a copy of submission” feature rather than starting discovery on a different aspect of the submission experience. Prioritizing “Provide a copy” in Sprint 10 would allow us to have the 1.0 version of the design ready for engineering. If we pause this work now, the team will need to ramp up again later, which would extend the design process.
