### ISSUE TITLE
686 Updates | ZSF Confirmation Page MVP

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#96220]
## Issue Description
_Update the confirmation page that is shown after a 686 or 674 or 686+674 page is submitted to align with the new design guidance form the zero silent failure initiative._

---
## Tasks
- [ ] Update confirmation page to align to [latest designs](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=2776-51211&node-type=frame&t=enDBpERdNZmmSsIn-0)

## Acceptance Criteria
- [ ] Confirmation page aligns with wireframe
- [ ] Design has signed off on page in staging (QA)
---
