### ISSUE TITLE
[FSR] Wizard - Remove deprecated wizard (Approximately one quarter post launch)

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#96228]
## Issue Description
This is to be completed after the new wizard pages/functionality have been implemented. (Approximately one quarter post launch)
Remove now deprecated wizard components/helpers/files. Be sure to include session storage references in App.jsx.  

## Tasks
- [x] Remove all deprecated wizard code
- [x] Update/remove relevant tests
- [x] Remove Feature flag (TBD- team to discuss best route)

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] All deprecated wizard files are removed
- [x] All tests passing

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
