### ISSUE TITLE
[FE] 10-10CG - Update mailing address for Submission Error Alert

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#96238]
## Summary

We got notice the mailing address for the submission error alert still contains an old address to the Health Eligibility Center in Atlanta, GA. This facility is no longer utilized and we need to update the address to the following:

> 10-10CG Evidence Intake Center
> PO Box 5154
> Janesville, WI 53547-5154

## Screenshot(s)

![Image](https://github.com/user-attachments/assets/8194265a-451f-499e-838d-a3a38a68d7bf)

## Task(s)

- [x] Update content in submission error alert
- [x] Validate with QA/PM
- [x] Release to production

## Acceptance criteria

 - Address display is accurate for the Veteran to submit application via mail.

**Comment by longmd** [comment]
Here is the updated alert:

![Image](https://github.com/user-attachments/assets/478aca06-fe17-4588-a107-ae807b7ff601)
