### ISSUE TITLE
Onboard JR

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#96242]
## Issue Description
_Onboard JR to the non-disability and dependents team._

---
## Tasks
- [x] Access to Coforma Slack
- [x] Access to VA Slack
- [x] Access to repos
- [x] Access to GitHub
- [x] Access to SOCKS

## Acceptance Criteria
- [ ] JR has access to all tools and repos needed
- [ ] JR has shadowed engineers as needed
---
