### ISSUE TITLE
Create an error report for remediation determination

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#96241]
## Description

We need to generate a report to help determine the scope of errors and assist in defining what instances need to or can be remediated.

**Fields we would like to see:**
Account identifier
Contact information (Email or phone#?)
Date of error
Type of error
Is there a current debt

**The end goal is to apply one of these attributes to each instance:**
Total resolved: #
Total unresolved: #
Total unrecoverable: #

## Tasks
- [ ] Source a way to pull a report and provide a sample
- [ ] Create an automated report

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [X] Not Required

## Acceptance criteria
- [ ] An approved report is provided to the PO/PM
- [ ] The report can be sourced by the PO/PM or is automated

## Testing
- [X] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [X] Description written
- [X] Tasks defined
- [X] Acceptance criteria written
- [X] Testing defined
- [X] Add Labels
- [X] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by Tom-Davis** [comment]
@digitaldrk once we have the data points that "can" be pulled in the report we can refine that we would like to see from those.

@denisecoveyduc once we have a sample report, we can look at how to add resolution states and move forward from that.

**Comment by dhill802** [comment]
All set per Denise. Closing.
