### ISSUE TITLE
686 Updates | E2E UAT Testing

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#96274]
## Issue Description
_Once phase 2 updates are done, end-to-end testing needs to be done in the [staging environment](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c-v2/introduction)._

Testing should confirm:
- The pdf generated and received by the VA matches what the user entered on VA.gov.
- Claims are [off-ramped by VA.gov](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/dependents/RBPS-offramp-scenarios.md) for manual processing (as expected)
- The json data received by RBPS can be processed as expected:
   - Processed automatically by RBPS
   - Off-ramped from VA.gov for manual processing (as expected)

Instructions for testing:

1. Test assigned [scenario](https://docs.google.com/spreadsheets/d/1Hd9pWDVzfduV2UsYF7eUqXJ_PShJeo5yLrgwvZJ5Nak/edit?gid=1908961305#gid=1908961305).
2. Follow directions where specified and fill out with dummy info where not specified
3. Capture screenshot of review page BEFORE submission and save in [this folder](https://drive.google.com/drive/folders/1wknuOQG2Euqt66mYRqQvH4Gje_LiW4-Z?usp=drive_link). Use submission date + GUID as file name (e.g. 2024.04.05_cb2298e8-8411-495c-9b58-586288eeaf95).
4. Capture claim confirmation # (GUID) from confirmation page and add to submission tab in [this sheet](https://docs.google.com/spreadsheets/d/1mBEZJ7gORRMpsFVUAXr5wi5NYH-CaKc5njb4EJKZtfo/edit?usp=sharing).
5. Product Manager will work with backend engineer to convert the GUID to a Participant ID.
6. Product Manager or backend engineer will give the ParticipantID to OBI via a [Teams channel](https://teams.microsoft.com/l/channel/19%3A7Dew_Vfcs2z_BJK7XVhgWbaSQfJej2UO13Kq51sebX81%40thread.tacv2/General?groupId=954a8eef-0c1f-4129-8eea-94149c3fef97&tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf) and in [mvp-686-674-staging-pdf](https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FDependents%20Management%2Fmvp%2D674%2Dstaging%2Dpdfs&viewid=3fa7a9bb%2D3d4e%2D44c2%2Db93f%2D629268a08e72&OR=Teams%2DHL&CT=1717096760601&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNDA0MTEyMjMxNSJ9) SharePoint folder.
7. The following individuals should be tagged in the Teams thread to validate the claim went through BGS, VBMS, and RBPS as expected:
  - Sanja Bajovic (Lifestage PO)
  - I, Tara: Program Analyst
  - Elizabeth Reeher: Project Manager
  - BGS/VBMS:
    - Caleb Roberts: Government lead on testing team:
      - Daniel Lattin
      - Donald Moses
      - Benjamin Brown
  - RBPS
     -  Baha Abu Khaled
     -  Linda Ciston (semi-retired, but a backup for Baha)
     -  Jim Keese
     -  Benjamin Brown
     -  Daniel Lattin
     -  Donald Moses
     -  Elizabeth Reeher
     -  Caleb Roberts

---
## Tasks
- [x] Test identified scenarios in VA.gov staging [according to instructions](https://docs.google.com/spreadsheets/d/1Hd9pWDVzfduV2UsYF7eUqXJ_PShJeo5yLrgwvZJ5Nak/edit?gid=1908961305#gid=1908961305)
- [x] Document encountered bugs
- [x] Remediate bugs that prevent form submissions
- [ ] When initial 8 scenarios are successfully submitted on VA.gov Staging, ensure BE integrations worked properly
- [x] Prepare data payload for downstream partners
- [x] Delivery data payload and notify team in appropriate Teams channel
- [ ] Respond to feedback from downstream partners and prioritize launch-blocking bugs
- [ ] Repeat until no launch-blocking bugs remain

## Acceptance Criteria
- [ ] 686-only submission scenarios are successful and accepted by BGS/RBPS/VBMS
- [ ] 674-only submission scenarios are successful and accepted by BGS/RBPS
- [ ] 674+686 submission scenarios are successful and accepted by BGS/Central Mail
---

**Comment by jacobworrell** [comment]
This ticket is now duplicative so closing
