### ISSUE TITLE
[FE] 10-10CG - Update mailing address in Submission Error Alert

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#96284]
## Background
Gaspare from the CG stakeholder team informed us that the old Atlanta address is still showing on the Confirmation Error alert.  Upon review, we confirmed this and need to update it to the latest Janesville address

> 10-10CG Evidence Intake Center
>PO Box 5154
>Janesville, WI 53547-5154

## Tasks
- [x] Update address on Submission error alert box
- [x] Validate alert is displaying the new address appropriately
- [x] Launch to production

## Acceptance Criteria
- Mailing address for applications to be sent is updated to the latest Janesville, WI address

**Comment by hdjustice** [comment]
duplicate of 96238
