### ISSUE TITLE
User submissions failed due to empty disabilities array - backend fix

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#96289]
This ticket is to implement a backend fix for the following [bug](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95368). In a nutshell, users are somehow submitting claims with no "NEW" or "INCREASE" disabilities (i.e. all their ratedDisabilities are marked "NONE")- which is not supposed to be allowed. The result is that an empty disabilities array is sent to the LH submit request, which fails the submission.

The impact to the veteran is that their initial attempt(s) at submission fail. We believe it fails visibly to them, because the pattern observed is that they return a few days later and resubmit their application successfully.

The short-term fix here would be to detect the absence of "NEW" or "INCREASE" disabilities, and return an error in the `submit_all_claim` response before it is sent to the submit service.

## Tasks
- [ ] Implement a stop-gap fix for incoming submissions sans NEW of CFI disabilities

## Acceptance Criteria
- [ ] Implement a fix that fails the submission at the controller level if no "NEW" or "INCREASE" disabilities are found on a submission coming in from the FE
- [ ] Unit tests as needed
