### ISSUE TITLE
Connect with mobile app team to answer unknowns from research

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96295]
## User Story
As a subject matter expert for the Governance team, I want to connect with my SME counterpart on the VA Mobile App Core team so that I can learn mobile app specific guidance for when mobile app products are brought through the Collab Cycle.

Assignee: @allison0034 @briandeconinck @erinrwhite @it-harrison @KKitagawa-Bosch 
Peer Reviewer: @shiragoodman 

## Description
Governance team has completed our mobile app discovery research and has compiled a[ list of questions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3632398343/Prioritized+questions) for the Mobile App team. The current Mobile App core team contract ends on 12/16, so we have a tight timeline for connecting with them to get our questions from research answered. 

The purpose of this ticket is for the 5 subject matter experts on Governance (design, content, IA, accessibility and QA) to connect with the equivalent role on the Mobile App Core team in order to better understand their role and uncover any gaps in knowledge.

### Live pages
- [Governance/Mobile App SME Notes](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3680600080/Governance+Mobile+App+SME+Notes)

### Drafted pages
- 

## Tasks
- [ ] QA to connect with QA from Mobile App team (Therese Dickson)
   - Therese informed Ian that she is not available and suggested Ian connect with Tim Wright. 
- [x] Accessibility to connect with Accessibility from Mobile App team (Brea Blackwelder)
    - Meeting scheduled for 11am CT on 12/12 
- [x] IA to connect with IA from Mobile App team (Holly and Misty)
- [ ] Content to connect with content from Mobile App team (Misty)
- [x] Design to connect with design from Mobile App team (Lauren Russell)

- [ ] Please ask to record meeting 
- [ ] Contact Shira if you need to use her Zoom account
   - Shira is available to attend meeting if you'd like her there to help move the conversation along
- [x] Please document findings and share recording link [here.](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3632398343/Prioritized+questions)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] QA SME has met with QA counterpart from Mobile app team and documented responses to questions, if applicable, and any gaps in knowledge. 
- [x] Accessibility SME has met with Accessibility counterpart from Mobile app team and documented responses to questions, if applicable, and any gaps in knowledge. 
- [x] Content SME has met with content counterpart from Mobile app team and documented responses to questions, if applicable, and any gaps in knowledge. 
- [x] IA SME has met with IA counterpart from Mobile app team and documented responses to questions, if applicable, and any gaps in knowledge. 
- [x] Design SME has met with design counterpart from Mobile app team and documented responses to questions, if applicable, and any gaps in knowledge. 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Meeting with Lauren Thursday.

**Comment by shiragoodman** [comment]
I am meeting with PM Kelly Lein on Tuesday 12/17

**Comment by KKitagawa-Bosch** [comment]
@erinrwhite and I met with Content and IA folks this morning, and it was very informative! Lots more to learn

**Comment by erinrwhite** [comment]
Sharing [notes for our call with Content and IA](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3691773970/Conversation+with+Content+and+IA+specialists+from+Mobile+App+team#Notes-from-our-call) along with a link to video recording.

**Comment by shiragoodman** [comment]
@it-harrison what is the status of your call with Tim Wright?
