### ISSUE TITLE
User submissions failed due to empty disabilities array - frontend investigation

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#96290]
## Issue Description
This ticket is to investigate and implement a frontend fix for the following [bug](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95368). In a nutshell, users are somehow submitting claims with no "NEW" or "INCREASE" disabilities (i.e. all their ratedDisabilities are marked "NONE")- which is not supposed to be allowed. The result is that an empty disabilities array is sent to the LH submit request, which fails the submission.

The purpose of this ticket is to determine what conditions allow this submission to happen, even though there is active validation in the FE to disallow this type of submission

---
## Tasks
- [ ] Determine how users are proceeding to submit the application without selecting a new or increase in an existing condition

## Acceptance Criteria
- [ ] Implement a fix that ensures that the user cannot submit an application without selecting a new or increase in an existing condition
- [ ] Unit tests

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
