### ISSUE TITLE
Connect with OCTO-DE to answer unknowns from research

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96294]
## User Story
As a Governance team member attempting to understand the expectations and scope boundaries of bringing the mobile app into Collab Cycle, I want to connect with OCTO-DE so that I receive answers on our unknowns from both the Cognitive Walkthrough and Diary Study research sessions.

Assignee: @erinrwhite 
Peer Reviewer: @briandeconinck 

## Description
Governance has completed the Cognitive Walkthrough and Diary Study research sessions, based off our [Research Plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3436871682/2024-09+Research+plan+for+folding+mobile+app+into+the+Collaboration+Cycle) for bringing Mobile App into Collaboration Cycle. In our research findings, we had several questions for our OCTO-DE Design Practice Area leads to help us better understand what to expect from VFS teams building on mobile, as well as what the plans for other non-VFS teams that could have an impact on Governance and Collab Cycle. All of those questions have been grouped and prioritized based in ticket #96523.

The purpose of this ticket is to reach out to our OCTO-DE leads to get their input on the questions from our research findings. 

### Live pages
- 

### Drafted pages
- 

## Tasks
- [x] Reach out to @humancompanion-usds via the Governance team Slack channel to determine who, aside from Ryan Thurlwell, we should be connecting with to get input from re: our research findings for mobile
- [x] Schedule a session with the requested OCTO-DE folks
- [x] Synthesize [questions for OCTO-DE](https://vfs.atlassian.net/wiki/spaces/PPST/database/3632365611?savedViewId=692c5543-5bec-42c0-a336-3f0ef7b2b9e7) to create a conversation guide for the call
- [x] Meet with OCTO-DE folks, record the session, and ask our questions in priority order
- [ ] Determine how we will keep track, and document all responses (as well as the responses from Rachel Han). Do we have more questions post- meeting? Do we need to schedule a follow up? Or can we make assumptions? Does the response impact the CC operational process, VA.gov Experience Standards, and/or our learning plans for each practice area?

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have connected with OCTO-DE to answer our unknowns from the Mobile App research 
- [ ] We have documented their responses

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
Call with OCTO leads scheduled for Monday 12/2. Reviewing [our questions for them](https://vfs.atlassian.net/wiki/spaces/PPST/database/3632365611?savedViewId=692c5543-5bec-42c0-a336-3f0ef7b2b9e7) and will synthesize a high-level overview doc to guide our conversation next week.

**Comment by erinrwhite** [comment]
[Synthesized/refined a list of questions for our conversation](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3666214913/Conversation+with+OCTO-DE+leads) - sharing with team for as many eyeballs as possible ahead of our call next week

**Comment by shiragoodman** [comment]
@erinrwhite I added a couple comments - nothing major. I think we just want to make sure we guide the conversation if it goes off course. I can help with this if you'd like.

**Comment by erinrwhite** [comment]
[Recording of call](https://oddball-io.zoom.us/rec/share/eOPt65jFoYT5otK-bbJjORx9hz5L99QYxPITmuV4NTBldezKovz1zN__3wWERAmq.P4gisrJV3INhCfd6) 
Passcode: `wECsu!9&`

Meeting with @shiragoodman on Friday to talk next steps - this ticket will carry over into the next sprint!

**Comment by erinrwhite** [comment]
Shira and I met last Friday and came up with some next steps for this initiative. We'll convene the team again in early '25 to redo our walkthrough about process changes for the mobile app, now that we know what we know after chatting with OCTO leads and our practice-area counterparts. Closing!
