### ISSUE TITLE
Edit: Update the Feedback Footer links

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#96331]
## Issue Description
In ticket [90696](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?filterQuery=90696&pane=issue&itemId=84087725&issue=department-of-veterans-affairs%7Cva.gov-team%7C90696) we decided to update the [Provide or Suggest New Content for the Platform Website page ](https://depo-platform-documentation.scrollhelp.site/support/how-to-provide-and-suggest-new-content-for-the-pla) to include a link at the **top** of the page directly to the [Documentation Support Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=vbellissimo%2C+amygoldman&labels=documentation-support%2C+platform-content-team&projects=&template=documentation-support-request.yml&title=Documentation+support)

---
## Tasks
- [x] Per the Slack thread below,`add a callout box at the top of the instructions that says, in essence, if you want to go right to GitHub here's the link but if you need instructions, see below.`

![Image](https://github.com/user-attachments/assets/775ee945-950d-4ea9-a610-613d987afc2a)

## Acceptance Criteria
- [x] All tasks complete

## Relevant 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by taylojill** [comment]
I added a blue info box after the introduction. Page date stamped, checked for blockers and SG issues. Ready to publish!

**Comment by jknipes** [comment]
While [ticket 92645 is currently blocked](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?filterQuery=&pane=issue&itemId=84087622&issue=department-of-veterans-affairs%7Cva.gov-team%7C92645), we decided to work on this small ticket.

**Comment by jknipes** [comment]
Added to Current Sprint due to available capacity. Work is completed, closing as _Done_
