### ISSUE TITLE
[CDP] Why might I have this debt additional info component copy updates

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#96336]
## Description

Enter a detailed description of the work - gherkin syntax below is acceptable.

Given: A veteran has an overpayment
When: They see their debt detail
Then: They should have relevant additional info text

Update additional info content based off CAIA feedback, part 2 of #92812

## Tasks
- [x] Clean up figma file
- [ ] Update code in the CDP 

## Design and Front End sync on implementation of design
- [X] Required
- [ ] Complete
- [ ] Not Required

## Acceptance criteria
- [x] Figma file has been updated with new content
- [ ] PR with new content has been merged

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
