### ISSUE TITLE
Update data payload for next steps email endpoint

### ISSUE THREAD

**Issue by opticbob** [department-of-veterans-affairs/va.gov-team#96353]
## Background
There are some validation issues with the interplay between the frontend and the backend for the next steps email endpoint. We are going to move from sending a rep name, address, and type to sending a entity_type and entity_id so those values can be looked up on the backend. This will make it easier to cover both selections of individuals and orgs as a whole.  The frontend also needs to send the `email_address` field.

## Tasks
- [ ] Remove `representative_address`, `_name`, and `_type` fields.
- [ ] Add `entity_type` that should be validated to be `individual` or `organization`.
- [ ] Add `entity_id`.
- [ ] Add `email_address`.  If there is a claimant email it should be that one, if not we should use the veteran's email.

## Acceptance Criteria
- [ ] The frontend will generate a payload that return a 200 status from the backend.

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/32886
