### ISSUE TITLE
Lookup rep and org info for next steps email

### ISSUE THREAD

**Issue by opticbob** [department-of-veterans-affairs/va.gov-team#96351]
## Background
There are some validation issues with the interplay between the frontend and the backend for the next steps email endpoint.  We are going to move from sending a rep name, address, and type to sending a `entity_type` and `entity_id` so those values can be looked up on the backend.  This will make it easier to cover both selections of individuals and orgs as a whole.

## Tasks
- [x] Remove `representative_address`, `_name`, and `_type` fields.
- [x] Add `entity_type` that should be validated to be `individual` or `organization`.
- [x] Add `entity_id`.
- [x] Use those two new fields to lookup the entities from both the legacy and accredited tables like we do in the PDF data objects.

## Acceptance Criteria
- [x] Frontend payloads that match the changes above will send the next steps email from VA Notify and return a 200 status.

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by opticbob** [comment]
I'm working on fixing the last test and the [PR for this](https://github.com/department-of-veterans-affairs/vets-api/pull/19249) will be ready for review.  I anticipate that happening early tomorrow morning.

**Comment by opticbob** [comment]
@holdenhinkle Has approved the PR for this.  If platform hasn't approved it by 11:15 CST tomorrow I'll ping them.

**Comment by opticbob** [comment]
I pinged Platform today and was informed that their policy is currently to have developers wait 3 business days after their teammates approval before requesting a PR review.

**Comment by opticbob** [comment]
Platform has commented on the PR but hasn't responded to further comments.
