### ISSUE TITLE
Handle VSOs and VSORs with only one organization, for PDF generation

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96361]
## Background
We have uncovered that when a user selects the following representatives types, the PDF cannot be generated for the user to download:
1. An entire VSO: when selecting an Organization only, the frontend tries to pass that to the backend as if the org was a representative. The backend can't find a representative with the org's id and throws an error. Additional errors are thrown for the validation related to organizations because we're telling the backend there is no organization, there's only a rep.
2. A VSO representative, who is associated with only one organization: the organization id is not being passed to the backend.

## Tasks
- [ ] Pass the organization ID to the backend **as an organization** (not a representative) when an entire VSO is selected 
- [x] Pass the organization ID to the backend when a VSO representative with only one organization has been selected

## Acceptance Criteria
- [x] A PDF can be generated for users, when they select a VSO or a VSOR with only one organization.

**Comment by oddball-lindsay** [comment]
Looking good @jvcAdHoc! Confirming I am able to generate/download the PDF when:
1. a VSO representative with only one organization has been selected -- tested with VSO rep "John Lee".
2. an entire VSO has been selected -- tested with VSO "Gold Star Wives of America, Inc.".
