### ISSUE TITLE
[CST][Analytics] Make it so we can distinguish 1P and 3P requests in GA

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#96365]
## Value Statement

We're trying to run analysis to determine how many people who view a detail page, ultimately end up submitting evidence within the first week of viewing such requests. The problem is that the way we're currently doing this analysis is tracking who converts from /document-request/ pages, but that's the same URL structure used for 3P request detail pages. We want to only be looking at numbers converted from 3P requests. We need to provide a way for GA to distinguish 1P and 3P requests to run this analysis.
 
---
### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Google Analytics is able to distinguish a 1p and 3p requests.

**Comment by pmclaren19** [comment]
Please provide guidance for how we should resolve this issue @jacobworrell
