### ISSUE TITLE
Edit: Mitigating and Handling Leaked API Keys

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#96374]
### OVERVIEW
The Product Team asked us to move a doc into the IA for them. While assisting them with this request, we noticed that the doc contains several instances of alert emojis. The best practice here is to use Info Boxes. We need to update that page by converting the alert emojis into info boxes. 

### TASKS

- [ ] Convert alert emojis into the appropriate info box. 
- [ ] Re-edit text as necessary to make formatting clean and understandable. 
- [ ] Prep page for deployment

### Acceptance Criteria

- [ ] Updated page has been deployed

**Comment by taylojill** [comment]
All emojis replaced with info boxes as requested. Page checked for SG issues and blockers, date stamped, ready to publish.
