### ISSUE TITLE
Tiered status of alerts

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#96375]
## Issue Description
The purpose of this ticket is to track multiple categories of alerts to provide better insight into which are actionable and which are non actionable.

Guidance on the approach from Steve Albers [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/architectural-decision-records/more-actionable-alerts.md)

Note:
Steve and Sanja would like us to tackle this late in December
---
## Tasks
- [ ] Review guidance from rom Steve Albers [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/architectural-decision-records/more-actionable-alerts.md)
- [ ] Update the system and monitors per guidance

## Acceptance Criteria
- [ ] The systems and monitors are updated per documented guidance.
---
