### ISSUE TITLE
5103 and claim certification: Deploy to prod

### ISSUE THREAD

**Issue by tommasina-va** [department-of-veterans-affairs/va.gov-team#96383]
After we review the 5103 and signature component work in Staging, we need to remove the environment checks to release this into production. 

As a Veteran, I can review 5103/evidence requirements and certify that I have received notice of evidence needed to complete Form 21-526EZ. 

### Tasks 
- [ ] Remove environment checks in vets-website
- [ ] Update all unit and e2e tests as needed with new certification flow

### Acceptance Criteria
- [ ] 5103 Notice of Evidence on Introduction page and Supporting Evidence page are visible and functional in production
- [ ] Signature component on Review and Submit is visible and functional in production
- [ ] Regression test(s) to verify claim is submitting as expected

**Comment by christinec-fftc** [comment]
Noting that we can start work on these code changes and testing, but that we can't merge the pr until we're ready to launch
