### ISSUE TITLE
DR | Notify when jobs run out of retries

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#96419]
## Value Statement

**_As a_** Veteran

**_I want to_** receive notifications if there is an issue with my submission

**_So that_**  I can address the issues and/or submit via another avenue
---

## Background Context
- Decision Review jobs (`Form4142Submit` and `SubmitUpload`) do not automatically notify the user of an issue when they run out of retries

#84372
#94461

## Outcome, Success Measure, KPI(S), and Tracking Link

- If a failure occurs, the user is notified via Email with steps to achieve a favorable outcome if needed

## Acceptance Criteria

- [x] Update jobs to send notifications to needed parties with information to resolve the issue
- [ ] Refactor FailureNotificationEmailJob to minimize code duplication

## Designs and Build Notes

- Add here

### Enablement team (if needed)
@ member of team

## Out of scope

- Add here

## Open questions

- Do we need different email templates for this (i.e. can the user resubmit online instead of telling them to mail in evidence)?

## Tasks

- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
Will have a PR ready today.

**Comment by dfong-adh** [comment]
PR ready for review: https://github.com/department-of-veterans-affairs/vets-api/pull/19337

**Comment by eileen-coforma** [comment]
Can be tested within staging, but can't really test in PROD, no way of forcing retries. Will close when tested in PROD.

**Comment by dfong-adh** [comment]
Verified in staging.
