### ISSUE TITLE
Update number of days to complete disability-related claims for April 2020

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#9641]
## User story
As a Veteran, I need to know the most recent average number of days it takes VA to make a decision on disability-related claims so that I can further understand the claims process.

## Issue Description
Update the number of days to **105.9** and change month to **April 2020** per Sandy Tadeo on two disability pages
![Screen Shot 2020-05-29 at 12.12.38 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/a509c648-1812-4870-9735-3e93666d6530)
## Tasks
- [x] Update number of days and month on [How to file a claim](https://www.va.gov/disability/how-to-file-claim/) and [After you file a claim](https://www.va.gov/disability/after-you-file-claim/) pages.

## Acceptance Criteria
- [x] Changes are on live site
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
These changes have been made. Moving to validate. FYSA @stephorkandatx

**Comment by RLHecht** [comment]
These changes have been validated on live site. Closing ticket. FYSA @stephorkandatx
