### ISSUE TITLE
Create Wireframe & Content for Aynsychronous Appt Scheduling Notification

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#96418]
Based on the userflow created for asynchronous appt scheduling notification, we need to create or update our designs for this process. 

## Tasks
- [x] Create or update designs in CC
- [x] Run by UX 
- [x] Get any approval needed (i.e. Kristen)
- [x] Add to CC MVP scope page once confirmed

## A/C
- [x] Designs created or updated
- [x] Designs added to CC MVP scope page

**Comment by StevenStraily** [comment]
This has been narrowed down to what we believe is one real [viable option](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=6335-4251&t=CwbMQA3svtXZtt7E-4). The logistics and content for the ZSF messaging we would be sending out will need to be looked at in a future sprint.

**Comment by StevenStraily** [comment]
@cgednalske @zach-park I believe this is ready to close out; let me know if I missed anything; thank you!

**Comment by cgednalske** [comment]
@StevenStraily maybe check with the engineers to see if they need any more (initial) annotations, but looks good to me and like you covered everything 🎉
