### ISSUE TITLE
[Design Debt] VADS spacing update (Breadcrumb)

### ISSUE THREAD

**Issue by zach-park** [department-of-veterans-affairs/va.gov-team#96429]
## Background
VADS guidelines recently released new spacing guidelines for the breadcrumb that will need to be applied to current CIE wireframes (20px top and 32px bottom).

VADS:
https://design.va.gov/components/breadcrumbs

Figma:
https://www.figma.com/design/fy5a9MDhPRKOFucfKITYhw/Design-System-Updates?node-id=1-2&t=rMEzLJIeNSGyWaQ9-1

## Tasks

Inspect and see if all breadcrumb components (in the CIE Figma files) can be redirected to the VADS component
- [x] If so, redirect them from the breadcrumb component in the [MHV component library](https://www.figma.com/design/ktX3at2KixnYf2G6MoBSuC/MHV---Unified-Appointments-Library?node-id=482-2417&t=IPMXFbfrNgCOHCon-1) to the VADS. Also remove the section in the MHV component library
- [x] If not, make updates to the MHV component library instead

Review the following figma files. Make updates if necessary
- [x] Check-in Figma file: Latest Design page (or also include In-progress pages?)
- [x] Pre-check-in Figma file: Latest Design page (or also include In-progress pages?)
- [x] Production Figma file: Check in design - in person page and Pre-check-in design - in person page

## AC

- [x] Updated Check-in / Pre-check-in designs / Production Figma files

**Comment by loripusey** [comment]
@zach-park @cgednalske can you point this one please?

**Comment by zach-park** [comment]
Tagging @Cieramaddox for the future collab.

**Comment by zach-park** [comment]
@StevenStraily , @cgednalske , @cgednalske , ready to be validated.

I co-worked with @Cieramaddox to add a simplified header to the existing header from the appt component in the mhv component library. 

Updated are made to to following figma file and pages:
- Pre-check-in: [Latest design page](https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=72-19372&t=0QCCpPvf5aSoyKfB-1)
- Check-in: [Lates design page](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=3541-9132&t=uHwdTLph1xpjtcAT-1)
- Production: 
   [Pre-check-in design - in person page](https://www.figma.com/design/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-PCI?node-id=239-860&t=j974tvpD4CmcoCIF-1)
   [Check in design - in person page](https://www.figma.com/design/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-PCI?node-id=239-860&t=j974tvpD4CmcoCIF-1)

**Comment by Cieramaddox** [comment]
@zach-park I looked through everything here and it all looks great!

**Comment by StevenStraily** [comment]
@zach-park Looks good to me as well.
