### ISSUE TITLE
Update Drafting Template for recent changes

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96426]
## User Story
As a Governance team member supporting Collab Cycle, I want to ensure that the DraftingTemplate is up to date so that I can rely on it for tagging accurate experience standards and descriptive tags in the SR process.

Assignee: @erinrwhite 
Peer Reviewer: @KKitagawa-Bosch 

## Description
There have been several changes recently that impact the DraftingTemplate, including:

- changes to the Content Style Guide
- updates VADS components and patterns
- new VA.gov Experience Standard for notifications

The purpose of this ticket is to ensure the DraftingTemplate is accurate and reflects the correct references for descriptive tags.

### Live pages
- 

### Drafted pages
- 

## Tasks
- [x] Identify the updated VADS components, CSG pages, and Experience Standards that have been modified recently
- [ ] Following the [Updating experience standards and descriptive tags guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards#Updating-Experience-Standards-and-descriptive-tags) make the appropriate changes to the DraftingTemplate and other applicable Sources of Truth documents
- [ ] Peer review

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The DraftingTemplate has been updated to reflect the current experience standards and descriptive tags

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
FYI - I spoke with @aprocik1 and @NaomiPMC at the Governance/CAIA sync on 11/8 and made them aware of this ticket.

**Comment by aprocik1** [comment]
These are the updates worth noting:

> Content style guide updates
> 
> * In [Email and text notifications](https://design.va.gov/content-style-guide/email-and-text-notifications): Added new page with general guidance for email notifications. [[PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3406)]
> * In [Bulleted lists](https://design.va.gov/content-style-guide/bulleted-lists): Added clarification that single sentences don't require punctuation. [[PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3268)] 
> * In [Use short sentences](https://design.va.gov/content-style-guide/plain-language/use-short-sentences): Added "so" as a word that we start sentences with. Added a suggested guideline for maximum sentence length (25 words). [[PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3268)] 
> * In [Sign in and identity verification special topic section](https://design.va.gov/content-style-guide/specific-topics-and-programs/sign-in-and-identity-verification): Made several updates to word list related to sign-in changes and clarified guidance around when and when not to use "verify your identity"
> 
> Design system updates
> 
> * In [Phone numbers](https://design.va.gov/patterns/ask-users-for/phone-numbers#content-considerations): Reviewed new field label and error message for international phone numbers. [[PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3446)] 
> * In [Alert - Sign - in](https://design.va.gov/components/alert/alert-sign-in/): Clarified when to use the alerts. [[PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3431/files?short_path=6ffcd50#diff-6ffcd50f2b28561dc4c2591a76ada2a7635ff28026a640981d81a3e0da2b9db7)] 
> * In [Help users stay informed of their application status](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status): Updated the example templates and explained when to use the different versions depending on how the forms are submitted. [[PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3402)]
> 
> Other updates 
> 
> * Crosslinks guidance with Radio button and Checkbox components. [[PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3268)] 
> * Adjusts Like this / Not this examples for accessibility. [[PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3268)]

We're going to ask Matt to add the content style guide to [this section of VADS](https://design.va.gov/about/whats-new), so that future updates are more readily visible.

**Comment by erinrwhite** [comment]
@aprocik1 this is amazing! Thanks so much!

**Comment by shiragoodman** [comment]
@erinrwhite i learned in Team of Teams today that there is new guidance published from the AE Design Patterns team on Help users to... Know when their information is prefilled ![Image](https://github.com/user-attachments/assets/2f26d741-97b2-477c-b0ff-86b0443af456)

**Comment by erinrwhite** [comment]
Work in progress - updating our [Source of Truth spreadsheet](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit?usp=drive_link)

**Comment by shiragoodman** [comment]
@erinrwhite I will review this by EOD - thank you!

**Comment by KKitagawa-Bosch** [comment]
@erinrwhite everything looks good to me, should I run a test upload for posterity or have you already done that?

**Comment by erinrwhite** [comment]
@KKitagawa-Bosch It's helpful but not required - I usually just copy/paste into a new github issue and see if the code looks right!

**Comment by shiragoodman** [comment]
@erinrwhite I don't see the Utilities: Position listed in Design Foundation in the source of truth document

**Comment by erinrwhite** [comment]
@shiragoodman Ack! You're right. Adding it in.

**Comment by shiragoodman** [comment]
@erinrwhite I have validated that all identified changes have been added to the source of truth. I have also verified that all changes are working as expected in the revised DraftingTemplates for VFS and DST.

I am going to close this out, however please be sure to archive the old DraftingTemplates and move the new ones to their correct location in Google Drive. Thank you!

**Comment by erinrwhite** [comment]
@shiragoodman thank you for the last-minute fixes! I have moved these files into production and saved the old DT's in our backups folder.
