### ISSUE TITLE
Update QA artifacts in SR code block for logging silent failures

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96427]
## User Story
As a VFS team member, I want to be able to rely on the guidance in my Collaboration Cycle Request ticket so that I can ensure my team is prepared for any upcoming touchpoint. 

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
Governance team introduced a new QA standard via ticket # for logging silent failures. However, we did not update the QA artifacts guidance that lives in already open Collab Cycle Request tickets.

The purpose of this ticket is to make modifications to our script for updating the Collaboration Cycle Request ticket to include a line for the new logging silent failures standard, and then execute the script. The assignee should follow [this guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3553755390/Github+Ticket+Issue+Uploader+Tool) for making changes to the open Github issue tickets. 

### Live pages
- 

### Drafted pages
- 

## Tasks
- [ ] Following the guidance shared above, make the updates to the Staging Review/QA Artifacts section of the Collaboration Cycle Request ticket
- [ ] Execute the script
- [ ] Validate that tickets have been updated successfully.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] All open Collaboration Cycle Request tickets have up to date guidance on the QA artifacts

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@briandeconinck all tickets have been updated and the commit for the script update is [here](2a9657424b5f64cf02eb26cdf8e9ea37d1d3663b)

**Comment by briandeconinck** [comment]
@it-harrison I'm not seeing the logging silent failures item in Collab Cycle tickets with [status Awaiting Staging Review](https://github.com/orgs/department-of-veterans-affairs/projects/998/views/15?filterQuery=status%3A%22Awaiting+Staging+Review+Scheduling%22). Were those intentionally excluded?

**Comment by briandeconinck** [comment]
@it-harrison Fix looks good! You're good to close!

**Comment by briandeconinck** [comment]
Er... I accidentally closed it for you 😆 🤦
