### ISSUE TITLE
Update Collaboration Cycle Contact Us Page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96421]
## User Story
As a VFS team member, I want to know who supports the Collaboration Cycle, so that I know I'm connecting with the right people.

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @it-harrison 

## Description
As of 1/29/2025, the following issues exist on the Collaboration Cycle Contact Us page:

- Ryan Thurlwell, Mobile lead, is missing
- Beth Potts can be removed as content lead
- OCTO-DE Security and engineering leads are missing (Don McCaughey, Jeff Keene, Jonathan Kamens)
- CMS titles and roles have changed
- CAIA team is in transition. The new contract for content and IA may have a new name

The purpose of this ticket is to update the page to be as accurate as possible, however the CAIA roles and titles may need to change later on once more information is learned.

### Live pages
- [Contact Us](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us)

### Drafted pages
- [Contact Us Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3826614273/96421+-+Collab+Cycle+Contact+Us+Page)

## Tasks
- [x] Reach out to Don, Jeff, Jonathan to learn of their titles and what practice area they lead. You can do this via the #platform-collaboration-cycle channel. Let them know the reason why we're doing this (ie I don't want to get answers like "Product Owner" bc that's not helping anyone)
  - [x] Update information accordingly
- [x] Reach out to Grace from CMS team to let her know we're updating the titles and roles for CMS. Give her the option to only have her role and a technical role listed. Not every member of her team needs to be listed. This will make it easier for us to maintain.
  - [x] Update information accordingly 
- [x] Add Ryan, remove Beth
- [x] For CAIA, remove section entirely. We will add them back in later once more is known.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have updated the Contact Us page with known, up-to-date information of supporting teams in the Collaboration Cycle

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by KKitagawa-Bosch** [comment]
@it-harrison all the info should be updated per the task list and good to review!

**Comment by it-harrison** [comment]
@KKitagawa-Bosch  - looks good. The only thing to note is that the order of Title: Name is reversed for the last two people listed under Additional Support:

<img width="432" alt="Image" src="https://github.com/user-attachments/assets/e3be0bff-dfcc-4c26-ba76-5a675ec61f23" />

**Comment by KKitagawa-Bosch** [comment]
ooh good catch! 

Fixed and pushed to the live page!
