### ISSUE TITLE
Remove Sitewide CAIA label from Collaboration Cycle Request template at kickoff

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96424]
## User Story
As a Governance team member, I want to remove the Sitewide CAIA label from our yaml template at CC Kickoff so that it doesn't introduce confusion for VFS teams because it is no longer used.

Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
Sitewide CAIA is no longer using the `sitewide CAIA` label that is automatically added to all CC Requests via the kickoff. The purpose of this ticket is to edit the yaml template to remove the `sitewide CAIA` label.

### Live pages
- [Collab Cycle request YAML template ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collaboration-cycle-request.yml)(edit version)
- [Collab Cycle request YAML template ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2CCC-Request%2Csitewide+CAIA&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)(live version)
- [Collaboration Cycle kickoff request (Platform website)](https://vfs.atlassian.net/wiki/spaces/CC/pages/1760493650/Collaboration+cycle+kickoff+request)
### Drafted pages
- 

## Tasks
- [x] Edit the yaml template to remove the `sitewide CAIA` label
- [ ] ~~submit a pull request for peer review~~
   - [x] Committed change directly without thinking...
- [x] publish changes
- [x] Update link in Collab Cycle kickoff page of Platform website to remove label

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Collab Cycle Request tickets no longer include the `sitewide CAIA` label by default when the ticket is created

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@allison0034 Ready for review. A couple of notes:
- I added (and completed) a task to update the link on the [Platform website kickoff page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1760493650/Collaboration+cycle+kickoff+request) to remove the `sitewide-CAIA` label from the link to start a GitHub ticket. Since the label was included in the link it would be added to the ticket for anyone following that link even with it removed from the yaml template. Change saved, should be updated on Platform website the next time it publishes.
- The ticket said to create a pull request for you to review and I... got a little ahead of myself and just committed the change directly to the master branch. 🤦

**Comment by allison0034** [comment]
Reviewed... do not see the label anymore.
