### ISSUE TITLE
Update script for "completed" touchpoint tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96422]
## User Story
As PM of the Governance team, I want to ensure that the script for creating the "completed" touchpoint ticket is updated to remove Zenhub references so that the script doesn't become invalid if/when VA loses Zenhub access at the end of 2024.

As PM of the Governance team, I want to ensure that the script for creating the "completed" touchpoint ticket is updated for GitHub projects so that we no longer have to manually add the "completed" ticket to the correct parent issue, add points, add to the Sprint, and close.

Assignee: @it-harrison 
Peer Reviewer: ~~@briandeconinck~~  ~~@KKitagawa-Bosch~~ @briandeconinck 

## Description
Governance team has switched from ZenHub to GitHub projects. We currently have a script that creates "completed" tickets (signifying that a touchpoint has been completed) when we add the` cc-kickoff`, `design-intent`, `midpoint-review` or `staging-review` label to any `CC-Request` ticket. This current script utilizes the Zenhub api.

The purpose of this ticket is to modify the script so that it no longer relies on the Zenhub api, and instead alter it to create the new ticket for the [Governance Team GH projects board](https://github.com/orgs/department-of-veterans-affairs/projects/1491/views/1). The "completed" tickets should meet the following criteria:

- assign the appropriate Points value, per the Points field in the Governance Team gh projects board
   - kickoff - 1 pt
   - Design Intent - 5 pts
   - Midpoint Review - 5 pts
   - Staging Review - 8 pts
- assign the current sprint, per the Sprint field in the Governance Team gh projects board
- assign as a sub-issue of the Collaboration Cycle Support initiative
   - current initiative is for CY24-Q4, however new initiatives will be created for each upcoming quarter and will follow the same naming convention
- "completed" ticket is closed after it is created
- title of "completed" ticket should remain the same.
- "completed" ticket should continue to be added to the milestone associated with the CC-Request ticket

### Live pages
- [Guide to Automation to Create Completed Tickets for Collab Cycle Touchpoints](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2841280559/Guide+to+Automation+to+Create+Completed+Tickets+for+Collab+Cycle+Touchpoints)
- 
### Drafted pages
- 

## Tasks
- [ ] Update the script per the specifications listed above
- [ ] Update the guidance doc to reflect the GH Projects changes
- [ ] Test the updated script

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team has modified the script for creating the touchpoint "completed" tickets to align with the Governance Team GH projects board
- [x] Governance team has updated the team guidance for managing and maintaining the script

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@briandeconinck this is ready for review:
* [updated workflow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/create-cc-completed-ticket.yml)
* [updated script](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/scripts/github-actions/gov-team/create-cc-completed-ticket.js)

To test: 
1. add a touchpoint label (e.g. `staging-review`) to a Collab Cycle Request ticket
2. after the [action](https://github.com/department-of-veterans-affairs/va.gov-team/actions/workflows/create-cc-completed-ticket.yml?query=) completes, check that an entry for the completed ticket appears on the project board [Initiative View](https://github.com/orgs/department-of-veterans-affairs/projects/1491/views/5) under the **Governance Team Collaboration Cycle Customer Support: CY24-Q4** heading.

**Comment by shiragoodman** [comment]
reassigned peer reviewer to @KKitagawa-Bosch since @briandeconinck has been out sick and is still catching up with Collab cycle reviews

**Comment by briandeconinck** [comment]
Got traded back to me at 11/20 stand-up... and @it-harrison it looks good! Code seems clear, documentation makes sense, and test ticket with label worked exactly as expected (test CC ticket #97539, generated completed ticket #97543).

This is good to close!
