### ISSUE TITLE
Update Review Page Content

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96440]
## Issue Description
Carry over from #95020 

## Tasks
- [ ] Update the chapter title to be "Review" (currently says "Review application").
- [ ] Add H3 "Review the information for your form" above the accordions (currently there is no content) -- see [annotated designs](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2194-153450&t=aUyBK2z4DlpOqzdm-4).

## Acceptance Criteria
- [ ] The content updates above have been addressed
