### ISSUE TITLE
Update Content Build Deployment Schedule

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#96453]
## Pain Point
VFS Front End engineer commented in Q2 Survey: 
"_Documentation for content-build deployments (https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments) is incorrect and has not kept pace with the recent deploy time changes._"  
- this comment was made on  Q2 2024

## Relevant links:
[Platform All Feedback Repository](https://vfs.atlassian.net/wiki/spaces/RESEARCH/database/3120759313?contentId=3120759313&entryId=162dfca5-8c33-4632-b55c-7d7fb726fcec&savedViewId=be6f94ca-bd44-466c-b2f4-3a652314499f)

## Issue Description
Although Platform is moving away from content build and toward next build, we may need to publish the most current deployment info on both systems so engineers are able to successfully use whichever is appropriate.

---
## Tasks
- [x] Audit page for Content Build deployment info
- [x] Contact CMS team for deployment schedule - Tim Cosgrove & Grace Kretschmer Tran 

## Acceptance Criteria
- [x] page is updated or confirmed to be current
- [x] date stamp is added with today's date
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
December 4 is launch of Next Build, will Content Build deployments schedule continue to be relevant?

**Comment by jknipes** [comment]
[This issue may have already been addressed in this Slack thread from 5/28-6/5/24](https://dsva.slack.com/archives/CL181NRJQ/p1716929567423409)

**Comment by jknipes** [comment]
[Per this Slack thread](https://dsva.slack.com/archives/CL181NRJQ/p1732651566335619), the current `content-build` deployment schedule is confirmed to be correct on Platform Website. `content-build (content-only)` was updated today 11/26/24

**Comment by jknipes** [comment]
In the effort to secure a SME for this work, the issue was resolved. Therefore, we have pulled this ticket into the current sprint and closing as _complete_
