### ISSUE TITLE
Discovery: Should Developer Docs Move to Code VA?

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#96454]
## Pain Point

- VFS engineers need a single source-of-truth, but they are using Code VA, Design System, GitHub and Platform Website to locate information on the Build experience, which leads to duplication of information, longer building and testing times, and overall confusion.

## Issue Description
Platform Content team needs to gather a consensus of where developer documentation should live

---
## Tasks
- [x] Compose a question to include in the next Platform Satisfaction survey that asks "where should developer documentation live?" and offers the choices above.

## Acceptance Criteria
- [x] All tasks are completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
This question and similar questions will be added to [the upcoming Developer documentation survey and research project](https://vfs.atlassian.net/wiki/spaces/PR/pages/3336011777/Research+plan+Developer+documentation?atlOrigin=eyJpIjoiY2Q4ZTg5YWZhNmJiNGI4YTgxMzJjOTRhZmVlZmMxZjciLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ). 
Closing this Discovery ticket as _Done_.
