### ISSUE TITLE
[Discovery] Logged-in homepage: Team handoff and collaboration session

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#9646]
## Background

In Slack, Shawna suggested that Liz present final discovery results to our team and that we have a team collaboration session to sketch and discuss the path forward. This is a great idea, so we're going to move forward with this after the final readout is in a good place but before we share the readout with DEPO or the larger team.

## Tasks

- [x] Schedule session
- [ ] Plan session (including any technical constraints for sketching/sharing)
- [ ] Confirm any materials/supplies team members will need
- [ ] Conduct session

## Acceptance criteria

- [ ] Team handoff/collab session has been completed

**Comment by Samara-Strauss** [comment]
@mshea0606 will schedule the session for some time on Thursday, 6/11

**Comment by andaleliz** [comment]
@Samara-Strauss, wanted to share more thoughts on the team brainstorm/sketching session now that I saw more details on your portion of the summary doc.  You've done a great job phasing it out already, so I'm re-considering having that be the focus of the exercise.  

I think I could share the findings, **and** give a brief overview of the phases you outlined.  Then, have the sketching/ideation session focus on phase 1.  I think that could generate interesting ideas for how the page would visually come together, and also shed light on what people think is reasonable to include in phase 1.

Obv need to work out more details, but generally, how does that sound?

**Comment by Samara-Strauss** [comment]
That sounds good re: also giving a brief overview of the phases I outlined, but I think we should still go with your original plan to have a team discussion right after presenting the findings, and then talk about the plan I outlined. What do you think of this?:

- Presentation of findings
- Discussion:
  - Thoughts on findings
  - Concerns the team has moving forward
  - What each person thinks could be an MVP (this could still be a sketching session)
- THEN, we could share the initial plan and see if people have feedback on that

My instincts are that if we present my plan first and then ask for feedback, we might miss concerns that people would have raised if they weren't already primed with a plan, and/or people may feel they can't disagree or question a plan if I've already put it together. 

Thoughts on this?

**Comment by andaleliz** [comment]
Ah yes, that's a good point.  Sounds good to me!

**Comment by andaleliz** [comment]
Held session 6/11/20. 

[Mural board used for session](https://app.mural.co/t/vsa8243/m/vsa8243/1591380270057/c9d329b413d7113abeb79dc9c9d24ef20defcdcb)

[Presentation deck shared with team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/logged-in-homepage-findings-deck-for-team.pptx)
