### ISSUE TITLE
Supply Reordering: ChooseSupplies - Select supplies to reorder

### ISSUE THREAD

**Issue by JasmineYohannan** [department-of-veterans-affairs/va.gov-team#96476]
## User Story

```
As a Veteran visiting the Supply Reorder app,
I want to select the supplies I want to reorder,
So that I can complete my order and receive the medical supplies that I require.
```

## Acceptance Criteria

- [x] UI for selecting supplies
- [x] Selected supplies are indicated in `formData` (or relevant redux state)
- [ ] When revisiting page from a saved form, previously selected supplies are checked

## Tasks
 
- [ ] ~utilize the checkbox vads web component with `tile` attribute for displaying available supplies~
- [ ] ~utilize `replaceSchema` and `updateUiSchema` to build a dynamic list of checkboxes (one per supply) in the form.~ [See #97690]
- [ ] utilize the web-component checkbox, with the addition of a custom component in order to render UI as designed. -- via Adam W.

## QA Steps/Instructions

TBD

**Comment by radavis** [comment]
Relevant support requests:
- [Multi-line checkbox description with `VaCheckbox`](https://dsva.slack.com/archives/CBU0KDSB1/p1732033256828029)
- [VA Forms: display a dynamic list of checkboxes in a form via `checkboxGroup`/`checkboxGroupUI`](https://dsva.slack.com/archives/CBU0KDSB1/p1732302583145889)
