### ISSUE TITLE
Create Received email feature toggle

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#96485]
## Issue Description
As an engineer I want to control the availability of the new Received email so that Veterans do not experience a degraded or otherwise non-functional submission experience. A received email exists today, so it’s important that we are able to maintain this important Veteran touchpoint.

We plan to use a feature flag/toggle to gate this functionality. It will help us to test emails in staging, and should we decide to use the toggle to release this feature in Production, it will be readily available.

## Tasks
- [x] Determine the feature toggle name
- [x] Create the toggle using ~[Platform best practices](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide)~ as a guide
- [x] Set up feature flag in features.yaml
- [x] Add feature toggle to PollForm526Pdf perform method success
- [x] Add logging stating when & where the email is being called
- [x] Wrap sending email call in 'workflow complete handler' (line 347)
  - [x] add logging stating when & where the email is being called
- [x] add new unit tests to PollForm526Pdf that check Form526ConfirmationEmailJob usage
- [x] update unit tests that involve Form526ConfirmationEmailJob

## Acceptance Criteria
- [x] The feature toggle has a name that follows our established naming conventions
- [x] The feature toggle exists for both staging and production
- [x] Ensure the toggle is available in Flipper Admin
- [x] Toggle can be retrieved and utilized
- [x] Unit tests are updated or added net new as needed to ensure functionality
- [x] The 526 application uses the va-notify template ID to send the new Received email 
- [x] Email can be sent when the 526 polling job is sucessful for a given Veteran’s submission
- [x] The email job is monitored such that we will know if it’s not working

**Comment by mchae-nava** [comment]
Effective start 11/13 evening due to being OOO, apologies for the delay
