### ISSUE TITLE
Establish Ground Rules for VEO Engagement 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#96489]
## Issue Description
As a Contact Center Manager, I want to establish clear ground rules for engagement, so that contact center agents can communicate effectively, escalate issues properly, and report errors consistently, improving the overall efficiency and experience of both agents and customers.

---
## Tasks
- [x] Establish guidelines on when and how to post issues to Teams channel
- [x] Establish guidelines on how to escalate issues to Teams channel 
- [x] Document guidelines on posting and escalating issues to Teams channel

## Acceptance Criteria
- [x] Provide training materials for Teams channel engagement
- [x] Publish guidelines for engagement and participation in Teams channel
- [x] Established feedback loop for effectiveness of teams channel  

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Further discuss will commence at the monthly VEO synch meeting 11/20/24.

**Comment by UXCamG** [comment]
DRAFT: [Tier 2 and Tier 3 Ground Rules](https://docs.google.com/document/d/1EHzt_zkM0T1PCx87J8s2vFwEvsXnkHZiyoLACpHzqcs/edit?usp=sharing)

**Comment by ATMiddleton** [comment]
@Kimberley2023-CSM will engage Dale Carr (VEO) on the VA.gov side of the network.

**Comment by Kimberley2023-CSM** [comment]
Below is the correspondence from Dale Carr (VEO lead) which includes his recommendations for the shared channel rules of engagement.

We are very open to what the business model could look like. Here are some general thoughts.

- No Tier 1 agents in the channel.

- Tier 1 Supervisors & Managers with very specific (spelled out) use guidelines, also include designated members of the VEOCC Operations team so they have awareness, including members of Work Force Management (so they understand call spikes and can adjust forecasting), Knowledge Management Team (in case they need to update or create KM’s), and the Quality Team (so they are aware if any parts of the Quality program needs to be adjusted.

- Closed cases with confusing Case Resolution Descriptions

- Open case inquiry “x” days past SLA (such as 90 days)—would only want “extreme” situations allowed

- Notification of call spike reasons

- We have received an unusual increase in calls regarding Code “XXX” which is not listed in our KMS. It is occurring when Veterans attempt to do <insert [va.gov](http://va.gov/) process>
- 
- We have received a spike in calls due to <insert [va.gov](http://va.gov/) issue> and we do not have a KM on how to address this issue
- 
- We have received an increase in calls, and based on the issues we suspect that [va.gov](http://va.gov/) is down, can you confirm?
- ETA to restore service?

- Would also love to have Tier 2 communicate new or known issues—expected maintenance windows, unexpected offline times, scheduled changes to the site, and etcetera.
- What other type of Tier 2 communications to Tier 1 do you think would be helpful?

 

Hopefully, this provides a starting place for structure, and I think this is like the list I rattled off during the meeting last week.

 

Regards,

 

Dale Carr 

Supervisor Lead

VEO Contact Center

The Bowen Group - A GTSC Company

**Comment by ATMiddleton** [comment]
Will present to VEO 1/16/25 - @Kimberley2023-CSM will forward to VEO for review. 

@Kimberley2023-CSM @UXCamG @ATMiddleton  will review week of 1/13 and present to @starlow00  for review and input

**Comment by ATMiddleton** [comment]
Upon review @starlow00 will publish to Veteran Support SharePoint. 

Veteran Support meeting with VEO 1/16/24

**Comment by ATMiddleton** [comment]
[Shared Ground RUles ](https://docs.google.com/document/d/1FmJTXWMhTQ1ubXL-Wijoh-tZG0HuNspqhvcJgCF16-o/edit?tab=t.0)

Working document to be presented to VEO for feedback.

**Comment by ATMiddleton** [comment]
VEO stated that only VEO Supervisors will have access to the Teams channel for notifications of recurring issues and increases in calls, outages, specific case resolution description, and discussions regarding cases greater than 90 days.

VEO and Veteran Support agree on stated ground rules - Open and continual communication through the Teams channel.
