### ISSUE TITLE
Update Received email va-notify template in Staging

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#96487]
## Issue Description
As a Veteran I want to get an email from VA when my application has been received by VA that matches the same format I’m used to with other parts of VA.gov and I expect plain language to be used to describe information I find useful. This helps me feel more confident in VA’s effort to submit my application, and in my ability to understand the status of my claim.

## Tasks
- [ ] update template in staging va-notify
- [ ] test

## Additional Information
[Figma file](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/(526ez)-New-Confirmation-Page-and-Email-Touchpoints?node-id=8412-192677&t=TbnvKFJa56KbOHg9-4). Look at "New email touchpoints" we're looking at the "Happy path (new) email Received"
![Image](https://github.com/user-attachments/assets/2bb5c103-f05f-42aa-b6e5-864a19047760)

Carbs wrote some [helpful documentation](https://docs.google.com/document/d/11ese_oZD32Xt3SjE4RUErhx6zdXb99oI7SBPSymR-Wc/edit?tab=t.0#heading=h.sya20hwrz5c4) on va-notify procedures.
Not applicable to this user story directly, but [slack thread](https://dsva.slack.com/archives/C010R6AUPHT/p1728594463215329) on conditionally displaying info in va-notify templates.

There's a button that in their Staging environment that lets you push to prod

https://staging.notifications.va.gov/ 
*Note:* this link only works behind VA firewall

This will go through Staging Review in Dec, this ticket is to prepare for that

## Acceptance Criteria
- [ ] The existing va-notify template is updated with our new content from the Figma file
- [ ] The information in the Submission Details box contains accurate information pertaining to the Veteran's submission
- [ ] The existing va-notify template is updated in Staging

**Comment by mchae-nava** [comment]
https://staging.notifications.va.gov/
Need GFE or CAG to access

**Comment by sethdarragile6** [comment]
note: update in figma
![Image](https://github.com/user-attachments/assets/f416c534-1b49-40b5-bba1-bec8dbc66d18)

**Comment by aurora-a-k-a-lightning** [comment]
@sethdarragile6 we need to add `((received_date))` to the email parameters from vets-api to send to va-notify:
app/models/form526_submission.rb:365
add to the outputted hash

**Comment by sethdarragile6** [comment]
Successfully tested in Staging with User 99 (Randall)! Screenshot below.
![Image](https://github.com/user-attachments/assets/5bd5301d-2ca5-4b11-b232-3d89e58d63bc)
