### ISSUE TITLE
[PM, Eng] 10-10EZ - Notifications: Update the Submission Failure email template in VA Notify

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#96500]
## Benefit to the Veteran
As a Veteran, I want to have clear messaging when my 10-10EZ application submission fails, so that I know what steps to take for a successful submission

## Scope
Now that the Submission failure email content has been reviewed with CAIA and our Privacy Officer, we can move forward with updating the template, testing, and launching to production

### References
- #93766 UX ticket working with CAIA on template
- #96499 Privacy Officer ticket
- [Figma Design](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=7252-304&node-type=instance&t=p7KsvNz8bo3MmovM-0)

## Tasks
- [x] Update the VA Notify staging template for Submission failure emails
- [x] Complete a test (engineering assist)
- [x] Once testing has been documented in this ticket, update the VA Notify production template

## Acceptance Criteria
- The EZ Submission failure email content has been updated in Production

**Comment by coope93** [comment]
I updated the template in staging per the Figma designs above. @allanto-ah Did you want to pair on testing this sometime?

**Comment by hdjustice** [comment]
Template looks good!  
Note: URL directing users back to the 10-10EZ was updated to the new Root URL, still retaining the source and campaign for data tracking

**Comment by coope93** [comment]
@allanto-ah I added [this testing documentation](https://github.com/department-of-veterans-affairs/va.gov-team/pull/97754) that should be helpful in testing this. I'll wait to confirm it works as expected before merging the documentation in, so feel free to use that to test this in staging when you get the chance.

**Comment by coope93** [comment]
@hdjustice Successful test in staging for the new design. We just need to update the template in production through the VANotify UI whenever we want to turn this on in production.

**Comment by hdjustice** [comment]
Template has been pushed to production - test email sent successfully with new content
![Image](https://github.com/user-attachments/assets/56e5b619-aad6-499d-b919-26e50bb3ad99)
