### ISSUE TITLE
[PM, Eng] 10-10EZ - Notifications: Update the In-Progress email template in VA Notify

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#96501]
## Benefit to the Veteran
As a Veteran, I want to have clear messaging when my 10-10EZ application is In-Progress, so that I know what steps to take for a successful submission

## Scope
Now that the In-Progress email content has been reviewed with CAIA and our Privacy Officer, we can move forward with updating the template, testing, and launching to production

### References
- #93766 UX ticket working with CAIA on template
- #96499 Privacy Officer ticket
- [Figma Design](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=7252-304&node-type=instance&t=p7KsvNz8bo3MmovM-0)

## Tasks
- [x] Update the VA Notify staging template for In-Progress emails
- [x] Complete a test (engineering assist)
- [x] Once testing has been documented in this ticket, update the VA Notify production template

## Acceptance Criteria
- The EZ In-Progress email content has been updated in Production

**Comment by coope93** [comment]
@hdjustice This is ready to be moved to production whenever we want. We just need to push it to prod in the VANotify UI.

**Comment by hdjustice** [comment]
Pending Privacy Officer review (see #95357)

**Comment by hdjustice** [comment]
Received response from Kamilah Jackson that there are no privacy concerns
Additional follow-up steps may be taken for Ethics review, however for now we will move forward with pushing email to prod

![Image](https://github.com/user-attachments/assets/f3b48d7b-0f8e-4730-9931-73bf199a6201)

**Comment by coope93** [comment]
This was email template was pushed from Staging to Production today.
