### ISSUE TITLE
Design intent Collaboration [Service level operating status]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9650]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [X] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [X] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [X] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [X] VSP <> **requesting team** design intent collaboration meeting completed
- [ ] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- [Feature brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/product/facility-level-alerts/service-level-feature-brief.md)
- [Draft design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/images/draft%20service%20status%20on%20facility%20detail%20page.png)
- [Link to similar design component](https://www.va.gov/housing-assistance/)
- [Link to component within design system](https://design.va.gov/components/additional-info) 

## Meeting attendees from **requesting team**
- Designer(s)/DEPO design lead (required): **Ryan Thurlwell**
- Product Manager (optional): **Michelle Middaugh**

## Scheduling
- Requesting Tuesday, June 2 at 11 ET

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by CrystabelReiter** [comment]
Scheduled for June 2, 11am ET

**Comment by rtwell** [comment]
We decided to remove the icons—there are too many, they would have to be much larger to be helpful, and it makes the **Operating status** column more prominent than the **Services** column. Users should first look for a service they care about, and then the status of that service, not the other way around.

## Default view

![image](https://user-images.githubusercontent.com/12564977/83409797-26ad0b80-a3e3-11ea-8c97-0c473221bbfd.png)

## Status expanded view

![image](https://user-images.githubusercontent.com/12564977/83409810-2f9ddd00-a3e3-11ea-9ced-13d8ee034dbb.png)

# Mobile view

![image](https://user-images.githubusercontent.com/12564977/83409822-36c4eb00-a3e3-11ea-9d32-f423988e241b.png)

**Comment by CrystabelReiter** [comment]
VSP design approves the uses of the additional info component in these designs. No need for a feedback ticket, our only thing to note is that for next steps to talk to a content person about the additional info component label. Thanks for giving us context and for the discussion!

**Comment by rtwell** [comment]
## updated comps
I deleted the table headers and inserted a descriptive sentence in its place. 

### desktop - default

![image](https://user-images.githubusercontent.com/12564977/83682903-8c032700-a5b2-11ea-8691-703af06bbac8.png)

### desktop - expanded

![image](https://user-images.githubusercontent.com/12564977/83682911-8f96ae00-a5b2-11ea-995f-8dbe443177d3.png)

### Mobile

![image](https://user-images.githubusercontent.com/12564977/83682924-92919e80-a5b2-11ea-9e12-ef951b7620a2.png)
