### ISSUE TITLE
Generate report of errored forms

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#96515]
## Description

We need to know the numbers for errors since 9/14/23.

Namely, we need to know what system the errors are coming from and which ones are recoverable.

We _think_ sharepoint is not needing recovery.

Mural Denise and I worked on:
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1730829862059/77160a5d1fb6a49e9a7f40dc846f2fd2b92b097f

## Tasks
- [x] Report submitted to Denise

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [x] Report has error information and submitted to Denise

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by denisecoveyduc** [comment]
Appreciate all the work on this @digitaldrk thank you!!!
