### ISSUE TITLE
Create new Domo dataset to replace 'BQ - All MyVA Users, Pageviews and Events 2' without api_calls.

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#96521]
### Description
This ticket is to replace this dataset in Domo, ([BQ - All MyVA Users, Pageviews and Events 2](https://va-gov.domo.com/datasources/bdc0655a-8fbd-41a5-8919-9b79d9fc780b/details/data/table). It currently contains 1.2B rows, but most of the data isn't being used.

Instead of trying to remove the unneeded data, and add a filter, be easier to create a new dataset, and point the cards to the new one.

**[Domo Dataset Settings](https://va-gov.domo.com/datasources/bdc0655a-8fbd-41a5-8919-9b79d9fc780b/details/settings)**

---

### Tasks

- [x] Create a new dataset in Domo with the same logic as [BQ - All MyVA Users, Pageviews and Events 2](https://va-gov.domo.com/datasources/bdc0655a-8fbd-41a5-8919-9b79d9fc780b/details/data/table), but be sure to exclude data where event_label = api_call
- [x] Confirm it its populating correctly.
- [x] QA -- create duplicates of the existing cards, and test them on the newly created dataset, to ensure they are still functional
- [ ] Change existing cards that used old dataset to the new one.
- [ ] Delete the old, original dataset, BQ - All MyVA Users, Pageviews and Events 2

### Acceptance Criteria

- [x] New dataset is created.
- [ ] Domo cards are functional, and tied to new dataset.
- [ ] Old dataset is deleted.

**Comment by johnny-jesensky-adhoc** [comment]
@Blivaditis -- Moving this one to Done. Can you create a new card for the card transfer that will be needed on this?
