### ISSUE TITLE
Prioritize questions from research findings

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96523]
## User Story
As a Governance team member attempting to understand the necessary changes for bringing mobile app into Collab Cycle, I want to prioritize my questions so that I am getting answers to the most important and critical questions first.

Assignee: @erinrwhite @briandeconinck 
Peer Reviewer: @KKitagawa-Bosch 

## Description
Governance team completed 2 research sessions for mobile app discovery, including a Cognitive Walkthrough and a Diary Study. Both research sessions were very successful, and we ended up with 2 extremely long lists of follow-up questions we have for our OCTO-DE practice area leads, the Mobile App team and potentially others.

We assume that it will take a significant amount of time and energy to get all of our questions answered, so instead Governance will come up with a scale for setting priority of each question. In a later sprint when we do reach out to OCTO and mobile app teams for answers to our questions, we can ask our critical questions first, and less priority questions last.

This ticket will include determining a scale for priority (example: critical - must be answered or we cannot continue, low - learning this would be helpful, but we should be able to continue without the information, and then maybe a middle/medium priority item), and then applying that scale to all questions in both research findings docs. 

### Live pages
- 

### Drafted pages
- 

## Tasks
- [x] Review [cognitive walkthrough findings](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3547627548/Research+findings+Cognitive+walkthrough+-+mobile+app+in+the+Collab+Cycle)
- [x] Review [diary study synthesis](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3586457602/Synthesis+Workspace)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have determined a priority scale for classifying each  question we have.
- [x] We have applied the priority scale to all questions from the research findings

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@erinrwhite @briandeconinck - I spoke to Matt on Friday and gave him the status of this initiative. He shared with me that he'd really like us to follow up with Rachel Han from OCTO-DE, who is now part of Platform but supported the Mobile App team for a while, and get her perspective. It's something we will need a rush a bit bc Rachel is planning to go on maternity leave starting 11/18, so Matt would like us to get her input before then.

Let me know if the 2 of you would like to discuss this with me in more detail. I think we can try and keep in casual/informal. Let's chat at standup.

**Comment by erinrwhite** [comment]
Reached out to Rachel to schedule a meeting tomorrow; started on [prioritized questions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3632398343/Prioritized+questions)

**Comment by erinrwhite** [comment]
1. Drafted rough scale for coding questions  (Could be better but it's a start!)

>   1=critical
>   2=important
>   3=can wait

2. created a [database of questions](https://vfs.atlassian.net/wiki/spaces/PPST/database/3632365611)

3. Created a list of priority-1 questions for OCTO Mobile lead, refined, categorized, and shared with team for feedback:

- Roadmap for mobile app and [VA.gov](http://va.gov/)
  - Future of the mobile app team
  - How should we collaborate with the mobile app team for Collab Cycle reviews, even if only initially?
  - What will be the development process for non-mobile app teams building for the mobile app?
  - Should we expect to see teams building app and web in parallel? Is there a preference for which is first?
  - Are there things we should consider for teams who are iterating on something the mobile app team built, rather than building an entirely new feature?
- Philosophical considerations:
  - What's a launch blocker for the mobile app?
  - How do we maintain Zero Silent Failures with the app? What's the philosophy on notifications?
  - Do we have an idea of what is "too big" for mobile app? Is anything too big or should the mobile app support anything that the web supports?
- What are the plans for mobile app updates to the Design System? Additional guidelines for teams building for mobile app - Android and iOS?
- Is the VA 508 office going to review the mobile app?

**Comment by erinrwhite** [comment]
Held meeting with Rachel Han on Thursday 11/14

[Rough notes from meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3635871759/Conversation+with+OCTO+Mobile+App+lead)
[Recording of meeting](https://drive.google.com/file/d/15_MWtmrSQEBMJNtkidw_RTl6hC1LR1xS/view?usp=drive_link)

Next steps: review notes and re-prioritize + add new questions.

**Comment by erinrwhite** [comment]
@shiragoodman @KKitagawa-Bosch I think these are ready for review. I [drafted the questions into a database](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3632398343/Prioritized+questions) and prioritized them based on this scale:

1. **Critical:** impacting strategic planning. Should be prioritized first.
2. **Important:** impacting tactical planning.
3. **Can wait:** more granular and/or practice-are specific and not impacting strategic planning.

**Comment by shiragoodman** [comment]
@erinrwhite I agree with Keegan. The organization is extremely helpful. I like that you've acknowledged that some of our questions are for both OCTO and the mobile app team. from my perspective, we've definitely met the acceptance criteria and now have a template for moving forward. thank you for the great work!

**Comment by erinrwhite** [comment]
Thanks both!! @KKitagawa-Bosch can you do a final spin and check the AC and peer review boxes when you're ready? Then I'll close.

**Comment by KKitagawa-Bosch** [comment]
Good to go @erinrwhite !

**Comment by erinrwhite** [comment]
thanks @KKitagawa-Bosch ! Closing...
