### ISSUE TITLE
Transition vets-api settings to the new vars (128 variables)

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#96548]
**Blocked by:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/97393

128 of the 470 SSM sourced variables in vets-api are set in all 4 static environments, and we can now transition the vets-api code to utilize these new values. The list of values is below.

## Tasks
- [x] Change vets-api code to use the new settings names
- [ ] Deploy to all environment - confirm working
- [ ] remove the setting of these values from the dev, staging, prod and sandbox manifest repositories

## Acceptance Criteria
- [x] vets-api is using the new settings variable names
- [ ] old now unused variable names are removed

New env var names:
	- SETTINGS__ARGOCD__SLACK__API_KEY
	- SETTINGS__BGS__URL
	- SETTINGS__BRD__API_KEY
	- SETTINGS__BRD__BASE_NAME
	- SETTINGS__CASEFLOW__APP_TOKEN
	- SETTINGS__CASEFLOW__HOST
	- SETTINGS__CENTRAL_MAIL__UPLOAD__HOST
	- SETTINGS__CENTRAL_MAIL__UPLOAD__TOKEN
	- SETTINGS__CHECK_IN__CHIP_API_V2__TMP_API_ID
	- SETTINGS__CHECK_IN__CHIP_API_V2__TMP_API_USER
	- SETTINGS__CHECK_IN__CHIP_API_V2__TMP_API_USERNAME
	- SETTINGS__CHECK_IN__CHIP_API_V2__URL
	- SETTINGS__CHECK_IN__LOROTA_V2__KEY_PATH
	- SETTINGS__CHECK_IN__LOROTA_V2__URL
	- SETTINGS__CLAIMS_API__BENEFITS_DOCUMENTS__AUTH__CCG__AUD_CLAIM_URL
	- SETTINGS__CLAIMS_API__BENEFITS_DOCUMENTS__AUTH__CCG__CLIENT_ID
	- SETTINGS__CLAIMS_API__BENEFITS_DOCUMENTS__AUTH__CCG__SECRET_KEY
	- SETTINGS__CLAIMS_API__BENEFITS_DOCUMENTS__HOST
	- SETTINGS__CLAIMS_API__EVSS_CONTAINER__CLIENT_KEY
	- SETTINGS__CLAIMS_API__PDF_GENERATOR_526__URL
	- SETTINGS__CLAIMS_API__TOKEN_VALIDATION__API_KEY
	- SETTINGS__CLAIMS_API__TOKEN_VALIDATION__URL
	- SETTINGS__CLAIMS_API__USER_INFO__URL
	- SETTINGS__CONNECTED_APPS_API__CONNECTED_APPS__API_KEY
	- SETTINGS__CONNECTED_APPS_API__CONNECTED_APPS__REVOKE_URL
	- SETTINGS__CONNECTED_APPS_API__CONNECTED_APPS__URL
	- SETTINGS__COVERBAND__GITHUB_OAUTH_KEY
	- SETTINGS__COVERBAND__GITHUB_OAUTH_SECRET
	- SETTINGS__DATABASE_URL
	- SETTINGS__DECISION_REVIEW__API_KEY
	- SETTINGS__DECISION_REVIEW__PDF_VALIDATION__URL
	- SETTINGS__DECISION_REVIEW__V1__URL
	- SETTINGS__DHP__FITBIT__CLIENT_ID
	- SETTINGS__DHP__FITBIT__CLIENT_SECRET
	- SETTINGS__DHP__FITBIT__CODE_CHALLENGE
	- SETTINGS__DHP__FITBIT__CODE_VERIFIER
	- SETTINGS__DHP__FITBIT__REDIRECT_URI
	- SETTINGS__DHP__FITBIT__SCOPE
	- SETTINGS__DHP__S3__AWS_ACCESS_KEY_ID
	- SETTINGS__DHP__S3__AWS_SECRET_ACCESS_KEY
	- SETTINGS__DHP__S3__BUCKET
	- SETTINGS__DIRECTORY__KEY
	- SETTINGS__DIRECTORY__URL
	- SETTINGS__EVSS__CERT_PATH
	- SETTINGS__EVSS__DVP__URL
	- SETTINGS__EVSS__KEY_PATH
	- SETTINGS__EVSS__LETTERS__URL
	- SETTINGS__EVSS__S3__AWS_ACCESS_KEY_ID
	- SETTINGS__EVSS__S3__AWS_SECRET_ACCESS_KEY
	- SETTINGS__EVSS__S3__BUCKET
	- SETTINGS__EVSS__URL
	- SETTINGS__FLIPPER__GITHUB_OAUTH_KEY
	- SETTINGS__FLIPPER__GITHUB_OAUTH_SECRET
	- SETTINGS__FLIPPER__GITHUB_TEAM
	- SETTINGS__FORM526_BACKUP__API_KEY
	- SETTINGS__FORM526_BACKUP__AWS__ACCESS_KEY_ID
	- SETTINGS__FORM526_BACKUP__AWS__BUCKET
	- SETTINGS__FORM526_BACKUP__AWS__REGION
	- SETTINGS__FORM526_BACKUP__AWS__SECRET_ACCESS_KEY
	- SETTINGS__FORM526_BACKUP__URL
	- SETTINGS__FORM_10_10CG__POA__S3__AWS_ACCESS_KEY_ID
	- SETTINGS__FORM_10_10CG__POA__S3__AWS_SECRET_ACCESS_KEY
	- SETTINGS__FORM_10_10CG__POA__S3__BUCKET
	- SETTINGS__GITHUB_CVU__INSTALLATION_ID
	- SETTINGS__GITHUB_CVU__INTEGRATION_ID
	- SETTINGS__GITHUB_CVU__PRIVATE_PEM
	- SETTINGS__GOOGLE_ANALYTICS_CVU__AUTH_PROVIDER_X509_CERT_URL
	- SETTINGS__GOOGLE_ANALYTICS_CVU__AUTH_URI
	- SETTINGS__GOOGLE_ANALYTICS_CVU__CLIENT_ID
	- SETTINGS__GOOGLE_ANALYTICS_CVU__CLIENT_X509_CERT_URL
	- SETTINGS__GOOGLE_ANALYTICS_CVU__PRIVATE_KEY
	- SETTINGS__GOOGLE_ANALYTICS_CVU__PRIVATE_KEY_ID
	- SETTINGS__GOOGLE_ANALYTICS_CVU__TOKEN_URI
	- SETTINGS__GOOGLE_ANALYTICS__URL
	- SETTINGS__HOSTNAME
	- SETTINGS__LIGHTHOUSE__API_KEY
	- SETTINGS__LIGHTHOUSE__BENEFITS_INTAKE__API_KEY
	- SETTINGS__LIGHTHOUSE__BENEFITS_INTAKE__HOST
	- SETTINGS__LIGHTHOUSE__FACILITIES__API_KEY
	- SETTINGS__LIGHTHOUSE__FACILITIES__URL
	- SETTINGS__LIGHTHOUSE__VETERAN_VERIFICATION__AUD_CLAIM_URL
	- SETTINGS__LIGHTHOUSE__VETERAN_VERIFICATION__FORM526__ACCESS_TOKEN__CLIENT_ID
	- SETTINGS__LIGHTHOUSE__VETERAN_VERIFICATION__FORM526__ACCESS_TOKEN__RSA_KEY
	- SETTINGS__LIGHTHOUSE__VETERAN_VERIFICATION__FORM526__AUD_CLAIM_URL
	- SETTINGS__LIGHTHOUSE__VETERAN_VERIFICATION__FORM526__HOST
	- SETTINGS__LIGHTHOUSE__VETERAN_VERIFICATION__HOST
	- SETTINGS__LOCATORS__VHA
	- SETTINGS__LOCKBOX__MASTER_KEY
	- SETTINGS__MAINTENANCE__PAGERDUTY_API_URL
	- SETTINGS__MODULES_APPEALS_API__SLACK__API_KEY
	- SETTINGS__MVI__CLIENT_CERT_PATH
	- SETTINGS__MVI__URL
	- SETTINGS__OIDC__ISOLATED_AUDIENCE__CLAIMS
	- SETTINGS__OLD_SECRET_KEY_BASE
	- SETTINGS__PPMS__URL
	- SETTINGS__REDIS__APP_DATA__URL
	- SETTINGS__REDIS__HOST
	- SETTINGS__REDIS__RAILS_CACHE__URL
	- SETTINGS__REDIS__SIDEKIQ__URL
	- SETTINGS__SECRET_KEY_BASE
	- SETTINGS__SENTRY__DSN
	- SETTINGS__SIDEKIQ__GITHUB_OAUTH_KEY
	- SETTINGS__SIDEKIQ__GITHUB_OAUTH_SECRET
	- SETTINGS__TEST_DATABASE_URL
	- SETTINGS__TOKEN_VALIDATION__URL
	- SETTINGS__VA_FORMS__DRUPAL_PASSWORD
	- SETTINGS__VA_FORMS__DRUPAL_URL
	- SETTINGS__VA_FORMS__DRUPAL_USERNAME
	- SETTINGS__VA_FORMS__SLACK__API_KEY
	- SETTINGS__VA_PROFILE__ADDRESS_VALIDATION__API_KEY
	- SETTINGS__VA_PROFILE__ADDRESS_VALIDATION__HOSTNAME
	- SETTINGS__VA_PROFILE__URL
	- SETTINGS__VBA_DOCUMENTS__LOCATION__PREFIX
	- SETTINGS__VBA_DOCUMENTS__LOCATION__REPLACEMENT
	- SETTINGS__VBA_DOCUMENTS__S3__AWS_ACCESS_KEY_ID
	- SETTINGS__VBA_DOCUMENTS__S3__AWS_SECRET_ACCESS_KEY
	- SETTINGS__VBA_DOCUMENTS__S3__BUCKET
	- SETTINGS__VBA_DOCUMENTS__S3__REGION
	- SETTINGS__VBA_DOCUMENTS__SLACK__API_KEY
	- SETTINGS__VBA_DOCUMENTS__SLACK__DEFAULT_ALERT_EMAIL
	- SETTINGS__VBA_DOCUMENTS__SNS__REGION
	- SETTINGS__VBMS__CLIENT_KEYFILE
	- SETTINGS__VBMS__URL
	- SETTINGS__VIRTUAL_HOSTS
	- SETTINGS__VIRTUAL_REGIONAL_OFFICE__API_KEY
	- SETTINGS__VIRTUAL_REGIONAL_OFFICE__URL
	- SETTINGS__VSP_ENVIRONMENT
	- SETTINGS__XLSX_FILE_FETCHER__GITHUB_ACCESS_TOKEN

**Comment by stevenjcumming** [comment]
- SETTINGS__EVSS__LETTERS__URL
- SETTINGS__EVSS__S3__AWS_ACCESS_KEY_ID
- SETTINGS__EVSS__S3__AWS_SECRET_ACCESS_KEY
- SETTINGS__EVSS__S3__BUCKET
- SETTINGS__EVSS__URL

should be SETTINGS__CLAIMS_API__...

 - SETTINGS__MODULES_APPEALS_API__SLACK__API_KEY

should be SETTINGS__APPEALS_API__...

- SETTINGS__MVI__URL

should be SETTINGS__MOCKED_AUTHENTICATION__....

- SETTINGS__PPMS__URL

should be SETTINGS__FACILITIES_API__...

- SETTINGS__XLSX_FILE_FETCHER__GITHUB_ACCESS_TOKEN

should be SETTINGS__VETERAN__...

**Comment by stevenjcumming** [comment]
Moved to: https://github.com/department-of-veterans-affairs/va.gov-team/issues/97716
