### ISSUE TITLE
Analytics Tools: Quarterly Access Reviews [Q4 2024] - BigQuery

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#96549]
### Description
OCTO-DE teams are responsible for periodically reviewing access to systems and applications they manage to ensure that only authorized personnel have the required access and permissions.

Remove any users that should no longer have access to the systems or applications. Results must include a list of user access that was changed and why. Note -- we have guidance to deactivate users who have not been active in more than 1 year.

- [Access Review Process](https://www.google.com/url?q=https%3A%2F%2Fvfs.atlassian.net%2Fwiki%2Fspaces%2FPSEC%2Fpages%2F2987917734%2FAccess%2BReview%2BProcess&sa=D&ust=1718564280000000&usg=AOvVaw3Q0NQzPxL-XWPBZEqBEpAU)

- [Q4 Access Review Schedule](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3558637579/Access+Review+Rollout+Plan+-+Iteration+2)

---
### Tasks

- [x] Remove any users that should no longer have access to the systems or applications. Results must include a list of user access that was changed and why. Note -- we have guidance to deactivate users who have not been active in more than 1 year.

- [x] Document the results of the review using the below template. 

- [BigQuery Security Access](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3213885514/ACCESS+REVIEW+-+BigQuery)

### Acceptance Criteria

- [x] Necessary information on the access review template is filled out.

**Comment by johnny-jesensky-adhoc** [comment]
In the final phases of this -- expecting to have this completed in the next couple of days.

FYI @dorseypa1, @jwoodman5
