### ISSUE TITLE
[FSR] Bug - Employment work dates

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#96544]
## Issue Description
There have been some reported issues from [October Medallia survey](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/research/medallia_reports/Medallia-October-2024.md) stating that the work history dates will not let the veteran proceed.

URL: `manage-va-debt/request-debt-help-form-5655/employment-work-dates`

### Responses:
> Glitch in application process while filling out online VA Form 5655. Won't accept last job start date of January 2022 and end date of November 2023.

> I am trying to enter a start date for the day I started my job. It keeps saying "Please enter a valid start date"

## Tasks
- [ ] Attempt to recreate bug
- [ ] Identify issue
- [ ] Apply fix

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Bug relating to date issue has been addressed / fixed

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by Dr-Pongo** [comment]
DUplicate: 
https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/96545
