### ISSUE TITLE
Continued Support to Mobile Team for Flagship Looker Report

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#96552]
### Description
This task is to continue working with Victor and the Mobile Team to implement some of the job changes to their Looker report. This will likely involve working to implement the partioned reporting tables that were created by Phil in this ticket.

- [Prep Reporting Table for Mobile Team & Date Suffix Query Changes](https://github.com/orgs/department-of-veterans-affairs/projects/1168/views/1?sliceBy%5BcolumnId%5D=127719658&groupedBy%5BcolumnId%5D=127719658&pane=issue&itemId=82652664&issue=department-of-veterans-affairs%7Cva.gov-team%7C94570)
---

### Tasks

- [x] Continue to be on stand-by support to help Victor with recommended changes.
- [ ]  Confirm once all changes have been implemented in the report.

### Acceptance Criteria

- [ ] Mobile Team no longer needs our assistance implementing changes into Flagship Mobile Looker report.

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1 -- Moving this to Done. Our timing on this is likely going to be dependent on Mobile -- so finalizing this work will be taken on when they are ready.
