### ISSUE TITLE
BE | Profile | Test Tags | Personal Info

### ISSUE THREAD

**Issue by asiisii** [department-of-veterans-affairs/va.gov-team#96569]
## Background
When modifying a feature in vets-api, it would be faster to run specs related to a feature or our team instead of running the full test spec (eg: 10,000+ specs).  RSpec provides a tag for this.

We want to tag our test cases related to the profile team, with the tag “**:profile**” as the second parameter of **it** / **describe** / **context** .

```ruby
# spec/requests/v0/profile/personal_information_spec.rb
describe V0::Profile::PersonalInformation, team: :profile, feature: :personal_info do
  # test code ...
end
```

We can instruct RSpec to only run tests with a specific tag like this:

```ruby
bundle exec rspec spec --tag team:profile
bundle exec rspec spec --tag feature:direct_deposit
bundle exec rspec spec --tag team:profile --tag feature:direct_deposit
```

## Tasks
- [ ] Review Vets-API specs (Tom).
- [ ] Add `team: :profile` and `feature: :personal_info` tags to Personal Information specs

## Acceptance Criteria
- [ ] All Personal Information, preferred names, and gender indenties controller and model spec files have the appropriate tags. Also the Demographic service as well
- [ ] BE engineer handbook updates.
