### ISSUE TITLE
Create sample page - 93788 pt. 2

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#96577]
## Issue Description
In ticket [93788](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?pane=issue&itemId=84087573&issue=department-of-veterans-affairs%7Cva.gov-team%7C93788), a page was created in Confluence to highlight all the elements we expect to see in a well-formatted page for Platform Website.

### This ticket is for the creation of a sample page using examples of correct formatting
Note:
- be sure to include accordions

### Finished Page
[Here](https://vfs.atlassian.net/wiki/spaces/AP/pages/3656646707/Sample+page+All+about+horses)
---
## Tasks
- [x] based on [the sample page guidelines](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3565617356/Draft+Sample+Confluence+page+93788), create actual sample page
- [x] review with the team 
- [ ] schedule announcement of the page in future Tip of The Sprint if ready
- [ ] schedule demo of the page for future [Platform Demo ] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1657995446/End+of+Sprint+Demos) if ready

## Acceptance Criteria
- [x] all tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by taylojill** [comment]
Team feedback received and incorporated for both pages. They are now published in the "About the Platform" space. All tasks complete!

**Comment by jknipes** [comment]
Closing as _Done_
