### ISSUE TITLE
[DESIGN] Create error state for when travel link cannot be retrieved

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#96578]
## Background
Based on [this discussion](https://dsva.slack.com/archives/C05Q9HH47PS/p1730826770711339), we'll need an error state for when a when there’s an error fetching the travel claim link from the api. 

Appointments team already has this in place for AVS, which we should likely follow while ensuring this does not present any new page concerns:
[AVS error state pattern](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=54-11449&node-type=canvas&t=QhI2aMTe9tENmX1j-0)

Some questions to consider: 
- Do we need something in the travel reimbursement section only? 
- How will we treat the action link section? Is something needed there as well or does that link disappear?
- Which scenarios does this apply to?

(Reach out to John W. and Simi with any questions)

## Tasks
- [x] Create any needed error frame states
- [x] Review with CIE UX and Peter/Appointments UX
- [ ] Update feature and latest designs

## A/C
- [ ] Error states created and added to appropriate Figma pages
- [ ] Solution reviewed with CIE UX and Peter/Appointments UX

**Comment by zach-park** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-FE-UX-5fff340c2d80a4000fb6f69c/issues/department-of-veterans-affairs/va.gov-team/96578?planning-poker) with Zenhub @cgednalske @StevenStraily

**Comment by loripusey** [comment]
@zach-park if you guys are going to continue to use Planning Poker (which is a ZenHub feature that will be going away towards the end of the year), please remember to copy the estimate into the Estimate field for the ticket inside the GitHub project.
![Image](https://github.com/user-attachments/assets/fc3b632e-d61b-446e-83aa-b69b5642dd2e)

**Comment by cgednalske** [comment]
We can probably just comment here in the ticket or in a related Slack thread moving forward.

My vote was a 2‍⃣

**Comment by cgednalske** [comment]
@zach-park @StevenStraily want to add your estimates?

**Comment by StevenStraily** [comment]
I voted 3 in the poker.

**Comment by cgednalske** [comment]
Based on our pointing discussion, proposing this is a 2‍⃣

**Comment by zach-park** [comment]
FYI, FE ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96580

**Comment by zach-park** [comment]
@cgednalske , would this go to the Simple mileage-only travel pay claim submission Figma file? I'm assuming it is, but could you please confirm? Thank you!

**Comment by cgednalske** [comment]
@zach-park correct 👍  This is just for the simple mileage-only cross-team collaboration with the travel team - NOT our regular Check-in travel or standalone LoROTA OH travel.

**Comment by cgednalske** [comment]
@zach-park looks good to me 👍 , but I know you said you were going to go over some things with John. Let me know if any changes come up if it needs another review. I'd also recommend checking in with Peter seeing as they need to be ok with the way this works for AVS as well.

**Comment by zach-park** [comment]
@cgednalske @StevenStraily , I synced with @wullaski and we collaborated to develop a draft MVP idea in case the original UI concept is re-prioritized due to the resource limitation. From what John and I agreed was that the engineering team will start with the original UI concept, but will let us know to rescope if there is a need for an MVP when the engineering team starts working on it.
