### ISSUE TITLE
[CDP] Annotations for VHA and VBA Payment History

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#96581]
## Description
Add annotations and updates to VHA and VBA Payment History/ One thing per page mockups

## Tasks
- [x] Update Figma mockups

## Acceptance criteria
- [x] Figma mockups updated

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by mgleo** [comment]
VBA: https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=4279-29090&t=UAbFwxw3HfujH5K8-1

VHA: https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=4147-24675&t=UAbFwxw3HfujH5K8-1
