### ISSUE TITLE
SC [spike] | Investigate work needed to switch list loop

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#96602]
## Value Statement

**_As a_** Veteran
**_I want to_** see consistency of pages across VA.gov
**_So that_** list loop pages use a familiar pattern

---

## Background Context

The Forms team has added a [multipage pattern](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---multi-page) to create multiple response data (array data). Our Supplemental Claim evidence pages use a separate list-loop pattern, but Veteran's have found it to be difficult to navigate. We plan to investigate the amount of work it would require to switch our pattern to the multiple response pattern.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] Evaluate changing VA evidence to new multi-page pattern
- [ ] Evaluate changing private evidence to new multi-page pattern

## Designs and Build Notes

- VA evidence: given the small amount of content, we may be able to have a single page for this
- Private evidence: Split into multiple pages, with at least address being on it's own page

### Enablement team (if needed)
@ member of team

## Out of scope

- Implement changes

## Open questions

- Add here

## Tasks

- [ ] Evaluate replacing list loop with multi-page pattern
- [ ] Evaluate adding a custom component into a page (issue checkboxes are dynamically built based on selections)
- [ ] Evaluate multi-page pattern limitations
- [ ] Evaluate review & submit page views - keep everything in the summary? Or, split up each section
- [ ] Evaluate unit test changes & coverage
- [ ] Evaluate e2e test changes needed

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
- Opened a pull request with platform changes that will add full form data to list loop pages. This will allow us to include issues on the add evidence pages and evidence summary page.
- I have some preliminary work done for the VA evidence page, but haven't worked on the non-VA evidence page since it is fairly similar. We will need a design for the non-VA pages since it might be better to split up the questions across several list loop pages. And we may not need an overall evidence summary page since VA and non-VA will have their own summary pages.

**Comment by dfong-adh** [comment]
Waiting for PR to be reviewed

**Comment by Mottie** [comment]
PR to add full data to array builder has been merged.

After this spike and merged in changes, it is possible to update our SC evidence pages to use the array builder list loop pattern, but we'll need some design changes first:

- Remove the overall evidence summary page
- Build a VA-only evidence summary page
- Build a non-VA-only evidence summary page
- Build an uploaded evidence summary page
- Update review & submit page design
- Update confirmation page design

Moving this ticket to the backlog until the team has time for this

**Comment by eileen-coforma** [comment]
@Mottie Can you create a new ticket for work required to replace list-and-loop? It's separate from this spike, and most likely won't be something we can start by this contract end.

**Comment by Mottie** [comment]
[List loop implementation ticket created](https://github.com/department-of-veterans-affairs/va.gov-team/issues/103986)
