### ISSUE TITLE
[CST] Remove Checkbox confirming file uploads only supports the current claim

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#96603]
## Value Statement
**_As a_** Veteran
**_I want to_** have the checkbox confirming my uploads only support the claim I'm looking at
**_So that_** I understand that don't hesitate to upload a file that applies to more than one claim (i.e 21-4142).
---
## Background Context
Currently in the files page in CST, the UI contains a checkbox that is required for Veterans to check in order to upload files. The label creates the impression that Veterans are only allowed to upload documents that support the currently claim they have accessed.  There are two main concerns with this method: 

1. Veterans might hesitate to upload a file that applies to more than one claim, e.g. a 4142. But there's no reason for them to hesitate.
2. Claims reviewers have no awareness of which documents were uploaded in relation to which claims. This affirmation by the claimant isn't used by them in any way.

**Design for reference**

![Image](https://github.com/user-attachments/assets/7e13d6a8-95f8-4002-b75c-9d5be5c2483f)

### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Remove checkmark from page_
- [ ] _Update form validation to submit without that field_
- [ ] _Create feature flag, suggestion: "remove_supporting_doc_check"_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Files page no longer has checkbox_
- [ ] _Form can submit without the checkbox_
- [ ] _Behind a feature flag_

**Comment by skylerschain** [comment]
This is a dupe of [this ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1549/views/3?filterQuery=check&pane=issue&itemId=88730918&issue=department-of-veterans-affairs%7Cva.gov-team%7C96728), which has been completed, so I'm going to close this ticket.
