### ISSUE TITLE
Refine content operational guidance at Midpoint Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96631]
## User Story
As the content specialist supporting Governance team in Collaboration Cycle, I want to have thorough, comprehensive guidance to follow at Midpoint Review so that I can ensure I am completing each review consistently with all factors considered.

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @erinrwhite 

## Description
The operational guidance that our content specialist follows at Midpoint Review has not been updated since New content specialist @KKitagawa-Bosch joined Governance team. The guidance could use some refinement as it's been observed that giving specific grammar and formatting feedback at Midpoint may be unnecessary as teams are still working off designs and may not have a content source of truth. In addition, the guidance could be refined to include recommendations for when a team is working with CAIA content vs. when they're not.

### Live pages
- [How to complete a Content review for Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2491613360/How+to+complete+a+Content+review+for+Midpoint+Review)

### Drafted pages
- [Draft Page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3722346517/96631+-+Keegan+-+Midpoint+Content+Guidance)

## Tasks
- [ ] Review the existing guidance to determine where changes may be necessary
   - Note from Shira: I don't police or monitor this guidance, so feel free to make any changes that you feel would be helpful for you, your backfill, or any future content specialist. This is your guidance doc so structure it in a way that is most beneficial to you.
- [ ] Make changes to the document as you see fit.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The operational guidance for content at Midpoint Review has been updated 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by KKitagawa-Bosch** [comment]
Created [draft copy of midpoint review guidance ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3722346517/96631+-+Keegan+-+Midpoint+Content+Guidance) to act as the parent document and started bucketing in a child page

**Comment by KKitagawa-Bosch** [comment]
Realizing through the bucketing process that it's a bit more nuanced than what this version of the process will allow. Still going to finish bucketing, but then I also have some plans to pivot and write out more nuanced guidance

**Comment by KKitagawa-Bosch** [comment]
Added a section to the MPR guidance to explain content that should _not_ be reviewed at MPR

**Comment by shiragoodman** [comment]
@erinrwhite please peer review!

**Comment by KKitagawa-Bosch** [comment]
@erinrwhite [here's the updated confluence doc!](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3722346517/96631+-+Keegan+-+Midpoint+Content+Guidance) let me know what you think.

**Comment by erinrwhite** [comment]
@KKitagawa-Bosch looks good! some small notes for revisions to consider. Once you've reviews those you're good to close 👍🏻

**Comment by KKitagawa-Bosch** [comment]
@erinrwhite fantastic call on that comment, thank you! Everything is updated now and I'll close the ticket as soon as I move this from the draft space to its proper home!
