### ISSUE TITLE
[DESIGN] Add annotations for referral and requests link behavior

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#96632]
## Background

We need to add annotations to the Community Care MVP and specs pages to clarify referral and requests link behavior.

Background info:

- The link will always be there - regardless of if there are or aren’t referrals and/or requests (note: there WILL be empty states on the Referrals and requests page when there aren’t any of either to show. Ciera’s currently working on that ticket.)
- No number or badge indicator will be included with the link 

## Tasks
- [x] Add annotations to MVP and specs Figma pages to include the necessary info engineers will need to understand the link behavior
- [x] Check that all other annotations have been updated, specifically with referrals and requests
- [ ] Review with Brian (eng)

## A/C
- [ ] Annotations updated
- [ ] Reviewed with Brian (eng)

**Comment by cgednalske** [comment]
@loripusey here's the annotations ticket. Did I apply the parent issue correctly? 👀

**Comment by cgednalske** [comment]
@zach-park @StevenStraily want to comment your estimates here? 

My vote is a 1‍⃣

**Comment by zach-park** [comment]
> [@zach-park](https://github.com/zach-park) [@StevenStraily](https://github.com/StevenStraily) want to comment your estimates here?
> 
> My vote is a 1‍⃣

I vote a 1‍⃣ also

**Comment by StevenStraily** [comment]
Seems reasonable to me as well.

**Comment by zach-park** [comment]
@cgednalske and @StevenStraily , the annotation is added to the following pages: 

MVP scope: https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=4873-21379&t=2D3VPJVRJcNcDwdk-1

Specs: https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1966-15111&t=2D3VPJVRJcNcDwdk-1

**Comment by cgednalske** [comment]
@zach-park saw you made some changes 👍 Once you've checked with eng to make sure they're good with the annotations (keeping in mind they already did this work 😄), this is probably good to close.

**Comment by zach-park** [comment]
> @zach-park saw you made some changes 👍 Once you've checked with eng to make sure they're good with the annotations (keeping in mind they already did this work 😄), this is probably good to close. 

That sounds good, @cgednalske ! @brianseek and @JohnWilson19 , please take a look at the annotations (linked in the above comment) and let us know what you think. Thank you!

**Comment by brianseek** [comment]
@zach-park annotations look good. One question, with this annotation: "No number or badge indicator is included with the link" why are we still showing it with the number in the actual design?

**Comment by zach-park** [comment]
> [@zach-park](https://github.com/zach-park) annotations look good. One question, with this annotation: "No number or badge indicator is included with the link" why are we still showing it with the number in the actual design?

Apologies, it was an oversight. Fixed now. :)

**Comment by brianseek** [comment]
Thanks @zach-park !
