### ISSUE TITLE
Make email field required on Burial application

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#96640]
### Background:
We currently do not require the email information for applicants filling out the Burial application. If a failure occurs in submitting the application, we have no way of notifying the applicant through email. As part of the zero-silent-failure initiative, we need to inform (send the appropriate emails notifications) the applicant when there is any submission failures.
Additional notes here: https://dsva.slack.com/archives/C07QVEDUQ2D/p1730990852811129

### User Story
As an applicant filling out the Burial form (21P-530), I will be required to enter my email. 

### Tasks
- [ ] Update UX to indicate that the email field is required
- [ ] Update UX to display alert if the email field is left blank and the applicant tries to go to the next step
- [ ] For in progress forms, include migration to send applicant back to email field

### Acceptance Criteria
- [ ] Email field on Burial form is required and provides all UX indicators and alerts to enforce required field.

**Comment by matt4su** [comment]
Passed review in staging environment
