### ISSUE TITLE
Move GH and Calendly notifications to new Slack channel

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96706]
## User Story
As a Governance team member supporting Collaboration Cycle, I want to create a new Slack channel strictly for notifications so that our main channel isn't overused and messages or notifications aren't accidentally missed.

Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
Governance has utilized our #Platform-govenance-team channel to notify us via email notification when:

- Calendly Collaboration Cycle touchpoints (including Design Intent, Midpoint Review, Staging Review, Architecture Intent and PO Sync) are scheduled, rescheduled or cancelled
- Zoom recordings from said touchpoints are available
- new Github Collaboration Cycle Request tickets are created (ie Collaboration Cycle Kickoff) or closed.

The number of notifications has grown significantly over the last couple months and the channel has been crowded with messages. This makes it very difficult for Governance team members to keep up with team discussions, and it also means we're more likely to miss an important notification.

The purpose of this ticket is to create a new Slack channel strictly for the above scenarios. This ticket will include creating the new channel and transferring all notification to occur on the new channel opposed to #platform-governance-team. This ticket will also include updating any operational guidance docs to reflect the change in Slack channel (if needed).

### Live pages
- [On-support guide](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2454093924/On-Support+guide)
- [Collab Cycle Kickoff - Admin Tasks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Admin+Tasks)
- [PO Sync - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3467018468/PO+Sync+-+Scheduling)
- [Architecture Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3468263425/Architecture+Intent+-+Scheduling)
- [Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Scheduling)
- [Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling)
- [Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)
- [Design System Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Design+System+Staging+Review+-+Scheduling)
- [Rescheduling and cancelling touchpoints](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2737766401/Rescheduling+and+cancelling+touchpoints)

### Drafted pages
- 

## Tasks
- [x] Create the new channel
   - `#platform-governance-notifications`
- [x] Transfer all notifications to the new channel
   - [x] New Collab Cycle requests (GitHub)
   - [x] New touchpoint scheduling requests (Calendly/email)
   - [x] New Zoom recordings (Zoom/email) 
- [x] Remove notifications from `#platform-governance-team`
- [x] Update documentation where necessary
- [x] Notify Governance team 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have created a new Slack channel for Collaboration Cycle notifications only
- [ ] We have transferred all existing notifications to the new Slack channel
- [ ] Governance team has been notified of the new channel 

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@allison0034 Ready for review! Besides creating the channel and setting up notifications, I've updated the following pages:
- [On-support guide](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2454093924/On-Support+guide)
- [PO Sync - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3467018468/PO+Sync+-+Scheduling)
- [Architecture Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3468263425/Architecture+Intent+-+Scheduling)
- [Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Scheduling)
- [Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling)
- [Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)
- [Design System Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Design+System+Staging+Review+-+Scheduling)
- [Rescheduling and cancelling touchpoints](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2737766401/Rescheduling+and+cancelling+touchpoints)

**Comment by briandeconinck** [comment]
Thank you! I have fixed the spots you flagged. Will post the announcement to #platform-governance-team and close out!
