### ISSUE TITLE
Remove tasks for asking teams if they intended to skip a touchpoint

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96707]
## User Story
As a Governance team member, I want to remove unnecessary steps in Collab Cycle Scheduling so that it takes me less time to complete the necessary steps. 

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @erinrwhite 

## Description
The Governance operational process for supporting the Collaboration Cycle has gotten more and more complex since the introduction of new touchpoints including PO Sync, CMS Request and Architecture Intent. In order to reduce the amount of work associated with On-Support work, Governance team has decided to cut tasks from our process that are no longer necessary.

Currently, if a VFS team schedules a Midpoint Review without having had a Staging Review, or if they schedule a Staging Review without having had a Design Intent or Midpoint Review, Governance will ask if they intended to skip a touchpoint, and give them the opportunity to change their mind. Since this has been implemented, not a single VFS team has changes their mind and requested the lower touchpoint instead. For these reasons, we will be removing these steps from our guidance.

The purpose of this ticket is to update the operational guidance associated with scheduling Midpoint Review and Staging Review to remove the step for commenting, "We noticed you did not request a _____."

### Live pages
- [Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling)
- [Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)

### Drafted pages
- 

## Tasks
- [ ] Remove the steps in each guidance doc for asking the team via Slack if they intended to skip a touchpoint
- [ ] Verify that the guidance content still flows well and is easy to follow

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team no longer asks if a VFS team intended to skip a touchpoint at scheduling

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by KKitagawa-Bosch** [comment]
@shiragoodman does this particularly need a draft copy in confluence since it's just removal and there's no additions being made?

**Comment by shiragoodman** [comment]
@KKitagawa-Bosch no, I think it's fine if you edit the docs directly (since they're operational and since you're removing - not adding).

**Comment by KKitagawa-Bosch** [comment]
@erinrwhite these should be good to go!

**Comment by erinrwhite** [comment]
@KKitagawa-Bosch this is looking good to me!
