### ISSUE TITLE
Define plan for updating DST SR process for non-DST teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96708]
## User Story
As a Governance team member, I want to define and plan for how we will continue to provide support to teams building out components, patterns, templates and guidance for VFS teams, so that we can implement the plan and support them appropriately, instead of just forcing them down the path VFS teams follow.

Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
The DST Staging Review process was defined and written when DST was the only team building components and/or services for Veteran Facing teams. Since then, we've had the Veteran Facing Forms team and the AE design patterns team contribute to the components, patterns, templates, and guidance for VFS teams to use and follow. 

The current DST Staging Review process is very niche and specific to the Design System team. The purpose of this ticket is to  refine the current DST Staging Review process to make it more inclusive and usable for similar teams. In addition, we'd like like to make the process more visible to these teams so that they don't go down the traditional Collaboration Cycle path that is built specifically for VFS teams.

Things to consider:

- What do we call these teams building components, patterns, templates or guidance for VFS teams? We need an easy name since "DST" will no longer work for all. 
- How do we make this process visible to all of these teams? DST is part of platform, so the current guidance is in Confluence, but not all of these teams have access to Confluence.
- Right now, we allow DST to just go straight to Staging Review and they have their own template. Should we pivot and ask them to complete kickoff first? We could add a question at kickoff asking if the team is a VFS OR ask if they're a team building guidance, and then have a custom tracks flow specific to these teams. Although DST only does SR, sometimes VFF and AE Design patterns have participated in Design Intent. How should we account for that?
- How will we label these tickets? Right now we use the `DS-Staging-Review` label but that won't suffice for all. All CC requests currently have the `CC-Request` label.
- How will we label the SR findings tickets? For severity, the difference currently is that VFS teams have `launch-blocking` issues, while DST teams have `high-priority` items and `consider` issues. For tracking, VFS teams have the `CC-Dashboard` label, while DST tickets have the `DS-Staging-Review` label.
- We currently upload all DST issues to their repo, vets-design-system-documentation, but all VFS issues are uploaded to va.gov-team. How will we change or modify this?
- What about the DST DraftingTempalte? What changes need to happen there in order to support more than just DST?

### Live pages
- 

### Drafted pages
- [Proposal for handling "facilitation products" in the Collab Cycle](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3811016741/Proposal+for+handling+facilitation+products+in+Collab+Cycle+96708)

## Tasks
- [x] Document a proposal, answering the questions above, for how we might build out a solution to support DST, VFF, AE Design Patterns, and potentially other teams building out services for VFS teams
- [x] Share with Governance team members for their review and input.
- [x] Make changes based on feedback, if needed.
- [x] Once all Governance team members have provided input, create a ticket for the Governance backlog to implement solution. Break up into more than 1 ticket if needed. Consult with Shira.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have documented a plan for updating the DST SR process to support other teams that are not building directly for VA.gov
- [x] We have created a ticket for implementing our proposed solution.

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
Quick status update: Unexpected out-of-office time last week has me a bit behind on this, and it's likely to carry over into the next sprint. I have some notes on what the process could look like, just need to clean them up and collect them in Confluence.

**Comment by briandeconinck** [comment]
@allison0034 Ready for you to review!

[Proposal for handling "facilitation products" in the Collab Cycle](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3811016741/Proposal+for+handling+facilitation+products+in+Collab+Cycle+96708)

**Comment by allison0034** [comment]
Hi @shiragoodman , I just met with Brian and had some questions about removing the current DST process and replacing it.

I see the benefit for making a process for AE/forms team and those "other" non VFS teams, but I am not seeing a benefit to changing the DST process, although I may not fully understand. If we change the DST to complete a kickoff, that will add time and work (death by 1000 cuts) to our support process. It will also add time and work to the DST. Is there any benefit to having them fill out a kick off request since they only need a Staging Review?

cc @briandeconinck

**Comment by shiragoodman** [comment]
I see your point, and I agree that it would add to both our workload and theirs.

Let me think about this and I'll get back to you both.

**Comment by briandeconinck** [comment]
@allison0034 Made some updates to the [Confluence document](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3811016741/Proposal+for+handling+facilitation+products+in+Collab+Cycle+96708) based on conversations this week. Let me know if the changes make sense and if I've captured everything in the DST discussion.

Thank you!

**Comment by allison0034** [comment]
@briandeconinck I made some comments. I think it may be useful to compare what the differences would be between the 2 flows you are proposing. For example, for MPR, it looks as though the only difference is asking for guidance under the artifacts. Do we really need a separate code block just for that?

**Comment by briandeconinck** [comment]
Per our discussion in standup today, this ticket is carrying over to the next sprint to give more time for Governance team feedback and feedback from Matt

**Comment by briandeconinck** [comment]
@allison0034 Working on draft tickets for the backlog, per the last part of this. Might need you to read them later today to make sure they make sense!

**Comment by briandeconinck** [comment]
Draft tickets added to the backlog for implementing this plan:
#103700
#103702
#103703 (still blank)
#103704

**Comment by allison0034** [comment]
@briandeconinck the tickets look good to me. Do you need me to review anything else?

**Comment by briandeconinck** [comment]
Thank you @allison0034! I think that's it --- if it all looks good to you I'll close this out.
