### ISSUE TITLE
Refine SR requirements for production-ready products

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96705]
## User Story
As a Governance team member, I want to communicate in our Staging Review guidance that a product must be production ready before coming to staging review so that we can prevent teams from coming to Staging Review prematurely. 

As a Governance team member, I want to block VFS teams from coming to Staging Review if their product isn't production ready so that I don't have to waste my time logging an excessive amount of issues.

Assignee: @erinrwhite 
Peer Reviewer: @briandeconinck 

## Description
The Staging Review requirements currently communicated on Platform Website do not state anything about the product being production ready. It's somewhat implied, however we have recently had teams come to Staging Review with products that are full of errors and issues and definitely not production ready. In these situations, Governance team spends a significant amount of time completing the Staging Review (sometimes double the amount of time compared to a team that does have a production ready product). By adding this new Staging Review requirement, Governance team will be able to push back on VFS teams that are not ready for production, and will have the power to cancel their Staging Review citing that it's not production ready. 

The purpose of this ticket is to modify the Staging Review requirements so that they include language stating that the product, to the VFS teams knowledge, is ready to launch on VA.gov. In short, we want to ensure that the team has done their due diligence and is not wasting Governance's time by sending an incomplete product to us.

### Live pages
- [Staging Review ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)touchpoint page
- Staging Review video??
- [Staging Review scheduling page in Calendly](https://calendly.com/collaboration-cycle/staging-review?month=2024-12)

### Drafted pages
- 

## Tasks
- [x] Refine the SR requirements as you see fit
- [x] Once peer reviewed, share with Matt and Shira for review
- [x] Draft change history post and Slack change announcement
- [x] Publish changes and post Slack announcement

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Staging Review requirements have been updated to include that the product must be production-ready
- [x] VFS teams have been notified of the change to the SR requirements

## Team Notification
- [x] Slack post on #platform-governance-team (x share change announcement)
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
[Current requirements:
](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review#Stagingreview-SchedulingandRequirements)

> The VFS team agrees to:
> 1. Make the product available for testing on an [approved staging environment](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-environment-guidance-for-vfs-teams).
> 2. Fix all bugs and communicate any known issues on the backlog.
> 3. Provide test user information with valid credentials if the product requires authentication.
> 4. Document all user scenarios and how to test them, i.e.: in-progress form, submitted form, new form.
> 5. Update the product’s primary entry point page and include it for review, if applicable.
> 6. Provide all other artifacts marked as required in the Collaboration Cycle ticket.
> 7. Not make changes to code or artifacts during the 4-business-day window before the meeting.

"Fix all bugs and communicate any known issues" is a bit contradictory. I think this whole bullet point should be edited and, from an order-of-operations perspective, this should be requirement number 1 rather than number 2.

Recommended language:

> The VFS team agrees to:
> 1. Verify that the product/feature is complete and ready to go to production, with any known bugs or defects addressed and no additional development planned prior to launch.
> 2. Make the product available for testing on an approved staging environment 4 business days before the Staging Review meeting.
> ...
> 7. Not make any changes to code or artifacts during the 4-day business window before the meeting.

@briandeconinck when you're back online next week, any feedback on this language? Also tagging in @shiragoodman

**Comment by erinrwhite** [comment]
Thank you @shiragoodman - how about this? @briandeconinck 

> The VFS team agrees to:
> 
> 1. Verify that the product/feature is ready to go to production, with no additional development planned besides addressing issues identified at Staging Review.
> 2. Make the product available for testing on an approved staging environment 4 business days before the Staging Review meeting. 
> 3. Communicate any known issues that are on the backlog.

(rest of list remains the same)
> 4. Provide test user information with valid credentials if the product requires authentication.
> 5. Document all user scenarios and how to test them, i.e.: in-progress form, submitted form, new form.
> 6. Update the product’s primary entry point page and include it for review, if applicable.
> 7. Provide all other artifacts marked as required in the Collaboration Cycle ticket.
> 8. Not make changes to code or artifacts during the 4-business-day window before the meeting.

**Comment by shiragoodman** [comment]
@erinrwhite Better. 2 is good to go. However, I have concerns about the language used in 1 and 3.

> Verify that the product/feature is ready to go to production, with no additional development planned besides addressing issues identified at Staging Review."

I think we should change "ready to go to production" to "ready for production". Something doesn't sit right with me with the wording, "besides addressing issues..." Maybe "no additional development planned outside of addressing findings identified at Staging Review."

> Communicate any known issues that are on the backlog.

I think mentioning backlog might create more problems for us. We don't need them to communicate what's planned or next steps. We should be more specific here. Maybe just, "Communicate any known issues that we may identify in Staging Review."

Open to suggestions!

**Comment by erinrwhite** [comment]
@shiragoodman thank you!! these are big improvements. Okay, how about this: @briandeconinck

> The VFS team agrees to:
> 
> 1. Verify that the product/feature is ready for production, with no additional development planned outside of addressing findings from Staging Review.
> 2. Make the product available for testing on an approved staging environment 4 business days before the Staging Review meeting.
> 3. Communicate any known issues that we may identify in Staging Review.

(rest of list remains the same)

If I remember correctly we *might* hit a character limit in Calendly for this. If so, I can take a stab at streamlining the text of the list to be more succinct.

**Comment by shiragoodman** [comment]
thank you for making the changes, @erinrwhite ! this looks great. Let me know if the Calendly char. limit is hit.

**Comment by briandeconinck** [comment]
Catching up --- sorry for the long delay!

> Communicate any known issues that we may identify in Staging Review.

I think it's a little unclear who "we" is in this, the VFS team or Governance. Otherwise I think everything is clear and concise!

**Comment by erinrwhite** [comment]
Okay, here's what we've got. @humancompanion-usds can you review this updated language and let us know if it's okay to proceed? Big goals here were (1) clarify that products need to be production-ready and (2) clarify language about known issues.

## EXISTING Staging Review requirements

The VFS team agrees to:

> 1. Make the product available for testing on an [approved staging environment](https://vfs.atlassian.net/wiki/spaces/CC/pages/2396094469).
> 2. Fix all bugs and communicate any known issues on the backlog.
> 3. Provide test user information with valid credentials if the product requires authentication.
> 4. Document all user scenarios and how to test them, i.e.: in-progress form, submitted form, new form.
> 5. Update the product’s primary entry point page and include it for review, if applicable.
> 6. Provide all other artifacts marked as required in the Collaboration Cycle ticket.
> 7. Not make changes to code or artifacts during the 4-business-day window before the meeting.

## NEW Staging Review requirements

> The VFS team agrees to:
> 
> 1. Verify that the product/feature is ready for production, with no additional development planned outside of addressing findings from Staging Review.
> 2. Make the product available for testing on an [approved staging environment](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-environment-guidance-for-vfs-teams#StagingEnvironmentGuidance-TypesofStagingenvironments) 4 business days before the Staging Review meeting.
> 3. Communicate any known issues that the Governance Team may identify in Staging Review.

[rest of list is the same as current guidance, with new numbers]
> 4. Provide test user information with valid credentials if the product requires authentication.
> 5. Document all user scenarios and how to test them, i.e.: in-progress form, submitted form, new form.
> 6. Update the product’s primary entry point page and include it for review, if applicable.
> 7. Provide all other artifacts marked as required in the Collaboration Cycle ticket.
> 8. Not make changes to code or artifacts during the 4-business-day window before the meeting.

**Comment by erinrwhite** [comment]
@shiragoodman @briandeconinck I also verified there are no character limits in Calendly 👍🏻

**Comment by shiragoodman** [comment]
Thanks, @erinrwhite ! If Matt is unable to take a look today, I will add to our agenda for our 1:1 tomorrow.

**Comment by erinrwhite** [comment]
Thanks @shiragoodman I'm guessing Matt is OOO today for the Federal holiday for President Carter's memorial. I appreciate you bringing it to him tomorrow!

**Comment by shiragoodman** [comment]
@erinrwhite I reviewed these changed with Matt at our 1:1 this morning and he approves! 

The one thing he did note, which I told him we already discussed, it determining _how_ we want teams to notify us of existing issues and bugs. I think I mentioned before that this can be handled in another ticket. If you haven't already, could you please create a ticket for that and tag it here? ty! please lmk if you have any questions.

**Comment by shiragoodman** [comment]
Slack announcement looks good to me. I appreciate the sentence, "This is not a change so much as a clarification of existing practice."

**Comment by briandeconinck** [comment]
@erinrwhite This all looks great to me! 👍

**Comment by erinrwhite** [comment]
> The one thing he did note, which I told him we already discussed, it determining _how_ we want teams to notify us of existing issues and bugs. I think I mentioned before that this can be handled in another ticket. If you haven't already, could you please create a ticket for that and tag it here? ty! please lmk if you have any questions.

New ticket created! #100878

**Comment by erinrwhite** [comment]
Draft pages ready to be published this afternoon, will check back after 3:30 then post to Slack:

[Change history](https://vfs.atlassian.net/wiki/spaces/CC/pages/1846870032/Change+history)
[Staging review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1810137181/Staging+review)

Live pages:
[Change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history)
[Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review#Stagingreview-SchedulingandRequirements)

**Comment by erinrwhite** [comment]
Pages published!
[Change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history)
[Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review#Stagingreview-SchedulingandRequirements)

[Announcement made](https://dsva.slack.com/archives/CE4304QPK/p1736802011947969) and [shared with Governance Team](https://dsva.slack.com/archives/GNF5GSD9N/p1736802047520389)

@briandeconinck one final review?

**Comment by briandeconinck** [comment]
Looks good @erinrwhite! I think you're good to close

**Comment by erinrwhite** [comment]
Thanks @briandeconinck! closing...
