### ISSUE TITLE
Update Staging Review code block for 2 things

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96703]
This ticket is a prerequisite for #96427 and must be completed before #96427 can begin.

## User Story
As a VFS team member, I want to be able to rely on the guidance within my Collab Cycle Request ticket so that I can ensure my team is prepared for any upcoming touchpoint. 

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
The Staging Review code block that is added to all new Collab Cycle request tickets via kickoff has 2 errors:
1. The reference to the experimental design process has a broken link:

> - [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.

2. The QA Artifacts section is missing a reference to Logging Silent Failures. 

### Live pages
- [Collaboration Cycle Kickoff - Code Blocks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3387457549/Collaboration+Cycle+Kickoff+-+Code+Blocks)

### Drafted pages
- 

## Tasks
- [ ] Update the experimental design link to direct to the correct page
- [ ] Add Logging Silent failures to the QA artifacts section

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] All new Collab Cycle Request tickets post kickoff will have up to date Staging Review guidance

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
This ticket will replace #96427 for updating the QA artifacts in the Staging Review code block. #96427 will be closed.

**Comment by it-harrison** [comment]
@briandeconinck this is ready for review:
* [combined code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3387457549/Collaboration+Cycle+Kickoff+-+Code+Blocks#Combined-code-block-for-all-touchpoints)
* [staging review code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3387457549/Collaboration+Cycle+Kickoff+-+Code+Blocks#Staging-Review)

**Comment by briandeconinck** [comment]
@it-harrison Perfect, looks good to close!
