### ISSUE TITLE
Content Edit: 96615 My Healthe Vet page 

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#96717]
## Issue Description
Per [Footer ticket 96615](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?pane=issue&itemId=86272028&issue=department-of-veterans-affairs%7Cva.gov-team%7C96615), make content edits.
Note: links provided by requestor point to individual comments on the same Google doc.

### Relevant Link:
 - [Here's what's changing with My Healthe Vet](https://www.va.gov/initiatives/prepare-for-vas-secure-sign-in-changes/)
---
## Tasks
- [x] Edit page according to 96615

## Acceptance Criteria
- [x] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
look into timeline of MHV going away

**Comment by jknipes** [comment]
@taylojill

**Comment by jknipes** [comment]
work is complete, closing ticket
