### ISSUE TITLE
[CST] Remove required checkbox in file uploader widget

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#96728]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to submit files that can apply to more than one claim from CST
**_So that_** I don't have to submit files multiple times across different claims for the same purpose (e.g. 21-4142)

---
## Background Context

Currently there is a checkbox in the file uploader widget when a Veteran is uploading a file. This shows up in two places:
1. The [Additional evidence section](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST-V2?node-id=518-2560&t=jKlxzSjcBT2YP813-4) of the Files tab
2. The [document request page](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST-V2?node-id=3643-4867&t=jKlxzSjcBT2YP813-4) of a 1P/3P request.

<img width="1308" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGFrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44fb12a858f77ac175dbec027da320fbf7905da9/Screenshot%202024-11-07%20at%203.45.23%E2%80%AFPM.png" alt="Screenshot 2024-11-07 at 3.45.23 PM.png" />

We don't think this checkbox is very valuable to users, and in fact could be detrimental in the scenario where a Veteran wants to upload a file that could apply to multiple claims (e.g. 21-4142). We want to remove it.

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Design spec will be updated once checkbox is removed. Can add mock if needed.

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Does clicking the checkbox send any unique information to VA? Answer: no it does not.

## Tasks
- [x] _Remove the "The files I uploaded support this claim only (*Required)" checkbox from the Files tab for all claims in CST_
- [x] _Remove the "The files I uploaded support this claim only (*Required)" checkbox from document request pages for 1P and 3P alerts_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Checkbox is removed from document request page of 1P and 3P alerts_
- [ ] _Checkbox is removed from the Files tab of claims in CST_
- [ ] _[CST V2](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST-V2?node-id=0-1&node-type=canvas&t=jKlxzSjcBT2YP813-0) spec has been updated to reflect UI changes_

**Comment by pmclaren19** [comment]
tested in staging and looks good!

**Comment by pmclaren19** [comment]
> [@pmclaren19](https://github.com/pmclaren19) [@skylerschain](https://github.com/skylerschain) It looks like the description of this ticket missed that we also need to remove the sentence that says:
> 
> > Please only submit evidence that supports this claim. To submit supporting documents for a new disability claim, please visit our [How to File a Claim page (opens in a new tab)](https://staging.va.gov/disability/how-to-file-claim) .
> 
> This sentence that needs removal is also on both places described in the Background Context section of this issue's description
> 
> Could you remove or create a separate ticket for it?

Hey Julie! Yea I can make another ticket for that work since its not related to this current ticket and this current ticket is already closed.

**Comment by pmclaren19** [comment]
> [@jstrothman](https://github.com/jstrothman) Are you saying we don't want to draw that distinction at all? I don't really have a problem removing it, but I also don't see the harm in keeping it on the off chance someone is trying to submit files for a new claim.

Can we please add any discussions around this issue on the new ticket - https://github.com/orgs/department-of-veterans-affairs/projects/1549/views/3?pane=issue&itemId=91089048&issue=department-of-veterans-affairs%7Cva.gov-team%7C99180 ? Thank you !
