### ISSUE TITLE
Define imposter component in appropriate guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96720]
## User Story
As a VFS team member, I want to understand what an imposter component is so that I can prevent them from being used in my product, or learn how to address them if/when an imposter component is flagged at Staging Review.

Assignee: @allison0034 
Peer Reviewer: @KKitagawa-Bosch 

## Description
There is currently no guidance on Platform Website or on VADS that explains what an imposter component is. If we're going to use this language in Staging Review and throughout the Collaboration Cycle, then we need to define an imposter component and provide guidance on how it is flagged and how to handle it. 

The purpose of this ticket is to write guidance on Imposter Components, as well as identify where the guidance should live. (Shira's vote is for VADS).

### Live pages
- [Components overview](https://design.va.gov/components/)

### Drafted pages
- 

## Tasks
- [x] Identify where the new Imposter Component guidance should live 
   - Note: we don't necessarily need to create a new page dedicated to imposter components. Would it make sense for the guidance to live within an existing page?  
- [x] Identify if we need to reference the Imposter Component guidance in any other existing guidance documentation
- [x] Draft guidance on the imposter component, ~~including labels used (both exp-std label and imposter component label)~~
- [x] Peer review
- [x] Once approved, publish the guidance
- [x] Would it make sense to link to this guidance in future imposter component staging review findings tickets? If you think so, please create a ticket for the Governance backlog and tag Shira

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance has published guidance for VFS teams on imposter components

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
[Working with Ian on "technical" wording.](https://dsva.slack.com/archives/GNF5GSD9N/p1732644610713129)

**Comment by allison0034** [comment]
@shiragoodman I have a question about...

> Draft guidance on the imposter component, including labels used (both exp-std label and imposter component label)

We do not include any labels for any other violations we log at Staging review. I am thinking we do not want to start listing specific ones in the guidance for DS (which is where this will be going). The experience standard and label are included in our [internal guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+the+Staging+review+touchpoint#Check-for-imposter-components). 

Is it ok to not add the label and experience standard to DS guidance? For what it is worth I will likely be adding it to [this page](https://design.va.gov/components/).

**Comment by allison0034** [comment]
@erinrwhite wanted to get your opinion. I am planning on putting something like this (gonna have Keegan and Ian look at the content)...

Imposter components
Most components are listed in Storybook. If your team is not using the components and their code in Storybook, then that is considered an imposter component and will be flagged at a Staging Review. This includes components that are coded to look like the ones in Storybook, but do not use the Storybook code.

...after the alert on [this page](https://design.va.gov/components/).

**Comment by shiragoodman** [comment]
@allison0034 I am okay with us not adding info on the experience standard or labels. If we ever feel like it is needed, we can always add it in.

**Comment by erinrwhite** [comment]
@allison0034 I like the idea of updating the [components page](https://design.va.gov/components/) and putting this info where the current h3 `Governance rules for using v3-based components` is. Maybe transform that heading to be more broad, something like...

> ### Governance rules for components
> 
> #### Avoid imposter components
> Most components are listed in Storybook. If your team is not using the components and their code in Storybook, then that is considered an imposter component and will be flagged at a Staging Review. This includes components that are coded to look like the ones in Storybook, but do not use the Storybook code.
> 
> #### Use newest component versions when possible; when not possible, be consistent
> v3-based versions of the components are designed to sit alongside our current v1 based components and the foundational elements of the Design System. Teams must use the new versions of our web-components and following these rules:
> 
> [ ... ]

**Comment by allison0034** [comment]
@KKitagawa-Bosch [this is ready](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/3883af36a6f9affbd3a3c26b5947ac492a73e456/src/_components/index.md) for your peer review.

**Comment by allison0034** [comment]
Waiting for peer review to approve PR #3548

**Comment by KKitagawa-Bosch** [comment]
Ah sorry I thought the edits I did in slack were the peer review! Just checked the GH and everything looks good!

**Comment by allison0034** [comment]
@KKitagawa-Bosch [published](https://design.va.gov/components/)! One last peer review before I close?

**Comment by allison0034** [comment]
Using that word is fine where it is placed. He had me change it in a different spot.
