### ISSUE TITLE
Tracking if SR findings were flagged at DI and/or MPR

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96726]
## User Story
As a Governance PO/PM, I want to know when issues identified at Staging Review were issues identified previously so that I can begin to understand and track when VFS teams don't follow our recommendations.

Assignee: @shiragoodman 
Peer Reviewer: @it-harrison 

## Description
Governance would like to begin to track is issues found in lower touchpoints (ie Design Intent and Midpoint Review) are still issues existing when the VFS team brings the product to Staging Review. This will help us identify what percentage of Staging Review issues were concerns raised earlier.

The purpose of this ticket is to modify the DraftingTemplate to add 2 new columns to the Findings tab, 1 for Design Intent and 1 for Midpoint Review, asking the Governance review to specify if this was an issue raised at 1 of those touchpoints. There should be a specific unique label associated with both. If/when the Governance team specifies that yes - this issue was raised at DI, or yes - this issue was raised at MPR, the unique labels will be added to the labels list in the CSV, creating SR Findings tickets with those labels. **Labels used were determined via ticket #[101146](https://github.com/department-of-veterans-affairs/va.gov-team/issues/101146)**

~~Additionally, the [Anatomy of a Staging Review Issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket) should be updated to add the new labels.~~ No longer needed due to completion of ticket #101146.

### Live pages
- 

### Drafted pages
- 

## Tasks
- [x] Edit the DraftingTemplate Findings tab to include 2 new columns: 1 asking if the issue was previously identified at DI, and 1 asking if the issue was previously identified at MPR
- [x] If/when either of those cells are checked off, the appropriate label should be added to the finding
- [x] When changes are made, test and validate the change

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team will now be able to track/label if/when a SR issue was previously identified at MPR or DI

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
postponing this ticket to Sprint 20 since I will likely work on it, and I will be OOO for most of Sprint 19.

**Comment by shiragoodman** [comment]
@it-harrison I believe the DraftingTemplate is ready for your review. I created a[ draft version,](https://docs.google.com/spreadsheets/d/1ftCMxCufYMkgAW_n3RL52bv_GsoerGZChU_eeoqopQQ/edit?usp=drive_link) so please test it out and make sure it is easily understood and functions as intended. LMK if you have any questions!

**Comment by it-harrison** [comment]
@shiragoodman tested, works perfectly!

**Comment by shiragoodman** [comment]
The DraftingTemplate changes have been published and the new Drafting Template is renamed 2.1.

In addition, the DraftingTemplates for the following Staging Reviews have been updated:

- [Education Date Migration, Yellow Ribbon Tool ](https://drive.google.com/drive/u/0/folders/1Lv0NUVoU1cYnDRDIfCieDsacV7voNr-U)scheduled for 2/21
- [Benefits Dependent Experience, 21-686c/674, Critical Form Updates](https://drive.google.com/drive/u/0/folders/15ix628V41p7Qyusvs-Nyu64cp8MpYZIV) scheduled for 2/25
- [Debt Resolution, Digital Debt Dispute](https://drive.google.com/drive/u/0/folders/1dUELZY3g5HTd3QIR833k8ht9incI2Eaq) scheduled for 2/28
- [Accredited Rep Facing (Accredited Rep Portal MVP), Accredited Rep Mgmt (Appoint a Rep 2.0)](https://drive.google.com/drive/u/0/folders/1ET7rvs-MxIXcjJc-Y-CeBeJq06HFj1zF) scheduled for 2/27
- [Modernized Check-in, Appointments, Travel Claims for Past Appointments ](https://drive.google.com/drive/u/0/folders/1mJ_NBAd30udNHkLt32PFpH8q8cpubiU8) scheduled for 2/27
- [Ask VA Integration/Ask VA](https://drive.google.com/drive/u/0/folders/1NkSbH6r4oGT-i8Dj_ek7OUt8SNLa6GMD) scheduled for 3/4

**Comment by shiragoodman** [comment]
[Announced to Governance team. ](https://dsva.slack.com/archives/GNF5GSD9N/p1739306583242249)
