### ISSUE TITLE
Prevent vets-api commits that fail tests from being deployed

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#96743]
## User Story
As a maintainer of vets-api, I want to ensure that only commits that pass CI tests are deployed, so that we maintain code quality and prevent issues in production due to unverified changes.

## Issue Description
vets-api can sometimes deploy a commit that did not pass CI. See details [in this thread](https://dsva.slack.com/archives/C0460N83Y9G/p1730238221670349). We believe this can happen when commits are merged within a few minutes of each other. It has been seen a few times.

### Example:
**This commit failed its CI tests:**
![Image](https://github.com/user-attachments/assets/f87d51b5-e619-4eb2-a50b-97c2860c08d6)

**The [Build, Push, & Deploy](https://github.com/department-of-veterans-affairs/vets-api/actions/workflows/build.yml?query=branch%3Amaster) action from a previous commits run picks up the latest sha:**
![Image](https://github.com/user-attachments/assets/1a710e3b-da5a-4b89-aab3-00de48262035)

**And deploys it:**
![Image](https://github.com/user-attachments/assets/82382eb3-ee10-4c8d-8665-a1a91b61fc62)

## Tasks
- [x] Understand the edge case where this can happen.
- [x] Edit [deploy-template.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/deploy-template.yml) to prevent this from happening. 

## Acceptance Criteria
- [ ] Updates to the deploy template are reviewed and merged.
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note:** The dev. was asked to focus on higher priority work. This ticket will roll over to Sprint 17.

**Comment by rjohnson2011** [comment]
PR open -> https://github.com/department-of-veterans-affairs/vets-api/pull/20031
