### ISSUE TITLE
Content Edit: Footer Ticket 89374

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#96741]
## Issue Description

- We need to edit formatting of [Screen Reader Instructions page](https://depo-platform-documentation.scrollhelp.site/research-design/screen-reader-instructions-and-troubleshooting-dur), including any necessary fixes to indented bullets, creating numbered lists and breaking up numerical steps.
---
## Tasks
- [x] Based on discovery in [ticket 96737](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?pane=issue&itemId=86430120&issue=department-of-veterans-affairs%7Cva.gov-team%7C96737), make formatting edits
- [x] Collaborate with SME, Jamie Klenetsky-Faye
- [x] prepare for deployment

## Acceptance Criteria
- [x] page is ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by taylojill** [comment]
Draft of **iOS VoiceOver** page sent to Jamie (SME); she's OOO until Nov 30th. I need SME assistance with some of the language on the page. The other two pages are in good shape and I'll ask her to review them as well.

**Comment by taylojill** [comment]
Sent updated draft to Jamie for review/sign-off. Naomi is working to get video hosted on YouTube channel; once done I will update the page link.

**Comment by jknipes** [comment]
Additional time needed to review changes and prepare for deployment. This issue continued to grow in scope and therefore requires additional time to resolve. Carrying over into Upcoming Sprint.

**Comment by taylojill** [comment]
All pages approved by Jamie. I will prepare the pages for deployment.

**Comment by jknipes** [comment]
Closing as _Complete_
