### ISSUE TITLE
686 Updates | PDF and json Testing

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#96740]
## Issue Description
_As part of the phase 2 686/674 updates, data from VA.gov needed to be [re-mapped to the json and pdf files](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91068). We need to provide updated json and pdf files to the VBA, so they can verify they are correct and approved for release. The maximal scenario should be used for testing where as many fields as possible are filled out on the online form flow on VA.gov._

Testing should confirm:
- The pdf generated by VA.gov matches what the user entered on the front end
- The date stamped in the upper-right date stamp field and the signature line represents the date the claim was submitted (not the date the pdf was generated -- sometimes they can be different dates)
- Data that is too long for the field on the pdf overflows as expected to the last page

Instructions for testing:

1. Generate minimum, maximum, and overflow pdf scenarios.
2. Product Manager or backend engineer will post the pdfs and json to the OBI [Teams channel](https://teams.microsoft.com/l/message/19:7Dew_Vfcs2z_BJK7XVhgWbaSQfJej2UO13Kq51sebX81@thread.tacv2/1744742252979?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=954a8eef-0c1f-4129-8eea-94149c3fef97&parentMessageId=1744742252979&teamName=OBI%20and%20VA.GOV%20Submission%20%2B%20Backup%20Processes&channelName=General&createdTime=1744742252979) and in [mvp-686-674-staging-pdf](https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FDependents%20Management%2Fmvp%2D674%2Dstaging%2Dpdfs&viewid=3fa7a9bb%2D3d4e%2D44c2%2Db93f%2D629268a08e72&OR=Teams%2DHL&CT=1717096760601&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNDA0MTEyMjMxNSJ9) SharePoint folder.
3. The following individuals should be tagged in the Teams thread to validate the pdf and json files. Note, on the initial post, confirm that this is still the testing group that should be included (bc some are contractors):
  - Sanja Bajovic
  - I, Tara: Program Analyst
  - Elizabeth Reeher: Project Manager
  - Caleb Roberts: Government lead on testing team:
     - Daniel Lattin
     - Donald Moses
     - Benjamin Brown

---
## Tasks
- [ ] Generate maximal json submission
- [ ] QA maximal json submission
- [ ] Generate maximal pdf submission
- [ ] QA maximal pdf submission (e.g. date stamped is date claim was submitted)
- [ ] Post json and pdfs to OBI testing channel in [Teams](https://teams.microsoft.com/l/message/19:7Dew_Vfcs2z_BJK7XVhgWbaSQfJej2UO13Kq51sebX81@thread.tacv2/1744742252979?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=954a8eef-0c1f-4129-8eea-94149c3fef97&parentMessageId=1744742252979&teamName=OBI%20and%20VA.GOV%20Submission%20%2B%20Backup%20Processes&channelName=General&createdTime=1744742252979)

## Acceptance Criteria
- [ ] Form fields map to PDF filed in VBMS e-folder
- [ ] All form fields submitted through maximal submission map correctly to the PDF filed in VBMS
- [ ] Minimum submissions for add, remove, and double student 674 scenarios map correctly to the PDF filed in VBMS

**Comment by jacobworrell** [comment]
This is complete, but acceptance criteria was updated to adapt to new testing protocols. Original criteria was set before team knew we could validate PDF mapping ourselves by finding the submission in VBMS.
