### ISSUE TITLE
Content Edit: Footer Ticket 95548

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#96753]
## Issue Description
Make content edits per [95548](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95548): Prohibited Characters:
>Right now [the platform docs page](https://depo-platform-documentation.scrollhelp.site/getting-started/adding-files-to-the-github-repository) says to avoid _question marks, colons, and pipe symbols_; to avoid file names ending with a space or period or starting with a space; and to avoid long file paths because of the 256-character file path limit on Windows.

>The information shown in italics in the previous paragraph is what needs to be updated. 
**The list of characters to avoid needs to be expanded. It should include: forward and back slashes (/, \), less and greater than signs (<, >), colons (:), double quotes ("), pipe symbols (|), question marks (?), and asterisks (*).**
---
## SME:
-Johnathan Kamans

## Tasks
- [x] add list of prohibited characters above to the [Adding files to the GitHub repository page](https://depo-platform-documentation.scrollhelp.site/getting-started/adding-files-to-the-github-repository)
- [x] prepare for deployment

## Acceptance Criteria
- [x] all tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by BSmolensky** [comment]
Made copy of page and working on update.

**Comment by BSmolensky** [comment]
All tasks complete. Ticket is ready to close.
