### ISSUE TITLE
Tech Discovery: Veteran Details

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#96751]
## Issue Description
As a team member I want to know which custom components or legacy widgets are in use within the Veteran Details chapter of the 526 form so that I am able to plan for potential upgrades to these form components.

---
## Tasks
Review the following pages
- [x] veteran-information
- [x] contact-information
- [x] housing-situation
- [x] terminally-ill
- [x] alternate-names
- [x] review-veteran-details/military-service-history
- [x] review-veteran-details/military-service-history/reserves-national-guard
- [x] review-veteran-details/military-service-history/federal-orders
- [x] review-veteran-details/separation-location
- [x] separation-pay
- [x] retirement-pay
- [x] training-pay

## Acceptance Criteria
- [x] A list of any custom components or legacy widgets in use within the Veteran Details chapter is created
- [x] This list is reviewed with the PM and another member of the team, knowledgable about frontend
- [ ] Documentation is created in [Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez)
- [x] Save working spreadsheet in Google Drive Engineering folder

**Comment by bacitracin** [comment]
Work in progress google sheet is here https://docs.google.com/spreadsheets/d/1xjGHcPX2JtvQBh5_M1uPQv6izjs0utjmv0qrs2SsRB4/edit?gid=0#gid=0

Have not created documentation in GitHub yet. Was going to save that for when we have a better idea of what we will & won't fix...

**Comment by pacerwow** [comment]
Google doc works for now, pls make sure VA stakeholders have access. Thanks! Good to close.
