### ISSUE TITLE
DIC rates tables spreadsheet for stakeholder approval

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#9676]
## User story

As a DIC stakeholder, I need a way to easily generate and share updated rates
So that I can get my needed updates implemented on VA.gov

## Issue description

The researched-and-ready approach we have chosen:

The Public Websites team will structure and share spreadsheets (Excel) to our stakeholders, who will fill out the spreadsheets with their content
The Public Websites team will identify all the VBA stakeholder groups who will use, or may use in the future, spreadsheets to capture table data for Drupal upload onto VA.gov
When the spreadsheets are sent back to the PW team, we will turn the spreadsheets into CSVs and the 'import' into Drupal for the appropriate rate table

## Tasks

- [ ] Internal review of DIC rates spreadsheet(s)
- [ ]  Finalize structure/layout of rates table spreadsheet(s)
- [ ]  Develop talking points, education strategy for when we present to stakeholders (this may be very lightweight, but will help in making sure we provide consistent material)
Note: we are planning to schedule time with stakeholders in a series of meetings, vs one big meeting
- [ ]  Stretch goal: schedule the first group of stakeholders' meeting - done 5/28 with approval from Angie (Alfreda) Smith et al.

## Acceptance criteria
- [ ] Stakeholder meeting completed and next steps determined

Related to: #9385

**Comment by AnneHurley** [comment]
[DIC rates tables template]
(https://app.zenhub.com/files/133843125/7ea83815-1eeb-4036-bc28-4d5bbbfab64f/download)
@bethpotts @stephorkandatx  FYSA

**Comment by stephorkandatx** [comment]
Next steps for this work:

Stakeholder meeting scheduled for 06/05/2020. 

When that takes place, recommendations & next steps to be written up and built out in a new ticket.

**Comment by AnneHurley** [comment]
[DIC rates spreadsheet template]
(https://app.zenhub.com/files/133843125/1c9d096b-b675-42b3-8448-e3f5404b5b81/download)
Presented with @bethpottsVADEPO 6/5 to Angie Smith and Kelly Wante. Next steps are stakeholders to present/evangelize to rest of their team.
@stephorkandatx  FYSA

**Comment by AnneHurley** [comment]
Followup email sent to Angie Smith and Kelly Wante to get remaining feedback. FYSA @stephorkandatx  @bethpottsVADEPO @jenniferlee-dsva

**Comment by AnneHurley** [comment]
Blocked until we hear back from Kelly and Angie. 6/21

**Comment by AnneHurley** [comment]
6/23 - Kelly Wante and team have approved this first spreadsheet. New tickets will cover the other DIC rates tables and Pension, which also are managed by Angie and Kelly.
