### ISSUE TITLE
[CST] Update language on Files tab to remove "see"

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#96776]
## Background Context

We need to remove "sighted language" for the line: "You can also see the files associated with this claim."

<img width="1668" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0tuQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdcb263ccb98d06e006380b7b24cb3ee96da2e03/Screenshot%202024-11-08%20at%209.52.01%E2%80%AFAM.png" alt="Screenshot 2024-11-08 at 9.52.01 AM.png" />

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/0cae1ca9-3f7f-4a07-8a35-4d3a44e1d042" />

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
Old: "If you need to add evidence, you can do that here. You can also see the files associated with this claim."
New: "If you need to add evidence, you can do that here. You can also review the files associated with this claim."

This string shows up in the [Files tab](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST-V2?node-id=14-5398&t=hLZz78gxzp8wC6OQ-4).

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Update string of text as defined above in Design section_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _String is updated_
- [ ] _[CST V2](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST-V2?node-id=0-1&node-type=canvas&t=hLZz78gxzp8wC6OQ-0) is updated with new design_
