### ISSUE TITLE
Update CC kickoff Slack workflow to remove "recommended"

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96786]
## User Story
As a VFS team member, I want to have clear guidance on what touchpoints are required vs. optional so that I can make appropriate decisions for my team and our product.

Assignee: @briandeconinck 
Peer Reviewer: @KKitagawa-Bosch 

## Description
We no longer refer to the Collaboration Cycle touchpoints in the CC Request ticket as "recommended touchpoints" since many of them are required. However, our language in out Slack workflow for CC Kickoff still says, "Your Collaboration Cycle Request ticket has been updated with recommended touchpoints..."

The purpose of this ticket is to modify the language in the Slack workflow for Collab Cycle kickoff to remove "recommended"

### Live pages
- 

### Drafted pages
- 

## Tasks
- [x] Edit the language in the workflow to remove "recommended"

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The message sent to VFS teams in the kickoff workflow no longer says "recommended" touchpoints

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
CC Kickoff message to VFS teams no longer says "recommended," now says "appropriate." Can be validated in the Automations section of Slack (edit the CC Kickoff workflow), but here's a screenshot too:

![CC Kickoff workflow message that reads "Your Collaboration Cycle Request ticket has been updated with appropriate touchpoints and your kickoff is complete."](https://github.com/user-attachments/assets/8271ca62-eec4-4e35-bef2-8fa2dccd7f50)

@KKitagawa-Bosch this is ready for review!

**Comment by KKitagawa-Bosch** [comment]
Looks good to me!

**Comment by briandeconinck** [comment]
Closing as complete!
