### ISSUE TITLE
[DESIGN] Change appointment details page content to reflect updated mileage-only travel policy

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#96784]
## Background

The policy has changed around which appointments are eligible for mileage-only travel reimbursement. We need to evaluate and change some content in our designs to reflect the updated policy.

[Slack thread](https://dsva.slack.com/archives/C05Q9HH47PS/p1730997002214649?thread_ts=1730826770.711339&cid=C05Q9HH47PS)

> According to policy the user must have the ability to submit a claim for every appointment, even if it’s the same day at the same facility, so we are building our appt > claim association logic to follow that policy.

> Due to that policy we are emphasizing the simple in simple mileage-only travel reimbursement claim submission (SMOC) by approaching it as…
> Have you submitted for this specific appointment (show status link) or have you not (show submit link)?

## Tasks

- [x] Evaluate content in our Appointment detail page designs and update accordingly
- [ ] Review with Laura W.
- [ ] Share in thread above to review with UX working on travel + Micah T. and John W.

## AC

- [x] Content updated
- [ ] Content reviewed with Laura W.
- [ ] Content reviewed with UX working on travel + Micah T. and John W.

**Comment by cgednalske** [comment]
@loripusey due to a update in the policy, we'll need to change some of our content for the past appointments travel work - nothing huge. We should do this next sprint as well - I can take a look at the goals/board today since we've had some new things pop up. 

But, separately, we also might want to talk through if this implies a change for Check-in + travel and LoROTA standalone travel as well.

**Comment by StevenStraily** [comment]
This would be a 3 for me too.
Reasoning: I see multiple external reviewers/dependencies here.

**Comment by zach-park** [comment]
I would like to vote 3 to be safe.

**Comment by cgednalske** [comment]
@loripusey I switched this to this sprint and the breadcrumb ticket to next sprint. This one is also more important than the breadcrumb one so we're not blocking any travel work.

**Comment by cgednalske** [comment]
Based on our pointing discussion, proposing this is a 2‍⃣

**Comment by cgednalske** [comment]
@wullaski there are only a few changes as far as the content to match the updated policy. 

Wherever we have "You've already filed a claim for this facility and date" we're changing it to "You've already filed a claim for this appointment."

Here are the two specific scenarios that changed in our designs (I've linked to the Responsive Appt. detail page specs, but it's also updated in the Appt detail page designs - not sure which one you're working from)
[Appt details / in person / within 30 days / filed](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2569-1364&t=DDH6ZozhML3iNqWu-1)
[Appt details / in person / past 30 days / filed](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2569-1416&t=DDH6ZozhML3iNqWu-1)

**Comment by cgednalske** [comment]
@zach-park do you want to validate this from my ticket above / make sure I didn't miss anywhere where this language needed to change?

**Comment by zach-park** [comment]
Looks great. Thank you!

**Comment by cgednalske** [comment]
@zach-park thank you! Closing this out.
