### ISSUE TITLE
[DD] Build prototypes based off figma mockups

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#96797]
We need a digital dispute prototype for to conduct a research study to ensure the usability of digital dispute form. 

## Issue Description
Given: A veteran has a debt that they think they have an error with
When: A veteran wants to submit a dispute digitalla
Then: A veteran should be able to submit a digital dispute              

## Tasks
- [x] Create a prototype based off the [Figma mocks](https://www.figma.com/design/D8tfoPhUZlqBUomMTxzkQb/Dispute-Form-(VHA-VBA)?node-id=152-4620&node-type=section&t=A0JKkrLgYdUFwBBL-11) using codesandbox.io 

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] [Prototype](https://zyc78g.csb.app/) has been created based off the screens in our Fimga mocks

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by josephrlee** [comment]
Marking this as complete for now! I will make a follow-up ticket for changes after the midpoint review!

Here's a link to the sandbox: https://codesandbox.io/p/sandbox/dispute-your-debt-zyc78g
