### ISSUE TITLE
Pull Usage Metrics in GA4 for Jeff

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#96807]
### Description
We met with Jeff Keane on 8 Nov 2024. He was interested in knowing what kinds of performance metrics we could see on VA.gov in GA4. The best thing we are likely able to provide him for now, is data on site usage -- which areas of the site have the most traffic, to serve as a good starting point for looking into more technical metrics.

---

### Tasks

- [x] Build report to share with Jeff that has usage data on most popular pages
- [x] If possible, include technical dimensions
- [x] Send report to Jeff

### Acceptance Criteria

- [ ] Report has been build, and sent to Jeff

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc  I'm going with filtered GUI reports. I'm hoping Jeff will explore a bit on his own so he can see what's available and useful for him so we have a better idea of requirements for the next version (DOMO?).

[Top VA.gov Pages](https://analytics.google.com/analytics/web/#/p419143770/reports/explorer?params=_u..nav%3Dmaui%26_r..dataFilters%3D%5B%7B%22type%22:1,%22fieldName%22:%22hostname%22,%22evaluationType%22:1,%22expressionList%22:%5B%22www.va.gov%22%5D,%22complement%22:false,%22isCaseSensitive%22:true,%22expression%22:%22%22%7D%5D&r=all-pages-and-screens&ruid=D4F7103F-DEA1-4A09-B066-EE554BF6F5F0&collectionId=8429185582)

[Tech Details](https://analytics.google.com/analytics/web/#/p419143770/reports/explorer?params=_u..nav%3Dmaui%26_r..dataFilters%3D%5B%7B%22type%22:1,%22fieldName%22:%22hostname%22,%22evaluationType%22:1,%22expressionList%22:%5B%22www.va.gov%22%5D,%22complement%22:false,%22isCaseSensitive%22:true,%22expression%22:%22%22%7D%5D&r=user-technology-detail&ruid=user-technology-detail,user,technology&collectionId=user) 
Drop-down includes: 

- Browser
- Device category
- Device model
- Screen resolution
- App version (n/a - mobile app only)
- Platform (n/a - mobile app only)
- OS version
- Platform / device category
- Operating system
- OS with version

[Demographic details (location information)](https://analytics.google.com/analytics/web/#/p419143770/reports/explorer?params=_u..nav%3Dmaui%26_r..dataFilters%3D%5B%7B%22type%22:1,%22fieldName%22:%22hostname%22,%22evaluationType%22:1,%22expressionList%22:%5B%22www.va.gov%22%5D,%22complement%22:false,%22isCaseSensitive%22:true,%22expression%22:%22%22%7D%5D&r=user-demographics-detail&ruid=user-demographics-detail,user,demographics&collectionId=user)
Drop-down includes: 

- Country
- Region
- City

If you need to re-add the Hostname filter:
![Image](https://github.com/user-attachments/assets/e25865a9-78e4-47c4-acb6-1e8b0fe28366)

Where to change the date and dimensions:
 ![Image](https://github.com/user-attachments/assets/db19e37c-696e-4364-a2c7-19d41dc8ce4a)

You can find definition for most GA4 dimensions and metrics here - https://ga-dev-tools.google/ga4/dimensions-metrics-explorer/. You can also ask -- I'm always happy to help. 

We'd also talked about timing attached to some of the `api_call` events. The label is "API Latency MS" and it's in the third tab of the [API Call Events [A&I]](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/YChsGPp1SnO7q4qTFhOqRg) Explore report.
