### ISSUE TITLE
BE | Profile | Military Service History | Fix user reference for academy attendance feature flag

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#96864]
## Summary
When retrieving military history records for a veteran, there is a conditional check in place that uses the `profile_show_military_academy_attendance` feature flag to determine whether to display academy attendance records.

The code checks the flag using the @current_user on [line](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/va_profile/military_personnel/service.rb#L34) in the VAProfile::MilitaryPersonnel::Service.  The @current_user is returning `nil`.  It should be changed from `@current_user` to `@user`.

## Tasks
- [ ] Determine if this code should be removed along with the feature flag.
- [ ] Either remove logic or change `@current_user` to `@user`.

## Acceptance Criteria
- [ ] Code is removed or fixed.

**Comment by ACParker89** [comment]
@tpharrison do we need an epic for this or do you see it looped into a past effort?

**Comment by tpharrison** [comment]
@ACParker89 There might be an old epic out there, but I'm not sure what it is.  I don't think it needs one.
