### ISSUE TITLE
Discovery - Investigate Cross App Imports to Ensure Compliance (DUE 2/3/2025)

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#96879]
## Description

Noticed the following warning in Aaron's latest pr. Per convo with Andrew creating ticket for discovery to make sure we're all square!

*WARNING* This PR contains changes related to an application that is currently not isolated. As of Feb 3, 2025 deployment may no longer be possible for apps that are not isolated. Please isolate this app from other directories in 'src/applications' to prevent future deployment issues. More information on your app's status can be seen here: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/cross-app-import-report Please reach out to Frontend Platform Support with any questions.

PR: https://github.com/department-of-veterans-affairs/vets-website/pull/32955/files?diff=split&w=1

## Tasks
- [ ] Confirm / remove cross app imports to align with Platform requirements

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ X ] Not Required

## Acceptance criteria
- [ ] Item one from the description performs as described in the description
- [ ] Item two from the description performs as described in the description

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

**Comment by OptionSelect** [comment]
Investigated FSR and found that it is the WIZARD_STATUS_COMPLETE const that we are using. Next steps is to replace/remove from application prior to 2/3/2025.

<img width="1323" alt="Image" src="https://github.com/user-attachments/assets/5d7f8dc4-3920-4f23-b090-d5ce761cdbc5" />
