### ISSUE TITLE
Net Worth | Automate annual net worth limit update

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#96876]
## Issue Description

Note: This work is on hold until [the API can be implemented](https://github.com/department-of-veterans-affairs/va.gov-team/issues/113516).

_Each year, the net worth limit listed in the 686/674 form flow changes. The updated limit is usually announced in early November and needs to be implemented by Nov 30 (see #96647). There may be a way to automate updating the net worth amount by leveraging the value passed by an existing API (see comment in [#76465](https://github.com/department-of-veterans-affairs/va.gov-team/issues/111237#issuecomment-3109232668))._

<img width="575" height="178" alt="Image" src="https://github.com/user-attachments/assets/af28a36a-c2be-4fa2-b152-3246c494c992" />

---
## Tasks
- [x] Determine if the existing award API could be used to automatically update the net worth limit in the 686/674 form flow -- it appears we can leverage the API to pull in the net worth limit based on Matt's research [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/111237#issuecomment-3109232668).
   - [x] How is the net worth number provided in the API updated? (Is it actively maintained?) 
- [ ] Integrate value from API into net worth question in the 686/674 form flow

## Acceptance Criteria
- [ ] The net worth limit in the 686/674 form flow is automatically updated with the new limit by 11/30 each year
- [ ] Outstanding questions are answered and documented in ticket
---

**Comment by mjknight50** [comment]
This API is a REST API:
vets-api/lib/bid/awards/service.rb

And returns this:

{
  "awardsPension": {
    "veteranId": 32436649,
    "isEligibleForPension": true,
    "isInReceiptOfPension": true,
    "netWorthLimit": 150538
  }
}
