### ISSUE TITLE
SC | Update confirmation page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#96883]
## Value Statement

**_As a_** Veteran
**_I want to_** see the data I entered on the confirmation page
**_So that_** I can print it out and maintain a record of the submission

---

## Background Context

We'll soon be implementing a change to our Board Appeal form (#94268) to show submitted data on the confirmation page. Soon after, we will need to update our Supplemental Claim from confirmation page

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] Update confirmation page to show submitted data
- [ ] Unit tests & E2E tests added and all passing
- [ ] Maintain 90+% code coverage
- [ ] Flow tested in staging

## Designs and Build Notes

- [Figma](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=2506-37167&node-type=section&t=qJmDDyOOMEDtjyLv-11)

## Open questions

- Add here

## Tasks

- [ ] Update confirmation page to show submitted data
- [ ] Add/update unit tests
- [ ] Add/update E2E tests
- [ ] Add/update mock data

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@eileen-coforma to provide design

**Comment by eileen-coforma** [comment]
Design hinges on how we want to handle 4142 in the accessible copy of submission. Eileen to reach out to 526 team to see how they're handling it.

**Comment by eileen-coforma** [comment]
Working on unit tests. 

Still needs design from @eileen-coforma for 4142 section.

**Comment by Mottie** [comment]
Changes are now available in staging for validation.

**Comment by eileen-coforma** [comment]
Picking this up to update based on new format

**Comment by Mottie** [comment]
Going to work on this _after_ I get the post-research changes done.

**Comment by Mottie** [comment]
Changes are now available for validation in staging

**Comment by eileen-coforma** [comment]
<img width="547" alt="Image" src="https://github.com/user-attachments/assets/81df2348-4270-42ac-9843-6d99ea1cc822" />

@Mottie two things:
1. The question shouldn't be bolded. It's not matching the style of the rest of the sections.
2. Can we display the full address entered for the non-VA medical facilities? They entered that information, so we should return that information to them.

**Comment by comaurice** [comment]
Still in progress, PR to be opened soon

**Comment by comaurice** [comment]
Ready for validation now

**Comment by kayline** [comment]
@comaurice will validate today

**Comment by comaurice** [comment]
<img width="831" alt="Image" src="https://github.com/user-attachments/assets/41221147-53ef-4286-9268-c31db5ce04f6" />

Validated. All good @Mottie
