### ISSUE TITLE
UX | Design "Medical treatments" L&L pattern to used by FBEUI

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#96904]
## Description
This ticket is to be used by the designers working on the Form Builder Editorial UI. Design the necessary screens required to enable use of the Medical Treatments List and loop Step and pattern so that it can be selected to be included in a form conversion

## Tasks 
- [ ] Wireframe out initial screens and options 
- [ ] Share either wireframes or prototypes as necessary to get necessary feedback and input from team/stakeholders
- [ ] Align with team's feasibility 
- [ ] Update Pattern matrix to include learnings and visual information

## Acceptance Criteria
- [ ] Feedback collected (link: view notes here)
- [ ] Feedback implemented in (link: Figma file)
- [ ] Team has reviewed and discussed item (link: recording)
- [ ] Item added to (link: Pattern matrix)

**Comment by Karak888** [comment]
Not using this as individual patterns, moved to flexible custom list and loop so this is no longer necessary.  Will not build specific steps.  Moving to close.
