### ISSUE TITLE
UX | Design "Comments" Pattern to be used by FBEUI

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#96903]
## Description
This ticket is to be used by the designers working on the Form Builder Editorial UI. Design the necessary screens required to enable use of the Comments Step and pattern so that it can be selected to be included in a form conversion. The first form to consume this step will be 21-8940-ARE.

## Tasks 
- [x] Wireframe out initial screens and options 
- [x] Share either wireframes or prototypes as necessary to get necessary feedback and input from team/stakeholders
- [ ] Align with team's feasibility 
- [ ] Update Pattern matrix to include learnings and visual information

## Acceptance Criteria
- [ ] Feedback collected (link: view notes here)
- [ ] Feedback implemented in (link: Figma file)
- [ ] Team has reviewed and discussed item (link: recording)
- [ ] Item added to (link: Pattern matrix)

**Comment by danielleoppendike** [comment]
As per discussion with Kara/Danielle/Brian on 1/6
- An input field for "Additional Comments" will be available/option at the end of each form for the user to enter in as they wish
- Follow input field free form component from VADS
- Build this first, then revisit pattern for other "steps that may need a common field" in the future.
- This is foundational for what it looks like to add a comment to a step within the form.
