### ISSUE TITLE
[DD] Create Digital Dispute feature toggle

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#96916]
## Issue Description
Create feature flag to manage Digital Dispute application visibility/functionality. 

- Platform [Feature Toggles Guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide)

## Tasks
- [x] `vets-website` PR merged
- [x] `vets-api` PR merged

## Design and Front End sync on implementation of design
- [ ] Required
- [x] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] Digital Dispute feature toggle created

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by OptionSelect** [comment]
FE PR: https://github.com/department-of-veterans-affairs/vets-website/pull/33154
BE PR: https://github.com/department-of-veterans-affairs/vets-api/pull/19546
