### ISSUE TITLE
Copy of [DD] Create Digital Dispute feature toggle

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#96917]
## Issue Description
Create feature flag to manage Digital Dispute application visibility/functionality. 

- Platform [Feature Toggles Guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide)

## Tasks
- [ ] `vets-website` PR merged
- [ ] `vets-api` PR merged

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Digital Dispute feature toggle created

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by Dr-Pongo** [comment]
- Blocked by main app not being merged
#97002

**Comment by Dr-Pongo** [comment]
Shifting to has dependency, so we can fill in some more gaps in pages

**Comment by Dr-Pongo** [comment]
Let's finish all of the FE pages and get approval from design before we start writing tests on display/functionality that can change

**Comment by Dr-Pongo** [comment]
- I'm stealing this ticket and also using it as a follow on to fix the cypress/pdf issues we were having from:
department-of-veterans-affairs/va.gov-team/issues/110744
