### ISSUE TITLE
Design/UX Knowledge Pick-Up - SSO/Login: VA.gov Health Pages

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9693]
## Issue Description
Background: this is not a 'start from scratch' discovery. This is a pick-up item so that we own the knowledge, and looking forward to potential scalability.
This has been through many design reviews, we do not anticipate changing the designs unless there is a clear scenario that needs to be addressed. We do need to do a knowledge transfer, look at what's been created, and begin to think about potential updates for scalability purposes in the future.

Investigation/Knowledge into the work done to date for the SSO/Login: VA.gov Health Pages to create new patterns, alert boxes for unauthenticated and authenticated experiences. 

These are updates to alert boxes, static content on VA.gov health pages (prescription, test results, messaging, etc.) to direct users who are patients at Cerner facilities to the right place.

Users who are marked on the backend as being patients at a facility that will start using Cerner for health tools, will start seeing the new pattern.

The UX that has been created is considered 'complete', with the caveat that there may be some complexities to manage in the future. 

The goal of this ticket is to have PW Design/UX/Research review the work that has completed to date, to:
- Become our design 'go to' as we have questions during development (as best we can)
- Review for needed/desired changes, updates
- Begin to plan for updates or additional research or design activities, artifacts needed to account for scalability

The output of this ticket will be an understanding of the design work done to date, and the decision if we need to make accommodations to the designs for this first phase of work.

---
## Tasks
- [x] Review supporting documentation, design elements
- [x] Generate list of questions/concerns
- [x] Review with the SSO/Login team POC (Bridget Hapner)

## Acceptance Criteria
- [x] Design knowledge shared
- [x] Recommendations documented, if any

---
## Documentation
- [Desktop Invision](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/409123884_Unauthenticated_Pages) 
- [Mobile Invision](https://adhoc.invisionapp.com/share/5QWAJJQNG2J#/409260607_M-Authenticated_Pages_-_Alerts) 
- [High level site map for MHV + Cerner patient](https://adhoc.invisionapp.com/share/VMW6WMI9NDU#/screens/407257731_No_Notifications_High_Level_Site_Maps_For_A_MHV_-_Cerner_Patient)

** A few notes: 
The mobile design uses the Contextual Warning Alert from the pattern library as-is, except for: 
a) transitioning the exclamation-triangle to above the headline and 
b) narrowing padding-right to 32px, narrowing padding-left to 24px. Padding-top and padding-bottom remains the same

"Bridget worked with Crystabel + Emily on VSP to make these changes to the alert box element for mobile. When we last talked in March we did not decide if those changes would be one-off for this work or be added into the design library. So that might be some UX work to coordinate with them.
Bridget only made 1 wireframe for mobile to pressure test how the more crowded alert box might work, which hopefully is okay. "

Usability testing summary: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/ux-research/alerts/research-summary.md

Usability discussion guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/ux-research/alerts/discussion-guide.md

Product Outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/sso

Handoff document: https://docs.google.com/document/d/11OGKfLk0fKd08pqCKT0Wvrt9ze2vZW_PSEn2kJdK714/edit#

---
## Complexities or points of consideration

* There may be some complexity to manage in the future when new Cerner facilities roll out (ex: what happens if a user is a patient at multiple facilities - how would that impact the alert box?)

**Comment by andaleliz** [comment]
@stephorkandatx question about the AC on this 
> design knowledge shared

Is this something that I should present to the team, and if so, who? I can set up some time next week.

Or did you just mean creating a doc and sharing the link?

**Comment by andaleliz** [comment]
@stephorkandatx  [Here's the write-up I put together](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Cerner-Support/design-ux-knowledge-transfer.md), which includes recommendations.  The biggest concern I have is that there hasn't been a formal accessibility review, and some concerns came up in a quick consult with Jen. I've captured everything in the doc.

I know the SSO/Login team thoughtfully and carefully came up with these solutions, and tested with users, so I am comfortable proceeding largely as-is. I do think it would be worthwhile exploring changes we can make to the very lengthy headers, at a minimum, and reviewing the copy carefully to ensure the button labels and copy set clear expectations about what will happen when a button is clicked.  

Going to close this out as I think any next steps would fall under a design/brainstorm/solution ticket instead of strict knowledge transfer.
