### ISSUE TITLE
Write guidance for using test accounts for conducting usability testing in staging

### ISSUE THREAD

**Issue by naomimarcussen** [department-of-veterans-affairs/va.gov-team#96939]
### User Story
As a VFS researcher, I want to know the recommended way to find a test account and security protocols for handling passwords, so that I can conduct usability testing in staging with assistive tech users.

- Intended Audience: VFS researchers
- Desired Outcome: Assure VFS researchers that Perigean is taking steps to reduce no-shows.

### Description
A VFS team member left the following feedback in the 2024 Q3 Quarterly Satisfaction Survey:

[What would make the experience of conducting research easier for you? What is missing?]
"A clear understanding of how to test (specifically accessibility testing)...Some folks have directions on how to leverage test users with live veterans in the staging environment.  Security team says that is not ok."
--VFS Product Manager

### Tasks
- [ ]  Draft guidance on Using testing accounts in staging for usability testing with assistive tech users
- [ ] Test the usefulness of the instructions with a VFS researcher

### Peer Review
- [ ]  Have Shane Strassberg review and validate that the user story and Acceptance Criteria are met

### Acceptance Criteria
- [ ]  Draft of [Using test accounts for testing in staging](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3370713089/DRAFT+Using+test+accounts+for+testing+in+staging)
- [ ]  Updates have been Peer Reviewed by Shane Strassberg
- [ ]  User Story need has been fulfilled
- [ ]  Change has been communicated on the #research-ops slack channel

**Comment by naomimarcussen** [comment]
@sstrassberg provided feedback in the [draft Confluence doc](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3370713089/Using+test+accounts+for+usability+testing+in+staging).

**Comment by naomimarcussen** [comment]
I've incorporated Shane's feedback and moved it to be published in the next push live (next Monday 11/25).
