### ISSUE TITLE
[Frontend] Update 'Additional info' components on both the 'Select hearing aid batteries' (C2P1) and 'Select hearing aid accessories (C2P2)

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#9695]
## Issue Description
_During usability testing, we found that Veterans were able to easily find the additional information component that housed information about what to do if they don't see their device or accessory, but they told us that the information housed within wasn't entirely sufficient._

The content has been updated in the 'additional info' components on both the ['Select hearing aid batteries'](https://vsateams.invisionapp.com/share/KWX53U12MGX) (C2P1) and ['Select hearing aid accessories'](https://vsateams.invisionapp.com/share/9GXIP1XDUSF) (C2P2) screens.

The content can also be copied from the corresponding GH documentation: ['Select hearing aid batteries'](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-battery-selection.md) | ['Select hearing aid accessories'](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-accessory-selection.md)

Please reach out to the design team with any questions!

---
## Tasks
- [ ] _Update the content on both the batteries and accessories screens based on the provided InVision links and/or the GH documentation_
- [ ] _Confirm the UI updates with the design team_

## Acceptance Criteria
- [ ] _The 'Additional info' component on both the batteries and accessories screens has been updated with the provided content_
---
