### ISSUE TITLE
Discharge upgrade wizard: Phase 1 DADT review

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#96954]
## Description
The DOD upgraded the discharge status of Veterans who received a less than honorable discharge due to Don’t Ask, Don’t Tell (DADT). We need to update the results screen for Veterans who request an updated DD214.

## Resources
- [Content source of truth](https://dvagov.sharepoint.com/:w:/r/sites/SitewideCAIA/Shared%20Documents/2.0%20Product%20work/Discharge%20upgrade%20wizard/Discharge%20upgrade%20wizard%20phase%201%20content%20updates.docx?d=w0b608d3f1895426e847c7b49194a627f&csf=1&web=1&e=4bWL3A) (SharePoint)
- [Public website ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19783) (GitHub)--this includes additional context

## Tasks
- [x] ML: Draft recommendations with support from AP
- [x] ML: Share recommendations with product team
- [x] ML: Finalize recommendations with product team

## Criteria
- [x] Content recommendations have been shared and finalized with the product team

**Comment by hermonica** [comment]
Hi @aprocik1! My recommendations are in [Discharge upgrade wizard phase 1 content](https://docs.google.com/document/d/1e6agkqxcFxT-dIqfk_5FziOEAjMASV5sakzeUxkO7yI/edit?tab=t.0#heading=h.bbsrplqhy1m) (Google Doc).

I used the same Google Doc with our recommendations for the results screen review so all new Phase 1 requests are in the same content source of truth. 

Also, I had a lot of questions for the product team about their logic because the user flow for this user group seems confusing. Lmk what you think before we share our recs and questions with Fran.

Thanks, and looking forward to your feedback!

**Comment by aprocik1** [comment]
@hermonica, thanks for drafting these recommendations. I share in your confusion about the logic. I don't think we need to update any of the questions. I think we only need to update the results screen, since question 3 already accounts for this use case.

Let me know if you have any questions about my comments or suggested edits.

**Comment by hermonica** [comment]
@aprocik1, thanks for your sound edits! I'll update Fran in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74787?issue=department-of-veterans-affairs%7Cva.gov-cms%7C19783) with our questions about the logic.

**Comment by hermonica** [comment]
Hi @aprocik1! Fran got back to us about the logic in question. 

She clarified that they're adding a new response to question 5b "because it would be the least recoding in logic and answers, and also because Veterans can receive DD215s for many reasons, not just because of the automatic review and upgrade for DADT." 

Fran also recommended exporting our content source of truth from Google Doc to SharePoint for easier access. So I've done that. 

Here are 2 small edits for your review (links to specific sections in the SharePoint doc):
- [New response to 5b](https://dvagov.sharepoint.com/:w:/r/sites/SitewideCAIA/Shared%20Documents/2.0%20Product%20work/Discharge%20upgrade%20wizard/Discharge%20upgrade%20wizard%20phase%201%20content%20updates.docx?d=w0b608d3f1895426e847c7b49194a627f&csf=1&web=1&e=PZufYb&nav=eyJjIjoxNDg2MTY1MzcxfQ)
- [Updated intro sentence to results screen](https://dvagov.sharepoint.com/:w:/r/sites/SitewideCAIA/Shared%20Documents/2.0%20Product%20work/Discharge%20upgrade%20wizard/Discharge%20upgrade%20wizard%20phase%201%20content%20updates.docx?d=w0b608d3f1895426e847c7b49194a627f&csf=1&web=1&e=yePGil&nav=eyJjIjo5ODQ3NDg4NTB9)

Would love your feedback. Thanks!

**Comment by aprocik1** [comment]
@hermonica, thanks for clarifying this with Fran. I think your new response to 5b works well. I think you should go with your alt option for the updated results screen:

> Because you received a discharge upgrade from the DOD due to the Don’t Ask, Don’t Tell policy, you can request an updated DD214 that shows your ~~discharge~~ upgrade.

I like that your alt option uses the same language as your new response to 5b. I think that clarity helps. One edit: I don't think you need to repeat the work "discharge" in front of "upgrade," since you've already used that phrase in the sentence.

**Comment by hermonica** [comment]
@aprocik1, appreciate your feedback and agree with your edits! I've shared our updated recs with Fran in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19783#issuecomment-2489201241).

**Comment by aprocik1** [comment]
The product team is launching phase 1 updates to the discharge upgrade wizard on Monday 12/16. Fran confirmed that we can close this ticket as complete.
