### ISSUE TITLE
Update Spanish and Tagalog pages with new COVID content

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#96955]
> [!WARNING]
> Do not use this ticket unless directed to do so by the CAIA team.

## Issue description
We made changes to the English COVID page. We need to get this content translated into Spanish and Tagalog and update those pages in Drupal. Once we add the content to the pages we need to remove the alerts we put up saying to check the English page for most recent information.
---
## Tasks
_What work is necessary for this ticket to be completed? Examples:_
- [x] Send content to translators (Randi)
- [x] Update Spanish page and remove alert (Victoria)
- [x] Review and publish Spanish page (Sara)
- [x] Update Tagalog page and remove alert (Victoria)
- [x] Review and publish Tagalog page (Sara)

## Acceptance Criteria
_What will be created or happen as a result of this story? Examples:_
- [x] Updated Spanish content is live on the site
- [x] Updated Tagalog content is live on the site

## Configure this issue
- [ ] _Attach to an Epic or Intake if this is related to other work_
- [ ] _Label with Originator/Team (product team or stakeholder requesting support)_
- [ ] _Label with Open Date_
- [ ] _Label with Estimate (level of effort expected for this ticket)_
- [ ] _Add assignee name to each task they will complete (if known)_
- [ ] _Update the status to reflect where this work is in the pipeline (in progress, backlog, etc.)_

**Comment by RLHecht** [comment]
@moviedosoco Here is the Spanish content back from translation. This is ready to be put on our main vaccines page. Thank you![25754_Covid-19vaccinecontent11.7_Spanish-CTO.pdf](https://github.com/user-attachments/files/17733716/25754_Covid-19vaccinecontent11.7_Spanish-CTO.pdf)

**Comment by moviedosoco** [comment]
@RLHecht Got it, Randi. I'm on it.

**Comment by moviedosoco** [comment]
Hi @saratorres2, the updated content in the **Spanish** page is ready to be reviewed and published. Thank you.

Preview: http://preview-prod.vfs.va.gov/preview?nodeId=16359
Node: https://prod.cms.va.gov/node/16359/latest

**Comment by saratorres2** [comment]
@moviedosoco Confirming that changes are now live!

**Comment by RLHecht** [comment]
@moviedosoco Here's the tagalog content back from the translators. Could you please update the page in Drupal? Thanks!

[25755_Covid-19vaccinecontent11.7_Tagalog-CTO.pdf](https://github.com/user-attachments/files/17779244/25755_Covid-19vaccinecontent11.7_Tagalog-CTO.pdf)

**Comment by moviedosoco** [comment]
@RLHecht Sure, the page in Tagalog is updated in Drupal.

@saratorres2 Could you please review it and publish?  Thank you.
Preview: http://preview-prod.vfs.va.gov/preview?nodeId=16413
Node: https://prod.cms.va.gov/node/16413/latest

**Comment by saratorres2** [comment]
@moviedosoco Tagalog page is published and live!

**Comment by moviedosoco** [comment]
@saratorres2 Thank you Sara!

**Comment by saratorres2** [comment]
Work complete on this ticket.
