### ISSUE TITLE
[FSR] Bug - Follow up employment work dates

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#96959]
## Issue Description
We can try to coordinate this ticket with the release of the November report. 

Follow up on the reported bug of employment work dates not accepting valid entries:
- department-of-veterans-affairs/va.gov-team/issues/96545
- department-of-veterans-affairs/vets-website/pull/32937

We included a change to the error messaging to clear the message onChange instead of onBlur to hopefully help make it clear the changes are taking effect. 

## Tasks
- [x] Check Medallia feedback to see if issue is persisting
- [x] Reinvestigate but, and maybe include some error logging to help 

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Employment date error is resolved

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by OptionSelect** [comment]
Per Devi this ticket is for replication of issue, now that it has been proven to happen closing ticket out and moving work to a new one.
