### ISSUE TITLE
UX | Design for how a user knows, or indicates, a conversion is ready to submit to staging review

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#96968]
## Description
This design issue is to create the UX (and Editorial UI Screens) needed to allow a user to indicate a conversion is ready to be submitted for staging review.

## Tasks 
- [ ] Wireframe out initial screens and options 
- [ ] Share either wireframes or prototypes as necessary to get necessary feedback and input from team/stakeholders
- [ ] Align with team's feasibility 

## Acceptance Criteria
- [ ] Feedback collected (link: view notes here)
- [ ] Feedback implemented in (link: Figma file)
- [ ] Team has reviewed and discussed item (link: recording)
- [ ] Item added to (link: Pattern matrix)

**Comment by Karak888** [comment]
moving to close this ticket as it is no longer relevant and handled elsewhere.
