### ISSUE TITLE
Engineering Knowledge Pick-Up - SSO/Login: VA.gov Health Pages

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9696]
## Issue Description
Knowledge pick-up into the work done to date for the SSO/Login: VA.gov Health Pages to create new patterns, alert boxes for unauthenticated and authenticated experiences. 

These are updates to alert boxes, static content on VA.gov health pages (prescription, test results, messaging, etc.) to direct users who are patients at Cerner facilities to the right place.

Users who are marked on the backend as being patients at a facility that will start using Cerner for health tools, will start seeing the new pattern.

The goal of this ticket is to have Engineering review the documentation and  work that has completed to date, to:
- Generate engineering path forward
- Generate outstanding questions for team that originated the request and work
- Knowledge share so that we may support this initiative going forward 

The output of this ticket will be an understanding of the work done to date, a path for PW engineering team to develop and support this initiative, and become the engineering 'experts'

---
## Tasks
- [ ] Review supporting documentation
- [ ] Generate list of questions/concerns
- [ ] Review with the SSO/Login team POC (Dan Hinze)

## Acceptance Criteria
- [ ] Engineering knowledge shared
- [ ] Recommendations documented, if any
- [ ] Defined next steps for engineering path

---
## Documentation
Desktop Invision: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/409123884_Unauthenticated_Pages

Mobile Invision: https://adhoc.invisionapp.com/share/5QWAJJQNG2J#/409260607_M-Authenticated_Pages_-_Alerts

Product Outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/sso

Handoff document: https://docs.google.com/document/d/11OGKfLk0fKd08pqCKT0Wvrt9ze2vZW_PSEn2kJdK714/edit#

Dan has a github branch in progress to review with us.

---
## Complexities or points of consideration

* There may be some complexity to manage in the future when new Cerner facilities roll out (ex: what happens if a user is a patient at multiple facilities - how would that impact the alert box?)

**Comment by kelsonic** [comment]
Had a great chat with @ncksllvn and Dan, main takeaway is that these pages will not be sourcing their content from Drupal but instead from `vets-website`: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/409123884_Unauthenticated_Pages

This means that in the future when there are requests to change content on those pages a developer will need to do it (shouldn't take too long to fulfill those requests though).

Those pages are currently just a React app and as you navigate between pages the routes do not change. We could consider adding client-side routing (via react-router) if it's desirable for those separate pages to have their own URLs.

It's not completely clear to me how we will derive if the user is logged in or not (presumably just by making `vets-api` requests to check), would love more info on this.

Lastly, there are 6 tickets I believe for this ticket's implementation work that I think Dan will post here in a bit on this ticket 🙂 Overall, seems quite feasible from a dev perspective based on the info I currently have and I'd be excited to work on it!

**Comment by kelsonic** [comment]
@stephorkandatx Follow-up engineering ticket needed to knock this out 🙂 I think we may be able to validate + close this ticket out
