### ISSUE TITLE
UX | Design flow and screens for building a preview (prior to submitting for Staging review)

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#96970]
## Description
This design issue is to mock up how a user of the tool might preview either a step or simulation of the conversion as a way to double check their work prior to sending to staging review

## Tasks 
- [x] Wireframe out initial screens and options 
- [x] Share either wireframes or prototypes as necessary to get necessary feedback and input from team/stakeholders
- [x] Align with team's feasibility 

## Acceptance Criteria
- [x] Feedback collected within [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1732893891875/69c3e654d8d8fd65ab2cad262d75b15ad8bec488?sender=ub5dc086a14b6f943de142963)
- [x] Feedback implemented in (link: [Figma file](https://www.figma.com/design/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?node-id=4574-64807&t=9dkbFo6djgJn9elC-1))
- [x] Team has reviewed and discussed item
- [x] PM has reviewed and approved this work

**Comment by brian-wilke** [comment]
Created a [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1732893891875/69c3e654d8d8fd65ab2cad262d75b15ad8bec488?sender=ub5dc086a14b6f943de142963)  to hold this discovery and design work. 

Will share with team at 16th minute or during collaboration session.

**Comment by brian-wilke** [comment]
This [comment](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1732893891875/69c3e654d8d8fd65ab2cad262d75b15ad8bec488?wid=0-1733493880866) should help you navigate to the final understanding (shared out at 12/6 Fallout Friday) of how preview might be accomplished via the Form Builder tool. 

This design needs to now be translated into screens for representation within Figma.

Future iterations may also carry additional features around notifications.

**Comment by brian-wilke** [comment]
@Karak888, need update to know if the way we are showing this (with potential error screen of un-setup view) is the correct path for us to capture in Figma. 

Thanks!

**Comment by brian-wilke** [comment]
@Karak888 the [figma file](https://www.figma.com/design/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?node-id=4574-64807&t=9dkbFo6djgJn9elC-1) for your review covers the updated content we discussed today for approval. 

Moving this ticket to review.
