### ISSUE TITLE
Conduct sessions Toxic Exposure Evaluative Research Study [Sprint 11]

### ISSUE THREAD

**Issue by mayacarrolluxa6** [department-of-veterans-affairs/va.gov-team#96975]
## Issue Description 
We are conducting post-launch research with Veterans so we can make improvements on the existing flow. This ticket represents the work of running sessions for the AT Evaluative Research Study. 

[Review research documentation](https://github.com/orgs/department-of-veterans-affairs/projects/880?pane=issue&itemId=87706612&issue=department-of-veterans-affairs%7Cva.gov-research-repository%7C723)

## Background
We will be conducting Veteran-facing usability testing on the new feature in the 526ez along with the IPF alerts from the 1.1 rollout. This user testing will complement ongoing UX monitoring of the release ([TE Monitoring](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/2024-08-Toxic-Exposure/TE-Monitoring.md)). Findings from previous monitoring will inform research questions and help to focus the study, itself.

## Impact
At a high level, we want to know what aspects of the UX are causing problems for Veterans, leading to abandonment, cognitive fatigue, frustration, etc. We are also curious about how the In Progress Form is impact opt-in/out rates for Veterans. 
Findings from the study will help drive design improvements to the TE flow, making it easier and more intuitive for Veterans to apply for benefits.

## Tasks
- [x] Conduct research sessions
- [x] Communicate with Perigean to ensure recruit is complete
- [x] Inform Perigean in study slack channel when participants do not show or qualify
- [x] Ensure facilitators, notetakers, and observers are assigned to every session 
- [x] Collect takeaways from people on each call (run debrief session where possible)
- [x] Update participant observation sheet (tracking pain points, task completion, etc.)
- [x] Upload sessions to Sharepoint folder and document once complete
 
## Acceptance Criteria
- [x] Research sessions are complete
- [x] Takeaways are collected
- [x] Recordings are added to [Sharepoint folder](https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x01200073ECFC0A16DB51439C06C6FDC0E92947&id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2F0%20%2D%20Benefits%20Portfolio%20%2D%20General%2FResearch%20Recordings%20%2D%20Veteran%2DStaff%2DVSO%2F2024%2D11%20526%20Toxic%20Exposure%20Research%20Study&viewid=3fa7a9bb%2D3d4e%2D44c2%2Db93f%2D629268a08e72)

**Comment by evelynhilbrichdavis** [comment]
All sessions [are now in Sharepoint](https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x01200073ECFC0A16DB51439C06C6FDC0E92947&id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2F0%20%2D%20Benefits%20Portfolio%20%2D%20General%2FResearch%20Recordings%20%2D%20Veteran%2DStaff%2DVSO%2F2024%2D11%20526%20Toxic%20Exposure%20Research%20Study&viewid=3fa7a9bb%2D3d4e%2D44c2%2Db93f%2D629268a08e72) as audio, video, and transcript:
