### ISSUE TITLE
[DRAFT] Redirect Request

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9697]
## Requested By
Facilities Team
Contacts: Michelle Middaugh (AdHoc), Dave Conlon (VA)

## Implementation Date
Date new URL(s) will be live: [TBD]

Please indicate when the redirect(s) needs to be implemented
[X] On the same date the new URLs launch

## Background
When a Veteran selects a facility from the Facility Locator search results, that location's facility detail page is displayed.

When the new pages for VISN 4 are rolled out, the existing Facility Detail pages for the specific  locations will be archived

## Tasks

- The existing (about to be retired) Facility detail page should redirect to the new facility detail pages.
- Although the page will no longer be part of the workflow for the locations in the VISN 4, this redirect is intended to assist visitors who may arrive to the page via outside links.

## Acceptance Criteria:

- Once VISN pages go live, Veterans who arrive on a relevant Facility Locator detail via outside link or bookmark will be redirect to the new VAMC pages.

**Facilities to be changed**
- https://docs.google.com/spreadsheets/d/12iIE2_GRxnVRnd-ZCKv0cJF-4YX02SOH7EHqMVbQx30/edit#gid=2015676392 _(this link to be replaced by file once URLS are confirmed)_

## Steps to complete
- [ ] Above information is provided and issue is tagged and assigned appropriately - @ requesting team
- [ ]  All appropriate VA stakeholders are notified of pending redirect - @ requesting team
- [ ]  Redirect request is vetted and documented and implementation plan is clear - @ Content & IA team
- [ ]  Request is assigned to appropriate team for implementation - @ Content & IA team
- [ ]  Implementation team completes work - @ Implementation team
- [ ]  Implementation pushed live and redirect is validated in production - @ all
- [ ]  Ticket is closed - @ requesting team
