### ISSUE TITLE
Content Knowledge Pick-Up - SSO/Login: VA.gov Health Pages

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9698]
## Issue Description
Discovery, investigation into the work done to date for the SSO/Login: VA.gov Health Pages to create new patterns, alert boxes for unauthenticated and authenticated experiences. 

These are updates to alert boxes, static content on VA.gov health pages (prescription, test results, messaging, etc.) to direct users who are patients at Cerner facilities to the right place.

Users who are marked on the backend as being patients at a facility that will start using Cerner for health tools, will start seeing the new pattern.

The existing content in the mock-ups has been 'approved' by Peggy. Changes from our team would need review. 

The goal of this ticket is to have Content review the work that has completed to date, to:
- Investigate the proposed content - does it need our required standards on plain language, 'voice', and structure/strategy?
-  If needed, flag that updates may/will be needed

The output of this ticket will be an understanding of the content, the goals of the initiative, and the decision if we need to make accommodations to the content for implementation and launch.

---
## Tasks
- [x] Review supporting documentation, design elements
- [x] Generate list of questions/concerns
- [x] Review with Peggy, if needed

## Acceptance Criteria
- [x] Questions/next steps documented
- [x] Issue created for editing work in next sprint

---
## Documentation
Desktop Invision: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/409123884_Unauthenticated_Pages

Mobile Invision: https://adhoc.invisionapp.com/share/5QWAJJQNG2J#/409260607_M-Authenticated_Pages_-_Alerts

Usability testing summary: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/ux-research/alerts/research-summary.md

Usability discussion guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/ux-research/alerts/discussion-guide.md

Product Outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/sso

Handoff document: https://docs.google.com/document/d/11OGKfLk0fKd08pqCKT0Wvrt9ze2vZW_PSEn2kJdK714/edit#

---
## Complexities or points of consideration

* There may be some complexity to manage in the future when new Cerner facilities roll out (ex: what happens if a user is a patient at multiple facilities - how would that impact the alert box?)

**Comment by DanielleThierryUSDSVA** [comment]
**Notes:**

- Reviewed content in invision app. From a high-level standpoint, everything looks solid. 
- @stephorkandatx Only larger question that I wondered about was whether we may need to do any engineering work to accommodate the alert component so that it can feature 2 buttons. May not be an issue, but wanted to flag just in case.
- I do see content pieces that are flagged for content review (and Peggy confirmed that she'd reviewed some content, but then it was put on hold), and other areas that looked like they were reviewed, but need some tweaks. I can create an issue for editing for next sprint.

**Comment by DanielleThierryUSDSVA** [comment]
@stephorkandatx Moving this to validate just until we can connect on my one question above. Thanks!

**Comment by stephorkandatx** [comment]
@DanielleThierryUSDSVA i'll flag this for a quick convo this AM but yes, we will need to do engineering work for the alert component. We have those tickets queued to start this coming sprint.
