### ISSUE TITLE
Discovery New Page: RevProxy Deployment

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#97025]
## Issue Description
[Ticket 79065](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?pane=issue&itemId=84087733&issue=department-of-veterans-affairs%7Cva.gov-team%7C79065) has brought to light the need for a separate page on RevProxy Deployment.

All the other deployment items on the Deployments page are _applications_. Rev Proxy is infrastructure. This difference alone could justify a Rev Proxy-specific page. Couple that with the fact that the Deployments page is getting rather long and it is easy to see that Rev Proxy should be split off into its own page. 

The real question, however, is should that page be titled "Infrastructure Deployments" and also include other infrastructure pieces -- and make room for future content expansion -- or should it remain simple a "Rev Proxy" page. 

The SME on the above-mentioned ticket hinted that we might not want to make other infrastructure pieces public. But that SME recommended that we talk to Kyle Matheny about this ticket. So our new SME for the Rev Proxy/Infrastructure page is Kyle. 

---
## Tasks
Discovery: 
- [x] Discuss scope of new page with SME.
- [x] Determine scope (Rev Proxy only vs. Infrastructure)

## Acceptance Criteria
- [x] _Scope is determined, ready to Edit_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by BSmolensky** [comment]
**NOTE**: There is a chance that this ticket is really a "Discovery" ticket AND an edit ticket.

**Comment by BSmolensky** [comment]
All Tasks Complete. Ticket is ready to close.

**Comment by jknipes** [comment]
Closing ticket as _Done_
