### ISSUE TITLE
[BE] 10-10EZ - Improvement: Temporarily disable BGS call for the COLA update weekend

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#97030]
## Background
- As part of the Cost of Living Adjustment (COLA), some systems (EVSS, BGS, VBMS) will be down over the weekend of 11/16-17.  
- The feedback provided last year was that there were still calls going to BGS (not just EZ form) even though it was going to be down, which caused an excess of errors, making it difficult to determine actual errors.

## Scope
- Temporarily disable the call to BGS for disability ratings on the 10-10EZ during the update weekend

### Resources
- Slack channel for COLA info: [#cola-downtime-planning](https://dsva.slack.com/archives/C064JKBD0N8)
- SNOW ticket [CHG0538489](https://yourit.va.gov/now/nav/ui/classic/params/target/change_request.do%3Fsys_id%3D9f06901a97a19a1442d1fcc0f053af54%26sysparm_view%3DDefault%2Bview%26sysparm_view_forced%3Dtrue) (VA Network)
- Slack Canvas - [COLA Overview & Retro](https://dsva.slack.com/canvas/C064JKBD0N8)

## Tasks
- [x] Create feature toggle
- [x] Update BGS call to be disabled
- [x] Return a zero/nil/null/undefined response to Frontend
- [x] Complete testing to ensure it does not impact other services or submission of the form (regression)
     - [x] QA/PM signoff in the comments below
- [x] Once successfully tested, deploy to production with feature toggle off
---
## Acceptance Criteria/Definition of Done
-  The 10-10EZ form will not be calling BGS while it is down, reducing the opportunity for erroneous error messages

**Comment by coope93** [comment]
@allanto-ah We will want to turn this flipper toggle on in staging and then confirm that we always receive a disability rating of 0 on the EZ/EZR forms where we call this endpoint. The maintenance window was postponed for another week or so, so there is no rush to get this tested today or anything.

**Comment by coope93** [comment]
@hdjustice Tagging you for final sign off on this ticket before we mark it as closed. @allanto-ah validated and documented the behavior above for on/off. We plan to make a new ticket to track us turning it on/off during the outage.

**Comment by hdjustice** [comment]
We will enable the toggle for all users at the EOB on Friday 11/22.  I will continue to monitor the traffic and activity over the weekend.  We will then disable the toggle for all users at the earliest we can on Monday 11/25.

**Comment by coope93** [comment]
Ticket created to turn the toggle on/off for the COLA outage when the dates are announced https://github.com/department-of-veterans-affairs/va.gov-team/issues/97751
