### ISSUE TITLE
Provide LH HLR form submission data

### ISSUE THREAD

**Issue by comaurice** [department-of-veterans-affairs/va.gov-team#97042]
## Value Statement

---

## Background Context

In HLR content form changes, we discovered...

Lighthouse doesn't have data for form submissions and want to know if anyone checked the `homeless` box so they can review. 
We can go back 59 days. 

LH needs the following:
* UUID
* ICN and/or SSN
* Submission date

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] Collect and share the data we have for the related HLR form submissions

## Designs and Build Notes

- Add here

### Enablement team (if needed)
@ member of team

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
Email with information has been sent.

**Comment by eileen-coforma** [comment]
Email has been sent. Considered done.
