### ISSUE TITLE
Verification | Create Confirmation Page

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97102]
## Issue Description
_As a Veteran verifying my dependents, I need to see a confirmation page before I submit my 0538 claim._

Wireframe: needs to be added

Notes:
- Once a Veteran clicks "submit" on the review page created in #97100, they will be shows this confirmation page

---
## Tasks
- [ ] Create a review page using the design system template and customize as needed to match wireframe

## Acceptance Criteria
- [ ] Page matches wireframe
- [ ] Ajia signs off on page in staging
---

**Comment by jacobworrell** [comment]
@fiorella-io I think we need to add designs to this ticket

**Comment by aplatt-coforma** [comment]
Created bug ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/112990 to fix the missing breadcrumb
Created bug ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/112993 to fix the text changes on the page.
