### ISSUE TITLE
Verification | Backup submission pathway

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97106]
## Issue Description
_As a Veteran, if my 0538 claim fails to submit to my eFolder, it needs to submit to Central Mail as a backup pathway._

---
## Tasks
- [ ] Implement a backup submission pathway to Central Mail (LH API)
- [ ] Create logging and monitoring to check for failure/success
- [ ] Send "action needed" email if backup pathway submission fails (total failure)

## Acceptance Criteria
- [ ] Failed claim submits to backup pathway (Central Mail)
- [ ] Logging and monitoring checks for failure and success
- [ ] "Action needed" email sent if backup submission pathway fails
---
