### ISSUE TITLE
DV | FE | Step 4: Review Page

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97100]
## Issue Description
_As a Veteran, verifying that I have no changes to make to my dependents, I need to see a review page that shows all the information I am about to submit for my verification claim._

Digitizing the Verification form ([VA form 21-0538](https://www.va.gov/find-forms/about-form-21-0538/))

**Note:**
- The review page will only be displayed if the Veteran indicates on the previous page (Step 3), that they have no changes to their dependents.

## Designs
- **Note:** The content for the `status of your dependents` question has not been finalized
- [Figma](https://www.figma.com/design/bvj72inycD0iZkuCbjYTWL/Dependent-Verification-MVP?node-id=3002-126937&t=Scj5iAt7cyG3h6zj-1)

<img src="https://github.com/user-attachments/assets/ac853677-336f-4606-9a5e-85e356b19d20" width="30%">
<img src="https://github.com/user-attachments/assets/3f95c3bc-fc99-4383-a704-22889e661995" width="30%">
<img src="https://github.com/user-attachments/assets/63894127-8b23-40d9-a10a-a548d38d4867" width="30%">

## Tasks
- [x] Create a review page using the design system template and customize it to align with the wireframe
- [x] Include the [additional info component](https://design.va.gov/components/additional-info) for the Veteran's information and Dependent's information sections. 
- [x] Ensure editing the 'status of dependents' section takes Veterans to the previous step (Step). 
- [x] Update unit test coverage

## Acceptance Criteria
- [x] Front end of form aligns with Figma file
- [x] Copy in online form matches Figma file
- [ ] Design team signs off on form flow in Staging
- [ ] Design team signs off on page updates in Staging
- [x] Unit tests and E2E tests are updated, passing, and meeting standards

**Comment by Mottie** [comment]
- Veteran info page PR: https://github.com/department-of-veterans-affairs/vets-website/pull/37204
- Veteran contact info PR: https://github.com/department-of-veterans-affairs/vets-website/pull/36943
- Veteran dependents PR: https://github.com/department-of-veterans-affairs/vets-website/pull/37147 (possible added to another PR?)

**Comment by fiorella-io** [comment]
Can we update the accordion title to `Veteran's information` to avoid a duplicate title? @Mottie [Noticed it](https://dsva.slack.com/archives/C05NEL4DKMX/p1750281290463849?thread_ts=1750281202.252069&cid=C05NEL4DKMX), and I've updated our [Figma files](https://www.figma.com/design/bvj72inycD0iZkuCbjYTWL/Dependent-Verification-MVP?node-id=3002-126918&t=wFlcI2b0IDzRUfwU-1).  

<img width="30%" src="https://github.com/user-attachments/assets/9c6cfcb8-8fa9-40a4-8c75-ae591f6e612a" />

**Comment by fiorella-io** [comment]
@Mottie, please update the following:

- Make sure the email address and privacy statement wrap on mobile 
     - <img width="50%" src="https://github.com/user-attachments/assets/f619cd77-3eb5-47e4-b25a-1dbc713293e7">
     - <img width="50%" src="https://github.com/user-attachments/assets/2dcec8d9-f9db-4246-b6f5-18de23d8e5b5">
- Update the "Status of dependents" question to match the question on Step 3. `Is your dependent information correct? `
     - <img width="50%" src="https://github.com/user-attachments/assets/ce79dff9-e361-4428-8189-7b3c11af8420">
- I just noticed our bolding in the additional info component is not consistent. I've updated the designs.
     - For "Dependents on your VA benefits" bold `we don't allow online changes to your dependents’ names, dates of birth, or Social Security numbers` and unbold `Monday through Friday, 8:00 a.m to 9:00 p.m ET.`
     - And add this link `Find more detailed instructions for how to change your dependents’ name (opens in new tab)` that links to `https://www.va.gov/resources/how-to-change-your-legal-name-on-file-with-va/`
      - Update accordion title from `Review your dependents` to `Dependents on your VA benefit`
      - <img width="40%" src="https://github.com/user-attachments/assets/1d5f823d-15d6-4a2b-973e-285b5189dbd6"><img width="40%" src="https://github.com/user-attachments/assets/e25cffd6-b0f0-496e-a23a-3a07a8a4da2b">

**Comment by Mottie** [comment]
I was able to fix all of the issues except for the statement of truth overflow - [I opened a ticket with the design system to fix the `va-statement-of-truth` web component](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4424). Please verify in staging.

**Comment by fiorella-io** [comment]
@Mottie Sorry, a few more things

- I notice when I click "edit" for home phone number or international number, it takes me to edit the email instead. 
-  The title `Edit email` should say `Edit email address`

<img width="30%" src="https://github.com/user-attachments/assets/8e560816-81d0-4abf-b84f-affccc516778">
<img width="30%" src="https://github.com/user-attachments/assets/dcd37e98-6eac-4ff0-8456-372caa80a287">
<img width="30%" src="https://github.com/user-attachments/assets/d22b79f3-b7fd-4e1d-9cfd-5e5a4bcc59f7">

**Comment by fiorella-io** [comment]
Looks good, and the edit functionality works too! 

<img width="40%" src="https://github.com/user-attachments/assets/301e1952-380c-4ca4-89b9-254fb08ab230">
