### ISSUE TITLE
Copy of Design | 674 | Confirmation Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97109]
## Issue Description
_New confirmation (received) email templates are available. We need to review the current template the form is using and determine if updates need to be made._

- [Current emails](https://docs.google.com/document/d/1kkbkDhgaGJuNrJbz2uHZGWAmbAq0ac21_nkpDQ8FkTc/edit#heading=h.nvwukvkz72q6) in use that need to be updated.
- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

Current confirmation email:
<img width="645" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3ZRQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b6dfd717cdaaf9aac754c9d52b55efca053d256/image.png" alt="image.png" />

---
## Tasks
- [ ] Review current confirmation email and determine if changes need to be made to align to updated template
- [ ] If changes do need to be made, update existing confirmation email template in VA Notify

## Acceptance Criteria
- [ ] Confirmation email template is updated in VA Notify
