### ISSUE TITLE
Verification | Generate 0538 and send to eFolder

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97104]
## Issue Description
_As a Veteran, once I've submitted my 0538 on VA.gov, I need VA.gov to create the EP and send to my eFolder (BGS SOAP service/REST API)._

PDF fields were mapped in #97093. 

---
## Tasks
- [ ] Create pdf
- [ ] Create EP
- [ ] Send to eFolder
- [ ] Add logging and monitoring to check for success and failure

## Acceptance Criteria
- [ ] The submitted 0538 creates an EP
- [ ] The submitted 0538 is successfully submitted to eFolder
- [ ] Logging and monitoring checks for submission failure and success
---
