### ISSUE TITLE
Create Digital Dispute Service/Model

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#97117]
We'll likely need a service or model that validates form input, maybe mutates data, and submitting the form to a SidekiqJob

## Tasks
- [x] Create DigitalDisputeService/Model
- [x] Add tests

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by digitaldrk** [comment]
Commenting since this is rolling over. I just pulled this in at the end of the sprint (ending 11/19). This is under active development and just started today.

**Comment by digitaldrk** [comment]
Submitted 24 hours ago. Awaiting platform review
