### ISSUE TITLE
[Feature] Refactor appointment list directory structure

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#97129]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
The frontend directory structure needs to be refactored due to the addition of new features and the relocation of unit test files. This refactoring will aide in the maintainability and locating source files.

---
## Tasks
This refactoring will occur in phases.

### Phase 1 - Move components shared by Referral appointments feature to the correct directory
- [ ] #99333
```
- ./vaos/appointment-list/components/AppointmentFlexGrid.jsx to ./vaos/components/AppointmentFlexGrid.jsx
- ./vaos/appointment-list/components/AppointmentRow.jsx to ./vaos/components/AppointmentRow.jsx
- ./vaos/appointment-list/components/AppointmentColumn.jsx to ./vaos/components/AppointmentColumn.jsx
- ./vaos/appointment-list/components/ListItem.jsx to ./vaos/components/ListItem.jsx
- ./vaos/appointment-list/hooks/useHandleClick.jsx to ./vaos/hooks/useHandleClick.jsx
- ./vaos/appointment-list/hooks/useHandleKeyDown.jsx to ./vaos/hooks/useHandleKeyDown.jsx
```
### Phase 2 - Update 'appointment-list' directory structure
- [ ] #99335
```
Currently, the './vaos/appointment-list/components' directory contains both page, component, and unit test artifacts thus making this directory unwieldy due to the number of files it contains.

Create a new 'pages' directory and the following page sub-directories to better reflect the artifacts contained in the directory.

- ./vaos/appointment-list/pages
- ./vaos/appointment-list/pages/RequestedAppointmentDetailsPage
- ./vaos/appointment-list/pages/RequestedAppointmentsPage
- ./vaos/appointment-list/pages/UpcomingAppointmentsPage

**Move and rename the following files:**

- ./vaos/appointment-list/components/RequestedAppointmentDetails.jsx to ./vaos/appointment-list/pages/RequestedAppointmentDetailsPage/**index.jsx**
- ./vaos/appointment-list/components/RequestedAppointmentDetailsPage.unit.spec.js to ./vaos/appointment-list/pages/RequestedAppointmentDetailsPage/RequestedAppointmentDetailsPage.unit.spec.js
- ./vaos/appointment-list/components/RequestedAppointmentsListGroup.jsx to ./vaos/appointment-list/pages/RequestedAppointmentsPage/**index.jsx**
- ./vaos/appointment-list/components/RequestedAppointmentsListGroup.unit.spec.jsx to ./vaos/appointment-list/pages/RequestedAppointmentsPage/**RequestedAppointmentsPage.unit.spec.js**
- ./vaos/appointment-list/components/UpcomingAppointmentsList.jsx to ./vaos/appointment-list/pages/UpcomingAppointmentsPage/**index.jsx**
- ./vaos/appointment-list/components/UpcomingAppointmentsList.unit.spec.jsx to ./vaos/appointment-list/pages/UpcomingAppointmentsPage/UpcomingAppointmentsPage.unit.spec.jsx

**Note: Delete. Not used.**
- ./vaos/appointment-list/components/RequestedAppointmentsList.jsx to ./vaos/appointment-list/pages/RequestedAppointmentsPage/index.jsx
- ./vaos/appointment-list/components/RequestedAppointmentsList.unit.spec.jsx to ./vaos/appointment-list/pages/RequestedAppointmentsPage/RequestedAppointmentsPage.unit.spec.js
```

### Phase 3 - Move 'AppointmentsPage' directory to 'pages' directory
- [ ] #99336
```
- ./vaos/appointment-list/components/AppointmentsPage to ./vaos/appointment-list/pages/AppointmentsPage
```

### Phase 4 - Move 'cancel' directory to 'pages' directory
- [ ] #99337
```
- ./vaos/appointment-list/components/cancel to ./vaos/appointment-list/pages/**CancelAppointmentPage**
```

### Phase 5 - Move 'PastAppointmentList' directory to 'pages' directory
- [ ] #99338
```
- ./vaos/appointment-list/components/PastAppointmentList to ./vaos/appointment-list/pages/**PastAppointmentsPage**
- Rename component from **PastAppointmentsListNew** to **PastAppointmentsPage**
```

### Phase 6 - Move 'layout' directory to 'appointment-list' directory
- [ ] #99339
```
- ./vaos/components/layout to ./vaos/appointment-list/layout
- rename ./vaos/appointment-list/layout to ./vaos/appointment-list/**layouts**
- move ./vaos/components/PageLayout.jsx to ./vaos/appointment-list/layouts 

**NOTE**: There are 2 VideoLink components. Which one????
```

### Phase 7 - Move 'ConfirmedAppointmentDetailsPage' directory to 'pages' directory
- [ ] #99340
```
- ./vaos/appointment-list/components/ConfirmedAppointmentDetailsPage to ./vaos/appointment-list/pages/ConfirmedAppointmentDetailsPage
- rename ConfirmedAppointmentDetailsPage to UpcomingAppointmentDetailsPage
```
## Acceptance Criteria
- [ ] All unit tests must pass
- [ ] All e23 tests must pass
- [ ] Directory structure should look like the following:

![Image](https://github.com/user-attachments/assets/0255c5b1-6688-4756-9845-94e0ffa4e58b)
![Image](https://github.com/user-attachments/assets/4cbf7f55-cd1b-4ca7-b289-de0150f8be72)
![Image](https://github.com/user-attachments/assets/180cc41f-3c12-4dec-8891-6dfa8c022ec9)
![Image](https://github.com/user-attachments/assets/70cfaeac-65b4-49a1-8d23-ceb6684d2388)
![Image](https://github.com/user-attachments/assets/c6416ee5-af16-410a-82d5-b9c88606ef20)
![Image](https://github.com/user-attachments/assets/193219d5-b2ef-4b04-9f36-cdbbed6040d2)
![Image](https://github.com/user-attachments/assets/55a886c6-2aa1-4251-a082-f2d671a89741)
![Image](https://github.com/user-attachments/assets/b8ea6f01-a107-44b3-8e24-07008cd1697a)
![Image](https://github.com/user-attachments/assets/c3c1a12a-5e1a-44c8-9032-7a9740a15d37)
![Image](https://github.com/user-attachments/assets/873e407d-7c6f-4b82-aeb0-f29411084dcd)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
