### ISSUE TITLE
Make application available in lower environments : Supply Reordering

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#97137]
## User Stories

```
As a Developer,
I want to deploy changes to the Supply Reorder app to lower environments,
So that I can get feedback from my team and other Stakeholders.
```

```
As a Stakeholder of the Supply Reorder app,
I want to see the latest build of the app,
So that I can... 
  - demonstrate functionality of the application,
  - determine if a ticket has been completed, and
  - give feedback to developers to improve the application.
```

## Tasks

Documentation: https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application

For the following tasks, the react application needs to be merged in `vets-website` before the changes to `content-build` in order for the build process to work correctly. [[source](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application#Creatinganewapplication-PRmergeorder)]

- [x] Fix any failing specs in integration branch
- [x] Merge integration branch in `vets-website`
- [x] Add app to `content-build` manifest 
- [x] Add react application path to reverse proxy

## QA Steps

Visit https://dev.va.gov/my-health/order-supplies and log in 
  - email: `vets.gov.user+2@gmail.com`
  - password available at https://tud.vfs.va.gov

The Order Medical Supplies Introduction Page is visible (w/ plenty of [things to fix](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95836)).

Repeat these steps for https://staging.va.gov/my-health/order-supplies

## Acceptance Criteria

- Application is available at `{dev,staging}.va.gov/my-health/order-supplies`

**Comment by radavis** [comment]
Blocked by content-build build issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/98194

**Comment by radavis** [comment]
content-build issue resolved.

**Comment by radavis** [comment]
Initial supply reordering application will be available at `{dev,staging}.va.gov/my-health/order-supplies`, shortly.

**Comment by radavis** [comment]
Blocked by platform issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/98437

**Comment by radavis** [comment]
content-build `daily-production-release.yml` failed, today. [[source](https://github.com/department-of-veterans-affairs/content-build/actions/runs/12183564636)]

**Comment by radavis** [comment]
And, now we're live at `{dev,staging}.va.gov/my-health/order-supplies`

**Comment by radavis** [comment]
Verified application exists at `staging.va.gov/my-health/order-supplies`
