### ISSUE TITLE
[DD] Silent Failure Email for VA Notify

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#97138]
## Description
Submit a VA Notify ticket in order to send an email to users when a failure occurs.

## Tasks
- [x] UX Develop a message/display method to be implemented when this error occurs
- [x] Create VA Notify ticket

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required

## Acceptance criteria
- [x] [Email message created](https://docs.google.com/document/d/1b6LGY3H0jl1SGM-oVT6Fh3XfmdpZpBzrX4idFcMjSTM/edit?usp=sharing)
- [x] [VA Notify ticket created](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97143)

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>
