### ISSUE TITLE
[Burials] Add Burials form analytics in Datadog

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#97135]
## Issue Description
As the VA,  I want insight into submission volume on the 530EZ so that I may make informed decisions on business priorities.

Background: 
Today submission analytics on the 527EZ are provided to VA stakeholders but not the 530EZ, this will help close the gap.  Mimic the fields provided in the weekly Sprint Review for Pension for parity.

Desired metrics:
From form launch:
-Total submitted, count of authenticated, count of unauthenticated
For past week:
-Total submitted, count of authenticated, count of unauthenticated, # of unique sessions (out of total # of sessions), end to end conversion percentage

---
## Tasks
- [ ] Desired analytics are generated from the 530EZ form submissions
- [ ] Desired analytics are made available to end users in datadog dashboard

## Acceptance Criteria
- [ ] Desired analytics are made available to end users on an ongoing basis in datadog dashboard
