### ISSUE TITLE
[FSR] Bug - Monthly housing expenses PDF population

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97148]
## Issue Description
When `showUpdatedExpensePages` feature flag is true we should use `form.data.expense.monthlyHousingExpenses` to populate the "Rent or Mortgage Payment" box in the pdf. 

### Form Data fragment
```
data: {
    'view:showUpdatedExpensePages': true,
    expenses: {
      monthlyHousingExpenses: '3000'
    },
```

### PDF screenshot:
<img width="414" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTI5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02020442ff12efec4ba5614c0320a3b74e6ab3f5/image.png" alt="image.png" />

## Tasks
- [ ] Identify issue
- [ ] Resolve issue

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] PDF is correctly populated when feature flag is set

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by Tom-Davis** [comment]
Closing - duplicate ticket being worked in 97625
