### ISSUE TITLE
UX | Update Pattern Matrix to reflect lock-downs in Address and Contact info

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#97141]
## Description
This ticket is to assign the work of maintaining the Pattern Matrix. To keep the Pattern Matrix up to date, it needs reflect form builders version of these patterns in use. Specifically, the Identification, Address and Contact information are more locked down patterns than previously described.

## Tasks 
- [x] Confirm with engineering that specific patterns are solid and will be locked down
- [x] Update the personal information step with the associated patterns (unique case)
- [x] Verify any "Next, or Later" variations that may need to be captured for the backlog

## Acceptance Criteria
- [x] Review as part of Follow-up Friday
- [x] Refine Pattern Matrix into new Mural... [Step Library](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1731956783059/f34d7fc7b35ba062c2a10b42adc6ab25481a798e?sender=ub5dc086a14b6f943de142963)

**Comment by brian-wilke** [comment]
Will review this as part of Fallout Friday (Nov 22).

**Comment by brian-wilke** [comment]
Closing post share out to PO and to team.
