### ISSUE TITLE
Analytics Product Success Tool Request for [Coronavirus-chatbot team]

### ISSUE THREAD

**Issue by jeddacp** [department-of-veterans-affairs/va.gov-team#9714]
# Request the Product Success Tool

## What this form is for
To set up a Dashboard for the Coronavirus chatbot (https://www.va.gov/coronavirus-chatbot/) on DOMO

## Instructions for the VFS team
- [ ] For additional info, read through the [How to Request the PST Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/product-success-tool-request.md)
- [ ] Ensure your KPIs are clearly linked back to your OKRs or goals
- [ ] Link your KPIs below
- [ ] Submit this ticket as an epic
- [ ] Add your team label to follow progress

### KPIs
- KPI 1: Inbound traffic to chatbot from internal VA.gov pages (MHV, FAQ, other facility pages) #9611 
- KPI 2: Phone number clicks from mobile vs desktop, and the top level category from where the phone number was clicked on #9621 
- KPI 3: Number of users serviced or assisted (Call center vs Chatbot) #9622 
**Note:** this dashboard will evolve to include additional metrics that are currently being tracked in Appinsights in the future

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria
Issue 1 - Groom Analytics for [team]
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

Issue 2 - Draft PST Dashboard for [team]
- [ ] Draft dashboard on Domo
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team

**Comment by joanneesteban** [comment]
Thanks for sharing, @jeddacp ! Do you have the OKR(s or Goals) that these KPIs are linked to? I believe you and Ramya shared an iteration of those during our meeting last week. For instance,
- "Objective: Improve Veteran access to information"
- "KR: Increase the amount of chatbot resource clicks to online resources by X%"

**Comment by rumyeahs** [comment]
@joanneesteban Please find our initial thoughts for OKRs:

Objective: Assess if the chatbot is helping reduce contact center volumes:
* Metric/KR: Average call volume - (Compare before and after chatbot numbers) 
* Metric/KR: How often is the veteran clicking on a phone number from within the chatbot to speak to someone
* Metric/KR: How often does the veteran get routed elsewhere because the veteran called the wrong number

Objective: Improving Veteran access to information:
* Metric/KR: How often is the veteran directed to an online resource (clicks something we give them in an answer)
* Metric/KR: Other engagement metrics such as top level categories, paths taken within chatbot, I have the info, Speak with someone, Ask another question - already captured in PowerBI
* Metric/KR: Satisfaction responses from the user 

Objective: Improve Veteran customer experience
* Metric/KR: Is there proportionally more engagement with the chatbot as compared to the FAQ page - 
    - Links clicked 
    - Time spent
    - Incoming traffic to FAQ vs outgoing to Chatbot  
* Metric/KR: How are they rating their experience on this page vs the other pages they visit on VA.gov 

Let me know if you'd like more details
Thank you!

**Comment by joanneesteban** [comment]
@rumyeahs Awesome, thank you! 

It's not necessary, but if at some point you set KR targets (the goal you would like to hit for success) and KPI targets (the metric baseline you would like to be alerted to if your metric falls below that baseline), please send that over and we can incorporate that in this dashboard.

@bsmartin-ep @amycesal new issues for grooming and dashboard drafts are on the board.

**Comment by jonwehausen** [comment]
Reassigning to Jason.
