### ISSUE TITLE
[VETS-API] Backend CI - Fix current iteration

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#97156]
After further discussions with the team, we decided not to expand approving capabilities, and will keep the current approach. I learned a few things during my iteration, and believe I can fix a few of the issues that currently exist:
* `test-passing` and `test-failure` labels appearing simultaneously
* labels being added/removed&re-added unnecessarily. 
* There was an issue with some exempt teams unnecessarily requiring backend approval (need to investigate cause again)
* Update verbiage/task names for added clarity

## Tasks
- [x] Implement via PRs into current workflows
- [x] Test locally and in "production"

## Acceptance Criteria
- [x] Workflow is merged to master and everyone is happy.
