### ISSUE TITLE
Release EVSS to Lighthouse migration: use BRD endpoint for separation locations

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97158]
## Issue Description
As an OCTO stakeholder I want the 526 application to use the Lighthouse BRD endpoint to populate separation locations in the 526 form.

## Tasks (Engineering to revise)
- [x] update feature toggle in Flipper admin https://api.va.gov/flipper/features/disability_compensation_lighthouse_brd
    - [x] enable for all users. there is no reason to do an incremental rollout because once the data is cached once, it is cached for all users
- [x] clear the cache via the rails console, 
    - [x] run this command to see the cached value `EVSS::ReferenceData::ResponseStrategy.find("all_users:get_separation_locations")`
    - [x] run this command `EVSS::ReferenceData::ResponseStrategy.pop("all_users:get_separation_locations")`
    - [x] run **_this_** command **_again_** to make sure the cache cleared: `EVSS::ReferenceData::ResponseStrategy.find("all_users:get_separation_locations")` 
    - [x] the result should be `nil`
- [x] confirm it’s working via this [this dashboard](https://vagov.ddog-gov.com/dashboard/n5i-sba-u52/benefits---disability---526---evss-to-lh-brd?fromUser=false&refresh_mode=sliding&from_ts=1731694657602&to_ts=1731698257602&live=true)
    - [x] this is _usually_ ran only once a day. the cache clears every 24 hours. then a user will go to file a BDD claim and the resulting separation locations value is cached.

## Acceptance Criteria
- [x] 526 is using Lighthouse BRD for separation locations

## Additional Information

**Comment by aurora-a-k-a-lightning** [comment]
hi @samw-va, following up (also in the [Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1731945835719449?thread_ts=1731708543.442979&cid=C04KW0B46N5)), the dashboard looked to be incomplete with placeholders from the migration. apologies for that.
ae are working on making the queries correct.
thanks!
