### ISSUE TITLE
Tech Discovery: Disabilities

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97150]
## Issue Description
As a team member I want to know which custom components or legacy widgets are in use within the Veteran Details chapter of the 526 form so that I am able to plan for potential upgrades to these form components.

---
## Tasks
Review the following pages

- [x] claim-type
- [x] disabilities/orientation
- [x] disabilities/rated-disabilities
- [x] new-disabilities/add
- [x] new-disabilities/follow-up
- [x] toxic-exposure
- [x] pow
- [x] additional-disability-benefits
- [x] adaptive-benefits
- [x] aid-and-attendance
- [x] individual-unemployability ?
- [x] additional-disability-benefits-summary
- [x] disabilities/summary

## Acceptance Criteria
- [x] A list of any custom components or legacy widgets in use within the Veteran Details chapter is created
- [ ] This list is reviewed with the PM and another member of the team, knowledgable about frontend
- [ ] Documentation is created in [Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez)
- [x] Save working spreadsheet in Google Drive Engineering folder 

As you're going through this chapter if you see pages that are not released yet, consider excluding these.

**Comment by pammicmac** [comment]
Google Sheet continued from https://github.com/department-of-veterans-affairs/va.gov-team/issues/96751
