### ISSUE TITLE
Update EKS documentation

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#97175]
## User Story
As a VFS team member, I want documentation to help me deploy my application to EKS, so that I can work without the direct support of the Platform.

## Issue Description
Five pages in the [Manage applications in EKS](https://vfs.atlassian.net/wiki/spaces/OT/pages/2348909545/Manage+applications+in+EKS) section of the Infrastructure Team Confluence Space (screenshot below) are old and need a refresh. The process to onboard an application has changed slightly. Additionally, non-Platform members need access to this (related [Support request](https://dsva.slack.com/archives/CBU0KDSB1/p1730230446521219)) so it will need moved to the Developer Docs Confluence Space.
![Image](https://github.com/user-attachments/assets/3c77db1b-eb13-49c4-8d70-3abd1a3d63fc)

## Tasks
- [ ] Understand the process to onboard a new application to EKS
- [ ] Update those five pages accordingly
- [ ] To be on the Platform Website, each doc needs to follow [this style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/2438856880/Style+Guide+Checklist). This includes adding a footer, the Last Updated date, and making sure all links are accessible to non-Platform people, among other things.
- [ ] Move the pages to the [Developer Docs Space](https://vfs.atlassian.net/wiki/spaces/pilot/overview) (probably the Infrastructure section). Reach out to the Content team if you have any problems. 
- [ ] Resolve any launch-blocking items the content team brings up.

## Acceptance Criteria
- [ ] Docs are updated to reflect the current process
- [ ] Docs are published on the Platform Website
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
