### ISSUE TITLE
[FE] My VA Health Care: Update LOA1 alert

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#97188]
## Background
The MHV cartography team reached out to us regarding identity/access alerts. They received feedback that the initial sign-in widget should be blue and anything beyond initial sign-in should be yellow (not green).

Matt has completed the [design portion](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93415) of this task. 

| Current | New |
|--|--|
| ![Image](https://github.com/user-attachments/assets/eff18087-3fcc-4a0b-9fbb-d228c0b0d410) | ![Image](https://github.com/user-attachments/assets/a221d4cf-6b92-43ba-860a-c3b90667bf6e) |

---
## Tasks
- [ ] update [verification alert in FE code](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/Dashboard.jsx#L123)
- [ ] update unit or e2e tests as needed
- [ ] feature flag?

## Acceptance Criteria
- [ ] verification alert matches the mockup for LOA1 users only

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ dev or design
- _How can this work be validated?_ tbd

## Resources
- [Design ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93415)
- [Figma mockups](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=2727-34316&node-type=canvas)

**Comment by mtcA6** [comment]
No longer needed
