### ISSUE TITLE
RES/VRE Date Issue

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97183]
## Issue Description
_The RES team reported that the date VA.gov is sending for VRE claims may be incorrect._

The `application received date` in the json is a day ahead of the date in the pdf. For example:
- VBMS: 10/17 on VA.gov pdf
- RES: 10/18 on VA.gov json (this date is then sent to CorpDB)

Questions from RES Team:
- Is VA.gov storing as a date/time or just date?
- Is VA.gov recording time zone?

---
## Tasks
- [ ] Determine why there is a discrepancy in the `application received date` between the json and pdf

## Acceptance Criteria
- [ ] If it's a bug, fix the discrepancy and update RES Teams chat
- [ ] If it's not a bug, notify RES Team, and they will adjust in RES. Update RES in Teams chat.
---

**Comment by evansmith** [comment]
@steele-lm @mjknight50 I think this is just a matter of passing created_at to the template like we do with Burials and Dependents. I'd be willing to bet we don't need to special condition that, and can pass created_at for all calls that are made to pdf processing?

**Comment by mjknight50** [comment]
That entire section of code looks odd to me.  I will review it on Monday with @micahaspyr since he is the one who wrote it.

**Comment by mjknight50** [comment]
This is done in production.
