### ISSUE TITLE
Get with Design Team/Frontend and Run Through Copay History Experience [Lighthouse call]

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#97191]
We had a call with the Lighthouse team. One of the questions asked was about search parameters. It got the wheels turning about what we need request-wise from Lighthouse.

For example, we make one request for debts that has debt history. We use 2 attributes to create a unique id to show the history page.

The copay experience is more complicated. We need to see the latest statement and then previous statements in a link at the bottom of a page.

Here are some questions:
- How do we determine that there are other statements? (links at the bottom of the statement detail page)
- Do we want one request using ICN to get all statements/copays?
- Do we want a request for an individual statement/copay?
  - All statements are by month. Do we want just paginated results passing in an int? Do we want to do date ranges?

## Tasks
- [ ] Come up with a plan for Lighthouse requests that I/we can take to them as a starting point

## Acceptance Criteria
- [ ] Come up with HTTP requests that are needed to make copay history work properly

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
