### ISSUE TITLE
Add decision reviews guide PDF to Welcome Kit page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#9719]
## User story
As a Veteran looking for information on the new decision reviews process, I need access to VA's guide on the welcome kit page.

## Issue Description
Add the decision reviews guide PDF supplied to Danielle to the [Welcome Kit page](https://www.va.gov/welcome-kit/) under the For Veterans section with the text "Understanding the modernized decision review process (PDF)"

## Tasks
- [x] Add PDF to assets folder and name it decision-reviews-guide.pdf (Nick)
- [x] Update text on Welcome Kit page with teaser text listed above under the "For Veterans" section(Randi)
- [x] Publish page in Drupal (Randi)

## Acceptance Criteria
- [x] PDF link and text appears on live page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This work was completed. Moving to validate and will close after today's deployment. FYSA @stephorkandatx @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
This has been validated on the live site. Closing ticket. FYSA @stephorkandatx @DanielleThierryUSDSVA
