### ISSUE TITLE
Create / configure argoCD connection to ECR

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#97210]
Create / configure argoCD connection to ECR 

## Tasks
- [ ] Configure the argoCD instance in the utility cluster to connect to ECR repos
- [ ] Set up terraforrm / helm configurations for next clusters to have ECR connectivity on the argoCD instances

## Acceptance Criteria
- [ ] argoCD able to get at ecr helm charts

**Comment by patrick-black-oddball** [comment]
A good write up of the credential design:

https://developer.harness.io/docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr/

then the repo just needs to be added to argoCD

**Comment by JoeTice** [comment]
Bumped to Sprint 17

**Comment by patrick-black-oddball** [comment]
I was able to test and confirm that argoCD is able to pull the helm charts from ECR
