### ISSUE TITLE
Product/Admin: Prepare Submission Experience for Staging Review by Dec 4

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97219]
## Issue Description
As a VFS team member I want to prepare for the Platform Staging Review so that I can release the New Confirmation Page and updates to the Received email while being in compliance with VA policy and best practices.

## Tasks
- [ ] Verify against Platform's documentation that the AC have been completed

## Acceptance Criteria
- [x] The New Confirmation Page and Received email is available for testing in an approved staging environment
- [x] Provide test user information with valid credentials if the product requires authentication
- [x] User scenarios and how to test them are documented for these features, i.e.: in-progress form, submitted form, new form
- [x] The product’s primary entry point page is updated if needed
- [x] Staging Review is scheduled
- [x] No changes to code (relative to the impacted user flows) or artifacts are made during the 4-business-day window before the meeting

## Additional Information
As of Nov 14 we are not recommending a staged rollout, as the Veteran facing changes are largely addressing instances in which errors are mistakenly shown to Veterans, we are now sending the Received email when the Veteran's 526 is in their eFolder. Along with these changes we've made some design updates to bring our Veteran-facing touchpoints closer to the VFF templates.

User info w valid creds are already stored [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Administrative/vagov-users). We can duplicate this file and update the testing steps for Confirmation page and Received email.

The product’s primary entry point page is updated if needed - not needed

Provide test user information with valid credentials if the product requires authentication
These credentials are already in the va sensitive repo "[526-new-confirmation-page.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/526-new-confirmation-page.md)

Test cases will be updated when Test Rail test cases are finalized.

**Comment by pammicmac** [comment]
Create a new ticket for updating Form Flow Diagram https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?sender=ufe55a1a25f3f25394be01959
