### ISSUE TITLE
Discovery: Unit Testing Feedback

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#97217]
## Pain Point
VFS Team Feedback has highlighted this gap in documentation:
**Q**:  What would make Platform's testing tools more useful to you? What is missing? 
**A**: _I think updated guidance on unit testing for frontend would be helpful. **Specifically Platform's expectations about what lib(s) to use, how and when to update legacy unit tests to current libraries, and what constitutes good unit testing**._ (Trevor Pierce, Oddball)
**A**: _More documentation on how to write and run individual unit tests._ - VFS Fullstack engineer

## Issue Description

- Content team needs Front End SME to help us: 
1) determine if the above info is indeed missing on Platform Website, 
2) write guidance as necessary based on the specific areas in **bold** above.
3) determine if [the child pages in the Unit Tests section need an update after 3 years](https://depo-platform-documentation.scrollhelp.site/developer-docs/unit-tests)

## Relevant Artifacts

- [Slack Support thread](https://dsva.slack.com/archives/CBU0KDSB1/p1731941502629969)
- Slack Content thread - see 9am 11/20 when posted

### SMEs:
Isaac Gallup - Reliability Team; Joe Tice and Curt Bonade provided [answers in comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97217#issuecomment-2486860610). 

---
## Tasks
- [X] Find FE SME for this project
- [x]  Determine with SME how much of the Unit Tests section requires an udpate
- [x] JOE follow up with Trevor Pierce, Oddball to review changes re: does this provide necessary updates?

 (If necessary) create tickets to edit pages for 
- [ ] Recommended Libraries to use
- [ ] how and when to update legacy unit tests to current libraries
- [ ] what constitutes good unit testing
- [ ] additional Unit Testing documentation
- [x] Add blue box notice to top of Enzyme page

## Acceptance Criteria
- [ ] We have determined which pages need an update and created tickets as necessary
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Joe Tice says Isaac from Reliability will look at this in Sprint 15

**Comment by jknipes** [comment]
Curt Bonade, Engineer-Reliability team has confirmed the following information is present in Platform website documentation:
- [Which libraries to use](https://depo-platform-documentation.scrollhelp.site/developer-docs/example-unit-tests-react-testing-library)
- Converting old unit tests to new libraries - i don’t believe that’s our responsibility to provide a guide for that. That’s just learning how to write the code
- What constitutes good unit testing - [it states that 80% of code paths should be covered](https://depo-platform-documentation.scrollhelp.site/developer-docs/unit-tests) and gives guidelines for how to implement numerous functionalities - again, what is a good test for their app, they’ll need to determine based on their app

**Comment by jknipes** [comment]
Isaac made updates to pages, Trevor Pierce confirmed updates fill previous gaps. Closing ticket as _Done_
