### ISSUE TITLE
[CDP] Bug - Account number not showing on statement page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97211]
## Issue Description
Account number is showing as `0` on Statement page for some statements. 
- [Slack thread](https://dsva.slack.com/archives/G01KBHYEXV2/p1731612262337449)
- [Related PR](https://github.com/department-of-veterans-affairs/vets-website/pull/32242/files#diff-2a123afb79a1be2f223706f56089765db9b81f9965bb6fbd2d7522624d659e3eR88)

It looks like there are multiples of the same copay in some instances with missing/incomplete data. 

### Steps to recreate
1. Login as user 81
2. Navigate to `copay-balances` page
3. Select a specific copay, note Account Number
4. Select copay statement
  a. Repeat noting Account number

## Tasks
- [x] Identify issue
- [x] Address/fix issue
- [ ] Confirm data integrity for copays in staging environment

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] Account number issue is showing consistently for the same copay

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by penny-lischer** [comment]
Merged and waiting for code freeze to end to validate in production.
