### ISSUE TITLE
Staging Review: Test New Confirmation Page and Received Email

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97220]
## Issue Description
As a VSF team member I want to ensure these features are working as expected and 

## Tasks (2 copied from Sprint Goals doc - Eng to refine)
- [ ] Test the email feature by submitting a 526 (both claim ID and no claim ID)
- [ ] Write required test rail test cases

## Acceptance Criteria
- [ ] Test cases exist that cover the New Confirmation Page and Primary Path Received email
- [ ] Testing is performed for New Confirmation page and the updated Received email
- [ ] Any discovered defects that cause these features to fail are ticketed in the team's backlog with plans to address them
