### ISSUE TITLE
Test "Ready" Ticket

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#97233]
## Description

How do we make a ticket?

## Tasks
- [x] What is "Convert to issue" and how to we assign it to our team?
- [x] Are there comments separately or just in the body of the ticket?
- [x] How do we make the "Epic" tab it's own view?

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] We know what we are doing.

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
