### ISSUE TITLE
Tech Discovery: Provide a Copy of Submission on Confirmation (526 PDF)

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97235]
## Issue Description
As a VFS team member I want to be able to provide a copy of the Veteran's completed PDF on the Confirmation screen at the time of submission so that the Veteran has a copy they can refer to if they need help, or can save/store it for safe keeping.

### Tasks
- [x] Understand business/legal requirements
- [x] Answer the questions listed below in open questions. 

### Acceptance Criteria
- [x] Written documentation for how this could be achieved is created
- [ ] Results are shared with the team and OCTO stakeholders
- [x] Any identified risks, dependencies, or technical constraints are documented
- [x] Determine if the 526 url will be available to pass into the subcomponent of the VFF template

### Additional Information
We believe the best place to retrieve the Veteran's PDF is from their eFolder because it is the truest representation of a record of the established claim. Additionally, we're leveraging existing application logic that looks to the Veterans eFolder for sending the veteran a Received email, and the eFolder PDF would be the same one that VSRs use so leveraging this logic makes the most sense long term. Also this is only applicable to primary path submissions because for backup path submissions we won't have the PDF generated yet. However, long term, my VA and claims status tool will also be places where the PDF can live and the veteran can download from those touch points in cases where they can't get it from the confirmation page.

Just because Lighthouse has generated the PDF and we get a response back from LH, it doesn't mean that it's in the e-folder.

### Open Questions
- How will we get the 526 PDF? - 
- How quickly can we retrieve a PDF from the eFolder?
- If we can't retrieve the PDF from the eFolder within a reasonable amount of time, where should we get the PDF from?
- Will the 526 url be available to pass into the sub-component of the VFF Confirmation page template? 
- What knowledge does the decisions reviews team have to share about their implementation?
- What about other teams? How are they doing this? 
- Depending on the source of the PDF, is there a time requirement? Does the PDF get deleted after a certain amount of time?

**Comment by Dottifacilities** [comment]
This info will inform the design completion.

**Comment by sethdarragile6** [comment]
Started some [questions out to Matt Dingee](https://dsva.slack.com/archives/C01DBGX4P45/p1730753140519249?thread_ts=1730752151.975239&cid=C01DBGX4P45) in and around possible re-use of their [S3 remediation work](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/simple_forms_api/app/services/simple_forms_api/form_remediation/docs/form_submission_pdf_backups.md#s3-pre-signed-url-retrieval). Could work for the 526ez itself _if_ we're allowed to store the 526ez itself in S3

**Comment by sethdarragile6** [comment]
Also followed up on relevant discussions with the Decisions team [here](https://dsva.slack.com/archives/C044AGZFG2W/p1728997689598159?thread_ts=1723128859.703579&cid=C044AGZFG2W) got a feeling we're in for a wild ride on this one

**Comment by sethdarragile6** [comment]
Began consolidating some findings into this [wiki doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/provide_submission_copy_pdf_tech_discovery.md), however more research is pending.

**Comment by sethdarragile6** [comment]
### Open Questions

- How will we get the 526 PDF? - 

Implement a controller method that calls out to LH's generatePDF and returns the PDF content to the browser

- How quickly can we retrieve a PDF from the eFolder?

We have observed generatePDF generally only taking a few seconds to return results, it should not be issue (unless the service itself is poor health)

- If we can't retrieve the PDF from the eFolder within a reasonable amount of time, where should we get the PDF from?

We don't- it depends entirely on the LH generatePDF endpoint. If we want a backup plan, we would need to store the PDF in S3 redundantly. Issues with this approach are detailed in the wiki doc related to the [Existing Implementations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/provide_submission_copy_pdf_tech_discovery.md#existing-implementations)

- Will the 526 url be available to pass into the sub-component of the VFF Confirmation page template? 

The download URL should generally we able to be generated if the user is logged in and the submission id is known- it does not expire.

- What knowledge does the decisions reviews team have to share about their implementation?

Detailed on the [wiki doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/provide_submission_copy_pdf_tech_discovery.md) and generally on the referenced slack threads therein. 

- What about other teams? How are they doing this? 

Other teams are generally extending VFF's SimpleFormsAPI-based solution, which is S3-based and detailed in the doc. How wildly they extend this solution is unknown. On one slack thread (on the doc) suggests that the decisions team is experimenting with displaying the form embedded with on the confirmation page, which is interesting. This could be one avenue explore, and is likely extendable from the implementation approach I'm proposing

- Depending on the source of the PDF, is there a time requirement? Does the PDF get deleted after a certain amount of time? 

The existing implementation described in the doc has the document effectively "expiring" after 30 minutes (it's still unclear if that means it's actually deleted). In our _proposed_ implementation, the PDF is available as long as it's available in the VBMS eFolder

**Comment by mayacarrolluxa6** [comment]
@sethdarragile6 This was very helpful! I've gathered some of our stakeholders questions in the Mural, and mapped them to the answers and technical rationale in [this](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1736865041471/b1cfe802fe99c9dc661c082805a636bfd642de5b?sender=u2d8a66f6d38755bd8c4c6218) Mural board.
