### ISSUE TITLE
New Page in Dev Docs re: No va.gov emails in Public Repos

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#97275]
## Issue Description
_"we will block the use of [va.gov](http://va.gov/) email addresses on commits for public repos to comply with updated CSOC mandates. Team members will need to utilize the GitHub-native features to obfuscate their email addresses in commits moving forward as outlined in the Discussion post."_

---
## Tasks
- [ ] Create page advising against the use of va.gov email addresses on commits for public repos

## Acceptance Criteria
- [ ] New page ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
