### ISSUE TITLE
Section VII: Q24A - 24D "Retired Pay, Separation Pay, and Disability Severance Pay"

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97285]
## Description
As a Veteran, I want to be able to complete the 526 in full by responding to the "Retired Pay, Separation Pay, and Disability Severance Pay" questions so that I can complete my digital application in the same way that I can complete the paper form. 

Currently, questions 24A - 24D are missing from the digital form. "Retired Pay, Separation Pay, and Disability Severance Pay" don't appear as a question online. This wasn't mentioned in the audit, but because we're planning to implement Q25 which asks about Retired Status and is in the same section, it seemed appropriate to explore this.

## Tasks
- [ ] 

## Acceptance Criteria
- [ ] Document the Veteran and VA value of asking this question
- [ ] Discovery is performed to understand if questions 42A-24D need to be asked
- [ ] Technical discovery is performed to know what data format is acceptable by backend systems
- [ ] Where and how this data will be stored in systems, (i.e. form data, Lighthouse, VBMS) is documented
- [ ] Understand if there will be a necessary impact to user flow
- [ ] Sign off on proposed new user flow
- [ ] User flow in Mural is updated
- [ ] A placement for this question is proposed
- [ ] Change has been implemented
