### ISSUE TITLE
Section VI: Q21D "Current or last assigned name and address of unit"

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97287]
## Description
As a Veteran, I want to be able to complete the 526 in full by responding to the Section VI Q21D "Current or last assigned name and address of uni question so that I can complete my digital application in the same way that I can complete the paper form. 

Currently, question 21D is missing from the digital form. "Current or assigned phone number of unit" doesn't appear as a question online.

## Tasks
- [ ] 

## Acceptance Criteria
- [ ] Document the Veteran and VA value of asking this question
- [ ] Discovery is performed to understand if this question needs to be asked
- [ ] Technical discovery is performed to know what data format is acceptable by backend systems
- [ ] Where and how this data will be stored in systems, (i.e. form data, Lighthouse, VBMS) is documented
- [ ] Understand if there will be a necessary impact to user flow
- [ ] Sign off on proposed new user flow
- [ ] User flow in Mural is updated
- [ ] A placement for this question is proposed
- [ ] Change has been implemented if required
