### ISSUE TITLE
[FSR] Date::Error: invalid date

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#97295]
Preparing for the week, I went into Datadog and reviewed logs. I see we have an issue that started on 11/11. I was able to pull a few forms, it seems that the forms were submitted which doesn't make sense to me given where we error.

One form had the following date: 2016-01.

It seems we are passing something in that cannot be parsed into a date-type for bankruptcy namely the `date_discharged`.

## Tasks
- [x] Find root cause
- [x] Submit PR

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by digitaldrk** [comment]
this is rolling over because it is unplanned work and it's waiting for PR review
