### ISSUE TITLE
Section I: Q3 "Social Security number (SSN)"

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97290]
## Description
As a Veteran, I want to be able to complete the 526 in full by responding to Q3 "Social Security number (SSN)" question so that I can complete my digital application in the same way that I can complete the paper form. 

Currently, question 3 is missing from the digital form. "Social Security number (SSN)" doesn't appear as a question online.

## Tasks
- [ ] 

## Acceptance Criteria
- [ ] Document the Veteran and VA value of asking this question
- [ ] Discovery is performed to understand if this question need to be asked
- [ ] Technical discovery is performed to know what data format is acceptable by backend systems
- [ ] Where and how this data will be stored in systems, (i.e. form data, Lighthouse, VBMS) is documented
- [ ] Understand if there will be a necessary impact to user flow
- [ ] Sign off on proposed new user flow
- [ ] User flow in Mural is updated
- [ ] A placement for this question is proposed
- [ ] Change has been implemented

## Additional Information
Some previous proposals mention showing the Veteran the SSN returned from VA Profile and ask them to confirm it as correct. We need to confirm that the SSN we think is related to the Veteran is associated with them, and have them confirm its correct. We could make it uneditable in the UI but perhaps have them take another action to edit it in the record database (?). We would need to link them to wherever they can change it, ideally without disrupting the Veteran's place in the 526.
