### ISSUE TITLE
Migrate ZenHub Workspace Issues to GitHub Projects

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#97308]
[Z2G](https://z2g-ui.fly.dev) found many (mostly old) issues that weren't in our GitHub Project.

## Tasks

- [x] Determine which issues need to be migrated
- [x] Migrate the issues

## Acceptance Criteria

- [x] All relevant issues our migrated from ZenHub to GitHub

**Comment by JoeTice** [comment]
Completed 12/17/25
