### ISSUE TITLE
Add "Datadog write access" instructions to existing Platform Website article

### ISSUE THREAD

**Issue by bdech** [department-of-veterans-affairs/va.gov-team#97302]
## Description 
The purpose of this sprint ticket is to add a section to the existing Platform Website [Get Access to DataDog](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2529591336/Get+Access+to+Datadog) on requesting write access.
---

## Definition of Done
All tasks below are complete.
---

## Tasks 
_Steps to reach definition of done._ 
- [x] Create section on obtaining DataDog write access
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Publish addtions
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
Section added to Platform Website. Documentation has been deployed.

https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog#GetAccesstoDatadog-Step3:RequestingWriteAccess(optional)
