### ISSUE TITLE
[Digital Dispute] Create PDF for DMC

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#97311]
## Issue Description
DMC has informed us they need a PDF in order to accept our submissions. We need to get a PDF built with nice field mappings so that their dev team can map our submission data to the fields in the PDF

Spec from Denise in OCTO Slack: https://dsva.slack.com/archives/G01KBHYEXV2/p1731947433806979?thread_ts=1731602893.517339&cid=G01KBHYEXV2

## Tasks
- [x] Figure out what format/template to use to make the PDF
- [x] Add fields to be populated by form submission
- [x] Ensure field mapping/naming in the 'meta-code' is correct
- [ ] Get PDF to DMC team

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Item one from the description performs as described in the description
- [ ] Item two from the description performs as described in the description      

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by digitaldrk** [comment]
[debt_dispute_form.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTNLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8fc5bbeb24d5fb3586a707751a98e70a0b8e947/debt_dispute_form.pdf)

**Comment by digitaldrk** [comment]
[debt_dispute_form.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWpLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac6f81a2f6d5e5d267422066a4ea54ebe1f817d2/debt_dispute_form.pdf)
