### ISSUE TITLE
[FE] Update Direct Deposit header/add education benefits 

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#9733]
## Background

[Design ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9423)
Epic: #2086 

The current direct deposit header is very long - especially on mobile. We need to update the copy (if possible) so it's not so long.

## Design and content

<img width="543" alt="Screen Shot 2020-06-02 at 12 36 08 PM" src="https://user-images.githubusercontent.com/58752772/83567176-a911fa00-a4cd-11ea-9675-6382c00267f7.png">

Direct deposit information

Disability compensation and pension benefits
[no changes]

Education benefits

You’ll need to sign in to the eBenefits website with your Premium DS Logon account to change your direct deposit information for GI Bill and other education benefits online.
If you don’t have a Premium DS Logon account, you can register for one or upgrade your Basic account to Premium.  Your MyHealtheVet or ID.me credentials won’t work on eBenefits.

[Go to eBenefits to change your information]
Link: https://www.ebenefits.va.gov/ebenefits/about/feature?feature=direct-deposit-and-contact-information

[Find out how to change your information by mail or phone ]
Link: https://staging.va.gov/change-direct-deposit/

## Tasks
- [ ] Update Direct Deposit content changes
- [ ] Add education benefits box 

## Acceptance criteria
- [ ] Section has been tested and reviewed by Tressa/Matt

**Comment by erikphansen** [comment]
This should be pretty easy, BUT we first need to update our `ProfileInfoTable` component to allow for arbitrary text in a row. Will need to make a ticket for that work.
