### ISSUE TITLE
Staging Testing and Audit for 526 Rated Disability

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#97336]
## Issue Description
As a DBEX team member I want to understand how we'll migrate the /ratedDisabilities EVSS endpoint to Lighthouse's /disability_rating endpoint so that Veterans can continue to retrieve the list of disabilities and rating the Veteran has as needed on va.gov

To prepare this migration, we'll need to perform some tests and auditing of our provider for Rated Disability. As a r

## Tasks
- [x] Review changes made by LH since our last rollout attempt (Jerek Shoemaker or Lorri Glover for details)
- [x] Compare recent changes with our transform
- [x] A quick sanity check in staging to make sure things are still working as intended
- [x] Review and update of metrics

## Acceptance Criteria
- [x] Recent, non-DBEx changes to RD have been reviewed and sanity checked against our provider
- [x] Tests in Staging have been performed and we understand the feasibility of migrating this endpoint and how we'll plan to do it

## Additional Information
- Lighthouse /disability_rating API documentation](https://developer.va.gov/explore/api/veteran-service-history-and-eligibility/docs?version=current)
- [EVSS rated_disabilities documentation](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/getRatedDisabilities)
- Not sure of relevance, but FYI Sam Stuckey's proposal to [remove Rated Disability validation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/proposal_to_remove_ratedDisability_validation.md)

- [Overview of EVSS migration to Lighthouse platform for 526ez](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/evss-to-lighthouse-migration/overview.md)

- [Form 526 architecture diagram](https://lucid.app/lucidchart/645d8a16-22de-4971-9626-198da0483430/edit?invitationId=inv_f335ce12-6583-4396-8892-0c33e67c8b9e&page=KesmZHwb.TSj#)

#### There are two flags, one BE, one FE
Flags:
FE: disability_compensation_lighthouse_rated_disabilities_provider_foreground
BE: disability_compensation_lighthouse_rated_disabilities_provider_background

The FE toggle occurs before data transformation #2 before the submission job. To test this fully we'll need to test e2e (from the creation and IPF of the form all the way to VBMS). Also check code to ensure we're using the right user object for feature toggle.

**Comment by mchae-nava** [comment]
https://vagov.ddog-gov.com/dashboard/rsy-rne-zut/benefits---disability---526---evss-to-lh-rated-disability?fromUser=false&refresh_mode=sliding&from_ts=1731430279419&to_ts=1734022279419&live=true

**Comment by mchae-nava** [comment]
Noting that modprod is already an AC of [75564](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75564). Will close this and resume there
