### ISSUE TITLE
Allow service end date more than 180 days in the future

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97344]
## Issue Description
As a Active Reservist Veteran I want to be able to submit an application for disability compensation with a service end date more than 180 days in the future so that I can apply for and receive benefits even though I remain an active reservist.

The validation will be in vets-website: /applications/disability-benefits/all-claims/validations.js somewhere between lines 621 - 641

### Background
Current form validation incorrectly prevents Active Reservists from entering service end dates beyond 180 days, creating a barrier to disability compensation applications. While Active Reservists serve primarily one weekend monthly and two weeks yearly, their contracts often extend several years into the future. This restriction needs to be removed entirely to ensure these service members can accurately report their service dates and receive timely benefits processing. The enhancement affects all Active Reservists applying for disability compensation, supporting our goal of ensuring all eligible Veterans can successfully submit claims regardless of their service arrangement.

## Tasks
- [ ] understand validation rules regarding dates
- [ ] verify unaccounted for logical path is either accounted for or fixed
- [ ] put a flipper flag around this
- [ ] staging testing
- [ ] unit testing
- [ ] modprod
- [ ] release

## Acceptance Criteria
- [ ] Active reservists are able to apply for and receive benefits even though they remain active reservists.
- [ ] In the UI, an active reservist is able to select a service end date more than 180 days in the future
- [ ] There should be no limit on how far in the future an Veteran can select for their service period end date
- [ ] There's nothing upstream in the submission process preventing date restrictions
- [ ] Unaccounted for logical path is either accounted for or fixed

## Additional Information

*Unknown:* Does LH have any restrictions on future dates?

Active reservists can have contracts that extend many years, like active duty members, but they are not on active duty (most of the time) and are therefore eligible to apply for and receive benefits even though they remain an active reservist. Active reservists are the folks who serve one weekend a month and a two week period each year, but could be activated to active duty for longer periods as well.  That's a lot of "actives" in that explanation so if it doesn't make sense, let me know. This is not a BDD flow.

Since this is blocking Veterans from entering proper data or affecting benefits, it is "purely" prioritized above improvements to 5103/signature/confirmation page and should go before those. However, there's always a cost to dropping work and coming back to it so we can be sensible about the sequencing and not treat it as an emergency.

On the paper form for boxes 21c and 22c we should never limit the entries, even on BDD claims.  BDD claims are submitted while still on active duty, but the service member may still have a reserve commitment beyond 180 days, even after the active duty commitment ends

Q: Should this logic of "release the restriction of the date" be for all "types" of claims? Even non-reservist or BDD? In other words, should the time restriction logic be removed completely from this service date range question?
A: Yes, the restriction should be totally removed.

We'll have to make sure there's nothing upstream in the submission process preventing date restrictions (i.e. nothing else is checking dates in those fields for future date restrictions).

[Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1731693654273149)

![Image](https://github.com/user-attachments/assets/c6b37265-056d-4f43-bf23-4fb3c147abba)

**Comment by pammicmac** [comment]
Break into 
* investigation+potential fix/refactor
* delete validation and release

**Comment by aurora-a-k-a-lightning** [comment]
1. feature flag
2. [validation is used in one place, with a bunch of unit tests](https://github.com/department-of-veterans-affairs/vets-website/blob/2092351050b6c205e8d230f737d6b4c3db0546bb/src/applications/disability-benefits/all-claims/validations.js#L613)
3. question about if any logic needs to check at least in the future and how far out in the future, i.e. Reservist and/or BDD claim
4. confirm what is actually supposed to be populated on the PDF (21c - obligation term of service vs. 22c - anticipated separation date)

**Comment by aurora-a-k-a-lightning** [comment]
closing this as "won't do".
details in this [dsva slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1733865812485489?thread_ts=1731693654.273149&cid=C04KW0B46N5).
 next steps:
1. no change to date validation,
2. designs from david: 
    1. david come up with 3 or 4 scenarios that we need to account for while looking at the UX
    2. examples: current reservist; coming out of active duty; hardest: current;y in reserves, on active duty, filing a claim based on federal orders in 2003
3. shape research project to redesign the UX - address the issue of confusion of language "obligation" versus "active" duty. look to see if new 526 design incorporates this
