### ISSUE TITLE
[FSR] Resolution options style fixes and Household Monthly Expense legend fix

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#97347]
Minor style fixes need to be made for the resolution options section and the Monthly Housing Expenses title to ensure a consistent experience.  

## Issue Description
Given: A veteran wants to fill out an FSR      
When: A veteran chooses resolution options for a debt
Then: They should see the same formatting and visual consistency across options           

## Tasks
- [x] Fix the `legend` on the Monthly Housing Expenses input page to use a `h3`
- [x] Fix the resolution options `css` to make it match the other ones    

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [x] There's an `h3` on the 
- [x] Resolution option text is consistent across options

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [X] Description written
- [X] Tasks defined
- [X] Acceptance criteria written
- [X] Testing defined
- [X] Add Labels
- [X] Attach to an Epic
- [X] Estimate Points

**Comment by josephrlee** [comment]
This was completed in the last sprint, but is still waiting on FE review.
