### ISSUE TITLE
Section V: Q17A - 17C "List VAMC and DOD MTF where you received treatment..."

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97355]
## Description
As a Veteran, I want to be able to complete the 526 in full by responding to Q17 "List VAMC and DOD MTF where you received treatment..." question so that I can complete my digital application in the same way that I can complete the paper form without any risks of missing or partial information that would cause delays or otherwise difficulty in processing my claim.

Currently, question 17A - 17C is missing from the digital form. "List VAMC and DOD MTF where you received treatment..." doesn't appear as a question online.

## Tasks
- [ ] 

## Acceptance Criteria
- [ ] Document the Veteran and VA value of asking this question
- [ ] Discovery is performed to understand if this question need to be asked
- [ ] Technical discovery is performed to know what data format is acceptable by backend systems
- [ ] Where and how this data will be stored in systems, (i.e. form data, Lighthouse, VBMS) is documented
- [ ] Understand if there will be a necessary impact to user flow
- [ ] Sign off on proposed new user flow
- [ ] User flow in Mural is updated
- [ ] A placement for this question is proposed
- [ ] Change has been implemented

**Comment by shannonkford** [comment]
@pacerwow I believe these are covered in the evidence section, when Veterans select VA Medical Records... let's discuss in our meeting.
