### ISSUE TITLE
[FE] My VA Forms Status: create feature flag for PDF download link (part 1)

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#97352]
## Background
We need to add a link on the form status card to allow the user to download their submitted form. The link will be available for a set period of time (60 days from date of submission) and will be in the form of a pdf. We will also need to include error handling

_Technical approach will depend on whether we can reuse the same functionality that the VFF team is using to create this same link on the confirmation page._

_part 1: feature flag - this ticket
part 2: implementation - #89250_ 

## Tasks
- [x] meet with VFF team to [align on technical approach](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/components/ConfirmationView/components.jsx#L235) 
- [x] open [PR for feature flag](https://github.com/department-of-veterans-affairs/vets-api/pull/19470) on `vets-api` repo (this will be named `my_va_form_submission_pdf_link`, not to be confused with our previous `my_va_form_submission_statuses`)
- [x] set up feature flag on `vets-website` 

## Acceptance Criteria
- [ ] feature flag appears on [toggle UI](https://staging-api.va.gov/flipper/features)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Confirm download functionality works

**Comment by allisonlu** [comment]
@DanielMiller-agile6 can you help validate that the feature flag is set up on `vets-website`?

https://github.com/department-of-veterans-affairs/vets-website/compare/main...My-VA/allison/89250/pdf-link-initial-implement
