### ISSUE TITLE
Complete facility health services content model

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9738]
## Issue Description
Complete facility health services content structure model following demo and feedback session with VAMC upgrade team

---

## Tasks 
- [ ] Mockup front end variants based on common scenarios and variants for medical centers and clinics provided by Stan
- [ ] Determine best process for populating facility address and add additional address line(s) for Building and Floor/Wing/Room
- [ ] Determine best practice for phone number across CMS  and add phone extension
- [ ] Move operating status out of Appointment block
- [ ] Determine impact of system level online scheduling 

## Acceptance Criteria 
**TBD 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This issue will be estimated following demo with VAMC team

**Comment by ethanteague** [comment]
Backend pr: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1844
