### ISSUE TITLE
Style CC provider page "links" as buttons

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#97390]
## Task Description

The provider selection page in the CC flow has a few buttons that are styled as links:
* Find a provider
* Change provider
* Cancel

These are correctly coded as buttons, and just need the styling to match. [See screengrabs here](https://www.figma.com/slides/EVQub1UAzXkmKgtVHD6QEw/Small-Enhancements-2024-%7C-Appointments-FE?node-id=1-1104&t=DEq4zMERWye3KaoN-4)

## Acceptance Criteria
- [x] Designs created/added to working file

## Deliverables
- [Figma Design Link](https://www.figma.com/design/HnExAM5SGNXzUlv9yRS87t/Working-File-%7C-Appointments-FE?node-id=2737-2260&t=zSP4ChaTywAWBwNg-1)
---
## How to configure this issue
- [ ] Add title and task description
- [ ] Attach to an Epic
- [ ] Add labels based on work type: design, discovery, documentation, strategy
- [ ] Delete this section

**Comment by outerpress** [comment]
@Cieramaddox a couple of notes:
- Could you add screenshots of the current state, and note the changes? (In the design file)
- Do the buttons still stack on desktop?
- Could you add designs for the "+Find a provider" button at the beginning of the Choose a provider flow?

**Comment by Cieramaddox** [comment]
@outerpress Done!

**Comment by Cieramaddox** [comment]
Dev ticket created for this work [100523](https://github.com/department-of-veterans-affairs/va.gov-team/issues/100523)
