### ISSUE TITLE
Remove unused SSM values associated with the vets-api DEV environment

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#97394]
locate and remove from SSM any unused keys associated with the DEV vets-api environment

## Tasks
- [ ] Create a list of unused keys (~600)
- [ ] Delete the keys from SSM (move to "archive")
- [ ] Double check that keys are not being used

## Acceptance Criteria
- [ ] The Parameter store will be cleaned of unused keys associated with the DEV vets-api environment

**Comment by stevenjcumming** [comment]
Closed in favor of:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/97445
