### ISSUE TITLE
"Normalize" vets-api dev environment chart

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#97393]
The dev environment helm chart for the vets-api application needs to have secrets, config maps, and service definitions pushed into the parent helm chart. Minimizing the environmental configuration

## Tasks
- [ ] settings.local.yaml pushed into parent helm chart - removed from DEV
- [ ] Secret creation pushed into parent helm chart - removed from DEV

## Acceptance Criteria
- [ ] The DEV vets-api helm chart is minimized to only a chart.yaml and values.yal file - not code is in the values.yaml file

**Comment by JoeTice** [comment]
We've changed the structure of this work, and these items will be approached as standalone tickets going forward, we'll maintain this current structure though until the 6 sub-issues here reach a done state.
