### ISSUE TITLE
Map new Facility health services data model to front end

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9739]
## Issue
Newly created data model needs to be mapped to front end editorial experience 

## Tasks

- Map the fields in the new data model  for facility health services with the front end editorial experience

- [ ] Facility 
- [ ] VAMC System Health Service 
- [ ] Facility description of Service 
- [ ] Owner 
- [ ] Parent Category
- [ ] Service Offered? Y/N
- [ ] Referral Required? Y/N
- [ ] Walk-ins Accepted? Y/N
- [ ] Online Scheduling Available? Y/N
- [ ] Building or Department (Main title)
- [ ] Address, Floor, Wing, Suite, Room, etc
- [ ] Main Phone
- [ ] Extension
- [ ] Appointment Phone #
- [ ] Additional Phone Number(s)
- [ ] Hours of Operation

- Meet with Ryan Thurlwell to ensure page renders according to design system

## Acceptance Criteria

- All existing fields are present in new data structure
- Page renders with expected styling
VAMC system editor at the local level can:
- [ ] add local content
- [ ]  view national content
- [ ]  view who can edit national content
- [ ]  cannot edit national content
- [ ]  view how and where localized content will render

VHA editor at the national level can:

- [ ] view all versions of these pages from all VAMC systems in one spot (Dashboard)
- [ ]  find and interact with national detail page content
- [ ]  can bulk edit national content
- [ ]  can easily access and add a token
- [ ]  can view informational errors about tokens
- [ ]  view how and where national content will render

**Comment by ethanteague** [comment]
Frontend pr: https://github.com/department-of-veterans-affairs/vets-website/pull/12825/
