### ISSUE TITLE
Inconsistencies between unit test numbers on platform reporting site vs actual numbers

### ISSUE THREAD

**Issue by adamcaniparoli** [department-of-veterans-affairs/va.gov-team#97399]
## Issue Description
The numbers reported here for Pension and Burials are inaccurate: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/
 
For example, on November 19, 2024, these are the reported unit test numbers on the platform website for Burials:

Coverage
36.68% Statements
34.24% Branches
18.92% Functions
36.60% Lines

And these are the actual numbers, as reported by Todd Rizzolo for the same time:
Coverage
86.16% Statements 299/347
76.65% Branches 197/257
88.51% Functions 131/148
86.37% Lines 298/345

---
## Tasks
- [ ] Address these inconsistencies for the Pension form
- [ ] Address these inconsistencies for the Burial form

## Acceptance Criteria
- [ ] The numbers on the platform reporting site will match those that we can view on our back end
- [ ] Any work done will be a permanent fix moving forward, so the numbers on the platform side will match the back end reporting at all times

**Comment by ToddWebDev** [comment]
It appears that this issue is already being addressed by the VA Platform team, as indicated by this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96926) to address the inconsistencies with the published reports. The matter has recently been highlighted in a Slack conversation for prioritization. Given this, it seems that our team doesn't need to take further action on this issue at this time.
