### ISSUE TITLE
Create "CERT" location in SSM

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#97392]
Relocate all certificates in SSM to a "cert" directory, create a secret to house these certs

## Tasks
- [ ] Create CERTS keys for vets-api Certs in SSM
- [ ] Create K8s secret to pull all the certs into a secret
- [ ] Create a config map to place all the created secrets as files on the deployment containers file system
- [ ] ensure certs are not being placed into the environment variables

## Acceptance Criteria
- [ ] Certs are placed on deployed container's file system
