### ISSUE TITLE
Rename label of new notification standard

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#97401]
## User Story
As a Governance team member, I want to rename the gh label for the new notification standard to align with the broader goal of the standard so that VFS teams aren't confused by the currently niche label.

Assignee: @allison0034 
Peer Reviewer: @KKitagawa-Bosch 

## Description
In ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/94416 Governance team released a new VA.gov Experience Standard to communicate that email and/or text notifications must be sent to Veterans regarding the status of their request. This standard was written somewhat generically so that all scenarios where a notification is required can be covered (although at this time, the only scenario Governance team is supporting is regarding form submission status). 

The gh label that Governance team assigned to this new standard is `exp-std-submission-status` which is not an appropriate label because it's very specific to 1 notification scenario, and not written broadly for all scenarios. 

![Image](https://github.com/user-attachments/assets/89970115-1fc8-469f-9150-e6fb70549f41)

The purpose of this ticket is to rename the label, both in the [VADS guidance](https://design.va.gov/about/experience-standards/) and in the Drafting Template and other sources of truth. 

### Live pages
- [Experience standards](https://design.va.gov/about/experience-standards/)
- [Source of truth](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit?gid=2089466616#gid=2089466616)
- [Drafting templates](https://drive.google.com/drive/folders/1u9HVzUn4Id0p1SbzTt8J6z6bSoQLYOud)

### Drafted pages
- 

## Tasks
- [x] Decide on new tag name (thank you Erin)
- [x] Follow the [updating directions](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards) to update source of truth and templates
- [x] Update design system experience standards page

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The new notification standard, "User receives appropriate notification from the VA or VA.gov about the status of their request" no longer uses the `exp-std-submission-status` gh label
- [x] We have assigned a new gh label to the standard, "User receives appropriate notification from the VA or VA.gov about the status of their request" 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
Maybe we keep it simple with this one: `exp-std-notifications`

**Comment by allison0034** [comment]
@KKitagawa-Bosch I have updated both drafting templates and the source of truth if you want to get a head start on this review. Just need my PR to be approved for design system page. Everything is linked under live artifacts section.

**Comment by KKitagawa-Bosch** [comment]
source of truth and drafting templates look good! I'll review the design system page whenever it goes live!

**Comment by allison0034** [comment]
@KKitagawa-Bosch the [Experience standards](https://design.va.gov/about/experience-standards/) page has been updated. Once you review I will close.

**Comment by KKitagawa-Bosch** [comment]
@allison0034 looks good!
