### ISSUE TITLE
Align with OCTO-DE on expectations for notification standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#97400]
## User Story
As a Governance team member, I want to connect with OCTO-DE leads on what there expectations and goals are with bringing notifications into the VA.gov Experience standards (and Collab Cycle) so that Governance can set and strive towards goals that align with the OCTO-DE vision. 

Assignee: @shiragoodman 
Peer Reviewer: @erinrwhite 

## Description
Governance would like to begin the work for understanding when notifications should be required within VFS products on VA.gov. However, since it is likely that our work will need to involve teams outside of Platform, we'd like to confirm with them our plans first and align on expectations. Specifically, we'd like to reach out to Dave Conlon with VANotify, as well as any other OCTO leads involved in the notifications space.

### Live pages
- 

### Drafted pages
- 

## Tasks
- [x] Scheduled sync with Dave Conlon and Melanie Jones at 4pm ET on 12/12.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have connected with Dave Conlon and other OCTO leads to align on the work Governance would like to begin.

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
This work is not yet complete and will move into the next sprint.

**Comment by erinrwhite** [comment]
Call with Dave today for more information - [link to notes](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3696066964/2024-12+Notifications+in+the+Collab+Cycle)

**Comment by shiragoodman** [comment]
[VA Notify Onboarding Deck.pptx](https://github.com/user-attachments/files/18151964/VA.Notify.Onboarding.Deck.pptx)

**Comment by erinrwhite** [comment]
@shiragoodman checked off the AC on this. I think we are good to close!

**Comment by shiragoodman** [comment]
thanks, Erin! I will close this out.
