### ISSUE TITLE
Investigate Issues with KMS Encrypted Records [Dupe 2 of 2]

### ISSUE THREAD

**Issue by AshleyGuerrant** [department-of-veterans-affairs/va.gov-team#97417]
## User Story
As the owners of the KMS encryption for the ActiveRecord Queries and Postgres DB,
we need to identify and resolve records that have encrypted data but a nil KMS key,
OR if records have decryption issues,
so that we ensure data integrity and prevent potential issues with data access or encryption consistency.

## Issue Description

In [follow-up to this issue](https://github.com/department-of-veterans-affairs/vets-api/pull/19199), we identified records with encrypted data but a nil KMS key. These may be legacy records that weren’t fully migrated from the original attr_encrypted integration. Currently, only one such record exists, but further investigation is warranted. Deletion of the record may also be a viable option.

Additionally, we've identified a number of records (5 total) that are unable to be decrypted. It may be related to corrupted data, and deserve investigation. All of the records are still on the `v2023` version of the `encrypted_kms_key`, so they haven't been rotated since the October 12, 2024 key rotation.

```
models.each do |model|
   model = MODELS_FOR_QUERY[model.name] if MODELS_FOR_QUERY.key?(model.name)
   puts ‘#{model.name}-‘ model.where.not('encrypted_kms_key LIKE ?',   "v#{KmsEncryptedModelPatch.kms_version}:%").count
 end


UserCredentialEmail -1 [6336758]
Pensions::SavedClaim - 4 [9525415, 9526128, 9526162, 9526770]
SavedClaim::Pension - 4 [9525415, 9526128, 9526162, 9526770]

Note: SavedClaim::Pension and Pensions::SavedClaim seem to be aliases for one another!
```

Here is the query that was run in prod rails console to gather records with encrypted data but a nil KMS key:

```
# Loop through each model that uses encryption
ApplicationRecord.descendants_using_encryption.each do |model|
  # Retrieve the encrypted columns for the model
  encrypted_columns = model.lockbox_attributes.keys.map { |col| "#{col}_ciphertext" }

  # Build the query to find records with nil `encrypted_kms_key` and at least one non-nil encrypted field
  query = model.where(encrypted_kms_key: nil)
               .where(
                 encrypted_columns.map { |col| model.arel_table[col].not_eq(nil) }.reduce(:or)
               )

  # Check if any records match the query
  if query.exists?
    puts "Model #{model.name} has records with nil encrypted_kms_key and non-nil encrypted fields."
    puts "Record IDs: #{query.pluck(:id)}"
  else
    puts "Model #{model.name} has no records with nil encrypted_kms_key and non-nil encrypted fields."
  end
end
```

Additionally, there is still a PG Query duraton spike during the 3-5am window. While there are some decryption errors, it seems to be unrelated. It may be related to the Vye::MidnightRun::IngressTimsChunk job [where you can see the errors here](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20service%3Avets-api%20status%3A%28error%20OR%20critical%29%20host%3Avets-api-sidekiq%2A&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZMA_looXaVHgwAAAAAAAAAYAAAAAEFaTUFfbkE1QUFEVjcyMXM3Y3R6QWdBQQAAACQAAAAAMDE5MzAxMDYtMjQzMy00ZTY1LWExM2ItZWZjZjY4Y2Q0OGMy&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=time%2Casc&viz=stream&from_ts=1730887800000&to_ts=1730890020000&live=false)

## Tasks
- [x] Review nil kms key records
- [x] Review records encrypted with the old key material 
- [x] Update documentation accordingly

## Acceptance Criteria
- [x] Any corrupted records are mitigated and a path forward is documented
- [x] Additional KMS documentation is updated accordingly
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by AshleyGuerrant** [comment]
Moving into next sprint. All of the corrupted records are taken care of in #96409 . Moving forward we should understand why records get into this corrupted state (potentially related to the yearly key rotation).

**Comment by LindseySaari** [comment]
For the second part of this, I checked to see if there were any encrypted records with a nil KMS key and found 0. Things seem to be in a good state from the last rotation, but I want to also update documentation for debugging purposes incase there's an issue with the yearly record rotation causing things to get in this state

```
AccreditedRepresentativePortal::PowerOfAttorneyRequestResolution- 0
AccreditedRepresentativePortal::PowerOfAttorneyForm- 0
AppealsApi::SupplementalClaim- 0
AppealsApi::NoticeOfDisagreement- 0
AppealsApi::HigherLevelReview- 0
ClaimsApi::SupportingDocument- 0
ClaimsApi::PowerOfAttorney- 0
ClaimsApi::EvidenceWaiverSubmission- 0
DebtsApi::V0::Form5655Submission- 0
HealthQuest::QuestionnaireResponse- 0
VANotify::Notification- 0
Vye::UserInfo- 0
Vye::DirectDepositChange- 0
Vye::AddressChange- 0
ClaimsApi::AutoEstablishedClaim- 0
SignIn::OAuthSession- 0
UserCredentialEmail- 0
SecondaryAppealForm- 0
PersonalInformationLog- 0
NodNotification- 0
InProgressForm- 0
GibsNotFoundUser- 0
FormSubmissionAttempt- 0
FormSubmission- 0
Form526Submission- 0
Form1095B- 0
EvidenceSubmission- 0
EducationStemAutomatedDecision- 0
DecisionReviewNotificationAuditLog- 0
AppealSubmission- 0
AsyncTransaction::Vet360::TelephoneTransaction- 0
AsyncTransaction::Vet360::PermissionTransaction- 0
AsyncTransaction::Vet360::InitializePersonTransaction- 0
AsyncTransaction::Vet360::EmailTransaction- 0
AsyncTransaction::Vet360::AddressTransaction- 0
AsyncTransaction::VAProfile::TelephoneTransaction- 0
AsyncTransaction::VAProfile::PermissionTransaction- 0
AsyncTransaction::VAProfile::InitializePersonTransaction- 0
AsyncTransaction::VAProfile::EmailTransaction- 0
AsyncTransaction::VAProfile::AddressTransaction- 0
PersistentAttachments::VAForm- 0
PersistentAttachments::PensionBurial- 0
PersistentAttachments::MilitaryRecords- 0
PersistentAttachments::LgyClaim- 0
PersistentAttachments::DependencyClaim- 0
Burials::SavedClaim- 0
Pensions::SavedClaim- 0
SavedClaim::VeteranReadinessEmploymentClaim- 0
SavedClaim::Pension- 0
SavedClaim::IncomeAndAssets- 0
SavedClaim::CoeClaim- 0
SavedClaim::CaregiversAssistanceClaim- 0
SavedClaim::Burial- 0
SavedClaim::Ask- 0
SavedClaim::SupplementalClaim- 0
SavedClaim::NoticeOfDisagreement- 0
SavedClaim::HigherLevelReview- 0
SavedClaim::EducationBenefits::VA5495- 0
SavedClaim::EducationBenefits::VA5490- 0
SavedClaim::EducationBenefits::VA1995- 0
SavedClaim::EducationBenefits::VA1990s- 0
SavedClaim::EducationBenefits::VA1990n- 0
SavedClaim::EducationBenefits::VA1990e- 0
SavedClaim::EducationBenefits::VA1990- 0
SavedClaim::EducationBenefits::VA10282- 0
SavedClaim::EducationBenefits::VA10203- 0
SavedClaim::EducationBenefits::VA0994- 0
SavedClaim::EducationBenefits::VA0993- 0
SavedClaim::DisabilityCompensation::Form526IncreaseOnly- 0
SavedClaim::DisabilityCompensation::Form526AllClaim- 0
SavedClaim::EducationCareerCounselingClaim- 0
SavedClaim::DependencyVerificationClaim- 0
SavedClaim::DependencyClaim- 0
Preneeds::PreneedAttachment- 0
Form1010cg::Attachment- 0
DecisionReviewEvidenceAttachment- 0
SupportingEvidenceAttachment- 0
HCAAttachment- 0
Form1010EzrAttachment- 0
```

**Comment by LindseySaari** [comment]
Docs [here](https://vfs.atlassian.net/wiki/spaces/BCP/pages/2183037084/Backend+Support+Instructions#Database-Key-Rotation-%26-Record-Re-encryption), [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/data-encryption-in-vets-api) and [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/data-encryption-in-vets-api#DataEncryptioninVetsAPI-AutomatingtheKMSKeyRotation) can be updated to include information around the corrupted records and nil KMS key issues.

**Comment by LindseySaari** [comment]
For this query, there are currently no records that are no encrypted with the new key material. The docs will need to be updated  to include information around debugging after the yearly KMS key rotation

```
models.each do |model|
   model = MODELS_FOR_QUERY[model.name] if MODELS_FOR_QUERY.key?(model.name)
   puts ‘#{model.name}-‘ model.where.not('encrypted_kms_key LIKE ?',   "v#{KmsEncryptedModelPatch.kms_version}:%").count
 end
```

**Comment by LindseySaari** [comment]
The [backend doc](https://vfs.atlassian.net/wiki/spaces/BCP/pages/2183037084/Backend+Support+Instructions#Database-Key-Rotation-%26-Record-Re-encryption) has been updated has been updated with debugging information.

**Comment by LindseySaari** [comment]
Documentation and research findings are now complete. Closing as done!
