### ISSUE TITLE
Determine Veteran-facing UAT plan

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#97424]
In addition to the overall community care internal testing, we need to think through if and how we will complete UAT with Veterans. 

## Tasks
- [x] Familiarize with Appointments UAT process and recruitment process (can talk with Peter and Ciera)
- [x] Determine how we might recruit Veterans from the pilot sites (Perigean or ask facilities to help us recruit Veterans when they are talking to staff) 
- [x] Identity any other challenges
- [x] Document decisions/general overview of intentions to share with CC team (async or during SoS meeting)

## AC
- [x] General UAT and recruitment approach created and documented
- [x] Approach shared with team

**Comment by cgednalske** [comment]
@StevenStraily I think this is a good one to pair on and get you fully immersed in 🙂

**Comment by StevenStraily** [comment]
There are a couple of options after looking into everything.

**Option 1**
Contact OMB and make changes to the flow in one of the ways they provide. The most reasonable option is likely adding a "Feature flag survey." This would allow us to add a custom survey after the user finishes the flow. Alternatively, we could do an embedded survey or modify the feedback button survey to capture the needed data.

**Option 2 - Recommended**
We found out from Brian Moon at Perigean that we can direct users from the pilot sites to a unique version of their registration form. This would allow us to easily identify the folks we want to capture if we place the link in the flow and have staff remind them to sign up to provide feedback via that link. We could then have Perigean send those individuals a survey. The only disadvantage I can think of here, is there will be a delay between the participant finishing the process and providing feedback. That should be hours or days at most, though, and ultimately, we believe those differences will be negligible; this still feels like our best bet to reliably gather what we need without waiting an unknown amount of time for outside approvals.

**Comment by StevenStraily** [comment]
@cgednalske @zach-park I believe these are ready to close out; let me know if I missed anything; thank you!

**Comment by cgednalske** [comment]
I agree with your Option 2 recommendation - specifically because (regardless of any lag) we could actively send the survey to the right participants with relative ease. Perhaps Perigean can be ready to immediately send the survey as soon as the participant registers? My concern with option 1 is definitely the effort and time required for a bunch of folks.

Agree the ticket is ready to close / your findings all set to share with the CC group during SoS today! 💃  Nice work! 🎉
