### ISSUE TITLE
AAR MVP User Test - Planning

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#97429]
## Background
User testing of Appoint a Representative MVP on VA.gov with non-AT and AT users.

## Tasks
- [ ] Create GitHub research folder
- [ ] Create research plan
- [ ] Define screener questions
- [ ] Create conversation guide
- [ ] Submit all materials to team for review
- [ ] Create revisions Zenhub ticket

## Acceptance Criteria
- [ ] All tasks complete
