### ISSUE TITLE
Create Wireframes for OH Travel

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#97420]
## Background

[More information](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97418)

Slack thread

**VA Burden Statement:** An agency may not conduct or sponsor, and a person is not required to respond to, a collection of information unless it displays a currently valid OMB control number. The OMB control number for this project is 2900-0798, and it expires 11/30/2027. Public reporting burden for this collection of information is estimated to average 10 minutes per respondent, per year, including the time for reviewing instructions, searching existing data sources, gathering and maintaining the data needed, and completing and reviewing the collection of information. Send comments regarding this burden estimate and any other aspect of this collection of information, including suggestions for reducing the burden, to VA Reports Clearance Officer at [VACOPaperworkReduAct@va.gov](mailto:VACOPaperworkReduAct@va.gov). Please refer to OMB Control No. 2900-0798 in any correspondence. Do not send your completed BTSSS claim or VA Form 10-3542 to this email address.

**Privacy Act Information:** VA is asking you to provide the information on this form under 38 U.S.C. Sections 111 to determine your eligibility for Beneficiary Travel benefits and will be used for that purpose. Information you supply may be verified through a computer-matching program. VA may disclose the information that you put on the form as permitted by law; possible disclosures include those described in the “routine use” identified in the VA systems of records 24VA19 Patient Medical Record-VA, published in the Federal Register in accordance with the Privacy Act of 1974. Providing the requested information is voluntary, but if any or all of the requested information is not provided, it may delay or result in denial of your request for benefits. Failure to furnish the information will not have any effect on any other benefits to which you may be entitled. If you provide VA your Social Security Number, VA will use it to administer your VA benefits. VA may also use this information to identify Veterans and persons claiming or receiving VA benefits and their records, and for other purposes authorized or required by law.

**Estimated burden: 10 minutes
OMB Control : 2900-0798
Expiration Date : 11/30/2027**

[OMB component and guidance in Design System](https://design.va.gov/components/omb-info)

### Questions:
- Is this included on only one page or all related pages in the flow?

## Tasks

- [x] Update/create designs to add OMB to OH Travel (should be needed only on intro page)
- [x] Make sure updates are aligned with SMOC updates
- [x] Update "Latest Design" page in Figma to include changes

**Comment by cgednalske** [comment]
After digging into this a bit, I believe it's a 1‍⃣ because it will follow the exact pattern the travel team is adding.

**Comment by cgednalske** [comment]
[Link to OMB addition for OH travel](https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=4280-2041&t=Wv3Ve0OakaXYKUel-1)

@brianseek @wullaski does this seem to have all the information you'll need for this? Let me know if any annotations are missing.

@zach-park @StevenStraily this is ready for validation when you have a chance.

**Comment by StevenStraily** [comment]
This looks good to me based on my current understanding!

**Comment by cgednalske** [comment]
Thanks, Steve! Changes have also been updated in "Latest Design." 
Closing out the ticket.

**Comment by brianseek** [comment]
Looks good!
