### ISSUE TITLE
Janelle Leave Resources

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#97431]
## Background
Gather resources in an easily accessible place for team reference.

## Tasks
- [ ] Gather research links and organize so they're easy to find. (Example: Have all studies that ladder up to FAR in one list.)
- [ ] Put any VA research resource links in one place. (Example: instructions on how to submit a research collab cycle request.)
- [ ] Put any ARM research links in one place. (Example: roadmap)
- [ ] Check with team if everything is there and easily findable.

## Acceptance Criteria
- [ ] All tasks complete.

**Comment by oddball-lindsay** [comment]
Thanks @jfinnerty13! This looks like a good start and I'll be sure to leave some notes if I happen to think of anything as we get closer to your time off.

For that first task, I'm thinking about the mechanism to access these resources while you're out -- would you be open to a comprehensive Canvas to store all of this? And then we can bookmark that one canvas to the team channel for quick reference.
