### ISSUE TITLE
[BE] 10-10CG - Improvement: Add "County" source to create drop-down options based on address

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#97447]
## Benefit to the Veteran
As a Veteran, I want the County field to have options based on my address (Zip? State?), so that i can feel confident in my data input.

## Background
- After adding the county field on the 10-10CG form, applicants were entering the country name (US, USA, United States). This caused an issue for the staff to determine the correct Caregiver facility and the system to auto-calculate stipends, as it is based on the residential county.  We added field restrictions, however we want to use a more accurate way to have the County prepopulate (in a dropdown or one county filled in).

## Scope
- Implement a way to pull County based on address element (do we want zip code [single county] State? [dropdown])

### Out of Scope
- Populating other address fields based on type-ahead input (this will be explored in another ticket)

## Resources
- Design links
- Screenshots
- Reference docs/tickets where we have this kind of work documented
- Etc.
---
## Tasks
- [ ] Identify source data API
- [ ] Integrate API with Address pages (Veteran and all 3 CG roles)
- [ ] Review with team prior to QA
- [ ] Inform QA for testing readiness (ticket # )

## Acceptance Criteria/Definition of Done
- Update will be made in Address pages of 10-10CG form to populate County based on address.  
- Update is ready for QA

**Comment by hdjustice** [comment]
- display only county 
- remove field totally and send on the backend

Outstanding question - what happens today with mismatch data (county that does not match with zip code)?
