### ISSUE TITLE
Archive Param Store Secrets from Unused Settings

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#97445]
~160 settings were deleted from vets-api and env helm charts. The corresponding param store secrets can be moved to archive. 

## Tasks
- [x] Create a list of param store paths from unused settings (Steven)
- [ ] Create script to copy param store secrets to archive folder (Patrick)
- [ ] Create script to delete old/original param store secrets (Patrick)

## Acceptance Criteria
- [x] A list in a new sheet of AWS Parameter Store Inventory & Helm Chart Mapping is created
- [ ] All secrets in the below sheet are deleted and have a corresponding "archived" verison

https://docs.google.com/spreadsheets/d/1-7PLskyY67b4J1fsk-FADYxnSN1UrmVziFfFIt_1saU/edit?gid=1196209716#gid=1196209716

**Comment by stevenjcumming** [comment]
Covered by ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/99380
