### ISSUE TITLE
Edit: All Docs in Guide to Digitizing VA Forms section

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#97443]
All the docs in the [Guide to Digitizing VA Forms ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/3169517602/A+Guide+to+Digitizing+VA+Forms)section have the same issues and need to be fixed. What are those issues?

1. **ALL the emojis need to be deleted** - Not only due they violate our [Emoji guidance ](https://vfs.atlassian.net/wiki/spaces/AP/pages/3478552585/Emojis)in several categories, they are also gendered male. They need to go. They add nothing to the page and make the PW look like a silly site and not the professional home of information for VA.gov builders. 
2. **All headings are in title case** - [Headings should be in sentence case](https://vfs.atlassian.net/wiki/spaces/AP/pages/622362663/Formatting+and+organization#Formatting-page-titles-and-headings). We need to fix them. 
3. **Over-reliance on bullets** - Bullets can help content read faster and be more oganized...but not when bullets are used this often. Sometime the bullets should be numbers. 
4. **Inconsistent use of Roman Numerals** - while we do not recommend using roman numerals, they aren't LBers. However, these docs are titled with Roman numerals but are sometimes reference in the body text as normal numerals or as numbers spelled out (e.g. "seven"). We need to, at least, edit them for consistency. 

### TASKS

- [ ] Edit All 11 docs as outlined above
- [ ] Prepare for deployment

### ACCEPTANCE CRITERIA

- [ ] All 11 docs have been updated and deployed
