### ISSUE TITLE
[CDP] Clean up figma file

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#97457]
We need to clean up our Figma file and organize it better according to what's in production.      

## Issue Description
Given: I'm a designer working on the CDP
When: I view the CDP Figma file      
Then: Everything should be up to date and mirror our production environment as closely as possible.

## Tasks
- [x] Cleanup/archive outdated pages
- [ ] Label and organize our file to be more clear to non-designers
- [ ] Update outdated components 

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Figma file is cleaned up and more organized 
- [ ] Figma file mirrors our production environment 

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by dhill802** [comment]
Confirmed all set. Closing.
