### ISSUE TITLE
IA: Review collab cycle board for launched things

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#97458]
### Description
We rarely know when products launch, which means that entry points, redirects, and best bets don't get implemented, and we don't get to update our sitemaps. 

One idea for addressing this is looking at the collab cycle board to see which products have passed staging review. We can check the live product vs the IA spec to see whether we've missed steps

### Links

- [Collab cycle board - completed Staging Review
](https://github.com/orgs/department-of-veterans-affairs/projects/998/views/7)

## all non-MHV products that completed staging review 
- [x] [Form 20-0995](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43919): updated decision reviews sitemap to add form. all entry points ok.
- [x] [Form 4142a](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54257)
- [x] [Form 21-10201 (Lay Witness Statement)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55260)
- [x] [1010ez](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47766):
- [x] [21P-0847](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58945)
- [x] [21-0972 alternate signer](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57266)
- [x] [527ez pension deactivation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64897)
- [x] [presidential memorial certificate](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60496): updated sitemap
- [x] [21-0966 intent to file](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56287): 1 link should be action link. Open slack with content team.
- [x] [20-10206 FOIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65886): the IA spec lays out open tasks, Sam is going to see what remains (seems like content already has a ticket)
- [x] [2 new benefit detail pages](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73090)
- [x] [Request extension for board appeal?](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75865)
- [x] [Find a rep 2.0](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71943): hoping to launch by the end of 2024
- [x] [Burial 530](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65251)
- [x] [20-10207](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65887): Sam is creating ticket
- [x] [526 max cfi](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69299)
- [x] [Verify your enrollment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67530): updated sitemap
- [x] [VBA regional offices](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46029): Theyre in the midst of rolling these out. slack: https://dsva.slack.com/archives/C52CL1PKQ/p1732118402614049
- [x] [CST claim phases](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71293): they did launch this.
- [x] [FMP 10-7959f-1](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74178): Kristin spun up [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97580) to deal with this 
- [x] [VEBT resources for schools](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89238)
- [x] [National tests](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91380)
- [x] [Payment history](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85533): The team launched a portion of VBA payment history. They have not launched VHA payment history because they're waiting on a VHA lighthouse team to provide them data. 
- [x] [10-10d](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70913): not launched yet
- [x] [higher level review form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90188)
- [x] [22-5490 fry/dea updates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92989): they went through staging, url was id'd as blocker.

## Acceptance Criteria
- [x] Document all non-MHV products that have completed staging review since it started in March '23.
- [x] Check each one's live product vs the IA spec to see what is missing
- [x] Document needed changes
- [x] Make the changes (or create separate tickets to make them)
