### ISSUE TITLE
[discipline] formID - initiative: story title

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#97455]
## Benefit to the Veteran
As a Veteran, I want the County field to have options based on my address (Zip? State?), so that i can feel confident in my data input.

## Background
- After adding the county field on the 10-10CG form, applicants were entering the country name (US, USA, United States). This caused an issue for the staff to determine the correct Caregiver facility and the system to auto-calculate stipends, as it is based on the residential county.  We added field restrictions, however we want to use a more accurate way to have the County prepopulate (in a dropdown or one county filled in).

## Scope
- Validate that the County field in all address pages are populated based on entered address

### Out of Scope
- Populating other address fields based on type-ahead input (this will be explored in another ticket)

## Resources
- Design ticket #
- Engineering ticket #97447 

---
## Tasks
- [ ] Validate that all content is updated per design
- [ ] Validate that the County field auto-populates in Address pages (Veteran and all 3 CG roles)
- [ ] Validate that the 10-10CG form can be submitted successfully when the county is populated

## Acceptance Criteria/Definition of Done
- 10-10CG form is updated on all Address pages to populate County based on address.
