### ISSUE TITLE
[Business Optimation] Review VISN-19 system legacy sites for inclusion of any required pages [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9746]
## User Story or Problem Statement
As a Business Analyst, I need to know the specific details regarding the Health Services Provided and Content requirements, so I can document and create the Health Services listing correctly.

## Goal
_Review VISN-19 systems data from Legacy website data by VISN-19 system and medical center to be used in playbook_

## Objectives or Key Results this is meant to further
- _Reduction in page count_
- _Document pages that can be created in a scalable manner_

## Tasks
_Complete review and determine webpages that will need to be included in system creation:_
- [ ] Eastern Oklahoma VA Health Care System (Jack C. Montgomery VAMC)
- [ ] Fort Harrison VA Medical Center
- [ ] Oklahoma City VA Health Care System
- [ ] VA Eastern Colorado Health Care System(ECHCS)
- [ ] VA Salt Lake City Health Care System
- [ ] Cheyenne VA Medical
- [ ] Miles City VA Clinic and Community Living Center
- [ ] Sheridan VA Medical Center
- [ ] VA Western Colorado Health Care System

## Acceptance Criteria
Create report of pages to be included in VISN-19 system/sites creation listed below:
* Eastern Oklahoma VA Health Care System (Jack C. Montgomery VAMC)
* Fort Harrison VA Medical Center
* Oklahoma City VA Health Care System
* VA Eastern Colorado Health Care System(ECHCS)
* VA Salt Lake City Health Care System
* Cheyenne VA Medical
* Miles City VA Clinic and Community Living Center
* Sheridan VA Medical Center
* VA Western Colorado Health Care System
