### ISSUE TITLE
Update DORA Metric page to reflect latest numbers

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#97475]
## Description
OCTO has asked us to update the numbers linked on [this page](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3409838085/Latest+Snapshot). 

---

### Tasks
- [ ] Gather latest numbers for vets-website, vets-api, content build
- [ ] Output numbers to the Confluence page

### Acceptance Criteria
- [ ] Latest numbers are available on the Confluence page.

**Comment by ben-allen-oddball** [comment]
Because of changes to deployment configurations linked to github actions is preventing deployment discovery.  So it is no longer possible to generate metrics based on API queries only.

I suggest evaluating Linearb, DataDog or Backstage which provide state and history management as well as the ability to tune the algorithm to suite the complex processes within the platform.  These tools also provide dashboards.
