### ISSUE TITLE
[FSR] Bug - Empty box 3

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97488]
## Issue Description
The "Specify why you are completing this form" box is appearing empty for VBA submissions
<img width="1087" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODNUQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7af2492448ac37549ee2bf1a0cf8ecd65f3273c0/image.png" alt="image.png" />

## Tasks
- [x] Attempt to recreate locally
- [ ] Identify root cause of issue
- [ ] Determine if it is effecting VHA submissions as well
- [ ] Fix the problem

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Box 3 is correctly populated for all submissions
- [ ] Box 3 is correctly populated in downloadable version of FSR

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points

**Comment by amponce** [comment]
Attached is the latest version a PDF that is missing the resolution options in box 3 [VA Form 5655 - Submitted (3).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0hVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbdecaa2f09c4726c3b12094f96fbd94dd4c6a6b/VA%20Form%205655%20-%20Submitted%20%283%29.pdf)

I verified that the options are being sent from the frontend to the backend without errors in the response for non-streamlined forms. Next, I need to verify the streamlined long forms.

<img width="1196" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2pVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa1189882be4434670e5f83fbc2d001906c729ff/Screenshot%202024-11-19%20151351.png" alt="Screenshot 2024-11-19 151351.png" />

**Comment by amponce** [comment]
We figured out the PDF box 3 issue: the BE server-side `transform_and_submit `object was missing `resolution_option`, `resolution_comment`, and `resolution_waiver_check `from the whitelist. The problem has likely existed since we enabled the `fsr_5655_server_side_transform` feature flag. It was difficult to detect due to the percentage-based rollout.
