### ISSUE TITLE
Update Feature Reference: Opens in a new tab

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#97484]
## Task Description

Update Feature reference once this [dev ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97372)is complete. This updates pages to change links so that they open in a new tab. 

## Notes and References
[Midpoint review feedback](https://github.com/orgs/department-of-veterans-affairs/projects/1214/views/9?pane=issue&itemId=87446015&issue=department-of-veterans-affairs%7Cva.gov-team%7C97271)
Must: open links inside the form flow in a new tab There's a link to Go to your VA profile in the scheduling flow. It should open in a new tab, and include (opens in a new tab) in the link text.

## Acceptance Criteria

- [x] Request flow confirm your contact information
- [x] DS flow confirm your contact information
- [x] CC flow confirm your contact information
- [x] Type of care page - no address alert
- [x] DS flow choose a location page when there's no address
- [x] CC request flow - choose a provider when there's no address

## Deliverables
- [ ] [Figma file](https://www.figma.com/design/HnExAM5SGNXzUlv9yRS87t/Working-File-%7C-Appointments-FE?node-id=2450-2698&node-type=canvas&t=nEcx4K8lmtZ4Ywx7-11)

**Comment by outerpress** [comment]
@melissa-lefevre testing a notification

**Comment by outerpress** [comment]
@melissa-lefevre the dev ticket is done so moving this one to "Ready"

**Comment by melissa-lefevre** [comment]
Done, closing!
