### ISSUE TITLE
[Eventbus Gateway] Create Github actions to build the image and push it to ECR

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#97499]
## Background
We need to be able to build a new container image and push it to ECR on every push to the main branch. This will allow EKS to pull the latest tagged image and deploy it to the kubernetes cluster. We can do this manually, but it is much simpler to create a new Github Action to automate this process

## Engineering notes
- Some of our repos use stored secrets in the Github repo to store credentials to authenticate with AWS
  - It appears that these repos create a new IAM user and create an access key for it. They then store the credentials for the access key as secrets in the Github repo and use them directly in the Github Actions
- Others assume an existing AWS role that has access to ECR and assume that role in order to be properly authorized to push to ECR
  - The role to assume is stored as a variable in the repo 

## Tasks
- [ ] Create the github action
- [ ] Determine which role to use / create in order to assume a role that has access to ECR

## Acceptance Criteria
- [ ] We are building an image and pushing it to ECR on every push to main
