### ISSUE TITLE
SC | Research Recommendations

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#97497]
## Value Statement

**_As a_** designer

**_I want to_** make updates to the SC design

**_So that_** we resolve some of the frictions found during research

---

## Background Context

We conducted research for the 2024 SC updates. The following recommendations require design changes.

- Keep the initial MST question and add language to clarify that the question is optional and does not impact the Veteran’s claim.
- Possibly remove the presumptive conditions alert within the form.
- It’s clear to Veterans within the introduction of the form that it covers PACT Act. Including the alert mid-form to re-emphasize presumptive conditions causes unnecessary friction, especially for Veterans who use screen readers.
- Adjust the wording around types of facilities to provide more information and clarity.
- Adjust the hint for the optional memorable date.
- Adjust the limiting consent screen to either make clearer that not providing input is an option, or position question to de-emphasize input.
- Revisit the list-and-loop pattern to create a clearer editing flow.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [x] Designs have been updated

## Designs and Build Notes

- Add here

### Enablement team (if needed)
@ member of team

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [x] Update MST question
- [x] Remove PACT alert, or make dismissable alert more obvious
- [x] Update 5103 notice
- [x] Update facility question
- [x] Update memorable date question
- [x] Update limiting consent question

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
Complete research readout, share design updates with Julie, get approval from PO

**Comment by eileen-coforma** [comment]
We got approval from Julie on the recommended changes.

**Comment by eileen-coforma** [comment]
Creating a related development ticket and closing this design ticket.

**Comment by eileen-coforma** [comment]
Development tasks are captured in #98304 Closing this as complete.
