### ISSUE TITLE
Add clinic name to calendar page

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#97495]
## Task Description
Update designs to include the clinic name on the calendar page of DS VistA flow. 

## Notes and References
This is to be consistent with the OH flow where we added the provider name to the calendar page. In the subtext we have  "Scheduling with [Provider name]
Times are displayed in Eastern Time (ET). "
[For reference here is an example of this](https://www.figma.com/design/EHR9zBpGnAgc7bHqeIGEoT/OH-Direct-Schedule-MVP-%7C-Appointments-FE?node-id=6437-42231&node-type=instance&t=oCecRcJuQw3olbws-11)

[Collab cycle ticket initiating this work](https://github.com/orgs/department-of-veterans-affairs/projects/1214/views/9?pane=issue&itemId=87446015&issue=department-of-veterans-affairs%7Cva.gov-team%7C97271)

## Acceptance Criteria

- [x] Create a design file in the [ working file](https://www.figma.com/design/HnExAM5SGNXzUlv9yRS87t/Working-File-%7C-Appointments-FE?node-id=2253-52311)
- [x] Get approval from a content specialist
- [x] Create a design spec for handoff 
- [ ] Make Dev ticket

## Deliverables
- [X] [Figma file](https://www.figma.com/design/HnExAM5SGNXzUlv9yRS87t/Working-File-%7C-Appointments-FE?node-id=2500-4252)

**Comment by melissa-lefevre** [comment]
![Image](https://github.com/user-attachments/assets/dca0f0f2-3285-46eb-afb0-cb2a35e37377)

**Comment by melissa-lefevre** [comment]
[Ticket for DEV](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98807)
