### ISSUE TITLE
AE-Sprint 23 (6.3.20-6.17.20)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#9750]
# Priorities
1. Finish remaining Profile 2.0 design tickets
2. Continue Profile 2.0 build 
3. Complete IA review
4. Complete internal QA tickets (if possible)
5. Complete LIH handoff collaboration session

### Design
Finish remaining design tickets and complete IA review
- [x] [Design] - Add state in DD where user hasn't set up but is eligible #8757
- [x] [Design] Create alert for when a user tries to leave page without saving #9435
- [x] [Design] Create an alert for if a user tries to edit multiple sections in the profile #9424
- [x] [Copy] Improve copy for "We can't access your military information" message in the profile #7553
- [x] [Design] Block users from entering edit mode if they are already editing a field #9784
- [x] Warn user when exiting edit mode with unsaved data #9769 
- [ ] Update content and link in Change Address page #8420

### Build
 Finish build and team verifies in staging things are working correctly before beginning official QA
- [x] [FE] Add test coverage to Connected Apps #9633
- [x] [FE] Remove Direct Deposit on the Profile 2.0 if users are not eligible #8571
- [x] Block users from entering edit mode if they are already editing a field #9766
- [x] Profile 2.0 sometimes edit view will be automatically exited very quickly #9764
- [x] [FE] Update Terms and Conditions content (account security) #9734
- [x] [FE] P&C and Account security email address updates #9727
- [x] [FE] Update Direct Deposit header/add education benefits #9733
- [x] Allow for text-only row in ProfileInfoTable #9785
- [ ] [FE] Build alert for if a user tries to edit multiple pieces of contact information #9433
- [ ] [FE]- Build alert for when a user tries to leave page without saving #9436

#### In Validation
- [x] [FE] Profile 2.0: Build the contact information section #5353 
- [x] FE] Bug- Direct Deposit v2 - focus is on Edit button on first launch #9075

#### Internal QA (stretch goal)
Will add as they are brought into the sprint
- [x] Add PropTypes to all remaining Profile 2.0. components #9771

### PM
- [ ] Complete Profile 2.0 IA review #9752 (ticket submitted)

### Unplanned
Remove `profile_show_receive_text_notifications` feature flag from FE #9781
FE - Contact Info - In the mobile numbers box, remove second unnecessary message #10035

## Logged-in homepage
- [x] Team handoff and collaboration session #9646
