### ISSUE TITLE
Ensure duplicate Redis `namespaces` are not being created

### ISSUE THREAD

**Issue by AshleyGuerrant** [department-of-veterans-affairs/va.gov-team#97502]
## User Story
As the maintainers of Vets API,
We need to ensure that there are no overlapping Redis namespaces in Vets API,
to avoid potential issues with data being overwritten and inconsistent behavior.

## Issue Description
In reviewing this [vets-api PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19331) - it was discovered there are multiple instances of `redis_namespace = Redis::Namespace.new('breakers', redis: $redis) `. The breakers issue is being addressed in #97500. We should ensure that there are no other instances of duplicate namespaces

This could cause data to be overwritten if they are using the same namespace, and potentially duplicate namespaces could be created elsewhere.

Note: In the past, we have attempted to trigger a breaker manually and within seconds it would re-trip. 

## Tasks
- [x] Review the code for duplicate namespaces to ensure they are not being created elsewhere in this [vets-api PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19331).
- [x] Follow up on items needing work.
- [x] Update the [Platform documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-guide-caching-with-redis-namespace-in-vets-) to give warning about duplicate namespaces or other helpful info or patterns to use. 

## Acceptance Criteria
- [x] All namespaces are reviewed
- [x] Duplicate namespaces are removed and mitigated
- [x] Documentation updated
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

---
```[tasklist]
### Related Tickets
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98148
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/97500
```

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note:** there was not enough bandwidth to start on this ticket, because a high-priority security bug was reported and the dev. needed to switch direction to focus on that #2146.

**Comment by rmtolmach** [comment]
### Notes
There are 13 instances of `Redis::Namespace.new` in vets-api. 
1. `app/models/concerns/redis_caching.rb` (and a similar version in `modules/mobile/app/models/mobile/v0/concerns/redis_caching.rb`):
```ruby
    def redis_config(config)
      @redis_namespace = config[:namespace]
      @redis_ttl = config[:each_ttl]
      @redis = Redis::Namespace.new(@redis_namespace, redis: $redis)
    end
```
This instance creates a new namespace based on parameters passed in. So then I looked to see where `redis_config` was used and it's used 4 times in `app/models` and used 4 times in `modules/mobile/app/models/mobile/v0`. All of the mobile ones look fine:
<img width="567" alt="Image" src="https://github.com/user-attachments/assets/754894c8-a38b-40da-aa47-de318b9dae9e" />
:bangbang: But the main app ones are all matching! Not good.
<img width="450" alt="Image" src="https://github.com/user-attachments/assets/e9217348-f9fa-4714-bfd2-349a9bc3f7f8" />
2. `namespace = Redis::Namespace.new('common_collection', redis: $redis)` from `app/services/mhv_account_type_service.rb` - seems fine–I don't see "common_collection" used as a redis namespace elsewhere.
3. `redis_namespace = Redis::Namespace.new('breakers', redis: $redis)` from `config/initializers/breakers.rb`. - seems fine–I don't see "breakers" used as a redis namespace elsewhere.
4. In `lib/chip/redis_client.rb`, the namespace is `"chip"`. LGTM.
```ruby
    def initialize(key)
      @redis_namespace = Redis::Namespace.new(namespace, redis: $redis)
      @key = key
    end
...
    def namespace
      @namespace ||= REDIS_CONFIG[:chip][:namespace]
    end
```
Rails console:
```
    vets-api(prod)> REDIS_CONFIG[:chip][:namespace]
    => "chip"
```
5. `session_config_key` used in `Redis::Namespace.new(REDIS_CONFIG[session_config_key][:namespace], redis: $redis)`  in `lib/common/client/concerns/mhv_locked_session_client.rb`
is defined in `lib/common/client/concerns/mhv_jwt_session_client.rb`
```ruby
        def session_config_key
          :mhv_mr_fhir_session_lock
        end
```
and in `lib/common/client/concerns/mhv_session_based_client.rb`
```ruby
        def session_config_key
          :mhv_session_lock
        end
```
and in `lib/medical_records/bb_internal/client.rb`
```ruby
    def session_config_key
      :mhv_mr_bb_session_lock
    end
```
Those are all unique.
6. `lib/common/models/collection.rb` uses `'common_collection'` :bangbang: which is already used. BUT, I don't see it when I print the `REDIS_CONFIG` in the console. 
```ruby
CACHE_NAMESPACE = 'common_collection'
...
@redis_namespace ||= Redis::Namespace.new(CACHE_NAMESPACE, redis: $redis)
```
7. `lib/common/models/redis_store.rb`
```ruby
    def self.redis_store(namespace)
      @redis_namespace = Redis::Namespace.new(namespace, redis: $redis)
    end
    delegate :redis_namespace, to: 'self.class'
```
When I search `redis_store REDIS_CONFIG`, there are 34 results
8.
9.
10.
11.
12.
13. 
From printing and inspecting `REDIS_CONFIG` in the rails console (there are 64 total). These are the only duplicates:
```
:okta_response=>{:namespace=>"okta-response", :each_ttl=>3600},
:okta_response_app=>{:namespace=>"okta-response", :each_ttl=>86400},
```
Would there be any namespaces _not_ listed in the REDIS_CONFIG? Why am I not just searching `config/redis.yml`? Or only looking at `REDIS_CONFIG`? There is a duplicate mentioned there (it's also in redis.yml).

**Comment by rmtolmach** [comment]
## Notes on notes
In the bullet points, I'm referencing the numbers from my large comment above where I did the investigation. These are the ones that require action:
- Num. 1: `redis_config REDIS_CONFIG[:secure_messaging_store]` is repeated four times in four files. Exists in redis.yml.
- Num 2 & 6: A redis namespace with `'common_collection'` is created twice. Doesn't exist in redis.yml.
- Num 7: A redis namespace with `va_mobile_session` is created twice. Exists in redis.yml.
- `REDIS_CONFIG`/`redis.yml`: `okta-response` is there twice.

**Comment by LindseySaari** [comment]
@rmtolmach Comments on Notes on notes

1. Is redis_config REDIS_CONFIG[:secure_messaging_store] just referencing the config or doing a full Redis.new? I think we're just concerned about it being re-initialized
2 & 6: We probably want to fold this into the redis.yml unless there's a reason to not. Also, it seems like a duplicate, so we want to address that part as well
7. Let's get in contact with this team and also address the duplicates
REDIS_CONFIG/redis.yml: Let's get in contact with this team as well and remove/change the duplicate `okta-response`

**Comment by rmtolmach** [comment]
Confluence page created so we can comment easier: https://vfs.atlassian.net/wiki/spaces/PPT/pages/3727753220/Duplicate+Redis+namespaces

**Comment by rmtolmach** [comment]
- PR to https://github.com/department-of-veterans-affairs/vets-api/pull/20063. This takes care of 1/4 of the duplicates.

**Comment by rmtolmach** [comment]
✅ Documentation updated. I added [the alert ⚠ in this section](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2806775890/How-to+Guide+Caching+with+Redis-Namespace+in+Vets+API#Using-the-gem-in-vets-api).

The final thing we're waiting on is a response to my message in #mhv-secure-messaging. The point of contact may be out of office for the rest of the week.

**Comment by rmtolmach** [comment]
✅ handed off `secure_messaging_store` to MHV. They will take on any necessary work. [Slack thread](https://dsva.slack.com/archives/C03ECSBGSKX/p1735922739879149?thread_ts=1735834649.319589&cid=C03ECSBGSKX) for details. Done with all tasks, moving to Review.

**Comment by rmtolmach** [comment]
Lindsey [reviewed](https://adhoc.slack.com/archives/C045LCF8WU8/p1735928938831329?thread_ts=1735924940.356049&cid=C045LCF8WU8). Closing 🎉
