### ISSUE TITLE
Address issue with duplicate breakers Redis namespaces

### ISSUE THREAD

**Issue by AshleyGuerrant** [department-of-veterans-affairs/va.gov-team#97500]
## User Story
As the maintainers of Vets API,
We need to ensure that there are no overlapping Redis namespaces in Vets API for the **breakers** namespace,
to avoid potential issues with data being overwritten and inconsistent behavior.

## Issue Description
In reviewing this [vets-api PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19331) - it was discovered there are multiple instances of `redis_namespace = Redis::Namespace.new('breakers', redis: $redis) `. The Redis namespace is being used as a breaker and it is initialized 3 times ([also in this line](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/meb_api/config/initializers/breakers.rb#L13) and in [this line](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/breakers.rb#L43)).

Breakers::Client should not have to be re-initialized [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/meb_api/config/initializers/breakers.rb#L22). MebApi::DGI service should be added to the [breakers initializer](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/breakers.rb).

#### Background
- There have been some issues around manually triggering a breaker.
- [redis-namespace](https://github.com/resque/redis-namespace) (official documentation)
- [How-to Guide: Caching with Redis-Namespace in Vets API](https://vfs.atlassian.net/wiki/x/UgBMpw) (internal documentation)

## Tasks
- [x] Add MebApi::DGI to the[ breakers initializer](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/breakers.rb)
- [x] Remove Breakers::Client references in the [MebApi::DGI initializer](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/meb_api/config/initializers/breakers.rb)
- [x] Condense ~VYE~ meb-api breakers namespace with namespace in main app
- [x] Ensure Vets API is functioning properly
- [x] Potentially try to trigger a manual breakers outage

## Acceptance Criteria
- [x] Breakers namespaces are condensed
- [x] Ensure Vets API is functioning properly
---

## Validation
The My Education Benefits team validated it [See this Slack thread](https://dsva.slack.com/archives/C075DBTEYSH/p1733153805279599?thread_ts=1732913709.548459&cid=C075DBTEYSH).

---

### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98148
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/97502
```

**Comment by rmtolmach** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/19660

I'll want to get the My Education Benefits team to review. I reached out [in Slack](https://dsva.slack.com/archives/C075DBTEYSH/p1732913709548459).

I'm looking for ways to test this.
