### ISSUE TITLE
Static page wizard re-design research plan step 1

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#97507]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

We need to edit or rewrite the research plan we worked on previously. 
The new study will be evaluative. 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [ ] Write research plan
- [ ] Post to GitHub

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [ ] Posted to GitHub

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by charlottecesana** [comment]
Update: we were notified the Wizard design should change back to the Wizard experience after all. The team is working on pivoting back to the original design and prototyping. We might maintain the original [research plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/wizard/research/research-plan-complete-a-subtask.md) we wrote. 
cc: @mgleo
