### ISSUE TITLE
Troubleshoot E2E code coverage implementation

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#97512]
Code coverage tools have been installed, but the reports are not generating as expected (showing 0 coverage). We need to figure out where the problems here are.

## Tasks
- [x] Troubleshoot nyc_output directory not being created.
- [x] Troubleshoot nyc_output directory not being able to be located.
- [x] Troubleshoot code not being instrumented

## Acceptance Criteria
- [x] Existing errors have been resolved.

**Comment by CBonade** [comment]
Follow-on ticket for remaining errors here: https://github.com/orgs/department-of-veterans-affairs/projects/927/views/1?sliceBy%5Bvalue%5D=CBonade&pane=issue&itemId=89710826&issue=department-of-veterans-affairs%7Cva.gov-team%7C98310
