### ISSUE TITLE
Create VHA-copay archetypes methodology PDF and post to GitHub

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#97510]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

- Create VHA-copay archetypes methodology PDF and post to GitHub
---
## Tasks
- [x] _What work is necessary for this story to be completed?_
- [x] Create in Figma
- [x] Post to Github 

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
- [x] Posted to Github
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by charlottecesana** [comment]
[The final document is published on Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/research/VHA-Copay-Veteran-archetypes/VHA%20Copay%20Veteran%20Archetypes%20final.md)

The LOE ended up being 3 points.
