### ISSUE TITLE
Review codescanning alert list in vets-website

### ISSUE THREAD

**Issue by IGallupSoCo** [department-of-veterans-affairs/va.gov-team#97525]
## Issue Description

The work on epic #95676 would benefit from a manual review against the list of [Code scanning issues on vets-website](https://github.com/department-of-veterans-affairs/vets-website/security/code-scanning).  Issues are not always automatically resolved when the listed vulnerabilities get addressed via PRs.

---
## Tasks
- [x] Review the codescanning alert list
- [x] Create tickets for any CRITICAL alerts
- [x] Pull requests have been generated with automated fixes for each HIGH-severity alert

## Acceptance Criteria

- [x] The codescanning list has been updated, with any redundant or obsolete alerts removed
