### ISSUE TITLE
Review and update current list of Dependabot alerts

### ISSUE THREAD

**Issue by IGallupSoCo** [department-of-veterans-affairs/va.gov-team#97520]
## Issue Description

The work on epic #95676 would benefit from a manual review against the list of Dependabot issues on vets-website.  Issues are not always automatically resolved when the listed vulnerabilities get addressed via PRs.

---
## Tasks
- [x] Clean up the Dependabot alerts list
- [x] Any dangling alerts that are not tied to Node are added to the epic

## Acceptance Criteria

- [x] The existing epic accurately tracks any remaining CRITICAL or HIGH alerts in need of evaluation
- [x] The Dependabot alerts list has been accurately updated
