### ISSUE TITLE
Investigation & Fix: Allow Service End Date more than 180 days in the future

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97538]
## Issue Description
As a VFS team member I want to investigate and fix this issue so that it can be released to Veterans.

Previously, the validation preventing BDD dates >180 days in the future was added to prevent a silent failure caused by an unaccounted for logical branch in `/applications/disability-benefits/all-claims/validations.js` caused by usage of `isReserves` and `isBDD`

We need to verify if this is still the case, and if so, resolve the issue that removing the >180 day validation would cause

This is a complementary ticket to
#97344

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Implementation for this is known and understood and documented in this ticket
- [ ] The fix could be released by means of #97344

## Additional Information
Unknown: Does LH have any restrictions on future dates?

Active reservists can have contracts that extend many years, like active duty members, but they are not on active duty (most of the time) and are therefore eligible to apply for and receive benefits even though they remain an active reservist. Active reservists are the folks who serve one weekend a month and a two week period each year, but could be activated to active duty for longer periods as well. That's a lot of "actives" in that explanation so if it doesn't make sense, let me know. This is not a BDD flow.

Since this is blocking Veterans from entering proper data or affecting benefits, it is "purely" prioritized above improvements to 5103/signature/confirmation page and should go before those. However, there's always a cost to dropping work and coming back to it so we can be sensible about the sequencing and not treat it as an emergency.

On the paper form for boxes 21c and 22c we should never limit the entries, even on BDD claims. BDD claims are submitted while still on active duty, but the service member may still have a reserve commitment beyond 180 days, even after the active duty commitment ends

Q: Should this logic of "release the restriction of the date" be for all "types" of claims? Even non-reservist or BDD? In other words, should the time restriction logic be removed completely from this service date range question?
A: Yes, the restriction should be totally removed.

We'll have to make sure there's nothing upstream in the submission process preventing date restrictions (i.e. nothing else is checking dates in those fields for future date restrictions).

**Comment by pacerwow** [comment]
closed as dupe
