### ISSUE TITLE
[COPAYS] Get Becky Gradle example payloads so she can examine "Account Number"

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#97535]
In preparation for our coming Copay work, Becky has asked for current copay payload examples to help her triangulate data points she's seeing on her end.            

## Tasks
- [ ] Login to prod and pull example payloads for Becky

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance Criteria
- [ ] Payloads sent to Becky via encrpyted email

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by digitaldrk** [comment]
Email with payload sent via encrypted email.

Also pinged Becky in slack
