### ISSUE TITLE
Community Care Re-enable (by Aug 17th) & drive-time (Aug 28th)

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9753]
Per the approval of the Office of Community Care, VAOSR can reenable Community Care requests on August 14th, 2020.

When a Veteran logs into VAOSR on VA.gov, they should be able to request a community care appointment for their specified care if eligible. 

## Goals / Outcomes
- Upon reenable, we want to see a high % of successful community care appointment submissions if Veteran selects the CC path
- One July 6th drive-time should be enabled within CCE API and being used as part of the CC eligibility requirement

---
## Definition of done
- [ ] Content on static appointments page needs to be updated to include Community Care content
- [ ] Re-test existing flow:
    - [ ] If Veteran is not CC eligibility, Veteran advanced to VA request or VA self-schedule workflow based on VATS configuration
    - [ ] If Veteran is CC eligible due to E&E code and registered to at least one facility with CC enabled, Veteran is able to request a CC appointment
    - [ ] If Veteran is CC eligible based on drive-time AND they're registered at least one facility with Community Care enabled, Veteran is able to request a CC appointment
    - [ ] If Veteran is eligible for Community Care based on drive time AND none of the facilities where they're registered have Community Care enabled, redirect them to the VA appointment workflow

## Issues to create within this Epic
- [x] Content update ticket for static VA.gov appointments page
- [ ] Reenable & test CC flow
- [ ] CC drive-time / CCE eligibility test?
- [x] (potentially) If the results from the Community Care API indicate that the residential address is a "P.O. Box", display a message informing the user to enter a valid street address must be entered and include the link to va.gov."
