### ISSUE TITLE
Implement new Domo Dataset, replace 'BQ - All MyVA Users, Pageviews and Events 2' with updated dataset

### ISSUE THREAD

**Issue by Blivaditis** [department-of-veterans-affairs/va.gov-team#97537]
**Description**

This ticket is to replace all instances of this [dataset](([BQ - All MyVA Users, Pageviews and Events 2](https://va-gov.domo.com/datasources/bdc0655a-8fbd-41a5-8919-9b79d9fc780b/details/data/table) in the charts it powers. A new [dataset](https://va-gov.domo.com/redirect-to-datasource-details/0f767e9e-dfd7-44db-8ab2-5c33a3e3a757) has been created which filters out all instances of API Calls from the original, removing 900 million rows of unneeded data. 

The dataset is populating with proper row counts and the correct metrics. While reviewing the dataset I noticed that event_action is errored, it uses the new GA4 event action metrics and not Data layer event name. This issue will be reviewed and fixed (either before or after implementation of the new dataset) 

**Tasks**

- [x] QA -- create duplicates of the existing cards, and test them with the newly created dataset, to ensure they are still functional

- [x] Change existing cards that used old dataset to the new one.

- [x] Update event_action and reload the data

- [ ] Delete the old, original dataset, BQ - All MyVA Users, Pageviews and Events 2

**Acceptance Criteria**

- [x]  ] New dates has proper metrics and dimensions 

- [x] Domo cards are functional, and powered by the new dataset.

- [ ] Old dataset is deleted, no cards are impacted by the deletion.

**Comment by johnny-jesensky-adhoc** [comment]
Moving this to Done -- will be demo'ing this work in Platform Demo today.

FYI @Blivaditis
