### ISSUE TITLE
Review/Update Platform unit test documentation

### ISSUE THREAD

**Issue by IGallupSoCo** [department-of-veterans-affairs/va.gov-team#97547]
## Issue Description

At the request of other Platform engineers on behalf of VFS teams as a pain point during unit test development, I will set some time aside to make the unit test guidance more robust, and to address some recurring issues with specific pain points that have been brought up by the FE CoP.

---

## Tasks

- [x] Review the existing documentation and note some potential points of change
- [x] Update the documentation with that new info

## Acceptance Criteria

- [x] Documentation has been updated and published

**Comment by IGallupSoCo** [comment]
Linking this to #97217

**Comment by IGallupSoCo** [comment]
Some initial thoughts:

It would be be nice to set some firmer expectations on where tests are stored.  Not because Mocha needs it to run faster, but for other engineers who are manually looking at the code.

It could be handy to have an example of a good unit test vs a less ideal test

I would address established issues when testing elements within the shadow DOM, which I am 70% sure is relevant to unit tests and not e2e tests.

**Comment by IGallupSoCo** [comment]
Do the four pages nested beneath this primary unit test document need review as well?

**Comment by IGallupSoCo** [comment]
We have a [nested page on the use of the Enzyme utility](https://depo-platform-documentation.scrollhelp.site/developer-docs/example-unit-test-enzyme) for its unit testing features, such as shallow rendering of elements under test.  It appears that vets-website is using React@17.0.2, which is new enough that there is an Enzyme adapter in beta for it.
