### ISSUE TITLE
[Design Debt] Update Production Figma file to reflect no Pre-check-in/Check-in for VVC and CVT

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#97567]
## Background

We need to make sure our Production Figma files clearly indicate that we do not currently have Pre-check-in and Check-in turned on for VVC and CVT appointments. 

## Tasks
- [x] Update Production Figma file to indicate that BOTH Pre-Check-in and eCheck-in are turned off for all but in-person appointments 
  - [x] (Consider: Do we leave the screens variations in the file, but make it clear they are not active? Or do we remove them from our production file entirely?)
- [x] Let Kristen know about the updates

## A/C
- [x] Designs in Production design file match prod
- [x] [Check-in](https://www.figma.com/design/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-PCI?node-id=0-1&t=kJVPFTQ7b1xJxOiK-1): 
         https://www.figma.com/design/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-PCI?node-id=0-1&t=kJVPFTQ7b1xJxOiK-1
- [x] [Pre-check-in](https://www.figma.com/design/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-PCI?node-id=239-860&t=kJVPFTQ7b1xJxOiK-1): 
         https://www.figma.com/design/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-PCI?node-id=239-860&t=kJVPFTQ7b1xJxOiK-1

**Comment by cgednalske** [comment]
@loripusey this came up at our UX sync today. We should double check that our Prod designs are accurately reflecting prod. If it's accurate right now, we might have some pre-check-in messaging that doesn't quite line up for VVC and CVT appointments. It sounds like Kristen would like I to check this very soon so that IVC can know the status of where things are with those appointment types.

Probably falls in the tech debt camp, but maybe Zach can address this before other tech debt and annotations items.

**Comment by loripusey** [comment]
I'm confused, we turned off Pre-Check-in and eCheck-in for everything except in-person appointments, so why are we doing this exercise? Maybe PL today.

**Comment by cgednalske** [comment]
Ah! Ok, perfect. I couldn't remember where things were at with that. So we should still do this review because our Prod designs don't indicate that they're turned off, but more of just a housekeeping thing for us in that case 👍 (not a big lift at all - we'll just need to indicate that those are turned off right now).

**Comment by cgednalske** [comment]
@loripusey I updated the ticket accordingly. Let me know if anything else seems weird, but it's now focused on just making sure our designs indicate Pre-check-in and Check-in are turned off for anything other than in-person appointments.

**Comment by cgednalske** [comment]
@zach-park this turned out to be more of a housekeeping thing. Do you want to add your estimate? My vote is a 1‍⃣

**Comment by zach-park** [comment]
> [@zach-park](https://github.com/zach-park) this turned out to be more of a housekeeping thing. Do you want to add your estimate? My vote is a 1‍⃣

I'm also voting 1‍⃣ :)

**Comment by zach-park** [comment]
@cgednalske, ready for validation. Notes were added to both PCI and CI. And the CVT/VVC are kept in the Production Figma file:
https://www.figma.com/design/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-PCI?node-id=3268-21360&t=9UaPAigkypdhH70t-1
https://www.figma.com/design/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-PCI?node-id=3046-7720&t=9UaPAigkypdhH70t-1

**Comment by cgednalske** [comment]
@zach-park wondering if these can more clearly be called out - like by putting one of the grey overlays over the related screens?

**Comment by zach-park** [comment]
Updated!

**Comment by cgednalske** [comment]
@zach-park thoughts on making the box a (minimal) overlay on top of the screens rather than behind? Wondering if that'd help visually indicate they are not turned on while still keeping them kind of visible. I recall you've done this elsewhere with some designs lately. 

Currently, the dark box behind draws more attention to those screens than the other screens, which I'm not sure we want.

**Comment by zach-park** [comment]
> [@zach-park](https://github.com/zach-park) thoughts on making the box a (minimal) overlay on top of the screens rather than behind? Wondering if that'd help visually indicate they are not turned on while still keeping them kind of visible. I recall you've done this elsewhere with some designs lately.
> 
> Currently, the dark box behind draws more attention to those screens than the other screens, which I'm not sure we want.

I updated it and I think I did it right this time. So please let me know. Thank you!
