### ISSUE TITLE
[UX(done), FE, QA] 10-10CG - Facilities: Update search bar error message content

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#97565]
## Benefit to the Veteran
As a Veteran and/or Caregiver, I want to receive clear messaging when encountering an error on the facilities search page, so that I can correct the error and move on through the form.

## Background
During research sessions and testing on Mobile devices, after entering a zip code the user is tapping the "Continue" button, causing confusion when the error message appears. The user is not selecting the search/magnifying glass icon/button and receiving an error message stating they must make a selection, even though there are no search results appearing yet.  This does not occur much on the Desktop view.
![Image](https://github.com/user-attachments/assets/9e153225-8719-4896-8b9c-b38c80462c99)

## Scope
- In Scope
     - Update the search bar error messaging to be more clear on how to correct the issue when they have not yet performed the actual search (using the search button)
- Out of Scope
     - We will not be updating the search results error message content, as that applies when the results are on-screen.

## Tasks
- [x] [UX] Review with CAIA on improved content for the error message, as well as determining the best type of alert design
- [x] Review with the team (can be async)
- [x] [UX] Update designs with new content & style
- [ ] [FE] Update UI to match designs
- [x] [QA] Complete testing to validate
     - Error message content and style match
     - Error message triggering appropriately
     - Mobile view matches design and expectations
     - No new accessibility issues are introduced with this change
- [ ] Review any findings with team, if needed
- [x] QA/PM Signoff is required in the comments

## Acceptance Criteria
- The search bar error messaging has been updated to clearly inform users on how to correct the error.

**Comment by jessicastump** [comment]
[This section in Figma](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=3575-13915&t=UhOuFxMf1S1Fqlbq-4) shows the content recommendations from CAIA for the error messages and screen capture below. 
Note: The Figma link contains an accumulation of ALL the various content updates and the refined 2 directions for the search button after Platform design office hours. 
![Image](https://github.com/user-attachments/assets/a1b26e10-4310-4cd5-b166-6e654777feb9)

The error when search is empty (aka the user clicked continue instead of the search button): 

> You need to enter a city, state, or postal code. Then select the “Search” button.

The error message when a search is made but no facility selected: No changes

> Select a medical center or clinic

**Comment by jessicastump** [comment]
@hdjustice and @aagosto90 - I think (maybe) these are the final content changes from Aliyah on this so we can review async ... the search button on mobile direction is still pending so that might not be accurate in the above screen captures.

**Comment by hdjustice** [comment]
I like this.  The things I am thinking of is whether users equate the Search button with the magnifying glass, but I might be way off base with that.  Also, for the most part, our form is very good on mobile but wasn't there feedback or even in the session where the person couldn't see the search/magnifying glass button?

**Comment by jessicastump** [comment]
Yes, they didn't realize the input was a search. Not sure if the content helps with that or if we can see if it is possible via design system to a/b test both maybe? Can that be done in production?

**Comment by jessicastump** [comment]
Updated images - same content just the route showing the **mobile** search button as is/per design system.

@hdjustice - I don't think these error messages were mentioned during Staging Review looking through the spreadsheet, but content/design should be ready for whenever :) 

--

![Image](https://github.com/user-attachments/assets/fb7ff3be-96aa-430f-8c3d-03c9f65cda38)

--

![Image](https://github.com/user-attachments/assets/a3153b78-f502-4d81-a86c-ad377e2037ff)

--

![Image](https://github.com/user-attachments/assets/c14ca819-8482-4309-a471-6f05ff7d41cb)

**Comment by hdjustice** [comment]
you are right, there was no mention of the error messages, but I don't think they would have an issue with us making the one more specific.

**Comment by jessicastump** [comment]
@hdjustice - These error messages are done (content/design) and ready for engineers :)

**Comment by allanto-ah** [comment]
Environment: Staging

Verified the updated search bar error messages

<img width="951" alt="Image" src="https://github.com/user-attachments/assets/f7f892f2-41cf-4fe6-9757-77029c09dd64" />
<img width="917" alt="Image" src="https://github.com/user-attachments/assets/d5aa6a0f-897b-4d1a-9dec-9be934296d6b" />
<img width="895" alt="Image" src="https://github.com/user-attachments/assets/417e0836-5582-44ec-ad8d-e920e6c7f8e0" />
