### ISSUE TITLE
[VETS-API] Update Prawn / Re-create test PDFs

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#97579]
During the investigation of Prawn, It seems that our way forward is to simply re-create the ~15 test PDFs to get the tests to pass. Once done, we should visually compare them to confirm they look okay, and once merged to staging, run a few tests (with the help of VFS teams that utilize these libraries, if possible)

## Tasks
- [ ] Re-create necessary test PDFs to get specs passing
- [ ] Visually inspect/compare new/old files
- [ ] Test in staging with VFS team(s)

## Acceptance Criteria
- [ ] Prawn 2.5.0 is deployed to production
