### ISSUE TITLE
Create Initial Walkthrough for "Search for my VA representative"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9757]
## Goal
Based on existing product documentation, high-level thumbnail workflows, and our experience with other VA Search work, we need to start thinking about how Search workflows will look on regular screens for "Search for a representative."

## Tasks
- [x] Build out the necessary screens for Representative search that show its first happy path based on an authenticated Veteran
- [ ] Build out the remaining screens for other log in states, users.

## Acceptance Criteria
- [x] An initial prototype or wireframe has been created and shared with the team.

**Comment by sporeboy** [comment]
Walkthrough/low-fi wireframe is here: https://xd.adobe.com/view/612eab1b-3f29-4fa4-43c5-2f21deb912e3-171f/screen/e15816ba-c121-4b95-a49f-8da85fb216c4/View-Appoint-POA-Flow-1

Search concept 1: https://xd.adobe.com/view/fe3c02e8-a803-4a02-7a76-14c7dcad4a48-880d/screen/25f19aea-7630-473e-811e-3cb995869ff1/21-22-Search-Tool-1

Results concept 1:  https://xd.adobe.com/view/fe3c02e8-a803-4a02-7a76-14c7dcad4a48-880d/screen/63bcd2e9-accf-432c-8387-06c491592e8a/21-22-Search-Results-1
