### ISSUE TITLE
Architecture Intent

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#97573]
## Background
Platform documentation: https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent

We qualify because we will be integrating with a new API: the Accreditation API from GCLAWS.

## Tasks
There are 2 required artifacts:

- [ ] Complete the [Architecture Intent Meeting Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/collab-cycle/architecture-intent-meeting.md).
- [ ] Save Architecture Diagrams in the [Diagrams folder in the Sensitive Repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/platform/engineering/collaboration-cycle/architecture-intent/diagrams).
- [ ] Create a [user data flow diagram](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-create-a-user-data-flow-diagram.md) if your application accepts data from a user.
- [ ] Use [Calendly](https://calendly.com/collaboration-cycle/architecture-intent?month=2024-09) to schedule an Architecture Intent touch point.

## Acceptance Criteria
- [ ] An Architecture Intent has been scheduled.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/va.gov-team/pull/104644

**Comment by holdenhinkle** [comment]
This is done. At least the doc is done. It seems like I should whip up a quick architecture diagram. Should take me 15-20 mins.

**Comment by holdenhinkle** [comment]
Graph (online tool to generate the image below - https://www.planttext.com/#google_vignette)

```
@startuml
autonumber

actor "Scheduler" as scheduler

participant "QueueUpdates Sidekiq Job" as queue_updates
participant "PostgreSQL Database" as postgres
participant "Accreditation API" as accreditation_api
participant "Lighthouse Address Validation API" as address_api
participant "Update Sidekiq Job" as update_job

scheduler -> queue_updates : Trigger Daily Job

queue_updates -> accreditation_api : GET Paginated Results\n(Agents, Attorneys, Reps, Orgs)
accreditation_api --> queue_updates : Return Paginated Data

queue_updates -> queue_updates : Iterate through pages\nStore data in memory

queue_updates -> postgres : Query Existing Records\nby unique identifier (e.g., registration_number)
postgres --> queue_updates : Return Matching Records

queue_updates -> queue_updates : Compare Records\nIdentify New/Updated Records

queue_updates -> update_job : Enqueue Batch for Processing

update_job -> address_api : Validate Address\n(if new or changed)
address_api --> update_job : Return Validated Address

update_job -> postgres : Upsert Records\n(Insert/Update All at Once)
postgres --> update_job : Confirm Update/Insert

scheduler -[#red]-> queue_updates : Next Day Trigger

@enduml
```

![Image](https://github.com/user-attachments/assets/f468424e-33f4-4092-bf3a-6d4b8e757577)

Here’s the **supplemental explanation** that aligns with the updated architecture diagram.

---

# **Supplemental Explanation of the Workflow**

## **Actors Involved**
- **Vets-API Server**: The main application that interacts with external APIs and databases.
- **Sidekiq Server**: Handles background job processing with two separate jobs:
  1. **`QueueUpdates` Job**: Fetches accreditation data, compares it to existing records, and queues updates.
  2. **`Update` Job**: Processes updates, validates addresses, and inserts/updates records in the database.
- **PostgreSQL Database**: Stores accreditation records.
- **Accreditation API**: Provides accreditation records.
- **Lighthouse Address Validation API**: Validates addresses for accreditation records.

---

## **Process Overview**
A **daily scheduled Sidekiq job** (`QueueUpdates`) is triggered to fetch accreditation data, compare it against existing records, and queue updates. A second Sidekiq job (`Update`) is responsible for processing the updates.

### **1. Fetch Accreditation Data (`QueueUpdates` Job)**
- The **QueueUpdates** Sidekiq job runs daily and calls four Accreditation API endpoints:
  - `GET /api/v2/accreditations/Agents`
  - `GET /api/v2/accreditations/Attorneys`
  - `GET /api/v2/accreditations/Representatives`
  - `GET /api/v2/accreditations/VeteranServiceOrganizations`
- Each API response is **paginated**, and the job iterates through all pages to retrieve all records.
- The fetched data is **temporarily stored in memory**.

### **2. Compare and Identify New or Changed Records**
- The job processes the fetched records in **chunks**.
- An **ActiveRecord query** retrieves existing records in bulk using a **unique identifier** (e.g., `registration_number`, though the actual column may differ):
  ```ruby
  Representatives.where(unique_identifier: [1, 2, 3])
  ```
- Each fetched record is compared against its corresponding record in the **Representatives** or **Organizations** table.
- If a record is **new** or has **changed**, it is added to an array (e.g., `new_or_changed_records`).

### **3. Queue Updates for Processing**
- The **QueueUpdates** job processes the `new_or_changed_records` array in **chunks** and enqueues batches for the `Update` Sidekiq job.

### **4. Validate and Upsert Data (`Update` Job)**
- The `Update` Sidekiq job processes each batch of records by:
  1. **Validating addresses** for new or changed records using the **Lighthouse Address Validation API**.
  2. **Transforming data** to match the structure of the database.
  3. **Performing a bulk upsert** (insert/update operation):
     ```ruby
     Representatives.upsert_all(array_of_shaped_data)
     ```
  4. **Confirming successful updates** in the PostgreSQL database.

---

## **Key Benefits**
✅ **Efficient API Data Retrieval**: Uses batch processing and in-memory storage.  
✅ **Optimized Database Queries**: Fetches existing records in bulk to minimize query overhead.  
✅ **Incremental Updates**: Only new or modified records are updated, reducing unnecessary writes.  
✅ **Batch Processing**: Minimizes Sidekiq job load by processing updates in chunks.

---

This **clear separation of concerns** between `QueueUpdates` and `Update` ensures that the system remains **scalable, efficient, and easy to debug**. 🚀 Let me know if any refinements are needed!

**Comment by holdenhinkle** [comment]
Whoops, I put the PR in the wrong repo. Here's the correct one - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/2287

**Comment by holdenhinkle** [comment]
@oddball-lindsay , this is done. Should we schedule the meeting together?

**Comment by holdenhinkle** [comment]
Notes from yesterday's Architecture Intent Review:

What if OGC is down? Are we notified?

---

NICE TO HAVE
What happens if a large number of records go missing?
What happens if a large number of records suddently need to be updated?
Set alerts and a tracking mechanism for number of each kind of diff per day. Learn 'what looks normal' over time. Setup some percentages of what "doesn't look normal" initially. Have each scenario detailed in a Playbook. Eg: What do we do if a large number of records go missing in an update? Who can we contact to confirm that's everything is okay?

---

A soft delete flag is fine. No need to encrypt any of the fields on soft-delete. Keep soft-deleted records for 1 year, then hard-delete them:
Sam Raudabaugh (Mar 17, 2025, 5:16 PM)
Looking at the MOU it specifies a 1 year retention period of audit trails for both parties
Joe Niquette (Mar 17, 2025, 5:17 PM)

---

Make sure retries are cancelled before the next day's Sidekiq job starts.
Cancel any Sidekiq retries from previous day's jobs.

---

POSSIBLE EDGE CASE (more for attorneys and claims agents):
Jen B (Mar 17, 2025, 5:07 PM)
Is there a scenario where Oren's team needs to send a VA Notify email to the Veteran if a requested representative becomes unaccredited during the 60 days?

You (Mar 17, 2025, 5:07 PM)
Yes, this is an edge case to consider Jen.

Jen B (Mar 17, 2025, 5:07 PM)
Although, the POA request is technically at the org level, not the rep level

Jen B (Mar 17, 2025, 5:07 PM)
So someone else from the org could still accept

I do recommend confirming with OGC your data retention standards/requirements. If they dont have anything then you should set something and follow it.

---

Put this behind a feature flag

**Comment by holdenhinkle** [comment]
Notes added to Architectural Intent doc - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/2300
