### ISSUE TITLE
vets-api helm chart - common volumes into parent helm chart

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#97588]
Move common volumes into parent helm chart

## Tasks
- [ ] vets-api-mockdata
- [ ] clamav-volume
- [ ] dbsocket
- [ ] remove from manifest helm charts

## Acceptance Criteria
- [ ] app running in all environment with these three volumes set up in from parent helm chart
