### ISSUE TITLE
vets-api helm chart - move socat proxy into parent helm chart

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#97589]
the socat proxy runs in all environments - so push to parent helm chart

- note - a few values vary by environment - set these up to be settable via values.yaml override

## Tasks
- [x] Add socat proxy to parent helm chart
- [x] remove socat proxy from dev helm chart
- [x] remove socat proxy from staging helm chart
- [ ] remove socat proxy from prod helm chart
- [ ] remove socat proxy from sandbox helm chart

## Acceptance Criteria
- [ ] socat proxy running in all environments from the parent helm chart

**Comment by JoeTice** [comment]
Work is in progress, and being reviewed - but delays on reviews/approvals is delaying closure
