### ISSUE TITLE
ARP Contact Update Tool Ramp-up

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#97584]
## Background
Review designs and prior research for ARP Contact Update Tool. Determine if additional research and design are needed.

## Tasks
- [ ] Review prior research
- [ ] Review prior designs
- [ ] Meet with stakeholders (Lesley)
- [ ] Draft recommendation

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
[Contact Info Updates Resources.docx](https://github.com/user-attachments/files/17847889/Contact.Info.Updates.Resources.docx)

**Comment by jfinnerty13** [comment]
- [Notes from OGC meetings](https://dsva.slack.com/docs/T03FECE8V/F078CNNHQU9) (Slack Canvas) Meetings from regular discovery meetings ARF had with OGC in June and July 2024. These meetings helped us understand the problem and policies related to updating representative’s contact information.
- [Current and future state](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717174574592/c341950387ab12e53dc358182f0c84774e94efb2?sender=u8cf3f08a008c2b61ad621433) (Mural) These service blueprints were created by ARF in collaboration with subject matter experts from OGC. The current state has been validated, and as of August 2024 the future state is still a work in progress as we work more with OGC, conduct more research with VSO, certifying officials, and agents, and consider scope and technical feasibility.
- [Contact updating flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720800350435/11ddeed005714571717010aa00c2bdb6def343ac?sender=u8cf3f08a008c2b61ad621433) (Mural) Rough, basic flows of what we imagine designing and building to allow representatives to update their contact information. These were based on the future state map and used as a starting point to create mockups in Figma.  
- [Contact updating prototypes](https://www.figma.com/design/RbVQnV4eBl2K1Z5xRpZi7H/Contact-Info-Updating?node-id=1-18&t=NvEoomTTI8dUBm3c-0) (Figma) Mockups of ARP flows for attorneys and agents and VSO certifying officials to update contact information and do a few other things (e.g. submit recertification materials, cancel accreditation). These are non-interactive and were shared during research sessions to get feedback from users (early stage “concept testing”). 
- [Concept testing findings](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1722968980539/8ff88ec576db19a80a13e1f09f5faccf62a86a66?sender=u8cf3f08a008c2b61ad621433) (Mural) Board for our analysis to make sense of what we learned in research sessions conducted with VSO certifying officials, attorneys, and claims agents in August 2024.

**Comment by jfinnerty13** [comment]
Document together and ready for review - meeting on Friday
https://docs.google.com/document/d/1WCrKWqBWXPBy48hxj80eyDpQVcJlee0J4miz7BBipEo/edit?usp=sharing

**Comment by oddball-lindsay** [comment]
@mtri and @oddball-lindsay: take a look at the document linked above, prior to our meeting this Friday 12/6 at 12:05p ET.

**Comment by jfinnerty13** [comment]
Sending email with questions to OGC/OIT/VBA after team review.

**Comment by jfinnerty13** [comment]
Created revisions ticket - closing this one.
