### ISSUE TITLE
vets-api helm - move Expiry Scanner to parent helm chart

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#97587]
The expiry scanner is the same in all environments, so we will move this resource into the parent helm chart

- note: expiry scanner does not run in DEV. We probably should run it in DEV

## Tasks
- [ ] Determine if Expiry scanner can run in DEV
- [ ] move scanner to parent helm chart
- [ ] remove from env helm charts
- [ ] If it's not suppose to run in dev, make it conditional
- [ ] Figure out if mounts need to be mounted (currently there is a typo)
## Acceptance Criteria
- [ ] Expiry running in all environment from parent helm chart

**Comment by JoeTice** [comment]
Work is in progress, and being reviewed - but delays on reviews/approvals is delaying closure
