### ISSUE TITLE
Create prototype for appoint representative (VA Form 21-22/a)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9759]
## Goal
Based on existing product documentation, high-level thumbnail workflows, and our experience with other VA Search work, we need to start thinking about how Search workflows will look on regular screens for "Apoint my VA representative."

## Tasks
- [x] Build out the necessary screens for Representative search that show its first happy path based on an authenticated Veteran
- [x] Build out the remaining screens for other log in states, users.

## Acceptance Criteria
- [x] An initial prototype has been created and shared with the team.

**Comment by jason-gcio** [comment]
not finished, moved to next sprint

**Comment by sporeboy** [comment]
Search/Appoint representative prototype created based on design/content feedback: https://xd.adobe.com/view/3d1a7b7d-3240-44cb-9a19-45408805b48c-6849/

Further design feedback and development dictates that the Search/Appoint representative feature will be redesigned using VA form system elements.

**Comment by jason-gcio** [comment]
I am going to close this, but can you add this link to the updated part of the `/research-design/` folder?
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design
