### ISSUE TITLE
vets-api helm chart - move worker into parent helm chart

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#97592]
the worker is consistent in all environments - move into parent helm chart

- allow conditional enabling

## Tasks
- [ ] add worker into parent helm chart (with enable setting)
- [ ] remove from dev helm chart
- [ ] remove from staging helm chart
- [ ] remove from production helm chart
- [ ] remove from sandbox helm chart

## Acceptance Criteria
- [ ] Worker running in all environments from the parent helm chart

**Comment by JoeTice** [comment]
Work is in progress, and being reviewed - but delays on reviews/approvals is delaying closure

**Comment by JoeTice** [comment]
Closing as duplicate
