### ISSUE TITLE
[Pension and Burial] More descriptive error messaging for upload errors

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#97593]
## Issue Description
As an applicant that is uploading supplemental documents to the Pension or Burial application, I want descriptive error messaging that indicates specifically why the upload failed so that I may better understand the failure reason and potentially take corrective action.

Related ticket: [Pension + Burial | Validate evidence documents at upload](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91973)

Note: in sprint planning Dene mentioned that the 526 team created msging for similar errors. Pelase consult them to understand what they did. 

---
## Tasks
- [x] Identify the set of failure reasons that could generate an error (Dan provided below in [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97593#issuecomment-2515259428))
- [ ] Product/Design to provide approved message text for the reasons
- [ ] Review designs with stakeholders for approve
- [ ] Prep for eng handoff. 
- [ ] Create ENG ticket of ask Matt R or Anh to create the ticket

## Acceptance Criteria
- [ ] The more descriptive reason text is implemented for each error type identified in the 527 and 530
- [ ] Implementation meets VA Design System and CAIA standards
---

**Comment by danlim715** [comment]
There are 3 main scenarios we've identified that will need additional verbiage:

- File page size exceeds 21" x 21"
- File is corrupt and cannot be stamped
- Generic catch all message more descriptive than "Internal Server Error"

**Comment by gmaciolek** [comment]
@danlim715 for the "Generic catch all message more descriptive than "Internal Server Error" scenario, what are the recommended actions a user should take? Would they likely be successful if they try to upload the file again? 

That seems like it might fall under the [File upload failure error scenario documented in the content style guide](https://design.va.gov/content-style-guide/error-messages/feedback).

**Comment by gmaciolek** [comment]
One additional note: There's an updated file input component. We're using the older version. I don't think it's high priority to update now, but we should put it in our backlog.
Slack thread for reference: https://dsva.slack.com/archives/C06E83RNLQM/p1734385870862549

**Comment by aplatt-coforma** [comment]
@matt4su I created the ENG ticket for these changes here: PBP | File Upload Error Updates
[#99351](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99351)
cc @gmaciolek
