### ISSUE TITLE
vets-api helm chart - move clamav into parent helm chart

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#97591]
Clamav is consistent accross environments - push into parent helm chart

note - the following need to be moved
- ports
- probes (allow for overriding values)
- resources
- volume mounts

## Tasks
- [ ] Move clamav into parent helm chart
- [ ] allow overriding of probe settings
- [ ] remove from dev helm chart
- [ ] remove from staging helm chart
- [ ] remove from production helm chart
- [ ] remove from sandbox helm chart

## Acceptance Criteria
- [ ] clamav is running in all environment from parent helm chart

**Comment by JoeTice** [comment]
This task is complete, some follow-on actions may be needed
