### ISSUE TITLE
vets-api helm chart - move mock data init container into parent helm chart

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#97590]
mock data init container is the same everywhere, so moving into parent helm chart.

Make enabling of mock data init container conditional on values.yal boolean

## Tasks
- [ ] Move mock data into parent helm chart
- [ ] remove mock data from dev helm chart
- [ ] remove mock data from staging helm chart
- [ ] remove mock data from sandbox helm chart
- [ ] set production mock data to FALSE

## Acceptance Criteria
- [ ] Mock data running from parent helm chart for all envs except production
