### ISSUE TITLE
Add VA 508 Office audit link to SR touchpoint page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#97595]
## User Story
As a VFS team member, I want to easily find the guidance for requesting a Section 508 office audit so that I can request the audit post-launch.

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @it-harrison 

## Description
Governance recently learned that VFS teams aren't contacting the VA Section 508 Office for an audit post-launch. While we do communicate that this is necessary via the [Staging Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) on Platform Website, we don't provide a link to the [Request support from the VA Section 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office).

The purpose of this ticket is to link to the Request support from the VA Section 508 Office from the Staging Review touchpoint page. 

### Live pages
- [Staging Review touchpoint page (confluence)](https://vfs.atlassian.net/wiki/spaces/CC/pages/1810137181/Staging+review) 
- Staging Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) 

### Drafted pages
- [Confluence Draft Page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3722346497/97595+-+Keegan+-+Staging+review)

## Tasks
- [ ] Add a link to the Request support from the VA Section 508 Office page from the Staging Review touchpoint page, After Meeting

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS teams can easily find the Request support from the VA Section 508 Office page from the Staging Review touchpoint page

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by KKitagawa-Bosch** [comment]
Created a [draft page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3722346497/97595+-+Keegan+-+Staging+review) in governance space and added the information there. Tried to follow the tone/language from earlier in the doc. 

@it-harrison this is ready for you to take a look whenever!

**Comment by it-harrison** [comment]
@KKitagawa-Bosch - looks good!

**Comment by KKitagawa-Bosch** [comment]
lol pretend I didn't do that, I got excited and forgot it had to also go live 

Heard Ian, will close as soon as it gets published to platform

**Comment by KKitagawa-Bosch** [comment]
Live page updated on confluence

**Comment by KKitagawa-Bosch** [comment]
Confirmed that it's updated on the site and closing!
