### ISSUE TITLE
vets-api helm chart - move dbMigrate to parent helm chart

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#97594]
The dbMigrate init container is consistent in all environment - move into parent helm chart
- allow for conditional

## Tasks
- [ ] Add dbMigrate to parent helm chart - allow for override
- [ ] remove from dev helm chart
- [ ] remove from staging helm chart
- [ ] remove from production helm chart
- [ ] remove from sandbox helm chart

## Acceptance Criteria
- [ ] DB Migrate running in all environment from parent helm chart

**Comment by JoeTice** [comment]
This task is complete, some follow-on actions may be needed
