### ISSUE TITLE
[Design] DL - Drupal content page designs (HiFi)

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#9760]
## Issue Description
We need to create a design for the modernized VA.gov content page to replace the debtman content pages.

---
## Tasks
- [x] Create mockup for unauthenticated content page
- [x] Upload to UXPin
- [x] Update documentation

## Acceptance Criteria
- [x] Documentation linked to this ticket

**Comment by rebeccawalsh** [comment]
Ticket reduced because PW will be providing this content for us - we will be building out their content into our prototype for testing

**Comment by rebeccawalsh** [comment]
Removed 'authenticated content page' from the requirements as it will not exist!

Here is a link to the ["Manage your VA debt" unauthenticated tool landing page content](https://app.zenhub.com/files/133843125/83b52a51-2e25-4917-9cdd-41eddc88b635/download) that PW sent us for usability testing. Note that we do not have content for inside the accordions just yet.

**Comment by rileyorr** [comment]
I've updated [the UXPin prototype ](https://preview.uxpin.com/4355a6c97a71ddaf1069ec43e5dfc0ae46b79869#/pages/130133417/simulate/sitemap?mode=i) with the content provided by the PW team
