### ISSUE TITLE
[Claim Status Tool] Replace incorrect info about obtaining claim exam results

### ISSUE THREAD

**Issue by jstrothman** [department-of-veterans-affairs/va.gov-team#97601]
---
## Background Context
- In Claim Status Tool, we have sidebar content re `Want a copy of your claim exam?` It incorrectly says you can obtain a copy from your regional office (RO). This is false information, as regional offices can't provide copies of exams
- A Veteran reported driving 100 miles to their nearest RO in order to get an exam only to find they couldn't get it there.
![Image](https://github.com/user-attachments/assets/cb7cdb9b-42a9-450a-909b-a733ab0eaa85)

## Change to make
In CST, anywhere we offer information about how to get a copy of your claim exam, the instructions should say:
Use [VA Form 20-10206](https://www.va.gov/find-forms/about-form-20-10206/) to request a copy of your exam. You can submit the form using our online tool, or download a pdf of the form and send it by mail.

The link to the form page should open in the same tab/window
The heading should remain as is.

This content definitely shows in Higher Level Reviews and Board Appeals. We should make sure we've found all of the places it appears in CST.

### Enablement team (if needed)
@jstrothman 

## Tasks
- [ ] In Claim Status Tool, change content to match the language provided under `Change to make` in this ticket
- [ ] Reply in this ticket re what claim types show this information. This info is for reference later, and won't change the work in this ticket. 
- [ ] Add a top margin of 40px to the 'Want a copy of your claim exam?' header

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

**Comment by jstrothman** [comment]
@janechodance [vets.gov](http://vets.gov/).[user+226@gmail.com](mailto:user+226@gmail.com) has an [HLR in CST](https://staging.va.gov/track-claims/appeals/HLR2423/status)

**Comment by pmclaren19** [comment]
@jstrothman the CopyOfExam component that you are referring to only shows up on Appeals

**Comment by jstrothman** [comment]
@pmclaren19 Isn't it also on HLR?
Screenshot is [vets.gov](http://vets.gov/).[user+226@gmail.com](mailto:user+226@gmail.com) - [HLR in CST](https://staging.va.gov/track-claims/appeals/HLR2423/status)
![Image](https://github.com/user-attachments/assets/db7f3873-082f-4cfa-ab35-342677db37de)

**Comment by pmclaren19** [comment]
Yes, the HLR appears on the `AppealInfo` component so thats why I said appeals... Just dug into the code logic and looks like this component only appears for legacyAppeal, supplementalClaim, higherLevelReview and appeal.
