### ISSUE TITLE
Sass Upgrade - vets-website initial migration work

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#97615]
## Description
In preparation for unblocking the node upgrade, we're going to begin some initial work on migrating vets-website from node-sass to dart-sass. Though prior research has already been done on this, it's likely we'll get to a point where changes will need to sit in a feature branch until we're completely off of formation. 

## Considerations
- [Original ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37351) that includes some legwork from Nick Sprinkle
- [node-sass to dart-sass migration guide](https://dev.to/ccreusat/migrating-from-node-sass-to-sass-dart-sass-with-npm-3g3c)
- [Nick's original findings](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37351#issuecomment-1263969897)
- [Ian's discovery work](https://vfs.atlassian.net/wiki/spaces/DST/pages/2807070850/Discovery+-+Work+estimate+of+tasks+to+migrate+node-sass+to+dart-sass)
- [official migrator tool](https://sass-lang.com/documentation/cli/migrator/)

## Tasks
- [ ] Run the [migrator tool](https://sass-lang.com/documentation/cli/migrator/) in vets-website. This should give us an idea of how many platform + app files are impacted and whether or not we'll need to split things into multiple pull requests to accommodate CI
- [ ] Analyze any compilation errors or warnings that are raised as a result of running the migration tool and address them if possible. If they cannot be addressed, then make a note in this ticket that documents the issue
- [ ] Create a draft PR for the work

**Comment by caw310** [comment]
Closing as work on node upgrade is done.
