### ISSUE TITLE
686 Updates | Add detailed logging and monitoring

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97624]
## Issue Description
_Ensure logging exists for:_
- “Starting to send to RBPS”
- “Finished sending to RBPS”
- Zero Silent Failure stuff

_Monitors need to capture new V2 path_
- A good example of our monitoring gaps involves this [bug](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97301), for which we have no alerts
---
## Tasks
- [ ] Add logging for “Starting to send to RBPS”
- [ ] Add logging for “Finished sending to RBPS”
- [ ] Add logging for zero silent failure
- [ ] Add monitoring for new v2 path

## Acceptance Criteria
- [ ] Logging for “Starting to send to RBPS”
- [ ] Logging for “Finished sending to RBPS”
- [ ] Logging for zero silent failure
- [ ] Monitoring for new v2 path
