### ISSUE TITLE
686 Updates | Design | Update Info Alert

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97629]
## Issue Description
_Users with in-progress v1 686/674 forms will be redirected back to the start of the form and shown an updated info alert that explains that the form has been updated and all the data they previously entered has been migrated to the new version of the form._

Work with CAIA to confirm copy for alert. Existing CAIA Intake ticket for general form updates is [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75068).

Current info alert:
![Image](https://github.com/user-attachments/assets/f27afdee-40fc-4c92-80d8-93ac9428a555)

---
## Tasks
- [ ] Update info alert copy on the form start page for users who have in-progress v1 forms
- [ ] Obtain sign off from CAIA
- [ ] Obtain sign off from Dene

## Acceptance Criteria
- [ ] Final copy for info alert for users with in-progress v1 686/674 forms
- [ ] Update corresponding engineering ticket (#97628) with wireframe

**Comment by ajialeilani** [comment]
Created [mockup](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=3607-35894&t=6VbyLPxmE0TkiFGp-1) based on Burial's alert. Sharing in [existing CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75068) and moving to in-review for now.
