### ISSUE TITLE
[FSR] Audit FSR for for missing data

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#97625]
We caught the "box3" issue which is good. What else do we not know about? We should hive/mob on the FSR and make sure all fields that are added get sent through the PDF and our partners.

This will likely take a few people in FE and BE team to get this locked down.            

## Tasks
- [x] Identify and list all flows/combinations of the FSR
- [x] Figure out what data goes where in the PDF
- [x] Figure out what data goes where in partner submissions
- [x] Go box-by-box and verify all data is present and accounted for

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Team signs off on all data atrributes

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points

**Comment by amponce** [comment]
So it looks like we have an issue with the rent/mortgage box, `monthly_housing_expenses`
I've done some investigating and it looks like it's not currently on the whitelist in transform and submit controller. 

`modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb


<img width="649" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUxmQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a2ef60ddeec73a6a8001f4d4e44b3b32093db91/image%20%281%29.png" alt="image (1).png" />

<img width="582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVBmQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a88cbd25323f632a1e539f9c12cb151af5ddd2c/image.png" alt="image.png" />


```
full_transform_form.rb
 # rubocop:disable Metrics/MethodLength
      def full_transform_form
        params.permit(
          :'view:enhanced_financial_status_report',
          :'view:streamlined_waiver',
          :'view:streamlined_waiver_asset_update',
          :'view:review_page_navigation_toggle',
          questions: %i[
            has_repayments has_credit_card_bills has_recreational_vehicle
            has_vehicle has_real_estate spouse_has_benefits is_married
            has_dependents has_been_adjudicated_bankrupt vet_is_employed
            spouse_is_employed
          ],
          'view:components': {
            'view:contracts_additional_info': {}, 'view:rec_vehicle_info': {},
            'view:real_estate_additional_info': {}, 'view:marital_status': {},
            'view:veteran_info': {}, 'view:dependents_additional_info': {},
            'view:va_benefits_on_file': {}
          },
          assets: [
            :rec_vehicle_amount, :real_estate_value,
            {
              monetary_assets: %i[name amount],
              other_assets: %i[name amount],
              automobiles: %i[make model resale_value]
            }
          ],
          benefits: { spouse_benefits: %i[compensation_and_pension education] },
          personal_data: [
            :date_of_birth, :telephone_number, :email_address,
            {
              spouse_full_name: %i[first last],
              veteran_full_name: %i[first last middle],
              veteran_contact_information: [
                :email,
                {
                  mobile_phone: %i[
                    area_code country_code created_at extension
                    effective_end_date effective_start_date id
                    is_international is_textable is_text_permitted
                    is_tty is_voicemailable phone_number phone_type
                    source_date source_system_user transaction_id
                    updated_at vet360_id
                  ],
                  address: %i[
                    address_line1 address_line2 address_pou address_type
                    city country_name country_code_iso2 country_code_iso3
                    country_code_fips county_code county_name created_at
                    effective_end_date effective_start_date id province
                    source_date source_system_user state_code transaction_id
                    updated_at validation_key vet360_id zip_code zip_code_suffix
                  ]
                }
              ],
              dependents: [:dependent_age],
              address: %i[
                street city state country postal_code
              ],
              employment_history: [
                veteran: [
                  employment_records: [
                    :type, :from, :to, :is_current, :employer_name, :gross_monthly_income,
                    { deductions: %i[name amount] }
                  ]
                ],
                spouse: [
                  sp_employment_records: [
                    :type, :from, :to, :is_current, :employer_name, :gross_monthly_income,
                    { deductions: %i[name amount] }
                  ]
                ]
              ]
            }
          ],
          personal_identification: %i[ssn file_number],
          selected_debts_and_copays: [
            :id,
            :p_s_seq_num,
            :p_s_tot_seq_num,
            :p_s_facility_num,
            :p_s_fac_phone_num,
            :p_s_tot_statement,
            :p_s_statement_val,
            :p_s_statement_date,
            :p_s_statement_date_output,
            :p_s_process_date,
            :p_s_process_date_output,
            :p_h_patient_lst_nme,
            :p_h_patient_fst_nme,
            :p_h_patient_mid_nme,
            :p_h_address1,
            :p_h_address2,
            :p_h_address3,
            :p_h_city,
            :p_h_state,
            :p_h_zip_cde,
            :p_h_zip_cde_output,
            :p_h_ctry_nme,
            :p_h_amt_due,
            :p_h_amt_due_output,
            :p_h_prev_bal,
            :p_h_prev_bal_output,
            :p_h_tot_charges,
            :p_h_tot_charges_output,
            :p_h_tot_credits,
            :p_h_tot_credits_output,
            :p_h_new_balance,
            :p_h_new_balance_output,
            :p_h_special_notes,
            :p_hro_para_cdes,
            :p_h_num_of_lines,
            :p_h_dfn_number,
            :p_h_cerner_statement_number,
            :p_h_cerner_patient_id,
            :p_h_cerner_account_number,
            :p_h_icn_number,
            :p_h_account_number,
            :p_h_large_font_indcator,
            :debt_type,
            { details: [] },
            { station: {} }
          ],
          additional_income: [
            addl_inc_records: %i[name amount],
            spouse: [
              sp_addl_income: %i[name amount]
            ]
          ],
          expenses: [
            expense_records: %i[name amount],
            credit_card_bills: %i[
              purpose creditor_name original_amount unpaid_balance
              amount_due_monthly date_started amount_past_due
            ]
          ],
          utility_records: %i[name amount],
          other_expenses: %i[name amount],
          additional_data: [
            :additional_comments,
            { bankruptcy: %i[date_discharged court_location docket_number] }
          ],
          income: [:veteran_or_spouse],
          gmt_data: %i[
            is_eligible_for_streamlined gmt_threshold error income_upper_threshold
            asset_threshold discretionary_income_threshold income_below_gmt
            income_below_one_fifty_gmt liquid_assets_below_gmt discretionary_below
          ],
          installment_contracts: %i[
            purpose creditor_name original_amount unpaid_balance
            amount_due_monthly date_started amount_past_due
          ]
        ).to_h
      end
```

**Comment by amponce** [comment]
After testing the new transform and submission process, I believe the only actual issue is with the rent and mortgage/expenses box. Everything else appears to be complete. @digitaldrk @Dr-Pongo [VA Form 5655 - Submitted (9).pdf](https://github.com/user-attachments/files/17908307/VA.Form.5655.-.Submitted.9.pdf)

**Comment by Dr-Pongo** [comment]
@amponce Do you think we still need to whitelist those other missing fields you listed from `full_transform_form`? Thank you so much for digging into this! that "(9)" in the PDF shows dedication lol 

So as a postmortem, I think we shipped the expense changes around the same time as some of the BE work was wrapping up for transform and submit and we had some BE transition around the exact same time

**Comment by amponce** [comment]
@digitaldrk and I debugged the whitelisting issues and added `view:showUpdatedExpensePages` and `monthlyHousingExpenses `to the controller. He's working on submitting the PR, and we plan to have it merged with the Friday deployment.

cc @Dr-Pongo @Tom-Davis
