### ISSUE TITLE
686 Updates | Reconcile schema

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97622]
## Issue Description
_Reconcile schema differences between v1 and v2 of 686/674._

---
## Tasks
- [ ] Identify which properties need to be renamed/cleaned up
   - Don't be afraid to do this. Better to rename something than try to fit a square peg in a round hole.
   - How many properties changed? A count of the total.
   - Which properties have changed?
- [ ] Share out the results to the RPBS and BIS teams (Matt and Laura)
   - Find out if they can handle two different schemas
   - Some of the next steps may change depending on the answer to this question.

## Acceptance Criteria
- [ ] Schema for 686/674 has been updated
---
