### ISSUE TITLE
Documentation - Create Plan for Settings Transition

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#97626]
A plan will need to be in plan to transition Settings to use the new convention while 

## Tasks
- [x] Create a confluence page that details the plan 
- [x] Ask for feedback from other backend engineers & Patrick 

## Acceptance Criteria
- [x] A confluence page is created
- [x] Feedback has been received and applied as needed

**Comment by stevenjcumming** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3653173381/vets-api+helm+chart+normalization+-+Settings+Transition+Plan
