### ISSUE TITLE
Update appoint_a_representative_enable_pdf feature flag name

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#97637]
## Background
The backend feature flag `appoint_a_representative_enable_pdf` does more than just enabling PDFs, it:
1. allows searching for representatives in Appoint
2. generates the PDF
3. sends the email notification

We talked about updating this feature flag to a different name, so that it better reflects the actual functionality. 

## Tasks
- [ ] Chat with the team to define an ideal name for this feature flag
- [ ] Update the feature flag name

## Acceptance Criteria
- [ ] The feature flag has a name that better represents its functionality.
