### ISSUE TITLE
Evaluate dbMigrate and cronJob volume mounts in parent helm charts

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#97673]

**Comment by RachalCassity** [comment]
## Issue Description
The [dbMigrate job](https://github.com/department-of-veterans-affairs/vets-api/blob/parent-helm-charts/chart/templates/db-migrate-job.yaml) and[ cronJob deployment](https://github.com/department-of-veterans-affairs/vets-api/blob/parent-helm-charts/chart/templates/cron-deployment.yaml) helm chart manifests are pulling in all common volume mounts. The mockdata volume is not used for the dbMigrate and cronJob deployments. Volumes and volume mounts for the dbMigrate job the cronJob deployment should be re-evaluated

##Related Pull requests
https://github.com/department-of-veterans-affairs/vets-api/pull/19575
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3275
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3278

## Tasks
- [ ] Evaluate dbMigrate job volumes and volume mounts
- [ ]  Evaluate cronJob deployment volumes and volume mounts
- [ ] Update parent helm charts
- [ ] Successfully deploy dbMigrate volume and volume mounts to dev
- [ ] Successfully deploy dbMigrate volume and volume mounts to staging
- [ ] Successfully deploy dbMigrate volume and volume mounts to sandbox
- [ ] Successfully deploy dbMigrate volume and volume mounts to prod
- [ ] Successfully deploy cronjob volume and volume mounts to dev
- [ ] Successfully deploy cronjob volume and volume mounts to staging
- [ ] Successfully deploy cronjob volume and volume mounts to sandbox
- [ ] Successfully deploy cronjob volume and volume mounts to prod


## Acceptance Criteria
- [ ] dbMigrate volume and volume mounts have been fixed and dbMigrate job successfully runs migrations
- [ ] cronJob volume and volume mounts have been fixed and expiry-scanner successfully sends cert notifications to devops-alerts slack channel
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
