### ISSUE TITLE
Validate Chapter 33 Information

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#97682]
## Description

We are looking to validate what Chapter 33 information we get from DMC for Beneficiaries.

A list of 20 beneficiaries was sent via the VA network to validate what information we receive via the API from DMC.
What we are 'theoretically' checking is if these beneficiaries were to log in - could they see those education debts on VODA.

We will validate that yes those debts are indeed included in the API.

To help me determine next steps there are 20 provided in the list, hopefully these all can be researched - if not please provide the information for an many as possible.

Summary: IF these people were to come to the portal and log in.. they would see Chapter 33 education debts

## Tasks
- [ ] Check the DMC API for Chapter 33 data.

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [X] Not Required

## Acceptance criteria
- [ ] The report is provided to Denise (most likely via the VA network).

## Testing
- [X] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [X] Description written
- [X] Tasks defined
- [X] Acceptance criteria written
- [X] Testing defined
- [X] Add Labels
- [X] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by denisecoveyduc** [comment]
For tracking purposes adding a note copied over from an email thread: Bob and @digitaldrk discussed the findings from this ticket and determined that transfer of eligibility debts are all showing in VODA. 
There were a couple instances where the initial findings were reporting no debts but when run a second time, they’re showing. The assumption is that occurred initially because there was an error in retrieving the debts or could be that there is some time that has to go by before the API lines up with the data in VAMS. More investigation will be needed to ensure that beneficiaries are seeing Chapter 33 debts consistently. A future super epic will be established to encompass this need alongside future work. 
@digitaldrk Please add a comment to clarify anything that I may have misinterpreted from the email or add any additional context you may have. Thank you.
