### ISSUE TITLE
'180 Day' Terminology Audit"

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#97683]
## Description

VA will be adjusting the timeframe for VBA 5655 Form submissions that are currently set to 180 days. Our partners would like to see all instances of where the 180 day language is being used in production today.  Although this change would be specifically for VBA Submissions could we capture screenshots for any instances across the debt portal (including VHA and the upcoming dispute work)

## Tasks
- [x] Query production data for any reference to '180 day' timeframe 
- [x] Collect 180 day reference from current digital dispute designs
- [x] Document a list of where each '180 day' timeframe is being mentioned'  - ideally by capturing visual/screenshots of any instances. 
- [x] Tag Denise when completed so she can discuss with partners.

## Acceptance Criteria
-   [x] All mentions of "180 day" in production data and upcoming digital dispute are identified and documented.
-   [x] A summary report is shared with VA Product Owner detailing findings and any actions taken.

## Testing
- [X] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [X] Description written
- [X] Tasks defined
- [X] Acceptance criteria written
- [X] Testing defined
- [X] Add Labels
- [X] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
Hi @denisecoveyduc, 

I did the audit and found only **two occurrences** of the 180-day timeframe, and they're both in the FSR Wizard under the overpayments path, there are also no mentions of the 180 limit in the dispute form as we removed it per our conversation with Bob:

| Error or Amount  | Disagree |
| -------- | ------- |
| ![Image](https://github.com/user-attachments/assets/ba5fc986-d2ea-4fd5-94e3-f677e13a46e8)  | ![Image](https://github.com/user-attachments/assets/3fb94b18-44c0-462b-be22-8a7985456c8b)|

Let me know if you need anything else on this ticket!

cc: @mgleo

**Comment by mgleo** [comment]
@denisecoveyduc I've flagged this in the comments on the new, unreleased [Complete a Subtask](https://www.figma.com/design/ea8baIDr09ncgr1P4Rfh8i/Financial-Status-Report-(VA5655)---(including-Streamlined-Waiver)?node-id=252-22439&t=mkgy9o7LTh7RFqnS-1). It is under **Report an error or a disagreement with a VA decision** > 
**I disagree with the VA decision that resulted in this overpayment** and **I think this overpayment is due to an error or the amount is wrong**. 
Do we have guidance on how this language will be updated? Otherwise we can make a note to update it when we learn more. 
cc @josephrlee

**Comment by josephrlee** [comment]
Marking this as closed, here is the follow-up ticket to update the 180-day term to 1 year after December 23, 2024: 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/99240 

cc: @denisecoveyduc @mgleo @Tom-Davis @dhill802
