### ISSUE TITLE
[a11y support] VA Notify: 508 Audit Prep for VANotify Portal

### ISSUE THREAD

**Issue by sara-amanda** [department-of-veterans-affairs/va.gov-team#97688]
> [!NOTE]
> **HIGH-LEVEL OVERVIEW** 
> - **Timeframe**: 
>     - Audit likely to take place in `2025`
> - **Prep Work:**
>     - The prep-work for this 508 audit is taking place in the following ticket: [#2501](https://github.com/department-of-veterans-affairs/notification-portal/issues/2501)
>     - **Initial support:** Provided by CAIA, to date, guidance on accessibility testing.
>     - **Additional guidance:** Needed to help assist the team, in preparing for the audit. Review the preparation guide. 
> - **The official 508 Request Process includes, and is currently in progress, by the VA Notify Team:** 
>     - Submit a 508 Audit Request to initiate an audit. 
>         - Ensure project/product testing results are included. 
>     - Self identify 508 accessibility defects to the 508 SME assigned to our product for tracking purposes and visibility. 
>         - **"Known Issues"** can be located in the [VA Notify Section 508 Audit Preparation Guide](https://github.com/department-of-veterans-affairs/notification-portal/issues/2501#issuecomment-2494380545) (Sharepoint access required) - `CAIA Review for Completeness` 

## Issue Description

> We need to prepare for the upcoming 508 office review of the portal. This will require gathering use cases, permissions, and other relevant documentation. We also need to identify any additional items required for the review, and schedule a grooming session to ensure we are ready for the review.

<details><summary>Review the problem, value and existing measures being taken by the VA Notify Team</summary>

> ### How do we know this is a problem?
> 
> The 508 office review is a mandatory part of our compliance process, and the review requires specific documentation and understanding of the portal’s accessibility.
> 
> ### Value
> 
> Successfully preparing for the 508 office review will ensure that the portal is accessible, compliant, and ready for review, reducing the likelihood of delays or additional rounds of revisions. This will benefit both the Notify team, by providing clarity on required changes, and Notify users, by ensuring the portal meets accessibility standards.

## Existing Measures Being Taken

> - UX ensures that all user interfaces are intuitive and accessible, conducting regular reviews for compliance with accessibility guidelines and testing for ease of use by individuals with diverse needs.
> - QA when testing all new features and changes to functionality, performs a color contrast check, tab navigation check and screen reader check as part of QA
> - ENG adheres to accessibility (a11y) standards

### To-do's/guidance from Martha:
> "The VA 508 Office will do it via their official processes. They will need a test user/password and maybe a description of some key user flows through your app. Anything you have on hand for your existing accessibility processes or known defects would be good for them to know as well."

</details>

## Known Issues

Jake Uhteg reached out via Slack to Sara Smith, and discussed the current accessibility testing, additional testing methods and additional accessibility advice. Jake then provided the known issues to Elissa. 

> - **Color contrast** - We may need to change a couple of inactive buttons to active buttons and trigger error message. I have an open question out about how inactive tabs factor in, but nothing big on that front
> - **Tab navigation** - we’re good, one weird bug where top nav isn’t accessible if a service is selected. But overall, in a good spot.
> - **Screen Reader** - good-ish. Everything on the portal is read when using the built-in windows narrator. But the way that was accomplished caused some errors when doing the axe tools check. And I’m not doing it in true screen reader fashion because of Citirx limitations. I am still working with Sara and finding a proper tool other than narrator to go through this.
> - **Zoom Testing** - I wasn’t aware this was a required piece so I never tested for it. We’ll have to adjust our pages to accommodate for this and I’ll have to add it to my testing plan going forward

## CAIA Feedback Provided

<details><summary>Review the feedback provided to Jake</summary>

> ### Avoiding Inactive Buttons
> When buttons are inactive, some users– particularly those with cognitive disabilities- may not know how to activate them. Disabled buttons don’t explain what’s wrong. They communicate that something is off, but very often that is not enough information. As a result, users are left wondering what’s actually missing, and consequently are locked out entirely. For example, if someone were to type in a short acronym like “VA” to search and the button doesn’t become accessible, they may think the search field is broken.
> In addition, disabled buttons can be unintentionally read out and accessed by mobile screen readers using touch controls.

Source: https://design.va.gov/components/button/#do-not-disable-form-elements

> ### What to do instead
> While it is technically possible, we strongly discourage disabling buttons. Here are recommendations on how to handle specific interactions:
> - Lack of required fields. When a user attempts to submit a form without entering all required form fields:
>     - Announce the error and shift focus to the first unfilled required form field.
>     - Properly indicate required form elements (the right thing will happen for you when you use the required property on form fields in the Design System).
> - No longer valid options. If certain options in a form are no longer valid then there are two options:
>     - Replace the form elements that can no longer be changed with text representing the current value instead of the current value within a disabled input.
>     - Hide the form elements that are no longer valid.

**Source**: https://design.va.gov/components/button/#what-to-do-instead

### Axe Scans
> Automated scans Pass with exceptions - Axe testing shows a false positive on color contrast for the default variation
> Axe is capable of finding many [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/) and accessibility best practice violations.
> In general, a product that is passing all of its axe tests should also pass all of the WAVE tests, and any issues flagged by WAVE should get a closer look.
> Install the [WAVE browser extension for Chrome, Firefox or Edge](https://wave.webaim.org/extension/).
> If engineers are using VSCode, they should use the [axe linter](https://marketplace.visualstudio.com/items?itemName=deque-systems.vscode-axe-linter).

**Sources:**
- https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#axe
- https://depo-platform-documentation.scrollhelp.site/developer-docs/end-to-end-testing-with-cypress
- https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-testing-helper-functions
- https://design.va.gov/about/accessibility/accessibility-testing-for-design-system-components#testing-principles
- https://marketplace.visualstudio.com/items?itemName=deque-systems.vscode-axe-linter

> ### Additional Automated Testing Options
> Although automated testing tools may only pick up on 20-30% of accessibility issues, they can be easy to use, provide immediate feedback, and help to find glaring accessibility issues. These tools are typically used when content is available in a live, coded environment that is viewable in a web browser.
>
> #### Browser Extensions
> The benefit of tools that integrate into browsers is that they give you the capability of testing directly in a browser.
> 
> - [Axe DevTools](https://www.deque.com/axe/devtools/) - an accessibility testing toolkit developed by Deque, that integrates with your browser of choice, to scan entire pages or individual components. This is typically a highly preferred automated tool across the board.
> - Additional tools - while we rely on axe DevTools for most automated testing, here are some additional tools to consider:
> - [ArcToolkit](https://www.tpgi.com/) - a set of accessibility tools that aids developers in identifying accessibility problems and features for WCAG 2, EN 301 549, and Section 508
> - [WAVE](https://wave.webaim.org/) - a web accessibility evaluation tool developed by [WebAIM.org](http://webaim.org/). It provides visual feedback about the accessibility of your web content
> - [IBM Equal Access Accessibility Checker](https://www.ibm.com/able/) - an open-source tool for web developers and auditors that utilizes IBM's accessibility rule engine, which detects accessibility issues for web pages and web applications.
> - [Accessibility insights for web](https://accessibilityinsights.io/docs/web/overview/) - a tool, similar to Axe and WAVE, that evaluates a page's semantic elements and styling

> ### Manual Testing Tools
> - Manually interacting with content can help to fill in the gaps missed by automated testing. Included below is a good grouping of several different tools, so feel free to experiment with different combinations in your testing.
> - Color and Contrast
> - Zoom/Magnification
> - Architecture and Semantics
> - Screen Readers
> - For details on the items above, see the link below. ...

**Source**: [Tools we use (CAIA Accessibility)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/tools-we-use.md#tools-we-use) 

### Zoom
> - Zoom Testing - This is another piece that I have never tested before. The preparing page mentions 400%, but a lot of the [information](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html) I’ve found only talks about 200%. I was wondering if you know which requirement would be better to follow, and just some tips if this is something you’ve encountered before.

- **:star: Yes, I would do the following all three :slightly_smiling_face: 200%, 300%, and 400% zoom (Browser width: 1280px)**
- All page elements must be readable and usable at 200%, 300%, and 400% zoom. That means:
    - No functionality has been hidden or removed from the page. (Example: a button that is visible on desktop but hidden on a mobile device will likely be hidden at high zoom.)
    - Nothing overlaps. (Example: text getting covered up by other elements.)
    - No horizontal scrolling. (Exceptions: data tables, charts, and images.)
- **Steps to test**
    - Set browser width to 1280px ...

**See on this page below:**
[https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#Prepareforanac[…]w-Stepstotest.2](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#Prepareforanaccessibilitystagingreview-Stepstotest.2)

</details>

## About the Team

- **Team name**: VA Notify
- **Product name:** VANotify Portal
- **Contacts:** Elissa Folk and Jake Uhteg (Strike Team)
- **GitHub:** [VA Notify, Enterprise Notification Platform](https://github.com/department-of-veterans-affairs/va.gov-team/blob/626fba904f14f35bd44ec771c739e2be606f7f45/products/va-notify/README.md)
- **GitHub Path:** ` /department-of-veterans-affairs/notification-portal`
- **Slack Channel:** [#va-notify-public](https://dsva.slack.com/archives/C010R6AUPHT)

### Supporting Artifacts 

<details><summary>Review the supporting artifacts</summary>

- [VA Notify Section 508 Audit Preparation Guide](https://github.com/department-of-veterans-affairs/notification-portal/issues/2501#issuecomment-2494380545) in [GitHub 2501 ](https://github.com/department-of-veterans-affairs/notification-portal/issues/2501)
- **508 Toolset and Documentation**
    - Access the tools used by the audit team, their versions, and instructions for obtaining them at the - [VA 508 Office Tools SharePoint page](https://dvagov.sharepoint.com/sites/vasection508/SitePages/Audit-Tools.aspx).
- **Staging Review Preparation**
    - Guidance on preparing for a staging review can be found in the [Accessibility Staging Review Documentation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
- **Developer References**
    - [Section 508 Official Website](http://www.section508.gov/)
    - [United States Access Board](http://www.access-board.gov/)
    - [WebAIM Accessibility Guidelines](http://webaim.org/)
    - [W3C WCAG 2.1 Quick Reference](https://www.w3.org/WAI/WCAG21/quickref/)

</details>

```[tasklist]
### a11y Tasks
- [x] **Collaborate** with VA Notify (Elissa and Jake) via Slack (Sara and Jamie)
- [x] **a11y Support** - feedback on accessibility testing (Sara)
- [x] **Document** - initial feedback provided and noted in this ticket (Jamie and Sara)
- [ ] **Review** - Discuss with Elissa next steps and assistance needed to help prepare the team for the 508 audit. @EvanAtCoforma
- [ ] **Review** - [VA Notify Section 508 Audit Preparation Guide](https://github.com/department-of-veterans-affairs/notification-portal/issues/2501#issuecomment-2494380545) @EvanAtCoforma
```
```[tasklist]
### Acceptance Criteria
- [x] Assigned by Martha to assist the team 11/19/2024
- [x] Prioritization received from Martha 11/22/2024
- [x] Support provided by CAIA, to date, guidance on accessibility testing.
- [ ] Additional guidance needed to help assist the team, in preparing for the audit by reviewing and providing feedback on the [VA Notify Section 508 Audit Preparation Guide](https://github.com/department-of-veterans-affairs/notification-portal/issues/2501#issuecomment-2494380545) 
```
```[tasklist]
## Ticket Updates (CAIA Internal)
- [ ] _Connect to an `Epic` or `Intake` (what body of work is this a part of?)_
- [x] _Label with `Originator/Team` (product team or stakeholder requesting support)_
- [x] _Label date in the `Open Date` field_
- [x] _Label with `Estimate` (level of effort expected for this ticket)_
- [x] _Add `Assignee(s)` name(s) to ticket_ (include Naomi)
- [ ] _Add `Assignee(s) name(s) to each task` they will complete via handle tag (if known)_
- [x] _Select a `Priority Level`_
- [x] _Update date in `Last Checked` field_
- [ ] _Label with `Actual` (level of effort it took to complete this ticket)_
- [ ] _Update date in_ `Closed Date`
```

```[tasklist]
### Related Tickets
- [ ] [UX: Prepare for 508 Office Review of VANotify Portal #2501](https://github.com/department-of-veterans-affairs/notification-portal/issues/2501)
```

**Comment by artsymartha68** [comment]
No rush on this at all. And since this is not Veteran-facing, it takes a lower priority.

**Comment by sara-amanda** [comment]
## Timeframe 
- Audit likely to take place in 2025. 
- Priority level assigned, and updated per Martha's note above.  

cc: @NaomiPMC

**Comment by coforma-jamie** [comment]
@Jake-Uhteg had several followup questions, which I provided answers to:

### Axe Devtools
- Q: Does every page need to have zero errors when running Axe DevTools? Do _all_ errors need to be resolved, or only when best practices is turned off?
- A: Yes, there should be no axe errors (unless you’re coming up with a false positive that can be explained by a manual check). See the [axe expected result](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#Prepareforanaccessibilitystagingreview-Expectedresult). Also note that most axe errors will correspond to items that the 508 office is auditing for.

### Screen Reader
- Q: Can you use a screen reader other than Narrator on Citrix? Having issues using Narrator like a standard screen reader.
- A: No, the JAWS enterprise license is only available on GFE. You may be able to use NVDA but I haven't had success. However, Narrator is a fully-fledged screen reader and is similar enough to the others that it's fine to use while testing. Couple of recommendations:
   - this list of [keyboard shortcuts](https://dequeuniversity.com/screenreaders/narrator-keyboard-shortcuts) for Narrator
   - note the shortcuts under "Scan Mode," these are what you use when navigating around a web page. Generally you're using [Narrator] (`CAPS` or `INS`) + up / down arrow to go line by line.
   - A quirk I noticed - when in a radio button group, use `F` to navigate between radio buttons (or `SHIFT` + `F` to cycle backwards through the radio buttons)

### Filter button / link
- Q: How to handle the "clear all" link when no filters are selected?
- A: This is a multi-part answer.
   - First, this should be a button, not a link - it's for interactivity, not for navigation.
   - The bigger issue - You want the user to be able to filter, but what happens when they click the button when no filters are applied? The `disabled` state has accessibility issues, so what can be done instead? I chatted with the other specialists and have narrowed it down to a couple of options for you:
       - OPTION 1 — Hide the button entirely (visually and from the accessibility tree) until a filter is selected
       - OPTION 2 — The button always clears the filters, and announces it to users, even if no filters were selected. This involves two things:
            - Dynamically change the button text. When no filters are selected, the text is “No filters to clear.” When filter(s) are selected, it’s “Clear filters.”
            - When someone clicks on the button, direct them to a message at the top of the page that says “Filters cleared.” You’d have to put focus on the the message, like you’d do with any other alert.

**Comment by artsymartha68** [comment]
Untagging myself, Low is the proper priority for this.

**Comment by sara-amanda** [comment]
## Feedback

> [!TIP]
> **The following includes information provided as they relate to:**
> - Horizontal data tables 
> - Back to top

### Horizontal Data Tables

#### WCAG: G206
> [WCAG: G206](https://www.w3.org/WAI/WCAG21/Techniques/general/G206): For instance, a spreadsheet that requires horizontal scrolling is acceptable if no horizontal scrolling is necessary for each column individually (i.e., scrolling is only necessary to see other columns, but not for the left or right edges of each individual column). 

#### Collab Cycle Feedback Around This Says ...

> For sticky content, be careful about high-zoom situations. The VA.gov experience standards and WCAG 2.1 AA require support for up to roughly 400% zoom without loss of functionality or requiring horizontal scrolling (vertical scrolling okay). Sticky content often doesn't play well with high zoom levels, covering up some/all information on the page. You'll want to select an appropriate break point where the sticky controls become not-sticky.

> The [VA.gov](http://va.gov/) experience standards and WCAG 2.1 AA require [support for up to roughly 400% zoom](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) without loss of functionality or requiring horizontal scrolling (vertical scrolling okay). When you have something as information-dense as the comparison tool, this can be a huge challenge -- sort of an extreme version of mobile/responsive design. I would recommend working on some high-zoom prototypes and start thinking about possible interaction patterns. Example: If the results map takes up the whole viewport at high zoom, what should happen when someone clicks a map marker? The more you plan for this early on the easier it will be to implement.


#### Example & Solution Options

Trevor does a good job and has a visual here, to show an example and a solution, if this helps? [Ticket: 95134](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95134)

> **Proposed solution or next steps I think there could be a few options here:**
> 1. Adding an optional prop to the VA-table component that allows it to take a tabindex="0" so the table can be focused and scrolled using a keyboard
> 2. Add a container with the tabindex on this particular view
> 3. Adjust the CSS to switch to the responsive layout sooner

#### References, articles, or WCAG support**
> [Understanding SC 1.4.10: Reflow (Level AA)
> ](https://w3.org/TR/WCAG22#reflow)

#### Related Research Feedback
> "We've seen other horizontal scrolling issues happen with people using magnification in research that suggest we need to be intentional about the cues we do or don't give users about what is on the right side of the page."
> "Cindy observed the opposite problem where people missed things on the right side of the page because there were no cues to suggest they should look there."

[Liz Lanz, Authenticated Experience Ticket 54046](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54046)

### Back to Top

#### Spacing
- In the desktop view there should be at least 5 spacing units (40 pixels) of white space above the Back to top component and 2.5 spacing units (20 pixels) white space below.
- In smaller screens where the Back to top component is the arrow icon, there should be at least 4 spacing units (32 pixels) of white space above and 2 spacing units (16 pixels) below the component.
- :warning:  The back to top button also has had some major issues for zoomtext users. Should be a link to be materially honest.

#### Alternative to Button, Link Examples
_The back to top link is focusable and users can trigger it with the enter key, like any other link. It will take users back to the top of the current page._

- [Scotland Design System](https://designsystem.gov.scot/components/back-to-top/)
    - Back to Top on bottom right
- [Gov.UK - Design System](https://design-system.service.gov.uk/community/accessibility-strategy/)
    - Back to Top on bottom left
- The back-to-top updates are in [storybook](https://design.va.gov/storybook/?path=/docs/components-va-back-to-top--default). Label is also being properly read out via Windows + JAWS/ Safari + VO.
- [Design System info in Back to Top](https://design.va.gov/components/back-to-top)

:star: [See this ticket comment, write up I did on this issue.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60812#issuecomment-1610054544)

#### VADS 

[VADS Usage and Considerations](https://design.va.gov/components/back-to-top)

> - **Usage**
>     - On large and medium screens, the Back to top component will have the label, “Back to top” with an arrow icon to the left of the label. On small screens, the Back to top component will only have the arrow icon. Use one Back to top component per page.
> - **When to use Back to top**
>     - In pages with static content that is more than two screens in length on large and medium screens, or more than four screens in length on small screens.
> - **When not to use Back to top**
>     - In pages with static content that is short in length.
> - **Placement**
>     - The Back to top component is anchored to the lower right edge of its parent container (the main content area) on desktop, and the lower right edge of the viewport on smaller screens.
>     - In the desktop view there should be at least 5 spacing units (40 pixels) of white space above the Back to top component and 2.5 spacing units (20 pixels) white space below.
>     - In smaller screens where the Back to top component is the arrow icon, there should be at least 4 spacing units (32 pixels) of white space above and 2 spacing units (16 pixels) below the component.
> - **Behavior**
>     - As the user scrolls down the page, the Back to top component reveals as a sticky element in the lower right edge of the main content area.
>     - The Back to top component stays fixed in the lower right edge of the main content area when the user reaches the bottom of the page.
>     - Clicking Back to top takes the user to the top of the page.
> - **Accessibility considerations**
>     - Animations can be distracting to users with vestibular conditions.
>     - Some users may have smooth scrolling turned off in their preferences, which will affect the transition going back to the top of the page.
>     - After the user has clicked Back to top, the code should call focus on an element near the top of the page, such as the H1.

**Comment by sara-amanda** [comment]
## Backlog
Moving to our `backlog` for now, as this work is set to continue in 2025. 

cc: @coforma-jamie @NaomiPMC
