### ISSUE TITLE
[Design] 10-10CG - Facilities: Exploration for Search page instructions content

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#97697]
## Benefit to the Veteran
As a Veteran and/or Caregiver, I want to feel confident on how I navigate the facilities search page, so that I can find what I need and move on through the form.

## Background
During research sessions, we found that the search and facility selection page did not have clear instructions or guidance on how to search and select the facility before moving on through the form.

## Scope
- In Scope
     - Investigate potential content updates we can make to provide more guidance on the search & selection process
          - This may include focus on using a postal code as a default search criteria (see email from CG stakeholders below)

### Resources

<details>

<Summary>Email from CG stakeholders with postal code suggestion</Summary>

> Thank you for putting together the screenshots for review. After testing some data from Florida/Mississippi (for Biloxi VAMC), we wanted to make a minor suggestion to the placement of “City, state or postal code” in the Search component.
>
>
>It seems that postal code is a bit more accurate in identifying the local facility. If possible, we would like to see “Postal code, city or state” in that order for the search bar. Otherwise, everything else looks good on our end.
>
>
> ![Image](https://github.com/user-attachments/assets/9ef74cbc-806e-47f7-aa18-08ced1445013)
>
</details>

- [Find a VA Location page](https://staging.va.gov/find-locations) for inspiration
- [Mural - Research next steps](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1731950503702/187f8510c3ff36b6a5f92a5442b77fbc976a93cc)
- [Figma - design explorations](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=3575-13565&node-type=canvas&t=4MbMQy84EvcwPAHZ-0)

## Tasks
- [x] [UX] Explore content updates to provide guidance on the search & selection page
- [x] Review option(s) as a team
- [x] Create tickets for development

## Acceptance Criteria
- Content exploration is done and we have decided on how best to provide guidance on the 10-10CG facilities search page

**Comment by jessicastump** [comment]
Content draft designs - [Fimga link](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=3623-6226&t=umF8sgDK8Yj0LNvB-4) (includes proposed search button changes in this design too)

**Comment by jessicastump** [comment]
Content recommendations post CAIA review from Aliyah:

- Headline and body copy changes
- Additional instruction content in search box
- Headline label above search results

-----


![Image](https://github.com/user-attachments/assets/357352e6-5335-417c-92db-bd04257247bb)

-----


@hdjustice and @aagosto90 - Another async review item -- or next week meeting? :)

**Comment by hdjustice** [comment]
I like this better.  Originally, i think folks missed that the header was a question.  With the header change and the instructions below it, i think that helps alot.

**Comment by jessicastump** [comment]
Commenting on this ticket too :) - I think we can close out the design exploration part (and had CAIA / Aliyah review too!) 

This can also be tied to resolve the Staging Review tickets: 99047 and 99050

**Comment by hdjustice** [comment]
yep agreed.

**Comment by jessicastump** [comment]
Closing and tagged in staging review tickets and [development ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99135)
