### ISSUE TITLE
Transition Settings in vets-api to New Convention

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#97716]
Vets-api Settings need to be updated to use the new key convention

More information on Convention: [Confluence page](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3653173381/vets-api+helm+chart+normalization+-+Settings+Transition+Plan#Convention%3A)

## Tasks
- [ ] Transition Settings for Vye module for new convention (6x)
- [ ] Transition Settings for Veteran module for new convention (1x)
- [ ] Transition Settings for VBA Documents module for new convention (11x)
- [ ] Transition Settings for VA Notify module for new convention (1x)
- [ ] Transition Settings for Travel Pay module for new convention (8x)
- [ ] Transition Settings for Test User Dashboard module for new convention (3x)
- [ ] Transition Settings for Mobile module for new convention (14x)
- [ ] Transition Settings for Meb API module for new convention (1x)
- [ ] Transition Settings for IVC Champva module for new convention (4x)
- [ ] Transition Settings for Identity module for new convention (20x)
- [ ] Transition Settings for Health Quest module for new convention (7x)
- [ ] Transition Settings for Facilities module for new convention (7x)
- [ ] Transition Settings for DHP Connected Devices module for new convention (10x)
- [ ] Transition Settings for Debt Api module for new convention (7x)
- [ ] Transition Settings for Debt Management module for new convention (1x)
- [ ] Transition Settings for Covid Vaccine module for new convention (4x)
- [ ] Transition Settings for Claims Api module for new convention (12x)
- [ ] Transition Settings for CheckIn module for new convention (9x)
- [ ] Transition Settings for Appeals Api module for new convention (10x)
- [ ] Transition Settings for that start with A or B for new convention (19x)
- [ ] Transition Settings for that start with C for new convention (11x)
- [ ] Transition Settings for that start with D for new convention (12x)
- [ ] Transition Settings for that start with E for new convention (10x)
- [ ] Transition Settings for that start with F for new convention (28x)
- [ ] Transition Settings for that start with G for new convention (18x)
- [ ] Transition Settings for that start with H or I for new convention (13x)
- [ ] Transition Settings for Lighthouse for new convention (28x)
- [ ] Transition Settings for that start with L (not lighthouse) for new convention (8x)
- [ ] Transition Settings for that start with M for new convention (26x)
- [ ] Transition Settings for that start with N, O, or P for new convention (12x)
- [ ] Transition Settings for that start with R for new convention (8x)
- [ ] Transition Settings for that start with S for new convention (22x)
- [ ] Transition Settings for that start with T for new convention (3x)
- [ ] Transition Settings for VA Form, VA Mobile, VA Profile module for new convention (9x)
- [ ] Transition Settings for Virtual Regional Office module for new convention (4x)
- [ ] Transition Settings for that start with V (other than above) for new convention (23x)
- [ ] Transition Settings for that start with X, Y, or Z for new convention (12x)

## Acceptance Criteria
- [ ] All settings use the new convention

**Comment by stevenjcumming** [comment]
Need to determine what to do with Settings what use files...
