### ISSUE TITLE
Move hardcoded Settings to vets-api

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#97711]
Some settings (~60) are hardcoded and the same in dev, staging, sandbox, and prod. These settings can be moved to `config/settings.yml`

## Tasks
- [x] Add these settings/values to `config/settings/production.yml`
- [x] Remove them from environment helm charts (lowers and prod)

## Acceptance Criteria
- [x] All hardcoded and matching settings/values are out of the helm charts & in `config/settings/production.yml`

**Comment by stevenjcumming** [comment]
Closing just waiting for PR approval and merging
