### ISSUE TITLE
Update Form Fields and Content Within PCPG (CH36)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9773]
## Goal
While the pages have been scaffolded, the form fields and pieces of content need to be updated to match the prototype so that this feature can move closer to its next step.

## Considerations
- Link to [prototype](https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/128093537/simulate/sitemap)
- [Changelog](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design)

## Tasks
- [x] Update fields per prototype
- [x] Update content per prototype

## Acceptance Criteria
- [x] The fields and content have been updated.
- [x] A PR has been requested for merging
