### ISSUE TITLE
BE | Profile | Notification Settings | Map Sensitive Indicator Fields

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#97734]
## Background
VA Profile has added sensitive indicator fields to the QA environment as of 11/15.  
- `defaultSensitiveIndicator`
- `sensitiveIndicator`
- `sensitive`

## Tasks
- [x] Confirm that the sensitive indicator fields are in QA environment.
- [ ] Map new fields for GET requests.
- [ ] Map new fields for POST/PUT requests.
- [x] Fill out, review, and submit VA Pro intake form for default sensitive indicators.

> _Note: no feature flag is needed at for this._

## Acceptance Criteria
- [ ] New specs have been added to test the mappings.
- [ ] Verify in staging:
  - [ ] The sensitive indicators are returned from the vets-api.
  - [ ] The sensitive indicators are permitted and included on POST/PUT requests.
- [ ] Review with FE engineers.
- [ ] Swagger and [notification settings product docs](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/notification_settings/backend_documentation.md) have been updated

**Comment by tpharrison** [comment]
@a6marinos As discussed, this is the ticket for the BE sensitive indicator work.

**Comment by tpharrison** [comment]
@a6marinos @ACParker89 - Please roll this to next sprint with 3 points.

**Comment by tpharrison** [comment]
I’m uncertain which communication item channels include a sensitive indicator. I reached out to Autumn Atchley on Monday, December 9th, to inquire.

**Comment by ACParker89** [comment]
Closing. Will pull in post code freeze 

AP

**Comment by adamodd** [comment]
Hi @emisparkles , some starting notes if it helps:

- path on staging 
https://staging.va.gov/profile/notifications
  - some api endpoints of interest
    - GET /v0/profile/communication_preferences
    - PATCH /v0/profile/communication_preferences/{communicationPermissionId}
- docs on test case & users. some info is stale
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md
  - i was able to find enough for my purposes with "vets gov user 50", which only has a text option, not email
- frontend mock data arrangement which shows the vars from this ticket's description
https://github.com/department-of-veterans-affairs/vets-website/pull/33688/files#diff-47352bfc7b0a63b0d42f1e6ed78ebd7672e58aa6ff9bc5a18862ee04c7ef74bf

**Comment by emisparkles** [comment]
Confirmed in the [VA Profile QA communication-hub](https://qa.vaprofile.va.gov:7005/communication-hub) that these boolean indicator fields exist.

`CommunicationPermission` > `sensitive`
Indicates whether a user has granted/denied permission to send sensitive information

`CommunicationItemChannel` > `defaultSensitiveIndicator`
Indicates a specific item within a specific communication channel may contain sensitive info without the user setting explicit permission

`CommunicationItemChannel` > `sensitiveIndicator`
Indicates a specific item within a specific communication channel has the ability to include sensitive info

**Comment by mtcA6** [comment]
These indicators exist because we requested them through the intake process. 

I don't think we need to complete an intake w/VA profile to connect to this.

**Comment by mtcA6** [comment]
Also, the indicators that require it, appointment reminders, I believe already has the indicator available.  No others require it (it being the sensitive indicator) at this time.

**Comment by emisparkles** [comment]
That was my next questions re: an above comment

> I’m uncertain which communication item channels include a sensitive indicator. I reached out to Autumn Atchley on Monday, December 9th, to inquire. Waiting to hear back...

So, the only communication item that needs this indicator is an appointment reminder, which can be sent via a text or email channel, correct?

What do you mean by appointment reminders already having the indicator available?

**Comment by mtcA6** [comment]
Yep should be on appointment reminders for either channel.

**Comment by mtcA6** [comment]
This is no longer needed. The privacy office determined that PHI/PII is required in the appointment reminder for them to be meaningful and there will not be an option to have an alert w/o phi/pii.

**Comment by emisparkles** [comment]
## Work Summary
*A summary of my completed work before we became aware of the decision not to move forward*

### Research & Implementation

#### Discovery

- Located the [VA Profile Communication Hub API](https://qa.vaprofile.va.gov:7005/communication-hub) documentation
    - Confirmed the `sensitive` field is included in `GET/PUT/POST` requests for `CommunicationPermission
    - Confirmed the `sensitive_indicator` and `default_sensitive_indicator` fields are included in `GET` requests for `CommunicationItemChannel`
- Read the API and BE documentation to understand the expected communication preferences structure and the definition/purpose of the various fields
- Examined mocked frontend code to understand the expected payload structure from Notification Settings
- Considered whether to include the Flipper toggle `profile_appointment_reminder_with_phi` on the BE

#### Completed Work

- Added the optional `sensitive` attribute to the `CommunicationPermission` model
- Whitelisted the `sensitive` field for incoming updates in the controller
- Added the `sensitive_indicator` and `default_sensitive_indicator` attributes to the `CommunicationChannel` model
    - Updated the `create_from_api` method to conditionally assign the sensitive permission and sensitive indicators based on their presence in the payload
    - Extracted helper methods from `create_from_api` to keep code DRY and adhere to linting rules on method length
- Added logic to conditionally serialize the `sensitive` permission is into outgoing payloads via the `CommunicationItem` model's `in_json` method
- Utilized AI tools to comprehend and trace data flow from the VA Profile API through service methods, model builders, and the controller response
- Updated fixtures and VCRs and created unit tests to account for the new fields

#### Planned Work

- Collaborate with our frontend developer to confirm payloads and endpoints, and to assist with frontend implementation
- Pair with another backend developer to
    - Perform functional testing within a development environment
    - Use the rails console to verify my code correctly calls the API
- Add tests to the `CommunicationPreferencesController`
- Document the new fields in Swagger
- Update the contact center guide and our backend documentation
