### ISSUE TITLE
Gather Resources to work with VAHB Wireframes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#97762]
## Tasks
- [x] Identify which screens we can work on
- [x] Review VAHB Library to identify the needed component files
- [x] Review VAHB designs to identify similar page patterns
- [x] Build hi-fidelity wireframes for
  - [x] Demo questions 
  - [ ] ~Confirmation page~ (Not possible before eng discovery)
  - [ ] ~(If time, can work on confirmation page alert versions)~ (Not possible before eng discovery)
- [x] Review with UX

## AC
- [x] Hi-fidelity wireframes created for
  - [x] Demo questions 
  - [ ] ~Confirmation page~ (Not possible before eng discovery)
  - [ ] ~(If time, can work on confirmation page alert versions)~ (Not possible before eng discovery)
- [x] Reviewed with UX

## Figma link to the latest mobile app pre-check-in file:
- https://www.figma.com/design/EqA0zouiQYfXPNma4jV1CR/VAHB-Mobile-App-%7C-PCI?node-id=4-20&t=YYXBwvqVZitCUyno-1

**Comment by cgednalske** [comment]
@zach-park I took a look at the userflow(s) based on our refinement discussion, and the screens within [this box + the confirmation page](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1732046663886/09f5f082d33ea39fff3e7321b4c502d49c053b34?wid=0-1732135578894) will be needed regardless of outcomes with the backend.

- Demo questions 
- Pages for do you want to edit this demo question (note: might not need this if we instead have an edit button in the demo questions page - explore both)
- Confirmation page

**Comment by cgednalske** [comment]
I also added "Review VAHB designs to identify similar page patterns" to the tasks.

**Comment by zach-park** [comment]
Reference: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1732046663886/09f5f082d33ea39fff3e7321b4c502d49c053b34

**Comment by zach-park** [comment]
Figma document created:
https://www.figma.com/design/EqA0zouiQYfXPNma4jV1CR/VAHB-Mobile-App-%7C-PCI?node-id=4-20&t=VUMTSEgfbiXPnA54-1

**Comment by cgednalske** [comment]
@zach-park want to double check that it's clear that we won't end up with a entire happy path from this ticket. The only screens we can actually design right now are the following (also listed above):

Build hi-fidelity wireframes for
- [ ] Demo questions
- [ ] Confirmation page
- [ ] (If time, can work on confirmation page alert versions)

Doesn't mean you can't get familiar with the usual mobile setup of other screens, but this is all we can do before backend questions are answered.

**Comment by zach-park** [comment]
Noted!

**Comment by cgednalske** [comment]
@zach-park fyi I crossed out the tasks and AC related to the confirmation page
