### ISSUE TITLE
[CDP][DD] Add AskVA instructions for Disputing Debt to Debt Portal

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#97779]
Add instructions and action link to AskVA on the Resolve section of VHA and VBA Debt Portal

## Tasks
- [ ] Mock up Figma file for VBA/VHA Resolve section

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] VBA/VHA Resolve section mock ups are created

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by mgleo** [comment]
Rough draft of language for VHA and VBA added to Figma for review: https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=4425-28579&t=lGgRsJtPhrIUCIjs-1

Instructions are based on latest version of AskVA, seen here: https://staging.va.gov/contact-us/ask-va-too/introduction
This version of AskVA will be released in a month according to AskVA designer, Thomas Michaud.
