### ISSUE TITLE
Add Redux Code for BE Communications for "View your VA payment history"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9777]
## Goal
Currently we have hard coded the data on the front end, we need to stub out the redux code to make a call to the BE to get this data even if the BE does not have an endpoint set up yet.

## Tasks
- [x] Establish the redux code to make a call to the BE
- [x] Test redux code

## Acceptance Criteria
- [x] Redux code is in place and is ready for BE

_See what comes of BE discussion with BGS on payment things_
