### ISSUE TITLE
686+674 | Trigger for Claim Received Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97816]
## Issue Description
_As a Veteran, I need to receive a "claim received" email when I submit a claim on VA.gov._

The existing email needs to be renamed from “686-c Application Confirmation” to "21-686c and 21-674 Received" before we push it to production.

## Resources
- [VA Notify Platform Overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#successes)
- [VA Notify GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify)
- [VA Notify Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/VA%20Notify%20Playbook.pdf)
- [API docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#reviewing-our-api-docs)
- [Completing the "create trigger" tickets](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Strike/Completing%20Trigger%20Tickets/create_trigger.md)
- [Forms Strike Team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/form%20confirmations) can assist with setting up a confirmation email trigger
- **Template ID:** 7dfb84ef-3743-4dd3-a16b-6b0e07828957

---
## Tasks
- [ ] Build notification code to call the VA Notify API
   - [ ] Notification should trigger an email when a claim is successfully received by systems downstream from VA.gov
   - [ ] The default email address should be the email the user entered into the form. If no email exists within the form, use their MyVA profile email.
   - [ ] Rename it from “686-c Application Confirmation” to "21-686c and 21-674 Received" 
- [ ] Test notification by logging into staging with a test user, updating the profile ID to something that sends to you
- [ ] Determine alerting and error handling if email fails to deliver

## Acceptance Criteria
- [ ] A notification trigger that sends an email to claimant when their claim is is successfully received by systems downstream from VA.gov
- [ ] Email renamed from “686-c Application Confirmation” to "21-686c and 21-674 Received" 
- [ ] Logging and monitoring for failed sends
- [ ] Logging and monitoring for successful sends

**Comment by steele-lm** [comment]
Email template is available on VA Notify.
