### ISSUE TITLE
Design | 686+674 | Received Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97815]
## Issue Description
_New confirmation (received) email templates are available. We need to review the current template the form is using and determine if updates need to be made. The 686 and 674 currently each have their own confirmation emails, but a new one needs to be created for a combined 686+674 claim. Stage 3 SZF_

- [Current emails](https://docs.google.com/document/d/1kkbkDhgaGJuNrJbz2uHZGWAmbAq0ac21_nkpDQ8FkTc/edit#heading=h.nvwukvkz72q6) in use that need to be updated.
- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks
- [ ] Draft copy for a new 686+674 "claim received" email
- [ ] Review copy with stakeholders
- [ ] Review copy with CAIA
- [ ] Create template in VA Notify

## Acceptance Criteria
- [ ] Confirmation email template is created in VA Notify

**Comment by fiorella-io** [comment]
We are waiting on the platform team to see if we should include a link to My VA in all our "received" emails to match the confirmation page. [See thread](https://dsva.slack.com/archives/C07KTTFP308/p1734028133892479).

**Comment by fiorella-io** [comment]
We decided to add a note to inform claimants of the timeframe they have to submit additional evidence when the VA requests it. [See thread](https://dsva.slack.com/archives/C06E83RNLQM/p1733862969116559).
