### ISSUE TITLE
Guidance on using Flippers in tests

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#97819]
## User Story
As a developer in vets-api, I want clear guidance on how to enable and disable Flippers in specs, so that flippers don't interfere with each other during parallel test execution.

## Issue Description
We have [flipper guidance](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#FeatureTogglesGuide-Backendexample) on the Platform Website that recommends using mocks instead of simply enabling or disabling a flipper. Some people have faced some [problems](https://github.com/department-of-veterans-affairs/vets-api/pull/19478/files#r1847626341) with the mocking method. We should have clear guidance on how to deal with flippers in tests.

- We could do something [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/spec_helper.rb#L188):
```ruby
  config.before(:all, :enable_csrf_protection) do
    @original_allow_forgery_protection = ActionController::Base.allow_forgery_protection
    ActionController::Base.allow_forgery_protection = true
  end
```
to tell each process to use it’s own flipper memory adapter so then people could just do flipper.enable/disable in their tests and they wouldn’t interfere with each other. And then mocking wouldn't be necessary.
When specs run locally, these flipper adapters are used for tests:
```
Flipper adapter: Flipper::Adapters::Memoizable
Underlying adapter: Flipper::Adapters::Instrumented
```
- Look into mocking more. If [this line](https://github.com/flippercloud/flipper/blob/main/lib/flipper/test_help.rb#L30) is getting called, we shouldn’t need a mock. Is it not being called?

## Tasks
- [ ] Investigate what the solution should be for using Flippers in tests
- [ ] Update guidance for [Platform Website](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#FeatureTogglesGuide-Backendexample). Update ➡ [this confluence page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/590938137/Feature+Toggles+Guide#Backend-example).
- [ ] Communicate update in backend-cop Slack channel. 

## Acceptance Criteria
- [ ] Change has been communicated to CoP members 
- [ ] Documentation is updated. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
