### ISSUE TITLE
[Design] MDT - Error 500 alert

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#9782]
## Issue Description
_The Medical Device Reordering Tool needs to display an alert for Error 500 (Internal Server Error). The design team and frontend team need to determine if VA.gov has an existing Error 500 alert. If not, the design team needs to create one._

[Reference this ticket for full scope of the problem
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9626)

---
## Tasks
- [x] _Determine if VA.gov has a generic Error 500 alert_
- [x] _If VA.gov has a generic Error 500 alert pattern, direct the frontend team to that alert_
- [x] _If VA.gov does not have a generic Error 500 alert, create a design and provide it to the frontend team_

## Acceptance Criteria
- [x] _A design for an Error 500 alert is created and uploaded to InVision_
- [x] _Design is linked in this ticket_
- [x] _Ticket for frontend implementation is created_

---

**Comment by rileyorr** [comment]
<img width="1065" alt="Screen Shot 2020-06-03 at 11 08 38 AM" src="https://user-images.githubusercontent.com/46329147/83662804-02456080-a596-11ea-9ae3-369fb4c0cea4.png">

Found an example of an 500 alert message. Going to adjust the content to align with our product.

**Comment by rileyorr** [comment]
The example of the Error 500 alert message I mentioned in the above comment can be viewed in the [File for disability compensation (VA Form 21-526EZ)](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction) form when logged in as vets.gov.user+1@gmail.com. 

I adjusted the content in the 21-526EZ's error 500 alert to align with our product. [The design can be viewed on InVision](https://vsateams.invisionapp.com/share/6MVTG94WNH5). The [content can be copied from the MDT's GH documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-introduction-screen.md#description-4).

**Comment by rileyorr** [comment]
@mr0sari0 and/or @bradl3yC Whenever you get a chance can you take a look at the design and let me know if it's feasible to implement? Thanks!

**Comment by bradl3yC** [comment]
@rileyorr @mr0sari0 @rebeccawalsh I will take it :)

**Comment by rileyorr** [comment]
Thanks @bradl3yC! I've created [a ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9850) and assigned it to @mr0sari0.
