### ISSUE TITLE
Design | 686+674 | In-progress Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97829]
## Issue Description
_When a user submits a combined 686+674 claim on VA.gov, they should receive an email letting them know their claim submission is in-progress._

- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks
- [ ] Customize in-progress email text to reflect a combined claim submission
- [ ] Confirm copy with stakeholders
- [ ] Confirm copy with CAIA
- [ ] Create email template in VA Notify

## Acceptance Criteria
- [ ] In-progress email has been created in VA Notify
---

**Comment by fiorella-io** [comment]
There’s a section where we are supposed to provide a timeframe estimate.
`This process may take up to [ESTIMATED NUMBER OF DAYS BETWEEN SUBMISSION AND RECEIPT] days.`

I requested our engineering team to provide me with an estimated average time and the minimum and maximum time it could take for 686c, 674, and combined submissions.
