### ISSUE TITLE
[Design] MDT - Order submission failed

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#9783]
## Issue Description
_When a Veteran places an order for hearing aid batteries and/or accessories, there is a chance that the order may not go through. We need to design a solution that alerts Veterans that their order has not been submitted and provide next steps for placing an order._

---
## Tasks
- [x] _Sync with frontend/backend devs to understand why this error may occur_
- [x] _Design a solution alerting why the order has not been submitted and next steps for placing an order_
- [x] _Link InVision mockup to this ticket_
- [x] _Create a ticket for frontend implementation_

## Acceptance Criteria
- [x] _Design solution is validated by frontend development team_
- [x] _InVision mockup is linked in this ticket_
- [x] _Ticket for frontend implementation is created_
---
