### ISSUE TITLE
Create duplicate submission baseline metric

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97845]
## Issue Description
As a VFS team member I want to create a baseline metric for duplicate submissions so that when I deliver features I expect that will address this problem I can know if what I've delivered is successful.

## Tasks
- [x] paste scripts found here into [argo](https://argocd.vfs.va.gov/applications/vets-api-prod): [super-duper de-duper](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/526/TREX/DEBUG/remediation_playbook.md)
     - [x] `bundle exec rails c -s -- --noautocomplete`
- [x] run scripts to get duplicate submission counts (see below in Additional Information)

## Acceptance Criteria
- [x] Determine whether submissions are duplicates based on a subset of meaningful fields (contentions, answers to retirement pay, etc) 
- [x] Average number of duplicate Submissions per month is also known, using data from Sept. Oct, and Nov

## Additional Information

1. get all unique user ids for the submissions over 3 months or 1 month or whatever timeframe
```
start_date = DateTime.parse('2024-11-01 00:00:00')
end_date = DateTime.parse('2024-11-30 11:59:59')

subs = Form526Submission.where(created_at: start_date..end_date)
user_uuids = subs.select(:user_uuid).distinct
```
2. run the de-duper script over all the unique user ids
3. loop over the `user_uuids` and run `DuplicateSetBuilder.run` to get an Array of Arrays consisting of duplicates
```
duplicate_count = 0
user_uuids.each{ |uuid| 
  duplicate_sets = DuplicateSetBuilder.new(uuid:) .run 
  duplicate_sets.each { |set| count += set.count - 1  } 
}
```
4. DISLCAIMER: all code above is pseudo code. not tested. at all.

8. We won't consider submissions/users that cross the month boundary. Example: user submits 10/31/2024, then comes back the next day to submit the same data. This baseline doesn't need to be perfect down to the last number. Directional is fine given that we have such a large sample size.

**Comment by sethdarragile6** [comment]
Findings and methods documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/duplicate_submission_metrics.md)

In a nutshell, the monthly duplicate submission percentages were found to be:
- Sept 24: 1.27%
- Oct 24: 1.23%
- Nov 24: 1.31%

Querying the entire Sept-Nov as one run gave us 1.38%
