### ISSUE TITLE
Draft communication strategy for tool adoption

### ISSUE THREAD

**Issue by candilemoine** [department-of-veterans-affairs/va.gov-team#97850]
### Description
After identifying our pilot participants, we can collaborate with Marty for tool adoption.

### Tasks
- [ ] obtain feedback on tool adoption from VSO liaison 
- [ ] understand the method of communication with participants
- [ ] draft an outline of content needed

**Comment by candilemoine** [comment]
Testing Slack notification
