### ISSUE TITLE
[Design] DL - Debt list, Current debts, default (HiFi)

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#9786]
## Issue Description
We need to create mockups of the debt list screen, showing debts populated under current debts:
- Debt with no action taken (ex: pension debt with no benefits to withhold) 
- Debt with action taken (ex: compensation debt that is being repaid out of pocket)
- Ch 35 triple debt (for illustration's sake)

---
## Tasks
- [x] Create mockups
- [x] Share with design team
- [x] Update [use case doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/use-cases.md)
- [x] Update this ticket

## Acceptance Criteria
- [ ] Screen(s) created with each of the debt statuses above
- [ ] [Use case doc updated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/use-cases.md)

**Comment by rebeccawalsh** [comment]
Find the design in the use case documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/use-cases.md#veteran-with-debts-wants-to-view-them-online)
