### ISSUE TITLE
Send 674-only claims to RBPS

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97875]
## Issue Description
_Currently, 5,750 674-only claims per month are manually off-ramped by VA.gov (through BIS) to Central Mail for manual processing. VA.gov does not send these claims to RBPS. RBPS confirmed on 12/16/24 that RBPS is capable of processing 674-only claims for existing dependents and has requested that VA.gov now send 674-only claims to RBPS._

VA.gov sends claim with a "claim type" of `MANUAL_VAGOV` with a note to BIS, and the suspicion is that BGS then off-ramps the claim to Central Mail.

Update this [flow chart](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727757799534/c7c5f5a6dc1b8f451ecab5f02afa70a9325b93c8) to reflect all off-ramp behavior.

Current submission pathway for 686 claims, but this will change when the new SOAP API is implemented:
- The claim gets created and calls the DependentService.
- It then first runs the pdf job which sends the pdfs off to vbms.
- It then calls the sidekiq jobs for 686 and/or 674. In the 674 sidekiq job it calls up the bgs form674 class which calls the various bgs methods to create Benefit Claims but also marks the claim type as MANUAL_VAGOV to prompt them to review the pdf (if im understanding their flow correctly on that end of things) 

Before implementing this change, a meeting with BGS, VBMS, and RBPS stakeholders is needed to determine what 674 claim data needs to be sent. Meeting held on 12/16.
- Whatever attributes we're renaming for the payload on v2 we probably won't have to coordinate with the bgs end, because we end up mapping those payload attributes to conform to bgs. but we will definitely want to see how they'd in theory receive 674 type attributes. we may need more bgs models on our end (and probably in the bgs-ext repo) 

Background:
- The pension line of business originally requested that RBPS be updated to simplify the processing of pension applications via dependency claims in 2020. [This](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7759) is the original VA.gov epic for that work.
- This project involved [adding two income questions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8777) to the 686/674 form flow on VA.gov:
   - Did this dependent have income in the last 365 days?
   - Did the household have a total income less that $xxx in the last tax year?
- These questions were supposed to be conditionally shown to Veterans who are receiving pension. VA.gov intended to leverage an API that indicated a Veteran's pension status and the annual net worth limit, but there were [issues connecting to the API](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76465). RBPS also may have [had issues](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18910) accepting the new income values from VA.gov.
- Because of these issues, the income questions were hidden in production (via a flipper), and [VA.gov](http://va.gov/) flagged 674-only claims for manual processing (bypassing RBPS).
- After meeting with BIS, VBMS, OBI, and RBPS stakeholders on 12/16, we confirmed that 674-only claims can be sent to RBPS without the income information. RBPS has the ability to determine which 674 claims impact pension benefits and will off-ramp those claims from RBPS for manual processing.
- Ideally, RBPS would have the income info from [VA.gov](http://va.gov/), so it could more effectively determine which 674-only claims impacting pension needed to be off-ramped rather than off-ramping all 674-related pension claims. But, this temporary solution ensures that the vast majority of 674-only claims, which do not impact pension, can be processed through RBPS.
- VA.gov agreed to remove the manual flag applied to 674-only claims in staging and work with RBPS stakeholders to test. RBPS did indicate that their testing bandwidth is limited bc of a migration they are completing in January.
- We will also work to test the pension benefit API and the related conditional question functionality. Once that functionality is confirmed, we can test sending the income+claim data to RBPS.

---
## Tasks
- [ ] Remove manual flag for 674-only claims in Va.gov staging environment
- [ ] Update logging and monitoring to check for failure and success
- [ ] Work with RBPS team to test a small batch of 674-only submissions in staging
- [ ] Launch in production once testing is complete/successful
- [ ] Update [flow chart](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727757799534/c7c5f5a6dc1b8f451ecab5f02afa70a9325b93c8) to reflect off-ramp behavior

## Acceptance Criteria
- [ ] 674-only claims submitted on VA.gov are sent to RBPS for automated processing.
- [ ] Logging and monitoring captures submission failures and successes
- [ ] Flow chart updated with off-ramp behavior
---

**Comment by steele-lm** [comment]
Met with BIS, VBMS, and RBPS stakeholders on 12/16. Stakeholders confirmed that VA.gov should be able to remove the manual_vagov flag from 674-only claims in VA.gov staging and send through test claims. Testing resources are limited, and stakeholders may not be able to test these claims until mid-January.

Sidenote: These claims were originally off-ramped bc VA.gov was not sending the income-related data (net worth and dependent income) to RBPS that is needed to process 674 claims involving pension. Linda Ciston confirmed that RBPS can still off-ramp any 674 claim related to pension itself if the VA.gov flag is removed.

**Comment by steele-lm** [comment]
Changes ready in Staging. Blocked until testing resources are available from RBPS team.
