### ISSUE TITLE
[Design] DL - Debt list, Current debts, empty state (HiFi)

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#9787]
## Issue Description
We need to create a mockup of the debt list screen's state if an individual has no current debts to list.

---
## Tasks
- [x] Create mockups
- [x] Share with design team
- [x] Update [use case doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/use-cases.md)
- [x] Update this ticket

## Acceptance Criteria
- [ ] Screen created 
- [ ] [Use case doc updated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/use-cases.md)

**Comment by rebeccawalsh** [comment]
Conversation concerning design can be seen [here.](https://dsva.slack.com/archives/C0NGDDXME/p1592511683441200)

Design can be seen [here](https://preview.uxpin.com/305eb36ed6ec2e5f2bc1dd91659b70ef961ab269#/pages/129917808/simulate/no-panels?mode=i).

Use case document updated [here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/use-cases.md)
