### ISSUE TITLE
[DD] Convert to minimal header

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97877]
## Issue Description
Convert form to use minimal header in the forms system. 

### Helpful links
(shoutout to @josephrlee  for all of these, you a real one)
- Mock form with minimal header example and loads of helpful links: https://staging.va.gov/mock-form-minimal-header
- [Slack convo](https://dsva.slack.com/archives/C044AGZFG2W/p1732554002394849) discussing minimal header in `#veteran-facing-forms`
- [Old slack convo](https://dsva.slack.com/archives/C044AGZFG2W/p1727979260362549)

## Tasks
- [x] Convert to using minimal header
- [x] Coordinate with design for testing

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [x] Dispute debt using minimal header
- [ ] Design approves implemented layout

## Testing
- [x] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by OptionSelect** [comment]
Content build pr merged.
