### ISSUE TITLE
AAR MVP User Test - Collab Cycle + Recruit

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#97882]
## Background
User testing of Appoint a Representative MVP on VA.gov with non-AT and AT users.

## Tasks

- [x] Request research review
- [x] Update user test to reflect collab cycle edits
- [x] Kick-off with Perigean
- [x] Set-up Enjoy HQ project
- [x] Create sign-up sheet
- [x] Set up Slack channel w/ observers
- [x] Create folders in Sharepoint
- [x] Create notes and debrief Mural
- [x] Create observer kick-off video
- [x] Transfer demographics to sign-up sheet & Excel
- [x] Conduct pilot session

## Acceptance Criteria
- [ ] All tasks complete

**Comment by oddball-lindsay** [comment]
Mentioning our research collab cycle ticket here for quick reference: https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/745#event-15530605983

**Comment by jfinnerty13** [comment]
Everything done and updated in Slack Canvas: https://dsva.slack.com/docs/T03FECE8V/F0814JAU831
