### ISSUE TITLE
AAR 1.0 (MVP) User Test - Conduct Interviews

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#97884]
## Background
User testing of Appoint a Representative MVP on VA.gov with Veterans who have worked or plan on working with an attorney or claims agent. [Resources in Slack](https://dsva.slack.com/docs/T03FECE8V/F0814JAU831)

## Tasks
- [ ] Complete interviews
- [ ] Manage interview day to day (team and recruiter coordination, debriefs, interviews, etc.)
- [ ] Download videos and transcripts
- [ ] Compile notes
- [ ] Upload notes, transcripts, and video to Sharepoint
- [ ] Upload notes and transcripts to EnjoyHQ

## Acceptance Criteria
- [ ] All tasks complete

**Comment by oddball-lindsay** [comment]
We had two Veteran interviews that were appointing a claims agent and an attorney. Feeling like we have enough learnings to synthesize trends. 

Since we no longer have Perigean support for rescheduling additional user interviews, we think we can wrap up this interview step and proceed on to analysis.

**Comment by MDomngz** [comment]
Upon the Perigean reinstatement, our Internal team discussions have determined that we are going to focus on analysis for **Appoint 1.0** (claims agents/attorneys) and focus on **Appoint 2.0 - Digital Sumit**

MD will notify Perigean of the decision to end the session.

**Comment by MDomngz** [comment]
[Location of Sharepoint folder](https://github.com/user-attachments/assets/98774869-e47e-46fb-b9be-01c91d6e7e86) for video, audio, and transcript files

Task - 

1. scrub any PII out - will use [platform guidance](https://depo-platform-documentation.scrollhelp.site/research-design/what-is-pii#) as source of truth
2. Upload files to EnjoyHQ for analyzing
