### ISSUE TITLE
[DD] Update Personal Information page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97890]
### NOTE
- This should likely wait until this LOA discovery is complete
#97919 
--- 

Update Personal Information page to match design

[Figma file for digital dispute](https://www.figma.com/design/D8tfoPhUZlqBUomMTxzkQb/Dispute-Form-(VHA-VBA)?node-id=19-220&node-type=canvas&t=3hWnN79h3avyyPDk-0)

**Note:** Need help footer is defined elsewhere in the form

![Image](https://github.com/user-attachments/assets/5003eda3-ed00-40ca-82c0-b7f0a4a8fc1f)

## Tasks
- [ ] Update Personal Information page
- [ ] Review changes with design 
- [ ] Add/update unit/e2e tests 

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Personal Information page matches design
- [ ] No linting warnings or errors
- [ ] All tests passing

## Testing
- [ ] Write/update tests for content or variable rendering

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by Dr-Pongo** [comment]
Marking has dependency for LOA checks ticket (listed above). Need to define what all we need to include for the dispute

**Comment by HeatherRienks** [comment]
FYI- the internal dependency has been completed in ticket #97919
