### ISSUE TITLE
686 674 | Separate Claim Received Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#97892]
## Issue Description
_Currently, when a 686 or 674 are submitted on VA.gov, the Veteran receives a single "claim received/confirmation" email that mentions both the 686 and 674 regardless if they only submitted one or the other. As a Veteran, when I submit a 686 or 674, I expect to receive a "claim received" email specific to the claim I submitted._

Design work to separate these emails is captured in #94277 and #82901 and #97815. We will also be implementing a new email for a 686+674 claim #97831.

---
## Tasks
- [ ] Create a separate VA Notify trigger for 686-only claims
- [ ] Create a separate VA Notify trigger for 674-only claims
- [ ] Create a separate VA Notify trigger for 686+674 claims
- [ ] Remove the existing VA Notify trigger that sends the existing 686/674 email for 686-only and 674-only claims

## Acceptance Criteria
- [ ] A 686-specific email is sent for 686-only claims
- [ ] A 674-specific email is sent for 674-only claims
- [ ] A 686+674 specific email is sent for 686+674 claims
- [ ] The current email mentioned both 686 and 674 is no longer sent for 686-only or 674-only claims

**Comment by steele-lm** [comment]
Email templates for individual 686 and 674 emails are available in VA Notify.

**Comment by fiorella-io** [comment]
Template IDs for all received emails:
- 686c: 85a1a8ea-41fa-47ec-ab36-5e1a1f686b72
- 674: 9786f6b0-a3fe-4a4b-8fb1-f63691ab4ac5
- Combined 686c/674: 714e4a8d-77b5-4d3f-93b8-1fc11ccf720b

**Comment by TaiWilkin** [comment]
@fiorella-io Are the template ids the same across environments, or are they different between staging and prod?

**Comment by fiorella-io** [comment]
The template IDs are different per email
