### ISSUE TITLE
[DD] Update Debt Selection page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97899]
## Issue Description
Update Debt Selection page to match design

[Figma file for digital dispute](https://www.figma.com/design/D8tfoPhUZlqBUomMTxzkQb/Dispute-Form-(VHA-VBA)?node-id=19-220&node-type=canvas&t=3hWnN79h3avyyPDk-0)

**Note:** Need help footer is defined elsewhere in the form

![Image](https://github.com/user-attachments/assets/b7c276c9-63ed-4366-8183-1b1a841e6db2)

## Tasks
- [ ] Update Debt Selection page
- [ ] Review changes with design 
- [ ] Update error messaging as necessary
- [ ] Add/update unit/e2e tests 

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Debt Selection page matches design
- [ ] Error messages match design
- [ ] No linting warnings or errors
- [ ] All tests passing

## Testing
- [ ] Write/update tests for content or variable rendering

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
