### ISSUE TITLE
[DD] Update Confirmation page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97901]
## Issue Description
Update Confirmation page to match design

[Figma file for digital dispute](https://www.figma.com/design/D8tfoPhUZlqBUomMTxzkQb/Dispute-Form-(VHA-VBA)?node-id=19-220&node-type=canvas&t=3hWnN79h3avyyPDk-0)

**Note:** Need help footer is defined elsewhere in the form
![Image](https://github.com/user-attachments/assets/6c896d04-e557-4256-a323-44b16889460b)

## Tasks
- [x] Update Confirmation page
- [x] Review changes with design 
- [x] Update error messaging as necessary
- [x] Add/update unit/e2e tests 

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [x] Debt Selection page matches design
- [x] Error messages match design
- [x] No linting warnings or errors
- [x] All tests passing

## Testing
- [x] Write/update tests for content or variable rendering

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
