### ISSUE TITLE
[DD] Update Contact Information

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97903]
## Issue Description
Update Contact Information page to match design. This is a tricky fun one. Currently we're using a platform 'component' which is more of a generic definition for a set of commonly used pages that pulls profile contact info and links out to update it in profile as well. If this is just a visual update to the existing contact info flow that platform is expecting to go sitewide then maybe _(hopefully)_ we can just update that shared component with the new designs. 

Currently implemented component/pages `profileContactInfo` [source here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/definitions/profileContactInfo.js)

[Figma file for digital dispute](https://www.figma.com/design/D8tfoPhUZlqBUomMTxzkQb/Dispute-Form-(VHA-VBA)?node-id=19-220&node-type=canvas&t=3hWnN79h3avyyPDk-0)

**Note:** Need help footer is defined elsewhere in the form
![Image](https://github.com/user-attachments/assets/77122e1e-b710-49e3-94e4-bedc05c30b72)

## Tasks
- [ ] Confirm which phone number to use/display
- [ ] Update Contact Information page
- [ ] Review changes with design 
- [ ] Update error messaging as necessary
- [ ] Add/update unit/e2e tests 

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Debt Selection page matches design
- [ ] Error messages match design
- [ ] No linting warnings or errors
- [ ] All tests passing

## Testing
- [ ] Write/update tests for content or variable rendering

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by amponce** [comment]
I ran into a few issues aligning with the recommended design pattern without introducing custom components that could lead to code drift. A new ticket is needed to finalize the design once we know whether the platform will provide the pattern as a shared component or if we’ll need to create our own.

**Comment by amponce** [comment]
Example using the pattern currently available:

![Image](https://github.com/user-attachments/assets/c6c8ebb8-6075-48f1-89e5-5de54b9b67cf)

**Comment by amponce** [comment]
Follow up ticket

https://github.com/department-of-veterans-affairs/va.gov-team/issues/109263
