### ISSUE TITLE
[DD] Update Transform and submit

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97907]
## Issue Description
We need to add a definition for `transform` to align the form data structure with the expected format for the data contract with `vets-api` dispute debt endpoint (`/debts_api/v0/digital_disputes`). The `submit` definition can handle some metric definitions and include the payload delivered from the `transform` definition. 

You can reference FSR [transform definition](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/utils/transform.js) and [submit definition](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/config/submitForm.js) 

## Tasks
- [x] Add `transform` so form data structure matches expected data contract with `vet-api`
- [x] Add `submit` definition to include metrics for tracking and payload from `transform`
- [x] Add unit test helpers
- [x] Add/update e2e tests

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] Debt Selection page matches design
- [ ] Error messages match design
- [ ] No linting warnings or errors
- [ ] All tests passing

## Testing
- [ ] Write unit tests for expected input/output for transform
- [ ] Write unit tests for expected input/output for submit

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by Dr-Pongo** [comment]
Marking has dependency since we still have floating questions on payload to BE and downstream

**Comment by Dr-Pongo** [comment]
We leverage the transform to change the shape of the FE form data to match what our vets-api endpoint is expecting. We need to finalize the FE pages and confirm all of the properties the BE is expecting. I think there's still an open question on if we need the veteran DOB and SSN to complete the form as well.

**Comment by HeatherRienks** [comment]
@denisecoveyduc -  Do you know if the Veteran DOB and SSN are needed to complete the form? If not, who is the best person to contact?

**Comment by HeatherRienks** [comment]
@Dr-Pongo - FYI :)

**Comment by Dr-Pongo** [comment]
Thank you all! leaving this as has dependency as we finalize the pdf submission stuffs

**Comment by HeatherRienks** [comment]
Per @Dr-Pongo - this "might" not be needed  - more to come
