### ISSUE TITLE
[DD] Update Review and Submit page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97900]
## Issue Description
Update Review and Submit page to match design

[Figma file for digital dispute](https://www.figma.com/design/D8tfoPhUZlqBUomMTxzkQb/Dispute-Form-(VHA-VBA)?node-id=19-220&node-type=canvas&t=3hWnN79h3avyyPDk-0)

**Note:** Need help footer is defined elsewhere in the form
![Image](https://github.com/user-attachments/assets/b791e2b9-8143-4b42-b788-7b6ab32a0623)

## Tasks
- [ ] Update Review and Submit page
- [ ] Review changes with design 
- [ ] Update error messaging as necessary
- [ ] Add/update unit/e2e tests 

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Debt Selection page matches design
- [ ] Error messages match design
- [ ] No linting warnings or errors
- [ ] All tests passing

## Testing
- [ ] Write/update tests for content or variable rendering

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by mgleo** [comment]
@Dr-Pongo 

https://zyc78g.csb.app/review-and-submit

**Comment by amponce** [comment]
Draft PR is up, I added the select debt section as well, I'll run it past design on Monday

![Image](https://github.com/user-attachments/assets/44594e46-a2e8-4502-99c1-5bc702b1f930)
