### ISSUE TITLE
[DD] Custom form content/messaging

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97915]
## Issue Description
Forms system has built in options for some custom messaging, so let's define those bad boys. Some of the messaging includes:
- `savedFormMessages`
- `saveInProgress`
- `customText`

You can reference other forms [including 5655](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/config/form.js) for examples. 

[Figma mockups for digital dispute](https://www.figma.com/design/D8tfoPhUZlqBUomMTxzkQb/Dispute-Form-(VHA-VBA)?node-id=19-220&node-type=canvas&t=3hWnN79h3avyyPDk-0)   

## Tasks
- [x] Coordinate with design for message content
- [x] Implement changes
- [ ] Add testing if necessary

## Design and Front End sync on implementation of design
- [x] Required
- [x] Complete
- [ ] Not Required           

## Acceptance Criteria
- [x] All custom content/messaging as been implemented

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by amponce** [comment]
@mgleo Hey Megan,

I’m updating the default **form-config messages** for the Digital Dispute workflow and could use your content eye. Below is the draft copy (first block) and, for comparison, the approved FSR copy (second block). Could you review the Digital Dispute wording and help me tighten it up?

```js
// Digital Dispute – current draft
export const TITLE = 'Dispute your VA debt';
export const SUBTITLE = 'Process to dispute debt';

saveInProgress: {
  messages: {
    inProgress:
      'Your digital dispute for debts application (DISPUTE-DEBT) is in progress.',
    expired:
      'Your saved digital dispute for debts application (DISPUTE-DEBT) has expired. If you want to apply again, please start a new application.',
    saved:
      'Your digital dispute for debts application has been saved.',
  },
},

savedFormMessages: {
  notFound:
    'Please start over to apply for digital dispute for debts.',
  noAuth:
    'Please sign in again to continue your application for digital dispute for debts.',
},

title: TITLE,
subTitle: SUBTITLE,
```

```js
// FSR – reference copy
savedFormMessages: {
  notFound:
    'Please start over to submit an application for financial hardship assistance.',
  noAuth:
    'Please sign in again to continue your application for financial hardship assistance.',
},
saveInProgress: {
  messages: {
    inProgress:
      'Your application for financial hardship assistance is in progress.',
    expired:
      'Your saved application for financial hardship assistance has expired. If you want to apply again, please start a new application.',
    saved:
      'Your application for financial hardship assistance has been saved.',
  },
},
title: 'Request help with VA debt for overpayments and copay bills',
subTitle: 'Financial Status Report (VA Form 5655)',
customText: {
  finishAppLaterMessage: 'Finish this request later',
  reviewPageTitle: 'Review your request',
  submitButtonText: 'Submit your request',
},
```

**Comment by mgleo** [comment]
// Digital Dispute – current draft
export const TITLE = 'Dispute your VA debt';
export const SUBTITLE = 'Process to dispute debt';

saveInProgress: {
  messages: {
    inProgress:
      'Your application for disputing your VA debt is in progress.',
    expired:
      'Your saved application for disputing your VA debt has expired. If you want to apply again, please start a new application.',
    saved:
      'Your application for disputing your VA debt has been saved.',
  },
},

savedFormMessages: {
  notFound:
    'Please start over your application to dispute your VA debt.',
  noAuth:
    'Please sign in again to continue your application for disputing your VA debt.',
},

title: TITLE,
subTitle: SUBTITLE,


Some ideas for custom messaging for the dispute form @amponce 

cc @denisecoveyduc For your awareness, let us know if you have any other suggestions.

**Comment by amponce** [comment]
@mgleo what do you think of:

```
 savedFormMessages: {
    notFound: 'Please start your application over to dispute your VA debt.',
    noAuth:
      'Please sign in again to continue your application to dispute your VA debt.',
  },
```
**instead of:**
notFound:`'Please start over your application to dispute your VA debt.'`
noAuth:`'Please sign in again to continue your application for disputing your VA debt.',`

**Comment by mgleo** [comment]
@amponce That's perfect! Thanks for catching that.
