### ISSUE TITLE
[DD] Update downtime definition

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97910]
## Issue Description
Update downtime definition for dispute debt, so proper alerts show when required upstream system is down for maintenance.          

## Tasks
- [x] Update downtime definition to include all required upstream services
- [ ] Test alerts

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] downtime definition updated and functioning as expected

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by amponce** [comment]
Showing downtime message

![Image](https://github.com/user-attachments/assets/2a77b10d-5337-4ab7-9572-aef72354bcf2)
