### ISSUE TITLE
[DD] LOA checks and messaging

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97919]
## Issue Description
Once we finally get word on if we need SSN/Filenumber on the FE we should investigate adding an alert for different [Levels of Assurance (LOA)](https://depo-platform-documentation.scrollhelp.site/developer-docs/authentication). 

The existing contact information page does a pretty good job of preventing veterans from continuing if they are missing required fields such as phone number, address, email address. Let's make sure if we need SSN/Filenumber from prefill/profile we can route them to correctly fill out that info before continuing the form. 

The default form creation includes checks for LOA, if needed let's leverage that to throw an alert that directs veterans to complete their profile as needed. Will likely need to work with design on this, but there are examples in other forms (maybe one of the other appeals?)

## Tasks
- [ ] Determine exactly what prefill info is needed
- [ ] Determine if LOA checks are needed (and)
  - [ ] Coordinate with design on alert message for veterans missing required info
  - [ ] Add necessary checks in the top level app to throw alert 
  - [ ] Write tests for alerts and checks

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Definitive answer to exactly what prefill data we need to pull 
- [ ] If LOA checks are necessary
  - [ ] LOA checks are implemented
  - [ ] Alerts are showing as expected
  - [ ] Tests are written for alerts & checks

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by OptionSelect** [comment]
Taking out of sprint for One VA Letter work per convo with Andrew yesterday.

**Comment by HeatherRienks** [comment]
Per @OptionSelect - this ticket is NOT critical to launch the MVP.
