### ISSUE TITLE
[DD] Add Need help footer definition

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#97913]
## Issue Description
Add "Need Help?" footer definition. This can be a new component referenced in the `formConfig` definition defined by the `getHelp` prop. 

[Figma mockups for digital dispute](https://www.figma.com/design/D8tfoPhUZlqBUomMTxzkQb/Dispute-Form-(VHA-VBA)?node-id=19-220&node-type=canvas&t=3hWnN79h3avyyPDk-0)   

![Image](https://github.com/user-attachments/assets/6a19a0b6-487d-406a-a662-418752983815)

## Tasks
- [x] Add Need Help component and
- [x] Confirm implementation matches design with design team
- [ ] If you can think of a good test to add for this add it

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Need Help section is defined for dispute debt
- [ ] No linting errors/warnings
- [ ] No console errors/warnings

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
