### ISSUE TITLE
[Design] DL - Debt list, Past debts, empty state (HiFi)

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#9791]
## Issue Description
We need to create a mockup of the empty state of the past debts section of the list page

---
## Tasks
- [ ] Create mockups
- [ ] Share with design team
- [ ] Update [use case doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/use-cases.md)
- [ ] Update this ticket

## Acceptance Criteria
- [ ] Screen created 
- [ ] [Use case doc updated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/use-cases.md)
