### ISSUE TITLE
Update BGS gem

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9792]
## Goal
The BGS gem is used to pass the calls used for the 686 into a chunk of Ruby code that allows for the application to more elegantly affect its tasks.

## Considerations
- Here is the previous [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9368)

## Tasks
- [x] Pass the data into the BGS gem as a hash as opposed to named parameters (or method args)
- [x] Include a helper function to validate the hash

## Acceptance Criteria
- [x] The BGS gem has been updated and a PR has been requested for merging

**Comment by digitaldrk** [comment]
Code is complete on the gem and requested review yesterday. Waiting for response.

**Comment by digitaldrk** [comment]
The gem PR was merged over the weekend
