### ISSUE TITLE
[Design] Debt detail page, Current debts (HiFi)

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#9793]
## Issue Description
We need to create mockups for the debt detail screen.

Include screens for:
- A debt that is new / has not been acted on (e.g. it is still progressing toward collection action)
- A debt that has resolution in-progess (e.g. not progressing toward collection action)

---
## Tasks
- [x] Create mockups
- [x] Share with design team
- [x] Update [use case doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/use-cases.md)
- [ ] Update this ticket

## Acceptance Criteria
- [x] Screen created 
- [x] [Use case doc updated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/use-cases.md)

**Comment by rileyorr** [comment]
I've updated the use case document. [This design's current iteration can also be found here](https://preview.uxpin.com/4081962ed045b5b2584e1a818b6b6f6b47071c0d#/pages/129818682/simulate/no-panels?mode=i).
