### ISSUE TITLE
Release Rated Disability 100%

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97933]
## Issue Description
As a VFS team member, I want to migrate rated disability API calls from EVSS to Lighthouse so that Veterans have a modernized experience that is technically sustainable. 

### Tasks
- [ ] 

### Acceptance Criteria
- [x] ModProd complete (including submission) and rated disabilities show up as expected in the VBMS
- [ ] Application monitoring will show that EVSS is no longer used for this purpose
- [ ] Release is performed as a cutover, not an incremental rollout

### Additional Information
[Datadog dashboard](https://vagov.ddog-gov.com/dashboard/rsy-rne-zut/benefits---disability---526---evss-to-lh-rated-disability?fromUser=false&from_ts=1733700266821&to_ts=1733786666821&live=true)

**Comment by mchae-nava** [comment]
Per guidance from David Reis [here](https://dsva.slack.com/archives/C04KW0B46N5/p1736889358426969?thread_ts=1736885454.049969&cid=C04KW0B46N5), start at 5% for a couple of days, then progress if no issues
