### ISSUE TITLE
Troubleshoot BGS Issues

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9794]
## Description
There are a few different things that need to get sorted with BGS:
- Sort out issue with date returning error in person call
  - We have a lead that it might be a change to the date format we are currently sending. Right now it is (mm-dd-yyyy) we think it needs to change to "iso." 
- Also we are struggling to get a proper response back from the `increment` / `insert_benefit` calls. We know we were creating/inserting benefits by looking in eBenefits.  We can successfully create benefits but never receive a success response in the process. The increment call was not returning incremented  `end_product_code`

## Tasks
- [x] Collaborate with any relevant partipants as needed
- [x] Establish a programmatic method for the insertion of a benefit
- [x] Test with a new range of users with, make some notes on what might be created for them

## Acceptance Criteria
- [x] A reliable increment call is returned
- [x] A benefit is inserted using the increment value
