### ISSUE TITLE
[Design] Debt detail page, Past debts (HiFi)

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#9795]
## Issue Description
We need to create mockups for the debt detail screen for past debts

---
## Tasks
- [ ] Create mockups
- [ ] Share with design team
- [ ] Update [use case doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/use-cases.md)
- [ ] Update this ticket

## Acceptance Criteria
- [ ] Screen created 
- [ ] [Use case doc updated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/use-cases.md)
