### ISSUE TITLE
Connect Digital Dispute Endpoint to Model

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#97958]
We have merged the Digital Dispute Endpoint, we have merged the Digital Dispute Model 🥳 .

Now, we need to connect the 2.

## Todo

- [ ] Initialize the Model in the endpoint
- [ ] Check if model is `valid?` if not, return error messages
- [ ] Write specs that show result
- [ ] Might have to update Swagger docs
- [ ] We will need to adjust our strong parameters for the data the form is sending
  - [ ] This might require is to make some changes in our model schema
- [ ] Maybe look into using the json-schema that Andrew wrote to validate the data.
