### ISSUE TITLE
Create List of Paths for Hardcoded Settings values

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#97969]
In order to remove the settings.local.yml config maps from the environment helm charts, hardcoded settings values will need to be moved to the param store secrets. 

These settings are hardcoded and not the same in all environments

## Tasks
- [x] Look for alternatives approaches to param store
- [x] Move hardcoded values that are just missing one environment to `config/settings/production.yml`
- [x] Create a list of paths for hardcoded settings values (~750 settings)

## Acceptance Criteria
- [x] No alternatives are reasonable/acceptable
- [x] List is created in helm mapping google sheet

**Comment by stevenjcumming** [comment]
Helm Mapping - Hardcoded to Param Store 

https://docs.google.com/spreadsheets/d/1-7PLskyY67b4J1fsk-FADYxnSN1UrmVziFfFIt_1saU/edit?pli=1&gid=1895045170#gid=1895045170
