### ISSUE TITLE
[Design] MDT - Empty states for hearing aid batteries and accessories on the order review screen

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#9796]
## Issue Description
_Some Veterans may only need to order either hearing aid batteries or accessories, so we need to provide an empty state on that portion of the review screen if they don't select items for both categories._

---
## Tasks
- [x] _Design an empty state to display on the review screen if a Veteran chooses not to add either hearing aid batteries or accessories to their order_
- [x] _Present the design to the frontend dev team to validate that it's feasible to implement_
- [x] _Present the design to the frontend dev team to validate that it's feasible to implement_

## Acceptance Criteria
- [x] _Proposed design is approved by frontend team_
- [x] _InVision prototype with empty states are linked in this ticket_
- [x] _Ticket for frontend implementation is created_
---

**Comment by rebeccawalsh** [comment]
Ticket for front end: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10075

**Comment by rebeccawalsh** [comment]
**Invision prototypes:**
[Empty states for when a Veteran is eligible to order within their categories](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/421066122_C3-_Review_-_Supply_Empty_State-_Eligible)
[Empty states for when a Veteran is not eligible to order within their categories](https://vsateams.invisionapp.com/d/main?origin=v7#/console/19309480/421066123/preview?scrollOffset=2003)
