### ISSUE TITLE
Create and test rescheduling and cancelling touchpoints operational guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#97981]
## User Story
As a Governance team member supporting Collaboration Cycle, I want to have clear and thorough guidance to follow if/when VFS teams cancel or reschedule a touchpoint so that I can ensure all necessary actions occur.

As a Governance team member supporting Collaboration Cycle, I want to have clear and thorough guidance to follow if/when I need to cancel or reschedule a touchpoint so that I can ensure all necessary actions occur.

Assignee: @allison0034 
Peer Reviewer: @it-harrison 

## Description
In December, Governance team had a lot of cancelled and rescheduled touchpoints. We realized that team members were rescheduling touchpoints in a couple different ways:

1. Rescheduling the event via Google Calendar
   - We know that if you move the event in Google calendar, then the change in date/time is not updated in Calendly, meaning that the original date the touchpoint occurred would still be marked as booked within Calendly, preventing other teams from using that timeslot. 
   - This method is NOT preferred. If we can find a way to move the event and have Calendly updated, then great, I am for it. But if not, then I do not think our guidance should recommend this path.
2. Rescheduling the event via Calendly
   - We know that if you move the event in Calendly first, that any changes we made to the event (adding the distribution list, adding the Slack thread and Drafting Template, changing the title of the touchpoint) are removed, meaning we then have to add those things to the calendar event a 2nd time.
   - This method is preferred, however we should include steps in our guidance for capturing the info from the body of the event (if Governance reschedules, not the VFS) so it is not lost when changes are made in Calendly.

If the VFS team is the team rescheduling or cancelling the event, we give them guidance to follow the links in the calendar event to cancel or reschedule. These links are the equivalent to changing the event in Calendly. The guidance to VFS teams should not change, however we don't have clear guidance with regards to what steps Governance team should take when 1)  the VFS team cancels the touchpoint, and 2) the VFS team reschedules the touchpoint.

The purpose of this ticket is to update the guidance on rescheduling and cancelling touchpoint. The guidance should include the following:

- Steps for when the VFS team reschedules a touchpoint (AKA when they follow the links in the ticket)
- Steps for when Governance team reschedules a touchpoint
- Steps for when the VFS team cancels a touchpoint (AKA when they follow the links in the ticket)
- Steps for when Governance team cancels a touchpoint

### Live pages
- [Rescheduling and cancelling touchpoints](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2737766401/Rescheduling+and+cancelling+touchpoints)

### Drafted pages
- 

## Tasks
- [x] Set up fake touchpoints (maybe in February?) for us to test all 4 scenarios:
   1. VFS cancels
   2. VFS reschedules
   3. Governance cancels
   4. Governance reschedules
- [x] Document the differences in each scenario in order to identify the different steps that must occur
- [x] Test cancelling and rescheduling the fake touchpoints. In these scenarios, the peer reviewer can act as the VFS team 
- [x] Update guidance doc to reflect the steps Governance should take in each of these scenarios 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team has documented clear guidance and steps for our team to follow if/when a VFS team cancels or reschedules a touchpoint
- [x] Governance team has documented clear guidance and steps for our team to follow if/when we need to cancel or reschedule a touchpoint

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Started [documentation](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3716710402/97981+Allison+Canceling+and+rescheduling+touchpoints)

**Comment by allison0034** [comment]
@KKitagawa-Bosch I know this is not assigned to you, BUT some super great content eyes would be much appreciated on the [updates I made](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2737766401/Rescheduling+and+cancelling+touchpoints). : ) As always, feel free to edit directly.

**Comment by KKitagawa-Bosch** [comment]
Made some updates @allison0034 !

**Comment by allison0034** [comment]
@it-harrison this should be ready to go. The idea is to direct VFS teams to use the links in the Google invite which will reschedule or cancel via Calendly. Let me know if you need help testing or find any issues.

**Comment by shiragoodman** [comment]
@allison0034 I am assuming that the Staging Review that got cancelled for Tuesday 1/14 followed the new guidance you have proposed. Can I make one small suggestion? This is the language that I saw in the Slack thread:

> Your touchpoint has been canceled. When you are ready, follow the directions in the Staging review section of your Collaboration Cycle ticket to schedule the new date.

It's a bit blunt. Can we change the first sentence a bit to imply _who_ cancelled the touchpoint and _how?_ For example, maybe we can say something like, "@aurora Hampton's request to cancel the touchpoint via Calendly has been confirmed." opposed to just "your touchpoint has been cancelled." That way, we're letting the team know that they were the ones who cancelled the touchpoint and not us. Seeing Joelle's response after you accidentally posted in the wrong thread made me recognize that she thought that WE cancelled the touchpoint. if the cancelling was done on accident (which has happened before!) at least there's some info to the team so they know who is accountable. Let me know if you have any questions or want to discuss.

**Comment by it-harrison** [comment]
@allison0034 - looks good! It might not be required but you might want to add in the "Cancelling Touchpoints" section that to cancel the touchpoint we need to click the link in the meeting invite.

**Comment by allison0034** [comment]
I added an alert at the top of the page.
