### ISSUE TITLE
[GIDS] Create Fargate POC

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#97989]
Instead of using the overly complicated EKS approach to manage GIDS, we're going to create a POC for utilizing the AWS Service Fargate to deploy and manage the relatively simple service.

## Tasks
- [x] Terraform necessary resources (within the `gibct-data-service` repo
  - [x] VPC/Subnets/Route53
  - [x] RDS
  - [x] ECS + Fargate
  - [x] ECR
  - [x] Security Groups
  - [x] .tfvar files (dev/staging/prod)
- [x] Pass through Env vars
- [x] Reference secrets/parameter store
- [x] Create design document

## Acceptance Criteria
- [x] POC has been demo'd to relevant parties and awaiting approval
