### ISSUE TITLE
Ask for Github username in Staging Review scheduling for Calendly

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#97980]
## User Story
As a Governance team member, I want to ask the VFS person to provide their GitHub username in the Calendly Staging Review scheduling event so that I can add it to the DraftingTemplate and ensure all tickets created are assigned to them.

Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description
The Staging Review - Scheduling tasks includes setting up the DraftingTemplate which now requires that we add an Assignee to all of the findings so that the tickets, once generated, are assigned to the PM or whomever requested the SR. The Assignee must be the GitHub username used by the requestor. A lot of the time, we have to dig for this information which adds extra time to our process.

The purpose of this ticket is to request the GitHub username of the VFS person scheduling the SR in Calendly. By asking for this information in Calendly, we can easily add it to the DraftingTemplate without having to search on GitHub.

### Live pages
- [Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)
- [Staging Review Calendly event](https://calendly.com/event_types/71688608/edit?return_to=%2Fevent_types%2Fuser%2Fme)

### Drafted pages
- 

## Tasks
- [x] Add a question to the Calendly- Staging Review event asking for GitHub username
- [x] Ensure GitHub username is included in the Staging Review: Scheduled email we get from Calendly
- [x] Ensure the Staging Review-scheduling guidance is updated to reflect this change

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We ask for GitHub username in the Staging Review event on Calendly

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Looks good you can close

**Comment by erinrwhite** [comment]
Thanks much! Closing...
