### ISSUE TITLE
[Ongoing Support] Mon - Thurs Deploy [S17]

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#98008]
## User Stories
As a Platform team member who just contributed to the Platform website,
I need my content published,
so that I can share my content updates with the intended audience.

As a content team,
we need to review any new content changes made on the platform,
so that we can deploy every Tuesday and Thursday of the week.

## Tasks
Someone from our team will use Scroll Viewport to publish changes to the website after 3pm EST on:

- [x] Thursday (12/19 ) - Jill  
- [x] Mon (12/23 ) - No Deployment
- [x] Tuesday (12/24 ) - No Deployment
- [x] Wednesday (12/25 ) - CHRISTMAS HOLIDAY  
- [x] Thursday (12/26) - No Deployment 
- [x] Monday (12/30) - No Deployment (Jill in emergency)
- [x] Tuesday (12/31) - No Deployment (Jill in emergency)
- [x] Wednesday (1/1/25 ) -No Deployment (Jill in emergency)

## Acceptance Criteria

- [x] The Platform website will be deployed on special Holiday schedule as above, between 3:30 and 5pm for this sprint.
- [x] Any edits with launch-blocking issues will be announced to their content editors via #platform-content

## Other Info

Data tracking info:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2282979860/KPIs+-+Content+Support

Temporary rotating schedule:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2405171201/Deployment+rotation+schedule

**Comment by jknipes** [comment]
Planning this sprint very light due to overlapping Holiday PTO

**Comment by jknipes** [comment]
work is complete, closing as _Done_
