### ISSUE TITLE
Link imposter component guidance in staging review

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#98005]
## User Story
As a VFS team member, I want to understand what an imposter component is so that I can prevent them from being used in my product, or learn how to address them if/when an imposter component is flagged at Staging Review.

Assignee: @allison0034 
Peer Reviewer: @KKitagawa-Bosch 

## Description
There is currently no guidance on Platform Website or on VADS that explains what an imposter component is. If we're going to use this language in Staging Review and throughout the Collaboration Cycle, then we need to define an imposter component and provide guidance on how it is flagged and how to handle it. 

The purpose of this ticket is to write guidance on Imposter Components, as well as identify where the guidance should live. (Shira's vote is for VADS).

### Live pages
- [Components overview](https://design.va.gov/components/)

### Drafted pages
- 

## Tasks
- [x] Identify where the new Imposter Component guidance should live 
   - Note: we don't necessarily need to create a new page dedicated to imposter components. Would it make sense for the guidance to live within an existing page?  
- [x] Identify if we need to reference the Imposter Component guidance in any other existing guidance documentation
- [x] Draft guidance on the imposter component, ~~including labels used (both exp-std label and imposter component label)~~
- [ ] Peer review
- [ ] Once approved, publish the guidance
- [ ] Would it make sense to link to this guidance in future imposter component staging review findings tickets? If you think so, please create a ticket for the Governance backlog and tag Shira

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance has published guidance for VFS teams on imposter components

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Moving out of Sprint 19 as we still need to determine a solution. At this time, there is no "imposter component" reference in the Staging Review finding template. Maybe we need to add imposter component to the References section (ie descriptive tags)?

**Comment by KKitagawa-Bosch** [comment]
@jasonday @shiragoodman spent a good chunk of time playing around in the new template and couldn't seem to break anything, so seems good to me!

**Comment by shiragoodman** [comment]
thanks @jasonday ! yes, sounds good to me. Please move the DraftingTemplate 2.2 to the Archive folder and share on our team Slack channel (or DM) that we're using DT 2.3 now! 

We should also update the DT used in the SR's scheduled for 8/22, 8/28/, 8/29 and 9/11 to use the newest 2.3. @KKitagawa-Bosch Can you show Jason how to do this and ensure all are done correctly? 

Note: This reason right here is EXACTLY why we link the DT folder in SR touchpoints and not the DT itself.
Note 2: There's already a couple findings documented in the DT for the SR on 8/15, so we can skip that one. 8/22 will be our first SR using DT 2.3.

**Comment by KKitagawa-Bosch** [comment]
@jasonday good to close!
