### ISSUE TITLE
November 2024 Metrics

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#98007]
## Background
Time to pull monthly metrics for November 2024.

## Tasks
- [x] Add GA4 metrics for November to the [GSheet](https://docs.google.com/spreadsheets/d/16Tr3nVdRHTteverx5yoBoBV32s0wvUrtW4-Daoi4hEE/edit?gid=458272975#gid=458272975)
- [x] Add Datadog metrics for November to the [GSheet](https://docs.google.com/spreadsheets/d/16Tr3nVdRHTteverx5yoBoBV32s0wvUrtW4-Daoi4hEE/edit?gid=458272975#gid=458272975) (Widget only)
- [x] Update the graphs in the [GSheet](https://docs.google.com/spreadsheets/d/16Tr3nVdRHTteverx5yoBoBV32s0wvUrtW4-Daoi4hEE/edit?gid=458272975#gid=458272975)
- [x] Export the GSheet to Excel and upload to Sharepoint

## Acceptance Criteria
- [x] November performance metrics are in Sharepoint

**Comment by oddball-lindsay** [comment]
GA4 metrics are almost complete in the GSheet, just had one question about the "Referrer" for the landing page referral sessions; asked Janelle about that and will wrap up tomorrow.
