### ISSUE TITLE
Obfuscate devops VA email

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#98003]
## User Story
As a member of the VA github org, I want to hide VA email addresses, so that we are in compliance with new requirements.

## Issue Description
The Platform owns three GitHub bots. If any of them perform commits on public repos, the email address associated needs hiding. This is to comply with this announcement: https://github.com/orgs/department-of-veterans-affairs/discussions/13

## Tasks
- [ ] Update 50+ files

## Acceptance Criteria
- [ ] devops bot email address are hidden. 
---

## Validation
- [ ] [This search](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+%22devops%40va.gov%22+path%3A.github%2Fworkflows%2F*&type=code) doesn't show any code references.

**Comment by ph-One** [comment]
Files left for eval:

- [ ] https://github.com/department-of-veterans-affairs/pst-amt-keycloak-authenticator/blob/main/.github/workflows/rebuild-keycloak.yml
- [ ] https://github.com/department-of-veterans-affairs/platform-console-ui/blob/main/.github/workflows/cd-staging.yml
- [ ] https://github.com/department-of-veterans-affairs/platform-console-ui/blob/main/.github/workflows/cd-utility.yml
- [ ] https://github.com/department-of-veterans-affairs/platform-console-ui/blob/main/.github/workflows/cd-build.yml
- [ ] https://github.com/department-of-veterans-affairs/platform-console-api/blob/master/.github/workflows/deploy-template.yml
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-atlantis/blob/main/.github/workflows/ci-cd.yml
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-grafana/settings
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-eks-autoscale/blob/main/.github/workflows/ci-cd.yml
- [ ] https://github.com/department-of-veterans-affairs/vets-api-sidekiq-ui/blob/main/.github/workflows/ci.yml
- [ ] https://github.com/department-of-veterans-affairs/pst-amt-keycloak/blob/main/.github/workflows/ci-next.yml
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-k8s-confluence/blob/main/.github/workflows/ci.yaml
- [ ] https://github.com/department-of-veterans-affairs/pst-amt-keycloak-node-test-app/blob/main/.github/workflows/ci.yml
- [ ] https://github.com/department-of-veterans-affairs/pst-amt-keycloak-react-test-app/blob/main/.github/workflows/ci.yml
- [ ] https://github.com/department-of-veterans-affairs/vets-api-file-upload/blob/main/.github/workflows/branch-build-and-deploy.yml
- [ ] https://github.com/department-of-veterans-affairs/pst-amt-keycloak/blob/main/.github/workflows/ci-utility.yml
- [ ] https://github.com/department-of-veterans-affairs/pst-amt-keycloak/blob/main/.github/workflows/ci-staging.yml
- [ ] https://github.com/department-of-veterans-affairs/pst-amt-keycloak/blob/main/.github/workflows/ci.yml
- [ ] https://github.com/department-of-veterans-affairs/pst-amt-keycloak-react-test-app/blob/main/.github/workflows/ci-utility.yml
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-clamav-mirror/blob/main/.github/workflows/ci-private-mirror-images.yml
- [ ] https://github.com/department-of-veterans-affairs/platform-console-api/blob/master/.github/workflows/create_deploy_pr.yml
