### ISSUE TITLE
[COPAYS] Get Becky Gradle example payloads so she can examine "Cerner_patient_id" and "Cerner_Accout_Number"

### ISSUE THREAD

**Issue by penny-lischer** [department-of-veterans-affairs/va.gov-team#98011]
In preparation for our coming Copay work, Becky has asked for current copay payload examples to help her triangulate data points she's seeing on her end.

## Tasks
- [x] Login to prod and pull example payloads for Becky

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance Criteria
- [ ] Payloads sent to Becky via encrpyted email

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by digitaldrk** [comment]
I had assigned this to Penny. Turns out she doesn't have the full permissions she needs to get into Argo and pull data. 

Marking this as blocked.

**Comment by dhill802** [comment]
Moving out of Sprint due to being blocked. @penny-lischer once you have permissions, please move forward with this work.

**Comment by dhill802** [comment]
Penny's permissions are set. This work is set. Closing.

**Comment by penny-lischer** [comment]
Was not able to find any data for the Cerner fields pH_CERNER_PATIENT or pH_CERNER_ACCOUNT_NUMBER.
For user_uuid, those fields would return the following:
empty array 
`[]`

empty string
```
"pH_CERNER_PATIENT_ID"=>"                ",
"pH_CERNER_ACCOUNT_NUMBER"=>"                ",
```

nil
`"pH_CERNER_PATIENT_ID"=>nil,
  "pH_CERNER_ACCOUNT_NUMBER"=>nil,`
