### ISSUE TITLE
Update headings: Introduction page

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#98028]
Accessibility has flagged issues with the headings on our `/introduction` page.

## Expected vs. Actual
**Expected**: Headings should match the [Figma annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=8967-301319&t=EAvsgPuw0NJnvWyP-4).

**Actual**: The sign-in widget is using an H3. This skips a heading level on the page - it jumps from H1 to H3. The incorrect heading level does not convey the intended structure of the content.

### The **unauthenticated** experience in Staging:
The sign-in widget is using an H3. This skips a heading level on the page - it jumps from H1 to H3. The Widget header should be an H2. 
![Image](https://github.com/user-attachments/assets/87974e56-8f07-47f2-ac48-125a2d55be0b)

### The **authenticated** experience in Staging:
The sign-in widget is using an H3. This skips a heading level on the page - it jumps from H1 to H3. The Widget header should be an H2 and the VSO name should be an H3.
![Image](https://github.com/user-attachments/assets/e30d81b7-1825-4332-bb45-e8eb6a63ffe8)

## Tasks
- [ ] Unauthenticated experience: Update the Widget header (currently an H3) to be an H2.
- [ ] Authenticated experience: Update the Widget header (currently an H3) to be an H2.
- [ ] Authenticated experience: Update the representative name in the Widget (currently an H4) to be an H3.
