### ISSUE TITLE
[FSR] Bug - Empty box 3

### ISSUE THREAD

**Issue by dhill802** [department-of-veterans-affairs/va.gov-team#98038]
## Issue Description
The "Specify why you are completing this form" box is appearing empty for VBA submissions           

![Image](https://github.com/user-attachments/assets/17b71add-3880-4d79-9cda-5e965650cfe1)

## Tasks
- [x] Attempt to recreate locally
- [ ] Identify root cause of issue
- [ ] Determine if it is effecting VHA submissions as well
- [ ] Fix the problem     

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] Box 3 is correctly populated for all submissions
- [x] Box 3 is correctly populated in downloadable version of FSR

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by dhill802** [comment]
Attached is the latest version a PDF that is missing the resolution options in box 3 [VA Form 5655 - Submitted (3).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0hVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbdecaa2f09c4726c3b12094f96fbd94dd4c6a6b/VA%20Form%205655%20-%20Submitted%20%283%29.pdf)

I verified that the options are being sent from the frontend to the backend without errors in the response for non-streamlined forms. Next, I need to verify the streamlined long forms.

![Image](https://github.com/user-attachments/assets/934523c9-2c7a-4289-8e23-97be0ed848f2)

**Comment by dhill802** [comment]
We figured out the PDF box 3 issue: the BE server-side transform_and_submit object was missing resolution_option, resolution_comment, and resolution_waiver_check from the whitelist. The problem has likely existed since we enabled the fsr_5655_server_side_transform feature flag. It was difficult to detect due to the percentage-based rollout.

**Comment by dhill802** [comment]
This ticket didn't migrate between Zen and Git. Recreated and added to Git. Closing.
