### ISSUE TITLE
Create Digital Dispute Service/Model

### ISSUE THREAD

**Issue by dhill802** [department-of-veterans-affairs/va.gov-team#98036]
## Issue Description
We'll likely need a service or model that validates form input, maybe mutates data, and submitting the form to a SidekiqJob            

## Tasks
- [x] Create DigitalDisputeService/Model
- [x] Add Tests  

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by dhill802** [comment]
Submitted.  Platform review complete.

Ticket didn't make the Zen to Git Migration. Recreated in Git.
