### ISSUE TITLE
[DD] Create Digital Dispute feature toggle

### ISSUE THREAD

**Issue by dhill802** [department-of-veterans-affairs/va.gov-team#98031]
## Tasks

- [x] vets-website PR merged
- [x] vets-api PR merged

Design and Front End sync on implementation of design
- [x] Complete
- [x] Not Required

## AC
- [x] Digital Dispute feature toggle created

## Testing

- [x]  Testing passed and documented in this ticket based off the "Then" statement in the description

## Ticket Creation - Definition of Ready

- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by dhill802** [comment]
FE PR: [department-of-veterans-affairs/vets-website#33154](https://github.com/department-of-veterans-affairs/vets-website/pull/33154)
BE PR: [department-of-veterans-affairs/vets-api#19546](https://github.com/department-of-veterans-affairs/vets-api/pull/19546)

Didn't make the merge from Zen to Git. Recreated ticket in Git.
