### ISSUE TITLE
[BE] 10-10CG - BUG: Investigate and confirm retries from MPI outage

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#98078]
## Background
During the COLA update, MPI/MVI experienced an outage due to a certificate mismatch (unrelated to the COLA update).  This caused all 10-10CG forms to fail upon submission due to the inability to confirm the Veteran through MPI.  

We want to confirm that all retries have either gone through successfully or are still in the retry queue.
We also want to confirm that the number of submissions sent from 4pm through Monday matches up with the MuleSoft/CARMA team.  (if there are still retries in progress, it may make up for any difference in numbers)

## Tasks
- [x] Confirm CG forms have either been successfully sent to Mulesoft, or are currently in Retry status
- [x] Gather the number of forms submitted since Friday
- [x] Confirm with CG tech team that they have received the same number of submissions
     - Retries in progress may not be counted yet

## Acceptance Criteria
- All CG forms have been confirmed as successful, or pending a retry. 
- No CG forms exhausted retries and failed without alerting our team.

**Comment by coope93** [comment]
I checked production sidekiq and all submissions have finished retries with no errors on the retries. We did not receive any failed out of retires notifications, so it looks like all submissions have been successfully submitted to mulesoft.

**Comment by coope93** [comment]
From 12:00am est on 11/29 to 12:00am est on 12/03 we had 492 successful submissions per [this datadog chart](https://vagov.ddog-gov.com/dashboard/p5g-fys-epz/1010-health-apps?fromUser=false&fullscreen_end_ts=1733202000000&fullscreen_paused=true&fullscreen_refresh_mode=paused&fullscreen_section=overview&fullscreen_start_ts=1732856400000&fullscreen_widget=1652960129845848&refresh_mode=sliding&from_ts=1732628998713&to_ts=1733233798713).

**Comment by hdjustice** [comment]
I sent this info to the CG Tech team to confirm volume

**Comment by coope93** [comment]
[Slack thread to confirm submission numbers](https://dsva.slack.com/archives/C02MJCT59S7/p1733160302133649)

**Comment by hdjustice** [comment]
Confirmed CG team received 494 submissions, we tracked 492 submissions.  The discrepancy is most likely due to timing of retries.  We are confident that there were no submissions unaddressed.
