### ISSUE TITLE
[BE] 10-10CG - Facilities: Architecture Intent - Explore options to replace GET to ensure URLs do not expose PII

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#98100]
## Background
As a result of the Architecture Intent review meeting, we are advised to replace the GET function to something that will ensure URLs do not expose PII.  Our current endpoint for retrieving the facilities list is a GET request where we pass the lat/long as query params in the URL. Because we log the urls, this is exposing what could be PII (the lat/long of a Veteran's address). 

Simply changing GET to POST could be considered an anti-pattern.  There were several ideas discussed in the team's meeting Slack thread, captured in the meeting notes.  We want to explore these and any other options that may be the best solution here.  

### Resources
- [Architecture Intent Meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Improve%20Facility%20Selection/Arch%20Intent%20-%20Questions%20&%20Meeting%20Notes.md)
- [Slack thread with the team and Adrian](https://dsva.slack.com/archives/CMJ2V70UV/p1732646603012339)

## Tasks
- [x] Explore options to resolve potential PII exposure
- [x] Outline effort and timeline to implement the options we like the best
- [x] Discuss options as a team and decide on the best path to take
- [x] Confirm with Architecture Intent team that the option is acceptable
- [x] Create tickets for the implementation

## Acceptance Criteria
- Options have been discussed and the team has decided on the best option

**Comment by coope93** [comment]
I spent some time researching and spiking out some possible solutions: 

1. Add ability to encrypt/decrypt sensitive query params as needed. I took a crack at spiking this out and it is certainly doable. I used RSA encryption with the [WebCrypto api](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) and have [this vets-website spike branch](https://github.com/department-of-veterans-affairs/vets-website/tree/98100-encrypt-query-params) in conjunction with [this vets-api branch to decrypt the params on the backend](https://github.com/department-of-veterans-affairs/vets-api/tree/98100-encrypt-query-params) that is using OpenSSL on the backend to decrypt it. This would take the most work to implement, and would involve new public/private keys and the subsequent configuration of them. One advantage is it could easily be implemented to allow for other teams to use, which could be a big benefit. It would allow us to keep the request as a `GET`, which would keep the api RESTful. 
2. Add sensitive credentials to headers. This would be fairly easy to implement in vets-website, since the `apiRequest` allows us to pass custom headers in requests. This would allow us to still use a `GET` request, we would just pass some of the query values in the headers instead of in the query params. The main downside is we'd have to add custom logic in `vet-api` to parse them since they would be different from the other query params, as well as separating out those params we are passing. Doing it this way would also be inconsistent from the Lighthouse facilities api since they are in query params there, but it would be more secure. One possible risk is that some loggers could be logging request headers, so we would need more info on that. My understanding is that headers should not be logged, but that they are sometimes unintentionally logged. Per [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html) putting sensitive values in headers for `GET` request is valid, although my understanding is it is usually more used for authentication purposes. 
3. By far the easiest solution is to change our existing `GET` request to a `POST` request. This would be fairly easy to implement and understand. The main downsides is this is not very RESTful for our api, as well as being an anti pattern with the Lighthouse api. In talking with OCTO engineers they preferred we at least looked into alternative methods before implementing this. 

One additional note is that in our `vets-api` Lighthouse service we are calling the Lighthouse api using a `GET` request with all of the params being passed in the url. So all values exist there as plain text (not encrypted or anything). This is true for anyone calling the Lighthouse facilities api. Our implementation is really just a wrapper around that call and between `vets-api` and `vets-website`.

**Comment by hdjustice** [comment]
Left a comment to Jonathan Kamens on the [Original Collab Cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51980#issuecomment-2536889734) with the top item proposed solution, requesting to confirm it is ok.

**Comment by hdjustice** [comment]
After discussions via [comments ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51980#issuecomment-2552587659)in Collab cycle ticket, the team has decided to follow initial suggestion to replace GET with POST for now (ticket #99567 ).  The scope of the proposed solution has increased with feedback from Architecture team.  While we want to be part of the discussions and activities to address the sitewide solution, we are not ready to build a new API endpoint for it at this time.
