### ISSUE TITLE
BRD: Separation Locations - Environments do not match (data mismatch)

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#98103]
As a developer, I want to be able to test BDD claims from end to end in staging.va.gov to lighthouse's staging environment so that I can push code to production with confidence that it is working as intended.

## Tasks
- [ ] update vets-api's staging Settings.lighthouse.benefits_reference_data block to point to LH's staging environment
    - [ ] figure out if Settings.lighthouse.benefits_reference_data are environment variable in infra repo of our staging environment
    - [ ] the environment variable maps to a value in parameter store
    - [ ] sleuth to figure out what LH's staging proxy value is - but is this even necessary? can we just use `staging-api.va.gov`
        - [ ] these are the Settings.lighthouse.benefits_reference_data.url values:
        staging: https://fwdproxy-staging.vfs.va.gov:4492 - which is Lighthouse's sandbox environment? 🤔 
         production: https://fwdproxy-prod.vfs.va.gov:4475
    - [ ] update the parameter store value for the va.gov staging environment
- [ ]  to test: 
    - [ ] turn brd_separation_locations provider to lighthouse https://staging-api.va.gov/flipper/features/disability_compensation_lighthouse_brd 
    - [ ] start a new BDD claim
    - [ ] fill out separation location
    - [ ] fill form all the way out to review-and-submit
    - [ ] submit form
    - [ ] claim id should be established in VBMS UAT
    - [ ] check claim in VBMS UAT! pdf should be generated

before, this would fail due to this due to the mismatch of data:
```
{"errors"=>
      [{"title"=>"Unprocessable Entity",
        "detail"=>"The separation location code (0) for the claimant is not a valid value.",
        "status"=>"422",
        "source"=>{"pointer"=>"data/attributes/serviceInformation/servicePeriods/0/separationLocationCode"}}]}
```
## Acceptance Criteria
- [x] a BDD claim can be established in staging

# Notes

1. vets-api staging LH Provider for BRD is pointing to LH's sandbox environment.
2. vets-api uses LH's staging endpoint to submit claims to go through to VBMS UAT.
3. When LH validates the separation location code, they check against their staging's BRD separation location code values.
4. vets-api needs to grab the separation location code values from the same environment LH does to test end-to-end.
6. vets-api staging's Settings.lighthouse.benefits_reference_data.url points to https://fwdproxy-staging.vfs.va.gov:4492/ which is LH's/BGS's sandbox environment
7. pipe dream: somehow, we need parity between services and environment the service is pointing to (i.e. sandbox points to sandbox, staging points to staging, production points to production)
8. this will mean that BRD provider will forever need to point to lighthouse's provider because we need parity between all endpoints.
    - why? the EVSS provider only returns "sandbox" data, which will never match with Lighthouse's staging data.

**Comment by aurora-a-k-a-lightning** [comment]
## DONE: 

1. added parameter store values in AWS for lighthouse staging api key and api host url
2. added to infrastructure in this PR:
    - https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3304
4. added a PR for an example in settings.yml for vets-api
    - https://github.com/department-of-veterans-affairs/vets-api/pull/19767

 ## REMAINING:

1. approve PRs
2. create extension to BRD service to inject staging credentials
3. send in staging credentials to BRD service in separation_locations endpoint.
4. i am thinking "Flipper Flag" here
5. PRs
6. test BDD claim creation in staging
