### ISSUE TITLE
[BE] 10-10CG - Facilities: Architecture Intent - Confirm no PII is being logged

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#98101]
## Background
As a result of the Architecture Intent review meeting, we are advised to confirm that no PII is being logged due to the facilities update.

### Resources
- [Architecture Intent Meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Improve%20Facility%20Selection/Arch%20Intent%20-%20Questions%20&%20Meeting%20Notes.md)

## Tasks
- [x] Validate that no PII is being logged due to the facilities update
- [x] Comment on what was reviewed and that no PII was found to be logged
- [x] If any PII is found to be logged, notify PM and discuss next steps to remedy

## Acceptance Criteria
- No PII is found to be logged due to the facilities changes

**Comment by Mitch-A6** [comment]
Requests to the vets-api caregiver facilities endpoint involve three components: 
- app/controllers/v0/caregivers_assistance_claims_controller.rb
- lib/lighthouse/facilities/v1/client.rb
- lib/lighthouse/facilities/v1/response.rb
None of these offer any logging that would capture the lat/long from the query. 

In addition, our MapBox API requests are constrained to relatively coarse datatypes (region, post code, place, or locality, see https://docs.mapbox.com/api/search/geocoding-v5/, used in src/applications/ask-va/utils/mapbox.js). If a user makes a request that does not follow the prompt, Searching on a more specific street address, the result would still be too generic to qualify as PII. For example, a search on every Manhattan street address I tried returned the lat/lon coordinates of City Hall. 

The attached log of network traffic shows 6 interactions, each consisting of a MapBox query followed by the corresponding requests to the Facilities endpoint in `vets-api` which uses the lat/lon MapBox provides. Searches for these 6 addresses (arbitrarily picked from various parts of Manhattan, across as many postal codes)
- 500 e 80th st, ny, ny
- 300 w 50th st, ny, ny
- 50 madison ave, ny, ny
- 5 dyckman ave, ny, ny
- 1 canal st, ny, ny
- 1 wall st, ny, ny
All map to the same coordinates: [40.712749,-74.005994](https://www.google.com/maps/place/40%C2%B042'45.9%22N+74%C2%B000'21.6%22W/@40.712749,-74.0085689,17z/data=!3m1!4b1!4m4!3m3!8m2!3d40.712749!4d-74.005994?entry=ttu&g_ep=EgoyMDI0MTIxMS4wIKXMDSoASAFQAw%3D%3D):
<img width="350" alt="Image" src="https://github.com/user-attachments/assets/4d8aac28-4ccf-468c-9286-de061ee75947" />

Previously, we did allow `address` type results from MapBox, but this was removed for other reasons years ago ([in this February 2019 PR](https://github.com/department-of-veterans-affairs/vets-website/pull/9570)).
