### ISSUE TITLE
NOD | customize confirmation information base on choices

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#98111]
## Value Statement

**_As a_** Veteran
**_I want to_** see information specific to my choices within the form
**_So that_** I am not confused by information from other choices

---

## Background Context

Replacing  additional info dropdown with generalized info from potential form choices into specific information based on selections made within the form

## Tasks

- [ ] Remove additional info
- [ ] Show specific info based on choices within the form
- [ ] Add unit tests

## Acceptance Criteria

- [ ] Specific info based on choices shown on confirmation page
- [ ] All tests passing

## Designs and Build Notes

- [Figma](https://www.figma.com/design/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?node-id=2488-13009&node-type=frame&t=KEcJyiILzzSij5d0-0)

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Changes are now available in staging for validation

**Comment by eileen-coforma** [comment]
@Mottie Two things:

For `Request a Hearing`, minor formatting mismatch with design
![Image](https://github.com/user-attachments/assets/f20f069c-0a69-493d-bb44-3b26b5f898b6)
The address is not formatted in that component with the blue line. Fax is bolded.

When I select `Submit more evidence` and `No, I'll submit it later.` I can't reach the confirmation page. The page is empty. Not sure if it's my staging acting up, but can you double-check that.

**Comment by Mottie** [comment]
Changes are now available in staging. The address block still hasn't been fixed by the Design System Team.

**Comment by comaurice** [comment]
### Direct review 
![Image](https://github.com/user-attachments/assets/31713ec7-0b6a-4f27-8d0e-bb414ff737dc)
Extremely minor. Design has no comma after "We'll send you a confirmation letter"

![Image](https://github.com/user-attachments/assets/6be2ea7f-52f3-4c69-b476-65026662155c)
Also very minor. Design has a 1 before the 800 number

![Image](https://github.com/user-attachments/assets/af724ab2-b54a-4634-86bf-0f36da2b2a61)
Design has United States after the address




### Request a hearing
Selected in person hearing. Is this the old conf page layout? 
![Image](https://github.com/user-attachments/assets/97a15198-c25e-4063-9121-aedbc10db92e)
Did this on 2 different users and did not reproduce, it showed the expected conf page layout. So perhaps this was a staging fluke?

**Comment by Mottie** [comment]
Thanks @comaurice!

* I'll fix that unnecessary comma in the success alert!
* For adding a "1 before the 800" in the phone number - our [content guide states](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers) "Use +1 only when the information is specifically addressing Veterans or people who are living outside the U.S.". Also don't use parentheses around the area code, if you ever encounter that.
* On that same [content guide page](https://design.va.gov/content-style-guide/dates-and-numbers#addresses) is how VA formats addresses. It doesn't explicitly say it, but addresses within the U.S. usually don't include the country. The code is set up to specifically _not_ show "United States". [I've asked in Slack to verify](https://dsva.slack.com/archives/C01K37HRUAH/p1733863841932229).
* In that last screenshot is the confirmation page you see when the feature toggles don't load as expected. It happens occasionally. I'm not sure how to get around that other than reload the page. I wonder how often it happens in production 😓

**Comment by Mottie** [comment]
Removed comma fix is now available in staging.

**Comment by comaurice** [comment]
Thanks for the explanation on those things @Mottie. I'm all good 👍

**Comment by Mottie** [comment]
[Address block left blue border will be fixed on Thursday](https://dsva.slack.com/archives/CBU0KDSB1/p1733930635056479?thread_ts=1733763217.363159&cid=CBU0KDSB1) (12/12/2024)

**Comment by comaurice** [comment]
Waiting for new validation (after 12/12)

**Comment by Mottie** [comment]
The address class name (left blue border) has been added back!

<img width="696" alt="NOD confirmation page showing Board of Veteran Appeals address with left blue border" src="https://github.com/user-attachments/assets/dfddd07c-4e06-4f57-adf9-a9c0dc91936b" />
