### ISSUE TITLE
SPIKE: Determine how we are going to implement the pilot feature

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#98136]
## Description
We will need to pilot the VSS CC feature.

## Tasks
- [x] Determine how we can limit the feature to certain facilities
- [x] Determine how we can limit the feature to certain appt types (Physical Therapy)
- [x] Sync w/ Appts team if they have any built-in utilities for piloting
- Find out the stations that are going to be part of the pilot
- [x] Create a follow-up ticket in this same epic

**Comment by brianseek** [comment]
There are two tickets form the result of this spike:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/99589
https://github.com/department-of-veterans-affairs/va.gov-team/issues/99590

We will build a util that compares a hard coded array of piloted stations against the stations in the logged in users user object in redux. This will act in conjunction with the feature flag to determine if the feature should be run. We will also be passing this value to vets-api in the appointments fetch so they can enhance the feature flag on their end.

The actual list of piloted stations is still TBD.
