### ISSUE TITLE
[VETS-API] Fix Deprecation Warnings ahead of Rails 7.2

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#98145]
There are a handful of `DEPRECATION WARNING`s that need to be addressed prior to upgrading Rails to 7.2 (and ✨8✨ )

## Tasks
- [x] Fix the following:
  - [x] `DEPRECATION WARNING: config.active_support.remove_deprecated_time_with_zone_name is deprecated and will be removed in Rails 7.2. ` (in specs)
  - [x] `DEPRECATION WARNING: Your `secret_key_base` is configured in `Rails.application.secrets`, which is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2.` (in specs)
  - [x] `DEPRECATION WARNING: Using preview_path= option is deprecated and will be removed in Rails 7.2. Please use preview_paths= instead.` (local server)

## Acceptance Criteria
- [x] Deprecation warnings blocking Rails upgrade are all addressed

**Comment by ericboehs** [comment]
PR merged. On to 7.2.2!
