### ISSUE TITLE
Consolidate Datadog metrics for external services

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#98148]
## User Story
As a developer, I want to standardize breakers client to consolidate external service statsd Metrics in order to consolidate Datadog metrics for the external services.

## Issue Description
The current configuration of the Breakers client has variations in how StatsD metrics are defined and handled. Standardizing this configuration will enhance metric uniformity and streamline the process of monitoring external service performance.

Incorrect configuration is blocking the external service metric consolidation completed in #83200. Instead of requiring configuration paths,` ex: require 'va_profile/veteran_status/configuration'`, external services that have a service configuration file should require the service path, `ex: require 'va_profile/veteran_status/service'`.

Ex:
`require 'va_profile/veteran_status/configuration' `-> `require 'va_profile/veteran_status/service'`

_Edit: Still investigating what's causing the external metrics to show up per-service. It's possible the configuration in breakers.rb is not causing this._

### Related Tickets
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97500
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97502

## Tasks
- [x] Investigate what's causing external services to show up per-service 
- [ ] Require service path for any external services that have service configs, if necessary.

## Acceptance Criteria
- [ ]  External [datadog metrics](https://vagov.ddog-gov.com/metric/summary?filter=external_service) are consolidated
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by rmtolmach** [comment]
The goal of this ticket is to consolidate the Datadog metrics for the external services. `vets_api.statsd.api_external_service.up` contains all of the external services, but specific per-service metrics like `vets_api.statsd.api_external_service_HCA_up` are _also_ are showing up (as seen [here](https://vagov.ddog-gov.com/metric/summary?filter=external_service)). We don't want that. I started changing up breakers.rb to call the `Service` instead of the `Configuration`, but I don't know if that will resolve it. 

👀 💡 If you look at a specific service, you'll see it's coming from `env:next` whereas the stats in `vets_api.statsd.api_external_service.up` are coming from `env:eks-<env>`. So **this is only a problem with metrics from the `next` cluster.** I have been looking all around and I can't figure out how these are configured 😣. It's configured for other envs in the [datadog-agent](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/datadog-agent) directory, but there's nothing for the next cluster in there. A search for [deployment_env:next](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+%22deployment_env%3Anext%22&type=code) returns nothing. I don't really see `DD_DOGSTATSD_MAPPER_PROFILES` defined for the next cluster anywhere else. I have reached out to Kshitiz to see if he knows. The `next` env is configured from vets-api dev, I believe, but the datadog-agent for dev is configured like the other envs. So maybe the per-service metrics are default and we need to _add_ configuration for the `next` cluster 🤷.

**Comment by rmtolmach** [comment]
The original ask of this ticket was to standardize breakers client configuration in order to consolidate datadog metrics for external services. Turns out our external services are already consolidated _except_ for the non-live `next` cluster. These are not a big concern since the average custom metrics per hour is <0.1%, so they're not a huge cost burden. It's easier to use these metrics in dashboards or alerting if they are consolidated, but we're not using these metrics in any way at the moment, so that is not a concern, either. **Because of these reasons (non-live env, small cost burden, not actually utilizing the metrics), I think we can close this ticket.**

I met with Kyle M to ask how this was being configured. The configuration we have now for the `next` cluster is the default, which is why the external services are defined per-service for the `next` cluster. Relatedly, Kyle is looking to decouple `DD_DOGSTATSD_MAPPER_PROFILES` from the datadog agent. It's possible to add multiple config files in the Datadog agent (probably still in the helm chart) so they would be more organized than [what we have now](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/datadog-agent/dev/values.yaml#L28-L106). We can't migrate to the `next` cluster until this is figured out, but that is a different problem than this ticket was calling out.

**Comment by rmtolmach** [comment]
Consolidation will happen on the Infra side with this ticket:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103893

**Comment by AshleyGuerrant** [comment]
**Standup note:** Closing out, this ticket ended up functioning as a discovery. Follow up work will be tracked in #103893.
