### ISSUE TITLE
Remove line asking VFS if they have info to share at Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#98186]
## User Story
As a Governance team member, I want to remove the line in our SR -During the meeting guidance asking VFS teams if they have anything to share before going over findings so that the meeting runs more efficiently. 

Assignee: ~~@it-harrison~~ @allison0034 
Peer Reviewer: ~~@allison0034~~ @it-harrison 

## Description
In our current script for SR, we ask the VFS team if they have any information to share with us before we begin going over the findings. VFS teams rarely answer yes to this question, and even when they do, it it will not change and/or impact the findings we had previously documented. For this reason, we'd like to remove the line in the script asking the VFS team is they have information to share. 

### Live pages
-  [Staging Review - During the meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447039/Staging+Review+-+During+the+meeting)

### Drafted pages
- 

## Tasks
- [x] Remove the step for asking the VFS team if they have anything to share.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We no longer ask the VFS team if they have anything to share before going over findings at the SR meeting

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@it-harrison ready for your review.

**Comment by it-harrison** [comment]
@allison0034 - looks good!
