### ISSUE TITLE
[BE] 10-10CG - BUG: Investigate actual schema validation errors

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#98193]
## Background
A [CG failure](https://vagov.ddog-gov.com/logs?query=trace_id%3A3020254648553971050&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZOINSRyqVvSywAAABhBWk9JTlM5VUFBREtXaDYzeGRqSE13Sm4AAAAkMDE5Mzg4NDAtYzc2Yy00Yjk5LWI3NjYtODkxY2Q5M2Q1OGE0ABED-g&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1733156003729&to_ts=1733158004461&live=false) was found on 12/2/2024 at 11:30 ET and it seems different than others.  It is saying that there was invalid information.  When looking at the log, it seems that the Primary CG data is coming back as invalid and the Veteran signature is invalid

> It looks like the schema validation did fail there. It looks like something with passing in the form data with a form key that causes it to be invalid. I went into argo and was able to get the form data (we store it in a personal information log when these errors occur) and when I removed the form key it validated correctly. This is validating against the json-schema gem, which we have had some issues with recently. But it does look like it has happened before [[https://vagov.ddog-gov.com/logs?query=env%3A%22eks-prod%22%20service%3Avets-api%20%40m[…]=stream&from_ts=1714405977348&to_ts=1716997977348&live=true](https://vagov.ddog-gov.com/logs?query=env%3A%22eks-prod%22%20service%3Avets-api%20%40message_content%3A%2A%22Submission%20Failed%3A%20invalid%20data%20provided%20by%20client%22%2A&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&source=monitor_notif&storage=hot&stream_sort=desc&viz=stream&from_ts=1714405977348&to_ts=1716997977348&live=true)]

Note: 
- The user would have seen an on-screen error message.  The form did not go through the submission process, it immediately triggered an error.
- There have been 10 occurrences in the last month

## Tasks
- [ ] Investigate these errors to determine the root cause
- [ ] Discuss possible causes and solutions, if any
- [ ] Determine next steps and create tickets

## Acceptance Criteria
- The team will have a better understanding of the issue and how to proceed toward a resolution

**Comment by hdjustice** [comment]
Schema validation issues have additional logging and have been greatly reduced due to improvements to the overall form
