### ISSUE TITLE
Content model: Facility health services

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9821]
## Problem Statement
How might we change the structure of facility health services content so that
- some content can be reusable
- national content cannot be edited locally
- the risk of introducing errors is reduced
- the editorial experience is enhanced and efficient

## OKR
Decrease the amount of national content which is locally editable 

## Definition of done

- [ ] Content structure changes
- [ ] Front end mapped to new data structure
- [ ] Pages render as expected 
- [ ] Editorial experience review with CMS
- [ ] Content model review with CMS
- [ ] Feedback session with VAMC upgrade team 
- [ ] Migration plan
- [ ] Testing plan

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
