### ISSUE TITLE
DR | Remove Sentry

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#98216]
## Value Statement

**_As a_** Decision Reviews engineer
**_I want to_** remove Sentry calls
**_So that_** the code doesn't cause errors once the library is removed

---

## Background Context

Sentry is going to be removed as a library from the main repo. The frontend makes specific error logging calls to Sentry which also have associated unit tests. See #77700.

## Tasks

- [ ] Remove Sentry log calls on frontend
- [ ] Remove Sentry unit tests

## Acceptance Criteria

- [ ] Sentry calls removed from frontend
- [ ] All tests passing

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Ready for validation

**Comment by kayline** [comment]
I will look today, no user-facing changes

**Comment by kayline** [comment]
Validated, error logs now appear in DataDog
