### ISSUE TITLE
Make application available in lower environments

### ISSUE THREAD

**Issue by JasmineYohannan** [department-of-veterans-affairs/va.gov-team#98211]
## User Stories

```
As a Developer,
I want to deploy changes to the Supply Reorder app to lower environments,
So that I can get feedback from my team and other Stakeholders.
```

```
As a Stakeholder of the Supply Reorder app,
I want to see the latest build of the app,
So that I can... 
  - demonstrate functionality of the application,
  - determine if a ticket has been completed, and
  - give feedback to developers to improve the application.
```

## Tasks

Documentation: https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application

For the following tasks, the react application needs to be merged in `vets-website` before the changes to `content-build` in order for the build process to work correctly. [[source](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application#Creatinganewapplication-PRmergeorder)]

- [x] Fix any failing specs in integration branch
- [ ] Merge integration branch in `vets-website`
- [ ] Add app to `content-build` manifest 
- [x] Add react application path to reverse proxy

## Acceptance Criteria

- Application is available at `{dev,staging}.va.gov/my-health/order-supplies`

**Comment by radavis** [comment]
Duplicate of department-of-veterans-affairs/va.gov-team#97137
