### ISSUE TITLE
[CST][Bug] -  Standard 5103 Notice alert is displaying when we are waiting for LH to mark evidenceWaiverSubmitted5103 flag to false

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#98245]
## Background Context
@jstrothman wrote in a bug that she found when submitting evidence waiver on a standard 5103 notice - https://dsva.slack.com/archives/C04KHCT3ZMY/p1733247400260019

### Bug
**Steps to reproduce**
- Create a standard 5103 notice on a claim
- Go to the tracked item on the claim and submit the evidence waiver
- You will be redirected to the files page and you will still see the tracked item but wont be able to view the details on it

**What is the bug?**
- We have to wait for LH Benefits Claims to mark the `evidenceWaiverSubmitted5103` flag to true and so the alert is still appearing on the status and files page event even though the evidence waiver has been submitted

## Tasks
- [x] Update files page 
- [x] Update status page
- [x] Write tests

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Files page does not show the Standard 5103 notice when an evidence waiver has been submitted
- [ ] Status page does not show the Standard 5103 notice when an evidence waiver has been submitted
