### ISSUE TITLE
CONSIDER: Facility Locator - Benefits Detail Page Self-Service Language

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#9825]
## Issue Description
As a veteran I want to know if there are ways in which I might solve my problem without going to a VA Benefits facility so that I can get my problem solved faster/without travel.

The current facility detail page for benefits facilities includes the sentence (as used on most facility detail pages) 

> Planning to visit? Please call first as information on this page may change.

This statement (screenshot below) is not particularly helpful to veterans because the phone number included in the Facilities API is a national number and likely not be able to provide location-specific information a veteran may be seeking before visiting. (e.g. what services are available at a specific VA facility, parking information, etc.)

We want to replace that in correct sentence with some self-service tools.

![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/08bdf90b-e5ef-4bf6-85c6-02bf2f3ae774)

---
## Tasks
- [ ] On Facility Detail pages of Facility type: Benefits replace "Planning to visit? Please call first as information on this page may change." with text in [https://app.zenhub.com/files/133843125/037f690a-2ab0-40cc-b506-2a4e4cc24058/download](https://app.zenhub.com/files/133843125/037f690a-2ab0-40cc-b506-2a4e4cc24058/download)

## Acceptance Criteria
- [ ] Benefits Detail Page will no longer have "Planning to visit..." text
- [ ] Benefits Detail Page will have additional 3 lines of text (see word doc)
- [ ] Formatting of 3 lines of text will match word doc
- [ ] Hyperlink for "use our online claim status tool" will link to https://www.va.gov/claim-or-appeal-status
- [ ] Hyperlink for "800-827-1000" will be a telephone link to tel:+18008271000
- [ ] Hyperlink for "IRIS (Inquiry Routing & Information System)" will go to https://iris.custhelp.va.gov/
- [ ] Detail Pages for other facility types (VA Health, Urgent Care - VA Health, Community Providers, VA Cemeteries, Vet Centers) are unaffected by this change.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
I think IRIS is going away, so may be incorrect.

**Comment by mmiddaugh** [comment]
One recommendation from March 2020 research:

Include information on regional offices for benefits help

This is based on several participants whose searches resulted in only one benefit office which were hundreds of miles away.

**Comment by mmiddaugh** [comment]
@davidconlon I think this is a duplicate for [#9496](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9496)
