### ISSUE TITLE
Create Referral Serializer (singular)

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#98261]
Create a Referral serializer that returns the details of a specific referral. This serializer has more data than the plural Referrals serializer

## Tasks
- [ ] [BE] ReferralSerializer implemented

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by carlosfelix2** [comment]
This is a very small effort. Set to be part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/98256
