### ISSUE TITLE
Host Workshop (2) based on Q3 Survey

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#98267]
## Purpose
Create a workshop series that helps Platform teams digest Quarterly Survey feedback and prioritize their work.

- We want to:
  - ensure that we focus on engineering-based teams
  - conduct workshops that include only PMs and TLs
  - facilitate conversation around feedback, and creating problem statements

## Tasks
- [x] Schedule and host Workshop 2 (week of 12/9)
- [x] Ensure any last items are filled out and organized on the Mural board
- [x] Discuss any learnings/next steps with Design Lead

## Acceptance Criteria
- [x] Workshop 2 has been conducted
- [x] Mural board is complete
- [x] Next steps are established
