### ISSUE TITLE
Sign in: Audit sign in types on VA.gov

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#98274]
## Description
We need to audit VA.gov to find unauthenticated pages that mention these sign in types:

- DS Logon
- ID.me
- Login.gov
- MyHealtheVet

**Note:** We don't need to find pages that mention these sign in types within sign in widgets. We aren't updating sign in widgets as a part of this work.

## Resources
- [Page tracker](https://dvagov.sharepoint.com/:x:/s/SitewideCAIA/EVCd3gQbVGxAnpg4Ng0iDdEBA26ootEzF_zBnRA0kbrLTg?e=ow7Mhm) (SharePoint)
- [IA MHV audit](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1728071932126/91696c078149ca319e0cf553278f2780db11efe8) (Mural)

## Tasks
- [x] AP: Create page tracker
- [x] MZ: Find and record pages using the Drupal audit and VA.gov search tool

## Criteria
- [x] We've identified all unauthenticated pages that mention sign in types on VA.gov

**Comment by aprocik1** [comment]
@megzehn, here's [the page tracker](https://dvagov.sharepoint.com/:x:/s/SitewideCAIA/EVCd3gQbVGxAnpg4Ng0iDdEBA26ootEzF_zBnRA0kbrLTg?e=ow7Mhm) for this audit. I'm happy to edit the columns, as needed. Let me know if you have any feedback!

**Comment by aprocik1** [comment]
From Danielle:

> Someone mentioned to me that this page needs updating because it mentions MHV Premium. You probably would catch this in your audit anyway, but dropping here just in case! https://www.va.gov/resources/covid-19-testing-at-va/

**Comment by megzehn** [comment]
This is a file from Drupal with pages that reference MyHealtheVet: [MyHealtheVet CSV.csv](https://github.com/user-attachments/files/18065211/MyHealtheVet.CSV.csv)

I'm going to look through these more closely and weed out the irrelevant ones before adding them to our spreadsheet.

**Comment by megzehn** [comment]
Update: All the Drupal static pages that we need to update are in [this page tracker that A set up](https://dvagov.sharepoint.com/:x:/s/SitewideCAIA/EVCd3gQbVGxAnpg4Ng0iDdEBA26ootEzF_zBnRA0kbrLTg?e=ow7Mhm). 

I was able to edit a few nodes and add some notes, but I didn't get through the whole list.

**Comment by megzehn** [comment]
A, Laura, and I chatted about this today. There are no next steps for us to do. Joelle from identity will be coordinating updates on the product side.
