### ISSUE TITLE
Terraform Upgrade

### ISSUE THREAD

**Issue by AshleyGuerrant** [department-of-veterans-affairs/va.gov-team#98290]
## Status
_Update each week until completed_
| Date | Status | Launch Date | Notes |
| ----- | ------ | ------------------------- | ------ |
| 2/12/25 | Done | end of February 2025 | Terraform Upgrade has been completed |
| 1/24/25 | In-progress, slightly delayed | end of February 2025 | Sprint 19: The development environment upgrade is complete. The staging environment upgrade was originally forecasted to start in Sprint 19, however, the developer is on support rotation during this sprint so work will resume during Sprint 20. No challenges or risks at this time. |
| 1/17/25 | In-progress, slightly delayed | Mid-February 2025 | Sprint 19: The development environment upgrade is complete. The staging environment upgrade was originally forecasted to start in Sprint 19, however, the developer is on support rotation during this sprint so work will resume during Sprint 20. No challenges or risks at this time. |
| 1/10/25 | In-progress | Start of February 2025 | Sprint 18: The development environment upgrade is in progress. The staging environment upgrade will start in Sprint 19. The dev. ran into some unexpected behavior in Terraform that is being referred to as "ghost changes" and has figured out a workaround for those, but I would not consider this a risk to the overall initiative. |
| 1/3/25 | In-progress | Start of February 2025 | Sprint 18: The development environment upgrade is in progress. The staging environment upgrade will start next week. No challenges or risks at this time. |
| 12/20/24 | In-progress | Start of February 2025 | Sprint 17: The development environment upgrade is in progress. The staging environment upgrade is planned for Sprint 18. No challenges or risks at this time. |
| 12/13/24 | In-progress | Start of February 2025 | Sprint 16: received [stakeholder approval](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3678208035/Terraform+Upgrade+Overview+and+Estimated+Timeline?focusedCommentId=3693543426) to proceed with the upgrade. The development environment upgrade has kicked off and will continue into Sprint 17. No challenges or risks at this time. |
| 12/6/24 | In-progress | Start of February 2025 | Sprint 16: An audit of the current Terraform modules is being conducted - this work will pin any modules that are not pinned to a concrete version. A [document](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3678208035/Terraform+Upgrade+Overview+and+Estimated+Timeline) outlining the upgrade milestones and estimated timeline was created. Additional documentation will be created this sprint which will provide an analysis of the recommended upgrade path. There are no immediate risks identified for this upgrade, although it does block the Redis upgrade. |
| 11/25/24 | Discovery | Start of February 2025 | Discovered that the version of Terraform currently being used needs to be upgraded because of security issues. This upgrade is necessary to continue work on the Redis POAM/upgrade. |

## Epic User Story
As the Managers of the Redis tool,
We need to perform upgrades to our Terraform version,
So that we can run security upgrades in our Redis clusters without the risk of Terraform crashing on Mac OS.

##  Issue Description
It was discovered on 11/25/24 that Terraform needs to be upgraded, because of stability issues with our current Terraform version. This work is a requisite to continuing work on the [Redis POAM (Plan of Action and Milestones) epic](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/2034).

## High Level Tasks
- [x] Complete discovery
- [x] Audit Terraform modules
- [x] Document analysis of recommended upgrade path
- [x] Perform Upgrade
     - [x] Upgrade and test in DEV environment
     - [x] Upgrade and test in STG environment
     - [x] Upgrade in SANDBOX environment (no downtime is required)
     - [x] Upgrade in PROD environment (no downtime is required)

## OCTO Objectives:
**Objective:**
O2: Our platforms are the best way to deliver products at VA
**OKR**
OKR1: Our platforms hit the "elite" level (as defined by DORA) on Deployment Frequency, Lead Time for Changes, Change Failure Rate, and Time to Restore Service

---

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/2135
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/2117
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98289
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/2118
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/2119
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/2132
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/2133
```

**Comment by JoeTice** [comment]
Terraform Upgrade has been completed
