### ISSUE TITLE
Github design documentation cleanup

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#98294]
## Issue Description
Currently, it's very hard to navigate the Debt team's GitHub docs, it'd be helpful to have the product and team docs better linked together. 

---
## Tasks
- [x] Add readmes to our team and product folders and better organize and cross link them.

## Acceptance Criteria
- [ ] Can easily navigate between team and product docs with clear readmes detailing what documentation there is
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Adding link to Repo guidelines on GH: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/repo-guidelines.md

**Comment by mgleo** [comment]
Table of contents for product/team added: 
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/benefits-memorials-2
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution/Financial-Status-Report
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/combined_va_debt_portal
