### ISSUE TITLE
SC | Implement post-research design changes

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#98304]
## Value Statement

**_As a_** Veteran

**_I want to_**

**_So that_** 

---

## Background Context

We conducted research for the 2024 SC updates. The following recommendations require design changes.
- Keep the initial MST question and add language to clarify that the question is optional and does not impact the Veteran’s claim.
- Possibly remove the presumptive conditions alert within the form.
- It’s clear to Veterans within the introduction of the form that it covers PACT Act. Including the alert mid-form to re-emphasize presumptive conditions causes unnecessary friction, especially for Veterans who use screen readers.
- Adjust the wording around types of facilities to provide more information and clarity.
- Adjust the hint for the optional memorable date.
- Adjust the limiting consent screen to either make clearer that not providing input is an option, or position question to de-emphasize input.

## Tasks

- [x] Update MST question
   - [x] Create new section (section 5 out of 6) for VHA Notification question
   - [x] Move MST questions to new section
   - [x] Update question and add hint text to first MST question page
- [x] Remove dismissable PACT alert
   - [x] Add additional info component about presumptive conditions
- [x] Update 5103 notice checkbox
   - [x]  Update the certify checkbox to include language about OR receiving a decision in less than a year
- [x] Update facility question
   - [x] Make question required 
   - [x] Reorder checkboxes
   - [x] Add hint for VA Vet Centers
   - [x] Remove excessive language under non-VA facilities 
- [x] Update memorable date question
   - [x] Update question to include language about date
   - [x] Remove hint text 
- [x] Update limiting consent question
   - [x] Add new yes/no screen for limiting consent
   - [x] Make limiting consent screen conditional and required
   - [x] Remove hint text from limiting consent screen 

## Dependencies 

- Add here

## Acceptance Criteria

- [ ] [5103 notice screen](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=2396-34461&m=dev)
- [ ] [Facilities and VA evidence screens](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=1498-14797&m=dev)
- [ ] [Non-VA evidence screens](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=2384-30921&m=dev)
- [ ] [VHA Indicator screens](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=1652-23613&m=dev)
- [ ] [Review and submit screens](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=2415-51162&m=dev)

## Out of scope

- Supplemental Claims HTML submission confirmation page

## Open questions

- Add here

## Designs and Build Notes

- Add here

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

### Enablement team (if needed)
@ member of team

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@comaurice @Mottie We got approval to implement design recommendations that came from research.

I'm not sure what to write for the value statement, but otherwise, the ticket should be refined and ready-to-go.

I can meet with @Mottie anytime to do a kick-off walkthrough for the changes.

**Comment by Mottie** [comment]
Post research changes merged in with https://github.com/department-of-veterans-affairs/vets-website/pull/33397, but that work was attached to https://github.com/department-of-veterans-affairs/va.gov-team/issues/95167

**Comment by Mottie** [comment]
Ready for validation in staging. See https://github.com/department-of-veterans-affairs/va.gov-team/issues/95167#issuecomment-2512683665 for latest changes that need validation.

**Comment by Mottie** [comment]
@comaurice to validate today - linked to #95167

**Comment by Mottie** [comment]
Ummm, actually, there are a few more post-research changes that I missed for this ticket.

**Comment by Mottie** [comment]
Changes are now available for validation in staging

**Comment by comaurice** [comment]
Needs validation

**Comment by eileen-coforma** [comment]
<img width="598" alt="Image" src="https://github.com/user-attachments/assets/6f743ae6-b8b5-4fad-853f-1b53f2fb1774" />

Treatment date is optional if it's after 2005, but I'm blocked from proceeding.

**Comment by comaurice** [comment]
<img width="710" alt="Image" src="https://github.com/user-attachments/assets/c814fe7b-04f9-463c-8b1d-cd20c1620ba5" />

Reproduced on my end, also blocked with no date provided. @eileen-coforma btw what can you point to that confirms treatment date is optional after 2005? 

<img width="690" alt="Image" src="https://github.com/user-attachments/assets/8946a1b9-d7af-49a3-b3c6-e4bf59616b83" />

"Go back to upload your records" is seen twice in the error message, is this redundancy expected? 

<img width="732" alt="Image" src="https://github.com/user-attachments/assets/dbc818a6-c65f-4bdc-acad-bea76da024a5" />

Should the headers in red boxes be bolded like the design? Or is that a web component limitation?

No other findings for me!

**Comment by Mottie** [comment]
Hmm, for the last screen shot, I made those _not_ bold because this is also rendered on the confirmation page. @eileen-coforma so bold here, but not on the confirmation page?

**Comment by eileen-coforma** [comment]
@comaurice The optional after 2015 is something written on the updated SC form. I also confirmed with Andrew Gray and Alejandro during the readout that it's best if we surfaced that language (which used to be part of a hint), since it's not beneficial for the Veteran to provide a date post 2015.

@Mottie Yes, bold for evidence summary. The confirmation has a separate treatment for questions, which is why it's not bolded. For the summary page, it'll be easier to parse if it is bolded.

**Comment by comaurice** [comment]
You are meaning to say 2005 right? Said 2015 twice so wanted to make sure @eileen-coforma

**Comment by eileen-coforma** [comment]
@comaurice yep, I typo'd XD

**Comment by kayline** [comment]
Ready to validate in staging

**Comment by eileen-coforma** [comment]
@Mottie @comaurice validated that the design issues were fixed. The memorable date validation can't be fixed until LH updates the date question to be optional, so it doesn't have to pass a value. Right now we're passing a test value to let us move forward in the form for testing.
