### ISSUE TITLE
[Development] Add contact info block to HLR review

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#9831]
## Issue Description

A Higher-Level Review design update includes a read-only accordion block containing the user's contact information. The typical "Edit" button is replaced with a "Edit on profile" button to redirect the user to their profile page to make any updates to their address, phone number or email address

<img width="565" alt="screen_shot_2020-06-03_at_10 29 17_am" src="https://user-images.githubusercontent.com/136959/83775885-1b5d1880-a64d-11ea-8ba2-c5f6f9d964a7.png">

## Tasks

- [ ] Add contact info review accordion to the review & submit page.
- [ ] Add appropriate unit test

## Acceptance Criteria

- [ ] An accessibile review contact information accordion is available on the review & submit page
