### ISSUE TITLE
ARM Edge Case Dashboard Prep

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#98337]
### Description
This work is to track the creation of the edge case dashboard for the accredited rep team. Domo dashboard can be found [here](https://va-gov.domo.com/page/1897070864).

### Tasks

- [x] Connect data to cards
- [x] Populate preliminary cards on data

### Acceptance Criteria

- [x] Edge case dashboard is ready for review with ARM Team.

**Comment by johnny-jesensky-adhoc** [comment]
This work was being tracked on the [original request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70424), so creating this one to track the work.

Dashboard progress can be found [here](https://va-gov.domo.com/page/1897070864).

![Image](https://github.com/user-attachments/assets/abfced00-64c4-487b-a527-d571f219883b)

FYI @Blivaditis, @ChristineYoungZA
