### ISSUE TITLE
DD: Look into submissions from frontend to backend

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#98335]
## Issue Description
Given: The frontend (vets-website) submits form data to the backend (vets-api)
When: The frontend code is merged in and the frontend is able to submit forms
Then: We must inspect the data coming from vets-website to vets-api and possibly make changes to the vets-api code including hardening validation and maybe changing what vets-api's expectations of what will be sent to what is actually being sent.

## Tasks
- [x] Look into payload coming from frontend, make adjustments to backend to accommodate the frontend's payload
- [ ] Look into using the JSON::Schema library for validation

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] All changes necessary to successfully accept and validate data coming from vets-website are made.

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by digitaldrk** [comment]
Marking this as blocked until we get [the FE PR merged](https://github.com/department-of-veterans-affairs/vets-website/pull/33332)

**Comment by digitaldrk** [comment]
Still blocked, we had to merge [another PR](https://github.com/department-of-veterans-affairs/vets-website/pull/33495) before the [FE PR could get merged](https://github.com/department-of-veterans-affairs/vets-website/pull/33332)

**Comment by penny-lischer** [comment]
We will look into using the JSON::Schema library for validation at a later time.
