### ISSUE TITLE
Engine BE 1: Duplicate Sidekiq Jobs in Engine

### ISSUE THREAD

**Issue by kayline** [department-of-veterans-affairs/va.gov-team#98348]
## Value Statement

**_As a_** backend dev

**_I want to_** to duplicate our backend jobs in an engine

**_So that_** we can isolate our code

---

## Background Context

- Part of the Engine epic
- Step 1 of migration plan
- All jobs: 
- [x] delete_saved_claim_records_job.rb  
- [x] form4142_submit.rb
- [ ] submit_upload.rb                 
- [x] nod_email_loader_job.rb           
- [x] nod_status_updater_job.rb          
- [x] sc_status_updater_job.rb
- [x] failure_notification_email_job.rb  
- [x] hlr_status_updater_job.rb          
- [x] nod_send_email_job.rb              
- [x] saved_claim_status_updater_job.rb  submit_upload.rb

## Tasks

- [ ] Duplicate job files
- [ ] Duplicate tests
- [ ] Duplicate any necessary service files

## Dependencies 

- Add here

## Acceptance Criteria

- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Out of scope

- Don't use new jobs
- No code deletion

## Open questions

- Add here

## Designs and Build Notes

- Add here

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

### Enablement team (if needed)
@ member of team

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design
