### ISSUE TITLE
Kerry Minott-Onboarding

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#98345]
## Description
This task represents the onboarding work that Kerry is doing that will allow her to get set up 

---
### Tasks
- [x] Get fingerprinting completed
- [ ] Finish the eApp, and submit
- [ ] In the meantime - Work w/ Curt to get a list of materials for frontend to get familiar with before you have access

### Acceptance Criteria
- [ ] The eApp has been submitted, and access requests have been made
