### ISSUE TITLE
Engine BE 3: Delete old Sidekiq jobs WAIT UNTIL Jan 13

### ISSUE THREAD

**Issue by kayline** [department-of-veterans-affairs/va.gov-team#98355]
## Value Statement

**_As a_** backend dev

**_I want to_** remove duplicated Sidekiq job classes in main

**_So that_** we are only maintaining the version is the engine

---

## Background Context

- Wait at least 1-2 weeks after enabling new jobs to ensure things are working
- DO NOT delete form4142_submit and submit_upload, they can't be moved until the controllers referencing them are moved

## Tasks

- [ ] Delete old jobs
- [ ] Delete old tests
- [ ] Delete and helpers/services that are not being used in main app

## Dependencies 

- Add here

## Acceptance Criteria

- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Out of scope

- Add here

## Open questions

- Add here

## Designs and Build Notes

- Add here

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

### Enablement team (if needed)
@ member of team

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by kayline** [comment]
Waiting period before merge

**Comment by comaurice** [comment]
Just needs final verification
