### ISSUE TITLE
Create Script for updating helm chart settings-local-secret paths

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#98389]
Each environment helm chart has a section for `settings-local-secrets` each secret has a `path` that corresponds to the current params store path and an env_var that is used in the container and setting-local-yml configmap

https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/prod/values.yaml#L619

## Tasks
- [x] Create a script that can be used in each environment helm chart

## Acceptance Criteria
- [x] The script updates the `settings-local-secret` paths to the temp path (based on sheet linked below)
- [x] The script updates the `settings-local-secret` env_var based on the temp path and config settings/env_var convention

Example:

Path:
` /dsva-vagov/vets-api/common/argocd/slack/api_key` -> `/dsva-vagov/vets-api/dev/env_vars/argocd/slack/api_key`

Env_Var:
`ARGOCD_API_TOKEN` -> `SETTINGS__ARGOCD__SLACK__API_KEY`
Note: the above converts `argocd/slack/api_key `to `SETTINGS__ARGOCD__SLACK__API_KEY`

## Resources

[Helm Chart Mapping - Param Store Transition Paths](https://docs.google.com/spreadsheets/d/1-7PLskyY67b4J1fsk-FADYxnSN1UrmVziFfFIt_1saU/edit?gid=395068805#gid=395068805
)
