### ISSUE TITLE
Create Script to Copy Param Store Secrets

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#98387]
Settings that use param store secrets will need to moved to a new intermediate path for the transition to the new settings convention

## Tasks
- [ ] Create a script to copy the values of the current paths to the new paths  

Example:

`/dsva-vagov/vets-api/dev/appeals_status/app_token` -> `/dsva-vagov/vets-api/dev/env_vars/appeals_status/app_token`

## Acceptance Criteria
- [x] The script can copy a param store values to a new param store path
- [x] The script accepts a list and can update all the entries in the list

## Resources

[Helm Chart Mapping - Param Store Transition Paths](https://docs.google.com/spreadsheets/d/1-7PLskyY67b4J1fsk-FADYxnSN1UrmVziFfFIt_1saU/edit?gid=395068805#gid=395068805
)
