### ISSUE TITLE
[Events] [CONSIDER] Additional display options for event listing pages

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#9839]
## Issue Description
Suggestion from Ryan Stubblebine, Pittsburgh VAMC:

I wonder if there is an opportunity to create a calendar view of events similar to what exists in teamsite. 
The current VAMC display of future events is in a list form. For recurring events, this list might look pretty jumbled, repetitive, and difficult to follow.

---
## Tasks
- [ ] Research: Is this something Veterans would want?

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jilladams** [comment]
Public Websites purview now, and any calendar will come from their board / priorities. Closing.

**Comment by FranECross** [comment]
Moving to Icebox per Dave C with note: The 'old' calendar view in teamsite is archaic and not mobile first. While we could do another view,, we would want to se whether this is something Veterans want rather than something that an editor wants because it's what they were used to.

**Comment by FranECross** [comment]
Closing old ticket per note above.
