### ISSUE TITLE
Copy Param Store Secrets from Current Path to Temp Path

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#98392]
Param store secrets need to be store in an intermediate path to be able to normalize the helm charts. 

## Tasks
- [ ] Copy Param Store Secrets from Current Path to Temp Path

## Blocked:

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98387

## Acceptance Criteria
- [ ] All the "Current" path values are copied to the "Temp" path based on the sheet linked below
- [ ] The values in each pair (current & temp) match exactly

## Resources 

[Helm Chart Mapping - Param Store Transition Paths](https://docs.google.com/spreadsheets/d/1-7PLskyY67b4J1fsk-FADYxnSN1UrmVziFfFIt_1saU/edit?gid=395068805#gid=395068805
)
