### ISSUE TITLE
Update settings-local-secrets to use Temp secrets

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#98403]
With the assistance of the script (referenced in the blocked section)... update the `settings-local-secret` and `settings-local-yml` of each environmental helm chart 

Note: Many PRs will be required & hardcoded settings are excluded

## Tasks
- [x] Update the `settings-local-secret` paths to the temp path (based on sheet linked below)
- [x] Update the `settings-local-secret` env_var based on the temp path and config settings/env_var convention 
- [ ] Remove the associated settings from `settings-local-yml` configmap

## Blocked
- Script: https://github.com/department-of-veterans-affairs/va.gov-team/issues/98389
- Pre-work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/98392

## Acceptance Criteria
- [ ] `settings-local-secret` paths and env_var are updated
- [ ] Settings are removed `settings-local-yml` configmap

Example Before/After

**Before:** 
_settings-local-secret_
```
name: mhv_rx_app_token
path: /dsva-vagov/vets-api/prod/mhv_app_token
env_var: MHV_APP_TOKEN
```

_settings-local-yml_
```
app_token: <%= ENV['MHV_APP_TOKEN'] %>
```

------

**After:** 
_settings-local-secret_
```
name: mhv_rx_app_token
path: /dsva-vagov/vets-api/prod/env_var/mhv/rx/app_token
env_var: SETTINGS__MHV__RX__APP_TOKEN
```

_settings-local-yml_
```
...REMOVED...
```

**Comment by AshleyGuerrant** [comment]
@stevenjcumming & @patrick-black-oddball - what is the status of this ticket & is it still relevant?

**Comment by stevenjcumming** [comment]
@AshleyGuerrant this can be closed as completed
