### ISSUE TITLE
DR | SavedClaim query timeout for Sidekiq jobs

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#98402]
## Value Statement

**_As a_** backend dev

**_I want to_** have queries that do not time out

**_So that_** the queries succeed

---

## Background Context
* SavedClaim queries being run by the sidekiq jobs occasionally time out:
`DecisionReview::HlrStatusUpdaterJob a3353e4630498ca2c916b3b7 died with error PG::QueryCanceled: ERROR:  canceling statement due to statement timeout`

## Tasks

- [ ] Investigate indexing
- [ ] Investigate batching

## Dependencies 

- Add here

## Acceptance Criteria

- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Out of scope

- Add here

## Open questions

- Add here

## Designs and Build Notes

- Add here

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

### Enablement team (if needed)
@ member of team

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
Deployed and verified in production.
