### ISSUE TITLE
[CST] Remove 5103 standard notice

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#98412]
## Value Statement

Slack Convo - https://dsva.slack.com/archives/C04KHCT3ZMY/p1733344334287379

**Problem:**
Veterans are currently seeing 5103 standard notices that tell them they should be able to download a corresponding 5103 letter in the claim letters section (or received it in the mail). In reality, in some cases, these letters are not available and haven't been received in the mail. In light of this, we need to remove the alert associated with the "Standard 5103 Notice" (not to be confused with Automated 5103 notices that have alerts associated with tracked items). 

More details here: https://www.reddit.com/r/VeteransBenefits/comments/1gpw0f5/review_evidence_list_5103_notice/?share_id=pc_ogPq0w7CATzgkWsC-M&utm_content=1&utm_medium=android_app&utm_name=androidcss&utm_source=share&utm_term=1&rdt=35611

**Solution:**
Possible solutions are..

- Changing the content for just the standard notice to not include invitations to download letters
- Not show the standard 5103 notice

Discussed in slack and we will plan to remove the alert all together! 

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Users can no longer see alerts associated with the Standard 5103 Notice (alerts not associated with 5103 tracked items)
- [ ] Users can still see Automated 5103 alerts and detail pages (these have actual tracked items associated with them).

**Comment by pmclaren19** [comment]
This ticket has been worked and the pr merged! Verified in Staging on user 19, claim https://staging.va.gov/track-claims/your-claims/600595858/status and it looks correct.
