### ISSUE TITLE
Access Requests: Info session(s)

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#98418]
## Purpose
Access Requests initial discovery research to set up for a study. Mapping the path of these requests -- what information is coming and going, and to where?

Naomi: start by looking at these docs, then talking to Alyssa from Support.
[Pre-requisites for Access Requests](https://depo-platform-documentation.scrollhelp.site/getting-started/prerequisites-for-access-requests)
[Request access to tools](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools)

Notes from Andrea and Clint:
- need to understand the pieces that live in the open repo
- need to be able to see who asked for the access and what level of access
   - Not ZenHub or Slack access
   - Access to Platform Tools that currently go through the open repo
      - Socks requests
      - Console
      - AWS
      - Elevated Datadog permissions
   - Not Datadog requests

## Tasks
- [x] Schedule info session w/ Support team
- [x] Prep mural board for discussion
- [x] Take notes about each open repo tool
- [x] Map each open repo tool

## Acceptance Criteria
- [x] Session scheduled and held
- [x] Info is gathered and roughly mapped on each open repo tool
