### ISSUE TITLE
[DESIGN] Create Wireframes for Displaying and Editing NOK & EC in the Profile Section of VAHB

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#98424]
We have been given the go-ahead to create the profile screens for emergency contact and next of kin that will need to be added to mobile.

## Tasks
- [x] Review current mobile Profile information
- [x] Review [Profile's design for next of kin and emergency contact on on va.gov](https://www.figma.com/design/uYMdNtQnrzq7OiDl0rPF9k/Profile---Personal-health-care-contacts?node-id=4-1425&node-type=canvas&t=CjVnAtQwrxlhR3XM-0)
- [x] Create wireframes using overlay component that Don told Kristen about (ask Kristen if not sure which component this is)
- [ ] Submit for review by appropriate parties: Kristen (and Ryan Thurwell via Kristen?) --- waiting until later

## AC
- [x] Wireframes created and confirmed for design direction
- [ ] Submit for review by appropriate parties: Kristen (and Ryan Thurwell via Kristen?) --- waiting until later (when Kristen returns from OOO and then a later feedback session with VAHB folks)

**Comment by cgednalske** [comment]
@loripusey and here's the second Pre-check-in VAHB ticket. I split them out because all work together would probably get to be too much. But Zach and I could each take one of these.

**Comment by cgednalske** [comment]
[Emergency Contact and Next of Kin additions to VAHB Profile](https://www.figma.com/design/EqA0zouiQYfXPNma4jV1CR/VAHB-Mobile-App-%7C-PCI?node-id=141-60569&t=jomNVIZvN7ujflqj-1)

@zach-park everything has been updated based on our conversation today. Could you take a look and validate when you have a chance? 🙂 

@loripusey while working on this ticket and Zach's ticket, we've identified some ticket work (content or alerts) or spikes (business/logic questions) that we'll want to address next. I can create those on Monday.

**Comment by zach-park** [comment]
Validated. Looks great. Thank you!

> [Emergency Contact and Next of Kin additions to VAHB Profile](https://www.figma.com/design/EqA0zouiQYfXPNma4jV1CR/VAHB-Mobile-App-%7C-PCI?node-id=141-60569&t=jomNVIZvN7ujflqj-1)
> 
> [@zach-park](https://github.com/zach-park) everything has been updated based on our conversation today. Could you take a look and validate when you have a chance? 🙂
> 
> [@loripusey](https://github.com/loripusey) while working on this ticket and Zach's ticket, we've identified some ticket work (content or alerts, for example) or spikes (business/logic questions) that we'll want to address next (or at least soonish). I can create those on Monday.

**Comment by cgednalske** [comment]
Awesome, thanks @zach-park!
