### ISSUE TITLE
[DESIGN] Create VAHB wireframes for electing to edit demographics information

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#98425]
In addition to creating the profile screens for emergency contact and next of kin, we'll also need to create the screens that will get the Veteran to the editing process for contact information, next of kin, and emergency contact. 

Example: At "Is this your contact information?" question, how does the process work as far as the Veteran selecting no and/or edit? Userflow currently has the option to say no and edit later, for example, but it may be something that ends up slightly different.

## Tasks
- [x] Review [userflow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1732046663886/09f5f082d33ea39fff3e7321b4c502d49c053b34) - _**NOTE: Evaluate if the "edit later" option currently shown in the userflow is our best pattern. It likely will change as pattern exploration continues**_
- [x] Review earlier editing iterations from Check-in
- [x] Review differences in patterns between PCI & VAHB
- [x] Create wireframes for feasible options
- [x] Discuss with UX
- [ ] Submit for review by appropriate parties: Kristen (and Ryan Thurwell via Kristen?)

## AC
- [ ] Wireframes created and confirmed for design direction
- [ ] Submitted for review by appropriate parties: Kristen (and Ryan Thurwell via Kristen?)

## Deliverable
- https://www.figma.com/design/EqA0zouiQYfXPNma4jV1CR?node-id=4-20

**Comment by cgednalske** [comment]
@zach-park I added a little note to the description to make sure it's clear you're expected to question this part of the userflow as you work on this pattern 🙂 It's definitely something that relies most on how the pattern works out, so you don't have to follow what's mapped out now if it's not the best solution.

**Comment by zach-park** [comment]
Thank you!

**Comment by zach-park** [comment]
@StevenStraily @cgednalske , this ticker is ready to be validated. Thank you!

**Comment by zach-park** [comment]
Figma link: https://www.figma.com/design/EqA0zouiQYfXPNma4jV1CR?node-id=4-20
