### ISSUE TITLE
[VETS-API] Upgrade Rails to 7.2.2

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#98427]
Upgrade rails to the next minor version (7.1.3 ->  7.2.2) ahead of upgrading to rails 8

## Tasks
- [x] Bump Rails to 7.2.2
- [x] Fix any issues/broken specs
- [ ] ~~Fix any Rails 8 Deprecation warnings~~ New ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98790)

## Acceptance Criteria
- [x] Rails 7.2.2 is deployed to production
