### ISSUE TITLE
[VETS-API] Upgrade Rails to 8.0.0

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#98428]
Upgrade from Rails 7.2.2 to 8.X.X (currently 8.0.0 as of writing this)

## Tasks
- [ ] Bump Rails to 8.X.X
- [ ] Fix any issues/broken specs
- [ ] Fix any Deprecation warnings

## Acceptance Criteria
- [x] ~~Rails 8 is deployed to production~~ Follow up ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99428)

**Comment by ryan-mcneil** [comment]
[Followup ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99428) created to track continued work on this upgrade
