### ISSUE TITLE
Edit: Revproxy

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#98421]
## Issue Description
[Ticket 79065](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?pane=issue&itemId=84087733&issue=department-of-veterans-affairs%7Cva.gov-team%7C79065) has brought to light the need for a separate page on RevProxy Deployment.

All the other deployment items on the Deployments page are _applications_. Rev Proxy is infrastructure. This difference alone could justify a Rev Proxy-specific page. Couple that with the fact that the Deployments page is getting rather long and it is easy to see that Rev Proxy should be split off into its own page. 

The real question, however, is should that page be titled "Infrastructure Deployments" and also include other infrastructure pieces -- and make room for future content expansion -- or should it remain simple a "Rev Proxy" page. 

The SME on the above-mentioned ticket hinted that we might not want to make other infrastructure pieces public. But that SME recommended that we talk to Kyle Matheny about this ticket. So our new SME for the Rev Proxy/Infrastructure page is Kyle. 

---
## Tasks
- [ ] Edit Deployments Page (remove rev proxy section and rework page intro)
- [ ] Create new page 
- [ ] Have SME check new page
- [ ] Deploy new page

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by BSmolensky** [comment]
See [comments in this discovery ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97025#issuecomment-2536217178) for more information on what to include in this new page.

**Comment by jknipes** [comment]
Based on concerns mentioned in [99929](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99929#issuecomment-2576214634), and the upcoming overhaul to Deployments mentioned in [70863](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70863), we are pausing this effort. Moving ticket to Icebox.

**Comment by jknipes** [comment]
Page was updated on February 25th, work is complete, closing ticket as _done_.
