### ISSUE TITLE
New VFS Team Member Template Kim McCaskill

### ISSUE THREAD

**Issue by kimmccaskill-oddball** [department-of-veterans-affairs/va.gov-team#98506]
### Your name

Kim McCaskill

### Pronouns

he/him

### Role

Full Stack Engineer

### Email

kim.mccaskill@oddball.io

### GitHub handle

kimmccaskill-oddball

### Start date

11/4/24

### VFS team

Mobile Feature Support

### Tasks for everyone

- [x] Add your name to the ticket title
- [x] Update your [Slack profile](https://depo-platform-documentation.scrollhelp.site/getting-started/slack-profile)
- [x] Request [access to tools](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html)
- [x] Confirm that you have access to the [VA GitHub Organization](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GettingaccesstotheVAGitHuborganization).
- [x] Opt out of [Google Analytics](https://www.va.gov/analytics-opt-out.html) on all of your browsers on your work machines, personal machines (if you are not a Veteran yourself using the site for your own applications), and mobile devices
- [ ] Are you a Veteran? Consider adding your name to the [Veterans willing to help VA teams with product testing](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md) document
- [x] Complete educational tasks

### Tasks for Front-end and Back-end Engineers

- [ ] Confirm that [you can log in as a test user](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)

### Tasks for Product Managers & Delivery Managers

- [ ] Schedule a PM intro via [Calendly](https://calendly.com/collaboration-cycle/product-manager-intro) with Shira Goodman (Platform Governance Team PM).
- [ ] If your team is new, please complete the [New VFS Team ticket](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members#Guidancefornewteamsandteammembers-NewVFSteams). If you're joining an existing team, you can skip this step.

### Tasks for Platform

- [x] New VFS team member has been added to the VFS Team Roster located in [Atlas](https://www.va.gov/atlas/)
- [x] New VFS team member has been added to the vets.gov-write GitHub team

**Comment by davidpetras** [comment]
Added to Atlas
Added to vets.gov-write

Platform Checklist complete
