### ISSUE TITLE
[CST] Create conversation guide for "Document Status"

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#98509]
## Value Statement
**_As a_** Researcher
**_I want to_** create a conversation guide
**_So that_** we aim to follow the same conversational style and set of questions for each user.

---
## Background Context
We want to test our Document Status designs to ensure that:

- File uploads and the timing of documents making it to the eFolder is clearly communicated and transparent to Veterans
- If there is a failure in uploading documents from CST, it is clear to Veterans both that it happened and what they should do about it

A prototype will be particularly important for this, as there are various interactions nuances that we need to get right in order for this design to be as successful as possible.

Additional documents:
- [Product Perspective for In-App Silent Failure Research and Design Exploration](https://docs.google.com/document/d/184_nKvWD4Ti3If5nQraAPYOSVTPMCOuHqvGGTbdBE6w/edit?tab=t.0#heading=h.uy8vncs0nodq)

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- [FIGMA](https://www.figma.com/design/m1Xt8XjVDjZIbliCYcCKpE/Silent-Failures-CST-Improvements?node-id=2395-11420&t=9lRCPvCrGTwX3CWW-4)
- [Prototype](https://www.figma.com/proto/m1Xt8XjVDjZIbliCYcCKpE/Document-status-(formerly-silent-failures)?node-id=2771-20256&t=YQPL10Sibs5kZtpY-1)

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] _Create a conversation guide_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] _Converstation is complete_
