### ISSUE TITLE
ARM Dashboard Follow-Ups

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#98502]
### Description
This task is to track the follow-up work on ARM's Custom Edge Case Dashboard.

- https://va-gov.domo.com/page/1897070864

---

### Tasks
-  [x] look into time_on_page (outliers), results returned (high count of no results), and event_action (it's currently DLE name which event_label also is, maybe theres another metric we can tie it to). 

- [x] Review the mural board and see what other charts we can/should add.
- [x] Review and incorporate feedback from Lindsay
- [ ] Load historical data, from March 2024.

### Acceptance Criteria

- [x] ARM Domo dashboard has additional iterative updates

**Comment by johnny-jesensky-adhoc** [comment]
@Blivaditis, @ChristineYoungZA -- Iterative updates made, https://va-gov.domo.com/page/1182586883. Will be presenting this in demo tomorrow. Moving this to _Done_.
