### ISSUE TITLE
[Frontend] MDT - Error 500 alert

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#9850]
## Issue Description
__The Medical Device Reordering Tool needs to display an alert for Error 500 (Internal Server Error). [Reference this ticket for full scope of the problem](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9626)._

An example of an existing Error 500 alert message can be viewed in the [File for disability compensation (VA Form 21-526EZ)](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction) form when logged in as vets.gov.user+1@gmail.com. 

A design has been created in reference to existing Error 500 alerts and [can be viewed on InVision](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/420368430_Error_500). The [content can be copied from the MDT's GH documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-introduction-screen.md#description-4). 

---
## Tasks
- [ ] _Implement the proposed design for internal server errors_
- [ ] _Share the updated UI with the design team for confirmation_

## Acceptance Criteria
- [ ] _The proposed design has been implemented_
- [ ] _The design team has approved the UI update_
---

**Comment by mr0sari0** [comment]
@rileyorr The PR for this has been created. Here is a screenshot of how it looks.

![screenshot-localhost_3001-2020 06 23-15_19_44](https://user-images.githubusercontent.com/12755283/85451549-04348b00-b568-11ea-8bf3-cd71f8233b76.png)

**Comment by rileyorr** [comment]
@mr0sari0 Thanks for providing a screenshot! The DLC's API is currently working (which is a good thing!) so I can't view this in staging. Some feedback I have based on the screenshot:

- Padding between header "We're sorry. Something went wrong on our end" and paragraph "You can't place an order for hearing aid batteries and accessories because something went wrong on our end" should be 16px
- Padding between paragraph "You can't place an order for hearing aid batteries and accessories because something went wrong on our end" and subheading "What you can do" should be 16px
- "What you can do" should be the Bitter typeface - I believe this would be utility class h5?
- Padding between "What you can do" and paragraph "For help ordering hearing aid batteries and accessories, please call the DLC Customer Service Section at 303-273-6200 or email dalc.css@va.gov" should be 16px
- For the entire component the top and bottom margin should be 24px 

Some of this feedback may not apply, I just have no way to inspect the component. LMK if you have any questions or concerns!

**Comment by mr0sari0** [comment]
@rileyorr It might be easier for you if we jumped on a call to do inspections. Let me know what time works for you.

**Comment by mr0sari0** [comment]
Received design team approval and this PR has been merged to `master`.
