### ISSUE TITLE
Consolidate Accredited Rep Crew roadmaps into one main Mural

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#98515]
## Background
We have a lot of roadmap Murals for the AR team and the desire for a high level crew roadmap has come up. 

We discussed creating one universal Mural to house that high level roadmap, along with our team-level roadmaps, so we have a central space for all things roadmapping (and don't have to juggle many roadmap Murals).

## Tasks
- [x] Create a universal Mural for roadmaps
- [x] Add in the [ARM Roadmap](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695926957756/3bcc5202bdc4d93a6898b5bc114b3a45461ab3f7?sender=ud8fb439cf1516edb66c71635)
- [x] Add in the [ARF Roadmap](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1730397202086/f72003f7a4d999ea68293823c66d34bbbdd13ba4)
- [x] Add a link to the [Research Initiatives](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718980793805/b1c89e3110a00b235ee30bc04bab3cc96a33c696)
- [x] Add a link to [Jen's scratchpad](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701101217163/2580a7f0000573dc450caa396b608e251a03e88d)

## Acceptance Criteria
- [x] There is a universal Roadmap Mural for future collaboration across the AR crew.

**Comment by oddball-lindsay** [comment]
Here is that new universal roadmap Mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1733520738354/f3dce99e16382f161269a73a2339de61aea289c6
