### ISSUE TITLE
UX | Design for starting a form in FBEUI

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#98529]
## Description
This design issue is to mock up how the screens and interactions of the FBEUI will support starting a new form and looking up an existing form already in the FBEUI

These steps include:

- Naming the form
- OMB Information

## Tasks 
- [x] Wireframe out initial screens and options 
- [x] Share either wireframes or prototypes as necessary to get necessary feedback and input from team/stakeholders
- [x] Align with team's feasibility 

## Acceptance Criteria
- [x] Feedback collected
- [x] Feedback implemented in (link: [Figma file](https://www.figma.com/design/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?node-id=4325-140422&t=4vCmgdj1Dji16LTq-1))
- [x] Team has reviewed and discussed item
- [x] PM approves of designs

**Comment by brian-wilke** [comment]
Link to where these screens are located has been updated within the acceptance criteria.
Posted [here](https://www.figma.com/design/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?node-id=4325-140422&t=4vCmgdj1Dji16LTq-1) as well

**Comment by brian-wilke** [comment]
Awaiting PM review (moved to Review state)
