### ISSUE TITLE
In-flow prompt to Update Physical address

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9852]
As a veteran who may eligible for Community Care based on drive time, I want to be prompted to update my physical address so I can request a Community Care appointment if I am eligible via drive time. 

---
## Tasks
- [x] ~Determine where in the scheduling flow a user would be prompted to update their physical address as part of community care eligibility consideration~ - Prompt will show as part of 'type of care' screen if physical address is missing in profile data
- [x] Determine content/copy for how to direct users to update their VA profile
- [x] Create new ticket for backlog to implement 'homepage' prompt for update address (#10660)
- [x] Create analytics ticket to track this prompt (#10662)

## Acceptance Criteria
- [ ] A user is prompted on the 'Type of Care' page to update their physical address if they are missing a physical (home) address
- [ ] A user is prompted on the 'Type of Care' page to update their physical address if they are using a PO box as their listed physical address
- [ ] We _will not_ show prompt to users if they have an overseas address or invalid/non-PO box address
- [ ] A user does not lose their spot in the scheduling flow if they receive the prompt to update their physical address
- [ ] The blue "update your address" should open https://www.va.gov/change-address/ in new tab
- [ ] A user does not have take action on the prompt to continue the schedule flow/select type of care
- [ ] The prompt/alert disappears after user clicks 'update address' button

## Final design & copy for in-flow prompt:
![Screen Shot 2020-06-26 at 9.10.27 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/b18891eb-5b14-4cfb-87ee-844b019068f2)

-------
## Background
- VAOSR is using the CCE API to check for CC eligibility
- the CCE API will soon check for 'drive time' as part of eligibility
- the CCE API uses set of geocodes from E&E that we use in our drive time API, knowing that they're generated by PSSG for healthcare enrollees
- Vista and/or va-profile provides residential addresses to E&E. 
- VA-profile validates the address and then provides geocodes back to E&E if the address is valid. If the address is invalid, it requires human intervention to correct. 
- Even if valid, E&E discards va-profile-derived geocoding for healthcare enrollees. 
- PSSG then provides/updates geocodes for new or updated addresses 2x/daily

**Comment by lenaecb** [comment]
I have updated the AC to reflect what we discussed today. 

Confirmed with team that we can make a call to check physical address status. 

@lalexanderson-dsva - for confirming if the address provided is the real Veterans' address... do you have an idea of where/who we can connect with on that? Would Dave have considered this use case with the CCE API?

**Comment by lalexanderson-dsva** [comment]
@lenaecb - I will ask members of the authentication team to start. If the only address listed on file for a Veteran is a PO Box, I'm not totally sure how we would validate if the physical address provided is theirs.

**Comment by lalexanderson-dsva** [comment]
We do not have a way of verifying if an address listed is theirs (no more than we would if they updated a paper form.) We do validate if it is a real address.

**Comment by lenaecb** [comment]
@davem-va - cc'ing you on this as an fyi. We are preparing to turn Community Care back on for user and supporting this edge for the drive-time eligibility. There is no action from you. This prompt will show _before_ the CCE checks.

**Comment by davem-va** [comment]
Thanks @lenaecb   We're good to do with all except for the PACT/PCMM issue.  I'm looking to setup a meeting between the teams.  I'll kick this off in dsva slack.

**Comment by davem-va** [comment]
@lenaecb Just to provide context on the above, while Lighthouse provides source of truth for drive time, we aren't the source of truth for a veteran's address, nor the geocodes derived from it.  E&E is for both.  The address is provided to E&E from either Vista or va-profile.  The geocoding is provided from PSSG for health care enrollees and va-profile for all other Veterans.

**Comment by lenaecb** [comment]
Thanks for that context @davem-va. So for this story, we trying to assist in making sure E&E can get that data if a Veteran is missing their residential physical address in their va-profile. My understanding is that the residential physical address is what is used for eligibility (vs. the other 3 physical address types - confidential, permanent, or temporary). 

@davem-va - when do you think thing something will be in staging for drive time? just thinking through testing.

**Comment by davem-va** [comment]
geocodes supplied from PSSG and derived from residential address are used for drive times.  Our drive time API is in prod today.  PSSG data was updated a couple of weeks ago.

**Comment by lenaecb** [comment]
@mshea0606 - here is the GH issue I reference in slack. Just tagging you for context as to why we're looking to enable the inline address modal for va profile.

**Comment by lenaecb** [comment]
_Q&A session with Dave: (super helpful)_
- **If a Veteran does not have a residential address on file, how does CCE handle that? What happens if CCE doesn't receive either the residential address or address provided is a PO Box?**
    - CCE API - We don't use residential addresses.  We use the geocoding that maps to that.  If we don't have geocoding, we will evaluate the other static criteria (grandfather, no full-service facility in the state, etc) but won't do a drive time calc.
- **If CCE does not have geocoding, will VAOS receive an error from CCE? What is that error?**
    - Yes, unless they're eligible due to the static stuff.  We exit/return at a "first Yes"
    - CCE API will return errors for no geocodes as well as addresses that are newer than the geocode if it exists (we have timestamps for both).  James Whited is trying to close this gap with PSSG so that we have the same update process for geocoding all Veterans.  However, it's not trivial as va-profile and PSSG currently use different sources (Pitney Bowes vs. ESRI).  And, geocoding for PSSG has all sorts of expensive policy outcomes in regard to where we build facilities, where we close them, grow/shrink them
    - Dave directed me to the Lighthouse dev team to find the exact error sent back
- **Can you verify that drive time doesn’t trump CC static eligibility?**
    - Correct, we don't even evaluate drive time if it's a Yes to the static
- **Breakdown of addresses, geocodes, & CCE process:** Vista and/or va-profile provides residential addresses to E&E.  Vista has no validation.  VA-profile validates the address and then provides geocodes back to E&E if the address is valid.  If the address is invalid, it requires human intervention to correct.  Even if valid, E&E discards va-profile-derived geocoding for healthcare enrollees.  PSSG then provides/updates geocodes for new or updated addresses  2x/daily for all VA healthcare enrolleees.  To us, we see one set of geocodes from E&E that we use in our drive time API, knowing that they're generated by PSSG for healthcare enrollees.


_Additional questions based on the above:_
Q: What is the error that is returned if geocode missing to VAOS? _(need to chat with Lighthouse dev, not in API documentation)_
Q: What kind of validation VA Profile has done on the residential address when va.gov pulls it from the VA Profile api? And if any of those validation checks are exposed in an api?
Q: Where is validation that physical address is not a PO Box? Does that happen anywhere in the process?

**Comment by saneshark** [comment]
> CCE API will return errors for no geocodes as well as addresses that are newer than the geocode if it exists (we have timestamps for both). James Whited is trying to close this gap with PSSG so that we have the same update process for geocoding all Veterans. However, it's not trivial as va-profile and PSSG currently use different sources (Pitney Bowes vs. ESRI). And, geocoding for PSSG has all sorts of expensive policy outcomes in regard to where we build facilities, where we close them, grow/shrink them

Can we get a comprehensive set of these errors and what they look like in JSON? I think this will be helpful. There are certain cases where we might want UI to reflect. For example, with respect to the timestamps: If a veteran has updated their VA Profile recently but E&E does not reflect the change yet, this might be an opportunity to show the user a message telling them to try again in X hours when E&E has been updated. It's only one example, based on this list of errors there might be other things to consider and other questions that might come up.

**Comment by davem-va** [comment]
Yes, I think we need to update our api docs on the portal to make this more clear.  I'll try to get you something out-of-band quicker and also get the work scheduled to update the docs.

**Comment by jbalboni** [comment]
Update after syncing with Erik:

- There is some address validation that VA profile does, but users can bypass it if they believe their address is actually valid (which is true in some cases)
- There is some standardization of addresses that go into VA Profile. PO Boxes are formatted into the USPS format from a wide variety of formats.
- Currently, we don't get any geocoding information from VA Profile, nor any kind of validation flag
- Both military overseas addresses and PO Box addresses can be entered into the home (residential) address field

Based on that:
1. I think we can reasonably detect missing addresses, military overseas addresses, and PO Boxes
2. We don't have a way to tell if an address is valid or not otherwise

We still don't know if there are other apis for getting geocoding or address validation information for a Veteran. VA Profile can tell us that. However, we'd have to make an extra call for that information, which is possible, but will be a useless delay for most users. So even if we can get that info separately, it's not clear to me if we'd want to use it.

**Comment by rtwell** [comment]
@peggygannon 

This includes some express care stuff, but all that we need to worry about on this page is the yellow alert at the top. it will appear twice: once on the vaos (authenticated) home page, and again when a user clicks "create appt" and at the top of the Type of care page:

## VAOS home page

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/2b77e63a-39b9-4a55-af5a-1827bd22983a)

## In the VAOS flow:

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/61a29c94-b24e-4378-b006-22474e97664c)

**Comment by lenaecb** [comment]
@rtwell @lalexanderson-dsva - It looks like the desired implementation for this has changed from only having this prompt show in flow to now having a prompt both on the Appointment list homepage and in app.

I want to make sure that's our new intention.

Also, @lalexanderson-dsva do we want the 'update your address' blue button to open which of the following links in a new tab:
- https://www.va.gov/change-address/
- or - https://www.va.gov/profile

**Comment by peggygannon** [comment]
@lenaecb I will take a look at this today. Also, i see there is additional content/detail describing the types of care. Was this recently added to the tool?

**Comment by peggygannon** [comment]
@lenaecb @rtwell 
Hello, please see recommended content for this message. Per Jeff's comment above, it looks like users can have a military and/or PO box address in the residential address field. As such, the content I recommend makes it clear that we need a physical address. 


**You need to have a physical address on file to use some of the tool's features**
You can update your address in your VA profile. Any updates you make there could take up to 24 hours to process through our records.
{button} Update your address (goes to? )

**Comment by rtwell** [comment]
Copy updated:

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/2e9e4fbe-0efd-4662-92e5-82fd1032e6af)

**Comment by lenaecb** [comment]
Awesome, thanks @peggygannon ! 

@rtwell - for your awareness, we are breaking this into two tickets. This ticket will only be about implementing this update 'in flow'. For implementing on alert on the homepage, we're going to create another ticket and hold off from now to revisit based on future homepage research/updates.

**Comment by lenaecb** [comment]
This has been updated to only focus on the 'in flow' prompt. GH issues have been created for a future implementation of the prompt on the appointments 'homepage.' An analytics ticket that corresponds to this work has also been created.

**Comment by jenniemc** [comment]
Hi @jbalboni, would you know the normalization pattern for the PO Box address?

**Comment by jbalboni** [comment]
@jenniemc Yes, it looks like VA Profile reformats all of them to start with `PO Box`

**Comment by lenaecb** [comment]
@jenniemc - Great demo today! I noticed while you were demo that we need to make sure to update the copy for the alert. We actually removed the "24 hr" time limit because we think it actually could be more than 24 hours. 

So the alert should look like this:
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/02b5ef4a-4912-41a4-94a9-33638ea98bfc)

Just wanted to point this out before we commit to staging. Thanks!
