### ISSUE TITLE
UX | Design for included steps of a form creation (Default steps)

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#98528]
## Description
This design issue is to mock up how the screens might look after a user of the tool has successfully started a form. It would include all of the essential steps as associated with a complete form. 

These steps include:

- Introduction page
- Your personal information
- Address information
- Contact information
- Review and sign
- Confirmation page

## Tasks 
- [x] Wireframe out initial screens and options 
- [x] Share either wireframes or prototypes as necessary to get necessary feedback and input from team/stakeholders
- [x] Align with team's feasibility 

## Acceptance Criteria
- [x] Feedback collected
- [x] Feedback implemented in (link: [Figma file](https://www.figma.com/design/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?node-id=4325-140139))
- [x] Team has reviewed and discussed item
- [x] PM approves of designs

**Comment by brian-wilke** [comment]
This task was added to support the epic about default added steps. 

After review by PM (@Karak888 ) this ticket can be closed if there are no further edits required.

**Comment by brian-wilke** [comment]
Awaiting review, so moved to Review state
