### ISSUE TITLE
5103 and claim certification: Deploy to staging

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#98523]
After staging review is complete for submission experience feature, deploy 5103 and claim certification changes to staging

## Tasks
- [x] Update util to allow changes to display on staging
- [x] Updates to tests as needed

## Acceptance criteria 
- [x] 5103 and claims certification changes display on local, dev and staging
- [x] changes do not display on prod

**Comment by christinec-fftc** [comment]
Found an issue when testing on staging. Reopening to revert for now.
