### ISSUE TITLE
HLR | Remove static page call to action

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#98550]
## Value Statement

**_As a_** member of the Decision Reviews team
**_I want to_** remove unused code
**_So that_** we have less code to maintain

---

## Background Context

While evaluating if the Higher-Level Review CTA needs to be updated, we [messaged the public websites team](https://dsva.slack.com/archives/C52CL1PKQ/p1733496776695149) and together determined that the CTA is no longer being used. So we can remove this code.

## Tasks

- [ ] Remove HLR from the static-pages CTA widget
- [ ] Remove unit tests, if applicable

## Acceptance Criteria

- [ ] HLR CTA removed
- [ ] All tests passing

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Work complete
