### ISSUE TITLE
[Bug] Fix proxy add

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#9856]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Intent to file process:
- After a user selects "file a disability", the FE makes a GET request to `/v0/intent_to_file`. 
- The intent to file controller contains a before action `before_action { authorize :evss, :access_form526? }`.
- That [`access_form526` evss policy](https://github.com/department-of-veterans-affairs/vets-api/blob/72529e6b63465b2753a54c315bf0566807397827/app/policies/evss_policy.rb#L22) checks that all of the following user attributes are present: edipi, ssn, birls_id, and participant_id.  
- Users failing this check are shown an error (the [swagger docs say 401](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/getIntentToFile), but I could have sworn it was a 403) and are unable to proceed to the form.

However, this is before_action is unfairly gating users who are only missing a birls_id and participant_id, users we are supposed to be helping by making a proxy add call to MVI.  We instead only call MVI during the get request to `/v0/in_progress_forms` which occurs _after_ this intent to call step is successful.

---
## Tasks
- [ ] Users missing birls_id and participant_id are able to file an intent to file and continue on to form 526

## Acceptance Criteria
- [ ] We should see an increase in proxy add calls in grafana chart [Add person Requests Rate](http://grafana.vfs.va.gov/d/000000062/mvi?panelId=16&fullscreen&orgId=1&from=now-7d&to=now).
- [ ] We should see a decrease in 401/403 responses for intent_to_files actions in grafana chart [403- Forbidden, 422- unprocessable by action](http://grafana.vfs.va.gov/d/000000056/evss-pundit-authorization?panelId=6&fullscreen&orgId=1&from=now-7d&to=now)
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SarahJaine** [comment]
Work in https://github.com/department-of-veterans-affairs/vets-api/compare/sj-itf-proxy-add

**Comment by SarahJaine** [comment]
@luke-gcio After looking around at the intent to file endpoints, and talking to Robin, it's clear that our current work flow does not allow the BE to differentiate between GET intent-to-file requests coming from the disability compensation flow, and those requests to the same endpoint coming from other places in the application. So, unlike the in progress forms endpoint, we can't check that someone is completing form 526 before doing the proxy add.  Can you talk to Andrea or MVI and determine if this is going to be problematic for our stakeholders? If MVI isn't okay with this we have a number of options available but they're all more involved.  For example, we could version the GET intent to file endpoint to require a form id param, or we could create a new endpoint for the FE to call that requires a form id.
