### ISSUE TITLE
PCIU Replacement Step 4a: Fix AddressValidation Bugs

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#98561]
## User Story
As a developer, I want to fix AddressValiation, so that the Contact Information Service upgrade is complete.

## Issue Description
The AddressValidation feature is encountering issues in the staging environment. These bugs are impacting functionality and causing unexpected behavior during the address verification process. This ticket is to identify, debug, and resolve these issues to ensure proper performance and reliability.

## Tasks
- [x] Reproduce the issues locally to understand their root causes.
- [x] Implement necessary fixes in the AddressValidation logic or API integration.
- [x] Test thoroughly to confirm the resolution of the bugs.

## Acceptance Criteria
- [x]  AddressValidation does not have any errors.
- [ ] Testing is complete and the mobile migration can kick off https://github.com/department-of-veterans-affairs/va.gov-team/issues/97889

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note**: This ticket needs to be injected into Sprint 16. This bug was identified as a part of the review process during Sprint 15 for [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18729).

**Comment by AshleyGuerrant** [comment]
As mentioned in a Slack thread, this bug fix is in progress and I am updating the status.

**Comment by AshleyGuerrant** [comment]
**Standup note:** working on resolving some flaky tests, the PR should be up shortly.

**Comment by RachalCassity** [comment]
Fixed two more bugs found during local testing. Waiting to test in staging
