### ISSUE TITLE
[BE,QA] 10-10CG - Notifications: Set up VA Notify Callback integration for Submission Failure email

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#98587]
## Benefit to the Veteran
As a Veteran/Caregiver, I want to be notified in some way that my application submission has failed, so that I can make corrective actions to resubmit.

## Scope
As part of the Zero silent failures initiative, we must ensure that any part of the 10-10CG process from starting the application to successful submission and processing downstream is accounted for where ever there is a fatal error and the Veteran/Caregiver is not notified.  For this work, we want to set up Delivery Status callbacks from VA Notify so we can track anytime that a submission failure email fails to send to the Veteran/Caregiver.  This way, we can capture Veteran/Caregiver data and ensure they are contacted through our existing escalation process.

### Reference
- [VA Notify Callback integration document](https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/va_notify#va-notify-callback-integration-guide-for-vets-api)
- [Logging Silent Failures guidance](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/274bea7fb835e51626259ac16b32c33ab0b2088a/platform/practices/zero-silent-failures/logging-silent-failures.md#logging-silent-failures)

## Tasks
- [x] Review the VA Notify Callback integration document for guidance
- [x] Implement the setup for the 10-10CG Submission Failure email
     - Document how the team will be notified of the issue (Datadog?)
     - Consider in the event of multiple failures, how will we be able to tell which email send failed?  What identifying data will we have?
- [ ] Create a new monitor (and logs?) in Datadog to track the email send failures
- [x] Complete QA testing as needed to ensure the functionality of the callback in the event of an email send failure
- [x] Update backend tests as needed
- [x] Review with PM prior to launch
     - Signoff required in the comments
- [x] Launch to production

## Acceptance Criteria
- We now have a process in place to monitor, track and remediate any email send failures

**Comment by coope93** [comment]
This was deployed and turned on earlier this week as part of [this work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95342). The only piece of this ticket we need to wrap up is finalizing the monitor in datadog https://vagov.ddog-gov.com/monitors/307366

**Comment by hdjustice** [comment]
Monitor is unmuted and pointed to PROD environment.
