### ISSUE TITLE
[CAIA Intake] Sitewide Facilities: Facility locator error states, copy review

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#98598]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) shared services team. Feel free to delete instructions and unselected options from the ticket to make it easier to scan.

## Your team

- **Product name:** Facility Locator
- **Team name**: Sitewide Facilities
- **OCTO product owner:** Michelle Middaugh
- **Product manager:**  @Agile6MSkinner 
- **Designer(s):** @thejordanwood 
- **Slack channel:** #sitewide-facilities 
- **Dedicated content writer on your team (if you have one):** N/A
- **Dedicated a11y specialist on your team (if you have one):** @laflannery 

## CAIA specialists involved
_Filled out by CAIA_
- **IA:** 
- **Content:** 
- **Accessibility:** 
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [x] Something else:  Copy review of error state messaging in the Facility Locator

### What's the nature of your initiative and desired outcomes?
`Tell us briefly about your work and the outcomes you’re aiming to achieve.`

We have a variety of active projects underway to iterate the Facility Locator. In the process, we identified that error messaging and empty states need updates. Due the importance / usage of this tool, and lack of a dedicated copywriter on our team, we'd love CAIA's help to review / sign off on the proposed copy. 

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content. FOR FIGMA/MURAL: please tell us which screens/board/section to look at so we don't leave comments on old stuff. 
- Sharepoint doc: https://dvagov.sharepoint.com/:w:/r/sites/SitewideFacilitiesTeam/_layouts/15/Doc.aspx?sourcedoc=%7B16133e45-c971-4bb2-870e-4ff3ef968601%7D&action=editnew
- New copy draft is in the body of this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17388

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

We've generated designs, and will implement these error messages once they're approved, but they're not currently blocking any work.

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [x]  No

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [x] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide a link to your Collaboration Cycle Request:
- **Hyperlinked Ticket Number:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/61610

## Next steps
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- N/A -  **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- N/A - **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- N/A - **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- N/A - **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).
- [ ] Please don't close this intake when work is complete - CAIA will close and track

**Comment by jilladams** [comment]
Sharepoint doc has been shared with a Sharepoint team "Sitewide CAIA members" but let us know if more folks need access .

**Comment by aprocik1** [comment]
@jilladams, thanks for submitting this intake ticket. @megzehn and Triana (who's not yet in GitHub) are going to work on this together. Since Triana is still getting access to VA systems, we'll be working in [this Google document](https://docs.google.com/document/d/1zRbvGpmShiFnkJfP9Eo8gUnTE0-08C17MM5CPQEaWx8/edit?usp=sharing). Can we share our recommendations with you in that Google document? Or, would you like us to copy comments and suggested edits into your SharePoint document?

**Comment by jilladams** [comment]
Google works fine for us! Thanks.

**Comment by aprocik1** [comment]
@jilladams, Triana added her content recommendations in [this Google document](https://docs.google.com/document/d/1zRbvGpmShiFnkJfP9Eo8gUnTE0-08C17MM5CPQEaWx8/edit?usp=sharing). @megzehn can help answer questions and finalize recommendations, as needed. Thanks!

**Comment by jilladams** [comment]
Thanks! Jordan will work on implementing the updates in our next sprint, and can ask questions in Slack as they pop up, if that works for you. Feel free to close this ticket if you like.

**Comment by aprocik1** [comment]
That works! Lets keep this ticket open until after your next sprint, so we can finalize this content. Thanks for your collaboration on this!

**Comment by mnorthuis** [comment]
@jilladams Can you confirm if the work on this ticket is complete?

**Comment by jilladams** [comment]
Yep - we got the updates we needed from Content folks, and incorporated those into our designs in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14167. This can close. (Closing.)
