### ISSUE TITLE
[DESIGN] Identify and create Referrals and requests page error states

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#98625]
## Background 
We need to account for all alert scenarios for the Referrals and requests page, based on what currently happens for alerts on the Pending page + new scenarios with referrals. 

_Note: Engineers may be able to see what errors exist now in the pending page ([thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1733522123009529?thread_ts=1733502320.649029&cid=C02GXKL8WM6))_

Need to account for: 
- API call failures for referrals
- API call failures for active requests
- API call failures for active requests
- Any other scenarios with alerts we might be missing

## Tasks
- [x] Identify all alerts needed for the referrals and requests page
- [x] Create wireframes for all alert scenarios
- [x] Share wireframes with engineering (John and Brian)

## AC
- [x] All needed alerts identified and documented
- [x] Wireframes created for all alert scenarios
- [x] Wireframes shared with engineering (John W. and Brian S.)

## Deliverables
- [x] [Design link](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=6486-11787&t=cRlHbdyPKml57h8j-1)

**Comment by cgednalske** [comment]
@Cieramaddox here's the ticket for the alert work! Let me know if it shows up on your board (probably in unassigned or something - for us it will appear in backlog)

**Comment by cgednalske** [comment]
@loripusey this is a ticket for Community Care UX work, but @Cieramaddox will be handling it, so not sure if/how we need to document it for our next sprint

**Comment by cgednalske** [comment]
@Cieramaddox finished up the error states and added them to our [MVP page](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=6750-8118&t=xpHpHDyqDtsqhwrY-1) 🎉 

@brianseek, since John is out, could you take a look when you have a chance and let us know if you have any questions, or if there are any scenarios you know of that aren't included?

**Comment by brianseek** [comment]
@cgednalske The errors for referrals and requests look good to me

**Comment by cgednalske** [comment]
@brianseek excellent, thanks for taking a look! @Cieramaddox closing this out

cc @loripusey I believe John will need a ticket for this but not sure if there's already one out there. 👀
