### ISSUE TITLE
[UX] Create notification wireframe & content for async failure response

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#98624]
Based on the results of [Create Wireframe & Content for Asynchronous Appt Scheduling Notification ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96418), we need to setup a draft (or drafts, if multiple types are needed) of the Community Care notification content to pass on to VeText/VA Notify.

## Task
- [x] Create notification wireframe and content
- [x] Submit to Laura W. for review
- [x] Share in CC SoS
- [x] Ask Kristen who will do the implementation; VeText or CIE?

## AC
- [x] Wireframe and content created
- [x] Content submitted to Laura W.
- [x] Shared with CC SoS

**Comment by cgednalske** [comment]
@loripusey here's a ticket for drafting the CC async notification, which was not part of the userflow/design work Steve and Ciera have been working on.
cc @StevenStraily feel free to make changes!

**Comment by StevenStraily** [comment]
I produced a [first draft of the content and wireframes in Figma](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=6630-29062&t=Oi6XSvr1DY46KsPU-4) to start preparing us to implement these. According to our last conversation, Kristen let us know we would need to work with both VANotify and VetText on this. I'm not sure if we have filled out the [VA Notify Intake Ticket](https://github.com/department-of-Veterans-affairs/va.gov-team/issues/new?assignees=christy-tongty%2C+mjones-oddball%2C+GitSamJennings&labels=vanotify-intake&template=VANotify-Business-Intake.md&title=Business+intake+form+for+%5BBusiness+or+team%5D) for the folks on the team who need access, will follow up on that this week.

There are still a significant number of questions to answer, though. I have added this to the next CC agenda to discuss it there. We also need CAIA feedback, so I scheduled a message to go out to Laura when she returns from OOO. I will keep looking for answers from folks who are available over the holiday period and make adjustments as needed.

Here are the major outstanding things we need to resolve before going live with this:

- Should we use the standard approach for async communication that forms use (submitted, received, and error emails/texts), or should we omit the submitted email in lieu of what should be a shorter response time?
- Can we carry over information from our appointment details card to the email, and is there enough value to justify it?
- Should we consider conditionally using the "On VA.gov" language when they come from VA.gov if that is possible? (I'm not currently sure this even happens myself, I don't know enough yet.)
- What timeframe should we put on the "submitted" email if we decide to use it?
- What call center or contact numbers should we give users at these different touchpoints?
- How will we ensure folks get these communications, considering everything is opt-in at the moment?
- How should we handle the "Next steps" part of ZSF guidance, and what can we include to provide value there?

I have thought about all of this, and most of my recommendations are in Figma comments and/or already implemented in the wireframes for now. These questions are big enough that they should be surfaced to the entire team for feedback, though, so I wanted to document them here.

**Comment by loripusey** [comment]
To my knowledge, we have not created an intake ticket. Also, I don't know if we created an intake ticket for the initial notification. @StevenStraily can you check with @cgednalske on these and create the intake tickets if they have not already been created?
Send me the links to them and I'll touch base with @jwowk on their timeline.

**Comment by outerpress** [comment]
@StevenStraily I think @laurwill will be able to answer a lot of these - she's been doing a lot of appointment notification work. (Also FYI @JamieRamsay for your upcoming appointment notification research.)

My thoughts on a couple of your questions:

> Can we carry over information from our appointment details card to the email, and is there enough value to justify it?

There are definite PHI/PII concerns here. Laura should be able to give you an idea of what is and isn't allowable.

> Should we consider conditionally using the "On VA.gov" language when they come from VA.gov if that is possible?

I think you could omit this. VA.gov (the newer health portal) is the only portal where Veterans can schedule these appointments and most others (Cerner has a very limited portal for scheduling Food and Nutrition and PT appts).

> What call center or contact numbers should we give users at these different touchpoints?

I wouldn't include the provider number until the appointment has been scheduled - though any number _might_ be a PHI concern, if someone could ascertain that you're going to an oncology clinic for example, based on the phone number in the email.

**Comment by cgednalske** [comment]
@StevenStraily @loripusey here's the [original intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92356#issuecomment-2419978192) for VA Notify/VeText regarding initial CC notification (prompt to schedule). Since, I believe things had mostly shifted to Stephen guiding those discussions, so more recent discussions might be documented better in our SoS canvas or elsewhere. We definitely don't have one for this particular notification yet though.

**Comment by loripusey** [comment]
@StevenStraily @cgednalske has a privacy officer approved this content?

**Comment by loripusey** [comment]
I created a [new intake form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99715) for this async notification. I think in January they will start doing kick offs for new tickets.
