### ISSUE TITLE
[BE] 10-10EZ - BUGs: Investigate >5% Monitor alert from the weekend

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#98635]
## Background
Early on Saturday morning (around 4am ET on 12/7), the monitor `1010EZ controller error rate is above 5%` was triggered.  It remained until 7am ET.  The Watchtower also noticed and created a [ticket #375](https://github.com/department-of-veterans-affairs/octo_watchofficer/issues/375) for our team to address the issue and provide details of the cause.

## Tasks
- [x] Investigate issue causing the monitor to send an alert to our APM channel
- [x] Determine root cause
- [x] Provide details to complete the Watchtower ticket request for information
- [x] Determine if there is any action needed

## Acceptance Criteria
- The issue that caused the alert has been investigated and details have been provided in the watchtower ticket

**Comment by coope93** [comment]
See notes mentioned on [this issue](https://github.com/department-of-veterans-affairs/octo_watchofficer/issues/375#issuecomment-2528266129). I think adding some additional logging around when the schema fails validation for 10-10EZ could be helpful, since that would give us more info on what went wrong for future similar cases. I think this one was due to invalid data from the VA Profile, so we may want to consider what the Veteran experience should look like when something like this happens and how we can make it better.

**Comment by hdjustice** [comment]
Completely agree.  Something on the profile should not stop a submission from a Veteran.  Do we want to use this ticket for adding the logging or do you want a new one?  
I can edit/create either way

**Comment by coope93** [comment]
@hdjustice I'd say create a new ticket since this one was really the discovery. I'm not sure where adding the logging fits as far as priorities vs this one to investigate seemed higher priority at the moment.

**Comment by hdjustice** [comment]
created ticket #98666 
Marked for refinement
