### ISSUE TITLE
Screen Shots for k15t - Disappearing Pages

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#98639]
## Issue Description
Per the following email, we need to send k15t screen shots of the problem we are having with disappearing pages during deployment:
Hi Joe,

Thanks a lot for reaching out.

I’m very sorry for the problem. Pages should not disappear if you don’t edit them and it’s technically unlikely that it’s because you didn’t edit them that they aren’t showing up.

To investigate what the problem really is, could you:

send me a screenshot of the missing page in Confluence (with the space sidebar visible)?
On the missing page in Confluence, click ‘Scroll Viewport’ right under the page title and take a screenshot of that?
tell me if the missing page(s) appear if you trigger a full site generation? To trigger a full site generation:
Open the site details screen
Hold the keys control + shift + g for 10 seconds
Open the ••• menu (next to the ‘update site’ button)
Click ‘Generate site from scratch’ (last menu item)
Please let me know how you go.

---
## Tasks
- [ ] Create screenshots and follow instructions above
- [ ] email evidence to k15t

## Acceptance Criteria
- [ ] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
pulled into this sprint due to recurring issue
