### ISSUE TITLE
Create Schema.org COVID-19 special announcement content

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#9863]
## Issue Description
Need to create content to appear in the Schema.org COVID-19 special announcement.
---
## Tasks
- [x] Create draft content
- [x] Incorporate internal feedback
- [x] Get final go-ahead/approvals

## Acceptance Criteria
- [x] Content is finalized and handed off to engineering for implementation
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @johnhashva @ncksllvn. Let me know what you think of the attached. I've just created a simple Word doc for now, but can put it into the template doc if needed. Thanks!

[Coronavirus schema.org content 6.4.20](https://app.zenhub.com/files/133843125/4b7ccb5b-f477-47b8-b2bc-04c75bca5d06/download)

**Comment by johnhashva** [comment]
@DanielleThierryUSDSVA this looks super solid to me.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @johnhashva! I'm just going to run this draft by Lauren to make sure we're okay to move forward. Will post when I have the okay. Thanks!

**Comment by johnhashva** [comment]
6/12 Update: @ncksllvn and @stephorkandatx  -- word just received from @DanielleThierryUSDSVA that Lauren has approved the content for the FAQs.

**Comment by DanielleThierryUSDSVA** [comment]
@stephorkandatx This is complete; closing. Thanks!
