### ISSUE TITLE
Covid-19 screening tool: Support/manage dynamic question content: Sprint 23

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#9864]
# User story

As a leader at a VA VISN or health facility, I want to use the COVID-19 screening tool while meeting the specific question needs of my VISN or facility.

## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ongoing] Work with stakeholders at different VISNs to discuss and coordinate customization of screening questions
- [ongoing] Work on an interim solution for managing dynamic content in GitHub
- [ongoing] Work with CMS team to discuss/determine capabilities to manage dynamic questions in Drupal 

## Acceptance Criteria
- [ ] We'll continue to have ongoing relationships with VISNs/facilities across the country while managing content dynamically
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by stephorkandatx** [comment]
Pull out of the sprint commitments
