### ISSUE TITLE
Engine BE Misc: General cleanup

### ISSUE THREAD

**Issue by kayline** [department-of-veterans-affairs/va.gov-team#98657]
## Value Statement

**_As a_** backend dev

**_I want to_** use as little shared code in the engine as possible

**_So that_** our code is clean and isolated from other teams' changes

---

## Background Context

- Cleanup that wasn't necessary for the main stories but would be good to get done

## Tasks

- [ ] Duplicate or remove shared test helpers
- [ ] Cleanup namespacing in `lib` files
- [ ] TBD

## Dependencies 

- Wait until background jobs and controllers are duplicated

## Acceptance Criteria

- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Out of scope

- Add here

## Open questions

- Add here

## Designs and Build Notes

- Add here

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

### Enablement team (if needed)
@ member of team

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by shaunburdick** [comment]
Created separate stories for the items. Can close.
