### ISSUE TITLE
[SPIKE] Evaluate current pending appointments empty state logic

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#98654]
We need to work with @wullaski to determine if the empty state appointment language/contents need to change at all based on some of the intricate logic that currently exists. 

## Tasks

- [x] Sync with John to understand the empty state logic for the various fields
- [x] Determine if changes are needed to our current content

## AC
- [x] Synced with John to understand the empty state logic for the various fields
- [x] Decision made for if changes are needed for our current Referrals and requests empty states

**Comment by cgednalske** [comment]
@Cieramaddox John brought up some possible concerns with how Pending empty states are now that we should look into separately, mostly because it sounds like there's a bunch of logic around which states are displayed when that he think a lot of thought went into. We should evaluate if we should stick to the existing logic or not. 

@wullaski feel free to add info to this ticket!

**Comment by cgednalske** [comment]
Already synced async and resolved this based on new info from John 🎉  We'll be going with our new CC-based content. 

@loripusey can I close this or should I wait until tomorrow when it's moved into current sprint?
