### ISSUE TITLE
User feedback - Roll-up 2024 Medallia Data

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#98672]
## Task description

Roll up 2024 user feedback into monthly trends for presentation to OCTO and IVC

## Tasks

- [x] Collect all 2024 user feedback data
- [x] Decide how to roll up CSAT data
- [x] Finish data synthesis
- [x] Finalize charts
- [x] Finalize recommendations
- [x] Finalize presentation

## AC

- [x] Complete user feedback rollup spreadsheet
- [x] Complete presentation deck

## Deliverables

[Presentation ](https://dvagov.sharepoint.com/:p:/r/sites/HealthApartment/Shared%20Documents/Appointments/User%20Feedback/Analysis/2024%20Analysis%20Archive/Medallia%20Feedback%202024.pptx?d=w53c22ff6151547db827bcef72adcd139&csf=1&web=1&e=Kq7CdR&nav=eyJzSWQiOjMzMywiY0lkIjozNTExOTA1MTk0fQ)(Sharepoint - starts on Slide 2)

**Comment by outerpress** [comment]
FYI @department-of-veterans-affairs/uae-ux @anita-halici I'm pulling this into Sprint 26. Let me know if you have any questions. I pointed it based on the remaining work.

**Comment by outerpress** [comment]
Passed this over to OCTO for review. Will open a new ticket if feedback comes through
