### ISSUE TITLE
Extend Vets::Model with secondary Common::Base functionality

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#98688]
In order to replace Common::Base with Vets::Model the following "features" from Common::Base need to be added:

## Tasks
- [x] Pagination
- [x] Sorting
- [x] Filtering
- [x] Attribute change tracking (ie changed?)

## Epic 

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92296

## Acceptance Criteria
- [x] An attribute can has the options for sorting & filtering
- [x] A model has the capability of pagination
- [x] A model can track if it's attribute values have changed since instantiation (similar to dirty model)

Example for attribute options:

```
  attribute :recipient_name, String, filterable: %w[eq not_eq match], sortable: { order: 'ASC' }
```

**Comment by stevenjcumming** [comment]
I'm updating the points from a 3 to a 5... This is more complex than I realized

**Comment by stevenjcumming** [comment]
Sortable has been separated from the attribute
