### ISSUE TITLE
Extend Vets::Model with value "coercion" functionality

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#98687]
In order to replace Virtus and Common::Base with Vets::Model the values will need to be coerced to the intended class

For example: strings will need to be coerced into integers  

```
model = ExampleModel.new(id: '123') 
model.id 
#=> 123
````

## Tasks
- [ ] Create a list of values that are "coercible" 
- [ ] Implement the list above in Vets::Model attributes

## Acceptance Criteria
- [ ] Values are coercible
- [ ] A list of coercible values is provided in vets as a readme.md

**Comment by stevenjcumming** [comment]
this is being sent to the backlog to prioritize the preview-environment related tickets

**Comment by stevenjcumming** [comment]
I noticed a business logic mistake and I'm working to correct it, but I think it will be correct by 12/20/23
