### ISSUE TITLE
Move the Representative Status Widget code to the /platform folder

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#98695]
## Background
The ARM team’s [Representative Status Widget](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/static-pages/representative-status) was designed to be placed on any page on [VA.gov](http://va.gov/). We currently include it in several of our other apps ([Find](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/representative-search) and [Appoint](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/representative-appoint)). This counts as a cross-app-import and will not be compliant with the Front-end deployment pipeline changes for vets-website.

To become compliant, the recommended action is to move the Representative Status Widget code out of /applications and into the /platform folder which is the desired directory for shared code.

## Tasks
- [ ] Move the Representative Status Widget code out of /applications and into the /platform folder.

## Acceptance Criteria
- [ ] The Representative Status Widget code has been moved from /applications to /platform.
- [ ] The widget is properly rendering on Find a Representative, Appoint a Representative (intro page) and our landing page.
