### ISSUE TITLE
Full Accessibility & 508 Office Audit GIBCT Sec. 103 Update

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9870]
## Steps to complete the Full Accessibility & 508 Audit: 
- [x] Product Manager: create issue and fill in feature name in the title and other bolded information appropriately
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts when you request a full review_
- Access information for the tool or feature in staging:
    - Example where institution is subject to 103, but no data is currently available in the CT: https://staging.va.gov/gi-bill-comparison-tool/profile/11929140
    - Example where institution is subject to 103 and info is available in the CT: https://staging.va.gov/gi-bill-comparison-tool/profile/31002227
    - Example where institution is not subject to 103: https://staging.va.gov/gi-bill-comparison-tool/profile/249J8143

- Link to your accessibility test plan:
  - **TestRail** [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/runs/view/409&group_by=cases:section_id&group_id=46&group_order=asc)

## Additional Notes
As part of this review, VSP will send your product to VA's 508 office for approval (as applicable)

**Comment by 1Copenut** [comment]
@desireeturner I found no additional issues for the Section 103 audit. I'll go ahead and contact the VA 508 office now and let them know this feature is ready for review. I'll be unavailable next week, so will follow up with you about any findings the following week. Thank you.

**Comment by 1Copenut** [comment]
@desireeturner Please feel free to close this one at your convenience. The only issue returned from the 508 office has been remediated to the best of our abilities.
