### ISSUE TITLE
Wrap up logistics of research studies

### ISSUE THREAD

**Issue by pammicmac** [department-of-veterans-affairs/va.gov-team#98726]
## Issue Description
Logistical tasks related to wrapping up the TE Research Studies
- Task from 12/9/24's [TE Research Synthesis + Reporting Plan workshop](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1733757532127/aecf9ed92865453c056528c6216a2c0a451ced45)
- @evelynhilbrichdavis volunteered to lead
- @conchette interested in pairing

---
## Tasks
- [x] Review recordings we missed
- [x] Finalize recruitment for equity sheet (to be included in Presentation Deck)
- [x] Upload recordings to Sharepoint @evelynhilbrichdavis 

## Acceptance Criteria
- [x] Artifacts are in the appropriate resting places
- [x] Determine when recordings should be deleted 
- [ ] @conchette to create follow up ticket to delete recordings on decided date
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by evelynhilbrichdavis** [comment]
Asked Shannon if 12/31/25 works for deleting the recordings[ in this slack thread. ](https://dsva.slack.com/archives/C053UDWMH7U/p1734127698756839
)

**Comment by evelynhilbrichdavis** [comment]
Recordings should be deleted 1/31/25. @conchette to make a ticket and ensure they are deleted from the Sharepoint folder.

**Comment by evelynhilbrichdavis** [comment]
@mayacarrolluxa6 here is the completed VA Recruitment tracker for the deck: https://docs.google.com/spreadsheets/d/1JK-3FVbUdragHNUEsfmqHXmBae6pOBG12tdyxDa2bOQ/edit?gid=728155694#gid=728155694

**Comment by evelynhilbrichdavis** [comment]
@conchette here is the ticket you can use to delete the recordings. I also recommend you put it on your calendar! https://github.com/department-of-veterans-affairs/va.gov-team/issues/99323
