### ISSUE TITLE
Draft a plan for a Front End Performance Improvements Initiative

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#98731]
Draft a plan in confluence that covers our upcoming initiative to improve Frontend performance across VA.gov.

## Tasks
- [x] Create a confluence page to cover the initiative.
- [x] List out all performance metrics we already have tracked
- [x] List out any metrics we want to start tracking.
- [x] List out any other factors that may need to be considered in this effort (CMS next build, for example).
- [x] Make a plan to accomplish these tasks.

## Acceptance Criteria
- [x] A draft confluence plan exists for the front end performance initiative.
- [x] An initiative gh ticket exists to reflect this work

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3688464396/Initiative+Proposal+Improve+Frontend+Performance
