### ISSUE TITLE
UX | Update Step Library to reflect designs for Employment List and loop

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#98748]
## Description
This design issue is to update the Step Library (as a documentation source of truth) to reflect the current and expected states of the Employment List and Loop step. It may also include future variations or concerns.

## Tasks 
- [x] Convert figma screens and capture notes in Mural
- [x] Share Mural updates to get necessary feedback and input from team/stakeholders
- [x] Align with team's feasibility 

## Acceptance Criteria
- [x] Feedback collected and/or incorportated within [Mural] 
- [x] PM has reviewed and approved this work

**Comment by brian-wilke** [comment]
Link in Mural is [here] (https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1731956783059/f34d7fc7b35ba062c2a10b42adc6ab25481a798e?wid=0-1732114528946) , this is the Step Library.

Updated Screen in Figma is [here](https://www.figma.com/design/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?node-id=4746-78649&t=blVG943otvpMoqYw-1)

Awaiting PM sign-off

**Comment by brian-wilke** [comment]
@Karak888 updated both figma and [Step Library](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1731956783059/f34d7fc7b35ba062c2a10b42adc6ab25481a798e?sender=ub5dc086a14b6f943de142963) to reflect what has been built for the "now" version of the tool.

**Comment by brian-wilke** [comment]
Moving to review
