### ISSUE TITLE
GTM redaction of myhealth.va.gov search parameter

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#98753]
### Description
We need to apply data redaction on in GTM for an impacted parameter in myhealth.va.gov. The parameter itself is too long to be applied to Google Analytics's summary feature, so we will be doing this in tag manager.

### Tasks
- [x] Prevent MHV Classic search query parameter -- `_com_liferay_portal_search_web_portlet_SearchPortlet_keywords` -- from being passed to GA using GTM 
- [ ] Confirm exclusion of `_com_liferay_portal_search_web_portlet_SearchPortlet_keywords` from GA

---
### Acceptance Criteria

- [x] `_com_liferay_portal_search_web_portlet_SearchPortlet_keywords` has successfully been prevented (excluded) from passing into GA

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc I found a variable template in GTM called Trim Query that mimics the old UA View setting “Exclude URL query parameters". I used it to exclude the MHV Classic search parameter from page_location and page_referrer 

It looked good in preview mode and the confirmation check will happen Wednesday (after it's been active for a calendar day).

**Comment by johnny-jesensky-adhoc** [comment]
Thanks for the update @jestutt, that sounds good.

As an administrative note, injected this into the current sprint due to priority from some folks at the VA. Going to pull a couple of tickets out to make room for this.

**Comment by johnny-jesensky-adhoc** [comment]
As discussed in SU, redaction seems to be working -- moving to _Done_.

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc  Confirmation of parameter exclusion.

As of 5pm ET 16 Dec, `_com_liferay_portal_search_web_portlet_SearchPortlet_keywords` is no longer appearing in the page URLs for`page_view` events (the only active GA4 event currently in the GTM legacy container). 
<img width="46%" alt="Image" src="https://github.com/user-attachments/assets/625a8d44-348a-4a82-91df-a73f20b5c6e0" />  <img width="46%" alt="Image" src="https://github.com/user-attachments/assets/7175296a-a538-4c8f-9192-30a93bdbb557" />
