### ISSUE TITLE
[CST] Remove alert that tells Veterans a claim has recently been closed

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#98752]
## Background Context

There's currently an alert in CST that shows (we think) when a claim or decision review has been closed "recently" and links the user to that claim/decision review.

This alert is inherited from the older CST design, and it is discordant with the current CST information architecture and design approach. We should consider removing it.

As part of this ticket, we should confirm the behavior of this alert. If we decide we should pursue an alternative design approach, we can do that too. 

Slack thread for context: https://dsva.slack.com/archives/C04KHCT3ZMY/p1733769253960049

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design

Current alert
![Image](https://github.com/user-attachments/assets/dbe50d47-ffb6-4192-94e5-fd25661de2dc)

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Remove the component ClosedClaimMessage
- Remove the test file ClosedClaimMessage.unit.spec.jsx
- remove the logic around when this component appears in YourClaimsPageV2.jsx

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] _Verify the current behavior of this alert (when does it appear)_ - tell skyler
- [ ] _Remove the alert_
- [x] _Identify the CST experience without the alert and decide if it is sufficient or if an alternative design is necessary_ - tell skyler

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _The alert has been removed_

**Comment by skylerschain** [comment]
Current logic: This alert will show up if you have a claim that was closed in the last 30 days or an appeal that has closed in the last 60 days. The alert consists of a list of paragraphs.

Once the claim/appeal has moved out of the 30 or 60 day window it won't show up anymore.

The alert will show up every session if there are claims or appeals that fall within that window. 

If you hit the dismiss button, the alert will go away for that session. But it will return for the next session.
