### ISSUE TITLE
ARP Representative Profile 1.0 Designs

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#98767]
## Background
This is a first version in ARP for a representative user to confirm their contact information in the GCLAWS system. This will be read-only and we plan to add edit functionality in later.

For requirements, please reference the "ARP Profile" section at the top of this document: [2024_12_ARF_contactupdate_secondaryresearch_notes](https://docs.google.com/document/d/1WCrKWqBWXPBy48hxj80eyDpQVcJlee0J4miz7BBipEo/edit?tab=t.0#heading=h.czx2vnxk36n4)

Approach
- Reuse design patterns and components from the va.gov profile, where it makes sense. [Screenshots](https://www.figma.com/design/RbVQnV4eBl2K1Z5xRpZi7H/ARF---Contact-Info-Updating?node-id=987-281926&t=HMVfH30OobOjCOno-1)

## Tasks
- [ ] Initial designs for a Profile section in ARP
- [ ] Share designs with the ARF and ARM teams for feedback (including content from Jen S)
- [ ] Incorporate feedback (including content) into the design

## Acceptance Criteria
- [ ] There is a design for ARP Profile that has been vetted with the team and is ready for development.

**Comment by jfinnerty13** [comment]
**User Story 1**
MVP view only profile: As an accredited representative whose email is successfully linked to OGCs database, I need a way to review my information, so I can ensure its accuracy.

**Requirements 1**
*   Profile will be view only and will reference data points available in the /accredited\_entities\_for\_appoint API, information includes:
*   POA ID: 123456
*   Individual type: VSO, attorney, claims agent
     *   Accredited organizations (VSOs only)
*   First name
     *   Last name
*   Address line 1
     *   Address line 2
     *   Address line 3
     *   City
     *   Country
     *   State/Providence/Region
     *   Postal code
*   Phone number
*   Email
*   OPEN QUESTION: Provide representatives with read only instructions on how to update their information. Will have to work with OGC to get this. Will need Jen S support.

**User Story 2**
MVP view only profile: As an accredited representative whose email is not linked to OGCs database, I need a way to upgrade my account, so I can have access to all of ARPs features.

**Requirements 2**
*   Profile will be view only and show information from identity provider:
     *   First name
     *   Last name
     *   Email
*   OPEN QUESTION: Users need to be provided a way to link their account to OGCs database. Will need Jen S support.

**Comment by eheintzelman** [comment]
[Link to Figma design](https://www.figma.com/design/RbVQnV4eBl2K1Z5xRpZi7H/ARF---Contact-Info-Updating?node-id=1327-185048&t=hhS3z9h3xiE2PHzk-1). The error message for non-linked profile is pulled into another ticket. 

Next steps
- Jen S will review content
