### ISSUE TITLE
Backend Approval sometimes required incorrectly

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#98762]
I've observed two cases where a BE review is required for a PR from Lighthouse (a team exempt from the BE approval requirement).

Example: https://github.com/department-of-veterans-affairs/vets-api/pull/19212

![Image](https://github.com/user-attachments/assets/4f0769c6-c57d-41c3-97d2-2bea2219b64d)

The author of the above pull request suspects it happens when using GitHub's UI to update their branch with the base branch (e.g. master).

## Tasks
- [x] Investigate issue and determine root cause
- [x] Implement and merge a fix for the discovered root cause

## Acceptance Criteria
- [x] Backend Approval is not required for exempt teams (bug is resolved)

## Related

https://github.com/department-of-veterans-affairs/va.gov-team/issues/98744

**Comment by ericboehs** [comment]
This might need a separate ticket pulled out to diagram the flow which should hopefully lower the estimate.

**Comment by rmtolmach** [comment]
Bug was resolved in https://github.com/department-of-veterans-affairs/va.gov-team/issues/111123

**Comment by rmtolmach** [comment]
An edge case related to this label: The `exempt-be-review` label gets added to a PR when backend _does_ actually own one or more files in the PR. The label shouldn't be added b/c it's confusing to the PR author and the person on backend support might ignore the PR and not review it. 

Example PR where we owned all of the files in the PR but `department-of-veterans-affairs/lighthouse-banana-peels` was added as a reviewer so the `exempt-be-review` label was added: https://github.com/department-of-veterans-affairs/vets-api/pull/24940. And here was the support request: https://dsva.slack.com/archives/CBU0KDSB1/p1762279232947339

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note**: this PR is still currently in review but will be closed out tomorrow.

cc @jwoodman5
