### ISSUE TITLE
Implement TokenService class for CCRA referrals service

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#98779]
## User Story
As a developer, I want to implement token authentication for the referral service, so the requests are authenticated.

## Tasks
- [ ] **Token Retrieval and Caching:**  
  - Implement a `get_token` method that uses monitoring to perform a POST request to `config.access_token_url` with appropriate token parameters and headers.
  - Implement a `token` method that retrieves and caches the access token using Rails cache (with keys and TTL defined by configuration).
  - Create a private `parse_token_response` method to extract and validate the access token from the response, raising a `TokenError` if the token is invalid.
  - Implement private helper methods `token_params` and `token_headers` to format the token request properly.

## Known Limitations
- The actual referrals endpoints are not available yet, so all external API calls must be handled via mocks.

## Acceptance Criteria
- [ ] The new base service class for referrals implements token authentication.
- [ ] Mocks are in place for all external API interactions.
- [ ] Unit tests pass, covering token retrieval, caching behavior, and error handling.

**Comment by loripusey** [comment]
@randomsync can you add details

**Comment by randomsync** [comment]
If the ReferralsService extends from UserService (as it should because it requires a fully authenticated user session), the appropriate JWT token is already added to the header of every request being made.

So this ticket will not be needed.

**Comment by carlosfelix2** [comment]
Reopening to use this ticket to add the token authentication portion to the code. This separate effort will keep the service PR smaller. E.g.
```
def token
      Rails.cache.fetch(REDIS_TOKEN_KEY, expires_in: REDIS_TOKEN_TTL) do
        token_response = get_token
        parse_token_response(token_response)
      end
    end

    private

    def parse_token_response(response)
      raise TokenError, 'Invalid token response' if response.body.nil? || response.body['access_token'].blank?

      response.body['access_token']
    end

    def token_params
      URI.encode_www_form({
                            grant_type: config.grant_type,
                            scope: config.scopes,
                            client_assertion_type: config.client_assertion_type,
                            client_assertion: JwtWrapper.new.sign_assertion
                          })
    end

    def token_headers
      { 'Content-Type' => 'application/x-www-form-urlencoded' }
    end

    def patient_id
      @patient_id ||= user.icn
    end

    class TokenError < StandardError; end
    ```

**Comment by loripusey** [comment]
Moving back to backlog
