### ISSUE TITLE
Implement Configuration class

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#98778]
## User Story
As a developer, I want to create a configuration class for Referrals so that we can easily manage and standardize API connections to the referrals service.

## Tasks
- [ ] **Create the `Referrals::Configuration` Class:**  
  - Extend from `Common::Client::Configuration::REST`.
  - Delegate necessary configuration attributes (e.g., `access_token_url`, `api_url`, `base_path`, `grant_type`, `scopes`, `client_assertion_type`) to a `settings` method.
  - The `settings` method should point to the appropriate settings, e.g., `Settings.vaos.referrals` or `Settings.eps.referrals` or `Settings.vaos.eps.referrals` or whatever.
  - Implement a `service_name` method returning a string identifier for the referrals service (e.g., `'Referrals'`, or `'EpsReferrals'`).

- [ ] **Implement Environment-Based Behaviors:**  
  - Create a `mock_enabled?` method that returns `true` when mocks should be enabled (check for `[true, 'true'].include?(settings.mock)`).
  - Configure a Faraday connection using `api_url`, proper headers, and request options.
  - Include middleware for JSON requests/responses, error handling, and support for debugging logs (using conditional logging similar to the EPS example).
  - If mocks are enabled, ensure that a betamocks response is used or VCR cassettes.

- [ ] **Testing and Documentation:**  
  - Write tests to ensure the configuration behaves as expected in both production and mock scenarios.
  - Update any relevant documentation or developer guides to reference the new configuration class and its usage.

### Example Code Reference

For guidance, see the EPS configuration implementation below:

```ruby
# frozen_string_literal: true

module Eps
  class Configuration < Common::Client::Configuration::REST
    delegate :access_token_url, :api_url, :base_path, :grant_type, :scopes, :client_assertion_type, to: :settings

    def settings
      Settings.vaos.eps
    end

    def service_name
      'EPS'
    end

    def mock_enabled?
      [true, 'true'].include?(settings.mock)
    end

    def connection
      Faraday.new(api_url, headers: base_request_headers, request: request_options) do |conn|
        conn.use :breakers
        conn.request :json

        if ENV['VAOS_EPS_DEBUG'] && !Rails.env.production?
          conn.request(:curl, ::Logger.new($stdout), :warn)
          conn.response(:logger, ::Logger.new($stdout), bodies: true)
        end

        conn.response :betamocks if mock_enabled?
        conn.response :json, content_type: /\bjson$/
        conn.response :vaos_errors
        conn.adapter Faraday.default_adapter
      end
    end
  end
end
```

Replace references to `Settings.vaos.eps` and `'EPS'` with their referrals-specific counterparts.

## Known Limitations
- This ticket focuses solely on the configuration class; actual API endpoint implementation and integration will be handled in separate tickets.
- Ensure that any environment variables or settings required for the referrals service are defined and accessible.

## Acceptance Criteria
- [ ] A new configuration class for Referrals is implemented, following the structure of the EPS configuration example.
- [ ] The class correctly delegates configuration settings and sets up the Faraday connection with all required middleware.
- [ ] Unit tests are in place and passing for both production and mock scenarios.
