### ISSUE TITLE
Implement ReferralsService base class

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#98782]
## User Story
As a developer, I want to implement a base service class for the referrals functionality so that we have a standardized way to interact with referrals endpoints (using mocks until the endpoints are ready).

## Tasks
- [ ] **Implement the Base Service Class:**  
  - Create a new base service class. The naming is flexible—you might choose `Referrals::BaseService`, `EPSReferrals::BaseService`, or another name that fits your fancy.
  - Inherit from `VAOS::SessionService` and include `Common::Client::Concerns::Monitoring`.
  - Define necessary constants for metrics and caching (for example, a `STATSD_KEY_PREFIX`, a `REDIS_TOKEN_KEY` based on the relevant `REDIS_CONFIG`, and a `REDIS_TOKEN_TTL`).

- [ ] **Define Core Methods:**  
  - Implement a `headers` method that returns a hash including:
    - `'Authorization'` with the bearer token.
    - `'Content-Type'` set to `'application/json'`.
    - `'X-Request-ID'` sourced from `RequestStore`.
  - Implement a `config` method that memoizes and returns the configuration for referrals (for instance, `Referrals::Configuration.instance` or a similar construct based on your chosen naming).

- [ ] **Mocking External Calls:**  
  - Since the referrals endpoints are not yet available, ensure that mocks are used for all external API calls during development and testing.

### Example Code Reference

For guidance, see the EPS BaseService implementation below (adapt this example for your referrals base service):

```ruby
# frozen_string_literal: true

module Eps
  class BaseService < VAOS::SessionService
    include Common::Client::Concerns::Monitoring

    STATSD_KEY_PREFIX = 'api.eps'
    REDIS_TOKEN_KEY = REDIS_CONFIG[:eps_access_token][:namespace]
    REDIS_TOKEN_TTL = REDIS_CONFIG[:eps_access_token][:each_ttl]

    def headers
      {
        'Authorization' => "Bearer #{token}",
        'Content-Type' => 'application/json',
        'X-Request-ID' => RequestStore.store['request_id']
      }
    end

    def config
      @config ||= Eps::Configuration.instance
    end

    def get_token
      with_monitoring do
        perform(:post,
                config.access_token_url,
                token_params,
                token_headers)
      end
    end

    def token
      Rails.cache.fetch(REDIS_TOKEN_KEY, expires_in: REDIS_TOKEN_TTL) do
        token_response = get_token
        parse_token_response(token_response)
      end
    end

    private

    def parse_token_response(response)
      raise TokenError, 'Invalid token response' if response.body.nil? || response.body['access_token'].blank?

      response.body['access_token']
    end

    def token_params
      URI.encode_www_form({
                            grant_type: config.grant_type,
                            scope: config.scopes,
                            client_assertion_type: config.client_assertion_type,
                            client_assertion: JwtWrapper.new.sign_assertion
                          })
    end

    def token_headers
      { 'Content-Type' => 'application/x-www-form-urlencoded' }
    end

    def patient_id
      @patient_id ||= user.icn
    end

    class TokenError < StandardError; end
  end
end
```

*Note:* Adapt the configuration access (for example, `Settings.vaos.eps` and references to `'EPS'`) to use the appropriate referrals settings according to your chosen naming convention.

## Known Limitations
- The actual referrals endpoints are not available yet, so all external API calls must be handled via mocks.

## Acceptance Criteria
- [ ] The new base service class for referrals is implemented with all specified methods and constants.
- [ ] The class name and module structure allow flexibility (e.g., `Referrals::BaseService`, `EPSReferrals::BaseService`, etc.) and follow project conventions.
- [ ] Mocks are in place for all external API interactions.
- [ ] Unit tests pass, covering token retrieval, caching behavior, and error handling.

**Comment by carlosfelix2** [comment]
This ticket is dependent on external work that may be completed by the end of February.
