### ISSUE TITLE
Determine Perigean registration form updates for CC UAT recruitment

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#98796]
## Background
We need to understand how the current Perigean registration form needs to be updated for our specific CC UAT case.

## Tasks
- [ ] Check what is on current registration form
- [ ] Determine what we need for CC and how that needs to change
- [ ] Check with Perigean that our changes are ok 
- [ ] Submit changes and any further info (dates, etc.) to Perigean

**Comment by outerpress** [comment]
We likely won't be changing Perigean's recruitment questionnaire for this study. We'll create a new ticket if we find out otherwise. Closing this for now
