### ISSUE TITLE
Edit: Consolidate/merge duplicate docs on Continuous Deployment

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#98816]
## Description
On a Slack thread in the #platform-cop-frontend, it was flagged that we have two documents essentially describing the same thing.

1. [Continuous deployment](https://depo-platform-documentation.scrollhelp.site/developer-docs/continuous-deployment#Continuousdeployment-Enablingcontinuousdeployment)
2. [Isolated application builds](https://depo-platform-documentation.scrollhelp.site/developer-docs/isolated-application-builds)

These two pages likely need to be merged, consolidated, or reconciled in some way, to avoid confusion

**Slack Thread:** https://dsva.slack.com/archives/C04868KS69L/p1701290307228389

** Note:
 - This ticket is for editing/combining the pages, based on Discovery ticket [70863](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?pane=issue&itemId=84087782&issue=department-of-veterans-affairs%7Cva.gov-team%7C70863)
 
## Tasks

- [ ] Edit/Combine information into a single page
- [ ] SME Curt Bonade review final edit
- [ ] Prepare for deployment

## Acceptance Criteria
- [ ] Page is ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
[Deployment section of website has been updated](https://depo-platform-documentation.scrollhelp.site/developer-docs/continuous-deployment#Continuousdeployment-Enablingcontinuousdeployment), this ticket is no longer relevant.
