### ISSUE TITLE
UX | Visual design for Employment History List and Loop rendered UI

### ISSUE THREAD

**Issue by gopixelsgo** [department-of-veterans-affairs/va.gov-team#98810]
## Description
This ticket is to be used by the designers working on the Form Builder rendered screens UI. Design the necessary screen outputs for the "Your employers" (Employment History List and Loop) Step.

## Tasks 
- [ ] Update existing Form Builder rendered screens in Figma to correspond to Form Builder Editorial UI sequence and content
- [ ] Socialize screens to receive necessary team and stakeholder feedback
- [ ] Adjust screens based on feedback

## Acceptance Criteria
- [ ] Screens updated in Figma
- [ ] Screens shared, feedback gathered
- [ ] Feedback implemented
- [ ] PM has reviewed and approved

**Comment by Karak888** [comment]
I am going to close this as I believe this has been covered under other existing work.  We can always reopen or open a new ticket as needed.
