### ISSUE TITLE
AAR 2.0 (Digital Submit) User Test - AT Support

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#98826]
## Background
4 days of AT support for screen reader interviews. Will need open availability for up to 4 screen reader users for 1.5 hour sessions, and 1 pilot session.

## Tasks
- [ ] Provide availability for screen reader Veterans. Recommend more open availability if possible.
- [ ] Request CAIA support for pilot session.
- [ ] Conduct pilot session with moderator and CAIA 'user'.
- [ ] Attend 4 Veteran interviews and provide screen reader support. Perigean will provide AT information prior to the sessions.

## Acceptance Criteria
- [ ] All tasks complete.

**Comment by oddball-lindsay** [comment]
We will not be pursuing AT testing for Appoint 2.0
