### ISSUE TITLE
Update govdelivery-tms-ruby activesupport dependency

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#98840]
To update vets-api to Rails 8, we must bump the `activesupport` dependency in [govdelivery-tms-ruby](https://github.com/department-of-veterans-affairs/govdelivery-tms-ruby)

## Tasks
- [x] Bump `activesupport` dependency to <8.1 (and any other linked dependencies, as needed)
- [x] Release new version (4.1.0)

## Acceptance Criteria
- [x] 4.1.0 is released and available to vets-api
