### ISSUE TITLE
Announce Deployment Freeze

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#98844]
## Issue Description
We need to compose and schedule a message alerting teams to our truncated Holiday deployment schedule for December 23 - 31, or at least 12/23 - 27.

### Relevant Links

- [See 2023 Holiday deployment announcement for reference](https://dsva.slack.com/archives/CL181NRJQ/p1703712303411119)

- [Platform Website Holiday Release Freeze Schedule 2024](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies#DeploymentPolicies-Holidayreleasefreezeschedule)

---
## Tasks
- [x] Decide deployment freeze dates 
- [x] Decide deployment assignments 
- [x] Draft announcement using [2023 format](https://dsva.slack.com/archives/CL181NRJQ/p1703712303411119)
- [x] Schedule the announcements in Slack

## Acceptance Criteria
- [x] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Created during sprint due to timely nature of this work + available capacity for this small ticket

**Comment by jknipes** [comment]
All tasks completed, moving to _Done_
