### ISSUE TITLE
Research Confirmation Number implementation

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#98842]
## Background
Other forms experiences have a confirmation number (also known as a UUID) generated upon submission, which helps with monitoring submissions in Datadog and troubleshooting issues with downstream services like Lighthouse and Central Mail. 

The other teams are using the Benefits Intake API to generate this confirmation number -- [documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current).

We'll want to review this documentation and understand how we might include a confirmation number in our Appoint v2 experience. And possibly pass this along with the POA request, so the confirmation number can continue to be referenced as the rep receives and accepts/declines the POA request.  

## Tasks
- [ ] Review existing documentation for the Benefits Intake API
- [ ] Propose a solution for 
   - generating a confirmation number when a Veteran submits a POA request
   - sending the confirmation number with the POA request, to further track activity on the representative side

## Acceptance Criteria
- [ ] We have a clear understanding of how we might implement a confirmation number, to track both the Veteran sending a POA request and the representative accepting/declining a POA request.

**Comment by oddball-lindsay** [comment]
The need for us to generate a confirmation number can be removed from v2 scope - discussions with ARF and Lighthouse point to using:
        1. a record ID in our vets-api database of POA requests (for pending or declined requests)
        2. a UUID from Lighthouse (for accepted requests) - this is what other form experiences rely on for the "confirmation number" concept
Both of these will be generated automatically.
