### ISSUE TITLE
EVSS PCIU Migration Step 5c: VAProfile Prefill data Test Plan Tracking (VFS Teams testing)

### ISSUE THREAD

**Issue by AshleyGuerrant** [department-of-veterans-affairs/va.gov-team#98850]
## User Story
As a developer,
I want to ensure spot checks are completed on a sample set of forms that are owned by specific VFS teams, 
so that PCIU can be replaced with `V2::ContactInformation` for web and mobile integrations.

## Issue Description
There are PCIU migration responsibilities for the VFS teams. Although the Product Team migrated the base classes for VA Profile, certain parts of the codebase are owned exclusively by the VFS teams. It is their responsibility to handle the migration of these specific components.

## Tasks
- [x] #99077 (ticket handed off to team on 1/2/25)
- [x] #99070 (ticket handed off to team on 1/2/25)
- [x] #99071
- [x] #99072 (ticket handed off to team on 12/17/24)
- [x] #99075 (ticket handed off to team on 12/17/24)

## Acceptance Criteria
- [x] Follow-up tickets will be created by/for each individual team and linked to this ticket
- [x] Hand off tickets to the 6 VFS teams with active contracts in this [dedicated Slack channel](https://dsva.slack.com/archives/C085A9JCB1B)
- [x] Work with Erika Washburn to figure out testing coverage for the Authenticated Experience Team, because their contract expired in December '24 & there is no interim team.
- [x] Testing is conducted
- [x] Issues that might arise during testing are fixed

---
### Glossary
- PCIU: Personal Contact Information (update)
- VFS: Veteran-facing Services
- IVC: Integrated Veteran Care

---

```[tasklist]
### Related Testing Tickets
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98925
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/99074
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/97889
```

**Comment by AshleyGuerrant** [comment]
**Discussed during the PCUI sync on 12/12:** today @rmtolmach will write up individual testing tickets for each team listed in the description.

**Comment by AshleyGuerrant** [comment]
All testing has been successfully completed by the VFS Teams & mobile. SRE Team work is now unblocked. Closing out this ticket.
