### ISSUE TITLE
Supply Reordering: Submit form to vets-api

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#98869]
Ticket for writing the form `submit` function. [[example](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/health-care-supply-reordering/config/form.js#L33:L33)]

## User Story

```
N/A
```

## Acceptance Criteria

- [ ] Form submission creates a HTTP request to vets-api
- [ ] Form submission outcome is reflected in UI
- [ ] Form submission function records both successful and unsuccessful results to analytics
- [ ] 

## Tasks

- [ ]
- [ ]

## QA Steps/Instructions

TBD

**Comment by mcarterA6** [comment]
@radavis - please add story points to this ticket when you have a moment.

**Comment by radavis** [comment]
Carryover: 
- 5xx response testing 
- analytics hookup
