### ISSUE TITLE
Facilities: Review error messages

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#98860]
## Description
We need to review the product team's draft content for empty states and error messages for the [facility search tool](https://www.va.gov/find-locations).

## Resources
- [CAIA content source of truth](https://docs.google.com/document/d/1zRbvGpmShiFnkJfP9Eo8gUnTE0-08C17MM5CPQEaWx8/edit?usp=sharing) (Google)--for TK's collaboration
- [Product team content source of truth](https://dvagov.sharepoint.com/:w:/r/sites/SitewideFacilitiesTeam/Shared%20Documents/General/98598%20Facility%20Locator%20error%20states-%20copy%20review.docx?d=w16133e45c9714bb2870e4ff3ef968601&csf=1&web=1&e=PdDq7C) (SharePoint)--the product team confirmed that we can share the Google doc with them instead

## Tasks
- [x] TK: Draft recommendations
- [x] MZ: Review recommendations
- [x] AP: Share recommendations with product team
- [ ] MZ: Finalize recommendations with product team

## Criteria
- [ ] Content recommendations have been shared and finalized with the product team

**Comment by megzehn** [comment]
@aprocik1 shared our [suggested error messages in the intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98598#issuecomment-2551348510).

Closing this!
