### ISSUE TITLE
[Payment History (VHA) (Current Balances only)] Establish Lighthouse API Integration

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#98885]
## Issue Description
Given: We don't have Lighthouse VHA data
When: The developer makes a request      
Then: Data is retrieved. We may need to just get requests running from Lighthouse. There is an API we can play with called Public health api FHIR

## Tasks
- [ ] Get Lighthouse creds for Public health api FHIR
- [ ] Get requests coming back either in Postman or Curl request

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] We are getting data back from Lighthouse either from Public health api FHIR or our endpoint that is getting made

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by HeatherRienks** [comment]
Dependency on Lighthouse Team (contract in flux as of 3/19/25)

**Comment by jtmst** [comment]
This looks to be a duplicate of another ticket thats already being completed:

https://github.com/issues/assigned?q=is%3Aissue+state%3Aclosed+archived%3Afalse+assignee%3A%40me+sort%3Aupdated-desc+&issue=department-of-veterans-affairs%7Cva.gov-team%7C100752

closing this
