### ISSUE TITLE
[Payment History (VHA) (Current Balances only)] Confirm data mapping (BE -> Design)

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#98899]
## Issue Description
Given: The backend code making requests to Lighthouse is merged  
When: When the Frontend makes a request to vets-api
Then: Serialized data is returned to the frontend

## Tasks
- [ ] Create controller or add to existing Copay controller
- [ ] Create vets-api serializer that returns serialized data for copay balances
- [ ] Specs written

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] PR is merged with copay data and FE likes the data contract/shape

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
