### ISSUE TITLE
[Payment History (VHA) (Current Balances only)] Update showing just statement data from new API via Lighthouse

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#98898]
## Issue Description
Given: We have requests working in Postman or Curl
When: Backend adds code
Then: We have code like a service or model that pulls data from Lighthouse

## Tasks
- [ ] Authenticate with Lighthouse if needed
- [ ] See if we need to make special credentials for QA and Prod
- [ ] Code with specs that makes request to Lighthouse

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Item one from the description performs as described in the description
- [ ] Item two from the description performs as described in the description      

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points

**Comment by HeatherRienks** [comment]
This is a dupe!
