### ISSUE TITLE
PCIU Replacement Step 4b: Replace PCIU calls

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#98901]
## Summary

`FormData.initialize_contact_information `prefills contact information with PCIU data.  
Coverband is showing a lot of data. This will have to be tested when migrating to VAProfile. PCIU references, extract_pciu_data, need to be removed.  Draft pull request can be found [here](https://github.com/department-of-veterans-affairs/vets-api/pull/18729).

Ex:

Previous:

```
  def initialize_contact_information
    opt = {}
    opt.merge!(vets360_contact_info_hash) if vet360_contact_info
    opt[:address] ||= user_address_hash
    opt[:email] ||= extract_pciu_data(:pciu_email)
    if opt[:home_phone].nil?
      opt[:home_phone] = pciu_primary_phone
      opt[:us_phone] = pciu_us_phone
    end
    format_for_schema_compatibility(opt)
    FormContactInformation.new(opt)
  end
```

## Next Steps
VFS teams can test their form pre-fills.

## Tasks
- [ ] Ensure initialize_contact_information is returning vet360_contact_info, no longer pciu data
- [ ] Remove initialize_contact_information PCIU calls
- [ ] Ensure all pre-fill form data is using vet360_contact_info data.
- [ ] Ensure forms data is being properly loaded by testing in a local environment.
- [ ] Ensure forms data is being properly loaded by testing in the staging environment.

## Acceptance Criteria
- [ ] VAProfile Contact Information V2 has successfully replaced the EVSS PCIU service for form pre-fill user data.

**Comment by RachalCassity** [comment]
Awaiting PR reviews. Will not be approved until after Christmas.

**Comment by RachalCassity** [comment]
Will merge 12/27 when PR reviewers return from holiday vacation.

**Comment by RachalCassity** [comment]
Fixed suggestions in pull request. Waiting for another review.
