### ISSUE TITLE
Engine BE 5.1: Add logging to old controllers

### ISSUE THREAD

**Issue by kayline** [department-of-veterans-affairs/va.gov-team#98907]
## Value Statement

**_As a_** backend dev

**_I want to_** know who is using our old routes and controllers

**_So that_** I can tell them to use the new ones

---

## Background Context

- This should happen at roughly the same time we swap our own frontend routes to use the engine

## Tasks

- [ ] Add specific logging to old controller methods
- [ ] Create temporary DD dashboard to track any use of the old controllers
- [ ] Coordinate the frontend change to new routes

## Dependencies 

- Add here

## Acceptance Criteria

- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Out of scope

- Add here

## Open questions

- Add here

## Designs and Build Notes

- Add here

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

### Enablement team (if needed)
@ member of team

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by kayline** [comment]
Merged! Waiting for deploy to validate logs in staging

**Comment by kayline** [comment]
DD dashboard now tracking controller calls: https://vagov.ddog-gov.com/dashboard/5h3-pjx-n2m/benefits-decision-review-module-transition?fromUser=true&index=%2A&refresh_mode=sliding&from_ts=1737134076038&to_ts=1737134976038&live=true
