### ISSUE TITLE
[BE] 10-10CG - Facilities: Architecture Intent - Add ability to encrypt/decrypt sensitive query params

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#98904]
## Background
As a result of the Architecture Intent review meeting, we are advised to replace the GET function to something that will ensure URLs do not expose PII.  Our current endpoint for retrieving the facilities list is a GET request where we pass the lat/long as query params in the URL. Because we log the urls, this is exposing what could be PII (the lat/long of a Veteran's address). 

Simply changing GET to POST could be considered an anti-pattern.  There were several ideas discussed in the team's meeting Slack thread, captured in the meeting notes.  A few options were explored and we've decided on implementing the ability to encrypt/decrypt sensitive query params (see comments on ticket [#98100](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98100)).  Adrian Rollett also agreed with this approach in the Slack thread (linked in Resources)

>Add ability to encrypt/decrypt sensitive query params as needed. I took a crack at spiking this out and it is certainly doable. I used RSA encryption with the [WebCrypto api](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) and have [this vets-website spike branch](https://github.com/department-of-veterans-affairs/vets-website/tree/98100-encrypt-query-params) in conjunction with [this vets-api branch to decrypt the params on the backend](https://github.com/department-of-veterans-affairs/vets-api/tree/98100-encrypt-query-params) that is using OpenSSL on the backend to decrypt it. This would take the most work to implement, and would involve new public/private keys and the subsequent configuration of them. One advantage is it could easily be implemented to allow for other teams to use, which could be a big benefit. It would allow us to keep the request as a GET, which would keep the api RESTful.

### Resources
- [Architecture Intent Meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Improve%20Facility%20Selection/Arch%20Intent%20-%20Questions%20&%20Meeting%20Notes.md)
- [Slack thread with the team and Adrian](https://dsva.slack.com/archives/CMJ2V70UV/p1732646603012339)
- [Ticket #98100](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98100)

## Tasks
- [ ] Add ability to encrypt/decrypt sensitive query params
- [ ] Complete testing to validate URLs are not exposing PII
- [ ] Review with the team
     - Signoff required from PM in comments

## Acceptance Criteria
- The new Facilities search pages do not expose PII in the URLs

**Comment by hdjustice** [comment]
Placing this in the Icebox.  The team has decided to follow the initial suggestion from the Architecture Intent review to change the GET to POST.  More in ticket #51980 comments

**Comment by hdjustice** [comment]
Closing this ticket.  The larger changes are not being addressed by platform at this time.  We will engage with them once they decide to prioritize it.
