### ISSUE TITLE
[Payment History (VHA) (Current Balances only)] Remove dummy data for testing

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#98903]
## Issue Description
Given: There is Dummy Data being used and we have live data getting returned in backend code
When: We remove dummy data
Then: Actual Lighthouse data is returned

## Tasks
- [ ] Remove dummy data

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Validate Lighthouse data is returned

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
