### ISSUE TITLE
PCIU Replacement Step 5a: VAProfile Contact Information V2 Testing (Authenticated Experience Team)

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#98925]
For the PCIU migration, the Platform Product Team changed the data source for ContactInformation to call VA Profile instead of PCIU. Contact Information contains the following user fields: 
- mailing address
- home address
- home number
- work number
- mobile number
- email

**Follow these steps to test the functionality:**
1. Turn on flipper `va_v3_contact_information_service` [**IN STAGING**](https://staging-api.va.gov/flipper/features)
2. Turn on flipper `remove_pciu` [**IN STAGING**](https://staging-api.va.gov/flipper/features)
3. Turn on flipper `remove_pciu_2` [**IN STAGING**](https://staging-api.va.gov/flipper/features)
4. Login as test user in [staging](https://staging.va.gov/).  Test user judy.morrison@id.me works for local and staging testing.
5. Navigate to the [Contact Information page](https://staging.va.gov/profile/contact-information)

6. **Address Testing** - Update Mailing Address 
<img width="551" alt="Image" src="https://github.com/user-attachments/assets/536afe8c-0385-4bf8-b39b-a72785a02809" />

7. **Address Testing** - Update Home Address 
<img width="448" alt="Image" src="https://github.com/user-attachments/assets/b1f06cdc-54cb-496e-84cb-33ad917fa990" />

8. **Phone Number Testing** - Update Home number 
<img width="312" alt="Image" src="https://github.com/user-attachments/assets/74ff9b43-3b0a-4c45-8222-78017c09c981" />

9. **Phone Number Testing** - Update Work number 
<img width="428" alt="Image" src="https://github.com/user-attachments/assets/29667a82-7c22-473b-9697-b00372fc12b6" />

10. **Phone Number Testing** - Update Mobile number 
<img width="356" alt="Image" src="https://github.com/user-attachments/assets/18ce2b89-0915-4967-994f-76b273dcc3db" />

11. **Email Testing** - Update Contact email 
<img width="337" alt="Image" src="https://github.com/user-attachments/assets/8357b280-ab07-43dd-8822-398cc6f86b21" />

### Tasks
- [ ] Follow the instructions above for testing.
- [ ] If testing is successful, comment and close this issue.
- [ ] If issues are found (or if there are questions) reach out in [#pciu-migration-testing](https://dsva.slack.com/archives/C085A9JCB1B)

**Comment by AshleyGuerrant** [comment]
Blocked pending this https://github.com/department-of-veterans-affairs/vets-api/pull/18729 being merged.

This work essentially serves as a "flood gate" PR where after it is merged, we will be pointing completely to VA Profile Contact Information instead of PCIU.

**Comment by AshleyGuerrant** [comment]
The [key PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18729) has been merged and testing can now kick off at any time.

**Comment by jfinnerty13** [comment]
@RachalCassity we're getting a 'we're not authorized' message in staging for the flipper. Can I get access please? I also submitted a ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/103242

CC'ing @clantosswett

**Comment by RachalCassity** [comment]
@jfinnerty13 All flippers have been enabled. Your team can skip enabling the flippers.

**Comment by andreahewitt-odd** [comment]
@jfinnerty13 Your team will need to follow the correct steps for getting access to flipper and your product in lower environments. [Flipper documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/flipper-ui-access)

**Comment by jfinnerty13** [comment]
@andreahewitt-odd I submitted ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/103242 is there anything else I need to do? Thanks.

**Comment by jfinnerty13** [comment]
@RachalCassity the team was wondering: what should we be looking for/see in the dev tools when we process a transaction so that we know the service is working as expected? Thank you!

**Comment by RachalCassity** [comment]
@jfinnerty13 Do you have access to Datadog logs? You should see successful requests.

**Comment by jfinnerty13** [comment]
Apologies for the delay - we'll be testing today, will keep you posted @AshleyGuerrant if we run into any challenges. Thanks.

**Comment by AshleyGuerrant** [comment]
Sounds great, thank you @jfinnerty13!

**Comment by andrew-t-pearce** [comment]
we have completed our testing. phone numbers and emails checked out. for addresses:

- error triggered when an address with Suite # was entered without the Suite (Street address line 2 (35 character maximum))
- address with only Street address line 1 worked correctly.
- When address was recommended - and we select the one NOT recommended and tell the system to use what we originally intended, system used the recommended one anyway

![Image](https://github.com/user-attachments/assets/a9f8ef8f-0547-4ad6-849b-5af9717a7c06)

![Image](https://github.com/user-attachments/assets/b3a6902b-423f-47e8-84ae-480df28a3444)

**Comment by andrew-t-pearce** [comment]
let us know if anything additional is required of our team for this testing effort

**Comment by RachalCassity** [comment]
Thank you! @AshleyGuerrant This can be closed. 🎉
