### ISSUE TITLE
Phase Two Platform Support Team Board Structure

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#98926]
## Description 
We created our first [Sprint Work board](https://github.com/orgs/department-of-veterans-affairs/projects/813) has been created but we have found a way to help prioritize tickets better by expanding the In Progress section to be specified by ticket type. This mirror's Brandon Dech's board [here](https://github.com/orgs/department-of-veterans-affairs/projects/1560).

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Add three new columns for Support Tckets, New VFS Team/Team Member tickets, and Access Requests. 
- [x] Identify if there are any other ticket types we should be tracking (i.e. AWS requests, off-boarding, etc.) and add a column for each
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
New columns have been created

**Comment by bdech** [comment]
Closing. Working completed.
