### ISSUE TITLE
EVSS PCIU Migration: Step 9 (a): Ensure Contact Infromation V1 references have been removed

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#98928]
## User Story
As a developer, we need to remove all Contact Information V1 references to prevent future services becoming dependent on this outdated service.

## Issue Description
Contact Information has been upgraded to V2. To ensure this service is no longer used in the future, Contact Information V1 should be removed from vets-api.

## Tasks
- [ ] Remove Contact Information references.
- [ ] Remove Contact Information flipper.
- [ ] Replace [app/models/va_profile_redis/](https://github.com/department-of-veterans-affairs/vets-api/tree/master/app/models/va_profile_redis) with files inside [app/models/va_profile_redis/v2 ](https://github.com/department-of-veterans-affairs/vets-api/tree/master/app/models/va_profile_redis/v2). V2 files should replace the existing files.
- [ ] Remove CIV2 spec files
- [ ] Remove CIV2 cassettes

## Success Metrics
No issues with the refactored content information

## Acceptance Criteria
- [ ] Contact Information has been removed from vets-api
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by AshleyGuerrant** [comment]
Blocked pending the work in [Step 5.5](https://github.com/department-of-veterans-affairs/va.gov-team/issues/101375) being complete. Step 5.5 will actually toggle the flipper on, and this ticket will remove the flipper after it has been toggled on.

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note**: This ticket is being ejected from the current sprint, so that a [high-priority ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/118774) for a CSOC finding regarding a potential PII incident can be investigated.

Ejecting the PCIU ticket will not impact the [Monday, 9/8 deadline](https://dsva.slack.com/archives/C03R5SBELQM/p1756388794359209) to remove the flipper that allows PCIU traffic to fall back from VA Profile to EVSS.

**Comment by RachalCassity** [comment]
[Removed Contact Information V1 cassettes in the mobile module](https://github.com/department-of-veterans-affairs/vets-api/pull/24191#top) is up for review
