### ISSUE TITLE
UX | Component list in use within FBEUI (inventory-audit)

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#98962]
**Description** 

Create list of current VADS components in use within the figma design files for the FBEUI. This list is to help the engineering team to understand what items are needed beyond reviewing the files in figma. This should help the engineering team meet the goal of matching the VADS as closely as possible.

**Tasks**

- [x] Setup a table in mural that reflects the components in use within figma. 
- [x] Share the mural location out for feedback on usability/value of this information

**Acceptance Criteria**

- [x] PM and PO agree that this documentation is valuable and correct
- [x] List is shared with the engineering team

**Comment by brian-wilke** [comment]
@Karak888 , I moved this to review as it was published yesterday.

Not sure what else might be needed at this point. If this satisfies this request, we can close it as well.
