### ISSUE TITLE
UX | Update figma prototype to reflect most recent updates in December design decisions

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#98964]
**Description** 

Version the current prototype to match the current approved (December) designs. This will require extensive relinking of figma components within the page and using the correct local figma components in order to provide the highest fidelity possible.

**Tasks**

- [x] Establish new page within the figma project to hold the prototype and flows to show this work
- [x] Update linkages across the prototype to support as many possible user flows 
- [x] Test prototype to track down any errant paths and links
- [x] Share back to team for alignment and informational purposes

**Acceptance Criteria**

- [x] Share to PM the design options being considered
- [x] Share the work to the Test track for collaboration and information
- [x] Share the design recommendation with the PO for information and alignment

**Comment by brian-wilke** [comment]
Even though this is an 8-pointer, starting this half-way through the sprint due to other tickets.

**Comment by brian-wilke** [comment]
Moving back to TO DO so I can finish the employment history step

**Comment by brian-wilke** [comment]
Created additional versions of **Forms** and **Layout** tabs for discussion by the PM/PO as this removes the need for the sidebar. 

Additionally, the sidebar would only be necessary to facilitate non-linear navigation during the content add/edit stages of form creation.
