### ISSUE TITLE
CC - Run Test Cases for Functional Testing

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#98970]
## Description
As a team, we need to perform functional testing so that we can ensure our feature is ready for release and that there are no discrepancies between Staging, Figma, and other flows within the UAE flows. (One such discrepancy is noted in [this Figma comment](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4?node-id=8800-17584#1240163747).) This is part of the staging review process.

## Resources
- [Test Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/community-care-direct-scheduling/cc-direct-scheduling-test-cases.md)
- [QA Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/community-care-direct-scheduling/cc-direct-scheduling-qa-plan.md)

## Tasks
- [ ] Complete the test runs identified in the QA Plan
    - [ ] [Product Test Run - iOS](https://dsvavsp.testrail.io/index.php?/runs/view/6184)
    - [ ] [UX Test Run - iOS](https://dsvavsp.testrail.io/index.php?/runs/view/6185)
    - [ ] [Product Test Run - Android](https://dsvavsp.testrail.io/index.php?/runs/view/6182)
    - [ ] [UX Test Run - Android](https://dsvavsp.testrail.io/index.php?/runs/view/6183)
