### ISSUE TITLE
Add appointment details null state tracking - Type of Care

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#98976]
## Description

This ticket tracks the the engineering work for Type of Care portion of the ticket #95657. As described in the parent ticket, we have the following design:

1. We choose to report base statistics on the FE using GA4 similar to what we do for [fetch results](https://github.com/department-of-veterans-affairs/vets-website/blob/436ce04628d106e6c8673fd1b51dbb30807bf07b/src/applications/vaos/appointment-list/redux/actions.js#L191C15-L200). 
2. When displaying appointment details on the FE (i.e. [in these layout files](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/vaos/components/layout)), we will increment the following statistics when they are expected to be present on the appointment type.  
  - i. Type of care: increment `vaos-null-states-expected-type-of-care` [^1] since all appointments should contain this field, then increment `vaos-null-states-missing-type-of-care` if it's not available.

## Development Checklist

- Null state statistics is added for each of the following appointment type:
  - [ ] In person
  - [ ] Video (At home)
  - [ ] Video - At VA
  - [ ] Video - At ATLAS
  - [ ] Phone
  - [ ] CC
  - [ ] Claims Exam
  - [ ] VA Request  
  - [ ] CC Request

### Design Assets
N/A

### Developer Reference
N/A

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove)

**Comment by JunTaoLuo** [comment]
@JRRoof The type of care null state percentage can be computed by looking up the events and calculating count(`vaos-null-states-missing-type-of-care`)/count(`vaos-null-states-expected-type-of-care`) over a specific timeframe.

**Comment by JRRoof** [comment]
@JunTaoLuo - I'm seeing the following events in GA4:

vaos-null-states-expected-total
vaos-null-states-expected-type-of-care
vaos-null-states-missing-type-of-care
vaos-null-states-missing-any

So far for January 1-14, 2025 I am seeing: 
vaos-null-states-missing-type-of-care 457,403 / vaos-null-states-expected-type-of-care 562,275 = 81.35%

Does that mean 81.35% of appointments are missing the type of care?

**Comment by JunTaoLuo** [comment]
Yes that is the correct interpretation. I'm shocked at how high that is but it lends some credence to the feedback we went over yesterday about how there's a lot of missing types of care.
