### ISSUE TITLE
Add two text links to the "how to file" page

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9897]
## Issue Description
Stakeholders would like to add links to some resources from this page:
https://www.va.gov/disability/how-to-file-claim/
---
## Tasks
Add text links to this video compilation and pdf user guide: 
[x] VIDEO: https://www.youtube.com/watch?v=dPuBrD-0niU&list=PLt_058CfeU2oqhqiIcbbYPgWPOY5fucl- (Anne/Beth)

USER GUIDE: 
[x] https://benefits.va.gov/benefits/docs/disability_compensation_claims_tool_20200611.pdf Anne/Beth

## Acceptance Criteria
- [ ] two text links are functional on the How to File a Claim page.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AnneHurley** [comment]
How do I prepare before starting my application?
Find out if you’re eligible for VA disability compensation 

- Gather any evidence (supporting documents) you’ll submit yourself when you file your VA disability claim.
- Be sure your claim is filled out completely and you have all the supporting documents ready to send in along with your claim. This will help us process your claim quickly. 
- Learn about fully developed claims 
- Find out if you’ll need to turn in any additional forms with your claim 

@bethpottsVADEPO Working on these text link placements 6/15

**Comment by AnneHurley** [comment]
[Revised copy with links to PDF and YouTube playlist]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/4782685/How.do.I.prepare.before.starting.my.application.docx)
@bethpottsVADEPO  Here's a draft putting links/context in that first section. We could also repeat the links with less context, I think, down by the green button. A couple of questions:
1. The PDF info seems to mostly be covered already, either on this Va.gov page, or on the next page where Veterans go to file the claim. We can keep it, but just wanted to raise that.
2. I linked to the YT playlist, so it's all those relevant videos, and only those. Seems a little less potentially confusing than the link listed above - ok?
3. The YT videos are branded with "526" but that doesn't appear on our page anywhere, nor on the PDF. Is that something we should consider mentioning elsewhere, like for SEO?
4  Let's also talk about whether we should maybe spell out more clearly that the top section of the page is how to file online/electronically. We may not need to since people will need to gather the same info - but then again if we place the new text links in that top section, and they apply only to online applications, maybe we should?

**Comment by stephorkandatx** [comment]
We have made the decision to not move forward with this work. Closing it out.
