### ISSUE TITLE
[FE] CC -Perform Accessibility Testing & Create Artifact

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#98971]
## Description
As a team, we need to perform accessibility testing so that we can ensure our feature is ready for release. Required for staging review.

## Tasks
- [x] Create an accessibility ticket/artifact using this [template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
- [x] Add the HCE-Checkin label to the accessibility ticket
- [x] Associate the accessibility ticket with the appropriate feature Epic
- [x] Attach the accessibility ticket to the collab cycle ticket for the feature Epic
- [x] Complete & check-off each test in the ticket

**Comment by wullaski** [comment]
@Dottifacilities this can be closed I added the link to the artifact to the collab cycle ticket
