### ISSUE TITLE
Add appointment details null state tracking - Facility ID

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#98978]
## Description

This ticket tracks the the engineering work for Type of Care portion of the ticket #95657. As described in the parent ticket, we have the following design:

1. We choose to report base statistics on the FE using GA4 similar to what we do for [fetch results](https://github.com/department-of-veterans-affairs/vets-website/blob/436ce04628d106e6c8673fd1b51dbb30807bf07b/src/applications/vaos/appointment-list/redux/actions.js#L191C15-L200). 
2. When displaying appointment details on the FE (i.e. [in these layout files](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/vaos/components/layout)), we will increment the following statistics when they are expected to be present on the appointment type
  - iii. Facility ID: increment `vaos-null-states-expected-facility-id` if expected, then increment `vaos-null-states-missing-facility-id` if not available. Note that this would imply missing facility details and facility phone as well.

## Development Checklist

- Null state statistics is added for each of the following appointment type:
  - [ ] In person
  - [x] ~~Video (At home)~~
  - [ ] Video - At VA
  - [x] ~~Video - At ATLAS~~
  - [x] ~~Phone~~
  - [ ] Claims Exam
  - [ ] VA Request 

### Design Assets
N/A

### Developer Reference
N/A

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove)

**Comment by JunTaoLuo** [comment]
Waiting for verification of the approach used in https://github.com/department-of-veterans-affairs/va.gov-team/issues/98976 before continuing work here.

**Comment by JunTaoLuo** [comment]
As I was working on the code, I realized that the facility ID isn't used for any display purpose for Phone, Video at Home and Video at a ATLAS location layouts so I don't think there's any value for tracking their null state statistics. cc @JRRoof

**Comment by JRRoof** [comment]
@JunTaoLuo - Agreed.  Closing out this issue.

**Comment by JunTaoLuo** [comment]
Actually we still need this for the other modalities.

**Comment by JunTaoLuo** [comment]
@JRRoof this is ready for validation. The facility id null state percentage can be computed by looking up the events and calculating count(`vaos-null-states-missing-facility-id`)/count(`vaos-null-states-expected-facility-id`) over a specific timeframe.

**Comment by JRRoof** [comment]
I'm seeing `vaos-null-states-expected-facility-id` in GA4, but not seeing any counts for `vaos-null-states-missing-facility-id`. Assuming that is because we have not seen any null states yet.

**Comment by JunTaoLuo** [comment]
Closing this since we're at the end of the sprint. Feel free to add more details or updated data though.
