### ISSUE TITLE
Add appointment details null state tracking - Facility Phone

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#98980]
## Description

This ticket tracks the the engineering work for Type of Care portion of the ticket #95657. As described in the parent ticket, we have the following design:

1. We choose to report base statistics on the FE using GA4 similar to what we do for [fetch results](https://github.com/department-of-veterans-affairs/vets-website/blob/436ce04628d106e6c8673fd1b51dbb30807bf07b/src/applications/vaos/appointment-list/redux/actions.js#L191C15-L200). 
2. When displaying appointment details on the FE (i.e. [in these layout files](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/vaos/components/layout)), we will increment the following statistics when they are expected to be present on the appointment type
  - v. Facility phone: If the facility ID is present, increment `vaos-null-states-expected-facility-phone` if expected, then increment `vaos-null-states-missing-facility-phone` if not available.

## Development Checklist

- Null state statistics is added for each of the following appointment type:
  - [ ] In person
  - [ ] Video (At home)
  - [ ] Video - At VA
  - [ ] Video - At ATLAS
  - [ ] Phone
  - [ ] Claims Exam
  - [ ] VA Request  

### Design Assets
N/A

### Developer Reference
N/A

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove)

**Comment by JunTaoLuo** [comment]
Waiting for verification of the approach used in https://github.com/department-of-veterans-affairs/va.gov-team/issues/98976 before continuing work here.

**Comment by JunTaoLuo** [comment]
@JRRoof this is ready for validation. The facility details null state percentage can be computed by looking up the events and calculating count(`vaos-null-states-missing-facility-phone`)/count(`vaos-null-states-expected-facility-phone`) over a specific timeframe.

**Comment by JRRoof** [comment]
I'm seeing `vaos-null-states-expected-facility-phone` in GA4, but not seeing any counts for `vaos-null-states-missing-facility-phone`.  Assuming that is because we have not seen any null states yet.

**Comment by simiadebowale** [comment]
@JunTaoLuo - just following up here, I think this is good to go assuming we're not seeing the `vaos-null-states-missing-facility-phone` event because those have not retuned null for any appointment as of now. cc: @JRRoof

**Comment by JunTaoLuo** [comment]
Yup that was probably the case on Monday since we only had about 30 minutes of data. I wonder if we caught any new cases where the facility phone was missing over the past week though.

**Comment by simiadebowale** [comment]
@JRRoof - can you verify this please

**Comment by JunTaoLuo** [comment]
Closing this since we're at the end of the sprint. Feel free to add more details or updated data though.
