### ISSUE TITLE
Add appointment details null state tracking - Clinic Phone

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#98981]
## Description

This ticket tracks the the engineering work for Type of Care portion of the ticket #95657. As described in the parent ticket, we have the following design:

1. We choose to report base statistics on the FE using GA4 similar to what we do for [fetch results](https://github.com/department-of-veterans-affairs/vets-website/blob/436ce04628d106e6c8673fd1b51dbb30807bf07b/src/applications/vaos/appointment-list/redux/actions.js#L191C15-L200). 
2. When displaying appointment details on the FE (i.e. [in these layout files](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/vaos/components/layout)), we will increment the following statistics when they are expected to be present on the appointment type
  - vi. Clinic phone: increment `vaos-null-states-expected-clinic-phone` if expected, then increment `vaos-null-states-missing-clinic-phone` if not available.

## Development Checklist

- Null state statistics is added for each of the following appointment type:
  - [ ] In person
  - [ ] Video (At home)
  - [ ] Video - At VA
  - [ ] Video - At ATLAS
  - [ ] Phone
  - [ ] Claims Exam

### Design Assets
N/A

### Developer Reference
N/A

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove)

**Comment by JunTaoLuo** [comment]
Waiting for verification of the approach used in https://github.com/department-of-veterans-affairs/va.gov-team/issues/98976 before continuing work here.

**Comment by JunTaoLuo** [comment]
@JRRoof this is ready for validation. The clinic phone null state percentage can be computed by looking up the events and calculating count(`vaos-null-states-missing-clinic-phone`)/count(`vaos-null-states-expected-clinic-phone`) over a specific timeframe.

**Comment by JRRoof** [comment]
Seeing counts for both events in GA4.  Todays counts so far show the following:
`vaos-null-states-missing-clinic-phone` = 2,058
`vaos-null-states-expected-clinic-phone` = 86,686
2,058 / 86.686 = 2.37%

Closing ticket.
