### ISSUE TITLE
Documentation: Combine Platform Support Responses

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#98982]
## Description 
We have multiple docs for the Tier 1 and Tier 2 responses. We need to combine them and use the format outlined on [this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2838003793/Support+Response+Templates+Tier+1).

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Cross reference Tier 1 Support Responses on [this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2847343007/Tier+1+Common+Responses) and add them to [this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2838003793/Support+Response+Templates+Tier+1)
- [x] Reformat [this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2838495318/Support+Response+Templates+Tier+2) to match [this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2838003793/Support+Response+Templates+Tier+1) 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
