### ISSUE TITLE
Documentation: Update Slack Channels for Platform Support Page

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#98984]
## Description 
We are auditing our internal documentation and noticed a need to update our Slack Channels list based on operational enhancements we have made. [The content lives here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2510195011/Slack+Channels+for+Platform+Support).

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Add any channels we maintain
- [x] Add any channels that we need to observe to do our job (i.e. support ticket channels)
- [x] Add any categories and channels that might be missing from the list currently
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
Documentation has been updated. Launched Support Enhancements Confluence doc has been updated.
