### ISSUE TITLE
Change VR&E name throughout benefits section

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9899]
## Issue Description
_The program name is changing on June 22, and stakeholders would like to update our pages as close to that date as possible. We will need to make these changes on static pages, left and top nav labels (and any others--are there any buttons with "voc rehab"?), and URL._

## New name of program: Veteran Readiness and Employment

---
## Tasks
**Note:** Process as discussed on 6/9 call: Laura makes the changes and edits per the below instructions. Randi follows behind her with a copyedit, making sure everything in the below list was done accurately. 
- [ ] Read through all static pages in the VR&E section on our site and change all instances of Vocational Rehabilitation and Employment to Veteran Readiness and Employment. (note, that's singular "Veteran")
- [ ] In addition to the full name change, there are also instances of shortened references that will require some editing (voc rehab, vocational rehab, rehabilitation services). We won't, in many of these instances, want to simply swap in the full name, but will need to be strategic about what works based on surrounding text. Let's talk this through.
- [ ] SEO task 1: For the first full program-name mention on each page--Veteran Readiness & Employment--please follow it with this in parentheses: "(formerly called Vocational Rehabilitation and Employment)"
- [ ] SEO task 2: Work the old name into the meta description for each page in the same way as above in task 1 in places where there are already mentions of the program name. In other words, don't rewrite the metas. Just try to make minor adjustments, and let me know if this turns out to be a can or worms (ie not as straightforward as I'm anticipating it to be). 
- [ ] Change the name for all labels (left and top nav and any buttons if there are any). (Randi)
- [ ] URL segment change. Beth, Danielle, Mikki to meet about this re: SEO implications and best path forward. (Beth's update on 6/13: After discussion with Mikki, we'd like to move forward with https://www.va.gov/careers-employment/readiness-program/
- [ ] Ensure all crosslinks are node IDs; Check with CMS team when publishing if there are any that weren't caught causing broken links
- [x] Check with stakeholder about contacting eBenefits POC to request the name change there too. Where else? (Beth)
- [x] Meet with Bettye and Robyn week of 6/8 to update them on timeframe for completing this work and any issues / questions that need to be discussed (like eBenefits).

## Style notes 
- [ ] "The Veteran Readiness and Employment program" refers to VR&E as a whole. It's what Veterans apply for. Avoid overuse of "program." Use "Veteran Readiness and Employment" when possible. Note that "program" is not capitalized. Use "and" (not ampersand) with full name.
- [ ] Use "services" when discussing the 5 tracks. So "Veteran Readiness and Employment services" refers to the 5 tracks -- NOT the program as a whole. 
- [ ] Use "VR&E" in front of track names, such as, "VR&E Reemployment track". Note that "track" is lowercase, but the track names (like "Reemployment") are capitalized. 
- [ ] Vocational Rehabilitation Counselor (VRC) > stet
- [ ] Delete all instances of "Voc Rehab" 
- [ ] Chapter 31 > stet
- [ ] support-and-services tracks > stet

## Changes made 

Page titles below are the current ones on VA.gov, not revised. 

- [L] **CAREERS AND EMPLOYMENT MAIN HUB PAGE CHANGES NEEDED:** The first link in the "Get" section, right above Eligibility needs "program" changed to "tracks." Also, second sentence in the blurb should say, "Our tracks" instead of "Our programs."

Under "More Information" (stakeholders agreed to update the pages we're linking to so the new program name appears):
- Subsistence blurb: change "Voc Rehab" to "Veteran Readiness and Employment"
- Glossary link (third one): Link itself should say, "Veteran Readiness and Employment glossary. The blurb under the link needs the new program name swapped in.
- Success stories (fourth link): For the link itself, use the program name--Veteran Readiness and Employment success stories. For the blurb, just spell out and lowercase "vocational rehabilitation" instead of "Voc Rehab" there. We'll use it in the general sense here. 

0 - [X] Careers and employment
https://www.va.gov/careers-employment/
Phttp://preview-prod.vfs.va.gov/preview?nodeId=72

1 - [X] VA Vocational Rehabilitation (Chapter 31)\
New name: Veteran Readiness and Employment (Chapter 31) (Name already appeared as written here.)\
<https://www.va.gov/careers-employment/vocational-rehabilitation/>\
<http://preview-prod.vfs.va.gov/preview?nodeId=725>

2 - [X] Veterans Vocational Rehabilitation programs\
New name: VR&E support-and-services tracks (Change complete.)\
<https://www.va.gov/careers-employment/vocational-rehabilitation/programs/>\
<http://preview-prod.vfs.va.gov/preview?nodeId=729>

3 - [X] VR&E Reemployment track
No new name. Remains the same. 
https://www.va.gov/careers-employment/vocational-rehabilitation/programs/reemployment/
http://preview-prod.vfs.va.gov/preview?nodeId=733 
Note: Capped Services in Step 3 of process list because it's the name of the button they should be clicking (like Additional Benefits in Step 2). Though we need to confirm that that is what the wording is changing to in eBenefits. Beth: Laura and I decided to try to match what we think the eBenefits changes will be, so we went with Veteran Readiness and Employment Program for No. 3 and lc "program" for No. 4.
**ADD FULL NEW PROGRAM NAME TO INTRO: Last sentence, change "we" to the new program name with initialism, like this: Find out how Veteran Readiness and Employment (VR&E) can help you return to your former job and support your employer in meeting your needs.**

4 - [X] VR&E Rapid Access to Employment track 
No new name. Remains the same. 
https://www.va.gov/careers-employment/vocational-rehabilitation/programs/rapid-access-to-employment/
http://preview-prod.vfs.va.gov/preview?nodeId=732 
**ADD FULL NEW PROGRAM NAME TO INTRO: Last sentence, add the full name, like this: Find out if you can get Veteran Readiness and Employment (VR&E) benefits and services to help you use your existing skill set to find a job.**

5 - [X] VR&E Self-Employment track
No new name. Remains the same. 
https://www.va.gov/careers-employment/vocational-rehabilitation/programs/self-employment/
http://preview-prod.vfs.va.gov/preview?nodeId=734
**ADD FULL NEW PROGRAM NAME TO INTRO: Revise last sentence to say: Find out if Veteran Readiness and Employment (VR&E) can help you start your own business.**

6 - [X] VR&E Employment through Long-Term Services track
No new name. Remains the same. 
https://www.va.gov/careers-employment/vocational-rehabilitation/programs/long-term-services/
http://preview-prod.vfs.va.gov/preview?nodeId=731
**ADD FULL NEW PROGRAM NAME TO INTRO: Revise last sentence to say: Find out if you’re eligible for vocational counseling and training through Veteran Readiness and Employment (VR&E).**

7 - [X] VR&E Independent Living track
No new name. Remains the same. 
https://www.va.gov/careers-employment/vocational-rehabilitation/programs/independent-living/
http://preview-prod.vfs.va.gov/preview?nodeId=730
**ADD FULL NEW PROGRAM NAME TO INTRO: Revise last sentence to say: Find out if you may be eligible for services through Veteran Readiness and Employment (VR&E) to help you live as independently as possible.**

8 - [X] Eligibility for VA Vocational Rehab and Employment\
**New name: Eligibility for Veteran Readiness and Employment** (Name already appeared as written here.)\
<https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/>\
<http://preview-prod.vfs.va.gov/preview?nodeId=726>

9 - [X] How to apply for VA Voc Rehab and Employment\
**New name: How to apply for Veteran Readiness and Employment **(Name already appeared as written here.)\
<https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/>\
<http://preview-prod.vfs.va.gov/preview?nodeId=727>

10 - [X] Accessing Vocational Rehabilitation through IDES\
New name: Veteran Readiness and Employment through IDES (Change complete.)\
<https://www.va.gov/careers-employment/vocational-rehabilitation/ides/>\
<http://preview-prod.vfs.va.gov/preview?nodeId=728>\
**Change H1 to Veteran Readiness and Employment through IDES (remove the verb "access" altogether)**

## Acceptance Criteria
- [ ] Name changed successfully across all our VA.gov pages.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lwalsh617** [comment]
@bethpotts @RLHecht - I revised the following based on yesterday's call: 
1) Veterans Vocational Rehabilitation programs. For the meta description, I provided two options at the top of this ticket. (I put my recommended version in Drupal.)
2) VR&E Reemployment track (changed ERC to VRC)
3) Rapid Access to Employment (changed ERC to VRC)
See Drupal links at top of ticket.

**Comment by RLHecht** [comment]
@bethpottsVADEPO @lwalsh617 I read over Laura's updates to the three pages listed above. Two things:

I capped Services in step three of the process list since it's the name of the link the user should click (similar to Additional Benefits in the step before). Though we should confirm that that's what it will say when logged in to eBenefits. 

Also, there are links to a few PDFs on the page for VR&E programs, which use the old name. I'm assuming those PDFs will eventually be updated with the new name, but if they change the PDF file name, the links will give a 404.

**Comment by lwalsh617** [comment]
@RLHecht Is the eBenefits question one we need to ask the SMEs, or can our authenticated team look into that? Thanks

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 I had assigned that one to myself, and already asked Bettye actually, so nice to check that one off! The answer is that she has already taken care of things on the eBenefits side.

**Comment by lwalsh617** [comment]
@RLHecht @bethpottsVADEPO - 

I revised the first 10 pages (which I suspect will have the most edits.) They're at the top of this ticket in a checklist. I included the live page url as well as Drupal preview link for comparison.

**On the 5 track pages**, I didn't use the old program name in the intro or meta description (like I did on the higher level pages).  It became more confusing than helpful, as it means addressing 2 program names, a track name, and abbreviations. Users will still see "VR&E" and the track names they are familiar with, so I don't see this being problematic. Nor should it create SEO issues for users searching by track name. 

**Housekeeping**: At the top of this ticket, I moved all our style decisions under the style section. This gives us one place to refer to while editing. 
Question: Would it make more sense to move the 10 pages I edited into the table Nick created? The pro is that it keeps all pages in one place. Con is that we want pertinent info at top of ticket rather than in comments. Either works for me.

**Comment by bethpottsVADEPO** [comment]
**Update after stakeholder call with Betty Hodge, Rob Hart, Melissa Prosper, and Robyn Trulock**
(@lwalsh617 @RLHecht I don't think there's a need to put this in the Style section here, but go ahead and do whatever is most useful for you!)
- In the subway map on the tracks pages, make No. 3: "Choose VR&E services"
- Confirmed that we don't need to use "program" too often as it sounds formal and isn't the way Veterans talk about it. They just say, "VR&E" rather than including "program" in any variation of the name.
- Confirmed that we should get rid of "voc rehab" and "vocational rehab" references. And even get rid of "vocational" and "rehabilitation" is there are instances where they aren't used together as a term.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO @RLHecht - There's Voc Rehab glossary (benefits.va.gov/vocrehab/program_definitions.asp) that is a legacy page. We link to it from the Careers and employment page. Should we leave it for last and edit and build in Drupal? Or kill the link to it for now??

**Comment by stephorkandatx** [comment]
We have determined that two of the pages will require frontend support for updates. Ticket at #10232 10232

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Re: your above question about the Voc Rehab glossary. I will ask about that and success stories and subsistence allowance rates pages on Tuesday. Will post here what I'm told. Don't remove these links.

**Comment by lwalsh617** [comment]
@bethpotts -- Per our phone call, I wrote up the following usage considerations that might be helpful. @RLHecht -- feel free to add/edit. 
![image](https://user-images.githubusercontent.com/53535663/84826650-3f2b4180-aff1-11ea-988e-f2b53e90d580.png)

**Comment by bethpottsVADEPO** [comment]
@stephorkandatx @ncksllvn @lwalsh617 @RLHecht We have to pause on this work because there's now potentially some new guidance on which terms we need to keep in the text and which terms definitely shouldn't be there. Also revisiting the URL changes and redirects. Trying to get a call set up with the stakeholder and Jen Lee to clarify the path forward.

**Comment by ncksllvn** [comment]
Keep me posted on what content changes in React apps we need to make!

**Comment by bethpottsVADEPO** [comment]
@ncksllvn We need to make sure Vocational Rehabilitation and Employment (the full name of the program) changes to Veteran Readiness and Employment. Not sure if you already figured out if those react apps were old/ghost pages, but if not, place change the name per above.

**Comment by ncksllvn** [comment]
@bethpotts can you check out my comment in this issue? https://github.com/department-of-veterans-affairs/va.gov-team/issues/10232

**Comment by RLHecht** [comment]
All the pages with an X in the Nick's comment above as well as the pages with an X in the top section have all been published. We made changes to the megamenu but not sure it made it into today's deploy. Moving ticket to validate. @bethpottsVADEPO @stephorkandatx

**Comment by bethpottsVADEPO** [comment]
It launched! Closing this ticket.
