### ISSUE TITLE
Add appointment details null state tracking - any null state

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#99006]
## Description

This ticket tracks the the engineering work for Type of Care portion of the ticket #95657. As described in the parent ticket, we have the following design:

1. We choose to report base statistics on the FE using GA4 similar to what we do for [fetch results](https://github.com/department-of-veterans-affairs/vets-website/blob/436ce04628d106e6c8673fd1b51dbb30807bf07b/src/applications/vaos/appointment-list/redux/actions.js#L191C15-L200). 
2. When displaying appointment details on the FE (i.e. [in these layout files](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/vaos/components/layout)), we will increment the following statistics when they are expected to be present on the appointment type
  - vii. Any null state: increment `vaos-null-states-expected-total` for each appointment, then increment `vaos-null-states-missing-any` if any of the following fields is missing: Type of care, Provider, Facility Id, Facility details, Facility phone, Clinic phone.

## Development Checklist

- Null state statistics is added for each of the following appointment type:
  - [ ] In person
  - [ ] Video (At home)
  - [ ] Video - At VA
  - [ ] Video - At ATLAS
  - [ ] Phone
  - [ ] CC
  - [ ] Claims Exam
  - [ ] VA Request  
  - [ ] CC Request

### Design Assets
N/A

### Developer Reference
N/A

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove)

**Comment by JunTaoLuo** [comment]
@JRRoof The type of care null state percentage can be computed by looking up the events and calculating count(`vaos-null-states-missing-any`)/count(`vaos-null-states-expected-total`) over a specific timeframe.

Note that since type of care is the only null states we're tracking right now, the percentage here should exactly match the percentage of missing type of care.

**Comment by JRRoof** [comment]
@JunTaoLuo - I'm seeing the following events in GA4:

vaos-null-states-expected-total
vaos-null-states-missing-any

So far for January 1-14, 2025 I am seeing: 
vaos-null-states-missing-any 456,988 / vaos-null-states-expected-total 563,251 = 81.13%

Does that mean 81.13% of appointments have at least one null field?

**Comment by JunTaoLuo** [comment]
Yes that's right.
