### ISSUE TITLE
Identify how to discover validation issues and alike

### ISSUE THREAD

**Issue by comaurice** [department-of-veterans-affairs/va.gov-team#99011]
## Value Statement

**_As a_** Veteran

**_I want to_** see helpful error messages when my form submission cannot validate

**_So that_** I know what to fix or how to report the issue

---

## Background Context

- There was an issue with the User Profile code that was not setting `countryCodeISO2`. This field is required by LightHouse and we were pulling that value automatically from the Veteran's profile. If there is an issue and the value isn't there, the form submission will fail schema validation and an error is shown in the UI when they try to submit. Unfortunately there is no specific error for that value so the Veteran is told there is a validation issue but not what field/issue is the problem or how to resolve it.
![Image](https://github.com/user-attachments/assets/3cd922eb-2e0c-4e81-abf1-3bf0bb72431e)

## Tasks

- [ ] _Add validation rules for all fields_
- [ ] _Add error messages to UI for each field_
- [ ] _Allow Veterans to update all fields as needed_

## Acceptance Criteria

- [ ] _Make sure there are validation rules for all fields_
- [ ] _Make sure the UI will show an error message for each field that fails_
- [ ] _Any validation failures can be remediated by the Veteran_

## Open questions

- Some data is pulled from the logged in profile, can/should we allow them to overwrite that data?

## Outcome, Success Measure, KPI(S), and Tracking Link

- Any future unexpected error in a field is communicated to the Veteran

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Ready for validation

**Comment by kayline** [comment]
Validated!
