### ISSUE TITLE
Engine BE 2.5: Add logging to old sidekiq jobs, remove from scheduler Dec 18

### ISSUE THREAD

**Issue by kayline** [department-of-veterans-affairs/va.gov-team#99019]
## Value Statement

**_As a_** backend dev

**_I want to_** know if anyone else is calling our old background jobs

**_So that_** I can feel safe to delete them

---

## Background Context

- Do NOT include form4142_submit or submit_upload, they aren't scheduled.

## Tasks

- [x] Add unique logging to the old versions of the jobs
- [x] Remove the jobs from the schedule, leaving the new engine versions

## Dependencies 

- Add here

## Acceptance Criteria

- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Out of scope

- Add here

## Open questions

- Add here

## Designs and Build Notes

- Add here

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

### Enablement team (if needed)
@ member of team

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
Merged, verifying in staging.

**Comment by dfong-adh** [comment]
Verfied in staging.

**Comment by dfong-adh** [comment]
Verified in prod.
