### ISSUE TITLE
IA Tracker: IA Spec for 5490/1990e/1900 migration work

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#99055]
## Acceptance Criteria
- [x] [IA spec draft in GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/5490-1990-1990e-url-updates.md) shared with Mikki/Sam
- [x] Revisions made to IA spec based on Mikki's comment
- [ ] Confirm whether we want to share this with the team, or just keep for our records

**Comment by kristinoletmuskat** [comment]
Not sharing with the team now -- may share in January, or may just keep it internal so as not to confuse the team.
