### ISSUE TITLE
VFF: Review form submitter pattern guidance

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#99059]
## Description
We need to review the product team's guidance for a new form submitter pattern for VADS. This includes information about accredited representatives and alternate signers.

## Resources
- [Draft guidance](https://docs.google.com/document/d/1XTGusTYeEqKbmId_Gu8g7h53LKUPIv0nm8pezHEUSyA/edit?usp=sharing) (Google)

## Tasks
- [x] LW, MZ: Draft guidance
- [x] LW, MZ: Share guidance with product team
- [x] LW, MZ: Finalize guidance with product team

## Criteria
- [ ] Content guidance has been shared and finalized with the product team

**Comment by megzehn** [comment]
Update: Laura provided feedback in Google. 

Separate but related to this pattern guidance: We have a [draft content brief](https://github.com/department-of-veterans-affairs/va.gov-team/pull/98897/files) with some working definitions for representative types that we intend to add to the style guide so teams can pull relevant language

CC @laurwill
