### ISSUE TITLE
Improve Calendar Selection Indicators in Direct Scheduling Flow

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#99057]
## Task Description

Update the calendar in the direct scheduling flow to improve how selected times and dates are indicated.

Currently, a checkmark appears over the date to show that a selected time is associated with it. Removing the checkmark would result in a loss of this visual indicator. Explore whether an indicator is necessary.

Reconsider the request calendar indicators. One option to evaluate is displaying the selected time, date, or timeframe beneath the calendar.

Currently what the checkmark looks like in staging:
<img width="297" alt="Image" src="https://github.com/user-attachments/assets/426eeb0b-88e6-4a36-988b-9f3dd3d691b6" />

## Notes and References
-

## Acceptance Criteria
- [ ] New designs in figma working file
- [ ] A11y feedback gathered and applied
- [ ] Dev ticket is made

## Deliverables
- Design specs

**Comment by outerpress** [comment]
@rileyorr this is the issue I mentioned in the SME sync - we're basically wondering if we can just remove the checkmark, or if we need that additional indicator that something has been selected

**Comment by rileyorr** [comment]
Hi @outerpress! I'm checking out this component right now but what I'm seeing in staging is different than the screenshot provided in the ticket so I want to make sure I'm in the right place before proceeding. I'm signed in as patient999 and am in the process of scheduling an optometry appointment at Richmond VA clinic. Does this component vary depending on a Veteran's selections in the appointments flow? If so, how might I get to the version in this ticket? 

I've attached a screenshot of what I'm seeing in staging:
<img width="742" alt="A calendar picker that allows selecting an up to 3 appointment times." src="https://github.com/user-attachments/assets/c80ce243-ca7f-41b4-87e2-c2268b95119d" />

**Comment by outerpress** [comment]
@rileyorr oh yep that's the request calendar. We send the user down different paths depending on if a facility lets them direct schedule (pick a specific date and time) or not. If not, they get that calendar. ([Here's the full labyrinth](https://www.figma.com/design/ugE1APC20v8OcArGB2IMQy/User-Flows-%7C-Appointments-FE?node-id=1-2) if you want to dig in more.)

So to find the direct schedule calendar ([this flow](https://www.figma.com/design/ugE1APC20v8OcArGB2IMQy/User-Flows-%7C-Appointments-FE?node-id=1-3649&t=Dyey4g21MLo4S0uO-4) in the labyrinth):
* Log in as patient999
* Choose primary care
* Choose "VA medical center or clinic"
* Choose Cheyenne VA Medical Center
* Choose the clinic "CHY PC VAR2"
* Enter a date in the future
* The next step should be the calendar

Let me know if you get stuck!

**Comment by rileyorr** [comment]
Thank you so much for providing instructions on how to get to the correct calendar! 

So when considering whether or not the checkmark is needed, we need to take into account [WCAG 1.4.1 Use of Color](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html) which indicates that color isn't the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element. 

There are a couple things related to passing this criteria relevant to your design: 

> Use information in addition to color, such as shape or text, to convey meaning.

When I interact with a date on the calendar picker, the shape changes from a square with rounded edges to a rounded square with a carrot pointing down to the times. This shape change visually indicates that I've selected the element and the state has changed. 

> If content is conveyed through the use of colors that differ not only in their hue, but that also have a significant difference in lightness, then this counts as an additional visual distinction, as long as the difference in relative luminance between the colors leads to a contrast ratio of 3:1 or greater. For example, a light green and a dark red differ both by color (hue) and by lightness, so they would pass if the contrast ratio is at least 3:1

When I compare the color contrast between the default state background of a light grey and the active state background of the dark blue which vary by hue and lightness the contrast ratio is 5.9:1. 

Based on this, I don't think you need the checkmark to visually indicate that a date and time has been selected because the date element uses shape to convey that the date is selected and the radio button selection indicates the time selected. 

**However**, I was interested in what the screen reader experience was when the checkmark icon appears upon selecting a date and time. I tested this out by selecting a date and time before navigating away and back to the selected date. I would expect to hear 'Date, Time, Selected' however I only hear 'Date' and 'Selected'. 'Selected' is the term associated with the checkmark. The only way a screen reader user would know what time they selected is if they navigated back into the radio buttons and found the one they had selected, which can take a while to get to. I took a video of my experience using VoiceOver on iPhone for reference. After I select a time I also need to swipe/tab through all the remaining available dates in the calendar to get to the 'Back' and 'Continue' buttons at the bottom of the page. 

If possible, I would recommend exposing the selected time to screenreaders when a date and time are selected so they don't need to dig for that information. Let me know if you have any questions!

Has this experience been tested with AT users? I'd love to read about any findings related to it!

**Comment by outerpress** [comment]
Thank you for the deep look and informative response! We haven't taken the date picker through A11Y testing. This was built awhile ago (before my time) so I expected some issues. 

It sounds like we can remove the checkmark without any issues - great!

> If possible, I would recommend exposing the selected time to screenreaders when a date and time are selected so they don't need to dig for that information. 

When you say exposing, do you mean the screenreader would announce the selected time (if present) when the date is selected? As in:

* Tab to date
* Announce "Wednesday, April 2, 2024. 7:40 a.m. option selected"

**Comment by rileyorr** [comment]
@outerpress that announcement recommendation is correct! 

It would be beneficial to include this component in some future AT testing. While I can technically navigate through it using keyboard and a screen reader, the interactions may pose challenges to AT users. For example, calendar pickers traditionally allow keyboard navigation between dates using arrow keys, but I have to navigate between dates by tabbing. I also noticed my screen reader making some strange announcements such as selecting '7:00 a.m.' on Tuesday April 2nd reading out 'Sunday at 7:00 a.m. option selected'.

I'm going to create a separate ticket for myself to audit this component and document any issues I encounter, but let me know if you have any questions related to the feedback relevant to this ticket!

**Comment by outerpress** [comment]
@rileyorr great, thanks! Let us know the results of your audit and we can create separate tickets for that work.

@Cieramaddox can you create a dev ticket to remove the checkmark from the direct scheduling calendar?

**Comment by Cieramaddox** [comment]
Dev work can be tracked [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/102377)

**Comment by outerpress** [comment]
Work has a dev ticket, closing
