### ISSUE TITLE
Update Product Guide for Release

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#99069]
**NOTE: We need to change the name of the product guide because the official name of the application (in the VFS Product Directory) is "Day of Appointment Travel Claim Submission"; we should change the name of the product guide to match the official name of the product.**

## Description
Update the product guide, as necessary, based on the feature release.

## Tasks
- [x] Look through the Product Guide and compare it to the latest designs for OH LoROTA travel (We know we need to update the OMB information and look at any error discrepancies. )
- [x] Update the OH Travel Product Guide, including content and screenshots, if necessary
- [x] Update the name of the product guide (see note above)

## Acceptance Criteria
- [ ] Product Guides are up-to-date and published to Git and SharePoint (https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/product/product-guides)

**Comment by zach-park** [comment]
@loripusey , I'm starting this ticket today, and I'm unable to get to the Sharpoint for a strange reason. And I'm wondering if you can access it (I've tried both a6 and va.gov emails via Citrix). And I wasn't able to. If you can access it, could you please let me know?
