### ISSUE TITLE
Test form prefills for Form 21-0966 (VA Product Forms Team)

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#99075]
For the PCIU migration, the Platform Product Team changed the base class pre-fill to call VA Profile. This impacts the prefill (and non-prefil) fields for form 21-0966 listed below:
```yaml
    veteran:
      address:
        zipCode5: [contact_information, address, postal_code]
      emailAddressText: [contact_information, email]
nonPrefill:
  veteranAddress:
    street: [contact_information, address, street]
    street2: [contact_information, address, street2]
    street3: [street3]
    city: [contact_information, address, city]
    state: [contact_information, address, state]
    country: [contact_information, address, country]
    postalCode: [contact_information, address, postal_code]
```

### Tasks
- [ ] Turn on flipper `remove_pciu` [**IN STAGING**](https://staging-api.va.gov/flipper/features)
- [x] Test prefill for form 21-0966 in staging.
- [x] Test the `nonPrefill` fields listed above, if possible. 
- [x] If testing is successful, comment and close this issue.
- [ ] If issues are found (or if there are questions) reach out in [#pciu-migration-testing](https://dsva.slack.com/archives/C085A9JCB1B)

**Comment by AshleyGuerrant** [comment]
Blocked pending this [key PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18729) being merged.

This work essentially serves as a "flood gate" PR where after it is merged, we will be pointing completely to VA Profile Contact Information instead of PCIU.
cc @tbaker1026

**Comment by tbaker1026** [comment]
@AshleyGuerrant Here is a screenshot of prefill - tested non prefill and looked ok as well<img width="1037" alt="Image" src="https://github.com/user-attachments/assets/616d8eff-060d-46c8-96e5-9f8c5ce87c9d" />

**Comment by AshleyGuerrant** [comment]
@RachalCassity - can you please review the comment above?

cc @LindseySaari @rmtolmach @rjohnson2011

**Comment by rmtolmach** [comment]
@tbaker1026 Can you test that once more? The code wasn't deployed to Staging until 5:45pm ET yesterday.

**Comment by tbaker1026** [comment]
@rmtolmach tested again - prefill works <img width="577" alt="Image" src="https://github.com/user-attachments/assets/e4f22fa0-146f-4201-946e-11f457e207c8" />

**Comment by AshleyGuerrant** [comment]
Excellent, thank you @tbaker1026! No additional tested is needed at this time. Closing this ticket out.
