### ISSUE TITLE
Test form prefills for Form 21-526ez (Disability Experience Team)

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#99071]
For the PCIU migration, the Platform Product Team changed the base class pre-fill to call VA Profile. This impacts the prefill field for form 21-526ez listed below:
```yaml
veteran: [veteran_contact_information, veteran]
```
### Tasks
- [x] Turn on flipper `remove_pciu` [**IN STAGING**](https://staging-api.va.gov/flipper/features)
- [x] Test prefill for form 21-526ez in staging.
- [x] If testing is successful, comment and close this issue.
- [x] If issues are found (or if there are questions) reach out in [#pciu-migration-testing](https://dsva.slack.com/archives/C085A9JCB1B)

**Comment by AshleyGuerrant** [comment]
The [key PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18729) has been merged and testing can now kick off any time.

**Comment by sethdarragile6** [comment]
[Stage testing complete](https://github.com/department-of-veterans-affairs/va.gov-team/issues/100519#issuecomment-2596782291).

**Comment by AshleyGuerrant** [comment]
Excellent, thanks for the update @sethdarragile6!
