### ISSUE TITLE
Test form prefills for Form 10-7959c (IVC CHAMPVA Team)

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#99072]
For the PCIU migration, the Platform Product Team changed the base class pre-fill to call VA Profile. This impacts the prefill fields for form 10-7959c listed below:
```yaml
    street: [contact_information, address, street]
    street2: [contact_information, address, street2]
    city: [contact_information, address, city]
    state: [contact_information, address, state]
    country: [contact_information, address, country]
    postalCode: [contact_information, address, postal_code]
  phone_number: [contact_information, us_phone]
  email_address: [contact_information, email]
```
### Tasks
- [ ] Turn on flipper `remove_pciu` [**IN STAGING**](https://staging-api.va.gov/flipper/features)
- [ ] Test prefill for form 10-7959c in staging.
- [ ] If testing is successful, comment and close this issue.
- [ ] If issues are found (or if there are questions) reach out in [#pciu-migration-testing](https://dsva.slack.com/archives/C085A9JCB1B)

**Comment by AshleyGuerrant** [comment]
Blocked pending this [key PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18729) being merged.

This work essentially serves as a "flood gate" PR where after it is merged, we will be pointing completely to VA Profile Contact Information instead of PCIU.
cc @pshahVA

**Comment by AshleyGuerrant** [comment]
The [key PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18729) has been merged and testing can now kick off at any time.
cc @pshahVA @baltes

**Comment by baltes** [comment]
Hi @AshleyGuerrant, no issues here as prefill is not used on this form.

**Comment by AshleyGuerrant** [comment]
@baltes - thanks for the update!
@RachalCassity @rmtolmach - could you please review Bo's comment above?

cc @LindseySaari

**Comment by RachalCassity** [comment]
Hi @baltes. Form 10-7959c (IVC CHAMPVA) was selected for prefill testing because prefill is enabled for 10-7959C. I was looking over your configuration. In the vets-api repo, ivc_champva settings have prefill set to true [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L414). There is not an ivc_champva prefill setting in the production manifest settings, [here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/prod/values.yaml#L2599). 

To disable prefill for 10-7959C, you can add`prefill: false` to the [production manifest ivc_champva settings](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/prod/values.yaml#L2599).

Prefill helps veterans complete forms more efficiently and reduces data mismatches across the platform. Could you explain why prefill is not being utilized for Form 10-7959c?

**Comment by baltes** [comment]
@michaelclement Could you take a look at this one to see if there is any impact on prefill?

cc @andrea-merrill

**Comment by michaelclement** [comment]
Prefill isn't being used on this form at the moment because we support a couple different cases when filling out the form (i.e., filling out for self or for someone else). 

In my understanding there's not a clear way to prevent the prefill data from being populated if the user selects they're filling it out on someone's behalf, and so we opted to not implement a prefill mapping so that users wouldn't need to manually remove prefilled information in that use case.

As far as why `prefill: true` is set, I was under the impression that flag needed to be on to enable populating data pulled from Save In Progress. If that's not the case, I can set that flag to false. Thanks!

**Comment by RachalCassity** [comment]
@michaelclement Thank you for your clarification. Would it be appropriate to keep prefill enabled and use it when users are filling out the form themselves? I wasn’t aware that data was populating from Saved in Progress. I’d like to investigate Saved in Progress before disabling prefill, as it could potentially be an issue if FormProfile and Saved in Progress are utilizing the same prefill settings.

**Comment by RachalCassity** [comment]
Also, I'm assuming Saved in Progress is referring to [InProgressForm](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/in_progress_form.rb). Is that correct?

**Comment by michaelclement** [comment]
Conditionally using prefill would be the ideal, and it's something we could revisit in a future sprint.  

It's been a while since I configured this initially, but I was following the [platform SIP docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si) which (according to [this other doc](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Engineering/Form%20Digitization%20development%20guide.md#step-7-collaborative-add-authenticated-experience-support-to-the-form)) must have indicated that the prefill configuration was a necessary step. I think that's not correct though, looking at the update platform docs.

**Comment by michaelclement** [comment]
I should also note that the mapping that exists for this form was never actually used and is not valid - it would probably be better to altogether remove it at this point to avoid confusion. I can put together a PR for that.
