### ISSUE TITLE
PCIU Replacement Step 5b: VAProfile Contact Information V2 Testing (VA Notify Team testing)

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#99074]
For the PCIU migration, the Platform Product Team changed the data source for ContactInformation to call VA Profile instead of PCIU.

### Tasks
- [ ] Turn on flipper `remove_pciu` [**IN STAGING**](https://staging-api.va.gov/flipper/features)
- [ ] Test any VA Notify code related to Contact Information.
- [ ] If testing is successful, comment and close this issue.
- [ ] If issues are found (or if there are questions) reach out in [#platform-product-team](https://dsva.slack.com/archives/C06JM7UUHE3) [#pciu-migration-testing](https://dsva.slack.com/archives/C085A9JCB1B)

**Comment by AshleyGuerrant** [comment]
Blocked pending this https://github.com/department-of-veterans-affairs/vets-api/pull/18729 being merged.

This work essentially serves as a "flood gate" PR where after it is merged, we will be pointing completely to VA Profile Contact Information instead of PCIU.

**Comment by nathanbwright** [comment]
@rmtolmach @AshleyGuerrant - We don't use EVSS in the `va_notify` module. We do pull some data for our [in progress reminders](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/va_notify/app/models/va_notify/veteran.rb#L55) but we use the `MPI::Service` for that - that is not related to this in any way is it?

**Comment by RachalCassity** [comment]
@nathanbwright This does not involve the MPI::Service.

**Comment by AshleyGuerrant** [comment]
Ticket handed off to the mobile team on 12/17 in this [dedicated testing channel in Slack](https://dsva.slack.com/archives/C085A9JCB1B).

**Comment by RachalCassity** [comment]
@nathanbwright At the moment, the in-progress forms are using the MPI::Service, mpi_profile_response cache, for form pre-fills. Every 24 hours, the MPI::Service will request data from the Contact Information service, va_profile_v2_contact_info_response cache. This means the MPI::Service only refreshes a user's contact info once every 24 hours. If a user updates email, address, or phone number, the pre-fill data may not be accurate.  The Contact Information Service, va_profile_v2_contact_info_response cache, is re-initialized every time a user logs in or when they modify contact info.

**Comment by AshleyGuerrant** [comment]
Hi @nathanbwright - are there any updates on the testing? Please let us know if you have any additional questions, we're happy to help.

cc @RachalCassity @LindseySaari

**Comment by nathanbwright** [comment]
@AshleyGuerrant - Re-pulling the contact info before attempting to send an email would be a possibility - but I do not think it would be worth the additional complexity given that these emails are just to remind users that they have an unfinished form. Can we simply document this as known behavior and close the ticket?

**Comment by AshleyGuerrant** [comment]
@nathanbwright - thanks for the update.
@RachalCassity & @LindseySaari - can you please review the question above?

**Comment by RachalCassity** [comment]
@nathanbwright Yes, we can close it. I was just informing your team that the email in MPI::Service is not always up to date. If a user updates their email then submits a form, the form will not have the correct email.

**Comment by kbelikova-oddball** [comment]
Closing the ticket
