### ISSUE TITLE
Test form prefills for the 10182 form (Benefits Decision Reviews Team)

### ISSUE THREAD

**Issue by AshleyGuerrant** [department-of-veterans-affairs/va.gov-team#99077]
For the PCIU migration, the Platform Product Team changed the base class pre-fill to call VA Profile. This impacts the prefill fields for form 10182 listed below:
```yaml
    veteran:
      address:
        addressLine1: [contact_information, address, street]
        addressLine2: [contact_information, address, street2]
        city: [contact_information, address, city]
        stateCode: [contact_information, address, state]
        zipCode5: [contact_information, address, postal_code]
        countryName: [contact_information, address, country]
      emailAddressText: [contact_information, email]
```
### Tasks
- [ ] Turn on flipper `remove_pciu` [**IN STAGING**](https://staging-api.va.gov/flipper/features)
- [ ] Test prefill for form 10182 in staging.
- [ ] If testing is successful, comment and close this issue.
- [ ] If issues are found (or if there are questions) reach out in [#pciu-migration-testing](https://dsva.slack.com/archives/C085A9JCB1B)

**Comment by AshleyGuerrant** [comment]
Blocked pending this https://github.com/department-of-veterans-affairs/vets-api/pull/18729 being merged.

This work essentially serves as a "flood gate" PR where after it is merged, we will be pointing completely to VA Profile Contact Information instead of PCIU.

**Comment by AshleyGuerrant** [comment]
Ticket handed off to the mobile team on 1/2/25 in this [dedicated testing channel in Slack (https://dsva.slack.com/archives/C085A9JCB1B).

The https://github.com/department-of-veterans-affairs/vets-api/pull/18729 has been merged and testing can now kick off any time.

**Comment by Mottie** [comment]
Actually, on the frontend, we only use `veteranSsnLastFour` and `veteranVaFileNumberLastFour` values. We're currently pulling in the address, email and phone numbers directly from profile. This data is already available to the frontend data store via the `/user` API call.

**Comment by AshleyGuerrant** [comment]
@Mottie - thank a lot for picking up this ticket!
I confirmed with the devs on the team, we are all set to close out this ticket. Because Form 28-8832 covers all of the same prefill fields that were relevant in this ticket, we will get testing coverage in [#99070](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99070).
