### ISSUE TITLE
Remove mentions of pre-filling information from Profile

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#99083]
⚠ Either/Or situation! ⚠ 

This ticket is dependent on https://github.com/department-of-veterans-affairs/va.gov-team/issues/96836. If we end up taking this work, we will not be pursuing the work in https://github.com/department-of-veterans-affairs/va.gov-team/issues/95534 and can close that issue out.

## Background
If we cannot pre-populate text input fields with Profile information, we'll need to remove any content for authenticated users about this functionality.

Essentially, the authenticated and unauthenticated experiences will be come the same -- blank text inputs that are not pre-populated.

## Tasks
- [ ] For **Auth non-Veteran users**, remove mentions of profile and their information pre-populating on all screens in the **Claimant** chapter.
- [ ] For **Auth Veteran users**, remove mentions of profile and their information pre-populating on all screens in the **Veteran** chapter.

## Acceptance Criteria
- [ ] If we are unable to pre-populate text inputs with Profile information, then our experience does not speak incorrectly to that being an option.

**Comment by oddball-lindsay** [comment]
We are able to pre-fill information, so this work is not needed.
