### ISSUE TITLE
Create template for Quarterly Workshops

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#99091]
## Purpose
Create a workshop series that helps Platform teams digest Quarterly Survey feedback and prioritize their work.

- We want to:
  - ensure that we focus on engineering-based teams first, and support teams second
  - conduct workshops that include only PMs and TLs
  - facilitate conversation around feedback, and creating problem statements

## Tasks
- [x] Create a mural board template based on recent workshops held
- [x] Review with Design Lead

## Acceptance Criteria
- [x] Mural board is ready
