### ISSUE TITLE
Host Q3 Survey Workshop for GT (1)

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#99090]
## Purpose
Create a workshop series that helps Platform teams digest Quarterly Survey feedback and prioritize their work.

- We want to:
  - conduct workshops that include only PMs and TLs
  - facilitate conversation around feedback, and creating problem statements

## Tasks
- [x] Schedule and host Workshop (week of 12/16)
- [x] Schedule workshop 2

## Acceptance Criteria
- [x] Workshop 1 has been conducted
- [x] Workshop 2 has been scheduled
