### ISSUE TITLE
IA Tracker: Form Builder

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#99119]
## Acceptance Criteria
- [x] IA/user flow assessment of current designs
- [x] Coordinate with other CAIA members on feedback delivery
- [x] Give feedback to team
- [ ] Ongoing collab as we try to see what of our feedback we can get implemented

**Comment by kristinoletmuskat** [comment]
Feedback documented in mural here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718989418064/02a3d8542fbe0fd70c4f6c741c51700a296502dd?wid=0-1734119430633

**Comment by kristinoletmuskat** [comment]
Ongoing collab includes attending their weekly sync, so I'm going to close this ticket. Their IA is now on the right track.
