### ISSUE TITLE
ZSF: Update burial and pension form confirm pages

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#99122]
## Description
As a part of the zero silent failures work, the product team is updating the confirmation page for the online burial and pension forms. They're updating these pages in two phases:

- Phase 1: Updating the success alert, including the "print this confirmation" section, updating the "what to expect" section, and updating the "how to contact us" section
- Phase 2: Removing the featured content box, including the "save a copy" section, and update the other benefit-specific sections for each form

## Resources
- [Keep a record of submitted information](https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information#confirmation-page-summary) (VADS pattern)
- Draft of burial confirmation screen (Figma)
- [Draft of pension confirmation screen](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/WIP---21P-527EZ---Pension-Benefits?node-id=9664-83618&t=ln0kjjKowMSpVs8o-4) (Figma)

### Phase 1
- [ ] AB: Draft recommendations for both forms with support from AP, as needed
- [ ] AB: Share recommendations with product team
- [ ] AB: Finalize recommendations with product team

### Phase 2
TBD

## Criteria
- [ ] Content recommendations have been shared and finalized with the product team for phase 1 updates
- [ ] Content recommendations have been shared and finalized with the product team for phase 2 updates

**Comment by aliyahblackmore** [comment]
I'm done with the Phase 1 recommendations in the Figma files ([burials](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=3969-25455&t=sPKSdu9I6FZ0v1qg-4) and [pension](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/WIP---21P-527EZ---Pension-Benefits?node-id=9664-83618&t=mpNuVidY7u3PrgUq-4)).  

:notebook:A few notes (cross-posting from Slack):

- I tracked adjustments on the auth and unauth screens and added comments for any items that we might need to revisit. I think that we are okay to revisit those items after staging, but before they launch (i.e. the TBD claims status tool question).
- They can refer to the 530ez auth screen to reference the specific comments about the content adjustments that span both forms. And there are some comments on the 527ez that are specific to that form.
- For right now, I more closely aligned the success alert with the VADS guidance. Since the current VADS success alert guidance is pretty specific to the submission in-progress, amount of days, and check VA status link, let's remove the last sentence from the alert for now. Our team is discussing this further. And we'll let the team know if there are any future updates they might need there.
- Re: the claim status tool - as mentioned, I left the content as is based on Gretchen's design updates. We may need to adjust for authenticated applicants once they get more confirmation about the tool and how it works with the 530ez and 527ez forms. And of course, we can revisit all of this once the status updates for these forms are available in My VA.
    And I made some font color adjustments to the process list. Whenever you do a design QA, I just recommended that Gretchen confirm the color settings are correct (i.e. for developers).
- And tomorrow or on Friday, I'll just track some of the Phase 2 or later phase future updates we can consider for the confirmation screens. I'll track those comments here.

**Comment by aliyahblackmore** [comment]
Tentative 530 Phase 2 considerations (tracking some notes here) 

- Since there's isn't an "After you submit your form/apply" page for the burials form, the confirmation screen and email contain other post-submission need to know details. We can consider leaving the details on the confirmation screen and email **or** consider leaving the details in the post submission in-progress email only.
- Can we use accordions on the "Supporting documents" section of the email for the "If" headers?
- If someone selects that they're submitting a FDC (i.e. they're uploading all documents), should we show the supporting documents information conditionally for the folks who selected "No" earlier in the form flow?

This is a [GitHub ticket that tracks](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80661) a few notes and some other more general future considerations for the form flow/designs.

**Comment by aliyahblackmore** [comment]
**Update here:**


Moving this to Blocked for now. We can revisit this work if the team needs additional content support after their staging review.
