### ISSUE TITLE
[FE, QA] 10-10CG - Facilities: Update content on facilities selection page

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#99135]
## Benefit to the Veteran
As a Veteran and/or Caregiver, I want to feel confident about the information I am reading and what it means to me, so that I can move forward without confusion.

## Background
During research sessions, we heard from Caregivers that the facility confirmation page was confusing and caused some uncertainty on what it meant, how it impacted them and if they should change something (like they did something wrong).

Design reviewed with CAIA and have update page content: 

![Image](https://github.com/user-attachments/assets/8e1df311-2529-462b-b91b-31bb3cc37417)

## Scope
- In Scope
- Content updates to the CG facility page
---
## Tasks
- [ ] [FE] Update UI to match designs
- [ ] [QA] Complete testing to validate
     - Error message content and style match
     - Error message triggering appropriately
     - Mobile view matches design and expectations
     - No new accessibility issues are introduced with this change
- [ ] Review any findings with team, if needed
- [ ] QA/PM Signoff is required in the comments

## Acceptance Criteria
- [ ] The content on the facility content page is updated for applicants to clearly understand they need to search for then select a facility.

---

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the content has been updated to match the designs

<img width="828" alt="Image" src="https://github.com/user-attachments/assets/626f39da-d410-4f2a-a2a6-c86c186d0220" />
