### ISSUE TITLE
[FE, QA] 10-10CG - Facilities: Update confirmation page content

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#99132]
## Benefit to the Veteran
As a Veteran and/or Caregiver, I want to feel confident about the information I am reading and what it means to me, so that I can move forward without confusion.

## Background
During research sessions, we heard from Caregivers that the facility confirmation page was confusing and caused some uncertainty on what it meant, how it impacted them and if they should change something (like they did something wrong).

Design reviewed with CAIA and have update page content: 

<img width="89" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFVtQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--761fac7c5e762d599a0857bd86e3d395e458853a/Form%20step.png" alt="Form step.png" />

## Scope
- In Scope
- Content updates to the CG facility conditional confirmation page
---
## Tasks
- [ ] [FE] Update UI to match designs
- [ ] [QA] Complete testing to validate
     - Error message content and style match
     - Error message triggering appropriately
     - Mobile view matches design and expectations
     - No new accessibility issues are introduced with this change
- [ ] Review any findings with team, if needed
- [ ] QA/PM Signoff is required in the comments

## Acceptance Criteria
- [ ] The content on the facility confirmation page is updated for applicants to clearly understand.

---

**Comment by hdjustice** [comment]
@jessicastump I can't access the screenshot you attached.  Is there a Figma file we can refer to?  I don't know if this work was done or not.  Thanks!

**Comment by hdjustice** [comment]
@jessicastump Nevermind, i found it.
