### ISSUE TITLE
Record a video walk through to explain the Veteran archetypes related to VHA copays

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#99145]
## Issue Description

Record a video walk through to explain the Veteran archetypes related to VHA copays. The recording can be shared. 

## Tasks
- [ ] Record video walk through
- [ ] Make it shareable
- [ ] Share with Denise

## Acceptance Criteria
- [ ] Shareable video walk through has been created

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Assign Type
- [x] Assign Priority (Normal = Medium)
- [x] Assign Group(s)
- [ ] Assign to a Project
- [ ] Attach to an Parent Epic
- [x] Estimate Points

</details>

**Comment by charlottecesana** [comment]
[Link to recording](https://cityfriends-my.sharepoint.com/:v:/g/personal/charlottecesana_cityfriends_onmicrosoft_com/EVX-BkxRQbtHoHJHr-zCxWUBl7XGfkcJK3lxG6gXmK6NCg?e=QtZBAo)
