### ISSUE TITLE
Pension: Evaluate Planned Form Changes

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#99168]
## Issue Description

As the VA I want to evaluate planned changes to the paper version of the 527EZ to determine what changes are required to keep the online pension application aligned so that I have consistency across channels. 

- Consider also opportunities to state planned content in plain language to improve applicant comprehension of what's being asked of them.
---
## Tasks
- [x] Review planned changes to the paper 527EZ in  [this Powerpoint file](https://dvagov.sharepoint.com/:p:/r/sites/vaabdvro/Shared%20Documents/Pension/pension%20raw%20data%20-%20somewhat%20reduced%20access/VAF527EZ%20Updates%20(002).pptx?d=w154394d7ab6f4a2ea979da52742758b7&csf=1&web=1&e=VOkYf1)
- [x] Propose changes to the online 527EZ to keep aligned

## Acceptance Criteria
- [x] Share high level LOE for requested changes with Product and VA enablement team
- [ ] Create next step tickets

**Comment by meggraham** [comment]
I did not create next steps tickets at this time because we are still waiting on a final list of paper pension form changes from VBA. Once we have more information about the changes to be made we will more accurately be able to determine next steps. We completed all other aspects of this ticket and decided to close it.
