### ISSUE TITLE
Begin coordinating Research Visit

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#99163]
## Background

Because we do not know exactly when this research will take place, Steve can begin looking into what needs to be coordinated for the trip and start planning where possible.

## Tasks

- [ ] Work with Lori to determine what needs to be done to coordinate this visit (locations, site contacts, VTP contacts, dates, schedule, etc.) - Anita
- [ ] Begin coordination if appropriate
- [ ] Determine who else might be going on the trip
- [ ] Document these steps/information
- [ ] Create any follow-up tickets

## AC

- [ ] Information documented
- [ ] Coordination started (if possible)
- [ ] Follow-up tickets created
