### ISSUE TITLE
Content updates to Language Assistance page in Spanish and Tagalog

### ISSUE THREAD

**Issue by moviedosoco** [department-of-veterans-affairs/va.gov-team#99167]
## Description

Our Language Assistance live page needs grammar corrections and content updates in the Spanish and Tagalog languages:
SPA: [Asistencia y recursos de VA en español](https://www.va.gov/asistencia-y-recursos-en-espanol/)
FIL:  [VA Tagalog wika mapagkukunan at tulong](https://www.va.gov/tagalog-wika-mapagkukunan-at-tulong/)

We can split the section _**Beneficios para los no veteranos**_ in two, and change it to "Benefits for survivors and dependents" and "Information for fiduciaries" or something else that may be a better fit, as per Danielle's recommendation. 

Once we settle on the language, we can send the content out to the State for Tagalog translations.

**Resources**
[Checklist for content readiness for translation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/editorial-resources/preparing-content-for-translation-checklist.md)
[Spanish translation process for static content pages](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/translation-work/spanish-translation-process.md)

## Tasks
- [ ] Update Spanish page in Drupal (Victoria)
- [ ] Review and publish Spanish page (Sara)
- [ ] Send content for translation into Tagalog to State Dept (Randi)
- [ ] Update Tagalog page in Drupal (Victoria)
- [ ] Review and publish Tagalog page (Sara)
- [ ] Send content in both languages for QA (Randi/Victoria)

## Acceptance Criteria

- [ ] Spanish page is live with changes
- [ ] Tagalog page is live with changes

**Comment by moviedosoco** [comment]
@RLHecht Hi, Randi. As you know, this page in Spanish is still in the process of being updated. Here's the Drupal node:
Preview: https://preview-prod.vfs.va.gov/preview?nodeId=20078

**Comment by RLHecht** [comment]
@juliana-jara Let's chat about this ticket. There are updates we need to make but the previous team was also wanting to rework this page so that the content was better placed under the right headers.

**Comment by juliana-jara** [comment]
@RLHecht I am ready to start work on this ticket whenever you are ready. Please let me know.

**Comment by RLHecht** [comment]
Want to put some time on our calendars this week to chat about this?

**Comment by juliana-jara** [comment]
Randi provided a GA report that shows "On this page" clicks, accordion clicks, and most visited pages (page path)

**Comment by juliana-jara** [comment]
Noting that several links need to be updated. I have added comments to [this Sharepoint document](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2399167/Spanish/Asistencia%20y%20recursos%20del%20VA%20en%20espa%C3%B1ol.docx?d=wb2ebe1f2c81e42d3a67b5cdd6136e42a&csf=1&web=1&e=MDtPZw).

**Comment by juliana-jara** [comment]
On 08/15, the GitHub repository was updated and many things switched around. The translation tracker was one of those and some information in the table has been lost. Therefore, I can't currently see the list of the Tagalog pages

**Comment by juliana-jara** [comment]
@RLHecht I'm ready to discuss the changes to these pages. I added some suggestions to the Spanish page in [this spreadsheet](https://dvagov.sharepoint.com/:x:/r/sites/oitcontentiateam/_layouts/15/Doc.aspx?sourcedoc=%7B28A49041-C60B-48D5-8431-5FEC8015D6F1%7D&file=Pages%20in%20other%20languages.xlsx&action=default&mobileredirect=true) (I color coded the rows by topic, but the most relevant rows are those at the bottom that have not yet been added to the page). The column at the right end is providing some of the recommendations related to those pages. Along with the comments about the [current page](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2399167/Spanish/Asistencia%20y%20recursos%20del%20VA%20en%20espa%C3%B1ol.docx?d=wb2ebe1f2c81e42d3a67b5cdd6136e42a&csf=1&web=1&e=qfpbda), I think we can move forward once we sync on this. 
Note that I am trying to not make too many changes to the current page to move things forward faster.
Thank you.

**Comment by juliana-jara** [comment]
@RLHecht Please let me know if you want to sync on this soon. A meeting would be ideal. However, it's been a while since I finalized this report so I'd need to revisit what I worked on to be able to better convey to you what the next steps would be. Please let me know and thank you!

**Comment by juliana-jara** [comment]
Met with Randi on 11/19

Action items and next steps:

- Move forward with Juliana's recs 
- Remove links that have been redirected 
- Create SharePoint with track changes 
- In the SharePoint, review if headers make sense or need to o away based on redirect removals

**Comment by juliana-jara** [comment]
@RLHecht 
The SharePoint drafts are ready for your review. 

- Note that some link copy can't be edited so I had to add the suggested changes in the comments.
- I also refrained from moving entire sections up/down since doing so would underscore the entire section and wouldn't let us track changes inside of the section itself, so I decided to make a comment if the section needed to be moved.

Here's the documents:

- [Tagalog](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2399167/Tagalog/VA%20Tagalog%20wika%20mapagkukunan%20at%20tulong.docx?d=wc9150a0ac7984baaa2e57780de0fa8f2&csf=1&web=1&e=0qsnuQ)
- [Spanish](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2399167/Spanish/Asistencia%20y%20recursos%20del%20VA%20en%20espa%C3%B1ol.docx?d=wb2ebe1f2c81e42d3a67b5cdd6136e42a&csf=1&web=1&e=WgCmaZ)

**Comment by juliana-jara** [comment]
Hi @RLHecht 
I just implemented most of the changes in Drupal. I am however now realizing there are 3 outstanding items that need your feedback. I'm linking them here for easy access:

1. [Intro text](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2399167/Spanish/Asistencia%20y%20recursos%20del%20VA%20en%20espa%C3%B1ol.docx?d=wb2ebe1f2c81e42d3a67b5cdd6136e42a&csf=1&web=1&e=oWB7d5&nav=eyJjIjoxNTIyMzMyNTEwfQ)
2. [Executive order](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2399167/Spanish/Asistencia%20y%20recursos%20del%20VA%20en%20espa%C3%B1ol.docx?d=wb2ebe1f2c81e42d3a67b5cdd6136e42a&csf=1&web=1&e=1IqeCe&nav=eyJjIjoxMTQ3ODk1ODQ2fQ%3D%3D)
3. [Missing link?](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2399167/Spanish/Asistencia%20y%20recursos%20del%20VA%20en%20espa%C3%B1ol.docx?d=wb2ebe1f2c81e42d3a67b5cdd6136e42a&csf=1&web=1&e=ZyOefC&nav=eyJjIjo0MDgyMDMwMn0%3D)

**Comment by juliana-jara** [comment]
Updated Spanish page in Drupal

**Comment by juliana-jara** [comment]
Updated both pages in Drupal:

- Spanish: https://prod.cms.va.gov/node/20078/revisions/1052955/view
- Tagalog: https://prod.cms.va.gov/node/20092/revisions/1052954/view

@RLHecht this is ready for your review.
