### ISSUE TITLE
Add link to list of VRCs to IDES page

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#9916]
## Issue Description
_Request from Bettye Hodge and Robyn Turlock to build VSOC counselor page on VA.gov. The page should be easily updatable as new states and counselors are added or subtracted on an ongoing basis_

---
## Tasks
What work is necessary for this story to be completed?
- [x] Anne and Beth to regroup with Bettye, Robyn to list all tasks needing to be done.
- [ ] ~~new page(s) to be added to VA.gov~~ 
- [ ] ~~Content strategy to determinr spreadsheet/csv vs. accordions - Beth, Anne~~
- [ ] Add link to IDES page once we have the url from stakeholder

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
--------
Jen Lee's notes: 
Call summary: 
1/ Migrating VSOC contacts list via our new CSV Drupal upload process to VA.gov
2/ Adding IDES contacts list to VA.gov using same method
3/ Bettye, Robyn, and Anne will work together on getting the right data fields and format for the upload; Anne will then work on the content strategy for where/how to incorporate this information
 
Open question needs resolving: 
•	What happens when a new row or section is added in the CSV? Will this break the Drupal table, how do we need to address that? EX: For VSOC list, when a new state is added; or when more individuals are added. 
•	We also didn’t discuss ETA. Please work with Anne to determine target desired ETA, so we can properly queue this into our backlog. 
 
 
Pages we looked at: 
https://staging.va.gov/careers-employment/vetsuccess-on-campus/ VetSuccess on Campus content page
https://www.benefits.va.gov/vocrehab/vsoc.asp - VSOC contacts list
https://staging.va.gov/careers-employment/vocational-rehabilitation/ides/ IDES content page

**Comment by stephorkandatx** [comment]
Further discussion needed on the process, import/adding rows and how this will be updated

**Comment by stephorkandatx** [comment]
This is being kept out of sprint 24 commitments, but may be brought back in once further discussion takes place

**Comment by AnneHurley** [comment]
@stephorkandatx @bethpottsVADEPO I agree and think we should also prioritize against other tickets. Since this information is already findable online, it may make more sense to put this in backlog till the rates historic pages and new rates spreadsheets can be completed. @jenniferlee-dsva  FYSA

**Comment by bethpottsVADEPO** [comment]
The long-term solution is now to add the needed contact info for VSOC counselors and VRCs to the Learning Center. The immediate-term way forward for this, after a convo with @jenniferlee-dsva , is to add a link to the IDES page that goes to a list of VRCs. A similar solution was already implemented on the VSOC page with a link to the teamsite page that lists the counselors and their contact info. I'm waiting to hear back from Bettye about whether there's a teamsite page for the VRC info. 

Will update this ticket to account for the new direction this work is taking. And then we should be able to close it.

@AnneHurley Your task now will be to add a link to the IDES page once we have the correct URL.

**Comment by AnneHurley** [comment]
Blocked as we await URL from stakeholders.

**Comment by FranECross** [comment]
Outdated/obsolete ticket. Closing.
