### ISSUE TITLE
Burial: Evaluate Planned Changes to Form

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#99171]
## Issue Description

As the VA I want to evaluate planned changes to the paper version of the 530EZ to determine what changes are required to keep the online burial application aligned so that I have consistency across channels. 

- Consider also opportunities to state planned content in plain language to improve applicant comprehension of what's being asked of them.
---
## Tasks
- [ ] Review planned changes to the paper 530EZ in [this PowerPoint file](https://dvagov.sharepoint.com/:p:/s/vaabdvro/EXsBBrkKPuRCk_RIZf86KQwB3kuVBWxeGfn5l4B0XTm6Ew?email=MATTHEW.REILLY1%40va.gov&e=KfqUVG)
- [ ] Propose changes to the online 530EZ to keep aligned

## Acceptance Criteria
- [ ] Share high level LOE for requested changes with Product and VA enablement team
- [ ] Create next step tickets

**Comment by meggraham** [comment]
Closing this ticket because [Dene shared](https://dvagov.sharepoint.com/:f:/s/vaabdvro/EtORh5NCnQpBvswHOIGv30wBEyTcrPVXgLfjKdO6eWGvTg?email=MATTHEW.REILLY1%40va.gov&e=UxxTK7) that, "It looks like Burial will not change other than the date and OMB#. So it seems Burial updates will be more on the engineering side and don't need to be evaluated by design."
