### ISSUE TITLE
[CST] Remove sentence from file uploader

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#99180]
## Background Context
@jstrothman asked that we remove the sentence 

> Please only submit evidence that supports this claim. To submit supporting documents for a new disability 
> claim, please visit our [How to File a Claim page (opens in a new tab)](https://staging.va.gov/disability/how-to file-claim) .

It currently appears on the Document Request page and the Files Page.

![Image](https://github.com/user-attachments/assets/acd54885-ffd6-4ac4-827d-a3574d781adf)

## Engineering 
- Changes will be on the AddFilesForm component

## Out of scope
- Add here

## Open questions
- Add here

## Tasks

- [ ] remove sentence from the AddFilesForm component
- [ ] update unit tests
- [ ] update cypress tests

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Document Request page no longer shows the sentence
- [ ] Files Tab no longer shows the sentence

**Comment by skylerschain** [comment]
Nope, I have no problem removing it.

**Comment by skylerschain** [comment]
LGTM 👍
