### ISSUE TITLE
OH Staff scheduling process documentation

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#99197]
## Task Description
Document the Oracle Health staff scheduling process by reviewing SOPs, past research, and discussions with stakeholders and engineers. Outline the steps for Veterans and staff, including the systems and services involved. Identify points of data collection, storage locations, and any gaps. Use this to determine OH requirements.

## Notes and References
- [SOP For OH self-scheduling](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/scheduling-improvements/scheduling-improvements.md#:~:text=Cerner%20Millennium%20Patient%20Self%2DReferral%20Direct%20Scheduling%20SOP%20%2D%20update_05302023%2D%20Signed.pdf)
- [OH requirements ](https://dsva.slack.com/archives/C062LRFAX7S/p1734109010148489)thread with Kay

## Acceptance Criteria
- [x] Create basic structure in Mural for the OH Staff scheduling process
- [x] Discuss each step in the process with Simi when he finished the [ZSF diagram](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98555)
- [x] Update [Feature reference](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference#start-of-scheduling-flows) when needed

## Deliverables
- [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1733936198041/4029e6dcd2ab87463b55d31c1f659af384bf54c3?sender=uc6180068871478c530ab2434)

---
## How to configure this issue
- [ ] Add title and task description
- [ ] Attach to an Epic
- [ ] Add labels based on work type: design, discovery, documentation, strategy
- [ ] Delete this section

**Comment by melissa-lefevre** [comment]
Created a slide deck to present to IVC. Marking done
