### ISSUE TITLE
[Eventbus Gateway] Upgrade to Rails 8

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#99198]
### Background
When we generated the new rails app for the Evenbus Gateway, we used Rails `7.1.5.1`. Rails is currently on major version 8 and we should be able to use it instead of `7.1.5.1`. It is more ideal to upgrade to Rails 8 now before we add more of our own code to the application

### Tasks
- [x] Generate a new rails app with Rails 8
- [x] Migrate the code changes from the old app over to the new one
- [x] Push the new app to the `eventbus-gateway` repo

### Acceptance Criteria
- [x] The `eventbus-gateway` app is using the latest version of Rails
