### ISSUE TITLE
Update guidance for imposter component checks to reassign to design practice area

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#99204]
## User Story
As a Governance team member supporting Collab Cycle, I want to update the guidance and documentation for imposter component checks so that it is specified as a design responsibility not a QA responsibility.
 
Assignee: @allison0034 
Peer Reviewer: @rsmithadhoc 

## Description
When Governance was tasked with checking VA.gov products at Staging Review for imposter components, it logically made sense for our former QA specialist, Ian, to take on that responsibility because Ian supported the Design System team 50% of the time. He was very familiar with the design system components and could easily identify when a component was not in use.

Checking for imposter components is the only task within the QA list of responsibilities at Staging Review that requires the QA specialist to complete E2E testing. All of their other responsibilities fall within the scope of QA standards and verifying that appropriate artifacts are present and meet our expectations.

The purpose of this 2 part effort is to transition the responsibility of checking for imposter components to the design practice area specialist as the design specialist should also have strong familiarity with the VADS components.

This is part 1 of a 2 part ticket. This ticket includes updating guidance and documentation to transition imposter component checks from the QA practice area to the design practice area. Part 2 ticket - #116764

### Live pages
- [How to complete a QA review for Staging Review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+the+Staging+review+touchpoint)
- [How to complete a design review for Staging Review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2302869722/How+to+complete+a+design+review+for+Staging+review+touchpoint?atl_f=PAGETREE)

### Drafted pages
- 

## Tasks
- [x] Review the how to complete a QA review for SR doc and identify where "imposter components" are included within the guidance.
- [x] Move the "imposter component" guidance from the QA doc to the Design doc
- [x] Clean up both guidance docs so that they flow smoothly and are easy to understand and follow
- [x] Review all other operational guidance on Collaboration Cycle. Confirm that there are no other locations where guidance needs to be updated.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have updated the operational guidance for QA so that it no longer includes checks for imposter components at SR
- [x] We have updated the operational guidance for design so that it includes checks for imposter components at SR
- [x] We have verified that no other operational guidance needs to be updated to reflect the transition of imposter component checks from QA to design

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Notes from refinement on 1/13:

- We assumed teams would become aware and imposter components would lessen. This hasn't happened.
- Maybe we need a more specific consistency standard. Can be for components and standards.
- Diff bw imposter component bc it doesn't behave, act or look like it's supposed to. VS. imposter component that looks, feels and acts the same, is more of a process problem. 
- Many teams ignore the guidance from CAIA. Given specific guidance for IA (breadcrumbs, etc.) and they completely disregard it.

**Comment by shiragoodman** [comment]
Shira to take this back to Matt for discussion.

**Comment by rsmithadhoc** [comment]
@allison0034 This looks good, thanks!
