### ISSUE TITLE
Add clarity in CC Request ticket if a touchpoint is required

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#99218]
## User Story
As a VFS team, I want to be able to easily see which touchpoints are required so that I don't always have to reference the Platform Website for that information.

Assignee: @erinrwhite 
Peer Reviewer: @shiragoodman 

## Description
The purpose of this ticket is to update the Collaboration Cycle code blocks to note which touchpoints are required. 

Notes from tech-debt meeting on 8/8:

- ONLY mark the touchpoints that are required (ie no "optional" labeling)
- Add required to the touchpoint headings within the CC Request ticket

At this time, the required touchpoints are PO Sync, Architecture Intent and Staging Review. (PSIRR is still currently required, but it will be phased out starting in Sprint 8 per ticket #116460.) PO Sync is only required for OCTO and VES teams. How do we want to communicate that via the ticket?

### Live pages
- 

### Drafted pages
- 

## Tasks
- [ ] Edit the code blocks

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have modified the Collab Cycle code blocks to specify if a touchpoint is required

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
ok, thanks @shiragoodman !
