### ISSUE TITLE
[CST] Remove unused feature toggles from vets-api

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#99228]
### Background
We are no longer using the `cst_use_lighthouse_index`, `cst_use_lighthouse_show`, and `cst_use_lighthouse_5103` feature toggles in `vets-website` so we should remove them from `vets-api`

### Tasks
- [x] Remove the `cst_use_lighthouse_5103` feature toggle from `config/features.yml`
- [x] Remove the `cst_use_lighthouse_index` feature toggle from `config/features.yml`
- [x] Remove the `cst_use_lighthouse_show` feature toggle from `config/features.yml`

### Acceptance Criteria
- [x] Unused feature toggles starting with `cst_use_lighthouse` have been removed from 'config/features.yml`

**Comment by pmclaren19** [comment]
Blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/99230 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/99231

**Comment by jerekshoe** [comment]
Feature toggles have been removed from the DB in all environments (dev, staging, prod)
