### ISSUE TITLE
[CST] Remove `cst_use_lighthouse_5103` code from claim status vets-website

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#99230]
### Background
We are at a point where we should be able to remove the `cst_use_lighthouse_5103` feature toggle from the `claims-status` application. This includes removing EVSS related code for submitting 5103s as well. **NOTE:** The feature toggle will be removed from `src/platform/utilities/featureFlagNames.json` and `vets-api` in separate tickets

### Tasks
- [x] Remove cst_use_lighthouse_5103 from claim status
- [x] Remove from tests

### Acceptance Criteria
- [x] The `cst_use_lighthouse_5103` feature toggle has been removed from `claim-status`
- [x] Code related to calling EVSS for submitting 5103 requests has been removed from `claims-status`

**Comment by pmclaren19** [comment]
This ticket blocks https://github.com/department-of-veterans-affairs/va.gov-team/issues/99231
