### ISSUE TITLE
[CST] Remove unused feature toggles from vets-website

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#99231]
### Background
There are a few feature toggles that are not being used anymore in `vets-website` and that can be removed from the platform code. These include all feature toggles that start with `cst_use_lighthouse_`.

### Engineering Notes
- Feature toggles can be found in `src/platform/utilities/featureFlagNames.json`
- The full list of feature toggles is:
  - `cst_use_lighthouse_5103`
  - `cst_use_lighthouse_index`
  - `cst_use_lighthouse_show`

### Tasks
- [ ] Remove the `cst_use_lighthouse_5103` feature toggle from `featureFlagNames.json`
- [ ] Remove the `cst_use_lighthouse_index` feature toggle from `featureFlagNames.json`
- [ ] Remove the `cst_use_lighthouse_show` feature toggle from `featureFlagNames.json`

### Acceptance Criteria
- [ ] All feature toggles beginning with `cst_use_lighthouse_` have been removed from `featureFlagNames.json`

**Comment by pmclaren19** [comment]
blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/99230
