### ISSUE TITLE
[Rated Disabilities] Remove code related to EVSS

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#99232]
### Background
We have been at 100% with Lighthouse Service History and Eligibility for several weeks now so it is time to remove the code related to the EVSS version of the application.

### Engineering notes
 Remove the logic associated to the ff `rated_disabilities_use_lighthouse` for when it is disabled (evss version)

### Tasks

- [x] remove evss logic from the components take a look at RatedDisabilityView and start there
- [x] remove feature toggle: `rated_disabilities_use_lighthouse`
- [x] remove / update tests as needed

### Acceptance Criteria
- [x] Code related to the EVSS version of the Rated Disabilities app has been removed from `vets-website`
- [x] remove ff `rated_disabilities_use_lighthouse`
- [x] remove tests and update tests
