### ISSUE TITLE
[Design debt] Revisit "Documents" vs. "Files" vs. "Evidence" language in CST

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#99244]
---
## Background Context

We are using all of these terms. Clean up how we use them for consistency throughout CST.

Source: [Figma comment](https://www.figma.com/design/m1Xt8XjVDjZIbliCYcCKpE?node-id=2771-20641#1062900850)

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@jstrothman 

### Other collaborators
@laurwill @kristinoletmuskat 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] _Clean up how we use them for consistency throughout CST_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

**Comment by jstrothman** [comment]
When we work on this, we should consider:
1. New [VADS guidance on the special topic -  claims and applications](https://design.va.gov/content-style-guide/specific-topics-and-programs/claims-and-applications), specifically when/how to use the terms: document, evidence, file
2. [Figma thread](https://www.figma.com/design/m1Xt8XjVDjZIbliCYcCKpE?node-id=2771-20258#1056907882) with Laura Willwerth

**Comment by skylerschain** [comment]
We did a lot of work on this and incorporated the latest thinking into the [Document Status final spec](https://www.figma.com/design/m1Xt8XjVDjZIbliCYcCKpE/Document-status?node-id=4107-89075&t=lQ0mLxd5SMu35r2h-4).

I've also created a [Word List](https://www.figma.com/design/lbRZz68qGRGTdUigcoJq3a/Local-Benefits-Tools-Components?node-id=1051-1342&t=77MEiwFfdnHDEFQ9-4) documenting our approach to the use of "Files," "Documents," and "Evidence" in CST.
