### ISSUE TITLE
[FSR] Updated 180 day verbaige to 1 year after December 23, 2024

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#99240]
## Issue Description
Given: A veteran views the FSR 
When: A veteran uses the wizard     
Then: They should see a `1 year` term instead of `180 days`

Related ticket: #97683
Related slack thread: https://dsva.slack.com/archives/CPE4AJ6Q0/p1733878520869279

## Tasks
- [x] Update `180 days` to `1 year` in the wizard and subtask in Figma/Prototypes and code   

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [X] Not Required           

## Acceptance Criteria
- [x] `180 day` term has been updated in wizard and subtask figma mockups/prototypes 
- [x] `180 day` term has been updated in production on the wizard 

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Assign Type
- [x] Assign Priority (Normal = Medium)
- [x] Assign Group(s)
- [x] Assign to a Project
- [x] Attach to an Parent Epic
- [x] Estimate Points

</details>

**Comment by josephrlee** [comment]
@dhill802 @Tom-Davis @denisecoveyduc bringing this in since I've got some bandwidth!
