### ISSUE TITLE
Connect BGS dev to `webtestbepbenefits`

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#99243]
## User Story
As a security precaution, I want to point dev to the BGS dev environment, so that we don't have PII in our lower environments.

## Issue Description
Connect BGS dev to `webtestbepbenefits` in [fwdproxy-vagov-dev-vars](https://github.com/department-of-veterans-affairs/vsp-platform-fwdproxy/blob/main/fwdproxy-config/fwdproxy-vagov-dev-vars.yml). The key and cert fields might also need updated. You can use this draft PR (or create your own): https://github.com/department-of-veterans-affairs/vsp-platform-fwdproxy/pull/508.

### Notes
- See last bullet point of [the meeting notes](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3691577408/BGS+pre-prod+connection+meeting+notes#Action-Items) with the BGS team. 
- Details about `curl`ing things through the fwdproxy here https://vfs.atlassian.net/wiki/spaces/OT/pages/2521043009/Debug+forward+proxy+issues#More-steps
- We can spin up a fwdproxy preview and test.
- We generate the cert and key through Venafi (we already have one to use), and we pass them the public cert. Based on that, we may not need to generate a new cert.
- We currently use `forward-proxy-lowers.crt` for certs, and ideally we continue using that cert for all environments lower than prod.

`prepbepbenefits` is a pre-production environment. While it does not currently contain veteran data, this environment is migrating to the production BEP VAEC AWS Virtual Private Cloud (VPC) environment (target date is July 2025) which may contain veteran data, so we need to move off of it. `pre-prod` is the first BGS env that has mTLS in it, so we are missing out on that by making this change. Investigate whether it's important for Dev to have mTLS.

## Tasks
- [x] Meet with DevOps CoP for mTLS and cert questions
- [x] Swap `prepbepbenefits` with `webtestbepbenefits` (can steal [this PR](https://github.com/department-of-veterans-affairs/vsp-platform-fwdproxy/pull/508)) - might need to coordinate with BGS team. 
- [x] Update certs and keys as needed ([BGS certs for staging](https://github.com/department-of-veterans-affairs/vsp-platform-fwdproxy/blob/87ba39e6f9f1389088f1a508d0c9450b0368c43f/fwdproxy-config/fwdproxy-vagov-staging-tasks.yml#L88-L91))
- [x] Test before merging (by using the `Preview` label explained in the README) or test after merging in dev.

## Acceptance Criteria
- [x] PR merged
- [x] Tested
---

## Validation
- Made sure the daily deploy was successful https://github.com/department-of-veterans-affairs/vsp-platform-fwdproxy/actions/workflows/deploy-daily.yaml
- Find the instance id in AWS in the ASG for the env. 
- Use that in the command
```
aws ssm start-session --target [i-xxxxx] --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["bgs port"], "localPortNumber":["any port"]}'
```
- Navigate to https://localhost:port-from-above/BenefitClaimServiceBean
- The WSDL should show the correct host.

**Comment by rmtolmach** [comment]
PR is ready for a devops review https://github.com/department-of-veterans-affairs/vsp-platform-fwdproxy/pull/508

**Comment by rmtolmach** [comment]
PR is merged. @Kshitiz-devops, how can this work be validated?

**Comment by rmtolmach** [comment]
Tested with Kshitiz using the validation tesps above.  The forwarding with dev looks good

<img width="861" alt="Image" src="https://github.com/user-attachments/assets/eaeb501a-79bb-4a15-8e6f-5ae020afa4c8" />

And sandbox looks good
<img width="844" alt="Image" src="https://github.com/user-attachments/assets/59bc9bbe-7ceb-4d58-abc7-0a133f3287bb" />
