### ISSUE TITLE
[Design debt] Revisit status story for objects in CST

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#99245]
## Background Context

With the introduction of "in progress" for documents, we now have competing status visual treatments and concepts for documents in CST. The goal of this ticket is to revisit that and decide if it makes sense to clean up the "status" story in terms of wording and visual treatment. 

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@jstrothman 

### Other collaborators
@laurwill @kristinoletmuskat 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] _Revisit that and decide if it makes sense to clean up the "status" story in terms of wording and visual treatment. _
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

**Comment by skylerschain** [comment]
We are going to work on this – we created a new ticket for it [here](https://github.com/orgs/department-of-veterans-affairs/projects/1549/views/3?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C149737419%2C149737418%2C149737417%2C%22Labels%22%5D&filterQuery=design+%22redesign%22&pane=issue&itemId=96636431&issue=department-of-veterans-affairs%7Cva.gov-team%7C102493).
