### ISSUE TITLE
[Copy] Profile 2.0 Content

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#9927]
##Background

With all of the design changes to the profile - we want to make sure that all the content is streamlined and concise. 

##Invision mocks

Desktop: https://vsateams.invisionapp.com/share/FJW9OGY2B9A
Mobile: https://vsateams.invisionapp.com/share/34WJ8JOCMAB

##Tasks

- [x] Personal and contact information
- [x] Military information
- [x] Direct deposit information
- [x] Account security
- [x] Connected apps

##Acceptance criteria

- [x] All sections have been reviewed and appropriate tickets have been made.

**Comment by peggygannon** [comment]
Hi, @tressaellen  Please see below for content updates to Profile 2.0.  Recommendations below don't include Connected apps. That will come to you on Monday. Please let me know if you have any questions. 



1. Personal and contact information

- Postal code label should be sentence-cased 

- Phone numbers should be in this format: xxx-xxx-xxxx

- I suggest tightening up this content a bit more. Recommend: We’ll send VA health care appointment text reminders to this number

- Contact email address box
What do you think about putting the contact email address field right below intro sentence? 
So it would read: 
This is the email we’ll use to contact you.
Contact email address field
then, 
To update the email you use to sign in, please go to the website where you manage your **sign in** information. 
[link]

Note, please use "sign in" not log in for this message. 


- Add period to end of this sentence: 
I live on a United States military base outside of the United States. 

- Please update this message: 
We’re sorry for the delay. This update could up to 30 minutes to save. You can close this section and we’ll let you know when it’s been saved. 

- Update your unit number message.  Should the blue button say “Continue” rather than Update? (see screenshot below)



![2020-06-11.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/e3f3fb12-6852-4bb6-80a2-efdc8d2b70b1)!

 

- Update this link "Which of my benefits will use this contact information?" 
TO
How will you use my contact information? 
We’ll use this information to contact you about certain benefits and services, like disability compensation, pension benefits, and claims and appeals. If you’re enrolled in VA health care, we’ll send your prescriptions to your mailing address. Your health care team may also use this information to contact you. 

- Screens 15-18 have no content in desktop version

- “We’re unable to retrieve” alert 
Please update this alert to: 
**We can’t access your contact information**
We’re sorry. Something went wrong on our end. Please try again later. 


Screen 19: Are you sure? alert
What is this message referring to? 

"You are currently editing" message. 
Please update the content TO: 

**You’re editing your [section]** (no period)
Please save or cancel your work before editing a new section of your profile. If you cancel, your in-progress work won’t be saved. 

Should the buttons read? See screenshot below says OK, which doesn't give much direction to user
Cancel
Save

the button in the mobile version says “Disconnect” which doesn’t seem like correct option.

![2020-06-11 (1).png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/b9158655-0eb6-4003-b445-e91157003a82)

----------------


2. Military information screens


- Under "What if my military service information doesn't look right?" link
Please fix misspellings of “Defence” in this message.  It should be Defense

----------

3. Direct deposit screens

- Please add back the time zone to the bank fraud Note

If you think you’ve been the victim of bank fraud, please call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. **ET.**

- Under this link:  How do I change my direct deposit information for education benefits. 

Please make these boldface: **Premium DS Logon** **My HealtheVet** and **ID.me**

- Under Disability comp and pension header

Please update this sentence to:

Please enter your bank’s routing and account numbers and your account type.


- “what’s my bank routing number” helper link.. is there content under this link? Also this link seems like it might be duplicative to “where can I find these numbers” link? 

-------

4. Account security screens 

- Sign in address content: please update to reflect change we made on the contact information screen
Instead of “go to the account” please change to “go to the website where you manage your settings and identify information….”

- Suggest updating link language to: Update **sign-in** email address on [name of account]

- “Verify your identity” alert.. Please change the hyphens to dashes in this content. 

- Green CTA button: I’ve never seen a CTA button language that include the name of the account. Is this  a new pattern?  
I suggest changing this button to simply: Verify my identity to match how we treat this other places on the site. 

- Here is an additional content recommendation to tighten up this alert even more: 

**We can’t match your information with our Veteran records**

We’re sorry. We can't give you access to health and benefit tools until we can match your information with our records and verify your identity.
If you’d like to use these tools on VA.gov, please contact your nearest VA medical center to verify and update your records.
[Find your nearest VA medical center]

- Please update Terms and conditions content to the below, per this ticket https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/8824

Before using our health tools, you’ll need to read and agree to the terms and conditions for medical information. This will give us permission to share your VA medical information with you. Once you do this, you can use the tools to refill your VA prescriptions or download your VA health records.
[Go to the terms and conditions for medical information](link to terms and condition page)

**Comment by tressaellen** [comment]
@peggygannon thank you so much for this! I'm going through and updating, but I have a few questions/answers.

1. Personal & Contact information:

- This is what the updated contact email content looks like. I personally prefer the original option, I'm nervous we'll have the same issue where people don't read the text below it. It also makes the the actual email address easier to find. But I'm definitely open to feedback or if you disagree at all.
<img width="736" alt="Screen Shot 2020-06-15 at 9 23 34 AM" src="https://user-images.githubusercontent.com/58752772/84676156-9fc75b00-aed9-11ea-9cc0-222a194cc1bb.png">
 
- Screen 19 is referring to warning a user when exiting edit mode with unsaved data (issue #9769 )
- 'You are currently editing content' is being tracked in #9784 . I'm waiting for Erik to respond and then we'll know which direction will work.

- I updated screens 15-18 in the prototype, not sure what happened there.

<br />

2. Military information 

- Could you take a look at issue #7553 and make any suggestions for that alert?

<br />

3. Direct Deposit

- Here is the content for "What's my bank routing number' helper link: Your bank’s routing number is a 9-digit code that’s based on the U.S. location where your bank was opened. It’s the first set of numbers on the bottom left of your paper checks. You can also search for this number on your bank’s website. If your bank has multiple routing numbers, you’ll want the number for the state where you opened your account.

I also think this is pretty duplicative of the “where can I find these numbers” link - I'd love to remove the "What's my bank routing number'. What do you think?

- Could you take a look at the text for adding bank information (this is new and was not in the prototype - tracked in #8757 ) I'm specifically looking for any changes in the verbiage for 'Please add your bank information'.
<img width="719" alt="Screen Shot 2020-06-15 at 9 42 57 AM" src="https://user-images.githubusercontent.com/58752772/84677917-daca8e00-aedb-11ea-87c6-5e464679a203.png">

<br />

4. Account Security

- No questions here, this all seems great. :)

**Comment by tressaellen** [comment]
Oh actually - @peggygannon , one thing with Account security - the green button is from a different page on the site, I just copy and pasted it. I can find it if you need. Or we can change what is on the button if you prefer.

**Comment by peggygannon** [comment]
Hi, @tressaellen some responses for you!

1. that's fine.. I defer to you on the design. I was just offering up an option. 

2. re: *Screen 19 is referring to warning a user when exiting edit mode with unsaved data (issue #9769 )*
I responded in this ticket.. Please let me know if you need anything else from me? 

3. re: *'You are currently editing content' is being tracked in #9784 . I'm waiting for Erik to respond and then we'll know which direction will work.*
I responded in this ticket. Please let me know if you need anything else from me? 

4. re: *Military info alert* I responded in that ticket. Please let me know if you need anything else from me? 

5. I do think we should remove the "What's my bank routing number?" link, as the bank routing content appears under the link "Where can I find these numbers" and also we show users the image of the check, so it seems clear to me. 

6. Account security. Yes, I do recommend we change the CTA button language to: Verify my identity

**Comment by tressaellen** [comment]
Thank you! I'll incorporate all of this.

**Comment by tressaellen** [comment]
FE changes tracked in #10596
Updated Copy document tracked in #10683
