### ISSUE TITLE
[FSR] - Fix Employment Work Date Validation for Mobile

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#99274]
## Issue Description
Employment work dates does not validate correctly on mobile browsers preventing users from continuing through the form workflow.            

## Tasks
- [x] I have reviewed the code changes and they align with the ticket's acceptance criteria.
- [x] I have pulled the branch and manually tested the changes (if applicable).
- [x] The changes do not introduce any new linting warnings or security vulnerabilities.
- [x] Any new or updated tests are passing.       

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] Item one from the description performs as described in the description
- [x] Item two from the description performs as described in the description      

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [x] Description written
- [x] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [x] Assign Type
- [x] Assign Priority (Normal = Medium)
- [x] Assign Group(s)
- [x] Assign to a Project
- [x] Attach to an Parent Epic
- [x] Estimate Points

</details>

**Comment by amponce** [comment]
Adding myself to this ticket, to assist with the debugging

**Comment by amponce** [comment]
We’ve identified the issue as an isolated mobile bug, likely caused by the recent update from moment to date-fns. Unfortunately, due to contract limitations, we don’t have enough time to resolve, test, and deploy the fix.

**Comment by amponce** [comment]
PR is up  https://github.com/department-of-veterans-affairs/vets-website/pull/33753

**Comment by amponce** [comment]
Here’s how we replicated the bug locally. On the employment dates page, we entered an incomplete date like ‘January 202’ and hit submit, which triggered the error message: ‘Please enter a valid employment start date.’ After adding the missing ‘1’ to make it ‘January 2021’ and hitting submit again, the error still persisted. Only after deleting and re-entering the ‘1’ were we able to proceed.

Our suspicion is that, specifically on mobile, validation might have been triggered too early while the user was still typing, leaving the field in a ‘dirty’ state and preventing progress. While it’s tricky to verify locally, we’ll confirm the fix on stage to ensure it’s resolved.

**Comment by amponce** [comment]
The PR has been merged, and will go live when code freeze is lifted

**Comment by amponce** [comment]
Will verify fix on stage and report back in this ticket.

**Comment by amponce** [comment]
Staging test failed, we're back to creating a mobile specific bugfix
