### ISSUE TITLE
[Eventbus Gateway] Create a GH Action to update the image tag on push

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#99288]
### Background
So far we have it set up so that a new image is pushed to ECR every time a new commit is made to main for the `eventbus-gateway` and the argo app is re-deployed every time a change to the helm charts is committed. In order for the new image in ECR to be deployed to the argo app, we currently have to manually update the image tag and commit the change to `vsp-infra-application-manifests`. Ideally this would be automated so that the image tag gets updated at the same time that the new image is pushed to ECR. We can do this via GH actions so we need to create a new workflow to accomplish this

### Tasks
- [x] Create a new IAM policy for access to the `/devops/VA_VSP_BOT_GITHUB_TOKEN` parameter and apply it to the GHA OIDC role so that it can commit to the `vsp-infra-application-manifests` repo
- [x] Create a Github action that updates the image tag in the helm chart in the `vsp-infra-application-manifests` repo whenever a commit is pushed to main
- [x] When the terraform changes have been applied, test that the Github action is working as expected

### Acceptance Criteria
- [x] The image tag in the helm chart is updated automatically on every commit to main in the `eventbus-gateway` repo

**Comment by jerekshoe** [comment]
I have merged the PRs to add the Github Action to the `eventbus-gateway` repo and to add a new IAM policy that gives access to the SSM param for the GHA OIDC IAM role. Waiting on the terraform changes to be applied and then I can see if the GH action works as expected
