### ISSUE TITLE
VA Form 21a v5 Midpoint Feedback Updates

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#99287]
Updates to designs based on Midpoint Feedback. Once complete recommendation is to user test the flow.

Current design status:
- Figma designs have captured OGC's latest requests, but need to be updated based on the Midpoint feedback linked above.

Future things to keep in mind, to get release ready:
- This has been mostly developed and approved, but we will need additional development based on Midpoint Review updates.
- OGC also needs to actually update the form before we release these developments, so our developments match the up-to-date form expectations.

## Tasks

[Link to midpoint feedback summary.
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representative-facing/21a-digital-accreditation.md#proposed-next-steps)

[Design Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92899):
- [ ] SHOULD: Include mobile designs in the future
- [ ] SHOULD: Use the [tile radio button component](https://design.va.gov/components/form/radio-button#tile) for the mailing address question

[Content Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93072):
- [ ] MUST: Use contractions
- [ ] MUST: Try to use plain language where possible

[Accessibility Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93097):
- [ ] MUST code the custom header and footer in ways that are accessible
- [ ] MUST make any H3 unique text (don't repeat the text below or on other pages)
- [ ] SHOULD consider and mock the mobile experience
- [ ] SHOULD strive for more plain language
- [ ] SHOULD give more explanations around the questions about physical limitations (see IA feedback above)

[IA Feedback ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93069):
- [ ] MUST open any links in a new tab and add text saying they will do so
- [ ] SHOULD: Give a visual cue that Veterans are in the wrong place (similar to the blue alert we have on [21-22 mocks](https://www.figma.com/design/LVCQBuW7a6nfVFNyhA4kv4/ARF---Form-21-22-Design-Explorations?node-id=854-146725&t=RqUG2a8vMUfxnfaI-1))
- In Step 6 specifically...
   - [ ] SHOULD: Shorten the H3s
   - [ ] SHOULD: Add missing heading on the [conditions or impairments](https://www.figma.com/design/2afIGOMII0uRI5ck1dWo1w/ARF---Form-21a---Apply-for-Accreditation-(CA-%26-Attorneys)?node-id=1026-24112&t=nOYR6et7OrNqA16g-4) page
      - (Note from ARF Design: as a rule of thumb, we only included H3s on a page if 1) there were multiple fields that were thematically grouped together and 2) they needed a header to make sense of them. An example would be "Employer address". You could understand a field on this page labeled "City," but you might not know which city you should add without the "Mailing address" header. For pages that only had 1 field, we did not see a need for an H3. It's possible that we weren't consistent with this across the dozens of pages in the form. Future teams can assess if/when H3s seem appropriate. We suggest working with CAIA on this.)
   - [ ] SHOULD: Add a note about if physical limitations will impact your application
   - [ ] CONSIDER: Adding a warning about sensitive questions ahead of Step 6
   - [ ] CONSIDER: Clarify language, or create two separate questions, for conditions/impairments pages. The [conditions or impairments](https://www.figma.com/design/2afIGOMII0uRI5ck1dWo1w/ARF---Form-21a---Apply-for-Accreditation-(CA-%26-Attorneys)?node-id=1026-24112&t=nOYR6et7OrNqA16g-4). It combines substance use disorders and mental illness 
as potential factors to consider for fitness to serve.
   - [ ] CONSIDER: Update disability and substance abuse disorder language on conditions/impairments pages. This section uses some out of date language around disability and substance abuse.

## Acceptance Criteria

- [ ] The Midpoint Feedback above has been incorporated into v5 designs.
- [ ] The related Midpoint Review tickets linked above can be closed out.

**Comment by mtri** [comment]
Next steps consolidated on https://github.com/department-of-veterans-affairs/va.gov-team/issues/106814
