### ISSUE TITLE
EVSS Deprecation and Migration Discovery

### ISSUE THREAD

**Issue by AshleyGuerrant** [department-of-veterans-affairs/va.gov-team#99294]
## User Story
As the Managers and Developers of the VA Platform,
We need to perform discovery on the connected EVSS services/sub-services Platform owns within Vets API,
So that we can prepare for the EVSS deprecation and migration.

## Issue Description
We've been informed that EVSS is being deprecated as a whole, with a [target sunset date of March 2025](https://dsva.slack.com/archives/C8R3JS8BU/p1734038574290519?thread_ts=1734022763.229839&cid=C8R3JS8BU). We’re [collaborating closely with stakeholders](https://dsva.slack.com/archives/C06JM7UUHE3/p1734458154073629) to align on priorities and clarification. On a high level, we will first need to determine ownership between Platform and VFS teams regarding the migration process. Additionally, we need to identify **what service we are migrating to** and determine the responsible Product Owner leading the effort. 

Accessing a discovery document outlining the EVSS migration strategy would greatly help inform our technical approach. There have been initial discussions suggesting that EVSS functionality might be integrated into Lighthouse APIs. We need to evaluate whether leveraging their APIs is feasible/the suggested approach OR if building our own integration with VA Profile would be more appropriate. We're also **unsure if VA Profile is the service that Platform will need to migrate to**. The final decision on the target service remains unresolved, though it’s understood that Lighthouse APIs may already interface with VA Profile behind the scenes.

It appears discussions about folding the EVSS service into Lighthouse have been ongoing since 2021 in the [#vfs-evss-service-migration](https://dsva.slack.com/archives/C02CQP3RFFX) OCTO slack channel. 

It seems Vets API integrates with several EVSS sub-services, making it essential to establish a clear, standardized plan for the migration and removal process. Platform should outline the various components involved, defining responsibilities and distinguishing what falls within our scope versus what the VFS teams own. Additionally, we should establish a timeline that reflects a practical and achievable migration and deprecation process

We’ve [initiated conversations](https://dsva.slack.com/archives/C06JM7UUHE3/p1734458154073629) with our stakeholders to address open questions and ensure a smooth transition.

Additionally, we've been provided [this document ](https://dsva.slack.com/archives/C06JM7UUHE3/p1734558495254289?thread_ts=1734390961.696269&cid=C06JM7UUHE3) detailing the `EVSS > Lighthouse APIs Modernization Initiatives` and [this historical documentation around the EVSS integrations with VA.gov](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/evss-integration/readme.md)

## Tasks
- [x] What services do we use? Which services need to be migrated?
- [x] What Platform owns vs VFS
- [x] Clearly define who uses the service or integration, it does NOT have to default to Platform
- [x] Review commit history around files, map teams to majority of commits
- [x] Break down document per service (e.g. `EVSS/dependents`, `EVSS/documents`, etc)
- [ ] Consider meeting with Lighthouse to inform overall vision (dependent on info from VA Stakeholders)
- [x] Consider any options for standardization to assist the migration process 

## Acceptance Criteria
- [x] A comprehensive document including EVSS migration details
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by AshleyGuerrant** [comment]
Hi @rjohnson2011 - below is some documentation that describes each endpoint that Lighthouse took over. I'm unsure if it will be helpful in your discovery, but wanted to share it.

[EVSS _ Lighthouse APIs Modernization Initiatives_created 5.23.2024.pdf](https://github.com/user-attachments/files/18190111/EVSS._.Lighthouse.APIs.Modernization.Initiatives_created.5.23.2024.pdf)

**Comment by rjohnson2011** [comment]
Here is an [initial table](https://docs.google.com/spreadsheets/d/16C9qIyexUttpF9KI6s1QOsX0_JrkniFMmH2O_Jeuz9M/edit?usp=sharing) with various EVSS files/directories segmented by either Platform or VFS

**Comment by rjohnson2011** [comment]
Continuing to refine the table in terms of Lighthouse vs Platform permissions and ownership of core classes.

**Comment by rmtolmach** [comment]
**Some notes:** 
> we need to identify what service we are migrating to

The shared PDF says, "All Consumers MUST integrate with new Lighthouse API or alternate service." So it sounds like our assumptions are accurate: migrate to Lighthouse or VA Profile (or something else).

`config/features.yml` lists about 15 feature flippers that are for using Lighthouse instead of EVSS in various parts of the app, so that's good.

**Comment by rjohnson2011** [comment]
Accounted for all files in vets-api repo containing EVSS mentions in the table. Adding number of instances and doing final pass on teams associated. Looking for ways to divide into tickets.

**Comment by rmtolmach** [comment]
I updated the [second tab of the spreadsheet](https://docs.google.com/spreadsheets/d/16C9qIyexUttpF9KI6s1QOsX0_JrkniFMmH2O_Jeuz9M/edit?gid=1123139542#gid=1123139542). I moved 9 services down to the bottom in a "service abstractions" section (look for the black header). That leaves 12 main EVSS services (10 if you ignore PCIU). I noted any that had data availability from Lighthouse in the Notes column. 

I got my data from the [EVSS Service List > APIs + Lighthouse Status table](https://confluence.devops.va.gov/pages/viewpage.action?spaceKey=VAExternal&title=Status+-+EVSS+%3E+Lighthouse+APIs+Modernization+Initiatives#StatusEVSS%3ELighthouseAPIsModernizationInitiatives-ITF), and searching vets-api for `'EVSS/`
<img width="381" alt="Image" src="https://github.com/user-attachments/assets/066ab20d-7cec-433a-86ee-b638fe1113ef" />

**Comment by rmtolmach** [comment]
I searched the following terms in Datadog Logs. The **Count** is over the past 2 days unless noted otherwise).

| Search Term                                                   | Count   | File in vets-api                                                   |
|---------------------------------------------------------------|---------------|--------------------------------------------------------|
| `EVSSError`                                                  | 0             | error_middleware.rb                                    |
| `EVSSBackendServiceError`                                    | 1             | error_middleware.rb                                    |
| `'Supplementing EVSS headers'`                               | 69            | evss_claim_service.rb                                  |
| `EVSS/Common`                                                | 0 (7d)        | evss/common_service.rb                                 |
| `inflightform`                                               | 0 (7d)        | evss/dependents/service.rb                             |
| `"EVSS" AND "Dependents"`                                    | 0             |                                                        |
| `EVSS/DisabilityCompensationForm`                            | 47            | evss/disability_compensation_form/configuration.rb     |
| `Form526 Veteran-attached file names included in overflowText` | > 2k          | evss/disability_compensation_form/data_translation_all_claims.rb |
| `EVSS/Documents`                                             | 0 (7d)        | evss/documents_service.rb                              |
| `EVSS/IntentToFile`                                          | 0 (7d)        | evss/intent_to_file/configuration.rb                  |
| `EVSS::IntentToFile`                                         | 0 (7d)        | evss/intent_to_file/service_exception.rb              |
| `EVSS/Letters`/`EVSS::Letters`                               | > 1k          | evss/letters/configuration.rb                         |
| `'name and letter_type are required'`                        | 0 (7d)        | evss/letters/letter.rb                                |
| `'EVSS/PPIU'`/`"EVSS::PPIU"`                                 | 0 (7d)        | evss/ppiu/configuration.rb/service_exception.rb       |
| `EVSS/ReferenceData`                                         | 0 (7d)        | evss/reference_data/configuration.rb                 |
| `EVSS/VSOSearch`/`VSOSearch`                                 | 0 (7d)        | evss/vso_search/configuration.rb                     |

**Comment by rmtolmach** [comment]
## Notes
### IntentToFIle
It's possible these calls have been migrated to Lighthouse already. I see a comment suggesting that in the [IntentToFilesController](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/intent_to_files_controller.rb#L91-L92). More evidence of non-use in [Coverband for intent_to_files_controller](https://api.va.gov/coverband#fe2ecf25ce8e98144425aecd2ac7e2b5db5bc774) (scroll to the bottom).

### PPIU
Authenticated Experience team is getting everything they need from PPIU in VA Profile now, so _they_ aren't using EVSS anymore. They added [this message](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/ppiu_controller.rb#L16-L18) to try and track down any other team using EVSS's PPIU. 

### ReferenceData
According to the Lighthouse migration table:
![Image](https://github.com/user-attachments/assets/8f8e414c-9dde-4786-8936-4f5babbf564e)
The LH version of EVSS's ReferenceData is called Benefits Reference Data. It's integrated into vets-api here: [lib/lighthouse/benefits_reference_data](https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/lighthouse/benefits_reference_data)

**Comment by AshleyGuerrant** [comment]
I'll take responsibility for orchestrating this task:
> Consider meeting with Lighthouse to inform overall vision (dependent on info from VA Stakeholders)

There is a bi-weekly meeting that the Lighthouse team has, @LindseySaari and I are working on materials to bring to the meeting and what key Platform team members would be best to attend. 

I'm tracking the coordination with the Lighthouse team in [the epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/100351), so we can probably remove that task from this ticket.

cc @rmtolmach @rjohnson2011

**Comment by rmtolmach** [comment]
> Consider meeting with Lighthouse to inform overall vision (dependent on info from VA Stakeholders)

Ashley has meetings set up for this week.

We are good to close this issue. There was sufficient discovery done and Ryan has moved on to work on a design doc (https://github.com/department-of-veterans-affairs/va.gov-team/issues/100286) based on some of this information.
