### ISSUE TITLE
AWS RDS Aurora Discovery

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#99291]
## User Story
As a user and maintainer of the AWS RDS Database for Vets API, I want to ensure optimal performance, scalability, and cost efficiency, so that the database can handle fluctuating workloads, maintain high availability, and minimize operational expense.

## Issue Description
We should investigate the feasibility of migrating to AWS RDS Aurora. Aurora offers built in autoscaling capabilities, which could enhance database performance and reliability by automatically scaling to meet demands. Additionally, its flexible pricing structure might align well with cost optimization goals.

The cost of RDS tends to increase disproportionately as you scale vertically to larger instance sizes, making horizontal scaling a more cost effective approach. Given our dynamic environment, current stability doesn’t guarantee future stability, as system demands and requirements continually evolve.

This is a follow up action item related to the [postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/edit/AnthonyWFlowers-patch-1/Postmortems/2024/2024-12-04%20-Prod%20DB%20Connection%20Errors.md?pr=%2Fdepartment-of-veterans-affairs%2Fva.gov-team-sensitive%2Fpull%2F2134) regarding the Prod Vets API RDS database connection incident. Additional conversation can be found in [this slack thread.](https://dsva.slack.com/archives/CBU0KDSB1/p1734428700771499?thread_ts=1733327685.530079&cid=CBU0KDSB1)

## Tasks
- [x] Research Aurora’s autoscaling features and how they could be applied to our current setup
- [ ] Evaluate Aurora's pricing structure to determine potential cost benefits
- [x] Explore documentation for scalability, high availability, and additional benefits
- [x] Assess the compatibility of our current workloads with Aurora’s features including FEDRAMP approval
- [x] Discovery around adding a read-replica with Aurora

## Acceptance Criteria
- [ ] A discovery document is created
- [ ] The discovery doc contains our suggestion for the stakeholders
- [ ] Document is forwarded to stakeholders
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note:** Cost benefit evaluation is still in progress, this discovery is nearly complete.
[Documentation](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3730702346/Discovery+RDS+Aurora)

**Comment by Kshitiz-devops** [comment]
https://vfs.atlassian.net/wiki/spaces/PPT/pages/3730702346/Discovery+RDS+Aurora
