### ISSUE TITLE
Refactor Sidekiq ExternalServicesStatusJob

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#99307]
## Investigation
**What does the job do?**
This runs every minute. It was added in https://github.com/department-of-veterans-affairs/vets-api/pull/2882/ to check for the current status of our external services (all pd services prefixed with "External:") based on what their statuses are in pd. It caches that data.

Why do we do this? I'm not sure yet. Currently, we grab external service statuses from statsd and report them in dd, [like this](https://vagov.ddog-gov.com/dashboard/jq8-w55-zzp/vets-api-external-service-outages-and-error-trends?fromUser=false&refresh_mode=sliding&from_ts=1733523770115&to_ts=1733524070115&live=true) and I don't think that has anything to do with pd or this Job. I noticed in two of the PRs ([one](https://github.com/department-of-veterans-affairs/vets-api/pull/2879) and [two](https://github.com/department-of-veterans-affairs/vets-api/pull/2882)) where part of this functionality was added that the title of the PRs start with "Status page". Was this work all part of an external service status page?? I found [this old Slack thread](https://dsva.slack.com/archives/C0CF2DR6V/p1555439562039800?thread_ts=1555430286.037700&cid=C0CF2DR6V) by the PR author mentioning exactly that. _...Searching..._ I found [this swagger file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/swagger/swagger/requests/backend_statuses.rb) which led me to https://staging-api.va.gov/v0/backend_statuses! It's alive and works. But is it still needed?

**Is the job still needed?**
Yes. This appears to be used to enable downtime banners. Evidence: https://github.com/department-of-veterans-affairs/va.gov-team/issues/580

**Does the job need exception handling added?**
Yes. The job file is simple and doesn't have any error handling. The `perform` function calls [ExternalServicesRedis in status.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/external_services_redis/status.rb) which is also a pretty simple file with no error handling. So error handling might extend beyond the Job.

**Any other modifications needed?**
Not that I could tell, but most of this code is many years old, so there's bound to be something!

## User Story
As a Platform engineer, I want to improve exception handling and monitoring for the external services status job, so that downtime banners and related functionality remain reliable.

## Issue Description
`ExternalServicesStatusJob` runs every minute to check the current status of external services (PagerDuty services prefixed with "External:") and caches the data. This job appears to power downtime banners, as noted in [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/580).  

Currently, the job does not have exception handling, which could cause silent failures and there is no clear monitoring or alerting in place for failures.

## Tasks
- [ ] Read the investigation notes at the top of this issue.
- [ ] Determine when we should care about failures and add exception handling accordingly to the code involved in `ExternalServicesStatusJob` (i.e. in `ExternalServicesRedis` and possibly `PagerDuty::ExternalServices`).
- [ ] Update specs
- [ ] Prefix errors sent to Datadog with a specific identifier (e.g., `EXTERNAL_SERVICES_STATUS_JOB_ERROR:`) for easier tracking.
- [ ] Create a Datadog Log Monitor to alert when job errors occur using the specific prefix. Make alert actionable. 

## Acceptance Criteria
- [ ] Exceptions in the job and its dependencies are handled.
- [ ] Specs updated.
- [ ] A Datadog Log Monitor has been reviewed.

---
## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
