### ISSUE TITLE
Add VSOC and IDES contacts lists to VA.gov with CSV drupal upload process

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#9930]
## Issue Description
VR&E stakeholders would like to add VSOC and IDES contacts lists to our modern pages. We can do this with our new CSV upload process, but we need to figure out the right data fields and format for the upload. 

Open questions need resolving:
- What happens when a new row or section is added in the CSV? Will this break the Drupal table, how do we need to address that? EX: For VSOC list, when a new state is added; or when more individuals are added.
- Determine ETA.
 

Pages looked at in the meeting:

https://staging.va.gov/careers-employment/vetsuccess-on-campus/ VetSuccess on Campus content page
https://www.benefits.va.gov/vocrehab/vsoc.asp - VSOC contacts list
https://staging.va.gov/careers-employment/vocational-rehabilitation/ides/ IDES content page

Related ticket: 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9916

---
## Tasks
- [ ]  Take a stab at this in a spreadsheet we can show stakeholders Bettye Hodge and Robyn Trulock. It'll be a starting point for them to visualize what we're intending and they can provide feedback so we can finalize the spreadsheet.
- [ ]  Set up time to meet with Bettye and Robyn to review spreadsheet.

## Acceptance Criteria
- [ ] Spreadsheet created
- [ ] Meeting scheduled.
- [ ] Next steps and ETA determined.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jenniferlee-dsva** [comment]
@bethpottsVADEPO - Hi Beth - I added a link to the [related ticket # 9916](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9916).  If it's duplicative - please close it. Didn't want these to get orphaned/lost if they are related.

**Comment by bethpottsVADEPO** [comment]
This is a dup. Closing now.
