### ISSUE TITLE
Debt Letters - Your VA Debt Page 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#9931]
##Wireframes here https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/wireframes.md

## High Level User Story/ies
As a veteran who has incurred debt and received a debt letter, I would like to be able to to see how I incurred the debt 

## Hypothesis or Bet
Veterans only know about their debt because they get a debt letter which is hard to understand and may be misplaced or lost. Our bet is if we make the debt information available on-line and easy to understand, the veteran are more likely to resolve the debt. 

## Definition of done
- [ ] The Veteran must authenticate to reach this page 
- [ ]  The amounts displayed must match the amount provided in the mailed letters 
- [ ] The cards must contain the name of the debt
- [ ] The date incurred must be displayed
- [ ] For each debt viewable on the cards, the veterans should be able to click through to see additional details
- [ ] Page must meet 508 accessibility requirements
- [ ] IPage must provide next steps on how to resolve debt 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
