### ISSUE TITLE
[Ongoing Support] Mon - Thurs Deploy [S18]

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#99312]
## User Stories
As a Platform team member who just contributed to the Platform website,
I need my content published,
so that I can share my content updates with the intended audience.

As a content team,
we need to review any new content changes made on the platform,
so that we can deploy every Tuesday and Thursday of the week.

## Tasks
Someone from our team will use Scroll Viewport to publish changes to the website after 3pm EST on:

- [x] Thursday (1/2/25) - Jill, per OCTO request, [prioritizing Code Freeze updates, incl. 1/9/25 Executive Order](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?pane=issue&itemId=92383754&issue=department-of-veterans-affairs%7Cva.gov-team%7C99845)
- [x] Mon (1/6) - Brian 
- [x] Tuesday (1/7) - Brian
- [x] Wednesday (1/8) - Casey  
- [x] Thursday (1/9) - Jill 
- [x] Monday (1/13) - Jill 
- [x] Tuesday (1/14) -  Brian
- [x] Wednesday (1/15) - Casey

## Acceptance Criteria

- [x] The Platform website will be deployed on special Holiday schedule as above, between 3:30 and 5pm for this sprint.
- [x] Any edits with launch-blocking issues will be announced to their content editors via #platform-content

## Other Info

Data tracking info:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2282979860/KPIs+-+Content+Support

Temporary rotating schedule:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2405171201/Deployment+rotation+schedule

**Comment by jknipes** [comment]
all tasks complete, moving to _closed_
