### ISSUE TITLE
[Research] 10-10CG - Improvement: Connect with other VFS teams on "search" user experiences

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#99320]
## Benefit to the Veteran
As a Veteran and/or Caregiver, I want to feel confident on how I navigate the facilities search page, so that I can find what I need and move on through the form.

## Background
During research sessions and testing on Mobile devices, after entering a zip code the user is tapping the "Continue" button, causing confusion when the error message appears.  The user is not selecting the search/magnifying glass icon/button and receiving an error message with no search results appearing.  This does not occur much on the Desktop view.

## Scope
- In Scope
     - Connect with teams to capture user experiences on "search" type functionality

## Tasks
- [x] Connect with Ask VA team, who has also experienced users selecting "Continue" instead of the search button
- [x] Connect with other teams across VA.gov that may have a similar "search" functionality to capture their user experiences
- [x] Consolidate findings
- [ ] Determine if there is compelling information that suggests the DST should consider a change

## Acceptance Criteria
- The team has gathered user experiences across VA.gov

**Comment by jessicastump** [comment]
### Notes on recent completed studies in the repo using the `search input component` label

[2025-02 Resources & Support Search Enhancements #794](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/794)
- Figma prototype used
- Mostly feedback on search input around filter/tags/etc
- There was a secondary finding that is was difficult to see the search and results in one view on mobile: "Finding 6 - Many participants (6 of 12) made comments about limited screen size"

[2024-08 Ask VA: Assistive Tech – Dashboard #626](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/626)
- Assistive tech study and no mentions of issues with mobile search button in research findings doc

[2024-09 Find help on Contact us #661](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/661)
- Secondary finding mentioned on how people prefer to use use search, but it does not always work/give results expected.
- "Search bar is my favorite thing. So I will usually search it unless I know exactly where I'm going."

**Comment by jessicastump** [comment]
### Some quick search input pattern research outside of VADS

----
#### Callout 1: The search button and text is often reflected in the device default keyboard.

<img width="274" alt="Image" src="https://github.com/user-attachments/assets/c104e68f-0ade-4287-bc40-37c1a21007ec" />
<img width="274" alt="Image" src="https://github.com/user-attachments/assets/f3cbca84-e2fb-482c-be42-86b983349aae" />
<img width="260" alt="Image" src="https://github.com/user-attachments/assets/8ddb43f1-7502-4857-adf4-48ac394cc0e9" />

----

#### Callout 2: There is no search button really in the input, just an icon and sometimes text placeholder.

<img width="838" alt="Image" src="https://github.com/user-attachments/assets/439b475f-3e20-4ac0-9e02-96cc06f3f9a7" />


----- 
Used Mobbin for screen captures

**Comment by jessicastump** [comment]
Reached out the Ask VA team and learned there was a bug when they ran their study and they also implemented error messaging. They have not had an opportunity to run another study since.

> The user should have been stopped from continuing and an error message should have been triggered because the question is required. But, at the time of testing, there was a bug so users could continue without selecting a facility. We fixed the bug to remedy this issue.

Also shared a common finding that not a lot of forms/product teams are using the search input component making this a unique use case.

**Comment by jessicastump** [comment]
@hdjustice a summary and notes below, we can chat in planning or close this ticket I think. 


#### A summary of findings: 
- Not many forms use the search input within
- The similar issue heard about in the Monday VA design sync was a bug and resolved with specific error messages on the search input (similar to what we implemented)and that team also has not had a chance to re-test but are watching Medallia feedback
- Magnifying glass on mobile and default mobile browser search text was a common pattern found outside of VA.gov

#### Recommendation: 
Leave as is unless there is negative feedback found in Medallia from Veterans/Caregivers. Keep as an item to watch for in all future usability studies for now.

**Comment by hdjustice** [comment]
Thanks @jessicastump - I'll bring it up in planning, and if there are no other feedback items on it, we can close.

**Comment by hdjustice** [comment]
No other feedback items. Closing this ticket with no further actions to take at this time.
