### ISSUE TITLE
Debt Letters - Debt Details Page

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#9932]
## High Level User Story/ies
As a veteran who has viewed my current debts and clicked on 'more details' I would like to see the details of the debt and have the ability to view the debt letters. I would like additional detail on the debt and how to pay or make payment arrangements

## Hypothesis or Bet
Currently Veterans have to way to see their debts except for the letters that are mailed to their address of file, that are very hard to understand. By having the functionality for the Veterans to see their debts on va.gov our bet is that the Veteran will have a better chance of resolving the debt. 

## OKR
_Lower number of debs that are written off and reported to credit bureaus 

## Definition of done
- [ ] Debit Details page must display the debt detail fo ra logged in veteran
- [ ] Page must meet 508 accessibility guidelines
- [ ] Veteran must be able  to download the letters they received in the mail 
- [ ] There must be content to assist Veterans in understand their debt and what the next steps are if they cannot pay their debt
- [ ]There must be a link to pay the debt if the veteran agrees with it and wishes to pay 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
