### ISSUE TITLE
Update Deployments Time - Drupal CMS

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#99347]
## Issue Description
Per [this announcement](https://dsva.slack.com/archives/C03R5SBELQM/p1734473711204209) in #vfs-change-announcements Slack channel, we will need to update the Deployments page to reflect: 
Drupal CMS to start at 8am ET. We will be implementing that change on Wednesday (12/18) and that is when the first 8am ET CMS daily deploy will occur.
 
### Pages to update:

1. [Deployments page > Automated Deployments Schedule table](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments#Deployments-Automateddeploymentschedule)
2. [Deployment section of VA.gov content management system overview](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-gov-content-management-system-overview#VA.govcontentmanagementsystemoverview-Deployment)

---
## Tasks
- [x] Contact SME Grace Kretschmer Tran
- [x] Confirm which page(s) needs the update
- [x] Confirm which section(s) of the table
- [x] Confirm `changes in by`
- [x] edit page(s) to show new deployment time
- [x] Determine whether additional tickets are needed to edit more content 

## Acceptance Criteria
- [x] pages are updated
- [x] pages are deployed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Planning this sprint very light due to overlapping Holiday PTO

**Comment by taylojill** [comment]
[Sent draft copies/links of changes (2 pages) to Grace (SME) via our channel.](https://dsva.slack.com/archives/CL181NRJQ/p1735671456630329) Waiting for feedback.

**Comment by jknipes** [comment]
work is blocked by SME, carrying over into next Sprint

**Comment by taylojill** [comment]
@jknipes - I completed the edits for this ticket based on feedback from Grace (SME). Both pages were deployed when I updated the holiday freeze schedule. The card is currently in the Current sprint column but all work is complete.

**Comment by jknipes** [comment]
Started in Sprint 17, completed in Sprint 18. All tasks complete, closing as _Done_
