### ISSUE TITLE
[Ongoing Support] Monday - Thursday Deploy [S19]

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#99348]
## User Stories
As a Platform team member who just contributed to the Platform website,
I need my content published,
so that I can share my content updates with the intended audience.

As a content team,
we need to review any new content changes made on the platform,
so that we can deploy every Tuesday and Thursday of the week.

## Tasks
Someone from our team will use Scroll Viewport to publish changes to the website after 3:30pm EST on:

- [x] Thursday (1/16) - Jill  
- [x] Mon (1/20) - No Deployment - MLK HOLIDAY
- [x] Tuesday (1/21) - Brian 
- [x] Wednesday (1/22) -  Casey 
- [x] Thursday (1/23) -  Jill
- [x] Monday (1/27) -  Casey
- [x] Tuesday (1/28) - Brian (w/Victoria)
- [x] Wednesday (1/29) - Casey

## Acceptance Criteria

- [x] The Platform website will be deployed on special Holiday schedule as above, between 3:30 and 5pm for this sprint.
- [x] Any edits with launch-blocking issues will be announced to their content editors via #platform-content

## Other Info

Data tracking info:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2282979860/KPIs+-+Content+Support

Temporary rotating schedule:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2405171201/Deployment+rotation+schedule

**Comment by jknipes** [comment]
work is complete, moving to _Done_
