### ISSUE TITLE
PCIU Migration: Step 6f: Remove PCIU from devops repos

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#99358]
## User Story
As a developer, I want to remove all references of PCIU to ensure Vets-API does not use PCIU, as we transition to VA Profile in preparation for the PCIU deprecation

## Issue Description
Remove any PCIU configuration from the devops repo and manifest repo. There are 2 in devops repo and 8 in manifest repo. This includes configurations such as fwdproxy settings and other relevant configurations related to the removal process.

#### Devops repo
[This configuration](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/review-instance-configure/vars/settings.local.yml#L167-L168) seems to be the only PCIU thing in the devops repo.

#### Manifest Repo
1. Review all configs, settings and secrets for [each env here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vets-api)
2. **Note:** It appears that there may only be some mockdata settings to remove in the manifest repo. Example: [dev manifest](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/dev/values.yaml#L1713-L1714). This is due to the fact that the base_url for the PCIU service config is the EVSS base url and the remainder of the sub paths are hard coded into Vets API. [Example here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/pciu/configuration.rb#L18). 

## Tasks
- [x] PCIU references removed from [devops repo](https://github.com/department-of-veterans-affairs/devops)
- [x] PCIU references removed from [manifest repo](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests)

## Acceptance Criteria
- [ ] PRs merged
- [ ] All environments have synced successfully. No errors in Argo.
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by Kshitiz-devops** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/15084
