### ISSUE TITLE
IA Tracker: Appoint a rep

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#99357]
## Acceptance Criteria
- [x] Wrap my brain around the team's launch plan on 1/6
- [x] Confirmed that[existing IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/manage-accredited-representative.md) accurately shows placement of this form
- [x] Communicate launch needs to A and team around launch time
- [ ] Make launch-related IA updates

**Comment by kristinoletmuskat** [comment]
I think the existing one is accurate. Checking with the team on their sub URLs, and to confirm that we only need the single entry point (sign in widget) on https://www.va.gov/get-help-from-accredited-representative/ to launch. 

After launch, we need to:
1) Update best bets for 21-22 and 21-22a
2) add 'go to online tool' link to About a Form pages
3) update sitemap with final URL: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1672351995789/71a5b7ba07995735d458df39e07a696f48a9be48

**Comment by mnorthuis** [comment]
All IA work is complete.  Closing issue.
