### ISSUE TITLE
PCIU Migration: Step 6g: vets-website PCIU removal

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#99359]
## User Story
As a developer, I want to remove all references of PCIU to ensure Vets-API does not use PCIU, as we transition to VA Profile in preparation for the PCIU deprecation.

## Issue Description 
Remove PCIU referenced from vets-website. Details based on discovery done in https://github.com/department-of-veterans-affairs/va.gov-team/issues/78839.

All PCIU variables need to be appropriately renamed. Vets-Website PCIU variables are imported from Vets-Json-schema. This ticket will need to be completed in two steps. First step, the variables in Vets-json-schema will need to be renamed and the package version must be updated. Details can be found in this [README](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/README.md). Please review the [README](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/README.md) before submitting the PR to ensure the schema is properly updated. The second step is to rename Vets-Website PCIU variables. 

IMPORTANT NOTE: Vets-Json-schema modifications have to be merged before Vets-Website modifications can be merged. 

Vets-json-schema PCIU variable replacements:
- pciuStates -> formProfileStates
- pciuCountries  -> formProfileCountries

Vets-Website PCIU variable replacements:
- pciuStates -> formProfileStates
- PCIU_STATES -> FORM_PROFILE_STATES

## Tasks
- [x] Rename pciuStates instances in [Vets-json-schema](https://github.com/department-of-veterans-affairs/vets-json-schema) and update version according to the  [README](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/README.md)
- [x] Rename pciuCountries in [Vets-json-schema](https://github.com/department-of-veterans-affairs/vets-json-schema)
- [x] Ensure Vets-json-schema versioning has been properly updated
- [x] Rename PCIU variable instances in [Vets-Website](https://github.com/department-of-veterans-affairs/vets-website)

## Acceptance Criteria
- [x] Vets-json-schema PCIU variables are renamed/removed.
- [x] Vets-Website PCIU variables are renamed
---

**Comment by AshleyGuerrant** [comment]
Reopening because this ticket was automatically closed when [this PR](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/970) was merged, however that PR is just part of the work and this ticket is not complete.

**Comment by RachalCassity** [comment]
Awaiting PR Reviews
