### ISSUE TITLE
Discovery: Talk to leadership about automated Slack posts. 

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#99369]
## Issue Description
 Once we have our list of automated slack posts (see other ticket), we need to know where what to do with them. Someone needs to reach out to leadership to ask what they would like us to do with them. If we don't do anything, they will, likely,  keep posting forever. 

---
## Tasks
- [x]  Reach out to leadership to find out what to do with our automated Slack posts. 
- [x]  Create additional ticket(s) to move/change/delete/archive automated Slack posts. 

## Acceptance Criteria
- [x]  all tasks complete 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by BSmolensky** [comment]
Ticket is ready to close.
