### ISSUE TITLE
[ZSF] Figure out why we weren't alerted to a Sharepoint upload error - Make sure to include VBSSubmissionJob too

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#99360]
## Issue Description
Given: We expect to be notified about all errors that occur with our code
When: Sharepoint PDF upload fails
Then: We should get an alert in Slack debt-alerts channel

Might be a duplicate of this one: https://github.com/orgs/department-of-veterans-affairs/projects/1514/views/3?pane=issue&itemId=92030053&issue=department-of-veterans-affairs%7Cva.gov-team%7C99685

## Tasks
- [ ] Figure out why we weren't getting alerted in Slack about a sharepoint error
- [ ] Get alert working

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Our Sharepoint errors are alerting in Slack   

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Assign Type
- [ ] Assign Priority (Normal = Medium)
- [ ] Assign Group(s)
- [ ] Assign to a Project
- [ ] Attach to an Parent Epic
- [ ] Estimate Points

</details>

**Comment by HeatherRienks** [comment]
Per backlog refinement, this ticket is no longer needed.
