### ISSUE TITLE
adjust settings-local-secrets and remove associated settings-local-yml configmap for current SSM in dev

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#99374]
adjust settings-local-secrets and remove associated settings-local-yml configmap for current SSM in dev

## Tasks
- [x] adjust env settings for settings-local-secrets to new values (in file)
- [x] remove entries from settings-local-yml config map

## Acceptance Criteria
- [x] vets-api DEV's settings-local-yml config map no longer has value inject (env vars) used in the file[devSettingsLocal.txt](https://github.com/user-attachments/files/18184535/devSettingsLocal.txt)
