### ISSUE TITLE
Staging: Update settings-local-secrets to use Temp secrets

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#99375]
adjust settings-local-secrets and remove associated settings-local-yml configmap for current SSM in staging

## Tasks
- [x] adjust env settings for settings-local-secrets to new values (in file)
- [x] remove entries from settings-local-yml config map

## Acceptance Criteria
- [x] vets-api staging settings-local-yml config map no longer has value inject (env vars) used in the file[stagingSettingsLocal.txt](https://github.com/user-attachments/files/18184566/stagingSettingsLocal.txt)
