### ISSUE TITLE
adjust settings-local-secrets and remove associated settings-local-yml configmap for current SSM in prod

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#99376]
adjust settings-local-secrets and remove associated settings-local-yml configmap for current SSM in prod

## Tasks
- [ ] adjust env settings for settings-local-secrets to new values (in file)
- [ ] remove entries from settings-local-yml config map

## Acceptance Criteria
- [ ] vets-api prod settings-local-yml config map no longer has value inject (env vars) used in the file[prodSettingsLocal.txt](https://github.com/user-attachments/files/18184572/prodSettingsLocal.txt)
