### ISSUE TITLE
remove hard coded values from settings-local-yml config map for sandbox

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#99387]
remove hard coded values from settings-local-yml config map for sandbox

## Tasks
- [ ] add the values to settings-local-secret
- [ ] remove the entries from the environment settings local configmap

## Acceptance Criteria
- [ ] settings-local-yml config map should be gone
