### ISSUE TITLE
Footer Ticket 97604: Remove Zenhub section after Dec 30

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#99383]
## Issue Description
Per ticket [97604](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?pane=issue&itemId=88172186&issue=department-of-veterans-affairs%7Cva.gov-team%7C97604), we need to remove references to ZenHub from Platform Website

[Search results for "Zenhub"](https://depo-platform-documentation.scrollhelp.site/search.html?l=&max=10&ol=&q=zenhub&s=&start=0)

### [ZenHub Guidance Removal Google Sheet](https://docs.google.com/spreadsheets/d/1Tj7imFEuaIkRlEnZ4sgVULu5nycWp5mwLp95aSBvhmY/edit?usp=sharing)
---
## Tasks
- [x] Review all search results
- [x] Remove sections if necessary
- [x] prepare pages for deployment if necessary
- [x] Keep track in ZenHub Guidance Removal sheet

## Acceptance Criteria
- [x] all tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
