### ISSUE TITLE
[DD] Final steps for Dispute Debt groundwork

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#99407]
## Issue Description
`vets-website` and `content-build` PRs are in draft mode, waiting for the new contract to mark ready and get merged. What's currently in the vets-website branch is a pretty high level skeleton, all the pages and basic functionaility are laid out, and remaining FE work is ticketed in the epic (**Digital Dispute (VBA) - FE/BE Development [#96176](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96176)**). We followed the setup progress in [VA.gov application generator](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-gov-application-generator), but noticed a few steps that we may still need to do in the more detailed **[Creating a new application](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application)** documentation.

**Note:** Keep in mind [PR merge order](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application#Creatinganewapplication-PRmergeorder)      

- FE ticket most of the work was completed under
department-of-veterans-affairs/va.gov-team#97002

### PRs for reference
- [x] `vets-website`
  department-of-veterans-affairs/vets-website/pull/33332
- [x] `vets-api` for prefill
department-of-veterans-affairs/vets-api/pull/19545
- [ ] `content-build`
department-of-veterans-affairs/content-build/pull/2393
- [x] `vets-json-schema`
department-of-veterans-affairs/vets-json-schema/pull/961

### New PRs
- [ ] Revproxy PR
department-of-veterans-affairs/vsp-platform-revproxy/pull/816

- [ ] Middleware config PR
department-of-veterans-affairs/vets-api/pull/20292

## Tasks
- [ ] Update [team docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/general/digital-dispute/dev-notes.md#remaining-work) once complete
### Remaining tasks defined in [Manual Setup](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application#Creatinganewapplication-Manualsetup)
- [x] 3. Add an entry to `src/applications/registry.json` in the `content-build`
  - [PR](https://github.com/department-of-veterans-affairs/content-build/pull/2393) has been generated, just noting we missed it initially
- [ ] 4. Add your new application to the [vets-api source app middleware configuration](https://github.com/department-of-veterans-affairs/vets-api/blob/c80b278e3c8cc3014035d6ec3670dfaa18ff4368/lib/source_app_middleware.rb#L23)
- [ ] 6. [Update revproxy config](https://depo-platform-documentation.scrollhelp.site/developer-docs/routing#Routing-ReverseProxyConfig) to reflect the addition of your application so that internal links created via react-routerwill work properly.

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           
  - Initial skeleton of work, we can sync with design after the bulk of the refinement work in this epic is complete

## Acceptance Criteria
- [ ] All steps have been completed for creating a new application
- [ ] All PRs merged
- [ ] [Team docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/general/digital-dispute/dev-notes.md#remaining-work) updated

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Assign Type
- [x] Assign Priority (Normal = Medium)
- [x] Assign Group(s)
- [x] Assign to a Project
- [x] Attach to an Parent Epic
- [x] Estimate Points

</details>

**Comment by Dr-Pongo** [comment]
Primary `vets-website` PR is merged! Waiting on `content-build` next! Opening vets-api and revproxy PRs shortly

**Comment by Dr-Pongo** [comment]
- Middleware PR that could be an adventure 
department-of-veterans-affairs/vets-api/pull/20292

**Comment by Dr-Pongo** [comment]
Closing out in flight PRs, updating [team docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/general/digital-dispute/dev-notes.md) and created a follow on ticket as the contract comes to a close. 

- Follow on ticket
department-of-veterans-affairs/va.gov-team/issues/101240
