### ISSUE TITLE
UX | Create screens for Your Employers step (finalize design)

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#99417]
## Description
This ticket is to finalize the design in Figma for the "Your Employers" step. 

## Tasks 
- [x] Create required screens to show how the pattern will be used in a step today.
- [x] Share final designs with PM and PO for approval
- [x] Share out to the team 

## Acceptance Criteria
- [x] Screens are created in figma
- [x] PM approves design

**Comment by brian-wilke** [comment]
This has been updated in the [Step Library](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1731956783059/f34d7fc7b35ba062c2a10b42adc6ab25481a798e?wid=0-1732114528946) via screens in the [Figma file.](https://www.figma.com/design/BPhic1KhsZoduxv0ptjjlu/Form-Builder---Editorial-UI?node-id=4746-78649&t=blVG943otvpMoqYw-1)

Awaiting @Karak888 (PM) approval to close.

**Comment by brian-wilke** [comment]
Updated [step library](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1731956783059/f34d7fc7b35ba062c2a10b42adc6ab25481a798e?sender=ub5dc086a14b6f943de142963) and figma pages that use the "Your employers" step
