### ISSUE TITLE
Create repeatable process for Quarterly Workshops

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#99427]
## Purpose
Create a workshop series that helps Platform teams digest Quarterly Survey feedback and prioritize their work.

- We want to:
  - ensure that we focus on engineering-based teams first, and support teams second
  - conduct workshops that include only PMs and TLs
  - facilitate conversation around feedback, and creating problem statements

## Tasks
- [x] Draft a process for the quarterly workshop process post-survey
- [x] Review with Design Lead
- [x] Finalize process

## Acceptance Criteria
- [x] Confluence page is ready
- [x] Repeatable process steps are established
