### ISSUE TITLE
Host Q3 Survey Workshop for GT (2)

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#99426]
## Purpose
Create a workshop series that helps Platform teams digest Quarterly Survey feedback and prioritize their work.

- We want to:
  - conduct workshops that include only PMs and TLs
  - facilitate conversation around feedback, and creating problem statements

## Tasks
- [x] Schedule and host Workshop 2 (first week of January)
- [x] Ensure any last items are filled out and organized on the Mural board
- [x] Discuss any learnings/next steps with Design Lead

## Acceptance Criteria
- [x] Workshop 2 has been conducted
- [x] Mural board is complete
- [x] Next steps are established
