### ISSUE TITLE
Submit GA4 Data Deletion Request on myhealth.va.gov search parameter

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#99425]
### Description
After the redaction of data collected from the myhealth.va.gov search parameter, we submitted GA4 data deletion request -- we now need to submit a data deletion request.

---

### Tasks

- [x] Submit GA4 data deletion request.
- [x] Validate the deletion request has been successful.
- [x] Confirm with Dennis once it's been completed.

### Acceptance Criteria

- [x] Data deletion request has been submitted.
- [x] Dennis has been notified it has been successful.

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc. Deletion request submitted. I'll check this evening/tomorrow morning for the initial deletion steps. 

<img width="553" alt="Image" src="https://github.com/user-attachments/assets/073121b8-3616-4e78-8ca3-168ad9dfb424" />

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc  We know by now that GA data deletion requests take months to fully complete but the temporary deletion is now in place. As you can see from the below screenshot, the search results page title is still being captured but anything with the query parameter is gone. 


<img width="1097" alt="Image" src="https://github.com/user-attachments/assets/2ee72815-158c-4997-9b46-593739b2cf9b" />
<img width="1139" alt="Image" src="https://github.com/user-attachments/assets/3342110c-3913-461d-a027-6f3a8f810335" />

Here you can see the (data deleted) variable in the Page path + query string Dimension as well as newer searches with the now excluded parameter gone. 
<img width="1386" alt="Image" src="https://github.com/user-attachments/assets/15c8e412-f740-491c-9b55-a07ee24238f5" />

I don't know if you want to notify Dennis now or wait until we're past the pending time period.
