### ISSUE TITLE
[CAIA Internal]: EDM team Yellow Ribbon tool Content changes

### ISSUE THREAD

**Issue by scjwalker** [department-of-veterans-affairs/va.gov-team#99434]
# CAIA Internal Collaboration 

Related tickets:
[CAIA Intake](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92367) 
[IA Spec ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/yellow-ribbon-finder.md)
[IA Tracker ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95206)

## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The EDM team is deprecating the 'Find a Yellow Ribbon school' tool, and moving all data from the Yellow Ribbon tool into the GI Bill school comparison tool. 
<img width="939" alt="YR 1" src="https://github.com/user-attachments/assets/a9be2a6e-91a5-45e1-9a82-77e995f8e739">

### Entry point to REMOVE

**Education hub page** - Remove
- Placement description: Education hub page 'More information and resources' section
- Link label: Find a Yellow Ribbon school
- Who will update (IA, content, product team): Content
- When will this entry point go live (at launch? After staged rollout? after some designated time?): At launch
- Notes: Remove both the header link and the explanation text for the Yellow Ribbon tool from the section. Consider updating the description of the Comparison Tool to include a mention that the Yellow Ribbon data is now available here, since this is a change to a somewhat popular program.
![YR 9](https://github.com/user-attachments/assets/b1e0d530-0052-496e-829b-a0cbb75d1e3e)

### Crosslinks
Identify all crosslinks to the Yellow Ribbon tool, and modify them to direct visitors to the new location of the information. Or remove the link if its no longer applicable in that context. The new location of the Yellow Ribbon data will be a sub-page of the current https://www.va.gov/education/gi-bill-comparison-tool URL, since the EDM team is moving data around within that tool as well - see the [WEAMS migration content ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99433) and [ IA Spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/WEAMS%20migration.md) for details.

---
## Tasks
- [ ] IA works with product team and CAIA writer to identify entry points and suggested crosslinks
- [x] IA documents plan in IA Spec in the [IA Spec folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/information-architecture/ia-design-docs) on github
- [ ] IA adds the IA spec to the intake ticket for the product team, tags Lily/Megan 
- [ ] Lily ensures IA spec is included in content entry point [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/CAIA%20entry%20points%20+%20crosslinks%20for%20launches.md) for Megan
- [ ] Lily confirms whether work requires a writer (or if writer is already involved), or SME review. Criteria: Any surrounding content change besides replacing PDF link with online form link
- [ ] Content writer notifies Megan/Chelsea when it’s time to implement
- [ ] Once a product is launched to 100% of users (staged rollout or not), content will take out the widget and put the rest of the entry points/crosslinks in in Drupal and publish. 
- [ ] Publish
- [ ] Megan or Chelsea will add Kristin or Jenny as an assignee to the entry point ticket
- [ ] Content will let IA know final decisions on crosslinks and why, so IA can document
- [ ] IA will check live site for accuracy of implementation, compared to IA spec
- [ ] Kristin or Jenny will update sitemaps with color coding to show product/change was implemented

## Acceptance Criteria
- [ ] Updated pages are live
- [ ] IA review complete
- [ ] Sitemaps update

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mnorthuis** [comment]
This work should happen as part of #99433
