### ISSUE TITLE
MHV sign in transition weekly report review

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#99432]
## Issue Description

There is likely going to be an increase of sign in/account creation issues occurring leading up to and in the aftermath of the January 31st MHV removal date. Because of this, we want to closely track the types of issues coming in so we can share with the relevant team's what are the problems veterans/users are facing so any appropriate changes or materials can be created to address the problems. 

We will create a report of Tier 1/2/3 technical support issues that can be reviewed daily to identify trending issues that can be shared out daily. 

---
## Tasks
- [x] Request new daily report that will be delivered starting on 1/2/2025
- [ ] Determine process for reviewing cases daily and categorizing
- [ ] Determine how information will be shared to relevant teams

## Acceptance Criteria
- [ ] New qualitative data report
- [ ] Presentation of information to be shared with relevant teams
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
[Here is the sign in support issues tracking spreadsheet.](https://dvagov.sharepoint.com/:x:/r/sites/AccountExperience/Shared%20Documents/General/identity%20report.xlsx?d=wf79c980b8eb4456d8052ad6eccf8f87b&csf=1&web=1&e=NMs0jE) We are going to start with a weekly cadence and right now it is only displaying volume for tier 1, tier 2, and AVA and then Tier 1 volume for sign in related issues.

**Comment by clantosswett** [comment]
@newworld2616 I am currently trying to put together the reporting we will do as part of the sign in transition work. Could you create a SF report for me that shows T2 daily cases as well as an SF report that displays daily T1 cases for sign in related issues? We can chat about this tomorrow during the medallia sync but wanted to put here as well. Thanks!

cc: @ATMiddleton and @Kimberley2023-CSM

**Comment by newworld2616** [comment]
[TemplateTest.xlsx](https://github.com/user-attachments/files/18443278/TemplateTest.xlsx)
Hello @clantosswett and @ATMiddleton , I have attached the sample file for new report. Could you provide me your input, if I need to modify, add, change or create new report.  Thank you.

**Comment by clantosswett** [comment]
Thank you for this! Let's plan to discuss tomorrow during our Medallia sync.

**Comment by newworld2616** [comment]
Anytime! Sounds great!

**Comment by clantosswett** [comment]
I've attached the template with the case types highlighted that should be shown for tier 1, 2, 3 and EVSS as well as for AVA. Please let me know if you have any questions!

[TemplateTest (1).xlsx](https://github.com/user-attachments/files/18509898/TemplateTest.1.xlsx)

**Comment by newworld2616** [comment]
Sure thing! I will start sharing the report every Monday. Thank you!

**Comment by ATMiddleton** [comment]
@newworld2616 will create a conversation in Slack and there we will determine the distribution protocol.
