### ISSUE TITLE
[CAIA Internal]:<EDM team><WEAMS migration><Content changes>

### ISSUE THREAD

**Issue by scjwalker** [department-of-veterans-affairs/va.gov-team#99433]
# CAIA Internal Collaboration 

[CAIA Intake](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92369)
[IA Spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/WEAMS%20migration.md#navigation-pathways-and-entry-point-for-launch)
[IA Tracker ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95208)

## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The EDM team is info about reimbursement rates for [national tests](https://inquiry.vba.va.gov/weamspub/buildSearchNE.do) and for [licenses and certifications](https://inquiry.vba.va.gov/weamspub/buildSearchCountryLCCriteria.do) into the School Comparison tool. The different types of data being added to the Comparison tool need different search and display controls, so as part of this project they're collaborating with the GovCIO team to convert the current School Comparison tool URL into a landing page, where users can choose which type of data they want to look at. There will be three categories - Licenses and certifications data which will be a search+results format, National tests which will be a list, and the current School comparison search+results which will now have the Yellow ribbon data integrated into it. (For more on the Yellow Ribbon changes, see the Yellow ribbon tool content changes ticket and [IA Spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/yellow-ribbon-finder.md).)
![weams 5](https://github.com/user-attachments/assets/3610e476-49c1-42ef-b4d6-2ddeeabd2d62)

We are working on controlling scope on this project. The team has received this, along with a framework to guide their content/IA decisions inside the tool: "On this project, CAIA IA support will be focused on the connections between the Comparison Tool and the rest of va.gov. We are not able to support IA and Content decisions within the tool Landing page or sub-pages."

### Primary entry point for launch

**1) [Education benefit hub page](https://www.va.gov/education/) - Modify**
- Placement description: Keep the entry point's current placement on the Education hub page. Update the descriptive text to reflect the additional content added into the Comparison Tool.
- Link label: [TBD by CAIA Content]
- Link destination: va.gov/education/gi-bill-comparison-tool
- Who will update (IA, content, product team): CAIA Content
- When will this entry point go live (at launch? After staged rollout? after some designated time?): At launch
![weams 2](https://github.com/user-attachments/assets/a48c651f-6459-4a82-8c4e-3307e58026cf)

### Secondary entry points
_Any additional locations that the page should be navigable from such as the "About a form" page, additional navigation component (top, left) placements, additional static pages where its prominently linked from, etc.   These are secondary, and while they are still very important, are not required for launch._

**1. Mega menu - Modifications TBD** - 
- Placement description: Mega Menu promo spot
- Link label: Keep current header text and descriptive text, or update to reflect additional data available in the tool. (Changes TBD by CAIA Content)
- Link destination: va.gov/education/gi-bill-comparison-tool (now the url of the new Landing page)
- Who will update (IA, content, product team): Education business line. Beth will coordinate.
- When will this entry point go live (at launch? After staged rollout? after some designated time?): At launch
- Notes: Editing a single location updates the promo spot in both the Mega menu and Right rail.
![weams 6](https://github.com/user-attachments/assets/49b2ce5f-d9dd-4481-8807-9bb6d1a85385)

**2. Right rail of Education hub page - Modifications TBD** - 
- Placement description: Right rail promo spot
- Link label: Keep current header text and descriptive text, or update to reflect additional data available in the tool. (Changes TBD by CAIA Content). The content here must be consistent with the content in the Mega Menu promo spot.
- Link destination: va.gov/education/gi-bill-comparison-tool (now the url of the new Landing page)
- Who will update (IA, content, product team): Education business line. Beth will coordinate.
- When will this entry point go live (at launch? After staged rollout? after some designated time?): At launch
- Notes: Editing a single location updates the promo spot in both the Mega menu and Right rail.
![weams 7](https://github.com/user-attachments/assets/e8bfa70c-56de-449e-bdd6-57eb7d36f3ac)

### Crosslinks
1.  Identify all existing crosslinks to the Comparison Tool and modify the links to direct visitors to the Landing page or the School Comparison, whichever is the best match.

2. On the [Licensing & Certification benefit info page](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/licensing-and-certification-tests/), update to navigate to the Licensing & Certification search flow in the tool. - 

3.  On the [Licensing & Certification benefit info page](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/licensing-and-certification-tests/), updates may be needed to the "Tips for using the tool" section.
![weams 10](https://github.com/user-attachments/assets/4fbdada3-2527-409f-9739-147b3c439e32)

4. On the [National Tests benefit info page](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/national-tests/), update to navigate to the National Tests page in the tool.
![weams 9](https://github.com/user-attachments/assets/c0c904e1-c56c-4277-b182-6d9d7aa96d92)

---
## Tasks
- [ ] IA works with product team and CAIA writer to identify entry points and suggested crosslinks
- [x] IA documents plan in IA Spec in the [IA Spec folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/information-architecture/ia-design-docs) on github
- [ ] IA adds the IA spec to the intake ticket for the product team, tags Lily/Megan 
- [ ] Lily ensures IA spec is included in content entry point [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/CAIA%20entry%20points%20+%20crosslinks%20for%20launches.md) for Megan
- [ ] Lily confirms whether work requires a writer (or if writer is already involved), or SME review. Criteria: Any surrounding content change besides replacing PDF link with online form link
- [ ] Content writer notifies Megan/Chelsea when it’s time to implement
- [ ] If staged rollout: Content publishes the main static page or landing page with the react widget and DOES NOT implement entry points or crosslinks. 
- [ ] Once a product is launched to 100% of users (staged rollout or not), content will take out the widget and put the rest of the entry points/crosslinks in in Drupal and publish. 
- [ ] Publish
- [ ] Megan or Chelsea will add Kristin or Jenny as an assignee to the entry point ticket
- [ ] Content will let IA know final decisions on crosslinks and why, so IA can document
- [ ] IA will check live site for accuracy of implementation, compared to IA spec
- [ ] Kristin OR Jenny will update sitemaps with color coding to show product/change was implemented

## Acceptance Criteria
- [ ] Updated pages are live
- [ ] IA review complete
- [ ] Sitemaps update

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Thanks for this thorough summary @scjwalker! Now that I see all the crosslinks affected and accompanying teaser text, I think it makes sense to have our content team member (rather than me) work on the text for secondary entry points 1 and 2 (it'll be a shorter version of whatever that person works up for the primary entry point for the hub landing page). I'd like that content team member to consult with me on the promo spots but drive that work themselves. And then everything can go back to stakeholders together rather than a separate contact from me. 

To explain a bit about this shift, the thing that was top of mind for me when you first raised it, @scjwalker, was that I didn't want our team to ask the stakeholders for that text. I wanted to make sure it originated with content experts so it would start out with our style and plain language standards applied. But I hadn't thought about the hub landing page that would also need text updates and that CAIA would be working on anyway. It's all related and we should reuse messaging!

So, let's change this line that appears for secondary entry points 1 and 2:

- Who will update (IA, content, product team): CAIA Content

Many thanks!

**Comment by mnorthuis** [comment]
Summary of entry points needed from IA spec:

**Education benefit hub page**
- KEEP the existing "GI Bill Comparison Tool" link label and destination, ~UPDATE the teaser text to reflect the additional content added into the Comparison Tool.~ _UPDATE: We are removing descriptions from manage benefits section on all hub page._ 
- REMOVE the "Find a Yellow Ribbon school" link and teaser text

**Education benefit hub secondary nav**
- REMOVE the "Find a Yellow Ribbon school" option from the left nav
- KEEP the "GI Bill Comparison Tool" link label and placement as is
 
**Benefit hub promo spot**
- ~UPDATE the teaser text of the GI Bill Comparison Tool promo spot to reflect the additional content added to the tool
Best bets~  _UPDATE: It was determined that this text does not need to be updated per Edu services partners._
 
**Best bets**
- UPDATE existing best bet for GIBCT with description and keyword matches that reflect the additional content added into the tool
- REMOVE the existing best bet in place for the Find a Yellow Ribbon school tool

Possible hub page teaser text from Beth that can be used for Best Bet since the page does not have a proper description to pull form:

- Compare your GI Bill benefits at schools with approved programs. And find out how much we’ll pay you back for licensing and certification tests and national tests. You can also search for employers with approved training programs for on-the-job training and apprenticeships.

**Comment by mnorthuis** [comment]
Sent email to Darla about deprecating the YR tool on 4/18.  The EDM team is claiming they are not responsible for it.
