### ISSUE TITLE
Decrease the Sentry RDS Storage (Dupe 2 of 2)

### ISSUE THREAD

**Issue by AshleyGuerrant** [department-of-veterans-affairs/va.gov-team#99472]
This ticket is a duplicate of [79198](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79198) & #91711.

## Issue Description
After the Sentry spike issue has been solved [with the Identity and Mobile teams?] the RDS storage can be decreased. This was increased due to the extreme storage required because of the issues (up to 6mm according to[ this Slack thread](https://adhoc.slack.com/archives/C045LCF8WU8/p1711134858385029)) that are taking up space. 

---
## Tasks
- [ ] Decrease RDS storage
- [ ] Test as required
- [ ] Adjust monitors as necessary, once the findings between past and current storage usage has been established. 

## Acceptance Criteria
- [ ] Comparison of the past and current storage volumes to determine if the RDS needs to be decreased.
