### ISSUE TITLE
Identify metrics

### ISSUE THREAD

**Issue by candilemoine** [department-of-veterans-affairs/va.gov-team#99489]
## Tasks 
- [x] identify metrics for pilot, both for success and performance
- [x] discuss OCTO monitoring metrics with Steve A
- [x] determine tools for metrics
- [x] create tasks for setting up the metrics

## Questions
- will there be disconnect if we track basic metrics now and switch to a subdomain?

**Comment by candilemoine** [comment]
https://github.com/digital-analytics-program/gov-wide-code
