### ISSUE TITLE
Deprecate Yellow Ribbon school finder

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#99482]
## Description
The product team is updating the GI Bill Comparison Tool to include the data in the current [Yellow Ribbon school finder](https://www.va.gov/education/yellow-ribbon-participating-schools/) tool. As a result, we need to remove mentions of this tool on VA.gov.

First, we need to find all the pages that crosslink to the Yellow Ribbon school finder tool. Then, we need to remove those crosslinks in Drupal and republish those pages.

## Tasks
- [x] DB: Audit VA.gov for crosslinks
- [ ] DB: Remove crosslinks in Drupal
- [ ] ST: Copyedit and publish

## Criteria
- [ ] All crosslinks to the Yellow Ribbon school finder tool have been removed on VA.gov

**Comment by d-beyer** [comment]
I completed an [audit of links that point to the GI Bill Comparison Tool, WEAMS, and the Yellow Ribbon Tool](https://dvagov.sharepoint.com/:x:/r/sites/SitewideCAIA/Shared%20Documents/2.0%20Product%20work/GI%20Bill%20Comparison%20Tool/GI%20Bill%20comp%20tool%20cross-links%20tracker.xlsx?d=we722e973b452419dabeb5eb4294bbd58&csf=1&web=1&e=H1pQ3E). (This was done manually since the link audit function doesn't work for non-drupal pages.) These updates can be made once the tool updates happen in March.

**Comment by mnorthuis** [comment]
Email sent to Darla to determine who is planning to redirect the YR tool.

**Comment by mnorthuis** [comment]
Work being handled in other tickets.
