### ISSUE TITLE
Verification | Design | Update info box with date last verified

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#99504]
## Issue Description
_The VBA anticipates that the date last verified (DLV) will be available in VBMS for VA.gov to use around 1/26/25. Designs for the info alert should be updated to leverage the date (if available) for authenticated users._

![Image](https://github.com/user-attachments/assets/b8850360-bad2-45c0-941e-3ecc0ce22e31)

---
## Tasks
- [ ] Update info box to display date last verified
   - What will an authenticated user see if they do not have a DLV on record?
- [ ] Decide if additional information should be included. For example:
   - What does this date mean?
   - How often do I need to verify?
   - What happens if I don't verify?

## Acceptance Criteria
- [ ] DLV appears in info box
- [ ] If no DLV is available for user, alternative text displays
---

**Comment by steele-lm** [comment]
@ajialeilani Did we ever make this update? Or, should I keep this ticket open?

**Comment by ajialeilani** [comment]
@steele-lm I added the data to the [prototype](https://www.figma.com/design/bvj72inycD0iZkuCbjYTWL/Dependent-Verification-MVP?node-id=1987-39447&t=DRlpcf02q4Vu6oOI-1). There are several changes I'll need to transfer from the prototype to designs, including this one, and it could likely use a content team review, but the data's there. 

<img width="372" alt="Image" src="https://github.com/user-attachments/assets/63c98bed-d52e-4eb1-8bd9-ad676c45b0f5" />
