### ISSUE TITLE
Scrub Filename PII in Datadog Agent

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#99502]
## User Story
As an engineer on the VA.gov Platform, I want to ensure PII is scrubbed before it reaches a Datadog component so that we can ensure the safety and compliance of sensitive Veteran data. 

## Issue Description
As a [follow up to this ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1335/views/1?filterQuery=assignee%3ALindseySaari&pane=issue&itemId=91525536&issue=department-of-veterans-affairs%7Cva.gov-team%7C99499)...

It was discovered that PII was being leaked to Datadog due to filenames not being covered by our [existing scrubbing filters](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/filter_parameter_logging.rb). The issue stemmed from `ActionDispatch::Http::UploadedFile`, which was causing issue because our current scrubber only processes strings.

To mitigate this, we need to implemented a scrubber in a Datadog pipeline to filter out these filenames. We cannot ensure that Veterans refrain from including PII in filenames, as these are user generated inputs. Our long term goal is to apply this rule at the agent level to prevent sensitive data from ever reaching Datadog. A Datadog mapper at the agent level should be applied. [Example here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/datadog-agent/prod/values.yaml#L29)

Attached are relevant conversations and example logs for reference:
1. [Slack Conversation](https://dsva.slack.com/archives/C0460N83Y9G/p1734544550087249)
2. [Log Example 1](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20%40message_content%3A%22Completed%20%23submit_supporting_documents%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZPbJ-Eezu0xBgAAABhBWlBiSi1nekFBRFlwUE1Ed25IR2hnQUMAAAAkMDE5M2RiMzEtZTMwNy00Yjc0LTk1YTYtMjg1M2ExNmJiMmE4AAEHXQ&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=flex_tier&stream_sort=time%2Casc&viz=stream&from_ts=1734546674828&to_ts=1734559066860&live=false)
3. [Log Example 2](https://vagov.ddog-gov.com/logs?query=%22Completed%20%23upload%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZPawElX2lWXaQAAABhBWlBhd0dBd0FBQ2VvdDVHR0FIalZRQW4AAAAkMDE5M2RhYzItOTUzOS00M2ZlLWEzNjItN2FjNjhhMGY5NzhjAAFmZA&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Casc&viz=stream&from_ts=1734541316225&to_ts=1734627716225&live=true)

## Tasks
- [x] Put a stop gap solution in place through filtering pipelines in Datadog
- [ ] Ensure filtering is working

## Acceptance Criteria
- [ ] The immediate issue for filename exposure in Datadog is mitigated
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
