### ISSUE TITLE
Verification | Pull in date last verified

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#99505]
## Issue Description
_VBMS recently exposed the date last verified (DLV) value for VA.gov to consume. We need to display this date to Veterans on the FE (#99504) and in the email they receiving asking them to review their dependents, so they are aware of when they last officially verified their dependent with the VA. Veterans are required to verify every 8 years, but the goal is to get them to at least review their dependent info on VA.gov at least once a year._

---
## Tasks
- [ ] Connect to the xxx API
- [ ] Expose DLV within FE info box
- [ ] Expose DLV within verification email (template in VA Notify)
- [ ] Consider how to handle cases where DLV value is empty

## Acceptance Criteria
- [ ] DLV appears within FE info box
- [ ] DLV appears within verification email (VA Notify)
- [ ] Exceptions for missing DLV are handled
---

**Comment by TaiWilkin** [comment]
@jacobworrell Is this unblocked now? If so, we should consider including it in sprint 7
