### ISSUE TITLE
Confirm Rated Disability background job activity in Staging

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#99501]
## Issue Description
After submitting with 2 users that appeared to not have claims, we did not see the expected Lighthouse activity in our Rated Disability metrics.

Using an internal tool [clear-pending-claims-linktest.py](https://github.com/department-of-veterans-affairs/lighthouse-evss-form526/blob/master/tools/clear-pending-claims-linktest.py), clear the claims for an existing user (confirm BIRLS with Identity team) and run through the process again.

If activity continues to not show up, reevaluate our logic

12/24:
It appears that one of our toggles is placed in the EVSS submission path. This means that we won't get Lighthouse logs from that toggle, and when LH is turned on, Veterans with pending claims will not properly execute all_rated_disabilities.
Confirm that test Veterans are taking the LH path correctly, otherwise

12/26:
Tests have been run confirming that `pending_eps?` returns `false` in Argo in addition to all claims being cleared, with conditions that have valid `rated_id`s (e.g. tinnitus). The graph is receiving no activity, meaning the logic is not currently being reached (we'd see a stating something otherwise)

---
## Tasks
- [x] Use internal tools to clear existing claims for desired staging user
- [ ] Ensure Rated Disabilities are being called in submit form 526 background job (https://vagov.ddog-gov.com/s/f327ad72-c02a-11ec-a50a-da7ad0900007/n22-a99-8dk)
- [ ] If not called, determine why and fix

## Acceptance Criteria
- [ ] Lighthouse activity confirmed in the proper graph

**Comment by mchae-nava** [comment]
Tested using user 76, user 79, user 54, and ~270 (forgot the exact number)

Tested control run, deleting claims in Argo, and then using internal tools from EVSS to remove pending claims (confirmed and removed 8 from user 76)

Expected activity has not shown in the DD graph. Confirming that there is likely a bug and will investigate a fix

**Comment by mchae-nava** [comment]
Confirming that there are some issues with the graph; this is likely a metrics thing. DD seems confused about what we're asking for

**Comment by mchae-nava** [comment]
^ Graph issues were just a visual bug. Unless I'm mistaken, it appears that one of our toggles is placed in the EVSS submission path. This means that we won't get Lighthouse logs from that toggle, and when LH is turned on, Veterans with pending claims will not trigger `all_rated_disabilities`

Assuming this is correct, the toggle needs to be moved

However, I _am_ able to confirm that test Veterans are taking the LH path correctly, otherwise

**Comment by mchae-nava** [comment]
Activity confirmed 13:00 12/30

The issue was a misunderstanding on my part regarding `rating_code`. The form submitted need to be a CFI; when submitting for a new disability claim, it's not guaranteed that the user will have an existing `rdid`, so you need to run this with a user that has no pending EPs, but an existing Rated Disability to claim for increase
