### ISSUE TITLE
Remove Case Owner Name from DOMO Dashboard

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#99506]
## Issue Description

Currently, the Domo dashboard displays the names of case owners for each record. To enhance data privacy and meet regulatory or organizational compliance requirements, the case owner names should no longer be displayed on the dashboard. 

As a Data Analyst, I need to remove the case owner name from the Domo dashboard to maintain privacy and align with compliance standards.

---
## Tasks
- [x] _Remove "Case Owner" field from Dashboard 

## Acceptance Criteria
- [ ] The "Case Owner Name" field is removed from all relevant visualizations, tables, and reports on the Domo dashboard.
- [ ] Existing exports or historical data views no longer include the "Case Owner Name" field.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Completed 1/2/25 
https://va-gov.domo.com/auth/index?redirectUrl=%2Fpage%2F2073440432
