### ISSUE TITLE
Update VA Forms Library Pages

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#99532]
## Issue Description
Since there have been content updates recently to the VA Forms Library, the Content Team has noticed exessive use of emojis, bold type and italicised type. We need to review the pages in this section for further Style Guide violations and come up with a plan to address them.

---
## Tasks
- [ ] placeholder

## Acceptance Criteria
- [ ] placeholder
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
