### ISSUE TITLE
BPDS: Setup credentials (JWT)

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#99544]
# Overview
We need to get appropriate credentials to work on and to put data into the BDPS system

The payload is:
{
 "iss": {issuer}
 "iat": 1733423929,
 "jti": "d734e442-e1c7-45fd-a9fd-a1c89827c91e",
 "exp": 1733424829,
 "applicationID": {App Id},
 "stationID": {Station id},
 "userID": {userId}
}

So, four of those values look like they need be provided by John-Tyler.

You can start on some JWT authentication code to generate the iat, jti, and expiration.
The other four values will come from secrets.

This entire authentication to BPDS should be part of the scaffolding that Dan may have already started on.

# Tasks
- [ ] - Create a ticket for credentials https://jira.devops.va.gov/servicedesk/customer/portal/60/group/348
- [ ] - Write some JWT authentication based upon the above payload.
- [ ] - Store secrets (placeholders for now)
- [ ] - Test authentication

**Comment by mjknight50** [comment]
Dan has already done the initial ticket.

**Comment by aplatt-coforma** [comment]
Create jira ticket to request credentials here: https://jira.devops.va.gov/servicedesk/customer/portal/60/BEPOSD-416

**Comment by aplatt-coforma** [comment]
@danlim715 received credentials today.
