### ISSUE TITLE
Add OCTO-DE design practice area leads to DI, MPR and SR intro slides

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#99549]
## User Story
As a VFS team member participating in the Collaboration Cycle, I want to understand who the stakeholders and leads are in this process so that I know who makes the final decisions if there is conflict.

Assignee: @allison0034 
Peer Reviewer: @it-harrison 

## Description
We want to make it more clear to VFS teams that the OCTO-DE design practice area leads make the final call if there's any disagreement or push back on feedback or findings we communicate throughout the Collaboration Cycle. Although their roles are already defined on Platform Website, it might be more clear to VFS teams that these individuals have the final say in any disputes if their names and photos are shared alongside Matt Dingee's at the beginning of the touchpoint.

The purpose of this ticket is to modify the DI, MPR and SR[ intro slides ](https://docs.google.com/presentation/d/17r8Z4tPC8wD83t3FTyaBzo9vMLRYYwWJ73FailI3Exw/edit#slide=id.g23db8d1d252_0_248)to include the following individuals:

- Accessibility: Martha Wilkes 
- Content: Danielle Thierry & Beth Potts
- Information Architecture (IA): Mikki Northuis
- Research: Shane Strassberg
- Mobile: Ryan Thurlwell

### Live pages
- [Slide deck](https://docs.google.com/presentation/d/17r8Z4tPC8wD83t3FTyaBzo9vMLRYYwWJ73FailI3Exw/edit#slide=id.g2e76d6c165a_0_0)

### Drafted pages
- 

## Tasks
- [x] Confirm if we should list both Danielle Thierry and Beth Potts for content, or if just Danielle will suffice
- [x] Contact all individuals listed above, cc Matt Dingee, via the #platform-collaboration-cycle channel. Inform them that we will be adding their names and photos to our touchpoint intro slides to ensure VFS teams know who they are and understand their role in the Collaboration Cycle process. Ask if they'd be okay with us using their Slack photo, or if they prefer, they can send us another photo
- [x] Once we hear back from all individuals, edit the intro slides to include the full Governance team as well as the OCTO-DE Design Practice Area leads. Edit Matt's title from PO to "Design Lead". All titles should include the practice area and then "Lead"
- [x] Once slides are updated, share in the original thread for awareness. If anyone has feedback, they're free to share, but do not ask for approval or for them to review.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have added the OCTO-DE Design Practice Area leads names and photos to our touchpoint intro slides

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Had to remove photos due to spacing. Created [draft](https://docs.google.com/presentation/d/1YMJZEVbBJ6WIxTE6TvxTSqSLntKhMWcMdq9uEnt6O7I/edit#slide=id.g23db8d1d252_0_248) and [made OCTO aware](https://dsva.slack.com/archives/G01DXP10GCA/p1737559747109589).

**Comment by allison0034** [comment]
@it-harrison the [live slides](https://docs.google.com/presentation/d/17r8Z4tPC8wD83t3FTyaBzo9vMLRYYwWJ73FailI3Exw/edit#slide=id.g2e76d6c165a_0_0) have been updated.

**Comment by it-harrison** [comment]
@allison0034 - looks good!

**Comment by shiragoodman** [comment]
I miss the photos, but understand that space was limited. Looks good, Allison!
