### ISSUE TITLE
[Burial Module] flipper implementation to route API calls to module paths

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#99554]
## Issue Description

Implement FE and BE flipper redirection to module controlled paths

---
## Tasks
- [ ] FE flipper implemented
- [ ] BE flipper implemented

## Acceptance Criteria
- [ ] when the flipper is enabled, api calls will direct to the module controlled paths
- [ ] when the flipper is disabled, a forbidden response will be returned

**Comment by balexandr** [comment]
@aplatt-coforma I think this is a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/98411

**Comment by aplatt-coforma** [comment]
Closing as dup as Bryan noted above.
