### ISSUE TITLE
Automate Github Projects - Platform Support Team - Support Tickets

### ISSUE THREAD

**Issue by bdech** [department-of-veterans-affairs/va.gov-team#99568]
## Issue Description
Platform Support receivesl support requests through Github issues. We have recently switched to using the Github projects (over from Zenhub). This initiative aims to eliminate the manual work required to move and organize tickets into our respective columns.  This will allows us to address issues more efficiently.

How might we automate Github projects in a way that pulls new issues into the project board, and organizes based on ticket type? 

Creating a GitHub Action that triggers a workflow whenever a new GitHub issue is opened. The workflow will check the label attached to the issue, add it to our GitHub Projects board, and place it in the appropriate column.

---
## Tasks
- [x] Configure [action](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/assign-to-support-project.yml) in `va.gov-team`
- [x] [Test] Workflow with [Platform Support Team - Support Tickets](https://github.com/orgs/department-of-veterans-affairs/projects/1408/views/1?filterQuery=)
- [x] Create [documentation](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426241154/Ticketing+Best+Practices#GitHub-Project-Automation) outlining the purpose of the automation and how it works. Publish the documentation in Confluence or GitHub
- [x] Publish & Share with Platform Support team

## Acceptance Criteria
- [x] New issues tagged with `platform-support-ticket` or `new-vfs-team`, or `new-vfs-team-member`, `platform-tech-team-support`, and `T1-access-request` are assigned to this [project board](https://github.com/orgs/department-of-veterans-affairs/projects/1408), and organized into the respective column
- [x] Document automation of adding issues to a Github project

**Comment by bdech** [comment]
Running into issues with the GitHub action being utilized in the workflow file. Been working on debugging for a few days now. Have a feeling this GitHub action may be bugged, and may need to find an alternative action to use. https://github.com/srggrs/assign-one-project-github-action/issues/65

**Comment by alyssagallion** [comment]
Moved to next sprint since it is taking longer to research than planned!

**Comment by bdech** [comment]
Sprint item is complete. Github workflows are working as expected. Accompanying documentation has been written and published. Its nested in the ticketing best practices doc. I felt that was suitable. If we need to, I can move it.
