### ISSUE TITLE
Mock Flipper Behavior in Specs

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#99574]
As a developer, I want to mock flipper behavior in spec files, to reduce unpredictable test behavior

## Summary
Currently, there are instances in the codebase where Flipper features are directly enabled using Flipper.enable during spec tests. This approach can lead to unpredictable test behavior, as the enabled state of features might inadvertently affect other tests, especially when running in parallel.

The best way to tackle this might be do look for flippers with fewer instances? 

## Tasks
- [ ] Audit the spec codebase to locate all occurrences of Flipper.enable and Flipper.disable in spec files.
- [ ] Replace direct calls to Flipper.enable with mocked behavior using appropriate mocking techniques (e.g., allow(Flipper).to receive(:enabled?).with(<feature_key>).and_return(true/false))
- [ ] Update the development/testing documentation to highlight the best practices for working with Flipper in specs, emphasizing the use of mocking.

## Acceptance Criteria
- [ ] Flipper behavior is mocked in the spec codebase.
