### ISSUE TITLE
[Design] Notifications overview and refresher

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#99604]
## Background
To prepare for improving notifications across the authenticated experience on VA.gov, the team should have an overview readily available for a high-level understanding of where things are at today, starting with our domains of My VA and Profile (and in a future ticket(s), notifications beyond them on VA.gov and the mobile app). 

As a designer, I want to understand and document the high-level state of notifications as of the end of 2024, so that our team is better prepared for updates in 2025 and beyond.

---
## Tasks
- [x] Review current team documentation and notes on notifications

## Acceptance Criteria
- [x] Document initial findings
- [ ] Discuss findings with team
- [ ] Create list of items to get more clarity on

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? Product

## Resources
[Notification notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/design/Notification%20High%20Level%20Notes.md)

**Comment by mattmarino-adhoc** [comment]
To do after this ticket:

- [ ] Review Mural for relevant content from other teams
- [ ] Review documentation on github from other teams
- [ ] Continue documenting findings
- [ ] Discuss initial findings, any knowledge gaps, with team
- [ ] Create list of items that need to be clarified after this sprint, when more stakeholders are available

**Comment by mattmarino-adhoc** [comment]
This ticket's scope was not fully completed due to the end of the team's contract renewal period. The notes on this ticket provide some overview of the BE notification services for My VA.
