### ISSUE TITLE
Update Calendly to include links

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#99611]
## User Story
As a Governance team member supporting Collaboration Cycle, I want to have Calendly include any links we can capture during scheduling so that I can lessen our support burden and help with cancelling/rescheduling touchpoints.

Assignee: 
Peer Reviewer:  

## Description
In #97981 it was discovered that we can capture links in Calendly and automatically include them on the meeting invite.  

### Live pages
- [Rescheduling and cancelling touchpoints](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2737766401/Rescheduling+and+cancelling+touchpoints)

### Drafted pages
- 

## Tasks
- [ ] Think about links we can capture and include directly thru calendly (collab cycle ticket, maybe a link directly to the drafting folder rather than a specific file?)
- [ ] Reach out to team and see what ideas they may have
- [ ] Update Calendly to include links
- [ ] Update on support guidance

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team has documented clear guidance and steps for our team to follow if/when a VFS team cancels or reschedules a touchpoint
- [ ] Governance team has documented clear guidance and steps for our team to follow if/when we need to cancel or reschedule a touchpoint

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer
