### ISSUE TITLE
[Research & Design] Urgent care mash-up

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9961]
## Issue Description
- [Previous research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/urgent-care/research-findings.md) revealed that Veterans searching for urgent care facilities want to see both VA facilities and Community care (in VA's network) facilities in a **single** search result list.  
- There are differences in eligibility and coverage for VA locations vs community care locations. 
- **We need to represent these locations in a single list and validate our design with Veteran feedback.** 

## Current behavior

Currently, when Urgent care is selected as the VA facility type, Veterans must choose to search for **VA urgent care** or **Community urgent care (in VA's network)** as a service type. 

<details> 
<summary>If "Choose a service type" = Community urgent care (in VA's network),</summary> 

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/c7306ceb-63ce-4290-aca8-39789ffd4dd1)

- The "Important information about your Community Care appointment" alert displays.
- Search result cards label the location as RETAIL/WALK-IN CARE or URGENT CARE (based on POS code).
- Search result cards include a "call first" message. 

![image](https://user-images.githubusercontent.com/55411834/85906404-735de980-b7cb-11ea-8e50-552a5bf31d80.png)

</details>

<details> 
<summary>If "Choose a service type" = VA urgent care</summary> 

![image](https://user-images.githubusercontent.com/55411834/85906534-d8194400-b7cb-11ea-8383-9c0103fa324d.png)

- No alert is displayed . 
- Search result cards label the location as VA URGENT CARE
- Search result cards do not include the "call first" message. 

</details>

---
## Task 1
<details>
 <summary>Collaborate with Ryan Thurlwell to create a prototype for use in gathering Veteran feedback which addresses the following user stories: </summary>

- Veterans can search for Urgent care facilities and view a single list containing the closest VA facilities and Community urgent care providers. 
- Veterans can differentiate between VA facilities and Community urgent care providers in the list. 
- Veterans have access to the alert information for Community urgent care providers in their search results. 
- Search result cards contain the same basic facility information as currently displayed in FL searches. 

</details>

## Task 2
<details>
 <summary>Develop a research plan to submit for approval/initiation of recruitment which will validate design choices</summary>

- Does the design help Veterans understand the differences between the facilities returned in the result list?
- Does the design help Veterans know how to access the alert/benefit information if they choose to visit a Community urgent care provider? 
- Are the labels used in the cards meaningful to Veterans?

</details>

## Task 3
- [ ] Develop a conversation guide which supports the research plan

## Acceptance Criteria
- [ ] Prototype is available for use in Veteran research
- [ ] Approved research plan
- [ ] Approved conversation guide
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@lildziner please link to prototype and research plan/guide

**Comment by lildziner** [comment]
[Prototype](https://preview.uxpin.com/f373333a8a59902cbf120c3f00e6d0e13d52fb75#/pages/130395562?mode=cvhidm)
[Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/urgent-care-mashup/research-plan.md)
[Convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/urgent-care-mashup/conversation-guide.md)
