### ISSUE TITLE
Q4 2024 Metrics

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#99627]
## Background
Time to pull quarterly quant/qual metrics for Q4 2024.

Process for the FAQ survey feedback:
1. View [Github folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/sitewide-content/unauthenticated-content-outcomes-and-metrics/monthly-experience-ratings/ratings-by-month) and grab the link for "Resources and support ratings spreadsheet" (in the bottom Analysis section).
2. View the spreadsheet link in Sharepoint and request access
3. Once access is granted, locate the row that has our FAQ page. 
3. Document the metrics for our FAQ page:  Good, Bad and Total responses, and % of Good and % of Bad.

## Tasks
- [ ] [Request contact center feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=ianMcCullough-ob%2C+ATMiddleton&labels=VSP-contact-center%2Ccc-data-request&projects=&template=qualitative-data-request.yml&title=Qualitative+Data+Request) for MyVA411 for Q4 ([example ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87293))
- [ ] [Request contact center feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=ianMcCullough-ob%2C+ATMiddleton&labels=VSP-contact-center%2Ccc-data-request&projects=&template=qualitative-data-request.yml&title=Qualitative+Data+Request) for Medallia for Q4 ([example ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87294))
- [ ] Remove PII from feedback
- [ ] Recap contact center feedback in Sharepoint
- [ ] Gather FAQ survey feedback for Q4 (process notes above)
- [ ] Recap FAQ survey feedback in Sharepoint

## Acceptance Criteria
- [ ] Q4 analytics are in Sharepoint

**Comment by oddball-lindsay** [comment]
Submitted contact center requests: (MyVA) and (Medallia).

Requested access the the Dec 2024 spreadsheet, for FAQ survey feedback.

**Comment by oddball-lindsay** [comment]
Received FAQ survey feedback, summarized in Sharepoint.
Received Medallia feedback, removed PII, uploaded to Sharepoint, and summarized feedback in Sharepoint.

Now just waiting on the MyVA411 feedback.

**Comment by oddball-lindsay** [comment]
There are over 2k pieces of MyVA411 feedback, but I think that is just a data dump of all feedback OR they included "claims" and "support" as opposed to "claims support" which I could see ballooning the amount of feedback. 

Here's how the feedback relates to our key words:

accredited - 0 results
representative - 34 results
representation - 0 results
power of attorney - 5 results
poa - 2 results
attorney - 11 results
claims agent - 1 result
vso - 28 results
veteran service organization - 1 result
vso representative - 0 results
vso rep - 0 results
veterans service officer - 2 results
service organization representative - 0 results
21-22 - 5 results
2122 - 0 results
21-22a - 1 result
2122a - 0 results
claims support - 0 results

I'm going to filter the feedback to only those related to our keywords, to get to a manageable amount to look through.

**Comment by oddball-lindsay** [comment]
Filtering the feedback is extremely tedious, I'm just going to tally up the type of responses and call it a day. Will not upload the export to our Sharepoint folder, because I am not able to scrub all of these for PII.

**Comment by oddball-lindsay** [comment]
Was able to filter the feedback by our key terms and this brought us down to 44 call logs, much more manageable.
