### ISSUE TITLE
[Design] Update content for CC API failure alert

### ISSUE THREAD

**Issue by StevenStraily** [department-of-veterans-affairs/va.gov-team#99626]
## Related Documentation
[Slack Thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1734977797648899)

## Description
Change the content on the alert to better represent previous messaging for the same error.

## Reference Materials
[Figma File](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=6477-14057&t=Oi6XSvr1DY46KsPU-4)

## Tasks
- [ ] Determine what content to bring over from the previous alert
- [ ] Update wireframes
- [ ] Set up a review with the rest of UX and Kristen

## Acceptance Criteria
- [ ] Content on all wireframes is updated 
- [ ] Plan to share and discuss at the next UX sync

**Comment by cgednalske** [comment]
@StevenStraily I'm not sure if this one is still needed now that we've replaced the details page with the confirmation page for error scenarios. Thoughts?

**Comment by cgednalske** [comment]
Closing this out as we no longer need it
