### ISSUE TITLE
December 2024 Metrics

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#99628]
## Background
Time to pull monthly metrics for December 2024.

## Tasks
- [x] Add GA4 metrics for December to the [GSheet](https://docs.google.com/spreadsheets/d/16Tr3nVdRHTteverx5yoBoBV32s0wvUrtW4-Daoi4hEE/edit?gid=458272975#gid=458272975)
- [x] Add Datadog metrics for December to the [GSheet](https://docs.google.com/spreadsheets/d/16Tr3nVdRHTteverx5yoBoBV32s0wvUrtW4-Daoi4hEE/edit?gid=458272975#gid=458272975) (Widget only)
- [x] Update the graphs in the [GSheet](https://docs.google.com/spreadsheets/d/16Tr3nVdRHTteverx5yoBoBV32s0wvUrtW4-Daoi4hEE/edit?gid=458272975#gid=458272975)
- [x] Export the GSheet to Excel and upload to Sharepoint

## Acceptance Criteria
- [x] December performance metrics are in Sharepoint
