### ISSUE TITLE
[CDP] VHA - Update Dispute process AskVA instructions

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#99633]
## Issue Description
Add instructions and action link to AskVA on the Resolve section of VHA Debt Portal. Update mockups based on stakeholder feedback.

## Tasks
- [x] Send mockup to VHA
- [x] Implement updates to mockups

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required    - future ticket

## Acceptance Criteria
- [x] Mockups sent to VHA
- [x] [Mockups updated](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=4425-28578&t=GzdRQBlalK3Vwfg9-1)
## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Assign Type
- [x] Assign Priority (Normal = Medium)
- [x] Assign Group(s)
- [x] Assign to a Project
- [x] Attach to an Parent Epic
- [x] Estimate Points

</details>
