### ISSUE TITLE
[2] Wizard usability study research planning step 2

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#99630]
## Issue Description

Step 2, write conversation guide and notetaking guide    

## Tasks
- [x] Write conversation guide
- [x] Write AT conversation guide
- [ ] Write notetaking guide 

## Acceptance Criteria
- [x] Conversation guide draft written
- [ ] AT conversation guide written
- [ ] Published to GH
- [ ] Notetaking guide is ready

## Testing
- [x] N/A if non development work

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Assign Type
- [ ] Assign Priority (Normal = Medium)
- [ ] Assign Group(s)
- [ ] Assign to a Project
- [ ] Attach to an Parent Epic
- [x] Estimate Points

</details>

**Comment by charlottecesana** [comment]
This ticket was started late in the sprint, and it will carry over to the new sprint beginning tomorrow with 2 points remaining. We are 50% done with the conversation guide and we need to connect with CAIA about testing comprehension on the pages that are linked since these pages are essential to the Veteran understanding the paths. 
CC: @Tom-Davis

**Comment by charlottecesana** [comment]
This ticket is complete. 
[The conversation guide is up on GitHub ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/combined_fsr/wizard/research/jan-2025)
[The AT conversation guide is up on GitHub as well ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/wizard/research/jan-2025/conversation-guide-at.md)

We will have to make adjustments once conversations with the CAIA team resume for refinements to the Wizard complete-a-subtask prototype. Additionally, the notetaking guide will be created once prototype and associated conversation guides are final.
