### ISSUE TITLE
[CDP] VBA - Update Dispute process AskVA instructions

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#99634]
## Issue Description
Add instructions and action link to AskVA on the Resolve section of VBA Debt Portal. Update mockups based on stakeholder feedback.

## Tasks
- [x] Send mockup to VBA
- [x] Implement updates to mockups

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required    - future ticket

## Acceptance Criteria
- [x] Mockups sent to VBA
- [x] Mockups updated
## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Assign Type
- [ ] Assign Priority (Normal = Medium)
- [ ] Assign Group(s)
- [ ] Assign to a Project
- [ ] Attach to an Parent Epic
- [ ] Estimate Points

</details>

**Comment by mgleo** [comment]
- Content was shared and approved by VBA. 

- [Mockups are on Figma.](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=4425-28578&t=GzdRQBlalK3Vwfg9-1).

- [CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/100814) was created. CAIA will review and update content if needed.
