### ISSUE TITLE
[Wizard] Update prototype intro page

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#99635]
## Issue Description
Update intro page of the Wizard prototype to incorporate FSR intro page. 
https://n4hl2d.csb.app/

## Tasks
- [x] Update intro page on Code Sandbox Wizard prototype
 

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] Intro page on prototype has been updated

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Assign Type
- [x] Assign Priority (Normal = Medium)
- [x] Assign Group(s)
- [x] Assign to a Project
- [x] Attach to an Parent Epic
- [x] Estimate Points

</details>

**Comment by mgleo** [comment]
Intro page has been added to prototype: https://n4hl2d.csb.app/
