### ISSUE TITLE
Wizard and Digital Dispute Usability Study (evaluative) - Moderator ticket (step 5)

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#99640]
## Issue Description

8-10 interviews with Veterans for Wizard and Digital Dispute Usability Study (evaluative)

## Tasks
- [x] At least 8 interviews take place

## Acceptance Criteria
- [x] Interviews have taken place

## Testing
- [x] N/A if non development work

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [x] Assign Type
- [ ] Assign Priority (Normal = Medium)
- [ ] Assign Group(s)
- [ ] Assign to a Project
- [ ] Attach to an Parent Epic
- [x] Estimate Points

</details>

**Comment by charlottecesana** [comment]
8 interviews have taken place and we will host the remaining interviews in Sprint 9. I have opened #110093 (https://github.com/department-of-veterans-affairs/va.gov-team/issues/110093)
