### ISSUE TITLE
January Medallia Feedback Report (for December 2024 data)

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#99647]
## Issue Description

Monthly reporting on Medallia satisfaction data.

## Tasks
- [x] Extract data
- [x] Analyze data
- [x] Write report
- [x] Publish to GH

## Acceptance Criteria
- [x] Published to GH

## Testing
- [x] N/A if non development work

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Assign Type
- [ ] Assign Priority (Normal = Medium)
- [ ] Assign Group(s)
- [ ] Assign to a Project
- [ ] Attach to an Parent Epic
- [x] Estimate Points

</details>

**Comment by charlottecesana** [comment]
[The report is live on GitHub. ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/research/medallia_reports/Medallia-December-2024.md)
