### ISSUE TITLE
Determine content for VAHB mobile wireframes

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#99654]
## Background
All content for our VAHB mobile wireframes need to be determined/updated based on mobile app's content approach. **Note:** we may run into delays with this due to mobile app team changes/timeline.

## Tasks
- [ ] Find and review content mobile app content documentation
- [ ] Update content for all wireframes to follow mobile content approach
- [ ] Work with Laura and/or mobile content designer to confirm content changes

## AC
- [ ] VAHB wireframes updated to reflect mobile app content approach
- [ ] Content submitted to Laura and/or mobile content designer to confirm content changes (back and forth likely needed and can be started during this sprint)
