### ISSUE TITLE
[SPIKE] Determine scope for NoK and EC based on Profile timeline

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#99662]
## Background
The Cartography and Profile team shared more information with us on the future implementation direction and timeline for NoK and EC editing. 

As of now, they do not have editing capabilities, but plan to add them in the future (timeline not confirmed) and have the designs to represent these additions.

## Tasks
- [x] Relay updated Profile information to Kristen
- [x] Work with Kristen to determine if/how this impacts what we'll do for the MVP of VAHB demographics check
- [ ] Create any follow-up tickets for resulting wireframe changes

## AC
- [x] MVP scope (and following iterations) solidified
- [ ] Follow-up tickets created for any resulting wireframes changes

**Comment by cgednalske** [comment]
Meeting scheduled with Kristen for 1/27

**Comment by cgednalske** [comment]
We met with Kristen and Kay on 1/27 and determined the following:

- There are enough blockers that UX will fully pause on this work until engineering has capacity to complete full discovery (and Cartography/Profile teams add editing for NoK and EC)
- The ideal approach will also take into account the eventual addition of things like questionnaires and clinical orders to Pre-check-in, so whenever UX resumes this work, we will evaluate/update our designs accordingly.

In-depth information about status, decisions, etc. included in our new [Slack canvas](https://dsva.slack.com/docs/T03FECE8V/F08B6KUMHNC) in the #appointments-ux channel.

No follow-up tickets needed.
