### ISSUE TITLE
[URGENT] Remove redirect for legacy site claim exam page

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9966]
This is an urgent change that needs to be deployed as quickly as possible because it  is communicating something that is COVID-19 service impacts.
This needed change was relayed to Jen Lee and to the team via Slack on 06/08/2020.

The page https://benefits.va.gov/compensation/claimexam.asp was just updated to include a map with C&P claim exam locations that will be re-opening as part of the regional rolling VA in-person service re-openings per various state/localities easing of the coronavirus lockdown

It is going to be updated weekly with regional re-openings.

There is currently a redirect in place that blocks users from seeing this page -
https://benefits.va.gov/compensation/claimexam.asp -> https://www.va.gov/disability/va-claim-exam/

**Task**
- [ ] Remove the redirect that is currently in place
- [ ] Validate post-deploy that the page is accessible and no longer being redirected

**Acceptance Criteria**
- [ ] https://benefits.va.gov/compensation/claimexam.asp is accessible to site users

**Comment by stephorkandatx** [comment]
Work to place the redirect made in https://github.com/department-of-veterans-affairs/va.gov-team/issues/6087

**Comment by kelsonic** [comment]
Will require an off-schedule deployment, not sure what the process is for this but posted it in #vfs-platform-support here: https://dsva.slack.com/archives/CBU0KDSB1/p1591649643139300

**Comment by stephorkandatx** [comment]
I have validated that https://benefits.va.gov/compensation/claimexam.asp is viewable and not blocked by a redirect. 

CC @bethpottsVADEPO I am closing this ticket out.
