### ISSUE TITLE
[Silent Error] Create Metric/Alert for when we trigger Silent error

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#99685]
## Issue Description
Given: We need to respond to ALL errored forms
When: Octo receives an alert about a silent error
Then: We need to be alerted as well

## Tasks
- [ ] Create a monitor for everytime a 5655 form goes into an error state

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Monitor is created

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [x] Assign Type
- [x] Assign Priority (Normal = Medium)
- [x] Assign Group(s)
- [x] Assign to a Project
- [x] Attach to an Parent Epic
- [x] Estimate Points

</details>
