### ISSUE TITLE
[Silent Error] Quiet VHA errors triggering Silent error alerts to Octo

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#99686]
## Issue Description
Given: We want to know when/how a submission failed
When: A 5655 fails submitting to VHA
Then: We need to get logs/info about why and how a VHA submission failed.

Our VHA [submission happens via a Sidekiq batch](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/debts_api/app/models/debts_api/v0/form5655_submission.rb#L59). Since we've added the register_failure method to the [set_vha_completed_state](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/debts_api/app/models/debts_api/v0/form5655_submission.rb#L76) method, we've been triggering silent errors to Octo and this makes us look bad.

I think all of our recent errors are with Sharepoint submissions. We need to look into the batch process and come up with a plan to either disable the sharepoint submissions, find out why we error frequently with them, and maybe get better logging for when we trigger `if status.failures.zero?` as false

## Tasks
- [ ] Check in with Denise about Sharepoint's necessity
- [ ] Look into better logging with the batch process and devise a plan
- [ ] If we need Sharepoint submission still, look into why we error and come up with a plan to quiet them if possible

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Game plan for getting Sharepoint/VHA and thus silent errors quieted. 

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Assign Type
- [ ] Assign Priority (Normal = Medium)
- [ ] Assign Group(s)
- [ ] Assign to a Project
- [ ] Attach to an Parent Epic
- [ ] Estimate Points

</details>

**Comment by HeatherRienks** [comment]
Per Derek, this work has been completed.
