### ISSUE TITLE
[Copay Errors] Go through config for VBS and get values mapped properly

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#99687]
## Issue Description
Given: We want VBS to remain stable throughout platform changes
When: VSP makes changes to our infrastructure
Then: Our system will not fall apart

Fresh off a week of down-age with VBS, it's come to my attention that our configuration across the following repos and services is brittle.

vets-api -> vsp-infra-application-manifests -> [AWS parameter store](https://us-gov-west-1.console.amazonaws-us-gov.com/systems-manager/parameters/?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:mcp%2Fvbs_v2)

## Tasks
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3          

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance Criteria
- [ ] Item one from the description performs as described in the description
- [ ] Item two from the description performs as described in the description      

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Assign Type
- [ ] Assign Priority (Normal = Medium)
- [ ] Assign Group(s)
- [ ] Assign to a Project
- [ ] Attach to an Parent Epic
- [ ] Estimate Points

</details>

**Comment by HeatherRienks** [comment]
See additional info here: https://dsva.slack.com/archives/CE4304QPK/p1741711872545919

Due date: APRIL 22, 2025

**Comment by HeatherRienks** [comment]
Closing this ticket as completed - work was done in: https://github.com/orgs/department-of-veterans-affairs/projects/1514/views/2?sliceBy%5Bvalue%5D=Sprint+5&pane=issue&itemId=93382017&issue=department-of-veterans-affairs%7Cva.gov-team%7C100846
