### ISSUE TITLE
Launch Grey Sky Product Health Tool

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#997]
## User Story
As a VFS stakeholder, I need to understand what the VSP Analytics and Insights team's product health tool will look like so I can prioritize my KPIs.

## Goal
Design the first draft of the "grey sky" product health tool.

## Acceptance Criteria
- [x] Design the first draft of the "grey sky" product health tool
- [x] Share results with team and DSVA

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
