### ISSUE TITLE
Update Product Documentation in Github

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#99705]
## Background
Review [product documentation in Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management) and update as needed for accuracy and clarity. 

## Tasks
- [x] Update Find a Rep documentation
- [x] Update Rep Status Widget documentation
- [x] Update Appoint a Rep documentation

## Acceptance Criteria
- [x] Product documentation in Github is up to date

**Comment by oddball-lindsay** [comment]
Ended up consolidating the "overview" documents into the "product outline" document, with a new "Release History" section. I think this will be more helpful in seeing the version history journey and should be easier for folks to know what document to look at.

Also added in the status codes for the Rep Status Widget, and how those map to what states the user sees.
