### ISSUE TITLE
[CDP] Update copays in betamocks so dates are current (within past 6 mo)

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#99728]
## Description

When this feature flipper is enabled (http://localhost:3000/flipper/features/medical_copays_six_mo_window), copays don't show because they are outdated in Betamocks, and that makes it hard to test the portal.

Can use this [PR](https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/493) from Max to fix this issue. 

Given: A designer/engineer needs to see copays in local/staging 
When: A designer/engineer looks at the debt portal
Then: They should see copays without having to disable the `medical_copays_six_mo_window` feature flipper

## Tasks
- [x] Update copay dates in betamocks to be recent (within the past 6 mo)
- [ ] Have one copay be current (this month)

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ ] Not Required           

## Acceptance criteria
- [ ] Copays display in the CDP without having to disable the feature flipper

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
<details><summary>Ticket requirements</summary>
      
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Assign Type
- [ ] Assign Priority (Normal = Medium)
- [ ] Assign Group(s)
- [ ] Assign to a Project
- [ ] Attach to an Parent Epic
- [ ] Estimate Points

</details>

**Comment by Dr-Pongo** [comment]
@penny-lischer 

Can we make a follow on ticket for May 2025? Just as a reminder for next time this happens

**Comment by penny-lischer** [comment]
Merged and waiting for code freeze to end to validate in production.

**Comment by penny-lischer** [comment]
> [@penny-lischer](https://github.com/penny-lischer)
> 
> Can we make a follow on ticket for May 2025? Just as a reminder for next time this happens

Future ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99888)

**Comment by Dr-Pongo** [comment]
Couldn't find the direct link to the PR but wanted to note it here!
department-of-veterans-affairs/vets-api-mockdata/pull/572
