### ISSUE TITLE
Representative Select: Add submission methods to rep search results

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#99786]
## Background
When users are searching for representatives on the `representative-select` page, we want to enhance the search result cards to show how those representatives accept the form 21-22 or 21-22a. 

This information will only be available when the user is eligible for digital submission (per https://github.com/department-of-veterans-affairs/va.gov-team/issues/99971).

The options will be:
1. **Online** -- these are reps who have opted in to accept digital POA requests via the Accredited Representative Portal (ARP). 
   1. Related work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/99972). 
3. **By mail and in person** -- all representatives should accept this method by default.

Implementation notes: 
1. This submission method is only for individual VSO representatives, for pilot.
2. The submission method order should always be: online, by mail, THEN in person.

## Designs
1. [Mobile](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=6329-256217&t=oO7ZdPgGPZBQfmM2-4)
2. [Desktop](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=6329-262120&t=oO7ZdPgGPZBQfmM2-4)
3. [Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=11273-561392&t=oO7ZdPgGPZBQfmM2-4)

In this example, Brian Daniel does accept digital submission and Lisa Daniel does not.
![Image](https://github.com/user-attachments/assets/431cf8e7-d79d-4b26-af6a-382f2e5a663d)

## Tasks
- [ ] Update the contact card component in the rep search results, to also include the submission methods.
- [ ] Ensure the online submission method is referencing the correct backend field.

## Acceptance Criteria
- [ ] As a user interested in appointing a representative online through a digital request, I can confirm up front (i.e. at the start of the Appoint a Rep experience) which representatives are accepting digital requests for appointment.

**Comment by oddball-lindsay** [comment]
> To confirm `This information will only be available when the user is eligible for digital submission` means that the new `Accepts VA Form...` content should only appear under specific user conditions? It's not "always show" content.

Correct this content should only appear under specific user conditions, and this case it's the "eligible for digital submission" user conditions. Which I think is the same thing as saying "gate this with the v2 feature flag".

The reason for this is that we don't want to set expectations for digital submission for users that cannot access it. Small concern for pilot, but it'll become a larger concern as the amount of representatives accepting digital submission increase.

**Comment by jvcAdHoc** [comment]
The pr assumes that all submission methods are available to all rep types. We can clean that up once submission method storage is implemented.

**Comment by mtri** [comment]
[Figma screen](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=13090-378835&t=YOAQy5Nvms7HSnCr-11)
- Missing an h3 above the question. Should be “Select how to submit your request”
- Question copy was recently tweaked when we had the error copy written. “Select how to submit your request” should be “How do you want to submit your request?”
- Missing Note copy below question: “**Note:** If you want to submit your request by mail or in person, you’ll need to print your form at the end of our online tool. We’ll provide instructions on how to submit it.”

Other than these copy changes, all seems good!

**Comment by jvcAdHoc** [comment]
@mtri I think that feedback is for https://github.com/department-of-veterans-affairs/va.gov-team/issues/99788

**Comment by mtri** [comment]
@jvcAdHoc Thanks for catching that! Sorry for the confusion, I’ll review the methods on the cards momentarily.

**Comment by mtri** [comment]
Using the cross accredited VSO rep John Hood as an example:

<img width="542" alt="Image" src="https://github.com/user-attachments/assets/3d8c78bb-3a18-4a60-83d1-4b8e2bf36651" />

The submission method text doesn’t seem to be displaying on the card. The method question does show afterward for online, in-person, and by mail, so it seems like it is attached to the representative. Am I testing this correctly?

**Comment by jvcAdHoc** [comment]
Were you logged in with a test account?

**Comment by mtri** [comment]
Yeah, I tried a couple test accounts last Friday and today used vets.gov.user+10@gmail.com with the same results. I tested in Chrome and Safari and restarted the application.

**Comment by mtri** [comment]
Looks good! Tested with vets.gov.user+21@gmail.com on mobile and desktop.

**Comment by jvcAdHoc** [comment]
I'm good with that
