### ISSUE TITLE
Submission Method page

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#99788]
## Issue Description

If users select a VSO representative to appoint and that representative is accredited with multiple organizations, **with different submission methods**, the user will need to select how they'd like to submit their request (in person/mail vs. online).

This functionality introduces a new page, and this "Representative Submission Method" page will only be available when:
1. The user is eligible for digital submission (per https://github.com/department-of-veterans-affairs/va.gov-team/issues/99971).
2. The representative accepts digital submission (per https://github.com/department-of-veterans-affairs/va.gov-team/issues/99972).
  
**URL**: `/representative-submission-method`  

**Previous path**: `/representative-contact` (ONLY if the selected representative has multiple organizations, with multiple submission methods)

**Next path**: `/representative-organization` 

[Appoint Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)
<img width="970" alt="Image" src="https://github.com/user-attachments/assets/754a25fb-c2a5-4618-a141-bab2fda31dc6" />

## Designs
1. [Mobile](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=13039-426865&t=oO7ZdPgGPZBQfmM2-4)
2. [Desktop](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=13072-223435&t=oO7ZdPgGPZBQfmM2-4)
3. [Error state](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=13090-378835&t=iv4rwHkrD6ucHwj3-4)

**Desktop view:**
<img width="533" alt="Image" src="https://github.com/user-attachments/assets/954a0276-37af-4d17-94e0-5694ebade3e3" />

**Error state:**
<img width="335" alt="Image" src="https://github.com/user-attachments/assets/48e92ec8-9055-4e83-a4d7-b4b611ac5ae2" />

---
## Tasks
- [ ] Create the Submission Method page based on the designs above
- [ ] Set up the proper logic for displaying the page as documented in the [Appoint Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)
- [ ] Store the submission method so we can update the CTA (and submit the request) at the end of the Appoint a Rep experience
- [ ] Add in unit tests

## Acceptance Criteria
- [ ] A Submission Method page has been implemented, with the specs outlined above.
- [ ] The user's selection will dictate if the Appoint experience ends in digital submission or PDF download/print.

**Comment by oddball-lindsay** [comment]
@cosu419 calling out that the design is now slightly out of date. Jen said it's fine to place the "Online" option first! 

I'll add a new screenshot to the issue above, after Michael's had a chance to update in Figma.

**Comment by oddball-lindsay** [comment]
Michael created an [error state for this page](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=13090-378835&t=iv4rwHkrD6ucHwj3-0) and I'm wondering @cosu419 if you'd like to handle that as part of this ticket, or a separate ticket that focuses on the error state? We've done both in the past, so defer to you on which approach you prefer!

<img width="341" alt="Image" src="https://github.com/user-attachments/assets/b1e7fe57-1d13-455b-b80d-e0f8ac446825" />

**Comment by cosu419** [comment]
@oddball-lindsay this ticket works thanks!

**Comment by oddball-lindsay** [comment]
Sounds good, I added that to the issue description up above! Feel free to bump up the estimate if you feel like this add merits it @cosu419.

**Comment by oddball-lindsay** [comment]
Reconfiguring the logic for the submission method page, after a team discussion:

![Image](https://github.com/user-attachments/assets/a1be4639-8d65-4b0d-9ea3-df19852ff911)

**Comment by oddball-lindsay** [comment]
@mtri ready for you! I'm pretty sure all representatives have all submission methods available right now, so you should see this page for any rep w multiple organizations. 

Functionality I'm hoping you can check:
- Error state is triggering okay
- User should re-select a submission method if they select a new rep

If you do have any QA findings, can you please create a new ticket for our backlog?

**Comment by cosu419** [comment]
@mtri @oddball-lindsay it looks like this hasn't actually deployed yet

https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard

**Comment by mtri** [comment]
[Figma screen](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=13090-378835&t=YOAQy5Nvms7HSnCr-11)
- Missing an h3 above the question. Should be “Select how to submit your request”
- Question copy was recently tweaked when we had the error copy written. “Select how to submit your request” should be “How do you want to submit your request?”
- Missing Note copy below question: “**Note:** If you want to submit your request by mail or in person, you’ll need to print your form at the end of our online tool. We’ll provide instructions on how to submit it.”

Other than these copy changes, functionality is working as expected!

**Comment by oddball-lindsay** [comment]
Thanks for doing that check @mtri ! I moved these findings to a new ticket which we can pick up next sprint: https://github.com/department-of-veterans-affairs/va.gov-team/issues/101586
