### ISSUE TITLE
[FSR] - Replace/Remove WIZARD_STATUS_COMPLETE Variable Causing Cross App Import Error

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#99783]
## Issue Description
Follow up to Discovery - Investigate Cross App Imports to Ensure Compliance (DUE 2/3/2025) #96879
https://github.com/department-of-veterans-affairs/va.gov-team/issues/96879

Replace/remove const causing warning.

## Tasks
- [ ] Replace/remove const causing warning
- [ ] Update/remove relevant tests

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Replace/remove const causing warning
- [ ] All tests passing

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
