### ISSUE TITLE
Design User Flow and Static Screens for PCPG Eligibility Wizard

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/va.gov-team#9979]
## User Story
As a Veteran looking for Career assistance, I want to check and see if I am eligible for the PCPG program before applying so I know that I will be accepted and get the help and benefits I need.

## Goal
Establish the flow of where this eligibility wizard lives given the considerations below, create a flow chart t o ensure shared understanding of the logic, and create static screens that will inform others what the wizard will look like.

## Considerations
- Eligibility wizard should take the format of the "Can I file my claim online?" wizard at https://www.va.gov/disability/eligibility/ per this Epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9665
  - Establish the location of where this should live
- VRE and the TED office suggest these eligibility questions:

> **1) Are you a Veteran, Service member, or Dependent?**  
> 
> **YES:** _(Go to question 2)_
> **NO:** In order to use Personalized Career Planning & Guidance (PCPG), you must be a Veteran, Service member, or Dependent of a Veteran or Service member. `(Suggest that this links the person to general info page on PCPG: https://www.va.gov/careers-employment/education-and-career-counseling/)`
> 
> **2) Do you have a service-connected disability rating, a memo rating, or are you going through  the Integrated Disability Evaluation System (IDES) process?**
> 
> **YES:** You may be eligible for Chapter 31, Veteran Readiness & Employment (VR&E) benefits. Please start your application here: https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/
> **NO:** _(Go to question 3)_
> 
> **3) Are you currently receiving Chapter 31, Veteran Readiness & Employment (VR&E) benefits?**
> 
> **YES:** Please reach out to your Vocational Rehabilitation Counselor.  VR&E office contact information can be found here:  https://www.benefits.va.gov/benefits/offices.asp
> **NO:** _(Go to question 4)_
> 
> **4) Are you currently using VA education benefits or eligible to use VA education benefits to attend school?**
> 
> **ES:** _(Go to question 6)_
> **NO:** _(Go to question 5)_
> 
> **5) Have you been discharged from active duty within the last year or are you a Service member with 6 months or less until discharge?**
> 
> **YES:** _(Go to Question 6)_
> **NO:** In order to use Personalized Career Planning & Guidance (PCPG), you must be a Veteran, Service member, or Dependent of a Veteran or Service member. `(Suggest that this links the person to general info page on PCPG: https://www.va.gov/careers-employment/education-and-career-counseling/)`
> 
> **6) Are you interested in educational and/or career guidance?**
> 
> **YES:** `(Button labeled Start Your Application)`
> **NO:**  You can start this application whenever you are ready. For more information about VA's programs, please visit https://www.va.gov/education/

## Tasks
- [x] Create or edit an existing thumbnail view of the PCPG workflow
- [x] Create a flow chart of the eligibility wizard itself per the suggestions above
- [x] Create a static screens of the wizard

## Acceptance Criteria
- [x] The user flow, flow chart and static screens have been created and shared with the team for feedback.

**Comment by sporeboy** [comment]
Initial take on flowchart and questions for CH36/PCPG are here: https://xd.adobe.com/view/879cf230-f3ce-4204-79ba-c3453b0bcc09-f1ad/

This wizard widget/component will live on the 28-8832 intro screen. Once user satisfies logic, typical subway map configuration appears. User can bypass widget via direct link. Cookies required to hide widget.

**Comment by sporeboy** [comment]
Low-fi wireframe flow added... https://xd.adobe.com/view/879cf230-f3ce-4204-79ba-c3453b0bcc09-f1ad/screen/28f5d3f7-c2c1-49c0-bfa1-3791dba4dd7e/CH31-CH36-Wizard-Screen-Flow-1

**Comment by sporeboy** [comment]
Basic static screens are built: https://xd.adobe.com/view/17b9e3b9-abb2-4c17-6619-adcc54353687-6188/
