### ISSUE TITLE
Digital submission email confirmation in VA Notify Staging

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#99803]
## Background
In [#99802](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99802), users who intend to request POA digitally will have a new "Submit form" CTA on the `review-and-submit` page.

Clicking "Submit form" will create the POA request (https://github.com/department-of-veterans-affairs/va.gov-team/issues/99974) and after that request is successfully created:
1. The user will be routed to the `confirmation` page
2. If the user entered an email address for themself (Veteran users only for v2), the user will receive an email notification reiterating the next steps.

This email notification currently exists in VA Notify Staging with the name "Appoint a Representative v2 - Digital Submit Confirm".

## Tasks
- [ ] After a POA request is successfully created, engage VA Notify for the "Appoint a Representative v2 - Digital Submit Confirm" email.
- [ ] Work with @oddball-lindsay to adjust variables in the email template, as needed.
- [ ] Confirm everything is working as expected in VA Notify Staging.

## Acceptance Criteria
- [ ] The Appoint v2 experience is setup to send an email notification to any users who request POA digitally.
- [ ] The VA Notify template is rendering as expected, including variable content and is ready to be promoted to Production.

**Comment by holdenhinkle** [comment]
Will include this in the request endpoint. Blocked until Jon is done building that.

**Comment by opticbob** [comment]
Now that the submission endpoint is done I can continue working on the data model for the email and can put the code that calls it in that new endpoint.  That calling code will probably be moved elsewhere eventually.

**Comment by opticbob** [comment]
The data object that takes the PDF/digital form submission and extracts the info used in the email template is done.  I need to write some tests for it and it'll be ready to go.

**Comment by opticbob** [comment]
This is in team review.

**Comment by oddball-lindsay** [comment]
@opticbob confirming I've removed the times from the email template: 

![Image](https://github.com/user-attachments/assets/40b476ed-baca-4a68-9402-5745515ee315)

**Comment by opticbob** [comment]
This is still in team review.

**Comment by opticbob** [comment]
This is still in team review.  Platform has reminded me that they can't review it until it's been team reviewed.

**Comment by opticbob** [comment]
The PR for this is team and Platform reviewed and ready to merge.  I haven't merged it yet because I can't figure out how to add the staging template id to the vsp-infra-application-manifests repo.  The staging file I added to last time no longer contains those values and I can't find it in the repo.  I confirmed that the email is still sending just fine from staging.

I've asked the VA Notify team for assistance, details on [slack.](https://dsva.slack.com/archives/C010R6AUPHT/p1739400441520529)

**Comment by opticbob** [comment]
The code for sending the email is done, I haven't added the template id to the manifests repo where that value can be used from within `vets-api`.  The PR to do that is waiting on feedback from Platform.

**Comment by opticbob** [comment]
Platform has responded, I've updated the PR and that is back in front of them to review.
