### ISSUE TITLE
Review page: Error state if creating a digital POA Request fails

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#99804]
## Background
On our `review-and-submit` page, we have an error state if the PDF generation fails.

With Appoint v2, we are introducing a new "Submit" CTA for this page. If the submission (i.e. creating a digital POA Request) fails, we will need to display a unique error message related to this failure and encourage the user to try again.

## Tasks
- [ ] Create a new error state for the `review-and-submit` page, when creating a digital POA request fails
- [ ] Partner with CAIA or Jen S for updated content
- [ ] Share with the team for feedback
- [ ] Update the error state design with any team feedback

## Acceptance Criteria
- [ ] There is a design for an error state on the `review-and-submit` page, when a digital POA request fails to get created.

**Comment by oddball-lindsay** [comment]
Moving this to Icebox, since we uncovered in MVP that a custom error message is not easy to implement. The issue is to identify how we might customize the error message for PDF generation, after which we can take the same approach for when digital submission fails.

**Comment by oddball-lindsay** [comment]
Why would the POA request fail? 
- technical issues: network request timed out, issue connecting to the database where the transaction fails (low occurrence, likely short-lived)
- form in progress, but the rep/org loses the accreditation in that time period and can no longer be appointed

**Comment by mtri** [comment]
[Final error states in Figma](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=14819-386447&t=b38m9ihY7VwQao0W-11)
