### ISSUE TITLE
Review: Change "Continue" button functionality based on submission method

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#99802]
## Background
On the Review page, we will need to update ~the CTA~ how the "Continue" button functions, based on the user's selected submission method in `representative-submission-method` https://github.com/department-of-veterans-affairs/va.gov-team/issues/99788.
1. For users ending in digital submission, the "Continue" button should trigger an API request to create a digital POA request (the actual request will be handled in #99974)
2. For users ending in the PDF download/print, the "Continue" button should generate a pre-filled 21-22 or 21-22a PDF

_We won't be using the following designs with a new "Submit form" button content, because the Forms Library does not have a straightforward way to implement dynamic content._
~[Mobile design](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=10172-399758&t=MOtErVd4fYEQlr9H-4)~
~[Desktop design](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4521-225964&t=uKLMu3L7kKVJ5SWH-4)~
~[Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=11274-585382&t=uKLMu3L7kKVJ5SWH-4)~

## Tasks
- [ ] ~Update CTA, based on conditions~
- [x] Introduce conditional functionality to the "Continue" button, to trigger an API request to create a digital POA request (the actual request will be handled in #99974) for digital submission users
- [x] Unit tests

## Acceptance Criteria
- [ ] As a Veteran user with ICN+PID (eligible for digital submission), when I select a representative that accepts digital submission AND choose "online" for my submission method, the ~Review page should have a "Submit" CTA~ "Continue" button should trigger an API request to create a digital POA request.

**Comment by oddball-lindsay** [comment]
@cosu419 FYI - realized I was missing some Figma links, added in links for the desktop design + annotations up top!

**Comment by cosu419** [comment]
I've been experimenting with different approaches and it seems like this can't be done without re-building the review page as a custom screen, which could be a level 5 or 8 ticket. 

The `submitButtonText` is built into the form config and not really intended to be dynamic. I attempted to work around this the same way that we update the `subTitle` based on form type (which is already a hacky approach not supported by the forms library). But that workaround doesn't seem to be effective here.

**Comment by oddball-lindsay** [comment]
@cosu419 thanks for checking in, this is really helpful to know!

What's the default non-dynamic `submitButtonText`? Is it the "Continue" that we have on the MVP Review page?

And let's say we take the path of least resistance and do not customize the CTA based on submission method (i.e. same content for all methods)... could we still have a dynamic approach for what that CTA button does (generate a PDF vs. create a digital POA request), or do you think that will also be a challenge with the forms library?

**Comment by cosu419** [comment]
@oddball-lindsay Yes, "Continue" is the default. We can change that, but not within the form flow. 

Conditionally setting the functionality of the button is not an issue.

**Comment by oddball-lindsay** [comment]
Thanks @cosu419 let's keep "Continue" for now then since it's the default and simply pursue the functionality of the button for now. I don't think the content change is worth the additional scope, given our tight turnaround to pilot launch. I'm going to update the ticket description to focus more on functionality.

cc @mtri for a heads up on the lack of ease to change the CTA content for the v2 Review page. Let us know if there are any design concerns with this pivot!

**Comment by cosu419** [comment]
As far as the conditional functionality, I think this ticket is blocked pending the endpoint:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/99974

I can add some placeholder logic, but we would most likely need to re-open the ticket once the endpoint is created. I think it makes sense to hold off on that for now.

**Comment by oddball-lindsay** [comment]
Agree that it makes sense, placing this in Blocked for now.

**Comment by oddball-lindsay** [comment]
@cosu419 and @holdenhinkle chatted about this ticket encompassing two pieces when the "Continue" button is clicked, and the submission method is digital submission:
1. Engage the PDF generation endpoint
2. Engage the POA request endpoint

These ^ need to be done in this sequence.
