### ISSUE TITLE
[Frontend] MDT - Incorporate content feedback from staging reviews

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#9982]
## Issue Description
_The VSP's content lead [provided feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9720) during MDT's staging review. Some of the feedback is mandatory while some is suggested to align with VA.gov's best practices. Additionally, BaM2's design team provided content feedback during internal staging reviews to be incorporated._

---
## Tasks
- [x] _BaM2 designer provides feedback that was discussed during internal staging review_
- [ ] _Content feedback is incorporated_
- [ ] _Once content is updated, comment on [VSP's feedback ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9720) so Peggy can check the tool_

## Acceptance Criteria
- [x] _BaM2 designer has provided content feedback_
- [ ] _Content updates are incorporated_
- [ ] _Peggy is notified of the content updates in [the original feedback ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9720)_

**Comment by rileyorr** [comment]
@mr0sari0 

Please see the content feedback from our internal staging review. Let me know if you have any questions! 

**Intro screen**

- When a veteran is returning to an order that’s in progress, the primary and secondary buttons should say ‘order’ instead of ‘application’ 

**Shipping address screen (C1P2)**

- Email address content: ‘We will’ should say ‘We’ll’ 

**Review screen**

- Change ‘Review application’ to ‘Review order details’ since it’s not an application

**Comment by mr0sari0** [comment]
PR for this is [here](https://github.com/department-of-veterans-affairs/vets-website/pull/13016).  

Still implementing feedback.

**Comment by mr0sari0** [comment]
PR for non form system changes is [here](https://github.com/department-of-veterans-affairs/vets-website/pull/13166)

**Comment by mr0sari0** [comment]
PR for non-form system changes is merged.

**Comment by mr0sari0** [comment]
The PR for the form system changes has now been merged.

**Comment by mr0sari0** [comment]
Also I raised the estimate on this ticket due to the effort required to get this PR merged.

**Comment by mr0sari0** [comment]
@rileyorr Can we meet up to figure out what's left to update on this ticket?

**Comment by mr0sari0** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11056 is needed to complete the content edits.

**Comment by mr0sari0** [comment]
Please see the comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10462#issuecomment-656284836).

**Comment by leahkeeler** [comment]
@mr0sari0 Is there work to be done on this? does it need to be in current sprint?

**Comment by mr0sari0** [comment]
@leahkeeler The last piece of this is to change the form ID to change from "MDOT" to "Form 2346A". It has to be done on the backend and the front end. See:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/11056

**Comment by leahkeeler** [comment]
@camerontesterman - can you please confirm that this is done?

**Comment by mr0sari0** [comment]
@leahkeeler  Based on Peggy's comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10462#issuecomment-657873083), I think we can leave this alone.
