### ISSUE TITLE
Staging Review [Facility Locator]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9984]
**This review was suggested by Jennifer Strickland to review existing functionality in preparation for Full 508 Accessibility Review and to assess design.**

## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [ ] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

### Features/enhancements
- Community care pharmacies (in VA's network) is hidden as a facility type for searching but has been feature flagged to return at the end of the month [#9177](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9177)
- Update to display of hours [#3541](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3541)
- Addition of chatbot link in intro text (this work was done by separate team)
- Addition of pins which correlate facility locations on the map to those within the search results list. [#5620](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5620)
- Sighted veterans can view a pin marking their geographic location as specified in the search parameters so they know their location relevant to search results. [#5501](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5501)
### Resolution of accessibility issues
- Search results lists are presented as ordered list with contextual information for Veterans using screen reader devices. [#5555](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5555)
- Heading changes made to the "Important information about your Community Care appointment" alert to support understanding of page structure. [#7244](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7244)
- Veterans using screen readers are able to navigate away from the search results using a keyboard.
[#7288](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7288)
- Veteran should be able to traverse the options in the dropdown using keyboard only [#7291](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7291)
### Out of scope
- Addition of Facility operating status and notes  (had separate [staging review])(https://github.com/department-of-veterans-affairs/va.gov-team/issues/8099)

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_

- [x] [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/product/facility-locator-product-outline.md)
- [x] Link to release plan
   - I believe this is irrelevant as we are testing functionality currently in Prod but please let me know otherwise. 
- [x] Access information for the tool: https://www.va.gov/find-locations
   - Facility Locator is unauthenicated and does not need access credentials
   - **Testing should be conducted in Production**
- [x] Link to your product test cases/test plan in TestRail with test execution logs 
   - [Core Regression Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/149) (see FL - Regression - Test Run 6/23/2020)
      - [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/112) (no defects logged)
   - [Facility Locator Staging Review June 2020](https://dsvavsp.testrail.io/index.php?/plans/view/464)
        - [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/118)
        - [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/119)

**Required accessibility tests**
- [x] Scan with axe browser plugin
- [ ] Create end-to-end tests for React apps (ignore if not applicable)
- [x] Color comparisons
- [ ] Zoom layouts
- [x] Keyboard navigation
- [ ] Screen reader

**Recommended tests**
- [x] Scan with axe-coconut
- [x] Visually scan with WAVE

**Experimental tests**
- [ ] Create keyboard end-to-end tests

## List of known issues
- Short list of health services should not have accordion [#10094](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10094)
- Results summary subhead has been suppressed [#6775](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6775)
- Vet Center "service type" should not be interactive [#5967](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5967)
- Map is cut off rather than scrolling horizontally. [#6184](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6184)
- Phone numbers on the Facility Detail page need to be linked and many are displayed twice: once as link for auto-dialer and one as routine display for "Main phone number". [#8063](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8063)
- Some cemetery searches may not yield results due to GeoBISL data freshness. This will be resolved by migration to v1. [#9662](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9662)
- Mapbox functionality has a number of accessibility defects related to leaflet limitations which will be explored in [#8535](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8535)
   - [#515](https://github.com/department-of-veterans-affairs/va.gov-team/issues/515)
   - [#6104](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6104)
   - [#6897](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6897)
   - [#6158](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6158)
   - [#6103](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6103)
   - [#6892](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6892)

## Meeting attendees from **requesting team**
- Product Manager (required): **Michelle Middaugh**
- DEPO product lead (required): **Dave Conlon**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Gibran Rodriguez, Lance Sanchez, Aricka Lewis, Leyda Hughes**
_(Please consider Aricka Lewis as optional as she has transitioned away from our team. Leyda is our new Designer but has not previously been involved in the application)_

## Scheduling
- Wednesday, June 18 at 1:30 ET

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by meganhkelley** [comment]
Per discussion with VSP reviewers, we are going to do this review asynchronously. Reviewers will have feedback documented within ~2 business days after you are able to provide the list of changes that have been made without review @mmiddaugh 

If we begin review and find that anything warrants deep discussion in a meeting format, we will reschedule a meeting accordingly.

**Comment by jenstrickland** [comment]
In order to do this review, the team needs a list of changes to review.

**Comment by pjhill** [comment]
A few things need to be addressed before I can provide a QA review --

1. It looks like you have a great suite of regression tests, but it looks like the [test run has yet to be executed](https://dsvavsp.testrail.io/index.php?/runs/view/466&group_by=cases:section_id&group_order=asc&group_id=36).
1. Are there any test cases / test plans / test runs that verify the fixes for the known issues that you've listed in this ticket?
1. Are there any test cases / test plans / test runs that verify the new features and enhancements you've listed in this ticket?

**Comment by peggygannon** [comment]
@mmiddaugh Hello, below is content feedback (v. minor)

The headings and labels are inconsistently styled (some sentence-cased, some are title-cased). We should follow our VA.gov styleguide of sentence-casing all labels, headings, subhead. 

This isn't a launch blocker, but something that should be updated at some point. 

Some examples that need to be sentence-cased:
Main number
Mental health
Hours of operation
View on map
Postal code

**Comment by mmiddaugh** [comment]
Thank you @peggygannon 

I recently made an [#10289](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10289) for "Postal code" but appreciate you bringing the others to our attention. I'll add them to that issue as well. 

Based on my reading of the style guide, it seems we need to change `Search by city, state or postal Code` to `Search by City, State or Postal code`. Is that true?

**Comment by tlei123** [comment]
> * It looks like you have a great suite of regression tests, but it looks like the [test run has yet to be executed](https://dsvavsp.testrail.io/index.php?/runs/view/466&group_by=cases:section_id&group_order=asc&group_id=36).

@leahkeeler @pjhill , I just finished Regression test-runs, and QA-artifact links have been updated/added in ticket description above.

NOTE: I marked a couple test-cases **Retest** due to some unexpected behavior, but haven't logged any defects for them as I'm not sure if any are warranted:
- City, State Search
- ZIP Code Search

The unexpected behaviors might well stem from certain test-case steps becoming out-of-date.  You can review the Actual Results for these cases.  The Steps marked Retest will have a yellow icons,

After you've review the test-run results for these case in TestRail, it may be prudent to follow-up with a quick Slack chat or Zoom meeting so that we can decide how to address those unexpected behaviors.

Feel free to ping me on Slack if you have any interim questions/comments.

Thanks much!

**Comment by tlei123** [comment]
@mmiddaugh @pjhill , "Staging Review" test-runs now also completed, see reports linked both below and in main Description above:

- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/118)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/117)
