### ISSUE TITLE
Staging Review: Estimate your benefits updates in the Comparison Tool

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9989]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
1. [Product Outline: Estimate Your Benefits](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/estimate-your-benefits/product-outline.md)
2. [Release Plan - Estimate Your Benefits](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/estimate-your-benefits/release-plan.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
3. Access information for the tool or feature in staging
   1. Navigate to the [Comparison Tool on staging](https://staging.va.gov/gi-bill-comparison-tool)
   2. Search for a Schools or VET TEC institutions 
   3. Select a school or institution
   4. On the school or institution "profile page" the first accordion is "Estimate your benefits"
4. [Product test cases/test plan in TestRail with test execution logs](https://dsvavsp.testrail.io/index.php?/runs/view/339&group_by=cases:section_id&group_order=asc)
5. [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/106)
    [Summary Defects](https://dsvavsp.testrail.io/index.php?/reports/view/105)
6. Link to accessibility test cases:
   - https://dsvavsp.testrail.io/index.php?/cases/view/671&group_by=cases:section_id&group_order=asc&group_id=46
   - https://dsvavsp.testrail.io/index.php?/cases/view/672&group_by=cases:section_id&group_order=asc&group_id=46
   - https://dsvavsp.testrail.io/index.php?/cases/view/670&group_by=cases:section_id&group_order=asc&group_id=46

7. List of known issues (with links to tickets when applicable)
   - [SCREENREADER]: GIBCT EYB - Focus MUST be set on the first added item when Show Next 10 button is pressed #9953
   - [KEYBOARD]: EYB - Focus MUST be returned to the trigger when modals are closed in IE11 #9241

## Meeting attendees from **requesting team**
- Product Manager (required): Darrell Neel @dneel-bah 
- DEPO product lead (required): Matt Self @mattpointzxer0 
- Anyone else from your team who significantly contributed to the artifacts provided (required): 
   - Amy Knox @amyknox 
   - Cindy Cruz @ccruzgra 
   - Jen Jones @JenLJ 
   - Will McCormack @WillMcCormack 
   - Dan Shawkey @shawkey-daniel 
   - Michael Delli-Gatti @delli-gatti-michael 
   - Adam Sonntag @sonntag-adam 
   - Desiree Turner @desireeturner 

## Scheduling
Preferred time block is 2-2:30PM on Friday 6/12/20

[VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by peggygannon** [comment]
Hello, @amyknox and @desireeturner I am providing my content review asynchronously here below. Two things I noticed: 

1. some of the tuition figures show TBD.. will these get populated? Two example are below: 

https://staging.va.gov/gi-bill-comparison-tool/profile/2V000105/HACK%20REACTOR%20SOFTWARE%20ENGINEERING 

https://staging.va.gov/gi-bill-comparison-tool/profile/3V000242/CISCO%20SYSTEMS%20-%20CCNP%20WIRELESS  

2. Also, not related to Estimate your benefits, but I noticed that under the Application process accordion TTY is TYY. Can you do a global fix/replace to correct this and make it TTY?

**Comment by pjhill** [comment]
I may not be able to attend the staging review this afternoon. I've linked my [QA review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10161) to the epic ahead of the meeting for your perusal. I don't have any feedback that requires a synchronous discussion.

**Comment by amyknox** [comment]
@peggygannon - thanks for the input on content. 

1. The tuition figures that are noted as TBD are data points that the provider hasn't provided.  In some instances, you'll see that a provider has tuition from some programs and not others. We'd like to have that info - and more - but it depends on what data the provider sends through. 

2. Great catch on TYY! I'll see what we can do to get that update going.

**Comment by desireeturner** [comment]
CT: Update TYY to be TTY in Application Process section #10169 entered to address @peggygannon's comment #2 above. Also linked to this issue.
