### ISSUE TITLE
Analytics Onboarding Meetings

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#999]
## User Story
As a new VFS team, I need to know what VSP Analytics and Insights does so I can use effectively use them for .

## Goal
Meet with new va.gov teams for onboarding onto VSP Analytics and Insights.

## Acceptance Criteria
- [ ] Onboarding meetings for the following teams:
    - [x] VSA Global UX
    - [x] VSA Authenticated Experience
    - [x] VSA Disability Benefits, Appeals
    - [x] VSA eBenefits
    - [ ] VSA Shared Support
    - [x] VSA Facility Locator
    - [x] By Light
    - [x] VAOS
    - [ ] VA Startup - VIEWS
    - [ ] VA Startup - CARMA
    - [ ] VA Starup - Get Care
    - [ ] VA MCT HCD

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
Epic now redundant, as work will live on the shared onboarding super epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1451
