### ISSUE TITLE
[Research] Community Care search result cards

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9993]
## Issue Description
**How might we display relevant information about community providers (in VA's network) on search results card?**
- Due to data issues, we may need to suppress facility detail cards for community providers. Some information which is displayed on those detail pages may be needed by Veterans searching on Facility Locator. 
- It is unknown if the details displayed on community care detail pages are relevant and/or meaningful to Veterans. 

## Current behavior
The following information may be available only on Facility detail pages for community care providers (not on search result cards):

- Email address
- Provider Gender
- Service definition
- Whether or not provider is accepting new patients
- Community Care Network 
- Preferred communication method
- Provider (NPI/Tax) ID

---
## Tasks
- [ ] Create a research plan to determine which information is important to Veterans and how best to display it
- [ ] Create an accompanying conversation guide

## Acceptance Criteria
- [ ] Approved research plan and conversation guide
- [ ] Prototype, prompt or tool as needed for sessions
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
@thejordanwood does your design cover everything here? Can this be closed? Anything worth saving?
