### ISSUE TITLE
[Discovery] VBA Facility Names

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9994]
## Issue Description
VBA facility names are not consistent and not in veteran-facing language. We need to create naming conventions for the various types of benefit offices/places were benefit services are offered. 

Benefit offices have multiple "classifications"

- Voc Rehab And Employment
- Outbased
- Vetsuccess On Campus

But even within a single classification, the naming logic is not consistent and may not be understood by Veterans. 

**Voc Rehab And Employment** locations have names such as

- Fort Huachuca Vocational Rehabilitation and Employment Office
- Tampa Polytrauma VR&E Office 
- Austin-2 VR&E Office (within VAOPC)

"Outbased" locations may be located at/within Vet Centers and VA medical facilities, such as 

- Waco Regional Benefits Satellite Office at Temple VA Medical Center
- VBA Pecos Veterans Assistance Office
- Scottsburg Out Based Office
- Chicago Regional Office - Lovell Federal Health Care Center Outbased Office
- Webster University
- National Guard Armory

---
## Tasks
- [ ] Research existing names and current logic
- [ ] Determine a method for validating naming logic with Veterans looking for plain language and meaning

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This work is underway
