### ISSUE TITLE
PPMS Taxonomy Mapping

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9995]
## Product Outline
[Link to be added](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## Context

The data source for Community care providers is PPMS.
- PPMS currently uses NUCC codes for provider services and categories. There are ~863 canonical codes that map to granular clinical terms. 

VHA health services taxonomy is a structure of words, associated conditions, and descriptions for a standard vocabulary with a preference for Veteran-facing plain language.
- It is a living, evolving taxonomy that is currently in an MVP state. 
- Will be growing beyond just VHA to incorporate services at Vet Centers, benefits offices and cemeteries
- VHA services are mapped to facilities
- Uses 1:1 service - category

## Goals
Veterans can search for Community care providers in the Facility Locator using Veteran-facing plain language.
 Taxonomy can be used broadly (ie: for scheduling)

## Solution (overview of approach)

Map PPMS taxonomy to VHA health services, beginning with VAOS top 5
- Optometry
- Audiology
- Podiatry
- Emergency care
- Food/nutrition

Questions to answer:

For a given search, which NUCC codes should be included?
What taxons are missing?

## Tasks

- [x] Identify resources and availability
- [x] Engage VHA and OCC 
- [x] Identify which services will be implemented first in VAOS #11207 
- [x] Conduct research interviews with Community care schedulers to learn how they query and in which system #13583

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [ ] **Convert to an Epic**  
- [ ] **Labeled with Team**  
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
@mmiddaugh @xiongjaneg Do we still need this old epic from the old facilities team repo. Or is the PPMS work on Facilities Locator better captured in other newer tickets?

**Comment by jilladams** [comment]
Effort is now tracked under https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15541
